port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: ğŸ‡²ğŸ‡½MX_39 |21.67Mb
  server: 147.78.1.230
  type: ss
  country: ğŸ‡²ğŸ‡½MX
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡¹GT_34 |38.06Mb
  server: 185.47.254.87
  type: ss
  country: ğŸ‡¬ğŸ‡¹GT
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_46 |52.48Mb
  server: 3.22.249.200
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡ºğŸ‡¸US_48 |33.39Mb
  server: 173.234.29.2
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_47 |52.46Mb
  server: 3.149.246.131
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡ºğŸ‡¸US_49 |10.79Mb
  server: 18.220.216.187
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡ºğŸ‡¸US_50 |50.06Mb
  server: 18.224.33.22
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡µğŸ‡¦PA_40 |13.98Mb
  server: 138.186.142.81
  type: ss
  country: ğŸ‡µğŸ‡¦PA
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: disney_MX |13.73Mb
  server: 38.165.231.25
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _17 |10.50Mb
  server: 185.163.204.94
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡µğŸ‡¹PT_42 |41.90Mb
  server: 185.113.143.186
  type: ss
  country: ğŸ‡µğŸ‡¹PT
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: Relay_-ğŸ‡©ğŸ‡ªDE_09 |10.15Mb
  server: 193.135.174.135
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¯ğŸ‡µJP_35 |15.30Mb
  server: 194.68.27.76
  type: ss
  country: ğŸ‡¯ğŸ‡µJP
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _13 |31.20Mb
  server: 185.93.173.60
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¦ğŸ‡ºAU_26 |33.36Mb
  server: 103.75.119.38
  type: ss
  country: ğŸ‡¦ğŸ‡ºAU
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - ğŸ‡²ğŸ‡½MX_39 |21.67Mb
  - ğŸ‡¬ğŸ‡¹GT_34 |38.06Mb
  - ğŸ‡ºğŸ‡¸US_46 |52.48Mb
  - ğŸ‡ºğŸ‡¸US_48 |33.39Mb
  - ğŸ‡ºğŸ‡¸US_47 |52.46Mb
  - ğŸ‡ºğŸ‡¸US_49 |10.79Mb
  - ğŸ‡ºğŸ‡¸US_50 |50.06Mb
  - ğŸ‡µğŸ‡¦PA_40 |13.98Mb
  - disney_MX |13.73Mb
  - _17 |10.50Mb
  - ğŸ‡µğŸ‡¹PT_42 |41.90Mb
  - Relay_-ğŸ‡©ğŸ‡ªDE_09 |10.15Mb
  - ğŸ‡¯ğŸ‡µJP_35 |15.30Mb
  - _13 |31.20Mb
  - ğŸ‡¦ğŸ‡ºAU_26 |33.36Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - ğŸ‡²ğŸ‡½MX_39 |21.67Mb
  - ğŸ‡¬ğŸ‡¹GT_34 |38.06Mb
  - ğŸ‡ºğŸ‡¸US_46 |52.48Mb
  - ğŸ‡ºğŸ‡¸US_48 |33.39Mb
  - ğŸ‡ºğŸ‡¸US_47 |52.46Mb
  - ğŸ‡ºğŸ‡¸US_49 |10.79Mb
  - ğŸ‡ºğŸ‡¸US_50 |50.06Mb
  - ğŸ‡µğŸ‡¦PA_40 |13.98Mb
  - disney_MX |13.73Mb
  - _17 |10.50Mb
  - ğŸ‡µğŸ‡¹PT_42 |41.90Mb
  - Relay_-ğŸ‡©ğŸ‡ªDE_09 |10.15Mb
  - ğŸ‡¯ğŸ‡µJP_35 |15.30Mb
  - _13 |31.20Mb
  - ğŸ‡¦ğŸ‡ºAU_26 |33.36Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
