port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: _132 |53.15Mb
  server: 167.160.90.178
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _178 |10.51Mb
  server: 138.186.142.81
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _150 |10.25Mb
  server: 62.100.205.100
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _133 |10.24Mb
  server: 206.206.125.53
  type: ss
  port: 20199
  udp: true
  password: W4ULRoPY8DvUhnbfKnjSWD
  cipher: chacha20-ietf-poly1305
- name: _176 |10.26Mb
  server: 38.165.231.25
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸ‡¨ğŸ‡¦CA-ğŸ‡¨ğŸ‡¦CA_207 |10.48Mb
  server: 79.127.200.169
  type: ss
  country: ğŸ‡¨ğŸ‡¦CA
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¨ğŸ‡¦CA_208 |10.56Mb
  server: 138.197.141.58
  type: ss
  country: ğŸ‡¨ğŸ‡¦CA
  port: 8080
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: ğŸ‡¨ğŸ‡¦CA_210 |13.87Mb
  server: 178.128.231.214
  type: ss
  country: ğŸ‡¨ğŸ‡¦CA
  port: 8080
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: ğŸ‡¨ğŸ‡¦CA_211 |29.17Mb
  server: 68.183.193.204
  type: ss
  country: ğŸ‡¨ğŸ‡¦CA
  port: 8080
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: ğŸ‡¨ğŸ‡¦CA_212 |10.55Mb
  server: 147.182.150.107
  type: ss
  country: ğŸ‡¨ğŸ‡¦CA
  port: 8080
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: disney_US |10.31Mb
  server: 79.127.200.162
  type: ss
  country: ğŸ‡¨ğŸ‡¦CA
  port: 990
  password: f8f7aCzcPKbsF8p3
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡§ğŸ‡ªBE_198 |200.57Mb
  server: 192.71.249.108
  type: ss
  country: ğŸ‡§ğŸ‡ªBE
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ğŸ‡¦ğŸ‡·AR_186 |44.93Mb
  server: 38.54.45.129
  type: ss
  country: ğŸ‡¦ğŸ‡·AR
  port: 990
  password: f8f7aCzcPKbsF8p3
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¨ğŸ‡¦CA_215 |10.90Mb
  server: 147.182.146.81
  type: ss
  country: ğŸ‡¨ğŸ‡¦CA
  port: 8080
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: ğŸ‡¨ğŸ‡¦CA_216 |10.59Mb
  server: 137.184.174.93
  type: ss
  country: ğŸ‡¨ğŸ‡¦CA
  port: 8080
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: ğŸ‡¨ğŸ‡¦CA_218 |10.09Mb
  server: 148.113.176.192
  type: vmess
  country: ğŸ‡¨ğŸ‡¦CA
  port: 443
  uuid: 03fcc618-b93d-6796-6aed-8a38c975d581
  alterId: 0
  cipher: auto
  network: ws
  servername: fapeng.org
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: linkvws
    headers:
      HOST: fapeng.org
- name: ğŸ‡¨ğŸ‡¦CA_219 |10.48Mb
  server: 51.79.102.253
  type: vmess
  country: ğŸ‡¨ğŸ‡¦CA
  port: 80
  uuid: 58fe1542-5290-40ad-815a-77707a81afe5
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
  ws-opts:
    path: /IOebhLMhl1CTbFHbL95myfRX2
- name: ğŸ‡¦ğŸ‡ºAU_194 |10.30Mb
  server: 45.77.234.206
  type: ss
  country: ğŸ‡¦ğŸ‡ºAU
  port: 8080
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: ğŸ‡§ğŸ‡ªBE_201 |48.25Mb
  server: 192.71.249.108
  type: ss
  country: ğŸ‡§ğŸ‡ªBE
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡§ğŸ‡ªBE_199 |188.98Mb
  server: 192.71.249.78
  type: ss
  country: ğŸ‡§ğŸ‡ªBE
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: _145 |10.11Mb
  server: 45.82.252.109
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _184 |10.01Mb
  server: 58.152.110.40
  type: trojan
  port: 443
  password: ea39fa94f1ee00999337ea1fd3318e69
  sni: www.nintendogames.net
  network: tcp
- name: ğŸ‡¦ğŸ‡ºAU_196 |167.14Mb
  server: 38.55.105.55
  type: vmess
  country: ğŸ‡¦ğŸ‡ºAU
  port: 5551
  uuid: 3977956a-5093-4f39-97eb-4826dc5105e5
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
  ws-opts:
    path: /arki?ed=2048
- name: Relay_ğŸ‡¨ğŸ‡¦CA-ğŸ‡¨ğŸ‡¦CA_217 |102.00Mb
  server: ssca.irundns.net
  type: ssr
  country: ğŸ‡¨ğŸ‡¦CA
  port: 443
  password: $$Turb0VPN$$
  cipher: aes-128-cfb
  protocol: auth_aes128_md5
  obfs: http_post
- name: ğŸ‡©ğŸ‡ªDE_235 |13.63Mb
  server: 93.186.201.64
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 57456
  password: c40641c1f89e7acb
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡©ğŸ‡ªDE_246 |16.09Mb
  server: 81.19.141.45
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 443
  password: rC23nT4eVDHF06wmuyvSUe
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡©ğŸ‡ªDE_250 |10.14Mb
  server: 3.79.95.181
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡©ğŸ‡ªDE_256 |10.09Mb
  server: 18.196.31.30
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡©ğŸ‡ªDE_258 |10.14Mb
  server: 18.195.116.149
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡©ğŸ‡ªDE_262 |10.20Mb
  server: 18.199.98.206
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡©ğŸ‡ªDE_263 |12.78Mb
  server: 81.19.141.45
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 443
  password: ZL5RbLM4etVp3vK1YQG6Ap
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡©ğŸ‡ªDE_268 |10.16Mb
  server: 3.79.189.65
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡©ğŸ‡ªDE_272 |10.08Mb
  server: 18.159.37.90
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: Relay_ğŸ‡¨ğŸ‡­CH-ğŸ‡¨ğŸ‡­CH_221 |10.05Mb
  server: h110vpnch.outlinekeys.net
  type: ss
  country: ğŸ‡¨ğŸ‡­CH
  port: 4248
  password: nweTvVPR1DapgM5c8CpE1q
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡©ğŸ‡ªDE_275 |10.22Mb
  server: 18.196.156.200
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡©ğŸ‡ªDE_278 |10.14Mb
  server: 3.66.163.109
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡¬ğŸ‡§GB_358 |10.08Mb
  server: 146.70.61.37
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: ğŸ‡¬ğŸ‡§GB_366 |10.26Mb
  server: 18.175.147.245
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡¬ğŸ‡§GB_373 |10.17Mb
  server: 18.134.245.70
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡«ğŸ‡®FI_330 |10.08Mb
  server: 37.143.129.230
  type: ss
  country: ğŸ‡«ğŸ‡®FI
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ğŸ‡ªğŸ‡¸ES_296 |14.43Mb
  server: 194.87.45.189
  type: ss
  country: ğŸ‡ªğŸ‡¸ES
  port: 443
  password: AnxMfj2oL2RaZTQVfVd5EY
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡«ğŸ‡·FR_344 |13.03Mb
  server: 83.147.216.70
  type: ss
  country: ğŸ‡«ğŸ‡·FR
  port: 64519
  password: PSmqa9uK9Oo1eivPyXiAH8
  cipher: chacha20-ietf-poly1305
- name: Pool_ğŸ‡¬ğŸ‡§GB_392 |10.31Mb
  server: 79.127.233.170
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 990
  password: f8f7aCzcPKbsF8p3
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_380 |34.37Mb
  server: 35.178.211.150
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡¬ğŸ‡¹GT_413 |15.81Mb
  server: 185.47.254.87
  type: ss
  country: ğŸ‡¬ğŸ‡¹GT
  port: 990
  password: f8f7aCzcPKbsF8p3
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_385 |47.10Mb
  server: 18.133.243.78
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡¬ğŸ‡§GB_390 |15.43Mb
  server: 3.9.171.152
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡¬ğŸ‡§GB_387 |15.25Mb
  server: 141.98.101.181
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: shadowsocks
  cipher: aes-128-gcm
- name: ğŸ‡­ğŸ‡°HK_417 |58.97Mb
  server: 154.223.16.212
  type: ss
  country: ğŸ‡­ğŸ‡°HK
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ğŸ‡®ğŸ‡ªIE_445 |10.22Mb
  server: 196.196.192.58
  type: ss
  country: ğŸ‡®ğŸ‡ªIE
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡­ğŸ‡°HK_422 |151.55Mb
  server: 8.217.124.8
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 14165
  uuid: 1f8daab3-34f9-4d01-914c-71c56c41c039
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
  ws-opts:
    path: /arki?ed=2048
- name: ğŸ‡­ğŸ‡°HK_424 |46.38Mb
  server: 47.238.78.223
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 37053
  uuid: 848e2c77-ef8c-429f-b3cb-c2a159ee03b0
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
  ws-opts:
    path: /arki?ed=2048
- name: ğŸ‡­ğŸ‡°HK_440 |46.00Mb
  server: 8.217.209.82
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 6874
  uuid: 1f8a9781-3088-4499-8909-283826d05457
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
  ws-opts:
    path: /arki?ed=2048
- name: ğŸ‡­ğŸ‡°HK_441 |66.06Mb
  server: 47.243.231.14
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 4624
  uuid: 2e015cb2-4377-476c-9ba3-f859ceb4c551
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
  ws-opts:
    path: /arki?ed=2048
- name: Relay_ğŸ‡¬ğŸ‡§GB-ğŸ‡¬ğŸ‡§GB_360 |28.95Mb
  server: media.mothyleela.cfd
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 40521
  password: 2WkRGh6tAv8UmsHh4i3F6zosj2dzA6sCzXbwq4TdXteztMfyA5aZcLy5jY5Z7FZ3QQMcTVwM7TvibdvzYircC7iDZafp2U6z
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸ‡¬ğŸ‡§GB-ğŸ‡¬ğŸ‡§GB_378 |123.36Mb
  server: media.mothyleela.cfd
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 40521
  password: Z94FoM1xpW3CJzixME8CjJEFBiCFhKSWfLzT6E92Pjh7y73YfNrwPju46Gd4HE85eXSjNiTtiAYc6WTskuhxZZFebd4rcXfp
  cipher: chacha20-ietf-poly1305
- name: Pool_ğŸ‡­ğŸ‡°HK_420 |425.00Mb
  server: 150.107.46.21
  type: ssr
  country: ğŸ‡­ğŸ‡°HK
  port: 8083
  password: iFqnzSscN
  cipher: aes-256-cfb
  protocol: origin
  obfs: tls1.2_ticket_auth
- name: Relay_ğŸ‡®ğŸ‡·IR-ğŸ‡³ğŸ‡±NL_456 |10.10Mb
  server: 151.242.251.152
  type: ss
  country: ğŸ‡®ğŸ‡·IR
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸ‡®ğŸ‡·IR-ğŸ‡³ğŸ‡±NL_469 |10.12Mb
  server: 151.242.251.147
  type: ss
  country: ğŸ‡®ğŸ‡·IR
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡­ğŸ‡°HK_438 |25.08Mb
  server: 103.243.25.213
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 7883
  uuid: a3688a34-88ce-4178-96ac-a5a0607d08be
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
  ws-opts:
    path: /arki?ed=2048
- name: ğŸ‡®ğŸ‡³IN_447 |114.10Mb
  server: 103.111.114.29
  type: ss
  country: ğŸ‡®ğŸ‡³IN
  port: 57456
  password: 360e21d21977dc11
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¯ğŸ‡µJP_481 |10.58Mb
  server: 202.182.98.223
  type: ss
  country: ğŸ‡¯ğŸ‡µJP
  port: 9443
  password: lINaALnHIiH4cSj8pJn6TQ==
  cipher: aes-128-gcm
- name: ğŸ‡¯ğŸ‡µJP_482 |21.09Mb
  server: 172.105.199.91
  type: ss
  country: ğŸ‡¯ğŸ‡µJP
  port: 8080
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: ğŸ‡¯ğŸ‡µJP_483 |10.17Mb
  server: 153.121.43.183
  type: ss
  country: ğŸ‡¯ğŸ‡µJP
  port: 10087
  password: '10086'
  cipher: aes-128-gcm
- name: ğŸ‡±ğŸ‡¹LT_498 |15.41Mb
  server: 45.87.175.185
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¯ğŸ‡µJP_484 |10.36Mb
  server: 172.105.199.111
  type: ss
  country: ğŸ‡¯ğŸ‡µJP
  port: 8080
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: ğŸ‡°ğŸ‡·KR_489 |15.83Mb
  server: 218.237.185.230
  type: ss
  country: ğŸ‡°ğŸ‡·KR
  port: 4652
  password: qwerREWQ@@
  cipher: aes-256-cfb
- name: ğŸ‡±ğŸ‡¹LT_503 |12.44Mb
  server: 45.87.175.171
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: QCXDxuDlTTMD7jtgHUjIoj
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_515 |15.30Mb
  server: 45.87.175.181
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: 1RWwXhwfAB5gAEozU4G2Pg
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_518 |14.43Mb
  server: 45.87.175.164
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: QCXDxuDlTTMD7jtgHUjIoj
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_522 |13.19Mb
  server: 45.87.175.192
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_524 |11.50Mb
  server: 45.87.175.188
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: 1RWwXhwfAB5gAEozU4G2Pg
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_537 |12.67Mb
  server: 45.87.175.165
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: QCXDxuDlTTMD7jtgHUjIoj
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸ‡®ğŸ‡¶IQ-ğŸ‡®ğŸ‡¶IQ_452 |10.01Mb
  server: h110vpnnl3.outlinekeys.net
  type: ss
  country: ğŸ‡®ğŸ‡¶IQ
  port: 58080
  password: RKwqPa0fotnJ6oaFsEpGWI
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_500 |10.05Mb
  server: ltnl14.saint.ydns.eu
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: 1RWwXhwfAB5gAEozU4G2Pg
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡­ğŸ‡°HK_427 |38.79Mb
  server: 8.217.158.92
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 49761
  uuid: b224875e-98a6-4477-a1ee-533887b6701d
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
  ws-opts:
    path: /arki?ed=2048
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - _132 |53.15Mb
  - _178 |10.51Mb
  - _150 |10.25Mb
  - _133 |10.24Mb
  - _176 |10.26Mb
  - Relay_ğŸ‡¨ğŸ‡¦CA-ğŸ‡¨ğŸ‡¦CA_207 |10.48Mb
  - ğŸ‡¨ğŸ‡¦CA_208 |10.56Mb
  - ğŸ‡¨ğŸ‡¦CA_210 |13.87Mb
  - ğŸ‡¨ğŸ‡¦CA_211 |29.17Mb
  - ğŸ‡¨ğŸ‡¦CA_212 |10.55Mb
  - disney_US |10.31Mb
  - ğŸ‡§ğŸ‡ªBE_198 |200.57Mb
  - ğŸ‡¦ğŸ‡·AR_186 |44.93Mb
  - ğŸ‡¨ğŸ‡¦CA_215 |10.90Mb
  - ğŸ‡¨ğŸ‡¦CA_216 |10.59Mb
  - ğŸ‡¨ğŸ‡¦CA_218 |10.09Mb
  - ğŸ‡¨ğŸ‡¦CA_219 |10.48Mb
  - ğŸ‡¦ğŸ‡ºAU_194 |10.30Mb
  - ğŸ‡§ğŸ‡ªBE_201 |48.25Mb
  - ğŸ‡§ğŸ‡ªBE_199 |188.98Mb
  - _145 |10.11Mb
  - _184 |10.01Mb
  - ğŸ‡¦ğŸ‡ºAU_196 |167.14Mb
  - Relay_ğŸ‡¨ğŸ‡¦CA-ğŸ‡¨ğŸ‡¦CA_217 |102.00Mb
  - ğŸ‡©ğŸ‡ªDE_235 |13.63Mb
  - ğŸ‡©ğŸ‡ªDE_246 |16.09Mb
  - ğŸ‡©ğŸ‡ªDE_250 |10.14Mb
  - ğŸ‡©ğŸ‡ªDE_256 |10.09Mb
  - ğŸ‡©ğŸ‡ªDE_258 |10.14Mb
  - ğŸ‡©ğŸ‡ªDE_262 |10.20Mb
  - ğŸ‡©ğŸ‡ªDE_263 |12.78Mb
  - ğŸ‡©ğŸ‡ªDE_268 |10.16Mb
  - ğŸ‡©ğŸ‡ªDE_272 |10.08Mb
  - Relay_ğŸ‡¨ğŸ‡­CH-ğŸ‡¨ğŸ‡­CH_221 |10.05Mb
  - ğŸ‡©ğŸ‡ªDE_275 |10.22Mb
  - ğŸ‡©ğŸ‡ªDE_278 |10.14Mb
  - ğŸ‡¬ğŸ‡§GB_358 |10.08Mb
  - ğŸ‡¬ğŸ‡§GB_366 |10.26Mb
  - ğŸ‡¬ğŸ‡§GB_373 |10.17Mb
  - ğŸ‡«ğŸ‡®FI_330 |10.08Mb
  - ğŸ‡ªğŸ‡¸ES_296 |14.43Mb
  - ğŸ‡«ğŸ‡·FR_344 |13.03Mb
  - Pool_ğŸ‡¬ğŸ‡§GB_392 |10.31Mb
  - ğŸ‡¬ğŸ‡§GB_380 |34.37Mb
  - ğŸ‡¬ğŸ‡¹GT_413 |15.81Mb
  - ğŸ‡¬ğŸ‡§GB_385 |47.10Mb
  - ğŸ‡¬ğŸ‡§GB_390 |15.43Mb
  - ğŸ‡¬ğŸ‡§GB_387 |15.25Mb
  - ğŸ‡­ğŸ‡°HK_417 |58.97Mb
  - ğŸ‡®ğŸ‡ªIE_445 |10.22Mb
  - ğŸ‡­ğŸ‡°HK_422 |151.55Mb
  - ğŸ‡­ğŸ‡°HK_424 |46.38Mb
  - ğŸ‡­ğŸ‡°HK_440 |46.00Mb
  - ğŸ‡­ğŸ‡°HK_441 |66.06Mb
  - Relay_ğŸ‡¬ğŸ‡§GB-ğŸ‡¬ğŸ‡§GB_360 |28.95Mb
  - Relay_ğŸ‡¬ğŸ‡§GB-ğŸ‡¬ğŸ‡§GB_378 |123.36Mb
  - Pool_ğŸ‡­ğŸ‡°HK_420 |425.00Mb
  - Relay_ğŸ‡®ğŸ‡·IR-ğŸ‡³ğŸ‡±NL_456 |10.10Mb
  - Relay_ğŸ‡®ğŸ‡·IR-ğŸ‡³ğŸ‡±NL_469 |10.12Mb
  - ğŸ‡­ğŸ‡°HK_438 |25.08Mb
  - ğŸ‡®ğŸ‡³IN_447 |114.10Mb
  - ğŸ‡¯ğŸ‡µJP_481 |10.58Mb
  - ğŸ‡¯ğŸ‡µJP_482 |21.09Mb
  - ğŸ‡¯ğŸ‡µJP_483 |10.17Mb
  - ğŸ‡±ğŸ‡¹LT_498 |15.41Mb
  - ğŸ‡¯ğŸ‡µJP_484 |10.36Mb
  - ğŸ‡°ğŸ‡·KR_489 |15.83Mb
  - ğŸ‡±ğŸ‡¹LT_503 |12.44Mb
  - ğŸ‡±ğŸ‡¹LT_515 |15.30Mb
  - ğŸ‡±ğŸ‡¹LT_518 |14.43Mb
  - ğŸ‡±ğŸ‡¹LT_522 |13.19Mb
  - ğŸ‡±ğŸ‡¹LT_524 |11.50Mb
  - ğŸ‡±ğŸ‡¹LT_537 |12.67Mb
  - Relay_ğŸ‡®ğŸ‡¶IQ-ğŸ‡®ğŸ‡¶IQ_452 |10.01Mb
  - ğŸ‡±ğŸ‡¹LT_500 |10.05Mb
  - ğŸ‡­ğŸ‡°HK_427 |38.79Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - _132 |53.15Mb
  - _178 |10.51Mb
  - _150 |10.25Mb
  - _133 |10.24Mb
  - _176 |10.26Mb
  - Relay_ğŸ‡¨ğŸ‡¦CA-ğŸ‡¨ğŸ‡¦CA_207 |10.48Mb
  - ğŸ‡¨ğŸ‡¦CA_208 |10.56Mb
  - ğŸ‡¨ğŸ‡¦CA_210 |13.87Mb
  - ğŸ‡¨ğŸ‡¦CA_211 |29.17Mb
  - ğŸ‡¨ğŸ‡¦CA_212 |10.55Mb
  - disney_US |10.31Mb
  - ğŸ‡§ğŸ‡ªBE_198 |200.57Mb
  - ğŸ‡¦ğŸ‡·AR_186 |44.93Mb
  - ğŸ‡¨ğŸ‡¦CA_215 |10.90Mb
  - ğŸ‡¨ğŸ‡¦CA_216 |10.59Mb
  - ğŸ‡¨ğŸ‡¦CA_218 |10.09Mb
  - ğŸ‡¨ğŸ‡¦CA_219 |10.48Mb
  - ğŸ‡¦ğŸ‡ºAU_194 |10.30Mb
  - ğŸ‡§ğŸ‡ªBE_201 |48.25Mb
  - ğŸ‡§ğŸ‡ªBE_199 |188.98Mb
  - _145 |10.11Mb
  - _184 |10.01Mb
  - ğŸ‡¦ğŸ‡ºAU_196 |167.14Mb
  - Relay_ğŸ‡¨ğŸ‡¦CA-ğŸ‡¨ğŸ‡¦CA_217 |102.00Mb
  - ğŸ‡©ğŸ‡ªDE_235 |13.63Mb
  - ğŸ‡©ğŸ‡ªDE_246 |16.09Mb
  - ğŸ‡©ğŸ‡ªDE_250 |10.14Mb
  - ğŸ‡©ğŸ‡ªDE_256 |10.09Mb
  - ğŸ‡©ğŸ‡ªDE_258 |10.14Mb
  - ğŸ‡©ğŸ‡ªDE_262 |10.20Mb
  - ğŸ‡©ğŸ‡ªDE_263 |12.78Mb
  - ğŸ‡©ğŸ‡ªDE_268 |10.16Mb
  - ğŸ‡©ğŸ‡ªDE_272 |10.08Mb
  - Relay_ğŸ‡¨ğŸ‡­CH-ğŸ‡¨ğŸ‡­CH_221 |10.05Mb
  - ğŸ‡©ğŸ‡ªDE_275 |10.22Mb
  - ğŸ‡©ğŸ‡ªDE_278 |10.14Mb
  - ğŸ‡¬ğŸ‡§GB_358 |10.08Mb
  - ğŸ‡¬ğŸ‡§GB_366 |10.26Mb
  - ğŸ‡¬ğŸ‡§GB_373 |10.17Mb
  - ğŸ‡«ğŸ‡®FI_330 |10.08Mb
  - ğŸ‡ªğŸ‡¸ES_296 |14.43Mb
  - ğŸ‡«ğŸ‡·FR_344 |13.03Mb
  - Pool_ğŸ‡¬ğŸ‡§GB_392 |10.31Mb
  - ğŸ‡¬ğŸ‡§GB_380 |34.37Mb
  - ğŸ‡¬ğŸ‡¹GT_413 |15.81Mb
  - ğŸ‡¬ğŸ‡§GB_385 |47.10Mb
  - ğŸ‡¬ğŸ‡§GB_390 |15.43Mb
  - ğŸ‡¬ğŸ‡§GB_387 |15.25Mb
  - ğŸ‡­ğŸ‡°HK_417 |58.97Mb
  - ğŸ‡®ğŸ‡ªIE_445 |10.22Mb
  - ğŸ‡­ğŸ‡°HK_422 |151.55Mb
  - ğŸ‡­ğŸ‡°HK_424 |46.38Mb
  - ğŸ‡­ğŸ‡°HK_440 |46.00Mb
  - ğŸ‡­ğŸ‡°HK_441 |66.06Mb
  - Relay_ğŸ‡¬ğŸ‡§GB-ğŸ‡¬ğŸ‡§GB_360 |28.95Mb
  - Relay_ğŸ‡¬ğŸ‡§GB-ğŸ‡¬ğŸ‡§GB_378 |123.36Mb
  - Pool_ğŸ‡­ğŸ‡°HK_420 |425.00Mb
  - Relay_ğŸ‡®ğŸ‡·IR-ğŸ‡³ğŸ‡±NL_456 |10.10Mb
  - Relay_ğŸ‡®ğŸ‡·IR-ğŸ‡³ğŸ‡±NL_469 |10.12Mb
  - ğŸ‡­ğŸ‡°HK_438 |25.08Mb
  - ğŸ‡®ğŸ‡³IN_447 |114.10Mb
  - ğŸ‡¯ğŸ‡µJP_481 |10.58Mb
  - ğŸ‡¯ğŸ‡µJP_482 |21.09Mb
  - ğŸ‡¯ğŸ‡µJP_483 |10.17Mb
  - ğŸ‡±ğŸ‡¹LT_498 |15.41Mb
  - ğŸ‡¯ğŸ‡µJP_484 |10.36Mb
  - ğŸ‡°ğŸ‡·KR_489 |15.83Mb
  - ğŸ‡±ğŸ‡¹LT_503 |12.44Mb
  - ğŸ‡±ğŸ‡¹LT_515 |15.30Mb
  - ğŸ‡±ğŸ‡¹LT_518 |14.43Mb
  - ğŸ‡±ğŸ‡¹LT_522 |13.19Mb
  - ğŸ‡±ğŸ‡¹LT_524 |11.50Mb
  - ğŸ‡±ğŸ‡¹LT_537 |12.67Mb
  - Relay_ğŸ‡®ğŸ‡¶IQ-ğŸ‡®ğŸ‡¶IQ_452 |10.01Mb
  - ğŸ‡±ğŸ‡¹LT_500 |10.05Mb
  - ğŸ‡­ğŸ‡°HK_427 |38.79Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
