port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: Relay_-ğŸ‡¨ğŸ‡¦CA_392 |68.97Mb
  server: 79.127.200.169
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _386 |238.58Mb
  server: 45.87.175.28
  type: ss
  port: 8080
  udp: true
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: _379 |235.23Mb
  server: 82.38.31.179
  type: ss
  port: 8080
  udp: true
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: _384 |175.62Mb
  server: 45.87.175.22
  type: ss
  port: 8080
  udp: true
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: _381 |84.18Mb
  server: 82.38.31.199
  type: ss
  port: 8080
  udp: true
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: _391 |168.39Mb
  server: 193.29.139.177
  type: ss
  port: 8080
  udp: true
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: _387 |164.90Mb
  server: 45.158.171.70
  type: ss
  port: 8080
  udp: true
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: _405 |76.53Mb
  server: 103.35.189.136
  type: ss
  port: 443
  udp: true
  password: SS2QvbC9nqLp2sXXZo0BVy4slcErRuCt
  cipher: chacha20-ietf-poly1305
- name: _396 |70.81Mb
  server: 15.157.66.237
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: _394 |150.13Mb
  server: 45.87.175.187
  type: ss
  port: 8080
  udp: true
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: _393 |276.78Mb
  server: 5.181.21.246
  type: ss
  port: 443
  udp: true
  password: gKYygTcRYhc3skc2x6tZ073lYz0DnieX
  cipher: chacha20-ietf-poly1305
- name: _376 |17.11Mb
  server: 38.165.233.93
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: _406 |23.68Mb
  server: 196.196.192.58
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _400 |159.31Mb
  server: 82.38.31.205
  type: ss
  port: 8080
  udp: true
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: _404 |261.67Mb
  server: 51.15.23.166
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: disney_netflix_GB |380.94Mb
  server: 146.70.61.37
  type: ss
  port: 8080
  udp: true
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: _412 |147.24Mb
  server: 193.29.139.206
  type: ss
  port: 8080
  udp: true
  password: 4a2rfixophdjffa8KVA4Aa
  cipher: chacha20-ietf-poly1305
- name: _414 |54.46Mb
  server: 82.38.31.214
  type: ss
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: _410 |40.77Mb
  server: 95.164.116.33
  type: ss
  port: 443
  password: pQmnC03JObbPhdh5FBJHgD6jnTLchsRA
  cipher: chacha20-ietf-poly1305
- name: _385 |11.66Mb
  server: 172.237.74.36
  type: ss
  port: 443
  udp: true
  password: Dk0XrU/n+SB84g0k+mX4zdy5HVVhuAUP6pCaldJxQjY=
  cipher: aes-256-gcm
- name: _411 |55.04Mb
  server: 141.98.101.178
  type: ss
  port: 443
  udp: true
  password: shadowsocks
  cipher: aes-128-gcm
- name: _415 |859.38Mb
  server: 82.38.31.190
  type: ss
  port: 8080
  udp: true
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: _419 |742.99Mb
  server: 82.38.31.176
  type: ss
  port: 8080
  udp: true
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: disney_US |70.50Mb
  server: 79.127.200.162
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: _435 |46.12Mb
  server: 47.253.228.138
  type: vmess
  port: 22524
  uuid: 80845fcc-f862-45fe-c1d3-0a7120373712
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
- name: _422 |121.17Mb
  server: 45.87.175.197
  type: ss
  port: 8080
  udp: true
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: _426 |695.66Mb
  server: 82.38.31.194
  type: ss
  port: 8080
  udp: true
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: _433 |26.13Mb
  server: 82.38.31.202
  type: ss
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: _420 |20.10Mb
  server: 149.22.87.241
  type: ss
  port: 443
  udp: true
  password: shadowsocks
  cipher: aes-128-gcm
- name: _434 |92.26Mb
  server: 193.29.139.132
  type: ss
  port: 8080
  udp: true
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: _457 |13.70Mb
  server: 15.235.41.200
  type: vmess
  port: 80
  uuid: 58fe1542-5290-40ad-815a-77707a81afe5
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /IOebhLMhl1CTbFHbL95myfRX2
- name: disney_US |42.59Mb
  server: 165.140.216.141
  type: vmess
  port: 443
  uuid: e7d72a8d-26f2-4b54-b366-0c43e0bcba7d
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _428 |45.21Mb
  server: 147.78.0.182
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _417 |44.16Mb
  server: 156.59.243.6
  type: ss
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _421 |27.62Mb
  server: 119.59.98.58
  type: ss
  port: 990
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: chacha20-ietf-poly1305
- name: _460 |40.40Mb
  server: 154.29.157.189
  type: vmess
  port: 38152
  uuid: b8ce19b1-4b15-41f9-a206-11957cc902d4
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
- name: _424 |30.60Mb
  server: 119.59.98.58
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: _451 |10.60Mb
  server: 54.206.192.9
  type: vmess
  port: 16407
  uuid: 08f45028-1db6-4e93-bf51-d344b6c71e19
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: Pool__494 |24.51Mb
  server: 70.34.218.149
  type: trojan
  port: 11930
  password: BaeSzHdfJIR13l67
  sni: softpillow.silentrocket.click
- name: disney_US |11.58Mb
  server: 206.119.191.9
  type: vmess
  port: 7100
  uuid: 10853485-26e1-477b-d257-58a3f4873db3
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
- name: Relay_-ğŸ‡¯ğŸ‡µJP_465 |18.07Mb
  server: 160.16.107.37
  type: trojan
  port: 3169
  password: 44e660b0ee21cf3ac66aee2c08af85d2
  sni: www.nintendogames.net
- name: ğŸ‡¨ğŸ‡¦CA_588 |15.18Mb
  server: 185.213.23.63
  type: ss
  country: ğŸ‡¨ğŸ‡¦CA
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _454 |40.49Mb
  server: 89.31.120.192
  type: vmess
  port: 443
  uuid: 44537595-9ccc-4b83-8936-5f9ad3229019
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _500 |10.80Mb
  server: 160.16.81.84
  type: trojan
  port: 2760
  password: 44e660b0ee21cf3ac66aee2c08af85d2
  sni: www.nintendogames.net
  skip-cert-verify: true
- name: Relay_-ğŸ‡¯ğŸ‡µJP_546 |14.95Mb
  server: 160.16.107.37
  type: trojan
  port: 3093
  password: 44e660b0ee21cf3ac66aee2c08af85d2
  sni: www.nintendogames.net
- name: ğŸ‡¬ğŸ‡§GB_591 |73.49Mb
  server: 141.98.101.182
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: shadowsocks
  cipher: aes-128-gcm
- name: _561 |11.03Mb
  server: 160.16.116.227
  type: trojan
  port: 2760
  password: 44e660b0ee21cf3ac66aee2c08af85d2
  sni: www.nintendogames.net
  skip-cert-verify: true
- name: _562 |10.50Mb
  server: 160.16.57.238
  type: trojan
  port: 2760
  password: 44e660b0ee21cf3ac66aee2c08af85d2
  sni: www.nintendogames.net
  skip-cert-verify: true
- name: ğŸ‡±ğŸ‡¹ LT_602 |101.73Mb
  server: 45.87.175.178
  type: ss
  country: ğŸ‡±ğŸ‡¹ LT
  port: 8080
  password: 1RWwXhwfAB5gAEozU4G2Pg
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹ LT_603 |140.09Mb
  server: 45.87.175.178
  type: ss
  country: ğŸ‡±ğŸ‡¹ LT
  port: 8080
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹ LT_604 |122.90Mb
  server: 45.87.175.178
  type: ss
  country: ğŸ‡±ğŸ‡¹ LT
  port: 8080
  password: 4a2rfixophdjffa8KVA4Aa
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_606 |615.96Mb
  server: 45.87.175.185
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_607 |59.30Mb
  server: 45.87.175.200
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: Relay_-ğŸ‡­ğŸ‡°HK_547 |10.69Mb
  server: cdnfire.xiaomispeed.com
  type: trojan
  port: 21102
  udp: true
  password: 0793b374-95af-48da-9bdc-f6d5fb8d3634
  sni: cdnfire.xiaomispeed.com
  skip-cert-verify: true
- name: ğŸ‡±ğŸ‡¹LT_608 |737.06Mb
  server: 45.87.175.183
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_609 |154.13Mb
  server: 45.87.175.180
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: QCXDxuDlTTMD7jtgHUjIoj
  cipher: chacha20-ietf-poly1305
- name: disney_HK |28.61Mb
  server: 45.207.157.29
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 13852
  uuid: 845764df-ecb3-4b13-bed2-bf1551b68e9a
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡±ğŸ‡¹LT_611 |364.26Mb
  server: 45.87.175.185
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡²ğŸ‡½MX_614 |37.78Mb
  server: 216.238.87.47
  type: vmess
  country: ğŸ‡²ğŸ‡½MX
  port: 27502
  uuid: b8155ce4-7e08-4c40-800f-8671312b7124
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡±ğŸ‡¹LT_612 |160.73Mb
  server: 45.87.175.190
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡³ğŸ‡±NL_615 |170.26Mb
  server: 193.29.139.141
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 8080
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: disney_LV |25.73Mb
  server: 46.183.217.204
  type: ss
  country: ğŸ‡±ğŸ‡» LV
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_626 |89.75Mb
  server: 64.69.40.135
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 10678
  uuid: c5aec222-3b11-4af8-f01f-f9145b0caabb
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡³ğŸ‡±NL_618 |167.02Mb
  server: 193.29.139.209
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 8080
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡³ğŸ‡±NL_617 |56.36Mb
  server: 178.23.190.238
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 443
  password: uo7EbtqIwgZXXHmMv5LbLcOxptyPlNkh
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡µğŸ‡¹PT_622 |61.76Mb
  server: 185.113.143.186
  type: ss
  country: ğŸ‡µğŸ‡¹PT
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_610 |163.45Mb
  server: ltnl16.saint.ydns.eu
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_605 |38.53Mb
  server: 45.87.175.175
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: QCXDxuDlTTMD7jtgHUjIoj
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¨ğŸ‡±CL_589 |10.31Mb
  server: 154.205.153.107
  type: ss
  country: ğŸ‡¨ğŸ‡±CL
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - Relay_-ğŸ‡¨ğŸ‡¦CA_392 |68.97Mb
  - _386 |238.58Mb
  - _379 |235.23Mb
  - _384 |175.62Mb
  - _381 |84.18Mb
  - _391 |168.39Mb
  - _387 |164.90Mb
  - _405 |76.53Mb
  - _396 |70.81Mb
  - _394 |150.13Mb
  - _393 |276.78Mb
  - _376 |17.11Mb
  - _406 |23.68Mb
  - _400 |159.31Mb
  - _404 |261.67Mb
  - disney_netflix_GB |380.94Mb
  - _412 |147.24Mb
  - _414 |54.46Mb
  - _410 |40.77Mb
  - _385 |11.66Mb
  - _411 |55.04Mb
  - _415 |859.38Mb
  - _419 |742.99Mb
  - disney_US |70.50Mb
  - _435 |46.12Mb
  - _422 |121.17Mb
  - _426 |695.66Mb
  - _433 |26.13Mb
  - _420 |20.10Mb
  - _434 |92.26Mb
  - _457 |13.70Mb
  - disney_US |42.59Mb
  - _428 |45.21Mb
  - _417 |44.16Mb
  - _421 |27.62Mb
  - _460 |40.40Mb
  - _424 |30.60Mb
  - _451 |10.60Mb
  - Pool__494 |24.51Mb
  - disney_US |11.58Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_465 |18.07Mb
  - ğŸ‡¨ğŸ‡¦CA_588 |15.18Mb
  - _454 |40.49Mb
  - _500 |10.80Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_546 |14.95Mb
  - ğŸ‡¬ğŸ‡§GB_591 |73.49Mb
  - _561 |11.03Mb
  - _562 |10.50Mb
  - ğŸ‡±ğŸ‡¹ LT_602 |101.73Mb
  - ğŸ‡±ğŸ‡¹ LT_603 |140.09Mb
  - ğŸ‡±ğŸ‡¹ LT_604 |122.90Mb
  - ğŸ‡±ğŸ‡¹LT_606 |615.96Mb
  - ğŸ‡±ğŸ‡¹LT_607 |59.30Mb
  - Relay_-ğŸ‡­ğŸ‡°HK_547 |10.69Mb
  - ğŸ‡±ğŸ‡¹LT_608 |737.06Mb
  - ğŸ‡±ğŸ‡¹LT_609 |154.13Mb
  - disney_HK |28.61Mb
  - ğŸ‡±ğŸ‡¹LT_611 |364.26Mb
  - ğŸ‡²ğŸ‡½MX_614 |37.78Mb
  - ğŸ‡±ğŸ‡¹LT_612 |160.73Mb
  - ğŸ‡³ğŸ‡±NL_615 |170.26Mb
  - disney_LV |25.73Mb
  - ğŸ‡ºğŸ‡¸US_626 |89.75Mb
  - ğŸ‡³ğŸ‡±NL_618 |167.02Mb
  - ğŸ‡³ğŸ‡±NL_617 |56.36Mb
  - ğŸ‡µğŸ‡¹PT_622 |61.76Mb
  - ğŸ‡±ğŸ‡¹LT_610 |163.45Mb
  - ğŸ‡±ğŸ‡¹LT_605 |38.53Mb
  - ğŸ‡¨ğŸ‡±CL_589 |10.31Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - Relay_-ğŸ‡¨ğŸ‡¦CA_392 |68.97Mb
  - _386 |238.58Mb
  - _379 |235.23Mb
  - _384 |175.62Mb
  - _381 |84.18Mb
  - _391 |168.39Mb
  - _387 |164.90Mb
  - _405 |76.53Mb
  - _396 |70.81Mb
  - _394 |150.13Mb
  - _393 |276.78Mb
  - _376 |17.11Mb
  - _406 |23.68Mb
  - _400 |159.31Mb
  - _404 |261.67Mb
  - disney_netflix_GB |380.94Mb
  - _412 |147.24Mb
  - _414 |54.46Mb
  - _410 |40.77Mb
  - _385 |11.66Mb
  - _411 |55.04Mb
  - _415 |859.38Mb
  - _419 |742.99Mb
  - disney_US |70.50Mb
  - _435 |46.12Mb
  - _422 |121.17Mb
  - _426 |695.66Mb
  - _433 |26.13Mb
  - _420 |20.10Mb
  - _434 |92.26Mb
  - _457 |13.70Mb
  - disney_US |42.59Mb
  - _428 |45.21Mb
  - _417 |44.16Mb
  - _421 |27.62Mb
  - _460 |40.40Mb
  - _424 |30.60Mb
  - _451 |10.60Mb
  - Pool__494 |24.51Mb
  - disney_US |11.58Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_465 |18.07Mb
  - ğŸ‡¨ğŸ‡¦CA_588 |15.18Mb
  - _454 |40.49Mb
  - _500 |10.80Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_546 |14.95Mb
  - ğŸ‡¬ğŸ‡§GB_591 |73.49Mb
  - _561 |11.03Mb
  - _562 |10.50Mb
  - ğŸ‡±ğŸ‡¹ LT_602 |101.73Mb
  - ğŸ‡±ğŸ‡¹ LT_603 |140.09Mb
  - ğŸ‡±ğŸ‡¹ LT_604 |122.90Mb
  - ğŸ‡±ğŸ‡¹LT_606 |615.96Mb
  - ğŸ‡±ğŸ‡¹LT_607 |59.30Mb
  - Relay_-ğŸ‡­ğŸ‡°HK_547 |10.69Mb
  - ğŸ‡±ğŸ‡¹LT_608 |737.06Mb
  - ğŸ‡±ğŸ‡¹LT_609 |154.13Mb
  - disney_HK |28.61Mb
  - ğŸ‡±ğŸ‡¹LT_611 |364.26Mb
  - ğŸ‡²ğŸ‡½MX_614 |37.78Mb
  - ğŸ‡±ğŸ‡¹LT_612 |160.73Mb
  - ğŸ‡³ğŸ‡±NL_615 |170.26Mb
  - disney_LV |25.73Mb
  - ğŸ‡ºğŸ‡¸US_626 |89.75Mb
  - ğŸ‡³ğŸ‡±NL_618 |167.02Mb
  - ğŸ‡³ğŸ‡±NL_617 |56.36Mb
  - ğŸ‡µğŸ‡¹PT_622 |61.76Mb
  - ğŸ‡±ğŸ‡¹LT_610 |163.45Mb
  - ğŸ‡±ğŸ‡¹LT_605 |38.53Mb
  - ğŸ‡¨ğŸ‡±CL_589 |10.31Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
