port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: ğŸ‡¨ğŸ‡¦CA_16 |47.05Mb
  server: 138.197.165.21
  type: ss
  country: ğŸ‡¨ğŸ‡¦CA
  port: 8080
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: ğŸ‡¨ğŸ‡¦CA_14 |16.34Mb
  server: 138.197.153.10
  type: ss
  country: ğŸ‡¨ğŸ‡¦CA
  port: 8080
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: ğŸ‡¨ğŸ‡¦CA_17 |221.37Mb
  server: 137.184.174.93
  type: ss
  country: ğŸ‡¨ğŸ‡¦CA
  port: 8080
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: ğŸ‡¨ğŸ‡¦CA_18 |151.74Mb
  server: 147.182.146.81
  type: ss
  country: ğŸ‡¨ğŸ‡¦CA
  port: 8080
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: disney_US |14.85Mb
  server: 79.127.200.162
  type: ss
  country: ğŸ‡¨ğŸ‡¦CA
  port: 990
  password: f8f7aCzcPKbsF8p3
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸ‡¨ğŸ‡¦CA-ğŸ‡¨ğŸ‡¦CA_19 |735.00Mb
  server: ssca.irundns.net
  type: ssr
  country: ğŸ‡¨ğŸ‡¦CA
  port: 443
  password: $$Turb0VPN$$
  cipher: aes-128-cfb
  protocol: auth_aes128_md5
  obfs: http_post
- name: ğŸ‡©ğŸ‡ªDE_23 |13.38Mb
  server: 18.199.176.226
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: _07 |10.23Mb
  server: 46.183.217.204
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¨ğŸ‡¾CY_21 |43.16Mb
  server: 91.148.135.31
  type: ss
  country: ğŸ‡¨ğŸ‡¾CY
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡©ğŸ‡ªDE_28 |25.28Mb
  server: 81.19.141.45
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 443
  password: ql8iN6ChurUrd25DoZJA0n
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡©ğŸ‡ªDE_38 |13.06Mb
  server: 93.186.201.64
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 57456
  password: c40641c1f89e7acb
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡©ğŸ‡ªDE_29 |36.49Mb
  server: 3.123.25.149
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡©ğŸ‡ªDE_39 |17.52Mb
  server: 18.158.60.169
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡©ğŸ‡ªDE_34 |111.50Mb
  server: 81.19.141.45
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 443
  password: eTJKAiONWap955RkxyPi3F
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡©ğŸ‡ªDE_40 |189.47Mb
  server: 81.19.141.45
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 443
  password: rC23nT4eVDHF06wmuyvSUe
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡©ğŸ‡ªDE_48 |66.40Mb
  server: 85.195.101.122
  type: vmess
  country: ğŸ‡©ğŸ‡ªDE
  port: 40878
  uuid: f3d4167e-b15e-4e46-82e9-9286ef93fda7
  alterId: 0
  cipher: auto
  network: tcp
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡ªğŸ‡¸ES_58 |14.13Mb
  server: 194.87.45.189
  type: ss
  country: ğŸ‡ªğŸ‡¸ES
  port: 443
  password: bwCWtYQWtc4ez14JGe7K51
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡©ğŸ‡ªDE_44 |11.90Mb
  server: 81.19.141.45
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 443
  password: GolXNbBG1EfcTZhaccBOAG
  cipher: chacha20-ietf-poly1305
- name: disney_GB |10.05Mb
  server: 89.185.84.185
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: ozSHXLRuO7JckCvhgLjLaU
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ªğŸ‡¸ES_72 |10.54Mb
  server: 194.87.45.189
  type: ss
  country: ğŸ‡ªğŸ‡¸ES
  port: 443
  password: 676zALNF1CckrwJ6HGjRKl
  cipher: chacha20-ietf-poly1305
- name: disney_GB |20.83Mb
  server: 89.185.84.185
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: tVBUTDznmHpV3lpKzbw2Nl
  cipher: chacha20-ietf-poly1305
- name: disney_GB |18.65Mb
  server: 89.185.84.185
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: IKM7Oo8MqE5gaba7mifgyx
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_84 |47.93Mb
  server: 213.109.147.242
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 62685
  password: VpKABcOpNNA0l5G2AVOmw8
  cipher: chacha20-ietf-poly1305
- name: disney_GB |18.17Mb
  server: 89.185.84.185
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: gbCXg98Ecfx15al9somp9w
  cipher: chacha20-ietf-poly1305
- name: disney_GB |12.50Mb
  server: 89.185.84.185
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: V9gJ8OOLGreg27vYV5HSd3
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_93 |47.38Mb
  server: 18.169.158.38
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: disney_GB |10.94Mb
  server: 89.185.84.185
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: RCep1UaygXjYEdFS9kOsm3
  cipher: chacha20-ietf-poly1305
- name: disney_GB |55.20Mb
  server: 89.185.84.185
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: 2kCbzhE1x9M8mfqzDEBeyL
  cipher: chacha20-ietf-poly1305
- name: disney_GB |56.30Mb
  server: 89.185.84.185
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: L1K56urlkYrclYgNEEpz74
  cipher: chacha20-ietf-poly1305
- name: disney_GB |13.97Mb
  server: 89.185.84.185
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: IP77QXJz3YEA90m7miLOBu
  cipher: chacha20-ietf-poly1305
- name: disney_GB |13.87Mb
  server: 89.185.84.185
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: xAtN0lzbVwFASy3wi6pVq4
  cipher: chacha20-ietf-poly1305
- name: disney_GB |21.76Mb
  server: 89.185.84.185
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: teojx0gaa5ctzJ7m0VoXky
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_109 |36.63Mb
  server: 3.8.172.214
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡¬ğŸ‡§GB_111 |36.66Mb
  server: 18.135.29.154
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡¯ğŸ‡µJP_131 |11.92Mb
  server: 140.83.80.36
  type: vmess
  country: ğŸ‡¯ğŸ‡µJP
  port: 22545
  uuid: 5b907403-239e-4660-8ab6-b6f3d811d1da
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
  ws-opts:
    path: /
- name: disney_GB |53.98Mb
  server: 89.185.84.185
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: B2ISJ3faDXlkRUXUeQu182
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_136 |12.29Mb
  server: 45.87.175.192
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_137 |12.05Mb
  server: 45.87.175.188
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡®ğŸ‡¶IQ_117 |48.98Mb
  server: 81.90.31.219
  type: ss
  country: ğŸ‡®ğŸ‡¶IQ
  port: 443
  password: iRZgNTcrf657aaZpPkCFWu
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_143 |24.66Mb
  server: 45.87.175.164
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: 4a2rfixophdjffa8KVA4Aa
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_144 |24.47Mb
  server: 45.87.175.171
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: 4a2rfixophdjffa8KVA4Aa
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡³ğŸ‡±NL_149 |93.39Mb
  server: 193.29.139.160
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 8080
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡³ğŸ‡±NL_158 |17.43Mb
  server: 193.29.139.188
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 8080
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_254 |19.30Mb
  server: 38.91.102.40
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 5003
  password: g5MeD6Ft3CWlJId
  cipher: aes-256-gcm
- name: ğŸ‡µğŸ‡±PL_174 |10.12Mb
  server: 217.30.10.70
  type: ss
  country: ğŸ‡µğŸ‡±PL
  port: 9060
  password: ueLXVkvh4hckhErQ
  cipher: aes-256-cfb
- name: ğŸ‡ºğŸ‡¸US_255 |15.14Mb
  server: 18.224.70.173
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡ºğŸ‡¸US_256 |10.44Mb
  server: 3.141.46.88
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: disney_US |19.97Mb
  server: 165.140.216.141
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  uuid: e7d72a8d-26f2-4b54-b366-0c43e0bcba7d
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡µğŸ‡±PL_197 |11.54Mb
  server: 217.30.10.70
  type: ss
  country: ğŸ‡µğŸ‡±PL
  port: 9003
  password: JdmRK9gMEqFgs8nP
  cipher: aes-256-cfb
- name: ğŸ‡µğŸ‡¹PT_213 |18.73Mb
  server: 185.231.233.173
  type: ss
  country: ğŸ‡µğŸ‡¹PT
  port: 990
  password: f8f7aCzcPKbsF8p3
  cipher: chacha20-ietf-poly1305
- name: disney_US |11.88Mb
  server: 154.64.243.19
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 38533
  uuid: 9bc23ccf-4769-4e9a-b278-2dfa8d9ef425
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
  ws-opts:
    path: /
- name: disney_US |180.15Mb
  server: 193.124.24.247
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 6513
  uuid: 5cf7fcbc-e2c1-42c4-d0d7-79c45a7d588d
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡¸ğŸ‡ªSE_220 |10.18Mb
  server: 121.127.46.147
  type: ss
  country: ğŸ‡¸ğŸ‡ªSE
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ğŸ‡ºğŸ‡¸US_258 |37.95Mb
  server: 13.59.110.241
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡³ğŸ‡±NL_239 |18.59Mb
  server: 45.158.171.70
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 8080
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: disney_US |447.61Mb
  server: 193.124.24.247
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 6508
  uuid: b68fead5-5b0b-43a1-c34a-804467f0f368
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_US |110.71Mb
  server: 193.124.24.247
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 6504
  uuid: 7ceb165c-9aff-4ab7-ce9e-1df31a5ed911
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_US |249.77Mb
  server: 193.124.24.247
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 6515
  uuid: 2f3c646a-37f3-483a-a2a5-6bc1c5e526ae
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_US |319.36Mb
  server: 193.124.24.247
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 6507
  uuid: 3003e094-707c-4dbb-faca-4b8d579bc604
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Pool_ğŸ‡­ğŸ‡°HK_116 |183.00Mb
  server: 150.107.46.21
  type: ssr
  country: ğŸ‡­ğŸ‡°HK
  port: 8083
  password: iFqnzSscN
  cipher: aes-256-cfb
  protocol: origin
  obfs: tls1.2_ticket_auth
- name: ğŸ‡ºğŸ‡¸US_272 |12.94Mb
  server: 45.8.146.129
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 80
  uuid: 0704016f-5435-4655-be6a-771a5aba52c3
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
  ws-opts:
    path: /vmess/
- name: disney_GB |54.93Mb
  server: 89.185.84.185
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: uQ61t9OowCuNc2aaU3YRAP
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡©ğŸ‡ªDE_35 |181.36Mb
  server: 81.19.141.45
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 443
  password: R3mKxe2C75w5KLik5dhZXn
  cipher: chacha20-ietf-poly1305
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - ğŸ‡¨ğŸ‡¦CA_16 |47.05Mb
  - ğŸ‡¨ğŸ‡¦CA_14 |16.34Mb
  - ğŸ‡¨ğŸ‡¦CA_17 |221.37Mb
  - ğŸ‡¨ğŸ‡¦CA_18 |151.74Mb
  - disney_US |14.85Mb
  - Relay_ğŸ‡¨ğŸ‡¦CA-ğŸ‡¨ğŸ‡¦CA_19 |735.00Mb
  - ğŸ‡©ğŸ‡ªDE_23 |13.38Mb
  - _07 |10.23Mb
  - ğŸ‡¨ğŸ‡¾CY_21 |43.16Mb
  - ğŸ‡©ğŸ‡ªDE_28 |25.28Mb
  - ğŸ‡©ğŸ‡ªDE_38 |13.06Mb
  - ğŸ‡©ğŸ‡ªDE_29 |36.49Mb
  - ğŸ‡©ğŸ‡ªDE_39 |17.52Mb
  - ğŸ‡©ğŸ‡ªDE_34 |111.50Mb
  - ğŸ‡©ğŸ‡ªDE_40 |189.47Mb
  - ğŸ‡©ğŸ‡ªDE_48 |66.40Mb
  - ğŸ‡ªğŸ‡¸ES_58 |14.13Mb
  - ğŸ‡©ğŸ‡ªDE_44 |11.90Mb
  - disney_GB |10.05Mb
  - ğŸ‡ªğŸ‡¸ES_72 |10.54Mb
  - disney_GB |20.83Mb
  - disney_GB |18.65Mb
  - ğŸ‡¬ğŸ‡§GB_84 |47.93Mb
  - disney_GB |18.17Mb
  - disney_GB |12.50Mb
  - ğŸ‡¬ğŸ‡§GB_93 |47.38Mb
  - disney_GB |10.94Mb
  - disney_GB |55.20Mb
  - disney_GB |56.30Mb
  - disney_GB |13.97Mb
  - disney_GB |13.87Mb
  - disney_GB |21.76Mb
  - ğŸ‡¬ğŸ‡§GB_109 |36.63Mb
  - ğŸ‡¬ğŸ‡§GB_111 |36.66Mb
  - ğŸ‡¯ğŸ‡µJP_131 |11.92Mb
  - disney_GB |53.98Mb
  - ğŸ‡±ğŸ‡¹LT_136 |12.29Mb
  - ğŸ‡±ğŸ‡¹LT_137 |12.05Mb
  - ğŸ‡®ğŸ‡¶IQ_117 |48.98Mb
  - ğŸ‡±ğŸ‡¹LT_143 |24.66Mb
  - ğŸ‡±ğŸ‡¹LT_144 |24.47Mb
  - ğŸ‡³ğŸ‡±NL_149 |93.39Mb
  - ğŸ‡³ğŸ‡±NL_158 |17.43Mb
  - ğŸ‡ºğŸ‡¸US_254 |19.30Mb
  - ğŸ‡µğŸ‡±PL_174 |10.12Mb
  - ğŸ‡ºğŸ‡¸US_255 |15.14Mb
  - ğŸ‡ºğŸ‡¸US_256 |10.44Mb
  - disney_US |19.97Mb
  - ğŸ‡µğŸ‡±PL_197 |11.54Mb
  - ğŸ‡µğŸ‡¹PT_213 |18.73Mb
  - disney_US |11.88Mb
  - disney_US |180.15Mb
  - ğŸ‡¸ğŸ‡ªSE_220 |10.18Mb
  - ğŸ‡ºğŸ‡¸US_258 |37.95Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡³ğŸ‡±NL_239 |18.59Mb
  - disney_US |447.61Mb
  - disney_US |110.71Mb
  - disney_US |249.77Mb
  - disney_US |319.36Mb
  - Pool_ğŸ‡­ğŸ‡°HK_116 |183.00Mb
  - ğŸ‡ºğŸ‡¸US_272 |12.94Mb
  - disney_GB |54.93Mb
  - ğŸ‡©ğŸ‡ªDE_35 |181.36Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - ğŸ‡¨ğŸ‡¦CA_16 |47.05Mb
  - ğŸ‡¨ğŸ‡¦CA_14 |16.34Mb
  - ğŸ‡¨ğŸ‡¦CA_17 |221.37Mb
  - ğŸ‡¨ğŸ‡¦CA_18 |151.74Mb
  - disney_US |14.85Mb
  - Relay_ğŸ‡¨ğŸ‡¦CA-ğŸ‡¨ğŸ‡¦CA_19 |735.00Mb
  - ğŸ‡©ğŸ‡ªDE_23 |13.38Mb
  - _07 |10.23Mb
  - ğŸ‡¨ğŸ‡¾CY_21 |43.16Mb
  - ğŸ‡©ğŸ‡ªDE_28 |25.28Mb
  - ğŸ‡©ğŸ‡ªDE_38 |13.06Mb
  - ğŸ‡©ğŸ‡ªDE_29 |36.49Mb
  - ğŸ‡©ğŸ‡ªDE_39 |17.52Mb
  - ğŸ‡©ğŸ‡ªDE_34 |111.50Mb
  - ğŸ‡©ğŸ‡ªDE_40 |189.47Mb
  - ğŸ‡©ğŸ‡ªDE_48 |66.40Mb
  - ğŸ‡ªğŸ‡¸ES_58 |14.13Mb
  - ğŸ‡©ğŸ‡ªDE_44 |11.90Mb
  - disney_GB |10.05Mb
  - ğŸ‡ªğŸ‡¸ES_72 |10.54Mb
  - disney_GB |20.83Mb
  - disney_GB |18.65Mb
  - ğŸ‡¬ğŸ‡§GB_84 |47.93Mb
  - disney_GB |18.17Mb
  - disney_GB |12.50Mb
  - ğŸ‡¬ğŸ‡§GB_93 |47.38Mb
  - disney_GB |10.94Mb
  - disney_GB |55.20Mb
  - disney_GB |56.30Mb
  - disney_GB |13.97Mb
  - disney_GB |13.87Mb
  - disney_GB |21.76Mb
  - ğŸ‡¬ğŸ‡§GB_109 |36.63Mb
  - ğŸ‡¬ğŸ‡§GB_111 |36.66Mb
  - ğŸ‡¯ğŸ‡µJP_131 |11.92Mb
  - disney_GB |53.98Mb
  - ğŸ‡±ğŸ‡¹LT_136 |12.29Mb
  - ğŸ‡±ğŸ‡¹LT_137 |12.05Mb
  - ğŸ‡®ğŸ‡¶IQ_117 |48.98Mb
  - ğŸ‡±ğŸ‡¹LT_143 |24.66Mb
  - ğŸ‡±ğŸ‡¹LT_144 |24.47Mb
  - ğŸ‡³ğŸ‡±NL_149 |93.39Mb
  - ğŸ‡³ğŸ‡±NL_158 |17.43Mb
  - ğŸ‡ºğŸ‡¸US_254 |19.30Mb
  - ğŸ‡µğŸ‡±PL_174 |10.12Mb
  - ğŸ‡ºğŸ‡¸US_255 |15.14Mb
  - ğŸ‡ºğŸ‡¸US_256 |10.44Mb
  - disney_US |19.97Mb
  - ğŸ‡µğŸ‡±PL_197 |11.54Mb
  - ğŸ‡µğŸ‡¹PT_213 |18.73Mb
  - disney_US |11.88Mb
  - disney_US |180.15Mb
  - ğŸ‡¸ğŸ‡ªSE_220 |10.18Mb
  - ğŸ‡ºğŸ‡¸US_258 |37.95Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡³ğŸ‡±NL_239 |18.59Mb
  - disney_US |447.61Mb
  - disney_US |110.71Mb
  - disney_US |249.77Mb
  - disney_US |319.36Mb
  - Pool_ğŸ‡­ğŸ‡°HK_116 |183.00Mb
  - ğŸ‡ºğŸ‡¸US_272 |12.94Mb
  - disney_GB |54.93Mb
  - ğŸ‡©ğŸ‡ªDE_35 |181.36Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
