port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: ğŸ‡¨ğŸ‡¦CA_10 |16.34Mb
  server: 138.197.153.10
  type: ss
  country: ğŸ‡¨ğŸ‡¦CA
  port: 8080
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: disney_GB |54.28Mb
  server: 89.185.84.185
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: WhUYn0yZ6bLrILxzItfxSI
  cipher: chacha20-ietf-poly1305
- name: _06 |38.15Mb
  server: 62.100.205.100
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: disney_GB |21.76Mb
  server: 89.185.84.185
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: teojx0gaa5ctzJ7m0VoXky
  cipher: chacha20-ietf-poly1305
- name: disney_GB |10.03Mb
  server: 89.185.84.185
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: m8V5Orkxu2ob8LH24OFobn
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡©ğŸ‡ªDE_19 |21.71Mb
  server: 35.159.233.191
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡«ğŸ‡®FI_35 |10.11Mb
  server: 37.143.129.98
  type: ss
  country: ğŸ‡«ğŸ‡®FI
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ªğŸ‡¸ES_30 |10.54Mb
  server: 194.87.45.189
  type: ss
  country: ğŸ‡ªğŸ‡¸ES
  port: 443
  password: 676zALNF1CckrwJ6HGjRKl
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ªğŸ‡¸ES_24 |16.81Mb
  server: 194.87.45.189
  type: ss
  country: ğŸ‡ªğŸ‡¸ES
  port: 443
  password: ibM43ZBJYYFnJKo1AHwHSu
  cipher: chacha20-ietf-poly1305
- name: _08 |12.73Mb
  server: 185.237.185.89
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_84 |19.30Mb
  server: 38.91.102.40
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 5003
  password: g5MeD6Ft3CWlJId
  cipher: aes-256-gcm
- name: ğŸ‡ºğŸ‡¸US_90 |894.88Mb
  server: 142.171.237.17
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 1988
  uuid: aed0feeb-1283-4b7d-b3a4-71ef038d59af
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_US |180.15Mb
  server: 193.124.24.247
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 6513
  uuid: 5cf7fcbc-e2c1-42c4-d0d7-79c45a7d588d
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_GB |19.94Mb
  server: 89.185.84.185
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: Qqt1DFQEMvj6oJ69n6uf1Z
  cipher: chacha20-ietf-poly1305
- name: disney_US |110.71Mb
  server: 193.124.24.247
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 6504
  uuid: 7ceb165c-9aff-4ab7-ce9e-1df31a5ed911
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡²ğŸ‡©MD_78 |12.18Mb
  server: 23.95.76.59
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_80 |15.14Mb
  server: 18.224.70.173
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: disney_US |14.83Mb
  server: 154.29.158.139
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 12299
  uuid: cccfe679-fbd0-4402-caf2-67e919db436f
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_US |447.61Mb
  server: 193.124.24.247
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 6508
  uuid: b68fead5-5b0b-43a1-c34a-804467f0f368
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_US |70.03Mb
  server: 193.124.24.247
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 6514
  uuid: c362d735-01a8-48eb-baa2-ae7aa63bfdc3
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_US |319.36Mb
  server: 193.124.24.247
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 6507
  uuid: 3003e094-707c-4dbb-faca-4b8d579bc604
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_GB |19.17Mb
  server: 89.185.84.185
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: FXjMQIem0uShGvRzOpfyib
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡³ğŸ‡±NL_77 |18.59Mb
  server: 45.158.171.70
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 8080
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡µğŸ‡±PL_68 |18.17Mb
  server: 77.83.246.74
  type: ss
  country: ğŸ‡µğŸ‡±PL
  port: 443
  password: 0fV7k5wmlkPk2TNmx22rCQ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡µğŸ‡±PL_60 |101.49Mb
  server: 77.83.246.74
  type: ss
  country: ğŸ‡µğŸ‡±PL
  port: 443
  password: 3lMY9rECUubSUVrQEeF2KC
  cipher: chacha20-ietf-poly1305
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - ğŸ‡¨ğŸ‡¦CA_10 |16.34Mb
  - disney_GB |54.28Mb
  - _06 |38.15Mb
  - disney_GB |21.76Mb
  - disney_GB |10.03Mb
  - ğŸ‡©ğŸ‡ªDE_19 |21.71Mb
  - ğŸ‡«ğŸ‡®FI_35 |10.11Mb
  - ğŸ‡ªğŸ‡¸ES_30 |10.54Mb
  - ğŸ‡ªğŸ‡¸ES_24 |16.81Mb
  - _08 |12.73Mb
  - ğŸ‡ºğŸ‡¸US_84 |19.30Mb
  - ğŸ‡ºğŸ‡¸US_90 |894.88Mb
  - disney_US |180.15Mb
  - disney_GB |19.94Mb
  - disney_US |110.71Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡²ğŸ‡©MD_78 |12.18Mb
  - ğŸ‡ºğŸ‡¸US_80 |15.14Mb
  - disney_US |14.83Mb
  - disney_US |447.61Mb
  - disney_US |70.03Mb
  - disney_US |319.36Mb
  - disney_GB |19.17Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡³ğŸ‡±NL_77 |18.59Mb
  - ğŸ‡µğŸ‡±PL_68 |18.17Mb
  - ğŸ‡µğŸ‡±PL_60 |101.49Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - ğŸ‡¨ğŸ‡¦CA_10 |16.34Mb
  - disney_GB |54.28Mb
  - _06 |38.15Mb
  - disney_GB |21.76Mb
  - disney_GB |10.03Mb
  - ğŸ‡©ğŸ‡ªDE_19 |21.71Mb
  - ğŸ‡«ğŸ‡®FI_35 |10.11Mb
  - ğŸ‡ªğŸ‡¸ES_30 |10.54Mb
  - ğŸ‡ªğŸ‡¸ES_24 |16.81Mb
  - _08 |12.73Mb
  - ğŸ‡ºğŸ‡¸US_84 |19.30Mb
  - ğŸ‡ºğŸ‡¸US_90 |894.88Mb
  - disney_US |180.15Mb
  - disney_GB |19.94Mb
  - disney_US |110.71Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡²ğŸ‡©MD_78 |12.18Mb
  - ğŸ‡ºğŸ‡¸US_80 |15.14Mb
  - disney_US |14.83Mb
  - disney_US |447.61Mb
  - disney_US |70.03Mb
  - disney_US |319.36Mb
  - disney_GB |19.17Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡³ğŸ‡±NL_77 |18.59Mb
  - ğŸ‡µğŸ‡±PL_68 |18.17Mb
  - ğŸ‡µğŸ‡±PL_60 |101.49Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
