port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: ğŸ‡¨ğŸ‡¦CA_75 |221.37Mb
  server: 137.184.174.93
  type: ss
  country: ğŸ‡¨ğŸ‡¦CA
  port: 8080
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: ğŸ‡¨ğŸ‡¦CA_76 |22.61Mb
  server: 134.195.198.147
  type: vmess
  country: ğŸ‡¨ğŸ‡¦CA
  port: 443
  uuid: 03fcc618-b93d-6796-6aed-8a38c975d581
  alterId: 0
  cipher: auto
  network: ws
  servername: inna.cfd
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /linkvws
    headers:
      HOST: inna.cfd
- name: _56 |38.15Mb
  server: 62.100.205.100
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _70 |12.64Mb
  server: 94.156.250.122
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡©ğŸ‡ªDE_82 |186.88Mb
  server: 81.19.141.45
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 443
  password: AbMSHUmd0GGSUVH1pdgKk5
  cipher: chacha20-ietf-poly1305
- name: _59 |13.73Mb
  server: 38.165.231.25
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _55 |10.50Mb
  server: 185.163.204.94
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _60 |12.23Mb
  server: 91.219.237.163
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡©ğŸ‡ªDE_93 |32.63Mb
  server: 81.19.141.45
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 443
  password: 0dEg9sKUtuROxn3zaNogzU
  cipher: chacha20-ietf-poly1305
- name: Relay_-ğŸ‡³ğŸ‡±NL_47 |10.15Mb
  server: 193.135.174.135
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡©ğŸ‡ªDE_100 |17.76Mb
  server: 3.123.25.149
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: _61 |31.20Mb
  server: 185.93.173.60
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡©ğŸ‡ªDE_116 |56.25Mb
  server: 81.19.141.45
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 443
  password: EEIh3YZZ5QZRvJM6C04YSM
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ªğŸ‡¸ES_138 |109.52Mb
  server: 194.87.45.189
  type: ss
  country: ğŸ‡ªğŸ‡¸ES
  port: 443
  password: jiMMLSYwAagbBvDq511rG3
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_152 |146.36Mb
  server: 78.129.140.11
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: DpBNt4YF9cIcVnWOcJqRgy
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_154 |19.17Mb
  server: 89.185.84.185
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: FXjMQIem0uShGvRzOpfyib
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_157 |18.17Mb
  server: 89.185.84.185
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: gbCXg98Ecfx15al9somp9w
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_159 |47.38Mb
  server: 18.169.158.38
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡¬ğŸ‡§GB_162 |36.63Mb
  server: 3.8.172.214
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡ªğŸ‡¸ES_139 |10.54Mb
  server: 194.87.45.189
  type: ss
  country: ğŸ‡ªğŸ‡¸ES
  port: 443
  password: 676zALNF1CckrwJ6HGjRKl
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_170 |20.44Mb
  server: 89.185.84.185
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: iEc68ruj1qOx8hjh1KWZmc
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_174 |54.28Mb
  server: 89.185.84.185
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: WhUYn0yZ6bLrILxzItfxSI
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_177 |20.83Mb
  server: 89.185.84.185
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: tVBUTDznmHpV3lpKzbw2Nl
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_178 |13.97Mb
  server: 89.185.84.185
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: IP77QXJz3YEA90m7miLOBu
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡®ğŸ‡¶IQ_184 |108.26Mb
  server: 81.90.31.219
  type: ss
  country: ğŸ‡®ğŸ‡¶IQ
  port: 443
  password: K1pen0J1phNGHMrxq2wK4a
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡®ğŸ‡¶IQ_191 |11.75Mb
  server: 81.90.31.219
  type: ss
  country: ğŸ‡®ğŸ‡¶IQ
  port: 443
  password: WMTeArYUJWgbvJ2w9SzMP1
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡®ğŸ‡¶IQ_187 |84.77Mb
  server: 81.90.31.219
  type: ss
  country: ğŸ‡®ğŸ‡¶IQ
  port: 443
  password: x947cWmxf2K4fNFElbxHdk
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡®ğŸ‡¶IQ_200 |124.59Mb
  server: 81.90.31.219
  type: ss
  country: ğŸ‡®ğŸ‡¶IQ
  port: 443
  password: KNcDGVv48KtCCtWpc7f9Ak
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡®ğŸ‡¶IQ_201 |11.40Mb
  server: 81.90.31.219
  type: ss
  country: ğŸ‡®ğŸ‡¶IQ
  port: 443
  password: 4dTgWe7yyli0t1tF0hU06C
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡®ğŸ‡¶IQ_206 |46.51Mb
  server: 81.90.31.219
  type: ss
  country: ğŸ‡®ğŸ‡¶IQ
  port: 443
  password: gRVbi5I3cGA7rPA2aFOmOq
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡®ğŸ‡¶IQ_210 |49.18Mb
  server: 81.90.31.219
  type: ss
  country: ğŸ‡®ğŸ‡¶IQ
  port: 443
  password: mKvt7CQhT6eUntXD5iB0ke
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡®ğŸ‡¶IQ_211 |48.98Mb
  server: 81.90.31.219
  type: ss
  country: ğŸ‡®ğŸ‡¶IQ
  port: 443
  password: iRZgNTcrf657aaZpPkCFWu
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_227 |18.00Mb
  server: 45.87.175.22
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_226 |10.88Mb
  server: 45.87.175.164
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: 1RWwXhwfAB5gAEozU4G2Pg
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_232 |19.83Mb
  server: 45.87.175.167
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_234 |13.37Mb
  server: 45.87.175.181
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: 4a2rfixophdjffa8KVA4Aa
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_236 |10.13Mb
  server: 45.87.175.171
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: 1RWwXhwfAB5gAEozU4G2Pg
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡³ğŸ‡±NL_242 |41.17Mb
  server: 193.29.139.143
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 8080
  password: 1RWwXhwfAB5gAEozU4G2Pg
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_309 |10.44Mb
  server: 3.141.46.88
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡ºğŸ‡¸US_310 |21.18Mb
  server: 3.137.215.129
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡¯ğŸ‡µJP_219 |11.49Mb
  server: 45.32.45.45
  type: vmess
  country: ğŸ‡¯ğŸ‡µJP
  port: 14760
  uuid: dbf7a6e4-d518-4f9b-a55e-27ef892ffac1
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡ºğŸ‡¸US_313 |37.95Mb
  server: 13.59.110.241
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡ºğŸ‡¸US_317 |15.14Mb
  server: 18.224.70.173
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡²ğŸ‡©MD_326 |10.94Mb
  server: 23.95.76.147
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡²ğŸ‡©MD_327 |12.18Mb
  server: 23.95.76.59
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡³ğŸ‡±NL_243 |11.77Mb
  server: 193.29.139.177
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 8080
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_331 |11.46Mb
  server: 66.23.207.82
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡µğŸ‡±PL_265 |18.17Mb
  server: 77.83.246.74
  type: ss
  country: ğŸ‡µğŸ‡±PL
  port: 443
  password: 0fV7k5wmlkPk2TNmx22rCQ
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_338 |447.61Mb
  server: 193.124.24.247
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 6508
  uuid: b68fead5-5b0b-43a1-c34a-804467f0f368
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡¸ğŸ‡°SK_304 |11.11Mb
  server: 193.37.255.38
  type: ss
  country: ğŸ‡¸ğŸ‡°SK
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡³ğŸ‡±NL_325 |18.59Mb
  server: 45.158.171.70
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 8080
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_341 |319.36Mb
  server: 193.124.24.247
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 6507
  uuid: 3003e094-707c-4dbb-faca-4b8d579bc604
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡ºğŸ‡¸US_332 |19.30Mb
  server: 38.91.102.40
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 5003
  password: g5MeD6Ft3CWlJId
  cipher: aes-256-gcm
- name: ğŸ‡ºğŸ‡¸US_337 |14.83Mb
  server: 154.29.158.139
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 12299
  uuid: cccfe679-fbd0-4402-caf2-67e919db436f
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡ºğŸ‡¸US_339 |894.88Mb
  server: 142.171.237.17
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 1988
  uuid: aed0feeb-1283-4b7d-b3a4-71ef038d59af
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_342 |249.77Mb
  server: 193.124.24.247
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 6515
  uuid: 2f3c646a-37f3-483a-a2a5-6bc1c5e526ae
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡·ğŸ‡ºRU_288 |41.28Mb
  server: 5.129.201.43
  type: ss
  country: ğŸ‡·ğŸ‡ºRU
  port: 23256
  password: yALtyAtHfbw1Vu4pqh6wUc
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¸ğŸ‡¨SC_291 |17.60Mb
  server: 154.205.153.107
  type: ss
  country: ğŸ‡¸ğŸ‡¨SC
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_344 |70.03Mb
  server: 193.124.24.247
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 6514
  uuid: c362d735-01a8-48eb-baa2-ae7aa63bfdc3
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_345 |110.71Mb
  server: 193.124.24.247
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 6504
  uuid: 7ceb165c-9aff-4ab7-ce9e-1df31a5ed911
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Pool_ğŸ‡ºğŸ‡¸US_346 |19.97Mb
  server: 165.140.216.141
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  uuid: e7d72a8d-26f2-4b54-b366-0c43e0bcba7d
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Pool_ğŸ‡­ğŸ‡°HK_180 |433.00Mb
  server: 150.107.46.21
  type: ssr
  country: ğŸ‡­ğŸ‡°HK
  port: 8083
  password: iFqnzSscN
  cipher: aes-256-cfb
  protocol: origin
  obfs: tls1.2_ticket_auth
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - ğŸ‡¨ğŸ‡¦CA_75 |221.37Mb
  - ğŸ‡¨ğŸ‡¦CA_76 |22.61Mb
  - _56 |38.15Mb
  - _70 |12.64Mb
  - ğŸ‡©ğŸ‡ªDE_82 |186.88Mb
  - _59 |13.73Mb
  - _55 |10.50Mb
  - _60 |12.23Mb
  - ğŸ‡©ğŸ‡ªDE_93 |32.63Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_47 |10.15Mb
  - ğŸ‡©ğŸ‡ªDE_100 |17.76Mb
  - _61 |31.20Mb
  - ğŸ‡©ğŸ‡ªDE_116 |56.25Mb
  - ğŸ‡ªğŸ‡¸ES_138 |109.52Mb
  - ğŸ‡¬ğŸ‡§GB_152 |146.36Mb
  - ğŸ‡¬ğŸ‡§GB_154 |19.17Mb
  - ğŸ‡¬ğŸ‡§GB_157 |18.17Mb
  - ğŸ‡¬ğŸ‡§GB_159 |47.38Mb
  - ğŸ‡¬ğŸ‡§GB_162 |36.63Mb
  - ğŸ‡ªğŸ‡¸ES_139 |10.54Mb
  - ğŸ‡¬ğŸ‡§GB_170 |20.44Mb
  - ğŸ‡¬ğŸ‡§GB_174 |54.28Mb
  - ğŸ‡¬ğŸ‡§GB_177 |20.83Mb
  - ğŸ‡¬ğŸ‡§GB_178 |13.97Mb
  - ğŸ‡®ğŸ‡¶IQ_184 |108.26Mb
  - ğŸ‡®ğŸ‡¶IQ_191 |11.75Mb
  - ğŸ‡®ğŸ‡¶IQ_187 |84.77Mb
  - ğŸ‡®ğŸ‡¶IQ_200 |124.59Mb
  - ğŸ‡®ğŸ‡¶IQ_201 |11.40Mb
  - ğŸ‡®ğŸ‡¶IQ_206 |46.51Mb
  - ğŸ‡®ğŸ‡¶IQ_210 |49.18Mb
  - ğŸ‡®ğŸ‡¶IQ_211 |48.98Mb
  - ğŸ‡±ğŸ‡¹LT_227 |18.00Mb
  - ğŸ‡±ğŸ‡¹LT_226 |10.88Mb
  - ğŸ‡±ğŸ‡¹LT_232 |19.83Mb
  - ğŸ‡±ğŸ‡¹LT_234 |13.37Mb
  - ğŸ‡±ğŸ‡¹LT_236 |10.13Mb
  - ğŸ‡³ğŸ‡±NL_242 |41.17Mb
  - ğŸ‡ºğŸ‡¸US_309 |10.44Mb
  - ğŸ‡ºğŸ‡¸US_310 |21.18Mb
  - ğŸ‡¯ğŸ‡µJP_219 |11.49Mb
  - ğŸ‡ºğŸ‡¸US_313 |37.95Mb
  - ğŸ‡ºğŸ‡¸US_317 |15.14Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡²ğŸ‡©MD_326 |10.94Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡²ğŸ‡©MD_327 |12.18Mb
  - ğŸ‡³ğŸ‡±NL_243 |11.77Mb
  - ğŸ‡ºğŸ‡¸US_331 |11.46Mb
  - ğŸ‡µğŸ‡±PL_265 |18.17Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_338 |447.61Mb
  - ğŸ‡¸ğŸ‡°SK_304 |11.11Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡³ğŸ‡±NL_325 |18.59Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_341 |319.36Mb
  - ğŸ‡ºğŸ‡¸US_332 |19.30Mb
  - ğŸ‡ºğŸ‡¸US_337 |14.83Mb
  - ğŸ‡ºğŸ‡¸US_339 |894.88Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_342 |249.77Mb
  - ğŸ‡·ğŸ‡ºRU_288 |41.28Mb
  - ğŸ‡¸ğŸ‡¨SC_291 |17.60Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_344 |70.03Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_345 |110.71Mb
  - Pool_ğŸ‡ºğŸ‡¸US_346 |19.97Mb
  - Pool_ğŸ‡­ğŸ‡°HK_180 |433.00Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - ğŸ‡¨ğŸ‡¦CA_75 |221.37Mb
  - ğŸ‡¨ğŸ‡¦CA_76 |22.61Mb
  - _56 |38.15Mb
  - _70 |12.64Mb
  - ğŸ‡©ğŸ‡ªDE_82 |186.88Mb
  - _59 |13.73Mb
  - _55 |10.50Mb
  - _60 |12.23Mb
  - ğŸ‡©ğŸ‡ªDE_93 |32.63Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_47 |10.15Mb
  - ğŸ‡©ğŸ‡ªDE_100 |17.76Mb
  - _61 |31.20Mb
  - ğŸ‡©ğŸ‡ªDE_116 |56.25Mb
  - ğŸ‡ªğŸ‡¸ES_138 |109.52Mb
  - ğŸ‡¬ğŸ‡§GB_152 |146.36Mb
  - ğŸ‡¬ğŸ‡§GB_154 |19.17Mb
  - ğŸ‡¬ğŸ‡§GB_157 |18.17Mb
  - ğŸ‡¬ğŸ‡§GB_159 |47.38Mb
  - ğŸ‡¬ğŸ‡§GB_162 |36.63Mb
  - ğŸ‡ªğŸ‡¸ES_139 |10.54Mb
  - ğŸ‡¬ğŸ‡§GB_170 |20.44Mb
  - ğŸ‡¬ğŸ‡§GB_174 |54.28Mb
  - ğŸ‡¬ğŸ‡§GB_177 |20.83Mb
  - ğŸ‡¬ğŸ‡§GB_178 |13.97Mb
  - ğŸ‡®ğŸ‡¶IQ_184 |108.26Mb
  - ğŸ‡®ğŸ‡¶IQ_191 |11.75Mb
  - ğŸ‡®ğŸ‡¶IQ_187 |84.77Mb
  - ğŸ‡®ğŸ‡¶IQ_200 |124.59Mb
  - ğŸ‡®ğŸ‡¶IQ_201 |11.40Mb
  - ğŸ‡®ğŸ‡¶IQ_206 |46.51Mb
  - ğŸ‡®ğŸ‡¶IQ_210 |49.18Mb
  - ğŸ‡®ğŸ‡¶IQ_211 |48.98Mb
  - ğŸ‡±ğŸ‡¹LT_227 |18.00Mb
  - ğŸ‡±ğŸ‡¹LT_226 |10.88Mb
  - ğŸ‡±ğŸ‡¹LT_232 |19.83Mb
  - ğŸ‡±ğŸ‡¹LT_234 |13.37Mb
  - ğŸ‡±ğŸ‡¹LT_236 |10.13Mb
  - ğŸ‡³ğŸ‡±NL_242 |41.17Mb
  - ğŸ‡ºğŸ‡¸US_309 |10.44Mb
  - ğŸ‡ºğŸ‡¸US_310 |21.18Mb
  - ğŸ‡¯ğŸ‡µJP_219 |11.49Mb
  - ğŸ‡ºğŸ‡¸US_313 |37.95Mb
  - ğŸ‡ºğŸ‡¸US_317 |15.14Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡²ğŸ‡©MD_326 |10.94Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡²ğŸ‡©MD_327 |12.18Mb
  - ğŸ‡³ğŸ‡±NL_243 |11.77Mb
  - ğŸ‡ºğŸ‡¸US_331 |11.46Mb
  - ğŸ‡µğŸ‡±PL_265 |18.17Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_338 |447.61Mb
  - ğŸ‡¸ğŸ‡°SK_304 |11.11Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡³ğŸ‡±NL_325 |18.59Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_341 |319.36Mb
  - ğŸ‡ºğŸ‡¸US_332 |19.30Mb
  - ğŸ‡ºğŸ‡¸US_337 |14.83Mb
  - ğŸ‡ºğŸ‡¸US_339 |894.88Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_342 |249.77Mb
  - ğŸ‡·ğŸ‡ºRU_288 |41.28Mb
  - ğŸ‡¸ğŸ‡¨SC_291 |17.60Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_344 |70.03Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_345 |110.71Mb
  - Pool_ğŸ‡ºğŸ‡¸US_346 |19.97Mb
  - Pool_ğŸ‡­ğŸ‡°HK_180 |433.00Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
