port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: ğŸ‡¨ğŸ‡¦CA_47 |16.34Mb
  server: 138.197.153.10
  type: ss
  country: ğŸ‡¨ğŸ‡¦CA
  port: 8080
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: ğŸ‡¨ğŸ‡¦CA_45 |221.37Mb
  server: 137.184.174.93
  type: ss
  country: ğŸ‡¨ğŸ‡¦CA
  port: 8080
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: Relay_ğŸ‡¨ğŸ‡¦CA-ğŸ‡¨ğŸ‡¦CA_51 |735.00Mb
  server: ssca.irundns.net
  type: ssr
  country: ğŸ‡¨ğŸ‡¦CA
  port: 443
  password: $$Turb0VPN$$
  cipher: aes-128-cfb
  protocol: auth_aes128_md5
  obfs: http_post
- name: _28 |36.56Mb
  server: 94.156.250.122
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _31 |38.15Mb
  server: 62.100.205.100
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: disney_MX |10.37Mb
  server: 38.165.231.25
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¦ğŸ‡¹AT_44 |11.80Mb
  server: 37.235.56.69
  type: ss
  country: ğŸ‡¦ğŸ‡¹AT
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _35 |13.16Mb
  server: 176.126.83.158
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _30 |12.73Mb
  server: 185.237.185.89
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¨ğŸ‡¾CY_54 |43.16Mb
  server: 91.148.135.31
  type: ss
  country: ğŸ‡¨ğŸ‡¾CY
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _40 |31.20Mb
  server: 185.93.173.60
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: disney_GB |53.98Mb
  server: 89.185.84.185
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: B2ISJ3faDXlkRUXUeQu182
  cipher: chacha20-ietf-poly1305
- name: disney_GB |19.94Mb
  server: 89.185.84.185
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: Qqt1DFQEMvj6oJ69n6uf1Z
  cipher: chacha20-ietf-poly1305
- name: disney_GB |20.83Mb
  server: 89.185.84.185
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: tVBUTDznmHpV3lpKzbw2Nl
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¨ğŸ‡¿CZ_56 |29.46Mb
  server: 185.193.102.7
  type: ss
  country: ğŸ‡¨ğŸ‡¿CZ
  port: 57456
  password: 360e21d21977dc11
  cipher: chacha20-ietf-poly1305
- name: disney_GB |10.05Mb
  server: 89.185.84.185
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: ozSHXLRuO7JckCvhgLjLaU
  cipher: chacha20-ietf-poly1305
- name: disney_GB |13.97Mb
  server: 89.185.84.185
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: IP77QXJz3YEA90m7miLOBu
  cipher: chacha20-ietf-poly1305
- name: disney_GB |18.62Mb
  server: 89.185.84.185
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: 5cX4v5smGo5hJR6HBDGz4E
  cipher: chacha20-ietf-poly1305
- name: disney_GB |21.76Mb
  server: 89.185.84.185
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: teojx0gaa5ctzJ7m0VoXky
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡®ğŸ‡¶IQ_117 |48.98Mb
  server: 81.90.31.219
  type: ss
  country: ğŸ‡®ğŸ‡¶IQ
  port: 443
  password: iRZgNTcrf657aaZpPkCFWu
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_140 |12.05Mb
  server: 45.87.175.188
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_194 |52.48Mb
  server: 3.22.249.200
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡®ğŸ‡¶IQ_118 |40.33Mb
  server: 81.90.31.219
  type: ss
  country: ğŸ‡®ğŸ‡¶IQ
  port: 443
  password: 4dTgWe7yyli0t1tF0hU06C
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡®ğŸ‡¶IQ_120 |15.56Mb
  server: 81.90.31.219
  type: ss
  country: ğŸ‡®ğŸ‡¶IQ
  port: 443
  password: x1BnwqAKnwOyejb1qJoPby
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_197 |50.06Mb
  server: 18.224.33.22
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: disney_RU |46.51Mb
  server: 81.90.31.219
  type: ss
  country: ğŸ‡®ğŸ‡¶IQ
  port: 443
  password: gRVbi5I3cGA7rPA2aFOmOq
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡³ğŸ‡±NL_145 |13.85Mb
  server: 193.29.139.184
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 8080
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_209 |11.46Mb
  server: 66.23.207.82
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡®ğŸ‡¶IQ_126 |98.31Mb
  server: 81.90.31.219
  type: ss
  country: ğŸ‡®ğŸ‡¶IQ
  port: 443
  password: hqrlGzhiiNdQl2fvcWvEVR
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_203 |16.26Mb
  server: 3.129.21.37
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡ºğŸ‡¸US_211 |52.46Mb
  server: 3.149.246.131
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡ºğŸ‡¸US_212 |37.95Mb
  server: 13.59.110.241
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡ºğŸ‡¸US_214 |10.44Mb
  server: 3.141.46.88
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡ºğŸ‡¸US_216 |16.85Mb
  server: 3.135.220.55
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: Pool_ğŸ‡­ğŸ‡°HK_113 |183.00Mb
  server: 150.107.46.21
  type: ssr
  country: ğŸ‡­ğŸ‡°HK
  port: 8083
  password: iFqnzSscN
  cipher: aes-256-cfb
  protocol: origin
  obfs: tls1.2_ticket_auth
- name: ğŸ‡ºğŸ‡¸US_199 |19.30Mb
  server: 38.91.102.40
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 5003
  password: g5MeD6Ft3CWlJId
  cipher: aes-256-gcm
- name: disney_US |86.85Mb
  server: 193.124.24.247
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 6511
  uuid: 5ef4e89b-262f-4c74-e793-c7332079f251
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_US |213.25Mb
  server: 193.124.24.247
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 6506
  uuid: c53d41d1-7d56-43ce-9994-408780c6476a
  alterId: 0
  cipher: auto
  network: tcp
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_US |110.71Mb
  server: 193.124.24.247
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 6504
  uuid: 7ceb165c-9aff-4ab7-ce9e-1df31a5ed911
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_US |319.36Mb
  server: 193.124.24.247
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 6507
  uuid: 3003e094-707c-4dbb-faca-4b8d579bc604
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡³ğŸ‡±NL_195 |18.59Mb
  server: 45.158.171.70
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 8080
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_206 |16.12Mb
  server: 38.244.136.233
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: dAHM1pm8ag7KdlrUylQi6t
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¸ğŸ‡¨SC_181 |17.60Mb
  server: 154.205.153.107
  type: ss
  country: ğŸ‡¸ğŸ‡¨SC
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _42 |14.19Mb
  server: 91.219.237.163
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: disney_RU |108.77Mb
  server: 81.90.31.219
  type: ss
  country: ğŸ‡®ğŸ‡¶IQ
  port: 443
  password: 4P08VhCtfXszlSCcu8CwF8
  cipher: chacha20-ietf-poly1305
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - ğŸ‡¨ğŸ‡¦CA_47 |16.34Mb
  - ğŸ‡¨ğŸ‡¦CA_45 |221.37Mb
  - Relay_ğŸ‡¨ğŸ‡¦CA-ğŸ‡¨ğŸ‡¦CA_51 |735.00Mb
  - _28 |36.56Mb
  - _31 |38.15Mb
  - disney_MX |10.37Mb
  - ğŸ‡¦ğŸ‡¹AT_44 |11.80Mb
  - _35 |13.16Mb
  - _30 |12.73Mb
  - ğŸ‡¨ğŸ‡¾CY_54 |43.16Mb
  - _40 |31.20Mb
  - disney_GB |53.98Mb
  - disney_GB |19.94Mb
  - disney_GB |20.83Mb
  - ğŸ‡¨ğŸ‡¿CZ_56 |29.46Mb
  - disney_GB |10.05Mb
  - disney_GB |13.97Mb
  - disney_GB |18.62Mb
  - disney_GB |21.76Mb
  - ğŸ‡®ğŸ‡¶IQ_117 |48.98Mb
  - ğŸ‡±ğŸ‡¹LT_140 |12.05Mb
  - ğŸ‡ºğŸ‡¸US_194 |52.48Mb
  - ğŸ‡®ğŸ‡¶IQ_118 |40.33Mb
  - ğŸ‡®ğŸ‡¶IQ_120 |15.56Mb
  - ğŸ‡ºğŸ‡¸US_197 |50.06Mb
  - disney_RU |46.51Mb
  - ğŸ‡³ğŸ‡±NL_145 |13.85Mb
  - ğŸ‡ºğŸ‡¸US_209 |11.46Mb
  - ğŸ‡®ğŸ‡¶IQ_126 |98.31Mb
  - ğŸ‡ºğŸ‡¸US_203 |16.26Mb
  - ğŸ‡ºğŸ‡¸US_211 |52.46Mb
  - ğŸ‡ºğŸ‡¸US_212 |37.95Mb
  - ğŸ‡ºğŸ‡¸US_214 |10.44Mb
  - ğŸ‡ºğŸ‡¸US_216 |16.85Mb
  - Pool_ğŸ‡­ğŸ‡°HK_113 |183.00Mb
  - ğŸ‡ºğŸ‡¸US_199 |19.30Mb
  - disney_US |86.85Mb
  - disney_US |213.25Mb
  - disney_US |110.71Mb
  - disney_US |319.36Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡³ğŸ‡±NL_195 |18.59Mb
  - ğŸ‡ºğŸ‡¸US_206 |16.12Mb
  - ğŸ‡¸ğŸ‡¨SC_181 |17.60Mb
  - _42 |14.19Mb
  - disney_RU |108.77Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - ğŸ‡¨ğŸ‡¦CA_47 |16.34Mb
  - ğŸ‡¨ğŸ‡¦CA_45 |221.37Mb
  - Relay_ğŸ‡¨ğŸ‡¦CA-ğŸ‡¨ğŸ‡¦CA_51 |735.00Mb
  - _28 |36.56Mb
  - _31 |38.15Mb
  - disney_MX |10.37Mb
  - ğŸ‡¦ğŸ‡¹AT_44 |11.80Mb
  - _35 |13.16Mb
  - _30 |12.73Mb
  - ğŸ‡¨ğŸ‡¾CY_54 |43.16Mb
  - _40 |31.20Mb
  - disney_GB |53.98Mb
  - disney_GB |19.94Mb
  - disney_GB |20.83Mb
  - ğŸ‡¨ğŸ‡¿CZ_56 |29.46Mb
  - disney_GB |10.05Mb
  - disney_GB |13.97Mb
  - disney_GB |18.62Mb
  - disney_GB |21.76Mb
  - ğŸ‡®ğŸ‡¶IQ_117 |48.98Mb
  - ğŸ‡±ğŸ‡¹LT_140 |12.05Mb
  - ğŸ‡ºğŸ‡¸US_194 |52.48Mb
  - ğŸ‡®ğŸ‡¶IQ_118 |40.33Mb
  - ğŸ‡®ğŸ‡¶IQ_120 |15.56Mb
  - ğŸ‡ºğŸ‡¸US_197 |50.06Mb
  - disney_RU |46.51Mb
  - ğŸ‡³ğŸ‡±NL_145 |13.85Mb
  - ğŸ‡ºğŸ‡¸US_209 |11.46Mb
  - ğŸ‡®ğŸ‡¶IQ_126 |98.31Mb
  - ğŸ‡ºğŸ‡¸US_203 |16.26Mb
  - ğŸ‡ºğŸ‡¸US_211 |52.46Mb
  - ğŸ‡ºğŸ‡¸US_212 |37.95Mb
  - ğŸ‡ºğŸ‡¸US_214 |10.44Mb
  - ğŸ‡ºğŸ‡¸US_216 |16.85Mb
  - Pool_ğŸ‡­ğŸ‡°HK_113 |183.00Mb
  - ğŸ‡ºğŸ‡¸US_199 |19.30Mb
  - disney_US |86.85Mb
  - disney_US |213.25Mb
  - disney_US |110.71Mb
  - disney_US |319.36Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡³ğŸ‡±NL_195 |18.59Mb
  - ğŸ‡ºğŸ‡¸US_206 |16.12Mb
  - ğŸ‡¸ğŸ‡¨SC_181 |17.60Mb
  - _42 |14.19Mb
  - disney_RU |108.77Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
