port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: _126 |19.69Mb
  server: 173.234.29.2
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _137 |53.58Mb
  server: 185.82.73.212
  type: ss
  port: 8444
  udp: true
  password: _bypfvq6ra7g4n5yCCR9DoVeGya2XUUS
  cipher: chacha20-ietf-poly1305
- name: netflix_NL |11.33Mb
  server: 45.87.175.28
  type: ss
  port: 8080
  udp: true
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: netflix_DE |40.87Mb
  server: 194.59.183.134
  type: ss
  port: 46114
  udp: true
  password: lejSRyqa033OEPmEQsvRsl
  cipher: chacha20-ietf-poly1305
- name: _129 |481.95Mb
  server: 46.183.184.60
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: _131 |29.70Mb
  server: pupas-shirting-unsung.freesocks.work
  type: ss
  port: 443
  udp: true
  password: p78naCf2EfOlRSLTX0wFVx
  cipher: chacha20-ietf-poly1305
- name: disney_PY |115.61Mb
  server: 38.165.233.93
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: disney_HK |11.92Mb
  server: 103.149.183.191
  type: ss
  port: 8388
  password: asd123456
  cipher: chacha20-ietf
- name: _133 |26.73Mb
  server: 103.149.182.86
  type: ss
  port: 8388
  udp: true
  password: asd123456
  cipher: chacha20-ietf
- name: _150 |162.06Mb
  server: 47.242.145.160
  type: vmess
  port: 44457
  uuid: 40290609-2743-4d85-c9c3-4c72dd151b9f
  alterId: 0
  cipher: auto
  network: http
  http-opts:
    method: GET
    path:
    - /
  h2-opts: {}
- name: disney_HK |10.79Mb
  server: 149.88.95.94
  type: vmess
  port: 40741
  uuid: 1b8a751b-4909-4fec-f019-907d92e6c47f
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
- name: disney_HK |115.46Mb
  server: 149.88.95.94
  type: vmess
  port: 18937
  uuid: ebaa1ae1-fa4d-40d8-958f-d4524d551218
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
- name: _167 |10.76Mb
  server: 160.16.131.243
  type: trojan
  port: 2760
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
  skip-cert-verify: true
- name: Relay_-ğŸ‡­ğŸ‡°HK_145 |53.04Mb
  server: v10.hdacd.com
  type: vmess
  port: 30807
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _168 |44.05Mb
  server: 160.16.136.130
  type: trojan
  port: 2890
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: _170 |40.37Mb
  server: 160.16.204.136
  type: trojan
  port: 2890
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡ºğŸ‡¸US_158 |47.77Mb
  server: v24.hdacd.com
  type: vmess
  port: 30824
  udp: true
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_-ğŸ‡¯ğŸ‡µJP_171 |20.02Mb
  server: 160.16.72.33
  type: trojan
  port: 3093
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¯ğŸ‡µJP_173 |22.49Mb
  server: 160.16.117.182
  type: trojan
  port: 3169
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: _174 |10.10Mb
  server: 160.16.116.227
  type: trojan
  port: 2760
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
  skip-cert-verify: true
- name: Relay_-ğŸ‡ºğŸ‡¸US_163 |10.34Mb
  server: cdnfire.xiaomispeed.com
  type: trojan
  port: 21104
  udp: true
  password: 2659b686-43f8-4924-a143-349bc07aea93
  sni: cdnfire.xiaomispeed.com
  skip-cert-verify: true
- name: Relay_-ğŸ‡¯ğŸ‡µJP_175 |12.59Mb
  server: 160.16.117.182
  type: trojan
  port: 3093
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: netflix_NO |30.30Mb
  server: 185.213.23.63
  type: ss
  country: ğŸ‡¨ğŸ‡¦CA
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: netflix_JP |11.24Mb
  server: 153.121.45.139
  type: trojan
  port: 3093
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: disney_DE |198.50Mb
  server: 89.163.140.136
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: netflix_NL |51.12Mb
  server: 82.38.31.208
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: netflix_NL |121.05Mb
  server: 45.87.175.180
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: QCXDxuDlTTMD7jtgHUjIoj
  cipher: chacha20-ietf-poly1305
- name: disney_HK |77.03Mb
  server: 219.79.214.159
  type: trojan
  port: 443
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: netflix_IT |18.43Mb
  server: 176.126.83.121
  type: ss
  country: ğŸ‡®ğŸ‡¹IT
  port: 443
  password: Q4t8T7hEYY3mD2Fn4wnxyK4X35AUzvR8
  cipher: chacha20-ietf-poly1305
- name: netflix_NL |112.52Mb
  server: 45.87.175.183
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡²ğŸ‡½MX_204 |41.28Mb
  server: 216.238.87.47
  type: vmess
  country: ğŸ‡²ğŸ‡½MX
  port: 27502
  uuid: b8155ce4-7e08-4c40-800f-8671312b7124
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: netflix_NL |107.53Mb
  server: 45.87.175.185
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: Relay_-ğŸ‡­ğŸ‡°HK_172 |10.28Mb
  server: cdnfire.xiaomispeed.com
  type: trojan
  port: 21102
  udp: true
  password: 2659b686-43f8-4924-a143-349bc07aea93
  sni: cdnfire.xiaomispeed.com
  skip-cert-verify: true
- name: ğŸ‡±ğŸ‡¹LT_203 |104.84Mb
  server: 45.87.175.185
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: disney_HK |103.02Mb
  server: 45.207.157.29
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 13852
  uuid: 845764df-ecb3-4b13-bed2-bf1551b68e9a
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡­ğŸ‡°HK_188 |103.85Mb
  server: 8.218.105.196
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 52752
  uuid: 925bdbf5-72be-4437-bebf-441c61089f6b
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_214 |41.13Mb
  server: 38.14.99.163
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 59807
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: auto
  network: tcp
  servername: 38.14.99.163
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: netflix_PT |70.40Mb
  server: 185.113.143.186
  type: ss
  country: ğŸ‡µğŸ‡¹PT
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_US |16.91Mb
  server: gy3.hdcloud.link
  type: trojan
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  udp: true
  password: 168f29a7-6922-4558-8296-61a69cf6a5a2
  network: grpc
  grpc-opts:
    grpc-service-name: GunService
- name: ğŸ‡¸ğŸ‡¬SG_212 |21.45Mb
  server: 68.183.227.45
  type: ss
  country: ğŸ‡¸ğŸ‡¬SG
  port: 8080
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: ğŸ ZZ_217 |144.36Mb
  server: 185.231.233.112
  type: ss
  country: ğŸ ZZ
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: netflix_NL |51.64Mb
  server: 45.14.245.2
  type: ss
  port: 443
  password: 17ZDORWIliQHuO6WRGHChXYMzdRtAYVP
  cipher: chacha20-ietf-poly1305
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - _126 |19.69Mb
  - _137 |53.58Mb
  - netflix_NL |11.33Mb
  - netflix_DE |40.87Mb
  - _129 |481.95Mb
  - _131 |29.70Mb
  - disney_PY |115.61Mb
  - disney_HK |11.92Mb
  - _133 |26.73Mb
  - _150 |162.06Mb
  - disney_HK |10.79Mb
  - disney_HK |115.46Mb
  - _167 |10.76Mb
  - Relay_-ğŸ‡­ğŸ‡°HK_145 |53.04Mb
  - _168 |44.05Mb
  - _170 |40.37Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_158 |47.77Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_171 |20.02Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_173 |22.49Mb
  - _174 |10.10Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_163 |10.34Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_175 |12.59Mb
  - netflix_NO |30.30Mb
  - netflix_JP |11.24Mb
  - disney_DE |198.50Mb
  - netflix_NL |51.12Mb
  - netflix_NL |121.05Mb
  - disney_HK |77.03Mb
  - netflix_IT |18.43Mb
  - netflix_NL |112.52Mb
  - ğŸ‡²ğŸ‡½MX_204 |41.28Mb
  - netflix_NL |107.53Mb
  - Relay_-ğŸ‡­ğŸ‡°HK_172 |10.28Mb
  - ğŸ‡±ğŸ‡¹LT_203 |104.84Mb
  - disney_HK |103.02Mb
  - ğŸ‡­ğŸ‡°HK_188 |103.85Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_214 |41.13Mb
  - netflix_PT |70.40Mb
  - disney_netflix_US |16.91Mb
  - ğŸ‡¸ğŸ‡¬SG_212 |21.45Mb
  - ğŸ ZZ_217 |144.36Mb
  - netflix_NL |51.64Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - _126 |19.69Mb
  - _137 |53.58Mb
  - netflix_NL |11.33Mb
  - netflix_DE |40.87Mb
  - _129 |481.95Mb
  - _131 |29.70Mb
  - disney_PY |115.61Mb
  - disney_HK |11.92Mb
  - _133 |26.73Mb
  - _150 |162.06Mb
  - disney_HK |10.79Mb
  - disney_HK |115.46Mb
  - _167 |10.76Mb
  - Relay_-ğŸ‡­ğŸ‡°HK_145 |53.04Mb
  - _168 |44.05Mb
  - _170 |40.37Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_158 |47.77Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_171 |20.02Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_173 |22.49Mb
  - _174 |10.10Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_163 |10.34Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_175 |12.59Mb
  - netflix_NO |30.30Mb
  - netflix_JP |11.24Mb
  - disney_DE |198.50Mb
  - netflix_NL |51.12Mb
  - netflix_NL |121.05Mb
  - disney_HK |77.03Mb
  - netflix_IT |18.43Mb
  - netflix_NL |112.52Mb
  - ğŸ‡²ğŸ‡½MX_204 |41.28Mb
  - netflix_NL |107.53Mb
  - Relay_-ğŸ‡­ğŸ‡°HK_172 |10.28Mb
  - ğŸ‡±ğŸ‡¹LT_203 |104.84Mb
  - disney_HK |103.02Mb
  - ğŸ‡­ğŸ‡°HK_188 |103.85Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_214 |41.13Mb
  - netflix_PT |70.40Mb
  - disney_netflix_US |16.91Mb
  - ğŸ‡¸ğŸ‡¬SG_212 |21.45Mb
  - ğŸ ZZ_217 |144.36Mb
  - netflix_NL |51.64Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
