port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: _175
  server: 23.95.72.81
  type: ss
  port: 443
  udp: true
  password: UAMVtHm54uahd6SiN5WcD16rsPSdabPG
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_NL
  server: 45.87.175.154
  type: ss
  port: 8080
  udp: true
  password: 1RWwXhwfAB5gAEozU4G2Pg
  cipher: chacha20-ietf-poly1305
- name: netflix_HR
  server: 185.156.110.92
  type: ss
  port: 443
  udp: true
  password: gXOXk2FJwsz9P6nXIICuDNOqF9gWX1dn
  cipher: chacha20-ietf-poly1305
- name: _180
  server: 213.159.66.206
  type: ss
  port: 443
  udp: true
  password: pl2XtR0pzwknQOGwewbwXtPYDw1zn9Vu
  cipher: chacha20-ietf-poly1305
- name: Relay_-ğŸ‡ºğŸ‡¸US_182
  server: clr.ducks.tel
  type: ss
  port: 17846
  udp: true
  password: '907560230'
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_US
  server: clr.ducks.tel
  type: ss
  port: 17847
  udp: true
  password: '907560230'
  cipher: chacha20-ietf-poly1305
- name: disney_DE
  server: clr.ducks.tel
  type: ss
  port: 17844
  udp: true
  password: '907560230'
  cipher: chacha20-ietf-poly1305
- name: _181
  server: 103.75.118.125
  type: ss
  port: 443
  udp: true
  password: XLOrvLWkCBBBxLqSEe9S8lnC5PLsNfRh
  cipher: chacha20-ietf-poly1305
- name: Relay_-ğŸ‡ºğŸ‡¸US_187
  server: 82.198.246.97
  type: vmess
  port: 180
  uuid: d13fc2f5-3e05-4795-81eb-44143a09e552
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: disney_MD
  server: 185.153.197.5
  type: ss
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: Relay_-ğŸ‡«ğŸ‡·FR_190
  server: 51.15.210.1
  type: trojan
  port: 443
  udp: true
  password: e6f0e8b0-3dc5-4d53-a23a-86c02d5ba098
  sni: joss.gpj1.web.id
  ws-opts:
    path: /Free-VPN-CF-Geo-Project/51.15.210.1=443
    headers:
      Host: joss.gpj1.web.id
  network: ws
- name: disney_netflix_US
  server: huojian1.vn9987.top
  type: ss
  port: 51004
  udp: true
  password: f1fa04be-bdf6-477e-81d0-b46232227455
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_NL
  server: 89.169.8.105
  type: trojan
  port: 443
  udp: true
  password: '0'
  alpn:
  - http%2F1.1
  sni: c03237cb.ba73fe85.netlib.re
  ws-opts:
    path: /
    headers:
      Host: c03237cb.ba73fe85.netlib.re
  network: ws
- name: Relay_-ğŸ‡­ğŸ‡°HK_186
  server: 131.186.63.89
  type: vmess
  port: 11655
  uuid: 4bf075f5-4d5e-4d39-f5ab-b32a86250f0e
  alterId: 0
  cipher: auto
  network: ws
  servername: hk.nbee.pp.ua
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /aa
    headers:
      Host: hk.nbee.pp.ua
- name: disney_netflix_NL
  server: 89.110.120.197
  type: trojan
  port: 443
  udp: true
  password: 35f8e682-54bd-42c7-b537-94a8e4c84bcd
  sni: joss.gpj1.web.id
  ws-opts:
    path: /Free-VPN-CF-Geo-Project/89.110.120.197=443
    headers:
      Host: joss.gpj1.web.id
  network: ws
- name: disney_NL
  server: 138.124.30.8
  type: trojan
  port: 443
  udp: true
  password: 0311306e-56d4-4aa1-bde5-8cede7fcd3e4
  sni: joss.gpj1.web.id
  ws-opts:
    path: /Free-VPN-CF-Geo-Project/138.124.30.8=443
    headers:
      Host: joss.gpj1.web.id
  network: ws
- name: disney_netflix_FR
  server: 51.44.94.146
  type: trojan
  port: 22223
  udp: true
  password: telegram-id-directvpn
  sni: trojan.burgerip.co.uk
  skip-cert-verify: true
- name: disney_netflix_GB
  server: 109.169.76.23
  type: trojan
  port: 443
  udp: true
  password: d69e725c-7c7e-4c75-9786-4859b4e0bbc6
  sni: joss.gpj1.web.id
  ws-opts:
    path: /Free-VPN-CF-Geo-Project/109.169.76.23=443
    headers:
      Host: joss.gpj1.web.id
  network: ws
- name: disney_netflix_NL
  server: 81.22.132.183
  type: trojan
  port: 443
  udp: true
  password: ee339912-0c35-4fac-8d85-180b65bcd49c
  sni: joss.gpj1.web.id
  ws-opts:
    path: /Free-VPN-CF-Geo-Project/81.22.132.183=443
    headers:
      Host: joss.gpj1.web.id
  network: ws
- name: Relay_-ğŸ‡³ğŸ‡±NL_193
  server: 160.16.63.16
  type: trojan
  port: 4054
  password: 2cf6d686799e6fa95316394064f26c0a
  sni: www.nintendogames.net
- name: disney_netflix_GB
  server: joss.gpj1.web.id
  type: trojan
  port: 443
  udp: true
  password: 6e6191a3-9a93-4617-859a-8d0ea0fce937
  sni: joss.gpj1.web.id
  ws-opts:
    path: /Free-VPN-CF-Geo-Project/81.91.214.85=443
    headers:
      Host: joss.gpj1.web.id
  network: ws
- name: disney_netflix_NL
  server: 86.107.197.239
  type: trojan
  port: 443
  udp: true
  password: e683d757-b855-44c3-b0b6-22586444914a
  sni: joss.gpj1.web.id
  ws-opts:
    path: /Free-VPN-CF-Geo-Project/86.107.197.239=443
    headers:
      Host: joss.gpj1.web.id
  network: ws
- name: disney_CA
  server: 69.28.82.253
  type: trojan
  port: 443
  udp: true
  password: 8001fbf7-4b59-4415-a4bd-8bfded02c9c6
  sni: joss.gpj1.web.id
  ws-opts:
    path: /Free-VPN-CF-Geo-Project/69.28.82.253=443
    headers:
      Host: joss.gpj1.web.id
  network: ws
- name: Relay_-ğŸ‡³ğŸ‡±NL_199
  server: 3.113.21.213
  type: trojan
  port: 2890
  password: 2cf6d686799e6fa95316394064f26c0a
  sni: www.nintendogames.net
- name: disney_OM
  server: 176.97.66.175
  type: trojan
  port: 443
  udp: true
  password: 8cdd7764-0143-4b64-bb50-c56599be438e
  sni: joss.gpj1.web.id
  ws-opts:
    path: /Free-VPN-CF-Geo-Project/176.97.66.175=443
    headers:
      Host: joss.gpj1.web.id
  network: ws
- name: disney_FR
  server: 34.22.190.30
  type: trojan
  port: 443
  udp: true
  password: 0a477acf-1f95-47cb-b4a5-a627b4c57de3
  sni: joss.gpj1.web.id
  ws-opts:
    path: /Free-VPN-CF-Geo-Project/34.22.190.30=443
    headers:
      Host: joss.gpj1.web.id
  network: ws
- name: disney_FR
  server: 34.22.190.30
  type: trojan
  port: 443
  udp: true
  password: 29ca24a5-e8aa-4cbd-9bcb-f96aba1d6f15
  sni: joss.gpj1.web.id
  ws-opts:
    path: /Free-VPN-CF-Geo-Project/34.22.190.30=443
    headers:
      Host: joss.gpj1.web.id
  network: ws
- name: disney_US
  server: 47.89.150.45
  type: trojan
  port: 21575
  udp: true
  password: abb96ae5-8337-4719-b300-fc3b2efbd14d
  sni: joss.gpj1.web.id
  ws-opts:
    path: /Free-VPN-CF-Geo-Project/47.89.150.45=21575
    headers:
      Host: joss.gpj1.web.id
  network: ws
- name: disney_FR
  server: 34.22.190.30
  type: trojan
  port: 443
  udp: true
  password: fea8b7a7-cc83-4a78-a3fc-bbce9cc89ddb
  sni: joss.gpj1.web.id
  ws-opts:
    path: /Free-VPN-CF-Geo-Project/34.22.190.30=443
    headers:
      Host: joss.gpj1.web.id
  network: ws
- name: Relay_-ğŸ‡³ğŸ‡±NL_200
  server: 160.16.236.32
  type: trojan
  port: 2760
  password: 2cf6d686799e6fa95316394064f26c0a
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¯ğŸ‡µJP_203
  server: 160.16.57.238
  type: trojan
  port: 3169
  password: 2cf6d686799e6fa95316394064f26c0a
  sni: www.nintendogames.net
- name: disney_ES
  server: 45.86.229.28
  type: trojan
  port: 443
  udp: true
  password: 9ccc3e1d-3df5-4348-aa05-738310149cc3
  sni: joss.gpj1.web.id
  ws-opts:
    path: /Free-VPN-CF-Geo-Project/45.86.229.28=443
    headers:
      Host: joss.gpj1.web.id
  network: ws
- name: disney_netflix_US
  server: usiys.southbyte.xyz
  type: trojan
  port: 5897
  udp: true
  password: fg20mtCFHy
  sni: usiys.southbyte.xyz
  skip-cert-verify: true
- name: disney_netflix_DE
  server: 80.211.249.240
  type: trojan
  port: 8443
  udp: true
  password: 5ff970a7-2897-40e9-aef3-188e699d23ae
  sni: joss.gpj1.web.id
  ws-opts:
    path: /Free-VPN-CF-Geo-Project/80.211.249.240=8443
    headers:
      Host: joss.gpj1.web.id
  network: ws
- name: disney_netflix_FR
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 27092
  uuid: a0596ba6-72a3-4366-8992-77088da65bd8
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_IT
  server: 94.177.199.119
  type: trojan
  port: 8443
  udp: true
  password: e04af4a8-ce76-4026-8480-82d0e35dd239
  sni: joss.gpj1.web.id
  ws-opts:
    path: /Free-VPN-CF-Geo-Project/94.177.199.119=8443
    headers:
      Host: joss.gpj1.web.id
  network: ws
- name: disney_netflix_NL
  server: 82.38.31.214
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_NL
  server: 82.38.31.205
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_NL
  server: 82.38.31.190
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_NL
  server: 82.38.31.208
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_220
  server: 82.38.31.199
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: disney_HK
  server: 58.152.110.92
  type: trojan
  port: 443
  udp: true
  password: dd2f25b4c70689de8bc0f7fa9d6591cb
  sni: www.nintendogames.net
- name: disney_netflix_NL
  server: 82.38.31.184
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡²ğŸ‡½MX_227
  server: 216.238.89.53
  type: vmess
  country: ğŸ‡²ğŸ‡½MX
  port: 57283
  uuid: 1a5aafc0-6482-451d-fe76-6875b7818579
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_NL
  server: 213.176.16.71
  type: ss
  country: ğŸ‡®ğŸ‡·IR
  port: 4966
  password: lXOVjEMsx00jeOQzHsQrkL
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸ‡©ğŸ‡ªDE-ğŸ‡©ğŸ‡ªDE_214
  server: node4.rtxconfigz.com
  type: vmess
  country: ğŸ‡©ğŸ‡ªDE
  port: 443
  uuid: 44e57485-eccc-46ef-808f-cd17ac810018
  alterId: 0
  cipher: auto
  network: ws
  servername: node4.rtxconfigz.com
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /@Malinda6104
    headers:
      HOST: node4.rtxconfigz.com
- name: disney_netflix_NL
  server: 93.183.91.172
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 6462
  password: 741kWqe81Pp8YTsXxter6g
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡·ğŸ‡ºRU_229
  server: 5.129.214.186
  type: ss
  country: ğŸ‡·ğŸ‡ºRU
  port: 6403
  password: HWNsKy61qPyoDtrEYEtZuk
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¯ğŸ‡µJP_226
  server: cgroup.node1.v.nodelist-airport.com
  type: vmess
  country: ğŸ‡¯ğŸ‡µJP
  port: 53231
  uuid: 8f3a835c-8a45-480d-ae35-1deb2c52dcae
  alterId: 0
  cipher: auto
  network: tcp
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_TR
  server: 185.39.204.189
  type: ss
  country: ğŸ‡·ğŸ‡ºRU
  port: 34085
  password: depjSbjv2Uql6W4Vge7sDf
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡·ğŸ‡ºRU_231
  server: 77.246.107.222
  type: ss
  country: ğŸ‡·ğŸ‡ºRU
  port: 443
  password: 42QuZ89iaZQElYKy1bDyOV
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¸ğŸ‡ªSE_233
  server: 78.40.116.178
  type: ss
  country: ğŸ‡¸ğŸ‡ªSE
  port: 34094
  password: yo6h9qkhwz8UJoTZCRtoSi
  cipher: chacha20-ietf-poly1305
- name: disney_US
  server: 193.124.24.247
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 6512
  uuid: 729bfa51-095c-4f50-a1e0-2dfc90d51ebd
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_US
  server: 193.124.24.247
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 6505
  uuid: b34732f9-2856-4974-8bae-1351928e347f
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡ºğŸ‡¸ US_235
  server: 38.54.57.90
  type: ss
  country: ğŸ‡ºğŸ‡¸ US
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: Relay_ğŸ‡­ğŸ‡°HK-ğŸ‡­ğŸ‡°HK_222
  server: n1761296893.lie5d.cyou
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 443
  uuid: 40f088bf-ed4b-4630-860f-45ed12c75ff7
  alterId: 0
  cipher: auto
  network: ws
  servername: n1761296893.lie5d.cyou
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /
    headers:
      HOST: n1761296893.lie5d.cyou
- name: disney_netflix_US
  server: 193.124.24.247
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 6502
  uuid: 242f22a3-29d9-4a94-d8ba-88043f2e1921
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_US
  server: 193.124.24.247
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 6508
  uuid: b68fead5-5b0b-43a1-c34a-804467f0f368
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_US
  server: 193.124.24.247
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 6513
  uuid: 5cf7fcbc-e2c1-42c4-d0d7-79c45a7d588d
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_US
  server: 193.124.24.247
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 6510
  uuid: 8f44f672-e53b-44fb-b502-c886d37107b5
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡¸ğŸ‡¬SG_234
  server: cgroup.node3.s.nodelist-airport.com
  type: ss
  country: ğŸ‡¸ğŸ‡¬SG
  port: 16198
  password: 8f3a835c-8a45-480d-ae35-1deb2c52dcae
  cipher: aes-256-gcm
- name: disney_netflix_US
  server: 193.124.24.247
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 6504
  uuid: 7ceb165c-9aff-4ab7-ce9e-1df31a5ed911
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_ğŸZZ-ğŸ‡¦ğŸ‡ºAU_244
  server: sy4.620720.xyz
  type: vmess
  country: ğŸZZ
  port: 443
  uuid: 516d8a7a-3f0b-41d3-bad0-246116381516
  alterId: 0
  cipher: auto
  network: ws
  servername: sy4.620720.xyz
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /
    headers:
      HOST: sy4.620720.xyz
- name: Relay_-ğŸ‡­ğŸ‡°HK_185
  server: d5e57692-t6ccg0-t7pjgr-11p9g.hk3.p5pv.com
  type: vmess
  port: 80
  udp: true
  uuid: 384d1b42-655f-11ed-a8bf-f23c91cfbbc9
  alterId: 2
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /
    headers:
      Host: broadcastlv.chat.bilibili.com
- name: Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_238
  server: n1749032902.xlxzzx.com
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  uuid: 6f932d64-1eb4-4160-bc8d-6085cfd4d37d
  alterId: 0
  cipher: auto
  network: ws
  servername: n1749032902.xlxzzx.com
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /
    headers:
      HOST: n1749032902.xlxzzx.com
- name: Relay_-ğŸ‡­ğŸ‡°HK_188
  server: n1761296886.lie5d.cyou
  type: vmess
  port: 443
  udp: true
  uuid: 697ece59-37c9-4a61-b986-705cad56057b
  alterId: 0
  cipher: auto
  network: ws
  servername: n1761296886.lie5d.cyou
  http-opts: {}
  h2-opts: {}
  tls: true
  ws-opts:
    path: /
    headers:
      Host: n1761296886.lie5d.cyou
- name: Relay_ğŸ‡­ğŸ‡°HK-ğŸ‡­ğŸ‡°HK_223
  server: n1744453319.lie5d.cyou
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 443
  uuid: 6928af97-a23e-408c-956e-5cd2207f3557
  alterId: 0
  cipher: auto
  network: ws
  servername: n1744453319.lie5d.cyou
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /
    headers:
      HOST: n1744453319.lie5d.cyou
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - _175
  - disney_netflix_NL
  - netflix_HR
  - _180
  - Relay_-ğŸ‡ºğŸ‡¸US_182
  - disney_netflix_US
  - disney_DE
  - _181
  - Relay_-ğŸ‡ºğŸ‡¸US_187
  - disney_MD
  - Relay_-ğŸ‡«ğŸ‡·FR_190
  - disney_netflix_US
  - disney_netflix_NL
  - Relay_-ğŸ‡­ğŸ‡°HK_186
  - disney_netflix_NL
  - disney_NL
  - disney_netflix_FR
  - disney_netflix_GB
  - disney_netflix_NL
  - Relay_-ğŸ‡³ğŸ‡±NL_193
  - disney_netflix_GB
  - disney_netflix_NL
  - disney_CA
  - Relay_-ğŸ‡³ğŸ‡±NL_199
  - disney_OM
  - disney_FR
  - disney_FR
  - disney_US
  - disney_FR
  - Relay_-ğŸ‡³ğŸ‡±NL_200
  - Relay_-ğŸ‡¯ğŸ‡µJP_203
  - disney_ES
  - disney_netflix_US
  - disney_netflix_DE
  - disney_netflix_FR
  - disney_IT
  - disney_netflix_NL
  - disney_netflix_NL
  - disney_netflix_NL
  - disney_netflix_NL
  - ğŸ‡¬ğŸ‡§GB_220
  - disney_HK
  - disney_netflix_NL
  - ğŸ‡²ğŸ‡½MX_227
  - disney_netflix_NL
  - Relay_ğŸ‡©ğŸ‡ªDE-ğŸ‡©ğŸ‡ªDE_214
  - disney_netflix_NL
  - ğŸ‡·ğŸ‡ºRU_229
  - ğŸ‡¯ğŸ‡µJP_226
  - disney_TR
  - ğŸ‡·ğŸ‡ºRU_231
  - ğŸ‡¸ğŸ‡ªSE_233
  - disney_US
  - disney_US
  - ğŸ‡ºğŸ‡¸ US_235
  - Relay_ğŸ‡­ğŸ‡°HK-ğŸ‡­ğŸ‡°HK_222
  - disney_netflix_US
  - disney_netflix_US
  - disney_netflix_US
  - disney_netflix_US
  - ğŸ‡¸ğŸ‡¬SG_234
  - disney_netflix_US
  - Relay_ğŸZZ-ğŸ‡¦ğŸ‡ºAU_244
  - Relay_-ğŸ‡­ğŸ‡°HK_185
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_238
  - Relay_-ğŸ‡­ğŸ‡°HK_188
  - Relay_ğŸ‡­ğŸ‡°HK-ğŸ‡­ğŸ‡°HK_223
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - _175
  - disney_netflix_NL
  - netflix_HR
  - _180
  - Relay_-ğŸ‡ºğŸ‡¸US_182
  - disney_netflix_US
  - disney_DE
  - _181
  - Relay_-ğŸ‡ºğŸ‡¸US_187
  - disney_MD
  - Relay_-ğŸ‡«ğŸ‡·FR_190
  - disney_netflix_US
  - disney_netflix_NL
  - Relay_-ğŸ‡­ğŸ‡°HK_186
  - disney_netflix_NL
  - disney_NL
  - disney_netflix_FR
  - disney_netflix_GB
  - disney_netflix_NL
  - Relay_-ğŸ‡³ğŸ‡±NL_193
  - disney_netflix_GB
  - disney_netflix_NL
  - disney_CA
  - Relay_-ğŸ‡³ğŸ‡±NL_199
  - disney_OM
  - disney_FR
  - disney_FR
  - disney_US
  - disney_FR
  - Relay_-ğŸ‡³ğŸ‡±NL_200
  - Relay_-ğŸ‡¯ğŸ‡µJP_203
  - disney_ES
  - disney_netflix_US
  - disney_netflix_DE
  - disney_netflix_FR
  - disney_IT
  - disney_netflix_NL
  - disney_netflix_NL
  - disney_netflix_NL
  - disney_netflix_NL
  - ğŸ‡¬ğŸ‡§GB_220
  - disney_HK
  - disney_netflix_NL
  - ğŸ‡²ğŸ‡½MX_227
  - disney_netflix_NL
  - Relay_ğŸ‡©ğŸ‡ªDE-ğŸ‡©ğŸ‡ªDE_214
  - disney_netflix_NL
  - ğŸ‡·ğŸ‡ºRU_229
  - ğŸ‡¯ğŸ‡µJP_226
  - disney_TR
  - ğŸ‡·ğŸ‡ºRU_231
  - ğŸ‡¸ğŸ‡ªSE_233
  - disney_US
  - disney_US
  - ğŸ‡ºğŸ‡¸ US_235
  - Relay_ğŸ‡­ğŸ‡°HK-ğŸ‡­ğŸ‡°HK_222
  - disney_netflix_US
  - disney_netflix_US
  - disney_netflix_US
  - disney_netflix_US
  - ğŸ‡¸ğŸ‡¬SG_234
  - disney_netflix_US
  - Relay_ğŸZZ-ğŸ‡¦ğŸ‡ºAU_244
  - Relay_-ğŸ‡­ğŸ‡°HK_185
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_238
  - Relay_-ğŸ‡­ğŸ‡°HK_188
  - Relay_ğŸ‡­ğŸ‡°HK-ğŸ‡­ğŸ‡°HK_223
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
