port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: Relay_-ğŸ‡ºğŸ‡¸US_472 |40.39Mb
  server: 38.14.99.179
  type: vmess
  port: 59807
  udp: true
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_-ğŸ‡³ğŸ‡±NL_455 |200.92Mb
  server: 151.242.251.137
  type: ss
  port: 8080
  password: o5osZg269v5zHpYjr1xY9s
  cipher: chacha20-ietf-poly1305
- name: _454 |17.17Mb
  server: 103.231.73.211
  type: ss
  port: 57456
  udp: true
  password: 8afc633eb63227e9
  cipher: chacha20-ietf-poly1305
- name: _571 |12.43Mb
  server: 68.183.231.236
  type: trojan
  port: 443
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: disney_SG |34.48Mb
  server: 188.253.124.53
  type: ss
  port: 63257
  udp: true
  password: RenzheCloudSS
  cipher: rc4-md5
  plugin: obfs
  plugin-opts:
    host: d1bf8290613.microsoft.com
    mode: http
- name: Relay_-ğŸ‡¸ğŸ‡¬SG_577 |10.03Mb
  server: 160.16.212.152
  type: trojan
  port: 507
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡³ğŸ‡±NL_578 |20.58Mb
  server: 160.16.132.158
  type: trojan
  port: 4054
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¯ğŸ‡µJP_581 |19.06Mb
  server: 160.16.70.180
  type: trojan
  port: 1331
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡³ğŸ‡±NL_584 |42.40Mb
  server: 160.16.236.32
  type: trojan
  port: 4054
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¯ğŸ‡µJP_587 |11.55Mb
  server: 153.121.45.139
  type: trojan
  port: 1331
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¯ğŸ‡µJP_588 |18.81Mb
  server: 153.121.38.213
  type: trojan
  port: 1331
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡³ğŸ‡±NL_590 |23.95Mb
  server: 160.16.57.238
  type: trojan
  port: 4054
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡³ğŸ‡±NL_591 |12.95Mb
  server: 160.16.131.243
  type: trojan
  port: 2890
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¯ğŸ‡µJP_596 |13.93Mb
  server: 160.16.72.33
  type: trojan
  port: 3093
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: disney_FR |152.00Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 27092
  uuid: a0596ba6-72a3-4366-8992-77088da65bd8
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_FR |205.18Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 40433
  uuid: d8fd8955-78db-49ba-d86f-3e4729f6ac4d
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_HK |27.18Mb
  server: 58.152.110.154
  type: trojan
  port: 443
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: ğŸ‡¬ğŸ‡§GB_603 |183.47Mb
  server: 82.38.31.190
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡§ğŸ‡·BR_598 |115.85Mb
  server: 38.180.16.86
  type: vmess
  country: ğŸ‡§ğŸ‡·BR
  port: 36104
  uuid: E146A8CB-9D2F-449C-ADCA-8736FB
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_ğŸ‡¬ğŸ‡§GB-ğŸ‡³ğŸ‡±NL_604 |222.24Mb
  server: 82.38.31.210
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_605 |10.66Mb
  server: 82.38.31.179
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: netflix_NL |236.80Mb
  server: 82.38.31.218
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡²ğŸ‡½MX_647 |37.38Mb
  server: 216.238.89.53
  type: vmess
  country: ğŸ‡²ğŸ‡½MX
  port: 57283
  uuid: 1a5aafc0-6482-451d-fe76-6875b7818579
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡­ğŸ‡°HK_634 |26.08Mb
  server: 47.242.140.52
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 48219
  uuid: 006893c6-79b1-4c44-94ff-b8bbea065f1f
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
  ws-opts:
    path: /arki?ed=2048
- name: ğŸ‡­ğŸ‡°HK_610 |21.92Mb
  server: 87.121.162.249
  type: ss
  country: ğŸ‡­ğŸ‡°HK
  port: 443
  password: JGv616hMWdjfuZ00jYfq7XkBHJZrOBrg
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸ‡¯ğŸ‡µJP-ğŸ‡¯ğŸ‡µJP_642 |22.06Mb
  server: kuame.missionsec.us
  type: trojan
  country: ğŸ‡¯ğŸ‡µJP
  port: 443
  udp: true
  password: FDIypSwe64a3DA7un2R8DFjYXZO3NS05gKZTTOC8SxO0Fy3cqYg3EaFDA3ABaEYKNx39D
  sni: kuame.missionsec.us
  skip-cert-verify: true
- name: disney_HK |71.50Mb
  server: 219.79.186.107
  type: trojan
  country: ğŸ‡­ğŸ‡°HK
  port: 443
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: ğŸ‡ºğŸ‡¸US_657 |16.93Mb
  server: 104.192.226.106
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ğŸ‡®ğŸ‡³IN_639 |126.41Mb
  server: 134.209.147.198
  type: ss
  country: ğŸ‡®ğŸ‡³IN
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_661 |40.80Mb
  server: 38.14.99.163
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 59807
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: auto
  network: tcp
  servername: 38.14.99.163
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡²ğŸ‡¾MY_648 |32.03Mb
  server: 38.54.98.110
  type: vmess
  country: ğŸ‡²ğŸ‡¾MY
  port: 2052
  uuid: 665d9b8f-153d-4907-adac-de12afd9c851
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: ğŸ‡¸ğŸ‡¬SG_650 |10.95Mb
  server: 68.183.178.131
  type: vmess
  country: ğŸ‡¸ğŸ‡¬SG
  port: 58607
  uuid: c11c32cb-27b3-4afa-c0f3-fb250aa4959e
  alterId: 0
  cipher: auto
  network: ws
  servername: www.12333.monster
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /
    headers:
      HOST: www.12333.monster
- name: disney_RU |482.11Mb
  server: 38.60.223.8
  type: ss
  country: ğŸ‡·ğŸ‡ºRU
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ğŸ‡ºğŸ‡¸US_655 |147.99Mb
  server: 45.12.144.18
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: LQyAUItafUmmO3EZZx9UbiX6IGydSBgL
  cipher: chacha20-ietf-poly1305
- name: disney_HK |12.56Mb
  server: 45.136.12.37
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 38141
  uuid: fd291be6-b48d-43a1-da38-66c7f80e2f80
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡¸ğŸ‡¬SG_659 |447.99Mb
  server: clr.ducks.tel
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 17844
  password: '907560230'
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_654 |143.70Mb
  server: 45.12.136.170
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: l668XHPejoSNNuD66BYzyehaCpZexiF7
  cipher: chacha20-ietf-poly1305
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - Relay_-ğŸ‡ºğŸ‡¸US_472 |40.39Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_455 |200.92Mb
  - _454 |17.17Mb
  - _571 |12.43Mb
  - disney_SG |34.48Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_577 |10.03Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_578 |20.58Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_581 |19.06Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_584 |42.40Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_587 |11.55Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_588 |18.81Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_590 |23.95Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_591 |12.95Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_596 |13.93Mb
  - disney_FR |152.00Mb
  - disney_FR |205.18Mb
  - disney_HK |27.18Mb
  - ğŸ‡¬ğŸ‡§GB_603 |183.47Mb
  - ğŸ‡§ğŸ‡·BR_598 |115.85Mb
  - Relay_ğŸ‡¬ğŸ‡§GB-ğŸ‡³ğŸ‡±NL_604 |222.24Mb
  - ğŸ‡¬ğŸ‡§GB_605 |10.66Mb
  - netflix_NL |236.80Mb
  - ğŸ‡²ğŸ‡½MX_647 |37.38Mb
  - ğŸ‡­ğŸ‡°HK_634 |26.08Mb
  - ğŸ‡­ğŸ‡°HK_610 |21.92Mb
  - Relay_ğŸ‡¯ğŸ‡µJP-ğŸ‡¯ğŸ‡µJP_642 |22.06Mb
  - disney_HK |71.50Mb
  - ğŸ‡ºğŸ‡¸US_657 |16.93Mb
  - ğŸ‡®ğŸ‡³IN_639 |126.41Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_661 |40.80Mb
  - ğŸ‡²ğŸ‡¾MY_648 |32.03Mb
  - ğŸ‡¸ğŸ‡¬SG_650 |10.95Mb
  - disney_RU |482.11Mb
  - ğŸ‡ºğŸ‡¸US_655 |147.99Mb
  - disney_HK |12.56Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡¸ğŸ‡¬SG_659 |447.99Mb
  - ğŸ‡ºğŸ‡¸US_654 |143.70Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - Relay_-ğŸ‡ºğŸ‡¸US_472 |40.39Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_455 |200.92Mb
  - _454 |17.17Mb
  - _571 |12.43Mb
  - disney_SG |34.48Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_577 |10.03Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_578 |20.58Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_581 |19.06Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_584 |42.40Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_587 |11.55Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_588 |18.81Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_590 |23.95Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_591 |12.95Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_596 |13.93Mb
  - disney_FR |152.00Mb
  - disney_FR |205.18Mb
  - disney_HK |27.18Mb
  - ğŸ‡¬ğŸ‡§GB_603 |183.47Mb
  - ğŸ‡§ğŸ‡·BR_598 |115.85Mb
  - Relay_ğŸ‡¬ğŸ‡§GB-ğŸ‡³ğŸ‡±NL_604 |222.24Mb
  - ğŸ‡¬ğŸ‡§GB_605 |10.66Mb
  - netflix_NL |236.80Mb
  - ğŸ‡²ğŸ‡½MX_647 |37.38Mb
  - ğŸ‡­ğŸ‡°HK_634 |26.08Mb
  - ğŸ‡­ğŸ‡°HK_610 |21.92Mb
  - Relay_ğŸ‡¯ğŸ‡µJP-ğŸ‡¯ğŸ‡µJP_642 |22.06Mb
  - disney_HK |71.50Mb
  - ğŸ‡ºğŸ‡¸US_657 |16.93Mb
  - ğŸ‡®ğŸ‡³IN_639 |126.41Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_661 |40.80Mb
  - ğŸ‡²ğŸ‡¾MY_648 |32.03Mb
  - ğŸ‡¸ğŸ‡¬SG_650 |10.95Mb
  - disney_RU |482.11Mb
  - ğŸ‡ºğŸ‡¸US_655 |147.99Mb
  - disney_HK |12.56Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡¸ğŸ‡¬SG_659 |447.99Mb
  - ğŸ‡ºğŸ‡¸US_654 |143.70Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
