port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: ' |48.80Mb'
  server: 173.234.29.2
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ' |29.55Mb'
  server: 138.186.142.81
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: netflix_NL |12.93Mb
  server: 82.38.31.199
  type: ss
  port: 8080
  udp: true
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ' |11.85Mb'
  server: 45.87.175.28
  type: ss
  port: 8080
  udp: true
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: ' |11.76Mb'
  server: 185.82.73.212
  type: ss
  port: 8444
  udp: true
  password: _bypfvq6ra7g4n5yCCR9DoVeGya2XUUS
  cipher: chacha20-ietf-poly1305
- name: disney_ES |11.30Mb
  server: 145.249.109.121
  type: ss
  port: 25512
  udp: true
  password: smSMfR9jqLgMkHuQtxSIWh
  cipher: chacha20-ietf-poly1305
- name: netflix_NL |22.34Mb
  server: 45.14.245.2
  type: ss
  port: 443
  password: 17ZDORWIliQHuO6WRGHChXYMzdRtAYVP
  cipher: chacha20-ietf-poly1305
- name: ' |808.32Mb'
  server: 192.71.249.78
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ' |52.75Mb'
  server: 46.246.96.30
  type: ss
  port: 31561
  udp: true
  password: hc8LMJew3Fl9MbcFCoFgT0
  cipher: chacha20-ietf-poly1305
- name: disney_PY |107.07Mb
  server: 38.165.233.93
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: disney_US |94.34Mb
  server: 156.233.232.192
  type: vmess
  port: 44329
  uuid: 1ba1fb56-e235-419e-c193-1c291adad4a7
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
- name: ' |40.95Mb'
  server: 160.16.106.144
  type: trojan
  port: 2890
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: ' |10.89Mb'
  server: 160.16.106.144
  type: trojan
  port: 2760
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
  skip-cert-verify: true
- name: ' |19.21Mb'
  server: 47.242.145.160
  type: vmess
  port: 44457
  uuid: 40290609-2743-4d85-c9c3-4c72dd151b9f
  alterId: 0
  cipher: auto
  network: http
  http-opts:
    method: GET
    path:
    - /
  h2-opts: {}
- name: ' |10.82Mb'
  server: 160.16.131.243
  type: trojan
  port: 2760
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
  skip-cert-verify: true
- name: disney_US |95.03Mb
  server: 156.233.232.192
  type: vmess
  port: 24004
  uuid: 582fcb35-20a0-452c-e179-4c759c62c494
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
- name: disney_US |82.76Mb
  server: 156.233.232.177
  type: vmess
  port: 24004
  uuid: 582fcb35-20a0-452c-e179-4c759c62c494
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
- name: disney_US |93.30Mb
  server: 156.233.232.177
  type: vmess
  port: 44329
  uuid: 1ba1fb56-e235-419e-c193-1c291adad4a7
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
- name: ' |42.21Mb'
  server: 185.213.23.63
  type: ss
  country: ğŸ‡¨ğŸ‡¦CA
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: Relay_ |219.69Mb
  server: 82.38.31.208
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: disney_HK |16.85Mb
  server: 45.207.157.29
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 13852
  uuid: 845764df-ecb3-4b13-bed2-bf1551b68e9a
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡­ğŸ‡°HK_404 |122.95Mb
  server: 8.218.116.26
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 32228
  uuid: e4767e9f-ed00-4f31-a984-a918bdd9b09c
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡­ğŸ‡°HK_405 |118.68Mb
  server: 8.218.105.196
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 52752
  uuid: 925bdbf5-72be-4437-bebf-441c61089f6b
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ' |229.95Mb'
  server: 45.87.175.183
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: ' |19.50Mb'
  server: 176.126.83.121
  type: ss
  country: ğŸ‡®ğŸ‡¹IT
  port: 443
  password: Q4t8T7hEYY3mD2Fn4wnxyK4X35AUzvR8
  cipher: chacha20-ietf-poly1305
- name: Relay_ |11.07Mb
  server: xray.kk37005.tk
  type: vmess
  country: ğŸ‡¯ğŸ‡µJP
  port: 55919
  uuid: 2e7548bb-7c5b-4d97-d64d-1b2fe4050089
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: _383 |28.53Mb
  server: 219.79.214.159
  type: trojan
  port: 443
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: ' |10.55Mb'
  server: 45.87.175.190
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: ' |40.30Mb'
  server: 216.238.87.47
  type: vmess
  country: ğŸ‡²ğŸ‡½MX
  port: 27502
  uuid: b8155ce4-7e08-4c40-800f-8671312b7124
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ' |11.31Mb'
  server: 103.97.203.220
  type: vmess
  country: ğŸ‡®ğŸ‡³IN
  port: 550
  uuid: 9e0e83ca-0fbc-44b1-8024-0eb8f9414156
  alterId: 0
  cipher: auto
  network: tcp
  servername: t.me/v2Line
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_ |40.63Mb
  server: 38.14.99.163
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 59807
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: auto
  network: tcp
  servername: 38.14.99.163
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ' |10.82Mb'
  server: 45.87.175.200
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: ' |233.68Mb'
  server: 45.87.175.185
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ' |253.99Mb'
  server: 45.87.175.185
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: ' |228.90Mb'
  server: 45.87.175.180
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: QCXDxuDlTTMD7jtgHUjIoj
  cipher: chacha20-ietf-poly1305
- name: Relay_ |11.05Mb
  server: gy3.hdcloud.link
  type: trojan
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  udp: true
  password: 168f29a7-6922-4558-8296-61a69cf6a5a2
  network: grpc
  grpc-opts:
    grpc-service-name: GunService
- name: ' |117.12Mb'
  server: 193.29.139.188
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 8080
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: ' |229.50Mb'
  server: 193.29.139.141
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 8080
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: ' |68.26Mb'
  server: 185.113.143.186
  type: ss
  country: ğŸ‡µğŸ‡¹PT
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ' |20.65Mb'
  server: 68.183.227.45
  type: ss
  country: ğŸ‡¸ğŸ‡¬SG
  port: 8080
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: disney_US |28.12Mb
  server: cf.fovi.tk
  type: vmess
  country: ğŸZZ
  port: 443
  uuid: bf67437e-6c90-45ca-abc2-c7240a5ce2aa
  alterId: 0
  cipher: auto
  network: ws
  servername: foxlux.fovi.tk
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /eisasqa
    headers:
      HOST: foxlux.fovi.tk
- name: ' |219.30Mb'
  server: ltnl16.saint.ydns.eu
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - ' |48.80Mb'
  - ' |29.55Mb'
  - netflix_NL |12.93Mb
  - ' |11.85Mb'
  - ' |11.76Mb'
  - disney_ES |11.30Mb
  - netflix_NL |22.34Mb
  - ' |808.32Mb'
  - ' |52.75Mb'
  - disney_PY |107.07Mb
  - disney_US |94.34Mb
  - ' |40.95Mb'
  - ' |10.89Mb'
  - ' |19.21Mb'
  - ' |10.82Mb'
  - disney_US |95.03Mb
  - disney_US |82.76Mb
  - disney_US |93.30Mb
  - ' |42.21Mb'
  - Relay_ |219.69Mb
  - disney_HK |16.85Mb
  - ğŸ‡­ğŸ‡°HK_404 |122.95Mb
  - ğŸ‡­ğŸ‡°HK_405 |118.68Mb
  - ' |229.95Mb'
  - ' |19.50Mb'
  - Relay_ |11.07Mb
  - _383 |28.53Mb
  - ' |10.55Mb'
  - ' |40.30Mb'
  - ' |11.31Mb'
  - Relay_ |40.63Mb
  - ' |10.82Mb'
  - ' |233.68Mb'
  - ' |253.99Mb'
  - ' |228.90Mb'
  - Relay_ |11.05Mb
  - ' |117.12Mb'
  - ' |229.50Mb'
  - ' |68.26Mb'
  - ' |20.65Mb'
  - disney_US |28.12Mb
  - ' |219.30Mb'
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - ' |48.80Mb'
  - ' |29.55Mb'
  - netflix_NL |12.93Mb
  - ' |11.85Mb'
  - ' |11.76Mb'
  - disney_ES |11.30Mb
  - netflix_NL |22.34Mb
  - ' |808.32Mb'
  - ' |52.75Mb'
  - disney_PY |107.07Mb
  - disney_US |94.34Mb
  - ' |40.95Mb'
  - ' |10.89Mb'
  - ' |19.21Mb'
  - ' |10.82Mb'
  - disney_US |95.03Mb
  - disney_US |82.76Mb
  - disney_US |93.30Mb
  - ' |42.21Mb'
  - Relay_ |219.69Mb
  - disney_HK |16.85Mb
  - ğŸ‡­ğŸ‡°HK_404 |122.95Mb
  - ğŸ‡­ğŸ‡°HK_405 |118.68Mb
  - ' |229.95Mb'
  - ' |19.50Mb'
  - Relay_ |11.07Mb
  - _383 |28.53Mb
  - ' |10.55Mb'
  - ' |40.30Mb'
  - ' |11.31Mb'
  - Relay_ |40.63Mb
  - ' |10.82Mb'
  - ' |233.68Mb'
  - ' |253.99Mb'
  - ' |228.90Mb'
  - Relay_ |11.05Mb
  - ' |117.12Mb'
  - ' |229.50Mb'
  - ' |68.26Mb'
  - ' |20.65Mb'
  - disney_US |28.12Mb
  - ' |219.30Mb'
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
