port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: Relay_-ğŸ‡ºğŸ‡¸US_490 |41.14Mb
  server: 38.14.99.179
  type: vmess
  port: 59807
  udp: true
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_-ğŸ‡³ğŸ‡±NL_482 |444.90Mb
  server: 151.242.251.137
  type: ss
  port: 8080
  password: o5osZg269v5zHpYjr1xY9s
  cipher: chacha20-ietf-poly1305
- name: _481 |23.71Mb
  server: 103.231.73.211
  type: ss
  port: 57456
  udp: true
  password: 8afc633eb63227e9
  cipher: chacha20-ietf-poly1305
- name: Relay_-ğŸ‡ºğŸ‡¸US_518 |166.45Mb
  server: 82.198.246.97
  type: vmess
  port: 180
  uuid: d13fc2f5-3e05-4795-81eb-44143a09e552
  alterId: 0
  cipher: auto
  network: tcp
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: _484 |36.08Mb
  server: 188.253.124.53
  type: ss
  port: 63257
  udp: true
  password: RenzheCloudSS
  cipher: rc4-md5
  plugin: obfs
  plugin-opts:
    host: d1bf8290613.microsoft.com
    mode: http
- name: Relay_-ğŸ‡¯ğŸ‡µJP_646 |14.77Mb
  server: 153.121.45.139
  type: trojan
  port: 1331
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: _642 |11.77Mb
  server: 58.152.110.154
  type: trojan
  port: 443
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¯ğŸ‡µJP_647 |14.62Mb
  server: 153.121.38.213
  type: trojan
  port: 1331
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¯ğŸ‡µJP_650 |14.46Mb
  server: 160.16.87.174
  type: trojan
  port: 3169
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡³ğŸ‡±NL_651 |41.44Mb
  server: 160.16.131.243
  type: trojan
  port: 2890
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡ºğŸ‡¸US_502 |57.37Mb
  server: v8.hdacd.com
  type: vmess
  port: 30808
  udp: true
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_-ğŸ‡¯ğŸ‡µJP_652 |11.73Mb
  server: 153.121.65.107
  type: trojan
  port: 3169
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: _649 |20.24Mb
  server: 68.183.231.236
  type: trojan
  port: 443
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¸ğŸ‡¬SG_659 |11.84Mb
  server: 160.16.131.243
  type: trojan
  port: 127
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡ºğŸ‡¸US_627 |12.55Mb
  server: v29.hdacd.com
  type: vmess
  port: 30829
  udp: true
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_-ğŸ‡¯ğŸ‡µJP_660 |21.72Mb
  server: 160.16.72.33
  type: trojan
  port: 3093
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: disney_FR |36.30Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 27092
  uuid: a0596ba6-72a3-4366-8992-77088da65bd8
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_FR |27.70Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 40433
  uuid: d8fd8955-78db-49ba-d86f-3e4729f6ac4d
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡§ğŸ‡·BR_667 |20.73Mb
  server: 38.180.16.86
  type: vmess
  country: ğŸ‡§ğŸ‡·BR
  port: 36104
  uuid: E146A8CB-9D2F-449C-ADCA-8736FB
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: _653 |90.52Mb
  server: 58.152.30.120
  type: trojan
  port: 443
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: Relay_-ğŸ‡³ğŸ‡±NL_666 |11.47Mb
  server: 160.16.116.227
  type: trojan
  port: 2890
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_ğŸ‡¬ğŸ‡§GB-ğŸ‡³ğŸ‡±NL_670 |497.41Mb
  server: 82.38.31.218
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸ‡¬ğŸ‡§GB-ğŸ‡³ğŸ‡±NL_671 |498.55Mb
  server: 82.38.31.210
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_672 |179.36Mb
  server: 82.38.31.190
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_673 |62.21Mb
  server: 82.38.31.179
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡­ğŸ‡°HK_678 |23.88Mb
  server: 87.121.162.249
  type: ss
  country: ğŸ‡­ğŸ‡°HK
  port: 443
  password: JGv616hMWdjfuZ00jYfq7XkBHJZrOBrg
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_726 |89.58Mb
  server: 45.87.175.166
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 443
  password: 1RWwXhwfAB5gAEozU4G2Pg
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡²ğŸ‡½MX_727 |39.79Mb
  server: 216.238.89.53
  type: vmess
  country: ğŸ‡²ğŸ‡½MX
  port: 57283
  uuid: 1a5aafc0-6482-451d-fe76-6875b7818579
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡­ğŸ‡°HK_705 |83.84Mb
  server: 8.210.134.183
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 3721
  uuid: e72f5c6b-220f-40b3-a115-2d81473458cf
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
  ws-opts:
    path: /
- name: ğŸ‡­ğŸ‡°HK_709 |20.82Mb
  server: 47.242.140.52
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 48219
  uuid: 006893c6-79b1-4c44-94ff-b8bbea065f1f
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
  ws-opts:
    path: /arki?ed=2048
- name: Relay_ğŸ‡¯ğŸ‡µJP-ğŸ‡¯ğŸ‡µJP_721 |14.63Mb
  server: kuame.missionsec.us
  type: trojan
  country: ğŸ‡¯ğŸ‡µJP
  port: 443
  udp: true
  password: FDIypSwe64a3DA7un2R8DFjYXZO3NS05gKZTTOC8SxO0Fy3cqYg3EaFDA3ABaEYKNx39D
  sni: kuame.missionsec.us
  skip-cert-verify: true
- name: Relay_ğŸ‡­ğŸ‡°HK-ğŸ‡ºğŸ‡¸US_690 |18.48Mb
  server: v24.hdacd.com
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 30824
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: auto
  network: tcp
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_ğŸ‡°ğŸ‡·KR-ğŸ‡°ğŸ‡·KR_724 |16.56Mb
  server: seoul03.zgjok.com
  type: vmess
  country: ğŸ‡°ğŸ‡·KR
  port: 443
  uuid: 72a0dac4-9689-4a57-b164-5c65bfa94772
  alterId: 0
  cipher: auto
  network: ws
  servername: seoul03.zgjok.com
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /
    headers:
      HOST: seoul03.zgjok.com
- name: ğŸ‡¸ğŸ‡¬SG_730 |11.17Mb
  server: 68.183.178.131
  type: vmess
  country: ğŸ‡¸ğŸ‡¬SG
  port: 58607
  uuid: c11c32cb-27b3-4afa-c0f3-fb250aa4959e
  alterId: 0
  cipher: auto
  network: ws
  servername: www.12333.monster
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /
    headers:
      HOST: www.12333.monster
- name: ğŸ‡²ğŸ‡¾MY_728 |30.39Mb
  server: 38.54.98.110
  type: vmess
  country: ğŸ‡²ğŸ‡¾MY
  port: 2052
  uuid: 665d9b8f-153d-4907-adac-de12afd9c851
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: ğŸ‡ºğŸ‡¸US_736 |138.99Mb
  server: 45.12.136.170
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: l668XHPejoSNNuD66BYzyehaCpZexiF7
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_737 |42.69Mb
  server: 104.192.226.106
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_741 |40.88Mb
  server: 38.14.99.163
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 59807
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: auto
  network: tcp
  servername: 38.14.99.163
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡·ğŸ‡ºRU_735 |42.29Mb
  server: clr.ducks.tel
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 17847
  password: '907560230'
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_739 |12.56Mb
  server: 45.136.12.37
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 38141
  uuid: fd291be6-b48d-43a1-da38-66c7f80e2f80
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_740 |15.44Mb
  server: cf.fovi.tk
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  uuid: bf67437e-6c90-45ca-abc2-c7240a5ce2aa
  alterId: 0
  cipher: auto
  network: ws
  servername: foxlux.fovi.tk
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /eisasqa
    headers:
      HOST: foxlux.fovi.tk
- name: Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡§ğŸ‡¬BG_734 |447.99Mb
  server: clr.ducks.tel
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 17844
  password: '907560230'
  cipher: chacha20-ietf-poly1305
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - Relay_-ğŸ‡ºğŸ‡¸US_490 |41.14Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_482 |444.90Mb
  - _481 |23.71Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_518 |166.45Mb
  - _484 |36.08Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_646 |14.77Mb
  - _642 |11.77Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_647 |14.62Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_650 |14.46Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_651 |41.44Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_502 |57.37Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_652 |11.73Mb
  - _649 |20.24Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_659 |11.84Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_627 |12.55Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_660 |21.72Mb
  - disney_FR |36.30Mb
  - disney_FR |27.70Mb
  - ğŸ‡§ğŸ‡·BR_667 |20.73Mb
  - _653 |90.52Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_666 |11.47Mb
  - Relay_ğŸ‡¬ğŸ‡§GB-ğŸ‡³ğŸ‡±NL_670 |497.41Mb
  - Relay_ğŸ‡¬ğŸ‡§GB-ğŸ‡³ğŸ‡±NL_671 |498.55Mb
  - ğŸ‡¬ğŸ‡§GB_672 |179.36Mb
  - ğŸ‡¬ğŸ‡§GB_673 |62.21Mb
  - ğŸ‡­ğŸ‡°HK_678 |23.88Mb
  - ğŸ‡±ğŸ‡¹LT_726 |89.58Mb
  - ğŸ‡²ğŸ‡½MX_727 |39.79Mb
  - ğŸ‡­ğŸ‡°HK_705 |83.84Mb
  - ğŸ‡­ğŸ‡°HK_709 |20.82Mb
  - Relay_ğŸ‡¯ğŸ‡µJP-ğŸ‡¯ğŸ‡µJP_721 |14.63Mb
  - Relay_ğŸ‡­ğŸ‡°HK-ğŸ‡ºğŸ‡¸US_690 |18.48Mb
  - Relay_ğŸ‡°ğŸ‡·KR-ğŸ‡°ğŸ‡·KR_724 |16.56Mb
  - ğŸ‡¸ğŸ‡¬SG_730 |11.17Mb
  - ğŸ‡²ğŸ‡¾MY_728 |30.39Mb
  - ğŸ‡ºğŸ‡¸US_736 |138.99Mb
  - ğŸ‡ºğŸ‡¸US_737 |42.69Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_741 |40.88Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡·ğŸ‡ºRU_735 |42.29Mb
  - ğŸ‡ºğŸ‡¸US_739 |12.56Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_740 |15.44Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡§ğŸ‡¬BG_734 |447.99Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - Relay_-ğŸ‡ºğŸ‡¸US_490 |41.14Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_482 |444.90Mb
  - _481 |23.71Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_518 |166.45Mb
  - _484 |36.08Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_646 |14.77Mb
  - _642 |11.77Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_647 |14.62Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_650 |14.46Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_651 |41.44Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_502 |57.37Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_652 |11.73Mb
  - _649 |20.24Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_659 |11.84Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_627 |12.55Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_660 |21.72Mb
  - disney_FR |36.30Mb
  - disney_FR |27.70Mb
  - ğŸ‡§ğŸ‡·BR_667 |20.73Mb
  - _653 |90.52Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_666 |11.47Mb
  - Relay_ğŸ‡¬ğŸ‡§GB-ğŸ‡³ğŸ‡±NL_670 |497.41Mb
  - Relay_ğŸ‡¬ğŸ‡§GB-ğŸ‡³ğŸ‡±NL_671 |498.55Mb
  - ğŸ‡¬ğŸ‡§GB_672 |179.36Mb
  - ğŸ‡¬ğŸ‡§GB_673 |62.21Mb
  - ğŸ‡­ğŸ‡°HK_678 |23.88Mb
  - ğŸ‡±ğŸ‡¹LT_726 |89.58Mb
  - ğŸ‡²ğŸ‡½MX_727 |39.79Mb
  - ğŸ‡­ğŸ‡°HK_705 |83.84Mb
  - ğŸ‡­ğŸ‡°HK_709 |20.82Mb
  - Relay_ğŸ‡¯ğŸ‡µJP-ğŸ‡¯ğŸ‡µJP_721 |14.63Mb
  - Relay_ğŸ‡­ğŸ‡°HK-ğŸ‡ºğŸ‡¸US_690 |18.48Mb
  - Relay_ğŸ‡°ğŸ‡·KR-ğŸ‡°ğŸ‡·KR_724 |16.56Mb
  - ğŸ‡¸ğŸ‡¬SG_730 |11.17Mb
  - ğŸ‡²ğŸ‡¾MY_728 |30.39Mb
  - ğŸ‡ºğŸ‡¸US_736 |138.99Mb
  - ğŸ‡ºğŸ‡¸US_737 |42.69Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_741 |40.88Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡·ğŸ‡ºRU_735 |42.29Mb
  - ğŸ‡ºğŸ‡¸US_739 |12.56Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_740 |15.44Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡§ğŸ‡¬BG_734 |447.99Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
