port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: disney_netflix_US |58.62Mb
  server: 45.150.52.40
  type: vmess
  port: 443
  uuid: c31777a1-2ee6-4864-db4c-a79fcbc8188b
  alterId: 0
  cipher: auto
  network: ws
  servername: xsj011-3.facai2024.com
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /c31777a1
- name: disney_netflix_FR |167.00Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 40433
  uuid: d8fd8955-78db-49ba-d86f-3e4729f6ac4d
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_MD |552.27Mb
  server: 185.153.197.5
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: netflix_SG |11.14Mb
  server: 160.16.153.13
  type: trojan
  port: 3145
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: disney_netflix_US |46.18Mb
  server: 160.16.106.144
  type: trojan
  port: 4054
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: netflix_JP |20.30Mb
  server: 160.16.242.183
  type: trojan
  port: 1331
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: disney_netflix_US |45.81Mb
  server: 160.16.89.176
  type: trojan
  port: 4054
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: ğŸ‡²ğŸ‡½MX_79 |39.28Mb
  server: 216.238.89.53
  type: vmess
  country: ğŸ‡²ğŸ‡½MX
  port: 57283
  uuid: 1a5aafc0-6482-451d-fe76-6875b7818579
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_FR |222.34Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 27092
  uuid: a0596ba6-72a3-4366-8992-77088da65bd8
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_US |40.31Mb
  server: 38.14.99.163
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 59807
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: auto
  network: tcp
  servername: 38.14.99.163
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_HK |20.23Mb
  server: 58.152.25.242
  type: trojan
  port: 443
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: disney_HK |13.42Mb
  server: 58.152.30.120
  type: trojan
  port: 443
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: disney_NL |38.83Mb
  server: 109.71.246.210
  type: ss
  country: ğŸ‡·ğŸ‡ºRU
  port: 56689
  password: YQCSKoCF3QazW8YlvDBWA4
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_83 |31.22Mb
  server: 45.83.22.118
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 8443
  password: 6af24790-76c9-49d3-bbe0-01285239e57d
  cipher: aes-256-gcm
- name: netflix_JP |64.31Mb
  server: 45.83.22.118
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 5223
  password: NS8BriBL9gcPEHTXiN66aT
  cipher: chacha20-ietf-poly1305
- name: _39 |95.34Mb
  server: pupas-shirting-unsung.freesocks.work
  type: ss
  port: 443
  udp: true
  password: p78naCf2EfOlRSLTX0wFVx
  cipher: chacha20-ietf-poly1305
- name: Relay_-ğŸ‡¸ğŸ‡¬SG_38 |16.76Mb
  server: clr.ducks.tel
  type: ss
  port: 17844
  password: '907560230'
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_86 |22.34Mb
  server: 45.136.12.37
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 38141
  uuid: fd291be6-b48d-43a1-da38-66c7f80e2f80
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_US |13.40Mb
  server: cf.fovi.tk
  type: vmess
  country: ğŸZZ
  port: 443
  uuid: bf67437e-6c90-45ca-abc2-c7240a5ce2aa
  alterId: 0
  cipher: auto
  network: ws
  servername: foxlux.fovi.tk
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /eisasqa
    headers:
      HOST: foxlux.fovi.tk
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - disney_netflix_US |58.62Mb
  - disney_netflix_FR |167.00Mb
  - disney_MD |552.27Mb
  - netflix_SG |11.14Mb
  - disney_netflix_US |46.18Mb
  - netflix_JP |20.30Mb
  - disney_netflix_US |45.81Mb
  - ğŸ‡²ğŸ‡½MX_79 |39.28Mb
  - disney_netflix_FR |222.34Mb
  - disney_netflix_US |40.31Mb
  - disney_HK |20.23Mb
  - disney_HK |13.42Mb
  - disney_NL |38.83Mb
  - ğŸ‡ºğŸ‡¸US_83 |31.22Mb
  - netflix_JP |64.31Mb
  - _39 |95.34Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_38 |16.76Mb
  - ğŸ‡ºğŸ‡¸US_86 |22.34Mb
  - disney_netflix_US |13.40Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - disney_netflix_US |58.62Mb
  - disney_netflix_FR |167.00Mb
  - disney_MD |552.27Mb
  - netflix_SG |11.14Mb
  - disney_netflix_US |46.18Mb
  - netflix_JP |20.30Mb
  - disney_netflix_US |45.81Mb
  - ğŸ‡²ğŸ‡½MX_79 |39.28Mb
  - disney_netflix_FR |222.34Mb
  - disney_netflix_US |40.31Mb
  - disney_HK |20.23Mb
  - disney_HK |13.42Mb
  - disney_NL |38.83Mb
  - ğŸ‡ºğŸ‡¸US_83 |31.22Mb
  - netflix_JP |64.31Mb
  - _39 |95.34Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_38 |16.76Mb
  - ğŸ‡ºğŸ‡¸US_86 |22.34Mb
  - disney_netflix_US |13.40Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
