port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: ğŸ‡¨ğŸ‡¦CA_43 |16.34Mb
  server: 138.197.153.10
  type: ss
  country: ğŸ‡¨ğŸ‡¦CA
  port: 8080
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: ğŸ‡¨ğŸ‡¦CA_44 |221.37Mb
  server: 137.184.174.93
  type: ss
  country: ğŸ‡¨ğŸ‡¦CA
  port: 8080
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: Relay_ğŸ‡¨ğŸ‡¦CA-ğŸ‡¨ğŸ‡¦CA_46 |735.00Mb
  server: ssca.irundns.net
  type: ssr
  country: ğŸ‡¨ğŸ‡¦CA
  port: 443
  password: $$Turb0VPN$$
  cipher: aes-128-cfb
  protocol: auth_aes128_md5
  obfs: http_post
- name: ğŸ‡©ğŸ‡ªDE_74 |189.47Mb
  server: 81.19.141.45
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 443
  password: rC23nT4eVDHF06wmuyvSUe
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡©ğŸ‡ªDE_62 |13.38Mb
  server: 18.199.176.226
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡©ğŸ‡ªDE_66 |36.49Mb
  server: 3.123.25.149
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡©ğŸ‡ªDE_50 |19.26Mb
  server: 3.127.136.134
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡©ğŸ‡ªDE_68 |21.71Mb
  server: 35.159.233.191
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡©ğŸ‡ªDE_59 |13.25Mb
  server: 3.79.57.79
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡¨ğŸ‡¿CZ_48 |29.46Mb
  server: 185.193.102.7
  type: ss
  country: ğŸ‡¨ğŸ‡¿CZ
  port: 57456
  password: 360e21d21977dc11
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡©ğŸ‡ªDE_81 |54.33Mb
  server: 57.129.24.131
  type: vmess
  country: ğŸ‡©ğŸ‡ªDE
  port: 443
  uuid: 03fcc618-b93d-6796-6aed-8a38c975d581
  alterId: 1
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: linkvws
- name: ğŸ‡©ğŸ‡ªDE_78 |14.17Mb
  server: 81.19.141.45
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 443
  password: LZ3pHFUBXtKKhaSrL9zLCs
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ªğŸ‡¸ES_86 |10.54Mb
  server: 194.87.45.189
  type: ss
  country: ğŸ‡ªğŸ‡¸ES
  port: 443
  password: 676zALNF1CckrwJ6HGjRKl
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡«ğŸ‡·FR_125 |60.18Mb
  server: 57.129.132.223
  type: vmess
  country: ğŸ‡«ğŸ‡·FR
  port: 80
  uuid: a25cbf11-2908-4a1b-a3a8-9a571777dca3
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
  ws-opts:
    path: /vmess/
- name: ğŸ‡¬ğŸ‡§GB_128 |10.05Mb
  server: 89.185.84.185
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: ozSHXLRuO7JckCvhgLjLaU
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_126 |19.49Mb
  server: 89.185.84.185
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: ocLhdiEXutNDlofHdfKPJB
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_127 |21.76Mb
  server: 89.185.84.185
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: teojx0gaa5ctzJ7m0VoXky
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_132 |19.17Mb
  server: 89.185.84.185
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: FXjMQIem0uShGvRzOpfyib
  cipher: chacha20-ietf-poly1305
- name: Pool_ğŸ‡¬ğŸ‡§GB_134 |13.37Mb
  server: 79.127.233.170
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ğŸ‡ªğŸ‡¸ES_99 |14.13Mb
  server: 194.87.45.189
  type: ss
  country: ğŸ‡ªğŸ‡¸ES
  port: 443
  password: bwCWtYQWtc4ez14JGe7K51
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_136 |10.03Mb
  server: 89.185.84.185
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: m8V5Orkxu2ob8LH24OFobn
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_139 |18.17Mb
  server: 89.185.84.185
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: gbCXg98Ecfx15al9somp9w
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_141 |12.50Mb
  server: 89.185.84.185
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: V9gJ8OOLGreg27vYV5HSd3
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_145 |13.87Mb
  server: 89.185.84.185
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: xAtN0lzbVwFASy3wi6pVq4
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_147 |13.97Mb
  server: 89.185.84.185
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: IP77QXJz3YEA90m7miLOBu
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_149 |18.62Mb
  server: 89.185.84.185
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: 5cX4v5smGo5hJR6HBDGz4E
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_148 |55.20Mb
  server: 89.185.84.185
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: 2kCbzhE1x9M8mfqzDEBeyL
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_150 |18.54Mb
  server: 89.185.84.185
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: 6D3AybGUDufEK4xulpE7zj
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_152 |18.65Mb
  server: 89.185.84.185
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: IKM7Oo8MqE5gaba7mifgyx
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_155 |10.94Mb
  server: 89.185.84.185
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: RCep1UaygXjYEdFS9kOsm3
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_158 |55.41Mb
  server: 89.185.84.185
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: ThG46MiCadQCj21AVZBpdG
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_154 |47.93Mb
  server: 213.109.147.242
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 62685
  password: VpKABcOpNNA0l5G2AVOmw8
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_161 |53.98Mb
  server: 89.185.84.185
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: B2ISJ3faDXlkRUXUeQu182
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_162 |36.66Mb
  server: 18.135.29.154
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡¬ğŸ‡§GB_165 |47.38Mb
  server: 18.169.158.38
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡¬ğŸ‡§GB_164 |20.44Mb
  server: 89.185.84.185
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: iEc68ruj1qOx8hjh1KWZmc
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸ‡®ğŸ‡·IR-ğŸ‡³ğŸ‡±NL_185 |35.41Mb
  server: 151.242.251.131
  type: ss
  country: ğŸ‡®ğŸ‡·IR
  port: 8080
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡®ğŸ‡·IR_186 |21.80Mb
  server: 151.242.251.147
  type: ss
  country: ğŸ‡®ğŸ‡·IR
  port: 8080
  password: QCXDxuDlTTMD7jtgHUjIoj
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡­ğŸ‡°HK_171 |94.16Mb
  server: 62.60.233.219
  type: ss
  country: ğŸ‡­ğŸ‡°HK
  port: 55922
  password: B5NTTp0zOY7xFiIVj8ScNh
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡®ğŸ‡¶IQ_178 |49.18Mb
  server: 81.90.31.219
  type: ss
  country: ğŸ‡®ğŸ‡¶IQ
  port: 443
  password: mKvt7CQhT6eUntXD5iB0ke
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_199 |53.45Mb
  server: 45.87.175.171
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: QCXDxuDlTTMD7jtgHUjIoj
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡²ğŸ‡½MX_213 |11.91Mb
  server: 147.78.1.27
  type: ss
  country: ğŸ‡²ğŸ‡½MX
  port: 990
  password: f8f7aCzcPKbsF8p3
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_203 |10.13Mb
  server: 45.87.175.171
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: 1RWwXhwfAB5gAEozU4G2Pg
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_206 |11.02Mb
  server: 45.87.175.58
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡³ğŸ‡±NL_218 |13.85Mb
  server: 193.29.139.184
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 8080
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¯ğŸ‡µJP_191 |22.35Mb
  server: 45.32.45.45
  type: vmess
  country: ğŸ‡¯ğŸ‡µJP
  port: 14760
  uuid: dbf7a6e4-d518-4f9b-a55e-27ef892ffac1
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡³ğŸ‡±NL_219 |93.39Mb
  server: 193.29.139.160
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 8080
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡³ğŸ‡±NL_222 |11.77Mb
  server: 193.29.139.177
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 8080
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡³ğŸ‡±NL_224 |13.28Mb
  server: 193.29.139.206
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 8080
  password: 4a2rfixophdjffa8KVA4Aa
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_297 |21.18Mb
  server: 3.137.215.129
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡ºğŸ‡¸US_303 |10.44Mb
  server: 3.141.46.88
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡µğŸ‡±PL_243 |11.54Mb
  server: 217.30.10.70
  type: ss
  country: ğŸ‡µğŸ‡±PL
  port: 9003
  password: JdmRK9gMEqFgs8nP
  cipher: aes-256-cfb
- name: ğŸ‡µğŸ‡±PL_237 |101.49Mb
  server: 77.83.246.74
  type: ss
  country: ğŸ‡µğŸ‡±PL
  port: 443
  password: 3lMY9rECUubSUVrQEeF2KC
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡µğŸ‡±PL_258 |12.20Mb
  server: 217.30.10.70
  type: ss
  country: ğŸ‡µğŸ‡±PL
  port: 9059
  password: 9XwYyZsK8SNzQDtY
  cipher: aes-256-cfb
- name: Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_320 |110.71Mb
  server: 193.124.24.247
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 6504
  uuid: 7ceb165c-9aff-4ab7-ce9e-1df31a5ed911
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_321 |70.03Mb
  server: 193.124.24.247
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 6514
  uuid: c362d735-01a8-48eb-baa2-ae7aa63bfdc3
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡ºğŸ‡¸US_305 |19.30Mb
  server: 38.91.102.40
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 5003
  password: g5MeD6Ft3CWlJId
  cipher: aes-256-gcm
- name: Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_322 |180.15Mb
  server: 193.124.24.247
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 6513
  uuid: 5cf7fcbc-e2c1-42c4-d0d7-79c45a7d588d
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡µğŸ‡±PL_264 |18.17Mb
  server: 77.83.246.74
  type: ss
  country: ğŸ‡µğŸ‡±PL
  port: 443
  password: 0fV7k5wmlkPk2TNmx22rCQ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡·ğŸ‡ºRU_272 |194.39Mb
  server: 80.66.72.11
  type: ss
  country: ğŸ‡·ğŸ‡ºRU
  port: 35291
  password: pPMNzFdvbgWRPXaFKZmsFW
  cipher: chacha20-ietf-poly1305
- name: Pool_ğŸ‡ºğŸ‡¸US_319 |19.97Mb
  server: 165.140.216.141
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  uuid: e7d72a8d-26f2-4b54-b366-0c43e0bcba7d
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_324 |319.36Mb
  server: 193.124.24.247
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 6507
  uuid: 3003e094-707c-4dbb-faca-4b8d579bc604
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_325 |447.61Mb
  server: 193.124.24.247
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 6508
  uuid: b68fead5-5b0b-43a1-c34a-804467f0f368
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_326 |86.85Mb
  server: 193.124.24.247
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 6511
  uuid: 5ef4e89b-262f-4c74-e793-c7332079f251
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_328 |372.50Mb
  server: 193.124.24.247
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 6510
  uuid: 8f44f672-e53b-44fb-b502-c886d37107b5
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡·ğŸ‡ºRU_271 |41.28Mb
  server: 5.129.201.43
  type: ss
  country: ğŸ‡·ğŸ‡ºRU
  port: 23256
  password: yALtyAtHfbw1Vu4pqh6wUc
  cipher: chacha20-ietf-poly1305
- name: Pool_ğŸ‡­ğŸ‡°HK_172 |183.00Mb
  server: 150.107.46.21
  type: ssr
  country: ğŸ‡­ğŸ‡°HK
  port: 8083
  password: iFqnzSscN
  cipher: aes-256-cfb
  protocol: origin
  obfs: tls1.2_ticket_auth
- name: disney_US |14.83Mb
  server: 154.29.158.139
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 12299
  uuid: cccfe679-fbd0-4402-caf2-67e919db436f
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡ºğŸ‡¸US_331 |894.88Mb
  server: 142.171.237.17
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 1988
  uuid: aed0feeb-1283-4b7d-b3a4-71ef038d59af
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡ºğŸ‡¸US_330 |879.64Mb
  server: 38.34.24.196
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 20522
  uuid: f65ae5d8-f779-4ab2-8ba3-e4d46d34ef9d
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
  ws-opts:
    path: /telegram_@sswia
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - ğŸ‡¨ğŸ‡¦CA_43 |16.34Mb
  - ğŸ‡¨ğŸ‡¦CA_44 |221.37Mb
  - Relay_ğŸ‡¨ğŸ‡¦CA-ğŸ‡¨ğŸ‡¦CA_46 |735.00Mb
  - ğŸ‡©ğŸ‡ªDE_74 |189.47Mb
  - ğŸ‡©ğŸ‡ªDE_62 |13.38Mb
  - ğŸ‡©ğŸ‡ªDE_66 |36.49Mb
  - ğŸ‡©ğŸ‡ªDE_50 |19.26Mb
  - ğŸ‡©ğŸ‡ªDE_68 |21.71Mb
  - ğŸ‡©ğŸ‡ªDE_59 |13.25Mb
  - ğŸ‡¨ğŸ‡¿CZ_48 |29.46Mb
  - ğŸ‡©ğŸ‡ªDE_81 |54.33Mb
  - ğŸ‡©ğŸ‡ªDE_78 |14.17Mb
  - ğŸ‡ªğŸ‡¸ES_86 |10.54Mb
  - ğŸ‡«ğŸ‡·FR_125 |60.18Mb
  - ğŸ‡¬ğŸ‡§GB_128 |10.05Mb
  - ğŸ‡¬ğŸ‡§GB_126 |19.49Mb
  - ğŸ‡¬ğŸ‡§GB_127 |21.76Mb
  - ğŸ‡¬ğŸ‡§GB_132 |19.17Mb
  - Pool_ğŸ‡¬ğŸ‡§GB_134 |13.37Mb
  - ğŸ‡ªğŸ‡¸ES_99 |14.13Mb
  - ğŸ‡¬ğŸ‡§GB_136 |10.03Mb
  - ğŸ‡¬ğŸ‡§GB_139 |18.17Mb
  - ğŸ‡¬ğŸ‡§GB_141 |12.50Mb
  - ğŸ‡¬ğŸ‡§GB_145 |13.87Mb
  - ğŸ‡¬ğŸ‡§GB_147 |13.97Mb
  - ğŸ‡¬ğŸ‡§GB_149 |18.62Mb
  - ğŸ‡¬ğŸ‡§GB_148 |55.20Mb
  - ğŸ‡¬ğŸ‡§GB_150 |18.54Mb
  - ğŸ‡¬ğŸ‡§GB_152 |18.65Mb
  - ğŸ‡¬ğŸ‡§GB_155 |10.94Mb
  - ğŸ‡¬ğŸ‡§GB_158 |55.41Mb
  - ğŸ‡¬ğŸ‡§GB_154 |47.93Mb
  - ğŸ‡¬ğŸ‡§GB_161 |53.98Mb
  - ğŸ‡¬ğŸ‡§GB_162 |36.66Mb
  - ğŸ‡¬ğŸ‡§GB_165 |47.38Mb
  - ğŸ‡¬ğŸ‡§GB_164 |20.44Mb
  - Relay_ğŸ‡®ğŸ‡·IR-ğŸ‡³ğŸ‡±NL_185 |35.41Mb
  - ğŸ‡®ğŸ‡·IR_186 |21.80Mb
  - ğŸ‡­ğŸ‡°HK_171 |94.16Mb
  - ğŸ‡®ğŸ‡¶IQ_178 |49.18Mb
  - ğŸ‡±ğŸ‡¹LT_199 |53.45Mb
  - ğŸ‡²ğŸ‡½MX_213 |11.91Mb
  - ğŸ‡±ğŸ‡¹LT_203 |10.13Mb
  - ğŸ‡±ğŸ‡¹LT_206 |11.02Mb
  - ğŸ‡³ğŸ‡±NL_218 |13.85Mb
  - ğŸ‡¯ğŸ‡µJP_191 |22.35Mb
  - ğŸ‡³ğŸ‡±NL_219 |93.39Mb
  - ğŸ‡³ğŸ‡±NL_222 |11.77Mb
  - ğŸ‡³ğŸ‡±NL_224 |13.28Mb
  - ğŸ‡ºğŸ‡¸US_297 |21.18Mb
  - ğŸ‡ºğŸ‡¸US_303 |10.44Mb
  - ğŸ‡µğŸ‡±PL_243 |11.54Mb
  - ğŸ‡µğŸ‡±PL_237 |101.49Mb
  - ğŸ‡µğŸ‡±PL_258 |12.20Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_320 |110.71Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_321 |70.03Mb
  - ğŸ‡ºğŸ‡¸US_305 |19.30Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_322 |180.15Mb
  - ğŸ‡µğŸ‡±PL_264 |18.17Mb
  - ğŸ‡·ğŸ‡ºRU_272 |194.39Mb
  - Pool_ğŸ‡ºğŸ‡¸US_319 |19.97Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_324 |319.36Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_325 |447.61Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_326 |86.85Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_328 |372.50Mb
  - ğŸ‡·ğŸ‡ºRU_271 |41.28Mb
  - Pool_ğŸ‡­ğŸ‡°HK_172 |183.00Mb
  - disney_US |14.83Mb
  - ğŸ‡ºğŸ‡¸US_331 |894.88Mb
  - ğŸ‡ºğŸ‡¸US_330 |879.64Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - ğŸ‡¨ğŸ‡¦CA_43 |16.34Mb
  - ğŸ‡¨ğŸ‡¦CA_44 |221.37Mb
  - Relay_ğŸ‡¨ğŸ‡¦CA-ğŸ‡¨ğŸ‡¦CA_46 |735.00Mb
  - ğŸ‡©ğŸ‡ªDE_74 |189.47Mb
  - ğŸ‡©ğŸ‡ªDE_62 |13.38Mb
  - ğŸ‡©ğŸ‡ªDE_66 |36.49Mb
  - ğŸ‡©ğŸ‡ªDE_50 |19.26Mb
  - ğŸ‡©ğŸ‡ªDE_68 |21.71Mb
  - ğŸ‡©ğŸ‡ªDE_59 |13.25Mb
  - ğŸ‡¨ğŸ‡¿CZ_48 |29.46Mb
  - ğŸ‡©ğŸ‡ªDE_81 |54.33Mb
  - ğŸ‡©ğŸ‡ªDE_78 |14.17Mb
  - ğŸ‡ªğŸ‡¸ES_86 |10.54Mb
  - ğŸ‡«ğŸ‡·FR_125 |60.18Mb
  - ğŸ‡¬ğŸ‡§GB_128 |10.05Mb
  - ğŸ‡¬ğŸ‡§GB_126 |19.49Mb
  - ğŸ‡¬ğŸ‡§GB_127 |21.76Mb
  - ğŸ‡¬ğŸ‡§GB_132 |19.17Mb
  - Pool_ğŸ‡¬ğŸ‡§GB_134 |13.37Mb
  - ğŸ‡ªğŸ‡¸ES_99 |14.13Mb
  - ğŸ‡¬ğŸ‡§GB_136 |10.03Mb
  - ğŸ‡¬ğŸ‡§GB_139 |18.17Mb
  - ğŸ‡¬ğŸ‡§GB_141 |12.50Mb
  - ğŸ‡¬ğŸ‡§GB_145 |13.87Mb
  - ğŸ‡¬ğŸ‡§GB_147 |13.97Mb
  - ğŸ‡¬ğŸ‡§GB_149 |18.62Mb
  - ğŸ‡¬ğŸ‡§GB_148 |55.20Mb
  - ğŸ‡¬ğŸ‡§GB_150 |18.54Mb
  - ğŸ‡¬ğŸ‡§GB_152 |18.65Mb
  - ğŸ‡¬ğŸ‡§GB_155 |10.94Mb
  - ğŸ‡¬ğŸ‡§GB_158 |55.41Mb
  - ğŸ‡¬ğŸ‡§GB_154 |47.93Mb
  - ğŸ‡¬ğŸ‡§GB_161 |53.98Mb
  - ğŸ‡¬ğŸ‡§GB_162 |36.66Mb
  - ğŸ‡¬ğŸ‡§GB_165 |47.38Mb
  - ğŸ‡¬ğŸ‡§GB_164 |20.44Mb
  - Relay_ğŸ‡®ğŸ‡·IR-ğŸ‡³ğŸ‡±NL_185 |35.41Mb
  - ğŸ‡®ğŸ‡·IR_186 |21.80Mb
  - ğŸ‡­ğŸ‡°HK_171 |94.16Mb
  - ğŸ‡®ğŸ‡¶IQ_178 |49.18Mb
  - ğŸ‡±ğŸ‡¹LT_199 |53.45Mb
  - ğŸ‡²ğŸ‡½MX_213 |11.91Mb
  - ğŸ‡±ğŸ‡¹LT_203 |10.13Mb
  - ğŸ‡±ğŸ‡¹LT_206 |11.02Mb
  - ğŸ‡³ğŸ‡±NL_218 |13.85Mb
  - ğŸ‡¯ğŸ‡µJP_191 |22.35Mb
  - ğŸ‡³ğŸ‡±NL_219 |93.39Mb
  - ğŸ‡³ğŸ‡±NL_222 |11.77Mb
  - ğŸ‡³ğŸ‡±NL_224 |13.28Mb
  - ğŸ‡ºğŸ‡¸US_297 |21.18Mb
  - ğŸ‡ºğŸ‡¸US_303 |10.44Mb
  - ğŸ‡µğŸ‡±PL_243 |11.54Mb
  - ğŸ‡µğŸ‡±PL_237 |101.49Mb
  - ğŸ‡µğŸ‡±PL_258 |12.20Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_320 |110.71Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_321 |70.03Mb
  - ğŸ‡ºğŸ‡¸US_305 |19.30Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_322 |180.15Mb
  - ğŸ‡µğŸ‡±PL_264 |18.17Mb
  - ğŸ‡·ğŸ‡ºRU_272 |194.39Mb
  - Pool_ğŸ‡ºğŸ‡¸US_319 |19.97Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_324 |319.36Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_325 |447.61Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_326 |86.85Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_328 |372.50Mb
  - ğŸ‡·ğŸ‡ºRU_271 |41.28Mb
  - Pool_ğŸ‡­ğŸ‡°HK_172 |183.00Mb
  - disney_US |14.83Mb
  - ğŸ‡ºğŸ‡¸US_331 |894.88Mb
  - ğŸ‡ºğŸ‡¸US_330 |879.64Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
