port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: _198 |10.30Mb
  server: 104.192.227.162
  type: ss
  port: 443
  udp: true
  password: CdazellqFPXP0sZPMl7MZG
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¨ğŸ‡¦CA_222 |435.28Mb
  server: 138.197.153.10
  type: ss
  country: ğŸ‡¨ğŸ‡¦CA
  port: 8080
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: _196 |10.08Mb
  server: 78.129.140.11
  type: ss
  port: 443
  udp: true
  password: hUVtUb8VuWMjycCCGF3JzB
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡§ğŸ‡¬BG_212 |50.13Mb
  server: 94.156.250.122
  type: ss
  country: ğŸ‡§ğŸ‡¬BG
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡§ğŸ‡ªBE_208 |200.54Mb
  server: 192.71.249.71
  type: ss
  country: ğŸ‡§ğŸ‡ªBE
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: _199 |48.25Mb
  server: 192.71.249.108
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¨ğŸ‡¦CA_225 |10.15Mb
  server: 51.79.102.253
  type: vmess
  country: ğŸ‡¨ğŸ‡¦CA
  port: 80
  uuid: 58fe1542-5290-40ad-815a-77707a81afe5
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
  ws-opts:
    path: /IOebhLMhl1CTbFHbL95myfRX2
- name: _193 |10.03Mb
  server: ie01.giamping.com
  type: ss
  port: 8080
  udp: true
  password: 42000e02-6b4d-46ad-a572-80db7db2a9ce
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¦ğŸ‡¹AT_205 |188.27Mb
  server: 151.236.11.221
  type: ss
  country: ğŸ‡¦ğŸ‡¹AT
  port: 8443
  password: kNAssqfNR8hhvm9rSSJvhq
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡§ğŸ‡·BR_214 |29.15Mb
  server: 185.192.124.188
  type: ss
  country: ğŸ‡§ğŸ‡·BR
  port: 990
  password: f8f7aCzcPKbsF8p3
  cipher: chacha20-ietf-poly1305
- name: Pool_ğŸ‡¬ğŸ‡§GB_271 |10.20Mb
  server: 79.127.233.170
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ğŸ‡§ğŸ‡·BR_213 |122.03Mb
  server: 38.54.57.90
  type: ss
  country: ğŸ‡§ğŸ‡·BR
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ğŸ‡«ğŸ‡·FR_249 |14.53Mb
  server: 83.147.216.70
  type: ss
  country: ğŸ‡«ğŸ‡·FR
  port: 64519
  password: MPFzoWp2cXcJ2xrlOGleaf
  cipher: chacha20-ietf-poly1305
- name: Pool_ğŸ‡¬ğŸ‡§GB_270 |201.52Mb
  server: 64.176.184.129
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 1866
  password: oXGp1+ihlfKg826H
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡«ğŸ‡·FR_250 |13.01Mb
  server: 83.147.216.70
  type: ss
  country: ğŸ‡«ğŸ‡·FR
  port: 64519
  password: 9z4XoS0TfzxNsSqBVAWt7N
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡«ğŸ‡·FR_262 |14.15Mb
  server: 83.147.216.70
  type: ss
  country: ğŸ‡«ğŸ‡·FR
  port: 64519
  password: kmgk1sWY4Fh4dw9bxk2NBG
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_277 |200.66Mb
  server: 146.70.23.32
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: ğŸ‡«ğŸ‡·FR_254 |12.53Mb
  server: 83.147.216.70
  type: ss
  country: ğŸ‡«ğŸ‡·FR
  port: 64519
  password: BJ5nDZTulmYznHvHXhS6Z3
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡«ğŸ‡·FR_260 |11.20Mb
  server: 83.147.216.70
  type: ss
  country: ğŸ‡«ğŸ‡·FR
  port: 64519
  password: RLfa7IlzmmrwyBtI4BOJs3
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡«ğŸ‡·FR_255 |14.53Mb
  server: 83.147.216.70
  type: ss
  country: ğŸ‡«ğŸ‡·FR
  port: 64519
  password: KaKeuUdiSZJ1vl2jU8GnfY
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡«ğŸ‡·FR_267 |12.85Mb
  server: 83.147.216.70
  type: ss
  country: ğŸ‡«ğŸ‡·FR
  port: 64519
  password: YXgS8ComTam7qoesPlzlMo
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_279 |10.21Mb
  server: 89.185.84.185
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: XsMiWpupGob8IouVwYW5WC
  cipher: chacha20-ietf-poly1305
- name: Pool_ğŸ‡­ğŸ‡°HK_286 |390.00Mb
  server: 150.107.46.21
  type: ssr
  country: ğŸ‡­ğŸ‡°HK
  port: 8083
  password: iFqnzSscN
  cipher: aes-256-cfb
  protocol: origin
  obfs: tls1.2_ticket_auth
- name: ğŸ‡¯ğŸ‡µJP_319 |10.50Mb
  server: 160.16.123.124
  type: ss
  country: ğŸ‡¯ğŸ‡µJP
  port: 10087
  password: '10086'
  cipher: aes-128-gcm
- name: ğŸ‡¯ğŸ‡µJP_320 |16.35Mb
  server: 153.121.51.214
  type: ss
  country: ğŸ‡¯ğŸ‡µJP
  port: 10087
  password: '10086'
  cipher: aes-128-gcm
- name: Relay_ğŸ‡®ğŸ‡·IR-ğŸ‡³ğŸ‡±NL_312 |10.13Mb
  server: 151.242.251.153
  type: ss
  country: ğŸ‡®ğŸ‡·IR
  port: 8080
  password: o5osZg269v5zHpYjr1xY9s
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¯ğŸ‡µJP_321 |10.28Mb
  server: 153.121.43.183
  type: ss
  country: ğŸ‡¯ğŸ‡µJP
  port: 10087
  password: '10086'
  cipher: aes-128-gcm
- name: ğŸ‡¯ğŸ‡µJP_322 |181.41Mb
  server: 172.105.199.91
  type: ss
  country: ğŸ‡¯ğŸ‡µJP
  port: 8080
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: Relay_ğŸ‡®ğŸ‡·IR-ğŸ‡³ğŸ‡±NL_313 |10.14Mb
  server: 151.242.251.153
  type: ss
  country: ğŸ‡®ğŸ‡·IR
  port: 8080
  password: QCXDxuDlTTMD7jtgHUjIoj
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸ‡®ğŸ‡·IR-ğŸ‡³ğŸ‡±NL_318 |10.13Mb
  server: 151.242.251.153
  type: ss
  country: ğŸ‡®ğŸ‡·IR
  port: 8080
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸ‡®ğŸ‡·IR-ğŸ‡³ğŸ‡±NL_317 |10.14Mb
  server: 151.242.251.144
  type: ss
  country: ğŸ‡®ğŸ‡·IR
  port: 8080
  password: o5osZg269v5zHpYjr1xY9s
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_326 |10.70Mb
  server: 45.87.175.157
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_331 |10.10Mb
  server: 45.87.175.171
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_338 |10.01Mb
  server: 45.87.175.165
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: QCXDxuDlTTMD7jtgHUjIoj
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_352 |10.11Mb
  server: 45.87.175.181
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_339 |16.66Mb
  server: 45.87.175.35
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_358 |11.39Mb
  server: 45.87.175.69
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡³ğŸ‡±NL_367 |10.02Mb
  server: 193.29.139.235
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 8080
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡³ğŸ‡±NL_374 |10.17Mb
  server: 193.29.139.233
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 8080
  password: QCXDxuDlTTMD7jtgHUjIoj
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡³ğŸ‡±NL_376 |10.12Mb
  server: 77.238.224.29
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 55702
  password: S2QudBxi0vRySw4YRLloPq
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡³ğŸ‡±NL_383 |10.22Mb
  server: 109.201.152.181
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 443
  password: shadowsocks
  cipher: aes-128-cfb
- name: ğŸ‡µğŸ‡±PL_400 |158.66Mb
  server: 217.30.10.18
  type: ss
  country: ğŸ‡µğŸ‡±PL
  port: 9037
  password: TN2YqghxeFDKZfLU
  cipher: aes-256-cfb
- name: ğŸ‡µğŸ‡±PL_389 |41.94Mb
  server: 217.30.10.18
  type: ss
  country: ğŸ‡µğŸ‡±PL
  port: 9033
  password: UTJA57ypk2XKQpnm
  cipher: aes-256-cfb
- name: ğŸ‡µğŸ‡±PL_412 |158.83Mb
  server: 217.30.10.18
  type: ss
  country: ğŸ‡µğŸ‡±PL
  port: 9008
  password: y9VURyNzJWNRYEGQ
  cipher: aes-256-cfb
- name: ğŸ‡µğŸ‡±PL_388 |165.39Mb
  server: 217.30.10.18
  type: ss
  country: ğŸ‡µğŸ‡±PL
  port: 9011
  password: M3t2ZEQcMGRWBjRa
  cipher: aes-256-cfb
- name: ğŸ‡µğŸ‡±PL_405 |149.72Mb
  server: 217.30.10.18
  type: ss
  country: ğŸ‡µğŸ‡±PL
  port: 9088
  password: f8npKgNzdkss2ytn
  cipher: aes-256-cfb
- name: ğŸ‡µğŸ‡±PL_414 |13.52Mb
  server: 217.30.10.18
  type: ss
  country: ğŸ‡µğŸ‡±PL
  port: 9046
  password: NvS8N4Vf8qAGPSCL
  cipher: aes-256-cfb
- name: ğŸ‡µğŸ‡±PL_418 |12.03Mb
  server: 217.30.10.18
  type: ss
  country: ğŸ‡µğŸ‡±PL
  port: 9060
  password: ueLXVkvh4hckhErQ
  cipher: aes-256-cfb
- name: ğŸ‡ºğŸ‡¸US_484 |48.06Mb
  server: 23.157.40.101
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 7307
  password: FoOiGlkAA9yPEGP
  cipher: aes-256-gcm
- name: ğŸ‡·ğŸ‡ºRU_440 |161.40Mb
  server: 95.163.176.37
  type: ss
  country: ğŸ‡·ğŸ‡ºRU
  port: 8506
  password: n4J9KuWgBBXPBoDn0SdprD
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡µğŸ‡±PL_431 |146.95Mb
  server: 217.30.10.70
  type: ss
  country: ğŸ‡µğŸ‡±PL
  port: 9097
  password: Sn5B7jTqr76aCJT8
  cipher: aes-256-cfb
- name: ğŸ‡ºğŸ‡¸US_492 |10.40Mb
  server: 173.244.56.9
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: shadowsocks
  cipher: aes-128-gcm
- name: ğŸ‡ºğŸ‡¸US_480 |53.85Mb
  server: 67.220.95.26
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 8080
  password: 42000e02-6b4d-46ad-a572-80db7db2a9ce
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_503 |10.13Mb
  server: 173.244.56.6
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: shadowsocks
  cipher: aes-128-gcm
- name: ğŸ‡ºğŸ‡¸US_498 |10.15Mb
  server: 156.146.38.169
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: shadowsocks
  cipher: aes-128-gcm
- name: ğŸ‡ºğŸ‡¸US_497 |50.96Mb
  server: 54.227.21.67
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡·ğŸ‡ºRU_441 |149.57Mb
  server: 95.163.176.37
  type: ss
  country: ğŸ‡·ğŸ‡ºRU
  port: 8506
  password: KVe53W0gvOHIOJxXChJ5uA
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡·ğŸ‡ºRU_445 |158.34Mb
  server: 95.163.176.37
  type: ss
  country: ğŸ‡·ğŸ‡ºRU
  port: 8506
  password: VdswxetVc6AhIps18rtYbm
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡·ğŸ‡ºRU_444 |158.36Mb
  server: 95.163.176.37
  type: ss
  country: ğŸ‡·ğŸ‡ºRU
  port: 8506
  password: dURrI3V1m42NLew9vJk6XC
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_489 |10.09Mb
  server: us33.giamping.com
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 8080
  password: 42000e02-6b4d-46ad-a572-80db7db2a9ce
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_509 |51.86Mb
  server: 54.157.216.140
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡ºğŸ‡¸US_521 |51.50Mb
  server: 23.157.40.5
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 8118
  password: cdBIDV42DCwnfIN
  cipher: aes-256-gcm
- name: ğŸ‡¹ğŸ‡·TR_458 |10.97Mb
  server: 185.123.101.241
  type: ss
  country: ğŸ‡¹ğŸ‡·TR
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ğŸ‡ºğŸ‡¸US_511 |20.46Mb
  server: 167.88.61.59
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 8091
  password: PCnnH6SQSnfoS27
  cipher: aes-256-gcm
- name: ğŸ‡ºğŸ‡¸US_510 |51.45Mb
  server: 54.242.126.43
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡ºğŸ‡¸US_514 |14.47Mb
  server: 23.154.136.213
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 7307
  password: FoOiGlkAA9yPEGP
  cipher: aes-256-gcm
- name: ğŸ‡ºğŸ‡¸US_547 |13.20Mb
  server: 167.88.61.110
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 6697
  password: TEzjfAYq2IjtuoS
  cipher: aes-256-gcm
- name: ğŸ‡ºğŸ‡¸US_542 |12.09Mb
  server: 167.88.61.110
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 7306
  password: FoOiGlkAA9yPEGP
  cipher: aes-256-gcm
- name: ğŸ‡ºğŸ‡¸US_530 |10.17Mb
  server: 156.146.38.170
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: shadowsocks
  cipher: aes-128-gcm
- name: disney_US |10.10Mb
  server: 165.140.216.141
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  uuid: e7d72a8d-26f2-4b54-b366-0c43e0bcba7d
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_SG |299.30Mb
  server: 104.16.155.10
  type: vmess
  country: ğŸZZ
  port: 2052
  uuid: a1a607e6-a04c-3db6-a36f-c2a4312e2fe1
  alterId: 0
  cipher: auto
  network: ws
  servername: 100-253-62-167.s5.cn-db.top
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
  ws-opts:
    path: /dabai.in172.64.15.49
    headers:
      HOST: 100-253-62-167.s5.cn-db.top
- name: ğŸ‡ºğŸ‡¸US_519 |10.33Mb
  server: 37.19.198.160
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: shadowsocks
  cipher: aes-128-gcm
- name: ğŸ‡ºğŸ‡¸US_527 |54.46Mb
  server: 54.234.186.14
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡ºğŸ‡¸US_545 |10.15Mb
  server: 104.192.227.162
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: mFdHJA70GpF32RcCjcfVV7
  cipher: chacha20-ietf-poly1305
- name: disney_US |10.10Mb
  server: 193.124.24.230
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 6507
  uuid: 5d12135d-1676-490c-b490-b6e624c431a3
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡±ğŸ‡¹LT_327 |10.00Mb
  server: ltnl02.saint.ydns.eu
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: 1RWwXhwfAB5gAEozU4G2Pg
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_566 |289.14Mb
  server: 15.204.234.200
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 41100
  uuid: c7f169a3-2e9a-4894-ba53-7b2fa6fd08b4
  alterId: 0
  cipher: auto
  network: tcp
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡ºğŸ‡¸US_491 |71.17Mb
  server: 23.157.40.101
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 8009
  password: XKFKl2rULjIp74
  cipher: aes-256-gcm
- name: ğŸ‡ºğŸ‡¸US_508 |11.88Mb
  server: 23.157.40.101
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 8000
  password: KixLvKzwjekG00rm
  cipher: aes-256-gcm
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - _198 |10.30Mb
  - ğŸ‡¨ğŸ‡¦CA_222 |435.28Mb
  - _196 |10.08Mb
  - ğŸ‡§ğŸ‡¬BG_212 |50.13Mb
  - ğŸ‡§ğŸ‡ªBE_208 |200.54Mb
  - _199 |48.25Mb
  - ğŸ‡¨ğŸ‡¦CA_225 |10.15Mb
  - _193 |10.03Mb
  - ğŸ‡¦ğŸ‡¹AT_205 |188.27Mb
  - ğŸ‡§ğŸ‡·BR_214 |29.15Mb
  - Pool_ğŸ‡¬ğŸ‡§GB_271 |10.20Mb
  - ğŸ‡§ğŸ‡·BR_213 |122.03Mb
  - ğŸ‡«ğŸ‡·FR_249 |14.53Mb
  - Pool_ğŸ‡¬ğŸ‡§GB_270 |201.52Mb
  - ğŸ‡«ğŸ‡·FR_250 |13.01Mb
  - ğŸ‡«ğŸ‡·FR_262 |14.15Mb
  - ğŸ‡¬ğŸ‡§GB_277 |200.66Mb
  - ğŸ‡«ğŸ‡·FR_254 |12.53Mb
  - ğŸ‡«ğŸ‡·FR_260 |11.20Mb
  - ğŸ‡«ğŸ‡·FR_255 |14.53Mb
  - ğŸ‡«ğŸ‡·FR_267 |12.85Mb
  - ğŸ‡¬ğŸ‡§GB_279 |10.21Mb
  - Pool_ğŸ‡­ğŸ‡°HK_286 |390.00Mb
  - ğŸ‡¯ğŸ‡µJP_319 |10.50Mb
  - ğŸ‡¯ğŸ‡µJP_320 |16.35Mb
  - Relay_ğŸ‡®ğŸ‡·IR-ğŸ‡³ğŸ‡±NL_312 |10.13Mb
  - ğŸ‡¯ğŸ‡µJP_321 |10.28Mb
  - ğŸ‡¯ğŸ‡µJP_322 |181.41Mb
  - Relay_ğŸ‡®ğŸ‡·IR-ğŸ‡³ğŸ‡±NL_313 |10.14Mb
  - Relay_ğŸ‡®ğŸ‡·IR-ğŸ‡³ğŸ‡±NL_318 |10.13Mb
  - Relay_ğŸ‡®ğŸ‡·IR-ğŸ‡³ğŸ‡±NL_317 |10.14Mb
  - ğŸ‡±ğŸ‡¹LT_326 |10.70Mb
  - ğŸ‡±ğŸ‡¹LT_331 |10.10Mb
  - ğŸ‡±ğŸ‡¹LT_338 |10.01Mb
  - ğŸ‡±ğŸ‡¹LT_352 |10.11Mb
  - ğŸ‡±ğŸ‡¹LT_339 |16.66Mb
  - ğŸ‡±ğŸ‡¹LT_358 |11.39Mb
  - ğŸ‡³ğŸ‡±NL_367 |10.02Mb
  - ğŸ‡³ğŸ‡±NL_374 |10.17Mb
  - ğŸ‡³ğŸ‡±NL_376 |10.12Mb
  - ğŸ‡³ğŸ‡±NL_383 |10.22Mb
  - ğŸ‡µğŸ‡±PL_400 |158.66Mb
  - ğŸ‡µğŸ‡±PL_389 |41.94Mb
  - ğŸ‡µğŸ‡±PL_412 |158.83Mb
  - ğŸ‡µğŸ‡±PL_388 |165.39Mb
  - ğŸ‡µğŸ‡±PL_405 |149.72Mb
  - ğŸ‡µğŸ‡±PL_414 |13.52Mb
  - ğŸ‡µğŸ‡±PL_418 |12.03Mb
  - ğŸ‡ºğŸ‡¸US_484 |48.06Mb
  - ğŸ‡·ğŸ‡ºRU_440 |161.40Mb
  - ğŸ‡µğŸ‡±PL_431 |146.95Mb
  - ğŸ‡ºğŸ‡¸US_492 |10.40Mb
  - ğŸ‡ºğŸ‡¸US_480 |53.85Mb
  - ğŸ‡ºğŸ‡¸US_503 |10.13Mb
  - ğŸ‡ºğŸ‡¸US_498 |10.15Mb
  - ğŸ‡ºğŸ‡¸US_497 |50.96Mb
  - ğŸ‡·ğŸ‡ºRU_441 |149.57Mb
  - ğŸ‡·ğŸ‡ºRU_445 |158.34Mb
  - ğŸ‡·ğŸ‡ºRU_444 |158.36Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_489 |10.09Mb
  - ğŸ‡ºğŸ‡¸US_509 |51.86Mb
  - ğŸ‡ºğŸ‡¸US_521 |51.50Mb
  - ğŸ‡¹ğŸ‡·TR_458 |10.97Mb
  - ğŸ‡ºğŸ‡¸US_511 |20.46Mb
  - ğŸ‡ºğŸ‡¸US_510 |51.45Mb
  - ğŸ‡ºğŸ‡¸US_514 |14.47Mb
  - ğŸ‡ºğŸ‡¸US_547 |13.20Mb
  - ğŸ‡ºğŸ‡¸US_542 |12.09Mb
  - ğŸ‡ºğŸ‡¸US_530 |10.17Mb
  - disney_US |10.10Mb
  - disney_SG |299.30Mb
  - ğŸ‡ºğŸ‡¸US_519 |10.33Mb
  - ğŸ‡ºğŸ‡¸US_527 |54.46Mb
  - ğŸ‡ºğŸ‡¸US_545 |10.15Mb
  - disney_US |10.10Mb
  - ğŸ‡±ğŸ‡¹LT_327 |10.00Mb
  - ğŸ‡ºğŸ‡¸US_566 |289.14Mb
  - ğŸ‡ºğŸ‡¸US_491 |71.17Mb
  - ğŸ‡ºğŸ‡¸US_508 |11.88Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - _198 |10.30Mb
  - ğŸ‡¨ğŸ‡¦CA_222 |435.28Mb
  - _196 |10.08Mb
  - ğŸ‡§ğŸ‡¬BG_212 |50.13Mb
  - ğŸ‡§ğŸ‡ªBE_208 |200.54Mb
  - _199 |48.25Mb
  - ğŸ‡¨ğŸ‡¦CA_225 |10.15Mb
  - _193 |10.03Mb
  - ğŸ‡¦ğŸ‡¹AT_205 |188.27Mb
  - ğŸ‡§ğŸ‡·BR_214 |29.15Mb
  - Pool_ğŸ‡¬ğŸ‡§GB_271 |10.20Mb
  - ğŸ‡§ğŸ‡·BR_213 |122.03Mb
  - ğŸ‡«ğŸ‡·FR_249 |14.53Mb
  - Pool_ğŸ‡¬ğŸ‡§GB_270 |201.52Mb
  - ğŸ‡«ğŸ‡·FR_250 |13.01Mb
  - ğŸ‡«ğŸ‡·FR_262 |14.15Mb
  - ğŸ‡¬ğŸ‡§GB_277 |200.66Mb
  - ğŸ‡«ğŸ‡·FR_254 |12.53Mb
  - ğŸ‡«ğŸ‡·FR_260 |11.20Mb
  - ğŸ‡«ğŸ‡·FR_255 |14.53Mb
  - ğŸ‡«ğŸ‡·FR_267 |12.85Mb
  - ğŸ‡¬ğŸ‡§GB_279 |10.21Mb
  - Pool_ğŸ‡­ğŸ‡°HK_286 |390.00Mb
  - ğŸ‡¯ğŸ‡µJP_319 |10.50Mb
  - ğŸ‡¯ğŸ‡µJP_320 |16.35Mb
  - Relay_ğŸ‡®ğŸ‡·IR-ğŸ‡³ğŸ‡±NL_312 |10.13Mb
  - ğŸ‡¯ğŸ‡µJP_321 |10.28Mb
  - ğŸ‡¯ğŸ‡µJP_322 |181.41Mb
  - Relay_ğŸ‡®ğŸ‡·IR-ğŸ‡³ğŸ‡±NL_313 |10.14Mb
  - Relay_ğŸ‡®ğŸ‡·IR-ğŸ‡³ğŸ‡±NL_318 |10.13Mb
  - Relay_ğŸ‡®ğŸ‡·IR-ğŸ‡³ğŸ‡±NL_317 |10.14Mb
  - ğŸ‡±ğŸ‡¹LT_326 |10.70Mb
  - ğŸ‡±ğŸ‡¹LT_331 |10.10Mb
  - ğŸ‡±ğŸ‡¹LT_338 |10.01Mb
  - ğŸ‡±ğŸ‡¹LT_352 |10.11Mb
  - ğŸ‡±ğŸ‡¹LT_339 |16.66Mb
  - ğŸ‡±ğŸ‡¹LT_358 |11.39Mb
  - ğŸ‡³ğŸ‡±NL_367 |10.02Mb
  - ğŸ‡³ğŸ‡±NL_374 |10.17Mb
  - ğŸ‡³ğŸ‡±NL_376 |10.12Mb
  - ğŸ‡³ğŸ‡±NL_383 |10.22Mb
  - ğŸ‡µğŸ‡±PL_400 |158.66Mb
  - ğŸ‡µğŸ‡±PL_389 |41.94Mb
  - ğŸ‡µğŸ‡±PL_412 |158.83Mb
  - ğŸ‡µğŸ‡±PL_388 |165.39Mb
  - ğŸ‡µğŸ‡±PL_405 |149.72Mb
  - ğŸ‡µğŸ‡±PL_414 |13.52Mb
  - ğŸ‡µğŸ‡±PL_418 |12.03Mb
  - ğŸ‡ºğŸ‡¸US_484 |48.06Mb
  - ğŸ‡·ğŸ‡ºRU_440 |161.40Mb
  - ğŸ‡µğŸ‡±PL_431 |146.95Mb
  - ğŸ‡ºğŸ‡¸US_492 |10.40Mb
  - ğŸ‡ºğŸ‡¸US_480 |53.85Mb
  - ğŸ‡ºğŸ‡¸US_503 |10.13Mb
  - ğŸ‡ºğŸ‡¸US_498 |10.15Mb
  - ğŸ‡ºğŸ‡¸US_497 |50.96Mb
  - ğŸ‡·ğŸ‡ºRU_441 |149.57Mb
  - ğŸ‡·ğŸ‡ºRU_445 |158.34Mb
  - ğŸ‡·ğŸ‡ºRU_444 |158.36Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_489 |10.09Mb
  - ğŸ‡ºğŸ‡¸US_509 |51.86Mb
  - ğŸ‡ºğŸ‡¸US_521 |51.50Mb
  - ğŸ‡¹ğŸ‡·TR_458 |10.97Mb
  - ğŸ‡ºğŸ‡¸US_511 |20.46Mb
  - ğŸ‡ºğŸ‡¸US_510 |51.45Mb
  - ğŸ‡ºğŸ‡¸US_514 |14.47Mb
  - ğŸ‡ºğŸ‡¸US_547 |13.20Mb
  - ğŸ‡ºğŸ‡¸US_542 |12.09Mb
  - ğŸ‡ºğŸ‡¸US_530 |10.17Mb
  - disney_US |10.10Mb
  - disney_SG |299.30Mb
  - ğŸ‡ºğŸ‡¸US_519 |10.33Mb
  - ğŸ‡ºğŸ‡¸US_527 |54.46Mb
  - ğŸ‡ºğŸ‡¸US_545 |10.15Mb
  - disney_US |10.10Mb
  - ğŸ‡±ğŸ‡¹LT_327 |10.00Mb
  - ğŸ‡ºğŸ‡¸US_566 |289.14Mb
  - ğŸ‡ºğŸ‡¸US_491 |71.17Mb
  - ğŸ‡ºğŸ‡¸US_508 |11.88Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
