port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: disney_netflix_US |37.43Mb
  server: 38.14.99.179
  type: vmess
  port: 59807
  udp: true
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_-ğŸ‡¸ğŸ‡¬SG_140 |11.59Mb
  server: 160.16.131.243
  type: trojan
  port: 127
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡³ğŸ‡±NL_141 |45.03Mb
  server: 160.16.116.227
  type: trojan
  port: 2890
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡³ğŸ‡±NL_142 |53.84Mb
  server: 160.16.124.55
  type: trojan
  port: 4054
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¸ğŸ‡¬SG_143 |11.01Mb
  server: 153.121.44.99
  type: trojan
  port: 507
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: disney_NO |27.65Mb
  server: 107.174.114.71
  type: ss
  port: 443
  password: 595HLF3fHUuw0McM51tpvPygSIB1uf4D
  cipher: chacha20-ietf-poly1305
- name: Relay_-ğŸ‡¸ğŸ‡¬SG_144 |15.83Mb
  server: 160.16.107.37
  type: trojan
  port: 507
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: disney_MD |265.85Mb
  server: 185.153.197.5
  type: ss
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: Relay_-ğŸ‡³ğŸ‡±NL_146 |18.10Mb
  server: 160.16.236.32
  type: trojan
  port: 4054
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡³ğŸ‡±NL_148 |52.32Mb
  server: 160.16.81.84
  type: trojan
  port: 4054
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡³ğŸ‡±NL_150 |56.63Mb
  server: 153.121.39.240
  type: trojan
  port: 4054
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: disney_netflix_US |13.30Mb
  server: 160.16.151.196
  type: trojan
  port: 2890
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡³ğŸ‡±NL_151 |44.93Mb
  server: 160.16.57.238
  type: trojan
  port: 4054
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¯ğŸ‡µJP_154 |10.33Mb
  server: 160.16.72.33
  type: trojan
  port: 3093
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡³ğŸ‡±NL_157 |53.44Mb
  server: 160.16.63.16
  type: trojan
  port: 4054
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡³ğŸ‡±NL_158 |25.11Mb
  server: 160.16.131.243
  type: trojan
  port: 2890
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: disney_HK |25.88Mb
  server: 58.152.110.154
  type: trojan
  port: 443
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¯ğŸ‡µJP_160 |10.73Mb
  server: 153.121.65.107
  type: trojan
  port: 1331
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: disney_netflix_FR |35.33Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 27092
  uuid: a0596ba6-72a3-4366-8992-77088da65bd8
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_FR |37.77Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 40433
  uuid: d8fd8955-78db-49ba-d86f-3e4729f6ac4d
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡§ğŸ‡·BR_165 |19.72Mb
  server: 38.180.16.86
  type: vmess
  country: ğŸ‡§ğŸ‡·BR
  port: 36104
  uuid: E146A8CB-9D2F-449C-ADCA-8736FB
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_NL |211.48Mb
  server: 82.38.31.190
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: disney_HK |11.69Mb
  server: 58.152.25.20
  type: trojan
  port: 443
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: netflix_MX |39.55Mb
  server: 216.238.89.53
  type: vmess
  country: ğŸ‡²ğŸ‡½MX
  port: 57283
  uuid: 1a5aafc0-6482-451d-fe76-6875b7818579
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_NL |10.96Mb
  server: 82.38.31.179
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_NL |177.47Mb
  server: 82.38.31.218
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_NL |119.69Mb
  server: 45.87.175.166
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 443
  password: 1RWwXhwfAB5gAEozU4G2Pg
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡°ğŸ‡·KR_183 |10.14Mb
  server: 146.56.112.110
  type: vmess
  country: ğŸ‡°ğŸ‡·KR
  port: 8888
  uuid: e7c302f3-90d6-42dd-9d7d-94a3683a3707
  alterId: 0
  cipher: auto
  network: tcp
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_US |240.29Mb
  server: 104.192.226.106
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: netflix_AL |45.14Mb
  server: 87.121.162.249
  type: ss
  country: ğŸ‡­ğŸ‡°HK
  port: 443
  password: JGv616hMWdjfuZ00jYfq7XkBHJZrOBrg
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_NL |140.89Mb
  server: 109.71.246.210
  type: ss
  country: ğŸ‡·ğŸ‡ºRU
  port: 56689
  password: YQCSKoCF3QazW8YlvDBWA4
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_US |38.46Mb
  server: 38.14.99.163
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 59807
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: auto
  network: tcp
  servername: 38.14.99.163
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_RU |292.22Mb
  server: 38.60.223.8
  type: ss
  country: ğŸ‡·ğŸ‡ºRU
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: netflix_HK |31.59Mb
  server: 38.54.98.110
  type: vmess
  country: ğŸ‡²ğŸ‡¾MY
  port: 2052
  uuid: 665d9b8f-153d-4907-adac-de12afd9c851
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: ğŸ‡¸ğŸ‡¬SG_190 |11.02Mb
  server: 68.183.178.131
  type: vmess
  country: ğŸ‡¸ğŸ‡¬SG
  port: 58607
  uuid: c11c32cb-27b3-4afa-c0f3-fb250aa4959e
  alterId: 0
  cipher: auto
  network: ws
  servername: www.12333.monster
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /
    headers:
      HOST: www.12333.monster
- name: disney_HK |23.08Mb
  server: 45.136.12.37
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 38141
  uuid: fd291be6-b48d-43a1-da38-66c7f80e2f80
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_US |30.54Mb
  server: cf.fovi.tk
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  uuid: bf67437e-6c90-45ca-abc2-c7240a5ce2aa
  alterId: 0
  cipher: auto
  network: ws
  servername: foxlux.fovi.tk
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /eisasqa
    headers:
      HOST: foxlux.fovi.tk
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - disney_netflix_US |37.43Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_140 |11.59Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_141 |45.03Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_142 |53.84Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_143 |11.01Mb
  - disney_NO |27.65Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_144 |15.83Mb
  - disney_MD |265.85Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_146 |18.10Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_148 |52.32Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_150 |56.63Mb
  - disney_netflix_US |13.30Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_151 |44.93Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_154 |10.33Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_157 |53.44Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_158 |25.11Mb
  - disney_HK |25.88Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_160 |10.73Mb
  - disney_netflix_FR |35.33Mb
  - disney_netflix_FR |37.77Mb
  - ğŸ‡§ğŸ‡·BR_165 |19.72Mb
  - disney_netflix_NL |211.48Mb
  - disney_HK |11.69Mb
  - netflix_MX |39.55Mb
  - disney_netflix_NL |10.96Mb
  - disney_netflix_NL |177.47Mb
  - disney_netflix_NL |119.69Mb
  - ğŸ‡°ğŸ‡·KR_183 |10.14Mb
  - disney_netflix_US |240.29Mb
  - netflix_AL |45.14Mb
  - disney_netflix_NL |140.89Mb
  - disney_netflix_US |38.46Mb
  - disney_RU |292.22Mb
  - netflix_HK |31.59Mb
  - ğŸ‡¸ğŸ‡¬SG_190 |11.02Mb
  - disney_HK |23.08Mb
  - disney_netflix_US |30.54Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - disney_netflix_US |37.43Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_140 |11.59Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_141 |45.03Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_142 |53.84Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_143 |11.01Mb
  - disney_NO |27.65Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_144 |15.83Mb
  - disney_MD |265.85Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_146 |18.10Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_148 |52.32Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_150 |56.63Mb
  - disney_netflix_US |13.30Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_151 |44.93Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_154 |10.33Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_157 |53.44Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_158 |25.11Mb
  - disney_HK |25.88Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_160 |10.73Mb
  - disney_netflix_FR |35.33Mb
  - disney_netflix_FR |37.77Mb
  - ğŸ‡§ğŸ‡·BR_165 |19.72Mb
  - disney_netflix_NL |211.48Mb
  - disney_HK |11.69Mb
  - netflix_MX |39.55Mb
  - disney_netflix_NL |10.96Mb
  - disney_netflix_NL |177.47Mb
  - disney_netflix_NL |119.69Mb
  - ğŸ‡°ğŸ‡·KR_183 |10.14Mb
  - disney_netflix_US |240.29Mb
  - netflix_AL |45.14Mb
  - disney_netflix_NL |140.89Mb
  - disney_netflix_US |38.46Mb
  - disney_RU |292.22Mb
  - netflix_HK |31.59Mb
  - ğŸ‡¸ğŸ‡¬SG_190 |11.02Mb
  - disney_HK |23.08Mb
  - disney_netflix_US |30.54Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
