port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: Relay_-ğŸ‡ºğŸ‡¸US_361 |50.45Mb
  server: 82.198.246.97
  type: vmess
  port: 180
  uuid: d13fc2f5-3e05-4795-81eb-44143a09e552
  alterId: 0
  cipher: auto
  network: tcp
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_NL |259.67Mb
  server: 151.242.251.137
  type: ss
  port: 8080
  password: o5osZg269v5zHpYjr1xY9s
  cipher: chacha20-ietf-poly1305
- name: disney_PT |10.89Mb
  server: 185.231.233.112
  type: ss
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: Relay_-ğŸ‡³ğŸ‡±NL_387 |21.27Mb
  server: 160.16.63.16
  type: trojan
  port: 4054
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡³ğŸ‡±NL_392 |13.67Mb
  server: 160.16.124.55
  type: trojan
  port: 2760
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡³ğŸ‡±NL_394 |11.14Mb
  server: 160.16.124.55
  type: trojan
  port: 4054
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¸ğŸ‡¬SG_393 |11.86Mb
  server: 153.121.51.29
  type: trojan
  port: 127
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: netflix_KZ |25.88Mb
  server: 103.106.3.82
  type: ss
  port: 443
  udp: true
  password: 4SaCIazlgumYkM8FkPzlmwjpyWBDZFBk
  cipher: chacha20-ietf-poly1305
- name: disney_HK |23.64Mb
  server: 58.152.25.20
  type: trojan
  port: 443
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: _396 |14.19Mb
  server: 58.152.18.95
  type: trojan
  port: 443
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: Relay_-ğŸ‡³ğŸ‡±NL_399 |31.54Mb
  server: 160.16.236.32
  type: trojan
  port: 4054
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: disney_netflix_NL |10.18Mb
  server: 82.38.31.190
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: Relay_-ğŸ‡¯ğŸ‡µJP_400 |12.82Mb
  server: 52.195.176.26
  type: trojan
  port: 2145
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: ğŸ‡§ğŸ‡·BR_403 |23.48Mb
  server: 38.180.16.86
  type: vmess
  country: ğŸ‡§ğŸ‡·BR
  port: 36104
  uuid: E146A8CB-9D2F-449C-ADCA-8736FB
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: netflix_AL |10.38Mb
  server: 87.121.162.249
  type: ss
  country: ğŸ‡­ğŸ‡°HK
  port: 443
  password: JGv616hMWdjfuZ00jYfq7XkBHJZrOBrg
  cipher: chacha20-ietf-poly1305
- name: netflix_MX |40.01Mb
  server: 216.238.89.53
  type: vmess
  country: ğŸ‡²ğŸ‡½MX
  port: 57283
  uuid: 1a5aafc0-6482-451d-fe76-6875b7818579
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡¦ğŸ‡ºAU_402 |10.55Mb
  server: 54.252.240.128
  type: vmess
  country: ğŸ‡¦ğŸ‡ºAU
  port: 1000
  uuid: ca26a9fd-fef8-4ea7-d194-450ce4e0c67a
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: _401 |12.71Mb
  server: 112.118.116.66
  type: trojan
  port: 443
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: disney_netflix_US |17.65Mb
  server: 38.84.201.21
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 53487
  uuid: c3c1ec05-df2c-4975-9b42-e9b007564eb1
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡­ğŸ‡°HK_410 |29.42Mb
  server: 47.243.51.237
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 52801
  uuid: ef93f413-9039-4ddb-aefb-2490287df55a
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
  ws-opts:
    path: /arki?ed=2048
- name: ğŸ‡­ğŸ‡°HK_411 |128.68Mb
  server: 47.242.125.104
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 58424
  uuid: 80016399-3178-472e-86e3-129aab31a025
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
  ws-opts:
    path: /arki?ed=2048
- name: ğŸ‡­ğŸ‡°HK_412 |20.37Mb
  server: 47.242.162.148
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 31813
  uuid: 00308f3b-747a-4710-b2cb-32c8de9785a1
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
  ws-opts:
    path: /arki?ed=2048
- name: ğŸ‡­ğŸ‡°HK_414 |24.62Mb
  server: 47.242.140.52
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 48219
  uuid: 006893c6-79b1-4c44-94ff-b8bbea065f1f
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
  ws-opts:
    path: /arki?ed=2048
- name: ğŸ‡·ğŸ‡ºRU_422 |13.42Mb
  server: 45.139.26.173
  type: ss
  country: ğŸ‡·ğŸ‡ºRU
  port: 57456
  password: d3837224ed465f00
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡­ğŸ‡°HK_415 |178.47Mb
  server: 47.242.162.235
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 3787
  uuid: e748fe05-2678-4c31-84c6-14ed825b92b4
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
  ws-opts:
    path: /arki?ed=2048
- name: ğŸ‡²ğŸ‡¾MY_421 |31.73Mb
  server: 38.54.98.110
  type: vmess
  country: ğŸ‡²ğŸ‡¾MY
  port: 2052
  uuid: 665d9b8f-153d-4907-adac-de12afd9c851
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: ğŸ‡¹ğŸ‡·TR_424 |19.60Mb
  server: 185.39.204.161
  type: ss
  country: ğŸ‡¹ğŸ‡·TR
  port: 33563
  password: bSlgCoGhApOb55tIMD0zxY
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¸ğŸ‡¬SG_423 |39.54Mb
  server: 68.183.178.131
  type: vmess
  country: ğŸ‡¸ğŸ‡¬SG
  port: 58607
  uuid: c11c32cb-27b3-4afa-c0f3-fb250aa4959e
  alterId: 0
  cipher: auto
  network: ws
  servername: www.12333.monster
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /
    headers:
      HOST: www.12333.monster
- name: ğŸ‡ºğŸ‡¸US_429 |16.82Mb
  server: 45.136.12.37
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 38141
  uuid: fd291be6-b48d-43a1-da38-66c7f80e2f80
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_US |20.17Mb
  server: cf.fovi.tk
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  uuid: bf67437e-6c90-45ca-abc2-c7240a5ce2aa
  alterId: 0
  cipher: auto
  network: ws
  servername: foxlux.fovi.tk
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /eisasqa
    headers:
      HOST: foxlux.fovi.tk
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - Relay_-ğŸ‡ºğŸ‡¸US_361 |50.45Mb
  - disney_netflix_NL |259.67Mb
  - disney_PT |10.89Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_387 |21.27Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_392 |13.67Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_394 |11.14Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_393 |11.86Mb
  - netflix_KZ |25.88Mb
  - disney_HK |23.64Mb
  - _396 |14.19Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_399 |31.54Mb
  - disney_netflix_NL |10.18Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_400 |12.82Mb
  - ğŸ‡§ğŸ‡·BR_403 |23.48Mb
  - netflix_AL |10.38Mb
  - netflix_MX |40.01Mb
  - ğŸ‡¦ğŸ‡ºAU_402 |10.55Mb
  - _401 |12.71Mb
  - disney_netflix_US |17.65Mb
  - ğŸ‡­ğŸ‡°HK_410 |29.42Mb
  - ğŸ‡­ğŸ‡°HK_411 |128.68Mb
  - ğŸ‡­ğŸ‡°HK_412 |20.37Mb
  - ğŸ‡­ğŸ‡°HK_414 |24.62Mb
  - ğŸ‡·ğŸ‡ºRU_422 |13.42Mb
  - ğŸ‡­ğŸ‡°HK_415 |178.47Mb
  - ğŸ‡²ğŸ‡¾MY_421 |31.73Mb
  - ğŸ‡¹ğŸ‡·TR_424 |19.60Mb
  - ğŸ‡¸ğŸ‡¬SG_423 |39.54Mb
  - ğŸ‡ºğŸ‡¸US_429 |16.82Mb
  - disney_netflix_US |20.17Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - Relay_-ğŸ‡ºğŸ‡¸US_361 |50.45Mb
  - disney_netflix_NL |259.67Mb
  - disney_PT |10.89Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_387 |21.27Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_392 |13.67Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_394 |11.14Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_393 |11.86Mb
  - netflix_KZ |25.88Mb
  - disney_HK |23.64Mb
  - _396 |14.19Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_399 |31.54Mb
  - disney_netflix_NL |10.18Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_400 |12.82Mb
  - ğŸ‡§ğŸ‡·BR_403 |23.48Mb
  - netflix_AL |10.38Mb
  - netflix_MX |40.01Mb
  - ğŸ‡¦ğŸ‡ºAU_402 |10.55Mb
  - _401 |12.71Mb
  - disney_netflix_US |17.65Mb
  - ğŸ‡­ğŸ‡°HK_410 |29.42Mb
  - ğŸ‡­ğŸ‡°HK_411 |128.68Mb
  - ğŸ‡­ğŸ‡°HK_412 |20.37Mb
  - ğŸ‡­ğŸ‡°HK_414 |24.62Mb
  - ğŸ‡·ğŸ‡ºRU_422 |13.42Mb
  - ğŸ‡­ğŸ‡°HK_415 |178.47Mb
  - ğŸ‡²ğŸ‡¾MY_421 |31.73Mb
  - ğŸ‡¹ğŸ‡·TR_424 |19.60Mb
  - ğŸ‡¸ğŸ‡¬SG_423 |39.54Mb
  - ğŸ‡ºğŸ‡¸US_429 |16.82Mb
  - disney_netflix_US |20.17Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
