port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: Relay_-ğŸ‡ºğŸ‡¸US_263 |18.81Mb
  server: 82.198.246.97
  type: vmess
  port: 180
  uuid: d13fc2f5-3e05-4795-81eb-44143a09e552
  alterId: 0
  cipher: auto
  network: tcp
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: netflix_NL |204.38Mb
  server: 151.242.251.137
  type: ss
  port: 8080
  password: o5osZg269v5zHpYjr1xY9s
  cipher: chacha20-ietf-poly1305
- name: disney_PT |430.84Mb
  server: 185.231.233.112
  type: ss
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: Relay_-ğŸ‡³ğŸ‡±NL_330 |13.17Mb
  server: 160.16.236.32
  type: trojan
  port: 4054
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡³ğŸ‡±NL_324 |11.05Mb
  server: 160.16.124.55
  type: trojan
  port: 2760
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¸ğŸ‡¬SG_329 |18.58Mb
  server: 153.121.51.29
  type: trojan
  port: 127
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¯ğŸ‡µJP_328 |22.86Mb
  server: 52.195.176.26
  type: trojan
  port: 2145
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: Relay_-ğŸ‡³ğŸ‡±NL_331 |11.94Mb
  server: 160.16.63.16
  type: trojan
  port: 4054
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡³ğŸ‡±NL_326 |10.57Mb
  server: 160.16.124.55
  type: trojan
  port: 4054
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡³ğŸ‡±NL_333 |56.49Mb
  server: 160.16.81.84
  type: trojan
  port: 4054
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: ğŸ‡ªğŸ‡¸ES_338 |21.59Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 40433
  uuid: d8fd8955-78db-49ba-d86f-3e4729f6ac4d
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡¬ğŸ‡§GB_340 |64.42Mb
  server: 82.38.31.190
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡§ğŸ‡·BR_337 |20.68Mb
  server: 38.180.16.86
  type: vmess
  country: ğŸ‡§ğŸ‡·BR
  port: 36104
  uuid: E146A8CB-9D2F-449C-ADCA-8736FB
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡¦ğŸ‡ºAU_336 |11.73Mb
  server: 54.252.240.128
  type: vmess
  country: ğŸ‡¦ğŸ‡ºAU
  port: 1000
  uuid: ca26a9fd-fef8-4ea7-d194-450ce4e0c67a
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: netflix_NL |13.33Mb
  server: 45.87.175.166
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 443
  password: 1RWwXhwfAB5gAEozU4G2Pg
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡°ğŸ‡·KR_350 |10.36Mb
  server: 146.56.112.110
  type: vmess
  country: ğŸ‡°ğŸ‡·KR
  port: 8888
  uuid: e7c302f3-90d6-42dd-9d7d-94a3683a3707
  alterId: 0
  cipher: auto
  network: tcp
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_US |176.66Mb
  server: 38.84.201.21
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 53487
  uuid: c3c1ec05-df2c-4975-9b42-e9b007564eb1
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡­ğŸ‡°HK_345 |23.03Mb
  server: 47.242.125.104
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 58424
  uuid: 80016399-3178-472e-86e3-129aab31a025
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
  ws-opts:
    path: /arki?ed=2048
- name: ğŸ‡­ğŸ‡°HK_344 |29.42Mb
  server: 47.243.51.237
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 52801
  uuid: ef93f413-9039-4ddb-aefb-2490287df55a
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
  ws-opts:
    path: /arki?ed=2048
- name: ğŸ‡­ğŸ‡°HK_346 |25.48Mb
  server: 47.242.162.148
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 31813
  uuid: 00308f3b-747a-4710-b2cb-32c8de9785a1
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
  ws-opts:
    path: /arki?ed=2048
- name: ğŸ‡²ğŸ‡¾MY_352 |32.17Mb
  server: 38.54.98.110
  type: vmess
  country: ğŸ‡²ğŸ‡¾MY
  port: 2052
  uuid: 665d9b8f-153d-4907-adac-de12afd9c851
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: ğŸ‡¸ğŸ‡¬SG_353 |11.23Mb
  server: 68.183.178.131
  type: vmess
  country: ğŸ‡¸ğŸ‡¬SG
  port: 58607
  uuid: c11c32cb-27b3-4afa-c0f3-fb250aa4959e
  alterId: 0
  cipher: auto
  network: ws
  servername: www.12333.monster
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /
    headers:
      HOST: www.12333.monster
- name: disney_HK |19.99Mb
  server: 45.136.12.37
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 38141
  uuid: fd291be6-b48d-43a1-da38-66c7f80e2f80
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_358 |10.04Mb
  server: cf.fovi.tk
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  uuid: bf67437e-6c90-45ca-abc2-c7240a5ce2aa
  alterId: 0
  cipher: auto
  network: ws
  servername: foxlux.fovi.tk
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /eisasqa
    headers:
      HOST: foxlux.fovi.tk
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - Relay_-ğŸ‡ºğŸ‡¸US_263 |18.81Mb
  - netflix_NL |204.38Mb
  - disney_PT |430.84Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_330 |13.17Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_324 |11.05Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_329 |18.58Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_328 |22.86Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_331 |11.94Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_326 |10.57Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_333 |56.49Mb
  - ğŸ‡ªğŸ‡¸ES_338 |21.59Mb
  - ğŸ‡¬ğŸ‡§GB_340 |64.42Mb
  - ğŸ‡§ğŸ‡·BR_337 |20.68Mb
  - ğŸ‡¦ğŸ‡ºAU_336 |11.73Mb
  - netflix_NL |13.33Mb
  - ğŸ‡°ğŸ‡·KR_350 |10.36Mb
  - disney_netflix_US |176.66Mb
  - ğŸ‡­ğŸ‡°HK_345 |23.03Mb
  - ğŸ‡­ğŸ‡°HK_344 |29.42Mb
  - ğŸ‡­ğŸ‡°HK_346 |25.48Mb
  - ğŸ‡²ğŸ‡¾MY_352 |32.17Mb
  - ğŸ‡¸ğŸ‡¬SG_353 |11.23Mb
  - disney_HK |19.99Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_358 |10.04Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - Relay_-ğŸ‡ºğŸ‡¸US_263 |18.81Mb
  - netflix_NL |204.38Mb
  - disney_PT |430.84Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_330 |13.17Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_324 |11.05Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_329 |18.58Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_328 |22.86Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_331 |11.94Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_326 |10.57Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_333 |56.49Mb
  - ğŸ‡ªğŸ‡¸ES_338 |21.59Mb
  - ğŸ‡¬ğŸ‡§GB_340 |64.42Mb
  - ğŸ‡§ğŸ‡·BR_337 |20.68Mb
  - ğŸ‡¦ğŸ‡ºAU_336 |11.73Mb
  - netflix_NL |13.33Mb
  - ğŸ‡°ğŸ‡·KR_350 |10.36Mb
  - disney_netflix_US |176.66Mb
  - ğŸ‡­ğŸ‡°HK_345 |23.03Mb
  - ğŸ‡­ğŸ‡°HK_344 |29.42Mb
  - ğŸ‡­ğŸ‡°HK_346 |25.48Mb
  - ğŸ‡²ğŸ‡¾MY_352 |32.17Mb
  - ğŸ‡¸ğŸ‡¬SG_353 |11.23Mb
  - disney_HK |19.99Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_358 |10.04Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
