port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: ğŸ‡©ğŸ‡ªDE_10 | 9.85Mb
  server: 212.224.125.154
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 57456
  password: fe166c5b3465540f
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡§ğŸ‡ªBE_07 |49.64Mb
  server: 192.71.249.71
  type: ss
  country: ğŸ‡§ğŸ‡ªBE
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ğŸ‡©ğŸ‡ªDE_09 | 0.74Mb
  server: 52.59.98.7
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡©ğŸ‡ªDE_08 | 3.54Mb
  server: 54.93.205.2
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡©ğŸ‡ªDE_12 | 1.14Mb
  server: 18.156.83.254
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡©ğŸ‡ªDE_11 | 0.43Mb
  server: 18.159.61.225
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: Relay_-ğŸ‡ºğŸ‡¸US_01 |86.41Mb
  server: gyus.aifjj.asia
  type: hysteria2
  port: 30249
  udp: true
  password: 79dc600a-b63b-4406-bd79-f5f7fb0c0e52
  auth: 79dc600a-b63b-4406-bd79-f5f7fb0c0e52
  sni: gyus.aifjj.asia
  skip-cert-verify: true
- name: _05 |34.03Mb
  server: 142.93.238.172
  type: ss
  port: 80
  udp: true
  password: mdPIrGoRyIAP97jWwIkRSn
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ªğŸ‡¸ES_17 | 3.03Mb
  server: 5.188.181.41
  type: ss
  country: ğŸ‡ªğŸ‡¸ES
  port: 8443
  password: jHH8Kgfd6IXpvx2svCVG1H
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡©ğŸ‡ªDE_13 | 5.10Mb
  server: 3.64.255.57
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡©ğŸ‡ªDE_14 | 2.38Mb
  server: 3.65.226.193
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡©ğŸ‡ªDE_16 | 5.49Mb
  server: 18.193.115.141
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡©ğŸ‡ªDE_15 | 2.22Mb
  server: 18.199.92.80
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡«ğŸ‡·FR_20
  server: 62.210.88.22
  type: ss
  country: ğŸ‡«ğŸ‡·FR
  port: 443
  password: 6B6O4ts0stERkPBsofaVAk
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡«ğŸ‡®FI_19 | 9.26Mb
  server: 94.237.105.27
  type: ss
  country: ğŸ‡«ğŸ‡®FI
  port: 8443
  password: Qcsukn6qSHlKiTnh08a9Cb
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡«ğŸ‡®FI_18 |36.21Mb
  server: 65.21.243.22
  type: ss
  country: ğŸ‡«ğŸ‡®FI
  port: 31348
  password: mZGUFWMAlfWqI4vP58zw9DAHxR8TZLndKkvRgHHFa9eqWdnx
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_23 | 9.84Mb
  server: 78.129.140.11
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: bBmY8pBEH84DLOwbOzyCaL
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡«ğŸ‡·FR_21
  server: 62.210.88.22
  type: ss
  country: ğŸ‡«ğŸ‡·FR
  port: 443
  password: CJXCIudNfb4fCHdNOEXQCX
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡®ğŸ‡ªIE_28 |14.89Mb
  server: 3.254.154.32
  type: ss
  country: ğŸ‡®ğŸ‡ªIE
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡®ğŸ‡ªIE_29 | 3.23Mb
  server: 34.243.228.158
  type: ss
  country: ğŸ‡®ğŸ‡ªIE
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡­ğŸ‡°HK_25 |141.04Mb
  server: 103.149.183.154
  type: ss
  country: ğŸ‡­ğŸ‡°HK
  port: 8388
  password: asd123456
  cipher: chacha20-ietf
- name: ğŸ‡±ğŸ‡¹LT_32 |33.11Mb
  server: 45.87.175.10
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡®ğŸ‡¸IS_30 | 0.80Mb
  server: 37.235.49.152
  type: ss
  country: ğŸ‡®ğŸ‡¸IS
  port: 990
  password: f8f7aCzcPKbsF8p3
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡³ğŸ‡´NO_33 | 2.17Mb
  server: 185.213.23.226
  type: ss
  country: ğŸ‡³ğŸ‡´NO
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ğŸ‡µğŸ‡±PL_34 |33.02Mb
  server: 217.30.10.18
  type: ss
  country: ğŸ‡µğŸ‡±PL
  port: 9032
  password: UWZQeLRWnkqgkseq
  cipher: aes-256-cfb
- name: ğŸ‡±ğŸ‡¹LT_31 | 2.29Mb
  server: 192.36.61.59
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 990
  password: f8f7aCzcPKbsF8p3
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡µğŸ‡±PL_35 |48.89Mb
  server: 217.30.10.70
  type: ss
  country: ğŸ‡µğŸ‡±PL
  port: 9042
  password: S7KwUu7yBy58S3Ga
  cipher: aes-256-cfb
- name: ğŸ‡µğŸ‡±PL_36 |37.47Mb
  server: 217.30.10.70
  type: ss
  country: ğŸ‡µğŸ‡±PL
  port: 9006
  password: FAdUvMJUq5vDgKEq
  cipher: aes-256-cfb
- name: ğŸ‡µğŸ‡±PL_37 |39.56Mb
  server: 217.30.10.70
  type: ss
  country: ğŸ‡µğŸ‡±PL
  port: 9031
  password: BwcAUZk8hUFAkDGN
  cipher: aes-256-cfb
- name: ğŸ‡µğŸ‡±PL_38 |42.28Mb
  server: 217.30.10.70
  type: ss
  country: ğŸ‡µğŸ‡±PL
  port: 9005
  password: ZET59LF6DvCC8KVt
  cipher: aes-256-cfb
- name: ğŸ‡·ğŸ‡ºRU_40 | 7.69Mb
  server: 95.163.176.37
  type: ss
  country: ğŸ‡·ğŸ‡ºRU
  port: 8506
  password: WLEqen5ubQYw4TbHTxxnjK
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡·ğŸ‡ºRU_41 | 1.51Mb
  server: 95.163.176.37
  type: ss
  country: ğŸ‡·ğŸ‡ºRU
  port: 8506
  password: n4J9KuWgBBXPBoDn0SdprD
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¸ğŸ‡ªSE_42 | 3.65Mb
  server: 51.21.244.34
  type: ss
  country: ğŸ‡¸ğŸ‡ªSE
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡¸ğŸ‡ªSE_44 | 0.57Mb
  server: 13.60.93.157
  type: ss
  country: ğŸ‡¸ğŸ‡ªSE
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡ºğŸ‡¸US_50 | 2.31Mb
  server: 64.74.163.218
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 990
  password: f8f7aCzcPKbsF8p3
  cipher: chacha20-ietf-poly1305
- name: disney_SE | 1.76Mb
  server: 121.127.46.147
  type: ss
  country: ğŸ‡¸ğŸ‡ªSE
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ğŸ‡¸ğŸ‡ªSE_46 | 2.13Mb
  server: 51.21.243.75
  type: ss
  country: ğŸ‡¸ğŸ‡ªSE
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡ºğŸ‡¸US_54 | 8.99Mb
  server: 104.192.226.106
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ğŸ‡ºğŸ‡¸US_53 | 2.50Mb
  server: 156.146.38.168
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: shadowsocks
  cipher: aes-128-gcm
- name: ğŸ‡¸ğŸ‡ªSE_47 | 0.83Mb
  server: 16.171.232.205
  type: ss
  country: ğŸ‡¸ğŸ‡ªSE
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡ºğŸ‡¸US_56 | 5.41Mb
  server: 23.157.40.5
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 8888
  password: Y6R9pAtvxxzmGC
  cipher: aes-256-gcm
- name: ğŸ‡ºğŸ‡¸US_55 | 2.86Mb
  server: 156.146.38.167
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: shadowsocks
  cipher: aes-128-gcm
- name: ğŸ‡ºğŸ‡¸US_51 | 3.99Mb
  server: 34.207.80.141
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡ºğŸ‡¸US_58 | 3.49Mb
  server: 23.157.40.5
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 5003
  password: g5MeD6Ft3CWlJId
  cipher: aes-256-gcm
- name: ğŸ‡ºğŸ‡¸US_60 | 6.38Mb
  server: 79.110.53.89
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 8080
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: ğŸ‡¹ğŸ‡·TR_49 | 2.27Mb
  server: 83.217.9.64
  type: ss
  country: ğŸ‡¹ğŸ‡·TR
  port: 443
  password: MgEU8qSlwf53
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_59 | 3.11Mb
  server: 23.157.40.5
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 6679
  password: TEzjfAYq2IjtuoS
  cipher: aes-256-gcm
- name: ğŸ‡¸ğŸ‡¬SG_48 |13.35Mb
  server: 128.199.172.224
  type: ss
  country: ğŸ‡¸ğŸ‡¬SG
  port: 8080
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: ğŸ‡ºğŸ‡¸US_57 | 3.02Mb
  server: 54.165.208.46
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡ºğŸ‡¸US_62 |31.91Mb
  server: 23.157.40.5
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 7307
  password: FoOiGlkAA9yPEGP
  cipher: aes-256-gcm
- name: ğŸ‡ºğŸ‡¸US_65 |39.46Mb
  server: 23.157.40.5
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 5001
  password: Y6R9pAtvxxzmGC
  cipher: aes-256-gcm
- name: ğŸ‡ºğŸ‡¸US_66 | 4.80Mb
  server: 156.146.38.170
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: shadowsocks
  cipher: aes-128-gcm
- name: ğŸ‡ºğŸ‡¸US_64 |54.38Mb
  server: pupas-shirting-unsung.freesocks.work
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: p78naCf2EfOlRSLTX0wFVx
  cipher: chacha20-ietf-poly1305
- name: Pool_ğŸ‡­ğŸ‡°HK_26 |694.00Mb
  server: 150.107.46.21
  type: ssr
  country: ğŸ‡­ğŸ‡°HK
  port: 8083
  password: iFqnzSscN
  cipher: aes-256-cfb
  protocol: origin
  obfs: tls1.2_ticket_auth
- name: ğŸ‡ºğŸ‡¸US_63 | 0.41Mb
  server: 54.92.201.198
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡ºğŸ‡¸US_61 |29.95Mb
  server: 13.59.220.8
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡ºğŸ‡¸US_67 | 5.12Mb
  server: 212.102.47.129
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: shadowsocks
  cipher: aes-128-gcm
- name: disney_US | 1.64Mb
  server: 193.124.24.230
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 6503
  uuid: ade0486c-fe64-4815-9895-78de66553a2c
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_US |20.50Mb
  server: 193.124.24.230
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 6513
  uuid: 651d7ad8-db2f-46a9-ec68-ef7054774fc0
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡ºğŸ‡¸US_68 |17.08Mb
  server: 38.107.226.159
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 7307
  password: FoOiGlkAA9yPEGP
  cipher: aes-256-gcm
- name: disney_US | 2.93Mb
  server: 193.124.24.230
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 6502
  uuid: 44e32afd-714e-4d60-f6bc-5d7a1d34080b
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡ºğŸ‡¸US_69 |27.97Mb
  server: 18.221.238.85
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡ºğŸ‡¸US_52 | 6.50Mb
  server: 38.110.1.122
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 7306
  password: FoOiGlkAA9yPEGP
  cipher: aes-256-gcm
- name: ğŸ‡ºğŸ‡¸US_70 | 7.04Mb
  server: 94.131.21.174
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 54075
  password: o38yuvzSe3m5aDNpHtUPH1zGwbGEXXMDsGwVaub2SYEmHUa2WGZUjiezX3Vvva9CCzpjxYtuJLgKsSnsyKBf9ciPVba3y4o3
  cipher: chacha20-ietf-poly1305
- name: Pool_ğŸ‡ºğŸ‡¸US_74 | 3.49Mb
  server: 206.119.191.20
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 7998
  uuid: 984429ed-3959-4022-e248-cbcb19c96f9a
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡·ğŸ‡ºRU_39 | 9.61Mb
  server: 94.159.96.245
  type: ss
  country: ğŸ‡·ğŸ‡ºRU
  port: 11902
  password: JRaGZsN5QIA3wZ06Y6YkL7
  cipher: chacha20-ietf-poly1305
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - ğŸ‡©ğŸ‡ªDE_10 | 9.85Mb
  - ğŸ‡§ğŸ‡ªBE_07 |49.64Mb
  - ğŸ‡©ğŸ‡ªDE_09 | 0.74Mb
  - ğŸ‡©ğŸ‡ªDE_08 | 3.54Mb
  - ğŸ‡©ğŸ‡ªDE_12 | 1.14Mb
  - ğŸ‡©ğŸ‡ªDE_11 | 0.43Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_01 |86.41Mb
  - _05 |34.03Mb
  - ğŸ‡ªğŸ‡¸ES_17 | 3.03Mb
  - ğŸ‡©ğŸ‡ªDE_13 | 5.10Mb
  - ğŸ‡©ğŸ‡ªDE_14 | 2.38Mb
  - ğŸ‡©ğŸ‡ªDE_16 | 5.49Mb
  - ğŸ‡©ğŸ‡ªDE_15 | 2.22Mb
  - ğŸ‡«ğŸ‡·FR_20
  - ğŸ‡«ğŸ‡®FI_19 | 9.26Mb
  - ğŸ‡«ğŸ‡®FI_18 |36.21Mb
  - ğŸ‡¬ğŸ‡§GB_23 | 9.84Mb
  - ğŸ‡«ğŸ‡·FR_21
  - ğŸ‡®ğŸ‡ªIE_28 |14.89Mb
  - ğŸ‡®ğŸ‡ªIE_29 | 3.23Mb
  - ğŸ‡­ğŸ‡°HK_25 |141.04Mb
  - ğŸ‡±ğŸ‡¹LT_32 |33.11Mb
  - ğŸ‡®ğŸ‡¸IS_30 | 0.80Mb
  - ğŸ‡³ğŸ‡´NO_33 | 2.17Mb
  - ğŸ‡µğŸ‡±PL_34 |33.02Mb
  - ğŸ‡±ğŸ‡¹LT_31 | 2.29Mb
  - ğŸ‡µğŸ‡±PL_35 |48.89Mb
  - ğŸ‡µğŸ‡±PL_36 |37.47Mb
  - ğŸ‡µğŸ‡±PL_37 |39.56Mb
  - ğŸ‡µğŸ‡±PL_38 |42.28Mb
  - ğŸ‡·ğŸ‡ºRU_40 | 7.69Mb
  - ğŸ‡·ğŸ‡ºRU_41 | 1.51Mb
  - ğŸ‡¸ğŸ‡ªSE_42 | 3.65Mb
  - ğŸ‡¸ğŸ‡ªSE_44 | 0.57Mb
  - ğŸ‡ºğŸ‡¸US_50 | 2.31Mb
  - disney_SE | 1.76Mb
  - ğŸ‡¸ğŸ‡ªSE_46 | 2.13Mb
  - ğŸ‡ºğŸ‡¸US_54 | 8.99Mb
  - ğŸ‡ºğŸ‡¸US_53 | 2.50Mb
  - ğŸ‡¸ğŸ‡ªSE_47 | 0.83Mb
  - ğŸ‡ºğŸ‡¸US_56 | 5.41Mb
  - ğŸ‡ºğŸ‡¸US_55 | 2.86Mb
  - ğŸ‡ºğŸ‡¸US_51 | 3.99Mb
  - ğŸ‡ºğŸ‡¸US_58 | 3.49Mb
  - ğŸ‡ºğŸ‡¸US_60 | 6.38Mb
  - ğŸ‡¹ğŸ‡·TR_49 | 2.27Mb
  - ğŸ‡ºğŸ‡¸US_59 | 3.11Mb
  - ğŸ‡¸ğŸ‡¬SG_48 |13.35Mb
  - ğŸ‡ºğŸ‡¸US_57 | 3.02Mb
  - ğŸ‡ºğŸ‡¸US_62 |31.91Mb
  - ğŸ‡ºğŸ‡¸US_65 |39.46Mb
  - ğŸ‡ºğŸ‡¸US_66 | 4.80Mb
  - ğŸ‡ºğŸ‡¸US_64 |54.38Mb
  - Pool_ğŸ‡­ğŸ‡°HK_26 |694.00Mb
  - ğŸ‡ºğŸ‡¸US_63 | 0.41Mb
  - ğŸ‡ºğŸ‡¸US_61 |29.95Mb
  - ğŸ‡ºğŸ‡¸US_67 | 5.12Mb
  - disney_US | 1.64Mb
  - disney_US |20.50Mb
  - ğŸ‡ºğŸ‡¸US_68 |17.08Mb
  - disney_US | 2.93Mb
  - ğŸ‡ºğŸ‡¸US_69 |27.97Mb
  - ğŸ‡ºğŸ‡¸US_52 | 6.50Mb
  - ğŸ‡ºğŸ‡¸US_70 | 7.04Mb
  - Pool_ğŸ‡ºğŸ‡¸US_74 | 3.49Mb
  - ğŸ‡·ğŸ‡ºRU_39 | 9.61Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - ğŸ‡©ğŸ‡ªDE_10 | 9.85Mb
  - ğŸ‡§ğŸ‡ªBE_07 |49.64Mb
  - ğŸ‡©ğŸ‡ªDE_09 | 0.74Mb
  - ğŸ‡©ğŸ‡ªDE_08 | 3.54Mb
  - ğŸ‡©ğŸ‡ªDE_12 | 1.14Mb
  - ğŸ‡©ğŸ‡ªDE_11 | 0.43Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_01 |86.41Mb
  - _05 |34.03Mb
  - ğŸ‡ªğŸ‡¸ES_17 | 3.03Mb
  - ğŸ‡©ğŸ‡ªDE_13 | 5.10Mb
  - ğŸ‡©ğŸ‡ªDE_14 | 2.38Mb
  - ğŸ‡©ğŸ‡ªDE_16 | 5.49Mb
  - ğŸ‡©ğŸ‡ªDE_15 | 2.22Mb
  - ğŸ‡«ğŸ‡·FR_20
  - ğŸ‡«ğŸ‡®FI_19 | 9.26Mb
  - ğŸ‡«ğŸ‡®FI_18 |36.21Mb
  - ğŸ‡¬ğŸ‡§GB_23 | 9.84Mb
  - ğŸ‡«ğŸ‡·FR_21
  - ğŸ‡®ğŸ‡ªIE_28 |14.89Mb
  - ğŸ‡®ğŸ‡ªIE_29 | 3.23Mb
  - ğŸ‡­ğŸ‡°HK_25 |141.04Mb
  - ğŸ‡±ğŸ‡¹LT_32 |33.11Mb
  - ğŸ‡®ğŸ‡¸IS_30 | 0.80Mb
  - ğŸ‡³ğŸ‡´NO_33 | 2.17Mb
  - ğŸ‡µğŸ‡±PL_34 |33.02Mb
  - ğŸ‡±ğŸ‡¹LT_31 | 2.29Mb
  - ğŸ‡µğŸ‡±PL_35 |48.89Mb
  - ğŸ‡µğŸ‡±PL_36 |37.47Mb
  - ğŸ‡µğŸ‡±PL_37 |39.56Mb
  - ğŸ‡µğŸ‡±PL_38 |42.28Mb
  - ğŸ‡·ğŸ‡ºRU_40 | 7.69Mb
  - ğŸ‡·ğŸ‡ºRU_41 | 1.51Mb
  - ğŸ‡¸ğŸ‡ªSE_42 | 3.65Mb
  - ğŸ‡¸ğŸ‡ªSE_44 | 0.57Mb
  - ğŸ‡ºğŸ‡¸US_50 | 2.31Mb
  - disney_SE | 1.76Mb
  - ğŸ‡¸ğŸ‡ªSE_46 | 2.13Mb
  - ğŸ‡ºğŸ‡¸US_54 | 8.99Mb
  - ğŸ‡ºğŸ‡¸US_53 | 2.50Mb
  - ğŸ‡¸ğŸ‡ªSE_47 | 0.83Mb
  - ğŸ‡ºğŸ‡¸US_56 | 5.41Mb
  - ğŸ‡ºğŸ‡¸US_55 | 2.86Mb
  - ğŸ‡ºğŸ‡¸US_51 | 3.99Mb
  - ğŸ‡ºğŸ‡¸US_58 | 3.49Mb
  - ğŸ‡ºğŸ‡¸US_60 | 6.38Mb
  - ğŸ‡¹ğŸ‡·TR_49 | 2.27Mb
  - ğŸ‡ºğŸ‡¸US_59 | 3.11Mb
  - ğŸ‡¸ğŸ‡¬SG_48 |13.35Mb
  - ğŸ‡ºğŸ‡¸US_57 | 3.02Mb
  - ğŸ‡ºğŸ‡¸US_62 |31.91Mb
  - ğŸ‡ºğŸ‡¸US_65 |39.46Mb
  - ğŸ‡ºğŸ‡¸US_66 | 4.80Mb
  - ğŸ‡ºğŸ‡¸US_64 |54.38Mb
  - Pool_ğŸ‡­ğŸ‡°HK_26 |694.00Mb
  - ğŸ‡ºğŸ‡¸US_63 | 0.41Mb
  - ğŸ‡ºğŸ‡¸US_61 |29.95Mb
  - ğŸ‡ºğŸ‡¸US_67 | 5.12Mb
  - disney_US | 1.64Mb
  - disney_US |20.50Mb
  - ğŸ‡ºğŸ‡¸US_68 |17.08Mb
  - disney_US | 2.93Mb
  - ğŸ‡ºğŸ‡¸US_69 |27.97Mb
  - ğŸ‡ºğŸ‡¸US_52 | 6.50Mb
  - ğŸ‡ºğŸ‡¸US_70 | 7.04Mb
  - Pool_ğŸ‡ºğŸ‡¸US_74 | 3.49Mb
  - ğŸ‡·ğŸ‡ºRU_39 | 9.61Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
