port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: ğŸ‡ºğŸ‡¸US_603 |13.96Mb
  server: 104.192.226.106
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 990
  password: f8f7aCzcPKbsF8p3
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_639 |50.58Mb
  server: 23.157.40.5
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 8009
  password: XKFKl2rULjIp74
  cipher: aes-256-gcm
- name: ğŸ‡ºğŸ‡¸US_636 |30.30Mb
  server: 167.88.61.59
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 8091
  password: PCnnH6SQSnfoS27
  cipher: aes-256-gcm
- name: ğŸ‡¬ğŸ‡§GB_302 |18.71Mb
  server: 18.175.147.245
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡³ğŸ‡±NL_601 |10.01Mb
  server: 45.158.171.146
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 8080
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_596 |117.33Mb
  server: 167.88.61.110
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 6379
  password: zDNVedRFPQexG9v
  cipher: aes-256-gcm
- name: ğŸ‡ªğŸ‡¸ES_259 |11.63Mb
  server: 194.87.45.189
  type: ss
  country: ğŸ‡ªğŸ‡¸ES
  port: 443
  password: nrH8cZTXpPelsxKA38QJfq
  cipher: chacha20-ietf-poly1305
- name: disney_US |20.64Mb
  server: 193.124.24.247
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 6513
  uuid: 5cf7fcbc-e2c1-42c4-d0d7-79c45a7d588d
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡µğŸ‡±PL_475 |70.84Mb
  server: 77.83.246.74
  type: ss
  country: ğŸ‡µğŸ‡±PL
  port: 443
  password: wh9TzuckwJLxm0REq9fx6e
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡µğŸ‡±PL_482 |10.02Mb
  server: 77.83.246.74
  type: ss
  country: ğŸ‡µğŸ‡±PL
  port: 443
  password: hja6ECKVovyUhLqWxcDPIm
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_654 |68.37Mb
  server: 23.157.40.101
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 7307
  password: FoOiGlkAA9yPEGP
  cipher: aes-256-gcm
- name: ğŸ‡ºğŸ‡¸US_656 |44.93Mb
  server: 23.157.40.5
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 5001
  password: Y6R9pAtvxxzmGC
  cipher: aes-256-gcm
- name: Relay_ğŸ‡¹ğŸ‡·TR-ğŸ‡¹ğŸ‡·TR_573 |10.31Mb
  server: promo16v.bystrivpn.ru
  type: ss
  country: ğŸ‡¹ğŸ‡·TR
  port: 443
  password: tJlEWh2PzDMew8qo9YkPEA
  cipher: chacha20-ietf-poly1305
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - ğŸ‡ºğŸ‡¸US_603 |13.96Mb
  - ğŸ‡ºğŸ‡¸US_639 |50.58Mb
  - ğŸ‡ºğŸ‡¸US_636 |30.30Mb
  - ğŸ‡¬ğŸ‡§GB_302 |18.71Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡³ğŸ‡±NL_601 |10.01Mb
  - ğŸ‡ºğŸ‡¸US_596 |117.33Mb
  - ğŸ‡ªğŸ‡¸ES_259 |11.63Mb
  - disney_US |20.64Mb
  - ğŸ‡µğŸ‡±PL_475 |70.84Mb
  - ğŸ‡µğŸ‡±PL_482 |10.02Mb
  - ğŸ‡ºğŸ‡¸US_654 |68.37Mb
  - ğŸ‡ºğŸ‡¸US_656 |44.93Mb
  - Relay_ğŸ‡¹ğŸ‡·TR-ğŸ‡¹ğŸ‡·TR_573 |10.31Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - ğŸ‡ºğŸ‡¸US_603 |13.96Mb
  - ğŸ‡ºğŸ‡¸US_639 |50.58Mb
  - ğŸ‡ºğŸ‡¸US_636 |30.30Mb
  - ğŸ‡¬ğŸ‡§GB_302 |18.71Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡³ğŸ‡±NL_601 |10.01Mb
  - ğŸ‡ºğŸ‡¸US_596 |117.33Mb
  - ğŸ‡ªğŸ‡¸ES_259 |11.63Mb
  - disney_US |20.64Mb
  - ğŸ‡µğŸ‡±PL_475 |70.84Mb
  - ğŸ‡µğŸ‡±PL_482 |10.02Mb
  - ğŸ‡ºğŸ‡¸US_654 |68.37Mb
  - ğŸ‡ºğŸ‡¸US_656 |44.93Mb
  - Relay_ğŸ‡¹ğŸ‡·TR-ğŸ‡¹ğŸ‡·TR_573 |10.31Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
