port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: _208 |16.42Mb
  server: 173.234.29.2
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _215 |20.03Mb
  server: 137.184.174.93
  type: ss
  port: 8080
  udp: true
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: _207 |19.69Mb
  server: 138.186.142.81
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _209 |38.62Mb
  server: 138.186.143.32
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_GB |205.07Mb
  server: 146.70.61.37
  type: ss
  port: 8080
  udp: true
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: _204 |60.60Mb
  server: 151.242.251.142
  type: ss
  port: 8080
  udp: true
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: _211 |88.55Mb
  server: 141.98.101.178
  type: ss
  port: 443
  udp: true
  password: shadowsocks
  cipher: aes-128-gcm
- name: _206 |228.56Mb
  server: 151.242.251.152
  type: ss
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: _214 |148.42Mb
  server: 82.38.31.214
  type: ss
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: _203 |143.82Mb
  server: 193.29.139.177
  type: ss
  port: 8080
  udp: true
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: _213 |11.06Mb
  server: 45.87.175.22
  type: ss
  port: 8080
  udp: true
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: _220 |51.38Mb
  server: 156.146.38.167
  type: ss
  port: 443
  udp: true
  password: shadowsocks
  cipher: aes-128-gcm
- name: _238 |52.36Mb
  server: 156.146.38.169
  type: ss
  port: 443
  udp: true
  password: shadowsocks
  cipher: aes-128-gcm
- name: Relay_-ğŸ‡¨ğŸ‡¦CA_219 |68.44Mb
  server: 79.127.200.169
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _217 |151.53Mb
  server: 138.186.143.32
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: _218 |208.29Mb
  server: 45.87.175.28
  type: ss
  port: 8080
  udp: true
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: _226 |44.50Mb
  server: 185.82.73.212
  type: ss
  port: 8444
  udp: true
  password: _bypfvq6ra7g4n5yCCR9DoVeGya2XUUS
  cipher: chacha20-ietf-poly1305
- name: _254 |47.85Mb
  server: 156.146.38.170
  type: ss
  port: 443
  udp: true
  password: shadowsocks
  cipher: aes-128-gcm
- name: netflix_US |19.88Mb
  server: 103.35.189.136
  type: ss
  port: 443
  udp: true
  password: SS2QvbC9nqLp2sXXZo0BVy4slcErRuCt
  cipher: chacha20-ietf-poly1305
- name: _225 |37.28Mb
  server: 89.221.225.15
  type: ss
  port: 443
  udp: true
  password: yCbQ4bry4otfifK7oel71NaXpPL9pYJb
  cipher: chacha20-ietf-poly1305
- name: _245 |266.82Mb
  server: 51.15.23.166
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: disney_SE |14.95Mb
  server: se1.opensocks.site
  type: ss
  port: 8388
  udp: true
  password: ODIzO
  cipher: chacha20-ietf-poly1305
- name: _246 |17.32Mb
  server: 185.192.124.188
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: disney_SG |18.92Mb
  server: 38.89.142.56
  type: ss
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _242 |42.61Mb
  server: 156.59.243.6
  type: ss
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _248 |167.71Mb
  server: 82.38.31.179
  type: ss
  port: 8080
  udp: true
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: _227 |31.07Mb
  server: 103.97.203.227
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _264 |21.13Mb
  server: 172.105.199.111
  type: ss
  port: 8080
  udp: true
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: _256 |25.00Mb
  server: 194.246.114.101
  type: ss
  port: 443
  udp: true
  password: HaNqw9pIE4jcx98sg7UQgHeGNTM4R2pk
  cipher: chacha20-ietf-poly1305
- name: Relay_-ğŸ‡ªğŸ‡ªEE_255 |22.27Mb
  server: est01-ss01.tcp-reset-club.net
  type: ss
  port: 8444
  udp: true
  password: AWNeHjukGQWwuFXadw2r6qH7gh4hZ9cj
  cipher: chacha20-ietf-poly1305
- name: _257 |20.11Mb
  server: 128.199.172.224
  type: ss
  port: 8080
  udp: true
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: _268 |16.61Mb
  server: 62.100.205.100
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _267 |105.74Mb
  server: 82.38.31.176
  type: ss
  port: 8080
  udp: true
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: _265 |11.32Mb
  server: 103.149.183.200
  type: ss
  port: 8388
  udp: true
  password: asd123456
  cipher: chacha20-ietf
- name: disney_PY |75.82Mb
  server: 38.165.233.93
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: netflix_US |70.89Mb
  server: 172.233.229.91
  type: vmess
  port: 14102
  udp: true
  uuid: 27ba87fc-583f-4763-9060-83cf0b9264db
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_-ğŸ‡±ğŸ‡ºLU_262 |20.69Mb
  server: 193.135.174.135
  type: ss
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _288 |11.92Mb
  server: 160.16.214.6
  type: trojan
  port: 4054
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: _289 |24.94Mb
  server: 160.16.57.238
  type: trojan
  port: 4054
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: _290 |10.55Mb
  server: 160.16.106.144
  type: trojan
  port: 2760
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
  skip-cert-verify: true
- name: _292 |10.71Mb
  server: 160.16.116.227
  type: trojan
  port: 2760
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
  skip-cert-verify: true
- name: _294 |19.01Mb
  server: 160.16.138.24
  type: trojan
  port: 4054
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: _296 |10.08Mb
  server: 160.16.131.243
  type: trojan
  port: 2760
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
  skip-cert-verify: true
- name: netflix_NL |176.92Mb
  server: h110vpnnl.outlinekeys.net
  type: ss
  port: 52571
  udp: true
  password: b0TKxnHAYeeFYyzTAMXn0F
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¨ğŸ‡¦CA_301 |25.34Mb
  server: 185.213.23.63
  type: ss
  country: ğŸ‡¨ğŸ‡¦CA
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: disney_CH |36.40Mb
  server: 138.124.67.26
  type: ss
  country: ğŸ‡¨ğŸ‡­CH
  port: 25572
  password: nqcIfYHlpMn3jzqkNDjKaG
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡§ğŸ‡·BR_299 |19.17Mb
  server: 185.192.124.188
  type: ss
  country: ğŸ‡§ğŸ‡·BR
  port: 990
  password: f8f7aCzcPKbsF8p3
  cipher: chacha20-ietf-poly1305
- name: disney_DE |97.30Mb
  server: 89.163.140.136
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: Relay_ğŸ‡¬ğŸ‡§GB-ğŸ‡³ğŸ‡±NL_308 |192.38Mb
  server: 82.38.31.208
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡²ğŸ‡½MX_329 |36.46Mb
  server: 216.238.87.47
  type: vmess
  country: ğŸ‡²ğŸ‡½MX
  port: 27502
  uuid: b8155ce4-7e08-4c40-800f-8671312b7124
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡±ğŸ‡¹LT_320 |206.27Mb
  server: 45.87.175.183
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_GB |69.57Mb
  server: 141.98.101.182
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: shadowsocks
  cipher: aes-128-gcm
- name: netflix_NL |169.64Mb
  server: 45.87.175.180
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: QCXDxuDlTTMD7jtgHUjIoj
  cipher: chacha20-ietf-poly1305
- name: netflix_NL |216.70Mb
  server: 45.87.175.185
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: netflix_NL |208.42Mb
  server: 45.87.175.185
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: ğŸZZ_343 |17.70Mb
  server: hgtrojan.zabc.net
  type: vmess
  country: ğŸZZ
  port: 2083
  uuid: e6395c20-4571-4b34-d6b1-55a5d36e49ea
  alterId: 0
  cipher: auto
  network: ws
  servername: hgtrojan.zabc.net
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /e6395c20
    headers:
      HOST: hgtrojan.zabc.net
- name: Relay_ğŸZZ-ğŸ‡®ğŸ‡³IN_344 |37.74Mb
  server: 104.18.14.55
  type: vmess
  country: ğŸZZ
  port: 2052
  uuid: e6447786-8c85-443c-8017-7feaa673ff45
  alterId: 0
  cipher: auto
  network: ws
  servername: in4.123417.xyz
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
  ws-opts:
    path: /
    headers:
      HOST: in4.123417.xyz
- name: disney_LV |54.97Mb
  server: 46.183.217.204
  type: ss
  country: ğŸ‡±ğŸ‡» LV
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: netflix_NL |31.09Mb
  server: 178.23.190.238
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 443
  password: uo7EbtqIwgZXXHmMv5LbLcOxptyPlNkh
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡²ğŸ‡©MD_328 |16.07Mb
  server: 176.123.5.253
  type: ss
  country: ğŸ‡²ğŸ‡©MD
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡³ğŸ‡±NL_331 |264.26Mb
  server: 194.87.216.218
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 52571
  password: b0TKxnHAYeeFYyzTAMXn0F
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡³ğŸ‡±NL_332 |14.22Mb
  server: 193.29.139.141
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 8080
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡³ğŸ‡±NL_333 |75.37Mb
  server: 193.29.139.188
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 8080
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¸ğŸ‡¬SG_339 |13.54Mb
  server: 68.183.227.45
  type: ss
  country: ğŸ‡¸ğŸ‡¬SG
  port: 8080
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: ğŸ‡µğŸ‡¹PT_338 |77.63Mb
  server: 185.113.143.186
  type: ss
  country: ğŸ‡µğŸ‡¹PT
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: disney_PT |90.06Mb
  server: 185.231.233.112
  type: ss
  country: ğŸ ZZ
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - _208 |16.42Mb
  - _215 |20.03Mb
  - _207 |19.69Mb
  - _209 |38.62Mb
  - disney_netflix_GB |205.07Mb
  - _204 |60.60Mb
  - _211 |88.55Mb
  - _206 |228.56Mb
  - _214 |148.42Mb
  - _203 |143.82Mb
  - _213 |11.06Mb
  - _220 |51.38Mb
  - _238 |52.36Mb
  - Relay_-ğŸ‡¨ğŸ‡¦CA_219 |68.44Mb
  - _217 |151.53Mb
  - _218 |208.29Mb
  - _226 |44.50Mb
  - _254 |47.85Mb
  - netflix_US |19.88Mb
  - _225 |37.28Mb
  - _245 |266.82Mb
  - disney_SE |14.95Mb
  - _246 |17.32Mb
  - disney_SG |18.92Mb
  - _242 |42.61Mb
  - _248 |167.71Mb
  - _227 |31.07Mb
  - _264 |21.13Mb
  - _256 |25.00Mb
  - Relay_-ğŸ‡ªğŸ‡ªEE_255 |22.27Mb
  - _257 |20.11Mb
  - _268 |16.61Mb
  - _267 |105.74Mb
  - _265 |11.32Mb
  - disney_PY |75.82Mb
  - netflix_US |70.89Mb
  - Relay_-ğŸ‡±ğŸ‡ºLU_262 |20.69Mb
  - _288 |11.92Mb
  - _289 |24.94Mb
  - _290 |10.55Mb
  - _292 |10.71Mb
  - _294 |19.01Mb
  - _296 |10.08Mb
  - netflix_NL |176.92Mb
  - ğŸ‡¨ğŸ‡¦CA_301 |25.34Mb
  - disney_CH |36.40Mb
  - ğŸ‡§ğŸ‡·BR_299 |19.17Mb
  - disney_DE |97.30Mb
  - Relay_ğŸ‡¬ğŸ‡§GB-ğŸ‡³ğŸ‡±NL_308 |192.38Mb
  - ğŸ‡²ğŸ‡½MX_329 |36.46Mb
  - ğŸ‡±ğŸ‡¹LT_320 |206.27Mb
  - disney_netflix_GB |69.57Mb
  - netflix_NL |169.64Mb
  - netflix_NL |216.70Mb
  - netflix_NL |208.42Mb
  - ğŸZZ_343 |17.70Mb
  - Relay_ğŸZZ-ğŸ‡®ğŸ‡³IN_344 |37.74Mb
  - disney_LV |54.97Mb
  - netflix_NL |31.09Mb
  - ğŸ‡²ğŸ‡©MD_328 |16.07Mb
  - ğŸ‡³ğŸ‡±NL_331 |264.26Mb
  - ğŸ‡³ğŸ‡±NL_332 |14.22Mb
  - ğŸ‡³ğŸ‡±NL_333 |75.37Mb
  - ğŸ‡¸ğŸ‡¬SG_339 |13.54Mb
  - ğŸ‡µğŸ‡¹PT_338 |77.63Mb
  - disney_PT |90.06Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - _208 |16.42Mb
  - _215 |20.03Mb
  - _207 |19.69Mb
  - _209 |38.62Mb
  - disney_netflix_GB |205.07Mb
  - _204 |60.60Mb
  - _211 |88.55Mb
  - _206 |228.56Mb
  - _214 |148.42Mb
  - _203 |143.82Mb
  - _213 |11.06Mb
  - _220 |51.38Mb
  - _238 |52.36Mb
  - Relay_-ğŸ‡¨ğŸ‡¦CA_219 |68.44Mb
  - _217 |151.53Mb
  - _218 |208.29Mb
  - _226 |44.50Mb
  - _254 |47.85Mb
  - netflix_US |19.88Mb
  - _225 |37.28Mb
  - _245 |266.82Mb
  - disney_SE |14.95Mb
  - _246 |17.32Mb
  - disney_SG |18.92Mb
  - _242 |42.61Mb
  - _248 |167.71Mb
  - _227 |31.07Mb
  - _264 |21.13Mb
  - _256 |25.00Mb
  - Relay_-ğŸ‡ªğŸ‡ªEE_255 |22.27Mb
  - _257 |20.11Mb
  - _268 |16.61Mb
  - _267 |105.74Mb
  - _265 |11.32Mb
  - disney_PY |75.82Mb
  - netflix_US |70.89Mb
  - Relay_-ğŸ‡±ğŸ‡ºLU_262 |20.69Mb
  - _288 |11.92Mb
  - _289 |24.94Mb
  - _290 |10.55Mb
  - _292 |10.71Mb
  - _294 |19.01Mb
  - _296 |10.08Mb
  - netflix_NL |176.92Mb
  - ğŸ‡¨ğŸ‡¦CA_301 |25.34Mb
  - disney_CH |36.40Mb
  - ğŸ‡§ğŸ‡·BR_299 |19.17Mb
  - disney_DE |97.30Mb
  - Relay_ğŸ‡¬ğŸ‡§GB-ğŸ‡³ğŸ‡±NL_308 |192.38Mb
  - ğŸ‡²ğŸ‡½MX_329 |36.46Mb
  - ğŸ‡±ğŸ‡¹LT_320 |206.27Mb
  - disney_netflix_GB |69.57Mb
  - netflix_NL |169.64Mb
  - netflix_NL |216.70Mb
  - netflix_NL |208.42Mb
  - ğŸZZ_343 |17.70Mb
  - Relay_ğŸZZ-ğŸ‡®ğŸ‡³IN_344 |37.74Mb
  - disney_LV |54.97Mb
  - netflix_NL |31.09Mb
  - ğŸ‡²ğŸ‡©MD_328 |16.07Mb
  - ğŸ‡³ğŸ‡±NL_331 |264.26Mb
  - ğŸ‡³ğŸ‡±NL_332 |14.22Mb
  - ğŸ‡³ğŸ‡±NL_333 |75.37Mb
  - ğŸ‡¸ğŸ‡¬SG_339 |13.54Mb
  - ğŸ‡µğŸ‡¹PT_338 |77.63Mb
  - disney_PT |90.06Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
