port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: _207 |20.56Mb
  server: 15.235.41.200
  type: vmess
  port: 80
  uuid: 58fe1542-5290-40ad-815a-77707a81afe5
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /IOebhLMhl1CTbFHbL95myfRX2
- name: _208 |42.58Mb
  server: 172.235.33.114
  type: vmess
  port: 10001
  uuid: 442a3923-eca1-4af0-b3ff-24a7ce0af68f
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _209 |42.18Mb
  server: 163.192.49.195
  type: vmess
  port: 443
  uuid: bcb7c581-3c95-4569-a4e7-918141e91ea3
  alterId: 0
  cipher: auto
  network: http
  http-opts:
    path:
    - /
    headers:
      Host:
      - a.189.cn
  h2-opts: {}
- name: _202 |13.21Mb
  server: 51.79.102.253
  type: vmess
  port: 80
  uuid: 58fe1542-5290-40ad-815a-77707a81afe5
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /IOebhLMhl1CTbFHbL95myfRX2
    headers:
      Host: wrmelmwxlf.gktevlrqznwqqozy.fabpfs66gizmnojhcvqxwl.kytrcfzqla87gvgvs6c7kjnrubuh.cc
- name: disney_US |40.88Mb
  server: 165.140.216.141
  type: vmess
  port: 443
  uuid: e7d72a8d-26f2-4b54-b366-0c43e0bcba7d
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _197 |16.01Mb
  server: 45.14.245.2
  type: ss
  port: 443
  password: 17ZDORWIliQHuO6WRGHChXYMzdRtAYVP
  cipher: chacha20-ietf-poly1305
- name: _200 |270.83Mb
  server: 85.195.101.122
  type: vmess
  port: 40878
  uuid: f3d4167e-b15e-4e46-82e9-9286ef93fda7
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _205 |61.20Mb
  server: 91.99.27.55
  type: vmess
  port: 8880
  uuid: f3025961-167b-4f49-e4e3-86505fe980fd
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _266 |48.47Mb
  server: 45.150.52.40
  type: vmess
  port: 443
  uuid: c31777a1-2ee6-4864-db4c-a79fcbc8188b
  alterId: 0
  cipher: auto
  network: ws
  servername: xsj011-3.facai2024.com
  http-opts: {}
  h2-opts: {}
  tls: true
  ws-opts:
    path: /c31777a1
    headers:
      Host: xsj011-3.facai2024.com
- name: Relay_-ğŸ‡­ğŸ‡°HK_204 |22.51Mb
  server: 131.186.63.89
  type: vmess
  port: 11655
  uuid: 4bf075f5-4d5e-4d39-f5ab-b32a86250f0e
  alterId: 0
  cipher: auto
  network: ws
  servername: hk.nbee.pp.ua
  http-opts: {}
  h2-opts: {}
  tls: true
  ws-opts:
    path: /aa
    headers:
      Host: hk.nbee.pp.ua
- name: _278 |24.62Mb
  server: 38.96.254.102
  type: trojan
  port: 18509
  password: .ie4rghJuMkcf0oF
  sni: shoppingmall.electricbanana.click
- name: Pool__275 |180.73Mb
  server: 70.34.218.149
  type: trojan
  port: 11930
  password: BaeSzHdfJIR13l67
  sni: softpillow.silentrocket.click
- name: disney_TW |15.65Mb
  server: 103.127.218.91
  type: vmess
  port: 54693
  uuid: 1cef03ad-6343-408c-8121-cbd1fda2ee9d
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /1cef03ad
- name: Relay_-ğŸ‡­ğŸ‡°HK_216 |17.34Mb
  server: 154.21.201.83
  type: vmess
  port: 443
  uuid: 4bf075f5-4d5e-4d39-f5ab-b32a86250f0e
  alterId: 0
  cipher: auto
  network: ws
  servername: hk.nbee.pp.ua
  http-opts: {}
  h2-opts: {}
  tls: true
  ws-opts:
    path: /aa
    headers:
      Host: hk.nbee.pp.ua
- name: _217 |22.48Mb
  server: 8.218.116.26
  type: vmess
  port: 32228
  uuid: e4767e9f-ed00-4f31-a984-a918bdd9b09c
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _210 |43.20Mb
  server: 89.31.120.192
  type: vmess
  port: 443
  uuid: 44537595-9ccc-4b83-8936-5f9ad3229019
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: Relay_-ğŸ‡¯ğŸ‡µJP_276 |12.41Mb
  server: 13.112.81.124
  type: trojan
  port: 3169
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: disney_HK |26.25Mb
  server: 219.78.209.224
  type: trojan
  port: 443
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: _279 |31.18Mb
  server: 160.16.223.205
  type: trojan
  port: 4054
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¸ğŸ‡¬SG_287 |10.85Mb
  server: 160.16.153.13
  type: trojan
  port: 3145
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡ºğŸ‡¸US_199 |14.00Mb
  server: v29.hdacd.com
  type: vmess
  port: 30829
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _289 |14.19Mb
  server: 202.181.103.235
  type: trojan
  port: 2890
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡ºğŸ‡¸US_255 |11.11Mb
  server: v8.hdacd.com
  type: vmess
  port: 30808
  udp: true
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: disney_HK |29.75Mb
  server: 58.152.18.95
  type: trojan
  port: 443
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: disney_HK |79.92Mb
  server: 58.152.25.20
  type: trojan
  port: 443
  udp: true
  password: BxceQaOe
  skip-cert-verify: true
- name: disney_HK |24.87Mb
  server: 58.152.53.174
  type: trojan
  port: 443
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: disney_HK |14.67Mb
  server: 58.152.30.120
  type: trojan
  port: 443
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: disney_FR |217.00Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 27092
  uuid: a0596ba6-72a3-4366-8992-77088da65bd8
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: _292 |14.00Mb
  server: 160.16.124.55
  type: trojan
  port: 2890
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: disney_FR |34.38Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 40433
  uuid: d8fd8955-78db-49ba-d86f-3e4729f6ac4d
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: netflix_NL |222.26Mb
  server: 82.38.31.194
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: disney_HK |29.06Mb
  server: 58.152.110.82
  type: trojan
  port: 443
  udp: true
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: disney_TR |54.83Mb
  server: tr-1.stunnel.cc
  type: ss
  country: ğŸ‡¹ğŸ‡·TR
  port: 8444
  password: tunnel-fbrof
  cipher: chacha20-ietf-poly1305
- name: disney_HK |25.18Mb
  server: 45.207.157.29
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 13852
  uuid: 845764df-ecb3-4b13-bed2-bf1551b68e9a
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - _207 |20.56Mb
  - _208 |42.58Mb
  - _209 |42.18Mb
  - _202 |13.21Mb
  - disney_US |40.88Mb
  - _197 |16.01Mb
  - _200 |270.83Mb
  - _205 |61.20Mb
  - _266 |48.47Mb
  - Relay_-ğŸ‡­ğŸ‡°HK_204 |22.51Mb
  - _278 |24.62Mb
  - Pool__275 |180.73Mb
  - disney_TW |15.65Mb
  - Relay_-ğŸ‡­ğŸ‡°HK_216 |17.34Mb
  - _217 |22.48Mb
  - _210 |43.20Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_276 |12.41Mb
  - disney_HK |26.25Mb
  - _279 |31.18Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_287 |10.85Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_199 |14.00Mb
  - _289 |14.19Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_255 |11.11Mb
  - disney_HK |29.75Mb
  - disney_HK |79.92Mb
  - disney_HK |24.87Mb
  - disney_HK |14.67Mb
  - disney_FR |217.00Mb
  - _292 |14.00Mb
  - disney_FR |34.38Mb
  - netflix_NL |222.26Mb
  - disney_HK |29.06Mb
  - disney_TR |54.83Mb
  - disney_HK |25.18Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - _207 |20.56Mb
  - _208 |42.58Mb
  - _209 |42.18Mb
  - _202 |13.21Mb
  - disney_US |40.88Mb
  - _197 |16.01Mb
  - _200 |270.83Mb
  - _205 |61.20Mb
  - _266 |48.47Mb
  - Relay_-ğŸ‡­ğŸ‡°HK_204 |22.51Mb
  - _278 |24.62Mb
  - Pool__275 |180.73Mb
  - disney_TW |15.65Mb
  - Relay_-ğŸ‡­ğŸ‡°HK_216 |17.34Mb
  - _217 |22.48Mb
  - _210 |43.20Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_276 |12.41Mb
  - disney_HK |26.25Mb
  - _279 |31.18Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_287 |10.85Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_199 |14.00Mb
  - _289 |14.19Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_255 |11.11Mb
  - disney_HK |29.75Mb
  - disney_HK |79.92Mb
  - disney_HK |24.87Mb
  - disney_HK |14.67Mb
  - disney_FR |217.00Mb
  - _292 |14.00Mb
  - disney_FR |34.38Mb
  - netflix_NL |222.26Mb
  - disney_HK |29.06Mb
  - disney_TR |54.83Mb
  - disney_HK |25.18Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
