port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: netflix_CA |41.57Mb
  server: 45.154.204.7
  type: ss
  country: ğŸ‡¨ğŸ‡¦CA
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: netflix_TR |16.00Mb
  server: 95.164.116.33
  type: ss
  port: 443
  password: pQmnC03JObbPhdh5FBJHgD6jnTLchsRA
  cipher: chacha20-ietf-poly1305
- name: netflix_IL |11.88Mb
  server: 89.221.225.15
  type: ss
  port: 443
  password: yCbQ4bry4otfifK7oel71NaXpPL9pYJb
  cipher: chacha20-ietf-poly1305
- name: _96 |10.29Mb
  server: 202.181.103.246
  type: trojan
  port: 2760
  password: 44e660b0ee21cf3ac66aee2c08af85d2
  sni: www.nintendogames.net
  skip-cert-verify: true
- name: disney_netflix_JP |17.96Mb
  server: 153.121.53.187
  type: trojan
  port: 3169
  password: 44e660b0ee21cf3ac66aee2c08af85d2
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¯ğŸ‡µJP_81 |12.85Mb
  server: 160.16.117.182
  type: trojan
  port: 3093
  password: 44e660b0ee21cf3ac66aee2c08af85d2
  sni: www.nintendogames.net
- name: disney_netflix_US |56.03Mb
  server: 160.16.196.59
  type: trojan
  port: 2890
  password: 44e660b0ee21cf3ac66aee2c08af85d2
  sni: www.nintendogames.net
- name: disney_netflix_HK |25.57Mb
  server: 194.246.114.101
  type: ss
  port: 443
  password: HaNqw9pIE4jcx98sg7UQgHeGNTM4R2pk
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_SG |28.83Mb
  server: 185.36.192.228
  type: vmess
  port: 35488
  uuid: fb5a4283-dbfb-458b-8619-c4a53739f781
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
- name: netflix_MX |43.16Mb
  server: 216.238.86.158
  type: vmess
  country: ğŸ‡²ğŸ‡½MX
  port: 34460
  uuid: 90be214d-048c-4ea2-a602-b8e4d4e51e36
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡²ğŸ‡©MD_191 |40.46Mb
  server: 176.123.1.175
  type: ss
  country: ğŸ‡²ğŸ‡©MD
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_US |39.26Mb
  server: us1.opensocks.site
  type: ss
  country: ğŸ‡·ğŸ‡ºRU
  port: 8388
  password: YjkxY
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_US |29.00Mb
  server: 23.95.75.146
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: NDRySIABARbErNIVsCNVkyYAHiBzhveT
  cipher: chacha20-ietf-poly1305
- name: netflix_NL |62.29Mb
  server: 178.23.190.238
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 443
  password: uo7EbtqIwgZXXHmMv5LbLcOxptyPlNkh
  cipher: chacha20-ietf-poly1305
- name: netflix_CA |42.57Mb
  server: 23.95.76.59
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_US |60.09Mb
  server: 47.253.228.138
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 22524
  uuid: 80845fcc-f862-45fe-c1d3-0a7120373712
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_HK |29.95Mb
  server: 45.207.157.29
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 13852
  uuid: 845764df-ecb3-4b13-bed2-bf1551b68e9a
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸZZ_214 |17.15Mb
  server: hgtrojan.zabc.net
  type: vmess
  country: ğŸZZ
  port: 2083
  uuid: e6395c20-4571-4b34-d6b1-55a5d36e49ea
  alterId: 0
  cipher: auto
  network: ws
  servername: hgtrojan.zabc.net
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /e6395c20
    headers:
      HOST: hgtrojan.zabc.net
- name: Relay_ğŸ‡­ğŸ‡°HK-ğŸ‡®ğŸ‡·IR_123 |11.76Mb
  server: e4d7a1c2f3b80976a5e2c1d4b3f0a987.358.onl
  type: ss
  country: ğŸ‡­ğŸ‡°HK
  port: 23105
  password: 309a74a1-364f-4788-b44f-fb15013f69fb
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸ‡­ğŸ‡°HK-ğŸ‡ºğŸ‡¸US_115 |10.32Mb
  server: e4d7a1c2f3b80976a5e2c1d4b3f0a987.358.onl
  type: ss
  country: ğŸ‡­ğŸ‡°HK
  port: 23116
  password: 309a74a1-364f-4788-b44f-fb15013f69fb
  cipher: chacha20-ietf-poly1305
- name: disney_KR |10.85Mb
  server: e4d7a1c2f3b80976a5e2c1d4b3f0a987.358.onl
  type: ss
  country: ğŸ‡­ğŸ‡°HK
  port: 23101
  password: 309a74a1-364f-4788-b44f-fb15013f69fb
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_JP |12.07Mb
  server: e4d7a1c2f3b80976a5e2c1d4b3f0a987.358.onl
  type: ss
  country: ğŸ‡­ğŸ‡°HK
  port: 23107
  password: 309a74a1-364f-4788-b44f-fb15013f69fb
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_US |62.19Mb
  server: 206.119.191.9
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 7100
  uuid: 10853485-26e1-477b-d257-58a3f4873db3
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_US |67.79Mb
  server: 156.233.232.177
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 24004
  uuid: 582fcb35-20a0-452c-e179-4c759c62c494
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_ğŸ‡¯ğŸ‡µJP-ğŸ‡¯ğŸ‡µJP_189 |20.77Mb
  server: n1753598446.wpg27.xyz
  type: vmess
  country: ğŸ‡¯ğŸ‡µJP
  port: 443
  uuid: a5047d95-24b8-451a-93e3-f2a387b93d5a
  alterId: 0
  cipher: auto
  network: ws
  servername: n1753598446.wpg27.xyz
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /
    headers:
      HOST: n1753598446.wpg27.xyz
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - netflix_CA |41.57Mb
  - netflix_TR |16.00Mb
  - netflix_IL |11.88Mb
  - _96 |10.29Mb
  - disney_netflix_JP |17.96Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_81 |12.85Mb
  - disney_netflix_US |56.03Mb
  - disney_netflix_HK |25.57Mb
  - disney_netflix_SG |28.83Mb
  - netflix_MX |43.16Mb
  - ğŸ‡²ğŸ‡©MD_191 |40.46Mb
  - disney_netflix_US |39.26Mb
  - disney_netflix_US |29.00Mb
  - netflix_NL |62.29Mb
  - netflix_CA |42.57Mb
  - disney_netflix_US |60.09Mb
  - disney_netflix_HK |29.95Mb
  - ğŸZZ_214 |17.15Mb
  - Relay_ğŸ‡­ğŸ‡°HK-ğŸ‡®ğŸ‡·IR_123 |11.76Mb
  - Relay_ğŸ‡­ğŸ‡°HK-ğŸ‡ºğŸ‡¸US_115 |10.32Mb
  - disney_KR |10.85Mb
  - disney_netflix_JP |12.07Mb
  - disney_netflix_US |62.19Mb
  - disney_netflix_US |67.79Mb
  - Relay_ğŸ‡¯ğŸ‡µJP-ğŸ‡¯ğŸ‡µJP_189 |20.77Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - netflix_CA |41.57Mb
  - netflix_TR |16.00Mb
  - netflix_IL |11.88Mb
  - _96 |10.29Mb
  - disney_netflix_JP |17.96Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_81 |12.85Mb
  - disney_netflix_US |56.03Mb
  - disney_netflix_HK |25.57Mb
  - disney_netflix_SG |28.83Mb
  - netflix_MX |43.16Mb
  - ğŸ‡²ğŸ‡©MD_191 |40.46Mb
  - disney_netflix_US |39.26Mb
  - disney_netflix_US |29.00Mb
  - netflix_NL |62.29Mb
  - netflix_CA |42.57Mb
  - disney_netflix_US |60.09Mb
  - disney_netflix_HK |29.95Mb
  - ğŸZZ_214 |17.15Mb
  - Relay_ğŸ‡­ğŸ‡°HK-ğŸ‡®ğŸ‡·IR_123 |11.76Mb
  - Relay_ğŸ‡­ğŸ‡°HK-ğŸ‡ºğŸ‡¸US_115 |10.32Mb
  - disney_KR |10.85Mb
  - disney_netflix_JP |12.07Mb
  - disney_netflix_US |62.19Mb
  - disney_netflix_US |67.79Mb
  - Relay_ğŸ‡¯ğŸ‡µJP-ğŸ‡¯ğŸ‡µJP_189 |20.77Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
