port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: Relay_-ğŸ‡³ğŸ‡±NL_274 |16.06Mb
  server: 160.16.63.16
  type: trojan
  port: 4054
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¸ğŸ‡¬SG_265 |11.63Mb
  server: 153.121.51.29
  type: trojan
  port: 127
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¸ğŸ‡¬SG_272 |10.38Mb
  server: 160.16.144.208
  type: trojan
  port: 3145
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡ºğŸ‡¸US_268 |10.36Mb
  server: 160.16.150.76
  type: trojan
  port: 1596
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¯ğŸ‡µJP_264 |21.08Mb
  server: 153.121.65.107
  type: trojan
  port: 1331
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¯ğŸ‡µJP_276 |21.47Mb
  server: 153.121.65.107
  type: trojan
  port: 3169
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: _197 |26.11Mb
  server: 103.106.3.82
  type: ss
  port: 443
  udp: true
  password: 4SaCIazlgumYkM8FkPzlmwjpyWBDZFBk
  cipher: chacha20-ietf-poly1305
- name: Relay_-ğŸ‡³ğŸ‡±NL_277 |10.91Mb
  server: 16.163.0.29
  type: trojan
  port: 4054
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: disney_HK |26.50Mb
  server: 203.198.122.13
  type: trojan
  port: 443
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: disney_netflix_FR |32.57Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 40433
  uuid: d8fd8955-78db-49ba-d86f-3e4729f6ac4d
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_FR |32.68Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 27092
  uuid: a0596ba6-72a3-4366-8992-77088da65bd8
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡§ğŸ‡·BR_281 |21.51Mb
  server: 38.180.16.86
  type: vmess
  country: ğŸ‡§ğŸ‡·BR
  port: 36104
  uuid: E146A8CB-9D2F-449C-ADCA-8736FB
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_-ğŸ‡³ğŸ‡±NL_278 |16.49Mb
  server: 160.16.124.55
  type: trojan
  port: 4054
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡³ğŸ‡±NL_279 |17.85Mb
  server: 160.16.81.84
  type: trojan
  port: 4054
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: ğŸ‡¬ğŸ‡§GB_288 |232.07Mb
  server: 82.38.31.190
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡­ğŸ‡°HK_292 |54.98Mb
  server: 87.121.162.249
  type: ss
  country: ğŸ‡­ğŸ‡°HK
  port: 443
  password: JGv616hMWdjfuZ00jYfq7XkBHJZrOBrg
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¦ğŸ‡ºAU_280 |10.84Mb
  server: 54.252.240.128
  type: vmess
  country: ğŸ‡¦ğŸ‡ºAU
  port: 1000
  uuid: ca26a9fd-fef8-4ea7-d194-450ce4e0c67a
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡²ğŸ‡½MX_308 |14.38Mb
  server: 216.238.89.53
  type: vmess
  country: ğŸ‡²ğŸ‡½MX
  port: 57283
  uuid: 1a5aafc0-6482-451d-fe76-6875b7818579
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: netflix_NL |189.95Mb
  server: 45.87.175.166
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 443
  password: 1RWwXhwfAB5gAEozU4G2Pg
  cipher: chacha20-ietf-poly1305
- name: disney_NL |106.15Mb
  server: 109.71.246.210
  type: ss
  country: ğŸ‡·ğŸ‡ºRU
  port: 56689
  password: YQCSKoCF3QazW8YlvDBWA4
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡­ğŸ‡°HK_295 |31.30Mb
  server: 47.242.140.52
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 48219
  uuid: 006893c6-79b1-4c44-94ff-b8bbea065f1f
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
  ws-opts:
    path: /arki?ed=2048
- name: ğŸ‡­ğŸ‡°HK_299 |30.91Mb
  server: 47.243.51.237
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 52801
  uuid: ef93f413-9039-4ddb-aefb-2490287df55a
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
  ws-opts:
    path: /arki?ed=2048
- name: disney_netflix_US |24.16Mb
  server: 38.84.201.21
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 53487
  uuid: c3c1ec05-df2c-4975-9b42-e9b007564eb1
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_ğŸ‡°ğŸ‡·KR-ğŸ‡°ğŸ‡·KR_305 |10.53Mb
  server: seoul03.zgjok.com
  type: vmess
  country: ğŸ‡°ğŸ‡·KR
  port: 443
  uuid: 72a0dac4-9689-4a57-b164-5c65bfa94772
  alterId: 0
  cipher: auto
  network: ws
  servername: seoul03.zgjok.com
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /
    headers:
      HOST: seoul03.zgjok.com
- name: ğŸ‡¹ğŸ‡·TR_313 |14.44Mb
  server: 185.39.204.161
  type: ss
  country: ğŸ‡¹ğŸ‡·TR
  port: 33563
  password: bSlgCoGhApOb55tIMD0zxY
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡²ğŸ‡¾MY_309 |16.60Mb
  server: 38.54.98.110
  type: vmess
  country: ğŸ‡²ğŸ‡¾MY
  port: 2052
  uuid: 665d9b8f-153d-4907-adac-de12afd9c851
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: ğŸ‡ºğŸ‡¸US_315 |14.59Mb
  server: 45.136.12.37
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 38141
  uuid: fd291be6-b48d-43a1-da38-66c7f80e2f80
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡¸ğŸ‡¬SG_312 |11.26Mb
  server: 68.183.178.131
  type: vmess
  country: ğŸ‡¸ğŸ‡¬SG
  port: 58607
  uuid: c11c32cb-27b3-4afa-c0f3-fb250aa4959e
  alterId: 0
  cipher: auto
  network: ws
  servername: www.12333.monster
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /
    headers:
      HOST: www.12333.monster
- name: disney_US |104.14Mb
  server: cf.fovi.tk
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  uuid: bf67437e-6c90-45ca-abc2-c7240a5ce2aa
  alterId: 0
  cipher: auto
  network: ws
  servername: foxlux.fovi.tk
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /eisasqa
    headers:
      HOST: foxlux.fovi.tk
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - Relay_-ğŸ‡³ğŸ‡±NL_274 |16.06Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_265 |11.63Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_272 |10.38Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_268 |10.36Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_264 |21.08Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_276 |21.47Mb
  - _197 |26.11Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_277 |10.91Mb
  - disney_HK |26.50Mb
  - disney_netflix_FR |32.57Mb
  - disney_netflix_FR |32.68Mb
  - ğŸ‡§ğŸ‡·BR_281 |21.51Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_278 |16.49Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_279 |17.85Mb
  - ğŸ‡¬ğŸ‡§GB_288 |232.07Mb
  - ğŸ‡­ğŸ‡°HK_292 |54.98Mb
  - ğŸ‡¦ğŸ‡ºAU_280 |10.84Mb
  - ğŸ‡²ğŸ‡½MX_308 |14.38Mb
  - netflix_NL |189.95Mb
  - disney_NL |106.15Mb
  - ğŸ‡­ğŸ‡°HK_295 |31.30Mb
  - ğŸ‡­ğŸ‡°HK_299 |30.91Mb
  - disney_netflix_US |24.16Mb
  - Relay_ğŸ‡°ğŸ‡·KR-ğŸ‡°ğŸ‡·KR_305 |10.53Mb
  - ğŸ‡¹ğŸ‡·TR_313 |14.44Mb
  - ğŸ‡²ğŸ‡¾MY_309 |16.60Mb
  - ğŸ‡ºğŸ‡¸US_315 |14.59Mb
  - ğŸ‡¸ğŸ‡¬SG_312 |11.26Mb
  - disney_US |104.14Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - Relay_-ğŸ‡³ğŸ‡±NL_274 |16.06Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_265 |11.63Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_272 |10.38Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_268 |10.36Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_264 |21.08Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_276 |21.47Mb
  - _197 |26.11Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_277 |10.91Mb
  - disney_HK |26.50Mb
  - disney_netflix_FR |32.57Mb
  - disney_netflix_FR |32.68Mb
  - ğŸ‡§ğŸ‡·BR_281 |21.51Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_278 |16.49Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_279 |17.85Mb
  - ğŸ‡¬ğŸ‡§GB_288 |232.07Mb
  - ğŸ‡­ğŸ‡°HK_292 |54.98Mb
  - ğŸ‡¦ğŸ‡ºAU_280 |10.84Mb
  - ğŸ‡²ğŸ‡½MX_308 |14.38Mb
  - netflix_NL |189.95Mb
  - disney_NL |106.15Mb
  - ğŸ‡­ğŸ‡°HK_295 |31.30Mb
  - ğŸ‡­ğŸ‡°HK_299 |30.91Mb
  - disney_netflix_US |24.16Mb
  - Relay_ğŸ‡°ğŸ‡·KR-ğŸ‡°ğŸ‡·KR_305 |10.53Mb
  - ğŸ‡¹ğŸ‡·TR_313 |14.44Mb
  - ğŸ‡²ğŸ‡¾MY_309 |16.60Mb
  - ğŸ‡ºğŸ‡¸US_315 |14.59Mb
  - ğŸ‡¸ğŸ‡¬SG_312 |11.26Mb
  - disney_US |104.14Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
