port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: Relay_-ğŸ‡ºğŸ‡¸US_197 |27.58Mb
  server: 38.14.99.163
  type: vmess
  port: 59807
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: disney_netflix_US |39.40Mb
  server: 38.14.99.179
  type: vmess
  port: 59807
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _203 |14.45Mb
  server: 51.79.102.253
  type: vmess
  port: 80
  uuid: 58fe1542-5290-40ad-815a-77707a81afe5
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /IOebhLMhl1CTbFHbL95myfRX2
    headers:
      Host: wrmelmwxlf.gktevlrqznwqqozy.fabpfs66gizmnojhcvqxwl.kytrcfzqla87gvgvs6c7kjnrubuh.cc
- name: disney_netflix_US |41.10Mb
  server: 165.140.216.141
  type: vmess
  port: 443
  uuid: e7d72a8d-26f2-4b54-b366-0c43e0bcba7d
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _188 |71.61Mb
  server: 138.124.67.26
  type: ss
  port: 443
  udp: true
  password: UdKq4itZdbbvsy0PCHTEUi
  cipher: chacha20-ietf-poly1305
- name: _191 |159.31Mb
  server: 13.61.180.46
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: netflix_SE |136.12Mb
  server: 13.61.13.231
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: disney_netflix_US |28.70Mb
  server: 192.204.47.79
  type: vmess
  port: 42277
  udp: true
  uuid: aee61b21-e85a-484b-f203-b245f1451cff
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: disney_PY |104.07Mb
  server: 38.165.233.93
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: _212 |41.98Mb
  server: 163.192.49.195
  type: vmess
  port: 443
  uuid: bcb7c581-3c95-4569-a4e7-918141e91ea3
  alterId: 0
  cipher: auto
  network: http
  http-opts:
    path:
    - /
    headers:
      Host:
      - a.189.cn
  h2-opts: {}
- name: disney_GB |179.85Mb
  server: 172.67.134.185
  type: trojan
  port: 443
  udp: true
  password: POORIARED
  sni: reDfRee8.REDFree8.ir
  ws-opts:
    path: /eyJqdW5rIjoiVUl6eXhLZkkwUTJ3ZzkiLCJwcm90b2NvbCI6InRyIiwibW9kZSI6InByb3h5aXAiLCJwYW5lbElQcyI6W119?ed=2560
    headers:
      Host: reDfRee8.REDFree8.ir
  network: ws
- name: _201 |26.47Mb
  server: 8.218.105.196
  type: vmess
  port: 52752
  uuid: 925bdbf5-72be-4437-bebf-441c61089f6b
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _206 |44.44Mb
  server: 89.31.120.192
  type: vmess
  port: 443
  uuid: 44537595-9ccc-4b83-8936-5f9ad3229019
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: disney_SG |13.05Mb
  server: 165.154.195.38
  type: vmess
  port: 35034
  uuid: 959a8caf-4cea-43d0-a548-3628e7ddfafc
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _226 |13.71Mb
  server: 160.16.204.136
  type: trojan
  port: 2890
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: _220 |12.39Mb
  server: 103.127.218.91
  type: vmess
  port: 54693
  uuid: 1cef03ad-6343-408c-8121-cbd1fda2ee9d
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /1cef03ad
- name: Pool__229 |181.53Mb
  server: 70.34.218.149
  type: trojan
  port: 11930
  password: BaeSzHdfJIR13l67
  sni: softpillow.silentrocket.click
- name: Relay_-ğŸ‡­ğŸ‡°HK_210 |16.82Mb
  server: 154.21.201.83
  type: vmess
  port: 443
  uuid: 4bf075f5-4d5e-4d39-f5ab-b32a86250f0e
  alterId: 0
  cipher: auto
  network: ws
  servername: hk.nbee.pp.ua
  http-opts: {}
  h2-opts: {}
  tls: true
  ws-opts:
    path: /aa
    headers:
      Host: hk.nbee.pp.ua
- name: Relay_-ğŸ‡¸ğŸ‡¬SG_228 |10.32Mb
  server: 160.16.150.76
  type: trojan
  port: 3145
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: _214 |19.64Mb
  server: 47.243.51.237
  type: vmess
  port: 52801
  uuid: ef93f413-9039-4ddb-aefb-2490287df55a
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /arki
- name: _236 |24.56Mb
  server: 38.96.254.102
  type: trojan
  port: 18509
  password: .ie4rghJuMkcf0oF
  sni: shoppingmall.electricbanana.click
- name: _230 |21.46Mb
  server: 160.16.57.238
  type: trojan
  port: 4054
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: _232 |11.50Mb
  server: 160.16.116.227
  type: trojan
  port: 2760
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
  skip-cert-verify: true
- name: _233 |16.82Mb
  server: 160.16.131.243
  type: trojan
  port: 2760
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
  skip-cert-verify: true
- name: _238 |88.73Mb
  server: 146.70.73.210
  type: trojan
  port: 53809
  udp: true
  password: blhwsknjxmfuydz0vhfv
  sni: www.vk.com
  skip-cert-verify: true
- name: _234 |10.65Mb
  server: 160.16.107.37
  type: trojan
  port: 3093
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: _235 |15.44Mb
  server: 160.16.63.16
  type: trojan
  port: 4054
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: _239 |12.16Mb
  server: 153.121.39.240
  type: trojan
  port: 4054
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¯ğŸ‡µJP_240 |10.44Mb
  server: 160.16.87.174
  type: trojan
  port: 3169
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: ğŸ‡²ğŸ‡½MX_274 |39.34Mb
  server: 216.238.87.47
  type: vmess
  country: ğŸ‡²ğŸ‡½MX
  port: 27502
  uuid: b8155ce4-7e08-4c40-800f-8671312b7124
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_US |69.40Mb
  server: 47.253.197.26
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 12056
  uuid: dd7be7f1-38ff-45e6-f1e5-b20c2190f527
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡¬ğŸ‡§GB_268 |227.40Mb
  server: 82.38.31.217
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_269 |218.51Mb
  server: 82.38.31.191
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: netflix_NL |198.81Mb
  server: 82.38.31.194
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: disney_HK |21.66Mb
  server: 45.207.157.29
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 13852
  uuid: 845764df-ecb3-4b13-bed2-bf1551b68e9a
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡­ğŸ‡°HK_272 |11.02Mb
  server: 156.245.232.15
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 21246
  uuid: 9526b462-c45f-4940-83b9-a204462b0744
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_-ğŸ‡¯ğŸ‡µJP_204 |11.77Mb
  server: yg6.ygkkk.dpdns.org
  type: vmess
  port: 80
  udp: true
  uuid: 130ec091-df05-4af9-9695-dc982e98a8ec
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /130ec091-df05-4af9-9695-dc982e98a8ec-vm?ed=2048
    headers:
      Host: jporacleyg2.336697.xyz
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - Relay_-ğŸ‡ºğŸ‡¸US_197 |27.58Mb
  - disney_netflix_US |39.40Mb
  - _203 |14.45Mb
  - disney_netflix_US |41.10Mb
  - _188 |71.61Mb
  - _191 |159.31Mb
  - netflix_SE |136.12Mb
  - disney_netflix_US |28.70Mb
  - disney_PY |104.07Mb
  - _212 |41.98Mb
  - disney_GB |179.85Mb
  - _201 |26.47Mb
  - _206 |44.44Mb
  - disney_SG |13.05Mb
  - _226 |13.71Mb
  - _220 |12.39Mb
  - Pool__229 |181.53Mb
  - Relay_-ğŸ‡­ğŸ‡°HK_210 |16.82Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_228 |10.32Mb
  - _214 |19.64Mb
  - _236 |24.56Mb
  - _230 |21.46Mb
  - _232 |11.50Mb
  - _233 |16.82Mb
  - _238 |88.73Mb
  - _234 |10.65Mb
  - _235 |15.44Mb
  - _239 |12.16Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_240 |10.44Mb
  - ğŸ‡²ğŸ‡½MX_274 |39.34Mb
  - disney_netflix_US |69.40Mb
  - ğŸ‡¬ğŸ‡§GB_268 |227.40Mb
  - ğŸ‡¬ğŸ‡§GB_269 |218.51Mb
  - netflix_NL |198.81Mb
  - disney_HK |21.66Mb
  - ğŸ‡­ğŸ‡°HK_272 |11.02Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_204 |11.77Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - Relay_-ğŸ‡ºğŸ‡¸US_197 |27.58Mb
  - disney_netflix_US |39.40Mb
  - _203 |14.45Mb
  - disney_netflix_US |41.10Mb
  - _188 |71.61Mb
  - _191 |159.31Mb
  - netflix_SE |136.12Mb
  - disney_netflix_US |28.70Mb
  - disney_PY |104.07Mb
  - _212 |41.98Mb
  - disney_GB |179.85Mb
  - _201 |26.47Mb
  - _206 |44.44Mb
  - disney_SG |13.05Mb
  - _226 |13.71Mb
  - _220 |12.39Mb
  - Pool__229 |181.53Mb
  - Relay_-ğŸ‡­ğŸ‡°HK_210 |16.82Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_228 |10.32Mb
  - _214 |19.64Mb
  - _236 |24.56Mb
  - _230 |21.46Mb
  - _232 |11.50Mb
  - _233 |16.82Mb
  - _238 |88.73Mb
  - _234 |10.65Mb
  - _235 |15.44Mb
  - _239 |12.16Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_240 |10.44Mb
  - ğŸ‡²ğŸ‡½MX_274 |39.34Mb
  - disney_netflix_US |69.40Mb
  - ğŸ‡¬ğŸ‡§GB_268 |227.40Mb
  - ğŸ‡¬ğŸ‡§GB_269 |218.51Mb
  - netflix_NL |198.81Mb
  - disney_HK |21.66Mb
  - ğŸ‡­ğŸ‡°HK_272 |11.02Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_204 |11.77Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
