port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: _112 |31.20Mb
  server: 23.95.72.81
  type: ss
  port: 443
  udp: true
  password: UAMVtHm54uahd6SiN5WcD16rsPSdabPG
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_US |46.03Mb
  server: usiys.southbyte.xyz
  type: trojan
  port: 5897
  udp: true
  password: fg20mtCFHy
  sni: usiys.southbyte.xyz
  skip-cert-verify: true
- name: disney_netflix_US |11.24Mb
  server: ufbji.zippydeal.xyz
  type: trojan
  port: 5743
  udp: true
  password: fg20mtCFHy
  sni: ufbji.zippydeal.xyz
  skip-cert-verify: true
- name: disney_netflix_US |56.01Mb
  server: 160.16.240.91
  type: trojan
  port: 4054
  password: 2cf6d686799e6fa95316394064f26c0a
  sni: www.nintendogames.net
- name: disney_netflix_NL |57.47Mb
  server: 82.38.31.176
  type: ss
  port: 8080
  udp: true
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_DE |50.71Mb
  server: 63.178.2.18
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: disney_netflix_DE |224.67Mb
  server: 3.65.219.59
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: disney_netflix_HK |10.16Mb
  server: 58.152.110.120
  type: trojan
  port: 443
  password: 2cf6d686799e6fa95316394064f26c0a
  sni: www.nintendogames.net
- name: netflix_BR |21.27Mb
  server: 38.180.16.86
  type: vmess
  country: ğŸ‡§ğŸ‡·BR
  port: 36236
  uuid: a58bc1a5-8c18-49ff-9453-c331b52f45dc
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_DE |737.90Mb
  server: frankfurt01.zgjok.com
  type: vmess
  port: 443
  uuid: b71579b1-6593-426d-90ac-f002fa96ade1
  alterId: 0
  cipher: auto
  network: ws
  servername: frankfurt01.zgjok.com
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /
    headers:
      Host: frankfurt01.zgjok.com
- name: netflix_BR |24.04Mb
  server: 38.180.16.86
  type: vmess
  country: ğŸ‡§ğŸ‡·BR
  port: 36104
  uuid: E146A8CB-9D2F-449C-ADCA-8736FB
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: netflix_MX |248.33Mb
  server: 216.238.89.53
  type: vmess
  country: ğŸ‡²ğŸ‡½MX
  port: 57283
  uuid: 1a5aafc0-6482-451d-fe76-6875b7818579
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_DE |171.14Mb
  server: 18.184.12.56
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: disney_netflix_FR |201.03Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 27092
  uuid: a0596ba6-72a3-4366-8992-77088da65bd8
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: _107 |10.05Mb
  server: 213.159.66.206
  type: ss
  port: 443
  udp: true
  password: pl2XtR0pzwknQOGwewbwXtPYDw1zn9Vu
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_DE |247.60Mb
  server: 54.93.211.165
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: disney_netflix_NL |244.94Mb
  server: 82.38.31.210
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_US |37.47Mb
  server: 216.167.107.61
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 44805
  uuid: f7d62526-9e06-455e-82bd-241d368002e8
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_US |55.34Mb
  server: 107.23.148.46
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: disney_netflix_NL |10.47Mb
  server: 45.87.175.166
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 443
  password: 1RWwXhwfAB5gAEozU4G2Pg
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_US |43.56Mb
  server: a3fyst.zeeoomboom.de
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  uuid: 03fcc618-b93d-6796-6aed-8a38c975d581
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /video/d4kapx2v.m3u8
- name: disney_netflix_US |85.72Mb
  server: xyst5w.teeoomboom.de
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  uuid: 03fcc618-b93d-6796-6aed-8a38c975d581
  alterId: 0
  cipher: auto
  network: ws
  servername: xyst5w.teeoomboom.de
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /video/g5petez.m3u8
    headers:
      HOST: xyst5w.teeoomboom.de
- name: netflix_NO |159.38Mb
  server: 89.46.233.148
  type: ss
  country: ğŸ‡·ğŸ‡´RO
  port: 443
  password: XeGAcwaviWxXzg87AwvnE6gWbhHHGwwB
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_DE |47.96Mb
  server: 62.133.60.43
  type: ss
  country: ğŸ‡·ğŸ‡ºRU
  port: 36456
  password: mqGN6VyYzNEq4O2s0zSOjM
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸ‡©ğŸ‡ªDE-ğŸ‡©ğŸ‡ªDE_160 |75.45Mb
  server: node4.rtxconfigz.com
  type: vmess
  country: ğŸ‡©ğŸ‡ªDE
  port: 443
  uuid: 44e57485-eccc-46ef-808f-cd17ac810018
  alterId: 0
  cipher: auto
  network: ws
  servername: node4.rtxconfigz.com
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /@Malinda6104
    headers:
      HOST: node4.rtxconfigz.com
- name: disney_netflix_TR |13.00Mb
  server: 185.39.204.189
  type: ss
  country: ğŸ‡·ğŸ‡ºRU
  port: 34085
  password: depjSbjv2Uql6W4Vge7sDf
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_TR |27.66Mb
  server: tr-1.stunnel.cc
  type: ss
  country: ğŸ‡¹ğŸ‡·TR
  port: 8444
  password: tunnel-fbrof
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸ‡­ğŸ‡°HK-ğŸ‡­ğŸ‡°HK_172 |22.98Mb
  server: n1761296893.lie5d.cyou
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 443
  uuid: 40f088bf-ed4b-4630-860f-45ed12c75ff7
  alterId: 0
  cipher: auto
  network: ws
  servername: n1761296893.lie5d.cyou
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /
    headers:
      HOST: n1761296893.lie5d.cyou
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - _112 |31.20Mb
  - disney_netflix_US |46.03Mb
  - disney_netflix_US |11.24Mb
  - disney_netflix_US |56.01Mb
  - disney_netflix_NL |57.47Mb
  - disney_netflix_DE |50.71Mb
  - disney_netflix_DE |224.67Mb
  - disney_netflix_HK |10.16Mb
  - netflix_BR |21.27Mb
  - disney_netflix_DE |737.90Mb
  - netflix_BR |24.04Mb
  - netflix_MX |248.33Mb
  - disney_netflix_DE |171.14Mb
  - disney_netflix_FR |201.03Mb
  - _107 |10.05Mb
  - disney_netflix_DE |247.60Mb
  - disney_netflix_NL |244.94Mb
  - disney_netflix_US |37.47Mb
  - disney_netflix_US |55.34Mb
  - disney_netflix_NL |10.47Mb
  - disney_netflix_US |43.56Mb
  - disney_netflix_US |85.72Mb
  - netflix_NO |159.38Mb
  - disney_netflix_DE |47.96Mb
  - Relay_ğŸ‡©ğŸ‡ªDE-ğŸ‡©ğŸ‡ªDE_160 |75.45Mb
  - disney_netflix_TR |13.00Mb
  - disney_netflix_TR |27.66Mb
  - Relay_ğŸ‡­ğŸ‡°HK-ğŸ‡­ğŸ‡°HK_172 |22.98Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - _112 |31.20Mb
  - disney_netflix_US |46.03Mb
  - disney_netflix_US |11.24Mb
  - disney_netflix_US |56.01Mb
  - disney_netflix_NL |57.47Mb
  - disney_netflix_DE |50.71Mb
  - disney_netflix_DE |224.67Mb
  - disney_netflix_HK |10.16Mb
  - netflix_BR |21.27Mb
  - disney_netflix_DE |737.90Mb
  - netflix_BR |24.04Mb
  - netflix_MX |248.33Mb
  - disney_netflix_DE |171.14Mb
  - disney_netflix_FR |201.03Mb
  - _107 |10.05Mb
  - disney_netflix_DE |247.60Mb
  - disney_netflix_NL |244.94Mb
  - disney_netflix_US |37.47Mb
  - disney_netflix_US |55.34Mb
  - disney_netflix_NL |10.47Mb
  - disney_netflix_US |43.56Mb
  - disney_netflix_US |85.72Mb
  - netflix_NO |159.38Mb
  - disney_netflix_DE |47.96Mb
  - Relay_ğŸ‡©ğŸ‡ªDE-ğŸ‡©ğŸ‡ªDE_160 |75.45Mb
  - disney_netflix_TR |13.00Mb
  - disney_netflix_TR |27.66Mb
  - Relay_ğŸ‡­ğŸ‡°HK-ğŸ‡­ğŸ‡°HK_172 |22.98Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
