port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: _224 |50.16Mb
  server: 137.184.174.93
  type: ss
  port: 8080
  udp: true
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: _226 |27.82Mb
  server: 23.95.72.81
  type: ss
  port: 443
  udp: true
  password: UAMVtHm54uahd6SiN5WcD16rsPSdabPG
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_NL |57.47Mb
  server: 82.38.31.176
  type: ss
  port: 8080
  udp: true
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: _223 |16.52Mb
  server: 185.156.110.92
  type: ss
  port: 443
  udp: true
  password: gXOXk2FJwsz9P6nXIICuDNOqF9gWX1dn
  cipher: chacha20-ietf-poly1305
- name: _221 |10.85Mb
  server: 213.159.67.124
  type: ss
  port: 443
  udp: true
  password: mbhqsStnFQT1cTZYCdsmkugGUC6GT6rp
  cipher: chacha20-ietf-poly1305
- name: netflix_IE |325.72Mb
  server: 18.203.224.78
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: disney_JP |17.33Mb
  server: gd.bjnet2.com
  type: ss
  port: 36609
  udp: true
  password: 84d85af8-2807-4306-a701-f784676b77c3
  cipher: aes-128-gcm
  plugin: obfs
  plugin-opts:
    host: de5bdbffa87896a4b126f8b62150bb4e.baidu.com
    mode: http
- name: disney_netflix_US |26.24Mb
  server: gd.bjnet2.com
  type: ss
  port: 36608
  udp: true
  password: 84d85af8-2807-4306-a701-f784676b77c3
  cipher: aes-128-gcm
  plugin: obfs
  plugin-opts:
    host: de5bdbffa87896a4b126f8b62150bb4e.baidu.com
    mode: http
- name: disney_HK |22.51Mb
  server: gd.bjnet2.com
  type: ss
  port: 36602
  udp: true
  password: 84d85af8-2807-4306-a701-f784676b77c3
  cipher: aes-128-gcm
  plugin: obfs
  plugin-opts:
    host: de5bdbffa87896a4b126f8b62150bb4e.baidu.com
    mode: http
- name: _231 |10.05Mb
  server: 213.159.66.206
  type: ss
  port: 443
  udp: true
  password: pl2XtR0pzwknQOGwewbwXtPYDw1zn9Vu
  cipher: chacha20-ietf-poly1305
- name: disney_MD |11.34Mb
  server: 185.153.197.5
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: Relay_-ğŸ‡ºğŸ‡¸US_235 |34.85Mb
  server: 38.14.99.163
  type: vmess
  port: 59807
  udp: true
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 64
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_US |48.93Mb
  server: 104.18.13.167
  type: vmess
  port: 443
  udp: true
  uuid: 24254866-770c-41b4-9404-3f50524f425b
  alterId: 0
  cipher: auto
  network: ws
  servername: 24254866-770c-41b4-9404-3f50524f425b.mihomo.baby
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /saoihgreg9384gh8934
    headers:
      Host: 24254866-770c-41b4-9404-3f50524f425b.mihomo.baby
- name: disney_DE |247.23Mb
  server: uk2-2.998998.best
  type: vmess
  port: 443
  udp: true
  uuid: 24254866-770c-41b4-9404-3f50524f425b
  alterId: 0
  cipher: auto
  network: ws
  servername: 24254866-770c-41b4-9404-3f50524f425b.placeunaorder.fun
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /logcatxiouerd34try9
    headers:
      Host: 24254866-770c-41b4-9404-3f50524f425b.placeunaorder.fun
- name: Relay_-ğŸ‡ºğŸ‡¸US_242 |12.90Mb
  server: 82.198.246.97
  type: vmess
  port: 180
  uuid: d13fc2f5-3e05-4795-81eb-44143a09e552
  alterId: 0
  cipher: auto
  network: tcp
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_-ğŸ‡«ğŸ‡·FR_239 |75.03Mb
  server: 81.12.33.182
  type: vmess
  port: 2021
  udp: true
  uuid: 52c6cfaf-34fb-4e91-9a8d-d4391ab3d8c4
  alterId: 0
  cipher: auto
  network: http
  http-opts:
    method: GET
    path:
    - /api/register/new/name/dav/response/cmV0aXJlZCBoZWxsbyBob3cgYXJlIHlvdSB0aGlzIGlzIG15IG5ldyBoZWFkZXIgd
  h2-opts: {}
- name: Relay_-ğŸ‡ºğŸ‡¸US_244 |35.35Mb
  server: 38.14.99.179
  type: vmess
  port: 59807
  udp: true
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 64
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: _243 |10.40Mb
  server: 45.136.244.201
  type: vmess
  port: 49934
  uuid: 90afa47d-341a-497d-ae25-1d81258804d5
  alterId: 0
  cipher: auto
  network: tcp
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_-ğŸ‡ºğŸ‡¸US_236 |42.37Mb
  server: us19-25.998998.best
  type: vmess
  port: 443
  udp: true
  uuid: 24254866-770c-41b4-9404-3f50524f425b
  alterId: 0
  cipher: auto
  network: ws
  servername: 24254866-770c-41b4-9404-3f50524f425b.mihomo.baby
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /saoihgreg9384gh8934
    headers:
      Host: 24254866-770c-41b4-9404-3f50524f425b.mihomo.baby
- name: Relay_-ğŸ‡­ğŸ‡°HK_233 |21.77Mb
  server: www.zhoubowen.vip
  type: vmess
  port: 443
  udp: true
  uuid: 71b2655e-07d9-4dad-a770-a2b08275142b
  alterId: 0
  cipher: auto
  network: ws
  servername: www.zhoubowen.vip
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /biutefor.icu
    headers:
      Host: www.zhoubowen.vip
- name: Relay_-ğŸ‡­ğŸ‡°HK_234 |14.86Mb
  server: www.zhoubowen.vip
  type: vmess
  port: 443
  udp: true
  uuid: 0e3b1c9b-a6f3-49d4-9b60-9f0072727e67
  alterId: 0
  cipher: auto
  network: ws
  servername: www.zhoubowen.vip
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /biutefor.icu
    headers:
      Host: www.zhoubowen.vip
- name: Relay_-ğŸ‡ºğŸ‡¸US_269 |35.56Mb
  server: usiys.southbyte.xyz
  type: trojan
  port: 5897
  udp: true
  password: fg20mtCFHy
  sni: usiys.southbyte.xyz
  skip-cert-verify: true
- name: ğŸ‡§ğŸ‡·BR_281 |19.38Mb
  server: 38.180.16.86
  type: vmess
  country: ğŸ‡§ğŸ‡·BR
  port: 36236
  uuid: a58bc1a5-8c18-49ff-9453-c331b52f45dc
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡§ğŸ‡·BR_282 |16.87Mb
  server: 38.180.16.86
  type: vmess
  country: ğŸ‡§ğŸ‡·BR
  port: 36104
  uuid: E146A8CB-9D2F-449C-ADCA-8736FB
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_-ğŸ‡¯ğŸ‡µJP_279 |21.96Mb
  server: 153.121.44.99
  type: trojan
  port: 3093
  password: 2cf6d686799e6fa95316394064f26c0a
  sni: www.nintendogames.net
- name: disney_FR |201.03Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 27092
  uuid: a0596ba6-72a3-4366-8992-77088da65bd8
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_NL |70.20Mb
  server: 82.38.31.217
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: Relay_-ğŸ‡ºğŸ‡¸US_245 |71.45Mb
  server: v24.hdacd.com
  type: vmess
  port: 30824
  udp: true
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_HK |10.98Mb
  server: green2.cdntencentmusic.com
  type: trojan
  port: 31102
  udp: true
  password: fac2c4d4-6c0d-4446-96b6-1234b884cc49
  sni: green2.cdntencentmusic.com
  skip-cert-verify: true
- name: disney_netflix_NL |239.58Mb
  server: 82.38.31.210
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_US |54.58Mb
  server: 107.23.148.46
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡²ğŸ‡½MX_300 |38.19Mb
  server: 216.238.89.53
  type: vmess
  country: ğŸ‡²ğŸ‡½MX
  port: 57283
  uuid: 1a5aafc0-6482-451d-fe76-6875b7818579
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_NL |44.65Mb
  server: 45.87.175.174
  type: ss
  country: ğŸ‡±ğŸ‡¹ LT
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: disney_US |36.87Mb
  server: 216.167.107.61
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 44805
  uuid: f7d62526-9e06-455e-82bd-241d368002e8
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡°ğŸ‡·KR_298 |10.10Mb
  server: 146.56.112.110
  type: vmess
  country: ğŸ‡°ğŸ‡·KR
  port: 8888
  uuid: e7c302f3-90d6-42dd-9d7d-94a3683a3707
  alterId: 0
  cipher: auto
  network: tcp
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡ºğŸ‡¸US_306 |36.81Mb
  server: 74.117.196.232
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 37934
  uuid: 9631096d-3032-4942-9446-bdf12665682b
  alterId: 0
  cipher: auto
  network: ws
  servername: imafake.locker
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /speedtest
    headers:
      HOST: imafake.locker
- name: Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡®ğŸ‡·IR_302 |11.73Mb
  server: cf.fovi.tk
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  uuid: bf67437e-6c90-45ca-abc2-c7240a5ce2aa
  alterId: 0
  cipher: auto
  network: ws
  servername: foxlux.fovi.tk
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /eisasqa
    headers:
      HOST: foxlux.fovi.tk
- name: disney_NL |27.17Mb
  server: 109.71.246.210
  type: ss
  port: 56689
  udp: true
  password: YQCSKoCF3QazW8YlvDBWA4
  cipher: chacha20-ietf-poly1305
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - _224 |50.16Mb
  - _226 |27.82Mb
  - disney_netflix_NL |57.47Mb
  - _223 |16.52Mb
  - _221 |10.85Mb
  - netflix_IE |325.72Mb
  - disney_JP |17.33Mb
  - disney_netflix_US |26.24Mb
  - disney_HK |22.51Mb
  - _231 |10.05Mb
  - disney_MD |11.34Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_235 |34.85Mb
  - disney_netflix_US |48.93Mb
  - disney_DE |247.23Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_242 |12.90Mb
  - Relay_-ğŸ‡«ğŸ‡·FR_239 |75.03Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_244 |35.35Mb
  - _243 |10.40Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_236 |42.37Mb
  - Relay_-ğŸ‡­ğŸ‡°HK_233 |21.77Mb
  - Relay_-ğŸ‡­ğŸ‡°HK_234 |14.86Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_269 |35.56Mb
  - ğŸ‡§ğŸ‡·BR_281 |19.38Mb
  - ğŸ‡§ğŸ‡·BR_282 |16.87Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_279 |21.96Mb
  - disney_FR |201.03Mb
  - disney_netflix_NL |70.20Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_245 |71.45Mb
  - disney_HK |10.98Mb
  - disney_netflix_NL |239.58Mb
  - disney_netflix_US |54.58Mb
  - ğŸ‡²ğŸ‡½MX_300 |38.19Mb
  - disney_netflix_NL |44.65Mb
  - disney_US |36.87Mb
  - ğŸ‡°ğŸ‡·KR_298 |10.10Mb
  - ğŸ‡ºğŸ‡¸US_306 |36.81Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡®ğŸ‡·IR_302 |11.73Mb
  - disney_NL |27.17Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - _224 |50.16Mb
  - _226 |27.82Mb
  - disney_netflix_NL |57.47Mb
  - _223 |16.52Mb
  - _221 |10.85Mb
  - netflix_IE |325.72Mb
  - disney_JP |17.33Mb
  - disney_netflix_US |26.24Mb
  - disney_HK |22.51Mb
  - _231 |10.05Mb
  - disney_MD |11.34Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_235 |34.85Mb
  - disney_netflix_US |48.93Mb
  - disney_DE |247.23Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_242 |12.90Mb
  - Relay_-ğŸ‡«ğŸ‡·FR_239 |75.03Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_244 |35.35Mb
  - _243 |10.40Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_236 |42.37Mb
  - Relay_-ğŸ‡­ğŸ‡°HK_233 |21.77Mb
  - Relay_-ğŸ‡­ğŸ‡°HK_234 |14.86Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_269 |35.56Mb
  - ğŸ‡§ğŸ‡·BR_281 |19.38Mb
  - ğŸ‡§ğŸ‡·BR_282 |16.87Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_279 |21.96Mb
  - disney_FR |201.03Mb
  - disney_netflix_NL |70.20Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_245 |71.45Mb
  - disney_HK |10.98Mb
  - disney_netflix_NL |239.58Mb
  - disney_netflix_US |54.58Mb
  - ğŸ‡²ğŸ‡½MX_300 |38.19Mb
  - disney_netflix_NL |44.65Mb
  - disney_US |36.87Mb
  - ğŸ‡°ğŸ‡·KR_298 |10.10Mb
  - ğŸ‡ºğŸ‡¸US_306 |36.81Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡®ğŸ‡·IR_302 |11.73Mb
  - disney_NL |27.17Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
