port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: disney_netflix_US |41.46Mb
  server: 38.14.99.179
  type: vmess
  port: 59807
  udp: true
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: _298 |12.14Mb
  server: 74.117.196.232
  type: vmess
  port: 37934
  udp: true
  uuid: 254551f6-ec28-4938-ad0e-0aa4aa1965ec
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /speedtest
- name: disney_netflix_NO |14.08Mb
  server: 107.174.114.71
  type: ss
  port: 443
  password: 595HLF3fHUuw0McM51tpvPygSIB1uf4D
  cipher: chacha20-ietf-poly1305
- name: Relay_-ğŸ‡³ğŸ‡±NL_422 |40.67Mb
  server: 160.16.236.32
  type: trojan
  port: 4054
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¯ğŸ‡µJP_417 |14.73Mb
  server: 153.121.65.107
  type: trojan
  port: 1331
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡³ğŸ‡±NL_425 |24.84Mb
  server: 160.16.57.238
  type: trojan
  port: 4054
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡³ğŸ‡±NL_424 |47.10Mb
  server: 160.16.131.243
  type: trojan
  port: 2890
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡³ğŸ‡±NL_419 |44.63Mb
  server: 160.16.151.196
  type: trojan
  port: 2890
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡³ğŸ‡±NL_430 |46.92Mb
  server: 160.16.116.227
  type: trojan
  port: 2890
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¸ğŸ‡¬SG_426 |16.96Mb
  server: 160.16.131.243
  type: trojan
  port: 127
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: disney_netflix_NL |187.01Mb
  server: 82.38.31.190
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_NL |18.48Mb
  server: 82.38.31.179
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: Relay_-ğŸ‡¸ğŸ‡¬SG_433 |10.39Mb
  server: 160.16.107.37
  type: trojan
  port: 507
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: netflix_AL |53.59Mb
  server: 87.121.162.249
  type: ss
  country: ğŸ‡­ğŸ‡°HK
  port: 443
  password: JGv616hMWdjfuZ00jYfq7XkBHJZrOBrg
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡§ğŸ‡·BR_436 |18.35Mb
  server: 38.180.16.86
  type: vmess
  country: ğŸ‡§ğŸ‡·BR
  port: 36104
  uuid: E146A8CB-9D2F-449C-ADCA-8736FB
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: netflix_MX |40.73Mb
  server: 216.238.89.53
  type: vmess
  country: ğŸ‡²ğŸ‡½MX
  port: 57283
  uuid: 1a5aafc0-6482-451d-fe76-6875b7818579
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡ºğŸ‡¸US_527 |151.39Mb
  server: 104.192.226.106
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ğŸ‡·ğŸ‡ºRU_516 |65.83Mb
  server: 109.71.246.210
  type: ss
  country: ğŸ‡·ğŸ‡ºRU
  port: 56689
  password: YQCSKoCF3QazW8YlvDBWA4
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_US |41.31Mb
  server: 38.14.99.163
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 59807
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: auto
  network: tcp
  servername: 38.14.99.163
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: netflix_LT |120.35Mb
  server: 45.12.136.170
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: l668XHPejoSNNuD66BYzyehaCpZexiF7
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡­ğŸ‡°HK_499 |22.91Mb
  server: 47.242.140.52
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 48219
  uuid: 006893c6-79b1-4c44-94ff-b8bbea065f1f
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
  ws-opts:
    path: /arki?ed=2048
- name: ğŸ‡²ğŸ‡¾MY_514 |15.60Mb
  server: 38.54.98.110
  type: vmess
  country: ğŸ‡²ğŸ‡¾MY
  port: 2052
  uuid: 665d9b8f-153d-4907-adac-de12afd9c851
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: ğŸ‡ºğŸ‡¸US_534 |10.63Mb
  server: 45.136.12.37
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 38141
  uuid: fd291be6-b48d-43a1-da38-66c7f80e2f80
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - disney_netflix_US |41.46Mb
  - _298 |12.14Mb
  - disney_netflix_NO |14.08Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_422 |40.67Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_417 |14.73Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_425 |24.84Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_424 |47.10Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_419 |44.63Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_430 |46.92Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_426 |16.96Mb
  - disney_netflix_NL |187.01Mb
  - disney_netflix_NL |18.48Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_433 |10.39Mb
  - netflix_AL |53.59Mb
  - ğŸ‡§ğŸ‡·BR_436 |18.35Mb
  - netflix_MX |40.73Mb
  - ğŸ‡ºğŸ‡¸US_527 |151.39Mb
  - ğŸ‡·ğŸ‡ºRU_516 |65.83Mb
  - disney_netflix_US |41.31Mb
  - netflix_LT |120.35Mb
  - ğŸ‡­ğŸ‡°HK_499 |22.91Mb
  - ğŸ‡²ğŸ‡¾MY_514 |15.60Mb
  - ğŸ‡ºğŸ‡¸US_534 |10.63Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - disney_netflix_US |41.46Mb
  - _298 |12.14Mb
  - disney_netflix_NO |14.08Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_422 |40.67Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_417 |14.73Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_425 |24.84Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_424 |47.10Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_419 |44.63Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_430 |46.92Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_426 |16.96Mb
  - disney_netflix_NL |187.01Mb
  - disney_netflix_NL |18.48Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_433 |10.39Mb
  - netflix_AL |53.59Mb
  - ğŸ‡§ğŸ‡·BR_436 |18.35Mb
  - netflix_MX |40.73Mb
  - ğŸ‡ºğŸ‡¸US_527 |151.39Mb
  - ğŸ‡·ğŸ‡ºRU_516 |65.83Mb
  - disney_netflix_US |41.31Mb
  - netflix_LT |120.35Mb
  - ğŸ‡­ğŸ‡°HK_499 |22.91Mb
  - ğŸ‡²ğŸ‡¾MY_514 |15.60Mb
  - ğŸ‡ºğŸ‡¸US_534 |10.63Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
