port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: disney_netflix_US |35.97Mb
  server: 172.235.33.114
  type: vmess
  port: 10001
  uuid: 442a3923-eca1-4af0-b3ff-24a7ce0af68f
  alterId: 0
  cipher: auto
  network: tcp
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_TW |31.50Mb
  server: 141.193.213.199
  type: trojan
  port: 443
  udp: true
  password: a8a5b34d-fe46-487d-bd6a-d9f3101525fd
  sni: 26z68w0ecxbuyf89.ukgogo202511.top
  skip-cert-verify: true
  ws-opts:
    path: /images
    headers:
      Host: 26z68w0ecxbuyf89.ukgogo202511.top
  network: ws
- name: disney_netflix_NL |295.44Mb
  server: 151.242.251.144
  type: ss
  port: 8080
  udp: true
  password: QCXDxuDlTTMD7jtgHUjIoj
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_NL |13.09Mb
  server: 109.71.246.210
  type: ss
  port: 56689
  udp: true
  password: YQCSKoCF3QazW8YlvDBWA4
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_NL |335.67Mb
  server: 45.87.175.177
  type: ss
  port: 8080
  udp: true
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_NL |278.13Mb
  server: 82.38.31.218
  type: ss
  port: 8080
  udp: true
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: netflix_PL |71.90Mb
  server: 45.15.126.19
  type: ss
  port: 443
  udp: true
  password: 6Ts2ZDTQAf3hkFoB8AFufDwsGrlF4e2t
  cipher: chacha20-ietf-poly1305
- name: netflix_ES |18.53Mb
  server: 213.159.67.124
  type: ss
  port: 443
  password: mbhqsStnFQT1cTZYCdsmkugGUC6GT6rp
  cipher: chacha20-ietf-poly1305
- name: Relay_-ğŸ‡³ğŸ‡±NL_138 |10.19Mb
  server: 160.16.89.176
  type: trojan
  port: 2890
  password: 2cf6d686799e6fa95316394064f26c0a
  sni: www.nintendogames.net
- name: disney_PT |267.35Mb
  server: 185.231.233.112
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: _129 |18.88Mb
  server: 103.106.3.82
  type: ss
  port: 443
  udp: true
  password: 4SaCIazlgumYkM8FkPzlmwjpyWBDZFBk
  cipher: chacha20-ietf-poly1305
- name: Relay_-ğŸ‡³ğŸ‡±NL_140 |10.52Mb
  server: 160.16.196.59
  type: trojan
  port: 2760
  password: 2cf6d686799e6fa95316394064f26c0a
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¸ğŸ‡¬SG_151 |10.27Mb
  server: 160.16.89.176
  type: trojan
  port: 127
  password: 2cf6d686799e6fa95316394064f26c0a
  sni: www.nintendogames.net
- name: disney_netflix_US |58.87Mb
  server: 160.16.196.59
  type: trojan
  port: 4054
  password: 2cf6d686799e6fa95316394064f26c0a
  sni: www.nintendogames.net
- name: disney_netflix_US |40.78Mb
  server: 160.16.204.136
  type: trojan
  port: 2890
  password: 2cf6d686799e6fa95316394064f26c0a
  sni: www.nintendogames.net
- name: disney_netflix_FR |40.96Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 27092
  uuid: a0596ba6-72a3-4366-8992-77088da65bd8
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_US |48.02Mb
  server: us19-25.998998.best
  type: vmess
  port: 443
  udp: true
  uuid: 24254866-770c-41b4-9404-3f50524f425b
  alterId: 0
  cipher: auto
  network: ws
  servername: 24254866-770c-41b4-9404-3f50524f425b.mihomo.baby
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /saoihgreg9384gh8934
    headers:
      Host: 24254866-770c-41b4-9404-3f50524f425b.mihomo.baby
- name: disney_TW |10.05Mb
  server: f7c5a058-fa4a-4f7c-aed6-203efaf52286.f1eb10ae-1d82-4c6a-b4dd-bd9525520956.com
  type: trojan
  country: ğŸ‡®ğŸ‡ªIE
  port: 12105
  udp: true
  password: 05bf6017-75c3-44c1-b9bf-6a038107afde
  skip-cert-verify: true
- name: Relay_ğŸ‡®ğŸ‡ªIE-ğŸ‡®ğŸ‡·IR_164 |62.14Mb
  server: f7c5a058-fa4a-4f7c-aed6-203efaf52286.f1eb10ae-1d82-4c6a-b4dd-bd9525520956.com
  type: trojan
  country: ğŸ‡®ğŸ‡ªIE
  port: 10104
  udp: true
  password: 05bf6017-75c3-44c1-b9bf-6a038107afde
  sni: sni.eos-suzhou-4.cmecloud.cn
  skip-cert-verify: true
- name: Relay_ğŸ‡®ğŸ‡ªIE-ğŸ‡®ğŸ‡·IR_157 |64.53Mb
  server: f7c5a058-fa4a-4f7c-aed6-203efaf52286.f1eb10ae-1d82-4c6a-b4dd-bd9525520956.com
  type: trojan
  country: ğŸ‡®ğŸ‡ªIE
  port: 10103
  udp: true
  password: 05bf6017-75c3-44c1-b9bf-6a038107afde
  sni: sni.eos-suzhou-4.cmecloud.cn
  skip-cert-verify: true
- name: disney_TW |10.88Mb
  server: f7c5a058-fa4a-4f7c-aed6-203efaf52286.f1eb10ae-1d82-4c6a-b4dd-bd9525520956.com
  type: trojan
  country: ğŸ‡®ğŸ‡ªIE
  port: 12103
  udp: true
  password: 05bf6017-75c3-44c1-b9bf-6a038107afde
  sni: 116.yuanul.com
  skip-cert-verify: true
- name: Relay_ğŸ‡®ğŸ‡ªIE-ğŸ‡®ğŸ‡·IR_172 |67.37Mb
  server: f7c5a058-fa4a-4f7c-aed6-203efaf52286.f1eb10ae-1d82-4c6a-b4dd-bd9525520956.com
  type: trojan
  country: ğŸ‡®ğŸ‡ªIE
  port: 10106
  udp: true
  password: 05bf6017-75c3-44c1-b9bf-6a038107afde
  sni: sni.eos-suzhou-4.cmecloud.cn
  skip-cert-verify: true
- name: Relay_ğŸ‡®ğŸ‡ªIE-ğŸ‡®ğŸ‡·IR_170 |69.35Mb
  server: f7c5a058-fa4a-4f7c-aed6-203efaf52286.f1eb10ae-1d82-4c6a-b4dd-bd9525520956.com
  type: trojan
  country: ğŸ‡®ğŸ‡ªIE
  port: 10107
  udp: true
  password: 05bf6017-75c3-44c1-b9bf-6a038107afde
  sni: sni.eos-suzhou-4.cmecloud.cn
  skip-cert-verify: true
- name: Relay_ğŸ‡®ğŸ‡ªIE-ğŸ‡®ğŸ‡·IR_168 |50.35Mb
  server: f7c5a058-fa4a-4f7c-aed6-203efaf52286.f1eb10ae-1d82-4c6a-b4dd-bd9525520956.com
  type: trojan
  country: ğŸ‡®ğŸ‡ªIE
  port: 10108
  udp: true
  password: 05bf6017-75c3-44c1-b9bf-6a038107afde
  sni: sni.eos-suzhou-4.cmecloud.cn
  skip-cert-verify: true
- name: disney_HK |65.90Mb
  server: f7c5a058-fa4a-4f7c-aed6-203efaf52286.f1eb10ae-1d82-4c6a-b4dd-bd9525520956.com
  type: trojan
  country: ğŸ‡®ğŸ‡ªIE
  port: 10102
  udp: true
  password: 05bf6017-75c3-44c1-b9bf-6a038107afde
  sni: sni.eos-suzhou-4.cmecloud.cn
  skip-cert-verify: true
- name: Relay_ğŸ‡®ğŸ‡ªIE-ğŸ‡®ğŸ‡·IR_165 |53.20Mb
  server: f7c5a058-fa4a-4f7c-aed6-203efaf52286.f1eb10ae-1d82-4c6a-b4dd-bd9525520956.com
  type: trojan
  country: ğŸ‡®ğŸ‡ªIE
  port: 10101
  udp: true
  password: 05bf6017-75c3-44c1-b9bf-6a038107afde
  sni: sni.eos-suzhou-4.cmecloud.cn
  skip-cert-verify: true
- name: Relay_ğŸ‡®ğŸ‡ªIE-ğŸ‡ªğŸ‡¸ES_169 |10.09Mb
  server: f7c5a058-fa4a-4f7c-aed6-203efaf52286.f1eb10ae-1d82-4c6a-b4dd-bd9525520956.com
  type: trojan
  country: ğŸ‡®ğŸ‡ªIE
  port: 12016
  udp: true
  password: 05bf6017-75c3-44c1-b9bf-6a038107afde
  sni: sg6.yuanul.com
  skip-cert-verify: true
- name: disney_netflix_NL |304.47Mb
  server: 151.242.251.144
  type: ss
  country: ğŸ‡®ğŸ‡· IR
  port: 8080
  password: 4a2rfixophdjffa8KVA4Aa
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_NL |320.51Mb
  server: 151.242.251.153
  type: ss
  country: ğŸ‡®ğŸ‡· IR
  port: 8080
  password: QCXDxuDlTTMD7jtgHUjIoj
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_US |35.97Mb
  server: 74.117.196.232
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 37934
  uuid: f1a513d2-c32a-49dc-8e64-d4f8a2f1e001
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /speedtest
- name: disney_US |10.06Mb
  server: f7c5a058-fa4a-4f7c-aed6-203efaf52286.f1eb10ae-1d82-4c6a-b4dd-bd9525520956.com
  type: trojan
  country: ğŸ‡®ğŸ‡ªIE
  port: 13207
  udp: true
  password: 05bf6017-75c3-44c1-b9bf-6a038107afde
  sni: 140.yuanul.com
  skip-cert-verify: true
- name: disney_HK |61.63Mb
  server: f7c5a058-fa4a-4f7c-aed6-203efaf52286.f1eb10ae-1d82-4c6a-b4dd-bd9525520956.com
  type: trojan
  country: ğŸ‡®ğŸ‡ªIE
  port: 10105
  udp: true
  password: 05bf6017-75c3-44c1-b9bf-6a038107afde
  sni: sni.eos-suzhou-4.cmecloud.cn
  skip-cert-verify: true
- name: disney_netflix_US |44.54Mb
  server: f7c5a058-fa4a-4f7c-aed6-203efaf52286.f1eb10ae-1d82-4c6a-b4dd-bd9525520956.com
  type: trojan
  country: ğŸ‡®ğŸ‡ªIE
  port: 13206
  udp: true
  password: 05bf6017-75c3-44c1-b9bf-6a038107afde
  sni: 138.yuanul.com
  skip-cert-verify: true
- name: disney_TW |10.57Mb
  server: f7c5a058-fa4a-4f7c-aed6-203efaf52286.f1eb10ae-1d82-4c6a-b4dd-bd9525520956.com
  type: trojan
  country: ğŸ‡®ğŸ‡ªIE
  port: 12101
  udp: true
  password: 05bf6017-75c3-44c1-b9bf-6a038107afde
  sni: 104.yuanul.com
  skip-cert-verify: true
- name: disney_US |43.22Mb
  server: f7c5a058-fa4a-4f7c-aed6-203efaf52286.f1eb10ae-1d82-4c6a-b4dd-bd9525520956.com
  type: trojan
  country: ğŸ‡®ğŸ‡ªIE
  port: 13204
  udp: true
  password: 05bf6017-75c3-44c1-b9bf-6a038107afde
  sni: 136.yuanul.com
  skip-cert-verify: true
- name: Relay_ğŸ‡®ğŸ‡ªIE-ğŸ‡ºğŸ‡¸US_194 |44.01Mb
  server: f7c5a058-fa4a-4f7c-aed6-203efaf52286.f1eb10ae-1d82-4c6a-b4dd-bd9525520956.com
  type: trojan
  country: ğŸ‡®ğŸ‡ªIE
  port: 13202
  udp: true
  password: 05bf6017-75c3-44c1-b9bf-6a038107afde
  sni: 135.yuanul.com
  skip-cert-verify: true
- name: netflix_JP |12.62Mb
  server: xray.kk37005.tk
  type: vmess
  country: ğŸ‡¯ğŸ‡µJP
  port: 55919
  uuid: 2e7548bb-7c5b-4d97-d64d-1b2fe4050089
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: disney_netflix_US |109.58Mb
  server: cf.fovi.tk
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  uuid: bf67437e-6c90-45ca-abc2-c7240a5ce2aa
  alterId: 0
  cipher: auto
  network: ws
  servername: foxpol.fovi.tk
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /eisasqa
    headers:
      HOST: foxpol.fovi.tk
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - disney_netflix_US |35.97Mb
  - disney_TW |31.50Mb
  - disney_netflix_NL |295.44Mb
  - disney_netflix_NL |13.09Mb
  - disney_netflix_NL |335.67Mb
  - disney_netflix_NL |278.13Mb
  - netflix_PL |71.90Mb
  - netflix_ES |18.53Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_138 |10.19Mb
  - disney_PT |267.35Mb
  - _129 |18.88Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_140 |10.52Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_151 |10.27Mb
  - disney_netflix_US |58.87Mb
  - disney_netflix_US |40.78Mb
  - disney_netflix_FR |40.96Mb
  - disney_netflix_US |48.02Mb
  - disney_TW |10.05Mb
  - Relay_ğŸ‡®ğŸ‡ªIE-ğŸ‡®ğŸ‡·IR_164 |62.14Mb
  - Relay_ğŸ‡®ğŸ‡ªIE-ğŸ‡®ğŸ‡·IR_157 |64.53Mb
  - disney_TW |10.88Mb
  - Relay_ğŸ‡®ğŸ‡ªIE-ğŸ‡®ğŸ‡·IR_172 |67.37Mb
  - Relay_ğŸ‡®ğŸ‡ªIE-ğŸ‡®ğŸ‡·IR_170 |69.35Mb
  - Relay_ğŸ‡®ğŸ‡ªIE-ğŸ‡®ğŸ‡·IR_168 |50.35Mb
  - disney_HK |65.90Mb
  - Relay_ğŸ‡®ğŸ‡ªIE-ğŸ‡®ğŸ‡·IR_165 |53.20Mb
  - Relay_ğŸ‡®ğŸ‡ªIE-ğŸ‡ªğŸ‡¸ES_169 |10.09Mb
  - disney_netflix_NL |304.47Mb
  - disney_netflix_NL |320.51Mb
  - disney_netflix_US |35.97Mb
  - disney_US |10.06Mb
  - disney_HK |61.63Mb
  - disney_netflix_US |44.54Mb
  - disney_TW |10.57Mb
  - disney_US |43.22Mb
  - Relay_ğŸ‡®ğŸ‡ªIE-ğŸ‡ºğŸ‡¸US_194 |44.01Mb
  - netflix_JP |12.62Mb
  - disney_netflix_US |109.58Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - disney_netflix_US |35.97Mb
  - disney_TW |31.50Mb
  - disney_netflix_NL |295.44Mb
  - disney_netflix_NL |13.09Mb
  - disney_netflix_NL |335.67Mb
  - disney_netflix_NL |278.13Mb
  - netflix_PL |71.90Mb
  - netflix_ES |18.53Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_138 |10.19Mb
  - disney_PT |267.35Mb
  - _129 |18.88Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_140 |10.52Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_151 |10.27Mb
  - disney_netflix_US |58.87Mb
  - disney_netflix_US |40.78Mb
  - disney_netflix_FR |40.96Mb
  - disney_netflix_US |48.02Mb
  - disney_TW |10.05Mb
  - Relay_ğŸ‡®ğŸ‡ªIE-ğŸ‡®ğŸ‡·IR_164 |62.14Mb
  - Relay_ğŸ‡®ğŸ‡ªIE-ğŸ‡®ğŸ‡·IR_157 |64.53Mb
  - disney_TW |10.88Mb
  - Relay_ğŸ‡®ğŸ‡ªIE-ğŸ‡®ğŸ‡·IR_172 |67.37Mb
  - Relay_ğŸ‡®ğŸ‡ªIE-ğŸ‡®ğŸ‡·IR_170 |69.35Mb
  - Relay_ğŸ‡®ğŸ‡ªIE-ğŸ‡®ğŸ‡·IR_168 |50.35Mb
  - disney_HK |65.90Mb
  - Relay_ğŸ‡®ğŸ‡ªIE-ğŸ‡®ğŸ‡·IR_165 |53.20Mb
  - Relay_ğŸ‡®ğŸ‡ªIE-ğŸ‡ªğŸ‡¸ES_169 |10.09Mb
  - disney_netflix_NL |304.47Mb
  - disney_netflix_NL |320.51Mb
  - disney_netflix_US |35.97Mb
  - disney_US |10.06Mb
  - disney_HK |61.63Mb
  - disney_netflix_US |44.54Mb
  - disney_TW |10.57Mb
  - disney_US |43.22Mb
  - Relay_ğŸ‡®ğŸ‡ªIE-ğŸ‡ºğŸ‡¸US_194 |44.01Mb
  - netflix_JP |12.62Mb
  - disney_netflix_US |109.58Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
