port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: disney_netflix_US |19.69Mb
  server: 173.234.29.2
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _170 |29.70Mb
  server: pupas-shirting-unsung.freesocks.work
  type: ss
  port: 443
  udp: true
  password: p78naCf2EfOlRSLTX0wFVx
  cipher: chacha20-ietf-poly1305
- name: _172 |53.58Mb
  server: 185.82.73.212
  type: ss
  port: 8444
  udp: true
  password: _bypfvq6ra7g4n5yCCR9DoVeGya2XUUS
  cipher: chacha20-ietf-poly1305
- name: _168 |188.63Mb
  server: 45.14.245.2
  type: ss
  port: 443
  password: 17ZDORWIliQHuO6WRGHChXYMzdRtAYVP
  cipher: chacha20-ietf-poly1305
- name: netflix_NL |32.32Mb
  server: 45.87.175.28
  type: ss
  port: 8080
  udp: true
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: _181 |10.11Mb
  server: 45.158.171.70
  type: ss
  port: 8080
  udp: true
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: _185 |818.30Mb
  server: 192.71.249.78
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: disney_netflix_DE |33.84Mb
  server: 194.59.183.134
  type: ss
  port: 46114
  udp: true
  password: lejSRyqa033OEPmEQsvRsl
  cipher: chacha20-ietf-poly1305
- name: disney_PY |16.07Mb
  server: 38.165.233.93
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: _166 |26.73Mb
  server: 103.149.182.86
  type: ss
  port: 8388
  udp: true
  password: asd123456
  cipher: chacha20-ietf
- name: disney_HK |166.67Mb
  server: 103.149.182.158
  type: ss
  port: 8388
  password: asd123456
  cipher: chacha20-ietf
- name: netflix_NO |41.33Mb
  server: 185.213.23.63
  type: ss
  country: ğŸ‡¨ğŸ‡¦CA
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: Relay_-ğŸ‡¯ğŸ‡µJP_212 |20.92Mb
  server: 160.16.87.174
  type: trojan
  port: 3169
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: _214 |10.81Mb
  server: 160.16.131.243
  type: trojan
  port: 2760
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
  skip-cert-verify: true
- name: _187 |11.32Mb
  server: 103.149.183.200
  type: ss
  port: 8388
  udp: true
  password: asd123456
  cipher: chacha20-ietf
- name: _192 |10.79Mb
  server: 149.88.95.94
  type: vmess
  port: 40741
  uuid: 1b8a751b-4909-4fec-f019-907d92e6c47f
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
- name: _190 |113.91Mb
  server: 47.242.145.160
  type: vmess
  port: 44457
  uuid: 40290609-2743-4d85-c9c3-4c72dd151b9f
  alterId: 0
  cipher: auto
  network: http
  http-opts:
    method: GET
    path:
    - /
  h2-opts: {}
- name: Relay_ğŸ‡¬ğŸ‡§GB-ğŸ‡³ğŸ‡±NL_221 |241.35Mb
  server: 82.38.31.208
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_DE |203.77Mb
  server: 89.163.140.136
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ğŸ‡®ğŸ‡¹IT_228 |57.10Mb
  server: 176.126.83.121
  type: ss
  country: ğŸ‡®ğŸ‡¹IT
  port: 443
  password: Q4t8T7hEYY3mD2Fn4wnxyK4X35AUzvR8
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_233 |107.53Mb
  server: 45.87.175.185
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: netflix_NL |104.84Mb
  server: 45.87.175.185
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_235 |12.20Mb
  server: 45.87.175.200
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_236 |112.52Mb
  server: 45.87.175.183
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡­ğŸ‡°HK_222 |103.85Mb
  server: 8.218.105.196
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 52752
  uuid: 925bdbf5-72be-4437-bebf-441c61089f6b
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_HK |23.54Mb
  server: 45.207.157.29
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 13852
  uuid: 845764df-ecb3-4b13-bed2-bf1551b68e9a
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡²ğŸ‡½MX_238 |39.13Mb
  server: 216.238.87.47
  type: vmess
  country: ğŸ‡²ğŸ‡½MX
  port: 27502
  uuid: b8155ce4-7e08-4c40-800f-8671312b7124
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_-ğŸ‡­ğŸ‡°HK_196 |50.64Mb
  server: v10.hdacd.com
  type: vmess
  port: 30807
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: ğŸ‡³ğŸ‡±NL_239 |11.41Mb
  server: 193.29.139.141
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 8080
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡³ğŸ‡±NL_240 |18.75Mb
  server: 193.29.139.188
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 8080
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_245 |41.05Mb
  server: 38.14.99.163
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 59807
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: auto
  network: tcp
  servername: 38.14.99.163
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_DE |108.59Mb
  server: 62.133.60.60
  type: ss
  country: ğŸ‡·ğŸ‡ºRU
  port: 7048
  password: OgAxVsDP6rexuKtrDhCSVA
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_US |21.65Mb
  server: gy3.hdcloud.link
  type: trojan
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  udp: true
  password: 168f29a7-6922-4558-8296-61a69cf6a5a2
  network: grpc
  grpc-opts:
    grpc-service-name: GunService
- name: netflix_PT |44.29Mb
  server: 185.113.143.186
  type: ss
  country: ğŸ‡µğŸ‡¹PT
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸ‡¯ğŸ‡µJP-ğŸ‡¯ğŸ‡µJP_231 |11.24Mb
  server: xray.kk37005.tk
  type: vmess
  country: ğŸ‡¯ğŸ‡µJP
  port: 55919
  uuid: 2e7548bb-7c5b-4d97-d64d-1b2fe4050089
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: ğŸ‡¸ğŸ‡¬SG_244 |19.42Mb
  server: 68.183.227.45
  type: ss
  country: ğŸ‡¸ğŸ‡¬SG
  port: 8080
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: ğŸ‡¨ğŸ‡­CH_218 |11.30Mb
  server: 138.124.67.26
  type: ss
  country: ğŸ‡¨ğŸ‡­CH
  port: 25572
  password: nqcIfYHlpMn3jzqkNDjKaG
  cipher: chacha20-ietf-poly1305
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - disney_netflix_US |19.69Mb
  - _170 |29.70Mb
  - _172 |53.58Mb
  - _168 |188.63Mb
  - netflix_NL |32.32Mb
  - _181 |10.11Mb
  - _185 |818.30Mb
  - disney_netflix_DE |33.84Mb
  - disney_PY |16.07Mb
  - _166 |26.73Mb
  - disney_HK |166.67Mb
  - netflix_NO |41.33Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_212 |20.92Mb
  - _214 |10.81Mb
  - _187 |11.32Mb
  - _192 |10.79Mb
  - _190 |113.91Mb
  - Relay_ğŸ‡¬ğŸ‡§GB-ğŸ‡³ğŸ‡±NL_221 |241.35Mb
  - disney_netflix_DE |203.77Mb
  - ğŸ‡®ğŸ‡¹IT_228 |57.10Mb
  - ğŸ‡±ğŸ‡¹LT_233 |107.53Mb
  - netflix_NL |104.84Mb
  - ğŸ‡±ğŸ‡¹LT_235 |12.20Mb
  - ğŸ‡±ğŸ‡¹LT_236 |112.52Mb
  - ğŸ‡­ğŸ‡°HK_222 |103.85Mb
  - disney_HK |23.54Mb
  - ğŸ‡²ğŸ‡½MX_238 |39.13Mb
  - Relay_-ğŸ‡­ğŸ‡°HK_196 |50.64Mb
  - ğŸ‡³ğŸ‡±NL_239 |11.41Mb
  - ğŸ‡³ğŸ‡±NL_240 |18.75Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_245 |41.05Mb
  - disney_netflix_DE |108.59Mb
  - disney_netflix_US |21.65Mb
  - netflix_PT |44.29Mb
  - Relay_ğŸ‡¯ğŸ‡µJP-ğŸ‡¯ğŸ‡µJP_231 |11.24Mb
  - ğŸ‡¸ğŸ‡¬SG_244 |19.42Mb
  - ğŸ‡¨ğŸ‡­CH_218 |11.30Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - disney_netflix_US |19.69Mb
  - _170 |29.70Mb
  - _172 |53.58Mb
  - _168 |188.63Mb
  - netflix_NL |32.32Mb
  - _181 |10.11Mb
  - _185 |818.30Mb
  - disney_netflix_DE |33.84Mb
  - disney_PY |16.07Mb
  - _166 |26.73Mb
  - disney_HK |166.67Mb
  - netflix_NO |41.33Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_212 |20.92Mb
  - _214 |10.81Mb
  - _187 |11.32Mb
  - _192 |10.79Mb
  - _190 |113.91Mb
  - Relay_ğŸ‡¬ğŸ‡§GB-ğŸ‡³ğŸ‡±NL_221 |241.35Mb
  - disney_netflix_DE |203.77Mb
  - ğŸ‡®ğŸ‡¹IT_228 |57.10Mb
  - ğŸ‡±ğŸ‡¹LT_233 |107.53Mb
  - netflix_NL |104.84Mb
  - ğŸ‡±ğŸ‡¹LT_235 |12.20Mb
  - ğŸ‡±ğŸ‡¹LT_236 |112.52Mb
  - ğŸ‡­ğŸ‡°HK_222 |103.85Mb
  - disney_HK |23.54Mb
  - ğŸ‡²ğŸ‡½MX_238 |39.13Mb
  - Relay_-ğŸ‡­ğŸ‡°HK_196 |50.64Mb
  - ğŸ‡³ğŸ‡±NL_239 |11.41Mb
  - ğŸ‡³ğŸ‡±NL_240 |18.75Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_245 |41.05Mb
  - disney_netflix_DE |108.59Mb
  - disney_netflix_US |21.65Mb
  - netflix_PT |44.29Mb
  - Relay_ğŸ‡¯ğŸ‡µJP-ğŸ‡¯ğŸ‡µJP_231 |11.24Mb
  - ğŸ‡¸ğŸ‡¬SG_244 |19.42Mb
  - ğŸ‡¨ğŸ‡­CH_218 |11.30Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
