port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: _289 |107.98Mb
  server: 185.82.73.212
  type: ss
  port: 8444
  udp: true
  password: _bypfvq6ra7g4n5yCCR9DoVeGya2XUUS
  cipher: chacha20-ietf-poly1305
- name: _280 |300.03Mb
  server: 45.14.245.2
  type: ss
  port: 443
  password: 17ZDORWIliQHuO6WRGHChXYMzdRtAYVP
  cipher: chacha20-ietf-poly1305
- name: _290 |11.32Mb
  server: 103.149.183.200
  type: ss
  port: 8388
  udp: true
  password: asd123456
  cipher: chacha20-ietf
- name: _293 |115.32Mb
  server: 149.88.95.94
  type: vmess
  port: 40741
  uuid: 1b8a751b-4909-4fec-f019-907d92e6c47f
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
- name: Pool__294 |114.29Mb
  server: 149.88.95.217
  type: vmess
  port: 40741
  uuid: 1b8a751b-4909-4fec-f019-907d92e6c47f
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
- name: _288 |166.67Mb
  server: 103.149.182.158
  type: ss
  port: 8388
  password: asd123456
  cipher: chacha20-ietf
- name: _282 |696.62Mb
  server: 46.183.184.60
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: Relay_-ğŸ‡­ğŸ‡°HK_286 |69.54Mb
  server: 103.149.182.105
  type: ss
  port: 8388
  password: asd123456
  cipher: chacha20-ietf
- name: disney_ES |104.52Mb
  server: 145.249.109.121
  type: ss
  port: 25512
  udp: true
  password: smSMfR9jqLgMkHuQtxSIWh
  cipher: chacha20-ietf-poly1305
- name: disney_PY |125.08Mb
  server: 38.165.233.93
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: Relay_-ğŸ‡¯ğŸ‡µJP_303 |11.90Mb
  server: 160.16.72.33
  type: trojan
  port: 3093
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¯ğŸ‡µJP_307 |22.05Mb
  server: 153.121.45.139
  type: trojan
  port: 3093
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¯ğŸ‡µJP_309 |13.49Mb
  server: 160.16.87.174
  type: trojan
  port: 3169
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: _313 |14.91Mb
  server: 160.16.136.130
  type: trojan
  port: 2890
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_331 |230.76Mb
  server: 38.14.99.163
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 59807
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: auto
  network: tcp
  servername: 38.14.99.163
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_332 |22.00Mb
  server: gy3.hdcloud.link
  type: trojan
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  udp: true
  password: 168f29a7-6922-4558-8296-61a69cf6a5a2
  network: grpc
  grpc-opts:
    grpc-service-name: GunService
- name: _297 |113.91Mb
  server: 47.242.145.160
  type: vmess
  port: 44457
  uuid: 40290609-2743-4d85-c9c3-4c72dd151b9f
  alterId: 0
  cipher: auto
  network: http
  http-opts:
    method: GET
    path:
    - /
  h2-opts: {}
- name: Pool__298 |108.85Mb
  server: 149.88.95.217
  type: vmess
  port: 35760
  uuid: 17e96792-d8c3-4741-9c34-e5d1c11d754f
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
- name: _300 |116.28Mb
  server: 149.88.95.94
  type: vmess
  port: 35760
  uuid: 17e96792-d8c3-4741-9c34-e5d1c11d754f
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
- name: ğŸ‡²ğŸ‡½MX_323 |39.35Mb
  server: 216.238.87.47
  type: vmess
  country: ğŸ‡²ğŸ‡½MX
  port: 27502
  uuid: b8155ce4-7e08-4c40-800f-8671312b7124
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_HK |94.82Mb
  server: 45.207.157.29
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 13852
  uuid: 845764df-ecb3-4b13-bed2-bf1551b68e9a
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡­ğŸ‡°HK_318 |120.78Mb
  server: 8.218.105.196
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 52752
  uuid: 925bdbf5-72be-4437-bebf-441c61089f6b
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡­ğŸ‡°HK_320 |169.05Mb
  server: 8.218.116.26
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 32228
  uuid: e4767e9f-ed00-4f31-a984-a918bdd9b09c
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - _289 |107.98Mb
  - _280 |300.03Mb
  - _290 |11.32Mb
  - _293 |115.32Mb
  - Pool__294 |114.29Mb
  - _288 |166.67Mb
  - _282 |696.62Mb
  - Relay_-ğŸ‡­ğŸ‡°HK_286 |69.54Mb
  - disney_ES |104.52Mb
  - disney_PY |125.08Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_303 |11.90Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_307 |22.05Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_309 |13.49Mb
  - _313 |14.91Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_331 |230.76Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_332 |22.00Mb
  - _297 |113.91Mb
  - Pool__298 |108.85Mb
  - _300 |116.28Mb
  - ğŸ‡²ğŸ‡½MX_323 |39.35Mb
  - disney_HK |94.82Mb
  - ğŸ‡­ğŸ‡°HK_318 |120.78Mb
  - ğŸ‡­ğŸ‡°HK_320 |169.05Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - _289 |107.98Mb
  - _280 |300.03Mb
  - _290 |11.32Mb
  - _293 |115.32Mb
  - Pool__294 |114.29Mb
  - _288 |166.67Mb
  - _282 |696.62Mb
  - Relay_-ğŸ‡­ğŸ‡°HK_286 |69.54Mb
  - disney_ES |104.52Mb
  - disney_PY |125.08Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_303 |11.90Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_307 |22.05Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_309 |13.49Mb
  - _313 |14.91Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_331 |230.76Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_332 |22.00Mb
  - _297 |113.91Mb
  - Pool__298 |108.85Mb
  - _300 |116.28Mb
  - ğŸ‡²ğŸ‡½MX_323 |39.35Mb
  - disney_HK |94.82Mb
  - ğŸ‡­ğŸ‡°HK_318 |120.78Mb
  - ğŸ‡­ğŸ‡°HK_320 |169.05Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
