port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: netflix_US |42.81Mb
  server: 88.210.36.107
  type: ss
  port: 2377
  udp: true
  password: t0srmdxrm3xyjnvqz9ewlxb2myq7rjuv
  cipher: chacha20-ietf-poly1305
  plugin: obfs
  plugin-opts:
    host: (TG @WangCai2)e7b7ab7:102816
    mode: tls
- name: netflix_US |43.73Mb
  server: 88.210.36.108
  type: ss
  port: 2377
  udp: true
  password: t0srmdxrm3xyjnvqz9ewlxb2myq7rjuv
  cipher: chacha20-ietf-poly1305
  plugin: obfs
  plugin-opts:
    host: (TG @WangCai2)e7b7ab7:102816
    mode: tls
- name: netflix_US |43.85Mb
  server: 88.210.36.109
  type: ss
  port: 2377
  udp: true
  password: t0srmdxrm3xyjnvqz9ewlxb2myq7rjuv
  cipher: chacha20-ietf-poly1305
  plugin: obfs
  plugin-opts:
    host: (TG @WangCai2)e7b7ab7:102816
    mode: tls
- name: netflix_US |42.79Mb
  server: 88.210.36.106
  type: ss
  port: 2377
  udp: true
  password: t0srmdxrm3xyjnvqz9ewlxb2myq7rjuv
  cipher: chacha20-ietf-poly1305
  plugin: obfs
  plugin-opts:
    host: (TG @WangCai2)e7b7ab7:102816
    mode: tls
- name: netflix_NL |249.31Mb
  server: 185.82.73.212
  type: ss
  port: 8444
  udp: true
  password: _bypfvq6ra7g4n5yCCR9DoVeGya2XUUS
  cipher: chacha20-ietf-poly1305
- name: netflix_NL |397.62Mb
  server: 45.14.245.2
  type: ss
  port: 443
  password: 17ZDORWIliQHuO6WRGHChXYMzdRtAYVP
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_DE |207.59Mb
  server: 45.80.188.48
  type: vmess
  port: 50255
  uuid: bc140c02-25a9-4feb-96bb-7d772b17fd17
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
- name: disney_PY |166.80Mb
  server: 38.165.233.93
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: Pool__123 |86.15Mb
  server: 156.233.232.192
  type: vmess
  port: 44329
  uuid: 1ba1fb56-e235-419e-c193-1c291adad4a7
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
- name: disney_HK |11.82Mb
  server: 149.88.95.217
  type: vmess
  port: 18937
  uuid: ebaa1ae1-fa4d-40d8-958f-d4524d551218
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
- name: Pool__124 |85.92Mb
  server: 156.233.232.192
  type: vmess
  port: 24004
  uuid: 582fcb35-20a0-452c-e179-4c759c62c494
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
- name: _135 |12.50Mb
  server: 160.16.131.243
  type: trojan
  port: 2760
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
  skip-cert-verify: true
- name: netflix_US |14.90Mb
  server: 205.209.109.194
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 17277
  password: d2fkgzsdu5sturjs8f19
  cipher: aes-128-gcm
- name: netflix_US |64.87Mb
  server: 69.164.240.86
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 10880
  password: 3px0wmx0e81145g568ga
  cipher: aes-128-gcm
- name: netflix_JP |17.78Mb
  server: 160.16.87.174
  type: trojan
  port: 3169
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: netflix_US |67.52Mb
  server: 69.164.240.83
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 10878
  password: t6d26id0pjzdo3x5wtlf
  cipher: aes-128-gcm
- name: Relay_-ğŸ‡¸ğŸ‡¬SG_137 |10.77Mb
  server: 160.16.196.59
  type: trojan
  port: 1507
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: netflix_US |87.07Mb
  server: 156.233.232.177
  type: vmess
  port: 44329
  uuid: 1ba1fb56-e235-419e-c193-1c291adad4a7
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
- name: Pool__131 |85.73Mb
  server: 156.233.232.177
  type: vmess
  port: 24004
  uuid: 582fcb35-20a0-452c-e179-4c759c62c494
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
- name: netflix_MX |227.97Mb
  server: 216.238.87.47
  type: vmess
  country: ğŸ‡²ğŸ‡½MX
  port: 27502
  uuid: b8155ce4-7e08-4c40-800f-8671312b7124
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: _145 |10.16Mb
  server: 160.16.116.227
  type: trojan
  port: 2760
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
  skip-cert-verify: true
- name: disney_netflix_CH |185.83Mb
  server: 138.124.67.26
  type: ss
  country: ğŸ‡¨ğŸ‡­CH
  port: 25572
  password: nqcIfYHlpMn3jzqkNDjKaG
  cipher: chacha20-ietf-poly1305
- name: netflix_US |40.95Mb
  server: 38.14.99.163
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 59807
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: auto
  network: tcp
  servername: 38.14.99.163
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_HK |26.59Mb
  server: 112.118.116.178
  type: trojan
  port: 443
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: _146 |53.41Mb
  server: 202.181.103.246
  type: trojan
  port: 4054
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: netflix_US |15.31Mb
  server: cf.fovi.tk
  type: vmess
  country: ğŸZZ
  port: 443
  uuid: bf67437e-6c90-45ca-abc2-c7240a5ce2aa
  alterId: 0
  cipher: auto
  network: ws
  servername: foxlux.fovi.tk
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /eisasqa
    headers:
      HOST: foxlux.fovi.tk
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - netflix_US |42.81Mb
  - netflix_US |43.73Mb
  - netflix_US |43.85Mb
  - netflix_US |42.79Mb
  - netflix_NL |249.31Mb
  - netflix_NL |397.62Mb
  - disney_netflix_DE |207.59Mb
  - disney_PY |166.80Mb
  - Pool__123 |86.15Mb
  - disney_HK |11.82Mb
  - Pool__124 |85.92Mb
  - _135 |12.50Mb
  - netflix_US |14.90Mb
  - netflix_US |64.87Mb
  - netflix_JP |17.78Mb
  - netflix_US |67.52Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_137 |10.77Mb
  - netflix_US |87.07Mb
  - Pool__131 |85.73Mb
  - netflix_MX |227.97Mb
  - _145 |10.16Mb
  - disney_netflix_CH |185.83Mb
  - netflix_US |40.95Mb
  - disney_netflix_HK |26.59Mb
  - _146 |53.41Mb
  - netflix_US |15.31Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - netflix_US |42.81Mb
  - netflix_US |43.73Mb
  - netflix_US |43.85Mb
  - netflix_US |42.79Mb
  - netflix_NL |249.31Mb
  - netflix_NL |397.62Mb
  - disney_netflix_DE |207.59Mb
  - disney_PY |166.80Mb
  - Pool__123 |86.15Mb
  - disney_HK |11.82Mb
  - Pool__124 |85.92Mb
  - _135 |12.50Mb
  - netflix_US |14.90Mb
  - netflix_US |64.87Mb
  - netflix_JP |17.78Mb
  - netflix_US |67.52Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_137 |10.77Mb
  - netflix_US |87.07Mb
  - Pool__131 |85.73Mb
  - netflix_MX |227.97Mb
  - _145 |10.16Mb
  - disney_netflix_CH |185.83Mb
  - netflix_US |40.95Mb
  - disney_netflix_HK |26.59Mb
  - _146 |53.41Mb
  - netflix_US |15.31Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
