port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: disney_netflix_NO |20.16Mb
  server: 107.174.114.71
  type: ss
  port: 443
  password: 595HLF3fHUuw0McM51tpvPygSIB1uf4D
  cipher: chacha20-ietf-poly1305
- name: _124 |36.31Mb
  server: 103.231.73.211
  type: ss
  port: 57456
  udp: true
  password: 8afc633eb63227e9
  cipher: chacha20-ietf-poly1305
- name: netflix_HR |13.44Mb
  server: 46.183.184.60
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: disney_netflix_US |63.04Mb
  server: 160.16.136.130
  type: trojan
  port: 4054
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: netflix_JP |22.19Mb
  server: 160.16.117.182
  type: trojan
  port: 3093
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡·ğŸ‡ºRU_130 |16.63Mb
  server: 146.19.128.183
  type: ss
  port: 17847
  udp: true
  password: '907560230'
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_HK |89.44Mb
  server: 58.152.18.95
  type: trojan
  port: 443
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: disney_netflix_HK |89.03Mb
  server: 58.152.30.120
  type: trojan
  port: 443
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: disney_netflix_FR |193.88Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 40433
  uuid: d8fd8955-78db-49ba-d86f-3e4729f6ac4d
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_FR |165.34Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 27092
  uuid: a0596ba6-72a3-4366-8992-77088da65bd8
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: netflix_MX |40.67Mb
  server: 216.238.89.53
  type: vmess
  country: ğŸ‡²ğŸ‡½MX
  port: 57283
  uuid: 1a5aafc0-6482-451d-fe76-6875b7818579
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: netflix_JP |23.03Mb
  server: 13.231.156.35
  type: trojan
  port: 1331
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: disney_netflix_HK |119.47Mb
  server: 58.152.110.154
  type: trojan
  port: 443
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: disney_netflix_HK |99.67Mb
  server: 58.152.25.242
  type: trojan
  port: 443
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: Relay_-ğŸ‡­ğŸ‡°HK_132 |32.56Mb
  server: v10.hdacd.com
  type: vmess
  port: 30807
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: disney_netflix_NL |99.82Mb
  server: 109.71.246.210
  type: ss
  country: ğŸ‡·ğŸ‡ºRU
  port: 56689
  password: YQCSKoCF3QazW8YlvDBWA4
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡­ğŸ‡°HK_146 |134.01Mb
  server: 8.218.116.26
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 32228
  uuid: e4767e9f-ed00-4f31-a984-a918bdd9b09c
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_JP |16.97Mb
  server: kuame.missionsec.us
  type: trojan
  country: ğŸ‡¯ğŸ‡µJP
  port: 443
  udp: true
  password: FDIypSwe64a3DA7un2R8DFjYXZO3NS05gKZTTOC8SxO0Fy3cqYg3EaFDA3ABaEYKNx39D
  sni: kuame.missionsec.us
  skip-cert-verify: true
- name: disney_netflix_US |40.44Mb
  server: 38.14.99.163
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 59807
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: auto
  network: tcp
  servername: 38.14.99.163
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: netflix_JP |10.46Mb
  server: 45.83.22.118
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 8443
  password: 6af24790-76c9-49d3-bbe0-01285239e57d
  cipher: aes-256-gcm
- name: ğŸ‡µğŸ‡¹ PT_152 |95.36Mb
  server: 185.231.233.112
  type: ss
  country: ğŸ‡µğŸ‡¹ PT
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ğŸ‡¸ğŸ‡¬SG_155 |11.38Mb
  server: 68.183.178.131
  type: vmess
  country: ğŸ‡¸ğŸ‡¬SG
  port: 58607
  uuid: c11c32cb-27b3-4afa-c0f3-fb250aa4959e
  alterId: 0
  cipher: auto
  network: ws
  servername: www.12333.monster
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /
    headers:
      HOST: www.12333.monster
- name: Relay_-ğŸ‡ºğŸ‡¸US_123 |28.11Mb
  server: clr.ducks.tel
  type: ss
  port: 17844
  password: '907560230'
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_US |29.99Mb
  server: cf.fovi.tk
  type: vmess
  country: ğŸZZ
  port: 443
  uuid: bf67437e-6c90-45ca-abc2-c7240a5ce2aa
  alterId: 0
  cipher: auto
  network: ws
  servername: foxlux.fovi.tk
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /eisasqa
    headers:
      HOST: foxlux.fovi.tk
- name: ğŸ‡ºğŸ‡¸US_158 |10.27Mb
  server: 45.83.22.118
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 5223
  password: NS8BriBL9gcPEHTXiN66aT
  cipher: chacha20-ietf-poly1305
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - disney_netflix_NO |20.16Mb
  - _124 |36.31Mb
  - netflix_HR |13.44Mb
  - disney_netflix_US |63.04Mb
  - netflix_JP |22.19Mb
  - Relay_-ğŸ‡·ğŸ‡ºRU_130 |16.63Mb
  - disney_netflix_HK |89.44Mb
  - disney_netflix_HK |89.03Mb
  - disney_netflix_FR |193.88Mb
  - disney_netflix_FR |165.34Mb
  - netflix_MX |40.67Mb
  - netflix_JP |23.03Mb
  - disney_netflix_HK |119.47Mb
  - disney_netflix_HK |99.67Mb
  - Relay_-ğŸ‡­ğŸ‡°HK_132 |32.56Mb
  - disney_netflix_NL |99.82Mb
  - ğŸ‡­ğŸ‡°HK_146 |134.01Mb
  - disney_JP |16.97Mb
  - disney_netflix_US |40.44Mb
  - netflix_JP |10.46Mb
  - ğŸ‡µğŸ‡¹ PT_152 |95.36Mb
  - ğŸ‡¸ğŸ‡¬SG_155 |11.38Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_123 |28.11Mb
  - disney_netflix_US |29.99Mb
  - ğŸ‡ºğŸ‡¸US_158 |10.27Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - disney_netflix_NO |20.16Mb
  - _124 |36.31Mb
  - netflix_HR |13.44Mb
  - disney_netflix_US |63.04Mb
  - netflix_JP |22.19Mb
  - Relay_-ğŸ‡·ğŸ‡ºRU_130 |16.63Mb
  - disney_netflix_HK |89.44Mb
  - disney_netflix_HK |89.03Mb
  - disney_netflix_FR |193.88Mb
  - disney_netflix_FR |165.34Mb
  - netflix_MX |40.67Mb
  - netflix_JP |23.03Mb
  - disney_netflix_HK |119.47Mb
  - disney_netflix_HK |99.67Mb
  - Relay_-ğŸ‡­ğŸ‡°HK_132 |32.56Mb
  - disney_netflix_NL |99.82Mb
  - ğŸ‡­ğŸ‡°HK_146 |134.01Mb
  - disney_JP |16.97Mb
  - disney_netflix_US |40.44Mb
  - netflix_JP |10.46Mb
  - ğŸ‡µğŸ‡¹ PT_152 |95.36Mb
  - ğŸ‡¸ğŸ‡¬SG_155 |11.38Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_123 |28.11Mb
  - disney_netflix_US |29.99Mb
  - ğŸ‡ºğŸ‡¸US_158 |10.27Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
