port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: _231 |67.82Mb
  server: 3.89.113.22
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: _247 |181.09Mb
  server: 15.235.41.200
  type: vmess
  port: 80
  uuid: 58fe1542-5290-40ad-815a-77707a81afe5
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /IOebhLMhl1CTbFHbL95myfRX2
- name: disney_US |45.48Mb
  server: 165.140.216.141
  type: vmess
  port: 443
  uuid: e7d72a8d-26f2-4b54-b366-0c43e0bcba7d
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _253 |41.67Mb
  server: 163.192.49.195
  type: vmess
  port: 443
  uuid: bcb7c581-3c95-4569-a4e7-918141e91ea3
  alterId: 0
  cipher: auto
  network: http
  http-opts:
    path:
    - /
    headers:
      Host:
      - a.189.cn
  h2-opts: {}
- name: _241 |255.77Mb
  server: 85.195.101.122
  type: vmess
  port: 40878
  uuid: f3d4167e-b15e-4e46-82e9-9286ef93fda7
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: netflix_IE |290.71Mb
  server: 3.250.105.240
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: _251 |11.56Mb
  server: 38.180.16.86
  type: vmess
  port: 36236
  uuid: a58bc1a5-8c18-49ff-9453-c331b52f45dc
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: Relay_-ğŸ‡­ğŸ‡°HK_260 |10.79Mb
  server: 104.19.61.72
  type: vmess
  port: 443
  uuid: 4bf075f5-4d5e-4d39-f5ab-b32a86250f0e
  alterId: 0
  cipher: auto
  network: ws
  servername: hk.nbee.pp.ua
  http-opts: {}
  h2-opts: {}
  tls: true
  ws-opts:
    path: /aa
    headers:
      Host: hk.nbee.pp.ua
- name: _264 |27.30Mb
  server: 51.79.102.253
  type: vmess
  port: 80
  uuid: 58fe1542-5290-40ad-815a-77707a81afe5
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /IOebhLMhl1CTbFHbL95myfRX2
    headers:
      Host: wrmelmwxlf.gktevlrqznwqqozy.fabpfs66gizmnojhcvqxwl.kytrcfzqla87gvgvs6c7kjnrubuh.cc
- name: disney_SG |13.81Mb
  server: 165.154.195.38
  type: vmess
  port: 35034
  uuid: 959a8caf-4cea-43d0-a548-3628e7ddfafc
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: Relay_-ğŸ‡§ğŸ‡·BR_245 |73.02Mb
  server: pq-brazil1.09vpn.com
  type: vmess
  port: 80
  uuid: c04c3b34-70fd-4fec-963e-c12d09f36bef
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /vmess/
    headers:
      Host: pq-brazil1.09vpn.com
- name: _240 |41.36Mb
  server: 89.31.120.192
  type: vmess
  port: 443
  uuid: 44537595-9ccc-4b83-8936-5f9ad3229019
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _268 |25.33Mb
  server: 216.238.86.158
  type: vmess
  port: 34460
  udp: true
  uuid: 90be214d-048c-4ea2-a602-b8e4d4e51e36
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _232 |81.58Mb
  server: 154.223.20.79
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: _255 |16.30Mb
  server: 47.243.51.237
  type: vmess
  port: 52801
  uuid: ef93f413-9039-4ddb-aefb-2490287df55a
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /arki
- name: _259 |11.16Mb
  server: 130.162.152.253
  type: vmess
  port: 56867
  uuid: 5206bb9f-2cbc-44ac-de2a-471439a23707
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: disney_US |12.90Mb
  server: 192.204.47.79
  type: vmess
  port: 42277
  udp: true
  uuid: aee61b21-e85a-484b-f203-b245f1451cff
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: disney_HK |21.83Mb
  server: 154.201.76.172
  type: vmess
  port: 20990
  uuid: ba50e1fe-055f-4587-fd0d-36c8d6615192
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _258 |23.51Mb
  server: 183.236.51.36
  type: vmess
  port: 59003
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 64
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _265 |20.26Mb
  server: 8.218.105.196
  type: vmess
  port: 52752
  uuid: 925bdbf5-72be-4437-bebf-441c61089f6b
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: Relay_-ğŸ‡­ğŸ‡°HK_267 |17.66Mb
  server: 154.21.201.83
  type: vmess
  port: 443
  uuid: 4bf075f5-4d5e-4d39-f5ab-b32a86250f0e
  alterId: 0
  cipher: auto
  network: ws
  servername: hk.nbee.pp.ua
  http-opts: {}
  h2-opts: {}
  tls: true
  ws-opts:
    path: /aa
    headers:
      Host: hk.nbee.pp.ua
- name: _275 |41.68Mb
  server: 160.16.223.205
  type: trojan
  port: 4054
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¯ğŸ‡µJP_278 |14.07Mb
  server: 153.121.73.102
  type: trojan
  port: 1331
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: _282 |49.70Mb
  server: 153.121.51.29
  type: trojan
  port: 2890
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: _276 |14.80Mb
  server: 160.16.229.223
  type: trojan
  port: 3093
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: _279 |60.78Mb
  server: 160.16.124.55
  type: trojan
  port: 2890
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: disney_GB |310.01Mb
  server: 172.67.134.185
  type: trojan
  port: 443
  udp: true
  password: POORIARED
  sni: reDfRee8.REDFree8.ir
  ws-opts:
    path: /eyJqdW5rIjoiVUl6eXhLZkkwUTJ3ZzkiLCJwcm90b2NvbCI6InRyIiwibW9kZSI6InByb3h5aXAiLCJwYW5lbElQcyI6W119?ed=2560
    headers:
      Host: reDfRee8.REDFree8.ir
  network: ws
- name: _283 |52.75Mb
  server: 160.16.236.32
  type: trojan
  port: 4054
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: _284 |12.14Mb
  server: 160.16.117.182
  type: trojan
  port: 3093
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¸ğŸ‡¬SG_285 |10.37Mb
  server: 160.16.153.13
  type: trojan
  port: 3145
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: _286 |60.83Mb
  server: 160.16.214.6
  type: trojan
  port: 2890
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: _290 |24.50Mb
  server: 38.96.254.102
  type: trojan
  port: 18509
  password: .ie4rghJuMkcf0oF
  sni: shoppingmall.electricbanana.click
- name: Pool__294 |180.46Mb
  server: 70.34.218.149
  type: trojan
  port: 11930
  password: BaeSzHdfJIR13l67
  sni: softpillow.silentrocket.click
- name: _287 |50.78Mb
  server: 202.181.103.235
  type: trojan
  port: 2890
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¯ğŸ‡µJP_288 |15.62Mb
  server: 153.121.67.215
  type: trojan
  port: 1331
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: _289 |56.21Mb
  server: 160.16.196.59
  type: trojan
  port: 2890
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: _291 |11.30Mb
  server: 153.121.53.187
  type: trojan
  port: 3093
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: ğŸ‡©ğŸ‡ªDE_299 |333.41Mb
  server: 3.126.180.133
  type: trojan
  country: ğŸ‡©ğŸ‡ªDE
  port: 22222
  udp: true
  password: telegram-id-privatevpns
  sni: trojan.burgerip.co.uk
  skip-cert-verify: true
- name: Relay_-ğŸ‡¯ğŸ‡µJP_293 |11.54Mb
  server: 160.16.70.180
  type: trojan
  port: 1331
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: _296 |42.36Mb
  server: 160.16.151.196
  type: trojan
  port: 4054
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: ğŸ‡©ğŸ‡ªDE_300 |224.72Mb
  server: 52.28.28.48
  type: trojan
  country: ğŸ‡©ğŸ‡ªDE
  port: 22222
  udp: true
  password: telegram-id-privatevpns
  sni: trojan.burgerip.co.uk
  skip-cert-verify: true
- name: disney_FR |203.75Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 27092
  uuid: a0596ba6-72a3-4366-8992-77088da65bd8
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_US |66.94Mb
  server: 18.207.122.59
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: _297 |61.12Mb
  server: 160.16.81.84
  type: trojan
  port: 4054
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: disney_FR |206.13Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 40433
  uuid: d8fd8955-78db-49ba-d86f-3e4729f6ac4d
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡¬ğŸ‡§GB_305 |184.90Mb
  server: 82.38.31.191
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: netflix_NL |231.46Mb
  server: 82.38.31.217
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡®ğŸ‡ªIE_317 |338.38Mb
  server: 52.50.200.2
  type: ss
  country: ğŸ‡®ğŸ‡ªIE
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡¬ğŸ‡§GB_307 |196.25Mb
  server: 82.38.31.194
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡²ğŸ‡½MX_320 |42.58Mb
  server: 216.238.87.47
  type: vmess
  country: ğŸ‡²ğŸ‡½MX
  port: 27502
  uuid: b8155ce4-7e08-4c40-800f-8671312b7124
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡ºğŸ‡¸US_326 |102.04Mb
  server: 45.12.136.170
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: l668XHPejoSNNuD66BYzyehaCpZexiF7
  cipher: chacha20-ietf-poly1305
- name: disney_HK |25.57Mb
  server: 45.207.157.29
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 13852
  uuid: 845764df-ecb3-4b13-bed2-bf1551b68e9a
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_ğŸ‡©ğŸ‡ªDE-ğŸ‡¦ğŸ‡¹AT_298 |88.19Mb
  server: desrv.vmagnum.win
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 57456
  password: 345dbf842bce4b66
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸZZ-ğŸ‡ºğŸ‡¸US_328 |30.46Mb
  server: oneonefour.cnm-dns1114514.top
  type: vmess
  country: ğŸZZ
  port: 443
  uuid: 4abbe813-997d-42a0-89bb-40c8a1d54faf
  alterId: 0
  cipher: auto
  network: ws
  servername: xn--l9qya146a7xav76l.xn--4gqza090la383cba657a9rw23a362bz35amu9c.link
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /cnmdfhq
    headers:
      HOST: xn--l9qya146a7xav76l.xn--4gqza090la383cba657a9rw23a362bz35amu9c.link
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - _231 |67.82Mb
  - _247 |181.09Mb
  - disney_US |45.48Mb
  - _253 |41.67Mb
  - _241 |255.77Mb
  - netflix_IE |290.71Mb
  - _251 |11.56Mb
  - Relay_-ğŸ‡­ğŸ‡°HK_260 |10.79Mb
  - _264 |27.30Mb
  - disney_SG |13.81Mb
  - Relay_-ğŸ‡§ğŸ‡·BR_245 |73.02Mb
  - _240 |41.36Mb
  - _268 |25.33Mb
  - _232 |81.58Mb
  - _255 |16.30Mb
  - _259 |11.16Mb
  - disney_US |12.90Mb
  - disney_HK |21.83Mb
  - _258 |23.51Mb
  - _265 |20.26Mb
  - Relay_-ğŸ‡­ğŸ‡°HK_267 |17.66Mb
  - _275 |41.68Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_278 |14.07Mb
  - _282 |49.70Mb
  - _276 |14.80Mb
  - _279 |60.78Mb
  - disney_GB |310.01Mb
  - _283 |52.75Mb
  - _284 |12.14Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_285 |10.37Mb
  - _286 |60.83Mb
  - _290 |24.50Mb
  - Pool__294 |180.46Mb
  - _287 |50.78Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_288 |15.62Mb
  - _289 |56.21Mb
  - _291 |11.30Mb
  - ğŸ‡©ğŸ‡ªDE_299 |333.41Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_293 |11.54Mb
  - _296 |42.36Mb
  - ğŸ‡©ğŸ‡ªDE_300 |224.72Mb
  - disney_FR |203.75Mb
  - disney_netflix_US |66.94Mb
  - _297 |61.12Mb
  - disney_FR |206.13Mb
  - ğŸ‡¬ğŸ‡§GB_305 |184.90Mb
  - netflix_NL |231.46Mb
  - ğŸ‡®ğŸ‡ªIE_317 |338.38Mb
  - ğŸ‡¬ğŸ‡§GB_307 |196.25Mb
  - ğŸ‡²ğŸ‡½MX_320 |42.58Mb
  - ğŸ‡ºğŸ‡¸US_326 |102.04Mb
  - disney_HK |25.57Mb
  - Relay_ğŸ‡©ğŸ‡ªDE-ğŸ‡¦ğŸ‡¹AT_298 |88.19Mb
  - Relay_ğŸZZ-ğŸ‡ºğŸ‡¸US_328 |30.46Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - _231 |67.82Mb
  - _247 |181.09Mb
  - disney_US |45.48Mb
  - _253 |41.67Mb
  - _241 |255.77Mb
  - netflix_IE |290.71Mb
  - _251 |11.56Mb
  - Relay_-ğŸ‡­ğŸ‡°HK_260 |10.79Mb
  - _264 |27.30Mb
  - disney_SG |13.81Mb
  - Relay_-ğŸ‡§ğŸ‡·BR_245 |73.02Mb
  - _240 |41.36Mb
  - _268 |25.33Mb
  - _232 |81.58Mb
  - _255 |16.30Mb
  - _259 |11.16Mb
  - disney_US |12.90Mb
  - disney_HK |21.83Mb
  - _258 |23.51Mb
  - _265 |20.26Mb
  - Relay_-ğŸ‡­ğŸ‡°HK_267 |17.66Mb
  - _275 |41.68Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_278 |14.07Mb
  - _282 |49.70Mb
  - _276 |14.80Mb
  - _279 |60.78Mb
  - disney_GB |310.01Mb
  - _283 |52.75Mb
  - _284 |12.14Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_285 |10.37Mb
  - _286 |60.83Mb
  - _290 |24.50Mb
  - Pool__294 |180.46Mb
  - _287 |50.78Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_288 |15.62Mb
  - _289 |56.21Mb
  - _291 |11.30Mb
  - ğŸ‡©ğŸ‡ªDE_299 |333.41Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_293 |11.54Mb
  - _296 |42.36Mb
  - ğŸ‡©ğŸ‡ªDE_300 |224.72Mb
  - disney_FR |203.75Mb
  - disney_netflix_US |66.94Mb
  - _297 |61.12Mb
  - disney_FR |206.13Mb
  - ğŸ‡¬ğŸ‡§GB_305 |184.90Mb
  - netflix_NL |231.46Mb
  - ğŸ‡®ğŸ‡ªIE_317 |338.38Mb
  - ğŸ‡¬ğŸ‡§GB_307 |196.25Mb
  - ğŸ‡²ğŸ‡½MX_320 |42.58Mb
  - ğŸ‡ºğŸ‡¸US_326 |102.04Mb
  - disney_HK |25.57Mb
  - Relay_ğŸ‡©ğŸ‡ªDE-ğŸ‡¦ğŸ‡¹AT_298 |88.19Mb
  - Relay_ğŸZZ-ğŸ‡ºğŸ‡¸US_328 |30.46Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
