port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: disney_netflix_US |61.49Mb
  server: 50.19.46.248
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: _229 |57.95Mb
  server: 54.159.62.233
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: disney_netflix_US |65.25Mb
  server: 23.22.182.151
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: _232 |65.67Mb
  server: 54.227.38.247
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: _231 |65.42Mb
  server: 3.93.196.82
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: _240 |62.44Mb
  server: 54.91.94.165
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: _246 |53.79Mb
  server: 54.144.64.227
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: _247 |65.68Mb
  server: 184.72.124.41
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: _249 |52.22Mb
  server: 3.89.113.22
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: _257 |58.85Mb
  server: 98.81.59.20
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: disney_netflix_US |63.29Mb
  server: 13.222.155.147
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: _259 |66.79Mb
  server: 13.218.107.141
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: _237 |328.73Mb
  server: 34.251.86.159
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: _238 |176.75Mb
  server: 45.87.175.166
  type: ss
  port: 443
  udp: true
  password: 1RWwXhwfAB5gAEozU4G2Pg
  cipher: chacha20-ietf-poly1305
- name: netflix_IE |262.66Mb
  server: 54.246.35.116
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: disney_US |30.61Mb
  server: 192.204.47.79
  type: vmess
  port: 42277
  udp: true
  uuid: aee61b21-e85a-484b-f203-b245f1451cff
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _264 |36.63Mb
  server: 51.79.102.253
  type: vmess
  port: 80
  uuid: 58fe1542-5290-40ad-815a-77707a81afe5
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /IOebhLMhl1CTbFHbL95myfRX2
    headers:
      Host: wrmelmwxlf.gktevlrqznwqqozy.fabpfs66gizmnojhcvqxwl.kytrcfzqla87gvgvs6c7kjnrubuh.cc
- name: _248 |136.66Mb
  server: 13.61.180.46
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: _256 |104.41Mb
  server: 51.20.125.235
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: _265 |41.40Mb
  server: 163.192.49.195
  type: vmess
  port: 443
  uuid: bcb7c581-3c95-4569-a4e7-918141e91ea3
  alterId: 0
  cipher: auto
  network: http
  http-opts:
    path:
    - /
    headers:
      Host:
      - a.189.cn
  h2-opts: {}
- name: Pool__267 |40.58Mb
  server: 165.140.216.141
  type: vmess
  port: 443
  uuid: e7d72a8d-26f2-4b54-b366-0c43e0bcba7d
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: netflix_DE |277.50Mb
  server: 85.195.101.122
  type: vmess
  port: 40878
  uuid: f3d4167e-b15e-4e46-82e9-9286ef93fda7
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _276 |11.33Mb
  server: 15.235.41.200
  type: vmess
  port: 80
  uuid: 58fe1542-5290-40ad-815a-77707a81afe5
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /IOebhLMhl1CTbFHbL95myfRX2
- name: _260 |10.02Mb
  server: 146.56.112.110
  type: vmess
  port: 8888
  uuid: e7c302f3-90d6-42dd-9d7d-94a3683a3707
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _228 |15.40Mb
  server: 94.198.220.183
  type: ss
  port: 64674
  udp: true
  password: s8LbJCgUiGXeCKVc63tHJP
  cipher: chacha20-ietf-poly1305
- name: _263 |23.54Mb
  server: 160.119.196.92
  type: vmess
  port: 36334
  uuid: 575ac7a3-0127-4420-a9ea-5ff3f6c02ac7
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
- name: _269 |129.00Mb
  server: 8.218.116.26
  type: vmess
  port: 32228
  uuid: e4767e9f-ed00-4f31-a984-a918bdd9b09c
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: disney_SG |18.88Mb
  server: 165.154.195.38
  type: vmess
  port: 35034
  uuid: 959a8caf-4cea-43d0-a548-3628e7ddfafc
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _274 |16.06Mb
  server: 8.218.105.196
  type: vmess
  port: 52752
  uuid: 925bdbf5-72be-4437-bebf-441c61089f6b
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _277 |18.18Mb
  server: 47.243.51.237
  type: vmess
  port: 52801
  uuid: ef93f413-9039-4ddb-aefb-2490287df55a
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /arki
- name: _268 |32.28Mb
  server: 89.31.120.192
  type: vmess
  port: 443
  uuid: 44537595-9ccc-4b83-8936-5f9ad3229019
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _279 |23.32Mb
  server: 47.242.140.52
  type: vmess
  port: 34815
  uuid: 1a46b66c-6ba9-4e9c-aa0b-0ebac2b69e32
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /arki
- name: _293 |31.37Mb
  server: 216.238.86.158
  type: vmess
  port: 34460
  udp: true
  uuid: 90be214d-048c-4ea2-a602-b8e4d4e51e36
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _296 |24.67Mb
  server: 38.96.254.102
  type: trojan
  port: 18509
  password: .ie4rghJuMkcf0oF
  sni: shoppingmall.electricbanana.click
- name: _282 |10.38Mb
  server: 130.162.152.253
  type: vmess
  port: 56867
  uuid: 5206bb9f-2cbc-44ac-de2a-471439a23707
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _283 |10.03Mb
  server: 140.238.2.250
  type: vmess
  port: 443
  uuid: 41a7089a-040b-4538-8b8d-010902405bde
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _284 |16.47Mb
  server: 54.206.192.9
  type: vmess
  port: 16407
  uuid: 08f45028-1db6-4e93-bf51-d344b6c71e19
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _295 |54.27Mb
  server: 160.16.223.205
  type: trojan
  port: 4054
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: _289 |21.49Mb
  server: 8.210.184.105
  type: vmess
  port: 40374
  udp: true
  uuid: 36b76373-7a4f-4669-9113-7d247bcf2704
  alterId: 0
  cipher: auto
  network: http
  http-opts:
    method: GET
    path:
    - /
  h2-opts: {}
- name: Relay_-ğŸ‡¸ğŸ‡¬SG_301 |10.69Mb
  server: 160.16.150.76
  type: trojan
  port: 3145
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: _303 |44.12Mb
  server: 160.16.236.32
  type: trojan
  port: 4054
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: _299 |13.71Mb
  server: 58.152.25.20
  type: trojan
  port: 443
  udp: true
  password: BxceQaOe
  skip-cert-verify: true
- name: disney_HK |12.26Mb
  server: 58.152.25.242
  type: trojan
  port: 443
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: Pool__306 |166.97Mb
  server: 70.34.218.149
  type: trojan
  port: 11930
  password: BaeSzHdfJIR13l67
  sni: softpillow.silentrocket.click
- name: disney_HK |15.42Mb
  server: 58.152.53.174
  type: trojan
  port: 443
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: Relay_-ğŸ‡¯ğŸ‡µJP_304 |18.95Mb
  server: 153.121.67.215
  type: trojan
  port: 1331
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: disney_HK |26.28Mb
  server: 219.78.209.224
  type: trojan
  port: 443
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: Relay_-ğŸ‡¯ğŸ‡µJP_307 |20.13Mb
  server: 160.16.70.180
  type: trojan
  port: 1331
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: _309 |41.32Mb
  server: 160.16.151.196
  type: trojan
  port: 4054
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: disney_GB |232.39Mb
  server: 172.67.134.185
  type: trojan
  port: 443
  udp: true
  password: POORIARED
  sni: reDfRee8.REDFree8.ir
  ws-opts:
    path: /eyJqdW5rIjoiVUl6eXhLZkkwUTJ3ZzkiLCJwcm90b2NvbCI6InRyIiwibW9kZSI6InByb3h5aXAiLCJwYW5lbElQcyI6W119?ed=2560
    headers:
      Host: reDfRee8.REDFree8.ir
  network: ws
- name: _311 |48.17Mb
  server: 153.121.51.29
  type: trojan
  port: 2890
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: _312 |43.74Mb
  server: 160.16.81.84
  type: trojan
  port: 4054
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: _313 |51.36Mb
  server: 160.16.124.55
  type: trojan
  port: 2890
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: _314 |48.88Mb
  server: 160.16.196.59
  type: trojan
  port: 2890
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: _315 |46.51Mb
  server: 160.16.214.6
  type: trojan
  port: 2890
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: _316 |57.53Mb
  server: 202.181.103.235
  type: trojan
  port: 2890
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¸ğŸ‡¬SG_318 |11.62Mb
  server: 160.16.153.13
  type: trojan
  port: 3145
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: disney_HK |11.46Mb
  server: 58.152.30.120
  type: trojan
  port: 443
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: disney_FR |248.22Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 40433
  uuid: d8fd8955-78db-49ba-d86f-3e4729f6ac4d
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_FR |197.63Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 27092
  uuid: a0596ba6-72a3-4366-8992-77088da65bd8
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: netflix_NL |192.80Mb
  server: 82.38.31.217
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: netflix_NL |263.26Mb
  server: 82.38.31.194
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_358 |55.11Mb
  server: 18.207.122.59
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: disney_netflix_US |43.50Mb
  server: 47.253.197.26
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 12056
  uuid: dd7be7f1-38ff-45e6-f1e5-b20c2190f527
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡¬ğŸ‡§GB_337 |251.51Mb
  server: 82.38.31.191
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡®ğŸ‡ªIE_345 |238.37Mb
  server: 52.50.200.2
  type: ss
  country: ğŸ‡®ğŸ‡ªIE
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡²ğŸ‡½MX_350 |40.51Mb
  server: 216.238.87.47
  type: vmess
  country: ğŸ‡²ğŸ‡½MX
  port: 27502
  uuid: b8155ce4-7e08-4c40-800f-8671312b7124
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: _290 |25.18Mb
  server: 154.201.76.172
  type: vmess
  port: 20990
  uuid: ba50e1fe-055f-4587-fd0d-36c8d6615192
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: ğŸ‡ºğŸ‡¸US_359 |18.10Mb
  server: 45.12.136.170
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: l668XHPejoSNNuD66BYzyehaCpZexiF7
  cipher: chacha20-ietf-poly1305
- name: disney_KZ |27.33Mb
  server: 31.3.209.183
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 28212
  password: Kmn7dHPw5wNfkqQMPcGWQA
  cipher: chacha20-ietf-poly1305
- name: disney_HK |22.78Mb
  server: 45.207.157.29
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 13852
  uuid: 845764df-ecb3-4b13-bed2-bf1551b68e9a
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_ğŸ‡©ğŸ‡ªDE-ğŸ‡©ğŸ‡ªDE_325 |224.97Mb
  server: cpanel.navar1.ir
  type: vmess
  country: ğŸ‡©ğŸ‡ªDE
  port: 100
  uuid: 95c6f6f0-84f7-4443-8a50-a59f8e66f5ee
  alterId: 0
  cipher: auto
  network: tcp
  servername: cpanel.navar1.ir
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_US |27.62Mb
  server: cf.fovi.tk
  type: vmess
  country: ğŸZZ
  port: 443
  uuid: bf67437e-6c90-45ca-abc2-c7240a5ce2aa
  alterId: 0
  cipher: auto
  network: ws
  servername: foxpol.fovi.tk
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /eisasqa
    headers:
      HOST: foxpol.fovi.tk
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - disney_netflix_US |61.49Mb
  - _229 |57.95Mb
  - disney_netflix_US |65.25Mb
  - _232 |65.67Mb
  - _231 |65.42Mb
  - _240 |62.44Mb
  - _246 |53.79Mb
  - _247 |65.68Mb
  - _249 |52.22Mb
  - _257 |58.85Mb
  - disney_netflix_US |63.29Mb
  - _259 |66.79Mb
  - _237 |328.73Mb
  - _238 |176.75Mb
  - netflix_IE |262.66Mb
  - disney_US |30.61Mb
  - _264 |36.63Mb
  - _248 |136.66Mb
  - _256 |104.41Mb
  - _265 |41.40Mb
  - Pool__267 |40.58Mb
  - netflix_DE |277.50Mb
  - _276 |11.33Mb
  - _260 |10.02Mb
  - _228 |15.40Mb
  - _263 |23.54Mb
  - _269 |129.00Mb
  - disney_SG |18.88Mb
  - _274 |16.06Mb
  - _277 |18.18Mb
  - _268 |32.28Mb
  - _279 |23.32Mb
  - _293 |31.37Mb
  - _296 |24.67Mb
  - _282 |10.38Mb
  - _283 |10.03Mb
  - _284 |16.47Mb
  - _295 |54.27Mb
  - _289 |21.49Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_301 |10.69Mb
  - _303 |44.12Mb
  - _299 |13.71Mb
  - disney_HK |12.26Mb
  - Pool__306 |166.97Mb
  - disney_HK |15.42Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_304 |18.95Mb
  - disney_HK |26.28Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_307 |20.13Mb
  - _309 |41.32Mb
  - disney_GB |232.39Mb
  - _311 |48.17Mb
  - _312 |43.74Mb
  - _313 |51.36Mb
  - _314 |48.88Mb
  - _315 |46.51Mb
  - _316 |57.53Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_318 |11.62Mb
  - disney_HK |11.46Mb
  - disney_FR |248.22Mb
  - disney_FR |197.63Mb
  - netflix_NL |192.80Mb
  - netflix_NL |263.26Mb
  - ğŸ‡ºğŸ‡¸US_358 |55.11Mb
  - disney_netflix_US |43.50Mb
  - ğŸ‡¬ğŸ‡§GB_337 |251.51Mb
  - ğŸ‡®ğŸ‡ªIE_345 |238.37Mb
  - ğŸ‡²ğŸ‡½MX_350 |40.51Mb
  - _290 |25.18Mb
  - ğŸ‡ºğŸ‡¸US_359 |18.10Mb
  - disney_KZ |27.33Mb
  - disney_HK |22.78Mb
  - Relay_ğŸ‡©ğŸ‡ªDE-ğŸ‡©ğŸ‡ªDE_325 |224.97Mb
  - disney_netflix_US |27.62Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - disney_netflix_US |61.49Mb
  - _229 |57.95Mb
  - disney_netflix_US |65.25Mb
  - _232 |65.67Mb
  - _231 |65.42Mb
  - _240 |62.44Mb
  - _246 |53.79Mb
  - _247 |65.68Mb
  - _249 |52.22Mb
  - _257 |58.85Mb
  - disney_netflix_US |63.29Mb
  - _259 |66.79Mb
  - _237 |328.73Mb
  - _238 |176.75Mb
  - netflix_IE |262.66Mb
  - disney_US |30.61Mb
  - _264 |36.63Mb
  - _248 |136.66Mb
  - _256 |104.41Mb
  - _265 |41.40Mb
  - Pool__267 |40.58Mb
  - netflix_DE |277.50Mb
  - _276 |11.33Mb
  - _260 |10.02Mb
  - _228 |15.40Mb
  - _263 |23.54Mb
  - _269 |129.00Mb
  - disney_SG |18.88Mb
  - _274 |16.06Mb
  - _277 |18.18Mb
  - _268 |32.28Mb
  - _279 |23.32Mb
  - _293 |31.37Mb
  - _296 |24.67Mb
  - _282 |10.38Mb
  - _283 |10.03Mb
  - _284 |16.47Mb
  - _295 |54.27Mb
  - _289 |21.49Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_301 |10.69Mb
  - _303 |44.12Mb
  - _299 |13.71Mb
  - disney_HK |12.26Mb
  - Pool__306 |166.97Mb
  - disney_HK |15.42Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_304 |18.95Mb
  - disney_HK |26.28Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_307 |20.13Mb
  - _309 |41.32Mb
  - disney_GB |232.39Mb
  - _311 |48.17Mb
  - _312 |43.74Mb
  - _313 |51.36Mb
  - _314 |48.88Mb
  - _315 |46.51Mb
  - _316 |57.53Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_318 |11.62Mb
  - disney_HK |11.46Mb
  - disney_FR |248.22Mb
  - disney_FR |197.63Mb
  - netflix_NL |192.80Mb
  - netflix_NL |263.26Mb
  - ğŸ‡ºğŸ‡¸US_358 |55.11Mb
  - disney_netflix_US |43.50Mb
  - ğŸ‡¬ğŸ‡§GB_337 |251.51Mb
  - ğŸ‡®ğŸ‡ªIE_345 |238.37Mb
  - ğŸ‡²ğŸ‡½MX_350 |40.51Mb
  - _290 |25.18Mb
  - ğŸ‡ºğŸ‡¸US_359 |18.10Mb
  - disney_KZ |27.33Mb
  - disney_HK |22.78Mb
  - Relay_ğŸ‡©ğŸ‡ªDE-ğŸ‡©ğŸ‡ªDE_325 |224.97Mb
  - disney_netflix_US |27.62Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
