port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: _251 |14.75Mb
  server: 137.184.174.93
  type: ss
  port: 8080
  udp: true
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: _260 |21.17Mb
  server: 23.95.72.81
  type: ss
  port: 443
  udp: true
  password: UAMVtHm54uahd6SiN5WcD16rsPSdabPG
  cipher: chacha20-ietf-poly1305
- name: _255 |44.43Mb
  server: 104.192.226.106
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: Relay_-ğŸ‡ºğŸ‡¸US_267 |39.29Mb
  server: 38.14.99.179
  type: vmess
  port: 59807
  udp: true
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 64
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: _245 |128.21Mb
  server: 45.87.175.155
  type: ss
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: _253 |76.97Mb
  server: 82.38.31.176
  type: ss
  port: 8080
  udp: true
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: Relay_-ğŸ‡³ğŸ‡±NL_258 |165.45Mb
  server: 82.38.31.218
  type: ss
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: netflix_DE |293.85Mb
  server: 62.133.60.43
  type: ss
  port: 36456
  udp: true
  password: djkVPO3WORCC0rv1zWJQ9G
  cipher: chacha20-ietf-poly1305
- name: Relay_-ğŸ‡ºğŸ‡¸US_270 |38.06Mb
  server: 38.14.99.163
  type: vmess
  port: 59807
  udp: true
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 64
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_-ğŸ‡ºğŸ‡¸US_265 |17.43Mb
  server: us19-25.998998.best
  type: vmess
  port: 443
  udp: true
  uuid: 24254866-770c-41b4-9404-3f50524f425b
  alterId: 0
  cipher: auto
  network: ws
  servername: 24254866-770c-41b4-9404-3f50524f425b.mihomo.baby
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /saoihgreg9384gh8934
    headers:
      Host: 24254866-770c-41b4-9404-3f50524f425b.mihomo.baby
- name: _248 |42.59Mb
  server: 213.159.67.124
  type: ss
  port: 443
  udp: true
  password: mbhqsStnFQT1cTZYCdsmkugGUC6GT6rp
  cipher: chacha20-ietf-poly1305
- name: _276 |40.95Mb
  server: 149.28.76.252
  type: trojan
  port: 443
  udp: true
  password: 7f7fea1d-16cf-3f0b-95c8-2dbb2fc5a97c
  sni: usa.sstank.top
  skip-cert-verify: true
- name: _262 |11.18Mb
  server: 213.159.66.206
  type: ss
  port: 443
  udp: true
  password: pl2XtR0pzwknQOGwewbwXtPYDw1zn9Vu
  cipher: chacha20-ietf-poly1305
- name: Relay_-ğŸ‡­ğŸ‡°HK_268 |10.35Mb
  server: 131.186.63.89
  type: vmess
  port: 11655
  uuid: 4bf075f5-4d5e-4d39-f5ab-b32a86250f0e
  alterId: 0
  cipher: auto
  network: ws
  servername: hk.nbee.pp.ua
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /aa
    headers:
      Host: hk.nbee.pp.ua
- name: Relay_-ğŸ‡ºğŸ‡¸US_302 |39.18Mb
  server: 141.193.213.199
  type: trojan
  port: 443
  udp: true
  password: a8a5b34d-fe46-487d-bd6a-d9f3101525fd
  sni: 26z68w0ecxbuyf89.ukgogo202511.top
  skip-cert-verify: true
  ws-opts:
    path: /images
    headers:
      Host: 26z68w0ecxbuyf89.ukgogo202511.top
  network: ws
- name: Relay_-ğŸ‡¯ğŸ‡µJP_283 |37.19Mb
  server: 160.16.106.144
  type: trojan
  port: 3169
  password: 2cf6d686799e6fa95316394064f26c0a
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¯ğŸ‡µJP_285 |65.36Mb
  server: 153.121.45.139
  type: trojan
  port: 3093
  password: 2cf6d686799e6fa95316394064f26c0a
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¯ğŸ‡µJP_299 |21.96Mb
  server: 153.121.44.99
  type: trojan
  port: 3093
  password: 2cf6d686799e6fa95316394064f26c0a
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡³ğŸ‡±NL_300 |25.27Mb
  server: 153.121.76.9
  type: trojan
  port: 4054
  password: 2cf6d686799e6fa95316394064f26c0a
  sni: www.nintendogames.net
- name: disney_HK |24.85Mb
  server: 58.152.18.55
  type: trojan
  port: 443
  password: 2cf6d686799e6fa95316394064f26c0a
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡³ğŸ‡±NL_305 |11.36Mb
  server: 153.121.76.9
  type: trojan
  port: 2890
  password: 2cf6d686799e6fa95316394064f26c0a
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¸ğŸ‡¬SG_306 |11.93Mb
  server: 160.16.132.158
  type: trojan
  port: 127
  password: 2cf6d686799e6fa95316394064f26c0a
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡ºğŸ‡¸US_319 |42.56Mb
  server: 141.193.213.199
  type: trojan
  port: 443
  udp: true
  password: a544940a-2c1c-4723-96cc-d03053a95530
  sni: 26z68w0ecxbuyf89.ukgogo202511.top
  skip-cert-verify: true
  ws-opts:
    path: /images
    headers:
      Host: 26z68w0ecxbuyf89.ukgogo202511.top
  network: ws
- name: Relay_-ğŸ‡­ğŸ‡°HK_271 |15.75Mb
  server: www.zhoubowen.vip
  type: vmess
  port: 443
  udp: true
  uuid: 0e3b1c9b-a6f3-49d4-9b60-9f0072727e67
  alterId: 0
  cipher: auto
  network: ws
  servername: www.zhoubowen.vip
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /biutefor.icu
    headers:
      Host: www.zhoubowen.vip
- name: Relay_-ğŸ‡­ğŸ‡°HK_272 |13.23Mb
  server: www.zhoubowen.vip
  type: vmess
  port: 443
  udp: true
  uuid: 71b2655e-07d9-4dad-a770-a2b08275142b
  alterId: 0
  cipher: auto
  network: ws
  servername: www.zhoubowen.vip
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /biutefor.icu
    headers:
      Host: www.zhoubowen.vip
- name: Relay_-ğŸ‡³ğŸ‡±NL_308 |13.15Mb
  server: 160.16.240.91
  type: trojan
  port: 4054
  password: 2cf6d686799e6fa95316394064f26c0a
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¸ğŸ‡¬SG_310 |10.56Mb
  server: 160.16.106.144
  type: trojan
  port: 127
  password: 2cf6d686799e6fa95316394064f26c0a
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¯ğŸ‡µJP_314 |11.54Mb
  server: 160.16.117.182
  type: trojan
  port: 3169
  password: 2cf6d686799e6fa95316394064f26c0a
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡ºğŸ‡¸US_321 |29.75Mb
  server: usiys.southbyte.xyz
  type: trojan
  port: 5897
  udp: true
  password: fg20mtCFHy
  sni: usiys.southbyte.xyz
  skip-cert-verify: true
- name: disney_FR |176.23Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 27092
  uuid: a0596ba6-72a3-4366-8992-77088da65bd8
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_ğŸ‡¬ğŸ‡§GB-ğŸ‡³ğŸ‡±NL_330 |173.14Mb
  server: 82.38.31.210
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡§ğŸ‡·BR_323 |21.29Mb
  server: 38.180.16.86
  type: vmess
  country: ğŸ‡§ğŸ‡·BR
  port: 36236
  uuid: a58bc1a5-8c18-49ff-9453-c331b52f45dc
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡§ğŸ‡·BR_324 |14.03Mb
  server: 38.180.16.86
  type: vmess
  country: ğŸ‡§ğŸ‡·BR
  port: 36104
  uuid: E146A8CB-9D2F-449C-ADCA-8736FB
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡²ğŸ‡½MX_342 |40.89Mb
  server: 216.238.89.53
  type: vmess
  country: ğŸ‡²ğŸ‡½MX
  port: 57283
  uuid: 1a5aafc0-6482-451d-fe76-6875b7818579
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡ºğŸ‡¸US_343 |64.25Mb
  server: 107.23.148.46
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡¬ğŸ‡§GB_332 |182.54Mb
  server: 82.38.31.194
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_331 |130.82Mb
  server: 82.38.31.191
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: disney_US |39.29Mb
  server: 216.167.107.61
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 44805
  uuid: f7d62526-9e06-455e-82bd-241d368002e8
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_ğŸ‡¬ğŸ‡§GB-ğŸ‡³ğŸ‡±NL_333 |183.46Mb
  server: 82.38.31.217
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹ LT_340 |155.35Mb
  server: 45.87.175.174
  type: ss
  country: ğŸ‡±ğŸ‡¹ LT
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: disney_HK |10.63Mb
  server: green2.cdntencentmusic.com
  type: trojan
  port: 31102
  udp: true
  password: 4e8bc2b8-96de-45ae-9b5c-304f2b288807
  sni: green2.cdntencentmusic.com
  skip-cert-verify: true
- name: Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡¯ğŸ‡µJP_345 |55.15Mb
  server: t1.620720.xyz
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 8443
  uuid: 516d8a7a-3f0b-41d3-bad0-246116381516
  alterId: 0
  cipher: auto
  network: ws
  servername: t1.620720.xyz
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /
    headers:
      HOST: t1.620720.xyz
- name: ğŸ‡°ğŸ‡·KR_338 |10.11Mb
  server: 146.56.112.110
  type: vmess
  country: ğŸ‡°ğŸ‡·KR
  port: 8888
  uuid: e7c302f3-90d6-42dd-9d7d-94a3683a3707
  alterId: 0
  cipher: auto
  network: tcp
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: _249 |43.05Mb
  server: 45.15.126.19
  type: ss
  port: 443
  udp: true
  password: 6Ts2ZDTQAf3hkFoB8AFufDwsGrlF4e2t
  cipher: chacha20-ietf-poly1305
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - _251 |14.75Mb
  - _260 |21.17Mb
  - _255 |44.43Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_267 |39.29Mb
  - _245 |128.21Mb
  - _253 |76.97Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_258 |165.45Mb
  - netflix_DE |293.85Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_270 |38.06Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_265 |17.43Mb
  - _248 |42.59Mb
  - _276 |40.95Mb
  - _262 |11.18Mb
  - Relay_-ğŸ‡­ğŸ‡°HK_268 |10.35Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_302 |39.18Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_283 |37.19Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_285 |65.36Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_299 |21.96Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_300 |25.27Mb
  - disney_HK |24.85Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_305 |11.36Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_306 |11.93Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_319 |42.56Mb
  - Relay_-ğŸ‡­ğŸ‡°HK_271 |15.75Mb
  - Relay_-ğŸ‡­ğŸ‡°HK_272 |13.23Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_308 |13.15Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_310 |10.56Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_314 |11.54Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_321 |29.75Mb
  - disney_FR |176.23Mb
  - Relay_ğŸ‡¬ğŸ‡§GB-ğŸ‡³ğŸ‡±NL_330 |173.14Mb
  - ğŸ‡§ğŸ‡·BR_323 |21.29Mb
  - ğŸ‡§ğŸ‡·BR_324 |14.03Mb
  - ğŸ‡²ğŸ‡½MX_342 |40.89Mb
  - ğŸ‡ºğŸ‡¸US_343 |64.25Mb
  - ğŸ‡¬ğŸ‡§GB_332 |182.54Mb
  - ğŸ‡¬ğŸ‡§GB_331 |130.82Mb
  - disney_US |39.29Mb
  - Relay_ğŸ‡¬ğŸ‡§GB-ğŸ‡³ğŸ‡±NL_333 |183.46Mb
  - ğŸ‡±ğŸ‡¹ LT_340 |155.35Mb
  - disney_HK |10.63Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡¯ğŸ‡µJP_345 |55.15Mb
  - ğŸ‡°ğŸ‡·KR_338 |10.11Mb
  - _249 |43.05Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - _251 |14.75Mb
  - _260 |21.17Mb
  - _255 |44.43Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_267 |39.29Mb
  - _245 |128.21Mb
  - _253 |76.97Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_258 |165.45Mb
  - netflix_DE |293.85Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_270 |38.06Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_265 |17.43Mb
  - _248 |42.59Mb
  - _276 |40.95Mb
  - _262 |11.18Mb
  - Relay_-ğŸ‡­ğŸ‡°HK_268 |10.35Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_302 |39.18Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_283 |37.19Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_285 |65.36Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_299 |21.96Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_300 |25.27Mb
  - disney_HK |24.85Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_305 |11.36Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_306 |11.93Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_319 |42.56Mb
  - Relay_-ğŸ‡­ğŸ‡°HK_271 |15.75Mb
  - Relay_-ğŸ‡­ğŸ‡°HK_272 |13.23Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_308 |13.15Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_310 |10.56Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_314 |11.54Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_321 |29.75Mb
  - disney_FR |176.23Mb
  - Relay_ğŸ‡¬ğŸ‡§GB-ğŸ‡³ğŸ‡±NL_330 |173.14Mb
  - ğŸ‡§ğŸ‡·BR_323 |21.29Mb
  - ğŸ‡§ğŸ‡·BR_324 |14.03Mb
  - ğŸ‡²ğŸ‡½MX_342 |40.89Mb
  - ğŸ‡ºğŸ‡¸US_343 |64.25Mb
  - ğŸ‡¬ğŸ‡§GB_332 |182.54Mb
  - ğŸ‡¬ğŸ‡§GB_331 |130.82Mb
  - disney_US |39.29Mb
  - Relay_ğŸ‡¬ğŸ‡§GB-ğŸ‡³ğŸ‡±NL_333 |183.46Mb
  - ğŸ‡±ğŸ‡¹ LT_340 |155.35Mb
  - disney_HK |10.63Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡¯ğŸ‡µJP_345 |55.15Mb
  - ğŸ‡°ğŸ‡·KR_338 |10.11Mb
  - _249 |43.05Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
