port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: netflix_NL |260.21Mb
  server: 151.242.251.137
  type: ss
  port: 8080
  password: o5osZg269v5zHpYjr1xY9s
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_US |49.56Mb
  server: us19-25.998998.best
  type: vmess
  port: 443
  udp: true
  uuid: b376015d-77d9-4482-9aa9-051be76aac65
  alterId: 0
  cipher: auto
  network: ws
  servername: b376015d-77d9-4482-9aa9-051be76aac65.mihomo.baby
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /saoihgreg9384gh8934
    headers:
      Host: b376015d-77d9-4482-9aa9-051be76aac65.mihomo.baby
- name: disney_netflix_PT |12.50Mb
  server: 185.231.233.112
  type: ss
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: disney_HK |24.58Mb
  server: m.cnmjin.net
  type: vmess
  port: 16632
  udp: true
  uuid: 77439561-dcef-4e45-803a-743cfa7d20c2
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /
    headers:
      Host: 9e97d6c9e2e0ad3444cbf96d3709366d.mobgslb.tbcache.com
- name: disney_SG |10.10Mb
  server: m.cnmjin.net
  type: vmess
  port: 16618
  udp: true
  uuid: 77439561-dcef-4e45-803a-743cfa7d20c2
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /
    headers:
      Host: 9e97d6c9e2e0ad3444cbf96d3709366d.mobgslb.tbcache.com
- name: Relay_-ğŸ‡¹ğŸ‡¼TW_329 |25.89Mb
  server: m.cnmjin.net
  type: vmess
  port: 16616
  udp: true
  uuid: 77439561-dcef-4e45-803a-743cfa7d20c2
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /
    headers:
      Host: 9e97d6c9e2e0ad3444cbf96d3709366d.mobgslb.tbcache.com
- name: disney_HK |22.50Mb
  server: m.cnmjin.net
  type: vmess
  port: 16622
  udp: true
  uuid: 77439561-dcef-4e45-803a-743cfa7d20c2
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /
    headers:
      Host: 9e97d6c9e2e0ad3444cbf96d3709366d.mobgslb.tbcache.com
- name: disney_HK |23.78Mb
  server: planb.mojcn.com
  type: vmess
  port: 16622
  udp: true
  uuid: 77439561-dcef-4e45-803a-743cfa7d20c2
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /
    headers:
      Host: 9e97d6c9e2e0ad3444cbf96d3709366d.mobgslb.tbcache.com
- name: disney_HK |24.35Mb
  server: planb.mojcn.com
  type: vmess
  port: 16632
  udp: true
  uuid: 77439561-dcef-4e45-803a-743cfa7d20c2
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /
    headers:
      Host: 9e97d6c9e2e0ad3444cbf96d3709366d.mobgslb.tbcache.com
- name: Relay_-ğŸ‡¯ğŸ‡µJP_330 |10.39Mb
  server: planb.mojcn.com
  type: vmess
  port: 16617
  udp: true
  uuid: 77439561-dcef-4e45-803a-743cfa7d20c2
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /
    headers:
      Host: 9e97d6c9e2e0ad3444cbf96d3709366d.mobgslb.tbcache.com
- name: Relay_-ğŸ‡¹ğŸ‡¼TW_345 |22.96Mb
  server: planb.mojcn.com
  type: vmess
  port: 16616
  udp: true
  uuid: 77439561-dcef-4e45-803a-743cfa7d20c2
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /
    headers:
      Host: 9e97d6c9e2e0ad3444cbf96d3709366d.mobgslb.tbcache.com
- name: disney_SG |10.59Mb
  server: planb.mojcn.com
  type: vmess
  port: 16618
  udp: true
  uuid: 77439561-dcef-4e45-803a-743cfa7d20c2
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /
    headers:
      Host: 9e97d6c9e2e0ad3444cbf96d3709366d.mobgslb.tbcache.com
- name: _295 |13.68Mb
  server: 103.36.91.32
  type: ss
  port: 8388
  udp: true
  password: asd123456
  cipher: chacha20-ietf
- name: Relay_-ğŸ‡®ğŸ‡³IN_347 |25.49Mb
  server: planb.mojcn.com
  type: vmess
  port: 16626
  udp: true
  uuid: 77439561-dcef-4e45-803a-743cfa7d20c2
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /
    headers:
      Host: 9e97d6c9e2e0ad3444cbf96d3709366d.mobgslb.tbcache.com
- name: Relay_-ğŸ‡¯ğŸ‡µJP_352 |10.59Mb
  server: m.cnmjin.net
  type: vmess
  port: 16617
  udp: true
  uuid: 77439561-dcef-4e45-803a-743cfa7d20c2
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /
    headers:
      Host: 9e97d6c9e2e0ad3444cbf96d3709366d.mobgslb.tbcache.com
- name: Relay_-ğŸ‡¯ğŸ‡µJP_362 |23.06Mb
  server: 160.16.236.32
  type: trojan
  port: 3093
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¯ğŸ‡µJP_363 |12.29Mb
  server: 160.16.138.24
  type: trojan
  port: 1331
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: disney_netflix_FR |200.68Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 27092
  uuid: a0596ba6-72a3-4366-8992-77088da65bd8
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_-ğŸ‡¯ğŸ‡µJP_364 |12.15Mb
  server: 52.195.176.26
  type: trojan
  port: 2145
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: Relay_-ğŸ‡³ğŸ‡±NL_368 |11.41Mb
  server: 160.16.81.84
  type: trojan
  port: 2760
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡³ğŸ‡±NL_369 |10.74Mb
  server: 160.16.124.55
  type: trojan
  port: 2760
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: disney_HK |17.77Mb
  server: 58.152.18.192
  type: trojan
  port: 443
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: ğŸ‡§ğŸ‡·BR_372 |12.92Mb
  server: 38.180.16.86
  type: vmess
  country: ğŸ‡§ğŸ‡·BR
  port: 36104
  uuid: E146A8CB-9D2F-449C-ADCA-8736FB
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_HK |28.91Mb
  server: 58.152.25.20
  type: trojan
  port: 443
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: disney_netflix_HK |23.52Mb
  server: 58.152.18.95
  type: trojan
  port: 443
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: disney_netflix_US |66.03Mb
  server: 100.25.219.192
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡²ğŸ‡½MX_384 |42.10Mb
  server: 216.238.89.53
  type: vmess
  country: ğŸ‡²ğŸ‡½MX
  port: 57283
  uuid: 1a5aafc0-6482-451d-fe76-6875b7818579
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: netflix_NL |222.15Mb
  server: 82.38.31.190
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_US |17.98Mb
  server: 38.84.201.21
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 53487
  uuid: c3c1ec05-df2c-4975-9b42-e9b007564eb1
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: netflix_AL |28.32Mb
  server: 87.121.162.249
  type: ss
  country: ğŸ‡­ğŸ‡°HK
  port: 443
  password: JGv616hMWdjfuZ00jYfq7XkBHJZrOBrg
  cipher: chacha20-ietf-poly1305
- name: netflix_IL |67.61Mb
  server: 45.93.95.187
  type: ss
  country: ğŸ‡®ğŸ‡±IL
  port: 8618
  password: 4lUEC91c1d8oeClzDbYpXA
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡­ğŸ‡°HK_379 |28.79Mb
  server: 47.242.140.52
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 48219
  uuid: 006893c6-79b1-4c44-94ff-b8bbea065f1f
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
  ws-opts:
    path: /arki?ed=2048
- name: ğŸ‡²ğŸ‡¾MY_385 |30.41Mb
  server: 38.54.98.110
  type: vmess
  country: ğŸ‡²ğŸ‡¾MY
  port: 2052
  uuid: 665d9b8f-153d-4907-adac-de12afd9c851
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: ğŸ‡ºğŸ‡¸US_395 |10.40Mb
  server: 45.136.12.37
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 38141
  uuid: fd291be6-b48d-43a1-da38-66c7f80e2f80
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡¸ğŸ‡¬SG_388 |10.89Mb
  server: 68.183.178.131
  type: vmess
  country: ğŸ‡¸ğŸ‡¬SG
  port: 58607
  uuid: c11c32cb-27b3-4afa-c0f3-fb250aa4959e
  alterId: 0
  cipher: auto
  network: ws
  servername: www.12333.monster
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /
    headers:
      HOST: www.12333.monster
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - netflix_NL |260.21Mb
  - disney_netflix_US |49.56Mb
  - disney_netflix_PT |12.50Mb
  - disney_HK |24.58Mb
  - disney_SG |10.10Mb
  - Relay_-ğŸ‡¹ğŸ‡¼TW_329 |25.89Mb
  - disney_HK |22.50Mb
  - disney_HK |23.78Mb
  - disney_HK |24.35Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_330 |10.39Mb
  - Relay_-ğŸ‡¹ğŸ‡¼TW_345 |22.96Mb
  - disney_SG |10.59Mb
  - _295 |13.68Mb
  - Relay_-ğŸ‡®ğŸ‡³IN_347 |25.49Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_352 |10.59Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_362 |23.06Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_363 |12.29Mb
  - disney_netflix_FR |200.68Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_364 |12.15Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_368 |11.41Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_369 |10.74Mb
  - disney_HK |17.77Mb
  - ğŸ‡§ğŸ‡·BR_372 |12.92Mb
  - disney_HK |28.91Mb
  - disney_netflix_HK |23.52Mb
  - disney_netflix_US |66.03Mb
  - ğŸ‡²ğŸ‡½MX_384 |42.10Mb
  - netflix_NL |222.15Mb
  - disney_netflix_US |17.98Mb
  - netflix_AL |28.32Mb
  - netflix_IL |67.61Mb
  - ğŸ‡­ğŸ‡°HK_379 |28.79Mb
  - ğŸ‡²ğŸ‡¾MY_385 |30.41Mb
  - ğŸ‡ºğŸ‡¸US_395 |10.40Mb
  - ğŸ‡¸ğŸ‡¬SG_388 |10.89Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - netflix_NL |260.21Mb
  - disney_netflix_US |49.56Mb
  - disney_netflix_PT |12.50Mb
  - disney_HK |24.58Mb
  - disney_SG |10.10Mb
  - Relay_-ğŸ‡¹ğŸ‡¼TW_329 |25.89Mb
  - disney_HK |22.50Mb
  - disney_HK |23.78Mb
  - disney_HK |24.35Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_330 |10.39Mb
  - Relay_-ğŸ‡¹ğŸ‡¼TW_345 |22.96Mb
  - disney_SG |10.59Mb
  - _295 |13.68Mb
  - Relay_-ğŸ‡®ğŸ‡³IN_347 |25.49Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_352 |10.59Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_362 |23.06Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_363 |12.29Mb
  - disney_netflix_FR |200.68Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_364 |12.15Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_368 |11.41Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_369 |10.74Mb
  - disney_HK |17.77Mb
  - ğŸ‡§ğŸ‡·BR_372 |12.92Mb
  - disney_HK |28.91Mb
  - disney_netflix_HK |23.52Mb
  - disney_netflix_US |66.03Mb
  - ğŸ‡²ğŸ‡½MX_384 |42.10Mb
  - netflix_NL |222.15Mb
  - disney_netflix_US |17.98Mb
  - netflix_AL |28.32Mb
  - netflix_IL |67.61Mb
  - ğŸ‡­ğŸ‡°HK_379 |28.79Mb
  - ğŸ‡²ğŸ‡¾MY_385 |30.41Mb
  - ğŸ‡ºğŸ‡¸US_395 |10.40Mb
  - ğŸ‡¸ğŸ‡¬SG_388 |10.89Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
