port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: Relay_-ğŸ‡ºğŸ‡¸US_183 |15.19Mb
  server: 82.198.246.97
  type: vmess
  port: 180
  uuid: d13fc2f5-3e05-4795-81eb-44143a09e552
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _191 |37.98Mb
  server: 160.16.136.130
  type: trojan
  port: 2890
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: _192 |10.73Mb
  server: 160.16.131.243
  type: trojan
  port: 2760
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
  skip-cert-verify: true
- name: _193 |10.57Mb
  server: 160.16.116.227
  type: trojan
  port: 2760
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
  skip-cert-verify: true
- name: netflix_NL |265.75Mb
  server: 45.14.245.2
  type: ss
  port: 443
  password: 17ZDORWIliQHuO6WRGHChXYMzdRtAYVP
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_DE |35.99Mb
  server: 194.59.183.134
  type: ss
  port: 46114
  udp: true
  password: lejSRyqa033OEPmEQsvRsl
  cipher: chacha20-ietf-poly1305
- name: disney_HK |10.73Mb
  server: 103.149.183.80
  type: ss
  port: 8388
  udp: true
  password: asd123456
  cipher: chacha20-ietf
- name: _172 |15.99Mb
  server: 46.183.184.60
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: disney_netflix_ES |125.77Mb
  server: 145.249.109.121
  type: ss
  port: 25512
  udp: true
  password: smSMfR9jqLgMkHuQtxSIWh
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_US |38.76Mb
  server: 38.14.99.163
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 59807
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: auto
  network: tcp
  servername: 38.14.99.163
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_PY |15.89Mb
  server: 38.165.233.93
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: netflix_MX |39.15Mb
  server: 216.238.87.47
  type: vmess
  country: ğŸ‡²ğŸ‡½MX
  port: 27502
  uuid: b8155ce4-7e08-4c40-800f-8671312b7124
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: _200 |24.18Mb
  server: 160.16.57.238
  type: trojan
  port: 4054
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: netflix_NL |33.79Mb
  server: 91.221.37.30
  type: ss
  port: 1234
  udp: true
  password: cPzFh2p9MWXvVYWs5hX55e5BZFty7ke-
  cipher: chacha20-ietf-poly1305
- name: disney_HK |23.93Mb
  server: 219.79.214.159
  type: trojan
  port: 443
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: disney_HK |12.06Mb
  server: 112.118.116.178
  type: trojan
  port: 443
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: ğŸ‡­ğŸ‡°HK_202 |18.64Mb
  server: 8.218.116.26
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 32228
  uuid: e4767e9f-ed00-4f31-a984-a918bdd9b09c
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡¨ğŸ‡­CH_201 |34.12Mb
  server: 138.124.67.26
  type: ss
  country: ğŸ‡¨ğŸ‡­CH
  port: 25572
  password: nqcIfYHlpMn3jzqkNDjKaG
  cipher: chacha20-ietf-poly1305
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - Relay_-ğŸ‡ºğŸ‡¸US_183 |15.19Mb
  - _191 |37.98Mb
  - _192 |10.73Mb
  - _193 |10.57Mb
  - netflix_NL |265.75Mb
  - disney_netflix_DE |35.99Mb
  - disney_HK |10.73Mb
  - _172 |15.99Mb
  - disney_netflix_ES |125.77Mb
  - disney_netflix_US |38.76Mb
  - disney_PY |15.89Mb
  - netflix_MX |39.15Mb
  - _200 |24.18Mb
  - netflix_NL |33.79Mb
  - disney_HK |23.93Mb
  - disney_HK |12.06Mb
  - ğŸ‡­ğŸ‡°HK_202 |18.64Mb
  - ğŸ‡¨ğŸ‡­CH_201 |34.12Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - Relay_-ğŸ‡ºğŸ‡¸US_183 |15.19Mb
  - _191 |37.98Mb
  - _192 |10.73Mb
  - _193 |10.57Mb
  - netflix_NL |265.75Mb
  - disney_netflix_DE |35.99Mb
  - disney_HK |10.73Mb
  - _172 |15.99Mb
  - disney_netflix_ES |125.77Mb
  - disney_netflix_US |38.76Mb
  - disney_PY |15.89Mb
  - netflix_MX |39.15Mb
  - _200 |24.18Mb
  - netflix_NL |33.79Mb
  - disney_HK |23.93Mb
  - disney_HK |12.06Mb
  - ğŸ‡­ğŸ‡°HK_202 |18.64Mb
  - ğŸ‡¨ğŸ‡­CH_201 |34.12Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
