port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: _438 |35.53Mb
  server: 172.235.33.114
  type: vmess
  port: 10001
  uuid: 442a3923-eca1-4af0-b3ff-24a7ce0af68f
  alterId: 0
  cipher: auto
  network: tcp
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_-ğŸ‡³ğŸ‡±NL_426 |355.23Mb
  server: 82.38.31.218
  type: ss
  port: 8080
  udp: true
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: netflix_NL |313.76Mb
  server: 151.242.251.144
  type: ss
  port: 8080
  udp: true
  password: QCXDxuDlTTMD7jtgHUjIoj
  cipher: chacha20-ietf-poly1305
- name: _428 |17.80Mb
  server: 82.38.31.179
  type: ss
  port: 8080
  udp: true
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: netflix_NL |338.64Mb
  server: 45.87.175.177
  type: ss
  port: 8080
  udp: true
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: _431 |124.75Mb
  server: 45.15.126.19
  type: ss
  port: 443
  udp: true
  password: 6Ts2ZDTQAf3hkFoB8AFufDwsGrlF4e2t
  cipher: chacha20-ietf-poly1305
- name: disney_PT |65.85Mb
  server: 185.231.233.112
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: _427 |10.76Mb
  server: 45.93.95.187
  type: ss
  port: 8618
  udp: true
  password: 4lUEC91c1d8oeClzDbYpXA
  cipher: chacha20-ietf-poly1305
- name: disney_US |30.37Mb
  server: 158.101.11.204
  type: trojan
  port: 15805
  udp: true
  password: iwangjie
  sni: nodes.830901.xyz
  ws-opts:
    path: /?ed=2560
    headers:
      Host: nodes.830901.xyz
  network: ws
- name: ğŸ‡ªğŸ‡¸ES_459 |142.99Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 27092
  uuid: a0596ba6-72a3-4366-8992-77088da65bd8
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_ğŸ‡®ğŸ‡· IR-ğŸ‡³ğŸ‡±NL_465 |254.66Mb
  server: 151.242.251.144
  type: ss
  country: ğŸ‡®ğŸ‡· IR
  port: 8080
  password: 4a2rfixophdjffa8KVA4Aa
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸ‡®ğŸ‡· IR-ğŸ‡³ğŸ‡±NL_464 |320.02Mb
  server: 151.242.251.153
  type: ss
  country: ğŸ‡®ğŸ‡· IR
  port: 8080
  password: QCXDxuDlTTMD7jtgHUjIoj
  cipher: chacha20-ietf-poly1305
- name: _423 |12.05Mb
  server: 103.149.183.200
  type: ss
  port: 8388
  udp: true
  password: asd123456
  cipher: chacha20-ietf
- name: disney_PY |159.34Mb
  server: 38.165.233.93
  type: ss
  country: ğŸ‡ºğŸ‡¸ US
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: Relay_-ğŸ‡¯ğŸ‡µJP_441 |10.65Mb
  server: w13.luoli.de
  type: vmess
  port: 443
  udp: true
  uuid: 42a99644-b90b-3627-8809-a2d6c4078b59
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  tls: true
  ws-opts:
    path: /v2ws
    headers:
      Host: w13.luoli.de
- name: Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_473 |34.26Mb
  server: sw19.sesamebuta.top
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  uuid: 805ba514-bf2f-4d5d-df49-8417804e8de3
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /abcd
- name: disney_US |22.93Mb
  server: cf.fovi.tk
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  uuid: bf67437e-6c90-45ca-abc2-c7240a5ce2aa
  alterId: 0
  cipher: auto
  network: ws
  servername: foxpol.fovi.tk
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /eisasqa
    headers:
      HOST: foxpol.fovi.tk
- name: Relay_-ğŸ‡ºğŸ‡¸US_439 |48.56Mb
  server: us19-25.998998.best
  type: vmess
  port: 443
  udp: true
  uuid: 24254866-770c-41b4-9404-3f50524f425b
  alterId: 0
  cipher: auto
  network: ws
  servername: 24254866-770c-41b4-9404-3f50524f425b.mihomo.baby
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /saoihgreg9384gh8934
    headers:
      Host: 24254866-770c-41b4-9404-3f50524f425b.mihomo.baby
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - _438 |35.53Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_426 |355.23Mb
  - netflix_NL |313.76Mb
  - _428 |17.80Mb
  - netflix_NL |338.64Mb
  - _431 |124.75Mb
  - disney_PT |65.85Mb
  - _427 |10.76Mb
  - disney_US |30.37Mb
  - ğŸ‡ªğŸ‡¸ES_459 |142.99Mb
  - Relay_ğŸ‡®ğŸ‡· IR-ğŸ‡³ğŸ‡±NL_465 |254.66Mb
  - Relay_ğŸ‡®ğŸ‡· IR-ğŸ‡³ğŸ‡±NL_464 |320.02Mb
  - _423 |12.05Mb
  - disney_PY |159.34Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_441 |10.65Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_473 |34.26Mb
  - disney_US |22.93Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_439 |48.56Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - _438 |35.53Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_426 |355.23Mb
  - netflix_NL |313.76Mb
  - _428 |17.80Mb
  - netflix_NL |338.64Mb
  - _431 |124.75Mb
  - disney_PT |65.85Mb
  - _427 |10.76Mb
  - disney_US |30.37Mb
  - ğŸ‡ªğŸ‡¸ES_459 |142.99Mb
  - Relay_ğŸ‡®ğŸ‡· IR-ğŸ‡³ğŸ‡±NL_465 |254.66Mb
  - Relay_ğŸ‡®ğŸ‡· IR-ğŸ‡³ğŸ‡±NL_464 |320.02Mb
  - _423 |12.05Mb
  - disney_PY |159.34Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_441 |10.65Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_473 |34.26Mb
  - disney_US |22.93Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_439 |48.56Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
