port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: _208 |341.75Mb
  server: 3.129.133.36
  type: ss
  port: 30000
  udp: true
  password: b9a7fe64-e236-4b8d-b6c9-65da8a7070cc
  cipher: aes-256-gcm
- name: _180 |10.30Mb
  server: 138.186.142.80
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _192 |10.28Mb
  server: 38.165.231.25
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _230 |10.40Mb
  server: 3.129.133.36
  type: ss
  port: 30000
  udp: true
  password: ece40cae-fb05-41d6-ab5e-870090f25d93
  cipher: aes-256-gcm
- name: _197 |10.14Mb
  server: 109.61.46.43
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _203 |46.31Mb
  server: 212.102.54.45
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _201 |10.05Mb
  server: 185.237.185.89
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _198 |11.82Mb
  server: 176.123.5.253
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¨ğŸ‡¦CA_249 |10.46Mb
  server: 79.127.200.162
  type: ss
  country: ğŸ‡¨ğŸ‡¦CA
  port: 990
  password: f8f7aCzcPKbsF8p3
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸ‡¨ğŸ‡¦CA-ğŸ‡¨ğŸ‡¦CA_258 |10.47Mb
  server: 79.127.200.169
  type: ss
  country: ğŸ‡¨ğŸ‡¦CA
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _228 |10.33Mb
  server: 138.186.142.81
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _199 |10.04Mb
  server: 45.82.252.109
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡§ğŸ‡ªBE_244 |174.47Mb
  server: 192.71.249.108
  type: ss
  country: ğŸ‡§ğŸ‡ªBE
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ğŸ‡¦ğŸ‡¹AT_238 |45.04Mb
  server: 37.235.56.69
  type: ss
  country: ğŸ‡¦ğŸ‡¹AT
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¦ğŸ‡¹AT_236 |10.02Mb
  server: 185.180.12.81
  type: ss
  country: ğŸ‡¦ğŸ‡¹AT
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ğŸ‡¨ğŸ‡·CR_265 |48.61Mb
  server: 145.14.131.37
  type: ss
  country: ğŸ‡¨ğŸ‡·CR
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _225 |38.88Mb
  server: 103.97.203.227
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡©ğŸ‡ªDE_280 |13.77Mb
  server: 91.107.141.164
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 2096
  password: AqgBwYDeQA
  cipher: aes-256-gcm
- name: ğŸ‡©ğŸ‡ªDE_281 |10.19Mb
  server: 18.199.153.21
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡©ğŸ‡ªDE_283 |10.18Mb
  server: 18.196.31.30
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡©ğŸ‡ªDE_293 |10.07Mb
  server: 18.196.156.200
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡«ğŸ‡·FR_346 |10.27Mb
  server: 51.15.17.169
  type: ss
  country: ğŸ‡«ğŸ‡·FR
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ğŸ‡©ğŸ‡ªDE_294 |10.09Mb
  server: 81.19.141.45
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 443
  password: 3mCD9NchPkbYIojfTHyNf0
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_365 |38.52Mb
  server: 89.185.84.185
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: nbnjas1SIeDmfOwNVK2gml
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡«ğŸ‡·FR_347 |14.18Mb
  server: 83.147.216.70
  type: ss
  country: ğŸ‡«ğŸ‡·FR
  port: 64519
  password: PSmqa9uK9Oo1eivPyXiAH8
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_366 |85.74Mb
  server: 89.185.84.185
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: ozSHXLRuO7JckCvhgLjLaU
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_369 |59.33Mb
  server: 89.185.84.185
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: z2z7JLFZExrhzT1SpnXh27
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡«ğŸ‡·FR_348 |20.44Mb
  server: 83.147.216.70
  type: ss
  country: ğŸ‡«ğŸ‡·FR
  port: 64519
  password: LCL2yAP1iPOvAEe8dWe2h1
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡«ğŸ‡·FR_351 |13.34Mb
  server: 83.147.216.70
  type: ss
  country: ğŸ‡«ğŸ‡·FR
  port: 64519
  password: UlT89D0rvcr05tKft1NB5a
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_379 |71.10Mb
  server: 89.185.84.185
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: i0Gf1YEtKzZmsVFpnrTxIt
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_380 |47.28Mb
  server: 89.185.84.185
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: 6D3AybGUDufEK4xulpE7zj
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_383 |77.55Mb
  server: 89.185.84.185
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: ktr94qVVsy34Lj2B5ltJV6
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_386 |81.76Mb
  server: 89.185.84.185
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: CVTeBy5Ne9D7XOl1wxQebj
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_391 |59.77Mb
  server: 89.185.84.185
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: APL3I9lSc4Gs9DzaHuBV0u
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_392 |81.61Mb
  server: 89.185.84.185
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: Lm0gSCFwvlkyYeU4nSGbUM
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸ‡«ğŸ‡·FR-ğŸ‡«ğŸ‡·FR_362 |112.15Mb
  server: jamekk.org
  type: vmess
  country: ğŸ‡«ğŸ‡·FR
  port: 443
  uuid: 03fcc618-b93d-6796-6aed-8a38c975d581
  alterId: 1
  cipher: auto
  network: ws
  servername: jamekk.org
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: linkvws
    headers:
      HOST: jamekk.org
- name: ğŸ‡¬ğŸ‡§GB_408 |10.40Mb
  server: 3.9.171.152
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡¬ğŸ‡§GB_404 |80.91Mb
  server: 89.185.84.185
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: XsMiWpupGob8IouVwYW5WC
  cipher: chacha20-ietf-poly1305
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - _208 |341.75Mb
  - _180 |10.30Mb
  - _192 |10.28Mb
  - _230 |10.40Mb
  - _197 |10.14Mb
  - _203 |46.31Mb
  - _201 |10.05Mb
  - _198 |11.82Mb
  - ğŸ‡¨ğŸ‡¦CA_249 |10.46Mb
  - Relay_ğŸ‡¨ğŸ‡¦CA-ğŸ‡¨ğŸ‡¦CA_258 |10.47Mb
  - _228 |10.33Mb
  - _199 |10.04Mb
  - ğŸ‡§ğŸ‡ªBE_244 |174.47Mb
  - ğŸ‡¦ğŸ‡¹AT_238 |45.04Mb
  - ğŸ‡¦ğŸ‡¹AT_236 |10.02Mb
  - ğŸ‡¨ğŸ‡·CR_265 |48.61Mb
  - _225 |38.88Mb
  - ğŸ‡©ğŸ‡ªDE_280 |13.77Mb
  - ğŸ‡©ğŸ‡ªDE_281 |10.19Mb
  - ğŸ‡©ğŸ‡ªDE_283 |10.18Mb
  - ğŸ‡©ğŸ‡ªDE_293 |10.07Mb
  - ğŸ‡«ğŸ‡·FR_346 |10.27Mb
  - ğŸ‡©ğŸ‡ªDE_294 |10.09Mb
  - ğŸ‡¬ğŸ‡§GB_365 |38.52Mb
  - ğŸ‡«ğŸ‡·FR_347 |14.18Mb
  - ğŸ‡¬ğŸ‡§GB_366 |85.74Mb
  - ğŸ‡¬ğŸ‡§GB_369 |59.33Mb
  - ğŸ‡«ğŸ‡·FR_348 |20.44Mb
  - ğŸ‡«ğŸ‡·FR_351 |13.34Mb
  - ğŸ‡¬ğŸ‡§GB_379 |71.10Mb
  - ğŸ‡¬ğŸ‡§GB_380 |47.28Mb
  - ğŸ‡¬ğŸ‡§GB_383 |77.55Mb
  - ğŸ‡¬ğŸ‡§GB_386 |81.76Mb
  - ğŸ‡¬ğŸ‡§GB_391 |59.77Mb
  - ğŸ‡¬ğŸ‡§GB_392 |81.61Mb
  - Relay_ğŸ‡«ğŸ‡·FR-ğŸ‡«ğŸ‡·FR_362 |112.15Mb
  - ğŸ‡¬ğŸ‡§GB_408 |10.40Mb
  - ğŸ‡¬ğŸ‡§GB_404 |80.91Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - _208 |341.75Mb
  - _180 |10.30Mb
  - _192 |10.28Mb
  - _230 |10.40Mb
  - _197 |10.14Mb
  - _203 |46.31Mb
  - _201 |10.05Mb
  - _198 |11.82Mb
  - ğŸ‡¨ğŸ‡¦CA_249 |10.46Mb
  - Relay_ğŸ‡¨ğŸ‡¦CA-ğŸ‡¨ğŸ‡¦CA_258 |10.47Mb
  - _228 |10.33Mb
  - _199 |10.04Mb
  - ğŸ‡§ğŸ‡ªBE_244 |174.47Mb
  - ğŸ‡¦ğŸ‡¹AT_238 |45.04Mb
  - ğŸ‡¦ğŸ‡¹AT_236 |10.02Mb
  - ğŸ‡¨ğŸ‡·CR_265 |48.61Mb
  - _225 |38.88Mb
  - ğŸ‡©ğŸ‡ªDE_280 |13.77Mb
  - ğŸ‡©ğŸ‡ªDE_281 |10.19Mb
  - ğŸ‡©ğŸ‡ªDE_283 |10.18Mb
  - ğŸ‡©ğŸ‡ªDE_293 |10.07Mb
  - ğŸ‡«ğŸ‡·FR_346 |10.27Mb
  - ğŸ‡©ğŸ‡ªDE_294 |10.09Mb
  - ğŸ‡¬ğŸ‡§GB_365 |38.52Mb
  - ğŸ‡«ğŸ‡·FR_347 |14.18Mb
  - ğŸ‡¬ğŸ‡§GB_366 |85.74Mb
  - ğŸ‡¬ğŸ‡§GB_369 |59.33Mb
  - ğŸ‡«ğŸ‡·FR_348 |20.44Mb
  - ğŸ‡«ğŸ‡·FR_351 |13.34Mb
  - ğŸ‡¬ğŸ‡§GB_379 |71.10Mb
  - ğŸ‡¬ğŸ‡§GB_380 |47.28Mb
  - ğŸ‡¬ğŸ‡§GB_383 |77.55Mb
  - ğŸ‡¬ğŸ‡§GB_386 |81.76Mb
  - ğŸ‡¬ğŸ‡§GB_391 |59.77Mb
  - ğŸ‡¬ğŸ‡§GB_392 |81.61Mb
  - Relay_ğŸ‡«ğŸ‡·FR-ğŸ‡«ğŸ‡·FR_362 |112.15Mb
  - ğŸ‡¬ğŸ‡§GB_408 |10.40Mb
  - ğŸ‡¬ğŸ‡§GB_404 |80.91Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
