port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: netflix_CA
  server: 137.184.174.93
  type: ss
  port: 8080
  udp: true
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: _557
  server: 46.183.184.60
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: disney_netflix_DE
  server: 54.93.101.215
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: disney_GB
  server: 144.217.164.29
  type: ss
  port: 12000
  password: 8JCsPssfgS8tiRwiMlhARg==
  cipher: aes-256-gcm
- name: netflix_HR
  server: 185.156.110.92
  type: ss
  port: 443
  udp: true
  password: gXOXk2FJwsz9P6nXIICuDNOqF9gWX1dn
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_DE
  server: 3.72.36.217
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: disney_netflix_FR
  server: 195.154.119.77
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: disney_netflix_NL
  server: 151.242.251.142
  type: ss
  port: 8080
  udp: true
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_DE
  server: 63.177.227.124
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: disney_netflix_DE
  server: 3.65.219.59
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: disney_netflix_DE
  server: 63.178.2.18
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: _568
  server: 5.78.51.123
  type: ss
  port: 1080
  password: 8tmnvX5zYuWGVIDP2jglZw
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_GB
  server: 172.66.44.230
  type: trojan
  port: 8443
  udp: true
  password: 8r<[9'l6hAO#8ZQi
  sni: Koma-YT.PAGeS.Dev
  ws-opts:
    path: /tro8sFW1S91B6sZrM1
    headers:
      Host: Koma-YT.PAGeS.Dev
  network: ws
- name: _567
  server: 213.159.66.206
  type: ss
  port: 443
  udp: true
  password: pl2XtR0pzwknQOGwewbwXtPYDw1zn9Vu
  cipher: chacha20-ietf-poly1305
- name: disney_MD
  server: 185.153.197.5
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: disney_EE
  server: 37.252.5.75
  type: trojan
  port: 443
  udp: true
  password: 3208e968-b862-4e2e-ad90-2b49e7ce7afb
  sni: joss.gpj1.web.id
  ws-opts:
    path: /Free-VPN-CF-Geo-Project/37.252.5.75=443
    headers:
      Host: joss.gpj1.web.id
  network: ws
- name: disney_netflix_GB
  server: 109.169.76.23
  type: trojan
  port: 443
  udp: true
  password: d69e725c-7c7e-4c75-9786-4859b4e0bbc6
  sni: joss.gpj1.web.id
  ws-opts:
    path: /Free-VPN-CF-Geo-Project/109.169.76.23=443
    headers:
      Host: joss.gpj1.web.id
  network: ws
- name: Relay_-ðŸ‡­ðŸ‡°HK_574
  server: 131.186.63.89
  type: vmess
  port: 11655
  udp: true
  uuid: 4bf075f5-4d5e-4d39-f5ab-b32a86250f0e
  alterId: 0
  cipher: auto
  network: ws
  servername: hk.nbee.pp.ua
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /aa
    headers:
      Host: hk.nbee.pp.ua
- name: disney_netflix_GB
  server: koma-yt.pages.dev
  type: trojan
  port: 8443
  udp: true
  password: 8r<[9'l6hAO#8ZQi
  sni: Koma-YT.PAGeS.Dev
  ws-opts:
    path: /tro8sFW1S91B6sZrM1
    headers:
      User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML,
        like Gecko) Chrome/67.0.3396.99 Safari/537.36
  network: ws
- name: disney_netflix_FR
  server: 51.15.210.1
  type: trojan
  port: 443
  udp: true
  password: e6f0e8b0-3dc5-4d53-a23a-86c02d5ba098
  sni: joss.gpj1.web.id
  ws-opts:
    path: /Free-VPN-CF-Geo-Project/51.15.210.1=443
    headers:
      Host: joss.gpj1.web.id
  network: ws
- name: disney_netflix_PL
  server: 217.30.10.31
  type: trojan
  port: 8443
  udp: true
  password: 422d402c-58f1-4473-abeb-fe6e69dc97ed
  sni: joss.gpj1.web.id
  ws-opts:
    path: /Free-VPN-CF-Geo-Project/217.30.10.31=8443
    headers:
      Host: joss.gpj1.web.id
  network: ws
- name: Relay_-ðŸ‡­ðŸ‡°HK_573
  server: 8c41940a-t66sg0-t7kvg3-1mij.hkt.gotochinatown.net
  type: vmess
  port: 80
  udp: true
  uuid: c2c634e8-ab9e-11ef-97e0-f23c9164ca5d
  alterId: 2
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /
    headers:
      Host: broadcastlv.chat.bilibili.com
- name: disney_KR
  server: 13.124.194.133
  type: ss
  port: 80
  udp: true
  password: dada0801
  cipher: aes-256-gcm
- name: disney_netflix_NL
  server: 138.124.30.8
  type: trojan
  port: 443
  udp: true
  password: 0311306e-56d4-4aa1-bde5-8cede7fcd3e4
  sni: joss.gpj1.web.id
  ws-opts:
    path: /Free-VPN-CF-Geo-Project/138.124.30.8=443
    headers:
      Host: joss.gpj1.web.id
  network: ws
- name: Relay_-ðŸ‡­ðŸ‡°HK_572
  server: bac52f5a-t66sg0-t7luxf-tng5.hkt.gotochinatown.net
  type: vmess
  port: 80
  udp: true
  uuid: 2ec58858-976b-11ea-82ef-f23c9164ca5d
  alterId: 2
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /
    headers:
      Host: broadcastlv.chat.bilibili.com
- name: Relay_-ðŸ‡­ðŸ‡°HK_571
  server: 69bb0fb7-t66sg0-t7kvg3-1mij.hk3.p5pv.com
  type: vmess
  port: 80
  udp: true
  uuid: c2c634e8-ab9e-11ef-97e0-f23c9164ca5d
  alterId: 2
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /
    headers:
      Host: broadcastlv.chat.bilibili.com
- name: disney_netflix_CZ
  server: 81.91.214.162
  type: trojan
  port: 443
  udp: true
  password: f583143c-2cbe-47f5-804d-27efa55442a1
  sni: joss.gpj1.web.id
  ws-opts:
    path: /Free-VPN-CF-Geo-Project/81.91.214.162=443
    headers:
      Host: joss.gpj1.web.id
  network: ws
- name: disney_netflix_US
  server: usiys.southbyte.xyz
  type: trojan
  port: 5897
  udp: true
  password: fg20mtCFHy
  sni: usiys.southbyte.xyz
  skip-cert-verify: true
- name: disney_netflix_ES
  server: 45.159.251.8
  type: trojan
  port: 81
  udp: true
  password: 6ead60c4-4321-45d5-81a9-ba4835f7c692
  sni: joss.gpj1.web.id
  ws-opts:
    path: /Free-VPN-CF-Geo-Project/45.159.251.8=81
    headers:
      Host: joss.gpj1.web.id
  network: ws
- name: disney_DK
  server: 38.180.72.162
  type: trojan
  port: 2053
  udp: true
  password: eb7339c5-70e4-4c7b-b5ef-4128adc8136a
  sni: joss.gpj1.web.id
  ws-opts:
    path: /Free-VPN-CF-Geo-Project/38.180.72.162=2053
    headers:
      Host: joss.gpj1.web.id
  network: ws
- name: disney_HK
  server: 58.152.18.124
  type: trojan
  port: 443
  password: dd2f25b4c70689de8bc0f7fa9d6591cb
  sni: www.nintendogames.net
- name: Relay_-ðŸ‡¯ðŸ‡µJP_588
  server: 160.16.204.136
  type: trojan
  port: 1331
  password: dd2f25b4c70689de8bc0f7fa9d6591cb
  sni: www.nintendogames.net
- name: Relay_-ðŸ‡¯ðŸ‡µJP_589
  server: 54.199.75.230
  type: trojan
  port: 1331
  password: dd2f25b4c70689de8bc0f7fa9d6591cb
  sni: www.nintendogames.net
- name: disney_netflix_US
  server: 160.16.204.136
  type: trojan
  port: 2890
  password: dd2f25b4c70689de8bc0f7fa9d6591cb
  sni: www.nintendogames.net
- name: disney_netflix_US
  server: 160.16.89.176
  type: trojan
  port: 702
  password: dd2f25b4c70689de8bc0f7fa9d6591cb
  sni: www.nintendogames.net
- name: Relay_-ðŸ‡³ðŸ‡±NL_592
  server: 160.16.89.176
  type: trojan
  port: 2760
  password: dd2f25b4c70689de8bc0f7fa9d6591cb
  sni: www.nintendogames.net
- name: Relay_-ðŸ‡³ðŸ‡±NL_593
  server: 160.16.214.6
  type: trojan
  port: 2760
  password: dd2f25b4c70689de8bc0f7fa9d6591cb
  sni: www.nintendogames.net
- name: disney_netflix_DE
  server: 18.184.12.56
  type: ss
  country: ðŸ‡©ðŸ‡ªDE
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: disney_netflix_FR
  server: 208.76.223.218
  type: vmess
  country: ðŸ‡ªðŸ‡¸ES
  port: 27092
  uuid: a0596ba6-72a3-4366-8992-77088da65bd8
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: netflix_MX
  server: 216.238.89.53
  type: vmess
  country: ðŸ‡²ðŸ‡½MX
  port: 57283
  uuid: 1a5aafc0-6482-451d-fe76-6875b7818579
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ðŸ‡¦ðŸ‡ºAU_594
  server: 54.252.214.254
  type: vmess
  country: ðŸ‡¦ðŸ‡ºAU
  port: 1000
  uuid: 61a9c747-cbe6-46aa-a0bb-8d5a615db8b1
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ðŸ‡­ðŸ‡°HK_598
  server: 103.149.182.38
  type: ss
  country: ðŸ‡­ðŸ‡°HK
  port: 8388
  password: asd123456
  cipher: chacha20-ietf
- name: ðŸ‡­ðŸ‡°HK_600
  server: 47.238.71.166
  type: vmess
  country: ðŸ‡­ðŸ‡°HK
  port: 13502
  uuid: 7ecfb350-e87b-4c3b-b90a-de4884ad2838
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ðŸ‡­ðŸ‡°HK_601
  server: 8.218.17.136
  type: vmess
  country: ðŸ‡­ðŸ‡°HK
  port: 52986
  uuid: 7363d47e-ac8b-4fe0-d23e-99077999a70d
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ðŸ‡¸ðŸ‡¬SG_603
  server: cgroup.node3.s.nodelist-airport.com
  type: ss
  country: ðŸ‡¸ðŸ‡¬SG
  port: 16198
  password: 8f3a835c-8a45-480d-ae35-1deb2c52dcae
  cipher: aes-256-gcm
- name: disney_netflix_US
  server: 193.124.24.247
  type: vmess
  country: ðŸ‡ºðŸ‡¸US
  port: 6512
  uuid: 729bfa51-095c-4f50-a1e0-2dfc90d51ebd
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ðŸ‡ºðŸ‡¸US_606
  server: cgroup.node5.s.nodelist-airport.com
  type: ss
  country: ðŸ‡ºðŸ‡¸US
  port: 5003
  password: 8f3a835c-8a45-480d-ae35-1deb2c52dcae
  cipher: aes-256-gcm
- name: ðŸ‡ºðŸ‡¸US_608
  server: pupas-shirting-unsung.freesocks.work
  type: ss
  country: ðŸ‡ºðŸ‡¸US
  port: 443
  password: p78naCf2EfOlRSLTX0wFVx
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_PL
  server: 45.15.126.19
  type: ss
  country: ðŸ‡ºðŸ‡¸US
  port: 443
  password: 6Ts2ZDTQAf3hkFoB8AFufDwsGrlF4e2t
  cipher: chacha20-ietf-poly1305
- name: ðŸ‡¸ðŸ‡¬SG_604
  server: cgroup.node3.s2.nodelist-airport.com
  type: ss
  country: ðŸ‡¸ðŸ‡¬SG
  port: 34502
  password: 8f3a835c-8a45-480d-ae35-1deb2c52dcae
  cipher: aes-256-gcm
- name: disney_netflix_US
  server: 193.124.24.247
  type: vmess
  country: ðŸ‡ºðŸ‡¸US
  port: 6502
  uuid: 242f22a3-29d9-4a94-d8ba-88043f2e1921
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_US
  server: 193.124.24.247
  type: vmess
  country: ðŸ‡ºðŸ‡¸US
  port: 6510
  uuid: 8f44f672-e53b-44fb-b502-c886d37107b5
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_US
  server: 193.124.24.247
  type: vmess
  country: ðŸ‡ºðŸ‡¸US
  port: 6504
  uuid: 7ceb165c-9aff-4ab7-ce9e-1df31a5ed911
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_US
  server: 193.124.24.247
  type: vmess
  country: ðŸ‡ºðŸ‡¸US
  port: 6508
  uuid: b68fead5-5b0b-43a1-c34a-804467f0f368
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_HK
  server: 2.59.62.63
  type: vmess
  country: ðŸ‡ºðŸ‡¸US
  port: 19365
  uuid: 9583a647-b0ba-47b0-d4b0-4e12a0201d67
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_US
  server: 193.124.24.247
  type: vmess
  country: ðŸ‡ºðŸ‡¸US
  port: 6513
  uuid: 5cf7fcbc-e2c1-42c4-d0d7-79c45a7d588d
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_US
  server: 193.124.24.247
  type: vmess
  country: ðŸ‡ºðŸ‡¸US
  port: 6505
  uuid: b34732f9-2856-4974-8bae-1351928e347f
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_TH
  server: th0603-1.ysds168.shop
  type: vmess
  country: ðŸ‡¹ðŸ‡­TH
  port: 1036
  uuid: 5893c6cd-c14f-4e99-a9ae-6c2ca7456584
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: Relay_ðŸ‡­ðŸ‡°HK-ðŸ‡­ðŸ‡°HK_599
  server: n1744453319.lie5d.cyou
  type: vmess
  country: ðŸ‡­ðŸ‡°HK
  port: 443
  uuid: 6928af97-a23e-408c-956e-5cd2207f3557
  alterId: 0
  cipher: auto
  network: ws
  servername: n1744453319.lie5d.cyou
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /
    headers:
      HOST: n1744453319.lie5d.cyou
- name: disney_FR
  server: 1a2d514b-37cf-499f-8d08-d017a92ab5bb.asoul-ava.top
  type: vmess
  country: ðŸ‡ºðŸ‡¸US
  port: 443
  uuid: 5f726fe3-d82e-4da5-a711-8af0cbb2b682
  alterId: 0
  cipher: auto
  network: ws
  servername: 1a2d514b-37cf-499f-8d08-d017a92ab5bb.asoul-ava.top
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /azumase.ren
    headers:
      HOST: 1a2d514b-37cf-499f-8d08-d017a92ab5bb.asoul-ava.top
- name: Relay_-ðŸ‡©ðŸ‡ªDE_577
  server: 158.178.206.197
  type: trojan
  port: 8443
  udp: true
  password: c2de1269-17cb-41f6-ab97-f8c11a6f0f4f
  sni: joss.gpj1.web.id
  ws-opts:
    path: /Free-VPN-CF-Geo-Project/158.178.206.197=8443
    headers:
      Host: joss.gpj1.web.id
  network: ws
proxy-groups:
- name: ðŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - netflix_CA
  - _557
  - disney_netflix_DE
  - disney_GB
  - netflix_HR
  - disney_netflix_DE
  - disney_netflix_FR
  - disney_netflix_NL
  - disney_netflix_DE
  - disney_netflix_DE
  - disney_netflix_DE
  - _568
  - disney_netflix_GB
  - _567
  - disney_MD
  - disney_EE
  - disney_netflix_GB
  - Relay_-ðŸ‡­ðŸ‡°HK_574
  - disney_netflix_GB
  - disney_netflix_FR
  - disney_netflix_PL
  - Relay_-ðŸ‡­ðŸ‡°HK_573
  - disney_KR
  - disney_netflix_NL
  - Relay_-ðŸ‡­ðŸ‡°HK_572
  - Relay_-ðŸ‡­ðŸ‡°HK_571
  - disney_netflix_CZ
  - disney_netflix_US
  - disney_netflix_ES
  - disney_DK
  - disney_HK
  - Relay_-ðŸ‡¯ðŸ‡µJP_588
  - Relay_-ðŸ‡¯ðŸ‡µJP_589
  - disney_netflix_US
  - disney_netflix_US
  - Relay_-ðŸ‡³ðŸ‡±NL_592
  - Relay_-ðŸ‡³ðŸ‡±NL_593
  - disney_netflix_DE
  - disney_netflix_FR
  - netflix_MX
  - ðŸ‡¦ðŸ‡ºAU_594
  - ðŸ‡­ðŸ‡°HK_598
  - ðŸ‡­ðŸ‡°HK_600
  - ðŸ‡­ðŸ‡°HK_601
  - ðŸ‡¸ðŸ‡¬SG_603
  - disney_netflix_US
  - ðŸ‡ºðŸ‡¸US_606
  - ðŸ‡ºðŸ‡¸US_608
  - disney_netflix_PL
  - ðŸ‡¸ðŸ‡¬SG_604
  - disney_netflix_US
  - disney_netflix_US
  - disney_netflix_US
  - disney_netflix_US
  - disney_netflix_HK
  - disney_netflix_US
  - disney_netflix_US
  - disney_TH
  - Relay_ðŸ‡­ðŸ‡°HK-ðŸ‡­ðŸ‡°HK_599
  - disney_FR
  - Relay_-ðŸ‡©ðŸ‡ªDE_577
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - netflix_CA
  - _557
  - disney_netflix_DE
  - disney_GB
  - netflix_HR
  - disney_netflix_DE
  - disney_netflix_FR
  - disney_netflix_NL
  - disney_netflix_DE
  - disney_netflix_DE
  - disney_netflix_DE
  - _568
  - disney_netflix_GB
  - _567
  - disney_MD
  - disney_EE
  - disney_netflix_GB
  - Relay_-ðŸ‡­ðŸ‡°HK_574
  - disney_netflix_GB
  - disney_netflix_FR
  - disney_netflix_PL
  - Relay_-ðŸ‡­ðŸ‡°HK_573
  - disney_KR
  - disney_netflix_NL
  - Relay_-ðŸ‡­ðŸ‡°HK_572
  - Relay_-ðŸ‡­ðŸ‡°HK_571
  - disney_netflix_CZ
  - disney_netflix_US
  - disney_netflix_ES
  - disney_DK
  - disney_HK
  - Relay_-ðŸ‡¯ðŸ‡µJP_588
  - Relay_-ðŸ‡¯ðŸ‡µJP_589
  - disney_netflix_US
  - disney_netflix_US
  - Relay_-ðŸ‡³ðŸ‡±NL_592
  - Relay_-ðŸ‡³ðŸ‡±NL_593
  - disney_netflix_DE
  - disney_netflix_FR
  - netflix_MX
  - ðŸ‡¦ðŸ‡ºAU_594
  - ðŸ‡­ðŸ‡°HK_598
  - ðŸ‡­ðŸ‡°HK_600
  - ðŸ‡­ðŸ‡°HK_601
  - ðŸ‡¸ðŸ‡¬SG_603
  - disney_netflix_US
  - ðŸ‡ºðŸ‡¸US_606
  - ðŸ‡ºðŸ‡¸US_608
  - disney_netflix_PL
  - ðŸ‡¸ðŸ‡¬SG_604
  - disney_netflix_US
  - disney_netflix_US
  - disney_netflix_US
  - disney_netflix_US
  - disney_netflix_HK
  - disney_netflix_US
  - disney_netflix_US
  - disney_TH
  - Relay_ðŸ‡­ðŸ‡°HK-ðŸ‡­ðŸ‡°HK_599
  - disney_FR
  - Relay_-ðŸ‡©ðŸ‡ªDE_577
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ðŸš€ èŠ‚ç‚¹é€‰æ‹©
