port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: _197 |53.15Mb
  server: 167.160.90.178
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _176 |10.25Mb
  server: 62.100.205.100
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _206 |10.24Mb
  server: 206.206.125.53
  type: ss
  port: 20199
  udp: true
  password: W4ULRoPY8DvUhnbfKnjSWD
  cipher: chacha20-ietf-poly1305
- name: _187 |10.51Mb
  server: 138.186.142.81
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _214 |10.26Mb
  server: 38.165.231.25
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¦ğŸ‡·AR_225 |44.93Mb
  server: 38.54.45.129
  type: ss
  country: ğŸ‡¦ğŸ‡·AR
  port: 990
  password: f8f7aCzcPKbsF8p3
  cipher: chacha20-ietf-poly1305
- name: _212 |43.94Mb
  server: 154.205.153.107
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡§ğŸ‡ªBE_238 |48.25Mb
  server: 192.71.249.108
  type: ss
  country: ğŸ‡§ğŸ‡ªBE
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡§ğŸ‡ªBE_237 |200.57Mb
  server: 192.71.249.108
  type: ss
  country: ğŸ‡§ğŸ‡ªBE
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: Relay_ğŸ‡¨ğŸ‡¦CA-ğŸ‡¨ğŸ‡¦CA_247 |10.48Mb
  server: 79.127.200.169
  type: ss
  country: ğŸ‡¨ğŸ‡¦CA
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡§ğŸ‡ªBE_240 |213.47Mb
  server: 192.71.249.71
  type: ss
  country: ğŸ‡§ğŸ‡ªBE
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ğŸ‡¨ğŸ‡¦CA_249 |10.59Mb
  server: 137.184.174.93
  type: ss
  country: ğŸ‡¨ğŸ‡¦CA
  port: 8080
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: ğŸ‡¨ğŸ‡¦CA_248 |10.55Mb
  server: 147.182.150.107
  type: ss
  country: ğŸ‡¨ğŸ‡¦CA
  port: 8080
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: ğŸ‡¨ğŸ‡¦CA_251 |10.90Mb
  server: 147.182.146.81
  type: ss
  country: ğŸ‡¨ğŸ‡¦CA
  port: 8080
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: ğŸ‡¦ğŸ‡ºAU_230 |10.30Mb
  server: 45.77.234.206
  type: ss
  country: ğŸ‡¦ğŸ‡ºAU
  port: 8080
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: ğŸ‡¨ğŸ‡¦CA_252 |13.87Mb
  server: 178.128.231.214
  type: ss
  country: ğŸ‡¨ğŸ‡¦CA
  port: 8080
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: ğŸ‡¨ğŸ‡¦CA_254 |10.56Mb
  server: 138.197.141.58
  type: ss
  country: ğŸ‡¨ğŸ‡¦CA
  port: 8080
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: ğŸ‡¨ğŸ‡¦CA_253 |29.17Mb
  server: 68.183.193.204
  type: ss
  country: ğŸ‡¨ğŸ‡¦CA
  port: 8080
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: _182 |10.11Mb
  server: 45.82.252.109
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _217 |10.01Mb
  server: 58.152.110.40
  type: trojan
  port: 443
  password: ea39fa94f1ee00999337ea1fd3318e69
  sni: www.nintendogames.net
  network: tcp
- name: ğŸ‡¨ğŸ‡¦CA_258 |10.48Mb
  server: 51.79.102.253
  type: vmess
  country: ğŸ‡¨ğŸ‡¦CA
  port: 80
  uuid: 58fe1542-5290-40ad-815a-77707a81afe5
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
  ws-opts:
    path: /IOebhLMhl1CTbFHbL95myfRX2
- name: ğŸ‡¨ğŸ‡¦CA_255 |10.31Mb
  server: 79.127.200.162
  type: ss
  country: ğŸ‡¨ğŸ‡¦CA
  port: 990
  password: f8f7aCzcPKbsF8p3
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¨ğŸ‡¦CA_259 |10.11Mb
  server: 23.162.200.227
  type: vmess
  country: ğŸ‡¨ğŸ‡¦CA
  port: 443
  uuid: 03fcc618-b93d-6796-6aed-8a38c975d581
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /linkvws
- name: ğŸ‡§ğŸ‡ªBE_241 |188.98Mb
  server: 192.71.249.78
  type: ss
  country: ğŸ‡§ğŸ‡ªBE
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ğŸ‡¨ğŸ‡¦CA_260 |10.09Mb
  server: 148.113.176.192
  type: vmess
  country: ğŸ‡¨ğŸ‡¦CA
  port: 443
  uuid: 03fcc618-b93d-6796-6aed-8a38c975d581
  alterId: 0
  cipher: auto
  network: ws
  servername: fapeng.org
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: linkvws
    headers:
      HOST: fapeng.org
- name: ğŸ‡¦ğŸ‡ºAU_233 |167.14Mb
  server: 38.55.105.55
  type: vmess
  country: ğŸ‡¦ğŸ‡ºAU
  port: 5551
  uuid: 3977956a-5093-4f39-97eb-4826dc5105e5
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
  ws-opts:
    path: /arki?ed=2048
- name: ğŸ‡¦ğŸ‡ºAU_235 |160.54Mb
  server: 38.55.105.55
  type: vmess
  country: ğŸ‡¦ğŸ‡ºAU
  port: 30791
  uuid: cbc58881-d3c5-4052-8e9e-451b2d0d7d5f
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
  ws-opts:
    path: /arki?ed=2048
- name: ğŸ‡©ğŸ‡ªDE_274 |10.22Mb
  server: 18.196.156.200
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: Relay_ğŸ‡¨ğŸ‡¦CA-ğŸ‡¨ğŸ‡¦CA_256 |102.00Mb
  server: ssca.irundns.net
  type: ssr
  country: ğŸ‡¨ğŸ‡¦CA
  port: 443
  password: $$Turb0VPN$$
  cipher: aes-128-cfb
  protocol: auth_aes128_md5
  obfs: http_post
- name: ğŸ‡©ğŸ‡ªDE_287 |10.13Mb
  server: 3.75.208.8
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡©ğŸ‡ªDE_289 |10.09Mb
  server: 18.196.31.30
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡©ğŸ‡ªDE_292 |10.16Mb
  server: 3.79.189.65
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡©ğŸ‡ªDE_295 |10.08Mb
  server: 18.159.37.90
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡©ğŸ‡ªDE_300 |16.09Mb
  server: 81.19.141.45
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 443
  password: rC23nT4eVDHF06wmuyvSUe
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸ‡¨ğŸ‡­CH-ğŸ‡¨ğŸ‡­CH_261 |10.05Mb
  server: h110vpnch.outlinekeys.net
  type: ss
  country: ğŸ‡¨ğŸ‡­CH
  port: 4248
  password: nweTvVPR1DapgM5c8CpE1q
  cipher: chacha20-ietf-poly1305
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - _197 |53.15Mb
  - _176 |10.25Mb
  - _206 |10.24Mb
  - _187 |10.51Mb
  - _214 |10.26Mb
  - ğŸ‡¦ğŸ‡·AR_225 |44.93Mb
  - _212 |43.94Mb
  - ğŸ‡§ğŸ‡ªBE_238 |48.25Mb
  - ğŸ‡§ğŸ‡ªBE_237 |200.57Mb
  - Relay_ğŸ‡¨ğŸ‡¦CA-ğŸ‡¨ğŸ‡¦CA_247 |10.48Mb
  - ğŸ‡§ğŸ‡ªBE_240 |213.47Mb
  - ğŸ‡¨ğŸ‡¦CA_249 |10.59Mb
  - ğŸ‡¨ğŸ‡¦CA_248 |10.55Mb
  - ğŸ‡¨ğŸ‡¦CA_251 |10.90Mb
  - ğŸ‡¦ğŸ‡ºAU_230 |10.30Mb
  - ğŸ‡¨ğŸ‡¦CA_252 |13.87Mb
  - ğŸ‡¨ğŸ‡¦CA_254 |10.56Mb
  - ğŸ‡¨ğŸ‡¦CA_253 |29.17Mb
  - _182 |10.11Mb
  - _217 |10.01Mb
  - ğŸ‡¨ğŸ‡¦CA_258 |10.48Mb
  - ğŸ‡¨ğŸ‡¦CA_255 |10.31Mb
  - ğŸ‡¨ğŸ‡¦CA_259 |10.11Mb
  - ğŸ‡§ğŸ‡ªBE_241 |188.98Mb
  - ğŸ‡¨ğŸ‡¦CA_260 |10.09Mb
  - ğŸ‡¦ğŸ‡ºAU_233 |167.14Mb
  - ğŸ‡¦ğŸ‡ºAU_235 |160.54Mb
  - ğŸ‡©ğŸ‡ªDE_274 |10.22Mb
  - Relay_ğŸ‡¨ğŸ‡¦CA-ğŸ‡¨ğŸ‡¦CA_256 |102.00Mb
  - ğŸ‡©ğŸ‡ªDE_287 |10.13Mb
  - ğŸ‡©ğŸ‡ªDE_289 |10.09Mb
  - ğŸ‡©ğŸ‡ªDE_292 |10.16Mb
  - ğŸ‡©ğŸ‡ªDE_295 |10.08Mb
  - ğŸ‡©ğŸ‡ªDE_300 |16.09Mb
  - Relay_ğŸ‡¨ğŸ‡­CH-ğŸ‡¨ğŸ‡­CH_261 |10.05Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - _197 |53.15Mb
  - _176 |10.25Mb
  - _206 |10.24Mb
  - _187 |10.51Mb
  - _214 |10.26Mb
  - ğŸ‡¦ğŸ‡·AR_225 |44.93Mb
  - _212 |43.94Mb
  - ğŸ‡§ğŸ‡ªBE_238 |48.25Mb
  - ğŸ‡§ğŸ‡ªBE_237 |200.57Mb
  - Relay_ğŸ‡¨ğŸ‡¦CA-ğŸ‡¨ğŸ‡¦CA_247 |10.48Mb
  - ğŸ‡§ğŸ‡ªBE_240 |213.47Mb
  - ğŸ‡¨ğŸ‡¦CA_249 |10.59Mb
  - ğŸ‡¨ğŸ‡¦CA_248 |10.55Mb
  - ğŸ‡¨ğŸ‡¦CA_251 |10.90Mb
  - ğŸ‡¦ğŸ‡ºAU_230 |10.30Mb
  - ğŸ‡¨ğŸ‡¦CA_252 |13.87Mb
  - ğŸ‡¨ğŸ‡¦CA_254 |10.56Mb
  - ğŸ‡¨ğŸ‡¦CA_253 |29.17Mb
  - _182 |10.11Mb
  - _217 |10.01Mb
  - ğŸ‡¨ğŸ‡¦CA_258 |10.48Mb
  - ğŸ‡¨ğŸ‡¦CA_255 |10.31Mb
  - ğŸ‡¨ğŸ‡¦CA_259 |10.11Mb
  - ğŸ‡§ğŸ‡ªBE_241 |188.98Mb
  - ğŸ‡¨ğŸ‡¦CA_260 |10.09Mb
  - ğŸ‡¦ğŸ‡ºAU_233 |167.14Mb
  - ğŸ‡¦ğŸ‡ºAU_235 |160.54Mb
  - ğŸ‡©ğŸ‡ªDE_274 |10.22Mb
  - Relay_ğŸ‡¨ğŸ‡¦CA-ğŸ‡¨ğŸ‡¦CA_256 |102.00Mb
  - ğŸ‡©ğŸ‡ªDE_287 |10.13Mb
  - ğŸ‡©ğŸ‡ªDE_289 |10.09Mb
  - ğŸ‡©ğŸ‡ªDE_292 |10.16Mb
  - ğŸ‡©ğŸ‡ªDE_295 |10.08Mb
  - ğŸ‡©ğŸ‡ªDE_300 |16.09Mb
  - Relay_ğŸ‡¨ğŸ‡­CH-ğŸ‡¨ğŸ‡­CH_261 |10.05Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
