port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: _271 |10.07Mb
  server: 196.196.192.58
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _257 |10.19Mb
  server: 185.26.236.196
  type: ss
  port: 8443
  udp: true
  password: hvce9IJx3AVhMgstYwBD4i
  cipher: chacha20-ietf-poly1305
- name: _264 |10.53Mb
  server: 45.87.175.158
  type: ss
  port: 8080
  udp: true
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: Relay_-ğŸ‡³ğŸ‡±NL_255 |10.15Mb
  server: 151.242.251.152
  type: ss
  port: 8080
  udp: true
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: Relay_-ğŸ‡³ğŸ‡±NL_269 |10.13Mb
  server: 151.242.251.137
  type: ss
  port: 8080
  udp: true
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: _270 |10.09Mb
  server: 109.61.125.161
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _266 |10.06Mb
  server: 109.61.46.43
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _261 |47.17Mb
  server: 37.143.129.98
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _287 |10.23Mb
  server: 15.235.85.147
  type: vmess
  port: 443
  udp: true
  uuid: 03fcc618-b93d-6796-6aed-8a38c975d581
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: linkvws
    headers:
      Host: pelang.org
- name: Relay_ğŸ‡¨ğŸ‡¦CA-ğŸ‡²ğŸ‡©MD_309 |10.47Mb
  server: 45.154.204.7
  type: ss
  country: ğŸ‡¨ğŸ‡¦CA
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _275 |10.17Mb
  server: 47.86.85.95
  type: vmess
  port: 14044
  udp: true
  uuid: 74475bf0-0267-4a04-b431-54752e31994b
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /arki?ed=2048
- name: _284 |10.16Mb
  server: 47.243.39.20
  type: vmess
  port: 36512
  udp: true
  uuid: cc13ac4b-d38f-4ebb-8a2a-73cf3aff5650
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /arki?ed=2048
- name: ğŸ‡¨ğŸ‡¦CA_311 |10.72Mb
  server: 68.183.193.204
  type: ss
  country: ğŸ‡¨ğŸ‡¦CA
  port: 8080
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: ğŸ‡¨ğŸ‡¦CA_312 |10.26Mb
  server: 79.127.200.162
  type: ss
  country: ğŸ‡¨ğŸ‡¦CA
  port: 990
  password: f8f7aCzcPKbsF8p3
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¨ğŸ‡¦CA_314 |10.79Mb
  server: 138.197.153.10
  type: ss
  country: ğŸ‡¨ğŸ‡¦CA
  port: 8080
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: ğŸ‡¨ğŸ‡¦CA_313 |10.18Mb
  server: 79.127.200.169
  type: ss
  country: ğŸ‡¨ğŸ‡¦CA
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¨ğŸ‡¦CA_315 |10.51Mb
  server: 147.182.146.81
  type: ss
  country: ğŸ‡¨ğŸ‡¦CA
  port: 8080
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: ğŸ‡¦ğŸ‡¹AT_297 |10.09Mb
  server: 192.121.170.52
  type: vmess
  country: ğŸ‡¦ğŸ‡¹AT
  port: 20522
  uuid: 08f870ed-520c-483a-bdec-c4884aad4665
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
  ws-opts:
    path: /telegram_@sswia
- name: ğŸ‡¨ğŸ‡¦CA_317 |10.71Mb
  server: 138.197.165.21
  type: ss
  country: ğŸ‡¨ğŸ‡¦CA
  port: 8080
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: ğŸ‡¨ğŸ‡¦CA_318 |10.61Mb
  server: 137.184.174.93
  type: ss
  country: ğŸ‡¨ğŸ‡¦CA
  port: 8080
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: ğŸ‡§ğŸ‡ªBE_305 |10.08Mb
  server: 192.71.249.108
  type: ss
  country: ğŸ‡§ğŸ‡ªBE
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ğŸ‡¦ğŸ‡·AR_294 |13.46Mb
  server: 190.103.176.32
  type: ss
  country: ğŸ‡¦ğŸ‡·AR
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _286 |10.03Mb
  server: 47.243.48.161
  type: vmess
  port: 42108
  udp: true
  uuid: 0c6a09a1-21b2-4891-8769-aeff793cccf6
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /arki?ed=2048
- name: ğŸ‡¦ğŸ‡ºAU_298 |10.27Mb
  server: 3.25.166.0
  type: ss
  country: ğŸ‡¦ğŸ‡ºAU
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡¦ğŸ‡ºAU_301 |10.28Mb
  server: 3.26.167.161
  type: ss
  country: ğŸ‡¦ğŸ‡ºAU
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡¦ğŸ‡ºAU_302 |10.25Mb
  server: 52.64.71.250
  type: ss
  country: ğŸ‡¦ğŸ‡ºAU
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡¨ğŸ‡·CR_328 |10.36Mb
  server: 145.14.131.99
  type: ss
  country: ğŸ‡¨ğŸ‡·CR
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: Pool_ğŸ‡©ğŸ‡ªDE_335 |10.21Mb
  server: 185.177.229.245
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 1866
  password: oXGp1+ihlfKg826H
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡©ğŸ‡ªDE_356 |187.30Mb
  server: 85.195.101.122
  type: vmess
  country: ğŸ‡©ğŸ‡ªDE
  port: 40878
  uuid: f3d4167e-b15e-4e46-82e9-9286ef93fda7
  alterId: 0
  cipher: auto
  network: tcp
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡©ğŸ‡ªDE_334 |10.46Mb
  server: 81.19.141.45
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 443
  password: MrrxToZtXWAIfxUMsJlHYd
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡©ğŸ‡°DK_357 |10.17Mb
  server: 192.36.27.94
  type: ss
  country: ğŸ‡©ğŸ‡°DK
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ğŸ‡ªğŸ‡¨EC_360 |41.34Mb
  server: 38.165.231.25
  type: ss
  country: ğŸ‡ªğŸ‡¨EC
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡©ğŸ‡°DK_358 |10.51Mb
  server: 121.127.45.165
  type: ss
  country: ğŸ‡©ğŸ‡°DK
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_390 |10.25Mb
  server: 146.70.61.37
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: ğŸ‡¬ğŸ‡§GB_393 |10.38Mb
  server: 62.100.205.100
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡«ğŸ‡®FI_366 |10.12Mb
  server: 65.21.243.22
  type: ss
  country: ğŸ‡«ğŸ‡®FI
  port: 31348
  password: mZGUFWMAlfWqI4vP58zw9DAHxR8TZLndKkvRgHHFa9eqWdnx
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_394 |67.84Mb
  server: 89.185.84.185
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: V9gJ8OOLGreg27vYV5HSd3
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_399 |75.63Mb
  server: 89.185.84.185
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: 2kCbzhE1x9M8mfqzDEBeyL
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_395 |176.11Mb
  server: 89.185.84.185
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: iEc68ruj1qOx8hjh1KWZmc
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_401 |78.89Mb
  server: 89.185.84.185
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: IMJ6tp1rUtUi0WebZqXWiJ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_405 |182.66Mb
  server: 213.109.147.242
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 62685
  password: VpKABcOpNNA0l5G2AVOmw8
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_403 |24.63Mb
  server: 89.185.84.185
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: QpjCHeJf3ig519DjNBytqn
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_408 |25.70Mb
  server: 89.185.84.185
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: isJjdU9iV5tmvJa2JDOM4I
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_414 |10.26Mb
  server: 141.98.101.179
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: shadowsocks
  cipher: aes-128-gcm
- name: ğŸ‡¬ğŸ‡§GB_416 |124.45Mb
  server: 89.185.84.185
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: gq2tNZSuBwrZXZDZ5Z2Gfo
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_419 |124.31Mb
  server: 89.185.84.185
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: dpRpqTAaO4ozrbcm2iN4qs
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_423 |141.22Mb
  server: 89.185.84.185
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: Lm0gSCFwvlkyYeU4nSGbUM
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_424 |150.96Mb
  server: 89.185.84.185
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: JP45VRXJqp1E1G2Wr6MSbR
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_427 |32.16Mb
  server: 89.185.84.185
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: uQ61t9OowCuNc2aaU3YRAP
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_426 |103.80Mb
  server: 107.181.147.235
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 40521
  password: Z94FoM1xpW3CJzixME8CjJEFBiCFhKSWfLzT6E92Pjh7y73YfNrwPju46Gd4HE85eXSjNiTtiAYc6WTskuhxZZFebd4rcXfp
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸ‡¨ğŸ‡­CH-ğŸ‡¨ğŸ‡­CH_320 |10.03Mb
  server: h110vpnch.outlinekeys.net
  type: ss
  country: ğŸ‡¨ğŸ‡­CH
  port: 4248
  password: XbUOyIsySmsSUDENO70DvJ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡®ğŸ‡³IN_445 |10.60Mb
  server: 134.209.147.198
  type: ss
  country: ğŸ‡®ğŸ‡³IN
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: Relay_ğŸ‡¬ğŸ‡§GB-ğŸ‡¬ğŸ‡§GB_421 |25.86Mb
  server: media.mothyleela.cfd
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 40521
  password: 2WkRGh6tAv8UmsHh4i3F6zosj2dzA6sCzXbwq4TdXteztMfyA5aZcLy5jY5Z7FZ3QQMcTVwM7TvibdvzYircC7iDZafp2U6z
  cipher: chacha20-ietf-poly1305
- name: Pool_ğŸ‡­ğŸ‡°HK_434 |437.00Mb
  server: 150.107.46.21
  type: ssr
  country: ğŸ‡­ğŸ‡°HK
  port: 8083
  password: iFqnzSscN
  cipher: aes-256-cfb
  protocol: origin
  obfs: tls1.2_ticket_auth
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - _271 |10.07Mb
  - _257 |10.19Mb
  - _264 |10.53Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_255 |10.15Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_269 |10.13Mb
  - _270 |10.09Mb
  - _266 |10.06Mb
  - _261 |47.17Mb
  - _287 |10.23Mb
  - Relay_ğŸ‡¨ğŸ‡¦CA-ğŸ‡²ğŸ‡©MD_309 |10.47Mb
  - _275 |10.17Mb
  - _284 |10.16Mb
  - ğŸ‡¨ğŸ‡¦CA_311 |10.72Mb
  - ğŸ‡¨ğŸ‡¦CA_312 |10.26Mb
  - ğŸ‡¨ğŸ‡¦CA_314 |10.79Mb
  - ğŸ‡¨ğŸ‡¦CA_313 |10.18Mb
  - ğŸ‡¨ğŸ‡¦CA_315 |10.51Mb
  - ğŸ‡¦ğŸ‡¹AT_297 |10.09Mb
  - ğŸ‡¨ğŸ‡¦CA_317 |10.71Mb
  - ğŸ‡¨ğŸ‡¦CA_318 |10.61Mb
  - ğŸ‡§ğŸ‡ªBE_305 |10.08Mb
  - ğŸ‡¦ğŸ‡·AR_294 |13.46Mb
  - _286 |10.03Mb
  - ğŸ‡¦ğŸ‡ºAU_298 |10.27Mb
  - ğŸ‡¦ğŸ‡ºAU_301 |10.28Mb
  - ğŸ‡¦ğŸ‡ºAU_302 |10.25Mb
  - ğŸ‡¨ğŸ‡·CR_328 |10.36Mb
  - Pool_ğŸ‡©ğŸ‡ªDE_335 |10.21Mb
  - ğŸ‡©ğŸ‡ªDE_356 |187.30Mb
  - ğŸ‡©ğŸ‡ªDE_334 |10.46Mb
  - ğŸ‡©ğŸ‡°DK_357 |10.17Mb
  - ğŸ‡ªğŸ‡¨EC_360 |41.34Mb
  - ğŸ‡©ğŸ‡°DK_358 |10.51Mb
  - ğŸ‡¬ğŸ‡§GB_390 |10.25Mb
  - ğŸ‡¬ğŸ‡§GB_393 |10.38Mb
  - ğŸ‡«ğŸ‡®FI_366 |10.12Mb
  - ğŸ‡¬ğŸ‡§GB_394 |67.84Mb
  - ğŸ‡¬ğŸ‡§GB_399 |75.63Mb
  - ğŸ‡¬ğŸ‡§GB_395 |176.11Mb
  - ğŸ‡¬ğŸ‡§GB_401 |78.89Mb
  - ğŸ‡¬ğŸ‡§GB_405 |182.66Mb
  - ğŸ‡¬ğŸ‡§GB_403 |24.63Mb
  - ğŸ‡¬ğŸ‡§GB_408 |25.70Mb
  - ğŸ‡¬ğŸ‡§GB_414 |10.26Mb
  - ğŸ‡¬ğŸ‡§GB_416 |124.45Mb
  - ğŸ‡¬ğŸ‡§GB_419 |124.31Mb
  - ğŸ‡¬ğŸ‡§GB_423 |141.22Mb
  - ğŸ‡¬ğŸ‡§GB_424 |150.96Mb
  - ğŸ‡¬ğŸ‡§GB_427 |32.16Mb
  - ğŸ‡¬ğŸ‡§GB_426 |103.80Mb
  - Relay_ğŸ‡¨ğŸ‡­CH-ğŸ‡¨ğŸ‡­CH_320 |10.03Mb
  - ğŸ‡®ğŸ‡³IN_445 |10.60Mb
  - Relay_ğŸ‡¬ğŸ‡§GB-ğŸ‡¬ğŸ‡§GB_421 |25.86Mb
  - Pool_ğŸ‡­ğŸ‡°HK_434 |437.00Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - _271 |10.07Mb
  - _257 |10.19Mb
  - _264 |10.53Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_255 |10.15Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_269 |10.13Mb
  - _270 |10.09Mb
  - _266 |10.06Mb
  - _261 |47.17Mb
  - _287 |10.23Mb
  - Relay_ğŸ‡¨ğŸ‡¦CA-ğŸ‡²ğŸ‡©MD_309 |10.47Mb
  - _275 |10.17Mb
  - _284 |10.16Mb
  - ğŸ‡¨ğŸ‡¦CA_311 |10.72Mb
  - ğŸ‡¨ğŸ‡¦CA_312 |10.26Mb
  - ğŸ‡¨ğŸ‡¦CA_314 |10.79Mb
  - ğŸ‡¨ğŸ‡¦CA_313 |10.18Mb
  - ğŸ‡¨ğŸ‡¦CA_315 |10.51Mb
  - ğŸ‡¦ğŸ‡¹AT_297 |10.09Mb
  - ğŸ‡¨ğŸ‡¦CA_317 |10.71Mb
  - ğŸ‡¨ğŸ‡¦CA_318 |10.61Mb
  - ğŸ‡§ğŸ‡ªBE_305 |10.08Mb
  - ğŸ‡¦ğŸ‡·AR_294 |13.46Mb
  - _286 |10.03Mb
  - ğŸ‡¦ğŸ‡ºAU_298 |10.27Mb
  - ğŸ‡¦ğŸ‡ºAU_301 |10.28Mb
  - ğŸ‡¦ğŸ‡ºAU_302 |10.25Mb
  - ğŸ‡¨ğŸ‡·CR_328 |10.36Mb
  - Pool_ğŸ‡©ğŸ‡ªDE_335 |10.21Mb
  - ğŸ‡©ğŸ‡ªDE_356 |187.30Mb
  - ğŸ‡©ğŸ‡ªDE_334 |10.46Mb
  - ğŸ‡©ğŸ‡°DK_357 |10.17Mb
  - ğŸ‡ªğŸ‡¨EC_360 |41.34Mb
  - ğŸ‡©ğŸ‡°DK_358 |10.51Mb
  - ğŸ‡¬ğŸ‡§GB_390 |10.25Mb
  - ğŸ‡¬ğŸ‡§GB_393 |10.38Mb
  - ğŸ‡«ğŸ‡®FI_366 |10.12Mb
  - ğŸ‡¬ğŸ‡§GB_394 |67.84Mb
  - ğŸ‡¬ğŸ‡§GB_399 |75.63Mb
  - ğŸ‡¬ğŸ‡§GB_395 |176.11Mb
  - ğŸ‡¬ğŸ‡§GB_401 |78.89Mb
  - ğŸ‡¬ğŸ‡§GB_405 |182.66Mb
  - ğŸ‡¬ğŸ‡§GB_403 |24.63Mb
  - ğŸ‡¬ğŸ‡§GB_408 |25.70Mb
  - ğŸ‡¬ğŸ‡§GB_414 |10.26Mb
  - ğŸ‡¬ğŸ‡§GB_416 |124.45Mb
  - ğŸ‡¬ğŸ‡§GB_419 |124.31Mb
  - ğŸ‡¬ğŸ‡§GB_423 |141.22Mb
  - ğŸ‡¬ğŸ‡§GB_424 |150.96Mb
  - ğŸ‡¬ğŸ‡§GB_427 |32.16Mb
  - ğŸ‡¬ğŸ‡§GB_426 |103.80Mb
  - Relay_ğŸ‡¨ğŸ‡­CH-ğŸ‡¨ğŸ‡­CH_320 |10.03Mb
  - ğŸ‡®ğŸ‡³IN_445 |10.60Mb
  - Relay_ğŸ‡¬ğŸ‡§GB-ğŸ‡¬ğŸ‡§GB_421 |25.86Mb
  - Pool_ğŸ‡­ğŸ‡°HK_434 |437.00Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
