port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: netflix_US |59.61Mb
  server: 54.159.62.233
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: netflix_US |61.39Mb
  server: 13.222.155.147
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: netflix_US |61.64Mb
  server: 23.22.182.151
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: _172 |64.05Mb
  server: 54.227.38.247
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: _160 |282.65Mb
  server: 34.251.86.159
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: _166 |150.85Mb
  server: 13.61.180.46
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: _164 |159.06Mb
  server: 13.61.13.231
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: netflix_US |64.57Mb
  server: 98.81.59.20
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: _173 |60.29Mb
  server: 54.91.94.165
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: _181 |62.75Mb
  server: 13.218.107.141
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: disney_SG |10.20Mb
  server: 103.36.91.32
  type: ss
  port: 8388
  udp: true
  password: asd123456
  cipher: chacha20-ietf
- name: netflix_US |62.24Mb
  server: 50.19.46.248
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: netflix_US |64.77Mb
  server: 3.89.113.22
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: _190 |67.01Mb
  server: 184.72.124.41
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: _197 |31.17Mb
  server: 216.238.86.158
  type: vmess
  port: 34460
  udp: true
  uuid: 90be214d-048c-4ea2-a602-b8e4d4e51e36
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: disney_US |41.34Mb
  server: 165.140.216.141
  type: vmess
  port: 443
  uuid: e7d72a8d-26f2-4b54-b366-0c43e0bcba7d
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: netflix_IE |353.42Mb
  server: 3.250.105.240
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: netflix_US |42.13Mb
  server: 163.192.49.195
  type: vmess
  port: 443
  uuid: bcb7c581-3c95-4569-a4e7-918141e91ea3
  alterId: 0
  cipher: auto
  network: http
  http-opts:
    path:
    - /
    headers:
      Host:
      - a.189.cn
  h2-opts: {}
- name: netflix_IE |351.57Mb
  server: 54.246.35.116
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: _168 |147.68Mb
  server: 185.231.233.112
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: _183 |167.77Mb
  server: 51.20.125.235
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: netflix_IE |308.93Mb
  server: 3.253.99.197
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: _199 |11.28Mb
  server: 15.235.41.200
  type: vmess
  port: 80
  uuid: 58fe1542-5290-40ad-815a-77707a81afe5
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /IOebhLMhl1CTbFHbL95myfRX2
- name: _208 |260.45Mb
  server: 85.195.101.122
  type: vmess
  port: 40878
  uuid: f3d4167e-b15e-4e46-82e9-9286ef93fda7
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _205 |23.18Mb
  server: 8.210.184.105
  type: vmess
  port: 40374
  udp: true
  uuid: 36b76373-7a4f-4669-9113-7d247bcf2704
  alterId: 0
  cipher: auto
  network: http
  http-opts:
    method: GET
    path:
    - /
  h2-opts: {}
- name: _162 |18.08Mb
  server: 94.198.220.183
  type: ss
  port: 64674
  udp: true
  password: s8LbJCgUiGXeCKVc63tHJP
  cipher: chacha20-ietf-poly1305
- name: disney_HK |10.84Mb
  server: 104.19.61.72
  type: vmess
  port: 443
  uuid: 4bf075f5-4d5e-4d39-f5ab-b32a86250f0e
  alterId: 0
  cipher: auto
  network: ws
  servername: hk.nbee.pp.ua
  http-opts: {}
  h2-opts: {}
  tls: true
  ws-opts:
    path: /aa
    headers:
      Host: hk.nbee.pp.ua
- name: disney_SG |18.20Mb
  server: 165.154.195.38
  type: vmess
  port: 35034
  uuid: 959a8caf-4cea-43d0-a548-3628e7ddfafc
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _206 |25.62Mb
  server: 8.218.105.196
  type: vmess
  port: 52752
  uuid: 925bdbf5-72be-4437-bebf-441c61089f6b
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _214 |10.84Mb
  server: 130.162.152.253
  type: vmess
  port: 56867
  uuid: 5206bb9f-2cbc-44ac-de2a-471439a23707
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _216 |12.49Mb
  server: 54.206.192.9
  type: vmess
  port: 16407
  uuid: 08f45028-1db6-4e93-bf51-d344b6c71e19
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _211 |22.23Mb
  server: 183.236.51.36
  type: vmess
  port: 59003
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 64
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _203 |42.26Mb
  server: 89.31.120.192
  type: vmess
  port: 443
  uuid: 44537595-9ccc-4b83-8936-5f9ad3229019
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: Relay_-ğŸ‡§ğŸ‡·BR_218 |73.02Mb
  server: pq-brazil1.09vpn.com
  type: vmess
  port: 80
  uuid: c04c3b34-70fd-4fec-963e-c12d09f36bef
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /vmess/
    headers:
      Host: pq-brazil1.09vpn.com
- name: _224 |56.21Mb
  server: 153.121.51.29
  type: trojan
  port: 2890
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: _226 |13.06Mb
  server: 202.181.103.235
  type: trojan
  port: 2890
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: _227 |52.22Mb
  server: 160.16.236.32
  type: trojan
  port: 4054
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: disney_netflix_GB |266.12Mb
  server: 172.67.134.185
  type: trojan
  port: 443
  udp: true
  password: POORIARED
  sni: reDfRee8.REDFree8.ir
  ws-opts:
    path: /eyJqdW5rIjoiVUl6eXhLZkkwUTJ3ZzkiLCJwcm90b2NvbCI6InRyIiwibW9kZSI6InByb3h5aXAiLCJwYW5lbElQcyI6W119?ed=2560
    headers:
      Host: reDfRee8.REDFree8.ir
  network: ws
- name: _229 |10.15Mb
  server: 153.121.39.240
  type: trojan
  port: 4054
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: _231 |22.26Mb
  server: 160.16.124.55
  type: trojan
  port: 2890
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: _222 |12.87Mb
  server: 47.243.51.237
  type: vmess
  port: 52801
  uuid: ef93f413-9039-4ddb-aefb-2490287df55a
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /arki
- name: _246 |161.55Mb
  server: 38.96.254.102
  type: trojan
  port: 18509
  password: .ie4rghJuMkcf0oF
  sni: shoppingmall.electricbanana.click
- name: disney_HK |14.99Mb
  server: 154.21.201.83
  type: vmess
  port: 443
  uuid: 4bf075f5-4d5e-4d39-f5ab-b32a86250f0e
  alterId: 0
  cipher: auto
  network: ws
  servername: hk.nbee.pp.ua
  http-opts: {}
  h2-opts: {}
  tls: true
  ws-opts:
    path: /aa
    headers:
      Host: hk.nbee.pp.ua
- name: _233 |19.19Mb
  server: 160.16.223.205
  type: trojan
  port: 4054
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: _234 |46.63Mb
  server: 160.16.151.196
  type: trojan
  port: 4054
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: _235 |12.48Mb
  server: 153.121.65.107
  type: trojan
  port: 3093
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: _240 |49.01Mb
  server: 160.16.196.59
  type: trojan
  port: 2890
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¸ğŸ‡¬SG_245 |10.05Mb
  server: 160.16.150.76
  type: trojan
  port: 3145
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: Pool__241 |162.27Mb
  server: 70.34.218.149
  type: trojan
  port: 11930
  password: BaeSzHdfJIR13l67
  sni: softpillow.silentrocket.click
- name: disney_FR |164.15Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 27092
  uuid: a0596ba6-72a3-4366-8992-77088da65bd8
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_FR |187.06Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 40433
  uuid: d8fd8955-78db-49ba-d86f-3e4729f6ac4d
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: netflix_NL |244.52Mb
  server: 82.38.31.217
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡²ğŸ‡½MX_267 |183.28Mb
  server: 216.238.87.47
  type: vmess
  country: ğŸ‡²ğŸ‡½MX
  port: 27502
  uuid: b8155ce4-7e08-4c40-800f-8671312b7124
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡¬ğŸ‡§GB_262 |233.05Mb
  server: 82.38.31.191
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: netflix_IE |397.21Mb
  server: 52.50.200.2
  type: ss
  country: ğŸ‡®ğŸ‡ªIE
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡ºğŸ‡¸US_272 |51.73Mb
  server: 18.207.122.59
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡¬ğŸ‡§GB_263 |238.31Mb
  server: 82.38.31.194
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: netflix_US |52.53Mb
  server: 47.253.197.26
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 12056
  uuid: dd7be7f1-38ff-45e6-f1e5-b20c2190f527
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_KZ |10.97Mb
  server: 31.3.209.183
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 28212
  password: Kmn7dHPw5wNfkqQMPcGWQA
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_273 |64.11Mb
  server: 45.12.136.170
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: l668XHPejoSNNuD66BYzyehaCpZexiF7
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸ‡©ğŸ‡ªDE-ğŸ‡©ğŸ‡ªDE_252 |168.59Mb
  server: cpanel.navar1.ir
  type: vmess
  country: ğŸ‡©ğŸ‡ªDE
  port: 100
  uuid: 95c6f6f0-84f7-4443-8a50-a59f8e66f5ee
  alterId: 0
  cipher: auto
  network: tcp
  servername: cpanel.navar1.ir
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - netflix_US |59.61Mb
  - netflix_US |61.39Mb
  - netflix_US |61.64Mb
  - _172 |64.05Mb
  - _160 |282.65Mb
  - _166 |150.85Mb
  - _164 |159.06Mb
  - netflix_US |64.57Mb
  - _173 |60.29Mb
  - _181 |62.75Mb
  - disney_SG |10.20Mb
  - netflix_US |62.24Mb
  - netflix_US |64.77Mb
  - _190 |67.01Mb
  - _197 |31.17Mb
  - disney_US |41.34Mb
  - netflix_IE |353.42Mb
  - netflix_US |42.13Mb
  - netflix_IE |351.57Mb
  - _168 |147.68Mb
  - _183 |167.77Mb
  - netflix_IE |308.93Mb
  - _199 |11.28Mb
  - _208 |260.45Mb
  - _205 |23.18Mb
  - _162 |18.08Mb
  - disney_HK |10.84Mb
  - disney_SG |18.20Mb
  - _206 |25.62Mb
  - _214 |10.84Mb
  - _216 |12.49Mb
  - _211 |22.23Mb
  - _203 |42.26Mb
  - Relay_-ğŸ‡§ğŸ‡·BR_218 |73.02Mb
  - _224 |56.21Mb
  - _226 |13.06Mb
  - _227 |52.22Mb
  - disney_netflix_GB |266.12Mb
  - _229 |10.15Mb
  - _231 |22.26Mb
  - _222 |12.87Mb
  - _246 |161.55Mb
  - disney_HK |14.99Mb
  - _233 |19.19Mb
  - _234 |46.63Mb
  - _235 |12.48Mb
  - _240 |49.01Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_245 |10.05Mb
  - Pool__241 |162.27Mb
  - disney_FR |164.15Mb
  - disney_FR |187.06Mb
  - netflix_NL |244.52Mb
  - ğŸ‡²ğŸ‡½MX_267 |183.28Mb
  - ğŸ‡¬ğŸ‡§GB_262 |233.05Mb
  - netflix_IE |397.21Mb
  - ğŸ‡ºğŸ‡¸US_272 |51.73Mb
  - ğŸ‡¬ğŸ‡§GB_263 |238.31Mb
  - netflix_US |52.53Mb
  - disney_KZ |10.97Mb
  - ğŸ‡ºğŸ‡¸US_273 |64.11Mb
  - Relay_ğŸ‡©ğŸ‡ªDE-ğŸ‡©ğŸ‡ªDE_252 |168.59Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - netflix_US |59.61Mb
  - netflix_US |61.39Mb
  - netflix_US |61.64Mb
  - _172 |64.05Mb
  - _160 |282.65Mb
  - _166 |150.85Mb
  - _164 |159.06Mb
  - netflix_US |64.57Mb
  - _173 |60.29Mb
  - _181 |62.75Mb
  - disney_SG |10.20Mb
  - netflix_US |62.24Mb
  - netflix_US |64.77Mb
  - _190 |67.01Mb
  - _197 |31.17Mb
  - disney_US |41.34Mb
  - netflix_IE |353.42Mb
  - netflix_US |42.13Mb
  - netflix_IE |351.57Mb
  - _168 |147.68Mb
  - _183 |167.77Mb
  - netflix_IE |308.93Mb
  - _199 |11.28Mb
  - _208 |260.45Mb
  - _205 |23.18Mb
  - _162 |18.08Mb
  - disney_HK |10.84Mb
  - disney_SG |18.20Mb
  - _206 |25.62Mb
  - _214 |10.84Mb
  - _216 |12.49Mb
  - _211 |22.23Mb
  - _203 |42.26Mb
  - Relay_-ğŸ‡§ğŸ‡·BR_218 |73.02Mb
  - _224 |56.21Mb
  - _226 |13.06Mb
  - _227 |52.22Mb
  - disney_netflix_GB |266.12Mb
  - _229 |10.15Mb
  - _231 |22.26Mb
  - _222 |12.87Mb
  - _246 |161.55Mb
  - disney_HK |14.99Mb
  - _233 |19.19Mb
  - _234 |46.63Mb
  - _235 |12.48Mb
  - _240 |49.01Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_245 |10.05Mb
  - Pool__241 |162.27Mb
  - disney_FR |164.15Mb
  - disney_FR |187.06Mb
  - netflix_NL |244.52Mb
  - ğŸ‡²ğŸ‡½MX_267 |183.28Mb
  - ğŸ‡¬ğŸ‡§GB_262 |233.05Mb
  - netflix_IE |397.21Mb
  - ğŸ‡ºğŸ‡¸US_272 |51.73Mb
  - ğŸ‡¬ğŸ‡§GB_263 |238.31Mb
  - netflix_US |52.53Mb
  - disney_KZ |10.97Mb
  - ğŸ‡ºğŸ‡¸US_273 |64.11Mb
  - Relay_ğŸ‡©ğŸ‡ªDE-ğŸ‡©ğŸ‡ªDE_252 |168.59Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
