port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: Relay_-ğŸ‡ºğŸ‡¸US_383 |12.50Mb
  server: 82.198.246.97
  type: vmess
  port: 180
  uuid: d13fc2f5-3e05-4795-81eb-44143a09e552
  alterId: 0
  cipher: auto
  network: tcp
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_US |246.41Mb
  server: 198.181.34.22
  type: vmess
  port: 11133
  uuid: 29b25bdf-9a83-4dde-90c7-77c51cd23724
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: Relay_-ğŸ‡³ğŸ‡±NL_448 |14.15Mb
  server: 160.16.124.55
  type: trojan
  port: 4054
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡³ğŸ‡±NL_449 |10.15Mb
  server: 160.16.63.16
  type: trojan
  port: 4054
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡³ğŸ‡±NL_451 |60.25Mb
  server: 160.16.57.238
  type: trojan
  port: 4054
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¯ğŸ‡µJP_450 |22.02Mb
  server: 52.195.176.26
  type: trojan
  port: 2145
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: Relay_-ğŸ‡¸ğŸ‡¬SG_457 |12.65Mb
  server: 153.121.51.29
  type: trojan
  port: 127
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: netflix_NL |237.50Mb
  server: 151.242.251.137
  type: ss
  port: 8080
  password: o5osZg269v5zHpYjr1xY9s
  cipher: chacha20-ietf-poly1305
- name: disney_HK |23.70Mb
  server: 58.152.25.20
  type: trojan
  port: 443
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: Relay_-ğŸ‡³ğŸ‡±NL_456 |54.56Mb
  server: 16.163.0.29
  type: trojan
  port: 4054
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: disney_MD |538.13Mb
  server: 185.153.197.5
  type: ss
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: Relay_-ğŸ‡¯ğŸ‡µJP_461 |11.16Mb
  server: 153.121.65.107
  type: trojan
  port: 1331
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡³ğŸ‡±NL_460 |12.31Mb
  server: 160.16.236.32
  type: trojan
  port: 4054
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: _378 |18.10Mb
  server: 103.106.3.82
  type: ss
  port: 443
  udp: true
  password: 4SaCIazlgumYkM8FkPzlmwjpyWBDZFBk
  cipher: chacha20-ietf-poly1305
- name: Relay_-ğŸ‡³ğŸ‡±NL_462 |10.49Mb
  server: 160.16.81.84
  type: trojan
  port: 4054
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¯ğŸ‡µJP_463 |12.49Mb
  server: 153.121.65.107
  type: trojan
  port: 3169
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: ğŸ‡¬ğŸ‡§GB_472 |38.29Mb
  server: 185.193.48.157
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: zwBLM6bBE5YxvwvnKgxAq3ErXpqMYv20
  cipher: chacha20-ietf-poly1305
- name: disney_HK |28.41Mb
  server: 112.118.116.66
  type: trojan
  port: 443
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: disney_HK |28.10Mb
  server: 203.198.122.13
  type: trojan
  port: 443
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: disney_netflix_DE |271.00Mb
  server: 3.123.51.236
  type: trojan
  country: ğŸ‡©ğŸ‡ªDE
  port: 22223
  udp: true
  password: telegram-id-directvpn
  sni: trojan.burgerip.co.uk
  skip-cert-verify: true
- name: ğŸ‡¦ğŸ‡ºAU_464 |10.96Mb
  server: 54.252.240.128
  type: vmess
  country: ğŸ‡¦ğŸ‡ºAU
  port: 1000
  uuid: ca26a9fd-fef8-4ea7-d194-450ce4e0c67a
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡§ğŸ‡·BR_465 |12.09Mb
  server: 38.180.16.86
  type: vmess
  country: ğŸ‡§ğŸ‡·BR
  port: 36104
  uuid: E146A8CB-9D2F-449C-ADCA-8736FB
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_FR |120.98Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 40433
  uuid: d8fd8955-78db-49ba-d86f-3e4729f6ac4d
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_FR |69.41Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 27092
  uuid: a0596ba6-72a3-4366-8992-77088da65bd8
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: netflix_NL |136.98Mb
  server: 82.38.31.190
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: netflix_NL |33.78Mb
  server: 82.38.31.179
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡²ğŸ‡½MX_490 |38.31Mb
  server: 216.238.89.53
  type: vmess
  country: ğŸ‡²ğŸ‡½MX
  port: 57283
  uuid: 1a5aafc0-6482-451d-fe76-6875b7818579
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡­ğŸ‡°HK_476 |29.34Mb
  server: 47.243.51.237
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 52801
  uuid: ef93f413-9039-4ddb-aefb-2490287df55a
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
  ws-opts:
    path: /arki?ed=2048
- name: ğŸ‡­ğŸ‡°HK_482 |31.42Mb
  server: 47.242.162.235
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 3787
  uuid: e748fe05-2678-4c31-84c6-14ed825b92b4
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
  ws-opts:
    path: /arki?ed=2048
- name: ğŸ‡­ğŸ‡°HK_475 |50.45Mb
  server: 87.121.162.249
  type: ss
  country: ğŸ‡­ğŸ‡°HK
  port: 443
  password: JGv616hMWdjfuZ00jYfq7XkBHJZrOBrg
  cipher: chacha20-ietf-poly1305
- name: disney_US |18.15Mb
  server: 38.84.201.21
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 53487
  uuid: c3c1ec05-df2c-4975-9b42-e9b007564eb1
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡­ğŸ‡°HK_484 |27.29Mb
  server: 8.210.134.183
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 3721
  uuid: e72f5c6b-220f-40b3-a115-2d81473458cf
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
  ws-opts:
    path: /
- name: netflix_NL |11.43Mb
  server: 45.87.175.166
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 443
  password: 1RWwXhwfAB5gAEozU4G2Pg
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡­ğŸ‡°HK_486 |26.22Mb
  server: 8.218.116.26
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 32228
  uuid: e4767e9f-ed00-4f31-a984-a918bdd9b09c
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡­ğŸ‡°HK_487 |31.30Mb
  server: 47.242.140.52
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 48219
  uuid: 006893c6-79b1-4c44-94ff-b8bbea065f1f
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
  ws-opts:
    path: /arki?ed=2048
- name: ğŸ‡·ğŸ‡ºRU_492 |106.15Mb
  server: 109.71.246.210
  type: ss
  country: ğŸ‡·ğŸ‡ºRU
  port: 56689
  password: YQCSKoCF3QazW8YlvDBWA4
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡²ğŸ‡¾MY_491 |30.76Mb
  server: 38.54.98.110
  type: vmess
  country: ğŸ‡²ğŸ‡¾MY
  port: 2052
  uuid: 665d9b8f-153d-4907-adac-de12afd9c851
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: ğŸ‡¸ğŸ‡¬SG_493 |11.01Mb
  server: 68.183.178.131
  type: vmess
  country: ğŸ‡¸ğŸ‡¬SG
  port: 58607
  uuid: c11c32cb-27b3-4afa-c0f3-fb250aa4959e
  alterId: 0
  cipher: auto
  network: ws
  servername: www.12333.monster
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /
    headers:
      HOST: www.12333.monster
- name: disney_HK |19.97Mb
  server: 45.136.12.37
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 38141
  uuid: fd291be6-b48d-43a1-da38-66c7f80e2f80
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_US |22.22Mb
  server: cf.fovi.tk
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  uuid: bf67437e-6c90-45ca-abc2-c7240a5ce2aa
  alterId: 0
  cipher: auto
  network: ws
  servername: foxlux.fovi.tk
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /eisasqa
    headers:
      HOST: foxlux.fovi.tk
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - Relay_-ğŸ‡ºğŸ‡¸US_383 |12.50Mb
  - disney_netflix_US |246.41Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_448 |14.15Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_449 |10.15Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_451 |60.25Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_450 |22.02Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_457 |12.65Mb
  - netflix_NL |237.50Mb
  - disney_HK |23.70Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_456 |54.56Mb
  - disney_MD |538.13Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_461 |11.16Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_460 |12.31Mb
  - _378 |18.10Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_462 |10.49Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_463 |12.49Mb
  - ğŸ‡¬ğŸ‡§GB_472 |38.29Mb
  - disney_HK |28.41Mb
  - disney_HK |28.10Mb
  - disney_netflix_DE |271.00Mb
  - ğŸ‡¦ğŸ‡ºAU_464 |10.96Mb
  - ğŸ‡§ğŸ‡·BR_465 |12.09Mb
  - disney_FR |120.98Mb
  - disney_netflix_FR |69.41Mb
  - netflix_NL |136.98Mb
  - netflix_NL |33.78Mb
  - ğŸ‡²ğŸ‡½MX_490 |38.31Mb
  - ğŸ‡­ğŸ‡°HK_476 |29.34Mb
  - ğŸ‡­ğŸ‡°HK_482 |31.42Mb
  - ğŸ‡­ğŸ‡°HK_475 |50.45Mb
  - disney_US |18.15Mb
  - ğŸ‡­ğŸ‡°HK_484 |27.29Mb
  - netflix_NL |11.43Mb
  - ğŸ‡­ğŸ‡°HK_486 |26.22Mb
  - ğŸ‡­ğŸ‡°HK_487 |31.30Mb
  - ğŸ‡·ğŸ‡ºRU_492 |106.15Mb
  - ğŸ‡²ğŸ‡¾MY_491 |30.76Mb
  - ğŸ‡¸ğŸ‡¬SG_493 |11.01Mb
  - disney_HK |19.97Mb
  - disney_netflix_US |22.22Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - Relay_-ğŸ‡ºğŸ‡¸US_383 |12.50Mb
  - disney_netflix_US |246.41Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_448 |14.15Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_449 |10.15Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_451 |60.25Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_450 |22.02Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_457 |12.65Mb
  - netflix_NL |237.50Mb
  - disney_HK |23.70Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_456 |54.56Mb
  - disney_MD |538.13Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_461 |11.16Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_460 |12.31Mb
  - _378 |18.10Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_462 |10.49Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_463 |12.49Mb
  - ğŸ‡¬ğŸ‡§GB_472 |38.29Mb
  - disney_HK |28.41Mb
  - disney_HK |28.10Mb
  - disney_netflix_DE |271.00Mb
  - ğŸ‡¦ğŸ‡ºAU_464 |10.96Mb
  - ğŸ‡§ğŸ‡·BR_465 |12.09Mb
  - disney_FR |120.98Mb
  - disney_netflix_FR |69.41Mb
  - netflix_NL |136.98Mb
  - netflix_NL |33.78Mb
  - ğŸ‡²ğŸ‡½MX_490 |38.31Mb
  - ğŸ‡­ğŸ‡°HK_476 |29.34Mb
  - ğŸ‡­ğŸ‡°HK_482 |31.42Mb
  - ğŸ‡­ğŸ‡°HK_475 |50.45Mb
  - disney_US |18.15Mb
  - ğŸ‡­ğŸ‡°HK_484 |27.29Mb
  - netflix_NL |11.43Mb
  - ğŸ‡­ğŸ‡°HK_486 |26.22Mb
  - ğŸ‡­ğŸ‡°HK_487 |31.30Mb
  - ğŸ‡·ğŸ‡ºRU_492 |106.15Mb
  - ğŸ‡²ğŸ‡¾MY_491 |30.76Mb
  - ğŸ‡¸ğŸ‡¬SG_493 |11.01Mb
  - disney_HK |19.97Mb
  - disney_netflix_US |22.22Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
