port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: _350
  server: 45.87.175.154
  type: ss
  port: 8080
  udp: true
  password: 1RWwXhwfAB5gAEozU4G2Pg
  cipher: chacha20-ietf-poly1305
- name: _351
  server: 82.38.31.202
  type: ss
  port: 8080
  udp: true
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: disney_NL
  server: 213.176.16.77
  type: ss
  port: 7022
  udp: true
  password: 8HtC7rj6NfZncXYvAjDV5t
  cipher: chacha20-ietf-poly1305
- name: _352
  server: 185.156.110.92
  type: ss
  port: 443
  udp: true
  password: gXOXk2FJwsz9P6nXIICuDNOqF9gWX1dn
  cipher: chacha20-ietf-poly1305
- name: _359
  server: 23.95.72.81
  type: ss
  port: 443
  udp: true
  password: UAMVtHm54uahd6SiN5WcD16rsPSdabPG
  cipher: chacha20-ietf-poly1305
- name: _358
  server: 45.14.245.2
  type: ss
  port: 443
  udp: true
  password: 17ZDORWIliQHuO6WRGHChXYMzdRtAYVP
  cipher: chacha20-ietf-poly1305
- name: Relay_-ðŸ‡ºðŸ‡¸US_357
  server: huojian1.vn9987.top
  type: ss
  port: 51004
  udp: true
  password: 5341d691-c16c-402e-b87f-27a36b7c88b3
  cipher: chacha20-ietf-poly1305
- name: Relay_-ðŸ‡ºðŸ‡¸US_349
  server: huojian1.vn9987.top
  type: ss
  port: 51004
  udp: true
  password: 293c263b-7b5a-4c39-9c0a-1be5139c6851
  cipher: chacha20-ietf-poly1305
- name: Relay_-ðŸ‡ºðŸ‡¸US_355
  server: huojian1.vn9987.top
  type: ss
  port: 51004
  udp: true
  password: 65e3253e-3707-49ec-b91a-c8b3546497cc
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_US
  server: huojian1.vn9987.top
  type: ss
  port: 51004
  udp: true
  password: 315143a7-753c-469c-a4b3-53f77ee49470
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_US
  server: huojian1.vn9987.top
  type: ss
  port: 51004
  udp: true
  password: 5e502af3-463b-43a8-ac64-8725b1e22a1a
  cipher: chacha20-ietf-poly1305
- name: _360
  server: 45.87.175.181
  type: ss
  port: 8080
  udp: true
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: _361
  server: 45.87.175.199
  type: ss
  port: 8080
  udp: true
  password: QCXDxuDlTTMD7jtgHUjIoj
  cipher: chacha20-ietf-poly1305
- name: Relay_-ðŸ‡³ðŸ‡±NL_364
  server: 151.242.251.131
  type: ss
  port: 8080
  udp: true
  password: QCXDxuDlTTMD7jtgHUjIoj
  cipher: chacha20-ietf-poly1305
- name: _363
  server: 82.38.31.176
  type: ss
  port: 8080
  udp: true
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: _362
  server: 213.159.67.124
  type: ss
  port: 443
  udp: true
  password: mbhqsStnFQT1cTZYCdsmkugGUC6GT6rp
  cipher: chacha20-ietf-poly1305
- name: _367
  server: 213.159.66.206
  type: ss
  port: 443
  udp: true
  password: pl2XtR0pzwknQOGwewbwXtPYDw1zn9Vu
  cipher: chacha20-ietf-poly1305
- name: _366
  server: 103.149.183.154
  type: ss
  port: 8388
  udp: true
  password: asd123456
  cipher: chacha20-ietf
- name: disney_MD
  server: 185.153.197.5
  type: ss
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: _365
  server: 95.174.68.33
  type: ss
  port: 443
  udp: true
  password: YzH4id7ZEyKpfy39F2YcOmzCsBklGwh8
  cipher: chacha20-ietf-poly1305
- name: _374
  server: 192.227.129.144
  type: ss
  port: 51004
  udp: true
  password: 5341d691-c16c-402e-b87f-27a36b7c88b3
  cipher: chacha20-ietf-poly1305
- name: _371
  server: 103.75.118.125
  type: ss
  port: 443
  udp: true
  password: XLOrvLWkCBBBxLqSEe9S8lnC5PLsNfRh
  cipher: chacha20-ietf-poly1305
- name: Relay_-ðŸ‡ºðŸ‡¸US_372
  server: huojian1.vn9987.top
  type: ss
  port: 51004
  udp: true
  password: f1fa04be-bdf6-477e-81d0-b46232227455
  cipher: chacha20-ietf-poly1305
- name: Relay_-ðŸ‡ºðŸ‡¸US_368
  server: huojian1.vn9987.top
  type: ss
  port: 51004
  udp: true
  password: 7142d7c5-fb76-4c9c-9b90-ba0c325aec4d
  cipher: chacha20-ietf-poly1305
- name: Relay_-ðŸ‡ºðŸ‡¸US_369
  server: huojian1.vn9987.top
  type: ss
  port: 51004
  udp: true
  password: 2eaa2cc3-9b7d-4bed-a8f9-c509d76cf57f
  cipher: chacha20-ietf-poly1305
- name: Relay_-ðŸ‡ºðŸ‡¸US_378
  server: usiys.southbyte.xyz
  type: trojan
  port: 5897
  udp: true
  password: fg20mtCFHy
  sni: usiys.southbyte.xyz
  skip-cert-verify: true
- name: disney_RU
  server: clr.ducks.tel
  type: ss
  port: 17846
  udp: true
  password: '907560230'
  cipher: chacha20-ietf-poly1305
- name: netflix_DE
  server: clr.ducks.tel
  type: ss
  port: 17844
  udp: true
  password: '907560230'
  cipher: chacha20-ietf-poly1305
- name: Relay_-ðŸ‡­ðŸ‡°HK_376
  server: 131.186.63.89
  type: vmess
  port: 11655
  uuid: 4bf075f5-4d5e-4d39-f5ab-b32a86250f0e
  alterId: 0
  cipher: auto
  network: ws
  servername: hk.nbee.pp.ua
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /aa
    headers:
      Host: hk.nbee.pp.ua
- name: Relay_-ðŸ‡³ðŸ‡±NL_379
  server: 3.113.21.213
  type: trojan
  port: 2890
  password: 2cf6d686799e6fa95316394064f26c0a
  sni: www.nintendogames.net
- name: Relay_-ðŸ‡¯ðŸ‡µJP_380
  server: 160.16.107.37
  type: trojan
  port: 3093
  password: 2cf6d686799e6fa95316394064f26c0a
  sni: www.nintendogames.net
- name: Relay_-ðŸ‡·ðŸ‡ºRU_375
  server: clr.ducks.tel
  type: ss
  port: 17847
  udp: true
  password: '907560230'
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_GB
  server: 172.66.44.230
  type: trojan
  port: 8443
  udp: true
  password: 8r<[9'l6hAO#8ZQi
  sni: Koma-YT.PAGeS.Dev
  ws-opts:
    path: /tro8sFW1S91B6sZrM1
    headers:
      Host: Koma-YT.PAGeS.Dev
  network: ws
- name: disney_GB
  server: 162.159.42.58
  type: trojan
  port: 443
  udp: true
  password: '0'
  alpn:
  - http%2F1.1
  sni: c03237cb.ba73fe85.netlib.re
  skip-cert-verify: true
  ws-opts:
    path: /
    headers:
      Host: c03237cb.ba73fe85.netlib.re
  network: ws
- name: disney_RU
  server: 37.18.14.33
  type: trojan
  port: 443
  udp: true
  password: Qzy7tgpRhu
  sni: m.vk.com
  skip-cert-verify: true
- name: Relay_-ðŸ‡¸ðŸ‡¬SG_383
  server: 202.181.103.246
  type: trojan
  port: 127
  password: 2cf6d686799e6fa95316394064f26c0a
  sni: www.nintendogames.net
- name: Relay_-ðŸ‡³ðŸ‡±NL_386
  server: 160.16.63.16
  type: trojan
  port: 2890
  password: 2cf6d686799e6fa95316394064f26c0a
  sni: www.nintendogames.net
- name: disney_FR
  server: 95.182.97.125
  type: trojan
  port: 8443
  udp: true
  password: '0'
  sni: c03237cb.ba73fe85.netlib.re
  skip-cert-verify: true
  ws-opts:
    path: /
    headers:
      Host: c03237cb.ba73fe85.netlib.re
  network: ws
- name: Relay_-ðŸ‡¯ðŸ‡µJP_390
  server: 160.16.131.243
  type: trojan
  port: 3169
  password: 2cf6d686799e6fa95316394064f26c0a
  sni: www.nintendogames.net
- name: disney_HK
  server: cdnfire.xiaomispeed.com
  type: trojan
  port: 21101
  udp: true
  password: 47da622e-b66b-4b73-8b76-f634986108ee
  sni: cdnfire.xiaomispeed.com
- name: disney_HK
  server: cdnfire.xiaomispeed.com
  type: trojan
  port: 21102
  udp: true
  password: 47da622e-b66b-4b73-8b76-f634986108ee
  sni: cdnfire.xiaomispeed.com
  skip-cert-verify: true
- name: _393
  server: 54.199.134.79
  type: trojan
  port: 20230
  udp: true
  password: aef43c17-8cf7-4ffc-800b-1dfb4e89ba83
  sni: www.alibaba.com
  skip-cert-verify: true
  ws-opts:
    path: /
    headers:
      Host: www.alibaba.com
  network: ws
- name: disney_GB
  server: koma-yt.pages.dev
  type: trojan
  port: 8443
  udp: true
  password: 8r<[9'l6hAO#8ZQi
  sni: Koma-YT.PAGeS.Dev
  ws-opts:
    path: /tro8sFW1S91B6sZrM1
    headers:
      Host: Koma-YT.PAGeS.Dev
  network: ws
- name: disney_SG
  server: cdnfire.xiaomispeed.com
  type: trojan
  port: 23301
  udp: true
  password: 47da622e-b66b-4b73-8b76-f634986108ee
  sni: cdnfire.xiaomispeed.com
  skip-cert-verify: true
- name: Relay_-ðŸ‡ºðŸ‡¸US_389
  server: cdnfire.xiaomispeed.com
  type: trojan
  port: 25502
  udp: true
  password: 47da622e-b66b-4b73-8b76-f634986108ee
  sni: cdnfire.xiaomispeed.com
  skip-cert-verify: true
- name: disney_HK
  server: cdnfire.xiaomispeed.com
  type: trojan
  port: 21103
  udp: true
  password: 47da622e-b66b-4b73-8b76-f634986108ee
  sni: cdnfire.xiaomispeed.com
  skip-cert-verify: true
- name: Relay_-ðŸ‡¯ðŸ‡µJP_398
  server: 160.16.57.238
  type: trojan
  port: 3169
  password: 2cf6d686799e6fa95316394064f26c0a
  sni: www.nintendogames.net
- name: disney_HK
  server: 58.152.110.120
  type: trojan
  port: 443
  password: 2cf6d686799e6fa95316394064f26c0a
  sni: www.nintendogames.net
- name: Relay_-ðŸ‡³ðŸ‡±NL_399
  server: 160.16.236.32
  type: trojan
  port: 2760
  password: 2cf6d686799e6fa95316394064f26c0a
  sni: www.nintendogames.net
- name: disney_HK
  server: cdnfire.xiaomispeed.com
  type: trojan
  port: 21104
  udp: true
  password: 47da622e-b66b-4b73-8b76-f634986108ee
  sni: cdnfire.xiaomispeed.com
  skip-cert-verify: true
- name: disney_NL
  server: 89.169.8.105
  type: trojan
  port: 443
  udp: true
  password: '0'
  alpn:
  - http%2F1.1
  sni: c03237cb.ba73fe85.netlib.re
  ws-opts:
    path: /
    headers:
      Host: c03237cb.ba73fe85.netlib.re
  network: ws
- name: disney_FR
  server: 208.76.223.218
  type: vmess
  country: ðŸ‡ªðŸ‡¸ES
  port: 27092
  uuid: a0596ba6-72a3-4366-8992-77088da65bd8
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ðŸ‡¬ðŸ‡§GB_404
  server: 82.38.31.199
  type: ss
  country: ðŸ‡¬ðŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: Relay_ðŸ‡¬ðŸ‡§GB-ðŸ‡³ðŸ‡±NL_405
  server: 82.38.31.214
  type: ss
  country: ðŸ‡¬ðŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: disney_HK
  server: 58.152.110.92
  type: trojan
  port: 443
  udp: true
  password: dd2f25b4c70689de8bc0f7fa9d6591cb
  sni: www.nintendogames.net
- name: ðŸ‡¬ðŸ‡§GB_406
  server: 82.38.31.184
  type: ss
  country: ðŸ‡¬ðŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ðŸ‡¬ðŸ‡§GB_407
  server: 82.38.31.190
  type: ss
  country: ðŸ‡¬ðŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ðŸ‡¬ðŸ‡§GB_408
  server: 82.38.31.205
  type: ss
  country: ðŸ‡¬ðŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_NL
  server: 82.38.31.208
  type: ss
  country: ðŸ‡¬ðŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: disney_NL
  server: 213.176.16.71
  type: ss
  country: ðŸ‡®ðŸ‡·IR
  port: 4966
  password: lXOVjEMsx00jeOQzHsQrkL
  cipher: chacha20-ietf-poly1305
- name: Relay_-ðŸ‡ºðŸ‡¸US_377
  server: www.ub888.cc
  type: vmess
  port: 8443
  udp: true
  uuid: bcb7c581-3c95-4569-a4e7-918141e91ea3
  alterId: 0
  cipher: auto
  network: ws
  servername: sg.hietamei-qingzeuyq.top
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /
    headers:
      Host: sg.hietamei-qingzeuyq.top
- name: ðŸ‡²ðŸ‡½MX_413
  server: 216.238.89.53
  type: vmess
  country: ðŸ‡²ðŸ‡½MX
  port: 57283
  uuid: 1a5aafc0-6482-451d-fe76-6875b7818579
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_ðŸ‡©ðŸ‡ªDE-ðŸ‡©ðŸ‡ªDE_402
  server: node4.rtxconfigz.com
  type: vmess
  country: ðŸ‡©ðŸ‡ªDE
  port: 443
  uuid: 44e57485-eccc-46ef-808f-cd17ac810018
  alterId: 0
  cipher: auto
  network: ws
  servername: node4.rtxconfigz.com
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /@Malinda6104
    headers:
      HOST: node4.rtxconfigz.com
- name: ðŸ‡±ðŸ‡¹LT_412
  server: 45.87.175.166
  type: ss
  country: ðŸ‡±ðŸ‡¹LT
  port: 443
  password: 1RWwXhwfAB5gAEozU4G2Pg
  cipher: chacha20-ietf-poly1305
- name: disney_US
  server: 193.124.24.247
  type: vmess
  country: ðŸ‡ºðŸ‡¸US
  port: 6505
  uuid: b34732f9-2856-4974-8bae-1351928e347f
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_US
  server: 193.124.24.247
  type: vmess
  country: ðŸ‡ºðŸ‡¸US
  port: 6502
  uuid: 242f22a3-29d9-4a94-d8ba-88043f2e1921
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_ðŸ‡¯ðŸ‡µJP-ðŸ‡¯ðŸ‡µJP_411
  server: 160.16.144.208
  type: trojan
  country: ðŸ‡¯ðŸ‡µJP
  port: 3093
  udp: true
  password: 2cf6d686799e6fa95316394064f26c0a
  sni: www.nintendogames.net
  skip-cert-verify: true
- name: disney_US
  server: 193.124.24.247
  type: vmess
  country: ðŸ‡ºðŸ‡¸US
  port: 6510
  uuid: 8f44f672-e53b-44fb-b502-c886d37107b5
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_US
  server: 193.124.24.247
  type: vmess
  country: ðŸ‡ºðŸ‡¸US
  port: 6504
  uuid: 7ceb165c-9aff-4ab7-ce9e-1df31a5ed911
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_NL
  server: 93.183.91.172
  type: ss
  country: ðŸ‡³ðŸ‡±NL
  port: 6462
  password: 741kWqe81Pp8YTsXxter6g
  cipher: chacha20-ietf-poly1305
- name: disney_US
  server: 193.124.24.247
  type: vmess
  country: ðŸ‡ºðŸ‡¸US
  port: 6513
  uuid: 5cf7fcbc-e2c1-42c4-d0d7-79c45a7d588d
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_US
  server: 193.124.24.247
  type: vmess
  country: ðŸ‡ºðŸ‡¸US
  port: 6512
  uuid: 729bfa51-095c-4f50-a1e0-2dfc90d51ebd
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ðŸ‡·ðŸ‡ºRU_415
  server: 5.129.214.186
  type: ss
  country: ðŸ‡·ðŸ‡ºRU
  port: 6403
  password: HWNsKy61qPyoDtrEYEtZuk
  cipher: chacha20-ietf-poly1305
- name: Relay_ðŸZZ-ðŸ‡¯ðŸ‡µJP_428
  server: t1.620720.xyz
  type: vmess
  country: ðŸZZ
  port: 8443
  uuid: 516d8a7a-3f0b-41d3-bad0-246116381516
  alterId: 0
  cipher: auto
  network: ws
  servername: t1.620720.xyz
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /
    headers:
      HOST: t1.620720.xyz
- name: Relay_ðŸZZ-ðŸ‡¦ðŸ‡ºAU_429
  server: sy4.620720.xyz
  type: vmess
  country: ðŸZZ
  port: 443
  uuid: 516d8a7a-3f0b-41d3-bad0-246116381516
  alterId: 0
  cipher: auto
  network: ws
  servername: sy4.620720.xyz
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /
    headers:
      HOST: sy4.620720.xyz
- name: netflix_SE
  server: 78.40.116.178
  type: ss
  country: ðŸ‡¸ðŸ‡ªSE
  port: 34094
  password: yo6h9qkhwz8UJoTZCRtoSi
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_US
  server: 193.124.24.247
  type: vmess
  country: ðŸ‡ºðŸ‡¸US
  port: 6508
  uuid: b68fead5-5b0b-43a1-c34a-804467f0f368
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ðŸ‡ºðŸ‡¸US_422
  server: xyst5w.teeoomboom.de
  type: vmess
  country: ðŸ‡ºðŸ‡¸US
  port: 443
  uuid: 03fcc618-b93d-6796-6aed-8a38c975d581
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /video/g5petez.m3u8
- name: disney_TR
  server: 185.39.204.189
  type: ss
  country: ðŸ‡·ðŸ‡ºRU
  port: 34085
  password: depjSbjv2Uql6W4Vge7sDf
  cipher: chacha20-ietf-poly1305
- name: disney_US
  server: cf.fovi.tk
  type: vmess
  country: ðŸ‡ºðŸ‡¸US
  port: 443
  uuid: bf67437e-6c90-45ca-abc2-c7240a5ce2aa
  alterId: 0
  cipher: auto
  network: ws
  servername: foxpol.fovi.tk
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /eisasqa
    headers:
      HOST: foxpol.fovi.tk
- name: ðŸ‡ºðŸ‡¸US_426
  server: 45.136.12.37
  type: vmess
  country: ðŸ‡ºðŸ‡¸US
  port: 38141
  uuid: fd291be6-b48d-43a1-da38-66c7f80e2f80
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_GB
  server: freeyx.cloudflare88.eu.org
  type: trojan
  port: 443
  udp: true
  password: '0'
  alpn:
  - http%2F1.1
  sni: c03237cb.ba73fe85.netlib.re
  skip-cert-verify: true
  ws-opts:
    path: /
    headers:
      Host: c03237cb.ba73fe85.netlib.re
  network: ws
proxy-groups:
- name: ðŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - _350
  - _351
  - disney_NL
  - _352
  - _359
  - _358
  - Relay_-ðŸ‡ºðŸ‡¸US_357
  - Relay_-ðŸ‡ºðŸ‡¸US_349
  - Relay_-ðŸ‡ºðŸ‡¸US_355
  - disney_netflix_US
  - disney_netflix_US
  - _360
  - _361
  - Relay_-ðŸ‡³ðŸ‡±NL_364
  - _363
  - _362
  - _367
  - _366
  - disney_MD
  - _365
  - _374
  - _371
  - Relay_-ðŸ‡ºðŸ‡¸US_372
  - Relay_-ðŸ‡ºðŸ‡¸US_368
  - Relay_-ðŸ‡ºðŸ‡¸US_369
  - Relay_-ðŸ‡ºðŸ‡¸US_378
  - disney_RU
  - netflix_DE
  - Relay_-ðŸ‡­ðŸ‡°HK_376
  - Relay_-ðŸ‡³ðŸ‡±NL_379
  - Relay_-ðŸ‡¯ðŸ‡µJP_380
  - Relay_-ðŸ‡·ðŸ‡ºRU_375
  - disney_netflix_GB
  - disney_GB
  - disney_RU
  - Relay_-ðŸ‡¸ðŸ‡¬SG_383
  - Relay_-ðŸ‡³ðŸ‡±NL_386
  - disney_FR
  - Relay_-ðŸ‡¯ðŸ‡µJP_390
  - disney_HK
  - disney_HK
  - _393
  - disney_GB
  - disney_SG
  - Relay_-ðŸ‡ºðŸ‡¸US_389
  - disney_HK
  - Relay_-ðŸ‡¯ðŸ‡µJP_398
  - disney_HK
  - Relay_-ðŸ‡³ðŸ‡±NL_399
  - disney_HK
  - disney_NL
  - disney_FR
  - ðŸ‡¬ðŸ‡§GB_404
  - Relay_ðŸ‡¬ðŸ‡§GB-ðŸ‡³ðŸ‡±NL_405
  - disney_HK
  - ðŸ‡¬ðŸ‡§GB_406
  - ðŸ‡¬ðŸ‡§GB_407
  - ðŸ‡¬ðŸ‡§GB_408
  - disney_netflix_NL
  - disney_NL
  - Relay_-ðŸ‡ºðŸ‡¸US_377
  - ðŸ‡²ðŸ‡½MX_413
  - Relay_ðŸ‡©ðŸ‡ªDE-ðŸ‡©ðŸ‡ªDE_402
  - ðŸ‡±ðŸ‡¹LT_412
  - disney_US
  - disney_US
  - Relay_ðŸ‡¯ðŸ‡µJP-ðŸ‡¯ðŸ‡µJP_411
  - disney_US
  - disney_US
  - disney_netflix_NL
  - disney_US
  - disney_US
  - ðŸ‡·ðŸ‡ºRU_415
  - Relay_ðŸZZ-ðŸ‡¯ðŸ‡µJP_428
  - Relay_ðŸZZ-ðŸ‡¦ðŸ‡ºAU_429
  - netflix_SE
  - disney_netflix_US
  - ðŸ‡ºðŸ‡¸US_422
  - disney_TR
  - disney_US
  - ðŸ‡ºðŸ‡¸US_426
  - disney_GB
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - _350
  - _351
  - disney_NL
  - _352
  - _359
  - _358
  - Relay_-ðŸ‡ºðŸ‡¸US_357
  - Relay_-ðŸ‡ºðŸ‡¸US_349
  - Relay_-ðŸ‡ºðŸ‡¸US_355
  - disney_netflix_US
  - disney_netflix_US
  - _360
  - _361
  - Relay_-ðŸ‡³ðŸ‡±NL_364
  - _363
  - _362
  - _367
  - _366
  - disney_MD
  - _365
  - _374
  - _371
  - Relay_-ðŸ‡ºðŸ‡¸US_372
  - Relay_-ðŸ‡ºðŸ‡¸US_368
  - Relay_-ðŸ‡ºðŸ‡¸US_369
  - Relay_-ðŸ‡ºðŸ‡¸US_378
  - disney_RU
  - netflix_DE
  - Relay_-ðŸ‡­ðŸ‡°HK_376
  - Relay_-ðŸ‡³ðŸ‡±NL_379
  - Relay_-ðŸ‡¯ðŸ‡µJP_380
  - Relay_-ðŸ‡·ðŸ‡ºRU_375
  - disney_netflix_GB
  - disney_GB
  - disney_RU
  - Relay_-ðŸ‡¸ðŸ‡¬SG_383
  - Relay_-ðŸ‡³ðŸ‡±NL_386
  - disney_FR
  - Relay_-ðŸ‡¯ðŸ‡µJP_390
  - disney_HK
  - disney_HK
  - _393
  - disney_GB
  - disney_SG
  - Relay_-ðŸ‡ºðŸ‡¸US_389
  - disney_HK
  - Relay_-ðŸ‡¯ðŸ‡µJP_398
  - disney_HK
  - Relay_-ðŸ‡³ðŸ‡±NL_399
  - disney_HK
  - disney_NL
  - disney_FR
  - ðŸ‡¬ðŸ‡§GB_404
  - Relay_ðŸ‡¬ðŸ‡§GB-ðŸ‡³ðŸ‡±NL_405
  - disney_HK
  - ðŸ‡¬ðŸ‡§GB_406
  - ðŸ‡¬ðŸ‡§GB_407
  - ðŸ‡¬ðŸ‡§GB_408
  - disney_netflix_NL
  - disney_NL
  - Relay_-ðŸ‡ºðŸ‡¸US_377
  - ðŸ‡²ðŸ‡½MX_413
  - Relay_ðŸ‡©ðŸ‡ªDE-ðŸ‡©ðŸ‡ªDE_402
  - ðŸ‡±ðŸ‡¹LT_412
  - disney_US
  - disney_US
  - Relay_ðŸ‡¯ðŸ‡µJP-ðŸ‡¯ðŸ‡µJP_411
  - disney_US
  - disney_US
  - disney_netflix_NL
  - disney_US
  - disney_US
  - ðŸ‡·ðŸ‡ºRU_415
  - Relay_ðŸZZ-ðŸ‡¯ðŸ‡µJP_428
  - Relay_ðŸZZ-ðŸ‡¦ðŸ‡ºAU_429
  - netflix_SE
  - disney_netflix_US
  - ðŸ‡ºðŸ‡¸US_422
  - disney_TR
  - disney_US
  - ðŸ‡ºðŸ‡¸US_426
  - disney_GB
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ðŸš€ èŠ‚ç‚¹é€‰æ‹©
