port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: disney_netflix_US |43.55Mb
  server: 88.210.36.108
  type: ss
  port: 2377
  udp: true
  password: t0srmdxrm3xyjnvqz9ewlxb2myq7rjuv
  cipher: chacha20-ietf-poly1305
  plugin: obfs
  plugin-opts:
    host: (TG @WangCai2)e7b7ab7:102816
    mode: tls
- name: disney_netflix_US |43.51Mb
  server: 88.210.36.107
  type: ss
  port: 2377
  udp: true
  password: t0srmdxrm3xyjnvqz9ewlxb2myq7rjuv
  cipher: chacha20-ietf-poly1305
  plugin: obfs
  plugin-opts:
    host: (TG @WangCai2)e7b7ab7:102816
    mode: tls
- name: disney_netflix_US |43.33Mb
  server: 88.210.36.109
  type: ss
  port: 2377
  udp: true
  password: t0srmdxrm3xyjnvqz9ewlxb2myq7rjuv
  cipher: chacha20-ietf-poly1305
  plugin: obfs
  plugin-opts:
    host: (TG @WangCai2)e7b7ab7:102816
    mode: tls
- name: disney_netflix_US |43.50Mb
  server: 88.210.36.106
  type: ss
  port: 2377
  udp: true
  password: t0srmdxrm3xyjnvqz9ewlxb2myq7rjuv
  cipher: chacha20-ietf-poly1305
  plugin: obfs
  plugin-opts:
    host: (TG @WangCai2)e7b7ab7:102816
    mode: tls
- name: netflix_NL |222.44Mb
  server: 185.82.73.212
  type: ss
  port: 8444
  udp: true
  password: _bypfvq6ra7g4n5yCCR9DoVeGya2XUUS
  cipher: chacha20-ietf-poly1305
- name: netflix_NL |152.05Mb
  server: 82.38.31.179
  type: ss
  port: 8080
  udp: true
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_DE |209.16Mb
  server: 45.80.188.48
  type: vmess
  port: 50255
  uuid: bc140c02-25a9-4feb-96bb-7d772b17fd17
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
- name: netflix_NL |61.97Mb
  server: 45.14.245.2
  type: ss
  port: 443
  password: 17ZDORWIliQHuO6WRGHChXYMzdRtAYVP
  cipher: chacha20-ietf-poly1305
- name: _125 |293.86Mb
  server: 185.153.197.5
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: _136 |10.73Mb
  server: 160.16.116.227
  type: trojan
  port: 2760
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
  skip-cert-verify: true
- name: ğŸ‡²ğŸ‡½MX_155 |243.74Mb
  server: 216.238.87.47
  type: vmess
  country: ğŸ‡²ğŸ‡½MX
  port: 27502
  uuid: b8155ce4-7e08-4c40-800f-8671312b7124
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: netflix_JP |10.22Mb
  server: 160.16.87.174
  type: trojan
  port: 3169
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: disney_netflix_US |52.65Mb
  server: 202.181.103.246
  type: trojan
  port: 4054
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: disney_netflix_US |33.40Mb
  server: 160.16.57.238
  type: trojan
  port: 4054
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: ğŸ‡ºğŸ‡¸US_159 |42.82Mb
  server: 47.253.197.26
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 12056
  uuid: dd7be7f1-38ff-45e6-f1e5-b20c2190f527
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_US |74.28Mb
  server: 69.164.240.83
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 10878
  password: t6d26id0pjzdo3x5wtlf
  cipher: aes-128-gcm
- name: disney_netflix_US |14.80Mb
  server: 205.209.109.194
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 17277
  password: d2fkgzsdu5sturjs8f19
  cipher: aes-128-gcm
- name: disney_netflix_US |73.89Mb
  server: 69.164.240.86
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 10880
  password: 3px0wmx0e81145g568ga
  cipher: aes-128-gcm
- name: Relay_-ğŸ‡¸ğŸ‡¬SG_143 |11.21Mb
  server: 160.16.196.59
  type: trojan
  port: 1507
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: _145 |13.91Mb
  server: 153.121.45.139
  type: trojan
  port: 3093
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: _149 |10.97Mb
  server: 160.16.131.243
  type: trojan
  port: 2760
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
  skip-cert-verify: true
- name: disney_HK |28.47Mb
  server: 112.118.116.178
  type: trojan
  port: 443
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: disney_netflix_US |39.34Mb
  server: 38.14.99.163
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 59807
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: auto
  network: tcp
  servername: 38.14.99.163
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡­ğŸ‡°HK_153 |113.15Mb
  server: 8.218.116.26
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 32228
  uuid: e4767e9f-ed00-4f31-a984-a918bdd9b09c
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡­ğŸ‡°HK_154 |111.71Mb
  server: 8.218.105.196
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 52752
  uuid: 925bdbf5-72be-4437-bebf-441c61089f6b
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_US |15.31Mb
  server: cf.fovi.tk
  type: vmess
  country: ğŸZZ
  port: 443
  uuid: bf67437e-6c90-45ca-abc2-c7240a5ce2aa
  alterId: 0
  cipher: auto
  network: ws
  servername: foxlux.fovi.tk
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /eisasqa
    headers:
      HOST: foxlux.fovi.tk
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - disney_netflix_US |43.55Mb
  - disney_netflix_US |43.51Mb
  - disney_netflix_US |43.33Mb
  - disney_netflix_US |43.50Mb
  - netflix_NL |222.44Mb
  - netflix_NL |152.05Mb
  - disney_netflix_DE |209.16Mb
  - netflix_NL |61.97Mb
  - _125 |293.86Mb
  - _136 |10.73Mb
  - ğŸ‡²ğŸ‡½MX_155 |243.74Mb
  - netflix_JP |10.22Mb
  - disney_netflix_US |52.65Mb
  - disney_netflix_US |33.40Mb
  - ğŸ‡ºğŸ‡¸US_159 |42.82Mb
  - disney_netflix_US |74.28Mb
  - disney_netflix_US |14.80Mb
  - disney_netflix_US |73.89Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_143 |11.21Mb
  - _145 |13.91Mb
  - _149 |10.97Mb
  - disney_HK |28.47Mb
  - disney_netflix_US |39.34Mb
  - ğŸ‡­ğŸ‡°HK_153 |113.15Mb
  - ğŸ‡­ğŸ‡°HK_154 |111.71Mb
  - disney_netflix_US |15.31Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - disney_netflix_US |43.55Mb
  - disney_netflix_US |43.51Mb
  - disney_netflix_US |43.33Mb
  - disney_netflix_US |43.50Mb
  - netflix_NL |222.44Mb
  - netflix_NL |152.05Mb
  - disney_netflix_DE |209.16Mb
  - netflix_NL |61.97Mb
  - _125 |293.86Mb
  - _136 |10.73Mb
  - ğŸ‡²ğŸ‡½MX_155 |243.74Mb
  - netflix_JP |10.22Mb
  - disney_netflix_US |52.65Mb
  - disney_netflix_US |33.40Mb
  - ğŸ‡ºğŸ‡¸US_159 |42.82Mb
  - disney_netflix_US |74.28Mb
  - disney_netflix_US |14.80Mb
  - disney_netflix_US |73.89Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_143 |11.21Mb
  - _145 |13.91Mb
  - _149 |10.97Mb
  - disney_HK |28.47Mb
  - disney_netflix_US |39.34Mb
  - ğŸ‡­ğŸ‡°HK_153 |113.15Mb
  - ğŸ‡­ğŸ‡°HK_154 |111.71Mb
  - disney_netflix_US |15.31Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
