port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: _281 |26.63Mb
  server: 137.184.174.93
  type: ss
  port: 8080
  udp: true
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: _297 |186.39Mb
  server: 18.203.224.78
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: _285 |24.24Mb
  server: 45.14.245.2
  type: ss
  port: 443
  udp: true
  password: 17ZDORWIliQHuO6WRGHChXYMzdRtAYVP
  cipher: chacha20-ietf-poly1305
- name: _284 |224.67Mb
  server: 3.65.219.59
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: disney_netflix_DE |118.38Mb
  server: 54.93.101.215
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: _290 |50.71Mb
  server: 63.178.2.18
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: _299 |56.17Mb
  server: 3.72.36.217
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: disney_netflix_DE |202.00Mb
  server: uk2-2.998998.best
  type: vmess
  port: 443
  udp: true
  uuid: 24254866-770c-41b4-9404-3f50524f425b
  alterId: 0
  cipher: auto
  network: ws
  servername: 24254866-770c-41b4-9404-3f50524f425b.placeunaorder.fun
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /logcatxiouerd34try9
    headers:
      Host: 24254866-770c-41b4-9404-3f50524f425b.placeunaorder.fun
- name: _292 |10.05Mb
  server: 213.159.66.206
  type: ss
  port: 443
  udp: true
  password: pl2XtR0pzwknQOGwewbwXtPYDw1zn9Vu
  cipher: chacha20-ietf-poly1305
- name: _305 |31.20Mb
  server: 23.95.72.81
  type: ss
  port: 443
  udp: true
  password: UAMVtHm54uahd6SiN5WcD16rsPSdabPG
  cipher: chacha20-ietf-poly1305
- name: Relay_-ğŸ‡ºğŸ‡¸US_306 |13.71Mb
  server: 38.14.99.163
  type: vmess
  port: 59807
  udp: true
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 64
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: netflix_US |240.57Mb
  server: 82.198.246.97
  type: vmess
  port: 180
  uuid: d13fc2f5-3e05-4795-81eb-44143a09e552
  alterId: 0
  cipher: auto
  network: tcp
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_-ğŸ‡¯ğŸ‡µJP_324 |24.74Mb
  server: 141.193.213.60
  type: trojan
  port: 443
  udp: true
  password: 8b45d379-702f-41b3-a6b2-9c87a01dcd5c
  sni: a3t5vfl95f4d5d9y.catimecsgo.xyz
  skip-cert-verify: true
  ws-opts:
    path: /images
    headers:
      Host: a3t5vfl95f4d5d9y.catimecsgo.xyz
  network: ws
- name: Relay_-ğŸ‡¸ğŸ‡¬SG_327 |14.21Mb
  server: 104.18.1.196
  type: trojan
  port: 443
  udp: true
  password: a9570330-769d-11ef-90dc-1577c1651679
  sni: sg-trojan.andfree.my.id
  skip-cert-verify: true
  ws-opts:
    path: /welcome
    headers:
      Host: sg-trojan.andfree.my.id
  network: ws
- name: _304 |57.41Mb
  server: 185.156.110.92
  type: ss
  port: 443
  udp: true
  password: gXOXk2FJwsz9P6nXIICuDNOqF9gWX1dn
  cipher: chacha20-ietf-poly1305
- name: Relay_-ğŸ‡ºğŸ‡¸US_310 |14.47Mb
  server: 38.14.99.179
  type: vmess
  port: 59807
  udp: true
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 64
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_-ğŸ‡ºğŸ‡¸US_333 |46.03Mb
  server: usiys.southbyte.xyz
  type: trojan
  port: 5897
  udp: true
  password: fg20mtCFHy
  sni: usiys.southbyte.xyz
  skip-cert-verify: true
- name: Relay_-ğŸ‡¯ğŸ‡µJP_317 |87.01Mb
  server: 153.121.44.99
  type: trojan
  port: 3093
  password: 2cf6d686799e6fa95316394064f26c0a
  sni: www.nintendogames.net
- name: ğŸ‡§ğŸ‡·BR_350 |21.27Mb
  server: 38.180.16.86
  type: vmess
  country: ğŸ‡§ğŸ‡·BR
  port: 36236
  uuid: a58bc1a5-8c18-49ff-9453-c331b52f45dc
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡§ğŸ‡·BR_351 |24.04Mb
  server: 38.180.16.86
  type: vmess
  country: ğŸ‡§ğŸ‡·BR
  port: 36104
  uuid: E146A8CB-9D2F-449C-ADCA-8736FB
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_-ğŸ‡³ğŸ‡±NL_334 |21.89Mb
  server: 202.181.103.235
  type: trojan
  port: 2760
  password: 2cf6d686799e6fa95316394064f26c0a
  sni: www.nintendogames.net
- name: _318 |107.46Mb
  server: 47.242.225.242
  type: trojan
  port: 443
  udp: true
  password: 92690597d6298061459918a371e8d77d
  sni: hezijiasuqi.com
  skip-cert-verify: true
- name: Relay_-ğŸ‡­ğŸ‡°HK_309 |21.64Mb
  server: www.zhoubowen.vip
  type: vmess
  port: 443
  udp: true
  uuid: 71b2655e-07d9-4dad-a770-a2b08275142b
  alterId: 0
  cipher: auto
  network: ws
  servername: www.zhoubowen.vip
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /biutefor.icu
    headers:
      Host: www.zhoubowen.vip
- name: ğŸ‡©ğŸ‡ªDE_353 |171.14Mb
  server: 18.184.12.56
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: disney_JP |11.30Mb
  server: gd.bjnet2.com
  type: ss
  port: 36609
  udp: true
  password: 84d85af8-2807-4306-a701-f784676b77c3
  cipher: aes-128-gcm
  plugin: obfs
  plugin-opts:
    host: de5bdbffa87896a4b126f8b62150bb4e.baidu.com
    mode: http
- name: disney_US |35.58Mb
  server: gd.bjnet2.com
  type: ss
  port: 36608
  udp: true
  password: 84d85af8-2807-4306-a701-f784676b77c3
  cipher: aes-128-gcm
  plugin: obfs
  plugin-opts:
    host: de5bdbffa87896a4b126f8b62150bb4e.baidu.com
    mode: http
- name: disney_TW |28.78Mb
  server: gd.bjnet2.com
  type: ss
  port: 36603
  udp: true
  password: 84d85af8-2807-4306-a701-f784676b77c3
  cipher: aes-128-gcm
  plugin: obfs
  plugin-opts:
    host: de5bdbffa87896a4b126f8b62150bb4e.baidu.com
    mode: http
- name: netflix_US |63.24Mb
  server: 107.23.148.46
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡©ğŸ‡ªDE_354 |247.60Mb
  server: 54.93.211.165
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: Relay_ğŸ‡¬ğŸ‡§GB-ğŸ‡³ğŸ‡±NL_359 |244.94Mb
  server: 82.38.31.210
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_NL |244.75Mb
  server: 82.38.31.217
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_361 |232.55Mb
  server: 82.38.31.194
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡²ğŸ‡½MX_370 |248.33Mb
  server: 216.238.89.53
  type: vmess
  country: ğŸ‡²ğŸ‡½MX
  port: 57283
  uuid: 1a5aafc0-6482-451d-fe76-6875b7818579
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_NL |182.42Mb
  server: 82.38.31.191
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_373 |38.46Mb
  server: 216.167.107.61
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 44805
  uuid: f7d62526-9e06-455e-82bd-241d368002e8
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_TR |13.00Mb
  server: 185.39.204.189
  type: ss
  country: ğŸ‡·ğŸ‡ºRU
  port: 34085
  password: depjSbjv2Uql6W4Vge7sDf
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸ‡©ğŸ‡ªDE-ğŸ‡©ğŸ‡ªDE_355 |75.45Mb
  server: node4.rtxconfigz.com
  type: vmess
  country: ğŸ‡©ğŸ‡ªDE
  port: 443
  uuid: 44e57485-eccc-46ef-808f-cd17ac810018
  alterId: 0
  cipher: auto
  network: ws
  servername: node4.rtxconfigz.com
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /@Malinda6104
    headers:
      HOST: node4.rtxconfigz.com
- name: Relay_ğŸ‡°ğŸ‡·KR-ğŸ‡°ğŸ‡·KR_369 |10.00Mb
  server: seoul02.zgjok.com
  type: vmess
  country: ğŸ‡°ğŸ‡·KR
  port: 443
  uuid: 1a1e5196-eab4-4772-9012-65c27f19a524
  alterId: 0
  cipher: auto
  network: ws
  servername: seoul02.zgjok.com
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /
    headers:
      HOST: seoul02.zgjok.com
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - _281 |26.63Mb
  - _297 |186.39Mb
  - _285 |24.24Mb
  - _284 |224.67Mb
  - disney_netflix_DE |118.38Mb
  - _290 |50.71Mb
  - _299 |56.17Mb
  - disney_netflix_DE |202.00Mb
  - _292 |10.05Mb
  - _305 |31.20Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_306 |13.71Mb
  - netflix_US |240.57Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_324 |24.74Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_327 |14.21Mb
  - _304 |57.41Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_310 |14.47Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_333 |46.03Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_317 |87.01Mb
  - ğŸ‡§ğŸ‡·BR_350 |21.27Mb
  - ğŸ‡§ğŸ‡·BR_351 |24.04Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_334 |21.89Mb
  - _318 |107.46Mb
  - Relay_-ğŸ‡­ğŸ‡°HK_309 |21.64Mb
  - ğŸ‡©ğŸ‡ªDE_353 |171.14Mb
  - disney_JP |11.30Mb
  - disney_US |35.58Mb
  - disney_TW |28.78Mb
  - netflix_US |63.24Mb
  - ğŸ‡©ğŸ‡ªDE_354 |247.60Mb
  - Relay_ğŸ‡¬ğŸ‡§GB-ğŸ‡³ğŸ‡±NL_359 |244.94Mb
  - disney_netflix_NL |244.75Mb
  - ğŸ‡¬ğŸ‡§GB_361 |232.55Mb
  - ğŸ‡²ğŸ‡½MX_370 |248.33Mb
  - disney_netflix_NL |182.42Mb
  - ğŸ‡ºğŸ‡¸US_373 |38.46Mb
  - disney_TR |13.00Mb
  - Relay_ğŸ‡©ğŸ‡ªDE-ğŸ‡©ğŸ‡ªDE_355 |75.45Mb
  - Relay_ğŸ‡°ğŸ‡·KR-ğŸ‡°ğŸ‡·KR_369 |10.00Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - _281 |26.63Mb
  - _297 |186.39Mb
  - _285 |24.24Mb
  - _284 |224.67Mb
  - disney_netflix_DE |118.38Mb
  - _290 |50.71Mb
  - _299 |56.17Mb
  - disney_netflix_DE |202.00Mb
  - _292 |10.05Mb
  - _305 |31.20Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_306 |13.71Mb
  - netflix_US |240.57Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_324 |24.74Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_327 |14.21Mb
  - _304 |57.41Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_310 |14.47Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_333 |46.03Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_317 |87.01Mb
  - ğŸ‡§ğŸ‡·BR_350 |21.27Mb
  - ğŸ‡§ğŸ‡·BR_351 |24.04Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_334 |21.89Mb
  - _318 |107.46Mb
  - Relay_-ğŸ‡­ğŸ‡°HK_309 |21.64Mb
  - ğŸ‡©ğŸ‡ªDE_353 |171.14Mb
  - disney_JP |11.30Mb
  - disney_US |35.58Mb
  - disney_TW |28.78Mb
  - netflix_US |63.24Mb
  - ğŸ‡©ğŸ‡ªDE_354 |247.60Mb
  - Relay_ğŸ‡¬ğŸ‡§GB-ğŸ‡³ğŸ‡±NL_359 |244.94Mb
  - disney_netflix_NL |244.75Mb
  - ğŸ‡¬ğŸ‡§GB_361 |232.55Mb
  - ğŸ‡²ğŸ‡½MX_370 |248.33Mb
  - disney_netflix_NL |182.42Mb
  - ğŸ‡ºğŸ‡¸US_373 |38.46Mb
  - disney_TR |13.00Mb
  - Relay_ğŸ‡©ğŸ‡ªDE-ğŸ‡©ğŸ‡ªDE_355 |75.45Mb
  - Relay_ğŸ‡°ğŸ‡·KR-ğŸ‡°ğŸ‡·KR_369 |10.00Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
