port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: ' |69.77Mb'
  server: 79.127.200.169
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ' |24.35Mb'
  server: 196.196.192.58
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ' |221.98Mb'
  server: 45.14.245.2
  type: ss
  port: 443
  password: 17ZDORWIliQHuO6WRGHChXYMzdRtAYVP
  cipher: chacha20-ietf-poly1305
- name: ' |155.55Mb'
  server: 82.38.31.176
  type: ss
  port: 8080
  udp: true
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ' |83.93Mb'
  server: 51.15.23.166
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ' |21.52Mb'
  server: 145.249.109.121
  type: ss
  port: 25512
  udp: true
  password: smSMfR9jqLgMkHuQtxSIWh
  cipher: chacha20-ietf-poly1305
- name: ' |67.12Mb'
  server: 79.127.200.162
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ' |52.16Mb'
  server: 95.164.116.33
  type: ss
  port: 443
  password: pQmnC03JObbPhdh5FBJHgD6jnTLchsRA
  cipher: chacha20-ietf-poly1305
- name: ' |37.55Mb'
  server: 62.100.205.100
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ' |22.26Mb'
  server: 128.199.172.224
  type: ss
  port: 8080
  udp: true
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: ' |169.03Mb'
  server: 82.38.31.214
  type: ss
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ' |22.45Mb'
  server: 149.22.87.241
  type: ss
  port: 443
  udp: true
  password: shadowsocks
  cipher: aes-128-gcm
- name: ' |41.76Mb'
  server: 103.97.203.227
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ' |45.18Mb'
  server: 173.244.56.6
  type: ss
  port: 443
  udp: true
  password: shadowsocks
  cipher: aes-128-gcm
- name: ' |55.82Mb'
  server: 89.221.225.15
  type: ss
  port: 443
  udp: true
  password: yCbQ4bry4otfifK7oel71NaXpPL9pYJb
  cipher: chacha20-ietf-poly1305
- name: ' |11.25Mb'
  server: 38.89.142.56
  type: ss
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ' |207.33Mb'
  server: 151.242.251.152
  type: ss
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ' |13.58Mb'
  server: 192.71.249.78
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ' |19.27Mb'
  server: 185.192.124.188
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ' |31.90Mb'
  server: 119.59.98.58
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ' |174.30Mb'
  server: 151.242.251.142
  type: ss
  port: 8080
  udp: true
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ' |30.63Mb'
  server: 156.146.38.167
  type: ss
  port: 443
  udp: true
  password: shadowsocks
  cipher: aes-128-gcm
- name: ' |32.52Mb'
  server: 156.146.38.169
  type: ss
  port: 443
  udp: true
  password: shadowsocks
  cipher: aes-128-gcm
- name: ' |223.84Mb'
  server: 151.242.251.147
  type: ss
  port: 8080
  password: QCXDxuDlTTMD7jtgHUjIoj
  cipher: chacha20-ietf-poly1305
- name: ' |73.87Mb'
  server: 103.35.189.136
  type: ss
  port: 443
  udp: true
  password: SS2QvbC9nqLp2sXXZo0BVy4slcErRuCt
  cipher: chacha20-ietf-poly1305
- name: ' |50.00Mb'
  server: 156.146.38.170
  type: ss
  port: 443
  udp: true
  password: shadowsocks
  cipher: aes-128-gcm
- name: ' |44.47Mb'
  server: 147.78.0.182
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ' |22.44Mb'
  server: 172.105.199.111
  type: ss
  port: 8080
  udp: true
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: ' |14.70Mb'
  server: 193.135.174.135
  type: ss
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ' |136.13Mb'
  server: 185.82.73.212
  type: ss
  port: 8444
  udp: true
  password: _bypfvq6ra7g4n5yCCR9DoVeGya2XUUS
  cipher: chacha20-ietf-poly1305
- name: ' |198.58Mb'
  server: 82.38.31.194
  type: ss
  port: 8080
  udp: true
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ' |40.10Mb'
  server: 156.59.243.6
  type: ss
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ' |151.42Mb'
  server: 38.165.233.93
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ' |226.21Mb'
  server: 82.38.31.179
  type: ss
  port: 8080
  udp: true
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ' |175.86Mb'
  server: 82.198.246.97
  type: vmess
  port: 180
  uuid: d13fc2f5-3e05-4795-81eb-44143a09e552
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: ' |144.05Mb'
  server: backup.fleetfoxi.link
  type: ss
  port: 44884
  udp: true
  password: 2DGq3jvVRg5n3CcxmysGK2kmrgJeSNof12A76cZvVxqPpetyC1XEciCFufq5xKvRWGGnKVembpThuUSQhbZ7GMsZY4UVxEBw
  cipher: chacha20-ietf-poly1305
- name: ' |29.71Mb'
  server: 38.165.231.25
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ' |305.98Mb'
  server: 172.233.229.91
  type: vmess
  port: 14102
  udp: true
  uuid: 27ba87fc-583f-4763-9060-83cf0b9264db
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ' |192.07Mb'
  server: h110vpnnl.outlinekeys.net
  type: ss
  port: 52571
  udp: true
  password: b0TKxnHAYeeFYyzTAMXn0F
  cipher: chacha20-ietf-poly1305
- name: ' |12.35Mb'
  server: 103.149.183.200
  type: ss
  port: 8388
  udp: true
  password: asd123456
  cipher: chacha20-ietf
- name: ' |23.09Mb'
  server: 194.246.114.101
  type: ss
  port: 443
  udp: true
  password: HaNqw9pIE4jcx98sg7UQgHeGNTM4R2pk
  cipher: chacha20-ietf-poly1305
- name: ' |59.76Mb'
  server: 156.233.232.192
  type: vmess
  port: 24004
  uuid: 582fcb35-20a0-452c-e179-4c759c62c494
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
- name: ' |13.84Mb'
  server: 160.16.87.174
  type: trojan
  port: 3169
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: ' |11.02Mb'
  server: 160.16.106.144
  type: trojan
  port: 2760
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
  skip-cert-verify: true
- name: ' |37.94Mb'
  server: 160.16.89.176
  type: trojan
  port: 2890
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: ' |10.94Mb'
  server: 160.16.131.243
  type: trojan
  port: 2760
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
  skip-cert-verify: true
- name: ' |71.80Mb'
  server: 156.233.232.192
  type: vmess
  port: 44329
  uuid: 1ba1fb56-e235-419e-c193-1c291adad4a7
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
- name: ' |71.13Mb'
  server: 156.233.232.177
  type: vmess
  port: 24004
  uuid: 582fcb35-20a0-452c-e179-4c759c62c494
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
- name: ' |17.36Mb'
  server: 193.203.203.66
  type: ss
  country: üá®üá¶CA
  port: 443
  password: S6jUK9Fw5fMHgNqlqXObHZWv8Tf4nEkm
  cipher: chacha20-ietf-poly1305
- name: ' |12.12Mb'
  server: 47.242.225.242
  type: trojan
  port: 443
  udp: true
  password: 92690597d6298061459918a371e8d77d
  sni: hezijiasuqi.com
  skip-cert-verify: true
- name: ' |11.82Mb'
  server: 112.118.116.8
  type: trojan
  port: 443
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: ' |41.91Mb'
  server: 160.16.229.223
  type: trojan
  port: 3169
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: ' |46.27Mb'
  server: 185.213.23.63
  type: ss
  country: üá®üá¶CA
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ' |42.57Mb'
  server: 160.16.204.136
  type: trojan
  port: 2890
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: ' |13.94Mb'
  server: 160.16.136.130
  type: trojan
  port: 2890
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: ' |75.48Mb'
  server: 156.233.232.177
  type: vmess
  port: 44329
  uuid: 1ba1fb56-e235-419e-c193-1c291adad4a7
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
- name: ' |23.15Mb'
  server: 89.163.140.136
  type: ss
  country: üá©üá™DE
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ' |10.30Mb'
  server: 160.16.116.227
  type: trojan
  port: 2760
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
  skip-cert-verify: true
- name: ' |19.33Mb'
  server: 185.192.124.188
  type: ss
  country: üáßüá∑BR
  port: 990
  password: f8f7aCzcPKbsF8p3
  cipher: chacha20-ietf-poly1305
- name: ' |238.60Mb'
  server: 138.124.67.26
  type: ss
  country: üá®üá≠CH
  port: 25572
  password: nqcIfYHlpMn3jzqkNDjKaG
  cipher: chacha20-ietf-poly1305
- name: ' |214.90Mb'
  server: 82.38.31.208
  type: ss
  country: üá¨üáßGB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ' |39.42Mb'
  server: 216.238.87.47
  type: vmess
  country: üá≤üáΩMX
  port: 27502
  uuid: b8155ce4-7e08-4c40-800f-8671312b7124
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ' |180.73Mb'
  server: 45.87.175.183
  type: ss
  country: üá±üáπLT
  port: 8080
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: ' |208.22Mb'
  server: 45.87.175.185
  type: ss
  country: üá±üáπLT
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ' |195.14Mb'
  server: 45.87.175.180
  type: ss
  country: üá±üáπLT
  port: 8080
  password: QCXDxuDlTTMD7jtgHUjIoj
  cipher: chacha20-ietf-poly1305
- name: ' |217.42Mb'
  server: 45.87.175.185
  type: ss
  country: üá±üáπLT
  port: 8080
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: ' |100.87Mb'
  server: 46.183.217.204
  type: ss
  country: üá±üáª LV
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ' |59.09Mb'
  server: 45.150.52.40
  type: vmess
  country: üá∫üá∏US
  port: 443
  uuid: c31777a1-2ee6-4864-db4c-a79fcbc8188b
  alterId: 0
  cipher: auto
  network: ws
  servername: xsj011-3.facai2024.com
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /c31777a1
    headers:
      HOST: xsj011-3.facai2024.com
- name: ' |14.38Mb'
  server: 176.123.5.253
  type: ss
  country: üá≤üá©MD
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ' |112.06Mb'
  server: 104.18.14.55
  type: vmess
  country: üèÅZZ
  port: 2052
  uuid: e6447786-8c85-443c-8017-7feaa673ff45
  alterId: 0
  cipher: auto
  network: ws
  servername: in4.123417.xyz
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
  ws-opts:
    path: /
    headers:
      HOST: in4.123417.xyz
- name: ' |10.00Mb'
  server: 193.29.139.141
  type: ss
  country: üá≥üá±NL
  port: 8080
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: ' |218.56Mb'
  server: 194.87.216.218
  type: ss
  country: üá≥üá±NL
  port: 52571
  password: b0TKxnHAYeeFYyzTAMXn0F
  cipher: chacha20-ietf-poly1305
- name: ' |40.72Mb'
  server: 38.14.99.163
  type: vmess
  country: üá∫üá∏US
  port: 59807
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: auto
  network: tcp
  servername: 38.14.99.163
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ' |10.67Mb'
  server: xray.kk37005.tk
  type: vmess
  country: üáØüáµJP
  port: 55919
  uuid: 2e7548bb-7c5b-4d97-d64d-1b2fe4050089
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: ' |132.50Mb'
  server: 103.97.203.220
  type: vmess
  country: üáÆüá≥IN
  port: 550
  uuid: 9e0e83ca-0fbc-44b1-8024-0eb8f9414156
  alterId: 0
  cipher: auto
  network: tcp
  servername: t.me/v2Line
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ' |42.02Mb'
  server: 185.113.143.186
  type: ss
  country: üáµüáπPT
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ' |107.75Mb'
  server: hgtrojan.zabc.net
  type: vmess
  country: üèÅZZ
  port: 2083
  uuid: e6395c20-4571-4b34-d6b1-55a5d36e49ea
  alterId: 0
  cipher: auto
  network: ws
  servername: hgtrojan.zabc.net
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /e6395c20
    headers:
      HOST: hgtrojan.zabc.net
- name: ' |21.00Mb'
  server: 68.183.227.45
  type: ss
  country: üá∏üá¨SG
  port: 8080
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: ' |137.58Mb'
  server: 185.231.233.112
  type: ss
  country: üèÅ ZZ
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ' |15.13Mb'
  server: 38.54.107.101
  type: ss
  country: üáπüáºTW
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ' |16.79Mb'
  server: cf.fovi.tk
  type: vmess
  country: üèÅZZ
  port: 443
  uuid: bf67437e-6c90-45ca-abc2-c7240a5ce2aa
  alterId: 0
  cipher: auto
  network: ws
  servername: foxlux.fovi.tk
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /eisasqa
    headers:
      HOST: foxlux.fovi.tk
proxy-groups:
- name: üöÄ ËäÇÁÇπÈÄâÊã©
  type: select
  proxies:
  - ‚ôªÔ∏è Ëá™Âä®ÈÄâÊã©
  - ' |69.77Mb'
  - ' |24.35Mb'
  - ' |221.98Mb'
  - ' |155.55Mb'
  - ' |83.93Mb'
  - ' |21.52Mb'
  - ' |67.12Mb'
  - ' |52.16Mb'
  - ' |37.55Mb'
  - ' |22.26Mb'
  - ' |169.03Mb'
  - ' |22.45Mb'
  - ' |41.76Mb'
  - ' |45.18Mb'
  - ' |55.82Mb'
  - ' |11.25Mb'
  - ' |207.33Mb'
  - ' |13.58Mb'
  - ' |19.27Mb'
  - ' |31.90Mb'
  - ' |174.30Mb'
  - ' |30.63Mb'
  - ' |32.52Mb'
  - ' |223.84Mb'
  - ' |73.87Mb'
  - ' |50.00Mb'
  - ' |44.47Mb'
  - ' |22.44Mb'
  - ' |14.70Mb'
  - ' |136.13Mb'
  - ' |198.58Mb'
  - ' |40.10Mb'
  - ' |151.42Mb'
  - ' |226.21Mb'
  - ' |175.86Mb'
  - ' |144.05Mb'
  - ' |29.71Mb'
  - ' |305.98Mb'
  - ' |192.07Mb'
  - ' |12.35Mb'
  - ' |23.09Mb'
  - ' |59.76Mb'
  - ' |13.84Mb'
  - ' |11.02Mb'
  - ' |37.94Mb'
  - ' |10.94Mb'
  - ' |71.80Mb'
  - ' |71.13Mb'
  - ' |17.36Mb'
  - ' |12.12Mb'
  - ' |11.82Mb'
  - ' |41.91Mb'
  - ' |46.27Mb'
  - ' |42.57Mb'
  - ' |13.94Mb'
  - ' |75.48Mb'
  - ' |23.15Mb'
  - ' |10.30Mb'
  - ' |19.33Mb'
  - ' |238.60Mb'
  - ' |214.90Mb'
  - ' |39.42Mb'
  - ' |180.73Mb'
  - ' |208.22Mb'
  - ' |195.14Mb'
  - ' |217.42Mb'
  - ' |100.87Mb'
  - ' |59.09Mb'
  - ' |14.38Mb'
  - ' |112.06Mb'
  - ' |10.00Mb'
  - ' |218.56Mb'
  - ' |40.72Mb'
  - ' |10.67Mb'
  - ' |132.50Mb'
  - ' |42.02Mb'
  - ' |107.75Mb'
  - ' |21.00Mb'
  - ' |137.58Mb'
  - ' |15.13Mb'
  - ' |16.79Mb'
  url: https://www.google.com/generate_204
- name: ‚ôªÔ∏è Ëá™Âä®ÈÄâÊã©
  type: url-test
  proxies:
  - ' |69.77Mb'
  - ' |24.35Mb'
  - ' |221.98Mb'
  - ' |155.55Mb'
  - ' |83.93Mb'
  - ' |21.52Mb'
  - ' |67.12Mb'
  - ' |52.16Mb'
  - ' |37.55Mb'
  - ' |22.26Mb'
  - ' |169.03Mb'
  - ' |22.45Mb'
  - ' |41.76Mb'
  - ' |45.18Mb'
  - ' |55.82Mb'
  - ' |11.25Mb'
  - ' |207.33Mb'
  - ' |13.58Mb'
  - ' |19.27Mb'
  - ' |31.90Mb'
  - ' |174.30Mb'
  - ' |30.63Mb'
  - ' |32.52Mb'
  - ' |223.84Mb'
  - ' |73.87Mb'
  - ' |50.00Mb'
  - ' |44.47Mb'
  - ' |22.44Mb'
  - ' |14.70Mb'
  - ' |136.13Mb'
  - ' |198.58Mb'
  - ' |40.10Mb'
  - ' |151.42Mb'
  - ' |226.21Mb'
  - ' |175.86Mb'
  - ' |144.05Mb'
  - ' |29.71Mb'
  - ' |305.98Mb'
  - ' |192.07Mb'
  - ' |12.35Mb'
  - ' |23.09Mb'
  - ' |59.76Mb'
  - ' |13.84Mb'
  - ' |11.02Mb'
  - ' |37.94Mb'
  - ' |10.94Mb'
  - ' |71.80Mb'
  - ' |71.13Mb'
  - ' |17.36Mb'
  - ' |12.12Mb'
  - ' |11.82Mb'
  - ' |41.91Mb'
  - ' |46.27Mb'
  - ' |42.57Mb'
  - ' |13.94Mb'
  - ' |75.48Mb'
  - ' |23.15Mb'
  - ' |10.30Mb'
  - ' |19.33Mb'
  - ' |238.60Mb'
  - ' |214.90Mb'
  - ' |39.42Mb'
  - ' |180.73Mb'
  - ' |208.22Mb'
  - ' |195.14Mb'
  - ' |217.42Mb'
  - ' |100.87Mb'
  - ' |59.09Mb'
  - ' |14.38Mb'
  - ' |112.06Mb'
  - ' |10.00Mb'
  - ' |218.56Mb'
  - ' |40.72Mb'
  - ' |10.67Mb'
  - ' |132.50Mb'
  - ' |42.02Mb'
  - ' |107.75Mb'
  - ' |21.00Mb'
  - ' |137.58Mb'
  - ' |15.13Mb'
  - ' |16.79Mb'
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,üöÄ ËäÇÁÇπÈÄâÊã©
