port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: ğŸ‡ºğŸ‡¸US_48 |11.80Mb
  server: 173.234.29.2
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_50 |14.32Mb
  server: 18.224.33.22
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡ºğŸ‡¸US_47 |18.39Mb
  server: 3.149.246.131
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡ºğŸ‡¸US_46 |17.65Mb
  server: 3.22.249.200
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡¬ğŸ‡¹GT_34 |10.72Mb
  server: 185.47.254.87
  type: ss
  country: ğŸ‡¬ğŸ‡¹GT
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¹ğŸ‡¼TW_44 |16.02Mb
  server: 154.223.20.79
  type: ss
  country: ğŸ‡¹ğŸ‡¼TW
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: Relay_-ğŸ‡©ğŸ‡ªDE_09 |10.15Mb
  server: 193.135.174.135
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡µğŸ‡¹PT_42 |11.87Mb
  server: 185.113.143.186
  type: ss
  country: ğŸ‡µğŸ‡¹PT
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _15 |25.13Mb
  server: 176.126.83.158
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - ğŸ‡ºğŸ‡¸US_48 |11.80Mb
  - ğŸ‡ºğŸ‡¸US_50 |14.32Mb
  - ğŸ‡ºğŸ‡¸US_47 |18.39Mb
  - ğŸ‡ºğŸ‡¸US_46 |17.65Mb
  - ğŸ‡¬ğŸ‡¹GT_34 |10.72Mb
  - ğŸ‡¹ğŸ‡¼TW_44 |16.02Mb
  - Relay_-ğŸ‡©ğŸ‡ªDE_09 |10.15Mb
  - ğŸ‡µğŸ‡¹PT_42 |11.87Mb
  - _15 |25.13Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - ğŸ‡ºğŸ‡¸US_48 |11.80Mb
  - ğŸ‡ºğŸ‡¸US_50 |14.32Mb
  - ğŸ‡ºğŸ‡¸US_47 |18.39Mb
  - ğŸ‡ºğŸ‡¸US_46 |17.65Mb
  - ğŸ‡¬ğŸ‡¹GT_34 |10.72Mb
  - ğŸ‡¹ğŸ‡¼TW_44 |16.02Mb
  - Relay_-ğŸ‡©ğŸ‡ªDE_09 |10.15Mb
  - ğŸ‡µğŸ‡¹PT_42 |11.87Mb
  - _15 |25.13Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
