port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: disney_netflix_US |18.81Mb
  server: 82.198.246.97
  type: vmess
  port: 180
  uuid: d13fc2f5-3e05-4795-81eb-44143a09e552
  alterId: 0
  cipher: auto
  network: tcp
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_NL |248.26Mb
  server: 151.242.251.137
  type: ss
  port: 8080
  password: o5osZg269v5zHpYjr1xY9s
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_PT |38.94Mb
  server: 185.231.233.112
  type: ss
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: Relay_-ğŸ‡¸ğŸ‡¬SG_368 |11.43Mb
  server: 153.121.51.29
  type: trojan
  port: 127
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡³ğŸ‡±NL_372 |14.17Mb
  server: 160.16.63.16
  type: trojan
  port: 4054
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡³ğŸ‡±NL_369 |11.03Mb
  server: 160.16.124.55
  type: trojan
  port: 4054
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡³ğŸ‡±NL_375 |12.01Mb
  server: 160.16.124.55
  type: trojan
  port: 2760
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡³ğŸ‡±NL_374 |45.83Mb
  server: 160.16.81.84
  type: trojan
  port: 4054
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¯ğŸ‡µJP_371 |19.97Mb
  server: 52.195.176.26
  type: trojan
  port: 2145
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: _313 |17.92Mb
  server: 103.106.3.82
  type: ss
  port: 443
  udp: true
  password: 4SaCIazlgumYkM8FkPzlmwjpyWBDZFBk
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_FR |44.24Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 27092
  uuid: a0596ba6-72a3-4366-8992-77088da65bd8
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_FR |21.59Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 40433
  uuid: d8fd8955-78db-49ba-d86f-3e4729f6ac4d
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_-ğŸ‡³ğŸ‡±NL_377 |17.17Mb
  server: 160.16.236.32
  type: trojan
  port: 4054
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: disney_netflix_NL |11.00Mb
  server: 82.38.31.179
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_384 |152.42Mb
  server: 82.38.31.190
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡§ğŸ‡·BR_379 |20.69Mb
  server: 38.180.16.86
  type: vmess
  country: ğŸ‡§ğŸ‡·BR
  port: 36104
  uuid: E146A8CB-9D2F-449C-ADCA-8736FB
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: _376 |14.19Mb
  server: 58.152.18.95
  type: trojan
  port: 443
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: ğŸ‡²ğŸ‡½MX_395 |40.01Mb
  server: 216.238.89.53
  type: vmess
  country: ğŸ‡²ğŸ‡½MX
  port: 57283
  uuid: 1a5aafc0-6482-451d-fe76-6875b7818579
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡¦ğŸ‡ºAU_378 |11.34Mb
  server: 54.252.240.128
  type: vmess
  country: ğŸ‡¦ğŸ‡ºAU
  port: 1000
  uuid: ca26a9fd-fef8-4ea7-d194-450ce4e0c67a
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_US |20.81Mb
  server: 38.84.201.21
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 53487
  uuid: c3c1ec05-df2c-4975-9b42-e9b007564eb1
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡­ğŸ‡°HK_388 |29.42Mb
  server: 47.243.51.237
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 52801
  uuid: ef93f413-9039-4ddb-aefb-2490287df55a
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
  ws-opts:
    path: /arki?ed=2048
- name: ğŸ‡°ğŸ‡·KR_393 |11.40Mb
  server: 146.56.112.110
  type: vmess
  country: ğŸ‡°ğŸ‡·KR
  port: 8888
  uuid: e7c302f3-90d6-42dd-9d7d-94a3683a3707
  alterId: 0
  cipher: auto
  network: tcp
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡·ğŸ‡ºRU_397 |13.42Mb
  server: 45.139.26.173
  type: ss
  country: ğŸ‡·ğŸ‡ºRU
  port: 57456
  password: d3837224ed465f00
  cipher: chacha20-ietf-poly1305
- name: disney_TR |10.09Mb
  server: 185.39.204.161
  type: ss
  country: ğŸ‡¹ğŸ‡·TR
  port: 33563
  password: bSlgCoGhApOb55tIMD0zxY
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡²ğŸ‡¾MY_396 |31.96Mb
  server: 38.54.98.110
  type: vmess
  country: ğŸ‡²ğŸ‡¾MY
  port: 2052
  uuid: 665d9b8f-153d-4907-adac-de12afd9c851
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: ğŸ‡¸ğŸ‡¬SG_398 |16.10Mb
  server: 68.183.178.131
  type: vmess
  country: ğŸ‡¸ğŸ‡¬SG
  port: 58607
  uuid: c11c32cb-27b3-4afa-c0f3-fb250aa4959e
  alterId: 0
  cipher: auto
  network: ws
  servername: www.12333.monster
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /
    headers:
      HOST: www.12333.monster
- name: ğŸ‡ºğŸ‡¸US_402 |23.75Mb
  server: 45.136.12.37
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 38141
  uuid: fd291be6-b48d-43a1-da38-66c7f80e2f80
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_403 |18.52Mb
  server: cf.fovi.tk
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  uuid: bf67437e-6c90-45ca-abc2-c7240a5ce2aa
  alterId: 0
  cipher: auto
  network: ws
  servername: foxlux.fovi.tk
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /eisasqa
    headers:
      HOST: foxlux.fovi.tk
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - disney_netflix_US |18.81Mb
  - disney_netflix_NL |248.26Mb
  - disney_netflix_PT |38.94Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_368 |11.43Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_372 |14.17Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_369 |11.03Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_375 |12.01Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_374 |45.83Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_371 |19.97Mb
  - _313 |17.92Mb
  - disney_netflix_FR |44.24Mb
  - disney_netflix_FR |21.59Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_377 |17.17Mb
  - disney_netflix_NL |11.00Mb
  - ğŸ‡¬ğŸ‡§GB_384 |152.42Mb
  - ğŸ‡§ğŸ‡·BR_379 |20.69Mb
  - _376 |14.19Mb
  - ğŸ‡²ğŸ‡½MX_395 |40.01Mb
  - ğŸ‡¦ğŸ‡ºAU_378 |11.34Mb
  - disney_netflix_US |20.81Mb
  - ğŸ‡­ğŸ‡°HK_388 |29.42Mb
  - ğŸ‡°ğŸ‡·KR_393 |11.40Mb
  - ğŸ‡·ğŸ‡ºRU_397 |13.42Mb
  - disney_TR |10.09Mb
  - ğŸ‡²ğŸ‡¾MY_396 |31.96Mb
  - ğŸ‡¸ğŸ‡¬SG_398 |16.10Mb
  - ğŸ‡ºğŸ‡¸US_402 |23.75Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_403 |18.52Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - disney_netflix_US |18.81Mb
  - disney_netflix_NL |248.26Mb
  - disney_netflix_PT |38.94Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_368 |11.43Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_372 |14.17Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_369 |11.03Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_375 |12.01Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_374 |45.83Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_371 |19.97Mb
  - _313 |17.92Mb
  - disney_netflix_FR |44.24Mb
  - disney_netflix_FR |21.59Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_377 |17.17Mb
  - disney_netflix_NL |11.00Mb
  - ğŸ‡¬ğŸ‡§GB_384 |152.42Mb
  - ğŸ‡§ğŸ‡·BR_379 |20.69Mb
  - _376 |14.19Mb
  - ğŸ‡²ğŸ‡½MX_395 |40.01Mb
  - ğŸ‡¦ğŸ‡ºAU_378 |11.34Mb
  - disney_netflix_US |20.81Mb
  - ğŸ‡­ğŸ‡°HK_388 |29.42Mb
  - ğŸ‡°ğŸ‡·KR_393 |11.40Mb
  - ğŸ‡·ğŸ‡ºRU_397 |13.42Mb
  - disney_TR |10.09Mb
  - ğŸ‡²ğŸ‡¾MY_396 |31.96Mb
  - ğŸ‡¸ğŸ‡¬SG_398 |16.10Mb
  - ğŸ‡ºğŸ‡¸US_402 |23.75Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_403 |18.52Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
