port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: _174 |48.53Mb
  server: 184.72.124.41
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: _178 |59.69Mb
  server: 13.218.107.141
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: _177 |51.26Mb
  server: 98.89.32.62
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: _181 |31.53Mb
  server: 23.22.182.151
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: netflix_US |37.13Mb
  server: 54.159.62.233
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: _183 |60.72Mb
  server: 54.144.64.227
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: netflix_US |64.06Mb
  server: 50.19.46.248
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: netflix_US |36.09Mb
  server: 54.227.38.247
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: netflix_US |38.76Mb
  server: 13.222.155.147
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: netflix_US |61.00Mb
  server: 98.81.59.20
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: _196 |43.68Mb
  server: 3.89.113.22
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: _187 |48.27Mb
  server: 3.93.196.82
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: _200 |31.49Mb
  server: 54.91.94.165
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: _185 |323.46Mb
  server: 34.251.86.159
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: netflix_IE |293.17Mb
  server: 3.253.99.197
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: netflix_IE |283.27Mb
  server: 54.246.35.116
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: _197 |207.60Mb
  server: 3.250.105.240
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: _205 |22.92Mb
  server: 82.38.31.187
  type: ss
  port: 8080
  udp: true
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: _211 |11.79Mb
  server: 15.235.41.200
  type: vmess
  port: 80
  uuid: 58fe1542-5290-40ad-815a-77707a81afe5
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /IOebhLMhl1CTbFHbL95myfRX2
- name: _206 |88.40Mb
  server: 45.87.175.166
  type: ss
  port: 443
  udp: true
  password: 1RWwXhwfAB5gAEozU4G2Pg
  cipher: chacha20-ietf-poly1305
- name: _179 |148.75Mb
  server: 13.61.180.46
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: _175 |147.87Mb
  server: 13.61.13.231
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: netflix_SE |147.22Mb
  server: 51.20.125.235
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: netflix_US |42.34Mb
  server: 163.192.49.195
  type: vmess
  port: 443
  uuid: bcb7c581-3c95-4569-a4e7-918141e91ea3
  alterId: 0
  cipher: auto
  network: http
  http-opts:
    path:
    - /
    headers:
      Host:
      - a.189.cn
  h2-opts: {}
- name: disney_US |37.67Mb
  server: 165.140.216.141
  type: vmess
  port: 443
  uuid: e7d72a8d-26f2-4b54-b366-0c43e0bcba7d
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _223 |295.89Mb
  server: 85.195.101.122
  type: vmess
  port: 40878
  uuid: f3d4167e-b15e-4e46-82e9-9286ef93fda7
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _238 |31.17Mb
  server: 216.238.86.158
  type: vmess
  port: 34460
  udp: true
  uuid: 90be214d-048c-4ea2-a602-b8e4d4e51e36
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _235 |13.11Mb
  server: 209.126.84.189
  type: vmess
  port: 443
  uuid: 2c981164-9b93-4bca-94ff-b78d3f8498d7
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /vmessws
- name: _215 |18.88Mb
  server: 8.218.105.196
  type: vmess
  port: 52752
  uuid: 925bdbf5-72be-4437-bebf-441c61089f6b
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: disney_SG |16.20Mb
  server: 165.154.195.38
  type: vmess
  port: 35034
  uuid: 959a8caf-4cea-43d0-a548-3628e7ddfafc
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: disney_US |33.91Mb
  server: 192.204.47.79
  type: vmess
  port: 42277
  udp: true
  uuid: aee61b21-e85a-484b-f203-b245f1451cff
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _234 |16.47Mb
  server: 54.206.192.9
  type: vmess
  port: 16407
  uuid: 08f45028-1db6-4e93-bf51-d344b6c71e19
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _229 |20.68Mb
  server: 8.210.184.105
  type: vmess
  port: 40374
  udp: true
  uuid: 36b76373-7a4f-4669-9113-7d247bcf2704
  alterId: 0
  cipher: auto
  network: http
  http-opts:
    method: GET
    path:
    - /
  h2-opts: {}
- name: _217 |42.43Mb
  server: 89.31.120.192
  type: vmess
  port: 443
  uuid: 44537595-9ccc-4b83-8936-5f9ad3229019
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _236 |10.68Mb
  server: 103.127.218.91
  type: vmess
  port: 54693
  uuid: 1cef03ad-6343-408c-8121-cbd1fda2ee9d
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /1cef03ad
- name: _226 |22.23Mb
  server: 183.236.51.36
  type: vmess
  port: 59003
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 64
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _241 |50.71Mb
  server: 43.165.7.71
  type: vmess
  port: 19751
  uuid: 6cfa6103-5d06-40cb-f452-b563db578288
  alterId: 0
  cipher: auto
  network: http
  http-opts:
    method: GET
    path:
    - /
  h2-opts: {}
- name: Pool__247 |187.82Mb
  server: 70.34.218.149
  type: trojan
  port: 11930
  password: BaeSzHdfJIR13l67
  sni: softpillow.silentrocket.click
- name: _245 |51.19Mb
  server: 160.16.196.59
  type: trojan
  port: 2890
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: _246 |48.35Mb
  server: 160.16.236.32
  type: trojan
  port: 4054
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: _254 |14.49Mb
  server: 160.16.124.55
  type: trojan
  port: 2890
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: _244 |15.23Mb
  server: 47.243.51.237
  type: vmess
  port: 52801
  uuid: ef93f413-9039-4ddb-aefb-2490287df55a
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /arki
- name: _258 |12.51Mb
  server: 160.16.214.6
  type: trojan
  port: 2890
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: _256 |52.60Mb
  server: 202.181.103.235
  type: trojan
  port: 2890
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: disney_netflix_GB |232.39Mb
  server: 172.67.134.185
  type: trojan
  port: 443
  udp: true
  password: POORIARED
  sni: reDfRee8.REDFree8.ir
  ws-opts:
    path: /eyJqdW5rIjoiVUl6eXhLZkkwUTJ3ZzkiLCJwcm90b2NvbCI6InRyIiwibW9kZSI6InByb3h5aXAiLCJwYW5lbElQcyI6W119?ed=2560
    headers:
      Host: reDfRee8.REDFree8.ir
  network: ws
- name: Relay_-ğŸ‡¸ğŸ‡¬SG_260 |11.27Mb
  server: 160.16.153.13
  type: trojan
  port: 3145
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: _263 |12.02Mb
  server: 153.121.51.29
  type: trojan
  port: 2890
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: netflix_CA |24.17Mb
  server: 38.96.254.102
  type: trojan
  port: 18509
  password: .ie4rghJuMkcf0oF
  sni: shoppingmall.electricbanana.click
- name: Relay_-ğŸ‡¯ğŸ‡µJP_264 |14.29Mb
  server: 153.121.67.215
  type: trojan
  port: 1331
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: disney_FR |211.76Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 40433
  uuid: d8fd8955-78db-49ba-d86f-3e4729f6ac4d
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_FR |217.51Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 27092
  uuid: a0596ba6-72a3-4366-8992-77088da65bd8
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡¬ğŸ‡§GB_284 |212.24Mb
  server: 82.38.31.194
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: _266 |10.67Mb
  server: 153.121.53.187
  type: trojan
  port: 3093
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: ğŸ‡¬ğŸ‡§GB_285 |197.01Mb
  server: 82.38.31.191
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: _267 |13.11Mb
  server: 153.121.65.107
  type: trojan
  port: 3093
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: ğŸ‡ºğŸ‡¸US_298 |19.80Mb
  server: 18.207.122.59
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: netflix_NL |247.47Mb
  server: 82.38.31.217
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: netflix_IE |329.28Mb
  server: 52.50.200.2
  type: ss
  country: ğŸ‡®ğŸ‡ªIE
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: _202 |18.08Mb
  server: 94.198.220.183
  type: ss
  port: 64674
  udp: true
  password: s8LbJCgUiGXeCKVc63tHJP
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡²ğŸ‡½MX_294 |40.99Mb
  server: 216.238.87.47
  type: vmess
  country: ğŸ‡²ğŸ‡½MX
  port: 27502
  uuid: b8155ce4-7e08-4c40-800f-8671312b7124
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_KZ |28.67Mb
  server: 31.3.209.183
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 28212
  password: Kmn7dHPw5wNfkqQMPcGWQA
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_300 |107.72Mb
  server: 45.12.136.170
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: l668XHPejoSNNuD66BYzyehaCpZexiF7
  cipher: chacha20-ietf-poly1305
- name: disney_HK |26.16Mb
  server: 45.207.157.29
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 13852
  uuid: 845764df-ecb3-4b13-bed2-bf1551b68e9a
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_KR |17.66Mb
  server: 49.128.204.85
  type: vmess
  country: ğŸ‡°ğŸ‡·KR
  port: 16629
  uuid: 2c78877c-6472-45da-ae89-9b9d6e3ec5e6
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
  ws-opts:
    path: /sfgjmero45
- name: disney_US |16.98Mb
  server: cf.fovi.tk
  type: vmess
  country: ğŸZZ
  port: 443
  uuid: bf67437e-6c90-45ca-abc2-c7240a5ce2aa
  alterId: 0
  cipher: auto
  network: ws
  servername: foxpol.fovi.tk
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /eisasqa
    headers:
      HOST: foxpol.fovi.tk
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - _174 |48.53Mb
  - _178 |59.69Mb
  - _177 |51.26Mb
  - _181 |31.53Mb
  - netflix_US |37.13Mb
  - _183 |60.72Mb
  - netflix_US |64.06Mb
  - netflix_US |36.09Mb
  - netflix_US |38.76Mb
  - netflix_US |61.00Mb
  - _196 |43.68Mb
  - _187 |48.27Mb
  - _200 |31.49Mb
  - _185 |323.46Mb
  - netflix_IE |293.17Mb
  - netflix_IE |283.27Mb
  - _197 |207.60Mb
  - _205 |22.92Mb
  - _211 |11.79Mb
  - _206 |88.40Mb
  - _179 |148.75Mb
  - _175 |147.87Mb
  - netflix_SE |147.22Mb
  - netflix_US |42.34Mb
  - disney_US |37.67Mb
  - _223 |295.89Mb
  - _238 |31.17Mb
  - _235 |13.11Mb
  - _215 |18.88Mb
  - disney_SG |16.20Mb
  - disney_US |33.91Mb
  - _234 |16.47Mb
  - _229 |20.68Mb
  - _217 |42.43Mb
  - _236 |10.68Mb
  - _226 |22.23Mb
  - _241 |50.71Mb
  - Pool__247 |187.82Mb
  - _245 |51.19Mb
  - _246 |48.35Mb
  - _254 |14.49Mb
  - _244 |15.23Mb
  - _258 |12.51Mb
  - _256 |52.60Mb
  - disney_netflix_GB |232.39Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_260 |11.27Mb
  - _263 |12.02Mb
  - netflix_CA |24.17Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_264 |14.29Mb
  - disney_FR |211.76Mb
  - disney_FR |217.51Mb
  - ğŸ‡¬ğŸ‡§GB_284 |212.24Mb
  - _266 |10.67Mb
  - ğŸ‡¬ğŸ‡§GB_285 |197.01Mb
  - _267 |13.11Mb
  - ğŸ‡ºğŸ‡¸US_298 |19.80Mb
  - netflix_NL |247.47Mb
  - netflix_IE |329.28Mb
  - _202 |18.08Mb
  - ğŸ‡²ğŸ‡½MX_294 |40.99Mb
  - disney_KZ |28.67Mb
  - ğŸ‡ºğŸ‡¸US_300 |107.72Mb
  - disney_HK |26.16Mb
  - disney_KR |17.66Mb
  - disney_US |16.98Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - _174 |48.53Mb
  - _178 |59.69Mb
  - _177 |51.26Mb
  - _181 |31.53Mb
  - netflix_US |37.13Mb
  - _183 |60.72Mb
  - netflix_US |64.06Mb
  - netflix_US |36.09Mb
  - netflix_US |38.76Mb
  - netflix_US |61.00Mb
  - _196 |43.68Mb
  - _187 |48.27Mb
  - _200 |31.49Mb
  - _185 |323.46Mb
  - netflix_IE |293.17Mb
  - netflix_IE |283.27Mb
  - _197 |207.60Mb
  - _205 |22.92Mb
  - _211 |11.79Mb
  - _206 |88.40Mb
  - _179 |148.75Mb
  - _175 |147.87Mb
  - netflix_SE |147.22Mb
  - netflix_US |42.34Mb
  - disney_US |37.67Mb
  - _223 |295.89Mb
  - _238 |31.17Mb
  - _235 |13.11Mb
  - _215 |18.88Mb
  - disney_SG |16.20Mb
  - disney_US |33.91Mb
  - _234 |16.47Mb
  - _229 |20.68Mb
  - _217 |42.43Mb
  - _236 |10.68Mb
  - _226 |22.23Mb
  - _241 |50.71Mb
  - Pool__247 |187.82Mb
  - _245 |51.19Mb
  - _246 |48.35Mb
  - _254 |14.49Mb
  - _244 |15.23Mb
  - _258 |12.51Mb
  - _256 |52.60Mb
  - disney_netflix_GB |232.39Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_260 |11.27Mb
  - _263 |12.02Mb
  - netflix_CA |24.17Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_264 |14.29Mb
  - disney_FR |211.76Mb
  - disney_FR |217.51Mb
  - ğŸ‡¬ğŸ‡§GB_284 |212.24Mb
  - _266 |10.67Mb
  - ğŸ‡¬ğŸ‡§GB_285 |197.01Mb
  - _267 |13.11Mb
  - ğŸ‡ºğŸ‡¸US_298 |19.80Mb
  - netflix_NL |247.47Mb
  - netflix_IE |329.28Mb
  - _202 |18.08Mb
  - ğŸ‡²ğŸ‡½MX_294 |40.99Mb
  - disney_KZ |28.67Mb
  - ğŸ‡ºğŸ‡¸US_300 |107.72Mb
  - disney_HK |26.16Mb
  - disney_KR |17.66Mb
  - disney_US |16.98Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
