port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: _563 |22.00Mb
  server: 107.175.87.207
  type: ss
  port: 10011
  udp: true
  password: 86039b71-ba82-4ca8-838e-87086ae666de
  cipher: chacha20-ietf-poly1305
- name: _562 |222.23Mb
  server: 45.87.175.181
  type: ss
  port: 8080
  udp: true
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: _558 |48.25Mb
  server: 45.93.95.187
  type: ss
  port: 8618
  udp: true
  password: 4lUEC91c1d8oeClzDbYpXA
  cipher: chacha20-ietf-poly1305
- name: _561 |280.77Mb
  server: 185.153.197.5
  type: ss
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: disney_PT |596.99Mb
  server: 185.231.233.112
  type: ss
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: _575 |195.21Mb
  server: 47.253.197.26
  type: vmess
  port: 12056
  uuid: dd7be7f1-38ff-45e6-f1e5-b20c2190f527
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
- name: Relay_-ğŸ‡³ğŸ‡±NL_566 |220.45Mb
  server: 151.242.251.137
  type: ss
  port: 8080
  password: o5osZg269v5zHpYjr1xY9s
  cipher: chacha20-ietf-poly1305
- name: _567 |93.83Mb
  server: 213.159.67.124
  type: ss
  port: 443
  password: mbhqsStnFQT1cTZYCdsmkugGUC6GT6rp
  cipher: chacha20-ietf-poly1305
- name: disney_LV |77.69Mb
  server: 31.56.117.73
  type: vmess
  port: 28573
  uuid: aa521837-6bfb-47dd-c87c-ec730a974020
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
- name: _586 |31.68Mb
  server: 104.168.94.41
  type: vmess
  port: 32301
  uuid: a2235b72-fd9c-404f-be5a-53b2de0cb798
  alterId: 0
  cipher: auto
  network: http
  http-opts:
    method: GET
    path:
    - /
  h2-opts: {}
- name: disney_US |32.68Mb
  server: 216.167.49.157
  type: vmess
  port: 36108
  uuid: ac9340c1-61d7-47bd-c5a2-9b888857dec6
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
- name: _570 |117.36Mb
  server: 47.76.31.123
  type: vmess
  port: 46356
  uuid: 2dec1dc2-e102-402f-e759-a719a0bc9111
  alterId: 0
  cipher: auto
  network: http
  http-opts:
    method: GET
    path:
    - /
  h2-opts: {}
- name: _580 |10.37Mb
  server: 54.252.240.128
  type: vmess
  port: 1000
  uuid: ca26a9fd-fef8-4ea7-d194-450ce4e0c67a
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
- name: _593 |91.08Mb
  server: 37.18.14.33
  type: trojan
  port: 443
  udp: true
  password: Qzy7tgpRhu
  sni: m.vk.com
  skip-cert-verify: true
- name: Relay_-ğŸ‡²ğŸ‡¾MY_578 |29.52Mb
  server: ml0724.ysds168.shop
  type: vmess
  port: 2052
  udp: true
  uuid: 665d9b8f-153d-4907-adac-de12afd9c851
  alterId: 0
  cipher: auto
  servername: ml0724.ysds168.shop
  http-opts: {}
  h2-opts: {}
  tls: true
- name: Relay_-ğŸ‡ºğŸ‡¸US_596 |17.60Mb
  server: gy3.hdcloud.link
  type: trojan
  port: 443
  udp: true
  password: 9b6419f8-8120-442e-a48c-6bf52aef0abf
  network: grpc
  grpc-opts:
    grpc-service-name: GunService
- name: ğŸ‡§ğŸ‡¬BG_616 |46.63Mb
  server: 87.121.162.249
  type: ss
  country: ğŸ‡§ğŸ‡¬BG
  port: 443
  password: JGv616hMWdjfuZ00jYfq7XkBHJZrOBrg
  cipher: chacha20-ietf-poly1305
- name: Relay_-ğŸ‡³ğŸ‡±NL_610 |11.42Mb
  server: 153.121.73.102
  type: trojan
  port: 2760
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡³ğŸ‡±NL_611 |10.65Mb
  server: 160.16.214.6
  type: trojan
  port: 2760
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: disney_FR |180.32Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 27092
  uuid: a0596ba6-72a3-4366-8992-77088da65bd8
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡§ğŸ‡·BR_617 |21.32Mb
  server: 38.180.16.86
  type: vmess
  country: ğŸ‡§ğŸ‡·BR
  port: 36104
  uuid: E146A8CB-9D2F-449C-ADCA-8736FB
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡§ğŸ‡·BR_618 |20.77Mb
  server: 38.180.16.86
  type: vmess
  country: ğŸ‡§ğŸ‡·BR
  port: 36236
  uuid: a58bc1a5-8c18-49ff-9453-c331b52f45dc
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_HK |27.09Mb
  server: 58.152.18.192
  type: trojan
  port: 443
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: disney_HK |27.22Mb
  server: 58.152.25.20
  type: trojan
  port: 443
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: ğŸ‡¬ğŸ‡§GB_623 |173.97Mb
  server: 82.38.31.184
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_624 |168.43Mb
  server: 82.38.31.179
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡²ğŸ‡½MX_695 |36.60Mb
  server: 216.238.89.53
  type: vmess
  country: ğŸ‡²ğŸ‡½MX
  port: 57283
  uuid: 1a5aafc0-6482-451d-fe76-6875b7818579
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡®ğŸ‡ªIE_692 |227.24Mb
  server: 18.203.220.111
  type: ss
  country: ğŸ‡®ğŸ‡ªIE
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: disney_US |13.40Mb
  server: 154.83.92.111
  type: ss
  country: ğŸ‡­ğŸ‡°HK
  port: 10014
  password: 8bd43408-d561-4bf7-b5fb-152acaa8fe34
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡­ğŸ‡°HK_663 |118.90Mb
  server: 8.218.17.136
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 52986
  uuid: 7363d47e-ac8b-4fe0-d23e-99077999a70d
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡ºğŸ‡¸US_699 |59.74Mb
  server: 23.95.75.146
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: NDRySIABARbErNIVsCNVkyYAHiBzhveT
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡·ğŸ‡ºRU_697 |145.37Mb
  server: 109.71.246.210
  type: ss
  country: ğŸ‡·ğŸ‡ºRU
  port: 56689
  password: YQCSKoCF3QazW8YlvDBWA4
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡­ğŸ‡°HK_683 |17.06Mb
  server: 8.210.134.183
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 3721
  uuid: e72f5c6b-220f-40b3-a115-2d81473458cf
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
  ws-opts:
    path: /
- name: ğŸ‡­ğŸ‡°HK_685 |114.49Mb
  server: 8.217.176.108
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 33185
  uuid: ebb5a5db-c0dc-487a-c41f-07219c9a0ddc
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_HK |28.44Mb
  server: 112.118.116.66
  type: trojan
  country: ğŸ‡­ğŸ‡°HK
  port: 443
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: ğŸ‡ºğŸ‡¸US_701 |32.55Mb
  server: 74.117.196.232
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 37934
  uuid: 4f3cfda3-a255-40eb-8801-71f9fffb19d6
  alterId: 0
  cipher: auto
  network: ws
  servername: imafake.locker
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /speedtest
    headers:
      HOST: imafake.locker
- name: ğŸ‡ºğŸ‡¸US_703 |30.41Mb
  server: 74.117.196.232
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 37934
  uuid: e3cb685e-7840-45cb-9d64-b2028d9b635e
  alterId: 0
  cipher: auto
  network: ws
  servername: imafake.locker
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /speedtest
    headers:
      HOST: imafake.locker
- name: ğŸ‡ºğŸ‡¸US_705 |28.72Mb
  server: 74.117.196.232
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 37934
  uuid: 54a0bf6d-f2b5-4b2a-942c-798fb129527e
  alterId: 0
  cipher: auto
  network: ws
  servername: imafake.locker
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /speedtest
    headers:
      HOST: imafake.locker
- name: disney_PY |16.31Mb
  server: 38.165.233.93
  type: ss
  country: ğŸ‡ºğŸ‡¸ US
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: Relay_ğŸ‡­ğŸ‡°HK-ğŸ‡­ğŸ‡°HK_679 |83.11Mb
  server: v10.hdacd.com
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 30807
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: auto
  network: tcp
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡ºğŸ‡¸US_706 |27.87Mb
  server: 74.117.196.232
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 37934
  uuid: 6d600864-32da-49fd-baf4-7df051762454
  alterId: 0
  cipher: auto
  network: ws
  servername: imafake.locker
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /speedtest
    headers:
      HOST: imafake.locker
- name: ğŸ‡ºğŸ‡¸US_709 |30.59Mb
  server: 74.117.196.232
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 37934
  uuid: 3b475934-cb2a-4d96-b260-5e50cca5d430
  alterId: 0
  cipher: auto
  network: ws
  servername: imafake.locker
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /speedtest
    headers:
      HOST: imafake.locker
- name: ğŸ‡²ğŸ‡¾MY_696 |30.06Mb
  server: 38.54.98.110
  type: vmess
  country: ğŸ‡²ğŸ‡¾MY
  port: 2052
  uuid: 665d9b8f-153d-4907-adac-de12afd9c851
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: ğŸ‡ºğŸ‡¸US_710 |28.22Mb
  server: 74.117.196.232
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 37934
  uuid: 254551f6-ec28-4938-ad0e-0aa4aa1965ec
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /speedtest
- name: disney_HK |22.51Mb
  server: 45.136.12.37
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 38141
  uuid: fd291be6-b48d-43a1-da38-66c7f80e2f80
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_708 |36.61Mb
  server: sw19.sesamebuta.top
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  uuid: 805ba514-bf2f-4d5d-df49-8417804e8de3
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /abcd
- name: disney_US |27.68Mb
  server: cf.fovi.tk
  type: vmess
  country: ğŸZZ
  port: 443
  uuid: bf67437e-6c90-45ca-abc2-c7240a5ce2aa
  alterId: 0
  cipher: auto
  network: ws
  servername: foxlux.fovi.tk
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /eisasqa
    headers:
      HOST: foxlux.fovi.tk
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - _563 |22.00Mb
  - _562 |222.23Mb
  - _558 |48.25Mb
  - _561 |280.77Mb
  - disney_PT |596.99Mb
  - _575 |195.21Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_566 |220.45Mb
  - _567 |93.83Mb
  - disney_LV |77.69Mb
  - _586 |31.68Mb
  - disney_US |32.68Mb
  - _570 |117.36Mb
  - _580 |10.37Mb
  - _593 |91.08Mb
  - Relay_-ğŸ‡²ğŸ‡¾MY_578 |29.52Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_596 |17.60Mb
  - ğŸ‡§ğŸ‡¬BG_616 |46.63Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_610 |11.42Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_611 |10.65Mb
  - disney_FR |180.32Mb
  - ğŸ‡§ğŸ‡·BR_617 |21.32Mb
  - ğŸ‡§ğŸ‡·BR_618 |20.77Mb
  - disney_HK |27.09Mb
  - disney_HK |27.22Mb
  - ğŸ‡¬ğŸ‡§GB_623 |173.97Mb
  - ğŸ‡¬ğŸ‡§GB_624 |168.43Mb
  - ğŸ‡²ğŸ‡½MX_695 |36.60Mb
  - ğŸ‡®ğŸ‡ªIE_692 |227.24Mb
  - disney_US |13.40Mb
  - ğŸ‡­ğŸ‡°HK_663 |118.90Mb
  - ğŸ‡ºğŸ‡¸US_699 |59.74Mb
  - ğŸ‡·ğŸ‡ºRU_697 |145.37Mb
  - ğŸ‡­ğŸ‡°HK_683 |17.06Mb
  - ğŸ‡­ğŸ‡°HK_685 |114.49Mb
  - disney_HK |28.44Mb
  - ğŸ‡ºğŸ‡¸US_701 |32.55Mb
  - ğŸ‡ºğŸ‡¸US_703 |30.41Mb
  - ğŸ‡ºğŸ‡¸US_705 |28.72Mb
  - disney_PY |16.31Mb
  - Relay_ğŸ‡­ğŸ‡°HK-ğŸ‡­ğŸ‡°HK_679 |83.11Mb
  - ğŸ‡ºğŸ‡¸US_706 |27.87Mb
  - ğŸ‡ºğŸ‡¸US_709 |30.59Mb
  - ğŸ‡²ğŸ‡¾MY_696 |30.06Mb
  - ğŸ‡ºğŸ‡¸US_710 |28.22Mb
  - disney_HK |22.51Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_708 |36.61Mb
  - disney_US |27.68Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - _563 |22.00Mb
  - _562 |222.23Mb
  - _558 |48.25Mb
  - _561 |280.77Mb
  - disney_PT |596.99Mb
  - _575 |195.21Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_566 |220.45Mb
  - _567 |93.83Mb
  - disney_LV |77.69Mb
  - _586 |31.68Mb
  - disney_US |32.68Mb
  - _570 |117.36Mb
  - _580 |10.37Mb
  - _593 |91.08Mb
  - Relay_-ğŸ‡²ğŸ‡¾MY_578 |29.52Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_596 |17.60Mb
  - ğŸ‡§ğŸ‡¬BG_616 |46.63Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_610 |11.42Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_611 |10.65Mb
  - disney_FR |180.32Mb
  - ğŸ‡§ğŸ‡·BR_617 |21.32Mb
  - ğŸ‡§ğŸ‡·BR_618 |20.77Mb
  - disney_HK |27.09Mb
  - disney_HK |27.22Mb
  - ğŸ‡¬ğŸ‡§GB_623 |173.97Mb
  - ğŸ‡¬ğŸ‡§GB_624 |168.43Mb
  - ğŸ‡²ğŸ‡½MX_695 |36.60Mb
  - ğŸ‡®ğŸ‡ªIE_692 |227.24Mb
  - disney_US |13.40Mb
  - ğŸ‡­ğŸ‡°HK_663 |118.90Mb
  - ğŸ‡ºğŸ‡¸US_699 |59.74Mb
  - ğŸ‡·ğŸ‡ºRU_697 |145.37Mb
  - ğŸ‡­ğŸ‡°HK_683 |17.06Mb
  - ğŸ‡­ğŸ‡°HK_685 |114.49Mb
  - disney_HK |28.44Mb
  - ğŸ‡ºğŸ‡¸US_701 |32.55Mb
  - ğŸ‡ºğŸ‡¸US_703 |30.41Mb
  - ğŸ‡ºğŸ‡¸US_705 |28.72Mb
  - disney_PY |16.31Mb
  - Relay_ğŸ‡­ğŸ‡°HK-ğŸ‡­ğŸ‡°HK_679 |83.11Mb
  - ğŸ‡ºğŸ‡¸US_706 |27.87Mb
  - ğŸ‡ºğŸ‡¸US_709 |30.59Mb
  - ğŸ‡²ğŸ‡¾MY_696 |30.06Mb
  - ğŸ‡ºğŸ‡¸US_710 |28.22Mb
  - disney_HK |22.51Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_708 |36.61Mb
  - disney_US |27.68Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
