port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: disney_netflix_US |176.73Mb
  server: 82.198.246.97
  type: vmess
  port: 180
  uuid: d13fc2f5-3e05-4795-81eb-44143a09e552
  alterId: 0
  cipher: auto
  network: tcp
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: _204 |71.94Mb
  server: 74.117.196.232
  type: vmess
  port: 37934
  udp: true
  uuid: 6d600864-32da-49fd-baf4-7df051762454
  alterId: 0
  cipher: auto
  network: ws
  servername: imafake.locker
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /speedtest
- name: disney_netflix_US |38.50Mb
  server: 38.14.99.179
  type: vmess
  port: 59807
  udp: true
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_US |56.25Mb
  server: 23.247.137.64
  type: trojan
  port: 443
  udp: true
  password: 3c4e10af98c30972
  sni: n2.gladns.com
  network: grpc
  grpc-opts:
    grpc-service-name: db
- name: Relay_-ğŸ‡³ğŸ‡±NL_223 |57.94Mb
  server: 160.16.124.55
  type: trojan
  port: 4054
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¯ğŸ‡µJP_225 |22.19Mb
  server: 153.121.65.107
  type: trojan
  port: 3169
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¯ğŸ‡µJP_228 |10.98Mb
  server: 153.121.65.107
  type: trojan
  port: 1331
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡³ğŸ‡±NL_222 |41.69Mb
  server: 16.163.0.29
  type: trojan
  port: 4054
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: _227 |10.83Mb
  server: 58.152.18.95
  type: trojan
  port: 443
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: Relay_-ğŸ‡³ğŸ‡±NL_229 |47.51Mb
  server: 160.16.151.196
  type: trojan
  port: 2890
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡³ğŸ‡±NL_230 |62.41Mb
  server: 160.16.131.243
  type: trojan
  port: 2890
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: _192 |13.68Mb
  server: 103.36.91.32
  type: ss
  port: 8388
  udp: true
  password: asd123456
  cipher: chacha20-ietf
- name: Relay_-ğŸ‡ºğŸ‡¸US_232 |19.82Mb
  server: 160.16.68.250
  type: trojan
  port: 1596
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: disney_HK |28.50Mb
  server: 58.152.18.78
  type: trojan
  port: 443
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡³ğŸ‡±NL_233 |57.29Mb
  server: 160.16.57.238
  type: trojan
  port: 4054
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¸ğŸ‡¬SG_234 |11.92Mb
  server: 160.16.131.243
  type: trojan
  port: 127
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡³ğŸ‡±NL_235 |46.62Mb
  server: 160.16.63.16
  type: trojan
  port: 4054
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡³ğŸ‡±NL_236 |56.87Mb
  server: 160.16.81.84
  type: trojan
  port: 4054
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡ºğŸ‡¸US_237 |11.48Mb
  server: 160.16.150.76
  type: trojan
  port: 1596
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¯ğŸ‡µJP_238 |11.97Mb
  server: 160.16.70.180
  type: trojan
  port: 1331
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¯ğŸ‡µJP_241 |19.55Mb
  server: 160.16.130.66
  type: trojan
  port: 3093
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: disney_netflix_FR |168.27Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 27092
  uuid: a0596ba6-72a3-4366-8992-77088da65bd8
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_-ğŸ‡¸ğŸ‡¬SG_242 |10.80Mb
  server: 160.16.144.208
  type: trojan
  port: 3145
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: disney_netflix_FR |112.92Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 40433
  uuid: d8fd8955-78db-49ba-d86f-3e4729f6ac4d
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_HK |12.67Mb
  server: 112.118.116.66
  type: trojan
  port: 443
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: ğŸ‡§ğŸ‡·BR_244 |11.07Mb
  server: 38.180.16.86
  type: vmess
  country: ğŸ‡§ğŸ‡·BR
  port: 36104
  uuid: E146A8CB-9D2F-449C-ADCA-8736FB
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡¬ğŸ‡§GB_249 |179.56Mb
  server: 82.38.31.190
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡²ğŸ‡½MX_265 |38.46Mb
  server: 216.238.89.53
  type: vmess
  country: ğŸ‡²ğŸ‡½MX
  port: 57283
  uuid: 1a5aafc0-6482-451d-fe76-6875b7818579
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_-ğŸ‡³ğŸ‡±NL_243 |60.83Mb
  server: 160.16.236.32
  type: trojan
  port: 4054
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: ğŸ‡¬ğŸ‡§GB_251 |10.50Mb
  server: 82.38.31.179
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_264 |42.36Mb
  server: 45.87.175.166
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 443
  password: 1RWwXhwfAB5gAEozU4G2Pg
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡­ğŸ‡°HK_253 |55.25Mb
  server: 87.121.162.249
  type: ss
  country: ğŸ‡­ğŸ‡°HK
  port: 443
  password: JGv616hMWdjfuZ00jYfq7XkBHJZrOBrg
  cipher: chacha20-ietf-poly1305
- name: disney_US |201.57Mb
  server: 38.84.201.21
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 53487
  uuid: c3c1ec05-df2c-4975-9b42-e9b007564eb1
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_NL |159.01Mb
  server: 109.71.246.210
  type: ss
  country: ğŸ‡·ğŸ‡ºRU
  port: 56689
  password: YQCSKoCF3QazW8YlvDBWA4
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_US |38.94Mb
  server: 38.14.99.163
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 59807
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: auto
  network: tcp
  servername: 38.14.99.163
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡ºğŸ‡¸US_275 |47.41Mb
  server: 74.117.196.232
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 37934
  uuid: 3b475934-cb2a-4d96-b260-5e50cca5d430
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /speedtest
- name: ğŸ‡ºğŸ‡¸US_276 |25.73Mb
  server: 74.117.196.232
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 37934
  uuid: b2da9920-b0a7-4354-9e26-3833ab8d00d0
  alterId: 0
  cipher: auto
  network: ws
  servername: imafake.locker
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /speedtest
    headers:
      HOST: imafake.locker
- name: ğŸ‡­ğŸ‡°HK_256 |28.30Mb
  server: 47.243.51.237
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 52801
  uuid: ef93f413-9039-4ddb-aefb-2490287df55a
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
  ws-opts:
    path: /arki?ed=2048
- name: ğŸ‡­ğŸ‡°HK_260 |22.61Mb
  server: 47.242.140.52
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 48219
  uuid: 006893c6-79b1-4c44-94ff-b8bbea065f1f
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
  ws-opts:
    path: /arki?ed=2048
- name: ğŸ‡²ğŸ‡¾MY_266 |32.13Mb
  server: 38.54.98.110
  type: vmess
  country: ğŸ‡²ğŸ‡¾MY
  port: 2052
  uuid: 665d9b8f-153d-4907-adac-de12afd9c851
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: ğŸ‡¸ğŸ‡¬SG_268 |10.95Mb
  server: 68.183.178.131
  type: vmess
  country: ğŸ‡¸ğŸ‡¬SG
  port: 58607
  uuid: c11c32cb-27b3-4afa-c0f3-fb250aa4959e
  alterId: 0
  cipher: auto
  network: ws
  servername: www.12333.monster
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /
    headers:
      HOST: www.12333.monster
- name: disney_HK |25.74Mb
  server: 45.136.12.37
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 38141
  uuid: fd291be6-b48d-43a1-da38-66c7f80e2f80
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_US |140.27Mb
  server: cf.fovi.tk
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  uuid: bf67437e-6c90-45ca-abc2-c7240a5ce2aa
  alterId: 0
  cipher: auto
  network: ws
  servername: foxlux.fovi.tk
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /eisasqa
    headers:
      HOST: foxlux.fovi.tk
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - disney_netflix_US |176.73Mb
  - _204 |71.94Mb
  - disney_netflix_US |38.50Mb
  - disney_US |56.25Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_223 |57.94Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_225 |22.19Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_228 |10.98Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_222 |41.69Mb
  - _227 |10.83Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_229 |47.51Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_230 |62.41Mb
  - _192 |13.68Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_232 |19.82Mb
  - disney_HK |28.50Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_233 |57.29Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_234 |11.92Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_235 |46.62Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_236 |56.87Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_237 |11.48Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_238 |11.97Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_241 |19.55Mb
  - disney_netflix_FR |168.27Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_242 |10.80Mb
  - disney_netflix_FR |112.92Mb
  - disney_HK |12.67Mb
  - ğŸ‡§ğŸ‡·BR_244 |11.07Mb
  - ğŸ‡¬ğŸ‡§GB_249 |179.56Mb
  - ğŸ‡²ğŸ‡½MX_265 |38.46Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_243 |60.83Mb
  - ğŸ‡¬ğŸ‡§GB_251 |10.50Mb
  - ğŸ‡±ğŸ‡¹LT_264 |42.36Mb
  - ğŸ‡­ğŸ‡°HK_253 |55.25Mb
  - disney_US |201.57Mb
  - disney_NL |159.01Mb
  - disney_netflix_US |38.94Mb
  - ğŸ‡ºğŸ‡¸US_275 |47.41Mb
  - ğŸ‡ºğŸ‡¸US_276 |25.73Mb
  - ğŸ‡­ğŸ‡°HK_256 |28.30Mb
  - ğŸ‡­ğŸ‡°HK_260 |22.61Mb
  - ğŸ‡²ğŸ‡¾MY_266 |32.13Mb
  - ğŸ‡¸ğŸ‡¬SG_268 |10.95Mb
  - disney_HK |25.74Mb
  - disney_netflix_US |140.27Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - disney_netflix_US |176.73Mb
  - _204 |71.94Mb
  - disney_netflix_US |38.50Mb
  - disney_US |56.25Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_223 |57.94Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_225 |22.19Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_228 |10.98Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_222 |41.69Mb
  - _227 |10.83Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_229 |47.51Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_230 |62.41Mb
  - _192 |13.68Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_232 |19.82Mb
  - disney_HK |28.50Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_233 |57.29Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_234 |11.92Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_235 |46.62Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_236 |56.87Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_237 |11.48Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_238 |11.97Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_241 |19.55Mb
  - disney_netflix_FR |168.27Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_242 |10.80Mb
  - disney_netflix_FR |112.92Mb
  - disney_HK |12.67Mb
  - ğŸ‡§ğŸ‡·BR_244 |11.07Mb
  - ğŸ‡¬ğŸ‡§GB_249 |179.56Mb
  - ğŸ‡²ğŸ‡½MX_265 |38.46Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_243 |60.83Mb
  - ğŸ‡¬ğŸ‡§GB_251 |10.50Mb
  - ğŸ‡±ğŸ‡¹LT_264 |42.36Mb
  - ğŸ‡­ğŸ‡°HK_253 |55.25Mb
  - disney_US |201.57Mb
  - disney_NL |159.01Mb
  - disney_netflix_US |38.94Mb
  - ğŸ‡ºğŸ‡¸US_275 |47.41Mb
  - ğŸ‡ºğŸ‡¸US_276 |25.73Mb
  - ğŸ‡­ğŸ‡°HK_256 |28.30Mb
  - ğŸ‡­ğŸ‡°HK_260 |22.61Mb
  - ğŸ‡²ğŸ‡¾MY_266 |32.13Mb
  - ğŸ‡¸ğŸ‡¬SG_268 |10.95Mb
  - disney_HK |25.74Mb
  - disney_netflix_US |140.27Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
