port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: Relay_ |41.17Mb
  server: 38.14.99.179
  type: vmess
  port: 59807
  udp: true
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_-ğŸ‡¯ğŸ‡µJP_542 |14.73Mb
  server: 153.121.65.107
  type: trojan
  port: 1331
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡³ğŸ‡±NL_545 |14.25Mb
  server: 160.16.131.243
  type: trojan
  port: 2890
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡³ğŸ‡±NL_552 |14.24Mb
  server: 160.16.116.227
  type: trojan
  port: 2890
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¸ğŸ‡¬SG_556 |10.38Mb
  server: 160.16.107.37
  type: trojan
  port: 507
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¸ğŸ‡¬SG_555 |10.05Mb
  server: 153.121.44.99
  type: trojan
  port: 507
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡³ğŸ‡±NL_551 |21.16Mb
  server: 160.16.151.196
  type: trojan
  port: 2890
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: ' |38.53Mb'
  server: 152.70.92.69
  type: vmess
  port: 80
  uuid: bb9c3993-a4b9-4dad-aeb9-ac86371ae68b
  alterId: 0
  cipher: auto
  network: http
  http-opts:
    path:
    - /
  h2-opts: {}
- name: disney_netflix_NL |253.49Mb
  server: 151.242.251.137
  type: ss
  port: 8080
  password: o5osZg269v5zHpYjr1xY9s
  cipher: chacha20-ietf-poly1305
- name: disney_HK |15.06Mb
  server: 58.152.30.120
  type: trojan
  port: 443
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: Relay_-ğŸ‡¸ğŸ‡¬SG_563 |12.56Mb
  server: 160.16.131.243
  type: trojan
  port: 127
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡³ğŸ‡±NL_562 |40.67Mb
  server: 160.16.236.32
  type: trojan
  port: 4054
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: disney_FR |121.78Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 40433
  uuid: d8fd8955-78db-49ba-d86f-3e4729f6ac4d
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_FR |155.57Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 27092
  uuid: a0596ba6-72a3-4366-8992-77088da65bd8
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_NL |226.63Mb
  server: 82.38.31.210
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_NL |16.75Mb
  server: 82.38.31.190
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_NL |247.04Mb
  server: 82.38.31.218
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ' |39.45Mb'
  server: 216.238.89.53
  type: vmess
  country: ğŸ‡²ğŸ‡½MX
  port: 57283
  uuid: 1a5aafc0-6482-451d-fe76-6875b7818579
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡¬ğŸ‡§GB_577 |10.03Mb
  server: 82.38.31.179
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_US |43.90Mb
  server: 104.192.226.106
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: Relay_ |41.48Mb
  server: 38.14.99.163
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 59807
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: auto
  network: tcp
  servername: 38.14.99.163
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: netflix_AL |10.53Mb
  server: 87.121.162.249
  type: ss
  country: ğŸ‡­ğŸ‡°HK
  port: 443
  password: JGv616hMWdjfuZ00jYfq7XkBHJZrOBrg
  cipher: chacha20-ietf-poly1305
- name: ' |22.91Mb'
  server: 47.242.140.52
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 48219
  uuid: 006893c6-79b1-4c44-94ff-b8bbea065f1f
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
  ws-opts:
    path: /arki?ed=2048
- name: ' |11.47Mb'
  server: 146.56.112.110
  type: vmess
  country: ğŸ‡°ğŸ‡·KR
  port: 8888
  uuid: e7c302f3-90d6-42dd-9d7d-94a3683a3707
  alterId: 0
  cipher: auto
  network: tcp
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_HK |16.36Mb
  server: 219.79.186.107
  type: trojan
  country: ğŸ‡­ğŸ‡°HK
  port: 443
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: ' |26.89Mb'
  server: 38.54.98.110
  type: vmess
  country: ğŸ‡²ğŸ‡¾MY
  port: 2052
  uuid: 665d9b8f-153d-4907-adac-de12afd9c851
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: disney_RU |321.32Mb
  server: 38.60.223.8
  type: ss
  country: ğŸ‡·ğŸ‡ºRU
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ' |10.93Mb'
  server: 68.183.178.131
  type: vmess
  country: ğŸ‡¸ğŸ‡¬SG
  port: 58607
  uuid: c11c32cb-27b3-4afa-c0f3-fb250aa4959e
  alterId: 0
  cipher: auto
  network: ws
  servername: www.12333.monster
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /
    headers:
      HOST: www.12333.monster
- name: netflix_LU |30.97Mb
  server: 45.12.144.18
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: LQyAUItafUmmO3EZZx9UbiX6IGydSBgL
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_681 |84.14Mb
  server: 45.12.136.170
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: l668XHPejoSNNuD66BYzyehaCpZexiF7
  cipher: chacha20-ietf-poly1305
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - Relay_ |41.17Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_542 |14.73Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_545 |14.25Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_552 |14.24Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_556 |10.38Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_555 |10.05Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_551 |21.16Mb
  - ' |38.53Mb'
  - disney_netflix_NL |253.49Mb
  - disney_HK |15.06Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_563 |12.56Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_562 |40.67Mb
  - disney_FR |121.78Mb
  - disney_FR |155.57Mb
  - disney_netflix_NL |226.63Mb
  - disney_netflix_NL |16.75Mb
  - disney_netflix_NL |247.04Mb
  - ' |39.45Mb'
  - ğŸ‡¬ğŸ‡§GB_577 |10.03Mb
  - disney_netflix_US |43.90Mb
  - Relay_ |41.48Mb
  - netflix_AL |10.53Mb
  - ' |22.91Mb'
  - ' |11.47Mb'
  - disney_HK |16.36Mb
  - ' |26.89Mb'
  - disney_RU |321.32Mb
  - ' |10.93Mb'
  - netflix_LU |30.97Mb
  - ğŸ‡ºğŸ‡¸US_681 |84.14Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - Relay_ |41.17Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_542 |14.73Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_545 |14.25Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_552 |14.24Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_556 |10.38Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_555 |10.05Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_551 |21.16Mb
  - ' |38.53Mb'
  - disney_netflix_NL |253.49Mb
  - disney_HK |15.06Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_563 |12.56Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_562 |40.67Mb
  - disney_FR |121.78Mb
  - disney_FR |155.57Mb
  - disney_netflix_NL |226.63Mb
  - disney_netflix_NL |16.75Mb
  - disney_netflix_NL |247.04Mb
  - ' |39.45Mb'
  - ğŸ‡¬ğŸ‡§GB_577 |10.03Mb
  - disney_netflix_US |43.90Mb
  - Relay_ |41.48Mb
  - netflix_AL |10.53Mb
  - ' |22.91Mb'
  - ' |11.47Mb'
  - disney_HK |16.36Mb
  - ' |26.89Mb'
  - disney_RU |321.32Mb
  - ' |10.93Mb'
  - netflix_LU |30.97Mb
  - ğŸ‡ºğŸ‡¸US_681 |84.14Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
