port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: disney_netflix_US |48.47Mb
  server: 45.150.52.40
  type: vmess
  port: 443
  uuid: c31777a1-2ee6-4864-db4c-a79fcbc8188b
  alterId: 0
  cipher: auto
  network: ws
  servername: xsj011-3.facai2024.com
  http-opts: {}
  h2-opts: {}
  tls: true
  ws-opts:
    path: /c31777a1
    headers:
      Host: xsj011-3.facai2024.com
- name: _134 |42.58Mb
  server: 172.235.33.114
  type: vmess
  port: 10001
  uuid: 442a3923-eca1-4af0-b3ff-24a7ce0af68f
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: disney_netflix_US |42.29Mb
  server: 163.192.49.195
  type: vmess
  port: 443
  uuid: bcb7c581-3c95-4569-a4e7-918141e91ea3
  alterId: 0
  cipher: auto
  network: http
  http-opts:
    path:
    - /
    headers:
      Host:
      - a.189.cn
  h2-opts: {}
- name: disney_netflix_US |43.80Mb
  server: 165.140.216.141
  type: vmess
  port: 443
  uuid: e7d72a8d-26f2-4b54-b366-0c43e0bcba7d
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _140 |24.65Mb
  server: 51.79.102.253
  type: vmess
  port: 80
  uuid: 58fe1542-5290-40ad-815a-77707a81afe5
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /IOebhLMhl1CTbFHbL95myfRX2
    headers:
      Host: wrmelmwxlf.gktevlrqznwqqozy.fabpfs66gizmnojhcvqxwl.kytrcfzqla87gvgvs6c7kjnrubuh.cc
- name: netflix_DE |270.83Mb
  server: 85.195.101.122
  type: vmess
  port: 40878
  uuid: f3d4167e-b15e-4e46-82e9-9286ef93fda7
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _207 |24.31Mb
  server: 38.96.254.102
  type: trojan
  port: 18509
  password: .ie4rghJuMkcf0oF
  sni: shoppingmall.electricbanana.click
- name: _147 |156.22Mb
  server: 8.218.116.26
  type: vmess
  port: 32228
  uuid: e4767e9f-ed00-4f31-a984-a918bdd9b09c
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: disney_SG |10.05Mb
  server: 165.154.195.38
  type: vmess
  port: 35034
  uuid: 959a8caf-4cea-43d0-a548-3628e7ddfafc
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _155 |36.13Mb
  server: 152.70.92.69
  type: vmess
  port: 80
  uuid: bb9c3993-a4b9-4dad-aeb9-ac86371ae68b
  alterId: 0
  cipher: auto
  network: http
  http-opts:
    path:
    - /
  h2-opts: {}
- name: _206 |47.63Mb
  server: 160.16.124.55
  type: trojan
  port: 2890
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: netflix_AE |45.70Mb
  server: 89.31.120.192
  type: vmess
  port: 443
  uuid: 44537595-9ccc-4b83-8936-5f9ad3229019
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: disney_HK |105.85Mb
  server: 45.136.12.37
  type: vmess
  port: 38141
  uuid: fd291be6-b48d-43a1-da38-66c7f80e2f80
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: ğŸ‡ªğŸ‡¸ES_218 |151.00Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 40433
  uuid: d8fd8955-78db-49ba-d86f-3e4729f6ac4d
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡ªğŸ‡¸ES_219 |192.17Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 27092
  uuid: a0596ba6-72a3-4366-8992-77088da65bd8
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: netflix_SE |188.74Mb
  server: 70.34.218.149
  type: trojan
  port: 11930
  password: BaeSzHdfJIR13l67
  sni: softpillow.silentrocket.click
- name: Relay_-ğŸ‡¯ğŸ‡µJP_209 |20.54Mb
  server: 13.112.81.124
  type: trojan
  port: 3169
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: netflix_NL |229.59Mb
  server: 82.38.31.217
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: netflix_NL |187.64Mb
  server: 82.38.31.194
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: disney_HK |29.24Mb
  server: 58.152.110.82
  type: trojan
  port: 443
  udp: true
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: _213 |47.37Mb
  server: 202.181.103.235
  type: trojan
  port: 2890
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: netflix_NL |193.24Mb
  server: 82.38.31.191
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: netflix_NL |79.87Mb
  server: 77.246.97.187
  type: ss
  country: ğŸ‡·ğŸ‡º RU
  port: 7749
  password: 7kJQs2RYHhViTYWaf1RobB
  cipher: chacha20-ietf-poly1305
- name: disney_TR |51.52Mb
  server: tr-1.stunnel.cc
  type: ss
  country: ğŸ‡¹ğŸ‡·TR
  port: 8444
  password: tunnel-fbrof
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸZZ-ğŸ‡ºğŸ‡¸US_245 |10.31Mb
  server: cf.fovi.tk
  type: vmess
  country: ğŸZZ
  port: 443
  uuid: bf67437e-6c90-45ca-abc2-c7240a5ce2aa
  alterId: 0
  cipher: auto
  network: ws
  servername: foxpol.fovi.tk
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /eisasqa
    headers:
      HOST: foxpol.fovi.tk
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - disney_netflix_US |48.47Mb
  - _134 |42.58Mb
  - disney_netflix_US |42.29Mb
  - disney_netflix_US |43.80Mb
  - _140 |24.65Mb
  - netflix_DE |270.83Mb
  - _207 |24.31Mb
  - _147 |156.22Mb
  - disney_SG |10.05Mb
  - _155 |36.13Mb
  - _206 |47.63Mb
  - netflix_AE |45.70Mb
  - disney_HK |105.85Mb
  - ğŸ‡ªğŸ‡¸ES_218 |151.00Mb
  - ğŸ‡ªğŸ‡¸ES_219 |192.17Mb
  - netflix_SE |188.74Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_209 |20.54Mb
  - netflix_NL |229.59Mb
  - netflix_NL |187.64Mb
  - disney_HK |29.24Mb
  - _213 |47.37Mb
  - netflix_NL |193.24Mb
  - netflix_NL |79.87Mb
  - disney_TR |51.52Mb
  - Relay_ğŸZZ-ğŸ‡ºğŸ‡¸US_245 |10.31Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - disney_netflix_US |48.47Mb
  - _134 |42.58Mb
  - disney_netflix_US |42.29Mb
  - disney_netflix_US |43.80Mb
  - _140 |24.65Mb
  - netflix_DE |270.83Mb
  - _207 |24.31Mb
  - _147 |156.22Mb
  - disney_SG |10.05Mb
  - _155 |36.13Mb
  - _206 |47.63Mb
  - netflix_AE |45.70Mb
  - disney_HK |105.85Mb
  - ğŸ‡ªğŸ‡¸ES_218 |151.00Mb
  - ğŸ‡ªğŸ‡¸ES_219 |192.17Mb
  - netflix_SE |188.74Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_209 |20.54Mb
  - netflix_NL |229.59Mb
  - netflix_NL |187.64Mb
  - disney_HK |29.24Mb
  - _213 |47.37Mb
  - netflix_NL |193.24Mb
  - netflix_NL |79.87Mb
  - disney_TR |51.52Mb
  - Relay_ğŸZZ-ğŸ‡ºğŸ‡¸US_245 |10.31Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
