port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: _634 |14.71Mb
  server: 82.38.31.199
  type: ss
  port: 8080
  udp: true
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_NL |226.14Mb
  server: 151.242.251.137
  type: ss
  port: 8080
  password: o5osZg269v5zHpYjr1xY9s
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_NL |140.93Mb
  server: 45.87.175.181
  type: ss
  port: 8080
  udp: true
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: _650 |69.80Mb
  server: 47.253.197.26
  type: vmess
  port: 12056
  uuid: dd7be7f1-38ff-45e6-f1e5-b20c2190f527
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
- name: netflix_ES |51.87Mb
  server: 213.159.67.124
  type: ss
  port: 443
  password: mbhqsStnFQT1cTZYCdsmkugGUC6GT6rp
  cipher: chacha20-ietf-poly1305
- name: _659 |10.12Mb
  server: 104.168.94.41
  type: vmess
  port: 32301
  uuid: a2235b72-fd9c-404f-be5a-53b2de0cb798
  alterId: 0
  cipher: auto
  network: http
  http-opts:
    method: GET
    path:
    - /
  h2-opts: {}
- name: _635 |40.71Mb
  server: 154.90.62.168
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: _640 |64.38Mb
  server: 45.93.95.187
  type: ss
  port: 8618
  udp: true
  password: 4lUEC91c1d8oeClzDbYpXA
  cipher: chacha20-ietf-poly1305
- name: disney_PT |321.51Mb
  server: 185.231.233.112
  type: ss
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: Relay_-ğŸ‡¯ğŸ‡µJP_677 |13.77Mb
  server: 160.16.236.32
  type: trojan
  port: 3093
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¯ğŸ‡µJP_678 |18.11Mb
  server: 160.16.223.205
  type: trojan
  port: 1331
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: _641 |11.27Mb
  server: 103.106.3.82
  type: ss
  port: 443
  udp: true
  password: 4SaCIazlgumYkM8FkPzlmwjpyWBDZFBk
  cipher: chacha20-ietf-poly1305
- name: _644 |107.83Mb
  server: 47.243.209.146
  type: vmess
  port: 29333
  uuid: 9681c9ac-c4e3-4600-b698-5cc6b14085f7
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /arki?ed=2048
- name: Relay_-ğŸ‡¯ğŸ‡µJP_683 |17.14Mb
  server: 160.16.138.24
  type: trojan
  port: 1331
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: disney_US |71.98Mb
  server: 23.247.137.64
  type: trojan
  port: 443
  udp: true
  password: 3c4e10af98c30972
  alpn:
  - h2
  sni: n2.gladns.com
  network: grpc
  grpc-opts:
    grpc-service-name: db
- name: Relay_-ğŸ‡³ğŸ‡±NL_682 |10.06Mb
  server: 18.162.142.242
  type: trojan
  port: 4054
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡ºğŸ‡¸US_695 |14.21Mb
  server: gy3.hdcloud.link
  type: trojan
  port: 443
  udp: true
  password: 9b6419f8-8120-442e-a48c-6bf52aef0abf
  network: grpc
  grpc-opts:
    grpc-service-name: GunService
- name: Relay_-ğŸ‡²ğŸ‡¾MY_665 |30.51Mb
  server: ml0724.ysds168.shop
  type: vmess
  port: 2052
  udp: true
  uuid: 665d9b8f-153d-4907-adac-de12afd9c851
  alterId: 0
  cipher: auto
  servername: ml0724.ysds168.shop
  http-opts: {}
  h2-opts: {}
  tls: true
- name: Relay_-ğŸ‡³ğŸ‡±NL_691 |10.56Mb
  server: 160.16.81.84
  type: trojan
  port: 2760
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¯ğŸ‡µJP_697 |21.01Mb
  server: 52.195.176.26
  type: trojan
  port: 2145
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: Relay_-ğŸ‡³ğŸ‡±NL_698 |10.70Mb
  server: 160.16.81.84
  type: trojan
  port: 4054
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡³ğŸ‡±NL_699 |10.90Mb
  server: 160.16.236.32
  type: trojan
  port: 4054
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡­ğŸ‡°HK_688 |10.22Mb
  server: green2.cdntencentmusic.com
  type: trojan
  port: 31102
  udp: true
  password: 7832727a-dce8-454a-9df0-591b642f69a9
  sni: green2.cdntencentmusic.com
  skip-cert-verify: true
- name: disney_FR |229.37Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 27092
  uuid: a0596ba6-72a3-4366-8992-77088da65bd8
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡§ğŸ‡¬BG_711 |41.49Mb
  server: 87.121.162.249
  type: ss
  country: ğŸ‡§ğŸ‡¬BG
  port: 443
  password: JGv616hMWdjfuZ00jYfq7XkBHJZrOBrg
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡§ğŸ‡·BR_712 |23.10Mb
  server: 38.180.16.86
  type: vmess
  country: ğŸ‡§ğŸ‡·BR
  port: 36104
  uuid: E146A8CB-9D2F-449C-ADCA-8736FB
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: _700 |12.36Mb
  server: 37.18.14.33
  type: trojan
  port: 443
  udp: true
  password: Qzy7tgpRhu
  sni: m.vk.com
  skip-cert-verify: true
- name: ğŸ‡§ğŸ‡·BR_713 |22.27Mb
  server: 38.180.16.86
  type: vmess
  country: ğŸ‡§ğŸ‡·BR
  port: 36236
  uuid: a58bc1a5-8c18-49ff-9453-c331b52f45dc
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡¬ğŸ‡§GB_717 |11.51Mb
  server: 82.38.31.179
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡®ğŸ‡ªIE_798 |160.99Mb
  server: 18.203.220.111
  type: ss
  country: ğŸ‡®ğŸ‡ªIE
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡ºğŸ‡¸US_808 |14.54Mb
  server: 23.95.75.146
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: NDRySIABARbErNIVsCNVkyYAHiBzhveT
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_801 |17.19Mb
  server: 45.87.175.166
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 443
  password: 1RWwXhwfAB5gAEozU4G2Pg
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡¦ğŸ‡ºAU_811 |10.17Mb
  server: sy4.620720.xyz
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  uuid: 516d8a7a-3f0b-41d3-bad0-246116381516
  alterId: 0
  cipher: auto
  network: ws
  servername: sy4.620720.xyz
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /
    headers:
      HOST: sy4.620720.xyz
- name: ğŸ‡­ğŸ‡°HK_766 |174.55Mb
  server: 8.218.17.136
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 52986
  uuid: 7363d47e-ac8b-4fe0-d23e-99077999a70d
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡ºğŸ‡¸ US_805 |94.76Mb
  server: 38.165.233.93
  type: ss
  country: ğŸ‡ºğŸ‡¸ US
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ğŸ‡²ğŸ‡¾MY_802 |30.86Mb
  server: 38.54.98.110
  type: vmess
  country: ğŸ‡²ğŸ‡¾MY
  port: 2052
  uuid: 665d9b8f-153d-4907-adac-de12afd9c851
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: ğŸ‡ºğŸ‡¸US_812 |21.35Mb
  server: 45.136.12.37
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 38141
  uuid: fd291be6-b48d-43a1-da38-66c7f80e2f80
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_809 |38.02Mb
  server: sw19.sesamebuta.top
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  uuid: 805ba514-bf2f-4d5d-df49-8417804e8de3
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /abcd
- name: ğŸ‡·ğŸ‡ºRU_803 |53.95Mb
  server: 109.71.246.210
  type: ss
  country: ğŸ‡·ğŸ‡ºRU
  port: 56689
  password: YQCSKoCF3QazW8YlvDBWA4
  cipher: chacha20-ietf-poly1305
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - _634 |14.71Mb
  - disney_netflix_NL |226.14Mb
  - disney_netflix_NL |140.93Mb
  - _650 |69.80Mb
  - netflix_ES |51.87Mb
  - _659 |10.12Mb
  - _635 |40.71Mb
  - _640 |64.38Mb
  - disney_PT |321.51Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_677 |13.77Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_678 |18.11Mb
  - _641 |11.27Mb
  - _644 |107.83Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_683 |17.14Mb
  - disney_US |71.98Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_682 |10.06Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_695 |14.21Mb
  - Relay_-ğŸ‡²ğŸ‡¾MY_665 |30.51Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_691 |10.56Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_697 |21.01Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_698 |10.70Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_699 |10.90Mb
  - Relay_-ğŸ‡­ğŸ‡°HK_688 |10.22Mb
  - disney_FR |229.37Mb
  - ğŸ‡§ğŸ‡¬BG_711 |41.49Mb
  - ğŸ‡§ğŸ‡·BR_712 |23.10Mb
  - _700 |12.36Mb
  - ğŸ‡§ğŸ‡·BR_713 |22.27Mb
  - ğŸ‡¬ğŸ‡§GB_717 |11.51Mb
  - ğŸ‡®ğŸ‡ªIE_798 |160.99Mb
  - ğŸ‡ºğŸ‡¸US_808 |14.54Mb
  - ğŸ‡±ğŸ‡¹LT_801 |17.19Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡¦ğŸ‡ºAU_811 |10.17Mb
  - ğŸ‡­ğŸ‡°HK_766 |174.55Mb
  - ğŸ‡ºğŸ‡¸ US_805 |94.76Mb
  - ğŸ‡²ğŸ‡¾MY_802 |30.86Mb
  - ğŸ‡ºğŸ‡¸US_812 |21.35Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_809 |38.02Mb
  - ğŸ‡·ğŸ‡ºRU_803 |53.95Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - _634 |14.71Mb
  - disney_netflix_NL |226.14Mb
  - disney_netflix_NL |140.93Mb
  - _650 |69.80Mb
  - netflix_ES |51.87Mb
  - _659 |10.12Mb
  - _635 |40.71Mb
  - _640 |64.38Mb
  - disney_PT |321.51Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_677 |13.77Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_678 |18.11Mb
  - _641 |11.27Mb
  - _644 |107.83Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_683 |17.14Mb
  - disney_US |71.98Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_682 |10.06Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_695 |14.21Mb
  - Relay_-ğŸ‡²ğŸ‡¾MY_665 |30.51Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_691 |10.56Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_697 |21.01Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_698 |10.70Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_699 |10.90Mb
  - Relay_-ğŸ‡­ğŸ‡°HK_688 |10.22Mb
  - disney_FR |229.37Mb
  - ğŸ‡§ğŸ‡¬BG_711 |41.49Mb
  - ğŸ‡§ğŸ‡·BR_712 |23.10Mb
  - _700 |12.36Mb
  - ğŸ‡§ğŸ‡·BR_713 |22.27Mb
  - ğŸ‡¬ğŸ‡§GB_717 |11.51Mb
  - ğŸ‡®ğŸ‡ªIE_798 |160.99Mb
  - ğŸ‡ºğŸ‡¸US_808 |14.54Mb
  - ğŸ‡±ğŸ‡¹LT_801 |17.19Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡¦ğŸ‡ºAU_811 |10.17Mb
  - ğŸ‡­ğŸ‡°HK_766 |174.55Mb
  - ğŸ‡ºğŸ‡¸ US_805 |94.76Mb
  - ğŸ‡²ğŸ‡¾MY_802 |30.86Mb
  - ğŸ‡ºğŸ‡¸US_812 |21.35Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_809 |38.02Mb
  - ğŸ‡·ğŸ‡ºRU_803 |53.95Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
