port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: _365 |48.81Mb
  server: 173.234.29.2
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _361 |26.18Mb
  server: 138.186.142.81
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _370 |101.72Mb
  server: 185.82.73.212
  type: ss
  port: 8444
  udp: true
  password: _bypfvq6ra7g4n5yCCR9DoVeGya2XUUS
  cipher: chacha20-ietf-poly1305
- name: _366 |144.98Mb
  server: 45.87.175.22
  type: ss
  port: 8080
  udp: true
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: _358 |20.46Mb
  server: 194.59.183.134
  type: ss
  port: 46114
  udp: true
  password: lejSRyqa033OEPmEQsvRsl
  cipher: chacha20-ietf-poly1305
- name: _368 |29.58Mb
  server: 45.14.245.2
  type: ss
  port: 443
  password: 17ZDORWIliQHuO6WRGHChXYMzdRtAYVP
  cipher: chacha20-ietf-poly1305
- name: disney_ES |27.15Mb
  server: 145.249.109.121
  type: ss
  port: 25512
  udp: true
  password: smSMfR9jqLgMkHuQtxSIWh
  cipher: chacha20-ietf-poly1305
- name: _371 |27.28Mb
  server: 46.246.96.30
  type: ss
  port: 31561
  udp: true
  password: hc8LMJew3Fl9MbcFCoFgT0
  cipher: chacha20-ietf-poly1305
- name: disney_PY |131.56Mb
  server: 38.165.233.93
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: _357 |166.67Mb
  server: 103.149.182.158
  type: ss
  port: 8388
  password: asd123456
  cipher: chacha20-ietf
- name: _372 |26.73Mb
  server: 103.149.182.86
  type: ss
  port: 8388
  udp: true
  password: asd123456
  cipher: chacha20-ietf
- name: Relay_-ğŸ‡¯ğŸ‡µJP_391 |22.64Mb
  server: 160.16.72.33
  type: trojan
  port: 3093
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: _392 |16.64Mb
  server: 160.16.136.130
  type: trojan
  port: 2890
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: disney_US |64.47Mb
  server: 156.233.232.192
  type: vmess
  port: 24004
  uuid: 582fcb35-20a0-452c-e179-4c759c62c494
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
- name: _379 |19.21Mb
  server: 47.242.145.160
  type: vmess
  port: 44457
  uuid: 40290609-2743-4d85-c9c3-4c72dd151b9f
  alterId: 0
  cipher: auto
  network: http
  http-opts:
    method: GET
    path:
    - /
  h2-opts: {}
- name: disney_US |61.25Mb
  server: 156.233.232.177
  type: vmess
  port: 44329
  uuid: 1ba1fb56-e235-419e-c193-1c291adad4a7
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
- name: disney_US |67.83Mb
  server: 156.233.232.192
  type: vmess
  port: 44329
  uuid: 1ba1fb56-e235-419e-c193-1c291adad4a7
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
- name: disney_US |59.91Mb
  server: 156.233.232.177
  type: vmess
  port: 24004
  uuid: 582fcb35-20a0-452c-e179-4c759c62c494
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
- name: _393 |11.22Mb
  server: 160.16.131.243
  type: trojan
  port: 2760
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
  skip-cert-verify: true
- name: _396 |11.16Mb
  server: 160.16.106.144
  type: trojan
  port: 2760
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
  skip-cert-verify: true
- name: Relay_-ğŸ‡¯ğŸ‡µJP_400 |21.84Mb
  server: 160.16.117.182
  type: trojan
  port: 3093
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: Relay_ğŸ‡¬ğŸ‡§GB-ğŸ‡³ğŸ‡±NL_413 |167.01Mb
  server: 82.38.31.208
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¨ğŸ‡¦CA_407 |94.67Mb
  server: 185.213.23.63
  type: ss
  country: ğŸ‡¨ğŸ‡¦CA
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: disney_DE |69.38Mb
  server: 89.163.140.136
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: Relay_-ğŸ‡¯ğŸ‡µJP_403 |11.16Mb
  server: 160.16.87.174
  type: trojan
  port: 3169
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: _404 |16.82Mb
  server: 160.16.204.136
  type: trojan
  port: 2890
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: ğŸ‡®ğŸ‡¹IT_419 |54.33Mb
  server: 176.126.83.121
  type: ss
  country: ğŸ‡®ğŸ‡¹IT
  port: 443
  password: Q4t8T7hEYY3mD2Fn4wnxyK4X35AUzvR8
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_424 |217.67Mb
  server: 45.87.175.183
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_425 |215.28Mb
  server: 45.87.175.180
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: QCXDxuDlTTMD7jtgHUjIoj
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_427 |195.58Mb
  server: 45.87.175.185
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡²ğŸ‡½MX_429 |39.62Mb
  server: 216.238.87.47
  type: vmess
  country: ğŸ‡²ğŸ‡½MX
  port: 27502
  uuid: b8155ce4-7e08-4c40-800f-8671312b7124
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡±ğŸ‡¹LT_428 |166.18Mb
  server: 45.87.175.185
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_437 |53.39Mb
  server: 47.253.197.26
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 12056
  uuid: dd7be7f1-38ff-45e6-f1e5-b20c2190f527
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡®ğŸ‡³IN_418 |27.82Mb
  server: 103.97.203.220
  type: vmess
  country: ğŸ‡®ğŸ‡³IN
  port: 550
  uuid: 9e0e83ca-0fbc-44b1-8024-0eb8f9414156
  alterId: 0
  cipher: auto
  network: tcp
  servername: t.me/v2Line
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_HK |17.54Mb
  server: 45.207.157.29
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 13852
  uuid: 845764df-ecb3-4b13-bed2-bf1551b68e9a
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡³ğŸ‡±NL_430 |209.83Mb
  server: 193.29.139.188
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 8080
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_436 |40.73Mb
  server: 38.14.99.163
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 59807
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: auto
  network: tcp
  servername: 38.14.99.163
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡³ğŸ‡±NL_431 |153.43Mb
  server: 193.29.139.141
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 8080
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_439 |10.12Mb
  server: 104.11.86.252
  type: trojan
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  udp: true
  password: hSA6YXe15O
  sni: TelegramğŸ‡¨ğŸ‡³ @WangCai2
  skip-cert-verify: true
- name: ğŸ‡µğŸ‡¹PT_433 |82.78Mb
  server: 185.113.143.186
  type: ss
  country: ğŸ‡µğŸ‡¹PT
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_438 |12.08Mb
  server: gy3.hdcloud.link
  type: trojan
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  udp: true
  password: 168f29a7-6922-4558-8296-61a69cf6a5a2
  network: grpc
  grpc-opts:
    grpc-service-name: GunService
- name: ğŸ‡¸ğŸ‡¬SG_434 |15.34Mb
  server: 68.183.227.45
  type: ss
  country: ğŸ‡¸ğŸ‡¬SG
  port: 8080
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: Relay_ğŸ‡¯ğŸ‡µJP-ğŸ‡¯ğŸ‡µJP_421 |10.97Mb
  server: xray.kk37005.tk
  type: vmess
  country: ğŸ‡¯ğŸ‡µJP
  port: 55919
  uuid: 2e7548bb-7c5b-4d97-d64d-1b2fe4050089
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: ğŸ‡±ğŸ‡¹LT_422 |166.01Mb
  server: ltnl16.saint.ydns.eu
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - _365 |48.81Mb
  - _361 |26.18Mb
  - _370 |101.72Mb
  - _366 |144.98Mb
  - _358 |20.46Mb
  - _368 |29.58Mb
  - disney_ES |27.15Mb
  - _371 |27.28Mb
  - disney_PY |131.56Mb
  - _357 |166.67Mb
  - _372 |26.73Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_391 |22.64Mb
  - _392 |16.64Mb
  - disney_US |64.47Mb
  - _379 |19.21Mb
  - disney_US |61.25Mb
  - disney_US |67.83Mb
  - disney_US |59.91Mb
  - _393 |11.22Mb
  - _396 |11.16Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_400 |21.84Mb
  - Relay_ğŸ‡¬ğŸ‡§GB-ğŸ‡³ğŸ‡±NL_413 |167.01Mb
  - ğŸ‡¨ğŸ‡¦CA_407 |94.67Mb
  - disney_DE |69.38Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_403 |11.16Mb
  - _404 |16.82Mb
  - ğŸ‡®ğŸ‡¹IT_419 |54.33Mb
  - ğŸ‡±ğŸ‡¹LT_424 |217.67Mb
  - ğŸ‡±ğŸ‡¹LT_425 |215.28Mb
  - ğŸ‡±ğŸ‡¹LT_427 |195.58Mb
  - ğŸ‡²ğŸ‡½MX_429 |39.62Mb
  - ğŸ‡±ğŸ‡¹LT_428 |166.18Mb
  - ğŸ‡ºğŸ‡¸US_437 |53.39Mb
  - ğŸ‡®ğŸ‡³IN_418 |27.82Mb
  - disney_HK |17.54Mb
  - ğŸ‡³ğŸ‡±NL_430 |209.83Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_436 |40.73Mb
  - ğŸ‡³ğŸ‡±NL_431 |153.43Mb
  - ğŸ‡ºğŸ‡¸US_439 |10.12Mb
  - ğŸ‡µğŸ‡¹PT_433 |82.78Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_438 |12.08Mb
  - ğŸ‡¸ğŸ‡¬SG_434 |15.34Mb
  - Relay_ğŸ‡¯ğŸ‡µJP-ğŸ‡¯ğŸ‡µJP_421 |10.97Mb
  - ğŸ‡±ğŸ‡¹LT_422 |166.01Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - _365 |48.81Mb
  - _361 |26.18Mb
  - _370 |101.72Mb
  - _366 |144.98Mb
  - _358 |20.46Mb
  - _368 |29.58Mb
  - disney_ES |27.15Mb
  - _371 |27.28Mb
  - disney_PY |131.56Mb
  - _357 |166.67Mb
  - _372 |26.73Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_391 |22.64Mb
  - _392 |16.64Mb
  - disney_US |64.47Mb
  - _379 |19.21Mb
  - disney_US |61.25Mb
  - disney_US |67.83Mb
  - disney_US |59.91Mb
  - _393 |11.22Mb
  - _396 |11.16Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_400 |21.84Mb
  - Relay_ğŸ‡¬ğŸ‡§GB-ğŸ‡³ğŸ‡±NL_413 |167.01Mb
  - ğŸ‡¨ğŸ‡¦CA_407 |94.67Mb
  - disney_DE |69.38Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_403 |11.16Mb
  - _404 |16.82Mb
  - ğŸ‡®ğŸ‡¹IT_419 |54.33Mb
  - ğŸ‡±ğŸ‡¹LT_424 |217.67Mb
  - ğŸ‡±ğŸ‡¹LT_425 |215.28Mb
  - ğŸ‡±ğŸ‡¹LT_427 |195.58Mb
  - ğŸ‡²ğŸ‡½MX_429 |39.62Mb
  - ğŸ‡±ğŸ‡¹LT_428 |166.18Mb
  - ğŸ‡ºğŸ‡¸US_437 |53.39Mb
  - ğŸ‡®ğŸ‡³IN_418 |27.82Mb
  - disney_HK |17.54Mb
  - ğŸ‡³ğŸ‡±NL_430 |209.83Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_436 |40.73Mb
  - ğŸ‡³ğŸ‡±NL_431 |153.43Mb
  - ğŸ‡ºğŸ‡¸US_439 |10.12Mb
  - ğŸ‡µğŸ‡¹PT_433 |82.78Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_438 |12.08Mb
  - ğŸ‡¸ğŸ‡¬SG_434 |15.34Mb
  - Relay_ğŸ‡¯ğŸ‡µJP-ğŸ‡¯ğŸ‡µJP_421 |10.97Mb
  - ğŸ‡±ğŸ‡¹LT_422 |166.01Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
