port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: _441 |11.47Mb
  server: 82.38.31.179
  type: ss
  port: 8080
  udp: true
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: _433 |189.82Mb
  server: 151.242.251.147
  type: ss
  port: 8080
  password: QCXDxuDlTTMD7jtgHUjIoj
  cipher: chacha20-ietf-poly1305
- name: _437 |12.35Mb
  server: 103.149.183.200
  type: ss
  port: 8388
  udp: true
  password: asd123456
  cipher: chacha20-ietf
- name: _438 |45.64Mb
  server: 212.224.125.154
  type: ss
  port: 57456
  udp: true
  password: 6a85b249286a74a9
  cipher: chacha20-ietf-poly1305
- name: _439 |391.06Mb
  server: 46.183.184.60
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: _435 |36.87Mb
  server: 38.60.250.107
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _466 |39.99Mb
  server: 104.192.226.106
  type: ss
  port: 990
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: chacha20-ietf-poly1305
- name: disney_PY |144.03Mb
  server: 38.165.233.93
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: _434 |21.75Mb
  server: 119.59.98.58
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: _440 |19.61Mb
  server: 119.59.98.58
  type: ss
  port: 990
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: chacha20-ietf-poly1305
- name: disney_US |70.11Mb
  server: 79.127.200.162
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: _473 |21.74Mb
  server: 137.184.174.93
  type: ss
  port: 8080
  udp: true
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: _450 |14.98Mb
  server: 138.124.70.206
  type: ss
  port: 1443
  udp: true
  password: ZGM1Y
  cipher: chacha20-ietf-poly1305
- name: _444 |14.92Mb
  server: 194.59.183.134
  type: ss
  port: 46114
  udp: true
  password: lejSRyqa033OEPmEQsvRsl
  cipher: chacha20-ietf-poly1305
- name: _451 |200.32Mb
  server: 82.38.31.214
  type: ss
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: _481 |11.55Mb
  server: pupas-shirting-unsung.freesocks.work
  type: ss
  port: 443
  udp: true
  password: p78naCf2EfOlRSLTX0wFVx
  cipher: chacha20-ietf-poly1305
- name: _462 |220.15Mb
  server: 82.38.31.194
  type: ss
  port: 8080
  udp: true
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: Relay_-ğŸ‡³ğŸ‡±NL_436 |40.18Mb
  server: backup.fleetfoxi.link
  type: ss
  port: 44884
  udp: true
  password: 2DGq3jvVRg5n3CcxmysGK2kmrgJeSNof12A76cZvVxqPpetyC1XEciCFufq5xKvRWGGnKVembpThuUSQhbZ7GMsZY4UVxEBw
  cipher: chacha20-ietf-poly1305
- name: Relay_-ğŸ‡¨ğŸ‡¦CA_482 |69.10Mb
  server: 79.127.200.169
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _477 |204.79Mb
  server: 151.242.251.142
  type: ss
  port: 8080
  udp: true
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: _489 |55.10Mb
  server: 103.35.189.136
  type: ss
  port: 443
  udp: true
  password: SS2QvbC9nqLp2sXXZo0BVy4slcErRuCt
  cipher: chacha20-ietf-poly1305
- name: _476 |10.95Mb
  server: 89.221.225.15
  type: ss
  port: 443
  udp: true
  password: yCbQ4bry4otfifK7oel71NaXpPL9pYJb
  cipher: chacha20-ietf-poly1305
- name: _491 |24.19Mb
  server: 149.22.87.241
  type: ss
  port: 443
  udp: true
  password: shadowsocks
  cipher: aes-128-gcm
- name: _469 |30.78Mb
  server: 147.78.0.182
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _479 |114.01Mb
  server: 45.12.136.170
  type: ss
  port: 443
  udp: true
  password: l668XHPejoSNNuD66BYzyehaCpZexiF7
  cipher: chacha20-ietf-poly1305
- name: _470 |45.03Mb
  server: 156.59.243.6
  type: ss
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: disney_DE |71.64Mb
  server: store.ubi.com
  type: vmess
  port: 443
  uuid: 5197ebcd-4381-45fa-b1d6-368551788d4b
  alterId: 0
  cipher: auto
  network: ws
  servername: fly.stari.dpdns.org
  http-opts: {}
  h2-opts: {}
  tls: true
  ws-opts:
    path: /5197ebcd-4381-45fa-b1d6-368551788d4b-vm
    headers:
      Host: fly.stari.dpdns.org
- name: Relay_-ğŸ‡ºğŸ‡¸US_508 |57.67Mb
  server: www.shopify.com
  type: vmess
  port: 2096
  uuid: 68f891b8-d7e8-47bf-a5f2-b7baf912f69c
  alterId: 0
  cipher: auto
  network: ws
  servername: asuka.0061.my
  http-opts: {}
  h2-opts: {}
  tls: true
  ws-opts:
    path: /
    headers:
      Host: asuka.0061.my
- name: _485 |27.27Mb
  server: 45.14.245.2
  type: ss
  port: 443
  password: 17ZDORWIliQHuO6WRGHChXYMzdRtAYVP
  cipher: chacha20-ietf-poly1305
- name: Relay_-ğŸ‡ºğŸ‡¸US_523 |23.09Mb
  server: 38.14.99.179
  type: vmess
  port: 59807
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: disney_US |42.24Mb
  server: 165.140.216.141
  type: vmess
  port: 443
  uuid: e7d72a8d-26f2-4b54-b366-0c43e0bcba7d
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: disney_JP |16.88Mb
  server: 46.3.47.250
  type: vmess
  port: 20022
  udp: true
  uuid: e5ce425e-0b84-435c-aee5-9f9ecbe2cb16
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _492 |57.99Mb
  server: 62.100.205.100
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _493 |40.69Mb
  server: 146.70.61.37
  type: ss
  port: 8080
  udp: true
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: _497 |10.51Mb
  server: 196.196.192.58
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _525 |25.94Mb
  server: 51.79.102.253
  type: vmess
  port: 80
  uuid: 58fe1542-5290-40ad-815a-77707a81afe5
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /IOebhLMhl1CTbFHbL95myfRX2
    headers:
      Host: wrmelmwxlf.gktevlrqznwqqozy.fabpfs66gizmnojhcvqxwl.kytrcfzqla87gvgvs6c7kjnrubuh.cc
- name: _526 |19.40Mb
  server: 15.235.41.200
  type: vmess
  port: 80
  uuid: 58fe1542-5290-40ad-815a-77707a81afe5
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /IOebhLMhl1CTbFHbL95myfRX2
- name: _495 |282.44Mb
  server: h110vpnnl.outlinekeys.net
  type: ss
  port: 52571
  udp: true
  password: b0TKxnHAYeeFYyzTAMXn0F
  cipher: chacha20-ietf-poly1305
- name: _522 |133.73Mb
  server: v2ray.codefyinc.com
  type: vmess
  port: 443
  uuid: 2c981164-9b93-4bca-94ff-b78d3f8498d7
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /vmessws
    headers:
      Host: v2ray.codefyinc.com
- name: _530 |30.42Mb
  server: 160.16.124.55
  type: trojan
  port: 2890
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¯ğŸ‡µJP_533 |16.38Mb
  server: 160.16.229.223
  type: trojan
  port: 3169
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: _537 |27.86Mb
  server: 160.16.106.144
  type: trojan
  port: 2890
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: _545 |31.53Mb
  server: 160.16.89.176
  type: trojan
  port: 2890
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¯ğŸ‡µJP_548 |16.43Mb
  server: 153.121.73.102
  type: trojan
  port: 3169
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¯ğŸ‡µJP_551 |22.02Mb
  server: 160.16.87.174
  type: trojan
  port: 3169
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: disney_HK |27.85Mb
  server: 219.79.214.159
  type: trojan
  port: 443
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: _521 |38.44Mb
  server: 89.31.120.192
  type: vmess
  port: 443
  uuid: 44537595-9ccc-4b83-8936-5f9ad3229019
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _561 |33.12Mb
  server: 153.121.51.29
  type: trojan
  port: 2890
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: _572 |11.18Mb
  server: 160.16.106.144
  type: trojan
  port: 2760
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
  skip-cert-verify: true
- name: Pool__549 |83.14Mb
  server: 70.34.218.149
  type: trojan
  port: 11930
  password: BaeSzHdfJIR13l67
  sni: softpillow.silentrocket.click
- name: Relay_-ğŸ‡¦ğŸ‡±AL_500 |16.74Mb
  server: 956030a4800ad773.hhshdihasgifghleagfuwefogybweufwef.ir
  type: vmess
  port: 80
  udp: true
  uuid: 42011c65-1de9-4642-9ada-aa626805c2ed
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /
    headers:
      Host: 956030a4800ad773.gdjkhwgedhujkgwehkudadasdasdas.ir
- name: _576 |32.51Mb
  server: 160.16.136.130
  type: trojan
  port: 2890
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: _577 |10.64Mb
  server: 160.16.116.227
  type: trojan
  port: 2760
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
  skip-cert-verify: true
- name: _581 |10.62Mb
  server: 160.16.131.243
  type: trojan
  port: 2760
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
  skip-cert-verify: true
- name: disney_US |23.50Mb
  server: 217.60.249.112
  type: ss
  country: ğŸ‡®ğŸ‡·IR
  port: 443
  password: 0eC4ZBvStOgQEzTpCYjWN5
  cipher: chacha20-ietf-poly1305
- name: _591 |10.86Mb
  server: 202.181.103.235
  type: trojan
  port: 2760
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
  skip-cert-verify: true
- name: _609 |26.77Mb
  server: 160.16.204.136
  type: trojan
  port: 2890
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: ğŸ‡¨ğŸ‡¦CA_610 |70.12Mb
  server: 185.213.23.63
  type: ss
  country: ğŸ‡¨ğŸ‡¦CA
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: disney_CH |36.82Mb
  server: 138.124.67.26
  type: ss
  country: ğŸ‡¨ğŸ‡­CH
  port: 25572
  password: nqcIfYHlpMn3jzqkNDjKaG
  cipher: chacha20-ietf-poly1305
- name: disney_DE |225.49Mb
  server: 89.163.140.136
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: Relay_ğŸ‡¬ğŸ‡§GB-ğŸ‡³ğŸ‡±NL_615 |197.07Mb
  server: 82.38.31.208
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_616 |10.42Mb
  server: 141.98.101.182
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: shadowsocks
  cipher: aes-128-gcm
- name: ğŸ‡±ğŸ‡¹LT_623 |235.37Mb
  server: 45.87.175.185
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¨ğŸ‡±CL_613 |28.72Mb
  server: 154.205.153.107
  type: ss
  country: ğŸ‡¨ğŸ‡±CL
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_641 |25.67Mb
  server: 38.14.99.163
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 59807
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: auto
  network: tcp
  servername: 38.14.99.163
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡±ğŸ‡¹LT_625 |194.28Mb
  server: 45.87.175.183
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸZZ-ğŸ‡®ğŸ‡³IN_643 |38.20Mb
  server: 104.18.14.55
  type: vmess
  country: ğŸZZ
  port: 2052
  uuid: e6447786-8c85-443c-8017-7feaa673ff45
  alterId: 0
  cipher: auto
  network: ws
  servername: in4.123417.xyz
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
  ws-opts:
    path: /
    headers:
      HOST: in4.123417.xyz
- name: ğŸ‡±ğŸ‡¹LT_626 |145.40Mb
  server: 45.87.175.180
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: QCXDxuDlTTMD7jtgHUjIoj
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_627 |152.44Mb
  server: 45.87.175.185
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡¯ğŸ‡µJP_640 |11.73Mb
  server: 46.3.47.250
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 20004
  uuid: e5ce425e-0b84-435c-aee5-9f9ecbe2cb16
  alterId: 0
  cipher: auto
  network: tcp
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡±ğŸ‡» LV_630 |48.29Mb
  server: 46.183.217.204
  type: ss
  country: ğŸ‡±ğŸ‡» LV
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡³ğŸ‡±NL_632 |175.85Mb
  server: 194.87.216.218
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 52571
  password: b0TKxnHAYeeFYyzTAMXn0F
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡µğŸ‡¹PT_639 |48.12Mb
  server: 185.113.143.186
  type: ss
  country: ğŸ‡µğŸ‡¹PT
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ ZZ_642 |77.98Mb
  server: 185.231.233.112
  type: ss
  country: ğŸ ZZ
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ğŸ‡±ğŸ‡¹LT_629 |19.15Mb
  server: ltnl16.saint.ydns.eu
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - _441 |11.47Mb
  - _433 |189.82Mb
  - _437 |12.35Mb
  - _438 |45.64Mb
  - _439 |391.06Mb
  - _435 |36.87Mb
  - _466 |39.99Mb
  - disney_PY |144.03Mb
  - _434 |21.75Mb
  - _440 |19.61Mb
  - disney_US |70.11Mb
  - _473 |21.74Mb
  - _450 |14.98Mb
  - _444 |14.92Mb
  - _451 |200.32Mb
  - _481 |11.55Mb
  - _462 |220.15Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_436 |40.18Mb
  - Relay_-ğŸ‡¨ğŸ‡¦CA_482 |69.10Mb
  - _477 |204.79Mb
  - _489 |55.10Mb
  - _476 |10.95Mb
  - _491 |24.19Mb
  - _469 |30.78Mb
  - _479 |114.01Mb
  - _470 |45.03Mb
  - disney_DE |71.64Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_508 |57.67Mb
  - _485 |27.27Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_523 |23.09Mb
  - disney_US |42.24Mb
  - disney_JP |16.88Mb
  - _492 |57.99Mb
  - _493 |40.69Mb
  - _497 |10.51Mb
  - _525 |25.94Mb
  - _526 |19.40Mb
  - _495 |282.44Mb
  - _522 |133.73Mb
  - _530 |30.42Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_533 |16.38Mb
  - _537 |27.86Mb
  - _545 |31.53Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_548 |16.43Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_551 |22.02Mb
  - disney_HK |27.85Mb
  - _521 |38.44Mb
  - _561 |33.12Mb
  - _572 |11.18Mb
  - Pool__549 |83.14Mb
  - Relay_-ğŸ‡¦ğŸ‡±AL_500 |16.74Mb
  - _576 |32.51Mb
  - _577 |10.64Mb
  - _581 |10.62Mb
  - disney_US |23.50Mb
  - _591 |10.86Mb
  - _609 |26.77Mb
  - ğŸ‡¨ğŸ‡¦CA_610 |70.12Mb
  - disney_CH |36.82Mb
  - disney_DE |225.49Mb
  - Relay_ğŸ‡¬ğŸ‡§GB-ğŸ‡³ğŸ‡±NL_615 |197.07Mb
  - ğŸ‡¬ğŸ‡§GB_616 |10.42Mb
  - ğŸ‡±ğŸ‡¹LT_623 |235.37Mb
  - ğŸ‡¨ğŸ‡±CL_613 |28.72Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_641 |25.67Mb
  - ğŸ‡±ğŸ‡¹LT_625 |194.28Mb
  - Relay_ğŸZZ-ğŸ‡®ğŸ‡³IN_643 |38.20Mb
  - ğŸ‡±ğŸ‡¹LT_626 |145.40Mb
  - ğŸ‡±ğŸ‡¹LT_627 |152.44Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡¯ğŸ‡µJP_640 |11.73Mb
  - ğŸ‡±ğŸ‡» LV_630 |48.29Mb
  - ğŸ‡³ğŸ‡±NL_632 |175.85Mb
  - ğŸ‡µğŸ‡¹PT_639 |48.12Mb
  - ğŸ ZZ_642 |77.98Mb
  - ğŸ‡±ğŸ‡¹LT_629 |19.15Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - _441 |11.47Mb
  - _433 |189.82Mb
  - _437 |12.35Mb
  - _438 |45.64Mb
  - _439 |391.06Mb
  - _435 |36.87Mb
  - _466 |39.99Mb
  - disney_PY |144.03Mb
  - _434 |21.75Mb
  - _440 |19.61Mb
  - disney_US |70.11Mb
  - _473 |21.74Mb
  - _450 |14.98Mb
  - _444 |14.92Mb
  - _451 |200.32Mb
  - _481 |11.55Mb
  - _462 |220.15Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_436 |40.18Mb
  - Relay_-ğŸ‡¨ğŸ‡¦CA_482 |69.10Mb
  - _477 |204.79Mb
  - _489 |55.10Mb
  - _476 |10.95Mb
  - _491 |24.19Mb
  - _469 |30.78Mb
  - _479 |114.01Mb
  - _470 |45.03Mb
  - disney_DE |71.64Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_508 |57.67Mb
  - _485 |27.27Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_523 |23.09Mb
  - disney_US |42.24Mb
  - disney_JP |16.88Mb
  - _492 |57.99Mb
  - _493 |40.69Mb
  - _497 |10.51Mb
  - _525 |25.94Mb
  - _526 |19.40Mb
  - _495 |282.44Mb
  - _522 |133.73Mb
  - _530 |30.42Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_533 |16.38Mb
  - _537 |27.86Mb
  - _545 |31.53Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_548 |16.43Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_551 |22.02Mb
  - disney_HK |27.85Mb
  - _521 |38.44Mb
  - _561 |33.12Mb
  - _572 |11.18Mb
  - Pool__549 |83.14Mb
  - Relay_-ğŸ‡¦ğŸ‡±AL_500 |16.74Mb
  - _576 |32.51Mb
  - _577 |10.64Mb
  - _581 |10.62Mb
  - disney_US |23.50Mb
  - _591 |10.86Mb
  - _609 |26.77Mb
  - ğŸ‡¨ğŸ‡¦CA_610 |70.12Mb
  - disney_CH |36.82Mb
  - disney_DE |225.49Mb
  - Relay_ğŸ‡¬ğŸ‡§GB-ğŸ‡³ğŸ‡±NL_615 |197.07Mb
  - ğŸ‡¬ğŸ‡§GB_616 |10.42Mb
  - ğŸ‡±ğŸ‡¹LT_623 |235.37Mb
  - ğŸ‡¨ğŸ‡±CL_613 |28.72Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_641 |25.67Mb
  - ğŸ‡±ğŸ‡¹LT_625 |194.28Mb
  - Relay_ğŸZZ-ğŸ‡®ğŸ‡³IN_643 |38.20Mb
  - ğŸ‡±ğŸ‡¹LT_626 |145.40Mb
  - ğŸ‡±ğŸ‡¹LT_627 |152.44Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡¯ğŸ‡µJP_640 |11.73Mb
  - ğŸ‡±ğŸ‡» LV_630 |48.29Mb
  - ğŸ‡³ğŸ‡±NL_632 |175.85Mb
  - ğŸ‡µğŸ‡¹PT_639 |48.12Mb
  - ğŸ ZZ_642 |77.98Mb
  - ğŸ‡±ğŸ‡¹LT_629 |19.15Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
