port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: disney_netflix_US |68.90Mb
  server: 98.81.59.20
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: disney_netflix_US |68.00Mb
  server: 13.218.107.141
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: _175 |68.06Mb
  server: 50.19.46.248
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: _176 |70.87Mb
  server: 98.89.32.62
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: _192 |66.94Mb
  server: 23.22.182.151
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: disney_netflix_US |68.68Mb
  server: 184.72.124.41
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: disney_netflix_US |70.59Mb
  server: 54.144.64.227
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: _197 |70.81Mb
  server: 3.93.196.82
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: _196 |68.21Mb
  server: 54.227.38.247
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: disney_netflix_US |70.53Mb
  server: 54.91.94.165
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: disney_netflix_US |63.46Mb
  server: 54.159.62.233
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: disney_netflix_US |69.75Mb
  server: 3.89.113.22
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: _172 |330.24Mb
  server: 3.250.105.240
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: _177 |216.47Mb
  server: 54.246.35.116
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: netflix_IE |234.11Mb
  server: 34.251.86.159
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: _207 |66.31Mb
  server: 13.222.155.147
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: _186 |25.01Mb
  server: 45.87.175.166
  type: ss
  port: 443
  udp: true
  password: 1RWwXhwfAB5gAEozU4G2Pg
  cipher: chacha20-ietf-poly1305
- name: _188 |141.67Mb
  server: 13.61.13.231
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: _189 |156.35Mb
  server: 13.61.180.46
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: disney_netflix_US |44.80Mb
  server: 165.140.216.141
  type: vmess
  port: 443
  uuid: e7d72a8d-26f2-4b54-b366-0c43e0bcba7d
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: disney_US |124.61Mb
  server: 192.204.47.79
  type: vmess
  port: 42277
  udp: true
  uuid: aee61b21-e85a-484b-f203-b245f1451cff
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _219 |42.17Mb
  server: 163.192.49.195
  type: vmess
  port: 443
  uuid: bcb7c581-3c95-4569-a4e7-918141e91ea3
  alterId: 0
  cipher: auto
  network: http
  http-opts:
    path:
    - /
    headers:
      Host:
      - a.189.cn
  h2-opts: {}
- name: _200 |353.52Mb
  server: 3.253.99.197
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: _213 |25.33Mb
  server: 216.238.86.158
  type: vmess
  port: 34460
  udp: true
  uuid: 90be214d-048c-4ea2-a602-b8e4d4e51e36
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: Relay_-ğŸ‡ºğŸ‡¸US_235 |27.81Mb
  server: 20251118.yixianled.com
  type: vmess
  port: 14820
  udp: true
  uuid: 6578c489-28d2-4f12-8c2f-9f2d8789626d
  alterId: 0
  cipher: auto
  network: ws
  servername: 20251118.yixianled.com
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /happy
    headers:
      Host: 20251118.yixianled.com
- name: _236 |10.22Mb
  server: 15.235.41.200
  type: vmess
  port: 80
  uuid: 58fe1542-5290-40ad-815a-77707a81afe5
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /IOebhLMhl1CTbFHbL95myfRX2
- name: _234 |58.24Mb
  server: 43.165.7.71
  type: vmess
  port: 19751
  uuid: 6cfa6103-5d06-40cb-f452-b563db578288
  alterId: 0
  cipher: auto
  network: http
  http-opts:
    method: GET
    path:
    - /
  h2-opts: {}
- name: _226 |22.70Mb
  server: 8.218.105.196
  type: vmess
  port: 52752
  uuid: 925bdbf5-72be-4437-bebf-441c61089f6b
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _247 |10.07Mb
  server: 146.56.112.110
  type: vmess
  port: 8888
  uuid: e7c302f3-90d6-42dd-9d7d-94a3683a3707
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: disney_SG |13.78Mb
  server: 165.154.195.38
  type: vmess
  port: 35034
  uuid: 959a8caf-4cea-43d0-a548-3628e7ddfafc
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: disney_netflix_GB |84.29Mb
  server: 172.67.134.185
  type: trojan
  port: 443
  udp: true
  password: POORIARED
  sni: reDfRee8.REDFree8.ir
  ws-opts:
    path: /eyJqdW5rIjoiVUl6eXhLZkkwUTJ3ZzkiLCJwcm90b2NvbCI6InRyIiwibW9kZSI6InByb3h5aXAiLCJwYW5lbElQcyI6W119?ed=2560
    headers:
      Host: reDfRee8.REDFree8.ir
  network: ws
- name: _260 |23.00Mb
  server: 160.16.81.84
  type: trojan
  port: 4054
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¸ğŸ‡¬SG_262 |14.47Mb
  server: 160.16.153.13
  type: trojan
  port: 3145
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: disney_HK |14.00Mb
  server: 154.21.201.83
  type: vmess
  port: 443
  uuid: 4bf075f5-4d5e-4d39-f5ab-b32a86250f0e
  alterId: 0
  cipher: auto
  network: ws
  servername: hk.nbee.pp.ua
  http-opts: {}
  h2-opts: {}
  tls: true
  ws-opts:
    path: /aa
    headers:
      Host: hk.nbee.pp.ua
- name: Pool__264 |20.16Mb
  server: 70.34.218.149
  type: trojan
  port: 11930
  password: BaeSzHdfJIR13l67
  sni: softpillow.silentrocket.click
- name: _224 |41.03Mb
  server: 89.31.120.192
  type: vmess
  port: 443
  uuid: 44537595-9ccc-4b83-8936-5f9ad3229019
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _263 |13.85Mb
  server: 160.16.117.182
  type: trojan
  port: 3093
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: ğŸ‡¬ğŸ‡§GB_286 |116.37Mb
  server: 82.38.31.194
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: _265 |25.43Mb
  server: 160.16.236.32
  type: trojan
  port: 4054
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: ğŸ‡¬ğŸ‡§GB_287 |193.61Mb
  server: 82.38.31.191
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_288 |113.61Mb
  server: 82.38.31.217
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: _268 |13.86Mb
  server: 160.16.229.223
  type: trojan
  port: 3093
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¯ğŸ‡µJP_272 |11.88Mb
  server: 160.16.70.180
  type: trojan
  port: 1331
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: disney_netflix_US |70.63Mb
  server: 18.207.122.59
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: _273 |10.67Mb
  server: 153.121.53.187
  type: trojan
  port: 3093
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: _274 |10.42Mb
  server: 160.16.151.196
  type: trojan
  port: 4054
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: ğŸ‡²ğŸ‡½MX_304 |167.86Mb
  server: 216.238.87.47
  type: vmess
  country: ğŸ‡²ğŸ‡½MX
  port: 27502
  uuid: b8155ce4-7e08-4c40-800f-8671312b7124
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: netflix_IE |365.38Mb
  server: 52.50.200.2
  type: ss
  country: ğŸ‡®ğŸ‡ªIE
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: disney_HK |14.03Mb
  server: 45.207.157.29
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 13852
  uuid: 845764df-ecb3-4b13-bed2-bf1551b68e9a
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡ºğŸ‡¸US_307 |17.84Mb
  server: 45.12.136.170
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: l668XHPejoSNNuD66BYzyehaCpZexiF7
  cipher: chacha20-ietf-poly1305
- name: netflix_NL |15.45Mb
  server: 45.14.245.2
  type: ss
  port: 443
  password: 17ZDORWIliQHuO6WRGHChXYMzdRtAYVP
  cipher: chacha20-ietf-poly1305
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - disney_netflix_US |68.90Mb
  - disney_netflix_US |68.00Mb
  - _175 |68.06Mb
  - _176 |70.87Mb
  - _192 |66.94Mb
  - disney_netflix_US |68.68Mb
  - disney_netflix_US |70.59Mb
  - _197 |70.81Mb
  - _196 |68.21Mb
  - disney_netflix_US |70.53Mb
  - disney_netflix_US |63.46Mb
  - disney_netflix_US |69.75Mb
  - _172 |330.24Mb
  - _177 |216.47Mb
  - netflix_IE |234.11Mb
  - _207 |66.31Mb
  - _186 |25.01Mb
  - _188 |141.67Mb
  - _189 |156.35Mb
  - disney_netflix_US |44.80Mb
  - disney_US |124.61Mb
  - _219 |42.17Mb
  - _200 |353.52Mb
  - _213 |25.33Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_235 |27.81Mb
  - _236 |10.22Mb
  - _234 |58.24Mb
  - _226 |22.70Mb
  - _247 |10.07Mb
  - disney_SG |13.78Mb
  - disney_netflix_GB |84.29Mb
  - _260 |23.00Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_262 |14.47Mb
  - disney_HK |14.00Mb
  - Pool__264 |20.16Mb
  - _224 |41.03Mb
  - _263 |13.85Mb
  - ğŸ‡¬ğŸ‡§GB_286 |116.37Mb
  - _265 |25.43Mb
  - ğŸ‡¬ğŸ‡§GB_287 |193.61Mb
  - ğŸ‡¬ğŸ‡§GB_288 |113.61Mb
  - _268 |13.86Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_272 |11.88Mb
  - disney_netflix_US |70.63Mb
  - _273 |10.67Mb
  - _274 |10.42Mb
  - ğŸ‡²ğŸ‡½MX_304 |167.86Mb
  - netflix_IE |365.38Mb
  - disney_HK |14.03Mb
  - ğŸ‡ºğŸ‡¸US_307 |17.84Mb
  - netflix_NL |15.45Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - disney_netflix_US |68.90Mb
  - disney_netflix_US |68.00Mb
  - _175 |68.06Mb
  - _176 |70.87Mb
  - _192 |66.94Mb
  - disney_netflix_US |68.68Mb
  - disney_netflix_US |70.59Mb
  - _197 |70.81Mb
  - _196 |68.21Mb
  - disney_netflix_US |70.53Mb
  - disney_netflix_US |63.46Mb
  - disney_netflix_US |69.75Mb
  - _172 |330.24Mb
  - _177 |216.47Mb
  - netflix_IE |234.11Mb
  - _207 |66.31Mb
  - _186 |25.01Mb
  - _188 |141.67Mb
  - _189 |156.35Mb
  - disney_netflix_US |44.80Mb
  - disney_US |124.61Mb
  - _219 |42.17Mb
  - _200 |353.52Mb
  - _213 |25.33Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_235 |27.81Mb
  - _236 |10.22Mb
  - _234 |58.24Mb
  - _226 |22.70Mb
  - _247 |10.07Mb
  - disney_SG |13.78Mb
  - disney_netflix_GB |84.29Mb
  - _260 |23.00Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_262 |14.47Mb
  - disney_HK |14.00Mb
  - Pool__264 |20.16Mb
  - _224 |41.03Mb
  - _263 |13.85Mb
  - ğŸ‡¬ğŸ‡§GB_286 |116.37Mb
  - _265 |25.43Mb
  - ğŸ‡¬ğŸ‡§GB_287 |193.61Mb
  - ğŸ‡¬ğŸ‡§GB_288 |113.61Mb
  - _268 |13.86Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_272 |11.88Mb
  - disney_netflix_US |70.63Mb
  - _273 |10.67Mb
  - _274 |10.42Mb
  - ğŸ‡²ğŸ‡½MX_304 |167.86Mb
  - netflix_IE |365.38Mb
  - disney_HK |14.03Mb
  - ğŸ‡ºğŸ‡¸US_307 |17.84Mb
  - netflix_NL |15.45Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
