port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: ' |51.50Mb'
  server: 137.184.174.93
  type: ss
  port: 8080
  udp: true
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: ' |26.63Mb'
  server: 23.95.72.81
  type: ss
  port: 443
  udp: true
  password: UAMVtHm54uahd6SiN5WcD16rsPSdabPG
  cipher: chacha20-ietf-poly1305
- name: netflix_IE |277.29Mb
  server: 18.203.224.78
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: disney_netflix_NL |179.97Mb
  server: 82.38.31.218
  type: ss
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ' |13.15Mb'
  server: 23.95.75.146
  type: ss
  port: 443
  udp: true
  password: NDRySIABARbErNIVsCNVkyYAHiBzhveT
  cipher: chacha20-ietf-poly1305
- name: ' |153.24Mb'
  server: 82.38.31.176
  type: ss
  port: 8080
  udp: true
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_NL |171.34Mb
  server: 45.87.175.155
  type: ss
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ' |86.74Mb'
  server: 185.156.110.92
  type: ss
  port: 443
  udp: true
  password: gXOXk2FJwsz9P6nXIICuDNOqF9gWX1dn
  cipher: chacha20-ietf-poly1305
- name: ' |15.13Mb'
  server: 213.159.67.124
  type: ss
  port: 443
  udp: true
  password: mbhqsStnFQT1cTZYCdsmkugGUC6GT6rp
  cipher: chacha20-ietf-poly1305
- name: Relay_ |37.89Mb
  server: 38.14.99.179
  type: vmess
  port: 59807
  udp: true
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 64
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_ |37.37Mb
  server: 38.14.99.163
  type: vmess
  port: 59807
  udp: true
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 64
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_ |12.90Mb
  server: 82.198.246.97
  type: vmess
  port: 180
  uuid: d13fc2f5-3e05-4795-81eb-44143a09e552
  alterId: 0
  cipher: auto
  network: tcp
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_ |10.44Mb
  server: 131.186.63.89
  type: vmess
  port: 11655
  uuid: 4bf075f5-4d5e-4d39-f5ab-b32a86250f0e
  alterId: 0
  cipher: auto
  network: ws
  servername: hk.nbee.pp.ua
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /aa
    headers:
      Host: hk.nbee.pp.ua
- name: ' |10.13Mb'
  server: 213.159.66.206
  type: ss
  port: 443
  udp: true
  password: pl2XtR0pzwknQOGwewbwXtPYDw1zn9Vu
  cipher: chacha20-ietf-poly1305
- name: Relay_-ğŸ‡ºğŸ‡¸US_284 |50.96Mb
  server: 104.18.13.167
  type: vmess
  port: 443
  udp: true
  uuid: 24254866-770c-41b4-9404-3f50524f425b
  alterId: 0
  cipher: auto
  network: ws
  servername: 24254866-770c-41b4-9404-3f50524f425b.mihomo.baby
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /saoihgreg9384gh8934
    headers:
      Host: 24254866-770c-41b4-9404-3f50524f425b.mihomo.baby
- name: disney_HK |28.38Mb
  server: gd.bjnet2.com
  type: ss
  port: 36602
  udp: true
  password: 84d85af8-2807-4306-a701-f784676b77c3
  cipher: aes-128-gcm
  plugin: obfs
  plugin-opts:
    host: de5bdbffa87896a4b126f8b62150bb4e.baidu.com
    mode: http
- name: Relay_ |26.24Mb
  server: gd.bjnet2.com
  type: ss
  port: 36608
  udp: true
  password: 84d85af8-2807-4306-a701-f784676b77c3
  cipher: aes-128-gcm
  plugin: obfs
  plugin-opts:
    host: de5bdbffa87896a4b126f8b62150bb4e.baidu.com
    mode: http
- name: ' |155.61Mb'
  server: 45.136.244.201
  type: vmess
  port: 49934
  uuid: 90afa47d-341a-497d-ae25-1d81258804d5
  alterId: 0
  cipher: auto
  network: tcp
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_-ğŸ‡³ğŸ‡±NL_300 |62.49Mb
  server: 160.16.117.182
  type: trojan
  port: 2890
  password: 2cf6d686799e6fa95316394064f26c0a
  sni: www.nintendogames.net
- name: Relay_ |19.87Mb
  server: www.zhoubowen.vip
  type: vmess
  port: 443
  udp: true
  uuid: 71b2655e-07d9-4dad-a770-a2b08275142b
  alterId: 0
  cipher: auto
  network: ws
  servername: www.zhoubowen.vip
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /biutefor.icu
    headers:
      Host: www.zhoubowen.vip
- name: Relay_-ğŸ‡ºğŸ‡¸US_279 |48.68Mb
  server: us19-25.998998.best
  type: vmess
  port: 443
  udp: true
  uuid: 24254866-770c-41b4-9404-3f50524f425b
  alterId: 0
  cipher: auto
  network: ws
  servername: 24254866-770c-41b4-9404-3f50524f425b.mihomo.baby
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /saoihgreg9384gh8934
    headers:
      Host: 24254866-770c-41b4-9404-3f50524f425b.mihomo.baby
- name: Relay_ |47.82Mb
  server: 141.193.213.199
  type: trojan
  port: 443
  udp: true
  password: a544940a-2c1c-4723-96cc-d03053a95530
  sni: 26z68w0ecxbuyf89.ukgogo202511.top
  skip-cert-verify: true
  ws-opts:
    path: /images
    headers:
      Host: 26z68w0ecxbuyf89.ukgogo202511.top
  network: ws
- name: Relay_ |32.15Mb
  server: 141.193.213.199
  type: trojan
  port: 443
  udp: true
  password: a8a5b34d-fe46-487d-bd6a-d9f3101525fd
  sni: 26z68w0ecxbuyf89.ukgogo202511.top
  skip-cert-verify: true
  ws-opts:
    path: /images
    headers:
      Host: 26z68w0ecxbuyf89.ukgogo202511.top
  network: ws
- name: Relay_ |11.54Mb
  server: 160.16.117.182
  type: trojan
  port: 3169
  password: 2cf6d686799e6fa95316394064f26c0a
  sni: www.nintendogames.net
- name: Relay_ |32.02Mb
  server: usiys.southbyte.xyz
  type: trojan
  port: 5897
  udp: true
  password: fg20mtCFHy
  sni: usiys.southbyte.xyz
  skip-cert-verify: true
- name: Relay_ |24.82Mb
  server: 23.227.38.178
  type: trojan
  port: 443
  udp: true
  password: a8a5b34d-fe46-487d-bd6a-d9f3101525fd
  sni: q6clkp794liy3y90.hktimecsgo.xyz
  skip-cert-verify: true
  ws-opts:
    path: /images
    headers:
      Host: q6clkp794liy3y90.hktimecsgo.xyz
  network: ws
- name: disney_HK |10.79Mb
  server: green2.cdntencentmusic.com
  type: trojan
  port: 31102
  udp: true
  password: 3a712733-2555-4ad8-9768-0a56c40350c7
  sni: green2.cdntencentmusic.com
  skip-cert-verify: true
- name: Relay_ |153.74Mb
  server: uk2-2.998998.best
  type: vmess
  port: 443
  udp: true
  uuid: 24254866-770c-41b4-9404-3f50524f425b
  alterId: 0
  cipher: auto
  network: ws
  servername: 24254866-770c-41b4-9404-3f50524f425b.placeunaorder.fun
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /logcatxiouerd34try9
    headers:
      Host: 24254866-770c-41b4-9404-3f50524f425b.placeunaorder.fun
- name: Relay_ |19.17Mb
  server: 23.227.38.178
  type: trojan
  port: 443
  udp: true
  password: aff9928f-7ba3-45fb-b56d-4dec45653ca9
  sni: q6clkp794liy3y90.hktimecsgo.xyz
  skip-cert-verify: true
  ws-opts:
    path: /images
    headers:
      Host: q6clkp794liy3y90.hktimecsgo.xyz
  network: ws
- name: Relay_ |45.89Mb
  server: 141.193.213.60
  type: trojan
  port: 443
  udp: true
  password: 8b45d379-702f-41b3-a6b2-9c87a01dcd5c
  sni: a3t5vfl95f4d5d9y.catimecsgo.xyz
  skip-cert-verify: true
  ws-opts:
    path: /images
    headers:
      Host: a3t5vfl95f4d5d9y.catimecsgo.xyz
  network: ws
- name: ' |29.40Mb'
  server: 58.152.18.55
  type: trojan
  port: 443
  password: 2cf6d686799e6fa95316394064f26c0a
  sni: www.nintendogames.net
- name: Relay_ |18.61Mb
  server: 160.16.240.91
  type: trojan
  port: 4054
  password: 2cf6d686799e6fa95316394064f26c0a
  sni: www.nintendogames.net
- name: Relay_ |94.95Mb
  server: 160.16.106.144
  type: trojan
  port: 3169
  password: 2cf6d686799e6fa95316394064f26c0a
  sni: www.nintendogames.net
- name: disney_HK |10.64Mb
  server: green2.cdntencentmusic.com
  type: trojan
  port: 31102
  udp: true
  password: 0dd72052-23c8-49bb-9b7e-80e9e804b7b2
  sni: green2.cdntencentmusic.com
  skip-cert-verify: true
- name: Relay_ |11.47Mb
  server: 160.16.132.158
  type: trojan
  port: 127
  password: 2cf6d686799e6fa95316394064f26c0a
  sni: www.nintendogames.net
- name: Relay_ |10.13Mb
  server: 160.16.106.144
  type: trojan
  port: 127
  password: 2cf6d686799e6fa95316394064f26c0a
  sni: www.nintendogames.net
- name: Relay_ |58.07Mb
  server: 153.121.76.9
  type: trojan
  port: 4054
  password: 2cf6d686799e6fa95316394064f26c0a
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡³ğŸ‡±NL_339 |11.11Mb
  server: 153.121.76.9
  type: trojan
  port: 2890
  password: 2cf6d686799e6fa95316394064f26c0a
  sni: www.nintendogames.net
- name: ' |102.79Mb'
  server: 38.180.16.86
  type: vmess
  country: ğŸ‡§ğŸ‡·BR
  port: 36104
  uuid: E146A8CB-9D2F-449C-ADCA-8736FB
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_RU |40.50Mb
  server: 37.18.14.33
  type: trojan
  port: 443
  udp: true
  password: Qzy7tgpRhu
  sni: m.vk.com
  skip-cert-verify: true
- name: disney_FR |101.78Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 27092
  uuid: a0596ba6-72a3-4366-8992-77088da65bd8
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ' |161.25Mb'
  server: 82.38.31.194
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ' |102.35Mb'
  server: 38.180.16.86
  type: vmess
  country: ğŸ‡§ğŸ‡·BR
  port: 36236
  uuid: a58bc1a5-8c18-49ff-9453-c331b52f45dc
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ' |42.11Mb'
  server: 216.238.89.53
  type: vmess
  country: ğŸ‡²ğŸ‡½MX
  port: 57283
  uuid: 1a5aafc0-6482-451d-fe76-6875b7818579
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ' |193.84Mb'
  server: 82.38.31.191
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: disney_HK |10.66Mb
  server: green2.cdntencentmusic.com
  type: trojan
  port: 31102
  udp: true
  password: 4e8bc2b8-96de-45ae-9b5c-304f2b288807
  sni: green2.cdntencentmusic.com
  skip-cert-verify: true
- name: Relay_ |239.58Mb
  server: 82.38.31.210
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ' |52.30Mb'
  server: 107.23.148.46
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ' |36.45Mb'
  server: 216.167.107.61
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 44805
  uuid: f7d62526-9e06-455e-82bd-241d368002e8
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_NL |70.20Mb
  server: 82.38.31.217
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_NL |13.25Mb
  server: 45.87.175.166
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 443
  password: 1RWwXhwfAB5gAEozU4G2Pg
  cipher: chacha20-ietf-poly1305
- name: Relay_ |55.15Mb
  server: t1.620720.xyz
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 8443
  uuid: 516d8a7a-3f0b-41d3-bad0-246116381516
  alterId: 0
  cipher: auto
  network: ws
  servername: t1.620720.xyz
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /
    headers:
      HOST: t1.620720.xyz
- name: netflix_US |13.77Mb
  server: cf.fovi.tk
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  uuid: bf67437e-6c90-45ca-abc2-c7240a5ce2aa
  alterId: 0
  cipher: auto
  network: ws
  servername: foxlux.fovi.tk
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /eisasqa
    headers:
      HOST: foxlux.fovi.tk
- name: ' |86.43Mb'
  server: 109.71.246.210
  type: ss
  port: 56689
  udp: true
  password: YQCSKoCF3QazW8YlvDBWA4
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡·ğŸ‡´RO_363 |159.38Mb
  server: 89.46.233.148
  type: ss
  country: ğŸ‡·ğŸ‡´RO
  port: 443
  password: XeGAcwaviWxXzg87AwvnE6gWbhHHGwwB
  cipher: chacha20-ietf-poly1305
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - ' |51.50Mb'
  - ' |26.63Mb'
  - netflix_IE |277.29Mb
  - disney_netflix_NL |179.97Mb
  - ' |13.15Mb'
  - ' |153.24Mb'
  - disney_netflix_NL |171.34Mb
  - ' |86.74Mb'
  - ' |15.13Mb'
  - Relay_ |37.89Mb
  - Relay_ |37.37Mb
  - Relay_ |12.90Mb
  - Relay_ |10.44Mb
  - ' |10.13Mb'
  - Relay_-ğŸ‡ºğŸ‡¸US_284 |50.96Mb
  - disney_HK |28.38Mb
  - Relay_ |26.24Mb
  - ' |155.61Mb'
  - Relay_-ğŸ‡³ğŸ‡±NL_300 |62.49Mb
  - Relay_ |19.87Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_279 |48.68Mb
  - Relay_ |47.82Mb
  - Relay_ |32.15Mb
  - Relay_ |11.54Mb
  - Relay_ |32.02Mb
  - Relay_ |24.82Mb
  - disney_HK |10.79Mb
  - Relay_ |153.74Mb
  - Relay_ |19.17Mb
  - Relay_ |45.89Mb
  - ' |29.40Mb'
  - Relay_ |18.61Mb
  - Relay_ |94.95Mb
  - disney_HK |10.64Mb
  - Relay_ |11.47Mb
  - Relay_ |10.13Mb
  - Relay_ |58.07Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_339 |11.11Mb
  - ' |102.79Mb'
  - disney_RU |40.50Mb
  - disney_FR |101.78Mb
  - ' |161.25Mb'
  - ' |102.35Mb'
  - ' |42.11Mb'
  - ' |193.84Mb'
  - disney_HK |10.66Mb
  - Relay_ |239.58Mb
  - ' |52.30Mb'
  - ' |36.45Mb'
  - disney_netflix_NL |70.20Mb
  - disney_netflix_NL |13.25Mb
  - Relay_ |55.15Mb
  - netflix_US |13.77Mb
  - ' |86.43Mb'
  - ğŸ‡·ğŸ‡´RO_363 |159.38Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - ' |51.50Mb'
  - ' |26.63Mb'
  - netflix_IE |277.29Mb
  - disney_netflix_NL |179.97Mb
  - ' |13.15Mb'
  - ' |153.24Mb'
  - disney_netflix_NL |171.34Mb
  - ' |86.74Mb'
  - ' |15.13Mb'
  - Relay_ |37.89Mb
  - Relay_ |37.37Mb
  - Relay_ |12.90Mb
  - Relay_ |10.44Mb
  - ' |10.13Mb'
  - Relay_-ğŸ‡ºğŸ‡¸US_284 |50.96Mb
  - disney_HK |28.38Mb
  - Relay_ |26.24Mb
  - ' |155.61Mb'
  - Relay_-ğŸ‡³ğŸ‡±NL_300 |62.49Mb
  - Relay_ |19.87Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_279 |48.68Mb
  - Relay_ |47.82Mb
  - Relay_ |32.15Mb
  - Relay_ |11.54Mb
  - Relay_ |32.02Mb
  - Relay_ |24.82Mb
  - disney_HK |10.79Mb
  - Relay_ |153.74Mb
  - Relay_ |19.17Mb
  - Relay_ |45.89Mb
  - ' |29.40Mb'
  - Relay_ |18.61Mb
  - Relay_ |94.95Mb
  - disney_HK |10.64Mb
  - Relay_ |11.47Mb
  - Relay_ |10.13Mb
  - Relay_ |58.07Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_339 |11.11Mb
  - ' |102.79Mb'
  - disney_RU |40.50Mb
  - disney_FR |101.78Mb
  - ' |161.25Mb'
  - ' |102.35Mb'
  - ' |42.11Mb'
  - ' |193.84Mb'
  - disney_HK |10.66Mb
  - Relay_ |239.58Mb
  - ' |52.30Mb'
  - ' |36.45Mb'
  - disney_netflix_NL |70.20Mb
  - disney_netflix_NL |13.25Mb
  - Relay_ |55.15Mb
  - netflix_US |13.77Mb
  - ' |86.43Mb'
  - ğŸ‡·ğŸ‡´RO_363 |159.38Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
