port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: _83 |42.06Mb
  server: 172.235.33.114
  type: vmess
  port: 10001
  uuid: 442a3923-eca1-4af0-b3ff-24a7ce0af68f
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: disney_netflix_US |42.24Mb
  server: 163.192.49.195
  type: vmess
  port: 443
  uuid: bcb7c581-3c95-4569-a4e7-918141e91ea3
  alterId: 0
  cipher: auto
  network: http
  http-opts:
    path:
    - /
    headers:
      Host:
      - a.189.cn
  h2-opts: {}
- name: disney_netflix_US |41.70Mb
  server: 165.140.216.141
  type: vmess
  port: 443
  uuid: e7d72a8d-26f2-4b54-b366-0c43e0bcba7d
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: netflix_CA |28.53Mb
  server: 51.79.102.253
  type: vmess
  port: 80
  uuid: 58fe1542-5290-40ad-815a-77707a81afe5
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /IOebhLMhl1CTbFHbL95myfRX2
    headers:
      Host: wrmelmwxlf.gktevlrqznwqqozy.fabpfs66gizmnojhcvqxwl.kytrcfzqla87gvgvs6c7kjnrubuh.cc
- name: netflix_CA |24.59Mb
  server: 38.96.254.102
  type: trojan
  port: 18509
  password: .ie4rghJuMkcf0oF
  sni: shoppingmall.electricbanana.click
- name: _118 |19.10Mb
  server: 160.16.223.205
  type: trojan
  port: 4054
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: netflix_SE |42.66Mb
  server: 70.34.218.149
  type: trojan
  port: 11930
  password: BaeSzHdfJIR13l67
  sni: softpillow.silentrocket.click
- name: disney_HK |88.56Mb
  server: 156.238.238.194
  type: vmess
  port: 47296
  uuid: 0524236a-e217-4cf3-9223-968a290ffce7
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /
- name: disney_netflix_US |11.35Mb
  server: 202.181.103.235
  type: trojan
  port: 2890
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: disney_netflix_SG |19.96Mb
  server: 165.154.195.38
  type: vmess
  port: 35034
  uuid: 959a8caf-4cea-43d0-a548-3628e7ddfafc
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _37 |162.89Mb
  server: 8.218.105.196
  type: vmess
  port: 52752
  uuid: 925bdbf5-72be-4437-bebf-441c61089f6b
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: netflix_AE |44.77Mb
  server: 89.31.120.192
  type: vmess
  port: 443
  uuid: 44537595-9ccc-4b83-8936-5f9ad3229019
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: disney_netflix_HK |69.80Mb
  server: 58.152.30.120
  type: trojan
  port: 443
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: disney_netflix_US |10.72Mb
  server: 160.16.214.6
  type: trojan
  port: 2890
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: disney_netflix_US |10.90Mb
  server: 160.16.124.55
  type: trojan
  port: 2890
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: disney_netflix_SG |11.23Mb
  server: 160.16.153.13
  type: trojan
  port: 3145
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: netflix_JP |21.29Mb
  server: 160.16.229.223
  type: trojan
  port: 3093
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: netflix_JP |16.81Mb
  server: 13.112.81.124
  type: trojan
  port: 3169
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: disney_netflix_HK |118.42Mb
  server: 58.152.110.82
  type: trojan
  port: 443
  udp: true
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: disney_netflix_FR |33.93Mb
  server: 208.76.223.218
  type: vmess
  country: üá™üá∏ES
  port: 40433
  uuid: d8fd8955-78db-49ba-d86f-3e4729f6ac4d
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_FR |34.24Mb
  server: 208.76.223.218
  type: vmess
  country: üá™üá∏ES
  port: 27092
  uuid: a0596ba6-72a3-4366-8992-77088da65bd8
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_US |27.07Mb
  server: 209.74.81.149
  type: ss
  country: üá∫üá∏US
  port: 21166
  password: q92MrrP9oJ3lMEzbQFpyuU
  cipher: chacha20-ietf-poly1305
- name: disney_HK |44.89Mb
  server: 154.201.76.172
  type: vmess
  port: 20990
  uuid: ba50e1fe-055f-4587-fd0d-36c8d6615192
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: disney_netflix_US |30.64Mb
  server: cf.fovi.tk
  type: vmess
  country: üèÅZZ
  port: 443
  uuid: bf67437e-6c90-45ca-abc2-c7240a5ce2aa
  alterId: 0
  cipher: auto
  network: ws
  servername: foxpol.fovi.tk
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /eisasqa
    headers:
      HOST: foxpol.fovi.tk
- name: _129 |26.23Mb
  server: 58.152.18.71
  type: trojan
  port: 443
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
proxy-groups:
- name: üöÄ ËäÇÁÇπÈÄâÊã©
  type: select
  proxies:
  - ‚ôªÔ∏è Ëá™Âä®ÈÄâÊã©
  - _83 |42.06Mb
  - disney_netflix_US |42.24Mb
  - disney_netflix_US |41.70Mb
  - netflix_CA |28.53Mb
  - netflix_CA |24.59Mb
  - _118 |19.10Mb
  - netflix_SE |42.66Mb
  - disney_HK |88.56Mb
  - disney_netflix_US |11.35Mb
  - disney_netflix_SG |19.96Mb
  - _37 |162.89Mb
  - netflix_AE |44.77Mb
  - disney_netflix_HK |69.80Mb
  - disney_netflix_US |10.72Mb
  - disney_netflix_US |10.90Mb
  - disney_netflix_SG |11.23Mb
  - netflix_JP |21.29Mb
  - netflix_JP |16.81Mb
  - disney_netflix_HK |118.42Mb
  - disney_netflix_FR |33.93Mb
  - disney_netflix_FR |34.24Mb
  - disney_netflix_US |27.07Mb
  - disney_HK |44.89Mb
  - disney_netflix_US |30.64Mb
  - _129 |26.23Mb
  url: https://www.google.com/generate_204
- name: ‚ôªÔ∏è Ëá™Âä®ÈÄâÊã©
  type: url-test
  proxies:
  - _83 |42.06Mb
  - disney_netflix_US |42.24Mb
  - disney_netflix_US |41.70Mb
  - netflix_CA |28.53Mb
  - netflix_CA |24.59Mb
  - _118 |19.10Mb
  - netflix_SE |42.66Mb
  - disney_HK |88.56Mb
  - disney_netflix_US |11.35Mb
  - disney_netflix_SG |19.96Mb
  - _37 |162.89Mb
  - netflix_AE |44.77Mb
  - disney_netflix_HK |69.80Mb
  - disney_netflix_US |10.72Mb
  - disney_netflix_US |10.90Mb
  - disney_netflix_SG |11.23Mb
  - netflix_JP |21.29Mb
  - netflix_JP |16.81Mb
  - disney_netflix_HK |118.42Mb
  - disney_netflix_FR |33.93Mb
  - disney_netflix_FR |34.24Mb
  - disney_netflix_US |27.07Mb
  - disney_HK |44.89Mb
  - disney_netflix_US |30.64Mb
  - _129 |26.23Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,üöÄ ËäÇÁÇπÈÄâÊã©
