port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: _240 |197.37Mb
  server: 172.235.33.114
  type: vmess
  port: 10001
  uuid: 442a3923-eca1-4af0-b3ff-24a7ce0af68f
  alterId: 0
  cipher: auto
  network: tcp
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_-ğŸ‡ºğŸ‡¸US_241 |49.21Mb
  server: us19-25.998998.best
  type: vmess
  port: 443
  udp: true
  uuid: 24254866-770c-41b4-9404-3f50524f425b
  alterId: 0
  cipher: auto
  network: ws
  servername: 24254866-770c-41b4-9404-3f50524f425b.mihomo.baby
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /saoihgreg9384gh8934
    headers:
      Host: 24254866-770c-41b4-9404-3f50524f425b.mihomo.baby
- name: Relay_-ğŸ‡³ğŸ‡±NL_239 |346.82Mb
  server: 151.242.251.144
  type: ss
  port: 8080
  udp: true
  password: QCXDxuDlTTMD7jtgHUjIoj
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_NL |278.13Mb
  server: 82.38.31.218
  type: ss
  port: 8080
  udp: true
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: disney_NL |72.60Mb
  server: 109.71.246.210
  type: ss
  port: 56689
  udp: true
  password: YQCSKoCF3QazW8YlvDBWA4
  cipher: chacha20-ietf-poly1305
- name: disney_US |30.30Mb
  server: 158.101.11.204
  type: trojan
  port: 15805
  udp: true
  password: iwangjie
  sni: nodes.830901.xyz
  ws-opts:
    path: /?ed=2560
    headers:
      Host: nodes.830901.xyz
  network: ws
- name: Relay_-ğŸ‡³ğŸ‡±NL_246 |55.04Mb
  server: 160.16.196.59
  type: trojan
  port: 4054
  password: 2cf6d686799e6fa95316394064f26c0a
  sni: www.nintendogames.net
- name: _237 |11.12Mb
  server: 213.159.67.124
  type: ss
  port: 443
  password: mbhqsStnFQT1cTZYCdsmkugGUC6GT6rp
  cipher: chacha20-ietf-poly1305
- name: disney_TW |41.35Mb
  server: 141.193.213.199
  type: trojan
  port: 443
  udp: true
  password: a8a5b34d-fe46-487d-bd6a-d9f3101525fd
  sni: 26z68w0ecxbuyf89.ukgogo202511.top
  skip-cert-verify: true
  ws-opts:
    path: /images
    headers:
      Host: 26z68w0ecxbuyf89.ukgogo202511.top
  network: ws
- name: disney_HK |10.77Mb
  server: green2.cdntencentmusic.com
  type: trojan
  port: 31104
  udp: true
  password: 308e282a-c8a8-41fb-9e0d-b312409f598c
  sni: green2.cdntencentmusic.com
  skip-cert-verify: true
- name: disney_HK |10.29Mb
  server: green2.cdntencentmusic.com
  type: trojan
  port: 31102
  udp: true
  password: 9e1f9579-d2dd-4bdf-a5c3-b8d54bfe5a4b
  sni: green2.cdntencentmusic.com
  skip-cert-verify: true
- name: Relay_ğŸ‡¬ğŸ‡§GB-ğŸ‡ºğŸ‡¸US_271 |235.20Mb
  server: 82.198.246.97
  type: vmess
  country: ğŸ‡¬ğŸ‡§GB
  port: 180
  uuid: d13fc2f5-3e05-4795-81eb-44143a09e552
  alterId: 0
  cipher: auto
  network: tcp
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_-ğŸ‡³ğŸ‡±NL_255 |26.19Mb
  server: 160.16.136.130
  type: trojan
  port: 4054
  password: 2cf6d686799e6fa95316394064f26c0a
  sni: www.nintendogames.net
- name: _232 |32.01Mb
  server: 103.106.3.82
  type: ss
  port: 443
  udp: true
  password: 4SaCIazlgumYkM8FkPzlmwjpyWBDZFBk
  cipher: chacha20-ietf-poly1305
- name: Relay_-ğŸ‡³ğŸ‡±NL_261 |10.15Mb
  server: 160.16.196.59
  type: trojan
  port: 2760
  password: 2cf6d686799e6fa95316394064f26c0a
  sni: www.nintendogames.net
- name: _238 |155.85Mb
  server: 185.231.233.112
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: disney_FR |137.08Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 27092
  uuid: a0596ba6-72a3-4366-8992-77088da65bd8
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_ğŸ‡®ğŸ‡· IR-ğŸ‡³ğŸ‡±NL_273 |348.24Mb
  server: 151.242.251.144
  type: ss
  country: ğŸ‡®ğŸ‡· IR
  port: 8080
  password: 4a2rfixophdjffa8KVA4Aa
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸ‡®ğŸ‡· IR-ğŸ‡³ğŸ‡±NL_274 |320.51Mb
  server: 151.242.251.153
  type: ss
  country: ğŸ‡®ğŸ‡· IR
  port: 8080
  password: QCXDxuDlTTMD7jtgHUjIoj
  cipher: chacha20-ietf-poly1305
- name: disney_HK |10.87Mb
  server: green2.cdntencentmusic.com
  type: trojan
  port: 31104
  udp: true
  password: 68fed51e-6b31-4cc2-8062-209ac093351b
  sni: green2.cdntencentmusic.com
  skip-cert-verify: true
- name: disney_HK |10.49Mb
  server: green2.cdntencentmusic.com
  type: trojan
  port: 31102
  udp: true
  password: e890aa11-6c4d-47f8-9ce3-713c17725781
  sni: green2.cdntencentmusic.com
  skip-cert-verify: true
- name: Relay_ğŸ‡¯ğŸ‡µJP-ğŸ‡¯ğŸ‡µJP_275 |11.75Mb
  server: xray.kk37005.tk
  type: vmess
  country: ğŸ‡¯ğŸ‡µJP
  port: 55919
  uuid: 2e7548bb-7c5b-4d97-d64d-1b2fe4050089
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡®ğŸ‡·IR_280 |109.58Mb
  server: cf.fovi.tk
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  uuid: bf67437e-6c90-45ca-abc2-c7240a5ce2aa
  alterId: 0
  cipher: auto
  network: ws
  servername: foxpol.fovi.tk
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /eisasqa
    headers:
      HOST: foxpol.fovi.tk
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - _240 |197.37Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_241 |49.21Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_239 |346.82Mb
  - disney_netflix_NL |278.13Mb
  - disney_NL |72.60Mb
  - disney_US |30.30Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_246 |55.04Mb
  - _237 |11.12Mb
  - disney_TW |41.35Mb
  - disney_HK |10.77Mb
  - disney_HK |10.29Mb
  - Relay_ğŸ‡¬ğŸ‡§GB-ğŸ‡ºğŸ‡¸US_271 |235.20Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_255 |26.19Mb
  - _232 |32.01Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_261 |10.15Mb
  - _238 |155.85Mb
  - disney_FR |137.08Mb
  - Relay_ğŸ‡®ğŸ‡· IR-ğŸ‡³ğŸ‡±NL_273 |348.24Mb
  - Relay_ğŸ‡®ğŸ‡· IR-ğŸ‡³ğŸ‡±NL_274 |320.51Mb
  - disney_HK |10.87Mb
  - disney_HK |10.49Mb
  - Relay_ğŸ‡¯ğŸ‡µJP-ğŸ‡¯ğŸ‡µJP_275 |11.75Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡®ğŸ‡·IR_280 |109.58Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - _240 |197.37Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_241 |49.21Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_239 |346.82Mb
  - disney_netflix_NL |278.13Mb
  - disney_NL |72.60Mb
  - disney_US |30.30Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_246 |55.04Mb
  - _237 |11.12Mb
  - disney_TW |41.35Mb
  - disney_HK |10.77Mb
  - disney_HK |10.29Mb
  - Relay_ğŸ‡¬ğŸ‡§GB-ğŸ‡ºğŸ‡¸US_271 |235.20Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_255 |26.19Mb
  - _232 |32.01Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_261 |10.15Mb
  - _238 |155.85Mb
  - disney_FR |137.08Mb
  - Relay_ğŸ‡®ğŸ‡· IR-ğŸ‡³ğŸ‡±NL_273 |348.24Mb
  - Relay_ğŸ‡®ğŸ‡· IR-ğŸ‡³ğŸ‡±NL_274 |320.51Mb
  - disney_HK |10.87Mb
  - disney_HK |10.49Mb
  - Relay_ğŸ‡¯ğŸ‡µJP-ğŸ‡¯ğŸ‡µJP_275 |11.75Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡®ğŸ‡·IR_280 |109.58Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
