port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: netflix_CA |30.50Mb
  server: 51.79.102.253
  type: vmess
  port: 80
  uuid: 58fe1542-5290-40ad-815a-77707a81afe5
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /IOebhLMhl1CTbFHbL95myfRX2
    headers:
      Host: wrmelmwxlf.gktevlrqznwqqozy.fabpfs66gizmnojhcvqxwl.kytrcfzqla87gvgvs6c7kjnrubuh.cc
- name: _205 |41.47Mb
  server: 172.235.33.114
  type: vmess
  port: 10001
  uuid: 442a3923-eca1-4af0-b3ff-24a7ce0af68f
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: netflix_US |41.85Mb
  server: 163.192.49.195
  type: vmess
  port: 443
  uuid: bcb7c581-3c95-4569-a4e7-918141e91ea3
  alterId: 0
  cipher: auto
  network: http
  http-opts:
    path:
    - /
    headers:
      Host:
      - a.189.cn
  h2-opts: {}
- name: disney_US |44.39Mb
  server: 165.140.216.141
  type: vmess
  port: 443
  uuid: e7d72a8d-26f2-4b54-b366-0c43e0bcba7d
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _247 |58.14Mb
  server: 45.150.52.40
  type: vmess
  port: 443
  uuid: c31777a1-2ee6-4864-db4c-a79fcbc8188b
  alterId: 0
  cipher: auto
  network: ws
  servername: xsj011-3.facai2024.com
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /c31777a1
- name: _239 |225.76Mb
  server: 85.195.101.122
  type: vmess
  port: 40878
  uuid: f3d4167e-b15e-4e46-82e9-9286ef93fda7
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: netflix_DE |34.02Mb
  server: 43.165.7.71
  type: vmess
  port: 19751
  uuid: 6cfa6103-5d06-40cb-f452-b563db578288
  alterId: 0
  cipher: auto
  network: http
  http-opts:
    method: GET
    path:
    - /
  h2-opts: {}
- name: netflix_SE |184.08Mb
  server: 70.34.218.149
  type: trojan
  port: 11930
  password: BaeSzHdfJIR13l67
  sni: softpillow.silentrocket.click
- name: Relay_-ðŸ‡³ðŸ‡±NL_270 |24.95Mb
  server: 202.181.103.235
  type: trojan
  port: 2890
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: _272 |20.05Mb
  server: 160.16.117.182
  type: trojan
  port: 3093
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: Relay_-ðŸ‡¯ðŸ‡µJP_273 |14.34Mb
  server: 13.112.81.124
  type: trojan
  port: 3169
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: disney_GB |259.73Mb
  server: koma-yt.pages.dev
  type: trojan
  port: 8443
  udp: true
  password: 8r<[9'l6hAO#8ZQi
  sni: Koma-YT.PAGeS.Dev
  ws-opts:
    path: /tro8sFW1S91B6sZrM1?ed=2560
    headers:
      Host: Koma-YT.PAGeS.Dev
  network: ws
- name: _177 |31.62Mb
  server: 209.74.82.196
  type: ss
  port: 48918
  udp: true
  password: 8Ij4seif85QQHfLmR0zYkQ
  cipher: chacha20-ietf-poly1305
- name: netflix_US |19.86Mb
  server: 209.74.82.227
  type: ss
  port: 26515
  udp: true
  password: uA1rLP5m0mMOQ8FcxRXxgr
  cipher: chacha20-ietf-poly1305
- name: _242 |40.54Mb
  server: 89.31.120.192
  type: vmess
  port: 443
  uuid: 44537595-9ccc-4b83-8936-5f9ad3229019
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: Relay_-ðŸ‡¯ðŸ‡µJP_274 |22.44Mb
  server: 153.121.67.215
  type: trojan
  port: 1331
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: _280 |24.48Mb
  server: 38.96.254.102
  type: trojan
  port: 18509
  password: .ie4rghJuMkcf0oF
  sni: shoppingmall.electricbanana.click
- name: Relay_-ðŸ‡¯ðŸ‡µJP_277 |10.88Mb
  server: 160.16.229.223
  type: trojan
  port: 3093
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: disney_HK |29.06Mb
  server: 58.152.110.82
  type: trojan
  port: 443
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: disney_FR |31.12Mb
  server: 208.76.223.218
  type: vmess
  country: ðŸ‡ªðŸ‡¸ES
  port: 40433
  uuid: d8fd8955-78db-49ba-d86f-3e4729f6ac4d
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ðŸ‡¬ðŸ‡§GB_292 |396.60Mb
  server: 51.15.17.169
  type: ss
  country: ðŸ‡¬ðŸ‡§GB
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: _281 |14.17Mb
  server: 160.16.124.55
  type: trojan
  port: 2890
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: Relay_-ðŸ‡³ðŸ‡±NL_283 |11.12Mb
  server: 160.16.214.6
  type: trojan
  port: 2890
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: Relay_-ðŸ‡¸ðŸ‡¬SG_286 |11.61Mb
  server: 160.16.153.13
  type: trojan
  port: 3145
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: Relay_-ðŸ‡¯ðŸ‡µJP_287 |20.95Mb
  server: 153.121.73.102
  type: trojan
  port: 1331
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: netflix_IE |15.58Mb
  server: 146.70.90.196
  type: ss
  country: ðŸ‡®ðŸ‡ªIE
  port: 17454
  password: u8gp148iz90ddoo6ms37
  cipher: aes-128-gcm
- name: disney_netflix_NL |206.91Mb
  server: 82.38.31.184
  type: ss
  country: ðŸ‡¬ðŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: netflix_US |31.94Mb
  server: 209.74.86.194
  type: ss
  country: ðŸ‡ºðŸ‡¸US
  port: 14936
  password: ppgtoOHdm7cszGunBWBTqQ
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_NL |24.69Mb
  server: 109.71.246.210
  type: ss
  country: ðŸ‡·ðŸ‡ºRU
  port: 56689
  password: YQCSKoCF3QazW8YlvDBWA4
  cipher: chacha20-ietf-poly1305
- name: ðŸ‡·ðŸ‡ºRU_315 |41.56Mb
  server: 81.200.158.206
  type: ss
  country: ðŸ‡·ðŸ‡ºRU
  port: 1080
  password: AqZbt1QCs3ngEfXo1p7T-w
  cipher: chacha20-ietf-poly1305
- name: _209 |36.17Mb
  server: 154.201.76.172
  type: vmess
  port: 20990
  uuid: ba50e1fe-055f-4587-fd0d-36c8d6615192
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: ðŸ‡ºðŸ‡¸US_320 |23.92Mb
  server: 45.136.12.37
  type: vmess
  country: ðŸ‡ºðŸ‡¸US
  port: 38141
  uuid: fd291be6-b48d-43a1-da38-66c7f80e2f80
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ðŸ‡ºðŸ‡¸US_318 |29.28Mb
  server: 209.74.81.149
  type: ss
  country: ðŸ‡ºðŸ‡¸US
  port: 21166
  password: q92MrrP9oJ3lMEzbQFpyuU
  cipher: chacha20-ietf-poly1305
proxy-groups:
- name: ðŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - netflix_CA |30.50Mb
  - _205 |41.47Mb
  - netflix_US |41.85Mb
  - disney_US |44.39Mb
  - _247 |58.14Mb
  - _239 |225.76Mb
  - netflix_DE |34.02Mb
  - netflix_SE |184.08Mb
  - Relay_-ðŸ‡³ðŸ‡±NL_270 |24.95Mb
  - _272 |20.05Mb
  - Relay_-ðŸ‡¯ðŸ‡µJP_273 |14.34Mb
  - disney_GB |259.73Mb
  - _177 |31.62Mb
  - netflix_US |19.86Mb
  - _242 |40.54Mb
  - Relay_-ðŸ‡¯ðŸ‡µJP_274 |22.44Mb
  - _280 |24.48Mb
  - Relay_-ðŸ‡¯ðŸ‡µJP_277 |10.88Mb
  - disney_HK |29.06Mb
  - disney_FR |31.12Mb
  - ðŸ‡¬ðŸ‡§GB_292 |396.60Mb
  - _281 |14.17Mb
  - Relay_-ðŸ‡³ðŸ‡±NL_283 |11.12Mb
  - Relay_-ðŸ‡¸ðŸ‡¬SG_286 |11.61Mb
  - Relay_-ðŸ‡¯ðŸ‡µJP_287 |20.95Mb
  - netflix_IE |15.58Mb
  - disney_netflix_NL |206.91Mb
  - netflix_US |31.94Mb
  - disney_netflix_NL |24.69Mb
  - ðŸ‡·ðŸ‡ºRU_315 |41.56Mb
  - _209 |36.17Mb
  - ðŸ‡ºðŸ‡¸US_320 |23.92Mb
  - ðŸ‡ºðŸ‡¸US_318 |29.28Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - netflix_CA |30.50Mb
  - _205 |41.47Mb
  - netflix_US |41.85Mb
  - disney_US |44.39Mb
  - _247 |58.14Mb
  - _239 |225.76Mb
  - netflix_DE |34.02Mb
  - netflix_SE |184.08Mb
  - Relay_-ðŸ‡³ðŸ‡±NL_270 |24.95Mb
  - _272 |20.05Mb
  - Relay_-ðŸ‡¯ðŸ‡µJP_273 |14.34Mb
  - disney_GB |259.73Mb
  - _177 |31.62Mb
  - netflix_US |19.86Mb
  - _242 |40.54Mb
  - Relay_-ðŸ‡¯ðŸ‡µJP_274 |22.44Mb
  - _280 |24.48Mb
  - Relay_-ðŸ‡¯ðŸ‡µJP_277 |10.88Mb
  - disney_HK |29.06Mb
  - disney_FR |31.12Mb
  - ðŸ‡¬ðŸ‡§GB_292 |396.60Mb
  - _281 |14.17Mb
  - Relay_-ðŸ‡³ðŸ‡±NL_283 |11.12Mb
  - Relay_-ðŸ‡¸ðŸ‡¬SG_286 |11.61Mb
  - Relay_-ðŸ‡¯ðŸ‡µJP_287 |20.95Mb
  - netflix_IE |15.58Mb
  - disney_netflix_NL |206.91Mb
  - netflix_US |31.94Mb
  - disney_netflix_NL |24.69Mb
  - ðŸ‡·ðŸ‡ºRU_315 |41.56Mb
  - _209 |36.17Mb
  - ðŸ‡ºðŸ‡¸US_320 |23.92Mb
  - ðŸ‡ºðŸ‡¸US_318 |29.28Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ðŸš€ èŠ‚ç‚¹é€‰æ‹©
