port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: _234 |31.53Mb
  server: 51.79.102.253
  type: vmess
  port: 80
  uuid: 58fe1542-5290-40ad-815a-77707a81afe5
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /IOebhLMhl1CTbFHbL95myfRX2
    headers:
      Host: wrmelmwxlf.gktevlrqznwqqozy.fabpfs66gizmnojhcvqxwl.kytrcfzqla87gvgvs6c7kjnrubuh.cc
- name: disney_netflix_US |243.12Mb
  server: 172.235.33.114
  type: vmess
  port: 10001
  uuid: 442a3923-eca1-4af0-b3ff-24a7ce0af68f
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _208 |41.51Mb
  server: 163.192.49.195
  type: vmess
  port: 443
  uuid: bcb7c581-3c95-4569-a4e7-918141e91ea3
  alterId: 0
  cipher: auto
  network: http
  http-opts:
    path:
    - /
    headers:
      Host:
      - a.189.cn
  h2-opts: {}
- name: disney_netflix_DE |248.87Mb
  server: 85.195.101.122
  type: vmess
  port: 40878
  uuid: f3d4167e-b15e-4e46-82e9-9286ef93fda7
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _187 |242.62Mb
  server: 91.99.27.55
  type: vmess
  port: 8880
  uuid: f3025961-167b-4f49-e4e3-86505fe980fd
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: disney_US |43.44Mb
  server: 165.140.216.141
  type: vmess
  port: 443
  uuid: e7d72a8d-26f2-4b54-b366-0c43e0bcba7d
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: disney_netflix_US |58.14Mb
  server: 45.150.52.40
  type: vmess
  port: 443
  uuid: c31777a1-2ee6-4864-db4c-a79fcbc8188b
  alterId: 0
  cipher: auto
  network: ws
  servername: xsj011-3.facai2024.com
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /c31777a1
- name: _268 |300.20Mb
  server: 43.165.7.71
  type: vmess
  port: 19751
  uuid: 6cfa6103-5d06-40cb-f452-b563db578288
  alterId: 0
  cipher: auto
  network: http
  http-opts:
    method: GET
    path:
    - /
  h2-opts: {}
- name: _227 |41.23Mb
  server: 89.31.120.192
  type: vmess
  port: 443
  uuid: 44537595-9ccc-4b83-8936-5f9ad3229019
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: Relay_-ðŸ‡­ðŸ‡°HK_230 |17.13Mb
  server: 154.21.201.83
  type: vmess
  port: 443
  uuid: 4bf075f5-4d5e-4d39-f5ab-b32a86250f0e
  alterId: 0
  cipher: auto
  network: ws
  servername: hk.nbee.pp.ua
  http-opts: {}
  h2-opts: {}
  tls: true
  ws-opts:
    path: /aa
    headers:
      Host: hk.nbee.pp.ua
- name: _177 |29.78Mb
  server: 209.74.82.196
  type: ss
  port: 48918
  udp: true
  password: 8Ij4seif85QQHfLmR0zYkQ
  cipher: chacha20-ietf-poly1305
- name: _176 |29.98Mb
  server: 209.74.82.227
  type: ss
  port: 26515
  udp: true
  password: uA1rLP5m0mMOQ8FcxRXxgr
  cipher: chacha20-ietf-poly1305
- name: _249 |11.23Mb
  server: 130.162.152.253
  type: vmess
  port: 56867
  uuid: 5206bb9f-2cbc-44ac-de2a-471439a23707
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _256 |11.35Mb
  server: 140.238.2.250
  type: vmess
  port: 443
  uuid: 41a7089a-040b-4538-8b8d-010902405bde
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: Pool__289 |181.58Mb
  server: 70.34.218.149
  type: trojan
  port: 11930
  password: BaeSzHdfJIR13l67
  sni: softpillow.silentrocket.click
- name: disney_SG |15.01Mb
  server: 165.154.195.38
  type: vmess
  port: 35034
  uuid: 959a8caf-4cea-43d0-a548-3628e7ddfafc
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _271 |27.29Mb
  server: 8.218.105.196
  type: vmess
  port: 52752
  uuid: 925bdbf5-72be-4437-bebf-441c61089f6b
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
- name: Relay_-ðŸ‡¯ðŸ‡µJP_287 |10.88Mb
  server: 160.16.229.223
  type: trojan
  port: 3093
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: _291 |21.67Mb
  server: 160.16.124.55
  type: trojan
  port: 2890
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: disney_netflix_GB |259.73Mb
  server: koma-yt.pages.dev
  type: trojan
  port: 8443
  udp: true
  password: 8r<[9'l6hAO#8ZQi
  sni: Koma-YT.PAGeS.Dev
  ws-opts:
    path: /tro8sFW1S91B6sZrM1?ed=2560
    headers:
      Host: Koma-YT.PAGeS.Dev
  network: ws
- name: netflix_CA |24.65Mb
  server: 38.96.254.102
  type: trojan
  port: 18509
  password: .ie4rghJuMkcf0oF
  sni: shoppingmall.electricbanana.click
- name: Relay_-ðŸ‡¯ðŸ‡µJP_293 |18.59Mb
  server: 13.112.81.124
  type: trojan
  port: 3169
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: _292 |20.05Mb
  server: 160.16.196.59
  type: trojan
  port: 2890
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: Relay_-ðŸ‡¯ðŸ‡µJP_294 |19.30Mb
  server: 153.121.67.215
  type: trojan
  port: 1331
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: _295 |20.05Mb
  server: 160.16.117.182
  type: trojan
  port: 3093
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: Relay_-ðŸ‡³ðŸ‡±NL_297 |10.41Mb
  server: 160.16.214.6
  type: trojan
  port: 2890
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: netflix_NL |217.70Mb
  server: 82.38.31.184
  type: ss
  country: ðŸ‡¬ðŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: netflix_IE |274.96Mb
  server: 146.70.90.196
  type: ss
  country: ðŸ‡®ðŸ‡ªIE
  port: 17454
  password: u8gp148iz90ddoo6ms37
  cipher: aes-128-gcm
- name: netflix_NL |313.67Mb
  server: 51.15.17.169
  type: ss
  country: ðŸ‡¬ðŸ‡§GB
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ðŸ‡¬ðŸ‡§GB_307 |32.98Mb
  server: 195.66.27.148
  type: ss
  country: ðŸ‡¬ðŸ‡§GB
  port: 28709
  password: hShp1Km0NcFSmSigc8ozky
  cipher: chacha20-ietf-poly1305
- name: Relay_-ðŸ‡³ðŸ‡±NL_299 |56.74Mb
  server: 202.181.103.235
  type: trojan
  port: 2890
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: Relay_-ðŸ‡¸ðŸ‡¬SG_304 |10.87Mb
  server: 160.16.153.13
  type: trojan
  port: 3145
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: disney_NL |44.01Mb
  server: 109.71.246.210
  type: ss
  country: ðŸ‡·ðŸ‡ºRU
  port: 56689
  password: YQCSKoCF3QazW8YlvDBWA4
  cipher: chacha20-ietf-poly1305
- name: ðŸ‡ºðŸ‡¸US_341 |30.92Mb
  server: 209.74.86.194
  type: ss
  country: ðŸ‡ºðŸ‡¸US
  port: 14936
  password: ppgtoOHdm7cszGunBWBTqQ
  cipher: chacha20-ietf-poly1305
- name: disney_HK |28.98Mb
  server: 58.152.110.82
  type: trojan
  port: 443
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: _188 |57.57Mb
  server: 154.201.76.172
  type: vmess
  port: 20990
  uuid: ba50e1fe-055f-4587-fd0d-36c8d6615192
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: ðŸ‡°ðŸ‡·KR_338 |10.01Mb
  server: 146.56.112.110
  type: vmess
  country: ðŸ‡°ðŸ‡·KR
  port: 8888
  uuid: e7c302f3-90d6-42dd-9d7d-94a3683a3707
  alterId: 0
  cipher: auto
  network: tcp
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ðŸ‡ºðŸ‡¸US_342 |28.88Mb
  server: 209.74.81.149
  type: ss
  country: ðŸ‡ºðŸ‡¸US
  port: 21166
  password: q92MrrP9oJ3lMEzbQFpyuU
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_US |15.18Mb
  server: cf.fovi.tk
  type: vmess
  country: ðŸZZ
  port: 443
  uuid: bf67437e-6c90-45ca-abc2-c7240a5ce2aa
  alterId: 0
  cipher: auto
  network: ws
  servername: foxlux.fovi.tk
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /eisasqa
    headers:
      HOST: foxlux.fovi.tk
proxy-groups:
- name: ðŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - _234 |31.53Mb
  - disney_netflix_US |243.12Mb
  - _208 |41.51Mb
  - disney_netflix_DE |248.87Mb
  - _187 |242.62Mb
  - disney_US |43.44Mb
  - disney_netflix_US |58.14Mb
  - _268 |300.20Mb
  - _227 |41.23Mb
  - Relay_-ðŸ‡­ðŸ‡°HK_230 |17.13Mb
  - _177 |29.78Mb
  - _176 |29.98Mb
  - _249 |11.23Mb
  - _256 |11.35Mb
  - Pool__289 |181.58Mb
  - disney_SG |15.01Mb
  - _271 |27.29Mb
  - Relay_-ðŸ‡¯ðŸ‡µJP_287 |10.88Mb
  - _291 |21.67Mb
  - disney_netflix_GB |259.73Mb
  - netflix_CA |24.65Mb
  - Relay_-ðŸ‡¯ðŸ‡µJP_293 |18.59Mb
  - _292 |20.05Mb
  - Relay_-ðŸ‡¯ðŸ‡µJP_294 |19.30Mb
  - _295 |20.05Mb
  - Relay_-ðŸ‡³ðŸ‡±NL_297 |10.41Mb
  - netflix_NL |217.70Mb
  - netflix_IE |274.96Mb
  - netflix_NL |313.67Mb
  - ðŸ‡¬ðŸ‡§GB_307 |32.98Mb
  - Relay_-ðŸ‡³ðŸ‡±NL_299 |56.74Mb
  - Relay_-ðŸ‡¸ðŸ‡¬SG_304 |10.87Mb
  - disney_NL |44.01Mb
  - ðŸ‡ºðŸ‡¸US_341 |30.92Mb
  - disney_HK |28.98Mb
  - _188 |57.57Mb
  - ðŸ‡°ðŸ‡·KR_338 |10.01Mb
  - ðŸ‡ºðŸ‡¸US_342 |28.88Mb
  - disney_netflix_US |15.18Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - _234 |31.53Mb
  - disney_netflix_US |243.12Mb
  - _208 |41.51Mb
  - disney_netflix_DE |248.87Mb
  - _187 |242.62Mb
  - disney_US |43.44Mb
  - disney_netflix_US |58.14Mb
  - _268 |300.20Mb
  - _227 |41.23Mb
  - Relay_-ðŸ‡­ðŸ‡°HK_230 |17.13Mb
  - _177 |29.78Mb
  - _176 |29.98Mb
  - _249 |11.23Mb
  - _256 |11.35Mb
  - Pool__289 |181.58Mb
  - disney_SG |15.01Mb
  - _271 |27.29Mb
  - Relay_-ðŸ‡¯ðŸ‡µJP_287 |10.88Mb
  - _291 |21.67Mb
  - disney_netflix_GB |259.73Mb
  - netflix_CA |24.65Mb
  - Relay_-ðŸ‡¯ðŸ‡µJP_293 |18.59Mb
  - _292 |20.05Mb
  - Relay_-ðŸ‡¯ðŸ‡µJP_294 |19.30Mb
  - _295 |20.05Mb
  - Relay_-ðŸ‡³ðŸ‡±NL_297 |10.41Mb
  - netflix_NL |217.70Mb
  - netflix_IE |274.96Mb
  - netflix_NL |313.67Mb
  - ðŸ‡¬ðŸ‡§GB_307 |32.98Mb
  - Relay_-ðŸ‡³ðŸ‡±NL_299 |56.74Mb
  - Relay_-ðŸ‡¸ðŸ‡¬SG_304 |10.87Mb
  - disney_NL |44.01Mb
  - ðŸ‡ºðŸ‡¸US_341 |30.92Mb
  - disney_HK |28.98Mb
  - _188 |57.57Mb
  - ðŸ‡°ðŸ‡·KR_338 |10.01Mb
  - ðŸ‡ºðŸ‡¸US_342 |28.88Mb
  - disney_netflix_US |15.18Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ðŸš€ èŠ‚ç‚¹é€‰æ‹©
