port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: ' |72.57Mb'
  server: 103.35.189.136
  type: ss
  port: 443
  udp: true
  password: SS2QvbC9nqLp2sXXZo0BVy4slcErRuCt
  cipher: chacha20-ietf-poly1305
- name: ' |24.01Mb'
  server: 137.184.174.93
  type: ss
  port: 8080
  udp: true
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: ' |16.92Mb'
  server: 156.146.38.167
  type: ss
  port: 443
  udp: true
  password: shadowsocks
  cipher: aes-128-gcm
- name: ' |19.43Mb'
  server: 156.146.38.169
  type: ss
  port: 443
  udp: true
  password: shadowsocks
  cipher: aes-128-gcm
- name: ' |19.38Mb'
  server: 156.146.38.170
  type: ss
  port: 443
  udp: true
  password: shadowsocks
  cipher: aes-128-gcm
- name: ' |37.66Mb'
  server: 45.87.175.22
  type: ss
  port: 8080
  udp: true
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: ' |32.91Mb'
  server: 151.242.251.147
  type: ss
  port: 8080
  password: QCXDxuDlTTMD7jtgHUjIoj
  cipher: chacha20-ietf-poly1305
- name: ' |10.59Mb'
  server: 212.224.125.154
  type: ss
  port: 57456
  udp: true
  password: 6a85b249286a74a9
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_GB |256.52Mb
  server: 141.98.101.178
  type: ss
  port: 443
  udp: true
  password: shadowsocks
  cipher: aes-128-gcm
- name: ' |62.12Mb'
  server: 15.157.66.237
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: disney_MX |28.05Mb
  server: 38.165.231.25
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: netflix_NL |202.31Mb
  server: 151.242.251.142
  type: ss
  port: 8080
  udp: true
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ' |207.77Mb'
  server: 45.87.175.178
  type: ss
  port: 8080
  udp: true
  password: QCXDxuDlTTMD7jtgHUjIoj
  cipher: chacha20-ietf-poly1305
- name: ' |12.23Mb'
  server: 138.186.143.32
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ' |188.82Mb'
  server: 82.38.31.214
  type: ss
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: Relay_ |135.34Mb
  server: 151.242.251.131
  type: ss
  port: 8080
  password: QCXDxuDlTTMD7jtgHUjIoj
  cipher: chacha20-ietf-poly1305
- name: ' |147.24Mb'
  server: 193.29.139.206
  type: ss
  port: 8080
  udp: true
  password: 4a2rfixophdjffa8KVA4Aa
  cipher: chacha20-ietf-poly1305
- name: ' |44.00Mb'
  server: 147.78.0.182
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ' |24.04Mb'
  server: 185.192.124.188
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: _483 |11.98Mb
  server: 45.87.175.174
  type: ss
  port: 8080
  udp: true
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ' |23.43Mb'
  server: 172.105.199.111
  type: ss
  port: 8080
  udp: true
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: disney_US |65.89Mb
  server: 79.127.200.162
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ' |41.82Mb'
  server: 104.192.226.106
  type: ss
  port: 990
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: chacha20-ietf-poly1305
- name: ' |170.39Mb'
  server: 82.38.31.179
  type: ss
  port: 8080
  udp: true
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ' |49.77Mb'
  server: 173.234.29.2
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ' |12.21Mb'
  server: 192.71.249.78
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ' |18.61Mb'
  server: 119.59.98.58
  type: ss
  port: 990
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: chacha20-ietf-poly1305
- name: ' |245.86Mb'
  server: 82.38.31.194
  type: ss
  port: 8080
  udp: true
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ' |29.80Mb'
  server: 119.59.98.58
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: Relay_ |68.80Mb
  server: 79.127.200.169
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ' |276.78Mb'
  server: 5.181.21.246
  type: ss
  port: 443
  udp: true
  password: gKYygTcRYhc3skc2x6tZ073lYz0DnieX
  cipher: chacha20-ietf-poly1305
- name: ' |127.90Mb'
  server: 45.87.175.28
  type: ss
  port: 8080
  udp: true
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: ' |141.58Mb'
  server: 151.242.251.152
  type: ss
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ' |43.31Mb'
  server: 173.244.56.6
  type: ss
  port: 443
  udp: true
  password: shadowsocks
  cipher: aes-128-gcm
- name: _498 |79.48Mb
  server: 38.54.57.90
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: _531 |70.05Mb
  server: 172.233.229.91
  type: vmess
  port: 14102
  udp: true
  uuid: 27ba87fc-583f-4763-9060-83cf0b9264db
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: _532 |38.43Mb
  server: 47.253.228.138
  type: vmess
  port: 22524
  uuid: 80845fcc-f862-45fe-c1d3-0a7120373712
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
- name: disney_netflix_GB |52.64Mb
  server: 146.70.61.37
  type: ss
  port: 8080
  udp: true
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: ' |171.86Mb'
  server: 51.15.23.166
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ' |15.88Mb'
  server: 45.87.175.197
  type: ss
  port: 8080
  udp: true
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ' |42.89Mb'
  server: 156.59.243.6
  type: ss
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _536 |31.54Mb
  server: 216.227.168.157
  type: vmess
  port: 45247
  uuid: 469e0b31-30c3-4dab-800d-711232634ce1
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: disney_US |44.31Mb
  server: 165.140.216.141
  type: vmess
  port: 443
  uuid: e7d72a8d-26f2-4b54-b366-0c43e0bcba7d
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _535 |40.40Mb
  server: 154.29.157.189
  type: vmess
  port: 38152
  uuid: b8ce19b1-4b15-41f9-a206-11957cc902d4
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
- name: _555 |20.29Mb
  server: 15.235.41.200
  type: vmess
  port: 80
  uuid: 58fe1542-5290-40ad-815a-77707a81afe5
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /IOebhLMhl1CTbFHbL95myfRX2
- name: disney_DO |57.17Mb
  server: xcf017-2.facai2024.com
  type: vmess
  port: 443
  uuid: db5208f7-b9b6-4396-b36e-b05b2153f595
  alterId: 0
  cipher: auto
  network: ws
  servername: xcf017-2.facai2024.com
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /db5208f7
- name: ' |11.81Mb'
  server: 172.237.74.36
  type: ss
  port: 443
  udp: true
  password: Dk0XrU/n+SB84g0k+mX4zdy5HVVhuAUP6pCaldJxQjY=
  cipher: aes-256-gcm
- name: Relay_-ğŸ‡ºğŸ‡¸US_560 |40.20Mb
  server: 38.14.99.179
  type: vmess
  port: 59807
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _550 |15.73Mb
  server: 103.160.100.140
  type: vmess
  port: 53046
  uuid: d0bfd418-0575-49a8-de55-38dd7fa72b6f
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
- name: ' |11.56Mb'
  server: pupas-shirting-unsung.freesocks.work
  type: ss
  port: 443
  udp: true
  password: p78naCf2EfOlRSLTX0wFVx
  cipher: chacha20-ietf-poly1305
- name: disney_US |11.22Mb
  server: 206.119.191.9
  type: vmess
  port: 7100
  uuid: 10853485-26e1-477b-d257-58a3f4873db3
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
- name: _547 |10.07Mb
  server: 54.206.192.9
  type: vmess
  port: 16407
  uuid: 08f45028-1db6-4e93-bf51-d344b6c71e19
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _557 |40.66Mb
  server: 89.31.120.192
  type: vmess
  port: 443
  uuid: 44537595-9ccc-4b83-8936-5f9ad3229019
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: Relay_-ğŸ‡¯ğŸ‡µJP_581 |12.46Mb
  server: 153.121.67.215
  type: trojan
  port: 3093
  password: 44e660b0ee21cf3ac66aee2c08af85d2
  sni: www.nintendogames.net
- name: _588 |10.38Mb
  server: 160.16.116.227
  type: trojan
  port: 2760
  password: 44e660b0ee21cf3ac66aee2c08af85d2
  sni: www.nintendogames.net
  skip-cert-verify: true
- name: _629 |10.98Mb
  server: 160.16.57.238
  type: trojan
  port: 2760
  password: 44e660b0ee21cf3ac66aee2c08af85d2
  sni: www.nintendogames.net
  skip-cert-verify: true
- name: Relay_-ğŸ‡¯ğŸ‡µJP_642 |20.49Mb
  server: 160.16.107.37
  type: trojan
  port: 3093
  password: 44e660b0ee21cf3ac66aee2c08af85d2
  sni: www.nintendogames.net
- name: _643 |10.18Mb
  server: 160.16.81.84
  type: trojan
  port: 2760
  password: 44e660b0ee21cf3ac66aee2c08af85d2
  sni: www.nintendogames.net
  skip-cert-verify: true
- name: Pool__663 |744.27Mb
  server: 70.34.218.149
  type: trojan
  port: 11930
  password: BaeSzHdfJIR13l67
  sni: softpillow.silentrocket.click
- name: Relay_-ğŸ‡¯ğŸ‡µJP_644 |18.07Mb
  server: 160.16.107.37
  type: trojan
  port: 3169
  password: 44e660b0ee21cf3ac66aee2c08af85d2
  sni: www.nintendogames.net
- name: ğŸ‡§ğŸ‡·BR |23.84Mb
  server: 185.192.124.188
  type: ss
  country: ğŸ‡§ğŸ‡·BR
  port: 990
  password: f8f7aCzcPKbsF8p3
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¨ğŸ‡¦CA |28.14Mb
  server: 185.213.23.63
  type: ss
  country: ğŸ‡¨ğŸ‡¦CA
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _660 |10.77Mb
  server: 160.16.63.16
  type: trojan
  port: 2760
  password: 44e660b0ee21cf3ac66aee2c08af85d2
  sni: www.nintendogames.net
  skip-cert-verify: true
- name: disney_DE |257.99Mb
  server: 89.163.140.136
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: disney_HK |28.16Mb
  server: 219.79.214.159
  type: trojan
  port: 443
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: ğŸ‡¬ğŸ‡§GB |111.21Mb
  server: 141.98.101.182
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: shadowsocks
  cipher: aes-128-gcm
- name: netflix_NL |155.08Mb
  server: 82.38.31.208
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹ LT |18.27Mb
  server: 45.87.175.178
  type: ss
  country: ğŸ‡±ğŸ‡¹ LT
  port: 8080
  password: 4a2rfixophdjffa8KVA4Aa
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹ LT |10.62Mb
  server: 45.87.175.178
  type: ss
  country: ğŸ‡±ğŸ‡¹ LT
  port: 8080
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹ LT |11.01Mb
  server: 45.87.175.178
  type: ss
  country: ğŸ‡±ğŸ‡¹ LT
  port: 8080
  password: 1RWwXhwfAB5gAEozU4G2Pg
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT |41.80Mb
  server: 45.87.175.180
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: QCXDxuDlTTMD7jtgHUjIoj
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT |221.88Mb
  server: 45.87.175.185
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT |63.35Mb
  server: 45.87.175.183
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡­ğŸ‡°HK_722 |113.47Mb
  server: 8.218.105.196
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 52752
  uuid: 925bdbf5-72be-4437-bebf-441c61089f6b
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_HK |24.79Mb
  server: 45.207.157.29
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 13852
  uuid: 845764df-ecb3-4b13-bed2-bf1551b68e9a
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡²ğŸ‡½MX_739 |40.76Mb
  server: 216.238.87.47
  type: vmess
  country: ğŸ‡²ğŸ‡½MX
  port: 27502
  uuid: b8155ce4-7e08-4c40-800f-8671312b7124
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡²ğŸ‡½MX_740 |41.11Mb
  server: 216.238.86.158
  type: vmess
  country: ğŸ‡²ğŸ‡½MX
  port: 34460
  uuid: 90be214d-048c-4ea2-a602-b8e4d4e51e36
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡±ğŸ‡¹LT |77.63Mb
  server: 45.87.175.185
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: ' |103.40Mb'
  server: 82.38.31.176
  type: ss
  port: 8080
  udp: true
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: disney_LV |21.41Mb
  server: 46.183.217.204
  type: ss
  country: ğŸ‡±ğŸ‡» LV
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_763 |39.36Mb
  server: 64.69.40.135
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 10678
  uuid: c5aec222-3b11-4af8-f01f-f9145b0caabb
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: netflix_NL |44.23Mb
  server: 178.23.190.238
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 443
  password: uo7EbtqIwgZXXHmMv5LbLcOxptyPlNkh
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_762 |40.84Mb
  server: 38.14.99.163
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 59807
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: auto
  network: tcp
  servername: 38.14.99.163
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡µğŸ‡¹PT |58.84Mb
  server: 185.113.143.186
  type: ss
  country: ğŸ‡µğŸ‡¹PT
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸZZ_766 |101.01Mb
  server: hgtrojan.zabc.net
  type: vmess
  country: ğŸZZ
  port: 2083
  uuid: e6395c20-4571-4b34-d6b1-55a5d36e49ea
  alterId: 0
  cipher: auto
  network: ws
  servername: hgtrojan.zabc.net
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /e6395c20
    headers:
      HOST: hgtrojan.zabc.net
- name: ğŸ‡¹ğŸ‡¼TW_749 |28.64Mb
  server: 38.54.107.101
  type: ss
  country: ğŸ‡¹ğŸ‡¼TW
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸ‡¯ğŸ‡µJP-ğŸ‡¯ğŸ‡µJP_726 |11.15Mb
  server: xray.kk37005.tk
  type: vmess
  country: ğŸ‡¯ğŸ‡µJP
  port: 55919
  uuid: 2e7548bb-7c5b-4d97-d64d-1b2fe4050089
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - ' |72.57Mb'
  - ' |24.01Mb'
  - ' |16.92Mb'
  - ' |19.43Mb'
  - ' |19.38Mb'
  - ' |37.66Mb'
  - ' |32.91Mb'
  - ' |10.59Mb'
  - disney_netflix_GB |256.52Mb
  - ' |62.12Mb'
  - disney_MX |28.05Mb
  - netflix_NL |202.31Mb
  - ' |207.77Mb'
  - ' |12.23Mb'
  - ' |188.82Mb'
  - Relay_ |135.34Mb
  - ' |147.24Mb'
  - ' |44.00Mb'
  - ' |24.04Mb'
  - _483 |11.98Mb
  - ' |23.43Mb'
  - disney_US |65.89Mb
  - ' |41.82Mb'
  - ' |170.39Mb'
  - ' |49.77Mb'
  - ' |12.21Mb'
  - ' |18.61Mb'
  - ' |245.86Mb'
  - ' |29.80Mb'
  - Relay_ |68.80Mb
  - ' |276.78Mb'
  - ' |127.90Mb'
  - ' |141.58Mb'
  - ' |43.31Mb'
  - _498 |79.48Mb
  - _531 |70.05Mb
  - _532 |38.43Mb
  - disney_netflix_GB |52.64Mb
  - ' |171.86Mb'
  - ' |15.88Mb'
  - ' |42.89Mb'
  - _536 |31.54Mb
  - disney_US |44.31Mb
  - _535 |40.40Mb
  - _555 |20.29Mb
  - disney_DO |57.17Mb
  - ' |11.81Mb'
  - Relay_-ğŸ‡ºğŸ‡¸US_560 |40.20Mb
  - _550 |15.73Mb
  - ' |11.56Mb'
  - disney_US |11.22Mb
  - _547 |10.07Mb
  - _557 |40.66Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_581 |12.46Mb
  - _588 |10.38Mb
  - _629 |10.98Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_642 |20.49Mb
  - _643 |10.18Mb
  - Pool__663 |744.27Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_644 |18.07Mb
  - ğŸ‡§ğŸ‡·BR |23.84Mb
  - ğŸ‡¨ğŸ‡¦CA |28.14Mb
  - _660 |10.77Mb
  - disney_DE |257.99Mb
  - disney_HK |28.16Mb
  - ğŸ‡¬ğŸ‡§GB |111.21Mb
  - netflix_NL |155.08Mb
  - ğŸ‡±ğŸ‡¹ LT |18.27Mb
  - ğŸ‡±ğŸ‡¹ LT |10.62Mb
  - ğŸ‡±ğŸ‡¹ LT |11.01Mb
  - ğŸ‡±ğŸ‡¹LT |41.80Mb
  - ğŸ‡±ğŸ‡¹LT |221.88Mb
  - ğŸ‡±ğŸ‡¹LT |63.35Mb
  - ğŸ‡­ğŸ‡°HK_722 |113.47Mb
  - disney_HK |24.79Mb
  - ğŸ‡²ğŸ‡½MX_739 |40.76Mb
  - ğŸ‡²ğŸ‡½MX_740 |41.11Mb
  - ğŸ‡±ğŸ‡¹LT |77.63Mb
  - ' |103.40Mb'
  - disney_LV |21.41Mb
  - ğŸ‡ºğŸ‡¸US_763 |39.36Mb
  - netflix_NL |44.23Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_762 |40.84Mb
  - ğŸ‡µğŸ‡¹PT |58.84Mb
  - ğŸZZ_766 |101.01Mb
  - ğŸ‡¹ğŸ‡¼TW_749 |28.64Mb
  - Relay_ğŸ‡¯ğŸ‡µJP-ğŸ‡¯ğŸ‡µJP_726 |11.15Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - ' |72.57Mb'
  - ' |24.01Mb'
  - ' |16.92Mb'
  - ' |19.43Mb'
  - ' |19.38Mb'
  - ' |37.66Mb'
  - ' |32.91Mb'
  - ' |10.59Mb'
  - disney_netflix_GB |256.52Mb
  - ' |62.12Mb'
  - disney_MX |28.05Mb
  - netflix_NL |202.31Mb
  - ' |207.77Mb'
  - ' |12.23Mb'
  - ' |188.82Mb'
  - Relay_ |135.34Mb
  - ' |147.24Mb'
  - ' |44.00Mb'
  - ' |24.04Mb'
  - _483 |11.98Mb
  - ' |23.43Mb'
  - disney_US |65.89Mb
  - ' |41.82Mb'
  - ' |170.39Mb'
  - ' |49.77Mb'
  - ' |12.21Mb'
  - ' |18.61Mb'
  - ' |245.86Mb'
  - ' |29.80Mb'
  - Relay_ |68.80Mb
  - ' |276.78Mb'
  - ' |127.90Mb'
  - ' |141.58Mb'
  - ' |43.31Mb'
  - _498 |79.48Mb
  - _531 |70.05Mb
  - _532 |38.43Mb
  - disney_netflix_GB |52.64Mb
  - ' |171.86Mb'
  - ' |15.88Mb'
  - ' |42.89Mb'
  - _536 |31.54Mb
  - disney_US |44.31Mb
  - _535 |40.40Mb
  - _555 |20.29Mb
  - disney_DO |57.17Mb
  - ' |11.81Mb'
  - Relay_-ğŸ‡ºğŸ‡¸US_560 |40.20Mb
  - _550 |15.73Mb
  - ' |11.56Mb'
  - disney_US |11.22Mb
  - _547 |10.07Mb
  - _557 |40.66Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_581 |12.46Mb
  - _588 |10.38Mb
  - _629 |10.98Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_642 |20.49Mb
  - _643 |10.18Mb
  - Pool__663 |744.27Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_644 |18.07Mb
  - ğŸ‡§ğŸ‡·BR |23.84Mb
  - ğŸ‡¨ğŸ‡¦CA |28.14Mb
  - _660 |10.77Mb
  - disney_DE |257.99Mb
  - disney_HK |28.16Mb
  - ğŸ‡¬ğŸ‡§GB |111.21Mb
  - netflix_NL |155.08Mb
  - ğŸ‡±ğŸ‡¹ LT |18.27Mb
  - ğŸ‡±ğŸ‡¹ LT |10.62Mb
  - ğŸ‡±ğŸ‡¹ LT |11.01Mb
  - ğŸ‡±ğŸ‡¹LT |41.80Mb
  - ğŸ‡±ğŸ‡¹LT |221.88Mb
  - ğŸ‡±ğŸ‡¹LT |63.35Mb
  - ğŸ‡­ğŸ‡°HK_722 |113.47Mb
  - disney_HK |24.79Mb
  - ğŸ‡²ğŸ‡½MX_739 |40.76Mb
  - ğŸ‡²ğŸ‡½MX_740 |41.11Mb
  - ğŸ‡±ğŸ‡¹LT |77.63Mb
  - ' |103.40Mb'
  - disney_LV |21.41Mb
  - ğŸ‡ºğŸ‡¸US_763 |39.36Mb
  - netflix_NL |44.23Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_762 |40.84Mb
  - ğŸ‡µğŸ‡¹PT |58.84Mb
  - ğŸZZ_766 |101.01Mb
  - ğŸ‡¹ğŸ‡¼TW_749 |28.64Mb
  - Relay_ğŸ‡¯ğŸ‡µJP-ğŸ‡¯ğŸ‡µJP_726 |11.15Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
