port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: ğŸ‡¨ğŸ‡¦CA_58 |16.34Mb
  server: 138.197.153.10
  type: ss
  country: ğŸ‡¨ğŸ‡¦CA
  port: 8080
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: ğŸ‡¨ğŸ‡¦CA_60 |151.74Mb
  server: 147.182.146.81
  type: ss
  country: ğŸ‡¨ğŸ‡¦CA
  port: 8080
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: ğŸ‡¨ğŸ‡¦CA_57 |14.85Mb
  server: 79.127.200.162
  type: ss
  country: ğŸ‡¨ğŸ‡¦CA
  port: 990
  password: f8f7aCzcPKbsF8p3
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¨ğŸ‡¦CA_61 |55.53Mb
  server: 68.183.193.204
  type: ss
  country: ğŸ‡¨ğŸ‡¦CA
  port: 8080
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: _40 |38.15Mb
  server: 62.100.205.100
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _35 |12.64Mb
  server: 94.156.250.122
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _45 |13.73Mb
  server: 38.165.231.25
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _48 |10.50Mb
  server: 185.163.204.94
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _33 |12.23Mb
  server: 91.219.237.163
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: Relay_-ğŸ‡©ğŸ‡ªDE_52 |10.15Mb
  server: 193.135.174.135
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡©ğŸ‡ªDE_69 |56.25Mb
  server: 81.19.141.45
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 443
  password: EEIh3YZZ5QZRvJM6C04YSM
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡©ğŸ‡ªDE_70 |11.90Mb
  server: 81.19.141.45
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 443
  password: GolXNbBG1EfcTZhaccBOAG
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡©ğŸ‡ªDE_73 |13.06Mb
  server: 93.186.201.64
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 57456
  password: c40641c1f89e7acb
  cipher: chacha20-ietf-poly1305
- name: _36 |31.20Mb
  server: 185.93.173.60
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¨ğŸ‡´CO_63 |11.23Mb
  server: 181.119.30.20
  type: ss
  country: ğŸ‡¨ğŸ‡´CO
  port: 990
  password: f8f7aCzcPKbsF8p3
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡©ğŸ‡ªDE_90 |17.76Mb
  server: 3.123.25.149
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡«ğŸ‡·FR_128 |105.26Mb
  server: 57.129.64.238
  type: vmess
  country: ğŸ‡«ğŸ‡·FR
  port: 443
  uuid: 03fcc618-b93d-6796-6aed-8a38c975d581
  alterId: 0
  cipher: auto
  network: ws
  servername: kapelleng.com
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /linkvws
    headers:
      HOST: kapelleng.com
- name: ğŸ‡©ğŸ‡ªDE_76 |32.63Mb
  server: 81.19.141.45
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 443
  password: 0dEg9sKUtuROxn3zaNogzU
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡©ğŸ‡ªDE_82 |189.47Mb
  server: 81.19.141.45
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 443
  password: rC23nT4eVDHF06wmuyvSUe
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ªğŸ‡¸ES_108 |109.52Mb
  server: 194.87.45.189
  type: ss
  country: ğŸ‡ªğŸ‡¸ES
  port: 443
  password: jiMMLSYwAagbBvDq511rG3
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_140 |54.28Mb
  server: 89.185.84.185
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: WhUYn0yZ6bLrILxzItfxSI
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_134 |146.36Mb
  server: 78.129.140.11
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: DpBNt4YF9cIcVnWOcJqRgy
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_143 |10.03Mb
  server: 89.185.84.185
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: m8V5Orkxu2ob8LH24OFobn
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_145 |20.83Mb
  server: 89.185.84.185
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: tVBUTDznmHpV3lpKzbw2Nl
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_146 |11.95Mb
  server: 89.185.84.185
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: bmoj6orLj0ipdovNVUJzVL
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_148 |54.52Mb
  server: 89.185.84.185
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: APL3I9lSc4Gs9DzaHuBV0u
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_149 |178.38Mb
  server: 146.70.61.37
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: Pool_ğŸ‡¬ğŸ‡§GB_150 |13.37Mb
  server: 79.127.233.170
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ğŸ‡¬ğŸ‡§GB_152 |19.17Mb
  server: 89.185.84.185
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: FXjMQIem0uShGvRzOpfyib
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_151 |10.03Mb
  server: 141.98.101.179
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: shadowsocks
  cipher: aes-128-gcm
- name: ğŸ‡¬ğŸ‡§GB_153 |20.44Mb
  server: 89.185.84.185
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: iEc68ruj1qOx8hjh1KWZmc
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡®ğŸ‡¶IQ_162 |41.36Mb
  server: 81.90.31.219
  type: ss
  country: ğŸ‡®ğŸ‡¶IQ
  port: 443
  password: H2WVYuCnBXrb7KfEYuPWYm
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_184 |13.37Mb
  server: 45.87.175.181
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: 4a2rfixophdjffa8KVA4Aa
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡®ğŸ‡¶IQ_163 |48.98Mb
  server: 81.90.31.219
  type: ss
  country: ğŸ‡®ğŸ‡¶IQ
  port: 443
  password: iRZgNTcrf657aaZpPkCFWu
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡®ğŸ‡¶IQ_166 |84.40Mb
  server: 81.90.31.219
  type: ss
  country: ğŸ‡®ğŸ‡¶IQ
  port: 443
  password: KtWqs1I6a2iaGXlhVXz6pp
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡³ğŸ‡±NL_195 |17.43Mb
  server: 193.29.139.188
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 8080
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡µğŸ‡¦PA_200 |13.98Mb
  server: 138.186.142.81
  type: ss
  country: ğŸ‡µğŸ‡¦PA
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_268 |12.61Mb
  server: 64.74.163.218
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 990
  password: f8f7aCzcPKbsF8p3
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡µğŸ‡±PL_237 |10.12Mb
  server: 217.30.10.70
  type: ss
  country: ğŸ‡µğŸ‡±PL
  port: 9060
  password: ueLXVkvh4hckhErQ
  cipher: aes-256-cfb
- name: ğŸ‡ºğŸ‡¸US_282 |14.62Mb
  server: 13.59.110.241
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡ºğŸ‡¸US_267 |15.19Mb
  server: 104.192.226.106
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ğŸ‡¯ğŸ‡µJP_175 |11.49Mb
  server: 45.32.45.45
  type: vmess
  country: ğŸ‡¯ğŸ‡µJP
  port: 14760
  uuid: dbf7a6e4-d518-4f9b-a55e-27ef892ffac1
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡ºğŸ‡¸US_274 |33.94Mb
  server: 104.192.226.106
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 990
  password: f8f7aCzcPKbsF8p3
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡³ğŸ‡±NL_270 |18.59Mb
  server: 45.158.171.70
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 8080
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡µğŸ‡±PL_244 |136.13Mb
  server: 217.30.10.18
  type: ss
  country: ğŸ‡µğŸ‡±PL
  port: 9026
  password: QWDDvVE9npNurQfA
  cipher: aes-256-cfb
- name: ğŸ‡ºğŸ‡¸US_292 |562.84Mb
  server: 154.29.158.139
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 12299
  uuid: cccfe679-fbd0-4402-caf2-67e919db436f
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_298 |55.76Mb
  server: 193.124.24.247
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 6514
  uuid: c362d735-01a8-48eb-baa2-ae7aa63bfdc3
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡ºğŸ‡¸US_293 |879.64Mb
  server: 38.34.24.196
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 20522
  uuid: f65ae5d8-f779-4ab2-8ba3-e4d46d34ef9d
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
  ws-opts:
    path: /telegram_@sswia
- name: ğŸ‡°ğŸ‡·KR_176 |94.74Mb
  server: 221.139.79.57
  type: ss
  country: ğŸ‡°ğŸ‡·KR
  port: 37008
  password: qwerREWQ@@
  cipher: aes-256-cfb
- name: ğŸ‡ºğŸ‡¸US_294 |59.98Mb
  server: 2.59.62.63
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 19365
  uuid: 9583a647-b0ba-47b0-d4b0-4e12a0201d67
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡ºğŸ‡¸US_273 |28.96Mb
  server: 149.22.87.240
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: shadowsocks
  cipher: aes-128-gcm
- name: Pool_ğŸ‡­ğŸ‡°HK_158 |433.00Mb
  server: 150.107.46.21
  type: ssr
  country: ğŸ‡­ğŸ‡°HK
  port: 8083
  password: iFqnzSscN
  cipher: aes-256-cfb
  protocol: origin
  obfs: tls1.2_ticket_auth
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - ğŸ‡¨ğŸ‡¦CA_58 |16.34Mb
  - ğŸ‡¨ğŸ‡¦CA_60 |151.74Mb
  - ğŸ‡¨ğŸ‡¦CA_57 |14.85Mb
  - ğŸ‡¨ğŸ‡¦CA_61 |55.53Mb
  - _40 |38.15Mb
  - _35 |12.64Mb
  - _45 |13.73Mb
  - _48 |10.50Mb
  - _33 |12.23Mb
  - Relay_-ğŸ‡©ğŸ‡ªDE_52 |10.15Mb
  - ğŸ‡©ğŸ‡ªDE_69 |56.25Mb
  - ğŸ‡©ğŸ‡ªDE_70 |11.90Mb
  - ğŸ‡©ğŸ‡ªDE_73 |13.06Mb
  - _36 |31.20Mb
  - ğŸ‡¨ğŸ‡´CO_63 |11.23Mb
  - ğŸ‡©ğŸ‡ªDE_90 |17.76Mb
  - ğŸ‡«ğŸ‡·FR_128 |105.26Mb
  - ğŸ‡©ğŸ‡ªDE_76 |32.63Mb
  - ğŸ‡©ğŸ‡ªDE_82 |189.47Mb
  - ğŸ‡ªğŸ‡¸ES_108 |109.52Mb
  - ğŸ‡¬ğŸ‡§GB_140 |54.28Mb
  - ğŸ‡¬ğŸ‡§GB_134 |146.36Mb
  - ğŸ‡¬ğŸ‡§GB_143 |10.03Mb
  - ğŸ‡¬ğŸ‡§GB_145 |20.83Mb
  - ğŸ‡¬ğŸ‡§GB_146 |11.95Mb
  - ğŸ‡¬ğŸ‡§GB_148 |54.52Mb
  - ğŸ‡¬ğŸ‡§GB_149 |178.38Mb
  - Pool_ğŸ‡¬ğŸ‡§GB_150 |13.37Mb
  - ğŸ‡¬ğŸ‡§GB_152 |19.17Mb
  - ğŸ‡¬ğŸ‡§GB_151 |10.03Mb
  - ğŸ‡¬ğŸ‡§GB_153 |20.44Mb
  - ğŸ‡®ğŸ‡¶IQ_162 |41.36Mb
  - ğŸ‡±ğŸ‡¹LT_184 |13.37Mb
  - ğŸ‡®ğŸ‡¶IQ_163 |48.98Mb
  - ğŸ‡®ğŸ‡¶IQ_166 |84.40Mb
  - ğŸ‡³ğŸ‡±NL_195 |17.43Mb
  - ğŸ‡µğŸ‡¦PA_200 |13.98Mb
  - ğŸ‡ºğŸ‡¸US_268 |12.61Mb
  - ğŸ‡µğŸ‡±PL_237 |10.12Mb
  - ğŸ‡ºğŸ‡¸US_282 |14.62Mb
  - ğŸ‡ºğŸ‡¸US_267 |15.19Mb
  - ğŸ‡¯ğŸ‡µJP_175 |11.49Mb
  - ğŸ‡ºğŸ‡¸US_274 |33.94Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡³ğŸ‡±NL_270 |18.59Mb
  - ğŸ‡µğŸ‡±PL_244 |136.13Mb
  - ğŸ‡ºğŸ‡¸US_292 |562.84Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_298 |55.76Mb
  - ğŸ‡ºğŸ‡¸US_293 |879.64Mb
  - ğŸ‡°ğŸ‡·KR_176 |94.74Mb
  - ğŸ‡ºğŸ‡¸US_294 |59.98Mb
  - ğŸ‡ºğŸ‡¸US_273 |28.96Mb
  - Pool_ğŸ‡­ğŸ‡°HK_158 |433.00Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - ğŸ‡¨ğŸ‡¦CA_58 |16.34Mb
  - ğŸ‡¨ğŸ‡¦CA_60 |151.74Mb
  - ğŸ‡¨ğŸ‡¦CA_57 |14.85Mb
  - ğŸ‡¨ğŸ‡¦CA_61 |55.53Mb
  - _40 |38.15Mb
  - _35 |12.64Mb
  - _45 |13.73Mb
  - _48 |10.50Mb
  - _33 |12.23Mb
  - Relay_-ğŸ‡©ğŸ‡ªDE_52 |10.15Mb
  - ğŸ‡©ğŸ‡ªDE_69 |56.25Mb
  - ğŸ‡©ğŸ‡ªDE_70 |11.90Mb
  - ğŸ‡©ğŸ‡ªDE_73 |13.06Mb
  - _36 |31.20Mb
  - ğŸ‡¨ğŸ‡´CO_63 |11.23Mb
  - ğŸ‡©ğŸ‡ªDE_90 |17.76Mb
  - ğŸ‡«ğŸ‡·FR_128 |105.26Mb
  - ğŸ‡©ğŸ‡ªDE_76 |32.63Mb
  - ğŸ‡©ğŸ‡ªDE_82 |189.47Mb
  - ğŸ‡ªğŸ‡¸ES_108 |109.52Mb
  - ğŸ‡¬ğŸ‡§GB_140 |54.28Mb
  - ğŸ‡¬ğŸ‡§GB_134 |146.36Mb
  - ğŸ‡¬ğŸ‡§GB_143 |10.03Mb
  - ğŸ‡¬ğŸ‡§GB_145 |20.83Mb
  - ğŸ‡¬ğŸ‡§GB_146 |11.95Mb
  - ğŸ‡¬ğŸ‡§GB_148 |54.52Mb
  - ğŸ‡¬ğŸ‡§GB_149 |178.38Mb
  - Pool_ğŸ‡¬ğŸ‡§GB_150 |13.37Mb
  - ğŸ‡¬ğŸ‡§GB_152 |19.17Mb
  - ğŸ‡¬ğŸ‡§GB_151 |10.03Mb
  - ğŸ‡¬ğŸ‡§GB_153 |20.44Mb
  - ğŸ‡®ğŸ‡¶IQ_162 |41.36Mb
  - ğŸ‡±ğŸ‡¹LT_184 |13.37Mb
  - ğŸ‡®ğŸ‡¶IQ_163 |48.98Mb
  - ğŸ‡®ğŸ‡¶IQ_166 |84.40Mb
  - ğŸ‡³ğŸ‡±NL_195 |17.43Mb
  - ğŸ‡µğŸ‡¦PA_200 |13.98Mb
  - ğŸ‡ºğŸ‡¸US_268 |12.61Mb
  - ğŸ‡µğŸ‡±PL_237 |10.12Mb
  - ğŸ‡ºğŸ‡¸US_282 |14.62Mb
  - ğŸ‡ºğŸ‡¸US_267 |15.19Mb
  - ğŸ‡¯ğŸ‡µJP_175 |11.49Mb
  - ğŸ‡ºğŸ‡¸US_274 |33.94Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡³ğŸ‡±NL_270 |18.59Mb
  - ğŸ‡µğŸ‡±PL_244 |136.13Mb
  - ğŸ‡ºğŸ‡¸US_292 |562.84Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_298 |55.76Mb
  - ğŸ‡ºğŸ‡¸US_293 |879.64Mb
  - ğŸ‡°ğŸ‡·KR_176 |94.74Mb
  - ğŸ‡ºğŸ‡¸US_294 |59.98Mb
  - ğŸ‡ºğŸ‡¸US_273 |28.96Mb
  - Pool_ğŸ‡­ğŸ‡°HK_158 |433.00Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
