port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: _130
  server: mla10.maliaojc.top
  type: hysteria2
  port: 58330
  password: 41108c8a-3115-4076-b318-fdccefe813bd
  sni: mla10.maliaojc.top
  skip-cert-verify: true
- name: disney_US
  server: 15.204.247.49
  type: ss
  port: 12000
  password: 8JCsPssfgS8tiRwiMlhARg==
  cipher: aes-256-gcm
- name: _216
  server: 18.203.127.31
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: _218
  server: 195.154.119.77
  type: ss
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: _215
  server: 213.159.66.206
  type: ss
  port: 443
  udp: true
  password: pl2XtR0pzwknQOGwewbwXtPYDw1zn9Vu
  cipher: chacha20-ietf-poly1305
- name: disney_MD
  server: 185.153.197.5
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: disney_netflix_US
  server: 5.78.51.123
  type: ss
  port: 1080
  password: 8tmnvX5zYuWGVIDP2jglZw
  cipher: chacha20-ietf-poly1305
- name: _224
  server: 23.95.75.146
  type: ss
  port: 443
  udp: true
  password: NDRySIABARbErNIVsCNVkyYAHiBzhveT
  cipher: chacha20-ietf-poly1305
- name: _217
  server: 134.209.147.198
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: _222
  server: 46.183.184.60
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: Relay_-ðŸ‡­ðŸ‡°HK_226
  server: 131.186.63.89
  type: vmess
  port: 11655
  uuid: 4bf075f5-4d5e-4d39-f5ab-b32a86250f0e
  alterId: 0
  cipher: auto
  network: ws
  servername: hk.nbee.pp.ua
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /aa
    headers:
      Host: hk.nbee.pp.ua
- name: _221
  server: 120.241.239.79
  type: ss
  port: 20006
  udp: true
  password: 8ddc0a47-9a7f-41e1-adf7-f6322276c1ca
  cipher: aes-256-gcm
- name: disney_EE
  server: 37.252.5.75
  type: trojan
  port: 443
  udp: true
  password: 3208e968-b862-4e2e-ad90-2b49e7ce7afb
  sni: joss.gpj1.web.id
  ws-opts:
    path: /Free-VPN-CF-Geo-Project/37.252.5.75=443
    headers:
      Host: joss.gpj1.web.id
  network: ws
- name: disney_netflix_FR
  server: 141.94.204.212
  type: trojan
  port: 2053
  udp: true
  password: 0e0c9c2a-6166-4337-bdfc-675602365807
  sni: joss.gpj1.web.id
  ws-opts:
    path: /Free-VPN-CF-Geo-Project/141.94.204.212=2053
    headers:
      Host: joss.gpj1.web.id
  network: ws
- name: disney_CZ
  server: 81.91.214.162
  type: trojan
  port: 443
  udp: true
  password: f583143c-2cbe-47f5-804d-27efa55442a1
  sni: joss.gpj1.web.id
  ws-opts:
    path: /Free-VPN-CF-Geo-Project/81.91.214.162=443
    headers:
      Host: joss.gpj1.web.id
  network: ws
- name: disney_PT
  server: 185.231.233.112
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: Relay_-ðŸ‡³ðŸ‡±NL_231
  server: 160.16.223.205
  type: trojan
  port: 2760
  password: dd2f25b4c70689de8bc0f7fa9d6591cb
  sni: www.nintendogames.net
- name: Relay_-ðŸ‡³ðŸ‡±NL_232
  server: 160.16.196.59
  type: trojan
  port: 2890
  password: dd2f25b4c70689de8bc0f7fa9d6591cb
  sni: www.nintendogames.net
- name: disney_GB
  server: 109.169.76.23
  type: trojan
  port: 443
  udp: true
  password: d69e725c-7c7e-4c75-9786-4859b4e0bbc6
  sni: joss.gpj1.web.id
  ws-opts:
    path: /Free-VPN-CF-Geo-Project/109.169.76.23=443
    headers:
      Host: joss.gpj1.web.id
  network: ws
- name: disney_FR
  server: 34.22.190.30
  type: trojan
  port: 443
  udp: true
  password: fea8b7a7-cc83-4a78-a3fc-bbce9cc89ddb
  sni: joss.gpj1.web.id
  ws-opts:
    path: /Free-VPN-CF-Geo-Project/34.22.190.30=443
    headers:
      Host: joss.gpj1.web.id
  network: ws
- name: Relay_-ðŸ‡³ðŸ‡±NL_236
  server: 160.16.214.6
  type: trojan
  port: 2760
  password: dd2f25b4c70689de8bc0f7fa9d6591cb
  sni: www.nintendogames.net
- name: disney_IT
  server: 185.247.184.186
  type: trojan
  port: 8443
  udp: true
  password: 2302eb2b-9401-4176-a4da-b41d4cd55756
  sni: joss.gpj1.web.id
  ws-opts:
    path: /Free-VPN-CF-Geo-Project/185.247.184.186=8443
    headers:
      Host: joss.gpj1.web.id
  network: ws
- name: Relay_-ðŸ‡­ðŸ‡°HK_227
  server: 0225a877-t66sg0-t7n4ch-1rfon.hkt.gotochinatown.net
  type: vmess
  port: 80
  udp: true
  uuid: aed1cc24-351d-11ef-ba52-f23c9164ca5d
  alterId: 2
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /
    headers:
      Host: broadcastlv.chat.bilibili.com
- name: Relay_-ðŸ‡¯ðŸ‡µJP_239
  server: 160.16.227.93
  type: trojan
  port: 1924
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: disney_DK
  server: 89.28.236.243
  type: trojan
  port: 443
  udp: true
  password: 5c8c8b61-9b24-4c5a-b6ad-f6560df2e9d3
  sni: joss.gpj1.web.id
  ws-opts:
    path: /Free-VPN-CF-Geo-Project/89.28.236.243=443
    headers:
      Host: joss.gpj1.web.id
  network: ws
- name: disney_PL
  server: 217.30.10.31
  type: trojan
  port: 8443
  udp: true
  password: 422d402c-58f1-4473-abeb-fe6e69dc97ed
  sni: joss.gpj1.web.id
  ws-opts:
    path: /Free-VPN-CF-Geo-Project/217.30.10.31=8443
    headers:
      Host: joss.gpj1.web.id
  network: ws
- name: disney_FR
  server: 51.15.210.1
  type: trojan
  port: 443
  udp: true
  password: e6f0e8b0-3dc5-4d53-a23a-86c02d5ba098
  sni: joss.gpj1.web.id
  ws-opts:
    path: /Free-VPN-CF-Geo-Project/51.15.210.1=443
    headers:
      Host: joss.gpj1.web.id
  network: ws
- name: disney_NL
  server: 81.22.132.183
  type: trojan
  port: 443
  udp: true
  password: ee339912-0c35-4fac-8d85-180b65bcd49c
  sni: joss.gpj1.web.id
  ws-opts:
    path: /Free-VPN-CF-Geo-Project/81.22.132.183=443
    headers:
      Host: joss.gpj1.web.id
  network: ws
- name: disney_netflix_GB
  server: koma-yt.pages.dev
  type: trojan
  port: 8443
  udp: true
  password: 8r<[9'l6hAO#8ZQi
  sni: Koma-YT.PAGeS.Dev
  ws-opts:
    path: /tro8sFW1S91B6sZrM1
    headers:
      Host: Koma-YT.PAGeS.Dev
  network: ws
- name: disney_netflix_FR
  server: 178.33.161.196
  type: trojan
  port: 2053
  udp: true
  password: be94cd60-8e91-4cd6-9c53-26ee1314edfd
  sni: joss.gpj1.web.id
  ws-opts:
    path: /Free-VPN-CF-Geo-Project/178.33.161.196=2053
    headers:
      Host: joss.gpj1.web.id
  network: ws
- name: disney_NL
  server: 89.110.120.197
  type: trojan
  port: 443
  udp: true
  password: 35f8e682-54bd-42c7-b537-94a8e4c84bcd
  sni: joss.gpj1.web.id
  ws-opts:
    path: /Free-VPN-CF-Geo-Project/89.110.120.197=443
    headers:
      Host: joss.gpj1.web.id
  network: ws
- name: Relay_-ðŸ‡³ðŸ‡±NL_246
  server: 160.16.89.176
  type: trojan
  port: 2760
  password: dd2f25b4c70689de8bc0f7fa9d6591cb
  sni: www.nintendogames.net
- name: disney_ES
  server: 45.159.251.8
  type: trojan
  port: 81
  udp: true
  password: 6ead60c4-4321-45d5-81a9-ba4835f7c692
  sni: joss.gpj1.web.id
  ws-opts:
    path: /Free-VPN-CF-Geo-Project/45.159.251.8=81
    headers:
      Host: joss.gpj1.web.id
  network: ws
- name: disney_HK
  server: 58.152.25.241
  type: trojan
  port: 443
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: Relay_-ðŸ‡ºðŸ‡¸US_249
  server: 160.16.89.176
  type: trojan
  port: 702
  password: dd2f25b4c70689de8bc0f7fa9d6591cb
  sni: www.nintendogames.net
- name: Relay_-ðŸ‡ºðŸ‡¸US_253
  server: usiys.southbyte.xyz
  type: trojan
  port: 5897
  udp: true
  password: fg20mtCFHy
  sni: usiys.southbyte.xyz
  skip-cert-verify: true
- name: Relay_-ðŸ‡ºðŸ‡¸US_250
  server: 160.16.124.55
  type: trojan
  port: 702
  password: dd2f25b4c70689de8bc0f7fa9d6591cb
  sni: www.nintendogames.net
- name: disney_NL
  server: 138.124.30.8
  type: trojan
  port: 443
  udp: true
  password: 0311306e-56d4-4aa1-bde5-8cede7fcd3e4
  sni: joss.gpj1.web.id
  ws-opts:
    path: /Free-VPN-CF-Geo-Project/138.124.30.8=443
    headers:
      Host: joss.gpj1.web.id
  network: ws
- name: Relay_-ðŸ‡©ðŸ‡ªDE_252
  server: 38.180.72.162
  type: trojan
  port: 2053
  udp: true
  password: eb7339c5-70e4-4c7b-b5ef-4128adc8136a
  sni: joss.gpj1.web.id
  ws-opts:
    path: /Free-VPN-CF-Geo-Project/38.180.72.162=2053
    headers:
      Host: joss.gpj1.web.id
  network: ws
- name: disney_FR
  server: 34.22.190.30
  type: trojan
  port: 443
  udp: true
  password: 0a477acf-1f95-47cb-b4a5-a627b4c57de3
  sni: joss.gpj1.web.id
  ws-opts:
    path: /Free-VPN-CF-Geo-Project/34.22.190.30=443
    headers:
      Host: joss.gpj1.web.id
  network: ws
- name: Relay_-ðŸ‡³ðŸ‡±NL_254
  server: 160.16.204.136
  type: trojan
  port: 2890
  password: dd2f25b4c70689de8bc0f7fa9d6591cb
  sni: www.nintendogames.net
- name: disney_netflix_US
  server: 74.48.14.238
  type: vmess
  country: ðŸ‡¨ðŸ‡¦CA
  port: 2087
  uuid: ffd95a2c-ab52-434b-8def-2d06a959f5b5
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /grqf
- name: Relay_-ðŸ‡¯ðŸ‡µJP_255
  server: 160.16.136.130
  type: trojan
  port: 1331
  password: dd2f25b4c70689de8bc0f7fa9d6591cb
  sni: www.nintendogames.net
- name: Relay_-ðŸ‡¯ðŸ‡µJP_256
  server: 160.16.204.136
  type: trojan
  port: 1331
  password: dd2f25b4c70689de8bc0f7fa9d6591cb
  sni: www.nintendogames.net
- name: Relay_-ðŸ‡¯ðŸ‡µJP_257
  server: 160.16.124.55
  type: trojan
  port: 3169
  password: dd2f25b4c70689de8bc0f7fa9d6591cb
  sni: www.nintendogames.net
- name: Relay_ðŸ‡¬ðŸ‡§GB-ðŸ‡ºðŸ‡¸US_264
  server: 82.198.246.97
  type: vmess
  country: ðŸ‡¬ðŸ‡§GB
  port: 180
  uuid: d13fc2f5-3e05-4795-81eb-44143a09e552
  alterId: 0
  cipher: auto
  network: tcp
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ðŸ‡²ðŸ‡½MX_268
  server: 216.238.89.53
  type: vmess
  country: ðŸ‡²ðŸ‡½MX
  port: 57283
  uuid: 1a5aafc0-6482-451d-fe76-6875b7818579
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ðŸ‡¦ðŸ‡ºAU_259
  server: 54.252.214.254
  type: vmess
  country: ðŸ‡¦ðŸ‡ºAU
  port: 1000
  uuid: 61a9c747-cbe6-46aa-a0bb-8d5a615db8b1
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_FR
  server: 208.76.223.218
  type: vmess
  country: ðŸ‡ªðŸ‡¸ES
  port: 27092
  uuid: a0596ba6-72a3-4366-8992-77088da65bd8
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: netflix_IE
  server: 3.252.162.214
  type: ss
  country: ðŸ‡®ðŸ‡ªIE
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: disney_US
  server: 193.124.24.247
  type: vmess
  country: ðŸ‡ºðŸ‡¸US
  port: 6505
  uuid: b34732f9-2856-4974-8bae-1351928e347f
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_US
  server: 193.124.24.247
  type: vmess
  country: ðŸ‡ºðŸ‡¸US
  port: 6510
  uuid: 8f44f672-e53b-44fb-b502-c886d37107b5
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: netflix_IE
  server: 34.245.193.205
  type: ss
  country: ðŸ‡®ðŸ‡ªIE
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ðŸ‡§ðŸ‡©BD_260
  server: 103.106.3.82
  type: ss
  country: ðŸ‡§ðŸ‡©BD
  port: 443
  password: 4SaCIazlgumYkM8FkPzlmwjpyWBDZFBk
  cipher: chacha20-ietf-poly1305
- name: disney_US
  server: 193.124.24.247
  type: vmess
  country: ðŸ‡ºðŸ‡¸US
  port: 6512
  uuid: 729bfa51-095c-4f50-a1e0-2dfc90d51ebd
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_US
  server: 193.124.24.247
  type: vmess
  country: ðŸ‡ºðŸ‡¸US
  port: 6513
  uuid: 5cf7fcbc-e2c1-42c4-d0d7-79c45a7d588d
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ðŸ‡¦ðŸ‡¹AT_258
  server: 95.174.68.33
  type: ss
  country: ðŸ‡¦ðŸ‡¹AT
  port: 443
  password: YzH4id7ZEyKpfy39F2YcOmzCsBklGwh8
  cipher: chacha20-ietf-poly1305
- name: disney_US
  server: 193.124.24.247
  type: vmess
  country: ðŸ‡ºðŸ‡¸US
  port: 6508
  uuid: b68fead5-5b0b-43a1-c34a-804467f0f368
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_US
  server: 193.124.24.247
  type: vmess
  country: ðŸ‡ºðŸ‡¸US
  port: 6504
  uuid: 7ceb165c-9aff-4ab7-ce9e-1df31a5ed911
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_US
  server: 193.124.24.247
  type: vmess
  country: ðŸ‡ºðŸ‡¸US
  port: 6502
  uuid: 242f22a3-29d9-4a94-d8ba-88043f2e1921
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ðŸ‡ºðŸ‡¸US_270
  server: 185.156.110.92
  type: ss
  country: ðŸ‡ºðŸ‡¸US
  port: 443
  password: gXOXk2FJwsz9P6nXIICuDNOqF9gWX1dn
  cipher: chacha20-ietf-poly1305
- name: disney_HK
  server: 2.59.62.63
  type: vmess
  country: ðŸ‡ºðŸ‡¸US
  port: 19365
  uuid: 9583a647-b0ba-47b0-d4b0-4e12a0201d67
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: _219
  server: 146.19.49.251
  type: ss
  port: 443
  udp: true
  password: ODfxioK0VkKxTdpVQJ4rv8HglAu0vzv6
  cipher: chacha20-ietf-poly1305
- name: ðŸ‡ºðŸ‡¸US_271
  server: cgroup.node5.s2.nodelist-airport.com
  type: ss
  country: ðŸ‡ºðŸ‡¸US
  port: 27232
  password: 8f3a835c-8a45-480d-ae35-1deb2c52dcae
  cipher: aes-256-gcm
- name: Relay_ðŸ‡©ðŸ‡ªDE-ðŸ‡©ðŸ‡ªDE_262
  server: node4.rtxconfigz.com
  type: vmess
  country: ðŸ‡©ðŸ‡ªDE
  port: 443
  uuid: 44e57485-eccc-46ef-808f-cd17ac810018
  alterId: 0
  cipher: auto
  network: ws
  servername: node4.rtxconfigz.com
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /@Malinda6104
    headers:
      HOST: node4.rtxconfigz.com
- name: Relay_ðŸ‡ºðŸ‡¸US-ðŸ‡¯ðŸ‡µJP_280
  server: t1.620720.xyz
  type: vmess
  country: ðŸ‡ºðŸ‡¸US
  port: 8443
  uuid: 516d8a7a-3f0b-41d3-bad0-246116381516
  alterId: 0
  cipher: auto
  network: ws
  servername: t1.620720.xyz
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /
    headers:
      HOST: t1.620720.xyz
- name: disney_TH
  server: th0603-1.ysds168.shop
  type: vmess
  country: ðŸ‡¹ðŸ‡­TH
  port: 1036
  uuid: 5893c6cd-c14f-4e99-a9ae-6c2ca7456584
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: Relay_ðŸ‡­ðŸ‡°HK-ðŸ‡­ðŸ‡°HK_265
  server: n1744453319.lie5d.cyou
  type: vmess
  country: ðŸ‡­ðŸ‡°HK
  port: 443
  uuid: 6928af97-a23e-408c-956e-5cd2207f3557
  alterId: 0
  cipher: auto
  network: ws
  servername: n1744453319.lie5d.cyou
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /
    headers:
      HOST: n1744453319.lie5d.cyou
proxy-groups:
- name: ðŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - _130
  - disney_US
  - _216
  - _218
  - _215
  - disney_MD
  - disney_netflix_US
  - _224
  - _217
  - _222
  - Relay_-ðŸ‡­ðŸ‡°HK_226
  - _221
  - disney_EE
  - disney_netflix_FR
  - disney_CZ
  - disney_PT
  - Relay_-ðŸ‡³ðŸ‡±NL_231
  - Relay_-ðŸ‡³ðŸ‡±NL_232
  - disney_GB
  - disney_FR
  - Relay_-ðŸ‡³ðŸ‡±NL_236
  - disney_IT
  - Relay_-ðŸ‡­ðŸ‡°HK_227
  - Relay_-ðŸ‡¯ðŸ‡µJP_239
  - disney_DK
  - disney_PL
  - disney_FR
  - disney_NL
  - disney_netflix_GB
  - disney_netflix_FR
  - disney_NL
  - Relay_-ðŸ‡³ðŸ‡±NL_246
  - disney_ES
  - disney_HK
  - Relay_-ðŸ‡ºðŸ‡¸US_249
  - Relay_-ðŸ‡ºðŸ‡¸US_253
  - Relay_-ðŸ‡ºðŸ‡¸US_250
  - disney_NL
  - Relay_-ðŸ‡©ðŸ‡ªDE_252
  - disney_FR
  - Relay_-ðŸ‡³ðŸ‡±NL_254
  - disney_netflix_US
  - Relay_-ðŸ‡¯ðŸ‡µJP_255
  - Relay_-ðŸ‡¯ðŸ‡µJP_256
  - Relay_-ðŸ‡¯ðŸ‡µJP_257
  - Relay_ðŸ‡¬ðŸ‡§GB-ðŸ‡ºðŸ‡¸US_264
  - ðŸ‡²ðŸ‡½MX_268
  - ðŸ‡¦ðŸ‡ºAU_259
  - disney_FR
  - netflix_IE
  - disney_US
  - disney_netflix_US
  - netflix_IE
  - ðŸ‡§ðŸ‡©BD_260
  - disney_US
  - disney_netflix_US
  - ðŸ‡¦ðŸ‡¹AT_258
  - disney_US
  - disney_US
  - disney_US
  - ðŸ‡ºðŸ‡¸US_270
  - disney_HK
  - _219
  - ðŸ‡ºðŸ‡¸US_271
  - Relay_ðŸ‡©ðŸ‡ªDE-ðŸ‡©ðŸ‡ªDE_262
  - Relay_ðŸ‡ºðŸ‡¸US-ðŸ‡¯ðŸ‡µJP_280
  - disney_TH
  - Relay_ðŸ‡­ðŸ‡°HK-ðŸ‡­ðŸ‡°HK_265
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - _130
  - disney_US
  - _216
  - _218
  - _215
  - disney_MD
  - disney_netflix_US
  - _224
  - _217
  - _222
  - Relay_-ðŸ‡­ðŸ‡°HK_226
  - _221
  - disney_EE
  - disney_netflix_FR
  - disney_CZ
  - disney_PT
  - Relay_-ðŸ‡³ðŸ‡±NL_231
  - Relay_-ðŸ‡³ðŸ‡±NL_232
  - disney_GB
  - disney_FR
  - Relay_-ðŸ‡³ðŸ‡±NL_236
  - disney_IT
  - Relay_-ðŸ‡­ðŸ‡°HK_227
  - Relay_-ðŸ‡¯ðŸ‡µJP_239
  - disney_DK
  - disney_PL
  - disney_FR
  - disney_NL
  - disney_netflix_GB
  - disney_netflix_FR
  - disney_NL
  - Relay_-ðŸ‡³ðŸ‡±NL_246
  - disney_ES
  - disney_HK
  - Relay_-ðŸ‡ºðŸ‡¸US_249
  - Relay_-ðŸ‡ºðŸ‡¸US_253
  - Relay_-ðŸ‡ºðŸ‡¸US_250
  - disney_NL
  - Relay_-ðŸ‡©ðŸ‡ªDE_252
  - disney_FR
  - Relay_-ðŸ‡³ðŸ‡±NL_254
  - disney_netflix_US
  - Relay_-ðŸ‡¯ðŸ‡µJP_255
  - Relay_-ðŸ‡¯ðŸ‡µJP_256
  - Relay_-ðŸ‡¯ðŸ‡µJP_257
  - Relay_ðŸ‡¬ðŸ‡§GB-ðŸ‡ºðŸ‡¸US_264
  - ðŸ‡²ðŸ‡½MX_268
  - ðŸ‡¦ðŸ‡ºAU_259
  - disney_FR
  - netflix_IE
  - disney_US
  - disney_netflix_US
  - netflix_IE
  - ðŸ‡§ðŸ‡©BD_260
  - disney_US
  - disney_netflix_US
  - ðŸ‡¦ðŸ‡¹AT_258
  - disney_US
  - disney_US
  - disney_US
  - ðŸ‡ºðŸ‡¸US_270
  - disney_HK
  - _219
  - ðŸ‡ºðŸ‡¸US_271
  - Relay_ðŸ‡©ðŸ‡ªDE-ðŸ‡©ðŸ‡ªDE_262
  - Relay_ðŸ‡ºðŸ‡¸US-ðŸ‡¯ðŸ‡µJP_280
  - disney_TH
  - Relay_ðŸ‡­ðŸ‡°HK-ðŸ‡­ðŸ‡°HK_265
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ðŸš€ èŠ‚ç‚¹é€‰æ‹©
