port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: Relay_-ğŸ‡ºğŸ‡¸US_448 |40.48Mb
  server: 38.14.99.179
  type: vmess
  port: 59807
  udp: true
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: netflix_NL |218.94Mb
  server: 151.242.251.137
  type: ss
  port: 8080
  password: o5osZg269v5zHpYjr1xY9s
  cipher: chacha20-ietf-poly1305
- name: _444 |23.71Mb
  server: 103.231.73.211
  type: ss
  port: 57456
  udp: true
  password: 8afc633eb63227e9
  cipher: chacha20-ietf-poly1305
- name: disney_HK |23.42Mb
  server: 58.152.110.154
  type: trojan
  port: 443
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: _442 |97.16Mb
  server: 185.231.233.112
  type: ss
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: Relay_-ğŸ‡¸ğŸ‡¬SG_612 |10.51Mb
  server: 160.16.212.152
  type: trojan
  port: 507
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡³ğŸ‡±NL_613 |20.58Mb
  server: 160.16.132.158
  type: trojan
  port: 4054
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¯ğŸ‡µJP_615 |11.64Mb
  server: 160.16.70.180
  type: trojan
  port: 1331
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡ºğŸ‡¸US_486 |25.18Mb
  server: v8.hdacd.com
  type: vmess
  port: 30808
  udp: true
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_-ğŸ‡¯ğŸ‡µJP_618 |10.07Mb
  server: 153.121.45.139
  type: trojan
  port: 1331
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡³ğŸ‡±NL_623 |23.95Mb
  server: 160.16.57.238
  type: trojan
  port: 4054
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡³ğŸ‡±NL_624 |16.53Mb
  server: 160.16.151.196
  type: trojan
  port: 2890
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡ºğŸ‡¸US_445 |12.55Mb
  server: v29.hdacd.com
  type: vmess
  port: 30829
  udp: true
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_-ğŸ‡³ğŸ‡±NL_628 |20.32Mb
  server: 160.16.131.243
  type: trojan
  port: 2890
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: _622 |14.53Mb
  server: 68.183.231.236
  type: trojan
  port: 443
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¯ğŸ‡µJP_634 |11.41Mb
  server: 160.16.87.174
  type: trojan
  port: 3169
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: disney_FR |36.30Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 27092
  uuid: a0596ba6-72a3-4366-8992-77088da65bd8
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_FR |129.01Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 40433
  uuid: d8fd8955-78db-49ba-d86f-3e4729f6ac4d
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡§ğŸ‡·BR_637 |19.74Mb
  server: 38.180.16.86
  type: vmess
  country: ğŸ‡§ğŸ‡·BR
  port: 36104
  uuid: E146A8CB-9D2F-449C-ADCA-8736FB
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡¬ğŸ‡§GB_643 |37.01Mb
  server: 82.38.31.190
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: Relay_-ğŸ‡¸ğŸ‡¬SG_636 |11.67Mb
  server: 160.16.131.243
  type: trojan
  port: 127
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: netflix_NL |497.41Mb
  server: 82.38.31.218
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸ‡¬ğŸ‡§GB-ğŸ‡³ğŸ‡±NL_645 |219.71Mb
  server: 82.38.31.210
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡²ğŸ‡½MX_712 |40.38Mb
  server: 216.238.89.53
  type: vmess
  country: ğŸ‡²ğŸ‡½MX
  port: 57283
  uuid: 1a5aafc0-6482-451d-fe76-6875b7818579
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡­ğŸ‡°HK_656 |21.92Mb
  server: 87.121.162.249
  type: ss
  country: ğŸ‡­ğŸ‡°HK
  port: 443
  password: JGv616hMWdjfuZ00jYfq7XkBHJZrOBrg
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_711 |10.64Mb
  server: 45.87.175.166
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 443
  password: 1RWwXhwfAB5gAEozU4G2Pg
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡·ğŸ‡ºRU_716 |57.69Mb
  server: 109.71.246.210
  type: ss
  country: ğŸ‡·ğŸ‡ºRU
  port: 56689
  password: YQCSKoCF3QazW8YlvDBWA4
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡­ğŸ‡°HK_670 |20.82Mb
  server: 47.242.140.52
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 48219
  uuid: 006893c6-79b1-4c44-94ff-b8bbea065f1f
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
  ws-opts:
    path: /arki?ed=2048
- name: disney_RU |214.96Mb
  server: 38.60.223.8
  type: ss
  country: ğŸ‡·ğŸ‡ºRU
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ğŸ‡­ğŸ‡°HK_689 |27.57Mb
  server: 47.243.51.237
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 52801
  uuid: ef93f413-9039-4ddb-aefb-2490287df55a
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
  ws-opts:
    path: /arki?ed=2048
- name: disney_JP |20.77Mb
  server: kuame.missionsec.us
  type: trojan
  country: ğŸ‡¯ğŸ‡µJP
  port: 443
  udp: true
  password: FDIypSwe64a3DA7un2R8DFjYXZO3NS05gKZTTOC8SxO0Fy3cqYg3EaFDA3ABaEYKNx39D
  sni: kuame.missionsec.us
  skip-cert-verify: true
- name: ğŸ‡²ğŸ‡¾MY_713 |31.67Mb
  server: 38.54.98.110
  type: vmess
  country: ğŸ‡²ğŸ‡¾MY
  port: 2052
  uuid: 665d9b8f-153d-4907-adac-de12afd9c851
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: ğŸ‡ºğŸ‡¸US_724 |43.01Mb
  server: 104.192.226.106
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ğŸ‡ºğŸ‡¸US_721 |174.39Mb
  server: 45.12.144.18
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: LQyAUItafUmmO3EZZx9UbiX6IGydSBgL
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_722 |111.70Mb
  server: 45.12.136.170
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: l668XHPejoSNNuD66BYzyehaCpZexiF7
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_725 |40.68Mb
  server: 38.14.99.163
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 59807
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: auto
  network: tcp
  servername: 38.14.99.163
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡¸ğŸ‡¬SG_717 |11.23Mb
  server: 68.183.178.131
  type: vmess
  country: ğŸ‡¸ğŸ‡¬SG
  port: 58607
  uuid: c11c32cb-27b3-4afa-c0f3-fb250aa4959e
  alterId: 0
  cipher: auto
  network: ws
  servername: www.12333.monster
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /
    headers:
      HOST: www.12333.monster
- name: disney_HK |12.56Mb
  server: 45.136.12.37
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 38141
  uuid: fd291be6-b48d-43a1-da38-66c7f80e2f80
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_SG |35.87Mb
  server: 188.253.124.53
  type: ss
  port: 63257
  udp: true
  password: RenzheCloudSS
  cipher: rc4-md5
  plugin: obfs
  plugin-opts:
    host: d1bf8290613.microsoft.com
    mode: http
- name: Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡·ğŸ‡ºRU_720 |42.29Mb
  server: clr.ducks.tel
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 17847
  password: '907560230'
  cipher: chacha20-ietf-poly1305
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - Relay_-ğŸ‡ºğŸ‡¸US_448 |40.48Mb
  - netflix_NL |218.94Mb
  - _444 |23.71Mb
  - disney_HK |23.42Mb
  - _442 |97.16Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_612 |10.51Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_613 |20.58Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_615 |11.64Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_486 |25.18Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_618 |10.07Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_623 |23.95Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_624 |16.53Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_445 |12.55Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_628 |20.32Mb
  - _622 |14.53Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_634 |11.41Mb
  - disney_FR |36.30Mb
  - disney_FR |129.01Mb
  - ğŸ‡§ğŸ‡·BR_637 |19.74Mb
  - ğŸ‡¬ğŸ‡§GB_643 |37.01Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_636 |11.67Mb
  - netflix_NL |497.41Mb
  - Relay_ğŸ‡¬ğŸ‡§GB-ğŸ‡³ğŸ‡±NL_645 |219.71Mb
  - ğŸ‡²ğŸ‡½MX_712 |40.38Mb
  - ğŸ‡­ğŸ‡°HK_656 |21.92Mb
  - ğŸ‡±ğŸ‡¹LT_711 |10.64Mb
  - ğŸ‡·ğŸ‡ºRU_716 |57.69Mb
  - ğŸ‡­ğŸ‡°HK_670 |20.82Mb
  - disney_RU |214.96Mb
  - ğŸ‡­ğŸ‡°HK_689 |27.57Mb
  - disney_JP |20.77Mb
  - ğŸ‡²ğŸ‡¾MY_713 |31.67Mb
  - ğŸ‡ºğŸ‡¸US_724 |43.01Mb
  - ğŸ‡ºğŸ‡¸US_721 |174.39Mb
  - ğŸ‡ºğŸ‡¸US_722 |111.70Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_725 |40.68Mb
  - ğŸ‡¸ğŸ‡¬SG_717 |11.23Mb
  - disney_HK |12.56Mb
  - disney_SG |35.87Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡·ğŸ‡ºRU_720 |42.29Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - Relay_-ğŸ‡ºğŸ‡¸US_448 |40.48Mb
  - netflix_NL |218.94Mb
  - _444 |23.71Mb
  - disney_HK |23.42Mb
  - _442 |97.16Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_612 |10.51Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_613 |20.58Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_615 |11.64Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_486 |25.18Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_618 |10.07Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_623 |23.95Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_624 |16.53Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_445 |12.55Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_628 |20.32Mb
  - _622 |14.53Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_634 |11.41Mb
  - disney_FR |36.30Mb
  - disney_FR |129.01Mb
  - ğŸ‡§ğŸ‡·BR_637 |19.74Mb
  - ğŸ‡¬ğŸ‡§GB_643 |37.01Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_636 |11.67Mb
  - netflix_NL |497.41Mb
  - Relay_ğŸ‡¬ğŸ‡§GB-ğŸ‡³ğŸ‡±NL_645 |219.71Mb
  - ğŸ‡²ğŸ‡½MX_712 |40.38Mb
  - ğŸ‡­ğŸ‡°HK_656 |21.92Mb
  - ğŸ‡±ğŸ‡¹LT_711 |10.64Mb
  - ğŸ‡·ğŸ‡ºRU_716 |57.69Mb
  - ğŸ‡­ğŸ‡°HK_670 |20.82Mb
  - disney_RU |214.96Mb
  - ğŸ‡­ğŸ‡°HK_689 |27.57Mb
  - disney_JP |20.77Mb
  - ğŸ‡²ğŸ‡¾MY_713 |31.67Mb
  - ğŸ‡ºğŸ‡¸US_724 |43.01Mb
  - ğŸ‡ºğŸ‡¸US_721 |174.39Mb
  - ğŸ‡ºğŸ‡¸US_722 |111.70Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_725 |40.68Mb
  - ğŸ‡¸ğŸ‡¬SG_717 |11.23Mb
  - disney_HK |12.56Mb
  - disney_SG |35.87Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡·ğŸ‡ºRU_720 |42.29Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
