port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: disney_netflix_US |12.43Mb
  server: 216.167.49.157
  type: vmess
  port: 36108
  uuid: ac9340c1-61d7-47bd-c5a2-9b888857dec6
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
- name: _146 |14.07Mb
  server: 45.87.175.166
  type: ss
  port: 443
  udp: true
  password: 1RWwXhwfAB5gAEozU4G2Pg
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_DE |992.66Mb
  server: 43.165.7.71
  type: vmess
  port: 19751
  uuid: 6cfa6103-5d06-40cb-f452-b563db578288
  alterId: 0
  cipher: auto
  network: http
  http-opts:
    method: GET
    path:
    - /
  h2-opts: {}
- name: netflix_CH |157.52Mb
  server: 86.106.84.195
  type: ss
  port: 13262
  udp: true
  password: kfuzkwdg4oynv495aywc
  cipher: aes-128-gcm
- name: disney_netflix_US |33.69Mb
  server: 192.204.47.79
  type: vmess
  port: 42277
  udp: true
  uuid: aee61b21-e85a-484b-f203-b245f1451cff
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: disney_HK |10.91Mb
  server: 103.149.183.191
  type: ss
  port: 8388
  udp: true
  password: asd123456
  cipher: chacha20-ietf
- name: netflix_SE |150.25Mb
  server: 13.61.13.231
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: netflix_SE |63.46Mb
  server: 13.61.180.46
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: netflix_SE |137.58Mb
  server: 51.20.125.235
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: disney_netflix_DE |260.45Mb
  server: 85.195.101.122
  type: vmess
  port: 40878
  uuid: f3d4167e-b15e-4e46-82e9-9286ef93fda7
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: disney_netflix_US |42.47Mb
  server: 163.192.49.195
  type: vmess
  port: 443
  uuid: bcb7c581-3c95-4569-a4e7-918141e91ea3
  alterId: 0
  cipher: auto
  network: http
  http-opts:
    path:
    - /
    headers:
      Host:
      - a.189.cn
  h2-opts: {}
- name: Relay_-ğŸ‡«ğŸ‡®FI_154 |48.75Mb
  server: 77.83.247.206
  type: ss
  port: 18284
  udp: true
  password: tijsjk3iwzc6b10azb0y
  cipher: aes-128-gcm
- name: _183 |15.50Mb
  server: 216.238.86.158
  type: vmess
  port: 34460
  udp: true
  uuid: 90be214d-048c-4ea2-a602-b8e4d4e51e36
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: Pool__151 |26.96Mb
  server: 185.103.110.68
  type: ss
  port: 18283
  udp: true
  password: y3o3ra6edy5nfc6hyb2n
  cipher: aes-128-gcm
- name: netflix_CA |30.49Mb
  server: 51.79.102.253
  type: vmess
  port: 80
  uuid: 58fe1542-5290-40ad-815a-77707a81afe5
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /IOebhLMhl1CTbFHbL95myfRX2
    headers:
      Host: wrmelmwxlf.gktevlrqznwqqozy.fabpfs66gizmnojhcvqxwl.kytrcfzqla87gvgvs6c7kjnrubuh.cc
- name: _192 |16.49Mb
  server: 154.201.76.172
  type: vmess
  port: 20990
  uuid: ba50e1fe-055f-4587-fd0d-36c8d6615192
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: Pool__194 |41.52Mb
  server: 165.140.216.141
  type: vmess
  port: 443
  uuid: e7d72a8d-26f2-4b54-b366-0c43e0bcba7d
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: Relay_-ğŸ‡ºğŸ‡¸US_180 |26.16Mb
  server: 20251118.yixianled.com
  type: vmess
  port: 33921
  udp: true
  uuid: 6578c489-28d2-4f12-8c2f-9f2d8789626d
  alterId: 0
  cipher: auto
  network: ws
  servername: 20251118.yixianled.com
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /happy
    headers:
      Host: 20251118.yixianled.com
- name: disney_TW |22.12Mb
  server: 103.127.218.91
  type: vmess
  port: 54693
  uuid: 1cef03ad-6343-408c-8121-cbd1fda2ee9d
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /1cef03ad
- name: _176 |23.88Mb
  server: 8.210.184.105
  type: vmess
  port: 40374
  udp: true
  uuid: 36b76373-7a4f-4669-9113-7d247bcf2704
  alterId: 0
  cipher: auto
  network: http
  http-opts:
    method: GET
    path:
    - /
  h2-opts: {}
- name: _185 |10.92Mb
  server: 156.245.232.15
  type: vmess
  port: 53947
  udp: true
  uuid: 8cb243df-fa82-472c-be25-b00acd4fcd3f
  alterId: 0
  cipher: auto
  network: http
  http-opts:
    method: GET
    path:
    - /ä½¿ç”¨æ­¤èŠ‚ç‚¹éœ€è¦å…ˆæ²æµ´ç„šé¦™ç„¶åç»™ç¾¤ä¸»ç£•800ä¸ªå“å¤´(à²¡Ï‰à²¡)
  h2-opts: {}
- name: _199 |35.73Mb
  server: 160.16.63.16
  type: trojan
  port: 4054
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: _201 |30.67Mb
  server: 153.121.39.240
  type: trojan
  port: 4054
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: _200 |19.32Mb
  server: 160.16.229.223
  type: trojan
  port: 3093
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: disney_netflix_GB |268.31Mb
  server: 172.67.134.185
  type: trojan
  port: 443
  udp: true
  password: POORIARED
  sni: reDfRee8.REDFree8.ir
  ws-opts:
    path: /eyJqdW5rIjoiVUl6eXhLZkkwUTJ3ZzkiLCJwcm90b2NvbCI6InRyIiwibW9kZSI6InByb3h5aXAiLCJwYW5lbElQcyI6W119?ed=2560
    headers:
      Host: reDfRee8.REDFree8.ir
  network: ws
- name: _186 |15.81Mb
  server: 183.236.51.36
  type: vmess
  port: 59003
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 64
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _202 |11.94Mb
  server: 160.16.81.84
  type: trojan
  port: 4054
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: _209 |24.44Mb
  server: 38.96.254.102
  type: trojan
  port: 18509
  password: .ie4rghJuMkcf0oF
  sni: shoppingmall.electricbanana.click
- name: disney_HK |28.55Mb
  server: 58.152.53.174
  type: trojan
  port: 443
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: _191 |39.46Mb
  server: 89.31.120.192
  type: vmess
  port: 443
  uuid: 44537595-9ccc-4b83-8936-5f9ad3229019
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _205 |33.07Mb
  server: 160.16.151.196
  type: trojan
  port: 4054
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¯ğŸ‡µJP_206 |18.86Mb
  server: 160.16.70.180
  type: trojan
  port: 1331
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: _211 |33.05Mb
  server: 160.16.236.32
  type: trojan
  port: 4054
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: _212 |38.87Mb
  server: 160.16.223.205
  type: trojan
  port: 4054
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: netflix_SE |187.75Mb
  server: 70.34.218.149
  type: trojan
  port: 11930
  password: BaeSzHdfJIR13l67
  sni: softpillow.silentrocket.click
- name: disney_netflix_FR |144.34Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 27092
  uuid: a0596ba6-72a3-4366-8992-77088da65bd8
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡²ğŸ‡½MX_234 |44.92Mb
  server: 216.238.87.47
  type: vmess
  country: ğŸ‡²ğŸ‡½MX
  port: 27502
  uuid: b8155ce4-7e08-4c40-800f-8671312b7124
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_FR |15.79Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 40433
  uuid: d8fd8955-78db-49ba-d86f-3e4729f6ac4d
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: netflix_NL |17.87Mb
  server: 82.38.31.191
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_228 |210.88Mb
  server: 82.38.31.194
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: netflix_NL |241.30Mb
  server: 82.38.31.217
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: disney_HK |13.43Mb
  server: 45.207.157.29
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 13852
  uuid: 845764df-ecb3-4b13-bed2-bf1551b68e9a
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Pool_ğŸ‡·ğŸ‡´RO_235 |129.75Mb
  server: 86.106.84.198
  type: ss
  country: ğŸ‡·ğŸ‡´RO
  port: 13265
  password: phizo046s4oqsm33sfvm
  cipher: aes-128-gcm
- name: netflix_LT |12.28Mb
  server: 45.12.136.170
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: l668XHPejoSNNuD66BYzyehaCpZexiF7
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_US |35.79Mb
  server: cf.fovi.tk
  type: vmess
  country: ğŸZZ
  port: 443
  uuid: bf67437e-6c90-45ca-abc2-c7240a5ce2aa
  alterId: 0
  cipher: auto
  network: ws
  servername: foxpol.fovi.tk
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /eisasqa
    headers:
      HOST: foxpol.fovi.tk
- name: Relay_ğŸ‡©ğŸ‡ªDE-ğŸ‡©ğŸ‡ªDE_219 |36.90Mb
  server: cpanel.navar1.ir
  type: vmess
  country: ğŸ‡©ğŸ‡ªDE
  port: 100
  uuid: 95c6f6f0-84f7-4443-8a50-a59f8e66f5ee
  alterId: 0
  cipher: auto
  network: tcp
  servername: cpanel.navar1.ir
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡ºğŸ‡¸US_239 |57.66Mb
  server: 47.253.197.26
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 12056
  uuid: dd7be7f1-38ff-45e6-f1e5-b20c2190f527
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - disney_netflix_US |12.43Mb
  - _146 |14.07Mb
  - disney_netflix_DE |992.66Mb
  - netflix_CH |157.52Mb
  - disney_netflix_US |33.69Mb
  - disney_HK |10.91Mb
  - netflix_SE |150.25Mb
  - netflix_SE |63.46Mb
  - netflix_SE |137.58Mb
  - disney_netflix_DE |260.45Mb
  - disney_netflix_US |42.47Mb
  - Relay_-ğŸ‡«ğŸ‡®FI_154 |48.75Mb
  - _183 |15.50Mb
  - Pool__151 |26.96Mb
  - netflix_CA |30.49Mb
  - _192 |16.49Mb
  - Pool__194 |41.52Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_180 |26.16Mb
  - disney_TW |22.12Mb
  - _176 |23.88Mb
  - _185 |10.92Mb
  - _199 |35.73Mb
  - _201 |30.67Mb
  - _200 |19.32Mb
  - disney_netflix_GB |268.31Mb
  - _186 |15.81Mb
  - _202 |11.94Mb
  - _209 |24.44Mb
  - disney_HK |28.55Mb
  - _191 |39.46Mb
  - _205 |33.07Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_206 |18.86Mb
  - _211 |33.05Mb
  - _212 |38.87Mb
  - netflix_SE |187.75Mb
  - disney_netflix_FR |144.34Mb
  - ğŸ‡²ğŸ‡½MX_234 |44.92Mb
  - disney_FR |15.79Mb
  - netflix_NL |17.87Mb
  - ğŸ‡¬ğŸ‡§GB_228 |210.88Mb
  - netflix_NL |241.30Mb
  - disney_HK |13.43Mb
  - Pool_ğŸ‡·ğŸ‡´RO_235 |129.75Mb
  - netflix_LT |12.28Mb
  - disney_netflix_US |35.79Mb
  - Relay_ğŸ‡©ğŸ‡ªDE-ğŸ‡©ğŸ‡ªDE_219 |36.90Mb
  - ğŸ‡ºğŸ‡¸US_239 |57.66Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - disney_netflix_US |12.43Mb
  - _146 |14.07Mb
  - disney_netflix_DE |992.66Mb
  - netflix_CH |157.52Mb
  - disney_netflix_US |33.69Mb
  - disney_HK |10.91Mb
  - netflix_SE |150.25Mb
  - netflix_SE |63.46Mb
  - netflix_SE |137.58Mb
  - disney_netflix_DE |260.45Mb
  - disney_netflix_US |42.47Mb
  - Relay_-ğŸ‡«ğŸ‡®FI_154 |48.75Mb
  - _183 |15.50Mb
  - Pool__151 |26.96Mb
  - netflix_CA |30.49Mb
  - _192 |16.49Mb
  - Pool__194 |41.52Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_180 |26.16Mb
  - disney_TW |22.12Mb
  - _176 |23.88Mb
  - _185 |10.92Mb
  - _199 |35.73Mb
  - _201 |30.67Mb
  - _200 |19.32Mb
  - disney_netflix_GB |268.31Mb
  - _186 |15.81Mb
  - _202 |11.94Mb
  - _209 |24.44Mb
  - disney_HK |28.55Mb
  - _191 |39.46Mb
  - _205 |33.07Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_206 |18.86Mb
  - _211 |33.05Mb
  - _212 |38.87Mb
  - netflix_SE |187.75Mb
  - disney_netflix_FR |144.34Mb
  - ğŸ‡²ğŸ‡½MX_234 |44.92Mb
  - disney_FR |15.79Mb
  - netflix_NL |17.87Mb
  - ğŸ‡¬ğŸ‡§GB_228 |210.88Mb
  - netflix_NL |241.30Mb
  - disney_HK |13.43Mb
  - Pool_ğŸ‡·ğŸ‡´RO_235 |129.75Mb
  - netflix_LT |12.28Mb
  - disney_netflix_US |35.79Mb
  - Relay_ğŸ‡©ğŸ‡ªDE-ğŸ‡©ğŸ‡ªDE_219 |36.90Mb
  - ğŸ‡ºğŸ‡¸US_239 |57.66Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
