port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: disney_netflix_US |176.73Mb
  server: 82.198.246.97
  type: vmess
  port: 180
  uuid: d13fc2f5-3e05-4795-81eb-44143a09e552
  alterId: 0
  cipher: auto
  network: tcp
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_US |40.12Mb
  server: 38.14.99.179
  type: vmess
  port: 59807
  udp: true
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_NL |218.45Mb
  server: 151.242.251.137
  type: ss
  port: 8080
  password: o5osZg269v5zHpYjr1xY9s
  cipher: chacha20-ietf-poly1305
- name: Relay_-ğŸ‡¸ğŸ‡¬SG_137 |13.72Mb
  server: 160.16.131.243
  type: trojan
  port: 127
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡ºğŸ‡¸US_139 |13.40Mb
  server: 160.16.68.250
  type: trojan
  port: 1596
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: disney_netflix_HK |24.59Mb
  server: 58.152.18.78
  type: trojan
  port: 443
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡³ğŸ‡±NL_140 |16.36Mb
  server: 160.16.81.84
  type: trojan
  port: 4054
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: _114 |138.28Mb
  server: 185.231.233.112
  type: ss
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: disney_netflix_US |22.11Mb
  server: 160.16.151.196
  type: trojan
  port: 2890
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: disney_netflix_US |45.67Mb
  server: 23.247.137.64
  type: trojan
  port: 443
  udp: true
  password: 3c4e10af98c30972
  sni: n2.gladns.com
  network: grpc
  grpc-opts:
    grpc-service-name: db
- name: Relay_-ğŸ‡¸ğŸ‡¬SG_143 |11.01Mb
  server: 160.16.144.208
  type: trojan
  port: 3145
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡ºğŸ‡¸US_147 |10.51Mb
  server: 160.16.150.76
  type: trojan
  port: 1596
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: ğŸ‡ªğŸ‡¸ES_156 |187.31Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 40433
  uuid: d8fd8955-78db-49ba-d86f-3e4729f6ac4d
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: netflix_JP |12.32Mb
  server: 160.16.70.180
  type: trojan
  port: 1331
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¸ğŸ‡¬SG_150 |10.29Mb
  server: 153.121.51.29
  type: trojan
  port: 127
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: netflix_JP |21.71Mb
  server: 160.16.130.66
  type: trojan
  port: 3093
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: ğŸ‡§ğŸ‡·BR_154 |10.16Mb
  server: 38.180.16.86
  type: vmess
  country: ğŸ‡§ğŸ‡·BR
  port: 36104
  uuid: E146A8CB-9D2F-449C-ADCA-8736FB
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_FR |95.48Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 27092
  uuid: a0596ba6-72a3-4366-8992-77088da65bd8
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_HK |12.67Mb
  server: 112.118.116.66
  type: trojan
  port: 443
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: netflix_MX |39.27Mb
  server: 216.238.89.53
  type: vmess
  country: ğŸ‡²ğŸ‡½MX
  port: 57283
  uuid: 1a5aafc0-6482-451d-fe76-6875b7818579
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_NL |44.61Mb
  server: 82.38.31.190
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_NL |185.44Mb
  server: 82.38.31.210
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_NL |57.39Mb
  server: 45.87.175.166
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 443
  password: 1RWwXhwfAB5gAEozU4G2Pg
  cipher: chacha20-ietf-poly1305
- name: netflix_AL |43.91Mb
  server: 87.121.162.249
  type: ss
  country: ğŸ‡­ğŸ‡°HK
  port: 443
  password: JGv616hMWdjfuZ00jYfq7XkBHJZrOBrg
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_US |27.38Mb
  server: 38.84.201.21
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 53487
  uuid: c3c1ec05-df2c-4975-9b42-e9b007564eb1
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_NL |77.88Mb
  server: 109.71.246.210
  type: ss
  country: ğŸ‡·ğŸ‡ºRU
  port: 56689
  password: YQCSKoCF3QazW8YlvDBWA4
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_US |11.85Mb
  server: 74.117.196.232
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 37934
  uuid: b2da9920-b0a7-4354-9e26-3833ab8d00d0
  alterId: 0
  cipher: auto
  network: ws
  servername: imafake.locker
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /speedtest
    headers:
      HOST: imafake.locker
- name: ğŸ‡­ğŸ‡°HK_166 |28.30Mb
  server: 47.243.51.237
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 52801
  uuid: ef93f413-9039-4ddb-aefb-2490287df55a
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
  ws-opts:
    path: /arki?ed=2048
- name: disney_netflix_US |40.53Mb
  server: 38.14.99.163
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 59807
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: auto
  network: tcp
  servername: 38.14.99.163
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_HK |31.15Mb
  server: 38.54.98.110
  type: vmess
  country: ğŸ‡²ğŸ‡¾MY
  port: 2052
  uuid: 665d9b8f-153d-4907-adac-de12afd9c851
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: ğŸ‡¹ğŸ‡·TR_183 |72.73Mb
  server: 185.39.204.161
  type: ss
  country: ğŸ‡¹ğŸ‡·TR
  port: 33563
  password: bSlgCoGhApOb55tIMD0zxY
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_188 |27.36Mb
  server: 45.136.12.37
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 38141
  uuid: fd291be6-b48d-43a1-da38-66c7f80e2f80
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡¸ğŸ‡¬SG_182 |11.23Mb
  server: 68.183.178.131
  type: vmess
  country: ğŸ‡¸ğŸ‡¬SG
  port: 58607
  uuid: c11c32cb-27b3-4afa-c0f3-fb250aa4959e
  alterId: 0
  cipher: auto
  network: ws
  servername: www.12333.monster
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /
    headers:
      HOST: www.12333.monster
- name: disney_netflix_US |16.89Mb
  server: cf.fovi.tk
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  uuid: bf67437e-6c90-45ca-abc2-c7240a5ce2aa
  alterId: 0
  cipher: auto
  network: ws
  servername: foxlux.fovi.tk
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /eisasqa
    headers:
      HOST: foxlux.fovi.tk
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - disney_netflix_US |176.73Mb
  - disney_netflix_US |40.12Mb
  - disney_netflix_NL |218.45Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_137 |13.72Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_139 |13.40Mb
  - disney_netflix_HK |24.59Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_140 |16.36Mb
  - _114 |138.28Mb
  - disney_netflix_US |22.11Mb
  - disney_netflix_US |45.67Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_143 |11.01Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_147 |10.51Mb
  - ğŸ‡ªğŸ‡¸ES_156 |187.31Mb
  - netflix_JP |12.32Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_150 |10.29Mb
  - netflix_JP |21.71Mb
  - ğŸ‡§ğŸ‡·BR_154 |10.16Mb
  - disney_netflix_FR |95.48Mb
  - disney_HK |12.67Mb
  - netflix_MX |39.27Mb
  - disney_netflix_NL |44.61Mb
  - disney_netflix_NL |185.44Mb
  - disney_netflix_NL |57.39Mb
  - netflix_AL |43.91Mb
  - disney_netflix_US |27.38Mb
  - disney_netflix_NL |77.88Mb
  - disney_netflix_US |11.85Mb
  - ğŸ‡­ğŸ‡°HK_166 |28.30Mb
  - disney_netflix_US |40.53Mb
  - disney_netflix_HK |31.15Mb
  - ğŸ‡¹ğŸ‡·TR_183 |72.73Mb
  - ğŸ‡ºğŸ‡¸US_188 |27.36Mb
  - ğŸ‡¸ğŸ‡¬SG_182 |11.23Mb
  - disney_netflix_US |16.89Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - disney_netflix_US |176.73Mb
  - disney_netflix_US |40.12Mb
  - disney_netflix_NL |218.45Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_137 |13.72Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_139 |13.40Mb
  - disney_netflix_HK |24.59Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_140 |16.36Mb
  - _114 |138.28Mb
  - disney_netflix_US |22.11Mb
  - disney_netflix_US |45.67Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_143 |11.01Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_147 |10.51Mb
  - ğŸ‡ªğŸ‡¸ES_156 |187.31Mb
  - netflix_JP |12.32Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_150 |10.29Mb
  - netflix_JP |21.71Mb
  - ğŸ‡§ğŸ‡·BR_154 |10.16Mb
  - disney_netflix_FR |95.48Mb
  - disney_HK |12.67Mb
  - netflix_MX |39.27Mb
  - disney_netflix_NL |44.61Mb
  - disney_netflix_NL |185.44Mb
  - disney_netflix_NL |57.39Mb
  - netflix_AL |43.91Mb
  - disney_netflix_US |27.38Mb
  - disney_netflix_NL |77.88Mb
  - disney_netflix_US |11.85Mb
  - ğŸ‡­ğŸ‡°HK_166 |28.30Mb
  - disney_netflix_US |40.53Mb
  - disney_netflix_HK |31.15Mb
  - ğŸ‡¹ğŸ‡·TR_183 |72.73Mb
  - ğŸ‡ºğŸ‡¸US_188 |27.36Mb
  - ğŸ‡¸ğŸ‡¬SG_182 |11.23Mb
  - disney_netflix_US |16.89Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
