port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: _248 |41.67Mb
  server: 173.234.29.2
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: Relay_-ğŸ‡¨ğŸ‡¦CA_256 |69.52Mb
  server: 79.127.200.169
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _241 |200.44Mb
  server: 151.242.251.152
  type: ss
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: _262 |199.62Mb
  server: 45.87.175.28
  type: ss
  port: 8080
  udp: true
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: _266 |29.47Mb
  server: 82.38.31.179
  type: ss
  port: 8080
  udp: true
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: Relay_-ğŸ‡«ğŸ‡®FI_258 |20.69Mb
  server: 193.135.174.135
  type: ss
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: Relay_-ğŸ‡ªğŸ‡ªEE_238 |21.69Mb
  server: est01-ss01.tcp-reset-club.net
  type: ss
  port: 8444
  udp: true
  password: AWNeHjukGQWwuFXadw2r6qH7gh4hZ9cj
  cipher: chacha20-ietf-poly1305
- name: _240 |14.92Mb
  server: 95.164.116.33
  type: ss
  port: 443
  password: pQmnC03JObbPhdh5FBJHgD6jnTLchsRA
  cipher: chacha20-ietf-poly1305
- name: _246 |108.62Mb
  server: 138.186.143.32
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: _255 |19.32Mb
  server: 138.186.143.32
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _270 |777.70Mb
  server: 46.183.184.60
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: _253 |75.82Mb
  server: 38.165.233.93
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: disney_netflix_GB |34.09Mb
  server: 146.70.61.37
  type: ss
  port: 8080
  udp: true
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: _280 |16.61Mb
  server: 62.100.205.100
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _281 |12.92Mb
  server: 45.87.175.22
  type: ss
  port: 8080
  udp: true
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: netflix_US |22.89Mb
  server: 103.35.189.136
  type: ss
  port: 443
  udp: true
  password: SS2QvbC9nqLp2sXXZo0BVy4slcErRuCt
  cipher: chacha20-ietf-poly1305
- name: _282 |15.79Mb
  server: 45.158.171.70
  type: ss
  port: 8080
  udp: true
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: netflix_NL |201.80Mb
  server: 51.15.23.166
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: _305 |69.49Mb
  server: 172.233.229.91
  type: vmess
  port: 14102
  udp: true
  uuid: 27ba87fc-583f-4763-9060-83cf0b9264db
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_SE |43.84Mb
  server: se1.opensocks.site
  type: ss
  port: 8388
  udp: true
  password: ODIzO
  cipher: chacha20-ietf-poly1305
- name: _276 |17.97Mb
  server: 172.105.199.111
  type: ss
  port: 8080
  udp: true
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: _279 |64.88Mb
  server: 89.221.225.15
  type: ss
  port: 443
  udp: true
  password: yCbQ4bry4otfifK7oel71NaXpPL9pYJb
  cipher: chacha20-ietf-poly1305
- name: _287 |19.69Mb
  server: 138.186.142.81
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _293 |67.20Mb
  server: 82.38.31.214
  type: ss
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: disney_HK |16.25Mb
  server: 103.149.183.191
  type: ss
  port: 8388
  password: asd123456
  cipher: chacha20-ietf
- name: _325 |24.94Mb
  server: 160.16.57.238
  type: trojan
  port: 4054
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: _330 |10.52Mb
  server: 160.16.106.144
  type: trojan
  port: 2760
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
  skip-cert-verify: true
- name: _327 |11.92Mb
  server: 160.16.214.6
  type: trojan
  port: 4054
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: _331 |12.97Mb
  server: 202.181.103.246
  type: trojan
  port: 4054
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: _297 |31.07Mb
  server: 103.97.203.227
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _299 |40.85Mb
  server: 156.59.243.6
  type: ss
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _332 |19.01Mb
  server: 160.16.138.24
  type: trojan
  port: 4054
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: ğŸ‡§ğŸ‡·BR_333 |43.19Mb
  server: 185.192.124.188
  type: ss
  country: ğŸ‡§ğŸ‡·BR
  port: 990
  password: f8f7aCzcPKbsF8p3
  cipher: chacha20-ietf-poly1305
- name: Relay_-ğŸ‡ºğŸ‡¸US_310 |29.47Mb
  server: v4.hdacd.com
  type: vmess
  port: 30804
  udp: true
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: _289 |177.01Mb
  server: h110vpnnl.outlinekeys.net
  type: ss
  port: 52571
  udp: true
  password: b0TKxnHAYeeFYyzTAMXn0F
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸ‡¬ğŸ‡§GB-ğŸ‡³ğŸ‡±NL_358 |192.38Mb
  server: 82.38.31.208
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¨ğŸ‡¦CA_335 |80.64Mb
  server: 185.213.23.63
  type: ss
  country: ğŸ‡¨ğŸ‡¦CA
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: disney_DE |239.80Mb
  server: 89.163.140.136
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: disney_CH |20.86Mb
  server: 138.124.67.26
  type: ss
  country: ğŸ‡¨ğŸ‡­CH
  port: 25572
  password: nqcIfYHlpMn3jzqkNDjKaG
  cipher: chacha20-ietf-poly1305
- name: netflix_NL |129.01Mb
  server: 45.87.175.185
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_372 |256.06Mb
  server: 45.87.175.185
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡²ğŸ‡½MX_376 |171.63Mb
  server: 216.238.87.47
  type: vmess
  country: ğŸ‡²ğŸ‡½MX
  port: 27502
  uuid: b8155ce4-7e08-4c40-800f-8671312b7124
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡±ğŸ‡¹LT_373 |110.22Mb
  server: 45.87.175.175
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: QCXDxuDlTTMD7jtgHUjIoj
  cipher: chacha20-ietf-poly1305
- name: netflix_NL |164.33Mb
  server: 45.87.175.183
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡³ğŸ‡±NL_379 |54.78Mb
  server: 193.29.139.188
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 8080
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡³ğŸ‡±NL_377 |49.80Mb
  server: 178.23.190.238
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 443
  password: uo7EbtqIwgZXXHmMv5LbLcOxptyPlNkh
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡³ğŸ‡±NL_378 |269.10Mb
  server: 194.87.216.218
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 52571
  password: b0TKxnHAYeeFYyzTAMXn0F
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡µğŸ‡¹PT_385 |57.48Mb
  server: 185.113.143.186
  type: ss
  country: ğŸ‡µğŸ‡¹PT
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸZZ_393 |17.70Mb
  server: hgtrojan.zabc.net
  type: vmess
  country: ğŸZZ
  port: 2083
  uuid: e6395c20-4571-4b34-d6b1-55a5d36e49ea
  alterId: 0
  cipher: auto
  network: ws
  servername: hgtrojan.zabc.net
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /e6395c20
    headers:
      HOST: hgtrojan.zabc.net
- name: disney_SG |20.09Mb
  server: 103.248.229.90
  type: ss
  country: ğŸ‡¸ğŸ‡¬SG
  port: 40413
  password: hGpFS8dtyN
  cipher: aes-256-gcm
- name: disney_SG |18.24Mb
  server: 103.248.229.90
  type: ss
  country: ğŸ‡¸ğŸ‡¬SG
  port: 24203
  password: 1GJth1Qjic
  cipher: aes-256-gcm
- name: ğŸ‡¸ğŸ‡¬SG_388 |12.67Mb
  server: 68.183.227.45
  type: ss
  country: ğŸ‡¸ğŸ‡¬SG
  port: 8080
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: disney_SG |18.02Mb
  server: 103.248.229.90
  type: ss
  country: ğŸ‡¸ğŸ‡¬SG
  port: 35817
  password: 4VqrUWV7hm
  cipher: aes-256-gcm
- name: ğŸ ZZ_392 |90.06Mb
  server: 185.231.233.112
  type: ss
  country: ğŸ ZZ
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: Relay_ğŸ‡¯ğŸ‡µJP-ğŸ‡¯ğŸ‡µJP_367 |11.16Mb
  server: xray.kk37005.tk
  type: vmess
  country: ğŸ‡¯ğŸ‡µJP
  port: 55919
  uuid: 2e7548bb-7c5b-4d97-d64d-1b2fe4050089
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: Relay_ğŸZZ-ğŸ‡®ğŸ‡·IR_395 |26.13Mb
  server: cf.fovi.tk
  type: vmess
  country: ğŸZZ
  port: 443
  uuid: bf67437e-6c90-45ca-abc2-c7240a5ce2aa
  alterId: 0
  cipher: auto
  network: ws
  servername: foxlux.fovi.tk
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /eisasqa
    headers:
      HOST: foxlux.fovi.tk
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - _248 |41.67Mb
  - Relay_-ğŸ‡¨ğŸ‡¦CA_256 |69.52Mb
  - _241 |200.44Mb
  - _262 |199.62Mb
  - _266 |29.47Mb
  - Relay_-ğŸ‡«ğŸ‡®FI_258 |20.69Mb
  - Relay_-ğŸ‡ªğŸ‡ªEE_238 |21.69Mb
  - _240 |14.92Mb
  - _246 |108.62Mb
  - _255 |19.32Mb
  - _270 |777.70Mb
  - _253 |75.82Mb
  - disney_netflix_GB |34.09Mb
  - _280 |16.61Mb
  - _281 |12.92Mb
  - netflix_US |22.89Mb
  - _282 |15.79Mb
  - netflix_NL |201.80Mb
  - _305 |69.49Mb
  - disney_SE |43.84Mb
  - _276 |17.97Mb
  - _279 |64.88Mb
  - _287 |19.69Mb
  - _293 |67.20Mb
  - disney_HK |16.25Mb
  - _325 |24.94Mb
  - _330 |10.52Mb
  - _327 |11.92Mb
  - _331 |12.97Mb
  - _297 |31.07Mb
  - _299 |40.85Mb
  - _332 |19.01Mb
  - ğŸ‡§ğŸ‡·BR_333 |43.19Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_310 |29.47Mb
  - _289 |177.01Mb
  - Relay_ğŸ‡¬ğŸ‡§GB-ğŸ‡³ğŸ‡±NL_358 |192.38Mb
  - ğŸ‡¨ğŸ‡¦CA_335 |80.64Mb
  - disney_DE |239.80Mb
  - disney_CH |20.86Mb
  - netflix_NL |129.01Mb
  - ğŸ‡±ğŸ‡¹LT_372 |256.06Mb
  - ğŸ‡²ğŸ‡½MX_376 |171.63Mb
  - ğŸ‡±ğŸ‡¹LT_373 |110.22Mb
  - netflix_NL |164.33Mb
  - ğŸ‡³ğŸ‡±NL_379 |54.78Mb
  - ğŸ‡³ğŸ‡±NL_377 |49.80Mb
  - ğŸ‡³ğŸ‡±NL_378 |269.10Mb
  - ğŸ‡µğŸ‡¹PT_385 |57.48Mb
  - ğŸZZ_393 |17.70Mb
  - disney_SG |20.09Mb
  - disney_SG |18.24Mb
  - ğŸ‡¸ğŸ‡¬SG_388 |12.67Mb
  - disney_SG |18.02Mb
  - ğŸ ZZ_392 |90.06Mb
  - Relay_ğŸ‡¯ğŸ‡µJP-ğŸ‡¯ğŸ‡µJP_367 |11.16Mb
  - Relay_ğŸZZ-ğŸ‡®ğŸ‡·IR_395 |26.13Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - _248 |41.67Mb
  - Relay_-ğŸ‡¨ğŸ‡¦CA_256 |69.52Mb
  - _241 |200.44Mb
  - _262 |199.62Mb
  - _266 |29.47Mb
  - Relay_-ğŸ‡«ğŸ‡®FI_258 |20.69Mb
  - Relay_-ğŸ‡ªğŸ‡ªEE_238 |21.69Mb
  - _240 |14.92Mb
  - _246 |108.62Mb
  - _255 |19.32Mb
  - _270 |777.70Mb
  - _253 |75.82Mb
  - disney_netflix_GB |34.09Mb
  - _280 |16.61Mb
  - _281 |12.92Mb
  - netflix_US |22.89Mb
  - _282 |15.79Mb
  - netflix_NL |201.80Mb
  - _305 |69.49Mb
  - disney_SE |43.84Mb
  - _276 |17.97Mb
  - _279 |64.88Mb
  - _287 |19.69Mb
  - _293 |67.20Mb
  - disney_HK |16.25Mb
  - _325 |24.94Mb
  - _330 |10.52Mb
  - _327 |11.92Mb
  - _331 |12.97Mb
  - _297 |31.07Mb
  - _299 |40.85Mb
  - _332 |19.01Mb
  - ğŸ‡§ğŸ‡·BR_333 |43.19Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_310 |29.47Mb
  - _289 |177.01Mb
  - Relay_ğŸ‡¬ğŸ‡§GB-ğŸ‡³ğŸ‡±NL_358 |192.38Mb
  - ğŸ‡¨ğŸ‡¦CA_335 |80.64Mb
  - disney_DE |239.80Mb
  - disney_CH |20.86Mb
  - netflix_NL |129.01Mb
  - ğŸ‡±ğŸ‡¹LT_372 |256.06Mb
  - ğŸ‡²ğŸ‡½MX_376 |171.63Mb
  - ğŸ‡±ğŸ‡¹LT_373 |110.22Mb
  - netflix_NL |164.33Mb
  - ğŸ‡³ğŸ‡±NL_379 |54.78Mb
  - ğŸ‡³ğŸ‡±NL_377 |49.80Mb
  - ğŸ‡³ğŸ‡±NL_378 |269.10Mb
  - ğŸ‡µğŸ‡¹PT_385 |57.48Mb
  - ğŸZZ_393 |17.70Mb
  - disney_SG |20.09Mb
  - disney_SG |18.24Mb
  - ğŸ‡¸ğŸ‡¬SG_388 |12.67Mb
  - disney_SG |18.02Mb
  - ğŸ ZZ_392 |90.06Mb
  - Relay_ğŸ‡¯ğŸ‡µJP-ğŸ‡¯ğŸ‡µJP_367 |11.16Mb
  - Relay_ğŸZZ-ğŸ‡®ğŸ‡·IR_395 |26.13Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
