port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: _257 |20.18Mb
  server: 216.238.86.158
  type: vmess
  port: 34460
  udp: true
  uuid: 90be214d-048c-4ea2-a602-b8e4d4e51e36
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: disney_DO |58.07Mb
  server: 45.150.52.40
  type: vmess
  port: 443
  uuid: c31777a1-2ee6-4864-db4c-a79fcbc8188b
  alterId: 0
  cipher: auto
  network: ws
  servername: xsj011-3.facai2024.com
  http-opts: {}
  h2-opts: {}
  tls: true
  ws-opts:
    path: /c31777a1
    headers:
      Host: xsj011-3.facai2024.com
- name: _233 |63.11Mb
  server: 3.89.113.22
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: _267 |183.19Mb
  server: 163.192.49.195
  type: vmess
  port: 443
  uuid: bcb7c581-3c95-4569-a4e7-918141e91ea3
  alterId: 0
  cipher: auto
  network: http
  http-opts:
    path:
    - /
    headers:
      Host:
      - a.189.cn
  h2-opts: {}
- name: _235 |405.41Mb
  server: 3.250.105.240
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: disney_US |173.93Mb
  server: 165.140.216.141
  type: vmess
  port: 443
  uuid: e7d72a8d-26f2-4b54-b366-0c43e0bcba7d
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _239 |18.43Mb
  server: 8.210.184.105
  type: vmess
  port: 40374
  udp: true
  uuid: 36b76373-7a4f-4669-9113-7d247bcf2704
  alterId: 0
  cipher: auto
  network: http
  http-opts:
    method: GET
    path:
    - /
  h2-opts: {}
- name: _242 |12.97Mb
  server: 47.242.140.52
  type: vmess
  port: 34815
  uuid: 1a46b66c-6ba9-4e9c-aa0b-0ebac2b69e32
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /arki
- name: _273 |23.33Mb
  server: 15.235.41.200
  type: vmess
  port: 80
  uuid: 58fe1542-5290-40ad-815a-77707a81afe5
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /IOebhLMhl1CTbFHbL95myfRX2
- name: disney_US |31.68Mb
  server: 192.204.47.79
  type: vmess
  port: 42277
  udp: true
  uuid: aee61b21-e85a-484b-f203-b245f1451cff
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _259 |32.14Mb
  server: 38.180.16.86
  type: vmess
  port: 36236
  uuid: a58bc1a5-8c18-49ff-9453-c331b52f45dc
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _254 |23.51Mb
  server: 183.236.51.36
  type: vmess
  port: 59003
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 64
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _279 |14.38Mb
  server: 51.79.102.253
  type: vmess
  port: 80
  uuid: 58fe1542-5290-40ad-815a-77707a81afe5
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /IOebhLMhl1CTbFHbL95myfRX2
    headers:
      Host: wrmelmwxlf.gktevlrqznwqqozy.fabpfs66gizmnojhcvqxwl.kytrcfzqla87gvgvs6c7kjnrubuh.cc
- name: disney_HK |16.43Mb
  server: 154.21.201.83
  type: vmess
  port: 443
  uuid: 4bf075f5-4d5e-4d39-f5ab-b32a86250f0e
  alterId: 0
  cipher: auto
  network: ws
  servername: hk.nbee.pp.ua
  http-opts: {}
  h2-opts: {}
  tls: true
  ws-opts:
    path: /aa
    headers:
      Host: hk.nbee.pp.ua
- name: Relay_-ğŸ‡§ğŸ‡·BR_263 |73.02Mb
  server: pq-brazil1.09vpn.com
  type: vmess
  port: 80
  uuid: c04c3b34-70fd-4fec-963e-c12d09f36bef
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /vmess/
    headers:
      Host: pq-brazil1.09vpn.com
- name: _236 |102.99Mb
  server: 154.223.20.79
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: _281 |10.68Mb
  server: 140.238.2.250
  type: vmess
  port: 443
  uuid: 41a7089a-040b-4538-8b8d-010902405bde
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _285 |22.26Mb
  server: 8.218.105.196
  type: vmess
  port: 52752
  uuid: 925bdbf5-72be-4437-bebf-441c61089f6b
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _292 |10.82Mb
  server: 54.206.192.9
  type: vmess
  port: 16407
  uuid: 08f45028-1db6-4e93-bf51-d344b6c71e19
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: disney_SG |15.75Mb
  server: 165.154.195.38
  type: vmess
  port: 35034
  uuid: 959a8caf-4cea-43d0-a548-3628e7ddfafc
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _288 |10.38Mb
  server: 209.38.31.133
  type: vmess
  port: 32077
  udp: true
  uuid: 412b22ec-e9d9-4ec6-d3ab-6a59537398bf
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _295 |45.99Mb
  server: 160.16.196.59
  type: trojan
  port: 2890
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: _294 |10.61Mb
  server: 130.162.152.253
  type: vmess
  port: 56867
  uuid: 5206bb9f-2cbc-44ac-de2a-471439a23707
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _293 |16.30Mb
  server: 47.243.51.237
  type: vmess
  port: 52801
  uuid: ef93f413-9039-4ddb-aefb-2490287df55a
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /arki
- name: _290 |110.48Mb
  server: 38.180.16.86
  type: vmess
  port: 38039
  uuid: 244a3464-1269-43b3-b491-4dc2713eb3f6
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _283 |43.24Mb
  server: 89.31.120.192
  type: vmess
  port: 443
  uuid: 44537595-9ccc-4b83-8936-5f9ad3229019
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _301 |24.70Mb
  server: 38.96.254.102
  type: trojan
  port: 18509
  password: .ie4rghJuMkcf0oF
  sni: shoppingmall.electricbanana.click
- name: _297 |55.52Mb
  server: 160.16.214.6
  type: trojan
  port: 2890
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¸ğŸ‡¬SG_298 |10.37Mb
  server: 160.16.153.13
  type: trojan
  port: 3145
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: disney_GB |310.01Mb
  server: 172.67.134.185
  type: trojan
  port: 443
  udp: true
  password: POORIARED
  sni: reDfRee8.REDFree8.ir
  ws-opts:
    path: /eyJqdW5rIjoiVUl6eXhLZkkwUTJ3ZzkiLCJwcm90b2NvbCI6InRyIiwibW9kZSI6InByb3h5aXAiLCJwYW5lbElQcyI6W119?ed=2560
    headers:
      Host: reDfRee8.REDFree8.ir
  network: ws
- name: Pool__296 |189.16Mb
  server: 70.34.218.149
  type: trojan
  port: 11930
  password: BaeSzHdfJIR13l67
  sni: softpillow.silentrocket.click
- name: _299 |22.46Mb
  server: 202.181.103.235
  type: trojan
  port: 2890
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: _307 |11.22Mb
  server: 153.121.65.107
  type: trojan
  port: 3093
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: _308 |58.77Mb
  server: 160.16.81.84
  type: trojan
  port: 4054
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: _310 |10.67Mb
  server: 153.121.53.187
  type: trojan
  port: 3093
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: _311 |56.75Mb
  server: 160.16.124.55
  type: trojan
  port: 2890
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: _312 |19.96Mb
  server: 153.121.51.29
  type: trojan
  port: 2890
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: _300 |26.00Mb
  server: 219.78.209.224
  type: trojan
  port: 443
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: _313 |13.97Mb
  server: 160.16.117.182
  type: trojan
  port: 3093
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: _315 |18.08Mb
  server: 160.16.229.223
  type: trojan
  port: 3093
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: _318 |42.80Mb
  server: 160.16.236.32
  type: trojan
  port: 4054
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: disney_FR |189.15Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 27092
  uuid: a0596ba6-72a3-4366-8992-77088da65bd8
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡©ğŸ‡ªDE_320 |251.00Mb
  server: 52.28.28.48
  type: trojan
  country: ğŸ‡©ğŸ‡ªDE
  port: 22222
  udp: true
  password: telegram-id-privatevpns
  sni: trojan.burgerip.co.uk
  skip-cert-verify: true
- name: ğŸ‡©ğŸ‡ªDE_321 |177.21Mb
  server: 3.126.180.133
  type: trojan
  country: ğŸ‡©ğŸ‡ªDE
  port: 22222
  udp: true
  password: telegram-id-privatevpns
  sni: trojan.burgerip.co.uk
  skip-cert-verify: true
- name: disney_FR |224.86Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 40433
  uuid: d8fd8955-78db-49ba-d86f-3e4729f6ac4d
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: netflix_NL |241.95Mb
  server: 82.38.31.217
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_327 |208.82Mb
  server: 82.38.31.191
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡²ğŸ‡½MX_338 |40.70Mb
  server: 216.238.87.47
  type: vmess
  country: ğŸ‡²ğŸ‡½MX
  port: 27502
  uuid: b8155ce4-7e08-4c40-800f-8671312b7124
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: netflix_IE |330.77Mb
  server: 52.50.200.2
  type: ss
  country: ğŸ‡®ğŸ‡ªIE
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: netflix_NL |246.30Mb
  server: 82.38.31.194
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: disney_HK |17.32Mb
  server: 45.207.157.29
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 13852
  uuid: 845764df-ecb3-4b13-bed2-bf1551b68e9a
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡ºğŸ‡¸US_341 |66.49Mb
  server: 18.207.122.59
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡ºğŸ‡¸US_342 |16.29Mb
  server: 47.253.197.26
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 12056
  uuid: dd7be7f1-38ff-45e6-f1e5-b20c2190f527
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡ºğŸ‡¸US_340 |29.79Mb
  server: 45.12.136.170
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: l668XHPejoSNNuD66BYzyehaCpZexiF7
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸ‡©ğŸ‡ªDE-ğŸ‡©ğŸ‡ªDE_319 |71.67Mb
  server: desrv.vmagnum.win
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 57456
  password: 345dbf842bce4b66
  cipher: chacha20-ietf-poly1305
- name: disney_US |95.34Mb
  server: cf.fovi.tk
  type: vmess
  country: ğŸZZ
  port: 443
  uuid: bf67437e-6c90-45ca-abc2-c7240a5ce2aa
  alterId: 0
  cipher: auto
  network: ws
  servername: foxpol.fovi.tk
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /eisasqa
    headers:
      HOST: foxpol.fovi.tk
- name: Relay_ğŸZZ-ğŸ‡ºğŸ‡¸US_344 |30.72Mb
  server: oneonefour.cnm-dns1114514.top
  type: vmess
  country: ğŸZZ
  port: 443
  uuid: 4abbe813-997d-42a0-89bb-40c8a1d54faf
  alterId: 0
  cipher: auto
  network: ws
  servername: xn--l9qya146a7xav76l.xn--4gqza090la383cba657a9rw23a362bz35amu9c.link
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /cnmdfhq
    headers:
      HOST: xn--l9qya146a7xav76l.xn--4gqza090la383cba657a9rw23a362bz35amu9c.link
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - _257 |20.18Mb
  - disney_DO |58.07Mb
  - _233 |63.11Mb
  - _267 |183.19Mb
  - _235 |405.41Mb
  - disney_US |173.93Mb
  - _239 |18.43Mb
  - _242 |12.97Mb
  - _273 |23.33Mb
  - disney_US |31.68Mb
  - _259 |32.14Mb
  - _254 |23.51Mb
  - _279 |14.38Mb
  - disney_HK |16.43Mb
  - Relay_-ğŸ‡§ğŸ‡·BR_263 |73.02Mb
  - _236 |102.99Mb
  - _281 |10.68Mb
  - _285 |22.26Mb
  - _292 |10.82Mb
  - disney_SG |15.75Mb
  - _288 |10.38Mb
  - _295 |45.99Mb
  - _294 |10.61Mb
  - _293 |16.30Mb
  - _290 |110.48Mb
  - _283 |43.24Mb
  - _301 |24.70Mb
  - _297 |55.52Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_298 |10.37Mb
  - disney_GB |310.01Mb
  - Pool__296 |189.16Mb
  - _299 |22.46Mb
  - _307 |11.22Mb
  - _308 |58.77Mb
  - _310 |10.67Mb
  - _311 |56.75Mb
  - _312 |19.96Mb
  - _300 |26.00Mb
  - _313 |13.97Mb
  - _315 |18.08Mb
  - _318 |42.80Mb
  - disney_FR |189.15Mb
  - ğŸ‡©ğŸ‡ªDE_320 |251.00Mb
  - ğŸ‡©ğŸ‡ªDE_321 |177.21Mb
  - disney_FR |224.86Mb
  - netflix_NL |241.95Mb
  - ğŸ‡¬ğŸ‡§GB_327 |208.82Mb
  - ğŸ‡²ğŸ‡½MX_338 |40.70Mb
  - netflix_IE |330.77Mb
  - netflix_NL |246.30Mb
  - disney_HK |17.32Mb
  - ğŸ‡ºğŸ‡¸US_341 |66.49Mb
  - ğŸ‡ºğŸ‡¸US_342 |16.29Mb
  - ğŸ‡ºğŸ‡¸US_340 |29.79Mb
  - Relay_ğŸ‡©ğŸ‡ªDE-ğŸ‡©ğŸ‡ªDE_319 |71.67Mb
  - disney_US |95.34Mb
  - Relay_ğŸZZ-ğŸ‡ºğŸ‡¸US_344 |30.72Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - _257 |20.18Mb
  - disney_DO |58.07Mb
  - _233 |63.11Mb
  - _267 |183.19Mb
  - _235 |405.41Mb
  - disney_US |173.93Mb
  - _239 |18.43Mb
  - _242 |12.97Mb
  - _273 |23.33Mb
  - disney_US |31.68Mb
  - _259 |32.14Mb
  - _254 |23.51Mb
  - _279 |14.38Mb
  - disney_HK |16.43Mb
  - Relay_-ğŸ‡§ğŸ‡·BR_263 |73.02Mb
  - _236 |102.99Mb
  - _281 |10.68Mb
  - _285 |22.26Mb
  - _292 |10.82Mb
  - disney_SG |15.75Mb
  - _288 |10.38Mb
  - _295 |45.99Mb
  - _294 |10.61Mb
  - _293 |16.30Mb
  - _290 |110.48Mb
  - _283 |43.24Mb
  - _301 |24.70Mb
  - _297 |55.52Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_298 |10.37Mb
  - disney_GB |310.01Mb
  - Pool__296 |189.16Mb
  - _299 |22.46Mb
  - _307 |11.22Mb
  - _308 |58.77Mb
  - _310 |10.67Mb
  - _311 |56.75Mb
  - _312 |19.96Mb
  - _300 |26.00Mb
  - _313 |13.97Mb
  - _315 |18.08Mb
  - _318 |42.80Mb
  - disney_FR |189.15Mb
  - ğŸ‡©ğŸ‡ªDE_320 |251.00Mb
  - ğŸ‡©ğŸ‡ªDE_321 |177.21Mb
  - disney_FR |224.86Mb
  - netflix_NL |241.95Mb
  - ğŸ‡¬ğŸ‡§GB_327 |208.82Mb
  - ğŸ‡²ğŸ‡½MX_338 |40.70Mb
  - netflix_IE |330.77Mb
  - netflix_NL |246.30Mb
  - disney_HK |17.32Mb
  - ğŸ‡ºğŸ‡¸US_341 |66.49Mb
  - ğŸ‡ºğŸ‡¸US_342 |16.29Mb
  - ğŸ‡ºğŸ‡¸US_340 |29.79Mb
  - Relay_ğŸ‡©ğŸ‡ªDE-ğŸ‡©ğŸ‡ªDE_319 |71.67Mb
  - disney_US |95.34Mb
  - Relay_ğŸZZ-ğŸ‡ºğŸ‡¸US_344 |30.72Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
