port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: _311 |35.65Mb
  server: pupas-shirting-unsung.freesocks.work
  type: ss
  port: 443
  udp: true
  password: p78naCf2EfOlRSLTX0wFVx
  cipher: chacha20-ietf-poly1305
- name: _306 |44.50Mb
  server: 185.82.73.212
  type: ss
  port: 8444
  udp: true
  password: _bypfvq6ra7g4n5yCCR9DoVeGya2XUUS
  cipher: chacha20-ietf-poly1305
- name: _319 |155.67Mb
  server: 82.38.31.176
  type: ss
  port: 8080
  udp: true
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: _300 |33.88Mb
  server: 62.100.205.100
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _313 |12.32Mb
  server: 45.87.175.22
  type: ss
  port: 8080
  udp: true
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: _307 |276.04Mb
  server: 45.14.245.2
  type: ss
  port: 443
  password: 17ZDORWIliQHuO6WRGHChXYMzdRtAYVP
  cipher: chacha20-ietf-poly1305
- name: _299 |14.23Mb
  server: 194.59.183.134
  type: ss
  port: 46114
  udp: true
  password: lejSRyqa033OEPmEQsvRsl
  cipher: chacha20-ietf-poly1305
- name: _308 |360.43Mb
  server: 46.183.184.60
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: Relay_-ğŸ‡­ğŸ‡°HK_315 |28.26Mb
  server: 103.149.182.105
  type: ss
  port: 8388
  password: asd123456
  cipher: chacha20-ietf
- name: _326 |10.77Mb
  server: 82.38.31.199
  type: ss
  port: 8080
  udp: true
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: _330 |47.66Mb
  server: 173.234.29.2
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: Relay_-ğŸ‡¨ğŸ‡¦CA_327 |69.70Mb
  server: 79.127.200.169
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _332 |47.80Mb
  server: 185.47.254.87
  type: ss
  port: 990
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: chacha20-ietf-poly1305
- name: netflix_US |72.65Mb
  server: 172.233.229.91
  type: vmess
  port: 14102
  udp: true
  uuid: 27ba87fc-583f-4763-9060-83cf0b9264db
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: _316 |44.25Mb
  server: 103.97.203.227
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _335 |229.34Mb
  server: 82.38.31.214
  type: ss
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: _352 |11.02Mb
  server: 160.16.131.243
  type: trojan
  port: 2760
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
  skip-cert-verify: true
- name: netflix_NL |231.30Mb
  server: 151.242.251.152
  type: ss
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: Relay_-ğŸ‡¯ğŸ‡µJP_353 |11.60Mb
  server: 153.121.45.139
  type: trojan
  port: 3093
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: disney_PY |17.10Mb
  server: 38.165.233.93
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: _344 |23.59Mb
  server: 47.242.145.160
  type: vmess
  port: 44457
  uuid: 40290609-2743-4d85-c9c3-4c72dd151b9f
  alterId: 0
  cipher: auto
  network: http
  http-opts:
    method: GET
    path:
    - /
  h2-opts: {}
- name: _356 |10.72Mb
  server: 160.16.116.227
  type: trojan
  port: 2760
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
  skip-cert-verify: true
- name: _354 |13.86Mb
  server: 112.118.116.8
  type: trojan
  port: 443
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¯ğŸ‡µJP_360 |13.67Mb
  server: 160.16.229.223
  type: trojan
  port: 3169
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: _329 |44.33Mb
  server: 156.59.243.6
  type: ss
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: disney_DE |263.19Mb
  server: 89.163.140.136
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ğŸ‡¨ğŸ‡¦CA_366 |63.72Mb
  server: 185.213.23.63
  type: ss
  country: ğŸ‡¨ğŸ‡¦CA
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _361 |12.38Mb
  server: 219.79.214.159
  type: trojan
  port: 443
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: Relay_ğŸ‡¬ğŸ‡§GB-ğŸ‡³ğŸ‡±NL_370 |198.10Mb
  server: 82.38.31.208
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: disney_HK |29.63Mb
  server: 45.207.157.29
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 13852
  uuid: 845764df-ecb3-4b13-bed2-bf1551b68e9a
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡²ğŸ‡½MX_388 |38.57Mb
  server: 216.238.87.47
  type: vmess
  country: ğŸ‡²ğŸ‡½MX
  port: 27502
  uuid: b8155ce4-7e08-4c40-800f-8671312b7124
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡®ğŸ‡¹IT_377 |17.66Mb
  server: 176.126.83.121
  type: ss
  country: ğŸ‡®ğŸ‡¹IT
  port: 443
  password: Q4t8T7hEYY3mD2Fn4wnxyK4X35AUzvR8
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_381 |237.02Mb
  server: 45.87.175.185
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_384 |246.76Mb
  server: 45.87.175.183
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_385 |242.49Mb
  server: 45.87.175.185
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡²ğŸ‡©MD_387 |61.68Mb
  server: 176.123.5.253
  type: ss
  country: ğŸ‡²ğŸ‡©MD
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡µğŸ‡¹PT_392 |31.85Mb
  server: 185.113.143.186
  type: ss
  country: ğŸ‡µğŸ‡¹PT
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ ZZ_395 |90.06Mb
  server: 185.231.233.112
  type: ss
  country: ğŸ ZZ
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ğŸ‡±ğŸ‡¹LT_380 |10.16Mb
  server: ltnl16.saint.ydns.eu
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸZZ-ğŸ‡®ğŸ‡·IR_397 |26.13Mb
  server: cf.fovi.tk
  type: vmess
  country: ğŸZZ
  port: 443
  uuid: bf67437e-6c90-45ca-abc2-c7240a5ce2aa
  alterId: 0
  cipher: auto
  network: ws
  servername: foxlux.fovi.tk
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /eisasqa
    headers:
      HOST: foxlux.fovi.tk
- name: ğŸ‡±ğŸ‡» LV_386 |78.86Mb
  server: 46.183.217.204
  type: ss
  country: ğŸ‡±ğŸ‡» LV
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - _311 |35.65Mb
  - _306 |44.50Mb
  - _319 |155.67Mb
  - _300 |33.88Mb
  - _313 |12.32Mb
  - _307 |276.04Mb
  - _299 |14.23Mb
  - _308 |360.43Mb
  - Relay_-ğŸ‡­ğŸ‡°HK_315 |28.26Mb
  - _326 |10.77Mb
  - _330 |47.66Mb
  - Relay_-ğŸ‡¨ğŸ‡¦CA_327 |69.70Mb
  - _332 |47.80Mb
  - netflix_US |72.65Mb
  - _316 |44.25Mb
  - _335 |229.34Mb
  - _352 |11.02Mb
  - netflix_NL |231.30Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_353 |11.60Mb
  - disney_PY |17.10Mb
  - _344 |23.59Mb
  - _356 |10.72Mb
  - _354 |13.86Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_360 |13.67Mb
  - _329 |44.33Mb
  - disney_DE |263.19Mb
  - ğŸ‡¨ğŸ‡¦CA_366 |63.72Mb
  - _361 |12.38Mb
  - Relay_ğŸ‡¬ğŸ‡§GB-ğŸ‡³ğŸ‡±NL_370 |198.10Mb
  - disney_HK |29.63Mb
  - ğŸ‡²ğŸ‡½MX_388 |38.57Mb
  - ğŸ‡®ğŸ‡¹IT_377 |17.66Mb
  - ğŸ‡±ğŸ‡¹LT_381 |237.02Mb
  - ğŸ‡±ğŸ‡¹LT_384 |246.76Mb
  - ğŸ‡±ğŸ‡¹LT_385 |242.49Mb
  - ğŸ‡²ğŸ‡©MD_387 |61.68Mb
  - ğŸ‡µğŸ‡¹PT_392 |31.85Mb
  - ğŸ ZZ_395 |90.06Mb
  - ğŸ‡±ğŸ‡¹LT_380 |10.16Mb
  - Relay_ğŸZZ-ğŸ‡®ğŸ‡·IR_397 |26.13Mb
  - ğŸ‡±ğŸ‡» LV_386 |78.86Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - _311 |35.65Mb
  - _306 |44.50Mb
  - _319 |155.67Mb
  - _300 |33.88Mb
  - _313 |12.32Mb
  - _307 |276.04Mb
  - _299 |14.23Mb
  - _308 |360.43Mb
  - Relay_-ğŸ‡­ğŸ‡°HK_315 |28.26Mb
  - _326 |10.77Mb
  - _330 |47.66Mb
  - Relay_-ğŸ‡¨ğŸ‡¦CA_327 |69.70Mb
  - _332 |47.80Mb
  - netflix_US |72.65Mb
  - _316 |44.25Mb
  - _335 |229.34Mb
  - _352 |11.02Mb
  - netflix_NL |231.30Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_353 |11.60Mb
  - disney_PY |17.10Mb
  - _344 |23.59Mb
  - _356 |10.72Mb
  - _354 |13.86Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_360 |13.67Mb
  - _329 |44.33Mb
  - disney_DE |263.19Mb
  - ğŸ‡¨ğŸ‡¦CA_366 |63.72Mb
  - _361 |12.38Mb
  - Relay_ğŸ‡¬ğŸ‡§GB-ğŸ‡³ğŸ‡±NL_370 |198.10Mb
  - disney_HK |29.63Mb
  - ğŸ‡²ğŸ‡½MX_388 |38.57Mb
  - ğŸ‡®ğŸ‡¹IT_377 |17.66Mb
  - ğŸ‡±ğŸ‡¹LT_381 |237.02Mb
  - ğŸ‡±ğŸ‡¹LT_384 |246.76Mb
  - ğŸ‡±ğŸ‡¹LT_385 |242.49Mb
  - ğŸ‡²ğŸ‡©MD_387 |61.68Mb
  - ğŸ‡µğŸ‡¹PT_392 |31.85Mb
  - ğŸ ZZ_395 |90.06Mb
  - ğŸ‡±ğŸ‡¹LT_380 |10.16Mb
  - Relay_ğŸZZ-ğŸ‡®ğŸ‡·IR_397 |26.13Mb
  - ğŸ‡±ğŸ‡» LV_386 |78.86Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
