port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: disney_netflix_US |58.48Mb
  server: 45.150.52.40
  type: vmess
  port: 443
  uuid: c31777a1-2ee6-4864-db4c-a79fcbc8188b
  alterId: 0
  cipher: auto
  network: ws
  servername: xsj011-3.facai2024.com
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /c31777a1
- name: disney_netflix_US |11.03Mb
  server: 160.16.214.6
  type: trojan
  port: 2890
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: disney_netflix_HK |28.09Mb
  server: 58.152.110.82
  type: trojan
  port: 443
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: _105 |25.97Mb
  server: 8.218.105.196
  type: vmess
  port: 52752
  uuid: 925bdbf5-72be-4437-bebf-441c61089f6b
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
- name: disney_netflix_SG |23.41Mb
  server: 103.36.91.32
  type: ss
  port: 8388
  udp: true
  password: asd123456
  cipher: chacha20-ietf
- name: disney_netflix_HK |14.78Mb
  server: 58.152.30.120
  type: trojan
  port: 443
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: disney_netflix_US |11.05Mb
  server: 202.181.103.235
  type: trojan
  port: 2890
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: netflix_JP |16.91Mb
  server: 153.121.73.102
  type: trojan
  port: 1331
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: disney_netflix_FR |184.87Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 40433
  uuid: d8fd8955-78db-49ba-d86f-3e4729f6ac4d
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: netflix_JP |14.87Mb
  server: 160.16.242.183
  type: trojan
  port: 1331
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: _133 |11.72Mb
  server: 160.16.229.223
  type: trojan
  port: 3093
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: disney_netflix_FR |34.23Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 27092
  uuid: a0596ba6-72a3-4366-8992-77088da65bd8
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: netflix_MX |38.39Mb
  server: 216.238.89.53
  type: vmess
  country: ğŸ‡²ğŸ‡½MX
  port: 57283
  uuid: 1a5aafc0-6482-451d-fe76-6875b7818579
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: netflix_NL |248.84Mb
  server: 82.38.31.184
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: netflix_NL |64.77Mb
  server: 51.15.17.169
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: disney_netflix_US |30.38Mb
  server: 195.66.27.148
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 28709
  password: hShp1Km0NcFSmSigc8ozky
  cipher: chacha20-ietf-poly1305
- name: netflix_IE |84.99Mb
  server: 146.70.90.196
  type: ss
  country: ğŸ‡®ğŸ‡ªIE
  port: 17454
  password: u8gp148iz90ddoo6ms37
  cipher: aes-128-gcm
- name: disney_netflix_US |40.13Mb
  server: 38.14.99.163
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 59807
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: auto
  network: tcp
  servername: 38.14.99.163
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: netflix_GR |10.30Mb
  server: 192.71.166.100
  type: ss
  country: ğŸ‡¬ğŸ‡·GR
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: disney_RU |48.04Mb
  server: 81.200.158.206
  type: ss
  country: ğŸ‡·ğŸ‡ºRU
  port: 1080
  password: AqZbt1QCs3ngEfXo1p7T-w
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_HK |160.98Mb
  server: 8.218.116.26
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 32228
  uuid: e4767e9f-ed00-4f31-a984-a918bdd9b09c
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_SE |42.14Mb
  server: 91.186.217.246
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 31764
  password: Ftc17VH9ZXQON5vslJCYmv
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_183 |14.33Mb
  server: 45.136.12.37
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 38141
  uuid: fd291be6-b48d-43a1-da38-66c7f80e2f80
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_US |28.85Mb
  server: cf.fovi.tk
  type: vmess
  country: ğŸZZ
  port: 443
  uuid: bf67437e-6c90-45ca-abc2-c7240a5ce2aa
  alterId: 0
  cipher: auto
  network: ws
  servername: foxlux.fovi.tk
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /eisasqa
    headers:
      HOST: foxlux.fovi.tk
- name: disney_netflix_HK |10.21Mb
  server: aflzzul.meiquankongjian.com
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 52511
  uuid: 342bacfd-2b8f-3f49-a16e-439db5b0b9d5
  alterId: 0
  cipher: auto
  network: ws
  servername: aflzzul.meiquankongjian.com
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
  ws-opts:
    path: /564dfa20/
    headers:
      HOST: aflzzul.meiquankongjian.com
- name: disney_netflix_HK |10.29Mb
  server: aflzzul.meiquankongjian.com
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 52513
  uuid: 342bacfd-2b8f-3f49-a16e-439db5b0b9d5
  alterId: 0
  cipher: auto
  network: ws
  servername: aflzzul.meiquankongjian.com
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
  ws-opts:
    path: /564dfa20/
    headers:
      HOST: aflzzul.meiquankongjian.com
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - disney_netflix_US |58.48Mb
  - disney_netflix_US |11.03Mb
  - disney_netflix_HK |28.09Mb
  - _105 |25.97Mb
  - disney_netflix_SG |23.41Mb
  - disney_netflix_HK |14.78Mb
  - disney_netflix_US |11.05Mb
  - netflix_JP |16.91Mb
  - disney_netflix_FR |184.87Mb
  - netflix_JP |14.87Mb
  - _133 |11.72Mb
  - disney_netflix_FR |34.23Mb
  - netflix_MX |38.39Mb
  - netflix_NL |248.84Mb
  - netflix_NL |64.77Mb
  - disney_netflix_US |30.38Mb
  - netflix_IE |84.99Mb
  - disney_netflix_US |40.13Mb
  - netflix_GR |10.30Mb
  - disney_RU |48.04Mb
  - disney_netflix_HK |160.98Mb
  - disney_netflix_SE |42.14Mb
  - ğŸ‡ºğŸ‡¸US_183 |14.33Mb
  - disney_netflix_US |28.85Mb
  - disney_netflix_HK |10.21Mb
  - disney_netflix_HK |10.29Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - disney_netflix_US |58.48Mb
  - disney_netflix_US |11.03Mb
  - disney_netflix_HK |28.09Mb
  - _105 |25.97Mb
  - disney_netflix_SG |23.41Mb
  - disney_netflix_HK |14.78Mb
  - disney_netflix_US |11.05Mb
  - netflix_JP |16.91Mb
  - disney_netflix_FR |184.87Mb
  - netflix_JP |14.87Mb
  - _133 |11.72Mb
  - disney_netflix_FR |34.23Mb
  - netflix_MX |38.39Mb
  - netflix_NL |248.84Mb
  - netflix_NL |64.77Mb
  - disney_netflix_US |30.38Mb
  - netflix_IE |84.99Mb
  - disney_netflix_US |40.13Mb
  - netflix_GR |10.30Mb
  - disney_RU |48.04Mb
  - disney_netflix_HK |160.98Mb
  - disney_netflix_SE |42.14Mb
  - ğŸ‡ºğŸ‡¸US_183 |14.33Mb
  - disney_netflix_US |28.85Mb
  - disney_netflix_HK |10.21Mb
  - disney_netflix_HK |10.29Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
