port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: _249 |248.20Mb
  server: 216.238.86.158
  type: vmess
  port: 34460
  udp: true
  uuid: 90be214d-048c-4ea2-a602-b8e4d4e51e36
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: disney_US |36.03Mb
  server: 192.204.47.79
  type: vmess
  port: 42277
  udp: true
  uuid: aee61b21-e85a-484b-f203-b245f1451cff
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: disney_US |42.04Mb
  server: 165.140.216.141
  type: vmess
  port: 443
  uuid: e7d72a8d-26f2-4b54-b366-0c43e0bcba7d
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _243 |42.35Mb
  server: 163.192.49.195
  type: vmess
  port: 443
  uuid: bcb7c581-3c95-4569-a4e7-918141e91ea3
  alterId: 0
  cipher: auto
  network: http
  http-opts:
    path:
    - /
    headers:
      Host:
      - a.189.cn
  h2-opts: {}
- name: _255 |49.74Mb
  server: 45.150.52.40
  type: vmess
  port: 443
  uuid: c31777a1-2ee6-4864-db4c-a79fcbc8188b
  alterId: 0
  cipher: auto
  network: ws
  servername: xsj011-3.facai2024.com
  http-opts: {}
  h2-opts: {}
  tls: true
  ws-opts:
    path: /c31777a1
    headers:
      Host: xsj011-3.facai2024.com
- name: _239 |690.17Mb
  server: 85.195.101.122
  type: vmess
  port: 40878
  uuid: f3d4167e-b15e-4e46-82e9-9286ef93fda7
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _231 |394.86Mb
  server: 185.153.197.5
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: _273 |77.28Mb
  server: 209.126.84.189
  type: vmess
  port: 443
  uuid: 2c981164-9b93-4bca-94ff-b78d3f8498d7
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /vmessws
- name: _256 |10.54Mb
  server: 38.180.16.86
  type: vmess
  port: 38039
  uuid: 244a3464-1269-43b3-b491-4dc2713eb3f6
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _235 |10.42Mb
  server: 54.206.192.9
  type: vmess
  port: 16407
  uuid: 08f45028-1db6-4e93-bf51-d344b6c71e19
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _261 |11.15Mb
  server: 38.180.16.86
  type: vmess
  port: 36236
  uuid: a58bc1a5-8c18-49ff-9453-c331b52f45dc
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: Relay_-ğŸ‡­ğŸ‡°HK_246 |17.84Mb
  server: 154.21.201.83
  type: vmess
  port: 443
  uuid: 4bf075f5-4d5e-4d39-f5ab-b32a86250f0e
  alterId: 0
  cipher: auto
  network: ws
  servername: hk.nbee.pp.ua
  http-opts: {}
  h2-opts: {}
  tls: true
  ws-opts:
    path: /aa
    headers:
      Host: hk.nbee.pp.ua
- name: _247 |23.99Mb
  server: 8.218.116.26
  type: vmess
  port: 32228
  uuid: e4767e9f-ed00-4f31-a984-a918bdd9b09c
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _283 |11.58Mb
  server: 51.79.102.253
  type: vmess
  port: 80
  uuid: 58fe1542-5290-40ad-815a-77707a81afe5
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /IOebhLMhl1CTbFHbL95myfRX2
    headers:
      Host: wrmelmwxlf.gktevlrqznwqqozy.fabpfs66gizmnojhcvqxwl.kytrcfzqla87gvgvs6c7kjnrubuh.cc
- name: _257 |20.98Mb
  server: 47.243.51.237
  type: vmess
  port: 52801
  uuid: ef93f413-9039-4ddb-aefb-2490287df55a
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /arki
- name: disney_HK |21.64Mb
  server: 45.136.12.37
  type: vmess
  port: 38141
  uuid: fd291be6-b48d-43a1-da38-66c7f80e2f80
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _276 |11.03Mb
  server: 140.238.2.250
  type: vmess
  port: 443
  uuid: 41a7089a-040b-4538-8b8d-010902405bde
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: Pool__302 |35.53Mb
  server: 70.34.218.149
  type: trojan
  port: 11930
  password: BaeSzHdfJIR13l67
  sni: softpillow.silentrocket.click
- name: _295 |11.29Mb
  server: 160.16.236.32
  type: trojan
  port: 4054
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: _278 |11.05Mb
  server: 130.162.152.253
  type: vmess
  port: 56867
  uuid: 5206bb9f-2cbc-44ac-de2a-471439a23707
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: Relay_-ğŸ‡¸ğŸ‡¬SG_297 |11.06Mb
  server: 160.16.144.208
  type: trojan
  port: 507
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: disney_FR |29.30Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 27092
  uuid: a0596ba6-72a3-4366-8992-77088da65bd8
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_FR |26.70Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 40433
  uuid: d8fd8955-78db-49ba-d86f-3e4729f6ac4d
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: _292 |13.20Mb
  server: 47.242.140.52
  type: vmess
  port: 34815
  uuid: 1a46b66c-6ba9-4e9c-aa0b-0ebac2b69e32
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /arki
- name: _304 |16.46Mb
  server: 153.121.53.187
  type: trojan
  port: 3093
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: ğŸ‡¬ğŸ‡§GB_309 |238.33Mb
  server: 82.38.31.194
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: _287 |40.46Mb
  server: 89.31.120.192
  type: vmess
  port: 443
  uuid: 44537595-9ccc-4b83-8936-5f9ad3229019
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: ğŸ‡¬ğŸ‡§GB_310 |143.24Mb
  server: 82.38.31.191
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡²ğŸ‡½MX_320 |240.57Mb
  server: 216.238.87.47
  type: vmess
  country: ğŸ‡²ğŸ‡½MX
  port: 27502
  uuid: b8155ce4-7e08-4c40-800f-8671312b7124
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡¬ğŸ‡§GB_311 |203.77Mb
  server: 82.38.31.217
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: disney_HK |15.52Mb
  server: 45.207.157.29
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 13852
  uuid: 845764df-ecb3-4b13-bed2-bf1551b68e9a
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡·ğŸ‡ºRU_321 |19.23Mb
  server: 45.129.2.185
  type: ss
  country: ğŸ‡·ğŸ‡ºRU
  port: 10081
  password: c5fcdf7829112cb4
  cipher: aes-256-gcm
- name: ğŸ‡ºğŸ‡¸US_324 |12.86Mb
  server: 47.253.197.26
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 12056
  uuid: dd7be7f1-38ff-45e6-f1e5-b20c2190f527
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: _229 |15.45Mb
  server: 45.14.245.2
  type: ss
  port: 443
  password: 17ZDORWIliQHuO6WRGHChXYMzdRtAYVP
  cipher: chacha20-ietf-poly1305
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - _249 |248.20Mb
  - disney_US |36.03Mb
  - disney_US |42.04Mb
  - _243 |42.35Mb
  - _255 |49.74Mb
  - _239 |690.17Mb
  - _231 |394.86Mb
  - _273 |77.28Mb
  - _256 |10.54Mb
  - _235 |10.42Mb
  - _261 |11.15Mb
  - Relay_-ğŸ‡­ğŸ‡°HK_246 |17.84Mb
  - _247 |23.99Mb
  - _283 |11.58Mb
  - _257 |20.98Mb
  - disney_HK |21.64Mb
  - _276 |11.03Mb
  - Pool__302 |35.53Mb
  - _295 |11.29Mb
  - _278 |11.05Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_297 |11.06Mb
  - disney_FR |29.30Mb
  - disney_netflix_FR |26.70Mb
  - _292 |13.20Mb
  - _304 |16.46Mb
  - ğŸ‡¬ğŸ‡§GB_309 |238.33Mb
  - _287 |40.46Mb
  - ğŸ‡¬ğŸ‡§GB_310 |143.24Mb
  - ğŸ‡²ğŸ‡½MX_320 |240.57Mb
  - ğŸ‡¬ğŸ‡§GB_311 |203.77Mb
  - disney_HK |15.52Mb
  - ğŸ‡·ğŸ‡ºRU_321 |19.23Mb
  - ğŸ‡ºğŸ‡¸US_324 |12.86Mb
  - _229 |15.45Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - _249 |248.20Mb
  - disney_US |36.03Mb
  - disney_US |42.04Mb
  - _243 |42.35Mb
  - _255 |49.74Mb
  - _239 |690.17Mb
  - _231 |394.86Mb
  - _273 |77.28Mb
  - _256 |10.54Mb
  - _235 |10.42Mb
  - _261 |11.15Mb
  - Relay_-ğŸ‡­ğŸ‡°HK_246 |17.84Mb
  - _247 |23.99Mb
  - _283 |11.58Mb
  - _257 |20.98Mb
  - disney_HK |21.64Mb
  - _276 |11.03Mb
  - Pool__302 |35.53Mb
  - _295 |11.29Mb
  - _278 |11.05Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_297 |11.06Mb
  - disney_FR |29.30Mb
  - disney_netflix_FR |26.70Mb
  - _292 |13.20Mb
  - _304 |16.46Mb
  - ğŸ‡¬ğŸ‡§GB_309 |238.33Mb
  - _287 |40.46Mb
  - ğŸ‡¬ğŸ‡§GB_310 |143.24Mb
  - ğŸ‡²ğŸ‡½MX_320 |240.57Mb
  - ğŸ‡¬ğŸ‡§GB_311 |203.77Mb
  - disney_HK |15.52Mb
  - ğŸ‡·ğŸ‡ºRU_321 |19.23Mb
  - ğŸ‡ºğŸ‡¸US_324 |12.86Mb
  - _229 |15.45Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
