port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: _225 |16.84Mb
  server: 66.23.207.82
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _202 |11.12Mb
  server: 94.156.250.122
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡§ğŸ‡ªBE_239 |11.53Mb
  server: 192.71.249.71
  type: ss
  country: ğŸ‡§ğŸ‡ªBE
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: _233 |17.20Mb
  server: 212.102.54.45
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _230 |10.73Mb
  server: 37.235.56.69
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _216 |10.74Mb
  server: 91.219.237.163
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _232 |21.17Mb
  server: 103.106.228.247
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _206 |11.29Mb
  server: 154.205.153.107
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _228 |22.31Mb
  server: 45.159.250.190
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _234 |20.05Mb
  server: 38.54.57.90
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_302 |45.70Mb
  server: 104.192.227.162
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: aWqt2Jx9cPauhC7Bb1BdwK
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_259 |12.85Mb
  server: 78.129.140.11
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: eG6vFZCvIm7439CFR6LenJ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_257 |15.11Mb
  server: 13.40.127.189
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: _231 |23.97Mb
  server: 37.143.130.203
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ªğŸ‡¸ES_253 |12.04Mb
  server: 194.87.45.189
  type: ss
  country: ğŸ‡ªğŸ‡¸ES
  port: 443
  password: XSVQG5Ul3Md0Kutdu819aQ
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸ‡®ğŸ‡·IR-ğŸ‡³ğŸ‡±NL_270 |23.42Mb
  server: 151.242.251.131
  type: ss
  country: ğŸ‡®ğŸ‡·IR
  port: 8080
  password: QCXDxuDlTTMD7jtgHUjIoj
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡­ğŸ‡·HR_266 |10.60Mb
  server: 169.150.242.77
  type: ss
  country: ğŸ‡­ğŸ‡·HR
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ªğŸ‡¸ES_254 |46.26Mb
  server: 194.87.45.189
  type: ss
  country: ğŸ‡ªğŸ‡¸ES
  port: 443
  password: VgliqHHPyAsjMKiDU2DReX
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¸ğŸ‡ªSE_288 |14.59Mb
  server: 121.127.46.147
  type: ss
  country: ğŸ‡¸ğŸ‡ªSE
  port: 990
  password: f8f7aCzcPKbsF8p3
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¸ğŸ‡¬SG_292 |14.54Mb
  server: 68.183.227.236
  type: ss
  country: ğŸ‡¸ğŸ‡¬SG
  port: 8080
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - _225 |16.84Mb
  - _202 |11.12Mb
  - ğŸ‡§ğŸ‡ªBE_239 |11.53Mb
  - _233 |17.20Mb
  - _230 |10.73Mb
  - _216 |10.74Mb
  - _232 |21.17Mb
  - _206 |11.29Mb
  - _228 |22.31Mb
  - _234 |20.05Mb
  - ğŸ‡ºğŸ‡¸US_302 |45.70Mb
  - ğŸ‡¬ğŸ‡§GB_259 |12.85Mb
  - ğŸ‡¬ğŸ‡§GB_257 |15.11Mb
  - _231 |23.97Mb
  - ğŸ‡ªğŸ‡¸ES_253 |12.04Mb
  - Relay_ğŸ‡®ğŸ‡·IR-ğŸ‡³ğŸ‡±NL_270 |23.42Mb
  - ğŸ‡­ğŸ‡·HR_266 |10.60Mb
  - ğŸ‡ªğŸ‡¸ES_254 |46.26Mb
  - ğŸ‡¸ğŸ‡ªSE_288 |14.59Mb
  - ğŸ‡¸ğŸ‡¬SG_292 |14.54Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - _225 |16.84Mb
  - _202 |11.12Mb
  - ğŸ‡§ğŸ‡ªBE_239 |11.53Mb
  - _233 |17.20Mb
  - _230 |10.73Mb
  - _216 |10.74Mb
  - _232 |21.17Mb
  - _206 |11.29Mb
  - _228 |22.31Mb
  - _234 |20.05Mb
  - ğŸ‡ºğŸ‡¸US_302 |45.70Mb
  - ğŸ‡¬ğŸ‡§GB_259 |12.85Mb
  - ğŸ‡¬ğŸ‡§GB_257 |15.11Mb
  - _231 |23.97Mb
  - ğŸ‡ªğŸ‡¸ES_253 |12.04Mb
  - Relay_ğŸ‡®ğŸ‡·IR-ğŸ‡³ğŸ‡±NL_270 |23.42Mb
  - ğŸ‡­ğŸ‡·HR_266 |10.60Mb
  - ğŸ‡ªğŸ‡¸ES_254 |46.26Mb
  - ğŸ‡¸ğŸ‡ªSE_288 |14.59Mb
  - ğŸ‡¸ğŸ‡¬SG_292 |14.54Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
