port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: _97 |29.47Mb
  server: 173.234.29.2
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _96 |22.72Mb
  server: 66.23.207.82
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _125 |10.48Mb
  server: 167.160.90.178
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _116 |31.78Mb
  server: 138.186.142.81
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _108 |39.42Mb
  server: 138.186.142.80
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _135 |22.23Mb
  server: 94.156.250.122
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _136 |26.25Mb
  server: 62.100.205.100
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _99 |22.31Mb
  server: 212.102.54.45
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¨ğŸ‡¿CZ_161 |27.86Mb
  server: 185.193.102.7
  type: ss
  country: ğŸ‡¨ğŸ‡¿CZ
  port: 57456
  password: 360e21d21977dc11
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡©ğŸ‡ªDE_164 |22.62Mb
  server: 18.199.153.21
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡©ğŸ‡ªDE_166 |47.98Mb
  server: 80.71.157.175
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 38211
  password: sbcaggqmDXHgUPN2DH1tVd
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡©ğŸ‡ªDE_167 |25.14Mb
  server: 18.196.23.20
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡©ğŸ‡ªDE_170 |26.21Mb
  server: 81.19.141.45
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 443
  password: mGmgnK6npgEFJS6kk2ox2P
  cipher: chacha20-ietf-poly1305
- name: _121 |10.79Mb
  server: 38.60.250.107
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _113 |20.67Mb
  server: 156.38.168.58
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡©ğŸ‡ªDE_176 |11.90Mb
  server: 18.196.156.200
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: _129 |18.77Mb
  server: 37.143.130.203
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡©ğŸ‡ªDE_177 |19.23Mb
  server: 81.19.141.45
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 443
  password: zq45RWqdUm3yjqBQpl9tBC
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡©ğŸ‡ªDE_178 |28.37Mb
  server: 81.19.141.45
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 443
  password: ql8iN6ChurUrd25DoZJA0n
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡©ğŸ‡ªDE_179 |27.52Mb
  server: 81.19.141.45
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 443
  password: 4FGE1sy7r8aLz8esdjXCXf
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡©ğŸ‡ªDE_180 |17.72Mb
  server: 81.19.141.45
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 443
  password: OL7MQydIsTbln3xOq4lVvM
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡©ğŸ‡ªDE_182 |46.59Mb
  server: 81.19.141.45
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 443
  password: pljs8t12Vkxy63KgIOkhZw
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡©ğŸ‡ªDE_183 |40.15Mb
  server: 81.19.141.45
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 443
  password: JBq3UYSKFAuzC0LPTxg7wj
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡©ğŸ‡ªDE_184 |24.45Mb
  server: 3.66.163.109
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡©ğŸ‡ªDE_185 |38.28Mb
  server: 81.19.141.45
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 443
  password: 1UpoeQy99jkkF8txSy44qb
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡©ğŸ‡ªDE_188 |24.06Mb
  server: 81.19.141.45
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 443
  password: k06muRwkorkwIVFiX2s6e5
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡©ğŸ‡ªDE_191 |17.07Mb
  server: 18.195.116.149
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡©ğŸ‡ªDE_190 |12.16Mb
  server: 18.196.31.30
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡©ğŸ‡ªDE_192 |17.57Mb
  server: 81.19.141.45
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 443
  password: eTJKAiONWap955RkxyPi3F
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ªğŸ‡¸ES_198 |30.97Mb
  server: 194.87.45.189
  type: ss
  country: ğŸ‡ªğŸ‡¸ES
  port: 443
  password: nXmm28kU7OCXtCwUziCreA
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ªğŸ‡¸ES_197 |66.26Mb
  server: 194.87.45.189
  type: ss
  country: ğŸ‡ªğŸ‡¸ES
  port: 443
  password: 9GyGpqucu0IozRSh15x0eS
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ªğŸ‡¸ES_199 |36.72Mb
  server: 194.87.45.189
  type: ss
  country: ğŸ‡ªğŸ‡¸ES
  port: 443
  password: jiMMLSYwAagbBvDq511rG3
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ªğŸ‡¸ES_200 |43.48Mb
  server: 194.87.45.189
  type: ss
  country: ğŸ‡ªğŸ‡¸ES
  port: 443
  password: 0qh20PRM41vxcoz05fgH1m
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ªğŸ‡¸ES_203 |47.97Mb
  server: 194.87.45.189
  type: ss
  country: ğŸ‡ªğŸ‡¸ES
  port: 443
  password: Nad2Br2R9zy5TAEpF0VBY3
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ªğŸ‡¸ES_202 |35.69Mb
  server: 194.87.45.189
  type: ss
  country: ğŸ‡ªğŸ‡¸ES
  port: 443
  password: i9KRMQtEgoPObgP953lr2h
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ªğŸ‡¸ES_204 |39.53Mb
  server: 194.87.45.189
  type: ss
  country: ğŸ‡ªğŸ‡¸ES
  port: 443
  password: Zc5RYQdfKMHNY0TgeIFvZ0
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ªğŸ‡¸ES_205 |31.59Mb
  server: 194.87.45.189
  type: ss
  country: ğŸ‡ªğŸ‡¸ES
  port: 443
  password: Il5SCqyrvK4naIheuaVjIz
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡«ğŸ‡·FR_215 |46.54Mb
  server: 57.129.140.88
  type: ss
  country: ğŸ‡«ğŸ‡·FR
  port: 8388
  password: k1v5g9FefdoO
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡«ğŸ‡·FR_207 |30.35Mb
  server: 83.147.216.70
  type: ss
  country: ğŸ‡«ğŸ‡·FR
  port: 64519
  password: MVAZ6nsCGVWhTzcRIUD85f
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡«ğŸ‡·FR_209 |39.97Mb
  server: 83.147.216.70
  type: ss
  country: ğŸ‡«ğŸ‡·FR
  port: 64519
  password: kmgk1sWY4Fh4dw9bxk2NBG
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ªğŸ‡¸ES_201 |43.15Mb
  server: 194.87.45.189
  type: ss
  country: ğŸ‡ªğŸ‡¸ES
  port: 443
  password: HW0EOsctbnZ0pwn0Rwnobx
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡«ğŸ‡·FR_210 |31.61Mb
  server: 83.147.216.70
  type: ss
  country: ğŸ‡«ğŸ‡·FR
  port: 64519
  password: UlT89D0rvcr05tKft1NB5a
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡«ğŸ‡·FR_214 |33.31Mb
  server: 83.147.216.70
  type: ss
  country: ğŸ‡«ğŸ‡·FR
  port: 64519
  password: RLfa7IlzmmrwyBtI4BOJs3
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡«ğŸ‡·FR_216 |37.57Mb
  server: 83.147.216.70
  type: ss
  country: ğŸ‡«ğŸ‡·FR
  port: 64519
  password: rOQrWhz7otxOrPBC6uHd3F
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_224 |24.53Mb
  server: 35.178.48.198
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡¬ğŸ‡§GB_228 |19.81Mb
  server: 35.176.103.67
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡¬ğŸ‡§GB_227 |22.21Mb
  server: 18.134.245.70
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡¬ğŸ‡§GB_232 |22.57Mb
  server: 18.134.252.219
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡¬ğŸ‡§GB_239 |25.96Mb
  server: 146.70.23.32
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: ğŸ‡¬ğŸ‡§GB_243 |31.21Mb
  server: 78.129.140.11
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: ky2yxR4bvKuQwRCp49b7pt
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_244 |27.83Mb
  server: 18.133.243.78
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡ºğŸ‡¸US_344 |12.35Mb
  server: 23.157.40.5
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 8000
  password: KixLvKzwjekG00rm
  cipher: aes-256-gcm
- name: ğŸ‡¬ğŸ‡·GR_245 |16.30Mb
  server: 192.71.166.102
  type: ss
  country: ğŸ‡¬ğŸ‡·GR
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ğŸ‡·ğŸ‡ºRU_326 |32.88Mb
  server: 95.163.176.37
  type: ss
  country: ğŸ‡·ğŸ‡ºRU
  port: 8506
  password: n4J9KuWgBBXPBoDn0SdprD
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡®ğŸ‡±IL_247 |19.72Mb
  server: 169.150.202.174
  type: ss
  country: ğŸ‡®ğŸ‡±IL
  port: 990
  password: f8f7aCzcPKbsF8p3
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_346 |28.60Mb
  server: 3.148.222.22
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡·ğŸ‡ºRU_325 |31.50Mb
  server: 185.126.239.250
  type: ss
  country: ğŸ‡·ğŸ‡ºRU
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ğŸ‡ºğŸ‡¸US_363 |11.62Mb
  server: 18.221.122.241
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡µğŸ‡¾PY_323 |12.94Mb
  server: 38.165.233.18
  type: ss
  country: ğŸ‡µğŸ‡¾PY
  port: 990
  password: f8f7aCzcPKbsF8p3
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_366 |55.79Mb
  server: 3.129.133.36
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 30000
  password: eecb62b3-456f-4c25-b072-2d10abe9c3d6
  cipher: aes-256-gcm
- name: ğŸ‡ºğŸ‡¸US_371 |29.34Mb
  server: 3.12.163.233
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡ºğŸ‡¸US_370 |22.85Mb
  server: 18.116.52.167
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡ºğŸ‡¸US_356 |38.05Mb
  server: 23.157.40.5
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 2376
  password: faBAoD54k87UJG7
  cipher: aes-256-gcm
- name: ğŸ‡ºğŸ‡¸US_373 |29.33Mb
  server: 3.129.133.36
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 30000
  password: ece40cae-fb05-41d6-ab5e-870090f25d93
  cipher: aes-256-gcm
- name: ğŸ‡ºğŸ‡¸US_374 |46.62Mb
  server: 3.129.133.36
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 30000
  password: 26f726f5-0e31-4784-ad6f-48d06a9a2806
  cipher: aes-256-gcm
- name: ğŸ‡ºğŸ‡¸US_349 |46.60Mb
  server: 167.88.61.110
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 8119
  password: cdBIDV42DCwnfIN
  cipher: aes-256-gcm
- name: ğŸ‡ºğŸ‡¸US_382 |22.02Mb
  server: 216.132.112.116
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 34958
  password: AJtV4VCLaVQUKGH4g1ADSyqvzCA0mSpN46an12ZeIKhx
  cipher: aes-256-gcm
- name: ğŸ‡ºğŸ‡¸US_368 |43.37Mb
  server: 107.151.182.197
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 8080
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: ğŸ‡ºğŸ‡¸US_378 |58.09Mb
  server: 3.129.133.36
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 30000
  password: bb2182d6-6369-4002-8159-3be2793fd0d0
  cipher: aes-256-gcm
- name: ğŸ‡ºğŸ‡¸US_365 |23.79Mb
  server: 167.88.61.110
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 8881
  password: kDWvXYZoTBcGkC4
  cipher: aes-256-gcm
- name: ğŸ‡ºğŸ‡¸US_377 |33.27Mb
  server: 18.191.254.124
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡ºğŸ‡¸US_396 |51.96Mb
  server: 3.129.133.36
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 30000
  password: 90931ca3-cc08-4dff-8da0-03b932fbddfa
  cipher: aes-256-gcm
- name: ğŸ‡ºğŸ‡¸US_397 |27.29Mb
  server: 3.147.66.58
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡¹ğŸ‡¼TW_338 |16.58Mb
  server: 154.223.20.79
  type: ss
  country: ğŸ‡¹ğŸ‡¼TW
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ğŸ‡ºğŸ‡¸US_402 |31.65Mb
  server: 3.12.120.55
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡ºğŸ‡¸US_403 |26.92Mb
  server: 3.137.165.150
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡ºğŸ‡¸US_384 |156.18Mb
  server: 23.157.40.5
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 7307
  password: FoOiGlkAA9yPEGP
  cipher: aes-256-gcm
- name: ğŸ‡ºğŸ‡¸US_392 |194.37Mb
  server: 23.157.40.5
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 5499
  password: lGqs95QkFHo2NV
  cipher: aes-256-gcm
- name: ğŸ‡ºğŸ‡¸US_404 |11.69Mb
  server: 3.139.67.190
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡ºğŸ‡¸US_405 |29.52Mb
  server: 3.148.242.11
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡ºğŸ‡¸US_375 |14.17Mb
  server: 23.157.40.101
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 7307
  password: FoOiGlkAA9yPEGP
  cipher: aes-256-gcm
- name: ğŸ‡ºğŸ‡¸US_400 |44.89Mb
  server: 23.157.40.5
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 8119
  password: cdBIDV42DCwnfIN
  cipher: aes-256-gcm
- name: ğŸ‡ºğŸ‡¸US_387 |174.06Mb
  server: 167.88.61.110
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 6679
  password: TEzjfAYq2IjtuoS
  cipher: aes-256-gcm
- name: Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_413 |19.14Mb
  server: 193.124.24.247
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 6502
  uuid: 242f22a3-29d9-4a94-d8ba-88043f2e1921
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Pool_ğŸ‡­ğŸ‡°HK_246 |422.00Mb
  server: 150.107.46.21
  type: ssr
  country: ğŸ‡­ğŸ‡°HK
  port: 8083
  password: iFqnzSscN
  cipher: aes-256-cfb
  protocol: origin
  obfs: tls1.2_ticket_auth
- name: ğŸ‡©ğŸ‡ªDE_169 |26.20Mb
  server: 81.19.141.45
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 443
  password: MrrxToZtXWAIfxUMsJlHYd
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡©ğŸ‡ªDE_171 |51.64Mb
  server: 81.19.141.45
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 443
  password: X9SxwyBkfwTyU7PpfycBIU
  cipher: chacha20-ietf-poly1305
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - _97 |29.47Mb
  - _96 |22.72Mb
  - _125 |10.48Mb
  - _116 |31.78Mb
  - _108 |39.42Mb
  - _135 |22.23Mb
  - _136 |26.25Mb
  - _99 |22.31Mb
  - ğŸ‡¨ğŸ‡¿CZ_161 |27.86Mb
  - ğŸ‡©ğŸ‡ªDE_164 |22.62Mb
  - ğŸ‡©ğŸ‡ªDE_166 |47.98Mb
  - ğŸ‡©ğŸ‡ªDE_167 |25.14Mb
  - ğŸ‡©ğŸ‡ªDE_170 |26.21Mb
  - _121 |10.79Mb
  - _113 |20.67Mb
  - ğŸ‡©ğŸ‡ªDE_176 |11.90Mb
  - _129 |18.77Mb
  - ğŸ‡©ğŸ‡ªDE_177 |19.23Mb
  - ğŸ‡©ğŸ‡ªDE_178 |28.37Mb
  - ğŸ‡©ğŸ‡ªDE_179 |27.52Mb
  - ğŸ‡©ğŸ‡ªDE_180 |17.72Mb
  - ğŸ‡©ğŸ‡ªDE_182 |46.59Mb
  - ğŸ‡©ğŸ‡ªDE_183 |40.15Mb
  - ğŸ‡©ğŸ‡ªDE_184 |24.45Mb
  - ğŸ‡©ğŸ‡ªDE_185 |38.28Mb
  - ğŸ‡©ğŸ‡ªDE_188 |24.06Mb
  - ğŸ‡©ğŸ‡ªDE_191 |17.07Mb
  - ğŸ‡©ğŸ‡ªDE_190 |12.16Mb
  - ğŸ‡©ğŸ‡ªDE_192 |17.57Mb
  - ğŸ‡ªğŸ‡¸ES_198 |30.97Mb
  - ğŸ‡ªğŸ‡¸ES_197 |66.26Mb
  - ğŸ‡ªğŸ‡¸ES_199 |36.72Mb
  - ğŸ‡ªğŸ‡¸ES_200 |43.48Mb
  - ğŸ‡ªğŸ‡¸ES_203 |47.97Mb
  - ğŸ‡ªğŸ‡¸ES_202 |35.69Mb
  - ğŸ‡ªğŸ‡¸ES_204 |39.53Mb
  - ğŸ‡ªğŸ‡¸ES_205 |31.59Mb
  - ğŸ‡«ğŸ‡·FR_215 |46.54Mb
  - ğŸ‡«ğŸ‡·FR_207 |30.35Mb
  - ğŸ‡«ğŸ‡·FR_209 |39.97Mb
  - ğŸ‡ªğŸ‡¸ES_201 |43.15Mb
  - ğŸ‡«ğŸ‡·FR_210 |31.61Mb
  - ğŸ‡«ğŸ‡·FR_214 |33.31Mb
  - ğŸ‡«ğŸ‡·FR_216 |37.57Mb
  - ğŸ‡¬ğŸ‡§GB_224 |24.53Mb
  - ğŸ‡¬ğŸ‡§GB_228 |19.81Mb
  - ğŸ‡¬ğŸ‡§GB_227 |22.21Mb
  - ğŸ‡¬ğŸ‡§GB_232 |22.57Mb
  - ğŸ‡¬ğŸ‡§GB_239 |25.96Mb
  - ğŸ‡¬ğŸ‡§GB_243 |31.21Mb
  - ğŸ‡¬ğŸ‡§GB_244 |27.83Mb
  - ğŸ‡ºğŸ‡¸US_344 |12.35Mb
  - ğŸ‡¬ğŸ‡·GR_245 |16.30Mb
  - ğŸ‡·ğŸ‡ºRU_326 |32.88Mb
  - ğŸ‡®ğŸ‡±IL_247 |19.72Mb
  - ğŸ‡ºğŸ‡¸US_346 |28.60Mb
  - ğŸ‡·ğŸ‡ºRU_325 |31.50Mb
  - ğŸ‡ºğŸ‡¸US_363 |11.62Mb
  - ğŸ‡µğŸ‡¾PY_323 |12.94Mb
  - ğŸ‡ºğŸ‡¸US_366 |55.79Mb
  - ğŸ‡ºğŸ‡¸US_371 |29.34Mb
  - ğŸ‡ºğŸ‡¸US_370 |22.85Mb
  - ğŸ‡ºğŸ‡¸US_356 |38.05Mb
  - ğŸ‡ºğŸ‡¸US_373 |29.33Mb
  - ğŸ‡ºğŸ‡¸US_374 |46.62Mb
  - ğŸ‡ºğŸ‡¸US_349 |46.60Mb
  - ğŸ‡ºğŸ‡¸US_382 |22.02Mb
  - ğŸ‡ºğŸ‡¸US_368 |43.37Mb
  - ğŸ‡ºğŸ‡¸US_378 |58.09Mb
  - ğŸ‡ºğŸ‡¸US_365 |23.79Mb
  - ğŸ‡ºğŸ‡¸US_377 |33.27Mb
  - ğŸ‡ºğŸ‡¸US_396 |51.96Mb
  - ğŸ‡ºğŸ‡¸US_397 |27.29Mb
  - ğŸ‡¹ğŸ‡¼TW_338 |16.58Mb
  - ğŸ‡ºğŸ‡¸US_402 |31.65Mb
  - ğŸ‡ºğŸ‡¸US_403 |26.92Mb
  - ğŸ‡ºğŸ‡¸US_384 |156.18Mb
  - ğŸ‡ºğŸ‡¸US_392 |194.37Mb
  - ğŸ‡ºğŸ‡¸US_404 |11.69Mb
  - ğŸ‡ºğŸ‡¸US_405 |29.52Mb
  - ğŸ‡ºğŸ‡¸US_375 |14.17Mb
  - ğŸ‡ºğŸ‡¸US_400 |44.89Mb
  - ğŸ‡ºğŸ‡¸US_387 |174.06Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_413 |19.14Mb
  - Pool_ğŸ‡­ğŸ‡°HK_246 |422.00Mb
  - ğŸ‡©ğŸ‡ªDE_169 |26.20Mb
  - ğŸ‡©ğŸ‡ªDE_171 |51.64Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - _97 |29.47Mb
  - _96 |22.72Mb
  - _125 |10.48Mb
  - _116 |31.78Mb
  - _108 |39.42Mb
  - _135 |22.23Mb
  - _136 |26.25Mb
  - _99 |22.31Mb
  - ğŸ‡¨ğŸ‡¿CZ_161 |27.86Mb
  - ğŸ‡©ğŸ‡ªDE_164 |22.62Mb
  - ğŸ‡©ğŸ‡ªDE_166 |47.98Mb
  - ğŸ‡©ğŸ‡ªDE_167 |25.14Mb
  - ğŸ‡©ğŸ‡ªDE_170 |26.21Mb
  - _121 |10.79Mb
  - _113 |20.67Mb
  - ğŸ‡©ğŸ‡ªDE_176 |11.90Mb
  - _129 |18.77Mb
  - ğŸ‡©ğŸ‡ªDE_177 |19.23Mb
  - ğŸ‡©ğŸ‡ªDE_178 |28.37Mb
  - ğŸ‡©ğŸ‡ªDE_179 |27.52Mb
  - ğŸ‡©ğŸ‡ªDE_180 |17.72Mb
  - ğŸ‡©ğŸ‡ªDE_182 |46.59Mb
  - ğŸ‡©ğŸ‡ªDE_183 |40.15Mb
  - ğŸ‡©ğŸ‡ªDE_184 |24.45Mb
  - ğŸ‡©ğŸ‡ªDE_185 |38.28Mb
  - ğŸ‡©ğŸ‡ªDE_188 |24.06Mb
  - ğŸ‡©ğŸ‡ªDE_191 |17.07Mb
  - ğŸ‡©ğŸ‡ªDE_190 |12.16Mb
  - ğŸ‡©ğŸ‡ªDE_192 |17.57Mb
  - ğŸ‡ªğŸ‡¸ES_198 |30.97Mb
  - ğŸ‡ªğŸ‡¸ES_197 |66.26Mb
  - ğŸ‡ªğŸ‡¸ES_199 |36.72Mb
  - ğŸ‡ªğŸ‡¸ES_200 |43.48Mb
  - ğŸ‡ªğŸ‡¸ES_203 |47.97Mb
  - ğŸ‡ªğŸ‡¸ES_202 |35.69Mb
  - ğŸ‡ªğŸ‡¸ES_204 |39.53Mb
  - ğŸ‡ªğŸ‡¸ES_205 |31.59Mb
  - ğŸ‡«ğŸ‡·FR_215 |46.54Mb
  - ğŸ‡«ğŸ‡·FR_207 |30.35Mb
  - ğŸ‡«ğŸ‡·FR_209 |39.97Mb
  - ğŸ‡ªğŸ‡¸ES_201 |43.15Mb
  - ğŸ‡«ğŸ‡·FR_210 |31.61Mb
  - ğŸ‡«ğŸ‡·FR_214 |33.31Mb
  - ğŸ‡«ğŸ‡·FR_216 |37.57Mb
  - ğŸ‡¬ğŸ‡§GB_224 |24.53Mb
  - ğŸ‡¬ğŸ‡§GB_228 |19.81Mb
  - ğŸ‡¬ğŸ‡§GB_227 |22.21Mb
  - ğŸ‡¬ğŸ‡§GB_232 |22.57Mb
  - ğŸ‡¬ğŸ‡§GB_239 |25.96Mb
  - ğŸ‡¬ğŸ‡§GB_243 |31.21Mb
  - ğŸ‡¬ğŸ‡§GB_244 |27.83Mb
  - ğŸ‡ºğŸ‡¸US_344 |12.35Mb
  - ğŸ‡¬ğŸ‡·GR_245 |16.30Mb
  - ğŸ‡·ğŸ‡ºRU_326 |32.88Mb
  - ğŸ‡®ğŸ‡±IL_247 |19.72Mb
  - ğŸ‡ºğŸ‡¸US_346 |28.60Mb
  - ğŸ‡·ğŸ‡ºRU_325 |31.50Mb
  - ğŸ‡ºğŸ‡¸US_363 |11.62Mb
  - ğŸ‡µğŸ‡¾PY_323 |12.94Mb
  - ğŸ‡ºğŸ‡¸US_366 |55.79Mb
  - ğŸ‡ºğŸ‡¸US_371 |29.34Mb
  - ğŸ‡ºğŸ‡¸US_370 |22.85Mb
  - ğŸ‡ºğŸ‡¸US_356 |38.05Mb
  - ğŸ‡ºğŸ‡¸US_373 |29.33Mb
  - ğŸ‡ºğŸ‡¸US_374 |46.62Mb
  - ğŸ‡ºğŸ‡¸US_349 |46.60Mb
  - ğŸ‡ºğŸ‡¸US_382 |22.02Mb
  - ğŸ‡ºğŸ‡¸US_368 |43.37Mb
  - ğŸ‡ºğŸ‡¸US_378 |58.09Mb
  - ğŸ‡ºğŸ‡¸US_365 |23.79Mb
  - ğŸ‡ºğŸ‡¸US_377 |33.27Mb
  - ğŸ‡ºğŸ‡¸US_396 |51.96Mb
  - ğŸ‡ºğŸ‡¸US_397 |27.29Mb
  - ğŸ‡¹ğŸ‡¼TW_338 |16.58Mb
  - ğŸ‡ºğŸ‡¸US_402 |31.65Mb
  - ğŸ‡ºğŸ‡¸US_403 |26.92Mb
  - ğŸ‡ºğŸ‡¸US_384 |156.18Mb
  - ğŸ‡ºğŸ‡¸US_392 |194.37Mb
  - ğŸ‡ºğŸ‡¸US_404 |11.69Mb
  - ğŸ‡ºğŸ‡¸US_405 |29.52Mb
  - ğŸ‡ºğŸ‡¸US_375 |14.17Mb
  - ğŸ‡ºğŸ‡¸US_400 |44.89Mb
  - ğŸ‡ºğŸ‡¸US_387 |174.06Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_413 |19.14Mb
  - Pool_ğŸ‡­ğŸ‡°HK_246 |422.00Mb
  - ğŸ‡©ğŸ‡ªDE_169 |26.20Mb
  - ğŸ‡©ğŸ‡ªDE_171 |51.64Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
