port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: disney_US |69.35Mb
  server: 79.127.200.162
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: netflix_US |19.46Mb
  server: 156.146.38.170
  type: ss
  port: 443
  udp: true
  password: shadowsocks
  cipher: aes-128-gcm
- name: _453 |42.44Mb
  server: 104.192.226.106
  type: ss
  port: 990
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: chacha20-ietf-poly1305
- name: _468 |184.52Mb
  server: 82.38.31.194
  type: ss
  port: 8080
  udp: true
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: _452 |260.48Mb
  server: 45.14.245.2
  type: ss
  port: 443
  password: 17ZDORWIliQHuO6WRGHChXYMzdRtAYVP
  cipher: chacha20-ietf-poly1305
- name: _474 |241.07Mb
  server: 82.38.31.179
  type: ss
  port: 8080
  udp: true
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: _476 |43.37Mb
  server: 173.244.56.6
  type: ss
  port: 443
  udp: true
  password: shadowsocks
  cipher: aes-128-gcm
- name: _473 |10.42Mb
  server: pupas-shirting-unsung.freesocks.work
  type: ss
  port: 443
  udp: true
  password: p78naCf2EfOlRSLTX0wFVx
  cipher: chacha20-ietf-poly1305
- name: _488 |14.09Mb
  server: 156.146.38.169
  type: ss
  port: 443
  udp: true
  password: shadowsocks
  cipher: aes-128-gcm
- name: _465 |15.42Mb
  server: 172.105.199.111
  type: ss
  port: 8080
  udp: true
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: disney_PY |16.97Mb
  server: 38.165.233.93
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: _489 |28.84Mb
  server: 137.184.174.93
  type: ss
  port: 8080
  udp: true
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: Relay_-ğŸ‡¸ğŸ‡ªSE_477 |16.42Mb
  server: 193.135.174.135
  type: ss
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: netflix_US |19.28Mb
  server: 156.146.38.167
  type: ss
  port: 443
  udp: true
  password: shadowsocks
  cipher: aes-128-gcm
- name: _486 |25.24Mb
  server: 185.192.124.188
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: _461 |12.37Mb
  server: 194.246.114.101
  type: ss
  port: 443
  udp: true
  password: HaNqw9pIE4jcx98sg7UQgHeGNTM4R2pk
  cipher: chacha20-ietf-poly1305
- name: _484 |38.96Mb
  server: 147.78.0.182
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _495 |75.38Mb
  server: 212.224.125.154
  type: ss
  port: 57456
  udp: true
  password: 6a85b249286a74a9
  cipher: chacha20-ietf-poly1305
- name: _475 |30.79Mb
  server: 119.59.98.58
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: disney_ES |159.19Mb
  server: 145.249.109.121
  type: ss
  port: 25512
  udp: true
  password: smSMfR9jqLgMkHuQtxSIWh
  cipher: chacha20-ietf-poly1305
- name: netflix_NL |226.19Mb
  server: 151.242.251.142
  type: ss
  port: 8080
  udp: true
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: _479 |21.74Mb
  server: 128.199.172.224
  type: ss
  port: 8080
  udp: true
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: _478 |23.67Mb
  server: 172.237.74.36
  type: ss
  port: 443
  udp: true
  password: Dk0XrU/n+SB84g0k+mX4zdy5HVVhuAUP6pCaldJxQjY=
  cipher: aes-256-gcm
- name: _497 |43.87Mb
  server: 95.164.116.33
  type: ss
  port: 443
  password: pQmnC03JObbPhdh5FBJHgD6jnTLchsRA
  cipher: chacha20-ietf-poly1305
- name: _508 |33.14Mb
  server: 185.47.254.87
  type: ss
  port: 990
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_GB |191.19Mb
  server: 141.98.101.178
  type: ss
  port: 443
  udp: true
  password: shadowsocks
  cipher: aes-128-gcm
- name: _507 |12.95Mb
  server: 192.71.249.78
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: _505 |144.89Mb
  server: 45.87.175.22
  type: ss
  port: 8080
  udp: true
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: _518 |58.73Mb
  server: 103.35.189.136
  type: ss
  port: 443
  udp: true
  password: SS2QvbC9nqLp2sXXZo0BVy4slcErRuCt
  cipher: chacha20-ietf-poly1305
- name: _492 |10.12Mb
  server: 68.183.227.4
  type: ss
  port: 8080
  udp: true
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: _504 |117.22Mb
  server: 13.61.17.80
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: _523 |13.24Mb
  server: 173.234.29.2
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _510 |49.62Mb
  server: 45.12.136.170
  type: ss
  port: 443
  udp: true
  password: l668XHPejoSNNuD66BYzyehaCpZexiF7
  cipher: chacha20-ietf-poly1305
- name: _513 |14.09Mb
  server: 89.221.225.15
  type: ss
  port: 443
  udp: true
  password: yCbQ4bry4otfifK7oel71NaXpPL9pYJb
  cipher: chacha20-ietf-poly1305
- name: _519 |132.07Mb
  server: 45.87.175.28
  type: ss
  port: 8080
  udp: true
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: _521 |15.79Mb
  server: 196.196.192.58
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _502 |43.68Mb
  server: 156.59.243.6
  type: ss
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _525 |24.01Mb
  server: 82.38.31.176
  type: ss
  port: 8080
  udp: true
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: Relay_-ğŸ‡¨ğŸ‡¦CA_533 |69.05Mb
  server: 79.127.200.169
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: netflix_NL |47.68Mb
  server: 51.15.23.166
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: _522 |175.64Mb
  server: 138.186.143.32
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: _527 |243.25Mb
  server: 82.38.31.214
  type: ss
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: _538 |43.61Mb
  server: 138.186.142.81
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: disney_BG |22.86Mb
  server: 38.60.247.151
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_GB |799.66Mb
  server: 146.70.61.37
  type: ss
  port: 8080
  udp: true
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: _514 |19.61Mb
  server: 38.89.142.56
  type: ss
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _536 |43.89Mb
  server: 138.186.143.32
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _547 |11.84Mb
  server: 45.87.175.187
  type: ss
  port: 8080
  udp: true
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: _528 |23.60Mb
  server: 149.22.87.241
  type: ss
  port: 443
  udp: true
  password: shadowsocks
  cipher: aes-128-gcm
- name: disney_MX |29.50Mb
  server: 38.165.231.25
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _516 |190.68Mb
  server: h110vpnnl.outlinekeys.net
  type: ss
  port: 52571
  udp: true
  password: b0TKxnHAYeeFYyzTAMXn0F
  cipher: chacha20-ietf-poly1305
- name: disney_DE |85.47Mb
  server: store.ubi.com
  type: vmess
  port: 443
  uuid: 5197ebcd-4381-45fa-b1d6-368551788d4b
  alterId: 0
  cipher: auto
  network: ws
  servername: fly.stari.dpdns.org
  http-opts: {}
  h2-opts: {}
  tls: true
  ws-opts:
    path: /5197ebcd-4381-45fa-b1d6-368551788d4b-vm
    headers:
      Host: fly.stari.dpdns.org
- name: Relay_ |33.15Mb
  server: luo.yixianled.com
  type: vmess
  port: 37014
  udp: true
  uuid: 6578c489-28d2-4f12-8c2f-9f2d8789626d
  alterId: 0
  cipher: auto
  network: ws
  servername: luo.yixianled.com
  http-opts: {}
  h2-opts: {}
  tls: true
  ws-opts:
    path: /happy
    headers:
      Host: luo.yixianled.com
- name: _540 |27.50Mb
  server: 119.59.98.58
  type: ss
  port: 990
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: chacha20-ietf-poly1305
- name: _591 |21.52Mb
  server: 160.16.138.24
  type: trojan
  port: 4054
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: _602 |13.16Mb
  server: 202.181.103.235
  type: trojan
  port: 4054
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: ğŸ‡§ğŸ‡·BR_641 |26.06Mb
  server: 185.192.124.188
  type: ss
  country: ğŸ‡§ğŸ‡·BR
  port: 990
  password: f8f7aCzcPKbsF8p3
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¨ğŸ‡¦CA_643 |81.44Mb
  server: 185.213.23.63
  type: ss
  country: ğŸ‡¨ğŸ‡¦CA
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: disney_CH |239.22Mb
  server: 138.124.67.26
  type: ss
  country: ğŸ‡¨ğŸ‡­CH
  port: 25572
  password: nqcIfYHlpMn3jzqkNDjKaG
  cipher: chacha20-ietf-poly1305
- name: disney_DE |92.57Mb
  server: 89.163.140.136
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: _626 |22.60Mb
  server: 202.181.103.246
  type: trojan
  port: 4054
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: disney_HK |28.42Mb
  server: 219.79.214.159
  type: trojan
  port: 443
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: Relay_-ğŸ‡­ğŸ‡°HK_562 |11.01Mb
  server: green2.cdntencentmusic.com
  type: trojan
  port: 31102
  udp: true
  password: 25a6f104-84d0-4a8b-9827-1937f8816a6e
  sni: green2.cdntencentmusic.com
  skip-cert-verify: true
- name: Relay_ğŸ‡¬ğŸ‡§GB-ğŸ‡³ğŸ‡±NL_649 |150.44Mb
  server: 82.38.31.208
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: Relay_-ğŸ‡­ğŸ‡°HK_596 |10.95Mb
  server: green2.cdntencentmusic.com
  type: trojan
  port: 31102
  udp: true
  password: a5049baa-eadf-4523-bcac-33139e4a99ea
  sni: green2.cdntencentmusic.com
  skip-cert-verify: true
- name: disney_netflix_GB |147.42Mb
  server: 141.98.101.182
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: shadowsocks
  cipher: aes-128-gcm
- name: ğŸ‡¨ğŸ‡±CL_645 |13.60Mb
  server: 154.205.153.107
  type: ss
  country: ğŸ‡¨ğŸ‡±CL
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_660 |218.07Mb
  server: 45.87.175.183
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_662 |210.43Mb
  server: 45.87.175.185
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡²ğŸ‡½MX |38.00Mb
  server: 216.238.86.158
  type: vmess
  country: ğŸ‡²ğŸ‡½MX
  port: 34460
  uuid: 90be214d-048c-4ea2-a602-b8e4d4e51e36
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡±ğŸ‡¹LT_664 |194.78Mb
  server: 45.87.175.180
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: QCXDxuDlTTMD7jtgHUjIoj
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_665 |179.43Mb
  server: 45.87.175.185
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡²ğŸ‡½MX |26.32Mb
  server: 216.238.87.47
  type: vmess
  country: ğŸ‡²ğŸ‡½MX
  port: 27502
  uuid: b8155ce4-7e08-4c40-800f-8671312b7124
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_DO |168.67Mb
  server: 45.150.52.40
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  uuid: c31777a1-2ee6-4864-db4c-a79fcbc8188b
  alterId: 0
  cipher: auto
  network: ws
  servername: xsj011-3.facai2024.com
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /c31777a1
    headers:
      HOST: xsj011-3.facai2024.com
- name: ğŸ‡±ğŸ‡» LV_668 |17.06Mb
  server: 46.183.217.204
  type: ss
  country: ğŸ‡±ğŸ‡» LV
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡³ğŸ‡±NL_672 |12.97Mb
  server: 193.29.139.141
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 8080
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸZZ |26.66Mb
  server: 104.18.14.55
  type: vmess
  country: ğŸZZ
  port: 2052
  uuid: e6447786-8c85-443c-8017-7feaa673ff45
  alterId: 0
  cipher: auto
  network: ws
  servername: in4.123417.xyz
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
  ws-opts:
    path: /
    headers:
      HOST: in4.123417.xyz
- name: Relay_ğŸ‡ºğŸ‡¸US |38.53Mb
  server: 38.14.99.163
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 59807
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: auto
  network: tcp
  servername: 38.14.99.163
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡³ğŸ‡±NL_674 |220.09Mb
  server: 194.87.216.218
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 52571
  password: b0TKxnHAYeeFYyzTAMXn0F
  cipher: chacha20-ietf-poly1305
- name: disney_HK |17.94Mb
  server: 45.207.157.29
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 13852
  uuid: 845764df-ecb3-4b13-bed2-bf1551b68e9a
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡µğŸ‡¹PT_680 |57.64Mb
  server: 185.113.143.186
  type: ss
  country: ğŸ‡µğŸ‡¹PT
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸZZ |29.45Mb
  server: hgtrojan.zabc.net
  type: vmess
  country: ğŸZZ
  port: 2083
  uuid: e6395c20-4571-4b34-d6b1-55a5d36e49ea
  alterId: 0
  cipher: auto
  network: ws
  servername: hgtrojan.zabc.net
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /e6395c20
    headers:
      HOST: hgtrojan.zabc.net
- name: Relay_ğŸ‡ºğŸ‡¸US |11.73Mb
  server: 46.3.47.250
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 20004
  uuid: e5ce425e-0b84-435c-aee5-9f9ecbe2cb16
  alterId: 0
  cipher: auto
  network: tcp
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_ğŸ‡ºğŸ‡¸US |15.55Mb
  server: 46.3.47.250
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 20002
  uuid: e5ce425e-0b84-435c-aee5-9f9ecbe2cb16
  alterId: 0
  cipher: auto
  network: tcp
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ ZZ_687 |77.98Mb
  server: 185.231.233.112
  type: ss
  country: ğŸ ZZ
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: _491 |20.90Mb
  server: 194.59.183.134
  type: ss
  port: 46114
  udp: true
  password: lejSRyqa033OEPmEQsvRsl
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸZZ-ğŸ‡®ğŸ‡·IR_688 |29.12Mb
  server: cf.fovi.tk
  type: vmess
  country: ğŸZZ
  port: 443
  uuid: bf67437e-6c90-45ca-abc2-c7240a5ce2aa
  alterId: 0
  cipher: auto
  network: ws
  servername: foxlux.fovi.tk
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /eisasqa
    headers:
      HOST: foxlux.fovi.tk
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - disney_US |69.35Mb
  - netflix_US |19.46Mb
  - _453 |42.44Mb
  - _468 |184.52Mb
  - _452 |260.48Mb
  - _474 |241.07Mb
  - _476 |43.37Mb
  - _473 |10.42Mb
  - _488 |14.09Mb
  - _465 |15.42Mb
  - disney_PY |16.97Mb
  - _489 |28.84Mb
  - Relay_-ğŸ‡¸ğŸ‡ªSE_477 |16.42Mb
  - netflix_US |19.28Mb
  - _486 |25.24Mb
  - _461 |12.37Mb
  - _484 |38.96Mb
  - _495 |75.38Mb
  - _475 |30.79Mb
  - disney_ES |159.19Mb
  - netflix_NL |226.19Mb
  - _479 |21.74Mb
  - _478 |23.67Mb
  - _497 |43.87Mb
  - _508 |33.14Mb
  - disney_netflix_GB |191.19Mb
  - _507 |12.95Mb
  - _505 |144.89Mb
  - _518 |58.73Mb
  - _492 |10.12Mb
  - _504 |117.22Mb
  - _523 |13.24Mb
  - _510 |49.62Mb
  - _513 |14.09Mb
  - _519 |132.07Mb
  - _521 |15.79Mb
  - _502 |43.68Mb
  - _525 |24.01Mb
  - Relay_-ğŸ‡¨ğŸ‡¦CA_533 |69.05Mb
  - netflix_NL |47.68Mb
  - _522 |175.64Mb
  - _527 |243.25Mb
  - _538 |43.61Mb
  - disney_BG |22.86Mb
  - disney_netflix_GB |799.66Mb
  - _514 |19.61Mb
  - _536 |43.89Mb
  - _547 |11.84Mb
  - _528 |23.60Mb
  - disney_MX |29.50Mb
  - _516 |190.68Mb
  - disney_DE |85.47Mb
  - Relay_ |33.15Mb
  - _540 |27.50Mb
  - _591 |21.52Mb
  - _602 |13.16Mb
  - ğŸ‡§ğŸ‡·BR_641 |26.06Mb
  - ğŸ‡¨ğŸ‡¦CA_643 |81.44Mb
  - disney_CH |239.22Mb
  - disney_DE |92.57Mb
  - _626 |22.60Mb
  - disney_HK |28.42Mb
  - Relay_-ğŸ‡­ğŸ‡°HK_562 |11.01Mb
  - Relay_ğŸ‡¬ğŸ‡§GB-ğŸ‡³ğŸ‡±NL_649 |150.44Mb
  - Relay_-ğŸ‡­ğŸ‡°HK_596 |10.95Mb
  - disney_netflix_GB |147.42Mb
  - ğŸ‡¨ğŸ‡±CL_645 |13.60Mb
  - ğŸ‡±ğŸ‡¹LT_660 |218.07Mb
  - ğŸ‡±ğŸ‡¹LT_662 |210.43Mb
  - ğŸ‡²ğŸ‡½MX |38.00Mb
  - ğŸ‡±ğŸ‡¹LT_664 |194.78Mb
  - ğŸ‡±ğŸ‡¹LT_665 |179.43Mb
  - ğŸ‡²ğŸ‡½MX |26.32Mb
  - disney_DO |168.67Mb
  - ğŸ‡±ğŸ‡» LV_668 |17.06Mb
  - ğŸ‡³ğŸ‡±NL_672 |12.97Mb
  - Relay_ğŸZZ |26.66Mb
  - Relay_ğŸ‡ºğŸ‡¸US |38.53Mb
  - ğŸ‡³ğŸ‡±NL_674 |220.09Mb
  - disney_HK |17.94Mb
  - ğŸ‡µğŸ‡¹PT_680 |57.64Mb
  - ğŸZZ |29.45Mb
  - Relay_ğŸ‡ºğŸ‡¸US |11.73Mb
  - Relay_ğŸ‡ºğŸ‡¸US |15.55Mb
  - ğŸ ZZ_687 |77.98Mb
  - _491 |20.90Mb
  - Relay_ğŸZZ-ğŸ‡®ğŸ‡·IR_688 |29.12Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - disney_US |69.35Mb
  - netflix_US |19.46Mb
  - _453 |42.44Mb
  - _468 |184.52Mb
  - _452 |260.48Mb
  - _474 |241.07Mb
  - _476 |43.37Mb
  - _473 |10.42Mb
  - _488 |14.09Mb
  - _465 |15.42Mb
  - disney_PY |16.97Mb
  - _489 |28.84Mb
  - Relay_-ğŸ‡¸ğŸ‡ªSE_477 |16.42Mb
  - netflix_US |19.28Mb
  - _486 |25.24Mb
  - _461 |12.37Mb
  - _484 |38.96Mb
  - _495 |75.38Mb
  - _475 |30.79Mb
  - disney_ES |159.19Mb
  - netflix_NL |226.19Mb
  - _479 |21.74Mb
  - _478 |23.67Mb
  - _497 |43.87Mb
  - _508 |33.14Mb
  - disney_netflix_GB |191.19Mb
  - _507 |12.95Mb
  - _505 |144.89Mb
  - _518 |58.73Mb
  - _492 |10.12Mb
  - _504 |117.22Mb
  - _523 |13.24Mb
  - _510 |49.62Mb
  - _513 |14.09Mb
  - _519 |132.07Mb
  - _521 |15.79Mb
  - _502 |43.68Mb
  - _525 |24.01Mb
  - Relay_-ğŸ‡¨ğŸ‡¦CA_533 |69.05Mb
  - netflix_NL |47.68Mb
  - _522 |175.64Mb
  - _527 |243.25Mb
  - _538 |43.61Mb
  - disney_BG |22.86Mb
  - disney_netflix_GB |799.66Mb
  - _514 |19.61Mb
  - _536 |43.89Mb
  - _547 |11.84Mb
  - _528 |23.60Mb
  - disney_MX |29.50Mb
  - _516 |190.68Mb
  - disney_DE |85.47Mb
  - Relay_ |33.15Mb
  - _540 |27.50Mb
  - _591 |21.52Mb
  - _602 |13.16Mb
  - ğŸ‡§ğŸ‡·BR_641 |26.06Mb
  - ğŸ‡¨ğŸ‡¦CA_643 |81.44Mb
  - disney_CH |239.22Mb
  - disney_DE |92.57Mb
  - _626 |22.60Mb
  - disney_HK |28.42Mb
  - Relay_-ğŸ‡­ğŸ‡°HK_562 |11.01Mb
  - Relay_ğŸ‡¬ğŸ‡§GB-ğŸ‡³ğŸ‡±NL_649 |150.44Mb
  - Relay_-ğŸ‡­ğŸ‡°HK_596 |10.95Mb
  - disney_netflix_GB |147.42Mb
  - ğŸ‡¨ğŸ‡±CL_645 |13.60Mb
  - ğŸ‡±ğŸ‡¹LT_660 |218.07Mb
  - ğŸ‡±ğŸ‡¹LT_662 |210.43Mb
  - ğŸ‡²ğŸ‡½MX |38.00Mb
  - ğŸ‡±ğŸ‡¹LT_664 |194.78Mb
  - ğŸ‡±ğŸ‡¹LT_665 |179.43Mb
  - ğŸ‡²ğŸ‡½MX |26.32Mb
  - disney_DO |168.67Mb
  - ğŸ‡±ğŸ‡» LV_668 |17.06Mb
  - ğŸ‡³ğŸ‡±NL_672 |12.97Mb
  - Relay_ğŸZZ |26.66Mb
  - Relay_ğŸ‡ºğŸ‡¸US |38.53Mb
  - ğŸ‡³ğŸ‡±NL_674 |220.09Mb
  - disney_HK |17.94Mb
  - ğŸ‡µğŸ‡¹PT_680 |57.64Mb
  - ğŸZZ |29.45Mb
  - Relay_ğŸ‡ºğŸ‡¸US |11.73Mb
  - Relay_ğŸ‡ºğŸ‡¸US |15.55Mb
  - ğŸ ZZ_687 |77.98Mb
  - _491 |20.90Mb
  - Relay_ğŸZZ-ğŸ‡®ğŸ‡·IR_688 |29.12Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
