port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: _200 |31.20Mb
  server: 23.95.72.81
  type: ss
  port: 443
  udp: true
  password: UAMVtHm54uahd6SiN5WcD16rsPSdabPG
  cipher: chacha20-ietf-poly1305
- name: netflix_IE |186.39Mb
  server: 18.203.224.78
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: _207 |26.63Mb
  server: 137.184.174.93
  type: ss
  port: 8080
  udp: true
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: disney_netflix_NL |57.47Mb
  server: 82.38.31.176
  type: ss
  port: 8080
  udp: true
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: _192 |118.38Mb
  server: 54.93.101.215
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: disney_netflix_DE |50.71Mb
  server: 63.178.2.18
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: disney_netflix_DE |56.17Mb
  server: 3.72.36.217
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: _191 |57.41Mb
  server: 185.156.110.92
  type: ss
  port: 443
  udp: true
  password: gXOXk2FJwsz9P6nXIICuDNOqF9gWX1dn
  cipher: chacha20-ietf-poly1305
- name: disney_MD |11.34Mb
  server: 185.153.197.5
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: Relay_-ğŸ‡¸ğŸ‡¬SG_225 |14.21Mb
  server: 104.18.1.196
  type: trojan
  port: 443
  udp: true
  password: a9570330-769d-11ef-90dc-1577c1651679
  sni: sg-trojan.andfree.my.id
  skip-cert-verify: true
  ws-opts:
    path: /welcome
    headers:
      Host: sg-trojan.andfree.my.id
  network: ws
- name: _194 |10.05Mb
  server: 213.159.66.206
  type: ss
  port: 443
  udp: true
  password: pl2XtR0pzwknQOGwewbwXtPYDw1zn9Vu
  cipher: chacha20-ietf-poly1305
- name: Relay_-ğŸ‡¯ğŸ‡µJP_226 |24.74Mb
  server: 141.193.213.60
  type: trojan
  port: 443
  udp: true
  password: 8b45d379-702f-41b3-a6b2-9c87a01dcd5c
  sni: a3t5vfl95f4d5d9y.catimecsgo.xyz
  skip-cert-verify: true
  ws-opts:
    path: /images
    headers:
      Host: a3t5vfl95f4d5d9y.catimecsgo.xyz
  network: ws
- name: Relay_-ğŸ‡ºğŸ‡¸US_209 |13.71Mb
  server: 38.14.99.163
  type: vmess
  port: 59807
  udp: true
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 64
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_-ğŸ‡ºğŸ‡¸US_213 |14.47Mb
  server: 38.14.99.179
  type: vmess
  port: 59807
  udp: true
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 64
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_US |46.03Mb
  server: usiys.southbyte.xyz
  type: trojan
  port: 5897
  udp: true
  password: fg20mtCFHy
  sni: usiys.southbyte.xyz
  skip-cert-verify: true
- name: _211 |10.40Mb
  server: 45.136.244.201
  type: vmess
  port: 49934
  uuid: 90afa47d-341a-497d-ae25-1d81258804d5
  alterId: 0
  cipher: auto
  network: tcp
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_-ğŸ‡³ğŸ‡±NL_218 |11.28Mb
  server: 160.16.70.180
  type: trojan
  port: 4054
  password: 2cf6d686799e6fa95316394064f26c0a
  sni: www.nintendogames.net
- name: disney_netflix_DE |202.00Mb
  server: uk2-2.998998.best
  type: vmess
  port: 443
  udp: true
  uuid: 24254866-770c-41b4-9404-3f50524f425b
  alterId: 0
  cipher: auto
  network: ws
  servername: 24254866-770c-41b4-9404-3f50524f425b.placeunaorder.fun
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /logcatxiouerd34try9
    headers:
      Host: 24254866-770c-41b4-9404-3f50524f425b.placeunaorder.fun
- name: Relay_-ğŸ‡³ğŸ‡±NL_223 |56.01Mb
  server: 160.16.240.91
  type: trojan
  port: 4054
  password: 2cf6d686799e6fa95316394064f26c0a
  sni: www.nintendogames.net
- name: ğŸ‡§ğŸ‡·BR_248 |21.27Mb
  server: 38.180.16.86
  type: vmess
  country: ğŸ‡§ğŸ‡·BR
  port: 36236
  uuid: a58bc1a5-8c18-49ff-9453-c331b52f45dc
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡§ğŸ‡·BR_249 |24.04Mb
  server: 38.180.16.86
  type: vmess
  country: ğŸ‡§ğŸ‡·BR
  port: 36104
  uuid: E146A8CB-9D2F-449C-ADCA-8736FB
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_DE |171.14Mb
  server: 18.184.12.56
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: disney_netflix_DE |247.60Mb
  server: 54.93.211.165
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡ªğŸ‡¸ES_253 |201.03Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 27092
  uuid: a0596ba6-72a3-4366-8992-77088da65bd8
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: _245 |107.46Mb
  server: 47.242.225.242
  type: trojan
  port: 443
  udp: true
  password: 92690597d6298061459918a371e8d77d
  sni: hezijiasuqi.com
  skip-cert-verify: true
- name: disney_netflix_NL |244.75Mb
  server: 82.38.31.217
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_US |63.24Mb
  server: 107.23.148.46
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: disney_netflix_NL |244.94Mb
  server: 82.38.31.210
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_NL |182.42Mb
  server: 82.38.31.191
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_US |35.06Mb
  server: a3fyst.zeeoomboom.de
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  uuid: 03fcc618-b93d-6796-6aed-8a38c975d581
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /video/d4kapx2v.m3u8
- name: ğŸZZ_277 |198.65Mb
  server: 5k2dc9.keeoomboom.de
  type: vmess
  country: ğŸZZ
  port: 443
  uuid: 03fcc618-b93d-6796-6aed-8a38c975d581
  alterId: 0
  cipher: auto
  network: ws
  servername: 5k2dc9.keeoomboom.de
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /
    headers:
      HOST: 5k2dc9.keeoomboom.de
- name: ğŸ‡²ğŸ‡½MX_268 |248.33Mb
  server: 216.238.89.53
  type: vmess
  country: ğŸ‡²ğŸ‡½MX
  port: 57283
  uuid: 1a5aafc0-6482-451d-fe76-6875b7818579
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡±ğŸ‡¹LT_267 |10.47Mb
  server: 45.87.175.166
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 443
  password: 1RWwXhwfAB5gAEozU4G2Pg
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_US |38.46Mb
  server: 216.167.107.61
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 44805
  uuid: f7d62526-9e06-455e-82bd-241d368002e8
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_TR |13.00Mb
  server: 185.39.204.189
  type: ss
  country: ğŸ‡·ğŸ‡ºRU
  port: 34085
  password: depjSbjv2Uql6W4Vge7sDf
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸ‡©ğŸ‡ªDE-ğŸ‡©ğŸ‡ªDE_252 |75.45Mb
  server: node4.rtxconfigz.com
  type: vmess
  country: ğŸ‡©ğŸ‡ªDE
  port: 443
  uuid: 44e57485-eccc-46ef-808f-cd17ac810018
  alterId: 0
  cipher: auto
  network: ws
  servername: node4.rtxconfigz.com
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /@Malinda6104
    headers:
      HOST: node4.rtxconfigz.com
- name: ğŸ‡°ğŸ‡·KR |10.10Mb
  server: 146.56.112.110
  type: vmess
  country: ğŸ‡°ğŸ‡·KR
  port: 8888
  uuid: e7c302f3-90d6-42dd-9d7d-94a3683a3707
  alterId: 0
  cipher: auto
  network: tcp
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_ğŸ‡ºğŸ‡¸US |11.73Mb
  server: cf.fovi.tk
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  uuid: bf67437e-6c90-45ca-abc2-c7240a5ce2aa
  alterId: 0
  cipher: auto
  network: ws
  servername: foxlux.fovi.tk
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /eisasqa
    headers:
      HOST: foxlux.fovi.tk
- name: Relay_ğŸ‡¯ğŸ‡µJP |12.08Mb
  server: n1744454501.4u9ma.icu
  type: vmess
  country: ğŸ‡¯ğŸ‡µJP
  port: 443
  uuid: bed7b743-6bf8-46a2-b346-c60e60919220
  alterId: 0
  cipher: auto
  network: ws
  servername: n1744454501.4u9ma.icu
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /
    headers:
      HOST: n1744454501.4u9ma.icu
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - _200 |31.20Mb
  - netflix_IE |186.39Mb
  - _207 |26.63Mb
  - disney_netflix_NL |57.47Mb
  - _192 |118.38Mb
  - disney_netflix_DE |50.71Mb
  - disney_netflix_DE |56.17Mb
  - _191 |57.41Mb
  - disney_MD |11.34Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_225 |14.21Mb
  - _194 |10.05Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_226 |24.74Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_209 |13.71Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_213 |14.47Mb
  - disney_netflix_US |46.03Mb
  - _211 |10.40Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_218 |11.28Mb
  - disney_netflix_DE |202.00Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_223 |56.01Mb
  - ğŸ‡§ğŸ‡·BR_248 |21.27Mb
  - ğŸ‡§ğŸ‡·BR_249 |24.04Mb
  - disney_netflix_DE |171.14Mb
  - disney_netflix_DE |247.60Mb
  - ğŸ‡ªğŸ‡¸ES_253 |201.03Mb
  - _245 |107.46Mb
  - disney_netflix_NL |244.75Mb
  - disney_netflix_US |63.24Mb
  - disney_netflix_NL |244.94Mb
  - disney_netflix_NL |182.42Mb
  - disney_netflix_US |35.06Mb
  - ğŸZZ_277 |198.65Mb
  - ğŸ‡²ğŸ‡½MX_268 |248.33Mb
  - ğŸ‡±ğŸ‡¹LT_267 |10.47Mb
  - disney_netflix_US |38.46Mb
  - disney_TR |13.00Mb
  - Relay_ğŸ‡©ğŸ‡ªDE-ğŸ‡©ğŸ‡ªDE_252 |75.45Mb
  - ğŸ‡°ğŸ‡·KR |10.10Mb
  - Relay_ğŸ‡ºğŸ‡¸US |11.73Mb
  - Relay_ğŸ‡¯ğŸ‡µJP |12.08Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - _200 |31.20Mb
  - netflix_IE |186.39Mb
  - _207 |26.63Mb
  - disney_netflix_NL |57.47Mb
  - _192 |118.38Mb
  - disney_netflix_DE |50.71Mb
  - disney_netflix_DE |56.17Mb
  - _191 |57.41Mb
  - disney_MD |11.34Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_225 |14.21Mb
  - _194 |10.05Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_226 |24.74Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_209 |13.71Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_213 |14.47Mb
  - disney_netflix_US |46.03Mb
  - _211 |10.40Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_218 |11.28Mb
  - disney_netflix_DE |202.00Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_223 |56.01Mb
  - ğŸ‡§ğŸ‡·BR_248 |21.27Mb
  - ğŸ‡§ğŸ‡·BR_249 |24.04Mb
  - disney_netflix_DE |171.14Mb
  - disney_netflix_DE |247.60Mb
  - ğŸ‡ªğŸ‡¸ES_253 |201.03Mb
  - _245 |107.46Mb
  - disney_netflix_NL |244.75Mb
  - disney_netflix_US |63.24Mb
  - disney_netflix_NL |244.94Mb
  - disney_netflix_NL |182.42Mb
  - disney_netflix_US |35.06Mb
  - ğŸZZ_277 |198.65Mb
  - ğŸ‡²ğŸ‡½MX_268 |248.33Mb
  - ğŸ‡±ğŸ‡¹LT_267 |10.47Mb
  - disney_netflix_US |38.46Mb
  - disney_TR |13.00Mb
  - Relay_ğŸ‡©ğŸ‡ªDE-ğŸ‡©ğŸ‡ªDE_252 |75.45Mb
  - ğŸ‡°ğŸ‡·KR |10.10Mb
  - Relay_ğŸ‡ºğŸ‡¸US |11.73Mb
  - Relay_ğŸ‡¯ğŸ‡µJP |12.08Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
