port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: ' |48.95Mb'
  server: 98.89.32.62
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: ' |65.73Mb'
  server: 50.19.46.248
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: ' |67.09Mb'
  server: 13.218.107.141
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: ' |63.29Mb'
  server: 13.222.155.147
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: ' |67.49Mb'
  server: 23.22.182.151
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: disney_netflix_US |66.21Mb
  server: 54.159.62.233
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: disney_netflix_US |65.68Mb
  server: 184.72.124.41
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: ' |59.42Mb'
  server: 54.91.94.165
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: ' |65.67Mb'
  server: 54.227.38.247
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: disney_netflix_US |65.70Mb
  server: 3.93.196.82
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: ' |62.63Mb'
  server: 98.81.59.20
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: netflix_IE |96.54Mb
  server: 3.250.105.240
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: netflix_IE |181.19Mb
  server: 34.251.86.159
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: netflix_IE |92.37Mb
  server: 54.246.35.116
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: ' |97.64Mb'
  server: 45.14.245.2
  type: ss
  port: 443
  password: 17ZDORWIliQHuO6WRGHChXYMzdRtAYVP
  cipher: chacha20-ietf-poly1305
- name: ' |134.97Mb'
  server: 13.61.180.46
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: ' |139.44Mb'
  server: 13.61.13.231
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: ' |104.41Mb'
  server: 51.20.125.235
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: disney_PT |244.42Mb
  server: 185.231.233.112
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ' |41.30Mb'
  server: 163.192.49.195
  type: vmess
  port: 443
  uuid: bcb7c581-3c95-4569-a4e7-918141e91ea3
  alterId: 0
  cipher: auto
  network: http
  http-opts:
    path:
    - /
    headers:
      Host:
      - a.189.cn
  h2-opts: {}
- name: ' |13.82Mb'
  server: 216.238.86.158
  type: vmess
  port: 34460
  udp: true
  uuid: 90be214d-048c-4ea2-a602-b8e4d4e51e36
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: disney_US |35.68Mb
  server: 192.204.47.79
  type: vmess
  port: 42277
  udp: true
  uuid: aee61b21-e85a-484b-f203-b245f1451cff
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: ' |18.74Mb'
  server: 43.165.7.71
  type: vmess
  port: 19751
  uuid: 6cfa6103-5d06-40cb-f452-b563db578288
  alterId: 0
  cipher: auto
  network: http
  http-opts:
    method: GET
    path:
    - /
  h2-opts: {}
- name: disney_US |42.77Mb
  server: 165.140.216.141
  type: vmess
  port: 443
  uuid: e7d72a8d-26f2-4b54-b366-0c43e0bcba7d
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: ' |10.69Mb'
  server: 15.235.41.200
  type: vmess
  port: 80
  uuid: 58fe1542-5290-40ad-815a-77707a81afe5
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /IOebhLMhl1CTbFHbL95myfRX2
- name: _208 |10.20Mb
  server: 103.36.91.32
  type: ss
  port: 8388
  udp: true
  password: asd123456
  cipher: chacha20-ietf
- name: ' |23.54Mb'
  server: 160.119.196.92
  type: vmess
  port: 36334
  uuid: 575ac7a3-0127-4420-a9ea-5ff3f6c02ac7
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
- name: ' |23.11Mb'
  server: 8.218.105.196
  type: vmess
  port: 52752
  uuid: 925bdbf5-72be-4437-bebf-441c61089f6b
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: disney_SG |15.50Mb
  server: 165.154.195.38
  type: vmess
  port: 35034
  uuid: 959a8caf-4cea-43d0-a548-3628e7ddfafc
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: ' |10.92Mb'
  server: 8.210.184.105
  type: vmess
  port: 40374
  udp: true
  uuid: 36b76373-7a4f-4669-9113-7d247bcf2704
  alterId: 0
  cipher: auto
  network: http
  http-opts:
    method: GET
    path:
    - /
  h2-opts: {}
- name: ' |29.56Mb'
  server: 51.79.102.253
  type: vmess
  port: 80
  uuid: 58fe1542-5290-40ad-815a-77707a81afe5
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /IOebhLMhl1CTbFHbL95myfRX2
    headers:
      Host: wrmelmwxlf.gktevlrqznwqqozy.fabpfs66gizmnojhcvqxwl.kytrcfzqla87gvgvs6c7kjnrubuh.cc
- name: disney_TW |23.44Mb
  server: 103.127.218.91
  type: vmess
  port: 54693
  uuid: 1cef03ad-6343-408c-8121-cbd1fda2ee9d
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /1cef03ad
- name: _248 |11.28Mb
  server: 146.56.112.110
  type: vmess
  port: 8888
  uuid: e7c302f3-90d6-42dd-9d7d-94a3683a3707
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: ' |20.77Mb'
  server: 89.31.120.192
  type: vmess
  port: 443
  uuid: 44537595-9ccc-4b83-8936-5f9ad3229019
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _274 |16.19Mb
  server: 160.16.196.59
  type: trojan
  port: 2890
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: _257 |79.85Mb
  server: 47.242.140.52
  type: vmess
  port: 34815
  uuid: 1a46b66c-6ba9-4e9c-aa0b-0ebac2b69e32
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /arki
- name: Relay_ |11.88Mb
  server: 160.16.70.180
  type: trojan
  port: 1331
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: Relay_ |11.41Mb
  server: 160.16.153.13
  type: trojan
  port: 3145
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: Relay_-üá≠üá∞HK_247 |60.78Mb
  server: v10.hdacd.com
  type: vmess
  port: 30807
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: ' |22.08Mb'
  server: 8.218.116.26
  type: vmess
  port: 32228
  uuid: e4767e9f-ed00-4f31-a984-a918bdd9b09c
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _277 |49.27Mb
  server: 202.181.103.235
  type: trojan
  port: 2890
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: _278 |13.72Mb
  server: 160.16.214.6
  type: trojan
  port: 2890
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: _279 |19.96Mb
  server: 160.16.117.182
  type: trojan
  port: 3093
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: ' |25.18Mb'
  server: 154.201.76.172
  type: vmess
  port: 20990
  uuid: ba50e1fe-055f-4587-fd0d-36c8d6615192
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: Relay_ |14.36Mb
  server: 153.121.73.102
  type: trojan
  port: 1331
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: ' |40.55Mb'
  server: 160.16.223.205
  type: trojan
  port: 4054
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: _281 |24.93Mb
  server: 160.16.124.55
  type: trojan
  port: 2890
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: disney_netflix_GB |232.39Mb
  server: 172.67.134.185
  type: trojan
  port: 443
  udp: true
  password: POORIARED
  sni: reDfRee8.REDFree8.ir
  ws-opts:
    path: /eyJqdW5rIjoiVUl6eXhLZkkwUTJ3ZzkiLCJwcm90b2NvbCI6InRyIiwibW9kZSI6InByb3h5aXAiLCJwYW5lbElQcyI6W119?ed=2560
    headers:
      Host: reDfRee8.REDFree8.ir
  network: ws
- name: _285 |16.29Mb
  server: 160.16.229.223
  type: trojan
  port: 3093
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: _289 |13.00Mb
  server: 153.121.51.29
  type: trojan
  port: 2890
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: disney_HK |19.79Mb
  server: 58.152.25.242
  type: trojan
  port: 443
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: disney_FR |154.75Mb
  server: 208.76.223.218
  type: vmess
  country: üá™üá∏ES
  port: 27092
  uuid: a0596ba6-72a3-4366-8992-77088da65bd8
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_HK |19.45Mb
  server: 58.152.25.20
  type: trojan
  port: 443
  udp: true
  password: BxceQaOe
  skip-cert-verify: true
- name: ' |10.67Mb'
  server: 153.121.53.187
  type: trojan
  port: 3093
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: disney_SE |167.74Mb
  server: 70.34.218.149
  type: trojan
  port: 11930
  password: BaeSzHdfJIR13l67
  sni: softpillow.silentrocket.click
- name: disney_FR |148.22Mb
  server: 208.76.223.218
  type: vmess
  country: üá™üá∏ES
  port: 40433
  uuid: d8fd8955-78db-49ba-d86f-3e4729f6ac4d
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ' |20.36Mb'
  server: 153.121.65.107
  type: trojan
  port: 3093
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: ' |42.40Mb'
  server: 216.238.87.47
  type: vmess
  country: üá≤üáΩMX
  port: 27502
  uuid: b8155ce4-7e08-4c40-800f-8671312b7124
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ' |67.36Mb'
  server: 18.207.122.59
  type: ss
  country: üá∫üá∏US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: disney_HK |15.95Mb
  server: 58.152.30.120
  type: trojan
  port: 443
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: ' |166.38Mb'
  server: 82.38.31.217
  type: ss
  country: üá¨üáßGB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ' |172.58Mb'
  server: 52.50.200.2
  type: ss
  country: üáÆüá™IE
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ' |179.24Mb'
  server: 82.38.31.194
  type: ss
  country: üá¨üáßGB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ' |234.83Mb'
  server: 82.38.31.191
  type: ss
  country: üá¨üáßGB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: disney_KZ |17.50Mb
  server: 31.3.209.183
  type: ss
  country: üá¨üáßGB
  port: 28212
  password: Kmn7dHPw5wNfkqQMPcGWQA
  cipher: chacha20-ietf-poly1305
- name: ' |71.56Mb'
  server: 45.12.136.170
  type: ss
  country: üá∫üá∏US
  port: 443
  password: l668XHPejoSNNuD66BYzyehaCpZexiF7
  cipher: chacha20-ietf-poly1305
- name: Relay_ |204.67Mb
  server: cpanel.navar1.ir
  type: vmess
  country: üá©üá™DE
  port: 100
  uuid: 95c6f6f0-84f7-4443-8a50-a59f8e66f5ee
  alterId: 0
  cipher: auto
  network: tcp
  servername: cpanel.navar1.ir
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_HK |23.37Mb
  server: 45.207.157.29
  type: vmess
  country: üá≠üá∞HK
  port: 13852
  uuid: 845764df-ecb3-4b13-bed2-bf1551b68e9a
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_US |21.88Mb
  server: cf.fovi.tk
  type: vmess
  country: üèÅZZ
  port: 443
  uuid: bf67437e-6c90-45ca-abc2-c7240a5ce2aa
  alterId: 0
  cipher: auto
  network: ws
  servername: foxpol.fovi.tk
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /eisasqa
    headers:
      HOST: foxpol.fovi.tk
proxy-groups:
- name: üöÄ ËäÇÁÇπÈÄâÊã©
  type: select
  proxies:
  - ‚ôªÔ∏è Ëá™Âä®ÈÄâÊã©
  - ' |48.95Mb'
  - ' |65.73Mb'
  - ' |67.09Mb'
  - ' |63.29Mb'
  - ' |67.49Mb'
  - disney_netflix_US |66.21Mb
  - disney_netflix_US |65.68Mb
  - ' |59.42Mb'
  - ' |65.67Mb'
  - disney_netflix_US |65.70Mb
  - ' |62.63Mb'
  - netflix_IE |96.54Mb
  - netflix_IE |181.19Mb
  - netflix_IE |92.37Mb
  - ' |97.64Mb'
  - ' |134.97Mb'
  - ' |139.44Mb'
  - ' |104.41Mb'
  - disney_PT |244.42Mb
  - ' |41.30Mb'
  - ' |13.82Mb'
  - disney_US |35.68Mb
  - ' |18.74Mb'
  - disney_US |42.77Mb
  - ' |10.69Mb'
  - _208 |10.20Mb
  - ' |23.54Mb'
  - ' |23.11Mb'
  - disney_SG |15.50Mb
  - ' |10.92Mb'
  - ' |29.56Mb'
  - disney_TW |23.44Mb
  - _248 |11.28Mb
  - ' |20.77Mb'
  - _274 |16.19Mb
  - _257 |79.85Mb
  - Relay_ |11.88Mb
  - Relay_ |11.41Mb
  - Relay_-üá≠üá∞HK_247 |60.78Mb
  - ' |22.08Mb'
  - _277 |49.27Mb
  - _278 |13.72Mb
  - _279 |19.96Mb
  - ' |25.18Mb'
  - Relay_ |14.36Mb
  - ' |40.55Mb'
  - _281 |24.93Mb
  - disney_netflix_GB |232.39Mb
  - _285 |16.29Mb
  - _289 |13.00Mb
  - disney_HK |19.79Mb
  - disney_FR |154.75Mb
  - disney_HK |19.45Mb
  - ' |10.67Mb'
  - disney_SE |167.74Mb
  - disney_FR |148.22Mb
  - ' |20.36Mb'
  - ' |42.40Mb'
  - ' |67.36Mb'
  - disney_HK |15.95Mb
  - ' |166.38Mb'
  - ' |172.58Mb'
  - ' |179.24Mb'
  - ' |234.83Mb'
  - disney_KZ |17.50Mb
  - ' |71.56Mb'
  - Relay_ |204.67Mb
  - disney_HK |23.37Mb
  - disney_netflix_US |21.88Mb
  url: https://www.google.com/generate_204
- name: ‚ôªÔ∏è Ëá™Âä®ÈÄâÊã©
  type: url-test
  proxies:
  - ' |48.95Mb'
  - ' |65.73Mb'
  - ' |67.09Mb'
  - ' |63.29Mb'
  - ' |67.49Mb'
  - disney_netflix_US |66.21Mb
  - disney_netflix_US |65.68Mb
  - ' |59.42Mb'
  - ' |65.67Mb'
  - disney_netflix_US |65.70Mb
  - ' |62.63Mb'
  - netflix_IE |96.54Mb
  - netflix_IE |181.19Mb
  - netflix_IE |92.37Mb
  - ' |97.64Mb'
  - ' |134.97Mb'
  - ' |139.44Mb'
  - ' |104.41Mb'
  - disney_PT |244.42Mb
  - ' |41.30Mb'
  - ' |13.82Mb'
  - disney_US |35.68Mb
  - ' |18.74Mb'
  - disney_US |42.77Mb
  - ' |10.69Mb'
  - _208 |10.20Mb
  - ' |23.54Mb'
  - ' |23.11Mb'
  - disney_SG |15.50Mb
  - ' |10.92Mb'
  - ' |29.56Mb'
  - disney_TW |23.44Mb
  - _248 |11.28Mb
  - ' |20.77Mb'
  - _274 |16.19Mb
  - _257 |79.85Mb
  - Relay_ |11.88Mb
  - Relay_ |11.41Mb
  - Relay_-üá≠üá∞HK_247 |60.78Mb
  - ' |22.08Mb'
  - _277 |49.27Mb
  - _278 |13.72Mb
  - _279 |19.96Mb
  - ' |25.18Mb'
  - Relay_ |14.36Mb
  - ' |40.55Mb'
  - _281 |24.93Mb
  - disney_netflix_GB |232.39Mb
  - _285 |16.29Mb
  - _289 |13.00Mb
  - disney_HK |19.79Mb
  - disney_FR |154.75Mb
  - disney_HK |19.45Mb
  - ' |10.67Mb'
  - disney_SE |167.74Mb
  - disney_FR |148.22Mb
  - ' |20.36Mb'
  - ' |42.40Mb'
  - ' |67.36Mb'
  - disney_HK |15.95Mb
  - ' |166.38Mb'
  - ' |172.58Mb'
  - ' |179.24Mb'
  - ' |234.83Mb'
  - disney_KZ |17.50Mb
  - ' |71.56Mb'
  - Relay_ |204.67Mb
  - disney_HK |23.37Mb
  - disney_netflix_US |21.88Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,üöÄ ËäÇÁÇπÈÄâÊã©
