port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: Relay_ğŸ‡¨ğŸ‡¦CA-ğŸ‡¨ğŸ‡¦CA_45 |735.00Mb
  server: ssca.irundns.net
  type: ssr
  country: ğŸ‡¨ğŸ‡¦CA
  port: 443
  password: $$Turb0VPN$$
  cipher: aes-128-cfb
  protocol: auth_aes128_md5
  obfs: http_post
- name: _32 |38.15Mb
  server: 62.100.205.100
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _36 |10.37Mb
  server: 38.165.231.25
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _28 |36.56Mb
  server: 94.156.250.122
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_58 |10.03Mb
  server: 89.185.84.185
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: m8V5Orkxu2ob8LH24OFobn
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡©ğŸ‡ªDE_47 |13.25Mb
  server: 3.79.57.79
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡¦ğŸ‡¹AT_41 |11.80Mb
  server: 37.235.56.69
  type: ss
  country: ğŸ‡¦ğŸ‡¹AT
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _33 |10.23Mb
  server: 46.183.217.204
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _34 |13.16Mb
  server: 176.126.83.158
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_86 |15.14Mb
  server: 18.224.70.173
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡¬ğŸ‡§GB_59 |20.44Mb
  server: 89.185.84.185
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: iEc68ruj1qOx8hjh1KWZmc
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡²ğŸ‡©MD_85 |12.18Mb
  server: 23.95.76.59
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_91 |70.03Mb
  server: 193.124.24.247
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 6514
  uuid: c362d735-01a8-48eb-baa2-ae7aa63bfdc3
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: _35 |31.20Mb
  server: 185.93.173.60
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: disney_GB |19.17Mb
  server: 89.185.84.185
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: FXjMQIem0uShGvRzOpfyib
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_62 |114.69Mb
  server: 146.70.23.32
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: ğŸ‡±ğŸ‡¹LT_69 |10.13Mb
  server: 45.87.175.171
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: 1RWwXhwfAB5gAEozU4G2Pg
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡³ğŸ‡±NL_87 |18.59Mb
  server: 45.158.171.70
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 8080
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¸ğŸ‡°SK_82 |11.11Mb
  server: 193.37.255.38
  type: ss
  country: ğŸ‡¸ğŸ‡°SK
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: Pool_ğŸ‡­ğŸ‡°HK_64 |183.00Mb
  server: 150.107.46.21
  type: ssr
  country: ğŸ‡­ğŸ‡°HK
  port: 8083
  password: iFqnzSscN
  cipher: aes-256-cfb
  protocol: origin
  obfs: tls1.2_ticket_auth
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - Relay_ğŸ‡¨ğŸ‡¦CA-ğŸ‡¨ğŸ‡¦CA_45 |735.00Mb
  - _32 |38.15Mb
  - _36 |10.37Mb
  - _28 |36.56Mb
  - ğŸ‡¬ğŸ‡§GB_58 |10.03Mb
  - ğŸ‡©ğŸ‡ªDE_47 |13.25Mb
  - ğŸ‡¦ğŸ‡¹AT_41 |11.80Mb
  - _33 |10.23Mb
  - _34 |13.16Mb
  - ğŸ‡ºğŸ‡¸US_86 |15.14Mb
  - ğŸ‡¬ğŸ‡§GB_59 |20.44Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡²ğŸ‡©MD_85 |12.18Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_91 |70.03Mb
  - _35 |31.20Mb
  - disney_GB |19.17Mb
  - ğŸ‡¬ğŸ‡§GB_62 |114.69Mb
  - ğŸ‡±ğŸ‡¹LT_69 |10.13Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡³ğŸ‡±NL_87 |18.59Mb
  - ğŸ‡¸ğŸ‡°SK_82 |11.11Mb
  - Pool_ğŸ‡­ğŸ‡°HK_64 |183.00Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - Relay_ğŸ‡¨ğŸ‡¦CA-ğŸ‡¨ğŸ‡¦CA_45 |735.00Mb
  - _32 |38.15Mb
  - _36 |10.37Mb
  - _28 |36.56Mb
  - ğŸ‡¬ğŸ‡§GB_58 |10.03Mb
  - ğŸ‡©ğŸ‡ªDE_47 |13.25Mb
  - ğŸ‡¦ğŸ‡¹AT_41 |11.80Mb
  - _33 |10.23Mb
  - _34 |13.16Mb
  - ğŸ‡ºğŸ‡¸US_86 |15.14Mb
  - ğŸ‡¬ğŸ‡§GB_59 |20.44Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡²ğŸ‡©MD_85 |12.18Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_91 |70.03Mb
  - _35 |31.20Mb
  - disney_GB |19.17Mb
  - ğŸ‡¬ğŸ‡§GB_62 |114.69Mb
  - ğŸ‡±ğŸ‡¹LT_69 |10.13Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡³ğŸ‡±NL_87 |18.59Mb
  - ğŸ‡¸ğŸ‡°SK_82 |11.11Mb
  - Pool_ğŸ‡­ğŸ‡°HK_64 |183.00Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
