port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: disney_netflix_US |23.16Mb
  server: 23.247.137.64
  type: trojan
  port: 443
  udp: true
  password: 3c4e10af98c30972
  sni: n2.gladns.com
  network: grpc
  grpc-opts:
    grpc-service-name: db
- name: disney_netflix_US |18.44Mb
  server: 160.16.124.55
  type: trojan
  port: 4054
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: disney_netflix_US |13.20Mb
  server: 160.16.57.238
  type: trojan
  port: 4054
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡ºğŸ‡¸US_213 |10.97Mb
  server: 160.16.150.76
  type: trojan
  port: 1596
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: netflix_JP |15.67Mb
  server: 153.121.65.107
  type: trojan
  port: 1331
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡³ğŸ‡±NL_216 |18.40Mb
  server: 160.16.63.16
  type: trojan
  port: 4054
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¯ğŸ‡µJP_208 |13.12Mb
  server: 153.121.65.107
  type: trojan
  port: 3169
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¸ğŸ‡¬SG_206 |15.50Mb
  server: 153.121.51.29
  type: trojan
  port: 127
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: disney_netflix_HK |15.32Mb
  server: 203.198.122.13
  type: trojan
  port: 443
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: disney_netflix_US |16.58Mb
  server: 16.163.0.29
  type: trojan
  port: 4054
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: disney_netflix_FR |73.51Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 27092
  uuid: a0596ba6-72a3-4366-8992-77088da65bd8
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_FR |65.20Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 40433
  uuid: d8fd8955-78db-49ba-d86f-3e4729f6ac4d
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_-ğŸ‡¸ğŸ‡¬SG_219 |13.35Mb
  server: 160.16.144.208
  type: trojan
  port: 3145
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: netflix_MX |40.70Mb
  server: 216.238.89.53
  type: vmess
  country: ğŸ‡²ğŸ‡½MX
  port: 57283
  uuid: 1a5aafc0-6482-451d-fe76-6875b7818579
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡¬ğŸ‡§GB_225 |19.56Mb
  server: 82.38.31.190
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡§ğŸ‡·BR_220 |11.05Mb
  server: 38.180.16.86
  type: vmess
  country: ğŸ‡§ğŸ‡·BR
  port: 36104
  uuid: E146A8CB-9D2F-449C-ADCA-8736FB
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_US |40.84Mb
  server: 38.14.99.163
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 59807
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: auto
  network: tcp
  servername: 38.14.99.163
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_US |16.17Mb
  server: 38.84.201.21
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 53487
  uuid: c3c1ec05-df2c-4975-9b42-e9b007564eb1
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡°ğŸ‡·KR_245 |13.79Mb
  server: 146.56.112.110
  type: vmess
  country: ğŸ‡°ğŸ‡·KR
  port: 8888
  uuid: e7c302f3-90d6-42dd-9d7d-94a3683a3707
  alterId: 0
  cipher: auto
  network: tcp
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡­ğŸ‡°HK_235 |109.32Mb
  server: 8.210.134.183
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 3721
  uuid: e72f5c6b-220f-40b3-a115-2d81473458cf
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
  ws-opts:
    path: /
- name: disney_netflix_HK |19.41Mb
  server: 8.218.116.26
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 32228
  uuid: e4767e9f-ed00-4f31-a984-a918bdd9b09c
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡ºğŸ‡¸US_253 |12.52Mb
  server: 45.136.12.37
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 38141
  uuid: fd291be6-b48d-43a1-da38-66c7f80e2f80
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_HK |27.15Mb
  server: 38.54.98.110
  type: vmess
  country: ğŸ‡²ğŸ‡¾MY
  port: 2052
  uuid: 665d9b8f-153d-4907-adac-de12afd9c851
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: ğŸ‡¸ğŸ‡¬SG_249 |10.48Mb
  server: 68.183.178.131
  type: vmess
  country: ğŸ‡¸ğŸ‡¬SG
  port: 58607
  uuid: c11c32cb-27b3-4afa-c0f3-fb250aa4959e
  alterId: 0
  cipher: auto
  network: ws
  servername: www.12333.monster
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /
    headers:
      HOST: www.12333.monster
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - disney_netflix_US |23.16Mb
  - disney_netflix_US |18.44Mb
  - disney_netflix_US |13.20Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_213 |10.97Mb
  - netflix_JP |15.67Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_216 |18.40Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_208 |13.12Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_206 |15.50Mb
  - disney_netflix_HK |15.32Mb
  - disney_netflix_US |16.58Mb
  - disney_netflix_FR |73.51Mb
  - disney_netflix_FR |65.20Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_219 |13.35Mb
  - netflix_MX |40.70Mb
  - ğŸ‡¬ğŸ‡§GB_225 |19.56Mb
  - ğŸ‡§ğŸ‡·BR_220 |11.05Mb
  - disney_netflix_US |40.84Mb
  - disney_netflix_US |16.17Mb
  - ğŸ‡°ğŸ‡·KR_245 |13.79Mb
  - ğŸ‡­ğŸ‡°HK_235 |109.32Mb
  - disney_netflix_HK |19.41Mb
  - ğŸ‡ºğŸ‡¸US_253 |12.52Mb
  - disney_netflix_HK |27.15Mb
  - ğŸ‡¸ğŸ‡¬SG_249 |10.48Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - disney_netflix_US |23.16Mb
  - disney_netflix_US |18.44Mb
  - disney_netflix_US |13.20Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_213 |10.97Mb
  - netflix_JP |15.67Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_216 |18.40Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_208 |13.12Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_206 |15.50Mb
  - disney_netflix_HK |15.32Mb
  - disney_netflix_US |16.58Mb
  - disney_netflix_FR |73.51Mb
  - disney_netflix_FR |65.20Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_219 |13.35Mb
  - netflix_MX |40.70Mb
  - ğŸ‡¬ğŸ‡§GB_225 |19.56Mb
  - ğŸ‡§ğŸ‡·BR_220 |11.05Mb
  - disney_netflix_US |40.84Mb
  - disney_netflix_US |16.17Mb
  - ğŸ‡°ğŸ‡·KR_245 |13.79Mb
  - ğŸ‡­ğŸ‡°HK_235 |109.32Mb
  - disney_netflix_HK |19.41Mb
  - ğŸ‡ºğŸ‡¸US_253 |12.52Mb
  - disney_netflix_HK |27.15Mb
  - ğŸ‡¸ğŸ‡¬SG_249 |10.48Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
