port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: _256 |59.45Mb
  server: 5.181.21.246
  type: ss
  port: 443
  udp: true
  password: gKYygTcRYhc3skc2x6tZ073lYz0DnieX
  cipher: chacha20-ietf-poly1305
- name: Pool__241 |152.48Mb
  server: 86.106.84.195
  type: ss
  port: 13262
  udp: true
  password: kfuzkwdg4oynv495aywc
  cipher: aes-128-gcm
- name: _265 |16.37Mb
  server: 43.165.7.71
  type: vmess
  port: 19751
  uuid: 6cfa6103-5d06-40cb-f452-b563db578288
  alterId: 0
  cipher: auto
  network: http
  http-opts:
    method: GET
    path:
    - /
  h2-opts: {}
- name: _243 |64.99Mb
  server: 13.61.13.231
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: _251 |146.88Mb
  server: 51.20.125.235
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: _271 |39.57Mb
  server: 216.238.86.158
  type: vmess
  port: 34460
  udp: true
  uuid: 90be214d-048c-4ea2-a602-b8e4d4e51e36
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _270 |41.99Mb
  server: 163.192.49.195
  type: vmess
  port: 443
  uuid: bcb7c581-3c95-4569-a4e7-918141e91ea3
  alterId: 0
  cipher: auto
  network: http
  http-opts:
    path:
    - /
    headers:
      Host:
      - a.189.cn
  h2-opts: {}
- name: disney_US |30.98Mb
  server: 192.204.47.79
  type: vmess
  port: 42277
  udp: true
  uuid: aee61b21-e85a-484b-f203-b245f1451cff
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _275 |214.24Mb
  server: 85.195.101.122
  type: vmess
  port: 40878
  uuid: f3d4167e-b15e-4e46-82e9-9286ef93fda7
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: disney_SG |14.78Mb
  server: 165.154.195.38
  type: vmess
  port: 35034
  uuid: 959a8caf-4cea-43d0-a548-3628e7ddfafc
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: disney_US |27.72Mb
  server: 165.140.216.141
  type: vmess
  port: 443
  uuid: e7d72a8d-26f2-4b54-b366-0c43e0bcba7d
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: disney_SG |10.20Mb
  server: 103.36.91.32
  type: ss
  port: 8388
  udp: true
  password: asd123456
  cipher: chacha20-ietf
- name: _238 |177.32Mb
  server: 185.231.233.112
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: _272 |25.84Mb
  server: 8.210.184.105
  type: vmess
  port: 40374
  udp: true
  uuid: 36b76373-7a4f-4669-9113-7d247bcf2704
  alterId: 0
  cipher: auto
  network: http
  http-opts:
    method: GET
    path:
    - /
  h2-opts: {}
- name: Pool__299 |184.74Mb
  server: 70.34.218.149
  type: trojan
  port: 11930
  password: BaeSzHdfJIR13l67
  sni: softpillow.silentrocket.click
- name: _303 |24.44Mb
  server: 38.96.254.102
  type: trojan
  port: 18509
  password: .ie4rghJuMkcf0oF
  sni: shoppingmall.electricbanana.click
- name: _300 |10.54Mb
  server: 160.16.131.243
  type: trojan
  port: 2760
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
  skip-cert-verify: true
- name: disney_netflix_GB |268.31Mb
  server: 172.67.134.185
  type: trojan
  port: 443
  udp: true
  password: POORIARED
  sni: reDfRee8.REDFree8.ir
  ws-opts:
    path: /eyJqdW5rIjoiVUl6eXhLZkkwUTJ3ZzkiLCJwcm90b2NvbCI6InRyIiwibW9kZSI6InByb3h5aXAiLCJwYW5lbElQcyI6W119?ed=2560
    headers:
      Host: reDfRee8.REDFree8.ir
  network: ws
- name: disney_HK |16.82Mb
  server: 154.21.201.83
  type: vmess
  port: 443
  uuid: 4bf075f5-4d5e-4d39-f5ab-b32a86250f0e
  alterId: 0
  cipher: auto
  network: ws
  servername: hk.nbee.pp.ua
  http-opts: {}
  h2-opts: {}
  tls: true
  ws-opts:
    path: /aa
    headers:
      Host: hk.nbee.pp.ua
- name: Relay_-ğŸ‡¯ğŸ‡µJP_279 |22.14Mb
  server: yg6.ygkkk.dpdns.org
  type: vmess
  port: 80
  udp: true
  uuid: 130ec091-df05-4af9-9695-dc982e98a8ec
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /130ec091-df05-4af9-9695-dc982e98a8ec-vm?ed=2048
    headers:
      Host: jporacleyg2.336697.xyz
- name: _289 |38.78Mb
  server: 89.31.120.192
  type: vmess
  port: 443
  uuid: 44537595-9ccc-4b83-8936-5f9ad3229019
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: disney_HK |28.67Mb
  server: 58.152.53.174
  type: trojan
  port: 443
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: Relay_-ğŸ‡¯ğŸ‡µJP_304 |23.39Mb
  server: 160.16.87.174
  type: trojan
  port: 3169
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: disney_FR |172.70Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 40433
  uuid: d8fd8955-78db-49ba-d86f-3e4729f6ac4d
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_FR |177.04Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 27092
  uuid: a0596ba6-72a3-4366-8992-77088da65bd8
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡¬ğŸ‡§GB_323 |154.29Mb
  server: 82.38.31.191
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: _305 |18.47Mb
  server: 160.16.107.37
  type: trojan
  port: 3093
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: ğŸ‡¬ğŸ‡§GB_324 |164.16Mb
  server: 82.38.31.217
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_325 |245.67Mb
  server: 82.38.31.194
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_337 |55.74Mb
  server: 47.253.197.26
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 12056
  uuid: dd7be7f1-38ff-45e6-f1e5-b20c2190f527
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡²ğŸ‡½MX_331 |42.01Mb
  server: 216.238.87.47
  type: vmess
  country: ğŸ‡²ğŸ‡½MX
  port: 27502
  uuid: b8155ce4-7e08-4c40-800f-8671312b7124
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_KZ |12.81Mb
  server: 31.3.209.183
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 28212
  password: Kmn7dHPw5wNfkqQMPcGWQA
  cipher: chacha20-ietf-poly1305
- name: Pool_ğŸ‡·ğŸ‡´RO_332 |181.20Mb
  server: 86.106.84.198
  type: ss
  country: ğŸ‡·ğŸ‡´RO
  port: 13265
  password: phizo046s4oqsm33sfvm
  cipher: aes-128-gcm
- name: ğŸ‡ºğŸ‡¸US_335 |123.75Mb
  server: 45.12.136.170
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: l668XHPejoSNNuD66BYzyehaCpZexiF7
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸ‡©ğŸ‡ªDE-ğŸ‡©ğŸ‡ªDE_315 |126.28Mb
  server: cpanel.navar1.ir
  type: vmess
  country: ğŸ‡©ğŸ‡ªDE
  port: 100
  uuid: 95c6f6f0-84f7-4443-8a50-a59f8e66f5ee
  alterId: 0
  cipher: auto
  network: tcp
  servername: cpanel.navar1.ir
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_HK |25.48Mb
  server: 45.207.157.29
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 13852
  uuid: 845764df-ecb3-4b13-bed2-bf1551b68e9a
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_US |32.27Mb
  server: cf.fovi.tk
  type: vmess
  country: ğŸZZ
  port: 443
  uuid: bf67437e-6c90-45ca-abc2-c7240a5ce2aa
  alterId: 0
  cipher: auto
  network: ws
  servername: foxpol.fovi.tk
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /eisasqa
    headers:
      HOST: foxpol.fovi.tk
- name: Relay_-ğŸ‡ºğŸ‡¸US_268 |13.33Mb
  server: yg1.ygkkk.dpdns.org
  type: vmess
  port: 443
  udp: true
  uuid: 7a88d322-eb4a-4a59-8c62-8c60d76abf4b
  alterId: 0
  cipher: auto
  network: ws
  servername: jporacleyg.336697.xyz
  http-opts: {}
  h2-opts: {}
  tls: true
  ws-opts:
    path: /7a88d322-eb4a-4a59-8c62-8c60d76abf4b-vm?ed=2048
    headers:
      Host: jporacleyg.336697.xyz
- name: Relay_-ğŸ‡¯ğŸ‡µJP_257 |14.78Mb
  server: yg1.ygkkk.dpdns.org
  type: vmess
  port: 443
  udp: true
  uuid: 130ec091-df05-4af9-9695-dc982e98a8ec
  alterId: 0
  cipher: auto
  network: ws
  servername: jporacleyg2.336697.xyz
  http-opts: {}
  h2-opts: {}
  tls: true
  ws-opts:
    path: /130ec091-df05-4af9-9695-dc982e98a8ec-vm
    headers:
      Host: jporacleyg2.336697.xyz
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - _256 |59.45Mb
  - Pool__241 |152.48Mb
  - _265 |16.37Mb
  - _243 |64.99Mb
  - _251 |146.88Mb
  - _271 |39.57Mb
  - _270 |41.99Mb
  - disney_US |30.98Mb
  - _275 |214.24Mb
  - disney_SG |14.78Mb
  - disney_US |27.72Mb
  - disney_SG |10.20Mb
  - _238 |177.32Mb
  - _272 |25.84Mb
  - Pool__299 |184.74Mb
  - _303 |24.44Mb
  - _300 |10.54Mb
  - disney_netflix_GB |268.31Mb
  - disney_HK |16.82Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_279 |22.14Mb
  - _289 |38.78Mb
  - disney_HK |28.67Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_304 |23.39Mb
  - disney_FR |172.70Mb
  - disney_FR |177.04Mb
  - ğŸ‡¬ğŸ‡§GB_323 |154.29Mb
  - _305 |18.47Mb
  - ğŸ‡¬ğŸ‡§GB_324 |164.16Mb
  - ğŸ‡¬ğŸ‡§GB_325 |245.67Mb
  - ğŸ‡ºğŸ‡¸US_337 |55.74Mb
  - ğŸ‡²ğŸ‡½MX_331 |42.01Mb
  - disney_KZ |12.81Mb
  - Pool_ğŸ‡·ğŸ‡´RO_332 |181.20Mb
  - ğŸ‡ºğŸ‡¸US_335 |123.75Mb
  - Relay_ğŸ‡©ğŸ‡ªDE-ğŸ‡©ğŸ‡ªDE_315 |126.28Mb
  - disney_HK |25.48Mb
  - disney_US |32.27Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_268 |13.33Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_257 |14.78Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - _256 |59.45Mb
  - Pool__241 |152.48Mb
  - _265 |16.37Mb
  - _243 |64.99Mb
  - _251 |146.88Mb
  - _271 |39.57Mb
  - _270 |41.99Mb
  - disney_US |30.98Mb
  - _275 |214.24Mb
  - disney_SG |14.78Mb
  - disney_US |27.72Mb
  - disney_SG |10.20Mb
  - _238 |177.32Mb
  - _272 |25.84Mb
  - Pool__299 |184.74Mb
  - _303 |24.44Mb
  - _300 |10.54Mb
  - disney_netflix_GB |268.31Mb
  - disney_HK |16.82Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_279 |22.14Mb
  - _289 |38.78Mb
  - disney_HK |28.67Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_304 |23.39Mb
  - disney_FR |172.70Mb
  - disney_FR |177.04Mb
  - ğŸ‡¬ğŸ‡§GB_323 |154.29Mb
  - _305 |18.47Mb
  - ğŸ‡¬ğŸ‡§GB_324 |164.16Mb
  - ğŸ‡¬ğŸ‡§GB_325 |245.67Mb
  - ğŸ‡ºğŸ‡¸US_337 |55.74Mb
  - ğŸ‡²ğŸ‡½MX_331 |42.01Mb
  - disney_KZ |12.81Mb
  - Pool_ğŸ‡·ğŸ‡´RO_332 |181.20Mb
  - ğŸ‡ºğŸ‡¸US_335 |123.75Mb
  - Relay_ğŸ‡©ğŸ‡ªDE-ğŸ‡©ğŸ‡ªDE_315 |126.28Mb
  - disney_HK |25.48Mb
  - disney_US |32.27Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_268 |13.33Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_257 |14.78Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
