port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: _208 |46.11Mb
  server: 173.234.29.2
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _204 |12.97Mb
  server: 172.105.199.111
  type: ss
  port: 8080
  udp: true
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: _211 |207.45Mb
  server: 151.242.251.152
  type: ss
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_NL |111.91Mb
  server: 193.29.139.177
  type: ss
  port: 8080
  udp: true
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: _197 |26.73Mb
  server: 103.149.182.86
  type: ss
  port: 8388
  udp: true
  password: asd123456
  cipher: chacha20-ietf
- name: disney_HK |12.35Mb
  server: 103.149.183.200
  type: ss
  port: 8388
  udp: true
  password: asd123456
  cipher: chacha20-ietf
- name: _213 |29.80Mb
  server: 194.246.114.101
  type: ss
  port: 443
  udp: true
  password: HaNqw9pIE4jcx98sg7UQgHeGNTM4R2pk
  cipher: chacha20-ietf-poly1305
- name: _207 |14.73Mb
  server: 185.192.124.188
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: _199 |10.52Mb
  server: 147.78.1.230
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: _215 |217.54Mb
  server: 82.38.31.176
  type: ss
  port: 8080
  udp: true
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: _227 |51.14Mb
  server: 156.146.38.170
  type: ss
  port: 443
  udp: true
  password: shadowsocks
  cipher: aes-128-gcm
- name: _234 |53.03Mb
  server: 156.146.38.169
  type: ss
  port: 443
  udp: true
  password: shadowsocks
  cipher: aes-128-gcm
- name: _237 |51.38Mb
  server: 156.146.38.167
  type: ss
  port: 443
  udp: true
  password: shadowsocks
  cipher: aes-128-gcm
- name: _210 |45.19Mb
  server: 156.59.243.6
  type: ss
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _216 |193.72Mb
  server: 82.38.31.214
  type: ss
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: Relay_-ğŸ‡¨ğŸ‡¦CA_231 |67.96Mb
  server: 79.127.200.169
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _221 |124.25Mb
  server: 82.38.31.202
  type: ss
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: _226 |10.01Mb
  server: 62.100.205.100
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _239 |21.25Mb
  server: 137.184.174.93
  type: ss
  port: 8080
  udp: true
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: _218 |22.62Mb
  server: 128.199.172.224
  type: ss
  port: 8080
  udp: true
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: disney_netflix_NL |223.95Mb
  server: 45.87.175.28
  type: ss
  port: 8080
  udp: true
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: _238 |243.11Mb
  server: 45.14.245.2
  type: ss
  port: 443
  password: 17ZDORWIliQHuO6WRGHChXYMzdRtAYVP
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_GB |740.94Mb
  server: 146.70.61.37
  type: ss
  port: 8080
  udp: true
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: _224 |26.87Mb
  server: 147.78.0.182
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _240 |17.63Mb
  server: 95.164.116.33
  type: ss
  port: 443
  password: pQmnC03JObbPhdh5FBJHgD6jnTLchsRA
  cipher: chacha20-ietf-poly1305
- name: Relay_-ğŸ‡µğŸ‡±PL_243 |20.69Mb
  server: 193.135.174.135
  type: ss
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: disney_ES |10.02Mb
  server: 145.249.109.121
  type: ss
  port: 25512
  udp: true
  password: smSMfR9jqLgMkHuQtxSIWh
  cipher: chacha20-ietf-poly1305
- name: Relay_-ğŸ‡ªğŸ‡ªEE_246 |12.82Mb
  server: est01-ss01.tcp-reset-club.net
  type: ss
  port: 8444
  udp: true
  password: AWNeHjukGQWwuFXadw2r6qH7gh4hZ9cj
  cipher: chacha20-ietf-poly1305
- name: _249 |240.22Mb
  server: 151.242.251.142
  type: ss
  port: 8080
  udp: true
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: _250 |146.67Mb
  server: 82.38.31.190
  type: ss
  port: 8080
  udp: true
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: disney_PY |17.75Mb
  server: 38.165.233.93
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: _262 |61.15Mb
  server: 103.35.189.136
  type: ss
  port: 443
  udp: true
  password: SS2QvbC9nqLp2sXXZo0BVy4slcErRuCt
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_NL |375.39Mb
  server: 51.15.23.166
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: _253 |58.10Mb
  server: 141.98.101.178
  type: ss
  port: 443
  udp: true
  password: shadowsocks
  cipher: aes-128-gcm
- name: _254 |42.82Mb
  server: 194.59.183.134
  type: ss
  port: 46114
  udp: true
  password: lejSRyqa033OEPmEQsvRsl
  cipher: chacha20-ietf-poly1305
- name: _261 |10.01Mb
  server: 196.196.192.58
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _257 |67.12Mb
  server: 89.221.225.15
  type: ss
  port: 443
  udp: true
  password: yCbQ4bry4otfifK7oel71NaXpPL9pYJb
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_NL |232.37Mb
  server: 82.38.31.179
  type: ss
  port: 8080
  udp: true
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: _280 |387.41Mb
  server: 172.233.229.91
  type: vmess
  port: 14102
  udp: true
  uuid: 27ba87fc-583f-4763-9060-83cf0b9264db
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: _265 |160.03Mb
  server: 138.186.143.32
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: _269 |44.50Mb
  server: 185.82.73.212
  type: ss
  port: 8444
  udp: true
  password: _bypfvq6ra7g4n5yCCR9DoVeGya2XUUS
  cipher: chacha20-ietf-poly1305
- name: _268 |43.58Mb
  server: 138.186.143.32
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _289 |10.86Mb
  server: 160.16.131.243
  type: trojan
  port: 2760
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
  skip-cert-verify: true
- name: Relay_-ğŸ‡¯ğŸ‡µJP_296 |11.53Mb
  server: 160.16.117.182
  type: trojan
  port: 3093
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡­ğŸ‡°HK_279 |66.27Mb
  server: v9.hdacd.com
  type: vmess
  port: 30809
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: ğŸ‡¨ğŸ‡¦CA_303 |45.66Mb
  server: 193.203.203.66
  type: ss
  country: ğŸ‡¨ğŸ‡¦CA
  port: 443
  password: S6jUK9Fw5fMHgNqlqXObHZWv8Tf4nEkm
  cipher: chacha20-ietf-poly1305
- name: _297 |10.83Mb
  server: 160.16.106.144
  type: trojan
  port: 2760
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
  skip-cert-verify: true
- name: _298 |10.92Mb
  server: 160.16.116.227
  type: trojan
  port: 2760
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
  skip-cert-verify: true
- name: disney_HK |26.71Mb
  server: 112.118.116.8
  type: trojan
  port: 443
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: disney_HK |23.07Mb
  server: 58.152.30.31
  type: trojan
  port: 443
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: netflix_NO |38.35Mb
  server: 185.213.23.63
  type: ss
  country: ğŸ‡¨ğŸ‡¦CA
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡§ğŸ‡·BR_301 |21.78Mb
  server: 185.192.124.188
  type: ss
  country: ğŸ‡§ğŸ‡·BR
  port: 990
  password: f8f7aCzcPKbsF8p3
  cipher: chacha20-ietf-poly1305
- name: _264 |176.92Mb
  server: h110vpnnl.outlinekeys.net
  type: ss
  port: 52571
  udp: true
  password: b0TKxnHAYeeFYyzTAMXn0F
  cipher: chacha20-ietf-poly1305
- name: disney_CH |190.66Mb
  server: 138.124.67.26
  type: ss
  country: ğŸ‡¨ğŸ‡­CH
  port: 25572
  password: nqcIfYHlpMn3jzqkNDjKaG
  cipher: chacha20-ietf-poly1305
- name: disney_DE |275.68Mb
  server: 89.163.140.136
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ğŸ‡©ğŸ‡ªDE_311 |245.01Mb
  server: 3.66.69.180
  type: trojan
  country: ğŸ‡©ğŸ‡ªDE
  port: 22223
  udp: true
  password: telegram-id-directvpn
  sni: trojan.burgerip.co.uk
  skip-cert-verify: true
- name: ğŸ‡©ğŸ‡ªDE_312 |313.97Mb
  server: 3.66.69.180
  type: trojan
  country: ğŸ‡©ğŸ‡ªDE
  port: 22222
  udp: true
  password: telegram-id-privatevpns
  sni: trojan.burgerip.co.uk
  skip-cert-verify: true
- name: ğŸ‡¬ğŸ‡§GB_313 |78.44Mb
  server: 141.98.101.182
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: shadowsocks
  cipher: aes-128-gcm
- name: Relay_ğŸ‡¬ğŸ‡§GB-ğŸ‡³ğŸ‡±NL_314 |136.87Mb
  server: 82.38.31.208
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡­ğŸ‡°HK_316 |112.97Mb
  server: 8.218.116.26
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 32228
  uuid: e4767e9f-ed00-4f31-a984-a918bdd9b09c
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡­ğŸ‡°HK_317 |123.03Mb
  server: 8.218.105.196
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 52752
  uuid: 925bdbf5-72be-4437-bebf-441c61089f6b
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_HK |29.66Mb
  server: 45.207.157.29
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 13852
  uuid: 845764df-ecb3-4b13-bed2-bf1551b68e9a
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡±ğŸ‡¹LT_327 |197.43Mb
  server: 45.87.175.185
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡²ğŸ‡½MX_337 |38.20Mb
  server: 216.238.87.47
  type: vmess
  country: ğŸ‡²ğŸ‡½MX
  port: 27502
  uuid: b8155ce4-7e08-4c40-800f-8671312b7124
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_NL |221.97Mb
  server: 45.87.175.180
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: QCXDxuDlTTMD7jtgHUjIoj
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_330 |49.78Mb
  server: 45.87.175.175
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: QCXDxuDlTTMD7jtgHUjIoj
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_332 |217.26Mb
  server: 45.87.175.185
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_333 |214.07Mb
  server: 45.87.175.183
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: disney_LV |54.97Mb
  server: 46.183.217.204
  type: ss
  country: ğŸ‡±ğŸ‡» LV
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡³ğŸ‡±NL_341 |264.26Mb
  server: 194.87.216.218
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 52571
  password: b0TKxnHAYeeFYyzTAMXn0F
  cipher: chacha20-ietf-poly1305
- name: ğŸZZ_354 |34.64Mb
  server: hgtrojan.zabc.net
  type: vmess
  country: ğŸZZ
  port: 2083
  uuid: e6395c20-4571-4b34-d6b1-55a5d36e49ea
  alterId: 0
  cipher: auto
  network: ws
  servername: hgtrojan.zabc.net
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /e6395c20
    headers:
      HOST: hgtrojan.zabc.net
- name: Relay_ğŸZZ-ğŸ‡®ğŸ‡³IN_356 |37.74Mb
  server: 104.18.14.55
  type: vmess
  country: ğŸZZ
  port: 2052
  uuid: e6447786-8c85-443c-8017-7feaa673ff45
  alterId: 0
  cipher: auto
  network: ws
  servername: in4.123417.xyz
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
  ws-opts:
    path: /
    headers:
      HOST: in4.123417.xyz
- name: Relay_ğŸ‡¯ğŸ‡µJP-ğŸ‡¯ğŸ‡µJP_324 |10.52Mb
  server: xray.kk37005.tk
  type: vmess
  country: ğŸ‡¯ğŸ‡µJP
  port: 55919
  uuid: 2e7548bb-7c5b-4d97-d64d-1b2fe4050089
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: ğŸ‡³ğŸ‡±NL_342 |47.09Mb
  server: 178.23.190.238
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 443
  password: uo7EbtqIwgZXXHmMv5LbLcOxptyPlNkh
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡³ğŸ‡±NL_343 |147.22Mb
  server: 193.29.139.141
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 8080
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¸ğŸ‡¬SG_348 |13.75Mb
  server: 68.183.227.45
  type: ss
  country: ğŸ‡¸ğŸ‡¬SG
  port: 8080
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: ğŸ‡µğŸ‡¹PT_347 |58.17Mb
  server: 185.113.143.186
  type: ss
  country: ğŸ‡µğŸ‡¹PT
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: disney_PT |212.72Mb
  server: 185.231.233.112
  type: ss
  country: ğŸ ZZ
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: Relay_ğŸZZ-ğŸ‡®ğŸ‡·IR_355 |16.70Mb
  server: cf.fovi.tk
  type: vmess
  country: ğŸZZ
  port: 443
  uuid: bf67437e-6c90-45ca-abc2-c7240a5ce2aa
  alterId: 0
  cipher: auto
  network: ws
  servername: foxlux.fovi.tk
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /eisasqa
    headers:
      HOST: foxlux.fovi.tk
- name: ğŸ‡±ğŸ‡¹LT_329 |47.92Mb
  server: ltnl16.saint.ydns.eu
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_350 |58.59Mb
  server: 45.150.52.40
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  uuid: c31777a1-2ee6-4864-db4c-a79fcbc8188b
  alterId: 0
  cipher: auto
  network: ws
  servername: xsj011-3.facai2024.com
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /c31777a1
    headers:
      HOST: xsj011-3.facai2024.com
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - _208 |46.11Mb
  - _204 |12.97Mb
  - _211 |207.45Mb
  - disney_netflix_NL |111.91Mb
  - _197 |26.73Mb
  - disney_HK |12.35Mb
  - _213 |29.80Mb
  - _207 |14.73Mb
  - _199 |10.52Mb
  - _215 |217.54Mb
  - _227 |51.14Mb
  - _234 |53.03Mb
  - _237 |51.38Mb
  - _210 |45.19Mb
  - _216 |193.72Mb
  - Relay_-ğŸ‡¨ğŸ‡¦CA_231 |67.96Mb
  - _221 |124.25Mb
  - _226 |10.01Mb
  - _239 |21.25Mb
  - _218 |22.62Mb
  - disney_netflix_NL |223.95Mb
  - _238 |243.11Mb
  - disney_netflix_GB |740.94Mb
  - _224 |26.87Mb
  - _240 |17.63Mb
  - Relay_-ğŸ‡µğŸ‡±PL_243 |20.69Mb
  - disney_ES |10.02Mb
  - Relay_-ğŸ‡ªğŸ‡ªEE_246 |12.82Mb
  - _249 |240.22Mb
  - _250 |146.67Mb
  - disney_PY |17.75Mb
  - _262 |61.15Mb
  - disney_netflix_NL |375.39Mb
  - _253 |58.10Mb
  - _254 |42.82Mb
  - _261 |10.01Mb
  - _257 |67.12Mb
  - disney_netflix_NL |232.37Mb
  - _280 |387.41Mb
  - _265 |160.03Mb
  - _269 |44.50Mb
  - _268 |43.58Mb
  - _289 |10.86Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_296 |11.53Mb
  - Relay_-ğŸ‡­ğŸ‡°HK_279 |66.27Mb
  - ğŸ‡¨ğŸ‡¦CA_303 |45.66Mb
  - _297 |10.83Mb
  - _298 |10.92Mb
  - disney_HK |26.71Mb
  - disney_HK |23.07Mb
  - netflix_NO |38.35Mb
  - ğŸ‡§ğŸ‡·BR_301 |21.78Mb
  - _264 |176.92Mb
  - disney_CH |190.66Mb
  - disney_DE |275.68Mb
  - ğŸ‡©ğŸ‡ªDE_311 |245.01Mb
  - ğŸ‡©ğŸ‡ªDE_312 |313.97Mb
  - ğŸ‡¬ğŸ‡§GB_313 |78.44Mb
  - Relay_ğŸ‡¬ğŸ‡§GB-ğŸ‡³ğŸ‡±NL_314 |136.87Mb
  - ğŸ‡­ğŸ‡°HK_316 |112.97Mb
  - ğŸ‡­ğŸ‡°HK_317 |123.03Mb
  - disney_HK |29.66Mb
  - ğŸ‡±ğŸ‡¹LT_327 |197.43Mb
  - ğŸ‡²ğŸ‡½MX_337 |38.20Mb
  - disney_netflix_NL |221.97Mb
  - ğŸ‡±ğŸ‡¹LT_330 |49.78Mb
  - ğŸ‡±ğŸ‡¹LT_332 |217.26Mb
  - ğŸ‡±ğŸ‡¹LT_333 |214.07Mb
  - disney_LV |54.97Mb
  - ğŸ‡³ğŸ‡±NL_341 |264.26Mb
  - ğŸZZ_354 |34.64Mb
  - Relay_ğŸZZ-ğŸ‡®ğŸ‡³IN_356 |37.74Mb
  - Relay_ğŸ‡¯ğŸ‡µJP-ğŸ‡¯ğŸ‡µJP_324 |10.52Mb
  - ğŸ‡³ğŸ‡±NL_342 |47.09Mb
  - ğŸ‡³ğŸ‡±NL_343 |147.22Mb
  - ğŸ‡¸ğŸ‡¬SG_348 |13.75Mb
  - ğŸ‡µğŸ‡¹PT_347 |58.17Mb
  - disney_PT |212.72Mb
  - Relay_ğŸZZ-ğŸ‡®ğŸ‡·IR_355 |16.70Mb
  - ğŸ‡±ğŸ‡¹LT_329 |47.92Mb
  - ğŸ‡ºğŸ‡¸US_350 |58.59Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - _208 |46.11Mb
  - _204 |12.97Mb
  - _211 |207.45Mb
  - disney_netflix_NL |111.91Mb
  - _197 |26.73Mb
  - disney_HK |12.35Mb
  - _213 |29.80Mb
  - _207 |14.73Mb
  - _199 |10.52Mb
  - _215 |217.54Mb
  - _227 |51.14Mb
  - _234 |53.03Mb
  - _237 |51.38Mb
  - _210 |45.19Mb
  - _216 |193.72Mb
  - Relay_-ğŸ‡¨ğŸ‡¦CA_231 |67.96Mb
  - _221 |124.25Mb
  - _226 |10.01Mb
  - _239 |21.25Mb
  - _218 |22.62Mb
  - disney_netflix_NL |223.95Mb
  - _238 |243.11Mb
  - disney_netflix_GB |740.94Mb
  - _224 |26.87Mb
  - _240 |17.63Mb
  - Relay_-ğŸ‡µğŸ‡±PL_243 |20.69Mb
  - disney_ES |10.02Mb
  - Relay_-ğŸ‡ªğŸ‡ªEE_246 |12.82Mb
  - _249 |240.22Mb
  - _250 |146.67Mb
  - disney_PY |17.75Mb
  - _262 |61.15Mb
  - disney_netflix_NL |375.39Mb
  - _253 |58.10Mb
  - _254 |42.82Mb
  - _261 |10.01Mb
  - _257 |67.12Mb
  - disney_netflix_NL |232.37Mb
  - _280 |387.41Mb
  - _265 |160.03Mb
  - _269 |44.50Mb
  - _268 |43.58Mb
  - _289 |10.86Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_296 |11.53Mb
  - Relay_-ğŸ‡­ğŸ‡°HK_279 |66.27Mb
  - ğŸ‡¨ğŸ‡¦CA_303 |45.66Mb
  - _297 |10.83Mb
  - _298 |10.92Mb
  - disney_HK |26.71Mb
  - disney_HK |23.07Mb
  - netflix_NO |38.35Mb
  - ğŸ‡§ğŸ‡·BR_301 |21.78Mb
  - _264 |176.92Mb
  - disney_CH |190.66Mb
  - disney_DE |275.68Mb
  - ğŸ‡©ğŸ‡ªDE_311 |245.01Mb
  - ğŸ‡©ğŸ‡ªDE_312 |313.97Mb
  - ğŸ‡¬ğŸ‡§GB_313 |78.44Mb
  - Relay_ğŸ‡¬ğŸ‡§GB-ğŸ‡³ğŸ‡±NL_314 |136.87Mb
  - ğŸ‡­ğŸ‡°HK_316 |112.97Mb
  - ğŸ‡­ğŸ‡°HK_317 |123.03Mb
  - disney_HK |29.66Mb
  - ğŸ‡±ğŸ‡¹LT_327 |197.43Mb
  - ğŸ‡²ğŸ‡½MX_337 |38.20Mb
  - disney_netflix_NL |221.97Mb
  - ğŸ‡±ğŸ‡¹LT_330 |49.78Mb
  - ğŸ‡±ğŸ‡¹LT_332 |217.26Mb
  - ğŸ‡±ğŸ‡¹LT_333 |214.07Mb
  - disney_LV |54.97Mb
  - ğŸ‡³ğŸ‡±NL_341 |264.26Mb
  - ğŸZZ_354 |34.64Mb
  - Relay_ğŸZZ-ğŸ‡®ğŸ‡³IN_356 |37.74Mb
  - Relay_ğŸ‡¯ğŸ‡µJP-ğŸ‡¯ğŸ‡µJP_324 |10.52Mb
  - ğŸ‡³ğŸ‡±NL_342 |47.09Mb
  - ğŸ‡³ğŸ‡±NL_343 |147.22Mb
  - ğŸ‡¸ğŸ‡¬SG_348 |13.75Mb
  - ğŸ‡µğŸ‡¹PT_347 |58.17Mb
  - disney_PT |212.72Mb
  - Relay_ğŸZZ-ğŸ‡®ğŸ‡·IR_355 |16.70Mb
  - ğŸ‡±ğŸ‡¹LT_329 |47.92Mb
  - ğŸ‡ºğŸ‡¸US_350 |58.59Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
