port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: disney_netflix_US |42.02Mb
  server: 163.192.49.195
  type: vmess
  port: 443
  uuid: bcb7c581-3c95-4569-a4e7-918141e91ea3
  alterId: 0
  cipher: auto
  network: http
  http-opts:
    path:
    - /
    headers:
      Host:
      - a.189.cn
  h2-opts: {}
- name: disney_netflix_US |40.32Mb
  server: 38.14.99.179
  type: vmess
  port: 59807
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: disney_netflix_US |137.30Mb
  server: 192.204.47.79
  type: vmess
  port: 42277
  udp: true
  uuid: aee61b21-e85a-484b-f203-b245f1451cff
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: disney_CH |71.61Mb
  server: 138.124.67.26
  type: ss
  port: 443
  udp: true
  password: UdKq4itZdbbvsy0PCHTEUi
  cipher: chacha20-ietf-poly1305
- name: netflix_SE |163.52Mb
  server: 13.61.13.231
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: netflix_SE |161.06Mb
  server: 13.61.180.46
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: netflix_SE |154.30Mb
  server: 51.20.125.235
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: disney_netflix_US |36.71Mb
  server: 38.14.99.163
  type: vmess
  port: 59807
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _155 |146.97Mb
  server: 38.165.233.93
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: disney_netflix_US |44.19Mb
  server: 165.140.216.141
  type: vmess
  port: 443
  uuid: e7d72a8d-26f2-4b54-b366-0c43e0bcba7d
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _156 |13.80Mb
  server: 103.149.182.86
  type: ss
  port: 8388
  udp: true
  password: asd123456
  cipher: chacha20-ietf
- name: _178 |23.11Mb
  server: 8.218.105.196
  type: vmess
  port: 52752
  uuid: 925bdbf5-72be-4437-bebf-441c61089f6b
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: disney_netflix_GB |179.85Mb
  server: 172.67.134.185
  type: trojan
  port: 443
  udp: true
  password: POORIARED
  sni: reDfRee8.REDFree8.ir
  ws-opts:
    path: /eyJqdW5rIjoiVUl6eXhLZkkwUTJ3ZzkiLCJwcm90b2NvbCI6InRyIiwibW9kZSI6InByb3h5aXAiLCJwYW5lbElQcyI6W119?ed=2560
    headers:
      Host: reDfRee8.REDFree8.ir
  network: ws
- name: _192 |10.59Mb
  server: 130.162.152.253
  type: vmess
  port: 56867
  uuid: 5206bb9f-2cbc-44ac-de2a-471439a23707
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _201 |15.81Mb
  server: 38.180.16.86
  type: vmess
  port: 36236
  uuid: a58bc1a5-8c18-49ff-9453-c331b52f45dc
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _184 |42.30Mb
  server: 89.31.120.192
  type: vmess
  port: 443
  uuid: 44537595-9ccc-4b83-8936-5f9ad3229019
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _208 |10.21Mb
  server: 160.16.204.136
  type: trojan
  port: 2890
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: _209 |18.66Mb
  server: 160.16.131.243
  type: trojan
  port: 2760
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
  skip-cert-verify: true
- name: _215 |10.90Mb
  server: 160.16.107.37
  type: trojan
  port: 3093
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: _206 |10.25Mb
  server: 140.238.2.250
  type: vmess
  port: 443
  uuid: 41a7089a-040b-4538-8b8d-010902405bde
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: Pool__217 |181.91Mb
  server: 70.34.218.149
  type: trojan
  port: 11930
  password: BaeSzHdfJIR13l67
  sni: softpillow.silentrocket.click
- name: netflix_NL |122.34Mb
  server: 82.38.31.191
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: _218 |11.22Mb
  server: 160.16.116.227
  type: trojan
  port: 2760
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
  skip-cert-verify: true
- name: netflix_IT |167.41Mb
  server: 146.70.73.210
  type: trojan
  port: 53809
  udp: true
  password: blhwsknjxmfuydz0vhfv
  sni: www.vk.com
  skip-cert-verify: true
- name: ğŸ‡¬ğŸ‡§GB_240 |184.35Mb
  server: 82.38.31.194
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: netflix_MX |131.70Mb
  server: 216.238.87.47
  type: vmess
  country: ğŸ‡²ğŸ‡½MX
  port: 27502
  uuid: b8155ce4-7e08-4c40-800f-8671312b7124
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: netflix_NL |141.31Mb
  server: 82.38.31.217
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: disney_KR |11.51Mb
  server: 49.128.204.85
  type: vmess
  country: ğŸ‡°ğŸ‡·KR
  port: 16629
  uuid: 2c78877c-6472-45da-ae89-9b9d6e3ec5e6
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
  ws-opts:
    path: /sfgjmero45
- name: disney_netflix_US |19.57Mb
  server: cf.fovi.tk
  type: vmess
  country: ğŸZZ
  port: 443
  uuid: bf67437e-6c90-45ca-abc2-c7240a5ce2aa
  alterId: 0
  cipher: auto
  network: ws
  servername: foxpol.fovi.tk
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /eisasqa
    headers:
      HOST: foxpol.fovi.tk
- name: Relay_-ğŸ‡¨ğŸ‡­CH_200 |70.50Mb
  server: lt.fxlcn.com
  type: vmess
  port: 45288
  uuid: 469e0b31-30c3-4dab-800d-711232634ce1
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _195 |15.06Mb
  server: 38.180.16.86
  type: vmess
  port: 38039
  uuid: 244a3464-1269-43b3-b491-4dc2713eb3f6
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - disney_netflix_US |42.02Mb
  - disney_netflix_US |40.32Mb
  - disney_netflix_US |137.30Mb
  - disney_CH |71.61Mb
  - netflix_SE |163.52Mb
  - netflix_SE |161.06Mb
  - netflix_SE |154.30Mb
  - disney_netflix_US |36.71Mb
  - _155 |146.97Mb
  - disney_netflix_US |44.19Mb
  - _156 |13.80Mb
  - _178 |23.11Mb
  - disney_netflix_GB |179.85Mb
  - _192 |10.59Mb
  - _201 |15.81Mb
  - _184 |42.30Mb
  - _208 |10.21Mb
  - _209 |18.66Mb
  - _215 |10.90Mb
  - _206 |10.25Mb
  - Pool__217 |181.91Mb
  - netflix_NL |122.34Mb
  - _218 |11.22Mb
  - netflix_IT |167.41Mb
  - ğŸ‡¬ğŸ‡§GB_240 |184.35Mb
  - netflix_MX |131.70Mb
  - netflix_NL |141.31Mb
  - disney_KR |11.51Mb
  - disney_netflix_US |19.57Mb
  - Relay_-ğŸ‡¨ğŸ‡­CH_200 |70.50Mb
  - _195 |15.06Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - disney_netflix_US |42.02Mb
  - disney_netflix_US |40.32Mb
  - disney_netflix_US |137.30Mb
  - disney_CH |71.61Mb
  - netflix_SE |163.52Mb
  - netflix_SE |161.06Mb
  - netflix_SE |154.30Mb
  - disney_netflix_US |36.71Mb
  - _155 |146.97Mb
  - disney_netflix_US |44.19Mb
  - _156 |13.80Mb
  - _178 |23.11Mb
  - disney_netflix_GB |179.85Mb
  - _192 |10.59Mb
  - _201 |15.81Mb
  - _184 |42.30Mb
  - _208 |10.21Mb
  - _209 |18.66Mb
  - _215 |10.90Mb
  - _206 |10.25Mb
  - Pool__217 |181.91Mb
  - netflix_NL |122.34Mb
  - _218 |11.22Mb
  - netflix_IT |167.41Mb
  - ğŸ‡¬ğŸ‡§GB_240 |184.35Mb
  - netflix_MX |131.70Mb
  - netflix_NL |141.31Mb
  - disney_KR |11.51Mb
  - disney_netflix_US |19.57Mb
  - Relay_-ğŸ‡¨ğŸ‡­CH_200 |70.50Mb
  - _195 |15.06Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
