port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: disney_netflix_US |54.21Mb
  server: 13.222.155.147
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: disney_netflix_US |50.26Mb
  server: 23.22.182.151
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: _165 |61.56Mb
  server: 54.144.64.227
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: disney_netflix_US |60.97Mb
  server: 184.72.124.41
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: _170 |57.62Mb
  server: 54.227.38.247
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: disney_netflix_US |55.24Mb
  server: 54.91.94.165
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: _148 |60.45Mb
  server: 98.89.32.62
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: disney_netflix_US |67.06Mb
  server: 98.81.59.20
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: _166 |52.33Mb
  server: 54.159.62.233
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: disney_netflix_US |61.77Mb
  server: 3.93.196.82
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: _174 |59.50Mb
  server: 3.89.113.22
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: _160 |195.88Mb
  server: 3.250.105.240
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: netflix_IE |153.09Mb
  server: 54.246.35.116
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: netflix_IE |154.62Mb
  server: 3.253.99.197
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: netflix_IE |149.58Mb
  server: 34.251.86.159
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: _156 |137.87Mb
  server: 13.61.13.231
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: disney_US |40.23Mb
  server: 165.140.216.141
  type: vmess
  port: 443
  uuid: e7d72a8d-26f2-4b54-b366-0c43e0bcba7d
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _158 |158.45Mb
  server: 13.61.180.46
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: _173 |157.42Mb
  server: 51.20.125.235
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: _187 |13.11Mb
  server: 209.126.84.189
  type: vmess
  port: 443
  uuid: 2c981164-9b93-4bca-94ff-b78d3f8498d7
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /vmessws
- name: disney_netflix_US |42.36Mb
  server: 163.192.49.195
  type: vmess
  port: 443
  uuid: bcb7c581-3c95-4569-a4e7-918141e91ea3
  alterId: 0
  cipher: auto
  network: http
  http-opts:
    path:
    - /
    headers:
      Host:
      - a.189.cn
  h2-opts: {}
- name: _199 |31.17Mb
  server: 216.238.86.158
  type: vmess
  port: 34460
  udp: true
  uuid: 90be214d-048c-4ea2-a602-b8e4d4e51e36
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: disney_netflix_US |34.36Mb
  server: 192.204.47.79
  type: vmess
  port: 42277
  udp: true
  uuid: aee61b21-e85a-484b-f203-b245f1451cff
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: disney_netflix_DE |269.81Mb
  server: 85.195.101.122
  type: vmess
  port: 40878
  uuid: f3d4167e-b15e-4e46-82e9-9286ef93fda7
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _172 |49.41Mb
  server: 185.231.233.112
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: _178 |15.85Mb
  server: 8.218.105.196
  type: vmess
  port: 52752
  uuid: 925bdbf5-72be-4437-bebf-441c61089f6b
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _208 |23.10Mb
  server: 160.16.63.16
  type: trojan
  port: 4054
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: _211 |36.17Mb
  server: 153.121.39.240
  type: trojan
  port: 4054
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: _198 |10.63Mb
  server: 130.162.152.253
  type: vmess
  port: 56867
  uuid: 5206bb9f-2cbc-44ac-de2a-471439a23707
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: disney_SG |17.94Mb
  server: 165.154.195.38
  type: vmess
  port: 35034
  uuid: 959a8caf-4cea-43d0-a548-3628e7ddfafc
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: disney_GB |266.12Mb
  server: 172.67.134.185
  type: trojan
  port: 443
  udp: true
  password: POORIARED
  sni: reDfRee8.REDFree8.ir
  ws-opts:
    path: /eyJqdW5rIjoiVUl6eXhLZkkwUTJ3ZzkiLCJwcm90b2NvbCI6InRyIiwibW9kZSI6InByb3h5aXAiLCJwYW5lbElQcyI6W119?ed=2560
    headers:
      Host: reDfRee8.REDFree8.ir
  network: ws
- name: _213 |22.45Mb
  server: 160.16.196.59
  type: trojan
  port: 2890
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: _214 |48.32Mb
  server: 160.16.124.55
  type: trojan
  port: 2890
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: _215 |20.32Mb
  server: 160.16.151.196
  type: trojan
  port: 4054
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: _191 |40.45Mb
  server: 89.31.120.192
  type: vmess
  port: 443
  uuid: 44537595-9ccc-4b83-8936-5f9ad3229019
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _216 |17.56Mb
  server: 202.181.103.235
  type: trojan
  port: 2890
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: _217 |46.32Mb
  server: 153.121.51.29
  type: trojan
  port: 2890
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: _225 |106.18Mb
  server: 38.96.254.102
  type: trojan
  port: 18509
  password: .ie4rghJuMkcf0oF
  sni: shoppingmall.electricbanana.click
- name: Pool__220 |174.48Mb
  server: 70.34.218.149
  type: trojan
  port: 11930
  password: BaeSzHdfJIR13l67
  sni: softpillow.silentrocket.click
- name: ğŸ‡ªğŸ‡¸ES_232 |187.06Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 40433
  uuid: d8fd8955-78db-49ba-d86f-3e4729f6ac4d
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: _219 |43.01Mb
  server: 160.16.236.32
  type: trojan
  port: 4054
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: ğŸ‡ªğŸ‡¸ES_233 |164.15Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 27092
  uuid: a0596ba6-72a3-4366-8992-77088da65bd8
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_-ğŸ‡¯ğŸ‡µJP_221 |14.29Mb
  server: 153.121.67.215
  type: trojan
  port: 1331
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: ğŸ‡¬ğŸ‡§GB_238 |245.58Mb
  server: 82.38.31.194
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: _229 |12.48Mb
  server: 153.121.65.107
  type: trojan
  port: 3093
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: ğŸ‡¬ğŸ‡§GB_239 |220.01Mb
  server: 82.38.31.191
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_251 |24.69Mb
  server: 47.253.197.26
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 12056
  uuid: dd7be7f1-38ff-45e6-f1e5-b20c2190f527
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡®ğŸ‡ªIE_245 |187.01Mb
  server: 52.50.200.2
  type: ss
  country: ğŸ‡®ğŸ‡ªIE
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡²ğŸ‡½MX_247 |37.81Mb
  server: 216.238.87.47
  type: vmess
  country: ğŸ‡²ğŸ‡½MX
  port: 27502
  uuid: b8155ce4-7e08-4c40-800f-8671312b7124
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: _224 |20.66Mb
  server: 219.78.209.224
  type: trojan
  port: 443
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: disney_KZ |16.35Mb
  server: 31.3.209.183
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 28212
  password: Kmn7dHPw5wNfkqQMPcGWQA
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_250 |75.77Mb
  server: 45.12.136.170
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: l668XHPejoSNNuD66BYzyehaCpZexiF7
  cipher: chacha20-ietf-poly1305
- name: disney_HK |16.76Mb
  server: 45.207.157.29
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 13852
  uuid: 845764df-ecb3-4b13-bed2-bf1551b68e9a
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_KR |13.71Mb
  server: 49.128.204.85
  type: vmess
  country: ğŸ‡°ğŸ‡·KR
  port: 16629
  uuid: 2c78877c-6472-45da-ae89-9b9d6e3ec5e6
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
  ws-opts:
    path: /sfgjmero45
- name: Relay_ğŸ‡©ğŸ‡ªDE-ğŸ‡©ğŸ‡ªDE_231 |203.10Mb
  server: cpanel.navar1.ir
  type: vmess
  country: ğŸ‡©ğŸ‡ªDE
  port: 100
  uuid: 95c6f6f0-84f7-4443-8a50-a59f8e66f5ee
  alterId: 0
  cipher: auto
  network: tcp
  servername: cpanel.navar1.ir
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_US |18.63Mb
  server: cf.fovi.tk
  type: vmess
  country: ğŸZZ
  port: 443
  uuid: bf67437e-6c90-45ca-abc2-c7240a5ce2aa
  alterId: 0
  cipher: auto
  network: ws
  servername: foxpol.fovi.tk
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /eisasqa
    headers:
      HOST: foxpol.fovi.tk
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - disney_netflix_US |54.21Mb
  - disney_netflix_US |50.26Mb
  - _165 |61.56Mb
  - disney_netflix_US |60.97Mb
  - _170 |57.62Mb
  - disney_netflix_US |55.24Mb
  - _148 |60.45Mb
  - disney_netflix_US |67.06Mb
  - _166 |52.33Mb
  - disney_netflix_US |61.77Mb
  - _174 |59.50Mb
  - _160 |195.88Mb
  - netflix_IE |153.09Mb
  - netflix_IE |154.62Mb
  - netflix_IE |149.58Mb
  - _156 |137.87Mb
  - disney_US |40.23Mb
  - _158 |158.45Mb
  - _173 |157.42Mb
  - _187 |13.11Mb
  - disney_netflix_US |42.36Mb
  - _199 |31.17Mb
  - disney_netflix_US |34.36Mb
  - disney_netflix_DE |269.81Mb
  - _172 |49.41Mb
  - _178 |15.85Mb
  - _208 |23.10Mb
  - _211 |36.17Mb
  - _198 |10.63Mb
  - disney_SG |17.94Mb
  - disney_GB |266.12Mb
  - _213 |22.45Mb
  - _214 |48.32Mb
  - _215 |20.32Mb
  - _191 |40.45Mb
  - _216 |17.56Mb
  - _217 |46.32Mb
  - _225 |106.18Mb
  - Pool__220 |174.48Mb
  - ğŸ‡ªğŸ‡¸ES_232 |187.06Mb
  - _219 |43.01Mb
  - ğŸ‡ªğŸ‡¸ES_233 |164.15Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_221 |14.29Mb
  - ğŸ‡¬ğŸ‡§GB_238 |245.58Mb
  - _229 |12.48Mb
  - ğŸ‡¬ğŸ‡§GB_239 |220.01Mb
  - ğŸ‡ºğŸ‡¸US_251 |24.69Mb
  - ğŸ‡®ğŸ‡ªIE_245 |187.01Mb
  - ğŸ‡²ğŸ‡½MX_247 |37.81Mb
  - _224 |20.66Mb
  - disney_KZ |16.35Mb
  - ğŸ‡ºğŸ‡¸US_250 |75.77Mb
  - disney_HK |16.76Mb
  - disney_KR |13.71Mb
  - Relay_ğŸ‡©ğŸ‡ªDE-ğŸ‡©ğŸ‡ªDE_231 |203.10Mb
  - disney_netflix_US |18.63Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - disney_netflix_US |54.21Mb
  - disney_netflix_US |50.26Mb
  - _165 |61.56Mb
  - disney_netflix_US |60.97Mb
  - _170 |57.62Mb
  - disney_netflix_US |55.24Mb
  - _148 |60.45Mb
  - disney_netflix_US |67.06Mb
  - _166 |52.33Mb
  - disney_netflix_US |61.77Mb
  - _174 |59.50Mb
  - _160 |195.88Mb
  - netflix_IE |153.09Mb
  - netflix_IE |154.62Mb
  - netflix_IE |149.58Mb
  - _156 |137.87Mb
  - disney_US |40.23Mb
  - _158 |158.45Mb
  - _173 |157.42Mb
  - _187 |13.11Mb
  - disney_netflix_US |42.36Mb
  - _199 |31.17Mb
  - disney_netflix_US |34.36Mb
  - disney_netflix_DE |269.81Mb
  - _172 |49.41Mb
  - _178 |15.85Mb
  - _208 |23.10Mb
  - _211 |36.17Mb
  - _198 |10.63Mb
  - disney_SG |17.94Mb
  - disney_GB |266.12Mb
  - _213 |22.45Mb
  - _214 |48.32Mb
  - _215 |20.32Mb
  - _191 |40.45Mb
  - _216 |17.56Mb
  - _217 |46.32Mb
  - _225 |106.18Mb
  - Pool__220 |174.48Mb
  - ğŸ‡ªğŸ‡¸ES_232 |187.06Mb
  - _219 |43.01Mb
  - ğŸ‡ªğŸ‡¸ES_233 |164.15Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_221 |14.29Mb
  - ğŸ‡¬ğŸ‡§GB_238 |245.58Mb
  - _229 |12.48Mb
  - ğŸ‡¬ğŸ‡§GB_239 |220.01Mb
  - ğŸ‡ºğŸ‡¸US_251 |24.69Mb
  - ğŸ‡®ğŸ‡ªIE_245 |187.01Mb
  - ğŸ‡²ğŸ‡½MX_247 |37.81Mb
  - _224 |20.66Mb
  - disney_KZ |16.35Mb
  - ğŸ‡ºğŸ‡¸US_250 |75.77Mb
  - disney_HK |16.76Mb
  - disney_KR |13.71Mb
  - Relay_ğŸ‡©ğŸ‡ªDE-ğŸ‡©ğŸ‡ªDE_231 |203.10Mb
  - disney_netflix_US |18.63Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
