port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: ğŸ‡¨ğŸ‡¦CA_30 |16.34Mb
  server: 138.197.153.10
  type: ss
  country: ğŸ‡¨ğŸ‡¦CA
  port: 8080
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: _26 |38.15Mb
  server: 62.100.205.100
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: disney_GB |20.83Mb
  server: 89.185.84.185
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: tVBUTDznmHpV3lpKzbw2Nl
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡©ğŸ‡ªDE_52 |13.25Mb
  server: 3.79.57.79
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: disney_GB |19.17Mb
  server: 89.185.84.185
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: FXjMQIem0uShGvRzOpfyib
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡©ğŸ‡ªDE_45 |189.47Mb
  server: 81.19.141.45
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 443
  password: rC23nT4eVDHF06wmuyvSUe
  cipher: chacha20-ietf-poly1305
- name: disney_DE |25.28Mb
  server: 81.19.141.45
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 443
  password: ql8iN6ChurUrd25DoZJA0n
  cipher: chacha20-ietf-poly1305
- name: _25 |12.73Mb
  server: 185.237.185.89
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: disney_GB |10.05Mb
  server: 89.185.84.185
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: ozSHXLRuO7JckCvhgLjLaU
  cipher: chacha20-ietf-poly1305
- name: disney_GB |20.44Mb
  server: 89.185.84.185
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: iEc68ruj1qOx8hjh1KWZmc
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_87 |36.66Mb
  server: 18.135.29.154
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡¬ğŸ‡§GB_88 |47.38Mb
  server: 18.169.158.38
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: disney_GB |54.28Mb
  server: 89.185.84.185
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: WhUYn0yZ6bLrILxzItfxSI
  cipher: chacha20-ietf-poly1305
- name: disney_GB |53.98Mb
  server: 89.185.84.185
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: B2ISJ3faDXlkRUXUeQu182
  cipher: chacha20-ietf-poly1305
- name: disney_GB |10.03Mb
  server: 89.185.84.185
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: m8V5Orkxu2ob8LH24OFobn
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_94 |36.63Mb
  server: 3.8.172.214
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡¬ğŸ‡§GB_95 |146.36Mb
  server: 78.129.140.11
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: DpBNt4YF9cIcVnWOcJqRgy
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¯ğŸ‡µJP_112 |22.35Mb
  server: 45.32.45.45
  type: vmess
  country: ğŸ‡¯ğŸ‡µJP
  port: 14760
  uuid: dbf7a6e4-d518-4f9b-a55e-27ef892ffac1
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡±ğŸ‡¹LT_114 |24.05Mb
  server: 45.87.175.28
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡®ğŸ‡¹IT_110 |10.23Mb
  server: 158.180.233.56
  type: ss
  country: ğŸ‡®ğŸ‡¹IT
  port: 23846
  password: 0MyacWbQXyGDI7939r4pgtrR5JlfsJIlxkWcPMxpMoo=
  cipher: aes-256-gcm
- name: ğŸ‡±ğŸ‡¹LT_116 |10.13Mb
  server: 45.87.175.171
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: 1RWwXhwfAB5gAEozU4G2Pg
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_118 |12.05Mb
  server: 45.87.175.188
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡³ğŸ‡±NL_123 |15.95Mb
  server: 193.29.139.199
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 8080
  password: QCXDxuDlTTMD7jtgHUjIoj
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡³ğŸ‡±NL_125 |11.77Mb
  server: 193.29.139.177
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 8080
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_176 |10.44Mb
  server: 3.141.46.88
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡ºğŸ‡¸US_177 |10.23Mb
  server: 3.145.46.227
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡ºğŸ‡¸US_184 |19.30Mb
  server: 38.91.102.40
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 5003
  password: g5MeD6Ft3CWlJId
  cipher: aes-256-gcm
- name: ğŸ‡ºğŸ‡¸US_180 |16.85Mb
  server: 3.135.220.55
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡µğŸ‡±PL_126 |11.54Mb
  server: 217.30.10.70
  type: ss
  country: ğŸ‡µğŸ‡±PL
  port: 9003
  password: JdmRK9gMEqFgs8nP
  cipher: aes-256-cfb
- name: Relay_-ğŸ‡ºğŸ‡¸US_28 |10.02Mb
  server: since2023.google.org.kg
  type: trojan
  port: 24455
  udp: true
  password: BJTvoSPr2p
  sni: www.apple.com
  skip-cert-verify: true
  ws-opts:
    path: /abc
    headers:
      Host: www.apple.com
  network: ws
- name: disney_US |813.45Mb
  server: 154.29.158.139
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 12299
  uuid: cccfe679-fbd0-4402-caf2-67e919db436f
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡µğŸ‡±PL_144 |11.77Mb
  server: 217.30.10.70
  type: ss
  country: ğŸ‡µğŸ‡±PL
  port: 9037
  password: TN2YqghxeFDKZfLU
  cipher: aes-256-cfb
- name: ğŸ‡ºğŸ‡¸US_189 |21.18Mb
  server: 3.137.215.129
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡ºğŸ‡¸US_191 |15.14Mb
  server: 18.224.70.173
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡ºğŸ‡¸US_197 |37.95Mb
  server: 13.59.110.241
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: disney_PY |35.05Mb
  server: 38.165.233.18
  type: ss
  country: ğŸ‡µğŸ‡¾PY
  port: 990
  password: f8f7aCzcPKbsF8p3
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¸ğŸ‡¬SG_164 |12.85Mb
  server: 68.183.227.4
  type: ss
  country: ğŸ‡¸ğŸ‡¬SG
  port: 8080
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡³ğŸ‡±NL_185 |18.59Mb
  server: 45.158.171.70
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 8080
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: Pool_ğŸ‡­ğŸ‡°HK_101 |183.00Mb
  server: 150.107.46.21
  type: ssr
  country: ğŸ‡­ğŸ‡°HK
  port: 8083
  password: iFqnzSscN
  cipher: aes-256-cfb
  protocol: origin
  obfs: tls1.2_ticket_auth
- name: disney_DE |56.25Mb
  server: 81.19.141.45
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 443
  password: EEIh3YZZ5QZRvJM6C04YSM
  cipher: chacha20-ietf-poly1305
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - ğŸ‡¨ğŸ‡¦CA_30 |16.34Mb
  - _26 |38.15Mb
  - disney_GB |20.83Mb
  - ğŸ‡©ğŸ‡ªDE_52 |13.25Mb
  - disney_GB |19.17Mb
  - ğŸ‡©ğŸ‡ªDE_45 |189.47Mb
  - disney_DE |25.28Mb
  - _25 |12.73Mb
  - disney_GB |10.05Mb
  - disney_GB |20.44Mb
  - ğŸ‡¬ğŸ‡§GB_87 |36.66Mb
  - ğŸ‡¬ğŸ‡§GB_88 |47.38Mb
  - disney_GB |54.28Mb
  - disney_GB |53.98Mb
  - disney_GB |10.03Mb
  - ğŸ‡¬ğŸ‡§GB_94 |36.63Mb
  - ğŸ‡¬ğŸ‡§GB_95 |146.36Mb
  - ğŸ‡¯ğŸ‡µJP_112 |22.35Mb
  - ğŸ‡±ğŸ‡¹LT_114 |24.05Mb
  - ğŸ‡®ğŸ‡¹IT_110 |10.23Mb
  - ğŸ‡±ğŸ‡¹LT_116 |10.13Mb
  - ğŸ‡±ğŸ‡¹LT_118 |12.05Mb
  - ğŸ‡³ğŸ‡±NL_123 |15.95Mb
  - ğŸ‡³ğŸ‡±NL_125 |11.77Mb
  - ğŸ‡ºğŸ‡¸US_176 |10.44Mb
  - ğŸ‡ºğŸ‡¸US_177 |10.23Mb
  - ğŸ‡ºğŸ‡¸US_184 |19.30Mb
  - ğŸ‡ºğŸ‡¸US_180 |16.85Mb
  - ğŸ‡µğŸ‡±PL_126 |11.54Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_28 |10.02Mb
  - disney_US |813.45Mb
  - ğŸ‡µğŸ‡±PL_144 |11.77Mb
  - ğŸ‡ºğŸ‡¸US_189 |21.18Mb
  - ğŸ‡ºğŸ‡¸US_191 |15.14Mb
  - ğŸ‡ºğŸ‡¸US_197 |37.95Mb
  - disney_PY |35.05Mb
  - ğŸ‡¸ğŸ‡¬SG_164 |12.85Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡³ğŸ‡±NL_185 |18.59Mb
  - Pool_ğŸ‡­ğŸ‡°HK_101 |183.00Mb
  - disney_DE |56.25Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - ğŸ‡¨ğŸ‡¦CA_30 |16.34Mb
  - _26 |38.15Mb
  - disney_GB |20.83Mb
  - ğŸ‡©ğŸ‡ªDE_52 |13.25Mb
  - disney_GB |19.17Mb
  - ğŸ‡©ğŸ‡ªDE_45 |189.47Mb
  - disney_DE |25.28Mb
  - _25 |12.73Mb
  - disney_GB |10.05Mb
  - disney_GB |20.44Mb
  - ğŸ‡¬ğŸ‡§GB_87 |36.66Mb
  - ğŸ‡¬ğŸ‡§GB_88 |47.38Mb
  - disney_GB |54.28Mb
  - disney_GB |53.98Mb
  - disney_GB |10.03Mb
  - ğŸ‡¬ğŸ‡§GB_94 |36.63Mb
  - ğŸ‡¬ğŸ‡§GB_95 |146.36Mb
  - ğŸ‡¯ğŸ‡µJP_112 |22.35Mb
  - ğŸ‡±ğŸ‡¹LT_114 |24.05Mb
  - ğŸ‡®ğŸ‡¹IT_110 |10.23Mb
  - ğŸ‡±ğŸ‡¹LT_116 |10.13Mb
  - ğŸ‡±ğŸ‡¹LT_118 |12.05Mb
  - ğŸ‡³ğŸ‡±NL_123 |15.95Mb
  - ğŸ‡³ğŸ‡±NL_125 |11.77Mb
  - ğŸ‡ºğŸ‡¸US_176 |10.44Mb
  - ğŸ‡ºğŸ‡¸US_177 |10.23Mb
  - ğŸ‡ºğŸ‡¸US_184 |19.30Mb
  - ğŸ‡ºğŸ‡¸US_180 |16.85Mb
  - ğŸ‡µğŸ‡±PL_126 |11.54Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_28 |10.02Mb
  - disney_US |813.45Mb
  - ğŸ‡µğŸ‡±PL_144 |11.77Mb
  - ğŸ‡ºğŸ‡¸US_189 |21.18Mb
  - ğŸ‡ºğŸ‡¸US_191 |15.14Mb
  - ğŸ‡ºğŸ‡¸US_197 |37.95Mb
  - disney_PY |35.05Mb
  - ğŸ‡¸ğŸ‡¬SG_164 |12.85Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡³ğŸ‡±NL_185 |18.59Mb
  - Pool_ğŸ‡­ğŸ‡°HK_101 |183.00Mb
  - disney_DE |56.25Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
