port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: disney_netflix_NL |227.62Mb
  server: 151.242.251.137
  type: ss
  port: 8080
  password: o5osZg269v5zHpYjr1xY9s
  cipher: chacha20-ietf-poly1305
- name: Relay_-ğŸ‡¸ğŸ‡¬SG_424 |11.29Mb
  server: 153.121.51.29
  type: trojan
  port: 127
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: disney_netflix_PT |12.32Mb
  server: 185.231.233.112
  type: ss
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: Relay_-ğŸ‡¯ğŸ‡µJP_429 |15.73Mb
  server: 52.195.176.26
  type: trojan
  port: 2145
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: disney_netflix_US |43.10Mb
  server: 160.16.63.16
  type: trojan
  port: 4054
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: ğŸ‡¦ğŸ‡ºAU_434 |10.77Mb
  server: 54.252.240.128
  type: vmess
  country: ğŸ‡¦ğŸ‡ºAU
  port: 1000
  uuid: ca26a9fd-fef8-4ea7-d194-450ce4e0c67a
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_FR |161.88Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 27092
  uuid: a0596ba6-72a3-4366-8992-77088da65bd8
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: _327 |16.08Mb
  server: 103.106.3.82
  type: ss
  port: 443
  udp: true
  password: 4SaCIazlgumYkM8FkPzlmwjpyWBDZFBk
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_FR |161.16Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 40433
  uuid: d8fd8955-78db-49ba-d86f-3e4729f6ac4d
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: netflix_MX |30.22Mb
  server: 216.238.89.53
  type: vmess
  country: ğŸ‡²ğŸ‡½MX
  port: 57283
  uuid: 1a5aafc0-6482-451d-fe76-6875b7818579
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_HK |22.42Mb
  server: 112.118.116.66
  type: trojan
  port: 443
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: disney_netflix_US |19.78Mb
  server: 38.84.201.21
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 53487
  uuid: c3c1ec05-df2c-4975-9b42-e9b007564eb1
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_NL |168.21Mb
  server: 82.38.31.190
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡§ğŸ‡·BR_435 |18.96Mb
  server: 38.180.16.86
  type: vmess
  country: ğŸ‡§ğŸ‡·BR
  port: 36104
  uuid: E146A8CB-9D2F-449C-ADCA-8736FB
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: netflix_AL |23.44Mb
  server: 87.121.162.249
  type: ss
  country: ğŸ‡­ğŸ‡°HK
  port: 443
  password: JGv616hMWdjfuZ00jYfq7XkBHJZrOBrg
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_469 |19.81Mb
  server: 45.136.12.37
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 38141
  uuid: fd291be6-b48d-43a1-da38-66c7f80e2f80
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡²ğŸ‡¾MY_466 |30.48Mb
  server: 38.54.98.110
  type: vmess
  country: ğŸ‡²ğŸ‡¾MY
  port: 2052
  uuid: 665d9b8f-153d-4907-adac-de12afd9c851
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: ğŸ‡¸ğŸ‡¬SG_467 |11.15Mb
  server: 68.183.178.131
  type: vmess
  country: ğŸ‡¸ğŸ‡¬SG
  port: 58607
  uuid: c11c32cb-27b3-4afa-c0f3-fb250aa4959e
  alterId: 0
  cipher: auto
  network: ws
  servername: www.12333.monster
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /
    headers:
      HOST: www.12333.monster
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - disney_netflix_NL |227.62Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_424 |11.29Mb
  - disney_netflix_PT |12.32Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_429 |15.73Mb
  - disney_netflix_US |43.10Mb
  - ğŸ‡¦ğŸ‡ºAU_434 |10.77Mb
  - disney_netflix_FR |161.88Mb
  - _327 |16.08Mb
  - disney_netflix_FR |161.16Mb
  - netflix_MX |30.22Mb
  - disney_HK |22.42Mb
  - disney_netflix_US |19.78Mb
  - disney_netflix_NL |168.21Mb
  - ğŸ‡§ğŸ‡·BR_435 |18.96Mb
  - netflix_AL |23.44Mb
  - ğŸ‡ºğŸ‡¸US_469 |19.81Mb
  - ğŸ‡²ğŸ‡¾MY_466 |30.48Mb
  - ğŸ‡¸ğŸ‡¬SG_467 |11.15Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - disney_netflix_NL |227.62Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_424 |11.29Mb
  - disney_netflix_PT |12.32Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_429 |15.73Mb
  - disney_netflix_US |43.10Mb
  - ğŸ‡¦ğŸ‡ºAU_434 |10.77Mb
  - disney_netflix_FR |161.88Mb
  - _327 |16.08Mb
  - disney_netflix_FR |161.16Mb
  - netflix_MX |30.22Mb
  - disney_HK |22.42Mb
  - disney_netflix_US |19.78Mb
  - disney_netflix_NL |168.21Mb
  - ğŸ‡§ğŸ‡·BR_435 |18.96Mb
  - netflix_AL |23.44Mb
  - ğŸ‡ºğŸ‡¸US_469 |19.81Mb
  - ğŸ‡²ğŸ‡¾MY_466 |30.48Mb
  - ğŸ‡¸ğŸ‡¬SG_467 |11.15Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
