port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: disney_netflix_US |23.68Mb
  server: 45.150.52.40
  type: vmess
  port: 443
  uuid: c31777a1-2ee6-4864-db4c-a79fcbc8188b
  alterId: 0
  cipher: auto
  network: ws
  servername: xsj011-3.facai2024.com
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /c31777a1
- name: netflix_DE |206.18Mb
  server: 43.165.7.71
  type: vmess
  port: 19751
  uuid: 6cfa6103-5d06-40cb-f452-b563db578288
  alterId: 0
  cipher: auto
  network: http
  http-opts:
    method: GET
    path:
    - /
  h2-opts: {}
- name: disney_netflix_HK |21.10Mb
  server: 8.218.105.196
  type: vmess
  port: 52752
  uuid: 925bdbf5-72be-4437-bebf-441c61089f6b
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
- name: disney_netflix_HK |16.83Mb
  server: 47.242.145.160
  type: vmess
  port: 44457
  uuid: 40290609-2743-4d85-c9c3-4c72dd151b9f
  alterId: 0
  cipher: auto
  network: http
  http-opts:
    method: GET
    path:
    - /
  h2-opts: {}
- name: disney_netflix_US |28.36Mb
  server: 209.74.82.196
  type: ss
  port: 48918
  udp: true
  password: 8Ij4seif85QQHfLmR0zYkQ
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_US |26.48Mb
  server: 209.74.82.227
  type: ss
  port: 26515
  udp: true
  password: uA1rLP5m0mMOQ8FcxRXxgr
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_GB |202.38Mb
  server: koma-yt.pages.dev
  type: trojan
  port: 8443
  udp: true
  password: 8r<[9'l6hAO#8ZQi
  sni: Koma-YT.PAGeS.Dev
  ws-opts:
    path: /tro8sFW1S91B6sZrM1?ed=2560
    headers:
      Host: Koma-YT.PAGeS.Dev
  network: ws
- name: disney_netflix_HK |15.40Mb
  server: 58.152.25.242
  type: trojan
  port: 443
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: Relay_-ðŸ‡¯ðŸ‡µJP_92 |19.98Mb
  server: 160.16.242.183
  type: trojan
  port: 1331
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: Relay_-ðŸ‡¯ðŸ‡µJP_93 |11.74Mb
  server: 153.121.73.102
  type: trojan
  port: 1331
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: disney_netflix_US |11.45Mb
  server: 160.16.214.6
  type: trojan
  port: 2890
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: disney_netflix_US |11.44Mb
  server: 202.181.103.235
  type: trojan
  port: 2890
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: disney_US |420.55Mb
  server: 185.221.23.251
  type: vmess
  country: ðŸ‡ªðŸ‡¸ES
  port: 29431
  uuid: 8b78363e-3c3a-44ab-f0d8-f13d950c8572
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_FR |29.38Mb
  server: 208.76.223.218
  type: vmess
  country: ðŸ‡ªðŸ‡¸ES
  port: 27092
  uuid: a0596ba6-72a3-4366-8992-77088da65bd8
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_HK |18.74Mb
  server: 58.152.30.120
  type: trojan
  port: 443
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: disney_netflix_HK |25.45Mb
  server: 58.152.110.82
  type: trojan
  port: 443
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: disney_netflix_FR |145.15Mb
  server: 208.76.223.218
  type: vmess
  country: ðŸ‡ªðŸ‡¸ES
  port: 40433
  uuid: d8fd8955-78db-49ba-d86f-3e4729f6ac4d
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_NL |162.22Mb
  server: 82.38.31.184
  type: ss
  country: ðŸ‡¬ðŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_NL |408.46Mb
  server: 51.15.17.169
  type: ss
  country: ðŸ‡¬ðŸ‡§GB
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: disney_netflix_US |32.16Mb
  server: 209.74.86.194
  type: ss
  country: ðŸ‡ºðŸ‡¸US
  port: 14936
  password: ppgtoOHdm7cszGunBWBTqQ
  cipher: chacha20-ietf-poly1305
- name: _104 |10.34Mb
  server: 54.179.216.24
  type: trojan
  port: 20230
  udp: true
  password: 8c92b985-02fc-4bc1-8cd7-a12e5aae243b
  sni: www.alibaba.com
  skip-cert-verify: true
  ws-opts:
    path: /
    headers:
      Host: www.alibaba.com
  network: ws
- name: netflix_IE |268.01Mb
  server: 146.70.90.196
  type: ss
  country: ðŸ‡®ðŸ‡ªIE
  port: 17454
  password: u8gp148iz90ddoo6ms37
  cipher: aes-128-gcm
- name: disney_netflix_HK |22.13Mb
  server: 8.218.116.26
  type: vmess
  country: ðŸ‡­ðŸ‡°HK
  port: 32228
  uuid: e4767e9f-ed00-4f31-a984-a918bdd9b09c
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_NL |48.89Mb
  server: 109.71.246.210
  type: ss
  country: ðŸ‡·ðŸ‡ºRU
  port: 56689
  password: YQCSKoCF3QazW8YlvDBWA4
  cipher: chacha20-ietf-poly1305
- name: ðŸ‡¬ðŸ‡§GB_112 |32.98Mb
  server: 195.66.27.148
  type: ss
  country: ðŸ‡¬ðŸ‡§GB
  port: 28709
  password: hShp1Km0NcFSmSigc8ozky
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_US |20.33Mb
  server: 209.74.81.149
  type: ss
  country: ðŸ‡ºðŸ‡¸US
  port: 21166
  password: q92MrrP9oJ3lMEzbQFpyuU
  cipher: chacha20-ietf-poly1305
- name: ðŸ‡·ðŸ‡ºRU_159 |12.99Mb
  server: 81.200.158.206
  type: ss
  country: ðŸ‡·ðŸ‡ºRU
  port: 1080
  password: AqZbt1QCs3ngEfXo1p7T-w
  cipher: chacha20-ietf-poly1305
proxy-groups:
- name: ðŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - disney_netflix_US |23.68Mb
  - netflix_DE |206.18Mb
  - disney_netflix_HK |21.10Mb
  - disney_netflix_HK |16.83Mb
  - disney_netflix_US |28.36Mb
  - disney_netflix_US |26.48Mb
  - disney_netflix_GB |202.38Mb
  - disney_netflix_HK |15.40Mb
  - Relay_-ðŸ‡¯ðŸ‡µJP_92 |19.98Mb
  - Relay_-ðŸ‡¯ðŸ‡µJP_93 |11.74Mb
  - disney_netflix_US |11.45Mb
  - disney_netflix_US |11.44Mb
  - disney_US |420.55Mb
  - disney_netflix_FR |29.38Mb
  - disney_netflix_HK |18.74Mb
  - disney_netflix_HK |25.45Mb
  - disney_netflix_FR |145.15Mb
  - disney_netflix_NL |162.22Mb
  - disney_netflix_NL |408.46Mb
  - disney_netflix_US |32.16Mb
  - _104 |10.34Mb
  - netflix_IE |268.01Mb
  - disney_netflix_HK |22.13Mb
  - disney_netflix_NL |48.89Mb
  - ðŸ‡¬ðŸ‡§GB_112 |32.98Mb
  - disney_netflix_US |20.33Mb
  - ðŸ‡·ðŸ‡ºRU_159 |12.99Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - disney_netflix_US |23.68Mb
  - netflix_DE |206.18Mb
  - disney_netflix_HK |21.10Mb
  - disney_netflix_HK |16.83Mb
  - disney_netflix_US |28.36Mb
  - disney_netflix_US |26.48Mb
  - disney_netflix_GB |202.38Mb
  - disney_netflix_HK |15.40Mb
  - Relay_-ðŸ‡¯ðŸ‡µJP_92 |19.98Mb
  - Relay_-ðŸ‡¯ðŸ‡µJP_93 |11.74Mb
  - disney_netflix_US |11.45Mb
  - disney_netflix_US |11.44Mb
  - disney_US |420.55Mb
  - disney_netflix_FR |29.38Mb
  - disney_netflix_HK |18.74Mb
  - disney_netflix_HK |25.45Mb
  - disney_netflix_FR |145.15Mb
  - disney_netflix_NL |162.22Mb
  - disney_netflix_NL |408.46Mb
  - disney_netflix_US |32.16Mb
  - _104 |10.34Mb
  - netflix_IE |268.01Mb
  - disney_netflix_HK |22.13Mb
  - disney_netflix_NL |48.89Mb
  - ðŸ‡¬ðŸ‡§GB_112 |32.98Mb
  - disney_netflix_US |20.33Mb
  - ðŸ‡·ðŸ‡ºRU_159 |12.99Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ðŸš€ èŠ‚ç‚¹é€‰æ‹©
