port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: _171 |52.75Mb
  server: 66.23.207.82
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _174 |28.34Mb
  server: 173.234.29.2
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¨ğŸ‡¦CA_210 |10.59Mb
  server: 138.197.153.10
  type: ss
  country: ğŸ‡¨ğŸ‡¦CA
  port: 8080
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: ğŸ‡¨ğŸ‡¦CA_209 |141.71Mb
  server: 138.197.165.21
  type: ss
  country: ğŸ‡¨ğŸ‡¦CA
  port: 8080
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: ğŸ‡¨ğŸ‡¦CA_208 |10.62Mb
  server: 147.182.146.81
  type: ss
  country: ğŸ‡¨ğŸ‡¦CA
  port: 8080
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: ğŸ‡¨ğŸ‡¦CA_211 |412.68Mb
  server: 68.183.193.204
  type: ss
  country: ğŸ‡¨ğŸ‡¦CA
  port: 8080
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: ğŸ‡¨ğŸ‡¦CA_212 |10.71Mb
  server: 147.182.150.107
  type: ss
  country: ğŸ‡¨ğŸ‡¦CA
  port: 8080
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: ğŸ‡¨ğŸ‡¦CA_215 |10.42Mb
  server: 79.127.200.162
  type: ss
  country: ğŸ‡¨ğŸ‡¦CA
  port: 990
  password: f8f7aCzcPKbsF8p3
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸ‡¨ğŸ‡¦CA-ğŸ‡¨ğŸ‡¦CA_216 |10.25Mb
  server: 79.127.200.169
  type: ss
  country: ğŸ‡¨ğŸ‡¦CA
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _175 |10.49Mb
  server: 145.14.131.99
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _180 |50.81Mb
  server: 138.186.142.81
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ªğŸ‡¸ES_302 |33.17Mb
  server: 212.34.140.184
  type: ss
  country: ğŸ‡ªğŸ‡¸ES
  port: 443
  password: 0NeN5ta7FLa5B9DLytU0um
  cipher: chacha20-ietf-poly1305
- name: _176 |62.26Mb
  server: 77.83.246.74
  type: ss
  port: 443
  udp: true
  password: 7115Q0ojojBF7mc2F7KLkN
  cipher: chacha20-ietf-poly1305
- name: Pool_ğŸ‡¬ğŸ‡§GB_348 |10.30Mb
  server: 79.127.233.170
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ğŸ‡©ğŸ‡°DK_282 |10.15Mb
  server: 121.127.45.165
  type: ss
  country: ğŸ‡©ğŸ‡°DK
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡«ğŸ‡·FR_331 |10.36Mb
  server: 57.129.140.88
  type: ss
  country: ğŸ‡«ğŸ‡·FR
  port: 8388
  password: k1v5g9FefdoO
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_346 |136.75Mb
  server: 213.109.147.242
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 62685
  password: VpKABcOpNNA0l5G2AVOmw8
  cipher: chacha20-ietf-poly1305
- name: Pool_ğŸ‡¬ğŸ‡§GB_361 |10.08Mb
  server: 79.127.233.170
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 990
  password: f8f7aCzcPKbsF8p3
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡«ğŸ‡·FR_322 |89.45Mb
  server: 83.147.216.70
  type: ss
  country: ğŸ‡«ğŸ‡·FR
  port: 64519
  password: WmDhVSiDij7R2XROr3Cm55
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_375 |11.03Mb
  server: 89.185.84.185
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: Qqt1DFQEMvj6oJ69n6uf1Z
  cipher: chacha20-ietf-poly1305
- name: Pool_ğŸ‡¬ğŸ‡§GB_367 |10.30Mb
  server: 64.176.184.129
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 1866
  password: oXGp1+ihlfKg826H
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_352 |32.75Mb
  server: 107.181.147.235
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 40521
  password: Z94FoM1xpW3CJzixME8CjJEFBiCFhKSWfLzT6E92Pjh7y73YfNrwPju46Gd4HE85eXSjNiTtiAYc6WTskuhxZZFebd4rcXfp
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸ‡®ğŸ‡·IR-ğŸ‡³ğŸ‡±NL_472 |10.11Mb
  server: 151.242.251.137
  type: ss
  country: ğŸ‡®ğŸ‡·IR
  port: 8080
  password: o5osZg269v5zHpYjr1xY9s
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡®ğŸ‡·IR_479 |10.10Mb
  server: 151.242.251.152
  type: ss
  country: ğŸ‡®ğŸ‡·IR
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_385 |15.27Mb
  server: 146.70.61.37
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: ğŸ‡®ğŸ‡·IR_484 |10.10Mb
  server: 151.242.251.153
  type: ss
  country: ğŸ‡®ğŸ‡·IR
  port: 8080
  password: o5osZg269v5zHpYjr1xY9s
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_523 |14.15Mb
  server: 45.87.175.199
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_529 |10.48Mb
  server: 45.87.175.175
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: QCXDxuDlTTMD7jtgHUjIoj
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_542 |14.58Mb
  server: 45.87.175.171
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¯ğŸ‡µJP_497 |47.83Mb
  server: 194.68.27.76
  type: ss
  country: ğŸ‡¯ğŸ‡µJP
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡³ğŸ‡±NL_561 |10.04Mb
  server: 193.29.139.235
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 8080
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¯ğŸ‡µJP_500 |10.48Mb
  server: 172.105.199.91
  type: ss
  country: ğŸ‡¯ğŸ‡µJP
  port: 8080
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: ğŸ‡³ğŸ‡±NL_564 |10.13Mb
  server: 193.29.139.217
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 8080
  password: QCXDxuDlTTMD7jtgHUjIoj
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡²ğŸ‡°MK_556 |96.30Mb
  server: 46.183.185.37
  type: ss
  country: ğŸ‡²ğŸ‡°MK
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ğŸ‡³ğŸ‡±NL_568 |10.73Mb
  server: 193.29.139.173
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 8080
  password: 4a2rfixophdjffa8KVA4Aa
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡°ğŸ‡·KR_508 |11.35Mb
  server: 154.90.63.177
  type: ss
  country: ğŸ‡°ğŸ‡·KR
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ğŸ‡³ğŸ‡±NL_576 |10.12Mb
  server: 193.29.139.217
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 8080
  password: 4a2rfixophdjffa8KVA4Aa
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡³ğŸ‡±NL_578 |25.21Mb
  server: 193.29.139.143
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 8080
  password: 1RWwXhwfAB5gAEozU4G2Pg
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡®ğŸ‡³IN_447 |107.25Mb
  server: 134.209.147.198
  type: ss
  country: ğŸ‡®ğŸ‡³IN
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ğŸ‡³ğŸ‡±NL_579 |10.12Mb
  server: 193.29.139.160
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 8080
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡µğŸ‡¦PA_594 |43.72Mb
  server: 138.186.142.80
  type: ss
  country: ğŸ‡µğŸ‡¦PA
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡³ğŸ‡±NL_591 |10.03Mb
  server: 79.127.227.53
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ğŸ‡µğŸ‡±PL_628 |13.72Mb
  server: 77.83.246.74
  type: ss
  country: ğŸ‡µğŸ‡±PL
  port: 443
  password: 8IPjdZFX8HGxbhVN9Qw2tB
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡µğŸ‡±PL_634 |37.90Mb
  server: 217.30.10.70
  type: ss
  country: ğŸ‡µğŸ‡±PL
  port: 9060
  password: ueLXVkvh4hckhErQ
  cipher: aes-256-cfb
- name: ğŸ‡µğŸ‡±PL_661 |11.56Mb
  server: 217.30.10.18
  type: ss
  country: ğŸ‡µğŸ‡±PL
  port: 9040
  password: p9z5BVADH2YFs3MN
  cipher: aes-256-cfb
- name: ğŸ‡µğŸ‡±PL_638 |56.76Mb
  server: 77.83.246.74
  type: ss
  country: ğŸ‡µğŸ‡±PL
  port: 443
  password: KwQZX5ziYHI0QHkanEj9iG
  cipher: chacha20-ietf-poly1305
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - _171 |52.75Mb
  - _174 |28.34Mb
  - ğŸ‡¨ğŸ‡¦CA_210 |10.59Mb
  - ğŸ‡¨ğŸ‡¦CA_209 |141.71Mb
  - ğŸ‡¨ğŸ‡¦CA_208 |10.62Mb
  - ğŸ‡¨ğŸ‡¦CA_211 |412.68Mb
  - ğŸ‡¨ğŸ‡¦CA_212 |10.71Mb
  - ğŸ‡¨ğŸ‡¦CA_215 |10.42Mb
  - Relay_ğŸ‡¨ğŸ‡¦CA-ğŸ‡¨ğŸ‡¦CA_216 |10.25Mb
  - _175 |10.49Mb
  - _180 |50.81Mb
  - ğŸ‡ªğŸ‡¸ES_302 |33.17Mb
  - _176 |62.26Mb
  - Pool_ğŸ‡¬ğŸ‡§GB_348 |10.30Mb
  - ğŸ‡©ğŸ‡°DK_282 |10.15Mb
  - ğŸ‡«ğŸ‡·FR_331 |10.36Mb
  - ğŸ‡¬ğŸ‡§GB_346 |136.75Mb
  - Pool_ğŸ‡¬ğŸ‡§GB_361 |10.08Mb
  - ğŸ‡«ğŸ‡·FR_322 |89.45Mb
  - ğŸ‡¬ğŸ‡§GB_375 |11.03Mb
  - Pool_ğŸ‡¬ğŸ‡§GB_367 |10.30Mb
  - ğŸ‡¬ğŸ‡§GB_352 |32.75Mb
  - Relay_ğŸ‡®ğŸ‡·IR-ğŸ‡³ğŸ‡±NL_472 |10.11Mb
  - ğŸ‡®ğŸ‡·IR_479 |10.10Mb
  - ğŸ‡¬ğŸ‡§GB_385 |15.27Mb
  - ğŸ‡®ğŸ‡·IR_484 |10.10Mb
  - ğŸ‡±ğŸ‡¹LT_523 |14.15Mb
  - ğŸ‡±ğŸ‡¹LT_529 |10.48Mb
  - ğŸ‡±ğŸ‡¹LT_542 |14.58Mb
  - ğŸ‡¯ğŸ‡µJP_497 |47.83Mb
  - ğŸ‡³ğŸ‡±NL_561 |10.04Mb
  - ğŸ‡¯ğŸ‡µJP_500 |10.48Mb
  - ğŸ‡³ğŸ‡±NL_564 |10.13Mb
  - ğŸ‡²ğŸ‡°MK_556 |96.30Mb
  - ğŸ‡³ğŸ‡±NL_568 |10.73Mb
  - ğŸ‡°ğŸ‡·KR_508 |11.35Mb
  - ğŸ‡³ğŸ‡±NL_576 |10.12Mb
  - ğŸ‡³ğŸ‡±NL_578 |25.21Mb
  - ğŸ‡®ğŸ‡³IN_447 |107.25Mb
  - ğŸ‡³ğŸ‡±NL_579 |10.12Mb
  - ğŸ‡µğŸ‡¦PA_594 |43.72Mb
  - ğŸ‡³ğŸ‡±NL_591 |10.03Mb
  - ğŸ‡µğŸ‡±PL_628 |13.72Mb
  - ğŸ‡µğŸ‡±PL_634 |37.90Mb
  - ğŸ‡µğŸ‡±PL_661 |11.56Mb
  - ğŸ‡µğŸ‡±PL_638 |56.76Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - _171 |52.75Mb
  - _174 |28.34Mb
  - ğŸ‡¨ğŸ‡¦CA_210 |10.59Mb
  - ğŸ‡¨ğŸ‡¦CA_209 |141.71Mb
  - ğŸ‡¨ğŸ‡¦CA_208 |10.62Mb
  - ğŸ‡¨ğŸ‡¦CA_211 |412.68Mb
  - ğŸ‡¨ğŸ‡¦CA_212 |10.71Mb
  - ğŸ‡¨ğŸ‡¦CA_215 |10.42Mb
  - Relay_ğŸ‡¨ğŸ‡¦CA-ğŸ‡¨ğŸ‡¦CA_216 |10.25Mb
  - _175 |10.49Mb
  - _180 |50.81Mb
  - ğŸ‡ªğŸ‡¸ES_302 |33.17Mb
  - _176 |62.26Mb
  - Pool_ğŸ‡¬ğŸ‡§GB_348 |10.30Mb
  - ğŸ‡©ğŸ‡°DK_282 |10.15Mb
  - ğŸ‡«ğŸ‡·FR_331 |10.36Mb
  - ğŸ‡¬ğŸ‡§GB_346 |136.75Mb
  - Pool_ğŸ‡¬ğŸ‡§GB_361 |10.08Mb
  - ğŸ‡«ğŸ‡·FR_322 |89.45Mb
  - ğŸ‡¬ğŸ‡§GB_375 |11.03Mb
  - Pool_ğŸ‡¬ğŸ‡§GB_367 |10.30Mb
  - ğŸ‡¬ğŸ‡§GB_352 |32.75Mb
  - Relay_ğŸ‡®ğŸ‡·IR-ğŸ‡³ğŸ‡±NL_472 |10.11Mb
  - ğŸ‡®ğŸ‡·IR_479 |10.10Mb
  - ğŸ‡¬ğŸ‡§GB_385 |15.27Mb
  - ğŸ‡®ğŸ‡·IR_484 |10.10Mb
  - ğŸ‡±ğŸ‡¹LT_523 |14.15Mb
  - ğŸ‡±ğŸ‡¹LT_529 |10.48Mb
  - ğŸ‡±ğŸ‡¹LT_542 |14.58Mb
  - ğŸ‡¯ğŸ‡µJP_497 |47.83Mb
  - ğŸ‡³ğŸ‡±NL_561 |10.04Mb
  - ğŸ‡¯ğŸ‡µJP_500 |10.48Mb
  - ğŸ‡³ğŸ‡±NL_564 |10.13Mb
  - ğŸ‡²ğŸ‡°MK_556 |96.30Mb
  - ğŸ‡³ğŸ‡±NL_568 |10.73Mb
  - ğŸ‡°ğŸ‡·KR_508 |11.35Mb
  - ğŸ‡³ğŸ‡±NL_576 |10.12Mb
  - ğŸ‡³ğŸ‡±NL_578 |25.21Mb
  - ğŸ‡®ğŸ‡³IN_447 |107.25Mb
  - ğŸ‡³ğŸ‡±NL_579 |10.12Mb
  - ğŸ‡µğŸ‡¦PA_594 |43.72Mb
  - ğŸ‡³ğŸ‡±NL_591 |10.03Mb
  - ğŸ‡µğŸ‡±PL_628 |13.72Mb
  - ğŸ‡µğŸ‡±PL_634 |37.90Mb
  - ğŸ‡µğŸ‡±PL_661 |11.56Mb
  - ğŸ‡µğŸ‡±PL_638 |56.76Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
