port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: ''
  server: 185.231.233.112
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ''
  server: 18.203.127.31
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: ''
  server: 5.78.51.123
  type: ss
  port: 1080
  password: 8tmnvX5zYuWGVIDP2jglZw
  cipher: chacha20-ietf-poly1305
- name: ''
  server: 195.154.119.77
  type: ss
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ''
  server: 134.209.147.198
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ''
  server: 213.159.66.206
  type: ss
  port: 443
  udp: true
  password: pl2XtR0pzwknQOGwewbwXtPYDw1zn9Vu
  cipher: chacha20-ietf-poly1305
- name: ''
  server: 15.204.247.49
  type: ss
  port: 12000
  password: 8JCsPssfgS8tiRwiMlhARg==
  cipher: aes-256-gcm
- name: ''
  server: 185.247.184.27
  type: ss
  port: 42203
  udp: true
  password: yDAMsX678XsjsESR4UJlAI
  cipher: chacha20-ietf-poly1305
- name: ''
  server: 23.95.72.81
  type: ss
  port: 443
  udp: true
  password: UAMVtHm54uahd6SiN5WcD16rsPSdabPG
  cipher: chacha20-ietf-poly1305
- name: ''
  server: 185.153.197.5
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ''
  server: 213.159.67.124
  type: ss
  port: 443
  udp: true
  password: mbhqsStnFQT1cTZYCdsmkugGUC6GT6rp
  cipher: chacha20-ietf-poly1305
- name: ''
  server: 146.19.49.251
  type: ss
  port: 443
  udp: true
  password: ODfxioK0VkKxTdpVQJ4rv8HglAu0vzv6
  cipher: chacha20-ietf-poly1305
- name: ''
  server: 38.165.233.93
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ''
  server: 23.95.75.146
  type: ss
  port: 443
  udp: true
  password: NDRySIABARbErNIVsCNVkyYAHiBzhveT
  cipher: chacha20-ietf-poly1305
- name: ''
  server: 141.164.45.187
  type: ss
  port: 7001
  password: RexnBgU7EV5ADxG
  cipher: aes-256-gcm
- name: ''
  server: 213.176.16.71
  type: ss
  port: 4966
  udp: true
  password: lXOVjEMsx00jeOQzHsQrkL
  cipher: chacha20-ietf-poly1305
- name: ''
  server: 46.183.184.60
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ''
  server: 103.75.118.125
  type: ss
  port: 443
  udp: true
  password: XLOrvLWkCBBBxLqSEe9S8lnC5PLsNfRh
  cipher: chacha20-ietf-poly1305
- name: ''
  server: 45.14.245.2
  type: ss
  port: 443
  udp: true
  password: 17ZDORWIliQHuO6WRGHChXYMzdRtAYVP
  cipher: chacha20-ietf-poly1305
- name: ''
  server: 74.117.196.232
  type: vmess
  port: 37934
  udp: true
  uuid: f1a513d2-c32a-49dc-8e64-d4f8a2f1e001
  alterId: 0
  cipher: auto
  network: ws
  servername: imafake.locker
  http-opts: {}
  h2-opts: {}
  tls: true
  ws-opts:
    path: /speedtest
- name: ''
  server: 192.71.166.100
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ''
  server: 172.66.44.230
  type: trojan
  port: 8443
  udp: true
  password: 8r<[9'l6hAO#8ZQi
  sni: Koma-YT.PAGeS.Dev
  ws-opts:
    path: /tro8sFW1S91B6sZrM1
    headers:
      Host: Koma-YT.PAGeS.Dev
  network: ws
- name: ''
  server: xray.kk37005.tk
  type: vmess
  port: 55919
  udp: true
  uuid: 2e7548bb-7c5b-4d97-d64d-1b2fe4050089
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: ''
  server: 138.124.30.8
  type: trojan
  port: 443
  udp: true
  password: 0311306e-56d4-4aa1-bde5-8cede7fcd3e4
  sni: joss.gpj1.web.id
  ws-opts:
    path: /Free-VPN-CF-Geo-Project/138.124.30.8=443
    headers:
      Host: joss.gpj1.web.id
  network: ws
- name: ''
  server: 45.86.229.28
  type: trojan
  port: 443
  udp: true
  password: 9ccc3e1d-3df5-4348-aa05-738310149cc3
  sni: joss.gpj1.web.id
  ws-opts:
    path: /Free-VPN-CF-Geo-Project/45.86.229.28=443
    headers:
      Host: joss.gpj1.web.id
  network: ws
- name: ''
  server: 34.22.190.30
  type: trojan
  port: 443
  udp: true
  password: 0a477acf-1f95-47cb-b4a5-a627b4c57de3
  sni: joss.gpj1.web.id
  ws-opts:
    path: /Free-VPN-CF-Geo-Project/34.22.190.30=443
    headers:
      Host: joss.gpj1.web.id
  network: ws
- name: ''
  server: 160.16.227.93
  type: trojan
  port: 1924
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: ''
  server: 94.177.199.119
  type: trojan
  port: 8443
  udp: true
  password: e04af4a8-ce76-4026-8480-82d0e35dd239
  sni: joss.gpj1.web.id
  ws-opts:
    path: /Free-VPN-CF-Geo-Project/94.177.199.119=8443
    headers:
      Host: joss.gpj1.web.id
  network: ws
- name: ''
  server: 153.121.51.29
  type: trojan
  port: 2760
  password: dd2f25b4c70689de8bc0f7fa9d6591cb
  sni: www.nintendogames.net
- name: ''
  server: 91.199.32.191
  type: trojan
  port: 2053
  udp: true
  password: 8b7d4642-dff2-4c16-81a4-88ca738d6718
  sni: joss.gpj1.web.id
  ws-opts:
    path: /Free-VPN-CF-Geo-Project/91.199.32.191=2053
    headers:
      Host: joss.gpj1.web.id
  network: ws
- name: ''
  server: 69.28.82.253
  type: trojan
  port: 443
  udp: true
  password: 8001fbf7-4b59-4415-a4bd-8bfded02c9c6
  sni: joss.gpj1.web.id
  ws-opts:
    path: /Free-VPN-CF-Geo-Project/69.28.82.253=443
    headers:
      Host: joss.gpj1.web.id
  network: ws
- name: ''
  server: v24.heduian.link
  type: vmess
  port: 30824
  udp: true
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ''
  server: 89.28.236.243
  type: trojan
  port: 443
  udp: true
  password: e9249478-ea4e-432f-a918-e84c1ce143c6
  sni: joss.gpj1.web.id
  ws-opts:
    path: /Free-VPN-CF-Geo-Project/89.28.236.243=443
    headers:
      Host: joss.gpj1.web.id
  network: ws
- name: ''
  server: 47.89.150.45
  type: trojan
  port: 21575
  udp: true
  password: abb96ae5-8337-4719-b300-fc3b2efbd14d
  sni: joss.gpj1.web.id
  ws-opts:
    path: /Free-VPN-CF-Geo-Project/47.89.150.45=21575
    headers:
      Host: joss.gpj1.web.id
  network: ws
- name: ''
  server: 38.180.72.162
  type: trojan
  port: 2053
  udp: true
  password: eb7339c5-70e4-4c7b-b5ef-4128adc8136a
  sni: joss.gpj1.web.id
  ws-opts:
    path: /Free-VPN-CF-Geo-Project/38.180.72.162=2053
    headers:
      Host: joss.gpj1.web.id
  network: ws
- name: ''
  server: 57.129.16.72
  type: trojan
  port: 2053
  udp: true
  password: 38af00d3-7c80-49fe-b91a-34d0d8044ee2
  sni: joss.gpj1.web.id
  ws-opts:
    path: /Free-VPN-CF-Geo-Project/57.129.16.72=2053
    headers:
      Host: joss.gpj1.web.id
  network: ws
- name: ''
  server: 34.22.190.30
  type: trojan
  port: 443
  udp: true
  password: 29ca24a5-e8aa-4cbd-9bcb-f96aba1d6f15
  sni: joss.gpj1.web.id
  ws-opts:
    path: /Free-VPN-CF-Geo-Project/34.22.190.30=443
    headers:
      Host: joss.gpj1.web.id
  network: ws
- name: ''
  server: 178.33.161.196
  type: trojan
  port: 2053
  udp: true
  password: be94cd60-8e91-4cd6-9c53-26ee1314edfd
  sni: joss.gpj1.web.id
  ws-opts:
    path: /Free-VPN-CF-Geo-Project/178.33.161.196=2053
    headers:
      Host: joss.gpj1.web.id
  network: ws
- name: ''
  server: 141.94.204.212
  type: trojan
  port: 2053
  udp: true
  password: 0e0c9c2a-6166-4337-bdfc-675602365807
  sni: joss.gpj1.web.id
  ws-opts:
    path: /Free-VPN-CF-Geo-Project/141.94.204.212=2053
    headers:
      Host: joss.gpj1.web.id
  network: ws
- name: ''
  server: 58.152.110.92
  type: trojan
  port: 443
  password: dd2f25b4c70689de8bc0f7fa9d6591cb
  sni: www.nintendogames.net
- name: ''
  server: koma-yt.pages.dev
  type: trojan
  port: 8443
  udp: true
  password: 8r<[9'l6hAO#8ZQi
  sni: Koma-YT.PAGeS.Dev
  ws-opts:
    path: /tro8sFW1S91B6sZrM1
    headers:
      Host: Koma-YT.PAGeS.Dev
  network: ws
- name: ''
  server: 89.110.120.197
  type: trojan
  port: 443
  udp: true
  password: 35f8e682-54bd-42c7-b537-94a8e4c84bcd
  sni: joss.gpj1.web.id
  ws-opts:
    path: /Free-VPN-CF-Geo-Project/89.110.120.197=443
    headers:
      Host: joss.gpj1.web.id
  network: ws
- name: ''
  server: 160.16.124.55
  type: trojan
  port: 702
  password: dd2f25b4c70689de8bc0f7fa9d6591cb
  sni: www.nintendogames.net
- name: ''
  server: 51.15.210.1
  type: trojan
  port: 443
  udp: true
  password: e6f0e8b0-3dc5-4d53-a23a-86c02d5ba098
  sni: joss.gpj1.web.id
  ws-opts:
    path: /Free-VPN-CF-Geo-Project/51.15.210.1=443
    headers:
      Host: joss.gpj1.web.id
  network: ws
- name: ''
  server: 188.132.129.199
  type: trojan
  port: 2053
  udp: true
  password: 0b5ea56a-056b-4917-9a47-b20ecfb78ad9
  sni: joss.gpj1.web.id
  ws-opts:
    path: /Free-VPN-CF-Geo-Project/188.132.129.199=2053
    headers:
      Host: joss.gpj1.web.id
  network: ws
- name: ''
  server: 212.227.144.37
  type: trojan
  port: 8443
  udp: true
  password: 1e1a7efa-a4f1-4936-a470-a001e0c3c85b
  sni: joss.gpj1.web.id
  ws-opts:
    path: /Free-VPN-CF-Geo-Project/212.227.144.37=8443
    headers:
      Host: joss.gpj1.web.id
  network: ws
- name: ''
  server: 45.159.251.8
  type: trojan
  port: 81
  udp: true
  password: 6ead60c4-4321-45d5-81a9-ba4835f7c692
  sni: joss.gpj1.web.id
  ws-opts:
    path: /Free-VPN-CF-Geo-Project/45.159.251.8=81
    headers:
      Host: joss.gpj1.web.id
  network: ws
- name: ''
  server: 34.22.190.30
  type: trojan
  port: 443
  udp: true
  password: fea8b7a7-cc83-4a78-a3fc-bbce9cc89ddb
  sni: joss.gpj1.web.id
  ws-opts:
    path: /Free-VPN-CF-Geo-Project/34.22.190.30=443
    headers:
      Host: joss.gpj1.web.id
  network: ws
- name: ''
  server: 217.30.10.31
  type: trojan
  port: 8443
  udp: true
  password: 422d402c-58f1-4473-abeb-fe6e69dc97ed
  sni: joss.gpj1.web.id
  ws-opts:
    path: /Free-VPN-CF-Geo-Project/217.30.10.31=8443
    headers:
      Host: joss.gpj1.web.id
  network: ws
- name: ''
  server: usiys.southbyte.xyz
  type: trojan
  port: 5897
  udp: true
  password: fg20mtCFHy
  sni: usiys.southbyte.xyz
  skip-cert-verify: true
- name: ''
  server: 37.252.5.75
  type: trojan
  port: 443
  udp: true
  password: 3208e968-b862-4e2e-ad90-2b49e7ce7afb
  sni: joss.gpj1.web.id
  ws-opts:
    path: /Free-VPN-CF-Geo-Project/37.252.5.75=443
    headers:
      Host: joss.gpj1.web.id
  network: ws
- name: ''
  server: 89.28.236.243
  type: trojan
  port: 443
  udp: true
  password: 5c8c8b61-9b24-4c5a-b6ad-f6560df2e9d3
  sni: joss.gpj1.web.id
  ws-opts:
    path: /Free-VPN-CF-Geo-Project/89.28.236.243=443
    headers:
      Host: joss.gpj1.web.id
  network: ws
- name: ''
  server: 94.131.123.74
  type: trojan
  port: 443
  udp: true
  password: 94a81dc7-e8e6-46e5-838d-84ca142b88b2
  sni: joss.gpj1.web.id
  ws-opts:
    path: /Free-VPN-CF-Geo-Project/94.131.123.74=443
    headers:
      Host: joss.gpj1.web.id
  network: ws
- name: ''
  server: 160.16.204.136
  type: trojan
  port: 1331
  password: dd2f25b4c70689de8bc0f7fa9d6591cb
  sni: www.nintendogames.net
- name: ''
  server: 58.152.25.241
  type: trojan
  port: 443
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: ''
  server: 160.16.89.176
  type: trojan
  port: 2760
  password: dd2f25b4c70689de8bc0f7fa9d6591cb
  sni: www.nintendogames.net
- name: ''
  server: 109.169.76.23
  type: trojan
  port: 443
  udp: true
  password: d69e725c-7c7e-4c75-9786-4859b4e0bbc6
  sni: joss.gpj1.web.id
  ws-opts:
    path: /Free-VPN-CF-Geo-Project/109.169.76.23=443
    headers:
      Host: joss.gpj1.web.id
  network: ws
- name: ''
  server: 160.16.89.176
  type: trojan
  port: 702
  password: dd2f25b4c70689de8bc0f7fa9d6591cb
  sni: www.nintendogames.net
- name: ''
  server: 81.91.214.162
  type: trojan
  port: 443
  udp: true
  password: f583143c-2cbe-47f5-804d-27efa55442a1
  sni: joss.gpj1.web.id
  ws-opts:
    path: /Free-VPN-CF-Geo-Project/81.91.214.162=443
    headers:
      Host: joss.gpj1.web.id
  network: ws
- name: ''
  server: 160.16.214.6
  type: trojan
  port: 2760
  password: dd2f25b4c70689de8bc0f7fa9d6591cb
  sni: www.nintendogames.net
- name: ''
  server: 81.22.132.183
  type: trojan
  port: 443
  udp: true
  password: ee339912-0c35-4fac-8d85-180b65bcd49c
  sni: joss.gpj1.web.id
  ws-opts:
    path: /Free-VPN-CF-Geo-Project/81.22.132.183=443
    headers:
      Host: joss.gpj1.web.id
  network: ws
- name: ''
  server: joss.gpj1.web.id
  type: trojan
  port: 443
  udp: true
  password: 6e6191a3-9a93-4617-859a-8d0ea0fce937
  sni: joss.gpj1.web.id
  ws-opts:
    path: /Free-VPN-CF-Geo-Project/81.91.214.85=443
    headers:
      Host: joss.gpj1.web.id
  network: ws
- name: ''
  server: cdnfire.xiaomispeed.com
  type: trojan
  port: 21104
  udp: true
  password: ab4f3f53-e34c-4e3d-bcdd-a2aee9801ec3
  sni: cdnfire.xiaomispeed.com
  skip-cert-verify: true
- name: ''
  server: cdnfire.xiaomispeed.com
  type: trojan
  port: 21102
  udp: true
  password: 18063020-3cc8-4691-9f43-77556a4b6bb8
  sni: cdnfire.xiaomispeed.com
  skip-cert-verify: true
- name: ''
  server: 43.163.203.24
  type: vmess
  country: ðŸ‡¨ðŸ‡³CN
  port: 6600
  uuid: 4945cf85-a9aa-433f-b845-4c06eda84e0a
  alterId: 0
  cipher: auto
  network: tcp
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ''
  server: 103.106.3.82
  type: ss
  country: ðŸ‡§ðŸ‡©BD
  port: 443
  password: 4SaCIazlgumYkM8FkPzlmwjpyWBDZFBk
  cipher: chacha20-ietf-poly1305
- name: ''
  server: 95.174.68.33
  type: ss
  country: ðŸ‡¦ðŸ‡¹AT
  port: 443
  password: YzH4id7ZEyKpfy39F2YcOmzCsBklGwh8
  cipher: chacha20-ietf-poly1305
- name: ''
  server: 208.76.223.218
  type: vmess
  country: ðŸ‡ªðŸ‡¸ES
  port: 27092
  uuid: a0596ba6-72a3-4366-8992-77088da65bd8
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ''
  server: 82.198.246.97
  type: vmess
  country: ðŸ‡¬ðŸ‡§GB
  port: 180
  uuid: d13fc2f5-3e05-4795-81eb-44143a09e552
  alterId: 0
  cipher: auto
  network: tcp
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ''
  server: node4.rtxconfigz.com
  type: vmess
  country: ðŸ‡©ðŸ‡ªDE
  port: 443
  uuid: 44e57485-eccc-46ef-808f-cd17ac810018
  alterId: 0
  cipher: auto
  network: ws
  servername: node4.rtxconfigz.com
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /@Malinda6104
    headers:
      HOST: node4.rtxconfigz.com
- name: ''
  server: 8.218.17.136
  type: vmess
  country: ðŸ‡­ðŸ‡°HK
  port: 52986
  uuid: 7363d47e-ac8b-4fe0-d23e-99077999a70d
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ''
  server: 47.238.71.166
  type: vmess
  country: ðŸ‡­ðŸ‡°HK
  port: 13502
  uuid: 7ecfb350-e87b-4c3b-b90a-de4884ad2838
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ''
  server: 34.245.193.205
  type: ss
  country: ðŸ‡®ðŸ‡ªIE
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ''
  server: 216.238.89.53
  type: vmess
  country: ðŸ‡²ðŸ‡½MX
  port: 57283
  uuid: 1a5aafc0-6482-451d-fe76-6875b7818579
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ''
  server: 3.252.162.214
  type: ss
  country: ðŸ‡®ðŸ‡ªIE
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ''
  server: 185.156.110.92
  type: ss
  country: ðŸ‡ºðŸ‡¸US
  port: 443
  password: gXOXk2FJwsz9P6nXIICuDNOqF9gWX1dn
  cipher: chacha20-ietf-poly1305
- name: ''
  server: th0603-1.ysds168.shop
  type: vmess
  country: ðŸ‡¹ðŸ‡­TH
  port: 1036
  uuid: 5893c6cd-c14f-4e99-a9ae-6c2ca7456584
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: ''
  server: 193.124.24.247
  type: vmess
  country: ðŸ‡ºðŸ‡¸US
  port: 6502
  uuid: 242f22a3-29d9-4a94-d8ba-88043f2e1921
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ''
  server: cgroup.node5.s.nodelist-airport.com
  type: ss
  country: ðŸ‡ºðŸ‡¸US
  port: 5003
  password: 8f3a835c-8a45-480d-ae35-1deb2c52dcae
  cipher: aes-256-gcm
- name: ''
  server: 193.124.24.247
  type: vmess
  country: ðŸ‡ºðŸ‡¸US
  port: 6504
  uuid: 7ceb165c-9aff-4ab7-ce9e-1df31a5ed911
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ''
  server: 193.124.24.247
  type: vmess
  country: ðŸ‡ºðŸ‡¸US
  port: 6512
  uuid: 729bfa51-095c-4f50-a1e0-2dfc90d51ebd
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ''
  server: 193.124.24.247
  type: vmess
  country: ðŸ‡ºðŸ‡¸US
  port: 6513
  uuid: 5cf7fcbc-e2c1-42c4-d0d7-79c45a7d588d
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ''
  server: 193.124.24.247
  type: vmess
  country: ðŸ‡ºðŸ‡¸US
  port: 6508
  uuid: b68fead5-5b0b-43a1-c34a-804467f0f368
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ''
  server: 193.124.24.247
  type: vmess
  country: ðŸ‡ºðŸ‡¸US
  port: 6510
  uuid: 8f44f672-e53b-44fb-b502-c886d37107b5
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ''
  server: 193.124.24.247
  type: vmess
  country: ðŸ‡ºðŸ‡¸US
  port: 6505
  uuid: b34732f9-2856-4974-8bae-1351928e347f
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ''
  server: sy4.620720.xyz
  type: vmess
  country: ðŸZZ
  port: 443
  uuid: 516d8a7a-3f0b-41d3-bad0-246116381516
  alterId: 0
  cipher: auto
  network: ws
  servername: sy4.620720.xyz
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /
    headers:
      HOST: sy4.620720.xyz
- name: ''
  server: 74.48.14.238
  type: vmess
  country: ðŸ‡¨ðŸ‡¦CA
  port: 2087
  uuid: ffd95a2c-ab52-434b-8def-2d06a959f5b5
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /grqf
proxy-groups:
- name: ðŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  - ''
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ðŸš€ èŠ‚ç‚¹é€‰æ‹©
