port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: ğŸ‡¨ğŸ‡¦CA_31 |12.89Mb
  server: 137.184.174.93
  type: ss
  country: ğŸ‡¨ğŸ‡¦CA
  port: 8080
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: ğŸ‡¨ğŸ‡¦CA_23 |12.88Mb
  server: 15.223.198.54
  type: ss
  country: ğŸ‡¨ğŸ‡¦CA
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: Pool_ğŸ‡¬ğŸ‡§GB_63 |13.37Mb
  server: 79.127.233.170
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: disney_GB |59.11Mb
  server: 89.185.84.185
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: ocLhdiEXutNDlofHdfKPJB
  cipher: chacha20-ietf-poly1305
- name: disney_GB |49.41Mb
  server: 89.185.84.185
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: 6D3AybGUDufEK4xulpE7zj
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡©ğŸ‡ªDE_41 |17.52Mb
  server: 18.158.60.169
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: disney_GB |28.84Mb
  server: 89.185.84.185
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: ozSHXLRuO7JckCvhgLjLaU
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸ‡®ğŸ‡·IR-ğŸ‡³ğŸ‡±NL_75 |11.73Mb
  server: 151.242.251.144
  type: ss
  country: ğŸ‡®ğŸ‡·IR
  port: 8080
  password: o5osZg269v5zHpYjr1xY9s
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡©ğŸ‡ªDE_38 |56.25Mb
  server: 81.19.141.45
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 443
  password: EEIh3YZZ5QZRvJM6C04YSM
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ªğŸ‡¸ES_52 |10.54Mb
  server: 194.87.45.189
  type: ss
  country: ğŸ‡ªğŸ‡¸ES
  port: 443
  password: 676zALNF1CckrwJ6HGjRKl
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ªğŸ‡¸ES_59 |12.14Mb
  server: 194.87.45.189
  type: ss
  country: ğŸ‡ªğŸ‡¸ES
  port: 443
  password: sR5IT3k2nRznHiLrJ6p48Q
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸ‡®ğŸ‡·IR-ğŸ‡³ğŸ‡±NL_77 |14.23Mb
  server: 151.242.251.131
  type: ss
  country: ğŸ‡®ğŸ‡·IR
  port: 8080
  password: o5osZg269v5zHpYjr1xY9s
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_84 |49.60Mb
  server: 45.87.175.171
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: 4a2rfixophdjffa8KVA4Aa
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_83 |12.51Mb
  server: 45.87.175.171
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: 1RWwXhwfAB5gAEozU4G2Pg
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_89 |12.29Mb
  server: 45.87.175.192
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¯ğŸ‡µJP_81 |59.71Mb
  server: 45.32.45.45
  type: vmess
  country: ğŸ‡¯ğŸ‡µJP
  port: 14760
  uuid: dbf7a6e4-d518-4f9b-a55e-27ef892ffac1
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡±ğŸ‡¹LT_91 |54.29Mb
  server: 45.87.175.22
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡³ğŸ‡±NL_98 |11.23Mb
  server: 193.29.139.179
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 8080
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡³ğŸ‡±NL_99 |44.18Mb
  server: 193.29.139.164
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 8080
  password: 1RWwXhwfAB5gAEozU4G2Pg
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_147 |10.23Mb
  server: 3.145.46.227
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡³ğŸ‡±NL_100 |16.53Mb
  server: 193.29.139.202
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 8080
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_152 |34.91Mb
  server: 18.188.211.45
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡³ğŸ‡±NL_102 |10.58Mb
  server: 193.29.139.173
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 8080
  password: 4a2rfixophdjffa8KVA4Aa
  cipher: chacha20-ietf-poly1305
- name: disney_US |25.19Mb
  server: 154.64.243.19
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 38533
  uuid: 9bc23ccf-4769-4e9a-b278-2dfa8d9ef425
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
  ws-opts:
    path: /
- name: Pool_ğŸ‡­ğŸ‡°HK_74 |674.00Mb
  server: 150.107.46.21
  type: ssr
  country: ğŸ‡­ğŸ‡°HK
  port: 8083
  password: iFqnzSscN
  cipher: aes-256-cfb
  protocol: origin
  obfs: tls1.2_ticket_auth
- name: ğŸ‡µğŸ‡±PL_109 |10.11Mb
  server: 217.30.10.70
  type: ss
  country: ğŸ‡µğŸ‡±PL
  port: 9001
  password: UkXRsXvR6buDMG2Y
  cipher: aes-256-cfb
- name: ğŸ‡±ğŸ‡¹LT_88 |15.68Mb
  server: ltnl10.saint.ydns.eu
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡µğŸ‡±PL_118 |11.17Mb
  server: 217.30.10.70
  type: ss
  country: ğŸ‡µğŸ‡±PL
  port: 9019
  password: GA9KzeEgvfxNrgmM
  cipher: aes-256-cfb
- name: disney_RU |41.28Mb
  server: 5.129.201.43
  type: ss
  country: ğŸ‡·ğŸ‡ºRU
  port: 23256
  password: yALtyAtHfbw1Vu4pqh6wUc
  cipher: chacha20-ietf-poly1305
- name: disney_RU |105.70Mb
  server: 147.45.235.63
  type: ss
  country: ğŸ‡·ğŸ‡ºRU
  port: 49115
  password: yYLiE0LOsr0CwIjbiCSLy2
  cipher: chacha20-ietf-poly1305
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - ğŸ‡¨ğŸ‡¦CA_31 |12.89Mb
  - ğŸ‡¨ğŸ‡¦CA_23 |12.88Mb
  - Pool_ğŸ‡¬ğŸ‡§GB_63 |13.37Mb
  - disney_GB |59.11Mb
  - disney_GB |49.41Mb
  - ğŸ‡©ğŸ‡ªDE_41 |17.52Mb
  - disney_GB |28.84Mb
  - Relay_ğŸ‡®ğŸ‡·IR-ğŸ‡³ğŸ‡±NL_75 |11.73Mb
  - ğŸ‡©ğŸ‡ªDE_38 |56.25Mb
  - ğŸ‡ªğŸ‡¸ES_52 |10.54Mb
  - ğŸ‡ªğŸ‡¸ES_59 |12.14Mb
  - Relay_ğŸ‡®ğŸ‡·IR-ğŸ‡³ğŸ‡±NL_77 |14.23Mb
  - ğŸ‡±ğŸ‡¹LT_84 |49.60Mb
  - ğŸ‡±ğŸ‡¹LT_83 |12.51Mb
  - ğŸ‡±ğŸ‡¹LT_89 |12.29Mb
  - ğŸ‡¯ğŸ‡µJP_81 |59.71Mb
  - ğŸ‡±ğŸ‡¹LT_91 |54.29Mb
  - ğŸ‡³ğŸ‡±NL_98 |11.23Mb
  - ğŸ‡³ğŸ‡±NL_99 |44.18Mb
  - ğŸ‡ºğŸ‡¸US_147 |10.23Mb
  - ğŸ‡³ğŸ‡±NL_100 |16.53Mb
  - ğŸ‡ºğŸ‡¸US_152 |34.91Mb
  - ğŸ‡³ğŸ‡±NL_102 |10.58Mb
  - disney_US |25.19Mb
  - Pool_ğŸ‡­ğŸ‡°HK_74 |674.00Mb
  - ğŸ‡µğŸ‡±PL_109 |10.11Mb
  - ğŸ‡±ğŸ‡¹LT_88 |15.68Mb
  - ğŸ‡µğŸ‡±PL_118 |11.17Mb
  - disney_RU |41.28Mb
  - disney_RU |105.70Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - ğŸ‡¨ğŸ‡¦CA_31 |12.89Mb
  - ğŸ‡¨ğŸ‡¦CA_23 |12.88Mb
  - Pool_ğŸ‡¬ğŸ‡§GB_63 |13.37Mb
  - disney_GB |59.11Mb
  - disney_GB |49.41Mb
  - ğŸ‡©ğŸ‡ªDE_41 |17.52Mb
  - disney_GB |28.84Mb
  - Relay_ğŸ‡®ğŸ‡·IR-ğŸ‡³ğŸ‡±NL_75 |11.73Mb
  - ğŸ‡©ğŸ‡ªDE_38 |56.25Mb
  - ğŸ‡ªğŸ‡¸ES_52 |10.54Mb
  - ğŸ‡ªğŸ‡¸ES_59 |12.14Mb
  - Relay_ğŸ‡®ğŸ‡·IR-ğŸ‡³ğŸ‡±NL_77 |14.23Mb
  - ğŸ‡±ğŸ‡¹LT_84 |49.60Mb
  - ğŸ‡±ğŸ‡¹LT_83 |12.51Mb
  - ğŸ‡±ğŸ‡¹LT_89 |12.29Mb
  - ğŸ‡¯ğŸ‡µJP_81 |59.71Mb
  - ğŸ‡±ğŸ‡¹LT_91 |54.29Mb
  - ğŸ‡³ğŸ‡±NL_98 |11.23Mb
  - ğŸ‡³ğŸ‡±NL_99 |44.18Mb
  - ğŸ‡ºğŸ‡¸US_147 |10.23Mb
  - ğŸ‡³ğŸ‡±NL_100 |16.53Mb
  - ğŸ‡ºğŸ‡¸US_152 |34.91Mb
  - ğŸ‡³ğŸ‡±NL_102 |10.58Mb
  - disney_US |25.19Mb
  - Pool_ğŸ‡­ğŸ‡°HK_74 |674.00Mb
  - ğŸ‡µğŸ‡±PL_109 |10.11Mb
  - ğŸ‡±ğŸ‡¹LT_88 |15.68Mb
  - ğŸ‡µğŸ‡±PL_118 |11.17Mb
  - disney_RU |41.28Mb
  - disney_RU |105.70Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
