port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: disney_netflix_US
  server: 107.175.87.208
  type: ss
  port: 10011
  udp: true
  password: 86039b71-ba82-4ca8-838e-87086ae666de
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_US
  server: 5.78.51.123
  type: ss
  port: 1080
  password: 8tmnvX5zYuWGVIDP2jglZw
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_US
  server: 15.204.247.49
  type: ss
  port: 12000
  password: 8JCsPssfgS8tiRwiMlhARg==
  cipher: aes-256-gcm
- name: disney_netflix_US
  server: 107.175.87.208
  type: ss
  port: 10011
  udp: true
  password: f5e5f9c5-9677-41ea-a81f-abcf015c66af
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_GB
  server: 144.217.164.29
  type: ss
  port: 12000
  password: 8JCsPssfgS8tiRwiMlhARg==
  cipher: aes-256-gcm
- name: disney_MD
  server: 185.153.197.5
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: disney_netflix_FR
  server: 195.154.119.77
  type: ss
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: netflix_IE
  server: 18.203.127.31
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: disney_netflix_DE
  server: 57.128.214.100
  type: ss
  port: 12000
  password: 8JCsPssfgS8tiRwiMlhARg==
  cipher: aes-256-gcm
- name: _97
  server: 134.209.147.198
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: disney_netflix_US
  server: usiys.southbyte.xyz
  type: trojan
  port: 5897
  udp: true
  password: fg20mtCFHy
  sni: usiys.southbyte.xyz
  skip-cert-verify: true
- name: netflix_BR
  server: 213.159.66.206
  type: ss
  port: 443
  udp: true
  password: pl2XtR0pzwknQOGwewbwXtPYDw1zn9Vu
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_ES
  server: 45.159.251.8
  type: trojan
  port: 81
  udp: true
  password: 6ead60c4-4321-45d5-81a9-ba4835f7c692
  sni: joss.gpj1.web.id
  ws-opts:
    path: /Free-VPN-CF-Geo-Project/45.159.251.8=81
    headers:
      Host: joss.gpj1.web.id
  network: ws
- name: disney_netflix_DE
  server: 91.103.253.193
  type: trojan
  port: 443
  udp: true
  password: 1a758d17-149a-47f3-9336-d1cc33232cc9
  sni: joss.gpj1.web.id
  ws-opts:
    path: /Free-VPN-CF-Geo-Project/91.103.253.193=443
    headers:
      Host: joss.gpj1.web.id
  network: ws
- name: Relay_-ğŸ‡­ğŸ‡°HK_106
  server: 131.186.63.89
  type: vmess
  port: 11655
  uuid: 4bf075f5-4d5e-4d39-f5ab-b32a86250f0e
  alterId: 0
  cipher: auto
  network: ws
  servername: hk.nbee.pp.ua
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /aa
    headers:
      Host: hk.nbee.pp.ua
- name: disney_netflix_GB
  server: 109.169.76.23
  type: trojan
  port: 443
  udp: true
  password: d69e725c-7c7e-4c75-9786-4859b4e0bbc6
  sni: joss.gpj1.web.id
  ws-opts:
    path: /Free-VPN-CF-Geo-Project/109.169.76.23=443
    headers:
      Host: joss.gpj1.web.id
  network: ws
- name: Relay_-ğŸ‡³ğŸ‡±NL_107
  server: 160.16.89.176
  type: trojan
  port: 2760
  password: dd2f25b4c70689de8bc0f7fa9d6591cb
  sni: www.nintendogames.net
- name: disney_netflix_NL
  server: 160.16.214.6
  type: trojan
  port: 2760
  password: dd2f25b4c70689de8bc0f7fa9d6591cb
  sni: www.nintendogames.net
- name: disney_netflix_CZ
  server: 81.91.214.162
  type: trojan
  port: 443
  udp: true
  password: f583143c-2cbe-47f5-804d-27efa55442a1
  sni: joss.gpj1.web.id
  ws-opts:
    path: /Free-VPN-CF-Geo-Project/81.91.214.162=443
    headers:
      Host: joss.gpj1.web.id
  network: ws
- name: disney_netflix_NL
  server: 81.22.132.183
  type: trojan
  port: 443
  udp: true
  password: ee339912-0c35-4fac-8d85-180b65bcd49c
  sni: joss.gpj1.web.id
  ws-opts:
    path: /Free-VPN-CF-Geo-Project/81.22.132.183=443
    headers:
      Host: joss.gpj1.web.id
  network: ws
- name: disney_netflix_FR
  server: 51.15.210.1
  type: trojan
  port: 443
  udp: true
  password: e6f0e8b0-3dc5-4d53-a23a-86c02d5ba098
  sni: joss.gpj1.web.id
  ws-opts:
    path: /Free-VPN-CF-Geo-Project/51.15.210.1=443
    headers:
      Host: joss.gpj1.web.id
  network: ws
- name: disney_DK
  server: 89.28.236.243
  type: trojan
  port: 443
  udp: true
  password: 5c8c8b61-9b24-4c5a-b6ad-f6560df2e9d3
  sni: joss.gpj1.web.id
  ws-opts:
    path: /Free-VPN-CF-Geo-Project/89.28.236.243=443
    headers:
      Host: joss.gpj1.web.id
  network: ws
- name: disney_netflix_PL
  server: 217.30.10.31
  type: trojan
  port: 8443
  udp: true
  password: 422d402c-58f1-4473-abeb-fe6e69dc97ed
  sni: joss.gpj1.web.id
  ws-opts:
    path: /Free-VPN-CF-Geo-Project/217.30.10.31=8443
    headers:
      Host: joss.gpj1.web.id
  network: ws
- name: disney_netflix_IT
  server: 185.247.184.186
  type: trojan
  port: 8443
  udp: true
  password: 2302eb2b-9401-4176-a4da-b41d4cd55756
  sni: joss.gpj1.web.id
  ws-opts:
    path: /Free-VPN-CF-Geo-Project/185.247.184.186=8443
    headers:
      Host: joss.gpj1.web.id
  network: ws
- name: disney_netflix_US
  server: 160.16.89.176
  type: trojan
  port: 702
  password: dd2f25b4c70689de8bc0f7fa9d6591cb
  sni: www.nintendogames.net
- name: netflix_JP
  server: 160.16.204.136
  type: trojan
  port: 1331
  password: dd2f25b4c70689de8bc0f7fa9d6591cb
  sni: www.nintendogames.net
- name: _115
  server: 58.152.25.241
  type: trojan
  port: 443
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: disney_netflix_US
  server: 74.48.14.238
  type: vmess
  country: ğŸ‡¨ğŸ‡¦CA
  port: 2087
  uuid: ffd95a2c-ab52-434b-8def-2d06a959f5b5
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /grqf
- name: disney_netflix_US
  server: 160.16.204.136
  type: trojan
  port: 2890
  password: dd2f25b4c70689de8bc0f7fa9d6591cb
  sni: www.nintendogames.net
- name: disney_netflix_FR
  server: 34.22.190.30
  type: trojan
  port: 443
  udp: true
  password: fea8b7a7-cc83-4a78-a3fc-bbce9cc89ddb
  sni: joss.gpj1.web.id
  ws-opts:
    path: /Free-VPN-CF-Geo-Project/34.22.190.30=443
    headers:
      Host: joss.gpj1.web.id
  network: ws
- name: disney_netflix_FR
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 27092
  uuid: a0596ba6-72a3-4366-8992-77088da65bd8
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡¦ğŸ‡¹AT_124
  server: 95.174.68.33
  type: ss
  country: ğŸ‡¦ğŸ‡¹AT
  port: 443
  password: YzH4id7ZEyKpfy39F2YcOmzCsBklGwh8
  cipher: chacha20-ietf-poly1305
- name: netflix_KZ
  server: 103.106.3.82
  type: ss
  country: ğŸ‡§ğŸ‡©BD
  port: 443
  password: 4SaCIazlgumYkM8FkPzlmwjpyWBDZFBk
  cipher: chacha20-ietf-poly1305
- name: netflix_IE
  server: 3.252.162.214
  type: ss
  country: ğŸ‡®ğŸ‡ªIE
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡¦ğŸ‡ºAU_125
  server: 54.252.214.254
  type: vmess
  country: ğŸ‡¦ğŸ‡ºAU
  port: 1000
  uuid: 61a9c747-cbe6-46aa-a0bb-8d5a615db8b1
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: netflix_MX
  server: 216.238.89.53
  type: vmess
  country: ğŸ‡²ğŸ‡½MX
  port: 57283
  uuid: 1a5aafc0-6482-451d-fe76-6875b7818579
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡­ğŸ‡°HK_133
  server: 8.218.17.136
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 52986
  uuid: 7363d47e-ac8b-4fe0-d23e-99077999a70d
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_HK
  server: 8.218.140.27
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 39174
  uuid: 5854b877-2b30-457a-b730-837aa5976279
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
  ws-opts:
    path: /arki?ed=2048
- name: disney_netflix_US
  server: 193.124.24.247
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 6505
  uuid: b34732f9-2856-4974-8bae-1351928e347f
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_US
  server: 193.124.24.247
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 6510
  uuid: 8f44f672-e53b-44fb-b502-c886d37107b5
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_HK
  server: 68e64cf5-t66sg0-t7luxf-tng5.hk3.p5pv.com
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 80
  uuid: 2ec58858-976b-11ea-82ef-f23c9164ca5d
  alterId: 2
  cipher: auto
  network: ws
  servername: broadcastlv.chat.bilibili.com
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
  ws-opts:
    path: /
    headers:
      HOST: broadcastlv.chat.bilibili.com
- name: netflix_JP
  server: t1.620720.xyz
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 8443
  uuid: 516d8a7a-3f0b-41d3-bad0-246116381516
  alterId: 0
  cipher: auto
  network: ws
  servername: t1.620720.xyz
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /
    headers:
      HOST: t1.620720.xyz
- name: disney_netflix_US
  server: 193.124.24.247
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 6502
  uuid: 242f22a3-29d9-4a94-d8ba-88043f2e1921
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: netflix_HR
  server: 185.156.110.92
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: gXOXk2FJwsz9P6nXIICuDNOqF9gWX1dn
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_US
  server: 193.124.24.247
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 6513
  uuid: 5cf7fcbc-e2c1-42c4-d0d7-79c45a7d588d
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_US
  server: 193.124.24.247
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 6508
  uuid: b68fead5-5b0b-43a1-c34a-804467f0f368
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_US
  server: 193.124.24.247
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 6504
  uuid: 7ceb165c-9aff-4ab7-ce9e-1df31a5ed911
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_TH
  server: th0603-1.ysds168.shop
  type: vmess
  country: ğŸ‡¹ğŸ‡­TH
  port: 1036
  uuid: 5893c6cd-c14f-4e99-a9ae-6c2ca7456584
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: disney_netflix_US
  server: 193.124.24.247
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 6512
  uuid: 729bfa51-095c-4f50-a1e0-2dfc90d51ebd
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_HK
  server: 2.59.62.63
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 19365
  uuid: 9583a647-b0ba-47b0-d4b0-4e12a0201d67
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡ºğŸ‡¸US_152
  server: 216.227.168.157
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 45258
  uuid: 469e0b31-30c3-4dab-800d-711232634ce1
  alterId: 0
  cipher: auto
  network: tcp
  servername: lt.fxlcn.com
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_US
  server: cf.fovi.tk
  type: vmess
  country: ğŸZZ
  port: 443
  uuid: bf67437e-6c90-45ca-abc2-c7240a5ce2aa
  alterId: 0
  cipher: auto
  network: ws
  servername: foxpol.fovi.tk
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /eisasqa
    headers:
      HOST: foxpol.fovi.tk
- name: Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_153
  server: west_a.gaogroup.bid
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  uuid: ef004cfa-b463-4473-97df-4f0da4473ae0
  alterId: 0
  cipher: auto
  network: ws
  servername: west_a.gaogroup.bid
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /ctzxvws
    headers:
      HOST: west_a.gaogroup.bid
- name: Relay_ğŸ‡­ğŸ‡°HK-ğŸ‡­ğŸ‡°HK_136
  server: n1744453319.lie5d.cyou
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 443
  uuid: 6928af97-a23e-408c-956e-5cd2207f3557
  alterId: 0
  cipher: auto
  network: ws
  servername: n1744453319.lie5d.cyou
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /
    headers:
      HOST: n1744453319.lie5d.cyou
- name: disney_netflix_US
  server: 82.198.246.97
  type: vmess
  country: ğŸ‡¬ğŸ‡§GB
  port: 180
  uuid: d13fc2f5-3e05-4795-81eb-44143a09e552
  alterId: 0
  cipher: auto
  network: tcp
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_HK
  server: 47.238.71.166
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 13502
  uuid: 7ecfb350-e87b-4c3b-b90a-de4884ad2838
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - disney_netflix_US
  - disney_netflix_US
  - disney_netflix_US
  - disney_netflix_US
  - disney_netflix_GB
  - disney_MD
  - disney_netflix_FR
  - netflix_IE
  - disney_netflix_DE
  - _97
  - disney_netflix_US
  - netflix_BR
  - disney_netflix_ES
  - disney_netflix_DE
  - Relay_-ğŸ‡­ğŸ‡°HK_106
  - disney_netflix_GB
  - Relay_-ğŸ‡³ğŸ‡±NL_107
  - disney_netflix_NL
  - disney_netflix_CZ
  - disney_netflix_NL
  - disney_netflix_FR
  - disney_DK
  - disney_netflix_PL
  - disney_netflix_IT
  - disney_netflix_US
  - netflix_JP
  - _115
  - disney_netflix_US
  - disney_netflix_US
  - disney_netflix_FR
  - disney_netflix_FR
  - ğŸ‡¦ğŸ‡¹AT_124
  - netflix_KZ
  - netflix_IE
  - ğŸ‡¦ğŸ‡ºAU_125
  - netflix_MX
  - ğŸ‡­ğŸ‡°HK_133
  - disney_netflix_HK
  - disney_netflix_US
  - disney_netflix_US
  - disney_netflix_HK
  - netflix_JP
  - disney_netflix_US
  - netflix_HR
  - disney_netflix_US
  - disney_netflix_US
  - disney_netflix_US
  - disney_netflix_TH
  - disney_netflix_US
  - disney_netflix_HK
  - ğŸ‡ºğŸ‡¸US_152
  - disney_netflix_US
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_153
  - Relay_ğŸ‡­ğŸ‡°HK-ğŸ‡­ğŸ‡°HK_136
  - disney_netflix_US
  - disney_netflix_HK
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - disney_netflix_US
  - disney_netflix_US
  - disney_netflix_US
  - disney_netflix_US
  - disney_netflix_GB
  - disney_MD
  - disney_netflix_FR
  - netflix_IE
  - disney_netflix_DE
  - _97
  - disney_netflix_US
  - netflix_BR
  - disney_netflix_ES
  - disney_netflix_DE
  - Relay_-ğŸ‡­ğŸ‡°HK_106
  - disney_netflix_GB
  - Relay_-ğŸ‡³ğŸ‡±NL_107
  - disney_netflix_NL
  - disney_netflix_CZ
  - disney_netflix_NL
  - disney_netflix_FR
  - disney_DK
  - disney_netflix_PL
  - disney_netflix_IT
  - disney_netflix_US
  - netflix_JP
  - _115
  - disney_netflix_US
  - disney_netflix_US
  - disney_netflix_FR
  - disney_netflix_FR
  - ğŸ‡¦ğŸ‡¹AT_124
  - netflix_KZ
  - netflix_IE
  - ğŸ‡¦ğŸ‡ºAU_125
  - netflix_MX
  - ğŸ‡­ğŸ‡°HK_133
  - disney_netflix_HK
  - disney_netflix_US
  - disney_netflix_US
  - disney_netflix_HK
  - netflix_JP
  - disney_netflix_US
  - netflix_HR
  - disney_netflix_US
  - disney_netflix_US
  - disney_netflix_US
  - disney_netflix_TH
  - disney_netflix_US
  - disney_netflix_HK
  - ğŸ‡ºğŸ‡¸US_152
  - disney_netflix_US
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_153
  - Relay_ğŸ‡­ğŸ‡°HK-ğŸ‡­ğŸ‡°HK_136
  - disney_netflix_US
  - disney_netflix_HK
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
