port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: _244 |20.51Mb
  server: 46.183.184.60
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: _252 |186.19Mb
  server: 13.61.180.46
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: Pool__254 |26.96Mb
  server: 185.103.110.68
  type: ss
  port: 18283
  udp: true
  password: y3o3ra6edy5nfc6hyb2n
  cipher: aes-128-gcm
- name: _251 |59.79Mb
  server: 13.61.13.231
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: Relay_-ğŸ‡«ğŸ‡®FI_241 |48.75Mb
  server: 77.83.247.206
  type: ss
  port: 18284
  udp: true
  password: tijsjk3iwzc6b10azb0y
  cipher: aes-128-gcm
- name: _273 |12.18Mb
  server: 15.235.41.200
  type: vmess
  port: 80
  uuid: 58fe1542-5290-40ad-815a-77707a81afe5
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /IOebhLMhl1CTbFHbL95myfRX2
- name: _264 |153.35Mb
  server: 51.20.125.235
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: netflix_US |42.06Mb
  server: 163.192.49.195
  type: vmess
  port: 443
  uuid: bcb7c581-3c95-4569-a4e7-918141e91ea3
  alterId: 0
  cipher: auto
  network: http
  http-opts:
    path:
    - /
    headers:
      Host:
      - a.189.cn
  h2-opts: {}
- name: _249 |56.31Mb
  server: 103.149.183.191
  type: ss
  port: 8388
  udp: true
  password: asd123456
  cipher: chacha20-ietf
- name: Relay_-ğŸ‡ºğŸ‡¸US_280 |39.24Mb
  server: 38.14.99.163
  type: vmess
  port: 59807
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: disney_US |33.55Mb
  server: 192.204.47.79
  type: vmess
  port: 42277
  udp: true
  uuid: aee61b21-e85a-484b-f203-b245f1451cff
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: Relay_-ğŸ‡ºğŸ‡¸US_281 |40.90Mb
  server: 38.14.99.179
  type: vmess
  port: 59807
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _285 |34.06Mb
  server: 216.238.86.158
  type: vmess
  port: 34460
  udp: true
  uuid: 90be214d-048c-4ea2-a602-b8e4d4e51e36
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _279 |15.06Mb
  server: 38.180.16.86
  type: vmess
  port: 38039
  uuid: 244a3464-1269-43b3-b491-4dc2713eb3f6
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _270 |41.62Mb
  server: 89.31.120.192
  type: vmess
  port: 443
  uuid: 44537595-9ccc-4b83-8936-5f9ad3229019
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: disney_US |40.99Mb
  server: 165.140.216.141
  type: vmess
  port: 443
  uuid: e7d72a8d-26f2-4b54-b366-0c43e0bcba7d
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _277 |25.47Mb
  server: 8.218.105.196
  type: vmess
  port: 52752
  uuid: 925bdbf5-72be-4437-bebf-441c61089f6b
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: Relay_-ğŸ‡ºğŸ‡¸US_288 |27.41Mb
  server: 20251118.yixianled.com
  type: vmess
  port: 18115
  udp: true
  uuid: 6578c489-28d2-4f12-8c2f-9f2d8789626d
  alterId: 0
  cipher: auto
  network: ws
  servername: 20251118.yixianled.com
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /happy
    headers:
      Host: 20251118.yixianled.com
- name: _283 |15.81Mb
  server: 38.180.16.86
  type: vmess
  port: 36236
  uuid: a58bc1a5-8c18-49ff-9453-c331b52f45dc
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _286 |11.80Mb
  server: 130.162.152.253
  type: vmess
  port: 56867
  uuid: 5206bb9f-2cbc-44ac-de2a-471439a23707
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _299 |20.16Mb
  server: 160.16.204.136
  type: trojan
  port: 2890
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: netflix_SE |182.73Mb
  server: 70.34.218.149
  type: trojan
  port: 11930
  password: BaeSzHdfJIR13l67
  sni: softpillow.silentrocket.click
- name: _302 |49.55Mb
  server: 160.16.57.238
  type: trojan
  port: 4054
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡§ğŸ‡·BR_295 |73.02Mb
  server: pq-brazil1.09vpn.com
  type: vmess
  port: 80
  uuid: c04c3b34-70fd-4fec-963e-c12d09f36bef
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /vmess/
    headers:
      Host: pq-brazil1.09vpn.com
- name: Relay_-ğŸ‡¨ğŸ‡­CH_272 |70.50Mb
  server: lt.fxlcn.com
  type: vmess
  port: 45288
  uuid: 469e0b31-30c3-4dab-800d-711232634ce1
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: Relay_-ğŸ‡¯ğŸ‡µJP_308 |18.10Mb
  server: 160.16.87.174
  type: trojan
  port: 3169
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: _309 |35.73Mb
  server: 160.16.63.16
  type: trojan
  port: 4054
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: _314 |30.67Mb
  server: 153.121.39.240
  type: trojan
  port: 4054
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: _306 |54.33Mb
  server: 51aa8f7.p2.glados-config.net
  type: trojan
  port: 443
  udp: true
  password: ab47264dad8b0fbe
  alpn:
  - h2
  sni: n2.gladns.com
  network: grpc
  grpc-opts:
    grpc-service-name: db
- name: _315 |115.72Mb
  server: 146.70.73.210
  type: trojan
  port: 53809
  udp: true
  password: blhwsknjxmfuydz0vhfv
  sni: www.vk.com
  skip-cert-verify: true
- name: disney_netflix_GB |268.31Mb
  server: 172.67.134.185
  type: trojan
  port: 443
  udp: true
  password: POORIARED
  sni: reDfRee8.REDFree8.ir
  ws-opts:
    path: /eyJqdW5rIjoiVUl6eXhLZkkwUTJ3ZzkiLCJwcm90b2NvbCI6InRyIiwibW9kZSI6InByb3h5aXAiLCJwYW5lbElQcyI6W119?ed=2560
    headers:
      Host: reDfRee8.REDFree8.ir
  network: ws
- name: _320 |11.63Mb
  server: 160.16.116.227
  type: trojan
  port: 2760
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
  skip-cert-verify: true
- name: Relay_-ğŸ‡ºğŸ‡¸US_311 |113.17Mb
  server: 51aa8f7.p5.glados-config.net
  type: trojan
  port: 443
  udp: true
  password: ab47264dad8b0fbe
  alpn:
  - h2
  sni: n2.gladns.com
  network: grpc
  grpc-opts:
    grpc-service-name: db
- name: _322 |11.29Mb
  server: 160.16.131.243
  type: trojan
  port: 2760
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
  skip-cert-verify: true
- name: ğŸ‡¬ğŸ‡§GB_336 |201.26Mb
  server: 82.38.31.217
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: netflix_NL |218.47Mb
  server: 82.38.31.194
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡²ğŸ‡½MX_345 |43.81Mb
  server: 216.238.87.47
  type: vmess
  country: ğŸ‡²ğŸ‡½MX
  port: 27502
  uuid: b8155ce4-7e08-4c40-800f-8671312b7124
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡¬ğŸ‡§GB_338 |187.64Mb
  server: 82.38.31.191
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: disney_HK |17.98Mb
  server: 45.207.157.29
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 13852
  uuid: 845764df-ecb3-4b13-bed2-bf1551b68e9a
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_-ğŸ‡¯ğŸ‡µJP_297 |21.22Mb
  server: yg6.ygkkk.dpdns.org
  type: vmess
  port: 80
  udp: true
  uuid: 130ec091-df05-4af9-9695-dc982e98a8ec
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /130ec091-df05-4af9-9695-dc982e98a8ec-vm?ed=2048
    headers:
      Host: jporacleyg2.336697.xyz
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - _244 |20.51Mb
  - _252 |186.19Mb
  - Pool__254 |26.96Mb
  - _251 |59.79Mb
  - Relay_-ğŸ‡«ğŸ‡®FI_241 |48.75Mb
  - _273 |12.18Mb
  - _264 |153.35Mb
  - netflix_US |42.06Mb
  - _249 |56.31Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_280 |39.24Mb
  - disney_US |33.55Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_281 |40.90Mb
  - _285 |34.06Mb
  - _279 |15.06Mb
  - _270 |41.62Mb
  - disney_US |40.99Mb
  - _277 |25.47Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_288 |27.41Mb
  - _283 |15.81Mb
  - _286 |11.80Mb
  - _299 |20.16Mb
  - netflix_SE |182.73Mb
  - _302 |49.55Mb
  - Relay_-ğŸ‡§ğŸ‡·BR_295 |73.02Mb
  - Relay_-ğŸ‡¨ğŸ‡­CH_272 |70.50Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_308 |18.10Mb
  - _309 |35.73Mb
  - _314 |30.67Mb
  - _306 |54.33Mb
  - _315 |115.72Mb
  - disney_netflix_GB |268.31Mb
  - _320 |11.63Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_311 |113.17Mb
  - _322 |11.29Mb
  - ğŸ‡¬ğŸ‡§GB_336 |201.26Mb
  - netflix_NL |218.47Mb
  - ğŸ‡²ğŸ‡½MX_345 |43.81Mb
  - ğŸ‡¬ğŸ‡§GB_338 |187.64Mb
  - disney_HK |17.98Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_297 |21.22Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - _244 |20.51Mb
  - _252 |186.19Mb
  - Pool__254 |26.96Mb
  - _251 |59.79Mb
  - Relay_-ğŸ‡«ğŸ‡®FI_241 |48.75Mb
  - _273 |12.18Mb
  - _264 |153.35Mb
  - netflix_US |42.06Mb
  - _249 |56.31Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_280 |39.24Mb
  - disney_US |33.55Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_281 |40.90Mb
  - _285 |34.06Mb
  - _279 |15.06Mb
  - _270 |41.62Mb
  - disney_US |40.99Mb
  - _277 |25.47Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_288 |27.41Mb
  - _283 |15.81Mb
  - _286 |11.80Mb
  - _299 |20.16Mb
  - netflix_SE |182.73Mb
  - _302 |49.55Mb
  - Relay_-ğŸ‡§ğŸ‡·BR_295 |73.02Mb
  - Relay_-ğŸ‡¨ğŸ‡­CH_272 |70.50Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_308 |18.10Mb
  - _309 |35.73Mb
  - _314 |30.67Mb
  - _306 |54.33Mb
  - _315 |115.72Mb
  - disney_netflix_GB |268.31Mb
  - _320 |11.63Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_311 |113.17Mb
  - _322 |11.29Mb
  - ğŸ‡¬ğŸ‡§GB_336 |201.26Mb
  - netflix_NL |218.47Mb
  - ğŸ‡²ğŸ‡½MX_345 |43.81Mb
  - ğŸ‡¬ğŸ‡§GB_338 |187.64Mb
  - disney_HK |17.98Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_297 |21.22Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
