port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: _325 |47.66Mb
  server: 173.234.29.2
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _327 |33.88Mb
  server: 62.100.205.100
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _323 |44.50Mb
  server: 185.82.73.212
  type: ss
  port: 8444
  udp: true
  password: _bypfvq6ra7g4n5yCCR9DoVeGya2XUUS
  cipher: chacha20-ietf-poly1305
- name: _329 |155.67Mb
  server: 82.38.31.176
  type: ss
  port: 8080
  udp: true
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: _328 |229.34Mb
  server: 82.38.31.214
  type: ss
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: Relay_-ğŸ‡¸ğŸ‡ªSE_317 |37.94Mb
  server: 193.135.174.135
  type: ss
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _336 |360.43Mb
  server: 46.183.184.60
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: _330 |11.32Mb
  server: 103.149.183.200
  type: ss
  port: 8388
  udp: true
  password: asd123456
  cipher: chacha20-ietf
- name: _341 |47.80Mb
  server: 185.47.254.87
  type: ss
  port: 990
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: chacha20-ietf-poly1305
- name: _335 |44.33Mb
  server: 156.59.243.6
  type: ss
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _337 |12.32Mb
  server: 45.87.175.22
  type: ss
  port: 8080
  udp: true
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: Relay_-ğŸ‡¨ğŸ‡¦CA_360 |69.70Mb
  server: 79.127.200.169
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _322 |44.25Mb
  server: 103.97.203.227
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _345 |10.77Mb
  server: 82.38.31.199
  type: ss
  port: 8080
  udp: true
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: _342 |276.04Mb
  server: 45.14.245.2
  type: ss
  port: 443
  password: 17ZDORWIliQHuO6WRGHChXYMzdRtAYVP
  cipher: chacha20-ietf-poly1305
- name: _346 |231.30Mb
  server: 151.242.251.152
  type: ss
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: _332 |35.65Mb
  server: pupas-shirting-unsung.freesocks.work
  type: ss
  port: 443
  udp: true
  password: p78naCf2EfOlRSLTX0wFVx
  cipher: chacha20-ietf-poly1305
- name: _367 |72.65Mb
  server: 172.233.229.91
  type: vmess
  port: 14102
  udp: true
  uuid: 27ba87fc-583f-4763-9060-83cf0b9264db
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_HK |166.67Mb
  server: 103.149.182.158
  type: ss
  port: 8388
  password: asd123456
  cipher: chacha20-ietf
- name: _359 |16.25Mb
  server: 103.149.183.191
  type: ss
  port: 8388
  password: asd123456
  cipher: chacha20-ietf
- name: Relay_-ğŸ‡¯ğŸ‡µJP_377 |10.75Mb
  server: 160.16.117.182
  type: trojan
  port: 3169
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: _378 |10.72Mb
  server: 160.16.116.227
  type: trojan
  port: 2760
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
  skip-cert-verify: true
- name: Relay_-ğŸ‡¯ğŸ‡µJP_379 |11.60Mb
  server: 153.121.45.139
  type: trojan
  port: 3093
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: _385 |11.02Mb
  server: 160.16.131.243
  type: trojan
  port: 2760
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
  skip-cert-verify: true
- name: Relay_-ğŸ‡¯ğŸ‡µJP_387 |13.67Mb
  server: 160.16.229.223
  type: trojan
  port: 3169
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: disney_PY |17.10Mb
  server: 38.165.233.93
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: _371 |23.59Mb
  server: 47.242.145.160
  type: vmess
  port: 44457
  uuid: 40290609-2743-4d85-c9c3-4c72dd151b9f
  alterId: 0
  cipher: auto
  network: http
  http-opts:
    method: GET
    path:
    - /
  h2-opts: {}
- name: _380 |12.38Mb
  server: 219.79.214.159
  type: trojan
  port: 443
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: Relay_-ğŸ‡¯ğŸ‡µJP_390 |13.80Mb
  server: 160.16.117.182
  type: trojan
  port: 3093
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: ğŸ‡¨ğŸ‡¦CA_391 |63.72Mb
  server: 185.213.23.63
  type: ss
  country: ğŸ‡¨ğŸ‡¦CA
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: disney_DE |263.19Mb
  server: 89.163.140.136
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: disney_HK |13.86Mb
  server: 112.118.116.8
  type: trojan
  port: 443
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: ğŸ‡±ğŸ‡¹LT_404 |242.49Mb
  server: 45.87.175.185
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡®ğŸ‡¹IT_401 |17.66Mb
  server: 176.126.83.121
  type: ss
  country: ğŸ‡®ğŸ‡¹IT
  port: 443
  password: Q4t8T7hEYY3mD2Fn4wnxyK4X35AUzvR8
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_405 |199.74Mb
  server: 45.87.175.180
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: QCXDxuDlTTMD7jtgHUjIoj
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡²ğŸ‡½MX_413 |38.57Mb
  server: 216.238.87.47
  type: vmess
  country: ğŸ‡²ğŸ‡½MX
  port: 27502
  uuid: b8155ce4-7e08-4c40-800f-8671312b7124
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_HK |29.63Mb
  server: 45.207.157.29
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 13852
  uuid: 845764df-ecb3-4b13-bed2-bf1551b68e9a
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡±ğŸ‡¹LT_408 |246.76Mb
  server: 45.87.175.183
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_420 |40.99Mb
  server: 38.14.99.163
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 59807
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: auto
  network: tcp
  servername: 38.14.99.163
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡±ğŸ‡¹LT_409 |237.02Mb
  server: 45.87.175.185
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: disney_LV |78.86Mb
  server: 46.183.217.204
  type: ss
  country: ğŸ‡±ğŸ‡» LV
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡²ğŸ‡©MD_412 |61.68Mb
  server: 176.123.5.253
  type: ss
  country: ğŸ‡²ğŸ‡©MD
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡µğŸ‡¹PT_418 |31.85Mb
  server: 185.113.143.186
  type: ss
  country: ğŸ‡µğŸ‡¹PT
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_406 |10.16Mb
  server: ltnl16.saint.ydns.eu
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸZZ-ğŸ‡®ğŸ‡·IR_422 |26.13Mb
  server: cf.fovi.tk
  type: vmess
  country: ğŸZZ
  port: 443
  uuid: bf67437e-6c90-45ca-abc2-c7240a5ce2aa
  alterId: 0
  cipher: auto
  network: ws
  servername: foxlux.fovi.tk
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /eisasqa
    headers:
      HOST: foxlux.fovi.tk
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - _325 |47.66Mb
  - _327 |33.88Mb
  - _323 |44.50Mb
  - _329 |155.67Mb
  - _328 |229.34Mb
  - Relay_-ğŸ‡¸ğŸ‡ªSE_317 |37.94Mb
  - _336 |360.43Mb
  - _330 |11.32Mb
  - _341 |47.80Mb
  - _335 |44.33Mb
  - _337 |12.32Mb
  - Relay_-ğŸ‡¨ğŸ‡¦CA_360 |69.70Mb
  - _322 |44.25Mb
  - _345 |10.77Mb
  - _342 |276.04Mb
  - _346 |231.30Mb
  - _332 |35.65Mb
  - _367 |72.65Mb
  - disney_HK |166.67Mb
  - _359 |16.25Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_377 |10.75Mb
  - _378 |10.72Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_379 |11.60Mb
  - _385 |11.02Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_387 |13.67Mb
  - disney_PY |17.10Mb
  - _371 |23.59Mb
  - _380 |12.38Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_390 |13.80Mb
  - ğŸ‡¨ğŸ‡¦CA_391 |63.72Mb
  - disney_DE |263.19Mb
  - disney_HK |13.86Mb
  - ğŸ‡±ğŸ‡¹LT_404 |242.49Mb
  - ğŸ‡®ğŸ‡¹IT_401 |17.66Mb
  - ğŸ‡±ğŸ‡¹LT_405 |199.74Mb
  - ğŸ‡²ğŸ‡½MX_413 |38.57Mb
  - disney_HK |29.63Mb
  - ğŸ‡±ğŸ‡¹LT_408 |246.76Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_420 |40.99Mb
  - ğŸ‡±ğŸ‡¹LT_409 |237.02Mb
  - disney_LV |78.86Mb
  - ğŸ‡²ğŸ‡©MD_412 |61.68Mb
  - ğŸ‡µğŸ‡¹PT_418 |31.85Mb
  - ğŸ‡±ğŸ‡¹LT_406 |10.16Mb
  - Relay_ğŸZZ-ğŸ‡®ğŸ‡·IR_422 |26.13Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - _325 |47.66Mb
  - _327 |33.88Mb
  - _323 |44.50Mb
  - _329 |155.67Mb
  - _328 |229.34Mb
  - Relay_-ğŸ‡¸ğŸ‡ªSE_317 |37.94Mb
  - _336 |360.43Mb
  - _330 |11.32Mb
  - _341 |47.80Mb
  - _335 |44.33Mb
  - _337 |12.32Mb
  - Relay_-ğŸ‡¨ğŸ‡¦CA_360 |69.70Mb
  - _322 |44.25Mb
  - _345 |10.77Mb
  - _342 |276.04Mb
  - _346 |231.30Mb
  - _332 |35.65Mb
  - _367 |72.65Mb
  - disney_HK |166.67Mb
  - _359 |16.25Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_377 |10.75Mb
  - _378 |10.72Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_379 |11.60Mb
  - _385 |11.02Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_387 |13.67Mb
  - disney_PY |17.10Mb
  - _371 |23.59Mb
  - _380 |12.38Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_390 |13.80Mb
  - ğŸ‡¨ğŸ‡¦CA_391 |63.72Mb
  - disney_DE |263.19Mb
  - disney_HK |13.86Mb
  - ğŸ‡±ğŸ‡¹LT_404 |242.49Mb
  - ğŸ‡®ğŸ‡¹IT_401 |17.66Mb
  - ğŸ‡±ğŸ‡¹LT_405 |199.74Mb
  - ğŸ‡²ğŸ‡½MX_413 |38.57Mb
  - disney_HK |29.63Mb
  - ğŸ‡±ğŸ‡¹LT_408 |246.76Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_420 |40.99Mb
  - ğŸ‡±ğŸ‡¹LT_409 |237.02Mb
  - disney_LV |78.86Mb
  - ğŸ‡²ğŸ‡©MD_412 |61.68Mb
  - ğŸ‡µğŸ‡¹PT_418 |31.85Mb
  - ğŸ‡±ğŸ‡¹LT_406 |10.16Mb
  - Relay_ğŸZZ-ğŸ‡®ğŸ‡·IR_422 |26.13Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
