port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: disney_netflix_US |58.70Mb
  server: 45.150.52.40
  type: vmess
  port: 443
  uuid: c31777a1-2ee6-4864-db4c-a79fcbc8188b
  alterId: 0
  cipher: auto
  network: ws
  servername: xsj011-3.facai2024.com
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /c31777a1
- name: disney_netflix_US |150.76Mb
  server: 82.198.246.97
  type: vmess
  port: 180
  udp: true
  uuid: d13fc2f5-3e05-4795-81eb-44143a09e552
  alterId: 0
  cipher: auto
  servername: 82.198.246.97
  http-opts: {}
  h2-opts: {}
- name: disney_netflix_NO |11.30Mb
  server: 107.174.114.71
  type: ss
  port: 443
  password: 595HLF3fHUuw0McM51tpvPygSIB1uf4D
  cipher: chacha20-ietf-poly1305
- name: netflix_JP |13.83Mb
  server: 160.16.242.183
  type: trojan
  port: 1331
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: disney_netflix_HK |29.49Mb
  server: 8.218.105.196
  type: vmess
  port: 52752
  uuid: 925bdbf5-72be-4437-bebf-441c61089f6b
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
- name: disney_netflix_HK |18.21Mb
  server: 58.152.25.242
  type: trojan
  port: 443
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: disney_netflix_SG |150.10Mb
  server: 103.36.91.32
  type: ss
  port: 8388
  udp: true
  password: asd123456
  cipher: chacha20-ietf
- name: disney_netflix_HK |28.73Mb
  server: 58.152.30.120
  type: trojan
  port: 443
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: Relay_-ğŸ‡³ğŸ‡±NL_108 |12.41Mb
  server: 160.16.106.144
  type: trojan
  port: 4054
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: disney_netflix_US |429.64Mb
  server: 185.221.23.251
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 29431
  uuid: 8b78363e-3c3a-44ab-f0d8-f13d950c8572
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: _107 |16.91Mb
  server: 219.79.186.107
  type: trojan
  port: 443
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: disney_netflix_US |18.93Mb
  server: v8.hdacd.com
  type: vmess
  port: 30808
  udp: true
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: disney_netflix_FR |46.99Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 40433
  uuid: d8fd8955-78db-49ba-d86f-3e4729f6ac4d
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_SG |11.49Mb
  server: 160.16.153.13
  type: trojan
  port: 3145
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: disney_netflix_FR |240.21Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 27092
  uuid: a0596ba6-72a3-4366-8992-77088da65bd8
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_-ğŸ‡³ğŸ‡±NL_110 |25.32Mb
  server: 160.16.89.176
  type: trojan
  port: 4054
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: netflix_MX |37.58Mb
  server: 216.238.89.53
  type: vmess
  country: ğŸ‡²ğŸ‡½MX
  port: 57283
  uuid: 1a5aafc0-6482-451d-fe76-6875b7818579
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_-ğŸ‡­ğŸ‡°HK_79 |13.20Mb
  server: v10.hdacd.com
  type: vmess
  port: 30807
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: disney_netflix_NL |175.84Mb
  server: 82.38.31.184
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_US |69.78Mb
  server: 195.66.27.148
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 28709
  password: hShp1Km0NcFSmSigc8ozky
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_NL |212.14Mb
  server: 51.15.17.169
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: disney_netflix_US |71.41Mb
  server: 47.253.197.26
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 12056
  uuid: dd7be7f1-38ff-45e6-f1e5-b20c2190f527
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: netflix_IE |399.79Mb
  server: 146.70.90.196
  type: ss
  country: ğŸ‡®ğŸ‡ªIE
  port: 17454
  password: u8gp148iz90ddoo6ms37
  cipher: aes-128-gcm
- name: disney_netflix_US |26.98Mb
  server: 209.74.86.194
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 14936
  password: ppgtoOHdm7cszGunBWBTqQ
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_US |38.23Mb
  server: 38.14.99.163
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 59807
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: auto
  network: tcp
  servername: 38.14.99.163
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_SE |47.26Mb
  server: 91.186.217.246
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 31764
  password: Ftc17VH9ZXQON5vslJCYmv
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_HK |12.73Mb
  server: 45.136.12.37
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 38141
  uuid: fd291be6-b48d-43a1-da38-66c7f80e2f80
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_US |27.30Mb
  server: 209.74.81.149
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 21166
  password: q92MrrP9oJ3lMEzbQFpyuU
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_US |28.39Mb
  server: cf.fovi.tk
  type: vmess
  country: ğŸZZ
  port: 443
  uuid: bf67437e-6c90-45ca-abc2-c7240a5ce2aa
  alterId: 0
  cipher: auto
  network: ws
  servername: foxlux.fovi.tk
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /eisasqa
    headers:
      HOST: foxlux.fovi.tk
- name: disney_RU |41.66Mb
  server: 81.200.158.206
  type: ss
  country: ğŸ‡·ğŸ‡ºRU
  port: 1080
  password: AqZbt1QCs3ngEfXo1p7T-w
  cipher: chacha20-ietf-poly1305
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - disney_netflix_US |58.70Mb
  - disney_netflix_US |150.76Mb
  - disney_netflix_NO |11.30Mb
  - netflix_JP |13.83Mb
  - disney_netflix_HK |29.49Mb
  - disney_netflix_HK |18.21Mb
  - disney_netflix_SG |150.10Mb
  - disney_netflix_HK |28.73Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_108 |12.41Mb
  - disney_netflix_US |429.64Mb
  - _107 |16.91Mb
  - disney_netflix_US |18.93Mb
  - disney_netflix_FR |46.99Mb
  - disney_netflix_SG |11.49Mb
  - disney_netflix_FR |240.21Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_110 |25.32Mb
  - netflix_MX |37.58Mb
  - Relay_-ğŸ‡­ğŸ‡°HK_79 |13.20Mb
  - disney_netflix_NL |175.84Mb
  - disney_netflix_US |69.78Mb
  - disney_netflix_NL |212.14Mb
  - disney_netflix_US |71.41Mb
  - netflix_IE |399.79Mb
  - disney_netflix_US |26.98Mb
  - disney_netflix_US |38.23Mb
  - disney_netflix_SE |47.26Mb
  - disney_netflix_HK |12.73Mb
  - disney_netflix_US |27.30Mb
  - disney_netflix_US |28.39Mb
  - disney_RU |41.66Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - disney_netflix_US |58.70Mb
  - disney_netflix_US |150.76Mb
  - disney_netflix_NO |11.30Mb
  - netflix_JP |13.83Mb
  - disney_netflix_HK |29.49Mb
  - disney_netflix_HK |18.21Mb
  - disney_netflix_SG |150.10Mb
  - disney_netflix_HK |28.73Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_108 |12.41Mb
  - disney_netflix_US |429.64Mb
  - _107 |16.91Mb
  - disney_netflix_US |18.93Mb
  - disney_netflix_FR |46.99Mb
  - disney_netflix_SG |11.49Mb
  - disney_netflix_FR |240.21Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_110 |25.32Mb
  - netflix_MX |37.58Mb
  - Relay_-ğŸ‡­ğŸ‡°HK_79 |13.20Mb
  - disney_netflix_NL |175.84Mb
  - disney_netflix_US |69.78Mb
  - disney_netflix_NL |212.14Mb
  - disney_netflix_US |71.41Mb
  - netflix_IE |399.79Mb
  - disney_netflix_US |26.98Mb
  - disney_netflix_US |38.23Mb
  - disney_netflix_SE |47.26Mb
  - disney_netflix_HK |12.73Mb
  - disney_netflix_US |27.30Mb
  - disney_netflix_US |28.39Mb
  - disney_RU |41.66Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
