port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: _253 |54.98Mb
  server: 137.184.174.93
  type: ss
  port: 8080
  udp: true
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: _255 |26.55Mb
  server: 23.95.72.81
  type: ss
  port: 443
  udp: true
  password: UAMVtHm54uahd6SiN5WcD16rsPSdabPG
  cipher: chacha20-ietf-poly1305
- name: _259 |42.42Mb
  server: 104.192.226.106
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: _256 |87.21Mb
  server: 45.87.175.155
  type: ss
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: Relay_-ğŸ‡³ğŸ‡±NL_252 |204.82Mb
  server: 82.38.31.218
  type: ss
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: _258 |12.57Mb
  server: 82.38.31.176
  type: ss
  port: 8080
  udp: true
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: Relay_-ğŸ‡ºğŸ‡¸US_268 |40.49Mb
  server: 104.18.13.167
  type: vmess
  port: 443
  udp: true
  uuid: 24254866-770c-41b4-9404-3f50524f425b
  alterId: 0
  cipher: auto
  network: ws
  servername: 24254866-770c-41b4-9404-3f50524f425b.mihomo.baby
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /saoihgreg9384gh8934
    headers:
      Host: 24254866-770c-41b4-9404-3f50524f425b.mihomo.baby
- name: _264 |169.74Mb
  server: 18.203.224.78
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: Relay_-ğŸ‡ºğŸ‡¸US_274 |32.09Mb
  server: 141.193.213.199
  type: trojan
  port: 443
  udp: true
  password: a8a5b34d-fe46-487d-bd6a-d9f3101525fd
  sni: 26z68w0ecxbuyf89.ukgogo202511.top
  skip-cert-verify: true
  ws-opts:
    path: /images
    headers:
      Host: 26z68w0ecxbuyf89.ukgogo202511.top
  network: ws
- name: _248 |20.48Mb
  server: 213.159.67.124
  type: ss
  port: 443
  udp: true
  password: mbhqsStnFQT1cTZYCdsmkugGUC6GT6rp
  cipher: chacha20-ietf-poly1305
- name: _262 |86.43Mb
  server: 109.71.246.210
  type: ss
  port: 56689
  udp: true
  password: YQCSKoCF3QazW8YlvDBWA4
  cipher: chacha20-ietf-poly1305
- name: _265 |65.25Mb
  server: 82.38.31.187
  type: ss
  port: 8080
  udp: true
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: Relay_-ğŸ‡¯ğŸ‡µJP_282 |39.55Mb
  server: 141.193.213.60
  type: trojan
  port: 443
  udp: true
  password: 8b45d379-702f-41b3-a6b2-9c87a01dcd5c
  sni: a3t5vfl95f4d5d9y.catimecsgo.xyz
  skip-cert-verify: true
  ws-opts:
    path: /images
    headers:
      Host: a3t5vfl95f4d5d9y.catimecsgo.xyz
  network: ws
- name: Relay_-ğŸ‡ºğŸ‡¸US_269 |44.22Mb
  server: us19-25.998998.best
  type: vmess
  port: 443
  udp: true
  uuid: 24254866-770c-41b4-9404-3f50524f425b
  alterId: 0
  cipher: auto
  network: ws
  servername: 24254866-770c-41b4-9404-3f50524f425b.mihomo.baby
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /saoihgreg9384gh8934
    headers:
      Host: 24254866-770c-41b4-9404-3f50524f425b.mihomo.baby
- name: _249 |11.39Mb
  server: 95.111.222.113
  type: ss
  port: 443
  udp: true
  password: SVt6ZiWzRI1Yxeig4xBZwiJOt6ceXwGa
  cipher: chacha20-ietf-poly1305
- name: Relay_-ğŸ‡¯ğŸ‡µJP_276 |11.54Mb
  server: 160.16.117.182
  type: trojan
  port: 3169
  password: 2cf6d686799e6fa95316394064f26c0a
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¸ğŸ‡¬SG_284 |10.53Mb
  server: 160.16.132.158
  type: trojan
  port: 127
  password: 2cf6d686799e6fa95316394064f26c0a
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡³ğŸ‡±NL_287 |10.28Mb
  server: 160.16.89.176
  type: trojan
  port: 2890
  password: 2cf6d686799e6fa95316394064f26c0a
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡³ğŸ‡±NL_298 |39.89Mb
  server: 160.16.116.227
  type: trojan
  port: 4054
  password: 2cf6d686799e6fa95316394064f26c0a
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡³ğŸ‡±NL_299 |11.22Mb
  server: 160.16.240.91
  type: trojan
  port: 4054
  password: 2cf6d686799e6fa95316394064f26c0a
  sni: www.nintendogames.net
- name: disney_US |31.77Mb
  server: fondly.appagent.net
  type: trojan
  port: 28331
  password: RFxCa3A4zwRXcICDlYxpZR8qSS3lEN93CSYFyA3TaDIyS2aXD2leS6we5yZEOn03qcNYD
  sni: fondly.appagent.net
- name: Relay_-ğŸ‡¯ğŸ‡µJP_305 |21.96Mb
  server: 153.121.44.99
  type: trojan
  port: 3093
  password: 2cf6d686799e6fa95316394064f26c0a
  sni: www.nintendogames.net
- name: disney_DE |147.85Mb
  server: uk2-2.998998.best
  type: vmess
  port: 443
  udp: true
  uuid: 24254866-770c-41b4-9404-3f50524f425b
  alterId: 0
  cipher: auto
  network: ws
  servername: 24254866-770c-41b4-9404-3f50524f425b.placeunaorder.fun
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /logcatxiouerd34try9
    headers:
      Host: 24254866-770c-41b4-9404-3f50524f425b.placeunaorder.fun
- name: Relay_-ğŸ‡³ğŸ‡±NL_306 |10.94Mb
  server: 153.121.76.9
  type: trojan
  port: 4054
  password: 2cf6d686799e6fa95316394064f26c0a
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡°ğŸ‡·KR_261 |14.69Mb
  server: p141.panda001.net
  type: ss
  port: 4652
  udp: true
  password: qwerREWQ@@
  cipher: aes-256-cfb
- name: Relay_-ğŸ‡¯ğŸ‡µJP_308 |10.27Mb
  server: 153.121.39.240
  type: trojan
  port: 3093
  password: 2cf6d686799e6fa95316394064f26c0a
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡ºğŸ‡¸US_307 |27.12Mb
  server: usiys.southbyte.xyz
  type: trojan
  port: 5897
  udp: true
  password: fg20mtCFHy
  sni: usiys.southbyte.xyz
  skip-cert-verify: true
- name: Relay_-ğŸ‡³ğŸ‡±NL_309 |19.13Mb
  server: 160.16.70.180
  type: trojan
  port: 4054
  password: 2cf6d686799e6fa95316394064f26c0a
  sni: www.nintendogames.net
- name: disney_FR |135.42Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 27092
  uuid: a0596ba6-72a3-4366-8992-77088da65bd8
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_RU |53.72Mb
  server: 37.18.14.33
  type: trojan
  port: 443
  udp: true
  password: Qzy7tgpRhu
  sni: m.vk.com
  skip-cert-verify: true
- name: ğŸ‡¬ğŸ‡§GB_324 |202.80Mb
  server: 82.38.31.194
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: Relay_-ğŸ‡¯ğŸ‡µJP_312 |65.36Mb
  server: 153.121.45.139
  type: trojan
  port: 3093
  password: 2cf6d686799e6fa95316394064f26c0a
  sni: www.nintendogames.net
- name: ğŸ‡ºğŸ‡¸US_330 |52.59Mb
  server: 107.23.148.46
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡¬ğŸ‡§GB_325 |197.98Mb
  server: 82.38.31.191
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸ‡¬ğŸ‡§GB-ğŸ‡³ğŸ‡±NL_327 |247.37Mb
  server: 82.38.31.217
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸ‡¬ğŸ‡§GB-ğŸ‡³ğŸ‡±NL_326 |170.70Mb
  server: 82.38.31.210
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_329 |76.99Mb
  server: 45.87.175.166
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 443
  password: 1RWwXhwfAB5gAEozU4G2Pg
  cipher: chacha20-ietf-poly1305
- name: _260 |133.15Mb
  server: 45.15.126.19
  type: ss
  port: 443
  udp: true
  password: 6Ts2ZDTQAf3hkFoB8AFufDwsGrlF4e2t
  cipher: chacha20-ietf-poly1305
- name: disney_US |13.77Mb
  server: cf.fovi.tk
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  uuid: bf67437e-6c90-45ca-abc2-c7240a5ce2aa
  alterId: 0
  cipher: auto
  network: ws
  servername: foxlux.fovi.tk
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /eisasqa
    headers:
      HOST: foxlux.fovi.tk
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - _253 |54.98Mb
  - _255 |26.55Mb
  - _259 |42.42Mb
  - _256 |87.21Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_252 |204.82Mb
  - _258 |12.57Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_268 |40.49Mb
  - _264 |169.74Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_274 |32.09Mb
  - _248 |20.48Mb
  - _262 |86.43Mb
  - _265 |65.25Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_282 |39.55Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_269 |44.22Mb
  - _249 |11.39Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_276 |11.54Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_284 |10.53Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_287 |10.28Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_298 |39.89Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_299 |11.22Mb
  - disney_US |31.77Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_305 |21.96Mb
  - disney_DE |147.85Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_306 |10.94Mb
  - Relay_-ğŸ‡°ğŸ‡·KR_261 |14.69Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_308 |10.27Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_307 |27.12Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_309 |19.13Mb
  - disney_FR |135.42Mb
  - disney_RU |53.72Mb
  - ğŸ‡¬ğŸ‡§GB_324 |202.80Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_312 |65.36Mb
  - ğŸ‡ºğŸ‡¸US_330 |52.59Mb
  - ğŸ‡¬ğŸ‡§GB_325 |197.98Mb
  - Relay_ğŸ‡¬ğŸ‡§GB-ğŸ‡³ğŸ‡±NL_327 |247.37Mb
  - Relay_ğŸ‡¬ğŸ‡§GB-ğŸ‡³ğŸ‡±NL_326 |170.70Mb
  - ğŸ‡±ğŸ‡¹LT_329 |76.99Mb
  - _260 |133.15Mb
  - disney_US |13.77Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - _253 |54.98Mb
  - _255 |26.55Mb
  - _259 |42.42Mb
  - _256 |87.21Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_252 |204.82Mb
  - _258 |12.57Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_268 |40.49Mb
  - _264 |169.74Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_274 |32.09Mb
  - _248 |20.48Mb
  - _262 |86.43Mb
  - _265 |65.25Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_282 |39.55Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_269 |44.22Mb
  - _249 |11.39Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_276 |11.54Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_284 |10.53Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_287 |10.28Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_298 |39.89Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_299 |11.22Mb
  - disney_US |31.77Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_305 |21.96Mb
  - disney_DE |147.85Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_306 |10.94Mb
  - Relay_-ğŸ‡°ğŸ‡·KR_261 |14.69Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_308 |10.27Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_307 |27.12Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_309 |19.13Mb
  - disney_FR |135.42Mb
  - disney_RU |53.72Mb
  - ğŸ‡¬ğŸ‡§GB_324 |202.80Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_312 |65.36Mb
  - ğŸ‡ºğŸ‡¸US_330 |52.59Mb
  - ğŸ‡¬ğŸ‡§GB_325 |197.98Mb
  - Relay_ğŸ‡¬ğŸ‡§GB-ğŸ‡³ğŸ‡±NL_327 |247.37Mb
  - Relay_ğŸ‡¬ğŸ‡§GB-ğŸ‡³ğŸ‡±NL_326 |170.70Mb
  - ğŸ‡±ğŸ‡¹LT_329 |76.99Mb
  - _260 |133.15Mb
  - disney_US |13.77Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
