port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: _303 |40.21Mb
  server: 172.235.33.114
  type: vmess
  port: 10001
  uuid: 442a3923-eca1-4af0-b3ff-24a7ce0af68f
  alterId: 0
  cipher: auto
  network: tcp
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_-ğŸ‡³ğŸ‡±NL_307 |10.55Mb
  server: 160.16.196.59
  type: trojan
  port: 2760
  password: 2cf6d686799e6fa95316394064f26c0a
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡³ğŸ‡±NL_313 |56.70Mb
  server: 160.16.204.136
  type: trojan
  port: 2890
  password: 2cf6d686799e6fa95316394064f26c0a
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡³ğŸ‡±NL_314 |54.75Mb
  server: 160.16.89.176
  type: trojan
  port: 2890
  password: 2cf6d686799e6fa95316394064f26c0a
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡ºğŸ‡¸US_321 |36.00Mb
  server: 141.193.213.199
  type: trojan
  port: 443
  udp: true
  password: a8a5b34d-fe46-487d-bd6a-d9f3101525fd
  sni: 26z68w0ecxbuyf89.ukgogo202511.top
  skip-cert-verify: true
  ws-opts:
    path: /images
    headers:
      Host: 26z68w0ecxbuyf89.ukgogo202511.top
  network: ws
- name: Relay_-ğŸ‡¸ğŸ‡¬SG_315 |13.11Mb
  server: 160.16.89.176
  type: trojan
  port: 127
  password: 2cf6d686799e6fa95316394064f26c0a
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡³ğŸ‡±NL_293 |248.07Mb
  server: 82.38.31.218
  type: ss
  port: 8080
  udp: true
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: _298 |248.65Mb
  server: 45.87.175.177
  type: ss
  port: 8080
  udp: true
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: netflix_NL |239.40Mb
  server: 151.242.251.144
  type: ss
  port: 8080
  udp: true
  password: QCXDxuDlTTMD7jtgHUjIoj
  cipher: chacha20-ietf-poly1305
- name: _291 |124.80Mb
  server: 45.15.126.19
  type: ss
  port: 443
  udp: true
  password: 6Ts2ZDTQAf3hkFoB8AFufDwsGrlF4e2t
  cipher: chacha20-ietf-poly1305
- name: Relay_-ğŸ‡¯ğŸ‡µJP_317 |10.72Mb
  server: 160.16.204.136
  type: trojan
  port: 3169
  password: 2cf6d686799e6fa95316394064f26c0a
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡³ğŸ‡±NL_318 |23.67Mb
  server: 160.16.196.59
  type: trojan
  port: 4054
  password: 2cf6d686799e6fa95316394064f26c0a
  sni: www.nintendogames.net
- name: disney_FR |66.84Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 27092
  uuid: a0596ba6-72a3-4366-8992-77088da65bd8
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: netflix_NL |390.86Mb
  server: 151.242.251.153
  type: ss
  country: ğŸ‡®ğŸ‡· IR
  port: 8080
  password: QCXDxuDlTTMD7jtgHUjIoj
  cipher: chacha20-ietf-poly1305
- name: netflix_NL |314.67Mb
  server: 151.242.251.144
  type: ss
  country: ğŸ‡®ğŸ‡· IR
  port: 8080
  password: 4a2rfixophdjffa8KVA4Aa
  cipher: chacha20-ietf-poly1305
- name: _299 |16.61Mb
  server: 103.106.3.82
  type: ss
  port: 443
  udp: true
  password: 4SaCIazlgumYkM8FkPzlmwjpyWBDZFBk
  cipher: chacha20-ietf-poly1305
- name: Relay_-ğŸ‡ºğŸ‡¸US_304 |49.06Mb
  server: us19-25.998998.best
  type: vmess
  port: 443
  udp: true
  uuid: 24254866-770c-41b4-9404-3f50524f425b
  alterId: 0
  cipher: auto
  network: ws
  servername: 24254866-770c-41b4-9404-3f50524f425b.mihomo.baby
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /saoihgreg9384gh8934
    headers:
      Host: 24254866-770c-41b4-9404-3f50524f425b.mihomo.baby
- name: Relay_ğŸ‡¯ğŸ‡µJP-ğŸ‡¯ğŸ‡µJP_327 |11.70Mb
  server: xray.kk37005.tk
  type: vmess
  country: ğŸ‡¯ğŸ‡µJP
  port: 55919
  uuid: 2e7548bb-7c5b-4d97-d64d-1b2fe4050089
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - _303 |40.21Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_307 |10.55Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_313 |56.70Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_314 |54.75Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_321 |36.00Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_315 |13.11Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_293 |248.07Mb
  - _298 |248.65Mb
  - netflix_NL |239.40Mb
  - _291 |124.80Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_317 |10.72Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_318 |23.67Mb
  - disney_FR |66.84Mb
  - netflix_NL |390.86Mb
  - netflix_NL |314.67Mb
  - _299 |16.61Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_304 |49.06Mb
  - Relay_ğŸ‡¯ğŸ‡µJP-ğŸ‡¯ğŸ‡µJP_327 |11.70Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - _303 |40.21Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_307 |10.55Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_313 |56.70Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_314 |54.75Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_321 |36.00Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_315 |13.11Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_293 |248.07Mb
  - _298 |248.65Mb
  - netflix_NL |239.40Mb
  - _291 |124.80Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_317 |10.72Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_318 |23.67Mb
  - disney_FR |66.84Mb
  - netflix_NL |390.86Mb
  - netflix_NL |314.67Mb
  - _299 |16.61Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_304 |49.06Mb
  - Relay_ğŸ‡¯ğŸ‡µJP-ğŸ‡¯ğŸ‡µJP_327 |11.70Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
