port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: Relay_-ğŸ‡ºğŸ‡¸US_526 |40.77Mb
  server: 38.14.99.179
  type: vmess
  port: 59807
  udp: true
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_-ğŸ‡³ğŸ‡±NL_487 |240.25Mb
  server: 151.242.251.137
  type: ss
  port: 8080
  password: o5osZg269v5zHpYjr1xY9s
  cipher: chacha20-ietf-poly1305
- name: Relay_-ğŸ‡¯ğŸ‡µJP_680 |13.05Mb
  server: 153.121.65.107
  type: trojan
  port: 1331
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: _488 |133.39Mb
  server: 103.149.182.38
  type: ss
  port: 8388
  udp: true
  password: asd123456
  cipher: chacha20-ietf
- name: Relay_-ğŸ‡³ğŸ‡±NL_681 |29.89Mb
  server: 160.16.63.16
  type: trojan
  port: 4054
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: _489 |36.08Mb
  server: 188.253.124.53
  type: ss
  port: 63257
  udp: true
  password: RenzheCloudSS
  cipher: rc4-md5
  plugin: obfs
  plugin-opts:
    host: d1bf8290613.microsoft.com
    mode: http
- name: _491 |97.16Mb
  server: 185.231.233.112
  type: ss
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: Relay_-ğŸ‡³ğŸ‡±NL_683 |10.19Mb
  server: 160.16.151.196
  type: trojan
  port: 2890
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡ºğŸ‡¸US_560 |11.70Mb
  server: v8.hdacd.com
  type: vmess
  port: 30808
  udp: true
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_-ğŸ‡³ğŸ‡±NL_685 |10.43Mb
  server: 160.16.236.32
  type: trojan
  port: 4054
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¸ğŸ‡¬SG_689 |12.88Mb
  server: 160.16.107.37
  type: trojan
  port: 507
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¯ğŸ‡µJP_686 |19.10Mb
  server: 160.16.87.174
  type: trojan
  port: 3169
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: _684 |21.08Mb
  server: 68.183.231.236
  type: trojan
  port: 443
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¯ğŸ‡µJP_691 |22.28Mb
  server: 160.16.70.180
  type: trojan
  port: 1331
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡³ğŸ‡±NL_692 |42.03Mb
  server: 160.16.81.84
  type: trojan
  port: 4054
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡ºğŸ‡¸US_518 |17.15Mb
  server: v29.hdacd.com
  type: vmess
  port: 30829
  udp: true
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_-ğŸ‡¸ğŸ‡¬SG_695 |13.38Mb
  server: 160.16.131.243
  type: trojan
  port: 127
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¯ğŸ‡µJP_700 |15.20Mb
  server: 153.121.38.213
  type: trojan
  port: 1331
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¯ğŸ‡µJP_701 |13.34Mb
  server: 153.121.45.139
  type: trojan
  port: 1331
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡³ğŸ‡±NL_703 |14.46Mb
  server: 153.121.39.240
  type: trojan
  port: 4054
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¸ğŸ‡¬SG_702 |11.06Mb
  server: 160.16.212.152
  type: trojan
  port: 507
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: disney_FR |176.05Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 40433
  uuid: d8fd8955-78db-49ba-d86f-3e4729f6ac4d
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡§ğŸ‡·BR_707 |117.07Mb
  server: 38.180.16.86
  type: vmess
  country: ğŸ‡§ğŸ‡·BR
  port: 36104
  uuid: E146A8CB-9D2F-449C-ADCA-8736FB
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_-ğŸ‡³ğŸ‡±NL_704 |15.92Mb
  server: 160.16.124.55
  type: trojan
  port: 4054
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: disney_FR |228.88Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 27092
  uuid: a0596ba6-72a3-4366-8992-77088da65bd8
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡¬ğŸ‡§GB_712 |153.29Mb
  server: 82.38.31.190
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸ‡¬ğŸ‡§GB-ğŸ‡³ğŸ‡±NL_714 |226.34Mb
  server: 82.38.31.218
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸ‡¬ğŸ‡§GB-ğŸ‡³ğŸ‡±NL_715 |232.78Mb
  server: 82.38.31.210
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡­ğŸ‡°HK_726 |56.22Mb
  server: 87.121.162.249
  type: ss
  country: ğŸ‡­ğŸ‡°HK
  port: 443
  password: JGv616hMWdjfuZ00jYfq7XkBHJZrOBrg
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡­ğŸ‡°HK_735 |177.64Mb
  server: 47.243.51.237
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 52801
  uuid: ef93f413-9039-4ddb-aefb-2490287df55a
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
  ws-opts:
    path: /arki?ed=2048
- name: ğŸ‡­ğŸ‡°HK_754 |151.65Mb
  server: 8.218.116.26
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 32228
  uuid: e4767e9f-ed00-4f31-a984-a918bdd9b09c
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡­ğŸ‡°HK_757 |83.84Mb
  server: 8.210.134.183
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 3721
  uuid: e72f5c6b-220f-40b3-a115-2d81473458cf
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
  ws-opts:
    path: /
- name: ğŸ‡°ğŸ‡·KR_780 |10.22Mb
  server: 146.56.112.110
  type: vmess
  country: ğŸ‡°ğŸ‡·KR
  port: 8888
  uuid: e7c302f3-90d6-42dd-9d7d-94a3683a3707
  alterId: 0
  cipher: auto
  network: tcp
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡­ğŸ‡°HK_771 |116.40Mb
  server: 47.242.140.52
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 48219
  uuid: 006893c6-79b1-4c44-94ff-b8bbea065f1f
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
  ws-opts:
    path: /arki?ed=2048
- name: ğŸ‡²ğŸ‡½MX_783 |36.98Mb
  server: 216.238.89.53
  type: vmess
  country: ğŸ‡²ğŸ‡½MX
  port: 57283
  uuid: 1a5aafc0-6482-451d-fe76-6875b7818579
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡±ğŸ‡¹LT_782 |171.65Mb
  server: 45.87.175.166
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 443
  password: 1RWwXhwfAB5gAEozU4G2Pg
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡®ğŸ‡³IN_778 |130.56Mb
  server: 134.209.147.198
  type: ss
  country: ğŸ‡®ğŸ‡³IN
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: disney_RU |305.31Mb
  server: 38.60.223.8
  type: ss
  country: ğŸ‡·ğŸ‡ºRU
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ğŸ‡ºğŸ‡¸US_791 |145.86Mb
  server: 45.12.136.170
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: l668XHPejoSNNuD66BYzyehaCpZexiF7
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸ‡°ğŸ‡·KR-ğŸ‡°ğŸ‡·KR_781 |14.52Mb
  server: seoul03.zgjok.com
  type: vmess
  country: ğŸ‡°ğŸ‡·KR
  port: 443
  uuid: 72a0dac4-9689-4a57-b164-5c65bfa94772
  alterId: 0
  cipher: auto
  network: ws
  servername: seoul03.zgjok.com
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /
    headers:
      HOST: seoul03.zgjok.com
- name: ğŸ‡²ğŸ‡¾MY_784 |31.12Mb
  server: 38.54.98.110
  type: vmess
  country: ğŸ‡²ğŸ‡¾MY
  port: 2052
  uuid: 665d9b8f-153d-4907-adac-de12afd9c851
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: ğŸ‡ºğŸ‡¸US_794 |42.06Mb
  server: 104.192.226.106
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: Relay_ğŸ‡¯ğŸ‡µJP-ğŸ‡¯ğŸ‡µJP_779 |13.49Mb
  server: kuame.missionsec.us
  type: trojan
  country: ğŸ‡¯ğŸ‡µJP
  port: 443
  udp: true
  password: FDIypSwe64a3DA7un2R8DFjYXZO3NS05gKZTTOC8SxO0Fy3cqYg3EaFDA3ABaEYKNx39D
  sni: kuame.missionsec.us
  skip-cert-verify: true
- name: ğŸ‡¸ğŸ‡¬SG_787 |11.34Mb
  server: 68.183.178.131
  type: vmess
  country: ğŸ‡¸ğŸ‡¬SG
  port: 58607
  uuid: c11c32cb-27b3-4afa-c0f3-fb250aa4959e
  alterId: 0
  cipher: auto
  network: ws
  servername: www.12333.monster
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /
    headers:
      HOST: www.12333.monster
- name: Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_797 |40.07Mb
  server: 38.14.99.163
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 59807
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: auto
  network: tcp
  servername: 38.14.99.163
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡ºğŸ‡¸US_796 |179.03Mb
  server: 45.136.12.37
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 38141
  uuid: fd291be6-b48d-43a1-da38-66c7f80e2f80
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_795 |26.42Mb
  server: cf.fovi.tk
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  uuid: bf67437e-6c90-45ca-abc2-c7240a5ce2aa
  alterId: 0
  cipher: auto
  network: ws
  servername: foxlux.fovi.tk
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /eisasqa
    headers:
      HOST: foxlux.fovi.tk
- name: Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡·ğŸ‡ºRU_790 |32.41Mb
  server: clr.ducks.tel
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 17847
  password: '907560230'
  cipher: chacha20-ietf-poly1305
- name: disney_DE |12.93Mb
  server: clr.ducks.tel
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 17844
  password: '907560230'
  cipher: chacha20-ietf-poly1305
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - Relay_-ğŸ‡ºğŸ‡¸US_526 |40.77Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_487 |240.25Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_680 |13.05Mb
  - _488 |133.39Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_681 |29.89Mb
  - _489 |36.08Mb
  - _491 |97.16Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_683 |10.19Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_560 |11.70Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_685 |10.43Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_689 |12.88Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_686 |19.10Mb
  - _684 |21.08Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_691 |22.28Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_692 |42.03Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_518 |17.15Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_695 |13.38Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_700 |15.20Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_701 |13.34Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_703 |14.46Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_702 |11.06Mb
  - disney_FR |176.05Mb
  - ğŸ‡§ğŸ‡·BR_707 |117.07Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_704 |15.92Mb
  - disney_FR |228.88Mb
  - ğŸ‡¬ğŸ‡§GB_712 |153.29Mb
  - Relay_ğŸ‡¬ğŸ‡§GB-ğŸ‡³ğŸ‡±NL_714 |226.34Mb
  - Relay_ğŸ‡¬ğŸ‡§GB-ğŸ‡³ğŸ‡±NL_715 |232.78Mb
  - ğŸ‡­ğŸ‡°HK_726 |56.22Mb
  - ğŸ‡­ğŸ‡°HK_735 |177.64Mb
  - ğŸ‡­ğŸ‡°HK_754 |151.65Mb
  - ğŸ‡­ğŸ‡°HK_757 |83.84Mb
  - ğŸ‡°ğŸ‡·KR_780 |10.22Mb
  - ğŸ‡­ğŸ‡°HK_771 |116.40Mb
  - ğŸ‡²ğŸ‡½MX_783 |36.98Mb
  - ğŸ‡±ğŸ‡¹LT_782 |171.65Mb
  - ğŸ‡®ğŸ‡³IN_778 |130.56Mb
  - disney_RU |305.31Mb
  - ğŸ‡ºğŸ‡¸US_791 |145.86Mb
  - Relay_ğŸ‡°ğŸ‡·KR-ğŸ‡°ğŸ‡·KR_781 |14.52Mb
  - ğŸ‡²ğŸ‡¾MY_784 |31.12Mb
  - ğŸ‡ºğŸ‡¸US_794 |42.06Mb
  - Relay_ğŸ‡¯ğŸ‡µJP-ğŸ‡¯ğŸ‡µJP_779 |13.49Mb
  - ğŸ‡¸ğŸ‡¬SG_787 |11.34Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_797 |40.07Mb
  - ğŸ‡ºğŸ‡¸US_796 |179.03Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_795 |26.42Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡·ğŸ‡ºRU_790 |32.41Mb
  - disney_DE |12.93Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - Relay_-ğŸ‡ºğŸ‡¸US_526 |40.77Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_487 |240.25Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_680 |13.05Mb
  - _488 |133.39Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_681 |29.89Mb
  - _489 |36.08Mb
  - _491 |97.16Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_683 |10.19Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_560 |11.70Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_685 |10.43Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_689 |12.88Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_686 |19.10Mb
  - _684 |21.08Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_691 |22.28Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_692 |42.03Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_518 |17.15Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_695 |13.38Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_700 |15.20Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_701 |13.34Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_703 |14.46Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_702 |11.06Mb
  - disney_FR |176.05Mb
  - ğŸ‡§ğŸ‡·BR_707 |117.07Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_704 |15.92Mb
  - disney_FR |228.88Mb
  - ğŸ‡¬ğŸ‡§GB_712 |153.29Mb
  - Relay_ğŸ‡¬ğŸ‡§GB-ğŸ‡³ğŸ‡±NL_714 |226.34Mb
  - Relay_ğŸ‡¬ğŸ‡§GB-ğŸ‡³ğŸ‡±NL_715 |232.78Mb
  - ğŸ‡­ğŸ‡°HK_726 |56.22Mb
  - ğŸ‡­ğŸ‡°HK_735 |177.64Mb
  - ğŸ‡­ğŸ‡°HK_754 |151.65Mb
  - ğŸ‡­ğŸ‡°HK_757 |83.84Mb
  - ğŸ‡°ğŸ‡·KR_780 |10.22Mb
  - ğŸ‡­ğŸ‡°HK_771 |116.40Mb
  - ğŸ‡²ğŸ‡½MX_783 |36.98Mb
  - ğŸ‡±ğŸ‡¹LT_782 |171.65Mb
  - ğŸ‡®ğŸ‡³IN_778 |130.56Mb
  - disney_RU |305.31Mb
  - ğŸ‡ºğŸ‡¸US_791 |145.86Mb
  - Relay_ğŸ‡°ğŸ‡·KR-ğŸ‡°ğŸ‡·KR_781 |14.52Mb
  - ğŸ‡²ğŸ‡¾MY_784 |31.12Mb
  - ğŸ‡ºğŸ‡¸US_794 |42.06Mb
  - Relay_ğŸ‡¯ğŸ‡µJP-ğŸ‡¯ğŸ‡µJP_779 |13.49Mb
  - ğŸ‡¸ğŸ‡¬SG_787 |11.34Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_797 |40.07Mb
  - ğŸ‡ºğŸ‡¸US_796 |179.03Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_795 |26.42Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡·ğŸ‡ºRU_790 |32.41Mb
  - disney_DE |12.93Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
