port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: _300 |41.34Mb
  server: 104.192.226.106
  type: ss
  port: 990
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: chacha20-ietf-poly1305
- name: netflix_US |53.56Mb
  server: 156.146.38.167
  type: ss
  port: 443
  udp: true
  password: shadowsocks
  cipher: aes-128-gcm
- name: _294 |49.99Mb
  server: 156.146.38.169
  type: ss
  port: 443
  udp: true
  password: shadowsocks
  cipher: aes-128-gcm
- name: _301 |47.99Mb
  server: 156.146.38.170
  type: ss
  port: 443
  udp: true
  password: shadowsocks
  cipher: aes-128-gcm
- name: _293 |53.10Mb
  server: 137.184.174.93
  type: ss
  port: 8080
  udp: true
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: _299 |177.53Mb
  server: 45.87.175.28
  type: ss
  port: 8080
  udp: true
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: netflix_NL |249.68Mb
  server: 151.242.251.142
  type: ss
  port: 8080
  udp: true
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: _306 |21.10Mb
  server: 149.22.87.241
  type: ss
  port: 443
  udp: true
  password: shadowsocks
  cipher: aes-128-gcm
- name: netflix_NL |248.19Mb
  server: 82.38.31.179
  type: ss
  port: 8080
  udp: true
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: _307 |40.00Mb
  server: 193.29.139.206
  type: ss
  port: 8080
  udp: true
  password: 4a2rfixophdjffa8KVA4Aa
  cipher: chacha20-ietf-poly1305
- name: _283 |197.20Mb
  server: 146.70.61.37
  type: ss
  port: 8080
  udp: true
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: _288 |23.08Mb
  server: 192.71.249.78
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: _305 |33.04Mb
  server: 134.209.147.198
  type: ss
  port: 990
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: chacha20-ietf-poly1305
- name: _312 |12.68Mb
  server: 62.100.205.100
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _309 |28.12Mb
  server: 119.59.98.58
  type: ss
  port: 990
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: chacha20-ietf-poly1305
- name: _311 |30.84Mb
  server: 119.59.98.58
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: _325 |20.22Mb
  server: 172.105.199.111
  type: ss
  port: 8080
  udp: true
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: _308 |102.07Mb
  server: 134.209.147.198
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: _317 |223.28Mb
  server: 45.14.245.2
  type: ss
  port: 443
  password: 17ZDORWIliQHuO6WRGHChXYMzdRtAYVP
  cipher: chacha20-ietf-poly1305
- name: netflix_NL |223.67Mb
  server: 151.242.251.152
  type: ss
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: _329 |50.85Mb
  server: 15.157.66.237
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: _320 |22.68Mb
  server: 172.237.74.36
  type: ss
  port: 443
  udp: true
  password: Dk0XrU/n+SB84g0k+mX4zdy5HVVhuAUP6pCaldJxQjY=
  cipher: aes-256-gcm
- name: _314 |43.32Mb
  server: 147.78.0.182
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: netflix_AT |132.19Mb
  server: 5.181.21.246
  type: ss
  port: 443
  udp: true
  password: gKYygTcRYhc3skc2x6tZ073lYz0DnieX
  cipher: chacha20-ietf-poly1305
- name: _341 |77.05Mb
  server: 103.35.189.136
  type: ss
  port: 443
  udp: true
  password: SS2QvbC9nqLp2sXXZo0BVy4slcErRuCt
  cipher: chacha20-ietf-poly1305
- name: disney_MX |25.72Mb
  server: 38.165.231.25
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: disney_US |69.80Mb
  server: 79.127.200.162
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: _338 |198.68Mb
  server: 151.242.251.147
  type: ss
  port: 8080
  password: QCXDxuDlTTMD7jtgHUjIoj
  cipher: chacha20-ietf-poly1305
- name: Relay_-ğŸ‡¨ğŸ‡¦CA_351 |68.15Mb
  server: 79.127.200.169
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: disney_PY |11.91Mb
  server: 38.165.233.93
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: _345 |28.15Mb
  server: 82.38.31.190
  type: ss
  port: 8080
  udp: true
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: _348 |12.12Mb
  server: 103.149.182.158
  type: ss
  port: 8388
  password: asd123456
  cipher: chacha20-ietf
- name: netflix_NL |168.53Mb
  server: 45.87.175.178
  type: ss
  port: 8080
  udp: true
  password: QCXDxuDlTTMD7jtgHUjIoj
  cipher: chacha20-ietf-poly1305
- name: _349 |11.92Mb
  server: 185.192.124.188
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: _340 |145.97Mb
  server: 141.98.101.178
  type: ss
  port: 443
  udp: true
  password: shadowsocks
  cipher: aes-128-gcm
- name: _355 |147.79Mb
  server: 82.38.31.214
  type: ss
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: disney_SG |18.59Mb
  server: 38.89.142.56
  type: ss
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: netflix_US |47.41Mb
  server: 172.233.229.91
  type: vmess
  port: 14102
  udp: true
  uuid: 27ba87fc-583f-4763-9060-83cf0b9264db
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: _362 |17.52Mb
  server: 196.196.192.58
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: Relay_-ğŸ‡­ğŸ‡°HK_383 |14.68Mb
  server: 104.19.61.72
  type: vmess
  port: 443
  uuid: 4bf075f5-4d5e-4d39-f5ab-b32a86250f0e
  alterId: 0
  cipher: auto
  network: ws
  servername: hk.nbee.pp.ua
  http-opts: {}
  h2-opts: {}
  tls: true
  ws-opts:
    path: /aa
    headers:
      Host: hk.nbee.pp.ua
- name: _359 |214.73Mb
  server: 82.38.31.194
  type: ss
  port: 8080
  udp: true
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: disney_US |37.85Mb
  server: 165.140.216.141
  type: vmess
  port: 443
  uuid: e7d72a8d-26f2-4b54-b366-0c43e0bcba7d
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: netflix_NL |376.37Mb
  server: 51.15.23.166
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: _377 |10.54Mb
  server: 146.56.112.110
  type: vmess
  port: 8888
  uuid: e7c302f3-90d6-42dd-9d7d-94a3683a3707
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _379 |50.36Mb
  server: 209.126.84.189
  type: vmess
  port: 443
  uuid: 2c981164-9b93-4bca-94ff-b78d3f8498d7
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /vmessws
- name: _378 |10.64Mb
  server: 54.206.192.9
  type: vmess
  port: 16407
  uuid: 08f45028-1db6-4e93-bf51-d344b6c71e19
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: disney_SG |22.56Mb
  server: 185.36.192.228
  type: vmess
  port: 35488
  uuid: fb5a4283-dbfb-458b-8619-c4a53739f781
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
- name: _380 |27.67Mb
  server: v2ray.codefyinc.com
  type: vmess
  port: 443
  uuid: 2c981164-9b93-4bca-94ff-b78d3f8498d7
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /vmessws
    headers:
      Host: v2ray.codefyinc.com
- name: _364 |44.45Mb
  server: 156.59.243.6
  type: ss
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: Pool__421 |24.18Mb
  server: 38.96.254.102
  type: trojan
  port: 18509
  password: .ie4rghJuMkcf0oF
  sni: shoppingmall.electricbanana.click
- name: _391 |21.88Mb
  server: 47.243.29.191
  type: vmess
  port: 13141
  uuid: 67126fa6-ecaa-4699-d5e7-515d968b33a9
  alterId: 0
  cipher: auto
  network: http
  http-opts:
    method: GET
    path:
    - /
  h2-opts: {}
- name: _402 |10.84Mb
  server: 160.16.236.32
  type: trojan
  port: 2760
  password: 44e660b0ee21cf3ac66aee2c08af85d2
  sni: www.nintendogames.net
  skip-cert-verify: true
- name: _405 |11.25Mb
  server: 202.181.103.246
  type: trojan
  port: 2760
  password: 44e660b0ee21cf3ac66aee2c08af85d2
  sni: www.nintendogames.net
  skip-cert-verify: true
- name: _408 |10.64Mb
  server: 160.16.136.130
  type: trojan
  port: 2760
  password: 44e660b0ee21cf3ac66aee2c08af85d2
  sni: www.nintendogames.net
  skip-cert-verify: true
- name: disney_US |12.64Mb
  server: 206.119.191.9
  type: vmess
  port: 7100
  uuid: 10853485-26e1-477b-d257-58a3f4873db3
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
- name: _387 |25.81Mb
  server: 89.31.120.192
  type: vmess
  port: 443
  uuid: 44537595-9ccc-4b83-8936-5f9ad3229019
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: Relay_-ğŸ‡ºğŸ‡¸US_385 |32.26Mb
  server: v4.hdacd.com
  type: vmess
  port: 30804
  udp: true
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: _425 |10.75Mb
  server: 160.16.57.238
  type: trojan
  port: 2760
  password: 44e660b0ee21cf3ac66aee2c08af85d2
  sni: www.nintendogames.net
  skip-cert-verify: true
- name: Pool__423 |183.46Mb
  server: 70.34.218.149
  type: trojan
  port: 11930
  password: BaeSzHdfJIR13l67
  sni: softpillow.silentrocket.click
- name: ğŸ‡¨ğŸ‡¦CA_477 |20.20Mb
  server: 193.203.203.66
  type: ss
  country: ğŸ‡¨ğŸ‡¦CA
  port: 443
  password: S6jUK9Fw5fMHgNqlqXObHZWv8Tf4nEkm
  cipher: chacha20-ietf-poly1305
- name: Relay_-ğŸ‡¯ğŸ‡µJP_438 |18.95Mb
  server: 153.121.67.215
  type: trojan
  port: 3093
  password: 44e660b0ee21cf3ac66aee2c08af85d2
  sni: www.nintendogames.net
- name: disney_HK |26.64Mb
  server: 219.79.214.159
  type: trojan
  port: 443
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: _434 |10.83Mb
  server: 112.118.116.8
  type: trojan
  port: 443
  password: 44e660b0ee21cf3ac66aee2c08af85d2
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡­ğŸ‡°HK_415 |10.68Mb
  server: cdnfire.xiaomispeed.com
  type: trojan
  port: 21101
  udp: true
  password: d785b966-115d-4a20-b740-b04c984bbdd6
  sni: cdnfire.xiaomispeed.com
- name: ğŸ‡¨ğŸ‡¦CA_476 |25.76Mb
  server: 185.213.23.63
  type: ss
  country: ğŸ‡¨ğŸ‡¦CA
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡§ğŸ‡·BR_475 |11.83Mb
  server: 185.192.124.188
  type: ss
  country: ğŸ‡§ğŸ‡·BR
  port: 990
  password: f8f7aCzcPKbsF8p3
  cipher: chacha20-ietf-poly1305
- name: disney_DE |857.36Mb
  server: 89.163.140.136
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ğŸ‡¨ğŸ‡±CL_478 |12.56Mb
  server: 154.205.153.107
  type: ss
  country: ğŸ‡¨ğŸ‡±CL
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_487 |44.98Mb
  server: 141.98.101.182
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: shadowsocks
  cipher: aes-128-gcm
- name: disney_HK |25.04Mb
  server: 45.207.157.29
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 13852
  uuid: 845764df-ecb3-4b13-bed2-bf1551b68e9a
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: netflix_NL |131.80Mb
  server: 45.87.175.178
  type: ss
  country: ğŸ‡±ğŸ‡¹ LT
  port: 8080
  password: 4a2rfixophdjffa8KVA4Aa
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹ LT_535 |163.87Mb
  server: 45.87.175.178
  type: ss
  country: ğŸ‡±ğŸ‡¹ LT
  port: 8080
  password: 1RWwXhwfAB5gAEozU4G2Pg
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸ‡¯ğŸ‡µJP-ğŸ‡¯ğŸ‡µJP_529 |10.75Mb
  server: xray.kk37005.tk
  type: vmess
  country: ğŸ‡¯ğŸ‡µJP
  port: 55919
  uuid: 2e7548bb-7c5b-4d97-d64d-1b2fe4050089
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: ğŸ‡±ğŸ‡¹ LT_536 |112.04Mb
  server: 45.87.175.178
  type: ss
  country: ğŸ‡±ğŸ‡¹ LT
  port: 8080
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_539 |111.15Mb
  server: 45.87.175.185
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_540 |231.53Mb
  server: 45.87.175.183
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_542 |221.60Mb
  server: 45.87.175.185
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡²ğŸ‡½MX_548 |37.09Mb
  server: 216.238.86.158
  type: vmess
  country: ğŸ‡²ğŸ‡½MX
  port: 34460
  uuid: 90be214d-048c-4ea2-a602-b8e4d4e51e36
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡²ğŸ‡½MX_549 |37.21Mb
  server: 216.238.87.47
  type: vmess
  country: ğŸ‡²ğŸ‡½MX
  port: 27502
  uuid: b8155ce4-7e08-4c40-800f-8671312b7124
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡±ğŸ‡¹LT_543 |169.50Mb
  server: 45.87.175.180
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: QCXDxuDlTTMD7jtgHUjIoj
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡» LV_545 |37.38Mb
  server: 46.183.217.204
  type: ss
  country: ğŸ‡±ğŸ‡» LV
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡²ğŸ‡©MD_546 |22.58Mb
  server: 176.123.5.253
  type: ss
  country: ğŸ‡²ğŸ‡©MD
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡³ğŸ‡±NL_551 |137.07Mb
  server: 178.23.190.238
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 443
  password: uo7EbtqIwgZXXHmMv5LbLcOxptyPlNkh
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡³ğŸ‡±NL_552 |59.33Mb
  server: 193.29.139.141
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 8080
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡µğŸ‡¹PT_556 |47.23Mb
  server: 185.113.143.186
  type: ss
  country: ğŸ‡µğŸ‡¹PT
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸ‡­ğŸ‡°HK-ğŸ‡­ğŸ‡°HK_523 |21.77Mb
  server: n1761214918.74qxv.top
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 443
  uuid: b141803a-209c-47bd-be6e-14d6bc1e96be
  alterId: 0
  cipher: auto
  network: ws
  servername: n1761214918.74qxv.top
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /
    headers:
      HOST: n1761214918.74qxv.top
- name: ğŸ‡±ğŸ‡¹LT_538 |20.39Mb
  server: ltnl16.saint.ydns.eu
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: _331 |16.60Mb
  server: 89.23.103.60
  type: ss
  port: 1234
  udp: true
  password: PgJV4yRPpGpoV-40PS8N0G6gS4BpBRkF
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_541 |27.98Mb
  server: 45.87.175.175
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: QCXDxuDlTTMD7jtgHUjIoj
  cipher: chacha20-ietf-poly1305
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - _300 |41.34Mb
  - netflix_US |53.56Mb
  - _294 |49.99Mb
  - _301 |47.99Mb
  - _293 |53.10Mb
  - _299 |177.53Mb
  - netflix_NL |249.68Mb
  - _306 |21.10Mb
  - netflix_NL |248.19Mb
  - _307 |40.00Mb
  - _283 |197.20Mb
  - _288 |23.08Mb
  - _305 |33.04Mb
  - _312 |12.68Mb
  - _309 |28.12Mb
  - _311 |30.84Mb
  - _325 |20.22Mb
  - _308 |102.07Mb
  - _317 |223.28Mb
  - netflix_NL |223.67Mb
  - _329 |50.85Mb
  - _320 |22.68Mb
  - _314 |43.32Mb
  - netflix_AT |132.19Mb
  - _341 |77.05Mb
  - disney_MX |25.72Mb
  - disney_US |69.80Mb
  - _338 |198.68Mb
  - Relay_-ğŸ‡¨ğŸ‡¦CA_351 |68.15Mb
  - disney_PY |11.91Mb
  - _345 |28.15Mb
  - _348 |12.12Mb
  - netflix_NL |168.53Mb
  - _349 |11.92Mb
  - _340 |145.97Mb
  - _355 |147.79Mb
  - disney_SG |18.59Mb
  - netflix_US |47.41Mb
  - _362 |17.52Mb
  - Relay_-ğŸ‡­ğŸ‡°HK_383 |14.68Mb
  - _359 |214.73Mb
  - disney_US |37.85Mb
  - netflix_NL |376.37Mb
  - _377 |10.54Mb
  - _379 |50.36Mb
  - _378 |10.64Mb
  - disney_SG |22.56Mb
  - _380 |27.67Mb
  - _364 |44.45Mb
  - Pool__421 |24.18Mb
  - _391 |21.88Mb
  - _402 |10.84Mb
  - _405 |11.25Mb
  - _408 |10.64Mb
  - disney_US |12.64Mb
  - _387 |25.81Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_385 |32.26Mb
  - _425 |10.75Mb
  - Pool__423 |183.46Mb
  - ğŸ‡¨ğŸ‡¦CA_477 |20.20Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_438 |18.95Mb
  - disney_HK |26.64Mb
  - _434 |10.83Mb
  - Relay_-ğŸ‡­ğŸ‡°HK_415 |10.68Mb
  - ğŸ‡¨ğŸ‡¦CA_476 |25.76Mb
  - ğŸ‡§ğŸ‡·BR_475 |11.83Mb
  - disney_DE |857.36Mb
  - ğŸ‡¨ğŸ‡±CL_478 |12.56Mb
  - ğŸ‡¬ğŸ‡§GB_487 |44.98Mb
  - disney_HK |25.04Mb
  - netflix_NL |131.80Mb
  - ğŸ‡±ğŸ‡¹ LT_535 |163.87Mb
  - Relay_ğŸ‡¯ğŸ‡µJP-ğŸ‡¯ğŸ‡µJP_529 |10.75Mb
  - ğŸ‡±ğŸ‡¹ LT_536 |112.04Mb
  - ğŸ‡±ğŸ‡¹LT_539 |111.15Mb
  - ğŸ‡±ğŸ‡¹LT_540 |231.53Mb
  - ğŸ‡±ğŸ‡¹LT_542 |221.60Mb
  - ğŸ‡²ğŸ‡½MX_548 |37.09Mb
  - ğŸ‡²ğŸ‡½MX_549 |37.21Mb
  - ğŸ‡±ğŸ‡¹LT_543 |169.50Mb
  - ğŸ‡±ğŸ‡» LV_545 |37.38Mb
  - ğŸ‡²ğŸ‡©MD_546 |22.58Mb
  - ğŸ‡³ğŸ‡±NL_551 |137.07Mb
  - ğŸ‡³ğŸ‡±NL_552 |59.33Mb
  - ğŸ‡µğŸ‡¹PT_556 |47.23Mb
  - Relay_ğŸ‡­ğŸ‡°HK-ğŸ‡­ğŸ‡°HK_523 |21.77Mb
  - ğŸ‡±ğŸ‡¹LT_538 |20.39Mb
  - _331 |16.60Mb
  - ğŸ‡±ğŸ‡¹LT_541 |27.98Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - _300 |41.34Mb
  - netflix_US |53.56Mb
  - _294 |49.99Mb
  - _301 |47.99Mb
  - _293 |53.10Mb
  - _299 |177.53Mb
  - netflix_NL |249.68Mb
  - _306 |21.10Mb
  - netflix_NL |248.19Mb
  - _307 |40.00Mb
  - _283 |197.20Mb
  - _288 |23.08Mb
  - _305 |33.04Mb
  - _312 |12.68Mb
  - _309 |28.12Mb
  - _311 |30.84Mb
  - _325 |20.22Mb
  - _308 |102.07Mb
  - _317 |223.28Mb
  - netflix_NL |223.67Mb
  - _329 |50.85Mb
  - _320 |22.68Mb
  - _314 |43.32Mb
  - netflix_AT |132.19Mb
  - _341 |77.05Mb
  - disney_MX |25.72Mb
  - disney_US |69.80Mb
  - _338 |198.68Mb
  - Relay_-ğŸ‡¨ğŸ‡¦CA_351 |68.15Mb
  - disney_PY |11.91Mb
  - _345 |28.15Mb
  - _348 |12.12Mb
  - netflix_NL |168.53Mb
  - _349 |11.92Mb
  - _340 |145.97Mb
  - _355 |147.79Mb
  - disney_SG |18.59Mb
  - netflix_US |47.41Mb
  - _362 |17.52Mb
  - Relay_-ğŸ‡­ğŸ‡°HK_383 |14.68Mb
  - _359 |214.73Mb
  - disney_US |37.85Mb
  - netflix_NL |376.37Mb
  - _377 |10.54Mb
  - _379 |50.36Mb
  - _378 |10.64Mb
  - disney_SG |22.56Mb
  - _380 |27.67Mb
  - _364 |44.45Mb
  - Pool__421 |24.18Mb
  - _391 |21.88Mb
  - _402 |10.84Mb
  - _405 |11.25Mb
  - _408 |10.64Mb
  - disney_US |12.64Mb
  - _387 |25.81Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_385 |32.26Mb
  - _425 |10.75Mb
  - Pool__423 |183.46Mb
  - ğŸ‡¨ğŸ‡¦CA_477 |20.20Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_438 |18.95Mb
  - disney_HK |26.64Mb
  - _434 |10.83Mb
  - Relay_-ğŸ‡­ğŸ‡°HK_415 |10.68Mb
  - ğŸ‡¨ğŸ‡¦CA_476 |25.76Mb
  - ğŸ‡§ğŸ‡·BR_475 |11.83Mb
  - disney_DE |857.36Mb
  - ğŸ‡¨ğŸ‡±CL_478 |12.56Mb
  - ğŸ‡¬ğŸ‡§GB_487 |44.98Mb
  - disney_HK |25.04Mb
  - netflix_NL |131.80Mb
  - ğŸ‡±ğŸ‡¹ LT_535 |163.87Mb
  - Relay_ğŸ‡¯ğŸ‡µJP-ğŸ‡¯ğŸ‡µJP_529 |10.75Mb
  - ğŸ‡±ğŸ‡¹ LT_536 |112.04Mb
  - ğŸ‡±ğŸ‡¹LT_539 |111.15Mb
  - ğŸ‡±ğŸ‡¹LT_540 |231.53Mb
  - ğŸ‡±ğŸ‡¹LT_542 |221.60Mb
  - ğŸ‡²ğŸ‡½MX_548 |37.09Mb
  - ğŸ‡²ğŸ‡½MX_549 |37.21Mb
  - ğŸ‡±ğŸ‡¹LT_543 |169.50Mb
  - ğŸ‡±ğŸ‡» LV_545 |37.38Mb
  - ğŸ‡²ğŸ‡©MD_546 |22.58Mb
  - ğŸ‡³ğŸ‡±NL_551 |137.07Mb
  - ğŸ‡³ğŸ‡±NL_552 |59.33Mb
  - ğŸ‡µğŸ‡¹PT_556 |47.23Mb
  - Relay_ğŸ‡­ğŸ‡°HK-ğŸ‡­ğŸ‡°HK_523 |21.77Mb
  - ğŸ‡±ğŸ‡¹LT_538 |20.39Mb
  - _331 |16.60Mb
  - ğŸ‡±ğŸ‡¹LT_541 |27.98Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
