port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: Relay_-ğŸ‡ºğŸ‡¸US_520 |51.05Mb
  server: us19-25.998998.best
  type: vmess
  port: 443
  udp: true
  uuid: 24254866-770c-41b4-9404-3f50524f425b
  alterId: 0
  cipher: auto
  network: ws
  servername: 24254866-770c-41b4-9404-3f50524f425b.mihomo.baby
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /saoihgreg9384gh8934
    headers:
      Host: 24254866-770c-41b4-9404-3f50524f425b.mihomo.baby
- name: Relay_-ğŸ‡³ğŸ‡±NL_510 |281.03Mb
  server: 151.242.251.144
  type: ss
  port: 8080
  udp: true
  password: QCXDxuDlTTMD7jtgHUjIoj
  cipher: chacha20-ietf-poly1305
- name: Relay_-ğŸ‡³ğŸ‡±NL_514 |295.35Mb
  server: 82.38.31.218
  type: ss
  port: 8080
  udp: true
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: _513 |185.79Mb
  server: 45.87.175.177
  type: ss
  port: 8080
  udp: true
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: Relay_-ğŸ‡ºğŸ‡¸US_533 |47.53Mb
  server: 141.193.213.199
  type: trojan
  port: 443
  udp: true
  password: a8a5b34d-fe46-487d-bd6a-d9f3101525fd
  sni: 26z68w0ecxbuyf89.ukgogo202511.top
  skip-cert-verify: true
  ws-opts:
    path: /images
    headers:
      Host: 26z68w0ecxbuyf89.ukgogo202511.top
  network: ws
- name: _522 |35.48Mb
  server: 172.235.33.114
  type: vmess
  port: 10001
  uuid: 442a3923-eca1-4af0-b3ff-24a7ce0af68f
  alterId: 0
  cipher: auto
  network: tcp
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_PT |14.92Mb
  server: 185.231.233.112
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: _511 |29.69Mb
  server: 213.159.67.124
  type: ss
  port: 443
  password: mbhqsStnFQT1cTZYCdsmkugGUC6GT6rp
  cipher: chacha20-ietf-poly1305
- name: disney_US |30.37Mb
  server: 158.101.11.204
  type: trojan
  port: 15805
  udp: true
  password: iwangjie
  sni: nodes.830901.xyz
  ws-opts:
    path: /?ed=2560
    headers:
      Host: nodes.830901.xyz
  network: ws
- name: Relay_-ğŸ‡¯ğŸ‡µJP_534 |10.99Mb
  server: 160.16.138.24
  type: trojan
  port: 3169
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡ºğŸ‡¸US_518 |34.26Mb
  server: w10.luoli.de
  type: vmess
  port: 443
  udp: true
  uuid: 42a99644-b90b-3627-8809-a2d6c4078b59
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  tls: true
  ws-opts:
    path: /v2ws
    headers:
      Host: w10.luoli.de
- name: disney_RU |28.23Mb
  server: 37.18.14.33
  type: trojan
  port: 443
  udp: true
  password: Qzy7tgpRhu
  sni: m.vk.com
  skip-cert-verify: true
- name: Relay_-ğŸ‡¯ğŸ‡µJP_521 |10.78Mb
  server: w13.luoli.de
  type: vmess
  port: 443
  udp: true
  uuid: 42a99644-b90b-3627-8809-a2d6c4078b59
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  tls: true
  ws-opts:
    path: /v2ws
    headers:
      Host: w13.luoli.de
- name: Relay_-ğŸ‡³ğŸ‡±NL_539 |36.28Mb
  server: 18.162.142.242
  type: trojan
  port: 4054
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡³ğŸ‡±NL_546 |40.95Mb
  server: 160.16.214.6
  type: trojan
  port: 4054
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: disney_FR |130.70Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 27092
  uuid: a0596ba6-72a3-4366-8992-77088da65bd8
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_ğŸ‡®ğŸ‡· IR-ğŸ‡³ğŸ‡±NL_554 |264.75Mb
  server: 151.242.251.153
  type: ss
  country: ğŸ‡®ğŸ‡· IR
  port: 8080
  password: QCXDxuDlTTMD7jtgHUjIoj
  cipher: chacha20-ietf-poly1305
- name: Relay_-ğŸ‡­ğŸ‡°HK_528 |10.43Mb
  server: green2.cdntencentmusic.com
  type: trojan
  port: 31102
  udp: true
  password: 7ca90727-8867-47aa-9486-70dbd06d9e32
  sni: green2.cdntencentmusic.com
  skip-cert-verify: true
- name: Relay_-ğŸ‡­ğŸ‡°HK_543 |10.31Mb
  server: green2.cdntencentmusic.com
  type: trojan
  port: 31102
  udp: true
  password: 4a269dea-f3dd-48d8-86aa-39596e68d71d
  sni: green2.cdntencentmusic.com
  skip-cert-verify: true
- name: Relay_-ğŸ‡¯ğŸ‡µJP_519 |11.90Mb
  server: npofb-g03.jp01-nn-vm0.entry.fr0528.art
  type: vmess
  port: 21583
  udp: true
  uuid: 5c44094f-43bb-301c-9878-37fd5e87d358
  alterId: 1
  cipher: auto
  http-opts: {}
  h2-opts: {}
  tls: true
- name: Relay_ğŸ‡®ğŸ‡· IR-ğŸ‡³ğŸ‡±NL_555 |254.92Mb
  server: 151.242.251.144
  type: ss
  country: ğŸ‡®ğŸ‡· IR
  port: 8080
  password: 4a2rfixophdjffa8KVA4Aa
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸ‡¯ğŸ‡µJP-ğŸ‡¯ğŸ‡µJP_556 |11.26Mb
  server: xray.kk37005.tk
  type: vmess
  country: ğŸ‡¯ğŸ‡µJP
  port: 55919
  uuid: 2e7548bb-7c5b-4d97-d64d-1b2fe4050089
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: disney_PY |154.23Mb
  server: 38.165.233.93
  type: ss
  country: ğŸ‡ºğŸ‡¸ US
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_564 |33.04Mb
  server: sw19.sesamebuta.top
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  uuid: 805ba514-bf2f-4d5d-df49-8417804e8de3
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /abcd
- name: _507 |10.69Mb
  server: 45.93.95.187
  type: ss
  port: 8618
  udp: true
  password: 4lUEC91c1d8oeClzDbYpXA
  cipher: chacha20-ietf-poly1305
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - Relay_-ğŸ‡ºğŸ‡¸US_520 |51.05Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_510 |281.03Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_514 |295.35Mb
  - _513 |185.79Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_533 |47.53Mb
  - _522 |35.48Mb
  - disney_PT |14.92Mb
  - _511 |29.69Mb
  - disney_US |30.37Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_534 |10.99Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_518 |34.26Mb
  - disney_RU |28.23Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_521 |10.78Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_539 |36.28Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_546 |40.95Mb
  - disney_FR |130.70Mb
  - Relay_ğŸ‡®ğŸ‡· IR-ğŸ‡³ğŸ‡±NL_554 |264.75Mb
  - Relay_-ğŸ‡­ğŸ‡°HK_528 |10.43Mb
  - Relay_-ğŸ‡­ğŸ‡°HK_543 |10.31Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_519 |11.90Mb
  - Relay_ğŸ‡®ğŸ‡· IR-ğŸ‡³ğŸ‡±NL_555 |254.92Mb
  - Relay_ğŸ‡¯ğŸ‡µJP-ğŸ‡¯ğŸ‡µJP_556 |11.26Mb
  - disney_PY |154.23Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_564 |33.04Mb
  - _507 |10.69Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - Relay_-ğŸ‡ºğŸ‡¸US_520 |51.05Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_510 |281.03Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_514 |295.35Mb
  - _513 |185.79Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_533 |47.53Mb
  - _522 |35.48Mb
  - disney_PT |14.92Mb
  - _511 |29.69Mb
  - disney_US |30.37Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_534 |10.99Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_518 |34.26Mb
  - disney_RU |28.23Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_521 |10.78Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_539 |36.28Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_546 |40.95Mb
  - disney_FR |130.70Mb
  - Relay_ğŸ‡®ğŸ‡· IR-ğŸ‡³ğŸ‡±NL_554 |264.75Mb
  - Relay_-ğŸ‡­ğŸ‡°HK_528 |10.43Mb
  - Relay_-ğŸ‡­ğŸ‡°HK_543 |10.31Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_519 |11.90Mb
  - Relay_ğŸ‡®ğŸ‡· IR-ğŸ‡³ğŸ‡±NL_555 |254.92Mb
  - Relay_ğŸ‡¯ğŸ‡µJP-ğŸ‡¯ğŸ‡µJP_556 |11.26Mb
  - disney_PY |154.23Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_564 |33.04Mb
  - _507 |10.69Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
