port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: _296 |52.53Mb
  server: 137.184.174.93
  type: ss
  port: 8080
  udp: true
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: _303 |14.21Mb
  server: 23.95.72.81
  type: ss
  port: 443
  udp: true
  password: UAMVtHm54uahd6SiN5WcD16rsPSdabPG
  cipher: chacha20-ietf-poly1305
- name: _299 |42.54Mb
  server: 104.192.226.106
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: Relay_-ğŸ‡ºğŸ‡¸US_310 |32.93Mb
  server: 104.18.13.167
  type: vmess
  port: 443
  udp: true
  uuid: 24254866-770c-41b4-9404-3f50524f425b
  alterId: 0
  cipher: auto
  network: ws
  servername: 24254866-770c-41b4-9404-3f50524f425b.mihomo.baby
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /saoihgreg9384gh8934
    headers:
      Host: 24254866-770c-41b4-9404-3f50524f425b.mihomo.baby
- name: Relay_-ğŸ‡ºğŸ‡¸US_308 |12.90Mb
  server: 82.198.246.97
  type: vmess
  port: 180
  uuid: d13fc2f5-3e05-4795-81eb-44143a09e552
  alterId: 0
  cipher: auto
  network: tcp
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_-ğŸ‡ºğŸ‡¸US_324 |42.56Mb
  server: 141.193.213.199
  type: trojan
  port: 443
  udp: true
  password: a544940a-2c1c-4723-96cc-d03053a95530
  sni: 26z68w0ecxbuyf89.ukgogo202511.top
  skip-cert-verify: true
  ws-opts:
    path: /images
    headers:
      Host: 26z68w0ecxbuyf89.ukgogo202511.top
  network: ws
- name: Relay_-ğŸ‡³ğŸ‡±NL_289 |252.43Mb
  server: 82.38.31.218
  type: ss
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: _295 |13.28Mb
  server: 82.38.31.176
  type: ss
  port: 8080
  udp: true
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: _288 |13.28Mb
  server: 45.14.245.2
  type: ss
  port: 443
  udp: true
  password: 17ZDORWIliQHuO6WRGHChXYMzdRtAYVP
  cipher: chacha20-ietf-poly1305
- name: _297 |11.81Mb
  server: 45.87.175.155
  type: ss
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: _290 |125.67Mb
  server: 45.15.126.19
  type: ss
  port: 443
  udp: true
  password: 6Ts2ZDTQAf3hkFoB8AFufDwsGrlF4e2t
  cipher: chacha20-ietf-poly1305
- name: netflix_US |30.15Mb
  server: us19-25.998998.best
  type: vmess
  port: 443
  udp: true
  uuid: 24254866-770c-41b4-9404-3f50524f425b
  alterId: 0
  cipher: auto
  network: ws
  servername: 24254866-770c-41b4-9404-3f50524f425b.mihomo.baby
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /saoihgreg9384gh8934
    headers:
      Host: 24254866-770c-41b4-9404-3f50524f425b.mihomo.baby
- name: Relay_-ğŸ‡¯ğŸ‡µJP_322 |13.64Mb
  server: 160.16.106.144
  type: trojan
  port: 3169
  password: 2cf6d686799e6fa95316394064f26c0a
  sni: www.nintendogames.net
- name: _294 |10.64Mb
  server: 95.111.222.113
  type: ss
  port: 443
  udp: true
  password: SVt6ZiWzRI1Yxeig4xBZwiJOt6ceXwGa
  cipher: chacha20-ietf-poly1305
- name: Relay_-ğŸ‡³ğŸ‡±NL_331 |13.15Mb
  server: 160.16.240.91
  type: trojan
  port: 4054
  password: 2cf6d686799e6fa95316394064f26c0a
  sni: www.nintendogames.net
- name: netflix_US |31.86Mb
  server: usiys.southbyte.xyz
  type: trojan
  port: 5897
  udp: true
  password: fg20mtCFHy
  sni: usiys.southbyte.xyz
  skip-cert-verify: true
- name: disney_netflix_DE |80.15Mb
  server: uk2-2.998998.best
  type: vmess
  port: 443
  udp: true
  uuid: 24254866-770c-41b4-9404-3f50524f425b
  alterId: 0
  cipher: auto
  network: ws
  servername: 24254866-770c-41b4-9404-3f50524f425b.placeunaorder.fun
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /logcatxiouerd34try9
    headers:
      Host: 24254866-770c-41b4-9404-3f50524f425b.placeunaorder.fun
- name: Relay_-ğŸ‡¸ğŸ‡¬SG_342 |18.96Mb
  server: 160.16.106.144
  type: trojan
  port: 127
  password: 2cf6d686799e6fa95316394064f26c0a
  sni: www.nintendogames.net
- name: ğŸ‡ºğŸ‡¸US_367 |47.97Mb
  server: 107.23.148.46
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: netflix_FR |125.94Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 27092
  uuid: a0596ba6-72a3-4366-8992-77088da65bd8
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_RU |13.89Mb
  server: 37.18.14.33
  type: trojan
  port: 443
  udp: true
  password: Qzy7tgpRhu
  sni: m.vk.com
  skip-cert-verify: true
- name: netflix_NL |340.40Mb
  server: 82.38.31.210
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: netflix_NL |12.91Mb
  server: 82.38.31.217
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_364 |300.57Mb
  server: 82.38.31.194
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹ LT_365 |22.42Mb
  server: 45.87.175.174
  type: ss
  country: ğŸ‡±ğŸ‡¹ LT
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: netflix_NL |76.36Mb
  server: 82.38.31.191
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: disney_HK |10.60Mb
  server: cdnfire.xiaomispeed.com
  type: trojan
  port: 21102
  udp: true
  password: dfde1bb1-41b7-4a1e-b757-7aa2378ccf4d
  sni: cdnfire.xiaomispeed.com
  skip-cert-verify: true
- name: disney_HK |10.48Mb
  server: cdnfire.xiaomispeed.com
  type: trojan
  port: 21104
  udp: true
  password: dfde1bb1-41b7-4a1e-b757-7aa2378ccf4d
  sni: cdnfire.xiaomispeed.com
  skip-cert-verify: true
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - _296 |52.53Mb
  - _303 |14.21Mb
  - _299 |42.54Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_310 |32.93Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_308 |12.90Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_324 |42.56Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_289 |252.43Mb
  - _295 |13.28Mb
  - _288 |13.28Mb
  - _297 |11.81Mb
  - _290 |125.67Mb
  - netflix_US |30.15Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_322 |13.64Mb
  - _294 |10.64Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_331 |13.15Mb
  - netflix_US |31.86Mb
  - disney_netflix_DE |80.15Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_342 |18.96Mb
  - ğŸ‡ºğŸ‡¸US_367 |47.97Mb
  - netflix_FR |125.94Mb
  - disney_RU |13.89Mb
  - netflix_NL |340.40Mb
  - netflix_NL |12.91Mb
  - ğŸ‡¬ğŸ‡§GB_364 |300.57Mb
  - ğŸ‡±ğŸ‡¹ LT_365 |22.42Mb
  - netflix_NL |76.36Mb
  - disney_HK |10.60Mb
  - disney_HK |10.48Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - _296 |52.53Mb
  - _303 |14.21Mb
  - _299 |42.54Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_310 |32.93Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_308 |12.90Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_324 |42.56Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_289 |252.43Mb
  - _295 |13.28Mb
  - _288 |13.28Mb
  - _297 |11.81Mb
  - _290 |125.67Mb
  - netflix_US |30.15Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_322 |13.64Mb
  - _294 |10.64Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_331 |13.15Mb
  - netflix_US |31.86Mb
  - disney_netflix_DE |80.15Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_342 |18.96Mb
  - ğŸ‡ºğŸ‡¸US_367 |47.97Mb
  - netflix_FR |125.94Mb
  - disney_RU |13.89Mb
  - netflix_NL |340.40Mb
  - netflix_NL |12.91Mb
  - ğŸ‡¬ğŸ‡§GB_364 |300.57Mb
  - ğŸ‡±ğŸ‡¹ LT_365 |22.42Mb
  - netflix_NL |76.36Mb
  - disney_HK |10.60Mb
  - disney_HK |10.48Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
