port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: disney_netflix_US |234.50Mb
  server: 67.209.177.69
  type: ss
  port: 26351
  password: 57dtozbdQRZT9MaL
  cipher: aes-256-gcm
- name: Relay_-ğŸ‡ºğŸ‡¸US_181 |39.42Mb
  server: 38.14.99.179
  type: vmess
  port: 59807
  udp: true
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: _187 |10.08Mb
  server: 74.117.196.232
  type: vmess
  port: 37934
  udp: true
  uuid: 27104fae-f047-4993-902a-9368d8a3e9bc
  alterId: 0
  cipher: auto
  network: ws
  servername: imafake.locker
  http-opts: {}
  h2-opts: {}
  tls: true
  ws-opts:
    path: /speedtest
- name: disney_netflix_NL |218.45Mb
  server: 151.242.251.137
  type: ss
  port: 8080
  password: o5osZg269v5zHpYjr1xY9s
  cipher: chacha20-ietf-poly1305
- name: Relay_-ğŸ‡¯ğŸ‡µJP_200 |12.39Mb
  server: 160.16.70.180
  type: trojan
  port: 1331
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡³ğŸ‡±NL_201 |61.96Mb
  server: 160.16.131.243
  type: trojan
  port: 2890
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¯ğŸ‡µJP_203 |12.31Mb
  server: 160.16.130.66
  type: trojan
  port: 3093
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¯ğŸ‡µJP_202 |19.03Mb
  server: 153.121.65.107
  type: trojan
  port: 3169
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡³ğŸ‡±NL_204 |10.07Mb
  server: 160.16.63.16
  type: trojan
  port: 4054
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: disney_PT |138.28Mb
  server: 185.231.233.112
  type: ss
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: Relay_-ğŸ‡ºğŸ‡¸US_209 |11.42Mb
  server: 160.16.150.76
  type: trojan
  port: 1596
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡ºğŸ‡¸US_206 |19.07Mb
  server: 160.16.68.250
  type: trojan
  port: 1596
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: disney_US |61.39Mb
  server: 23.247.137.64
  type: trojan
  port: 443
  udp: true
  password: 3c4e10af98c30972
  sni: n2.gladns.com
  network: grpc
  grpc-opts:
    grpc-service-name: db
- name: Relay_-ğŸ‡³ğŸ‡±NL_210 |47.28Mb
  server: 160.16.124.55
  type: trojan
  port: 4054
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡³ğŸ‡±NL_207 |10.55Mb
  server: 16.163.0.29
  type: trojan
  port: 4054
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: disney_FR |123.56Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 27092
  uuid: a0596ba6-72a3-4366-8992-77088da65bd8
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_FR |50.56Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 40433
  uuid: d8fd8955-78db-49ba-d86f-3e4729f6ac4d
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_-ğŸ‡¸ğŸ‡¬SG_211 |11.98Mb
  server: 160.16.131.243
  type: trojan
  port: 127
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡³ğŸ‡±NL_213 |59.31Mb
  server: 160.16.236.32
  type: trojan
  port: 4054
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡³ğŸ‡±NL_212 |46.88Mb
  server: 160.16.81.84
  type: trojan
  port: 4054
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡³ğŸ‡±NL_214 |45.92Mb
  server: 160.16.57.238
  type: trojan
  port: 4054
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: disney_netflix_NL |185.44Mb
  server: 82.38.31.210
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: Relay_-ğŸ‡³ğŸ‡±NL_220 |11.46Mb
  server: 160.16.151.196
  type: trojan
  port: 2890
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: disney_HK |12.67Mb
  server: 112.118.116.66
  type: trojan
  port: 443
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: disney_HK |28.47Mb
  server: 58.152.18.78
  type: trojan
  port: 443
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: netflix_AL |43.01Mb
  server: 87.121.162.249
  type: ss
  country: ğŸ‡­ğŸ‡°HK
  port: 443
  password: JGv616hMWdjfuZ00jYfq7XkBHJZrOBrg
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡²ğŸ‡½MX_252 |146.49Mb
  server: 216.238.89.53
  type: vmess
  country: ğŸ‡²ğŸ‡½MX
  port: 57283
  uuid: 1a5aafc0-6482-451d-fe76-6875b7818579
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_NL |98.11Mb
  server: 45.87.175.166
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 443
  password: 1RWwXhwfAB5gAEozU4G2Pg
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡­ğŸ‡°HK_236 |22.61Mb
  server: 47.242.140.52
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 48219
  uuid: 006893c6-79b1-4c44-94ff-b8bbea065f1f
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
  ws-opts:
    path: /arki?ed=2048
- name: disney_netflix_NL |134.58Mb
  server: 109.71.246.210
  type: ss
  country: ğŸ‡·ğŸ‡ºRU
  port: 56689
  password: YQCSKoCF3QazW8YlvDBWA4
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡­ğŸ‡°HK_240 |26.13Mb
  server: 8.218.116.26
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 32228
  uuid: e4767e9f-ed00-4f31-a984-a918bdd9b09c
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡­ğŸ‡°HK_235 |28.30Mb
  server: 47.243.51.237
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 52801
  uuid: ef93f413-9039-4ddb-aefb-2490287df55a
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
  ws-opts:
    path: /arki?ed=2048
- name: ğŸ‡°ğŸ‡·KR_250 |11.78Mb
  server: 146.56.112.110
  type: vmess
  country: ğŸ‡°ğŸ‡·KR
  port: 8888
  uuid: e7c302f3-90d6-42dd-9d7d-94a3683a3707
  alterId: 0
  cipher: auto
  network: tcp
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_US |139.77Mb
  server: 38.84.201.21
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 53487
  uuid: c3c1ec05-df2c-4975-9b42-e9b007564eb1
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_264 |38.97Mb
  server: 38.14.99.163
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 59807
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: auto
  network: tcp
  servername: 38.14.99.163
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡ºğŸ‡¸US_267 |87.68Mb
  server: 74.117.196.232
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 37934
  uuid: 3b475934-cb2a-4d96-b260-5e50cca5d430
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /speedtest
- name: Relay_ğŸ‡°ğŸ‡·KR-ğŸ‡°ğŸ‡·KR_249 |10.76Mb
  server: seoul03.zgjok.com
  type: vmess
  country: ğŸ‡°ğŸ‡·KR
  port: 443
  uuid: 72a0dac4-9689-4a57-b164-5c65bfa94772
  alterId: 0
  cipher: auto
  network: ws
  servername: seoul03.zgjok.com
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /
    headers:
      HOST: seoul03.zgjok.com
- name: ğŸ‡²ğŸ‡¾MY_253 |32.00Mb
  server: 38.54.98.110
  type: vmess
  country: ğŸ‡²ğŸ‡¾MY
  port: 2052
  uuid: 665d9b8f-153d-4907-adac-de12afd9c851
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: disney_HK |24.48Mb
  server: 45.136.12.37
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 38141
  uuid: fd291be6-b48d-43a1-da38-66c7f80e2f80
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡¸ğŸ‡¬SG_255 |10.93Mb
  server: 68.183.178.131
  type: vmess
  country: ğŸ‡¸ğŸ‡¬SG
  port: 58607
  uuid: c11c32cb-27b3-4afa-c0f3-fb250aa4959e
  alterId: 0
  cipher: auto
  network: ws
  servername: www.12333.monster
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /
    headers:
      HOST: www.12333.monster
- name: disney_US |105.86Mb
  server: cf.fovi.tk
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  uuid: bf67437e-6c90-45ca-abc2-c7240a5ce2aa
  alterId: 0
  cipher: auto
  network: ws
  servername: foxlux.fovi.tk
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /eisasqa
    headers:
      HOST: foxlux.fovi.tk
- name: disney_netflix_NL |233.79Mb
  server: 82.38.31.190
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - disney_netflix_US |234.50Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_181 |39.42Mb
  - _187 |10.08Mb
  - disney_netflix_NL |218.45Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_200 |12.39Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_201 |61.96Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_203 |12.31Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_202 |19.03Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_204 |10.07Mb
  - disney_PT |138.28Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_209 |11.42Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_206 |19.07Mb
  - disney_US |61.39Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_210 |47.28Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_207 |10.55Mb
  - disney_FR |123.56Mb
  - disney_FR |50.56Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_211 |11.98Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_213 |59.31Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_212 |46.88Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_214 |45.92Mb
  - disney_netflix_NL |185.44Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_220 |11.46Mb
  - disney_HK |12.67Mb
  - disney_HK |28.47Mb
  - netflix_AL |43.01Mb
  - ğŸ‡²ğŸ‡½MX_252 |146.49Mb
  - disney_netflix_NL |98.11Mb
  - ğŸ‡­ğŸ‡°HK_236 |22.61Mb
  - disney_netflix_NL |134.58Mb
  - ğŸ‡­ğŸ‡°HK_240 |26.13Mb
  - ğŸ‡­ğŸ‡°HK_235 |28.30Mb
  - ğŸ‡°ğŸ‡·KR_250 |11.78Mb
  - disney_netflix_US |139.77Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_264 |38.97Mb
  - ğŸ‡ºğŸ‡¸US_267 |87.68Mb
  - Relay_ğŸ‡°ğŸ‡·KR-ğŸ‡°ğŸ‡·KR_249 |10.76Mb
  - ğŸ‡²ğŸ‡¾MY_253 |32.00Mb
  - disney_HK |24.48Mb
  - ğŸ‡¸ğŸ‡¬SG_255 |10.93Mb
  - disney_US |105.86Mb
  - disney_netflix_NL |233.79Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - disney_netflix_US |234.50Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_181 |39.42Mb
  - _187 |10.08Mb
  - disney_netflix_NL |218.45Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_200 |12.39Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_201 |61.96Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_203 |12.31Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_202 |19.03Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_204 |10.07Mb
  - disney_PT |138.28Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_209 |11.42Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_206 |19.07Mb
  - disney_US |61.39Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_210 |47.28Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_207 |10.55Mb
  - disney_FR |123.56Mb
  - disney_FR |50.56Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_211 |11.98Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_213 |59.31Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_212 |46.88Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_214 |45.92Mb
  - disney_netflix_NL |185.44Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_220 |11.46Mb
  - disney_HK |12.67Mb
  - disney_HK |28.47Mb
  - netflix_AL |43.01Mb
  - ğŸ‡²ğŸ‡½MX_252 |146.49Mb
  - disney_netflix_NL |98.11Mb
  - ğŸ‡­ğŸ‡°HK_236 |22.61Mb
  - disney_netflix_NL |134.58Mb
  - ğŸ‡­ğŸ‡°HK_240 |26.13Mb
  - ğŸ‡­ğŸ‡°HK_235 |28.30Mb
  - ğŸ‡°ğŸ‡·KR_250 |11.78Mb
  - disney_netflix_US |139.77Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_264 |38.97Mb
  - ğŸ‡ºğŸ‡¸US_267 |87.68Mb
  - Relay_ğŸ‡°ğŸ‡·KR-ğŸ‡°ğŸ‡·KR_249 |10.76Mb
  - ğŸ‡²ğŸ‡¾MY_253 |32.00Mb
  - disney_HK |24.48Mb
  - ğŸ‡¸ğŸ‡¬SG_255 |10.93Mb
  - disney_US |105.86Mb
  - disney_netflix_NL |233.79Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
