port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: _282 |11.99Mb
  server: 147.78.1.230
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _283 |14.01Mb
  server: 138.186.142.81
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _289 |10.07Mb
  server: 145.14.131.99
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _291 |12.74Mb
  server: 62.100.205.100
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _314 |20.18Mb
  server: 173.234.29.2
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _290 |29.80Mb
  server: 37.143.129.98
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _318 |17.11Mb
  server: 167.160.90.178
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _292 |18.15Mb
  server: 171.22.254.129
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _295 |10.61Mb
  server: 38.165.231.25
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: Pool__297 |10.06Mb
  server: 62.100.205.177
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _322 |36.34Mb
  server: 196.196.192.58
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸ‡¨ğŸ‡¦CA-ğŸ‡²ğŸ‡©MD_344 |27.83Mb
  server: 45.154.204.7
  type: ss
  country: ğŸ‡¨ğŸ‡¦CA
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _301 |31.35Mb
  server: 176.126.83.158
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _288 |24.06Mb
  server: 38.54.59.180
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸ‡¨ğŸ‡¦CA-ğŸ‡¨ğŸ‡¦CA_349 |21.91Mb
  server: 79.127.200.169
  type: ss
  country: ğŸ‡¨ğŸ‡¦CA
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _302 |16.55Mb
  server: 185.113.143.186
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _323 |34.53Mb
  server: 192.71.249.108
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¨ğŸ‡¦CA_350 |24.45Mb
  server: 148.113.176.192
  type: vmess
  country: ğŸ‡¨ğŸ‡¦CA
  port: 443
  uuid: 03fcc618-b93d-6796-6aed-8a38c975d581
  alterId: 0
  cipher: auto
  network: ws
  servername: fapeng.org
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: linkvws
    headers:
      HOST: fapeng.org
- name: _300 |10.14Mb
  server: 190.103.176.32
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¨ğŸ‡¿CZ_359 |23.43Mb
  server: 195.181.160.6
  type: ss
  country: ğŸ‡¨ğŸ‡¿CZ
  port: 990
  password: f8f7aCzcPKbsF8p3
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¦ğŸ‡ºAU_334 |25.30Mb
  server: 3.27.47.19
  type: ss
  country: ğŸ‡¦ğŸ‡ºAU
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡¦ğŸ‡ºAU_335 |23.09Mb
  server: 13.238.185.109
  type: ss
  country: ğŸ‡¦ğŸ‡ºAU
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡©ğŸ‡ªDE_383 |16.18Mb
  server: 81.19.141.45
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 443
  password: A9MWMeeHuERFESDEBcJCMq
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡©ğŸ‡ªDE_390 |27.27Mb
  server: 91.107.141.164
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 2096
  password: AqgBwYDeQA
  cipher: aes-256-gcm
- name: ğŸ‡¦ğŸ‡ºAU_338 |11.47Mb
  server: 3.24.178.167
  type: ss
  country: ğŸ‡¦ğŸ‡ºAU
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡ªğŸ‡¸ES_403 |22.63Mb
  server: 194.87.45.189
  type: ss
  country: ğŸ‡ªğŸ‡¸ES
  port: 443
  password: izQIvp0nUcXqsEie4aKqVh
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ªğŸ‡¸ES_404 |59.08Mb
  server: 194.87.45.189
  type: ss
  country: ğŸ‡ªğŸ‡¸ES
  port: 443
  password: urDP5LCkoF6TlJTAkQOuUi
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ªğŸ‡¸ES_409 |43.82Mb
  server: 194.87.45.189
  type: ss
  country: ğŸ‡ªğŸ‡¸ES
  port: 443
  password: W9I03JdDPQYRQWINmhTPjJ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¦ğŸ‡ºAU_339 |21.96Mb
  server: 51.161.130.101
  type: vmess
  country: ğŸ‡¦ğŸ‡ºAU
  port: 550
  uuid: b592cf1a-d92f-4dbd-9c1d-b76936a1609e
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡ªğŸ‡¸ES_419 |44.42Mb
  server: 194.87.45.189
  type: ss
  country: ğŸ‡ªğŸ‡¸ES
  port: 443
  password: rlZrTPevXyv8GDenQNlkyz
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ªğŸ‡¸ES_418 |45.90Mb
  server: 194.87.45.189
  type: ss
  country: ğŸ‡ªğŸ‡¸ES
  port: 443
  password: jiMMLSYwAagbBvDq511rG3
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸ‡®ğŸ‡·IR-ğŸ‡³ğŸ‡±NL_490 |10.11Mb
  server: 151.242.251.137
  type: ss
  country: ğŸ‡®ğŸ‡·IR
  port: 8080
  password: o5osZg269v5zHpYjr1xY9s
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡®ğŸ‡¶IQ_487 |10.60Mb
  server: 81.90.31.219
  type: ss
  country: ğŸ‡®ğŸ‡¶IQ
  port: 443
  password: Ahf5xNJyTCOUv1Uz9tDPOZ
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸ‡®ğŸ‡·IR-ğŸ‡³ğŸ‡±NL_494 |10.10Mb
  server: 151.242.251.137
  type: ss
  country: ğŸ‡®ğŸ‡·IR
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡®ğŸ‡·IR_498 |10.64Mb
  server: 151.242.251.144
  type: ss
  country: ğŸ‡®ğŸ‡·IR
  port: 8080
  password: QCXDxuDlTTMD7jtgHUjIoj
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_509 |11.20Mb
  server: 45.87.175.154
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_515 |13.24Mb
  server: 45.87.175.199
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: QCXDxuDlTTMD7jtgHUjIoj
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡®ğŸ‡¹IT_504 |28.84Mb
  server: 212.102.54.45
  type: ss
  country: ğŸ‡®ğŸ‡¹IT
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_521 |14.15Mb
  server: 45.87.175.199
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡®ğŸ‡³IN_482 |30.12Mb
  server: 134.209.147.198
  type: ss
  country: ğŸ‡®ğŸ‡³IN
  port: 990
  password: f8f7aCzcPKbsF8p3
  cipher: chacha20-ietf-poly1305
- name: Pool_ğŸ‡­ğŸ‡°HK_478 |855.00Mb
  server: 150.107.46.21
  type: ssr
  country: ğŸ‡­ğŸ‡°HK
  port: 8083
  password: iFqnzSscN
  cipher: aes-256-cfb
  protocol: origin
  obfs: tls1.2_ticket_auth
- name: ğŸ‡±ğŸ‡¹LT_531 |10.16Mb
  server: 45.87.175.10
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡³ğŸ‡±NL_556 |10.98Mb
  server: 193.29.139.164
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 8080
  password: 1RWwXhwfAB5gAEozU4G2Pg
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡³ğŸ‡±NL_563 |15.47Mb
  server: 193.29.139.199
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 8080
  password: 4a2rfixophdjffa8KVA4Aa
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡µğŸ‡±PL_573 |10.11Mb
  server: 217.30.10.18
  type: ss
  country: ğŸ‡µğŸ‡±PL
  port: 9006
  password: FAdUvMJUq5vDgKEq
  cipher: aes-256-cfb
- name: ğŸ‡µğŸ‡±PL_590 |33.99Mb
  server: 77.83.246.74
  type: ss
  country: ğŸ‡µğŸ‡±PL
  port: 443
  password: LDSArVqUYdyRErZvLWaKuY
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡µğŸ‡±PL_598 |10.09Mb
  server: 217.30.10.70
  type: ss
  country: ğŸ‡µğŸ‡±PL
  port: 9038
  password: gYCYXfkUQEs2TaJQ
  cipher: aes-256-cfb
- name: ğŸ‡µğŸ‡±PL_601 |31.70Mb
  server: 77.83.246.74
  type: ss
  country: ğŸ‡µğŸ‡±PL
  port: 443
  password: hja6ECKVovyUhLqWxcDPIm
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡·ğŸ‡ºRU_611 |197.14Mb
  server: 95.163.176.37
  type: ss
  country: ğŸ‡·ğŸ‡ºRU
  port: 8506
  password: n4J9KuWgBBXPBoDn0SdprD
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡·ğŸ‡ºRU_613 |14.14Mb
  server: 95.163.176.37
  type: ss
  country: ğŸ‡·ğŸ‡ºRU
  port: 8506
  password: ZK8Hv7D68bNRynZeqLVFLM
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¸ğŸ‡ªSE_623 |12.11Mb
  server: 13.60.9.137
  type: ss
  country: ğŸ‡¸ğŸ‡ªSE
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡ºğŸ‡¸US_654 |10.87Mb
  server: 3.93.56.69
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡ºğŸ‡¸US_655 |21.20Mb
  server: 34.202.236.105
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡¸ğŸ‡ªSE_625 |15.44Mb
  server: 13.60.76.73
  type: ss
  country: ğŸ‡¸ğŸ‡ªSE
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: disney_PY |37.13Mb
  server: 38.165.233.18
  type: ss
  country: ğŸ‡µğŸ‡¾PY
  port: 990
  password: f8f7aCzcPKbsF8p3
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_664 |12.39Mb
  server: 64.74.163.218
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 990
  password: f8f7aCzcPKbsF8p3
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_680 |18.43Mb
  server: 18.118.10.94
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡ºğŸ‡¸US_684 |10.73Mb
  server: 18.218.220.83
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡ºğŸ‡¸US_679 |37.98Mb
  server: 64.74.163.82
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 990
  password: f8f7aCzcPKbsF8p3
  cipher: chacha20-ietf-poly1305
- name: disney_US |10.21Mb
  server: 216.132.112.116
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 34958
  password: AJtV4VCLaVQUKGH4g1ADSyqvzCA0mSpN46an12ZeIKhx
  cipher: aes-256-gcm
- name: ğŸ‡ºğŸ‡¸US_694 |10.83Mb
  server: 54.234.186.14
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡ºğŸ‡¸US_702 |14.04Mb
  server: 3.12.120.55
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡ºğŸ‡¸US_712 |20.73Mb
  server: 3.148.222.22
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡ºğŸ‡¸US_713 |18.96Mb
  server: 3.148.242.11
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡ºğŸ‡¸US_714 |21.02Mb
  server: 3.12.163.233
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡¹ğŸ‡·TR_642 |20.63Mb
  server: 45.89.52.66
  type: ss
  country: ğŸ‡¹ğŸ‡·TR
  port: 9054
  password: VcFuyXvND2yQWSFY
  cipher: aes-256-cfb
- name: ğŸ‡ºğŸ‡¸US_720 |10.19Mb
  server: 3.85.225.236
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 80
  password: dada0801
  cipher: aes-256-gcm
- name: Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡²ğŸ‡©MD_725 |15.61Mb
  server: 23.95.76.59
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_697 |10.32Mb
  server: 167.88.61.59
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 8118
  password: cdBIDV42DCwnfIN
  cipher: aes-256-gcm
- name: ğŸ‡ºğŸ‡¸US_693 |20.73Mb
  server: 167.88.61.113
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 6697
  password: TEzjfAYq2IjtuoS
  cipher: aes-256-gcm
- name: ğŸ‡ºğŸ‡¸US_727 |13.89Mb
  server: 52.90.171.241
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: disney_US |188.24Mb
  server: 193.124.24.247
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 6504
  uuid: 7ceb165c-9aff-4ab7-ce9e-1df31a5ed911
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_US |12.22Mb
  server: 193.124.24.247
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 6515
  uuid: 2f3c646a-37f3-483a-a2a5-6bc1c5e526ae
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_US |10.40Mb
  server: 193.124.24.247
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 6506
  uuid: c53d41d1-7d56-43ce-9994-408780c6476a
  alterId: 0
  cipher: auto
  network: tcp
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡¹ğŸ‡·TR_643 |37.96Mb
  server: 185.123.101.241
  type: ss
  country: ğŸ‡¹ğŸ‡·TR
  port: 990
  password: f8f7aCzcPKbsF8p3
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_729 |10.37Mb
  server: 104.192.226.106
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 990
  password: f8f7aCzcPKbsF8p3
  cipher: chacha20-ietf-poly1305
- name: disney_US |18.65Mb
  server: 193.124.24.247
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 6511
  uuid: 5ef4e89b-262f-4c74-e793-c7332079f251
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡ºğŸ‡¸US_723 |124.76Mb
  server: 167.88.61.110
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 7002
  password: RexnBgU7EV5ADxG
  cipher: aes-256-gcm
- name: ğŸ‡ºğŸ‡¸US_726 |17.81Mb
  server: 137.175.97.159
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 8388
  password: asd123456
  cipher: chacha20-ietf
- name: ğŸ‡¸ğŸ‡¬SG_631 |15.25Mb
  server: 156.59.243.6
  type: ss
  country: ğŸ‡¸ğŸ‡¬SG
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: disney_US |21.00Mb
  server: 154.29.158.139
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 12299
  uuid: cccfe679-fbd0-4402-caf2-67e919db436f
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡©ğŸ‡ªDE_375 |10.98Mb
  server: 81.19.141.45
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 443
  password: mGmgnK6npgEFJS6kk2ox2P
  cipher: chacha20-ietf-poly1305
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - _282 |11.99Mb
  - _283 |14.01Mb
  - _289 |10.07Mb
  - _291 |12.74Mb
  - _314 |20.18Mb
  - _290 |29.80Mb
  - _318 |17.11Mb
  - _292 |18.15Mb
  - _295 |10.61Mb
  - Pool__297 |10.06Mb
  - _322 |36.34Mb
  - Relay_ğŸ‡¨ğŸ‡¦CA-ğŸ‡²ğŸ‡©MD_344 |27.83Mb
  - _301 |31.35Mb
  - _288 |24.06Mb
  - Relay_ğŸ‡¨ğŸ‡¦CA-ğŸ‡¨ğŸ‡¦CA_349 |21.91Mb
  - _302 |16.55Mb
  - _323 |34.53Mb
  - ğŸ‡¨ğŸ‡¦CA_350 |24.45Mb
  - _300 |10.14Mb
  - ğŸ‡¨ğŸ‡¿CZ_359 |23.43Mb
  - ğŸ‡¦ğŸ‡ºAU_334 |25.30Mb
  - ğŸ‡¦ğŸ‡ºAU_335 |23.09Mb
  - ğŸ‡©ğŸ‡ªDE_383 |16.18Mb
  - ğŸ‡©ğŸ‡ªDE_390 |27.27Mb
  - ğŸ‡¦ğŸ‡ºAU_338 |11.47Mb
  - ğŸ‡ªğŸ‡¸ES_403 |22.63Mb
  - ğŸ‡ªğŸ‡¸ES_404 |59.08Mb
  - ğŸ‡ªğŸ‡¸ES_409 |43.82Mb
  - ğŸ‡¦ğŸ‡ºAU_339 |21.96Mb
  - ğŸ‡ªğŸ‡¸ES_419 |44.42Mb
  - ğŸ‡ªğŸ‡¸ES_418 |45.90Mb
  - Relay_ğŸ‡®ğŸ‡·IR-ğŸ‡³ğŸ‡±NL_490 |10.11Mb
  - ğŸ‡®ğŸ‡¶IQ_487 |10.60Mb
  - Relay_ğŸ‡®ğŸ‡·IR-ğŸ‡³ğŸ‡±NL_494 |10.10Mb
  - ğŸ‡®ğŸ‡·IR_498 |10.64Mb
  - ğŸ‡±ğŸ‡¹LT_509 |11.20Mb
  - ğŸ‡±ğŸ‡¹LT_515 |13.24Mb
  - ğŸ‡®ğŸ‡¹IT_504 |28.84Mb
  - ğŸ‡±ğŸ‡¹LT_521 |14.15Mb
  - ğŸ‡®ğŸ‡³IN_482 |30.12Mb
  - Pool_ğŸ‡­ğŸ‡°HK_478 |855.00Mb
  - ğŸ‡±ğŸ‡¹LT_531 |10.16Mb
  - ğŸ‡³ğŸ‡±NL_556 |10.98Mb
  - ğŸ‡³ğŸ‡±NL_563 |15.47Mb
  - ğŸ‡µğŸ‡±PL_573 |10.11Mb
  - ğŸ‡µğŸ‡±PL_590 |33.99Mb
  - ğŸ‡µğŸ‡±PL_598 |10.09Mb
  - ğŸ‡µğŸ‡±PL_601 |31.70Mb
  - ğŸ‡·ğŸ‡ºRU_611 |197.14Mb
  - ğŸ‡·ğŸ‡ºRU_613 |14.14Mb
  - ğŸ‡¸ğŸ‡ªSE_623 |12.11Mb
  - ğŸ‡ºğŸ‡¸US_654 |10.87Mb
  - ğŸ‡ºğŸ‡¸US_655 |21.20Mb
  - ğŸ‡¸ğŸ‡ªSE_625 |15.44Mb
  - disney_PY |37.13Mb
  - ğŸ‡ºğŸ‡¸US_664 |12.39Mb
  - ğŸ‡ºğŸ‡¸US_680 |18.43Mb
  - ğŸ‡ºğŸ‡¸US_684 |10.73Mb
  - ğŸ‡ºğŸ‡¸US_679 |37.98Mb
  - disney_US |10.21Mb
  - ğŸ‡ºğŸ‡¸US_694 |10.83Mb
  - ğŸ‡ºğŸ‡¸US_702 |14.04Mb
  - ğŸ‡ºğŸ‡¸US_712 |20.73Mb
  - ğŸ‡ºğŸ‡¸US_713 |18.96Mb
  - ğŸ‡ºğŸ‡¸US_714 |21.02Mb
  - ğŸ‡¹ğŸ‡·TR_642 |20.63Mb
  - ğŸ‡ºğŸ‡¸US_720 |10.19Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡²ğŸ‡©MD_725 |15.61Mb
  - ğŸ‡ºğŸ‡¸US_697 |10.32Mb
  - ğŸ‡ºğŸ‡¸US_693 |20.73Mb
  - ğŸ‡ºğŸ‡¸US_727 |13.89Mb
  - disney_US |188.24Mb
  - disney_US |12.22Mb
  - disney_US |10.40Mb
  - ğŸ‡¹ğŸ‡·TR_643 |37.96Mb
  - ğŸ‡ºğŸ‡¸US_729 |10.37Mb
  - disney_US |18.65Mb
  - ğŸ‡ºğŸ‡¸US_723 |124.76Mb
  - ğŸ‡ºğŸ‡¸US_726 |17.81Mb
  - ğŸ‡¸ğŸ‡¬SG_631 |15.25Mb
  - disney_US |21.00Mb
  - ğŸ‡©ğŸ‡ªDE_375 |10.98Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - _282 |11.99Mb
  - _283 |14.01Mb
  - _289 |10.07Mb
  - _291 |12.74Mb
  - _314 |20.18Mb
  - _290 |29.80Mb
  - _318 |17.11Mb
  - _292 |18.15Mb
  - _295 |10.61Mb
  - Pool__297 |10.06Mb
  - _322 |36.34Mb
  - Relay_ğŸ‡¨ğŸ‡¦CA-ğŸ‡²ğŸ‡©MD_344 |27.83Mb
  - _301 |31.35Mb
  - _288 |24.06Mb
  - Relay_ğŸ‡¨ğŸ‡¦CA-ğŸ‡¨ğŸ‡¦CA_349 |21.91Mb
  - _302 |16.55Mb
  - _323 |34.53Mb
  - ğŸ‡¨ğŸ‡¦CA_350 |24.45Mb
  - _300 |10.14Mb
  - ğŸ‡¨ğŸ‡¿CZ_359 |23.43Mb
  - ğŸ‡¦ğŸ‡ºAU_334 |25.30Mb
  - ğŸ‡¦ğŸ‡ºAU_335 |23.09Mb
  - ğŸ‡©ğŸ‡ªDE_383 |16.18Mb
  - ğŸ‡©ğŸ‡ªDE_390 |27.27Mb
  - ğŸ‡¦ğŸ‡ºAU_338 |11.47Mb
  - ğŸ‡ªğŸ‡¸ES_403 |22.63Mb
  - ğŸ‡ªğŸ‡¸ES_404 |59.08Mb
  - ğŸ‡ªğŸ‡¸ES_409 |43.82Mb
  - ğŸ‡¦ğŸ‡ºAU_339 |21.96Mb
  - ğŸ‡ªğŸ‡¸ES_419 |44.42Mb
  - ğŸ‡ªğŸ‡¸ES_418 |45.90Mb
  - Relay_ğŸ‡®ğŸ‡·IR-ğŸ‡³ğŸ‡±NL_490 |10.11Mb
  - ğŸ‡®ğŸ‡¶IQ_487 |10.60Mb
  - Relay_ğŸ‡®ğŸ‡·IR-ğŸ‡³ğŸ‡±NL_494 |10.10Mb
  - ğŸ‡®ğŸ‡·IR_498 |10.64Mb
  - ğŸ‡±ğŸ‡¹LT_509 |11.20Mb
  - ğŸ‡±ğŸ‡¹LT_515 |13.24Mb
  - ğŸ‡®ğŸ‡¹IT_504 |28.84Mb
  - ğŸ‡±ğŸ‡¹LT_521 |14.15Mb
  - ğŸ‡®ğŸ‡³IN_482 |30.12Mb
  - Pool_ğŸ‡­ğŸ‡°HK_478 |855.00Mb
  - ğŸ‡±ğŸ‡¹LT_531 |10.16Mb
  - ğŸ‡³ğŸ‡±NL_556 |10.98Mb
  - ğŸ‡³ğŸ‡±NL_563 |15.47Mb
  - ğŸ‡µğŸ‡±PL_573 |10.11Mb
  - ğŸ‡µğŸ‡±PL_590 |33.99Mb
  - ğŸ‡µğŸ‡±PL_598 |10.09Mb
  - ğŸ‡µğŸ‡±PL_601 |31.70Mb
  - ğŸ‡·ğŸ‡ºRU_611 |197.14Mb
  - ğŸ‡·ğŸ‡ºRU_613 |14.14Mb
  - ğŸ‡¸ğŸ‡ªSE_623 |12.11Mb
  - ğŸ‡ºğŸ‡¸US_654 |10.87Mb
  - ğŸ‡ºğŸ‡¸US_655 |21.20Mb
  - ğŸ‡¸ğŸ‡ªSE_625 |15.44Mb
  - disney_PY |37.13Mb
  - ğŸ‡ºğŸ‡¸US_664 |12.39Mb
  - ğŸ‡ºğŸ‡¸US_680 |18.43Mb
  - ğŸ‡ºğŸ‡¸US_684 |10.73Mb
  - ğŸ‡ºğŸ‡¸US_679 |37.98Mb
  - disney_US |10.21Mb
  - ğŸ‡ºğŸ‡¸US_694 |10.83Mb
  - ğŸ‡ºğŸ‡¸US_702 |14.04Mb
  - ğŸ‡ºğŸ‡¸US_712 |20.73Mb
  - ğŸ‡ºğŸ‡¸US_713 |18.96Mb
  - ğŸ‡ºğŸ‡¸US_714 |21.02Mb
  - ğŸ‡¹ğŸ‡·TR_642 |20.63Mb
  - ğŸ‡ºğŸ‡¸US_720 |10.19Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡²ğŸ‡©MD_725 |15.61Mb
  - ğŸ‡ºğŸ‡¸US_697 |10.32Mb
  - ğŸ‡ºğŸ‡¸US_693 |20.73Mb
  - ğŸ‡ºğŸ‡¸US_727 |13.89Mb
  - disney_US |188.24Mb
  - disney_US |12.22Mb
  - disney_US |10.40Mb
  - ğŸ‡¹ğŸ‡·TR_643 |37.96Mb
  - ğŸ‡ºğŸ‡¸US_729 |10.37Mb
  - disney_US |18.65Mb
  - ğŸ‡ºğŸ‡¸US_723 |124.76Mb
  - ğŸ‡ºğŸ‡¸US_726 |17.81Mb
  - ğŸ‡¸ğŸ‡¬SG_631 |15.25Mb
  - disney_US |21.00Mb
  - ğŸ‡©ğŸ‡ªDE_375 |10.98Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
