port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: _169 |23.38Mb
  server: 173.234.29.2
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _204 |10.36Mb
  server: 66.23.207.82
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _168 |341.75Mb
  server: 3.129.133.36
  type: ss
  port: 30000
  udp: true
  password: b9a7fe64-e236-4b8d-b6c9-65da8a7070cc
  cipher: aes-256-gcm
- name: _183 |10.30Mb
  server: 138.186.142.80
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _198 |10.33Mb
  server: 138.186.142.81
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _189 |10.28Mb
  server: 38.165.231.25
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _201 |46.31Mb
  server: 212.102.54.45
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _174 |10.05Mb
  server: 185.237.185.89
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _219 |10.14Mb
  server: 109.61.46.43
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¦ğŸ‡¹AT_224 |45.04Mb
  server: 37.235.56.69
  type: ss
  country: ğŸ‡¦ğŸ‡¹AT
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¨ğŸ‡¦CA_237 |10.46Mb
  server: 79.127.200.162
  type: ss
  country: ğŸ‡¨ğŸ‡¦CA
  port: 990
  password: f8f7aCzcPKbsF8p3
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸ‡¨ğŸ‡¦CA-ğŸ‡¨ğŸ‡¦CA_239 |10.47Mb
  server: 79.127.200.169
  type: ss
  country: ğŸ‡¨ğŸ‡¦CA
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸ‡¨ğŸ‡¦CA-ğŸ‡²ğŸ‡©MD_243 |10.32Mb
  server: 45.154.204.7
  type: ss
  country: ğŸ‡¨ğŸ‡¦CA
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _212 |11.82Mb
  server: 176.123.5.253
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡§ğŸ‡ªBE_229 |177.14Mb
  server: 192.71.249.78
  type: ss
  country: ğŸ‡§ğŸ‡ªBE
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ğŸ‡¦ğŸ‡¹AT_225 |173.70Mb
  server: 37.235.56.69
  type: ss
  country: ğŸ‡¦ğŸ‡¹AT
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ğŸ‡§ğŸ‡ªBE_230 |34.38Mb
  server: 192.71.249.108
  type: ss
  country: ğŸ‡§ğŸ‡ªBE
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¨ğŸ‡¦CA_244 |10.52Mb
  server: 51.79.102.253
  type: vmess
  country: ğŸ‡¨ğŸ‡¦CA
  port: 80
  uuid: 58fe1542-5290-40ad-815a-77707a81afe5
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
  ws-opts:
    path: /IOebhLMhl1CTbFHbL95myfRX2
- name: _166 |10.04Mb
  server: 45.82.252.109
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¨ğŸ‡·CR_251 |48.61Mb
  server: 145.14.131.37
  type: ss
  country: ğŸ‡¨ğŸ‡·CR
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡©ğŸ‡ªDE_259 |10.28Mb
  server: 18.159.37.90
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: _173 |38.88Mb
  server: 103.97.203.227
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡©ğŸ‡ªDE_271 |10.35Mb
  server: 3.66.163.109
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡©ğŸ‡ªDE_287 |10.09Mb
  server: 81.19.141.45
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 443
  password: 3mCD9NchPkbYIojfTHyNf0
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡©ğŸ‡ªDE_282 |10.18Mb
  server: 18.196.31.30
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡©ğŸ‡ªDE_292 |13.77Mb
  server: 91.107.141.164
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 2096
  password: AqgBwYDeQA
  cipher: aes-256-gcm
- name: ğŸ‡©ğŸ‡ªDE_294 |10.07Mb
  server: 18.196.156.200
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡«ğŸ‡·FR_331 |18.02Mb
  server: 57.129.140.88
  type: ss
  country: ğŸ‡«ğŸ‡·FR
  port: 8388
  password: k1v5g9FefdoO
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_337 |10.40Mb
  server: 3.9.171.152
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡¬ğŸ‡§GB_341 |43.71Mb
  server: 89.185.84.185
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: c0rALV8bvjaRHD1hg8SmuN
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_347 |85.74Mb
  server: 89.185.84.185
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: ozSHXLRuO7JckCvhgLjLaU
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_346 |10.32Mb
  server: 89.185.84.185
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: gVso41rEHjH4nZhcohbeod
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_351 |34.09Mb
  server: 89.185.84.185
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: zyzuJ2H4Tp5Cr8T9nnPKv2
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡«ğŸ‡·FR_329 |14.18Mb
  server: 83.147.216.70
  type: ss
  country: ğŸ‡«ğŸ‡·FR
  port: 64519
  password: PSmqa9uK9Oo1eivPyXiAH8
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_355 |71.10Mb
  server: 89.185.84.185
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: i0Gf1YEtKzZmsVFpnrTxIt
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_358 |81.75Mb
  server: 89.185.84.185
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: KOmxnPI5Pol1nYboUdCyQS
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_360 |81.72Mb
  server: 89.185.84.185
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: RGy5tlm8bAQdM5zc9XFF0Y
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_363 |85.02Mb
  server: 89.185.84.185
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: RCep1UaygXjYEdFS9kOsm3
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡®ğŸ‡·IR_411 |14.53Mb
  server: 151.242.251.144
  type: ss
  country: ğŸ‡®ğŸ‡·IR
  port: 8080
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸ‡®ğŸ‡·IR-ğŸ‡³ğŸ‡±NL_414 |10.12Mb
  server: 151.242.251.137
  type: ss
  country: ğŸ‡®ğŸ‡·IR
  port: 8080
  password: o5osZg269v5zHpYjr1xY9s
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡­ğŸ‡·HR_385 |13.02Mb
  server: 169.150.242.77
  type: ss
  country: ğŸ‡­ğŸ‡·HR
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸ‡®ğŸ‡·IR-ğŸ‡³ğŸ‡±NL_415 |10.04Mb
  server: 151.242.251.147
  type: ss
  country: ğŸ‡®ğŸ‡·IR
  port: 8080
  password: QCXDxuDlTTMD7jtgHUjIoj
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸ‡¨ğŸ‡­CH-ğŸ‡¨ğŸ‡­CH_246 |10.08Mb
  server: h110vpnch.outlinekeys.net
  type: ss
  country: ğŸ‡¨ğŸ‡­CH
  port: 4248
  password: 7tpJjfOOceafbvYXmVWYeI
  cipher: chacha20-ietf-poly1305
- name: Pool_ğŸ‡­ğŸ‡°HK_373 |172.00Mb
  server: 150.107.46.21
  type: ssr
  country: ğŸ‡­ğŸ‡°HK
  port: 8083
  password: iFqnzSscN
  cipher: aes-256-cfb
  protocol: origin
  obfs: tls1.2_ticket_auth
- name: ğŸ‡¯ğŸ‡µJP_420 |51.59Mb
  server: 194.68.27.76
  type: ss
  country: ğŸ‡¯ğŸ‡µJP
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡­ğŸ‡°HK_383 |10.12Mb
  server: 8.218.71.140
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 57714
  uuid: a2e3f41e-97a6-4dbb-b926-7093ff574f74
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
  ws-opts:
    path: /arki?ed=2048
- name: ğŸ‡±ğŸ‡¹LT_438 |15.59Mb
  server: 45.87.175.180
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: QCXDxuDlTTMD7jtgHUjIoj
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¯ğŸ‡µJP_422 |50.62Mb
  server: 153.121.51.214
  type: ss
  country: ğŸ‡¯ğŸ‡µJP
  port: 10087
  password: '10086'
  cipher: aes-128-gcm
- name: ğŸ‡¯ğŸ‡µJP_423 |49.62Mb
  server: 153.121.43.183
  type: ss
  country: ğŸ‡¯ğŸ‡µJP
  port: 10087
  password: '10086'
  cipher: aes-128-gcm
- name: ğŸ‡¯ğŸ‡µJP_426 |140.91Mb
  server: 8.211.164.215
  type: vmess
  country: ğŸ‡¯ğŸ‡µJP
  port: 20522
  uuid: 73193cce-7ca1-4b08-93ff-4ee8b0147374
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
  ws-opts:
    path: /telegram_@sswia
- name: ğŸ‡¯ğŸ‡µJP_424 |166.14Mb
  server: 47.74.10.111
  type: vmess
  country: ğŸ‡¯ğŸ‡µJP
  port: 20522
  uuid: 0b6a563a-7bee-4740-82ff-3d8126251ed9
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
  ws-opts:
    path: /telegram_@sswia
- name: ğŸ‡±ğŸ‡¹LT_443 |16.02Mb
  server: 45.87.175.166
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_450 |10.17Mb
  server: 45.87.175.165
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: QCXDxuDlTTMD7jtgHUjIoj
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡³ğŸ‡±NL_463 |15.66Mb
  server: 193.29.139.164
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 8080
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_431 |10.01Mb
  server: beesyar.org
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: QCXDxuDlTTMD7jtgHUjIoj
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡³ğŸ‡±NL_469 |16.06Mb
  server: 193.29.139.173
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 8080
  password: 4a2rfixophdjffa8KVA4Aa
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡³ğŸ‡±NL_470 |14.61Mb
  server: 193.29.139.179
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 8080
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡³ğŸ‡±NL_475 |15.59Mb
  server: 193.29.139.179
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 8080
  password: 1RWwXhwfAB5gAEozU4G2Pg
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡³ğŸ‡±NL_483 |10.14Mb
  server: 193.29.139.217
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 8080
  password: QCXDxuDlTTMD7jtgHUjIoj
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡³ğŸ‡±NL_477 |10.12Mb
  server: 79.127.227.53
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ğŸ‡µğŸ‡±PL_495 |13.36Mb
  server: 217.30.10.70
  type: ss
  country: ğŸ‡µğŸ‡±PL
  port: 9026
  password: QWDDvVE9npNurQfA
  cipher: aes-256-cfb
- name: ğŸ‡µğŸ‡±PL_505 |11.56Mb
  server: 217.30.10.18
  type: ss
  country: ğŸ‡µğŸ‡±PL
  port: 9007
  password: kSPmvwdFzGMMW5pY
  cipher: aes-256-cfb
- name: ğŸ‡µğŸ‡±PL_515 |13.09Mb
  server: 217.30.10.18
  type: ss
  country: ğŸ‡µğŸ‡±PL
  port: 9015
  password: ZpNDDKRu9MagNvaf
  cipher: aes-256-cfb
- name: ğŸ‡µğŸ‡±PL_519 |60.76Mb
  server: 77.83.246.74
  type: ss
  country: ğŸ‡µğŸ‡±PL
  port: 443
  password: KwQZX5ziYHI0QHkanEj9iG
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡µğŸ‡±PL_535 |13.80Mb
  server: 217.30.10.70
  type: ss
  country: ğŸ‡µğŸ‡±PL
  port: 9027
  password: EXN3S3eQpjE7EJu8
  cipher: aes-256-cfb
- name: ğŸ‡µğŸ‡±PL_526 |59.96Mb
  server: 77.83.246.74
  type: ss
  country: ğŸ‡µğŸ‡±PL
  port: 443
  password: uqM5lfG2Jpmzp8GdR2mMWC
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡·ğŸ‡ºRU_553 |14.59Mb
  server: 95.163.176.37
  type: ss
  country: ğŸ‡·ğŸ‡ºRU
  port: 8506
  password: VdswxetVc6AhIps18rtYbm
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡µğŸ‡¾PY_543 |114.45Mb
  server: 38.165.233.93
  type: ss
  country: ğŸ‡µğŸ‡¾PY
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ğŸ‡¸ğŸ‡ªSE_556 |10.70Mb
  server: 13.60.76.73
  type: ss
  country: ğŸ‡¸ğŸ‡ªSE
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡¸ğŸ‡ªSE_557 |132.20Mb
  server: 176.97.77.71
  type: ss
  country: ğŸ‡¸ğŸ‡ªSE
  port: 31778
  password: Iel2tlruoGON1PooiQy0G3
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¸ğŸ‡¨SC_555 |16.59Mb
  server: 154.205.159.100
  type: ss
  country: ğŸ‡¸ğŸ‡¨SC
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¸ğŸ‡¬SG_562 |10.82Mb
  server: 103.36.91.23
  type: ss
  country: ğŸ‡¸ğŸ‡¬SG
  port: 8388
  password: asd123456
  cipher: chacha20-ietf
- name: ğŸ‡¨ğŸ‡·CR_252 |50.02Mb
  server: 145.14.131.37
  type: ss
  country: ğŸ‡¨ğŸ‡·CR
  port: 990
  password: f8f7aCzcPKbsF8p3
  cipher: chacha20-ietf-poly1305
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - _169 |23.38Mb
  - _204 |10.36Mb
  - _168 |341.75Mb
  - _183 |10.30Mb
  - _198 |10.33Mb
  - _189 |10.28Mb
  - _201 |46.31Mb
  - _174 |10.05Mb
  - _219 |10.14Mb
  - ğŸ‡¦ğŸ‡¹AT_224 |45.04Mb
  - ğŸ‡¨ğŸ‡¦CA_237 |10.46Mb
  - Relay_ğŸ‡¨ğŸ‡¦CA-ğŸ‡¨ğŸ‡¦CA_239 |10.47Mb
  - Relay_ğŸ‡¨ğŸ‡¦CA-ğŸ‡²ğŸ‡©MD_243 |10.32Mb
  - _212 |11.82Mb
  - ğŸ‡§ğŸ‡ªBE_229 |177.14Mb
  - ğŸ‡¦ğŸ‡¹AT_225 |173.70Mb
  - ğŸ‡§ğŸ‡ªBE_230 |34.38Mb
  - ğŸ‡¨ğŸ‡¦CA_244 |10.52Mb
  - _166 |10.04Mb
  - ğŸ‡¨ğŸ‡·CR_251 |48.61Mb
  - ğŸ‡©ğŸ‡ªDE_259 |10.28Mb
  - _173 |38.88Mb
  - ğŸ‡©ğŸ‡ªDE_271 |10.35Mb
  - ğŸ‡©ğŸ‡ªDE_287 |10.09Mb
  - ğŸ‡©ğŸ‡ªDE_282 |10.18Mb
  - ğŸ‡©ğŸ‡ªDE_292 |13.77Mb
  - ğŸ‡©ğŸ‡ªDE_294 |10.07Mb
  - ğŸ‡«ğŸ‡·FR_331 |18.02Mb
  - ğŸ‡¬ğŸ‡§GB_337 |10.40Mb
  - ğŸ‡¬ğŸ‡§GB_341 |43.71Mb
  - ğŸ‡¬ğŸ‡§GB_347 |85.74Mb
  - ğŸ‡¬ğŸ‡§GB_346 |10.32Mb
  - ğŸ‡¬ğŸ‡§GB_351 |34.09Mb
  - ğŸ‡«ğŸ‡·FR_329 |14.18Mb
  - ğŸ‡¬ğŸ‡§GB_355 |71.10Mb
  - ğŸ‡¬ğŸ‡§GB_358 |81.75Mb
  - ğŸ‡¬ğŸ‡§GB_360 |81.72Mb
  - ğŸ‡¬ğŸ‡§GB_363 |85.02Mb
  - ğŸ‡®ğŸ‡·IR_411 |14.53Mb
  - Relay_ğŸ‡®ğŸ‡·IR-ğŸ‡³ğŸ‡±NL_414 |10.12Mb
  - ğŸ‡­ğŸ‡·HR_385 |13.02Mb
  - Relay_ğŸ‡®ğŸ‡·IR-ğŸ‡³ğŸ‡±NL_415 |10.04Mb
  - Relay_ğŸ‡¨ğŸ‡­CH-ğŸ‡¨ğŸ‡­CH_246 |10.08Mb
  - Pool_ğŸ‡­ğŸ‡°HK_373 |172.00Mb
  - ğŸ‡¯ğŸ‡µJP_420 |51.59Mb
  - ğŸ‡­ğŸ‡°HK_383 |10.12Mb
  - ğŸ‡±ğŸ‡¹LT_438 |15.59Mb
  - ğŸ‡¯ğŸ‡µJP_422 |50.62Mb
  - ğŸ‡¯ğŸ‡µJP_423 |49.62Mb
  - ğŸ‡¯ğŸ‡µJP_426 |140.91Mb
  - ğŸ‡¯ğŸ‡µJP_424 |166.14Mb
  - ğŸ‡±ğŸ‡¹LT_443 |16.02Mb
  - ğŸ‡±ğŸ‡¹LT_450 |10.17Mb
  - ğŸ‡³ğŸ‡±NL_463 |15.66Mb
  - ğŸ‡±ğŸ‡¹LT_431 |10.01Mb
  - ğŸ‡³ğŸ‡±NL_469 |16.06Mb
  - ğŸ‡³ğŸ‡±NL_470 |14.61Mb
  - ğŸ‡³ğŸ‡±NL_475 |15.59Mb
  - ğŸ‡³ğŸ‡±NL_483 |10.14Mb
  - ğŸ‡³ğŸ‡±NL_477 |10.12Mb
  - ğŸ‡µğŸ‡±PL_495 |13.36Mb
  - ğŸ‡µğŸ‡±PL_505 |11.56Mb
  - ğŸ‡µğŸ‡±PL_515 |13.09Mb
  - ğŸ‡µğŸ‡±PL_519 |60.76Mb
  - ğŸ‡µğŸ‡±PL_535 |13.80Mb
  - ğŸ‡µğŸ‡±PL_526 |59.96Mb
  - ğŸ‡·ğŸ‡ºRU_553 |14.59Mb
  - ğŸ‡µğŸ‡¾PY_543 |114.45Mb
  - ğŸ‡¸ğŸ‡ªSE_556 |10.70Mb
  - ğŸ‡¸ğŸ‡ªSE_557 |132.20Mb
  - ğŸ‡¸ğŸ‡¨SC_555 |16.59Mb
  - ğŸ‡¸ğŸ‡¬SG_562 |10.82Mb
  - ğŸ‡¨ğŸ‡·CR_252 |50.02Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - _169 |23.38Mb
  - _204 |10.36Mb
  - _168 |341.75Mb
  - _183 |10.30Mb
  - _198 |10.33Mb
  - _189 |10.28Mb
  - _201 |46.31Mb
  - _174 |10.05Mb
  - _219 |10.14Mb
  - ğŸ‡¦ğŸ‡¹AT_224 |45.04Mb
  - ğŸ‡¨ğŸ‡¦CA_237 |10.46Mb
  - Relay_ğŸ‡¨ğŸ‡¦CA-ğŸ‡¨ğŸ‡¦CA_239 |10.47Mb
  - Relay_ğŸ‡¨ğŸ‡¦CA-ğŸ‡²ğŸ‡©MD_243 |10.32Mb
  - _212 |11.82Mb
  - ğŸ‡§ğŸ‡ªBE_229 |177.14Mb
  - ğŸ‡¦ğŸ‡¹AT_225 |173.70Mb
  - ğŸ‡§ğŸ‡ªBE_230 |34.38Mb
  - ğŸ‡¨ğŸ‡¦CA_244 |10.52Mb
  - _166 |10.04Mb
  - ğŸ‡¨ğŸ‡·CR_251 |48.61Mb
  - ğŸ‡©ğŸ‡ªDE_259 |10.28Mb
  - _173 |38.88Mb
  - ğŸ‡©ğŸ‡ªDE_271 |10.35Mb
  - ğŸ‡©ğŸ‡ªDE_287 |10.09Mb
  - ğŸ‡©ğŸ‡ªDE_282 |10.18Mb
  - ğŸ‡©ğŸ‡ªDE_292 |13.77Mb
  - ğŸ‡©ğŸ‡ªDE_294 |10.07Mb
  - ğŸ‡«ğŸ‡·FR_331 |18.02Mb
  - ğŸ‡¬ğŸ‡§GB_337 |10.40Mb
  - ğŸ‡¬ğŸ‡§GB_341 |43.71Mb
  - ğŸ‡¬ğŸ‡§GB_347 |85.74Mb
  - ğŸ‡¬ğŸ‡§GB_346 |10.32Mb
  - ğŸ‡¬ğŸ‡§GB_351 |34.09Mb
  - ğŸ‡«ğŸ‡·FR_329 |14.18Mb
  - ğŸ‡¬ğŸ‡§GB_355 |71.10Mb
  - ğŸ‡¬ğŸ‡§GB_358 |81.75Mb
  - ğŸ‡¬ğŸ‡§GB_360 |81.72Mb
  - ğŸ‡¬ğŸ‡§GB_363 |85.02Mb
  - ğŸ‡®ğŸ‡·IR_411 |14.53Mb
  - Relay_ğŸ‡®ğŸ‡·IR-ğŸ‡³ğŸ‡±NL_414 |10.12Mb
  - ğŸ‡­ğŸ‡·HR_385 |13.02Mb
  - Relay_ğŸ‡®ğŸ‡·IR-ğŸ‡³ğŸ‡±NL_415 |10.04Mb
  - Relay_ğŸ‡¨ğŸ‡­CH-ğŸ‡¨ğŸ‡­CH_246 |10.08Mb
  - Pool_ğŸ‡­ğŸ‡°HK_373 |172.00Mb
  - ğŸ‡¯ğŸ‡µJP_420 |51.59Mb
  - ğŸ‡­ğŸ‡°HK_383 |10.12Mb
  - ğŸ‡±ğŸ‡¹LT_438 |15.59Mb
  - ğŸ‡¯ğŸ‡µJP_422 |50.62Mb
  - ğŸ‡¯ğŸ‡µJP_423 |49.62Mb
  - ğŸ‡¯ğŸ‡µJP_426 |140.91Mb
  - ğŸ‡¯ğŸ‡µJP_424 |166.14Mb
  - ğŸ‡±ğŸ‡¹LT_443 |16.02Mb
  - ğŸ‡±ğŸ‡¹LT_450 |10.17Mb
  - ğŸ‡³ğŸ‡±NL_463 |15.66Mb
  - ğŸ‡±ğŸ‡¹LT_431 |10.01Mb
  - ğŸ‡³ğŸ‡±NL_469 |16.06Mb
  - ğŸ‡³ğŸ‡±NL_470 |14.61Mb
  - ğŸ‡³ğŸ‡±NL_475 |15.59Mb
  - ğŸ‡³ğŸ‡±NL_483 |10.14Mb
  - ğŸ‡³ğŸ‡±NL_477 |10.12Mb
  - ğŸ‡µğŸ‡±PL_495 |13.36Mb
  - ğŸ‡µğŸ‡±PL_505 |11.56Mb
  - ğŸ‡µğŸ‡±PL_515 |13.09Mb
  - ğŸ‡µğŸ‡±PL_519 |60.76Mb
  - ğŸ‡µğŸ‡±PL_535 |13.80Mb
  - ğŸ‡µğŸ‡±PL_526 |59.96Mb
  - ğŸ‡·ğŸ‡ºRU_553 |14.59Mb
  - ğŸ‡µğŸ‡¾PY_543 |114.45Mb
  - ğŸ‡¸ğŸ‡ªSE_556 |10.70Mb
  - ğŸ‡¸ğŸ‡ªSE_557 |132.20Mb
  - ğŸ‡¸ğŸ‡¨SC_555 |16.59Mb
  - ğŸ‡¸ğŸ‡¬SG_562 |10.82Mb
  - ğŸ‡¨ğŸ‡·CR_252 |50.02Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
