port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: netflix_AT |93.23Mb
  server: 5.181.21.246
  type: ss
  port: 443
  udp: true
  password: gKYygTcRYhc3skc2x6tZ073lYz0DnieX
  cipher: chacha20-ietf-poly1305
- name: _114 |12.25Mb
  server: 45.87.175.166
  type: ss
  port: 443
  udp: true
  password: 1RWwXhwfAB5gAEozU4G2Pg
  cipher: chacha20-ietf-poly1305
- name: netflix_CH |68.95Mb
  server: 86.106.84.195
  type: ss
  port: 13262
  udp: true
  password: kfuzkwdg4oynv495aywc
  cipher: aes-128-gcm
- name: disney_HK |10.91Mb
  server: 103.149.183.191
  type: ss
  port: 8388
  udp: true
  password: asd123456
  cipher: chacha20-ietf
- name: disney_netflix_DE |283.77Mb
  server: 43.165.7.71
  type: vmess
  port: 19751
  uuid: 6cfa6103-5d06-40cb-f452-b563db578288
  alterId: 0
  cipher: auto
  network: http
  http-opts:
    method: GET
    path:
    - /
  h2-opts: {}
- name: disney_SG |109.21Mb
  server: 165.154.195.38
  type: vmess
  port: 35034
  uuid: 959a8caf-4cea-43d0-a548-3628e7ddfafc
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: netflix_SE |178.34Mb
  server: 51.20.125.235
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: disney_netflix_US |42.33Mb
  server: 163.192.49.195
  type: vmess
  port: 443
  uuid: bcb7c581-3c95-4569-a4e7-918141e91ea3
  alterId: 0
  cipher: auto
  network: http
  http-opts:
    path:
    - /
    headers:
      Host:
      - a.189.cn
  h2-opts: {}
- name: netflix_SE |132.22Mb
  server: 13.61.13.231
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: disney_netflix_US |44.01Mb
  server: 165.140.216.141
  type: vmess
  port: 443
  uuid: e7d72a8d-26f2-4b54-b366-0c43e0bcba7d
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: disney_netflix_US |141.26Mb
  server: 82.198.246.97
  type: vmess
  port: 180
  uuid: d13fc2f5-3e05-4795-81eb-44143a09e552
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _146 |35.75Mb
  server: 216.238.86.158
  type: vmess
  port: 34460
  udp: true
  uuid: 90be214d-048c-4ea2-a602-b8e4d4e51e36
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: disney_PT |118.57Mb
  server: 185.231.233.112
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: disney_TW |16.93Mb
  server: 103.127.218.91
  type: vmess
  port: 54693
  uuid: 1cef03ad-6343-408c-8121-cbd1fda2ee9d
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /1cef03ad
- name: disney_netflix_DE |195.25Mb
  server: 85.195.101.122
  type: vmess
  port: 40878
  uuid: f3d4167e-b15e-4e46-82e9-9286ef93fda7
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: netflix_HK |27.62Mb
  server: 8.210.184.105
  type: vmess
  port: 40374
  udp: true
  uuid: 36b76373-7a4f-4669-9113-7d247bcf2704
  alterId: 0
  cipher: auto
  network: http
  http-opts:
    method: GET
    path:
    - /
  h2-opts: {}
- name: disney_netflix_US |19.58Mb
  server: 192.204.47.79
  type: vmess
  port: 42277
  udp: true
  uuid: aee61b21-e85a-484b-f203-b245f1451cff
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: Relay_-ğŸ‡­ğŸ‡°HK_154 |16.82Mb
  server: 154.21.201.83
  type: vmess
  port: 443
  uuid: 4bf075f5-4d5e-4d39-f5ab-b32a86250f0e
  alterId: 0
  cipher: auto
  network: ws
  servername: hk.nbee.pp.ua
  http-opts: {}
  h2-opts: {}
  tls: true
  ws-opts:
    path: /aa
    headers:
      Host: hk.nbee.pp.ua
- name: _156 |10.36Mb
  server: 146.56.112.110
  type: vmess
  port: 8888
  uuid: e7c302f3-90d6-42dd-9d7d-94a3683a3707
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _159 |16.73Mb
  server: 154.201.76.172
  type: vmess
  port: 20990
  uuid: ba50e1fe-055f-4587-fd0d-36c8d6615192
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: disney_netflix_GB |268.31Mb
  server: 172.67.134.185
  type: trojan
  port: 443
  udp: true
  password: POORIARED
  sni: reDfRee8.REDFree8.ir
  ws-opts:
    path: /eyJqdW5rIjoiVUl6eXhLZkkwUTJ3ZzkiLCJwcm90b2NvbCI6InRyIiwibW9kZSI6InByb3h5aXAiLCJwYW5lbElQcyI6W119?ed=2560
    headers:
      Host: reDfRee8.REDFree8.ir
  network: ws
- name: _171 |20.21Mb
  server: 15.235.41.200
  type: vmess
  port: 80
  uuid: 58fe1542-5290-40ad-815a-77707a81afe5
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /IOebhLMhl1CTbFHbL95myfRX2
- name: Relay_-ğŸ‡¯ğŸ‡µJP_136 |18.30Mb
  server: yg1.ygkkk.dpdns.org
  type: vmess
  port: 443
  udp: true
  uuid: 130ec091-df05-4af9-9695-dc982e98a8ec
  alterId: 0
  cipher: auto
  network: ws
  servername: jporacleyg2.336697.xyz
  http-opts: {}
  h2-opts: {}
  tls: true
  ws-opts:
    path: /130ec091-df05-4af9-9695-dc982e98a8ec-vm
    headers:
      Host: jporacleyg2.336697.xyz
- name: _157 |10.94Mb
  server: 8.218.105.196
  type: vmess
  port: 52752
  uuid: 925bdbf5-72be-4437-bebf-441c61089f6b
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: netflix_AE |42.07Mb
  server: 89.31.120.192
  type: vmess
  port: 443
  uuid: 44537595-9ccc-4b83-8936-5f9ad3229019
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: netflix_CA |24.44Mb
  server: 38.96.254.102
  type: trojan
  port: 18509
  password: .ie4rghJuMkcf0oF
  sni: shoppingmall.electricbanana.click
- name: _165 |10.92Mb
  server: 156.245.232.15
  type: vmess
  port: 53947
  udp: true
  uuid: 8cb243df-fa82-472c-be25-b00acd4fcd3f
  alterId: 0
  cipher: auto
  network: http
  http-opts:
    method: GET
    path:
    - /ä½¿ç”¨æ­¤èŠ‚ç‚¹éœ€è¦å…ˆæ²æµ´ç„šé¦™ç„¶åç»™ç¾¤ä¸»ç£•800ä¸ªå“å¤´(à²¡Ï‰à²¡)
  h2-opts: {}
- name: _179 |11.10Mb
  server: 153.121.65.107
  type: trojan
  port: 3093
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: _172 |17.12Mb
  server: 47.242.140.52
  type: vmess
  port: 34815
  uuid: 1a46b66c-6ba9-4e9c-aa0b-0ebac2b69e32
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /arki
- name: _182 |10.84Mb
  server: 153.121.53.187
  type: trojan
  port: 3093
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: netflix_SE |166.64Mb
  server: 70.34.218.149
  type: trojan
  port: 11930
  password: BaeSzHdfJIR13l67
  sni: softpillow.silentrocket.click
- name: disney_HK |28.66Mb
  server: 58.152.53.174
  type: trojan
  port: 443
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: Relay_-ğŸ‡¯ğŸ‡µJP_141 |18.56Mb
  server: yg6.ygkkk.dpdns.org
  type: vmess
  port: 80
  udp: true
  uuid: 130ec091-df05-4af9-9695-dc982e98a8ec
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /130ec091-df05-4af9-9695-dc982e98a8ec-vm?ed=2048
    headers:
      Host: jporacleyg2.336697.xyz
- name: netflix_MX |42.57Mb
  server: 216.238.87.47
  type: vmess
  country: ğŸ‡²ğŸ‡½MX
  port: 27502
  uuid: b8155ce4-7e08-4c40-800f-8671312b7124
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_HK |16.03Mb
  server: 58.152.25.242
  type: trojan
  port: 443
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: disney_netflix_FR |19.13Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 27092
  uuid: a0596ba6-72a3-4366-8992-77088da65bd8
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_FR |23.22Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 40433
  uuid: d8fd8955-78db-49ba-d86f-3e4729f6ac4d
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: netflix_NL |208.32Mb
  server: 82.38.31.217
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: netflix_NL |217.09Mb
  server: 82.38.31.194
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: disney_HK |15.62Mb
  server: 45.207.157.29
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 13852
  uuid: 845764df-ecb3-4b13-bed2-bf1551b68e9a
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: netflix_CH |152.90Mb
  server: 86.106.84.198
  type: ss
  country: ğŸ‡·ğŸ‡´RO
  port: 13265
  password: phizo046s4oqsm33sfvm
  cipher: aes-128-gcm
- name: netflix_LT |86.57Mb
  server: 45.12.136.170
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: l668XHPejoSNNuD66BYzyehaCpZexiF7
  cipher: chacha20-ietf-poly1305
- name: Relay_-ğŸ‡¨ğŸ‡­CH_144 |70.50Mb
  server: lt.fxlcn.com
  type: vmess
  port: 45288
  uuid: 469e0b31-30c3-4dab-800d-711232634ce1
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: disney_netflix_US |25.22Mb
  server: cf.fovi.tk
  type: vmess
  country: ğŸZZ
  port: 443
  uuid: bf67437e-6c90-45ca-abc2-c7240a5ce2aa
  alterId: 0
  cipher: auto
  network: ws
  servername: foxpol.fovi.tk
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /eisasqa
    headers:
      HOST: foxpol.fovi.tk
- name: disney_netflix_DE |126.28Mb
  server: cpanel.navar1.ir
  type: vmess
  country: ğŸ‡©ğŸ‡ªDE
  port: 100
  uuid: 95c6f6f0-84f7-4443-8a50-a59f8e66f5ee
  alterId: 0
  cipher: auto
  network: tcp
  servername: cpanel.navar1.ir
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - netflix_AT |93.23Mb
  - _114 |12.25Mb
  - netflix_CH |68.95Mb
  - disney_HK |10.91Mb
  - disney_netflix_DE |283.77Mb
  - disney_SG |109.21Mb
  - netflix_SE |178.34Mb
  - disney_netflix_US |42.33Mb
  - netflix_SE |132.22Mb
  - disney_netflix_US |44.01Mb
  - disney_netflix_US |141.26Mb
  - _146 |35.75Mb
  - disney_PT |118.57Mb
  - disney_TW |16.93Mb
  - disney_netflix_DE |195.25Mb
  - netflix_HK |27.62Mb
  - disney_netflix_US |19.58Mb
  - Relay_-ğŸ‡­ğŸ‡°HK_154 |16.82Mb
  - _156 |10.36Mb
  - _159 |16.73Mb
  - disney_netflix_GB |268.31Mb
  - _171 |20.21Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_136 |18.30Mb
  - _157 |10.94Mb
  - netflix_AE |42.07Mb
  - netflix_CA |24.44Mb
  - _165 |10.92Mb
  - _179 |11.10Mb
  - _172 |17.12Mb
  - _182 |10.84Mb
  - netflix_SE |166.64Mb
  - disney_HK |28.66Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_141 |18.56Mb
  - netflix_MX |42.57Mb
  - disney_HK |16.03Mb
  - disney_netflix_FR |19.13Mb
  - disney_netflix_FR |23.22Mb
  - netflix_NL |208.32Mb
  - netflix_NL |217.09Mb
  - disney_HK |15.62Mb
  - netflix_CH |152.90Mb
  - netflix_LT |86.57Mb
  - Relay_-ğŸ‡¨ğŸ‡­CH_144 |70.50Mb
  - disney_netflix_US |25.22Mb
  - disney_netflix_DE |126.28Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - netflix_AT |93.23Mb
  - _114 |12.25Mb
  - netflix_CH |68.95Mb
  - disney_HK |10.91Mb
  - disney_netflix_DE |283.77Mb
  - disney_SG |109.21Mb
  - netflix_SE |178.34Mb
  - disney_netflix_US |42.33Mb
  - netflix_SE |132.22Mb
  - disney_netflix_US |44.01Mb
  - disney_netflix_US |141.26Mb
  - _146 |35.75Mb
  - disney_PT |118.57Mb
  - disney_TW |16.93Mb
  - disney_netflix_DE |195.25Mb
  - netflix_HK |27.62Mb
  - disney_netflix_US |19.58Mb
  - Relay_-ğŸ‡­ğŸ‡°HK_154 |16.82Mb
  - _156 |10.36Mb
  - _159 |16.73Mb
  - disney_netflix_GB |268.31Mb
  - _171 |20.21Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_136 |18.30Mb
  - _157 |10.94Mb
  - netflix_AE |42.07Mb
  - netflix_CA |24.44Mb
  - _165 |10.92Mb
  - _179 |11.10Mb
  - _172 |17.12Mb
  - _182 |10.84Mb
  - netflix_SE |166.64Mb
  - disney_HK |28.66Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_141 |18.56Mb
  - netflix_MX |42.57Mb
  - disney_HK |16.03Mb
  - disney_netflix_FR |19.13Mb
  - disney_netflix_FR |23.22Mb
  - netflix_NL |208.32Mb
  - netflix_NL |217.09Mb
  - disney_HK |15.62Mb
  - netflix_CH |152.90Mb
  - netflix_LT |86.57Mb
  - Relay_-ğŸ‡¨ğŸ‡­CH_144 |70.50Mb
  - disney_netflix_US |25.22Mb
  - disney_netflix_DE |126.28Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
