port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: disney_netflix_GB |60.65Mb
  server: koma-yt.pages.dev
  type: trojan
  port: 8443
  udp: true
  password: 8r<[9'l6hAO#8ZQi
  sni: Koma-YT.PAGeS.Dev
  ws-opts:
    path: /tro8sFW1S91B6sZrM1?ed=2560
    headers:
      Host: Koma-YT.PAGeS.Dev
  network: ws
- name: disney_DO |58.89Mb
  server: 45.150.52.40
  type: vmess
  port: 443
  uuid: c31777a1-2ee6-4864-db4c-a79fcbc8188b
  alterId: 0
  cipher: auto
  network: ws
  servername: xsj011-3.facai2024.com
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /c31777a1
- name: netflix_US |10.77Mb
  server: 202.181.103.235
  type: trojan
  port: 2890
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: netflix_US |10.88Mb
  server: 160.16.214.6
  type: trojan
  port: 2890
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: netflix_JP |19.98Mb
  server: 160.16.242.183
  type: trojan
  port: 1331
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: Relay_-ðŸ‡¯ðŸ‡µJP_140 |11.53Mb
  server: 160.16.229.223
  type: trojan
  port: 3093
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: disney_US |203.58Mb
  server: 185.221.23.251
  type: vmess
  country: ðŸ‡ªðŸ‡¸ES
  port: 29431
  uuid: 8b78363e-3c3a-44ab-f0d8-f13d950c8572
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_HK |11.93Mb
  server: 58.152.30.120
  type: trojan
  port: 443
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: disney_netflix_FR |34.28Mb
  server: 208.76.223.218
  type: vmess
  country: ðŸ‡ªðŸ‡¸ES
  port: 40433
  uuid: d8fd8955-78db-49ba-d86f-3e4729f6ac4d
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_NL |250.60Mb
  server: 82.38.31.184
  type: ss
  country: ðŸ‡¬ðŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_NL |366.20Mb
  server: 51.15.17.169
  type: ss
  country: ðŸ‡¬ðŸ‡§GB
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ðŸ‡¬ðŸ‡§GB_156 |11.39Mb
  server: 195.66.27.148
  type: ss
  country: ðŸ‡¬ðŸ‡§GB
  port: 28709
  password: hShp1Km0NcFSmSigc8ozky
  cipher: chacha20-ietf-poly1305
- name: netflix_US |40.60Mb
  server: 38.14.99.163
  type: vmess
  country: ðŸ‡ºðŸ‡¸US
  port: 59807
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: auto
  network: tcp
  servername: 38.14.99.163
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: netflix_US |31.05Mb
  server: 209.74.86.194
  type: ss
  country: ðŸ‡ºðŸ‡¸US
  port: 14936
  password: ppgtoOHdm7cszGunBWBTqQ
  cipher: chacha20-ietf-poly1305
- name: netflix_IE |101.50Mb
  server: 146.70.90.196
  type: ss
  country: ðŸ‡®ðŸ‡ªIE
  port: 17454
  password: u8gp148iz90ddoo6ms37
  cipher: aes-128-gcm
- name: ðŸ‡¬ðŸ‡·GR_158 |360.95Mb
  server: 192.71.166.100
  type: ss
  country: ðŸ‡¬ðŸ‡·GR
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: disney_netflix_NL |106.70Mb
  server: 109.71.246.210
  type: ss
  country: ðŸ‡·ðŸ‡ºRU
  port: 56689
  password: YQCSKoCF3QazW8YlvDBWA4
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_SE |45.91Mb
  server: 91.186.217.246
  type: ss
  country: ðŸ‡ºðŸ‡¸US
  port: 31764
  password: Ftc17VH9ZXQON5vslJCYmv
  cipher: chacha20-ietf-poly1305
- name: Relay_-ðŸ‡ºðŸ‡¸US_108 |24.89Mb
  server: clr.ducks.tel
  type: ss
  port: 17844
  password: '907560230'
  cipher: chacha20-ietf-poly1305
proxy-groups:
- name: ðŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - disney_netflix_GB |60.65Mb
  - disney_DO |58.89Mb
  - netflix_US |10.77Mb
  - netflix_US |10.88Mb
  - netflix_JP |19.98Mb
  - Relay_-ðŸ‡¯ðŸ‡µJP_140 |11.53Mb
  - disney_US |203.58Mb
  - disney_HK |11.93Mb
  - disney_netflix_FR |34.28Mb
  - disney_netflix_NL |250.60Mb
  - disney_netflix_NL |366.20Mb
  - ðŸ‡¬ðŸ‡§GB_156 |11.39Mb
  - netflix_US |40.60Mb
  - netflix_US |31.05Mb
  - netflix_IE |101.50Mb
  - ðŸ‡¬ðŸ‡·GR_158 |360.95Mb
  - disney_netflix_NL |106.70Mb
  - disney_netflix_SE |45.91Mb
  - Relay_-ðŸ‡ºðŸ‡¸US_108 |24.89Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - disney_netflix_GB |60.65Mb
  - disney_DO |58.89Mb
  - netflix_US |10.77Mb
  - netflix_US |10.88Mb
  - netflix_JP |19.98Mb
  - Relay_-ðŸ‡¯ðŸ‡µJP_140 |11.53Mb
  - disney_US |203.58Mb
  - disney_HK |11.93Mb
  - disney_netflix_FR |34.28Mb
  - disney_netflix_NL |250.60Mb
  - disney_netflix_NL |366.20Mb
  - ðŸ‡¬ðŸ‡§GB_156 |11.39Mb
  - netflix_US |40.60Mb
  - netflix_US |31.05Mb
  - netflix_IE |101.50Mb
  - ðŸ‡¬ðŸ‡·GR_158 |360.95Mb
  - disney_netflix_NL |106.70Mb
  - disney_netflix_SE |45.91Mb
  - Relay_-ðŸ‡ºðŸ‡¸US_108 |24.89Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ðŸš€ èŠ‚ç‚¹é€‰æ‹©
