port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: ' |14.21Mb'
  server: 23.95.72.81
  type: ss
  port: 443
  udp: true
  password: UAMVtHm54uahd6SiN5WcD16rsPSdabPG
  cipher: chacha20-ietf-poly1305
- name: ' |42.54Mb'
  server: 104.192.226.106
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ' |52.53Mb'
  server: 137.184.174.93
  type: ss
  port: 8080
  udp: true
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: Relay_ |32.93Mb
  server: 104.18.13.167
  type: vmess
  port: 443
  udp: true
  uuid: 24254866-770c-41b4-9404-3f50524f425b
  alterId: 0
  cipher: auto
  network: ws
  servername: 24254866-770c-41b4-9404-3f50524f425b.mihomo.baby
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /saoihgreg9384gh8934
    headers:
      Host: 24254866-770c-41b4-9404-3f50524f425b.mihomo.baby
- name: Relay_ |14.27Mb
  server: 23.227.38.178
  type: trojan
  port: 443
  udp: true
  password: 832afa39-df88-47ba-8234-45ef9c7080de
  sni: q6clkp794liy3y90.hktimecsgo.xyz
  skip-cert-verify: true
  ws-opts:
    path: /images
    headers:
      Host: q6clkp794liy3y90.hktimecsgo.xyz
  network: ws
- name: netflix_IE |169.74Mb
  server: 18.203.224.78
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: ' |13.28Mb'
  server: 82.38.31.176
  type: ss
  port: 8080
  udp: true
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: Relay_ |252.43Mb
  server: 82.38.31.218
  type: ss
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ' |11.81Mb'
  server: 45.87.175.155
  type: ss
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: Relay_ |20.67Mb
  server: 23.227.38.178
  type: trojan
  port: 443
  udp: true
  password: a544940a-2c1c-4723-96cc-d03053a95530
  sni: q6clkp794liy3y90.hktimecsgo.xyz
  skip-cert-verify: true
  ws-opts:
    path: /images
    headers:
      Host: q6clkp794liy3y90.hktimecsgo.xyz
  network: ws
- name: Relay_ |22.72Mb
  server: 23.227.38.178
  type: trojan
  port: 443
  udp: true
  password: aff9928f-7ba3-45fb-b56d-4dec45653ca9
  sni: q6clkp794liy3y90.hktimecsgo.xyz
  skip-cert-verify: true
  ws-opts:
    path: /images
    headers:
      Host: q6clkp794liy3y90.hktimecsgo.xyz
  network: ws
- name: ' |125.67Mb'
  server: 45.15.126.19
  type: ss
  port: 443
  udp: true
  password: 6Ts2ZDTQAf3hkFoB8AFufDwsGrlF4e2t
  cipher: chacha20-ietf-poly1305
- name: _248 |86.43Mb
  server: 109.71.246.210
  type: ss
  port: 56689
  udp: true
  password: YQCSKoCF3QazW8YlvDBWA4
  cipher: chacha20-ietf-poly1305
- name: ' |10.64Mb'
  server: 95.111.222.113
  type: ss
  port: 443
  udp: true
  password: SVt6ZiWzRI1Yxeig4xBZwiJOt6ceXwGa
  cipher: chacha20-ietf-poly1305
- name: Relay_-ğŸ‡¯ğŸ‡µJP_265 |11.54Mb
  server: 160.16.117.182
  type: trojan
  port: 3169
  password: 2cf6d686799e6fa95316394064f26c0a
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡ºğŸ‡¸US_296 |42.56Mb
  server: 141.193.213.199
  type: trojan
  port: 443
  udp: true
  password: a544940a-2c1c-4723-96cc-d03053a95530
  sni: 26z68w0ecxbuyf89.ukgogo202511.top
  skip-cert-verify: true
  ws-opts:
    path: /images
    headers:
      Host: 26z68w0ecxbuyf89.ukgogo202511.top
  network: ws
- name: Relay_ |19.13Mb
  server: 160.16.70.180
  type: trojan
  port: 4054
  password: 2cf6d686799e6fa95316394064f26c0a
  sni: www.nintendogames.net
- name: Relay_ |10.27Mb
  server: 153.121.39.240
  type: trojan
  port: 3093
  password: 2cf6d686799e6fa95316394064f26c0a
  sni: www.nintendogames.net
- name: Relay_ |18.96Mb
  server: 160.16.106.144
  type: trojan
  port: 127
  password: 2cf6d686799e6fa95316394064f26c0a
  sni: www.nintendogames.net
- name: Relay_ |13.64Mb
  server: 160.16.106.144
  type: trojan
  port: 3169
  password: 2cf6d686799e6fa95316394064f26c0a
  sni: www.nintendogames.net
- name: Relay_ |14.43Mb
  server: 23.227.38.178
  type: trojan
  port: 443
  udp: true
  password: 8b45d379-702f-41b3-a6b2-9c87a01dcd5c
  sni: q6clkp794liy3y90.hktimecsgo.xyz
  skip-cert-verify: true
  ws-opts:
    path: /images
    headers:
      Host: q6clkp794liy3y90.hktimecsgo.xyz
  network: ws
- name: _305 |40.95Mb
  server: 149.28.76.252
  type: trojan
  port: 443
  udp: true
  password: 7f7fea1d-16cf-3f0b-95c8-2dbb2fc5a97c
  sni: usa.sstank.top
  skip-cert-verify: true
- name: Relay_ |10.94Mb
  server: 153.121.76.9
  type: trojan
  port: 4054
  password: 2cf6d686799e6fa95316394064f26c0a
  sni: www.nintendogames.net
- name: Relay_ |31.86Mb
  server: usiys.southbyte.xyz
  type: trojan
  port: 5897
  udp: true
  password: fg20mtCFHy
  sni: usiys.southbyte.xyz
  skip-cert-verify: true
- name: Relay_ |30.15Mb
  server: us19-25.998998.best
  type: vmess
  port: 443
  udp: true
  uuid: 24254866-770c-41b4-9404-3f50524f425b
  alterId: 0
  cipher: auto
  network: ws
  servername: 24254866-770c-41b4-9404-3f50524f425b.mihomo.baby
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /saoihgreg9384gh8934
    headers:
      Host: 24254866-770c-41b4-9404-3f50524f425b.mihomo.baby
- name: Relay_ |21.96Mb
  server: 153.121.44.99
  type: trojan
  port: 3093
  password: 2cf6d686799e6fa95316394064f26c0a
  sni: www.nintendogames.net
- name: disney_DE |80.15Mb
  server: uk2-2.998998.best
  type: vmess
  port: 443
  udp: true
  uuid: 24254866-770c-41b4-9404-3f50524f425b
  alterId: 0
  cipher: auto
  network: ws
  servername: 24254866-770c-41b4-9404-3f50524f425b.placeunaorder.fun
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /logcatxiouerd34try9
    headers:
      Host: 24254866-770c-41b4-9404-3f50524f425b.placeunaorder.fun
- name: disney_FR |125.94Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 27092
  uuid: a0596ba6-72a3-4366-8992-77088da65bd8
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_NL |300.57Mb
  server: 82.38.31.194
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ' |47.97Mb'
  server: 107.23.148.46
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: disney_HK |10.48Mb
  server: cdnfire.xiaomispeed.com
  type: trojan
  port: 21104
  udp: true
  password: dfde1bb1-41b7-4a1e-b757-7aa2378ccf4d
  sni: cdnfire.xiaomispeed.com
  skip-cert-verify: true
- name: disney_netflix_NL |340.40Mb
  server: 82.38.31.210
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: Relay_ |12.91Mb
  server: 82.38.31.217
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸ‡¬ğŸ‡§GB-ğŸ‡·ğŸ‡´RO_312 |93.04Mb
  server: gaming.aliusvpn.com
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8388
  password: YTJLxL9qJWPNmX_uXvNQrJBH31LhtM1o
  cipher: chacha20-ietf-poly1305
- name: ' |76.36Mb'
  server: 82.38.31.191
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_NL |22.42Mb
  server: 45.87.175.174
  type: ss
  country: ğŸ‡±ğŸ‡¹ LT
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: disney_BG |73.12Mb
  server: 79.110.62.72
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 17844
  password: YTJLxL9qJWPNmX_uXvNQrJBH31LhtM1o
  cipher: chacha20-ietf-poly1305
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - ' |14.21Mb'
  - ' |42.54Mb'
  - ' |52.53Mb'
  - Relay_ |32.93Mb
  - Relay_ |14.27Mb
  - netflix_IE |169.74Mb
  - ' |13.28Mb'
  - Relay_ |252.43Mb
  - ' |11.81Mb'
  - Relay_ |20.67Mb
  - Relay_ |22.72Mb
  - ' |125.67Mb'
  - _248 |86.43Mb
  - ' |10.64Mb'
  - Relay_-ğŸ‡¯ğŸ‡µJP_265 |11.54Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_296 |42.56Mb
  - Relay_ |19.13Mb
  - Relay_ |10.27Mb
  - Relay_ |18.96Mb
  - Relay_ |13.64Mb
  - Relay_ |14.43Mb
  - _305 |40.95Mb
  - Relay_ |10.94Mb
  - Relay_ |31.86Mb
  - Relay_ |30.15Mb
  - Relay_ |21.96Mb
  - disney_DE |80.15Mb
  - disney_FR |125.94Mb
  - disney_netflix_NL |300.57Mb
  - ' |47.97Mb'
  - disney_HK |10.48Mb
  - disney_netflix_NL |340.40Mb
  - Relay_ |12.91Mb
  - Relay_ğŸ‡¬ğŸ‡§GB-ğŸ‡·ğŸ‡´RO_312 |93.04Mb
  - ' |76.36Mb'
  - disney_netflix_NL |22.42Mb
  - disney_BG |73.12Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - ' |14.21Mb'
  - ' |42.54Mb'
  - ' |52.53Mb'
  - Relay_ |32.93Mb
  - Relay_ |14.27Mb
  - netflix_IE |169.74Mb
  - ' |13.28Mb'
  - Relay_ |252.43Mb
  - ' |11.81Mb'
  - Relay_ |20.67Mb
  - Relay_ |22.72Mb
  - ' |125.67Mb'
  - _248 |86.43Mb
  - ' |10.64Mb'
  - Relay_-ğŸ‡¯ğŸ‡µJP_265 |11.54Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_296 |42.56Mb
  - Relay_ |19.13Mb
  - Relay_ |10.27Mb
  - Relay_ |18.96Mb
  - Relay_ |13.64Mb
  - Relay_ |14.43Mb
  - _305 |40.95Mb
  - Relay_ |10.94Mb
  - Relay_ |31.86Mb
  - Relay_ |30.15Mb
  - Relay_ |21.96Mb
  - disney_DE |80.15Mb
  - disney_FR |125.94Mb
  - disney_netflix_NL |300.57Mb
  - ' |47.97Mb'
  - disney_HK |10.48Mb
  - disney_netflix_NL |340.40Mb
  - Relay_ |12.91Mb
  - Relay_ğŸ‡¬ğŸ‡§GB-ğŸ‡·ğŸ‡´RO_312 |93.04Mb
  - ' |76.36Mb'
  - disney_netflix_NL |22.42Mb
  - disney_BG |73.12Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
