port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: _213 |13.17Mb
  server: 66.23.207.82
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _221 |53.15Mb
  server: 167.160.90.178
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _205 |10.84Mb
  server: 147.78.1.230
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _238 |10.49Mb
  server: 173.234.29.2
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸ‡¨ğŸ‡¦CA-ğŸ‡¨ğŸ‡¦CA_252 |25.70Mb
  server: 79.127.200.169
  type: ss
  country: ğŸ‡¨ğŸ‡¦CA
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: Pool__212 |27.26Mb
  server: 62.100.205.177
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _211 |23.91Mb
  server: 62.100.205.100
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _229 |24.16Mb
  server: 109.61.46.43
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _204 |20.72Mb
  server: 176.126.83.158
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _231 |12.83Mb
  server: 212.102.54.45
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _225 |32.94Mb
  server: 91.219.237.163
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _235 |14.04Mb
  server: 37.143.130.203
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡©ğŸ‡ªDE_268 |22.75Mb
  server: 18.196.31.30
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: _228 |24.22Mb
  server: 45.82.252.109
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡©ğŸ‡ªDE_272 |10.60Mb
  server: 81.19.141.45
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 443
  password: OL7MQydIsTbln3xOq4lVvM
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡©ğŸ‡ªDE_274 |11.83Mb
  server: 35.159.221.104
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡©ğŸ‡ªDE_281 |19.56Mb
  server: 18.195.116.149
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡©ğŸ‡ªDE_284 |25.74Mb
  server: 3.79.189.65
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡ªğŸ‡¸ES_293 |27.83Mb
  server: 194.87.45.189
  type: ss
  country: ğŸ‡ªğŸ‡¸ES
  port: 443
  password: AnxMfj2oL2RaZTQVfVd5EY
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ªğŸ‡¸ES_296 |41.32Mb
  server: 194.87.45.189
  type: ss
  country: ğŸ‡ªğŸ‡¸ES
  port: 443
  password: 9GyGpqucu0IozRSh15x0eS
  cipher: chacha20-ietf-poly1305
- name: _240 |17.05Mb
  server: 38.60.250.107
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ªğŸ‡¸ES_298 |27.46Mb
  server: 194.87.45.189
  type: ss
  country: ğŸ‡ªğŸ‡¸ES
  port: 443
  password: 2xv6krM00RVVZx8EzKl7F1
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_314 |23.24Mb
  server: 18.170.218.19
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡¬ğŸ‡§GB_315 |27.85Mb
  server: 35.179.184.210
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡ªğŸ‡¸ES_300 |23.79Mb
  server: 194.87.45.189
  type: ss
  country: ğŸ‡ªğŸ‡¸ES
  port: 443
  password: sZXSQhZw1EWmHwPKWVBWBa
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ªğŸ‡¸ES_299 |29.71Mb
  server: 194.87.45.189
  type: ss
  country: ğŸ‡ªğŸ‡¸ES
  port: 443
  password: uFiYu7SpjpkmO6ZYaO16xz
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_323 |12.25Mb
  server: 35.179.149.224
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡¬ğŸ‡§GB_316 |13.93Mb
  server: 3.9.171.152
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡ªğŸ‡¸ES_304 |24.79Mb
  server: 194.87.45.189
  type: ss
  country: ğŸ‡ªğŸ‡¸ES
  port: 443
  password: 5z9xQGBodSzrYakdQFAP7I
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_330 |10.30Mb
  server: 18.175.147.245
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡¬ğŸ‡§GB_335 |11.91Mb
  server: 35.178.48.198
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡¬ğŸ‡¹GT_342 |23.00Mb
  server: 185.47.254.87
  type: ss
  country: ğŸ‡¬ğŸ‡¹GT
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_336 |21.71Mb
  server: 18.171.186.242
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡¬ğŸ‡§GB_337 |27.36Mb
  server: 18.134.245.70
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡®ğŸ‡ªIE_344 |30.87Mb
  server: 196.196.192.58
  type: ss
  country: ğŸ‡®ğŸ‡ªIE
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_340 |25.59Mb
  server: 18.170.77.155
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡ºğŸ‡¸US_437 |15.49Mb
  server: 71.19.148.143
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: p78naCf2EfOlRSLTX0wFVx
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡µğŸ‡±PL_378 |12.10Mb
  server: 77.83.246.74
  type: ss
  country: ğŸ‡µğŸ‡±PL
  port: 443
  password: tVZZkK258knbSmtMKjTEPQ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¸ğŸ‡°SK_405 |24.65Mb
  server: 193.37.255.38
  type: ss
  country: ğŸ‡¸ğŸ‡°SK
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_447 |19.40Mb
  server: 167.88.61.110
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 6679
  password: TEzjfAYq2IjtuoS
  cipher: aes-256-gcm
- name: ğŸ‡ºğŸ‡¸US_448 |13.59Mb
  server: 167.88.61.110
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 7002
  password: RexnBgU7EV5ADxG
  cipher: aes-256-gcm
- name: ğŸ‡ºğŸ‡¸US_424 |12.22Mb
  server: 95.164.123.39
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 32821
  password: yXQLzA62V0b4swsrwFi5bL
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¹ğŸ‡·TR_406 |47.92Mb
  server: 45.89.52.66
  type: ss
  country: ğŸ‡¹ğŸ‡·TR
  port: 9029
  password: dU3DSNS8wYPXzEKw
  cipher: aes-256-cfb
- name: ğŸ‡¸ğŸ‡¨SC_396 |19.27Mb
  server: 154.205.150.157
  type: ss
  country: ğŸ‡¸ğŸ‡¨SC
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_440 |22.72Mb
  server: 38.247.64.176
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - _213 |13.17Mb
  - _221 |53.15Mb
  - _205 |10.84Mb
  - _238 |10.49Mb
  - Relay_ğŸ‡¨ğŸ‡¦CA-ğŸ‡¨ğŸ‡¦CA_252 |25.70Mb
  - Pool__212 |27.26Mb
  - _211 |23.91Mb
  - _229 |24.16Mb
  - _204 |20.72Mb
  - _231 |12.83Mb
  - _225 |32.94Mb
  - _235 |14.04Mb
  - ğŸ‡©ğŸ‡ªDE_268 |22.75Mb
  - _228 |24.22Mb
  - ğŸ‡©ğŸ‡ªDE_272 |10.60Mb
  - ğŸ‡©ğŸ‡ªDE_274 |11.83Mb
  - ğŸ‡©ğŸ‡ªDE_281 |19.56Mb
  - ğŸ‡©ğŸ‡ªDE_284 |25.74Mb
  - ğŸ‡ªğŸ‡¸ES_293 |27.83Mb
  - ğŸ‡ªğŸ‡¸ES_296 |41.32Mb
  - _240 |17.05Mb
  - ğŸ‡ªğŸ‡¸ES_298 |27.46Mb
  - ğŸ‡¬ğŸ‡§GB_314 |23.24Mb
  - ğŸ‡¬ğŸ‡§GB_315 |27.85Mb
  - ğŸ‡ªğŸ‡¸ES_300 |23.79Mb
  - ğŸ‡ªğŸ‡¸ES_299 |29.71Mb
  - ğŸ‡¬ğŸ‡§GB_323 |12.25Mb
  - ğŸ‡¬ğŸ‡§GB_316 |13.93Mb
  - ğŸ‡ªğŸ‡¸ES_304 |24.79Mb
  - ğŸ‡¬ğŸ‡§GB_330 |10.30Mb
  - ğŸ‡¬ğŸ‡§GB_335 |11.91Mb
  - ğŸ‡¬ğŸ‡¹GT_342 |23.00Mb
  - ğŸ‡¬ğŸ‡§GB_336 |21.71Mb
  - ğŸ‡¬ğŸ‡§GB_337 |27.36Mb
  - ğŸ‡®ğŸ‡ªIE_344 |30.87Mb
  - ğŸ‡¬ğŸ‡§GB_340 |25.59Mb
  - ğŸ‡ºğŸ‡¸US_437 |15.49Mb
  - ğŸ‡µğŸ‡±PL_378 |12.10Mb
  - ğŸ‡¸ğŸ‡°SK_405 |24.65Mb
  - ğŸ‡ºğŸ‡¸US_447 |19.40Mb
  - ğŸ‡ºğŸ‡¸US_448 |13.59Mb
  - ğŸ‡ºğŸ‡¸US_424 |12.22Mb
  - ğŸ‡¹ğŸ‡·TR_406 |47.92Mb
  - ğŸ‡¸ğŸ‡¨SC_396 |19.27Mb
  - ğŸ‡ºğŸ‡¸US_440 |22.72Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - _213 |13.17Mb
  - _221 |53.15Mb
  - _205 |10.84Mb
  - _238 |10.49Mb
  - Relay_ğŸ‡¨ğŸ‡¦CA-ğŸ‡¨ğŸ‡¦CA_252 |25.70Mb
  - Pool__212 |27.26Mb
  - _211 |23.91Mb
  - _229 |24.16Mb
  - _204 |20.72Mb
  - _231 |12.83Mb
  - _225 |32.94Mb
  - _235 |14.04Mb
  - ğŸ‡©ğŸ‡ªDE_268 |22.75Mb
  - _228 |24.22Mb
  - ğŸ‡©ğŸ‡ªDE_272 |10.60Mb
  - ğŸ‡©ğŸ‡ªDE_274 |11.83Mb
  - ğŸ‡©ğŸ‡ªDE_281 |19.56Mb
  - ğŸ‡©ğŸ‡ªDE_284 |25.74Mb
  - ğŸ‡ªğŸ‡¸ES_293 |27.83Mb
  - ğŸ‡ªğŸ‡¸ES_296 |41.32Mb
  - _240 |17.05Mb
  - ğŸ‡ªğŸ‡¸ES_298 |27.46Mb
  - ğŸ‡¬ğŸ‡§GB_314 |23.24Mb
  - ğŸ‡¬ğŸ‡§GB_315 |27.85Mb
  - ğŸ‡ªğŸ‡¸ES_300 |23.79Mb
  - ğŸ‡ªğŸ‡¸ES_299 |29.71Mb
  - ğŸ‡¬ğŸ‡§GB_323 |12.25Mb
  - ğŸ‡¬ğŸ‡§GB_316 |13.93Mb
  - ğŸ‡ªğŸ‡¸ES_304 |24.79Mb
  - ğŸ‡¬ğŸ‡§GB_330 |10.30Mb
  - ğŸ‡¬ğŸ‡§GB_335 |11.91Mb
  - ğŸ‡¬ğŸ‡¹GT_342 |23.00Mb
  - ğŸ‡¬ğŸ‡§GB_336 |21.71Mb
  - ğŸ‡¬ğŸ‡§GB_337 |27.36Mb
  - ğŸ‡®ğŸ‡ªIE_344 |30.87Mb
  - ğŸ‡¬ğŸ‡§GB_340 |25.59Mb
  - ğŸ‡ºğŸ‡¸US_437 |15.49Mb
  - ğŸ‡µğŸ‡±PL_378 |12.10Mb
  - ğŸ‡¸ğŸ‡°SK_405 |24.65Mb
  - ğŸ‡ºğŸ‡¸US_447 |19.40Mb
  - ğŸ‡ºğŸ‡¸US_448 |13.59Mb
  - ğŸ‡ºğŸ‡¸US_424 |12.22Mb
  - ğŸ‡¹ğŸ‡·TR_406 |47.92Mb
  - ğŸ‡¸ğŸ‡¨SC_396 |19.27Mb
  - ğŸ‡ºğŸ‡¸US_440 |22.72Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
