port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: Relay_-ğŸ‡¨ğŸ‡¦CA_362 |67.65Mb
  server: 79.127.200.169
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _352 |21.35Mb
  server: 196.196.192.58
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _351 |164.87Mb
  server: 45.87.175.167
  type: ss
  port: 8080
  udp: true
  password: QCXDxuDlTTMD7jtgHUjIoj
  cipher: chacha20-ietf-poly1305
- name: _354 |62.11Mb
  server: 45.14.245.2
  type: ss
  port: 443
  password: 17ZDORWIliQHuO6WRGHChXYMzdRtAYVP
  cipher: chacha20-ietf-poly1305
- name: _349 |222.44Mb
  server: 45.87.175.22
  type: ss
  port: 8080
  udp: true
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: _363 |205.97Mb
  server: 45.87.175.187
  type: ss
  port: 8080
  udp: true
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: _357 |498.89Mb
  server: 146.70.61.37
  type: ss
  port: 8080
  udp: true
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: _360 |22.13Mb
  server: 128.199.172.224
  type: ss
  port: 8080
  udp: true
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: _358 |43.76Mb
  server: 95.164.116.33
  type: ss
  port: 443
  password: pQmnC03JObbPhdh5FBJHgD6jnTLchsRA
  cipher: chacha20-ietf-poly1305
- name: _364 |55.57Mb
  server: 82.38.31.176
  type: ss
  port: 8080
  udp: true
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: disney_US |65.29Mb
  server: 79.127.200.162
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: _359 |22.77Mb
  server: 38.89.142.56
  type: ss
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _373 |20.85Mb
  server: 149.22.87.241
  type: ss
  port: 443
  udp: true
  password: shadowsocks
  cipher: aes-128-gcm
- name: _370 |225.51Mb
  server: 193.29.139.177
  type: ss
  port: 8080
  udp: true
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: disney_ES |31.40Mb
  server: 145.249.109.121
  type: ss
  port: 25512
  udp: true
  password: smSMfR9jqLgMkHuQtxSIWh
  cipher: chacha20-ietf-poly1305
- name: _376 |153.71Mb
  server: 62.100.205.100
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _369 |31.08Mb
  server: 119.59.98.58
  type: ss
  port: 990
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: chacha20-ietf-poly1305
- name: _372 |31.90Mb
  server: 119.59.98.58
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: _390 |43.01Mb
  server: 173.244.56.6
  type: ss
  port: 443
  udp: true
  password: shadowsocks
  cipher: aes-128-gcm
- name: _377 |682.99Mb
  server: 82.38.31.214
  type: ss
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: _367 |33.41Mb
  server: 103.97.203.227
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _378 |14.22Mb
  server: 89.221.225.15
  type: ss
  port: 443
  udp: true
  password: yCbQ4bry4otfifK7oel71NaXpPL9pYJb
  cipher: chacha20-ietf-poly1305
- name: _380 |932.93Mb
  server: 151.242.251.152
  type: ss
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: _384 |222.12Mb
  server: 82.38.31.199
  type: ss
  port: 8080
  udp: true
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: _388 |170.17Mb
  server: 141.98.101.178
  type: ss
  port: 443
  udp: true
  password: shadowsocks
  cipher: aes-128-gcm
- name: _389 |167.54Mb
  server: 82.38.31.190
  type: ss
  port: 8080
  udp: true
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: _385 |19.75Mb
  server: 185.192.124.188
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: _391 |129.63Mb
  server: 82.38.31.205
  type: ss
  port: 8080
  udp: true
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: _404 |50.53Mb
  server: 156.146.38.167
  type: ss
  port: 443
  udp: true
  password: shadowsocks
  cipher: aes-128-gcm
- name: _402 |19.87Mb
  server: 137.184.174.93
  type: ss
  port: 8080
  udp: true
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: _401 |13.92Mb
  server: 172.105.199.111
  type: ss
  port: 8080
  udp: true
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: _397 |219.07Mb
  server: 45.158.171.70
  type: ss
  port: 8080
  udp: true
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: _406 |49.84Mb
  server: 156.146.38.169
  type: ss
  port: 443
  udp: true
  password: shadowsocks
  cipher: aes-128-gcm
- name: _411 |50.83Mb
  server: 156.146.38.170
  type: ss
  port: 443
  udp: true
  password: shadowsocks
  cipher: aes-128-gcm
- name: _398 |10.03Mb
  server: 103.149.182.158
  type: ss
  port: 8388
  password: asd123456
  cipher: chacha20-ietf
- name: _409 |73.12Mb
  server: 103.35.189.136
  type: ss
  port: 443
  udp: true
  password: SS2QvbC9nqLp2sXXZo0BVy4slcErRuCt
  cipher: chacha20-ietf-poly1305
- name: _393 |40.53Mb
  server: 147.78.0.182
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _395 |41.72Mb
  server: 156.59.243.6
  type: ss
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _413 |13.04Mb
  server: 185.47.254.87
  type: ss
  port: 990
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: chacha20-ietf-poly1305
- name: Relay_-ğŸ‡«ğŸ‡·FR_403 |20.69Mb
  server: 193.135.174.135
  type: ss
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _412 |226.14Mb
  server: 193.29.139.132
  type: ss
  port: 8080
  udp: true
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: _414 |136.13Mb
  server: 185.82.73.212
  type: ss
  port: 8444
  udp: true
  password: _bypfvq6ra7g4n5yCCR9DoVeGya2XUUS
  cipher: chacha20-ietf-poly1305
- name: _405 |109.87Mb
  server: 38.165.233.93
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: disney_MX |29.28Mb
  server: 38.165.231.25
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _415 |12.35Mb
  server: 103.149.183.200
  type: ss
  port: 8388
  udp: true
  password: asd123456
  cipher: chacha20-ietf
- name: Relay_-ğŸ‡³ğŸ‡±NL_396 |144.05Mb
  server: backup.fleetfoxi.link
  type: ss
  port: 44884
  udp: true
  password: 2DGq3jvVRg5n3CcxmysGK2kmrgJeSNof12A76cZvVxqPpetyC1XEciCFufq5xKvRWGGnKVembpThuUSQhbZ7GMsZY4UVxEBw
  cipher: chacha20-ietf-poly1305
- name: _432 |55.18Mb
  server: 172.233.229.91
  type: vmess
  port: 14102
  udp: true
  uuid: 27ba87fc-583f-4763-9060-83cf0b9264db
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_US |33.72Mb
  server: 156.233.232.177
  type: vmess
  port: 44329
  uuid: 1ba1fb56-e235-419e-c193-1c291adad4a7
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
- name: disney_US |10.98Mb
  server: 156.233.232.192
  type: vmess
  port: 24004
  uuid: 582fcb35-20a0-452c-e179-4c759c62c494
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
- name: disney_US |17.59Mb
  server: 156.233.232.177
  type: vmess
  port: 24004
  uuid: 582fcb35-20a0-452c-e179-4c759c62c494
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
- name: disney_US |24.52Mb
  server: 156.233.232.192
  type: vmess
  port: 44329
  uuid: 1ba1fb56-e235-419e-c193-1c291adad4a7
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
- name: Relay_-ğŸ‡¯ğŸ‡µJP_435 |13.84Mb
  server: 160.16.87.174
  type: trojan
  port: 3169
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: _436 |16.06Mb
  server: 160.16.106.144
  type: trojan
  port: 2890
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: _439 |10.49Mb
  server: 160.16.106.144
  type: trojan
  port: 2760
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
  skip-cert-verify: true
- name: _441 |10.85Mb
  server: 160.16.131.243
  type: trojan
  port: 2760
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
  skip-cert-verify: true
- name: _443 |10.46Mb
  server: 160.16.124.55
  type: trojan
  port: 2890
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¯ğŸ‡µJP_444 |41.91Mb
  server: 160.16.229.223
  type: trojan
  port: 3169
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: _446 |16.24Mb
  server: 160.16.204.136
  type: trojan
  port: 2890
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: _437 |12.38Mb
  server: 47.242.225.242
  type: trojan
  port: 443
  udp: true
  password: 92690597d6298061459918a371e8d77d
  sni: hezijiasuqi.com
  skip-cert-verify: true
- name: ğŸ‡¨ğŸ‡¦CA_452 |30.63Mb
  server: 193.203.203.66
  type: ss
  country: ğŸ‡¨ğŸ‡¦CA
  port: 443
  password: S6jUK9Fw5fMHgNqlqXObHZWv8Tf4nEkm
  cipher: chacha20-ietf-poly1305
- name: _448 |38.73Mb
  server: 160.16.136.130
  type: trojan
  port: 2890
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: disney_AE |17.95Mb
  server: 217.60.249.112
  type: ss
  country: ğŸ‡®ğŸ‡·IR
  port: 443
  password: 0eC4ZBvStOgQEzTpCYjWN5
  cipher: chacha20-ietf-poly1305
- name: _449 |10.38Mb
  server: 160.16.116.227
  type: trojan
  port: 2760
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
  skip-cert-verify: true
- name: ğŸ‡¨ğŸ‡¦CA_451 |23.64Mb
  server: 185.213.23.63
  type: ss
  country: ğŸ‡¨ğŸ‡¦CA
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡§ğŸ‡·BR_450 |15.67Mb
  server: 185.192.124.188
  type: ss
  country: ğŸ‡§ğŸ‡·BR
  port: 990
  password: f8f7aCzcPKbsF8p3
  cipher: chacha20-ietf-poly1305
- name: disney_CH |181.69Mb
  server: 138.124.67.26
  type: ss
  country: ğŸ‡¨ğŸ‡­CH
  port: 25572
  password: nqcIfYHlpMn3jzqkNDjKaG
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_458 |192.81Mb
  server: 141.98.101.182
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: shadowsocks
  cipher: aes-128-gcm
- name: ğŸ‡±ğŸ‡¹LT_468 |924.67Mb
  server: 45.87.175.183
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_470 |942.36Mb
  server: 45.87.175.185
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_471 |866.61Mb
  server: 45.87.175.180
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: QCXDxuDlTTMD7jtgHUjIoj
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_472 |218.60Mb
  server: 45.87.175.190
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_475 |223.32Mb
  server: 45.87.175.175
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: QCXDxuDlTTMD7jtgHUjIoj
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡²ğŸ‡½MX_478 |133.07Mb
  server: 216.238.87.47
  type: vmess
  country: ğŸ‡²ğŸ‡½MX
  port: 27502
  uuid: b8155ce4-7e08-4c40-800f-8671312b7124
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_491 |40.66Mb
  server: 38.14.99.163
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 59807
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: auto
  network: tcp
  servername: 38.14.99.163
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡±ğŸ‡¹LT_474 |173.90Mb
  server: 45.87.175.200
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸZZ-ğŸ‡®ğŸ‡³IN_494 |109.11Mb
  server: 104.18.14.55
  type: vmess
  country: ğŸZZ
  port: 2052
  uuid: e6447786-8c85-443c-8017-7feaa673ff45
  alterId: 0
  cipher: auto
  network: ws
  servername: in4.123417.xyz
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
  ws-opts:
    path: /
    headers:
      HOST: in4.123417.xyz
- name: ğŸZZ_495 |76.05Mb
  server: hgtrojan.zabc.net
  type: vmess
  country: ğŸZZ
  port: 2083
  uuid: e6395c20-4571-4b34-d6b1-55a5d36e49ea
  alterId: 0
  cipher: auto
  network: ws
  servername: hgtrojan.zabc.net
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /e6395c20
    headers:
      HOST: hgtrojan.zabc.net
- name: disney_DO |59.09Mb
  server: 45.150.52.40
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  uuid: c31777a1-2ee6-4864-db4c-a79fcbc8188b
  alterId: 0
  cipher: auto
  network: ws
  servername: xsj011-3.facai2024.com
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /c31777a1
    headers:
      HOST: xsj011-3.facai2024.com
- name: ğŸ‡³ğŸ‡±NL_480 |60.17Mb
  server: 178.23.190.238
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 443
  password: uo7EbtqIwgZXXHmMv5LbLcOxptyPlNkh
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡» LV_476 |100.87Mb
  server: 46.183.217.204
  type: ss
  country: ğŸ‡±ğŸ‡» LV
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡³ğŸ‡±NL_481 |223.82Mb
  server: 193.29.139.209
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 8080
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡²ğŸ‡©MD_477 |33.88Mb
  server: 176.123.5.253
  type: ss
  country: ğŸ‡²ğŸ‡©MD
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡µğŸ‡¹PT_487 |52.27Mb
  server: 185.113.143.186
  type: ss
  country: ğŸ‡µğŸ‡¹PT
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¸ğŸ‡¬SG_488 |16.38Mb
  server: 68.183.227.45
  type: ss
  country: ğŸ‡¸ğŸ‡¬SG
  port: 8080
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: ğŸ‡¹ğŸ‡¼TW_489 |19.71Mb
  server: 38.54.107.101
  type: ss
  country: ğŸ‡¹ğŸ‡¼TW
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ ZZ_492 |191.59Mb
  server: 185.231.233.112
  type: ss
  country: ğŸ ZZ
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: Relay_ğŸZZ-ğŸ‡®ğŸ‡·IR_496 |16.79Mb
  server: cf.fovi.tk
  type: vmess
  country: ğŸZZ
  port: 443
  uuid: bf67437e-6c90-45ca-abc2-c7240a5ce2aa
  alterId: 0
  cipher: auto
  network: ws
  servername: foxlux.fovi.tk
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /eisasqa
    headers:
      HOST: foxlux.fovi.tk
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - Relay_-ğŸ‡¨ğŸ‡¦CA_362 |67.65Mb
  - _352 |21.35Mb
  - _351 |164.87Mb
  - _354 |62.11Mb
  - _349 |222.44Mb
  - _363 |205.97Mb
  - _357 |498.89Mb
  - _360 |22.13Mb
  - _358 |43.76Mb
  - _364 |55.57Mb
  - disney_US |65.29Mb
  - _359 |22.77Mb
  - _373 |20.85Mb
  - _370 |225.51Mb
  - disney_ES |31.40Mb
  - _376 |153.71Mb
  - _369 |31.08Mb
  - _372 |31.90Mb
  - _390 |43.01Mb
  - _377 |682.99Mb
  - _367 |33.41Mb
  - _378 |14.22Mb
  - _380 |932.93Mb
  - _384 |222.12Mb
  - _388 |170.17Mb
  - _389 |167.54Mb
  - _385 |19.75Mb
  - _391 |129.63Mb
  - _404 |50.53Mb
  - _402 |19.87Mb
  - _401 |13.92Mb
  - _397 |219.07Mb
  - _406 |49.84Mb
  - _411 |50.83Mb
  - _398 |10.03Mb
  - _409 |73.12Mb
  - _393 |40.53Mb
  - _395 |41.72Mb
  - _413 |13.04Mb
  - Relay_-ğŸ‡«ğŸ‡·FR_403 |20.69Mb
  - _412 |226.14Mb
  - _414 |136.13Mb
  - _405 |109.87Mb
  - disney_MX |29.28Mb
  - _415 |12.35Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_396 |144.05Mb
  - _432 |55.18Mb
  - disney_US |33.72Mb
  - disney_US |10.98Mb
  - disney_US |17.59Mb
  - disney_US |24.52Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_435 |13.84Mb
  - _436 |16.06Mb
  - _439 |10.49Mb
  - _441 |10.85Mb
  - _443 |10.46Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_444 |41.91Mb
  - _446 |16.24Mb
  - _437 |12.38Mb
  - ğŸ‡¨ğŸ‡¦CA_452 |30.63Mb
  - _448 |38.73Mb
  - disney_AE |17.95Mb
  - _449 |10.38Mb
  - ğŸ‡¨ğŸ‡¦CA_451 |23.64Mb
  - ğŸ‡§ğŸ‡·BR_450 |15.67Mb
  - disney_CH |181.69Mb
  - ğŸ‡¬ğŸ‡§GB_458 |192.81Mb
  - ğŸ‡±ğŸ‡¹LT_468 |924.67Mb
  - ğŸ‡±ğŸ‡¹LT_470 |942.36Mb
  - ğŸ‡±ğŸ‡¹LT_471 |866.61Mb
  - ğŸ‡±ğŸ‡¹LT_472 |218.60Mb
  - ğŸ‡±ğŸ‡¹LT_475 |223.32Mb
  - ğŸ‡²ğŸ‡½MX_478 |133.07Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_491 |40.66Mb
  - ğŸ‡±ğŸ‡¹LT_474 |173.90Mb
  - Relay_ğŸZZ-ğŸ‡®ğŸ‡³IN_494 |109.11Mb
  - ğŸZZ_495 |76.05Mb
  - disney_DO |59.09Mb
  - ğŸ‡³ğŸ‡±NL_480 |60.17Mb
  - ğŸ‡±ğŸ‡» LV_476 |100.87Mb
  - ğŸ‡³ğŸ‡±NL_481 |223.82Mb
  - ğŸ‡²ğŸ‡©MD_477 |33.88Mb
  - ğŸ‡µğŸ‡¹PT_487 |52.27Mb
  - ğŸ‡¸ğŸ‡¬SG_488 |16.38Mb
  - ğŸ‡¹ğŸ‡¼TW_489 |19.71Mb
  - ğŸ ZZ_492 |191.59Mb
  - Relay_ğŸZZ-ğŸ‡®ğŸ‡·IR_496 |16.79Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - Relay_-ğŸ‡¨ğŸ‡¦CA_362 |67.65Mb
  - _352 |21.35Mb
  - _351 |164.87Mb
  - _354 |62.11Mb
  - _349 |222.44Mb
  - _363 |205.97Mb
  - _357 |498.89Mb
  - _360 |22.13Mb
  - _358 |43.76Mb
  - _364 |55.57Mb
  - disney_US |65.29Mb
  - _359 |22.77Mb
  - _373 |20.85Mb
  - _370 |225.51Mb
  - disney_ES |31.40Mb
  - _376 |153.71Mb
  - _369 |31.08Mb
  - _372 |31.90Mb
  - _390 |43.01Mb
  - _377 |682.99Mb
  - _367 |33.41Mb
  - _378 |14.22Mb
  - _380 |932.93Mb
  - _384 |222.12Mb
  - _388 |170.17Mb
  - _389 |167.54Mb
  - _385 |19.75Mb
  - _391 |129.63Mb
  - _404 |50.53Mb
  - _402 |19.87Mb
  - _401 |13.92Mb
  - _397 |219.07Mb
  - _406 |49.84Mb
  - _411 |50.83Mb
  - _398 |10.03Mb
  - _409 |73.12Mb
  - _393 |40.53Mb
  - _395 |41.72Mb
  - _413 |13.04Mb
  - Relay_-ğŸ‡«ğŸ‡·FR_403 |20.69Mb
  - _412 |226.14Mb
  - _414 |136.13Mb
  - _405 |109.87Mb
  - disney_MX |29.28Mb
  - _415 |12.35Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_396 |144.05Mb
  - _432 |55.18Mb
  - disney_US |33.72Mb
  - disney_US |10.98Mb
  - disney_US |17.59Mb
  - disney_US |24.52Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_435 |13.84Mb
  - _436 |16.06Mb
  - _439 |10.49Mb
  - _441 |10.85Mb
  - _443 |10.46Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_444 |41.91Mb
  - _446 |16.24Mb
  - _437 |12.38Mb
  - ğŸ‡¨ğŸ‡¦CA_452 |30.63Mb
  - _448 |38.73Mb
  - disney_AE |17.95Mb
  - _449 |10.38Mb
  - ğŸ‡¨ğŸ‡¦CA_451 |23.64Mb
  - ğŸ‡§ğŸ‡·BR_450 |15.67Mb
  - disney_CH |181.69Mb
  - ğŸ‡¬ğŸ‡§GB_458 |192.81Mb
  - ğŸ‡±ğŸ‡¹LT_468 |924.67Mb
  - ğŸ‡±ğŸ‡¹LT_470 |942.36Mb
  - ğŸ‡±ğŸ‡¹LT_471 |866.61Mb
  - ğŸ‡±ğŸ‡¹LT_472 |218.60Mb
  - ğŸ‡±ğŸ‡¹LT_475 |223.32Mb
  - ğŸ‡²ğŸ‡½MX_478 |133.07Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_491 |40.66Mb
  - ğŸ‡±ğŸ‡¹LT_474 |173.90Mb
  - Relay_ğŸZZ-ğŸ‡®ğŸ‡³IN_494 |109.11Mb
  - ğŸZZ_495 |76.05Mb
  - disney_DO |59.09Mb
  - ğŸ‡³ğŸ‡±NL_480 |60.17Mb
  - ğŸ‡±ğŸ‡» LV_476 |100.87Mb
  - ğŸ‡³ğŸ‡±NL_481 |223.82Mb
  - ğŸ‡²ğŸ‡©MD_477 |33.88Mb
  - ğŸ‡µğŸ‡¹PT_487 |52.27Mb
  - ğŸ‡¸ğŸ‡¬SG_488 |16.38Mb
  - ğŸ‡¹ğŸ‡¼TW_489 |19.71Mb
  - ğŸ ZZ_492 |191.59Mb
  - Relay_ğŸZZ-ğŸ‡®ğŸ‡·IR_496 |16.79Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
