port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: _605 |11.03Mb
  server: 54.252.240.128
  type: vmess
  port: 1000
  uuid: ca26a9fd-fef8-4ea7-d194-450ce4e0c67a
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
- name: _591 |63.95Mb
  server: 82.38.31.176
  type: ss
  port: 8080
  udp: true
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: netflix_NL |239.19Mb
  server: 151.242.251.137
  type: ss
  port: 8080
  password: o5osZg269v5zHpYjr1xY9s
  cipher: chacha20-ietf-poly1305
- name: _600 |236.34Mb
  server: 45.87.175.181
  type: ss
  port: 8080
  udp: true
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: disney_PT |21.86Mb
  server: 185.231.233.112
  type: ss
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: _595 |200.50Mb
  server: 213.159.67.124
  type: ss
  port: 443
  password: mbhqsStnFQT1cTZYCdsmkugGUC6GT6rp
  cipher: chacha20-ietf-poly1305
- name: _616 |25.05Mb
  server: 47.243.51.237
  type: vmess
  port: 52801
  uuid: ef93f413-9039-4ddb-aefb-2490287df55a
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /arki?ed=2048
- name: _642 |14.32Mb
  server: 47.243.51.237
  type: vmess
  port: 23559
  uuid: e3f4cb0e-3b3d-41ad-b24a-9cbc2927b451
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /arki?ed=2048
- name: _648 |11.15Mb
  server: 47.242.238.231
  type: vmess
  port: 47843
  uuid: c12ab974-7b02-42fd-a99b-576a03b0c433
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /arki?ed=2048
- name: Relay_-ğŸ‡²ğŸ‡¾MY_653 |30.86Mb
  server: ml0724.ysds168.shop
  type: vmess
  port: 2052
  udp: true
  uuid: 665d9b8f-153d-4907-adac-de12afd9c851
  alterId: 0
  cipher: auto
  servername: ml0724.ysds168.shop
  http-opts: {}
  h2-opts: {}
  tls: true
- name: Relay_-ğŸ‡¹ğŸ‡¼TW_637 |28.25Mb
  server: planb.mojcn.com
  type: vmess
  port: 16616
  udp: true
  uuid: 77439561-dcef-4e45-803a-743cfa7d20c2
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /
    headers:
      Host: 9e97d6c9e2e0ad3444cbf96d3709366d.mobgslb.tbcache.com
- name: Relay_-ğŸ‡®ğŸ‡³IN_633 |27.61Mb
  server: planb.mojcn.com
  type: vmess
  port: 16626
  udp: true
  uuid: 77439561-dcef-4e45-803a-743cfa7d20c2
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /
    headers:
      Host: 9e97d6c9e2e0ad3444cbf96d3709366d.mobgslb.tbcache.com
- name: Relay_-ğŸ‡¯ğŸ‡µJP_611 |11.79Mb
  server: planb.mojcn.com
  type: vmess
  port: 16617
  udp: true
  uuid: 77439561-dcef-4e45-803a-743cfa7d20c2
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /
    headers:
      Host: 9e97d6c9e2e0ad3444cbf96d3709366d.mobgslb.tbcache.com
- name: Relay_-ğŸ‡³ğŸ‡±NL_658 |25.14Mb
  server: 160.16.236.32
  type: trojan
  port: 4054
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡³ğŸ‡±NL_659 |62.45Mb
  server: 160.16.81.84
  type: trojan
  port: 4054
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡³ğŸ‡±NL_660 |10.56Mb
  server: 160.16.81.84
  type: trojan
  port: 2760
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: disney_US |109.58Mb
  server: 23.247.137.64
  type: trojan
  port: 443
  udp: true
  password: 3c4e10af98c30972
  alpn:
  - h2
  sni: n2.gladns.com
  network: grpc
  grpc-opts:
    grpc-service-name: db
- name: Relay_-ğŸ‡¹ğŸ‡¼TW_625 |18.19Mb
  server: m.cnmjin.net
  type: vmess
  port: 16616
  udp: true
  uuid: 77439561-dcef-4e45-803a-743cfa7d20c2
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /
    headers:
      Host: 9e97d6c9e2e0ad3444cbf96d3709366d.mobgslb.tbcache.com
- name: Relay_-ğŸ‡¯ğŸ‡µJP_615 |11.05Mb
  server: m.cnmjin.net
  type: vmess
  port: 16617
  udp: true
  uuid: 77439561-dcef-4e45-803a-743cfa7d20c2
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /
    headers:
      Host: 9e97d6c9e2e0ad3444cbf96d3709366d.mobgslb.tbcache.com
- name: Relay_-ğŸ‡³ğŸ‡±NL_661 |13.41Mb
  server: 160.16.124.55
  type: trojan
  port: 2760
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¯ğŸ‡µJP_666 |21.97Mb
  server: 52.195.176.26
  type: trojan
  port: 2145
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: Relay_-ğŸ‡¯ğŸ‡µJP_667 |22.70Mb
  server: 160.16.138.24
  type: trojan
  port: 1331
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¯ğŸ‡µJP_670 |17.92Mb
  server: 160.16.138.24
  type: trojan
  port: 3169
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_ğŸ‡¬ğŸ‡§GB-ğŸ‡ºğŸ‡¸US_698 |198.43Mb
  server: 82.198.246.97
  type: vmess
  country: ğŸ‡¬ğŸ‡§GB
  port: 180
  uuid: d13fc2f5-3e05-4795-81eb-44143a09e552
  alterId: 0
  cipher: auto
  network: tcp
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: _673 |18.67Mb
  server: 58.152.18.95
  type: trojan
  port: 443
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: ğŸ‡¦ğŸ‡ºAU_686 |10.36Mb
  server: 95.111.222.113
  type: ss
  country: ğŸ‡¦ğŸ‡ºAU
  port: 443
  password: SVt6ZiWzRI1Yxeig4xBZwiJOt6ceXwGa
  cipher: chacha20-ietf-poly1305
- name: Relay_-ğŸ‡³ğŸ‡±NL_677 |22.37Mb
  server: 18.162.142.242
  type: trojan
  port: 4054
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: disney_FR |51.48Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 27092
  uuid: a0596ba6-72a3-4366-8992-77088da65bd8
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡§ğŸ‡·BR_688 |19.99Mb
  server: 38.180.16.86
  type: vmess
  country: ğŸ‡§ğŸ‡·BR
  port: 36104
  uuid: E146A8CB-9D2F-449C-ADCA-8736FB
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡§ğŸ‡·BR_689 |19.45Mb
  server: 38.180.16.86
  type: vmess
  country: ğŸ‡§ğŸ‡·BR
  port: 36236
  uuid: a58bc1a5-8c18-49ff-9453-c331b52f45dc
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡¬ğŸ‡§GB_697 |216.26Mb
  server: 82.38.31.184
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡²ğŸ‡½MX_740 |130.60Mb
  server: 216.238.89.53
  type: vmess
  country: ğŸ‡²ğŸ‡½MX
  port: 57283
  uuid: 1a5aafc0-6482-451d-fe76-6875b7818579
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_ğŸ‡­ğŸ‡°HK-ğŸ‡­ğŸ‡°HK_704 |12.54Mb
  server: cgroup.node4.s2.nodelist-airport.com
  type: ss
  country: ğŸ‡­ğŸ‡°HK
  port: 48712
  password: 8f3a835c-8a45-480d-ae35-1deb2c52dcae
  cipher: aes-256-gcm
- name: ğŸ‡°ğŸ‡·KR_738 |10.34Mb
  server: 146.56.112.110
  type: vmess
  country: ğŸ‡°ğŸ‡·KR
  port: 8888
  uuid: e7c302f3-90d6-42dd-9d7d-94a3683a3707
  alterId: 0
  cipher: auto
  network: tcp
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡­ğŸ‡°HK_735 |10.58Mb
  server: 112.118.116.66
  type: trojan
  country: ğŸ‡­ğŸ‡°HK
  port: 443
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: ğŸ‡±ğŸ‡¹LT_739 |14.68Mb
  server: 45.87.175.166
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 443
  password: 1RWwXhwfAB5gAEozU4G2Pg
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_748 |54.79Mb
  server: 100.25.219.192
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: disney_US |17.59Mb
  server: 38.84.201.21
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 53487
  uuid: c3c1ec05-df2c-4975-9b42-e9b007564eb1
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡·ğŸ‡ºRU_742 |53.95Mb
  server: 109.71.246.210
  type: ss
  country: ğŸ‡·ğŸ‡ºRU
  port: 56689
  password: YQCSKoCF3QazW8YlvDBWA4
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_749 |37.67Mb
  server: 23.95.75.146
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: NDRySIABARbErNIVsCNVkyYAHiBzhveT
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡²ğŸ‡¾MY_741 |31.15Mb
  server: 38.54.98.110
  type: vmess
  country: ğŸ‡²ğŸ‡¾MY
  port: 2052
  uuid: 665d9b8f-153d-4907-adac-de12afd9c851
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡¦ğŸ‡ºAU_762 |15.04Mb
  server: sy4.620720.xyz
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  uuid: 516d8a7a-3f0b-41d3-bad0-246116381516
  alterId: 0
  cipher: auto
  network: ws
  servername: sy4.620720.xyz
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /
    headers:
      HOST: sy4.620720.xyz
- name: ğŸ‡¸ğŸ‡¬SG_743 |10.47Mb
  server: 68.183.178.131
  type: vmess
  country: ğŸ‡¸ğŸ‡¬SG
  port: 58607
  uuid: c11c32cb-27b3-4afa-c0f3-fb250aa4959e
  alterId: 0
  cipher: auto
  network: ws
  servername: www.12333.monster
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /
    headers:
      HOST: www.12333.monster
- name: ğŸ‡ºğŸ‡¸ US_745 |17.22Mb
  server: 38.165.233.93
  type: ss
  country: ğŸ‡ºğŸ‡¸ US
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_760 |37.28Mb
  server: sw19.sesamebuta.top
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  uuid: 805ba514-bf2f-4d5d-df49-8417804e8de3
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /abcd
- name: ğŸ‡¬ğŸ‡§GB_696 |35.55Mb
  server: 185.193.48.157
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: zwBLM6bBE5YxvwvnKgxAq3ErXpqMYv20
  cipher: chacha20-ietf-poly1305
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - _605 |11.03Mb
  - _591 |63.95Mb
  - netflix_NL |239.19Mb
  - _600 |236.34Mb
  - disney_PT |21.86Mb
  - _595 |200.50Mb
  - _616 |25.05Mb
  - _642 |14.32Mb
  - _648 |11.15Mb
  - Relay_-ğŸ‡²ğŸ‡¾MY_653 |30.86Mb
  - Relay_-ğŸ‡¹ğŸ‡¼TW_637 |28.25Mb
  - Relay_-ğŸ‡®ğŸ‡³IN_633 |27.61Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_611 |11.79Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_658 |25.14Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_659 |62.45Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_660 |10.56Mb
  - disney_US |109.58Mb
  - Relay_-ğŸ‡¹ğŸ‡¼TW_625 |18.19Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_615 |11.05Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_661 |13.41Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_666 |21.97Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_667 |22.70Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_670 |17.92Mb
  - Relay_ğŸ‡¬ğŸ‡§GB-ğŸ‡ºğŸ‡¸US_698 |198.43Mb
  - _673 |18.67Mb
  - ğŸ‡¦ğŸ‡ºAU_686 |10.36Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_677 |22.37Mb
  - disney_FR |51.48Mb
  - ğŸ‡§ğŸ‡·BR_688 |19.99Mb
  - ğŸ‡§ğŸ‡·BR_689 |19.45Mb
  - ğŸ‡¬ğŸ‡§GB_697 |216.26Mb
  - ğŸ‡²ğŸ‡½MX_740 |130.60Mb
  - Relay_ğŸ‡­ğŸ‡°HK-ğŸ‡­ğŸ‡°HK_704 |12.54Mb
  - ğŸ‡°ğŸ‡·KR_738 |10.34Mb
  - ğŸ‡­ğŸ‡°HK_735 |10.58Mb
  - ğŸ‡±ğŸ‡¹LT_739 |14.68Mb
  - ğŸ‡ºğŸ‡¸US_748 |54.79Mb
  - disney_US |17.59Mb
  - ğŸ‡·ğŸ‡ºRU_742 |53.95Mb
  - ğŸ‡ºğŸ‡¸US_749 |37.67Mb
  - ğŸ‡²ğŸ‡¾MY_741 |31.15Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡¦ğŸ‡ºAU_762 |15.04Mb
  - ğŸ‡¸ğŸ‡¬SG_743 |10.47Mb
  - ğŸ‡ºğŸ‡¸ US_745 |17.22Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_760 |37.28Mb
  - ğŸ‡¬ğŸ‡§GB_696 |35.55Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - _605 |11.03Mb
  - _591 |63.95Mb
  - netflix_NL |239.19Mb
  - _600 |236.34Mb
  - disney_PT |21.86Mb
  - _595 |200.50Mb
  - _616 |25.05Mb
  - _642 |14.32Mb
  - _648 |11.15Mb
  - Relay_-ğŸ‡²ğŸ‡¾MY_653 |30.86Mb
  - Relay_-ğŸ‡¹ğŸ‡¼TW_637 |28.25Mb
  - Relay_-ğŸ‡®ğŸ‡³IN_633 |27.61Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_611 |11.79Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_658 |25.14Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_659 |62.45Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_660 |10.56Mb
  - disney_US |109.58Mb
  - Relay_-ğŸ‡¹ğŸ‡¼TW_625 |18.19Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_615 |11.05Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_661 |13.41Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_666 |21.97Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_667 |22.70Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_670 |17.92Mb
  - Relay_ğŸ‡¬ğŸ‡§GB-ğŸ‡ºğŸ‡¸US_698 |198.43Mb
  - _673 |18.67Mb
  - ğŸ‡¦ğŸ‡ºAU_686 |10.36Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_677 |22.37Mb
  - disney_FR |51.48Mb
  - ğŸ‡§ğŸ‡·BR_688 |19.99Mb
  - ğŸ‡§ğŸ‡·BR_689 |19.45Mb
  - ğŸ‡¬ğŸ‡§GB_697 |216.26Mb
  - ğŸ‡²ğŸ‡½MX_740 |130.60Mb
  - Relay_ğŸ‡­ğŸ‡°HK-ğŸ‡­ğŸ‡°HK_704 |12.54Mb
  - ğŸ‡°ğŸ‡·KR_738 |10.34Mb
  - ğŸ‡­ğŸ‡°HK_735 |10.58Mb
  - ğŸ‡±ğŸ‡¹LT_739 |14.68Mb
  - ğŸ‡ºğŸ‡¸US_748 |54.79Mb
  - disney_US |17.59Mb
  - ğŸ‡·ğŸ‡ºRU_742 |53.95Mb
  - ğŸ‡ºğŸ‡¸US_749 |37.67Mb
  - ğŸ‡²ğŸ‡¾MY_741 |31.15Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡¦ğŸ‡ºAU_762 |15.04Mb
  - ğŸ‡¸ğŸ‡¬SG_743 |10.47Mb
  - ğŸ‡ºğŸ‡¸ US_745 |17.22Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_760 |37.28Mb
  - ğŸ‡¬ğŸ‡§GB_696 |35.55Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
