port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: _228 |42.87Mb
  server: 104.192.226.106
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: _231 |24.67Mb
  server: 23.95.72.81
  type: ss
  port: 443
  udp: true
  password: UAMVtHm54uahd6SiN5WcD16rsPSdabPG
  cipher: chacha20-ietf-poly1305
- name: netflix_CA |23.35Mb
  server: 137.184.174.93
  type: ss
  port: 8080
  udp: true
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: _218 |263.99Mb
  server: 45.87.175.155
  type: ss
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: _224 |221.61Mb
  server: 82.38.31.176
  type: ss
  port: 8080
  udp: true
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: _233 |102.35Mb
  server: 18.203.224.78
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: Relay_-ğŸ‡ºğŸ‡¸US_243 |17.40Mb
  server: 104.18.13.167
  type: vmess
  port: 443
  udp: true
  uuid: 24254866-770c-41b4-9404-3f50524f425b
  alterId: 0
  cipher: auto
  network: ws
  servername: 24254866-770c-41b4-9404-3f50524f425b.mihomo.baby
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /saoihgreg9384gh8934
    headers:
      Host: 24254866-770c-41b4-9404-3f50524f425b.mihomo.baby
- name: _222 |40.81Mb
  server: 45.15.126.19
  type: ss
  port: 443
  udp: true
  password: 6Ts2ZDTQAf3hkFoB8AFufDwsGrlF4e2t
  cipher: chacha20-ietf-poly1305
- name: disney_TW |39.78Mb
  server: 141.193.213.199
  type: trojan
  port: 443
  udp: true
  password: a8a5b34d-fe46-487d-bd6a-d9f3101525fd
  sni: 26z68w0ecxbuyf89.ukgogo202511.top
  skip-cert-verify: true
  ws-opts:
    path: /images
    headers:
      Host: 26z68w0ecxbuyf89.ukgogo202511.top
  network: ws
- name: Relay_-ğŸ‡³ğŸ‡±NL_255 |19.13Mb
  server: 160.16.70.180
  type: trojan
  port: 4054
  password: 2cf6d686799e6fa95316394064f26c0a
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡³ğŸ‡±NL_262 |39.89Mb
  server: 160.16.116.227
  type: trojan
  port: 4054
  password: 2cf6d686799e6fa95316394064f26c0a
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¯ğŸ‡µJP_267 |20.59Mb
  server: 141.193.213.60
  type: trojan
  port: 443
  udp: true
  password: 8b45d379-702f-41b3-a6b2-9c87a01dcd5c
  sni: a3t5vfl95f4d5d9y.catimecsgo.xyz
  skip-cert-verify: true
  ws-opts:
    path: /images
    headers:
      Host: a3t5vfl95f4d5d9y.catimecsgo.xyz
  network: ws
- name: Relay_-ğŸ‡ºğŸ‡¸US_278 |30.44Mb
  server: usiys.southbyte.xyz
  type: trojan
  port: 5897
  udp: true
  password: fg20mtCFHy
  sni: usiys.southbyte.xyz
  skip-cert-verify: true
- name: disney_netflix_DE |74.03Mb
  server: uk2-2.998998.best
  type: vmess
  port: 443
  udp: true
  uuid: 24254866-770c-41b4-9404-3f50524f425b
  alterId: 0
  cipher: auto
  network: ws
  servername: 24254866-770c-41b4-9404-3f50524f425b.placeunaorder.fun
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /logcatxiouerd34try9
    headers:
      Host: 24254866-770c-41b4-9404-3f50524f425b.placeunaorder.fun
- name: disney_US |36.62Mb
  server: fondly.appagent.net
  type: trojan
  port: 28331
  password: RFxCa3A4zwRXcICDlYxpZR8qSS3lEN93CSYFyA3TaDIyS2aXD2leS6we5yZEOn03qcNYD
  sni: fondly.appagent.net
- name: Relay_-ğŸ‡ºğŸ‡¸US_286 |41.92Mb
  server: 141.193.213.199
  type: trojan
  port: 443
  udp: true
  password: a544940a-2c1c-4723-96cc-d03053a95530
  sni: 26z68w0ecxbuyf89.ukgogo202511.top
  skip-cert-verify: true
  ws-opts:
    path: /images
    headers:
      Host: 26z68w0ecxbuyf89.ukgogo202511.top
  network: ws
- name: Relay_-ğŸ‡¯ğŸ‡µJP_280 |10.04Mb
  server: 160.16.106.144
  type: trojan
  port: 3169
  password: 2cf6d686799e6fa95316394064f26c0a
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡ºğŸ‡¸US_244 |34.32Mb
  server: us19-25.998998.best
  type: vmess
  port: 443
  udp: true
  uuid: 24254866-770c-41b4-9404-3f50524f425b
  alterId: 0
  cipher: auto
  network: ws
  servername: 24254866-770c-41b4-9404-3f50524f425b.mihomo.baby
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /saoihgreg9384gh8934
    headers:
      Host: 24254866-770c-41b4-9404-3f50524f425b.mihomo.baby
- name: disney_RU |53.72Mb
  server: 37.18.14.33
  type: trojan
  port: 443
  udp: true
  password: Qzy7tgpRhu
  sni: m.vk.com
  skip-cert-verify: true
- name: disney_FR |116.44Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 27092
  uuid: a0596ba6-72a3-4366-8992-77088da65bd8
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡¬ğŸ‡§GB_294 |276.50Mb
  server: 82.38.31.191
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_295 |202.80Mb
  server: 82.38.31.194
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸ‡¬ğŸ‡§GB-ğŸ‡³ğŸ‡±NL_296 |256.51Mb
  server: 82.38.31.210
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: netflix_US |51.50Mb
  server: 107.23.148.46
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: disney_netflix_NL |231.31Mb
  server: 82.38.31.217
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: disney_TW |28.78Mb
  server: gd.bjnet2.com
  type: ss
  port: 36603
  udp: true
  password: 84d85af8-2807-4306-a701-f784676b77c3
  cipher: aes-128-gcm
  plugin: obfs
  plugin-opts:
    host: de5bdbffa87896a4b126f8b62150bb4e.baidu.com
    mode: http
- name: disney_JP |17.33Mb
  server: gd.bjnet2.com
  type: ss
  port: 36609
  udp: true
  password: 84d85af8-2807-4306-a701-f784676b77c3
  cipher: aes-128-gcm
  plugin: obfs
  plugin-opts:
    host: de5bdbffa87896a4b126f8b62150bb4e.baidu.com
    mode: http
- name: disney_HK |28.38Mb
  server: gd.bjnet2.com
  type: ss
  port: 36602
  udp: true
  password: 84d85af8-2807-4306-a701-f784676b77c3
  cipher: aes-128-gcm
  plugin: obfs
  plugin-opts:
    host: de5bdbffa87896a4b126f8b62150bb4e.baidu.com
    mode: http
- name: disney_US |26.24Mb
  server: gd.bjnet2.com
  type: ss
  port: 36608
  udp: true
  password: 84d85af8-2807-4306-a701-f784676b77c3
  cipher: aes-128-gcm
  plugin: obfs
  plugin-opts:
    host: de5bdbffa87896a4b126f8b62150bb4e.baidu.com
    mode: http
- name: disney_netflix_NL |129.90Mb
  server: 45.87.175.174
  type: ss
  country: ğŸ‡±ğŸ‡¹ LT
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡®ğŸ‡·IR_302 |13.77Mb
  server: cf.fovi.tk
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  uuid: bf67437e-6c90-45ca-abc2-c7240a5ce2aa
  alterId: 0
  cipher: auto
  network: ws
  servername: foxlux.fovi.tk
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /eisasqa
    headers:
      HOST: foxlux.fovi.tk
- name: Relay_-ğŸ‡°ğŸ‡·KR_216 |14.69Mb
  server: p141.panda001.net
  type: ss
  port: 4652
  udp: true
  password: qwerREWQ@@
  cipher: aes-256-cfb
- name: _215 |10.45Mb
  server: 95.111.222.113
  type: ss
  port: 443
  udp: true
  password: SVt6ZiWzRI1Yxeig4xBZwiJOt6ceXwGa
  cipher: chacha20-ietf-poly1305
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - _228 |42.87Mb
  - _231 |24.67Mb
  - netflix_CA |23.35Mb
  - _218 |263.99Mb
  - _224 |221.61Mb
  - _233 |102.35Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_243 |17.40Mb
  - _222 |40.81Mb
  - disney_TW |39.78Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_255 |19.13Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_262 |39.89Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_267 |20.59Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_278 |30.44Mb
  - disney_netflix_DE |74.03Mb
  - disney_US |36.62Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_286 |41.92Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_280 |10.04Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_244 |34.32Mb
  - disney_RU |53.72Mb
  - disney_FR |116.44Mb
  - ğŸ‡¬ğŸ‡§GB_294 |276.50Mb
  - ğŸ‡¬ğŸ‡§GB_295 |202.80Mb
  - Relay_ğŸ‡¬ğŸ‡§GB-ğŸ‡³ğŸ‡±NL_296 |256.51Mb
  - netflix_US |51.50Mb
  - disney_netflix_NL |231.31Mb
  - disney_TW |28.78Mb
  - disney_JP |17.33Mb
  - disney_HK |28.38Mb
  - disney_US |26.24Mb
  - disney_netflix_NL |129.90Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡®ğŸ‡·IR_302 |13.77Mb
  - Relay_-ğŸ‡°ğŸ‡·KR_216 |14.69Mb
  - _215 |10.45Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - _228 |42.87Mb
  - _231 |24.67Mb
  - netflix_CA |23.35Mb
  - _218 |263.99Mb
  - _224 |221.61Mb
  - _233 |102.35Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_243 |17.40Mb
  - _222 |40.81Mb
  - disney_TW |39.78Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_255 |19.13Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_262 |39.89Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_267 |20.59Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_278 |30.44Mb
  - disney_netflix_DE |74.03Mb
  - disney_US |36.62Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_286 |41.92Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_280 |10.04Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_244 |34.32Mb
  - disney_RU |53.72Mb
  - disney_FR |116.44Mb
  - ğŸ‡¬ğŸ‡§GB_294 |276.50Mb
  - ğŸ‡¬ğŸ‡§GB_295 |202.80Mb
  - Relay_ğŸ‡¬ğŸ‡§GB-ğŸ‡³ğŸ‡±NL_296 |256.51Mb
  - netflix_US |51.50Mb
  - disney_netflix_NL |231.31Mb
  - disney_TW |28.78Mb
  - disney_JP |17.33Mb
  - disney_HK |28.38Mb
  - disney_US |26.24Mb
  - disney_netflix_NL |129.90Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡®ğŸ‡·IR_302 |13.77Mb
  - Relay_-ğŸ‡°ğŸ‡·KR_216 |14.69Mb
  - _215 |10.45Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
