port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: _298 |39.86Mb
  server: 207.90.237.163
  type: ss
  port: 808
  udp: true
  password: tvX1v#NSFP_LG_bJ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¨ğŸ‡¦CA_314 |215.61Mb
  server: 68.183.193.204
  type: ss
  country: ğŸ‡¨ğŸ‡¦CA
  port: 8080
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: Relay_ğŸ‡¨ğŸ‡¦CA-ğŸ‡¨ğŸ‡¦CA_315 |450.00Mb
  server: ssca.irundns.net
  type: ssr
  country: ğŸ‡¨ğŸ‡¦CA
  port: 443
  password: $$Turb0VPN$$
  cipher: aes-128-cfb
  protocol: auth_aes128_md5
  obfs: http_post
- name: ğŸ‡¦ğŸ‡·AR_311 | 3.52Mb
  server: 190.103.176.32
  type: ss
  country: ğŸ‡¦ğŸ‡·AR
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ğŸ‡©ğŸ‡ªDE_316 | 3.33Mb
  server: 18.199.92.80
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡©ğŸ‡°DK_317 | 2.96Mb
  server: 192.36.27.94
  type: ss
  country: ğŸ‡©ğŸ‡°DK
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ğŸ‡ªğŸ‡¸ES_318 | 0.83Mb
  server: 194.87.45.189
  type: ss
  country: ğŸ‡ªğŸ‡¸ES
  port: 443
  password: cUgm3LyixNv6AElxYBPkoP
  cipher: chacha20-ietf-poly1305
- name: Relay_-ğŸ‡ºğŸ‡¸US_299 | 5.98Mb
  server: 45.144.174.60
  type: vmess
  port: 23177
  udp: true
  uuid: 977a8544-8606-4496-a3c3-0f03e7c92ac2
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /
- name: Relay_-ğŸ‡¹ğŸ‡¼TW_309 | 8.76Mb
  server: sevuior.missionsec.us
  type: trojan
  port: 443
  udp: true
  password: SaZa3XKYya0q3SZYDuE3SAC2NpeZgA9n3CA9jRDKz48O6Cg8Dn7Fx63lRITawuDeFRpBj
- name: ğŸ‡«ğŸ‡·FR_319 |10.29Mb
  server: 83.147.216.70
  type: ss
  country: ğŸ‡«ğŸ‡·FR
  port: 64519
  password: pTUb4YuSmPoSJT4bYUYee2
  cipher: chacha20-ietf-poly1305
- name: Relay_-ğŸ‡­ğŸ‡°HK_304
  server: hk1.0a32b11d-9fd3-fa30-2f56-58a4f384fa95.6df03129.the-best-airport.com
  type: trojan
  port: 443
  udp: true
  password: ee2efc59-dd65-43a5-92e6-f440eca492b1
  sni: new.download.the-best-airport.com
  skip-cert-verify: true
- name: ğŸ‡«ğŸ‡·FR_320 |168.85Mb
  server: 83.147.216.70
  type: ss
  country: ğŸ‡«ğŸ‡·FR
  port: 64519
  password: Vq1y6zEAmcfGoBB0dRBbV7
  cipher: chacha20-ietf-poly1305
- name: Relay_-ğŸ‡¸ğŸ‡¬SG_310 |31.06Mb
  server: spevoy.missionsec.us
  type: trojan
  port: 443
  udp: true
  password: R3SuZDAZXDO3FYqxwK36l7gpSIBTFCxlzc89a7qg3S9p8BOCeACSFaA8nxeD2ZlT5Nl4O
  skip-cert-verify: true
- name: ğŸ‡¬ğŸ‡§GB_323 | 8.66Mb
  server: 212.102.53.193
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: shadowsocks
  cipher: aes-128-gcm
- name: ğŸ‡«ğŸ‡·FR_321 | 9.45Mb
  server: 83.147.216.70
  type: ss
  country: ğŸ‡«ğŸ‡·FR
  port: 64519
  password: rOQrWhz7otxOrPBC6uHd3F
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡«ğŸ‡·FR_322 | 8.15Mb
  server: 83.147.216.70
  type: ss
  country: ğŸ‡«ğŸ‡·FR
  port: 64519
  password: eBzKXxEmQlAZKIBC8PhQYZ
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸ‡®ğŸ‡·IR-ğŸ‡³ğŸ‡±NL_325 |13.70Mb
  server: 151.242.251.131
  type: ss
  country: ğŸ‡®ğŸ‡·IR
  port: 8080
  password: QCXDxuDlTTMD7jtgHUjIoj
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸ‡®ğŸ‡·IR-ğŸ‡³ğŸ‡±NL_326 | 2.90Mb
  server: 151.242.251.153
  type: ss
  country: ğŸ‡®ğŸ‡·IR
  port: 8080
  password: QCXDxuDlTTMD7jtgHUjIoj
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸ‡±ğŸ‡¹LT-ğŸ‡³ğŸ‡±NL_330 |11.20Mb
  server: 45.87.175.178
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: 4a2rfixophdjffa8KVA4Aa
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_332 |15.06Mb
  server: 45.87.175.58
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_331 |16.01Mb
  server: 45.87.175.167
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: QCXDxuDlTTMD7jtgHUjIoj
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡³ğŸ‡±NL_335 |11.73Mb
  server: 79.127.227.53
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ğŸ‡³ğŸ‡±NL_336 | 5.41Mb
  server: 193.29.139.162
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 8080
  password: 4a2rfixophdjffa8KVA4Aa
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡³ğŸ‡±NL_337 | 3.14Mb
  server: 193.29.139.164
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 8080
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡³ğŸ‡±NL_338 | 5.69Mb
  server: 193.29.139.157
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 8080
  password: 4a2rfixophdjffa8KVA4Aa
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡³ğŸ‡±NL_339 | 6.64Mb
  server: 149.34.244.80
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 443
  password: shadowsocks
  cipher: aes-128-gcm
- name: ğŸ‡³ğŸ‡´NO_341 | 6.61Mb
  server: 185.213.23.226
  type: ss
  country: ğŸ‡³ğŸ‡´NO
  port: 990
  password: f8f7aCzcPKbsF8p3
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡·ğŸ‡ºRU_347 | 8.57Mb
  server: 94.159.96.245
  type: ss
  country: ğŸ‡·ğŸ‡ºRU
  port: 11902
  password: j887M9DxWzd5Jq971e3Y1B
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡µğŸ‡±PL_343 | 3.53Mb
  server: 217.30.10.18
  type: ss
  country: ğŸ‡µğŸ‡±PL
  port: 9026
  password: QWDDvVE9npNurQfA
  cipher: aes-256-cfb
- name: ğŸ‡µğŸ‡±PL_344 |86.82Mb
  server: 217.30.10.70
  type: ss
  country: ğŸ‡µğŸ‡±PL
  port: 9025
  password: XPtzA9sCug3SPR4c
  cipher: aes-256-cfb
- name: ğŸ‡µğŸ‡±PL_345 |11.38Mb
  server: 217.30.10.70
  type: ss
  country: ğŸ‡µğŸ‡±PL
  port: 9038
  password: gYCYXfkUQEs2TaJQ
  cipher: aes-256-cfb
- name: ğŸ‡ºğŸ‡¸US_355 |13.88Mb
  server: 54.165.23.236
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡µğŸ‡­PH_342
  server: 192.142.18.127
  type: ss
  country: ğŸ‡µğŸ‡­PH
  port: 443
  password: 952e3388-1fbc-44a2-b874-cad16f7b9f16
  cipher: aes-256-gcm
- name: ğŸ‡·ğŸ‡ºRU_348 | 2.08Mb
  server: 146.70.52.150
  type: ss
  country: ğŸ‡·ğŸ‡ºRU
  port: 8080
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: ğŸ‡ºğŸ‡¸US_354 | 7.20Mb
  server: 156.146.38.170
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: shadowsocks
  cipher: aes-128-gcm
- name: ğŸ‡¸ğŸ‡ªSE_349 | 8.47Mb
  server: 121.127.46.147
  type: ss
  country: ğŸ‡¸ğŸ‡ªSE
  port: 990
  password: f8f7aCzcPKbsF8p3
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_356 | 4.78Mb
  server: 193.124.24.247
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 6511
  uuid: 5ef4e89b-262f-4c74-e793-c7332079f251
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_357 | 2.46Mb
  server: 193.124.24.230
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 6502
  uuid: 44e32afd-714e-4d60-f6bc-5d7a1d34080b
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_358 | 5.73Mb
  server: 193.124.24.230
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 6505
  uuid: f77456b5-5a82-45ba-a941-1a83c09a1f41
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_ğŸ‡³ğŸ‡±NL-ğŸ‡ºğŸ‡¸US_340
  server: 45.144.174.60
  type: vmess
  country: ğŸ‡³ğŸ‡±NL
  port: 23177
  uuid: 6cb4583a-689d-4963-87c7-efe337a645d5
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
  ws-opts:
    path: /
- name: ğŸ‡¸ğŸ‡°SK_353 |119.87Mb
  server: 156.146.40.194
  type: ss
  country: ğŸ‡¸ğŸ‡°SK
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ğŸ‡¸ğŸ‡¬SG_350 | 2.32Mb
  server: 104.248.159.99
  type: ss
  country: ğŸ‡¸ğŸ‡¬SG
  port: 8080
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: ğŸ‡¸ğŸ‡¬SG_351 | 2.23Mb
  server: 68.183.227.236
  type: ss
  country: ğŸ‡¸ğŸ‡¬SG
  port: 8080
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: ğŸ‡¸ğŸ‡¬SG_352 | 2.19Mb
  server: 175.156.111.138
  type: ss
  country: ğŸ‡¸ğŸ‡¬SG
  port: 8899
  password: '03241'
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡»ğŸ‡³VN_359
  server: 103.186.154.64
  type: ss
  country: ğŸ‡»ğŸ‡³VN
  port: 38388
  password: Xn8jKdmDM00IeO%#$#fJAMtsEAEUOpH/YWYtYqDFnT0SV
  cipher: aes-256-cfb
- name: Pool_ğŸ‡»ğŸ‡³VN_361
  server: 103.186.154.74
  type: ss
  country: ğŸ‡»ğŸ‡³VN
  port: 38388
  password: Xn8jKdmDM00IeO%#$#fJAMtsEAEUOpH/YWYtYqDFnT0SV
  cipher: aes-256-cfb
- name: ğŸ‡»ğŸ‡³VN_360
  server: 103.186.155.28
  type: ss
  country: ğŸ‡»ğŸ‡³VN
  port: 38388
  password: Xn8jKdmDM00IeO%#$#fJAMtsEAEUOpH/YWYtYqDFnT0SV
  cipher: aes-256-cfb
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - _298 |39.86Mb
  - ğŸ‡¨ğŸ‡¦CA_314 |215.61Mb
  - Relay_ğŸ‡¨ğŸ‡¦CA-ğŸ‡¨ğŸ‡¦CA_315 |450.00Mb
  - ğŸ‡¦ğŸ‡·AR_311 | 3.52Mb
  - ğŸ‡©ğŸ‡ªDE_316 | 3.33Mb
  - ğŸ‡©ğŸ‡°DK_317 | 2.96Mb
  - ğŸ‡ªğŸ‡¸ES_318 | 0.83Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_299 | 5.98Mb
  - Relay_-ğŸ‡¹ğŸ‡¼TW_309 | 8.76Mb
  - ğŸ‡«ğŸ‡·FR_319 |10.29Mb
  - Relay_-ğŸ‡­ğŸ‡°HK_304
  - ğŸ‡«ğŸ‡·FR_320 |168.85Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_310 |31.06Mb
  - ğŸ‡¬ğŸ‡§GB_323 | 8.66Mb
  - ğŸ‡«ğŸ‡·FR_321 | 9.45Mb
  - ğŸ‡«ğŸ‡·FR_322 | 8.15Mb
  - Relay_ğŸ‡®ğŸ‡·IR-ğŸ‡³ğŸ‡±NL_325 |13.70Mb
  - Relay_ğŸ‡®ğŸ‡·IR-ğŸ‡³ğŸ‡±NL_326 | 2.90Mb
  - Relay_ğŸ‡±ğŸ‡¹LT-ğŸ‡³ğŸ‡±NL_330 |11.20Mb
  - ğŸ‡±ğŸ‡¹LT_332 |15.06Mb
  - ğŸ‡±ğŸ‡¹LT_331 |16.01Mb
  - ğŸ‡³ğŸ‡±NL_335 |11.73Mb
  - ğŸ‡³ğŸ‡±NL_336 | 5.41Mb
  - ğŸ‡³ğŸ‡±NL_337 | 3.14Mb
  - ğŸ‡³ğŸ‡±NL_338 | 5.69Mb
  - ğŸ‡³ğŸ‡±NL_339 | 6.64Mb
  - ğŸ‡³ğŸ‡´NO_341 | 6.61Mb
  - ğŸ‡·ğŸ‡ºRU_347 | 8.57Mb
  - ğŸ‡µğŸ‡±PL_343 | 3.53Mb
  - ğŸ‡µğŸ‡±PL_344 |86.82Mb
  - ğŸ‡µğŸ‡±PL_345 |11.38Mb
  - ğŸ‡ºğŸ‡¸US_355 |13.88Mb
  - ğŸ‡µğŸ‡­PH_342
  - ğŸ‡·ğŸ‡ºRU_348 | 2.08Mb
  - ğŸ‡ºğŸ‡¸US_354 | 7.20Mb
  - ğŸ‡¸ğŸ‡ªSE_349 | 8.47Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_356 | 4.78Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_357 | 2.46Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_358 | 5.73Mb
  - Relay_ğŸ‡³ğŸ‡±NL-ğŸ‡ºğŸ‡¸US_340
  - ğŸ‡¸ğŸ‡°SK_353 |119.87Mb
  - ğŸ‡¸ğŸ‡¬SG_350 | 2.32Mb
  - ğŸ‡¸ğŸ‡¬SG_351 | 2.23Mb
  - ğŸ‡¸ğŸ‡¬SG_352 | 2.19Mb
  - ğŸ‡»ğŸ‡³VN_359
  - Pool_ğŸ‡»ğŸ‡³VN_361
  - ğŸ‡»ğŸ‡³VN_360
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - _298 |39.86Mb
  - ğŸ‡¨ğŸ‡¦CA_314 |215.61Mb
  - Relay_ğŸ‡¨ğŸ‡¦CA-ğŸ‡¨ğŸ‡¦CA_315 |450.00Mb
  - ğŸ‡¦ğŸ‡·AR_311 | 3.52Mb
  - ğŸ‡©ğŸ‡ªDE_316 | 3.33Mb
  - ğŸ‡©ğŸ‡°DK_317 | 2.96Mb
  - ğŸ‡ªğŸ‡¸ES_318 | 0.83Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_299 | 5.98Mb
  - Relay_-ğŸ‡¹ğŸ‡¼TW_309 | 8.76Mb
  - ğŸ‡«ğŸ‡·FR_319 |10.29Mb
  - Relay_-ğŸ‡­ğŸ‡°HK_304
  - ğŸ‡«ğŸ‡·FR_320 |168.85Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_310 |31.06Mb
  - ğŸ‡¬ğŸ‡§GB_323 | 8.66Mb
  - ğŸ‡«ğŸ‡·FR_321 | 9.45Mb
  - ğŸ‡«ğŸ‡·FR_322 | 8.15Mb
  - Relay_ğŸ‡®ğŸ‡·IR-ğŸ‡³ğŸ‡±NL_325 |13.70Mb
  - Relay_ğŸ‡®ğŸ‡·IR-ğŸ‡³ğŸ‡±NL_326 | 2.90Mb
  - Relay_ğŸ‡±ğŸ‡¹LT-ğŸ‡³ğŸ‡±NL_330 |11.20Mb
  - ğŸ‡±ğŸ‡¹LT_332 |15.06Mb
  - ğŸ‡±ğŸ‡¹LT_331 |16.01Mb
  - ğŸ‡³ğŸ‡±NL_335 |11.73Mb
  - ğŸ‡³ğŸ‡±NL_336 | 5.41Mb
  - ğŸ‡³ğŸ‡±NL_337 | 3.14Mb
  - ğŸ‡³ğŸ‡±NL_338 | 5.69Mb
  - ğŸ‡³ğŸ‡±NL_339 | 6.64Mb
  - ğŸ‡³ğŸ‡´NO_341 | 6.61Mb
  - ğŸ‡·ğŸ‡ºRU_347 | 8.57Mb
  - ğŸ‡µğŸ‡±PL_343 | 3.53Mb
  - ğŸ‡µğŸ‡±PL_344 |86.82Mb
  - ğŸ‡µğŸ‡±PL_345 |11.38Mb
  - ğŸ‡ºğŸ‡¸US_355 |13.88Mb
  - ğŸ‡µğŸ‡­PH_342
  - ğŸ‡·ğŸ‡ºRU_348 | 2.08Mb
  - ğŸ‡ºğŸ‡¸US_354 | 7.20Mb
  - ğŸ‡¸ğŸ‡ªSE_349 | 8.47Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_356 | 4.78Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_357 | 2.46Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_358 | 5.73Mb
  - Relay_ğŸ‡³ğŸ‡±NL-ğŸ‡ºğŸ‡¸US_340
  - ğŸ‡¸ğŸ‡°SK_353 |119.87Mb
  - ğŸ‡¸ğŸ‡¬SG_350 | 2.32Mb
  - ğŸ‡¸ğŸ‡¬SG_351 | 2.23Mb
  - ğŸ‡¸ğŸ‡¬SG_352 | 2.19Mb
  - ğŸ‡»ğŸ‡³VN_359
  - Pool_ğŸ‡»ğŸ‡³VN_361
  - ğŸ‡»ğŸ‡³VN_360
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
