port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: _191 |173.86Mb
  server: 47.253.185.243
  type: vmess
  port: 23755
  uuid: b6d7a60b-b1e9-4513-8aec-d0b886ae4c37
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
- name: _201 |272.06Mb
  server: 47.253.185.243
  type: vmess
  port: 37267
  uuid: 4948cb85-668a-420e-d109-5d4b3aabe54c
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
- name: ğŸ‡¨ğŸ‡¦CA_213 |31.09Mb
  server: 35.183.43.124
  type: ss
  country: ğŸ‡¨ğŸ‡¦CA
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: _155 |13.38Mb
  server: 147.78.1.27
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _143 |49.26Mb
  server: 167.160.90.178
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¨ğŸ‡¦CA_217 |10.36Mb
  server: 79.127.200.162
  type: ss
  country: ğŸ‡¨ğŸ‡¦CA
  port: 990
  password: f8f7aCzcPKbsF8p3
  cipher: chacha20-ietf-poly1305
- name: _195 |906.33Mb
  server: 38.34.24.196
  type: vmess
  port: 20522
  uuid: f65ae5d8-f779-4ab2-8ba3-e4d46d34ef9d
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /telegram_@sswia
- name: _160 |44.16Mb
  server: 138.186.142.80
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _181 |43.94Mb
  server: 138.186.142.81
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _166 |47.96Mb
  server: 212.102.54.45
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _156 |13.57Mb
  server: 185.237.185.89
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _146 |43.75Mb
  server: 38.54.59.180
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¨ğŸ‡·CR_236 |48.16Mb
  server: 145.14.131.37
  type: ss
  country: ğŸ‡¨ğŸ‡·CR
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡©ğŸ‡°DK_260 |49.23Mb
  server: 121.127.45.165
  type: ss
  country: ğŸ‡©ğŸ‡°DK
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _167 |31.21Mb
  server: 154.205.153.107
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ªğŸ‡¸ES_266 |13.23Mb
  server: 194.87.45.189
  type: ss
  country: ğŸ‡ªğŸ‡¸ES
  port: 443
  password: 0Hj92ZrXT1gItrpMWLHb3u
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_296 |10.06Mb
  server: 89.185.84.185
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: QHJQzz2ZCOBXnwrcvj8uFX
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_300 |15.86Mb
  server: 89.185.84.185
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: bmoj6orLj0ipdovNVUJzVL
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_302 |79.80Mb
  server: 89.185.84.185
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: k1su9PMjKy4KQCPAkkBq0K
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡«ğŸ‡·FR_274 |13.14Mb
  server: 83.147.216.70
  type: ss
  country: ğŸ‡«ğŸ‡·FR
  port: 64519
  password: PSmqa9uK9Oo1eivPyXiAH8
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡«ğŸ‡·FR_281 |14.45Mb
  server: 83.147.216.70
  type: ss
  country: ğŸ‡«ğŸ‡·FR
  port: 64519
  password: WmDhVSiDij7R2XROr3Cm55
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡³ğŸ‡±NL_388 |10.12Mb
  server: 193.29.139.164
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 8080
  password: 1RWwXhwfAB5gAEozU4G2Pg
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡³ğŸ‡±NL_390 |14.74Mb
  server: 193.29.139.157
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 8080
  password: QCXDxuDlTTMD7jtgHUjIoj
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡³ğŸ‡±NL_389 |12.45Mb
  server: 193.29.139.202
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 8080
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡³ğŸ‡±NL_391 |10.09Mb
  server: 193.29.139.235
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 8080
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¯ğŸ‡µJP_332 |10.37Mb
  server: 140.83.80.36
  type: vmess
  country: ğŸ‡¯ğŸ‡µJP
  port: 22545
  uuid: 5b907403-239e-4660-8ab6-b6f3d811d1da
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
  ws-opts:
    path: /
- name: ğŸ‡µğŸ‡±PL_399 |13.37Mb
  server: 217.30.10.70
  type: ss
  country: ğŸ‡µğŸ‡±PL
  port: 9011
  password: M3t2ZEQcMGRWBjRa
  cipher: aes-256-cfb
- name: ğŸ‡ºğŸ‡¸US_479 |55.45Mb
  server: 18.190.219.74
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡ºğŸ‡¸US_482 |34.11Mb
  server: 3.147.66.58
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡ºğŸ‡¸US_488 |55.45Mb
  server: 18.188.226.48
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡µğŸ‡±PL_414 |11.70Mb
  server: 217.30.10.70
  type: ss
  country: ğŸ‡µğŸ‡±PL
  port: 9015
  password: ZpNDDKRu9MagNvaf
  cipher: aes-256-cfb
- name: ğŸ‡·ğŸ‡ºRU_438 |179.54Mb
  server: 95.163.176.37
  type: ss
  country: ğŸ‡·ğŸ‡ºRU
  port: 8506
  password: eUh4lSpi7nOYj0vSrqLUh0
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_476 |18.74Mb
  server: 173.244.56.6
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: shadowsocks
  cipher: aes-128-gcm
- name: ğŸ‡²ğŸ‡¹MT_369 |22.96Mb
  server: 171.22.254.129
  type: ss
  country: ğŸ‡²ğŸ‡¹MT
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_516 |34.55Mb
  server: 18.116.40.29
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡²ğŸ‡©MD_513 |10.27Mb
  server: 23.95.76.147
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡·ğŸ‡ºRU_439 |66.40Mb
  server: 95.163.176.37
  type: ss
  country: ğŸ‡·ğŸ‡ºRU
  port: 8506
  password: VdswxetVc6AhIps18rtYbm
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_499 |10.53Mb
  server: 156.146.38.167
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: shadowsocks
  cipher: aes-128-gcm
- name: disney_US |895.03Mb
  server: 193.124.24.247
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 6508
  uuid: b68fead5-5b0b-43a1-c34a-804467f0f368
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡ºğŸ‡¸US_518 |14.86Mb
  server: 173.244.56.9
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: shadowsocks
  cipher: aes-128-gcm
- name: disney_US |344.35Mb
  server: 193.124.24.247
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 6507
  uuid: 3003e094-707c-4dbb-faca-4b8d579bc604
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡ºğŸ‡¸US_496 |192.21Mb
  server: 71.19.148.143
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: p78naCf2EfOlRSLTX0wFVx
  cipher: chacha20-ietf-poly1305
- name: disney_US |308.65Mb
  server: 154.29.158.139
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 12299
  uuid: cccfe679-fbd0-4402-caf2-67e919db436f
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡ºğŸ‡¸US_478 |123.39Mb
  server: 94.131.22.134
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 40565
  password: n7nqKk8Dr1ycsZKd5q5huWdCsbxVQEa4McgLmohr5oeTARXjx49jLFG4Efq4FGN7MdAbVaQUZfp1Y4nCUCMzuqTxqdwBQ19T
  cipher: chacha20-ietf-poly1305
- name: disney_US |578.82Mb
  server: 154.64.243.19
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 38533
  uuid: 9bc23ccf-4769-4e9a-b278-2dfa8d9ef425
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
  ws-opts:
    path: /
- name: ğŸ‡ºğŸ‡¸US_498 |39.97Mb
  server: imap.roomyinmita.name
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 40565
  password: HoLrWgDZRsGAFfyScdAZucVSE3S8gn9K966G9ggvmFwHL937vbCHjSCb81cbbf1ubdvk1d8HabZLFK1b8yM7QtPhmmA67YbV
  cipher: chacha20-ietf-poly1305
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - _191 |173.86Mb
  - _201 |272.06Mb
  - ğŸ‡¨ğŸ‡¦CA_213 |31.09Mb
  - _155 |13.38Mb
  - _143 |49.26Mb
  - ğŸ‡¨ğŸ‡¦CA_217 |10.36Mb
  - _195 |906.33Mb
  - _160 |44.16Mb
  - _181 |43.94Mb
  - _166 |47.96Mb
  - _156 |13.57Mb
  - _146 |43.75Mb
  - ğŸ‡¨ğŸ‡·CR_236 |48.16Mb
  - ğŸ‡©ğŸ‡°DK_260 |49.23Mb
  - _167 |31.21Mb
  - ğŸ‡ªğŸ‡¸ES_266 |13.23Mb
  - ğŸ‡¬ğŸ‡§GB_296 |10.06Mb
  - ğŸ‡¬ğŸ‡§GB_300 |15.86Mb
  - ğŸ‡¬ğŸ‡§GB_302 |79.80Mb
  - ğŸ‡«ğŸ‡·FR_274 |13.14Mb
  - ğŸ‡«ğŸ‡·FR_281 |14.45Mb
  - ğŸ‡³ğŸ‡±NL_388 |10.12Mb
  - ğŸ‡³ğŸ‡±NL_390 |14.74Mb
  - ğŸ‡³ğŸ‡±NL_389 |12.45Mb
  - ğŸ‡³ğŸ‡±NL_391 |10.09Mb
  - ğŸ‡¯ğŸ‡µJP_332 |10.37Mb
  - ğŸ‡µğŸ‡±PL_399 |13.37Mb
  - ğŸ‡ºğŸ‡¸US_479 |55.45Mb
  - ğŸ‡ºğŸ‡¸US_482 |34.11Mb
  - ğŸ‡ºğŸ‡¸US_488 |55.45Mb
  - ğŸ‡µğŸ‡±PL_414 |11.70Mb
  - ğŸ‡·ğŸ‡ºRU_438 |179.54Mb
  - ğŸ‡ºğŸ‡¸US_476 |18.74Mb
  - ğŸ‡²ğŸ‡¹MT_369 |22.96Mb
  - ğŸ‡ºğŸ‡¸US_516 |34.55Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡²ğŸ‡©MD_513 |10.27Mb
  - ğŸ‡·ğŸ‡ºRU_439 |66.40Mb
  - ğŸ‡ºğŸ‡¸US_499 |10.53Mb
  - disney_US |895.03Mb
  - ğŸ‡ºğŸ‡¸US_518 |14.86Mb
  - disney_US |344.35Mb
  - ğŸ‡ºğŸ‡¸US_496 |192.21Mb
  - disney_US |308.65Mb
  - ğŸ‡ºğŸ‡¸US_478 |123.39Mb
  - disney_US |578.82Mb
  - ğŸ‡ºğŸ‡¸US_498 |39.97Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - _191 |173.86Mb
  - _201 |272.06Mb
  - ğŸ‡¨ğŸ‡¦CA_213 |31.09Mb
  - _155 |13.38Mb
  - _143 |49.26Mb
  - ğŸ‡¨ğŸ‡¦CA_217 |10.36Mb
  - _195 |906.33Mb
  - _160 |44.16Mb
  - _181 |43.94Mb
  - _166 |47.96Mb
  - _156 |13.57Mb
  - _146 |43.75Mb
  - ğŸ‡¨ğŸ‡·CR_236 |48.16Mb
  - ğŸ‡©ğŸ‡°DK_260 |49.23Mb
  - _167 |31.21Mb
  - ğŸ‡ªğŸ‡¸ES_266 |13.23Mb
  - ğŸ‡¬ğŸ‡§GB_296 |10.06Mb
  - ğŸ‡¬ğŸ‡§GB_300 |15.86Mb
  - ğŸ‡¬ğŸ‡§GB_302 |79.80Mb
  - ğŸ‡«ğŸ‡·FR_274 |13.14Mb
  - ğŸ‡«ğŸ‡·FR_281 |14.45Mb
  - ğŸ‡³ğŸ‡±NL_388 |10.12Mb
  - ğŸ‡³ğŸ‡±NL_390 |14.74Mb
  - ğŸ‡³ğŸ‡±NL_389 |12.45Mb
  - ğŸ‡³ğŸ‡±NL_391 |10.09Mb
  - ğŸ‡¯ğŸ‡µJP_332 |10.37Mb
  - ğŸ‡µğŸ‡±PL_399 |13.37Mb
  - ğŸ‡ºğŸ‡¸US_479 |55.45Mb
  - ğŸ‡ºğŸ‡¸US_482 |34.11Mb
  - ğŸ‡ºğŸ‡¸US_488 |55.45Mb
  - ğŸ‡µğŸ‡±PL_414 |11.70Mb
  - ğŸ‡·ğŸ‡ºRU_438 |179.54Mb
  - ğŸ‡ºğŸ‡¸US_476 |18.74Mb
  - ğŸ‡²ğŸ‡¹MT_369 |22.96Mb
  - ğŸ‡ºğŸ‡¸US_516 |34.55Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡²ğŸ‡©MD_513 |10.27Mb
  - ğŸ‡·ğŸ‡ºRU_439 |66.40Mb
  - ğŸ‡ºğŸ‡¸US_499 |10.53Mb
  - disney_US |895.03Mb
  - ğŸ‡ºğŸ‡¸US_518 |14.86Mb
  - disney_US |344.35Mb
  - ğŸ‡ºğŸ‡¸US_496 |192.21Mb
  - disney_US |308.65Mb
  - ğŸ‡ºğŸ‡¸US_478 |123.39Mb
  - disney_US |578.82Mb
  - ğŸ‡ºğŸ‡¸US_498 |39.97Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
