port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: ğŸ‡¨ğŸ‡¦CA_156 |14.68Mb
  server: 79.127.200.162
  type: ss
  country: ğŸ‡¨ğŸ‡¦CA
  port: 990
  password: f8f7aCzcPKbsF8p3
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸ‡¨ğŸ‡¦CA-ğŸ‡¨ğŸ‡¦CA_161 |431.00Mb
  server: ssca.irundns.net
  type: ssr
  country: ğŸ‡¨ğŸ‡¦CA
  port: 443
  password: $$Turb0VPN$$
  cipher: aes-128-cfb
  protocol: auth_aes128_md5
  obfs: http_post
- name: Relay_-ğŸ‡ºğŸ‡¸US_130 |24.93Mb
  server: us-n1.speedyyun.com
  type: vmess
  port: 25314
  udp: true
  uuid: 2a6c0365-e3ed-4aef-81ca-b1b6b46088da
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /victorias
    headers:
      Host: us-n1.speedyyun.com
- name: Pool_ğŸ‡¬ğŸ‡§GB_184 |10.85Mb
  server: 79.127.233.170
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 990
  password: f8f7aCzcPKbsF8p3
  cipher: chacha20-ietf-poly1305
- name: Relay_-ğŸ‡¯ğŸ‡µJP_136 |18.45Mb
  server: 160.16.68.250
  type: trojan
  port: 4451
  password: 253bc477d4e43c209f2d427272968280
  sni: www.nintendogames.net
  network: tcp
- name: ğŸ‡¦ğŸ‡ºAU_143 |28.42Mb
  server: 3.25.198.142
  type: ss
  country: ğŸ‡¦ğŸ‡ºAU
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡§ğŸ‡¬BG_151 |32.72Mb
  server: 94.156.250.122
  type: ss
  country: ğŸ‡§ğŸ‡¬BG
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¦ğŸ‡ºAU_144 |80.44Mb
  server: 143.244.62.106
  type: ss
  country: ğŸ‡¦ğŸ‡ºAU
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ğŸ‡¬ğŸ‡§GB_178 |92.16Mb
  server: 146.70.61.37
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: ğŸ‡¦ğŸ‡¹AT_140 |15.44Mb
  server: 151.236.11.221
  type: ss
  country: ğŸ‡¦ğŸ‡¹AT
  port: 8443
  password: kNAssqfNR8hhvm9rSSJvhq
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_180 |61.95Mb
  server: 38.180.30.147
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8388
  password: IDJY0hgIuUk7
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¯ğŸ‡µJP_235 |26.78Mb
  server: 160.16.123.124
  type: ss
  country: ğŸ‡¯ğŸ‡µJP
  port: 10087
  password: '10086'
  cipher: aes-128-gcm
- name: ğŸ‡­ğŸ‡°HK_196 |11.55Mb
  server: 47.239.141.74
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 11886
  uuid: 0d36b017-6d7c-493d-bb12-55c34faf6efc
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
  ws-opts:
    path: /
- name: ğŸ‡°ğŸ‡·KR_237 |44.37Mb
  server: 154.90.63.177
  type: ss
  country: ğŸ‡°ğŸ‡·KR
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ğŸ‡°ğŸ‡·KR_238 |10.89Mb
  server: 221.139.79.57
  type: ss
  country: ğŸ‡°ğŸ‡·KR
  port: 37008
  password: qwerREWQ@@
  cipher: aes-256-cfb
- name: Pool_ğŸ‡­ğŸ‡°HK_195 |519.00Mb
  server: 150.107.46.21
  type: ssr
  country: ğŸ‡­ğŸ‡°HK
  port: 8083
  password: iFqnzSscN
  cipher: aes-256-cfb
  protocol: origin
  obfs: tls1.2_ticket_auth
- name: ğŸ‡µğŸ‡±PL_265 |16.32Mb
  server: 217.30.10.18
  type: ss
  country: ğŸ‡µğŸ‡±PL
  port: 9094
  password: rpgbNnU9rDDU4aWZ
  cipher: aes-256-cfb
- name: ğŸ‡µğŸ‡±PL_266 |16.01Mb
  server: 217.30.10.18
  type: ss
  country: ğŸ‡µğŸ‡±PL
  port: 9027
  password: EXN3S3eQpjE7EJu8
  cipher: aes-256-cfb
- name: ğŸ‡µğŸ‡±PL_267 |22.41Mb
  server: 217.30.10.18
  type: ss
  country: ğŸ‡µğŸ‡±PL
  port: 9053
  password: SBM7R883jBmnqe6C
  cipher: aes-256-cfb
- name: ğŸ‡µğŸ‡±PL_284 |88.13Mb
  server: 217.30.10.70
  type: ss
  country: ğŸ‡µğŸ‡±PL
  port: 9084
  password: c3NtHJ5ujV2tGDfj
  cipher: aes-256-cfb
- name: ğŸ‡µğŸ‡±PL_275 |24.16Mb
  server: 77.83.246.74
  type: ss
  country: ğŸ‡µğŸ‡±PL
  port: 443
  password: w9wzHjefeN81NgMUuEFUda
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡µğŸ‡±PL_286 |17.30Mb
  server: 217.30.10.70
  type: ss
  country: ğŸ‡µğŸ‡±PL
  port: 9007
  password: kSPmvwdFzGMMW5pY
  cipher: aes-256-cfb
- name: ğŸ‡µğŸ‡±PL_290 |11.38Mb
  server: 217.30.10.70
  type: ss
  country: ğŸ‡µğŸ‡±PL
  port: 9019
  password: GA9KzeEgvfxNrgmM
  cipher: aes-256-cfb
- name: ğŸ‡µğŸ‡¹PT_296 |14.68Mb
  server: 185.231.233.173
  type: ss
  country: ğŸ‡µğŸ‡¹PT
  port: 990
  password: f8f7aCzcPKbsF8p3
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡µğŸ‡¹PT_297 |51.74Mb
  server: 185.231.233.173
  type: ss
  country: ğŸ‡µğŸ‡¹PT
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ğŸ‡ºğŸ‡¸US_333 |20.29Mb
  server: 167.88.61.59
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 8091
  password: PCnnH6SQSnfoS27
  cipher: aes-256-gcm
- name: ğŸ‡·ğŸ‡ºRU_300 |113.41Mb
  server: 95.163.176.37
  type: ss
  country: ğŸ‡·ğŸ‡ºRU
  port: 8506
  password: ZK8Hv7D68bNRynZeqLVFLM
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¸ğŸ‡¬SG_306 |31.94Mb
  server: 128.199.172.224
  type: ss
  country: ğŸ‡¸ğŸ‡¬SG
  port: 8080
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: ğŸ‡µğŸ‡¾PY_298 |35.78Mb
  server: 38.165.233.93
  type: ss
  country: ğŸ‡µğŸ‡¾PY
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ğŸ‡¸ğŸ‡¬SG_308 |36.45Mb
  server: 68.183.235.122
  type: ss
  country: ğŸ‡¸ğŸ‡¬SG
  port: 8080
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: ğŸ‡¸ğŸ‡¬SG_310 |40.58Mb
  server: 68.183.227.236
  type: ss
  country: ğŸ‡¸ğŸ‡¬SG
  port: 8080
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: ğŸ‡ºğŸ‡¸US_345 |11.38Mb
  server: 173.244.56.9
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: shadowsocks
  cipher: aes-128-gcm
- name: ğŸ‡ºğŸ‡¸US_359 |19.95Mb
  server: 167.88.61.59
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 8118
  password: cdBIDV42DCwnfIN
  cipher: aes-256-gcm
- name: Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_332 |68.60Mb
  server: us.vmagnum.win
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 57456
  password: 360e21d21977dc11
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¸ğŸ‡¬SG_312 |54.71Mb
  server: 167.71.205.112
  type: ss
  country: ğŸ‡¸ğŸ‡¬SG
  port: 80
  password: GjUtzQIjhyYSzhdN2ZMRft
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_344 |12.26Mb
  server: 156.146.38.169
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: shadowsocks
  cipher: aes-128-gcm
- name: ğŸ‡ºğŸ‡¸US_339 |21.33Mb
  server: 54.227.21.67
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡ºğŸ‡¸US_340 |11.17Mb
  server: 54.157.216.140
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_364 |25.14Mb
  server: 193.124.24.247
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 6511
  uuid: 5ef4e89b-262f-4c74-e793-c7332079f251
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_365 |16.82Mb
  server: 193.124.24.247
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 6507
  uuid: 3003e094-707c-4dbb-faca-4b8d579bc604
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡ºğŸ‡¸US_362 |18.23Mb
  server: 54.209.249.254
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡ºğŸ‡¸US_358 |36.13Mb
  server: us32.giamping.com
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 8080
  password: 42000e02-6b4d-46ad-a572-80db7db2a9ce
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸ‡¸ğŸ‡¬SG-ğŸ‡¸ğŸ‡¬SG_316 |31.94Mb
  server: oksl.cfapps.ap21.hana.ondemand.com
  type: vmess
  country: ğŸ‡¸ğŸ‡¬SG
  port: 443
  uuid: cb94c83d-50cf-4a68-ba03-c6ed757df1f2
  alterId: 0
  cipher: auto
  network: ws
  servername: oksl.cfapps.ap21.hana.ondemand.com
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /laoluo
    headers:
      HOST: oksl.cfapps.ap21.hana.ondemand.com
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - ğŸ‡¨ğŸ‡¦CA_156 |14.68Mb
  - Relay_ğŸ‡¨ğŸ‡¦CA-ğŸ‡¨ğŸ‡¦CA_161 |431.00Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_130 |24.93Mb
  - Pool_ğŸ‡¬ğŸ‡§GB_184 |10.85Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_136 |18.45Mb
  - ğŸ‡¦ğŸ‡ºAU_143 |28.42Mb
  - ğŸ‡§ğŸ‡¬BG_151 |32.72Mb
  - ğŸ‡¦ğŸ‡ºAU_144 |80.44Mb
  - ğŸ‡¬ğŸ‡§GB_178 |92.16Mb
  - ğŸ‡¦ğŸ‡¹AT_140 |15.44Mb
  - ğŸ‡¬ğŸ‡§GB_180 |61.95Mb
  - ğŸ‡¯ğŸ‡µJP_235 |26.78Mb
  - ğŸ‡­ğŸ‡°HK_196 |11.55Mb
  - ğŸ‡°ğŸ‡·KR_237 |44.37Mb
  - ğŸ‡°ğŸ‡·KR_238 |10.89Mb
  - Pool_ğŸ‡­ğŸ‡°HK_195 |519.00Mb
  - ğŸ‡µğŸ‡±PL_265 |16.32Mb
  - ğŸ‡µğŸ‡±PL_266 |16.01Mb
  - ğŸ‡µğŸ‡±PL_267 |22.41Mb
  - ğŸ‡µğŸ‡±PL_284 |88.13Mb
  - ğŸ‡µğŸ‡±PL_275 |24.16Mb
  - ğŸ‡µğŸ‡±PL_286 |17.30Mb
  - ğŸ‡µğŸ‡±PL_290 |11.38Mb
  - ğŸ‡µğŸ‡¹PT_296 |14.68Mb
  - ğŸ‡µğŸ‡¹PT_297 |51.74Mb
  - ğŸ‡ºğŸ‡¸US_333 |20.29Mb
  - ğŸ‡·ğŸ‡ºRU_300 |113.41Mb
  - ğŸ‡¸ğŸ‡¬SG_306 |31.94Mb
  - ğŸ‡µğŸ‡¾PY_298 |35.78Mb
  - ğŸ‡¸ğŸ‡¬SG_308 |36.45Mb
  - ğŸ‡¸ğŸ‡¬SG_310 |40.58Mb
  - ğŸ‡ºğŸ‡¸US_345 |11.38Mb
  - ğŸ‡ºğŸ‡¸US_359 |19.95Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_332 |68.60Mb
  - ğŸ‡¸ğŸ‡¬SG_312 |54.71Mb
  - ğŸ‡ºğŸ‡¸US_344 |12.26Mb
  - ğŸ‡ºğŸ‡¸US_339 |21.33Mb
  - ğŸ‡ºğŸ‡¸US_340 |11.17Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_364 |25.14Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_365 |16.82Mb
  - ğŸ‡ºğŸ‡¸US_362 |18.23Mb
  - ğŸ‡ºğŸ‡¸US_358 |36.13Mb
  - Relay_ğŸ‡¸ğŸ‡¬SG-ğŸ‡¸ğŸ‡¬SG_316 |31.94Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - ğŸ‡¨ğŸ‡¦CA_156 |14.68Mb
  - Relay_ğŸ‡¨ğŸ‡¦CA-ğŸ‡¨ğŸ‡¦CA_161 |431.00Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_130 |24.93Mb
  - Pool_ğŸ‡¬ğŸ‡§GB_184 |10.85Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_136 |18.45Mb
  - ğŸ‡¦ğŸ‡ºAU_143 |28.42Mb
  - ğŸ‡§ğŸ‡¬BG_151 |32.72Mb
  - ğŸ‡¦ğŸ‡ºAU_144 |80.44Mb
  - ğŸ‡¬ğŸ‡§GB_178 |92.16Mb
  - ğŸ‡¦ğŸ‡¹AT_140 |15.44Mb
  - ğŸ‡¬ğŸ‡§GB_180 |61.95Mb
  - ğŸ‡¯ğŸ‡µJP_235 |26.78Mb
  - ğŸ‡­ğŸ‡°HK_196 |11.55Mb
  - ğŸ‡°ğŸ‡·KR_237 |44.37Mb
  - ğŸ‡°ğŸ‡·KR_238 |10.89Mb
  - Pool_ğŸ‡­ğŸ‡°HK_195 |519.00Mb
  - ğŸ‡µğŸ‡±PL_265 |16.32Mb
  - ğŸ‡µğŸ‡±PL_266 |16.01Mb
  - ğŸ‡µğŸ‡±PL_267 |22.41Mb
  - ğŸ‡µğŸ‡±PL_284 |88.13Mb
  - ğŸ‡µğŸ‡±PL_275 |24.16Mb
  - ğŸ‡µğŸ‡±PL_286 |17.30Mb
  - ğŸ‡µğŸ‡±PL_290 |11.38Mb
  - ğŸ‡µğŸ‡¹PT_296 |14.68Mb
  - ğŸ‡µğŸ‡¹PT_297 |51.74Mb
  - ğŸ‡ºğŸ‡¸US_333 |20.29Mb
  - ğŸ‡·ğŸ‡ºRU_300 |113.41Mb
  - ğŸ‡¸ğŸ‡¬SG_306 |31.94Mb
  - ğŸ‡µğŸ‡¾PY_298 |35.78Mb
  - ğŸ‡¸ğŸ‡¬SG_308 |36.45Mb
  - ğŸ‡¸ğŸ‡¬SG_310 |40.58Mb
  - ğŸ‡ºğŸ‡¸US_345 |11.38Mb
  - ğŸ‡ºğŸ‡¸US_359 |19.95Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_332 |68.60Mb
  - ğŸ‡¸ğŸ‡¬SG_312 |54.71Mb
  - ğŸ‡ºğŸ‡¸US_344 |12.26Mb
  - ğŸ‡ºğŸ‡¸US_339 |21.33Mb
  - ğŸ‡ºğŸ‡¸US_340 |11.17Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_364 |25.14Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_365 |16.82Mb
  - ğŸ‡ºğŸ‡¸US_362 |18.23Mb
  - ğŸ‡ºğŸ‡¸US_358 |36.13Mb
  - Relay_ğŸ‡¸ğŸ‡¬SG-ğŸ‡¸ğŸ‡¬SG_316 |31.94Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
