port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: ' |150.76Mb'
  server: 82.198.246.97
  type: vmess
  port: 180
  udp: true
  uuid: d13fc2f5-3e05-4795-81eb-44143a09e552
  alterId: 0
  cipher: auto
  servername: 82.198.246.97
  http-opts: {}
  h2-opts: {}
- name: ' |11.92Mb'
  server: 185.153.197.5
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ' |13.83Mb'
  server: 160.16.242.183
  type: trojan
  port: 1331
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: ' |28.86Mb'
  server: 160.16.89.176
  type: trojan
  port: 4054
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: ' |11.40Mb'
  server: 160.16.153.13
  type: trojan
  port: 3145
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: ' |126.89Mb'
  server: 8.218.105.196
  type: vmess
  port: 52752
  uuid: 925bdbf5-72be-4437-bebf-441c61089f6b
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
- name: ' |17.70Mb'
  server: 58.152.18.95
  type: trojan
  port: 443
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: ğŸ‡¬ğŸ‡§GB |48.41Mb
  server: 51.15.17.169
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ' |83.14Mb'
  server: 58.152.30.120
  type: trojan
  port: 443
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: ğŸ‡¬ğŸ‡§GB |175.78Mb
  server: 195.66.27.148
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 28709
  password: hShp1Km0NcFSmSigc8ozky
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡²ğŸ‡½MX |174.29Mb
  server: 216.238.89.53
  type: vmess
  country: ğŸ‡²ğŸ‡½MX
  port: 57283
  uuid: 1a5aafc0-6482-451d-fe76-6875b7818579
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ' |46.32Mb'
  server: v10.hdacd.com
  type: vmess
  port: 30807
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: ğŸ‡®ğŸ‡ªIE |309.41Mb
  server: 146.70.90.196
  type: ss
  country: ğŸ‡®ğŸ‡ªIE
  port: 17454
  password: u8gp148iz90ddoo6ms37
  cipher: aes-128-gcm
- name: ' |43.70Mb'
  server: 160.16.106.144
  type: trojan
  port: 4054
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: ' |70.34Mb'
  server: 219.79.186.107
  type: trojan
  port: 443
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: ğŸ‡ºğŸ‡¸US |23.75Mb
  server: 209.74.86.194
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 14936
  password: ppgtoOHdm7cszGunBWBTqQ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US |32.63Mb
  server: 38.14.99.163
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 59807
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: auto
  network: tcp
  servername: 38.14.99.163
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡ºğŸ‡¸US |25.37Mb
  server: 91.186.217.246
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 31764
  password: Ftc17VH9ZXQON5vslJCYmv
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US |23.93Mb
  server: 209.74.81.149
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 21166
  password: q92MrrP9oJ3lMEzbQFpyuU
  cipher: chacha20-ietf-poly1305
- name: ' |19.75Mb'
  server: v8.hdacd.com
  type: vmess
  port: 30808
  udp: true
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: ' |28.39Mb'
  server: cf.fovi.tk
  type: vmess
  country: ğŸZZ
  port: 443
  uuid: bf67437e-6c90-45ca-abc2-c7240a5ce2aa
  alterId: 0
  cipher: auto
  network: ws
  servername: foxlux.fovi.tk
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /eisasqa
    headers:
      HOST: foxlux.fovi.tk
- name: ' |58.33Mb'
  server: 58.152.25.20
  type: trojan
  port: 443
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - ' |150.76Mb'
  - ' |11.92Mb'
  - ' |13.83Mb'
  - ' |28.86Mb'
  - ' |11.40Mb'
  - ' |126.89Mb'
  - ' |17.70Mb'
  - ğŸ‡¬ğŸ‡§GB |48.41Mb
  - ' |83.14Mb'
  - ğŸ‡¬ğŸ‡§GB |175.78Mb
  - ğŸ‡²ğŸ‡½MX |174.29Mb
  - ' |46.32Mb'
  - ğŸ‡®ğŸ‡ªIE |309.41Mb
  - ' |43.70Mb'
  - ' |70.34Mb'
  - ğŸ‡ºğŸ‡¸US |23.75Mb
  - ğŸ‡ºğŸ‡¸US |32.63Mb
  - ğŸ‡ºğŸ‡¸US |25.37Mb
  - ğŸ‡ºğŸ‡¸US |23.93Mb
  - ' |19.75Mb'
  - ' |28.39Mb'
  - ' |58.33Mb'
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - ' |150.76Mb'
  - ' |11.92Mb'
  - ' |13.83Mb'
  - ' |28.86Mb'
  - ' |11.40Mb'
  - ' |126.89Mb'
  - ' |17.70Mb'
  - ğŸ‡¬ğŸ‡§GB |48.41Mb
  - ' |83.14Mb'
  - ğŸ‡¬ğŸ‡§GB |175.78Mb
  - ğŸ‡²ğŸ‡½MX |174.29Mb
  - ' |46.32Mb'
  - ğŸ‡®ğŸ‡ªIE |309.41Mb
  - ' |43.70Mb'
  - ' |70.34Mb'
  - ğŸ‡ºğŸ‡¸US |23.75Mb
  - ğŸ‡ºğŸ‡¸US |32.63Mb
  - ğŸ‡ºğŸ‡¸US |25.37Mb
  - ğŸ‡ºğŸ‡¸US |23.93Mb
  - ' |19.75Mb'
  - ' |28.39Mb'
  - ' |58.33Mb'
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
