port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: Relay_-ğŸ‡ºğŸ‡¸US_492 |40.39Mb
  server: 38.14.99.179
  type: vmess
  port: 59807
  udp: true
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_-ğŸ‡³ğŸ‡±NL_649 |23.95Mb
  server: 160.16.57.238
  type: trojan
  port: 4054
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: netflix_NL |200.92Mb
  server: 151.242.251.137
  type: ss
  port: 8080
  password: o5osZg269v5zHpYjr1xY9s
  cipher: chacha20-ietf-poly1305
- name: _462 |46.09Mb
  server: 45.83.20.206
  type: ss
  port: 443
  udp: true
  password: g5RQoxQuVtnFv3Xxsa8edPisXNPnyWKy
  cipher: chacha20-ietf-poly1305
- name: _458 |17.17Mb
  server: 103.231.73.211
  type: ss
  port: 57456
  udp: true
  password: 8afc633eb63227e9
  cipher: chacha20-ietf-poly1305
- name: Relay_-ğŸ‡ºğŸ‡¸US_474 |16.09Mb
  server: v8.hdacd.com
  type: vmess
  port: 30808
  udp: true
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_-ğŸ‡ºğŸ‡¸US_595 |12.55Mb
  server: v29.hdacd.com
  type: vmess
  port: 30829
  udp: true
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_SG |34.48Mb
  server: 188.253.124.53
  type: ss
  port: 63257
  udp: true
  password: RenzheCloudSS
  cipher: rc4-md5
  plugin: obfs
  plugin-opts:
    host: d1bf8290613.microsoft.com
    mode: http
- name: Relay_-ğŸ‡¸ğŸ‡¬SG_650 |10.03Mb
  server: 160.16.212.152
  type: trojan
  port: 507
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¯ğŸ‡µJP_651 |11.55Mb
  server: 153.121.45.139
  type: trojan
  port: 1331
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¯ğŸ‡µJP_653 |18.81Mb
  server: 153.121.38.213
  type: trojan
  port: 1331
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¯ğŸ‡µJP_663 |13.93Mb
  server: 160.16.72.33
  type: trojan
  port: 3093
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: _460 |97.16Mb
  server: 185.231.233.112
  type: ss
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: Relay_-ğŸ‡¯ğŸ‡µJP_665 |19.06Mb
  server: 160.16.70.180
  type: trojan
  port: 1331
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡³ğŸ‡±NL_670 |12.95Mb
  server: 160.16.131.243
  type: trojan
  port: 2890
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: disney_HK |27.18Mb
  server: 58.152.110.154
  type: trojan
  port: 443
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: _661 |12.43Mb
  server: 68.183.231.236
  type: trojan
  port: 443
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: disney_FR |152.00Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 27092
  uuid: a0596ba6-72a3-4366-8992-77088da65bd8
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_FR |205.18Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 40433
  uuid: d8fd8955-78db-49ba-d86f-3e4729f6ac4d
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡§ğŸ‡·BR_674 |115.85Mb
  server: 38.180.16.86
  type: vmess
  country: ğŸ‡§ğŸ‡·BR
  port: 36104
  uuid: E146A8CB-9D2F-449C-ADCA-8736FB
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡¬ğŸ‡§GB_679 |10.66Mb
  server: 82.38.31.179
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: netflix_NL |183.47Mb
  server: 82.38.31.190
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: netflix_NL |222.24Mb
  server: 82.38.31.210
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡²ğŸ‡½MX_822 |37.38Mb
  server: 216.238.89.53
  type: vmess
  country: ğŸ‡²ğŸ‡½MX
  port: 57283
  uuid: 1a5aafc0-6482-451d-fe76-6875b7818579
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡­ğŸ‡°HK_699 |21.92Mb
  server: 87.121.162.249
  type: ss
  country: ğŸ‡­ğŸ‡°HK
  port: 443
  password: JGv616hMWdjfuZ00jYfq7XkBHJZrOBrg
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸ‡¯ğŸ‡µJP-ğŸ‡¯ğŸ‡µJP_816 |22.06Mb
  server: kuame.missionsec.us
  type: trojan
  country: ğŸ‡¯ğŸ‡µJP
  port: 443
  udp: true
  password: FDIypSwe64a3DA7un2R8DFjYXZO3NS05gKZTTOC8SxO0Fy3cqYg3EaFDA3ABaEYKNx39D
  sni: kuame.missionsec.us
  skip-cert-verify: true
- name: ğŸ‡·ğŸ‡ºRU_825 |57.69Mb
  server: 109.71.246.210
  type: ss
  country: ğŸ‡·ğŸ‡ºRU
  port: 56689
  password: YQCSKoCF3QazW8YlvDBWA4
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡®ğŸ‡³IN_815 |126.41Mb
  server: 134.209.147.198
  type: ss
  country: ğŸ‡®ğŸ‡³IN
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ğŸ‡²ğŸ‡¾MY_823 |32.03Mb
  server: 38.54.98.110
  type: vmess
  country: ğŸ‡²ğŸ‡¾MY
  port: 2052
  uuid: 665d9b8f-153d-4907-adac-de12afd9c851
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: netflix_US |16.93Mb
  server: 104.192.226.106
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: netflix_US |40.80Mb
  server: 38.14.99.163
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 59807
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: auto
  network: tcp
  servername: 38.14.99.163
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_RU |482.11Mb
  server: 38.60.223.8
  type: ss
  country: ğŸ‡·ğŸ‡ºRU
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ğŸ‡¸ğŸ‡¬SG_827 |10.95Mb
  server: 68.183.178.131
  type: vmess
  country: ğŸ‡¸ğŸ‡¬SG
  port: 58607
  uuid: c11c32cb-27b3-4afa-c0f3-fb250aa4959e
  alterId: 0
  cipher: auto
  network: ws
  servername: www.12333.monster
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /
    headers:
      HOST: www.12333.monster
- name: netflix_LU |147.99Mb
  server: 45.12.144.18
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: LQyAUItafUmmO3EZZx9UbiX6IGydSBgL
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_833 |143.70Mb
  server: 45.12.136.170
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: l668XHPejoSNNuD66BYzyehaCpZexiF7
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_837 |12.56Mb
  server: 45.136.12.37
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 38141
  uuid: fd291be6-b48d-43a1-da38-66c7f80e2f80
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_831 |447.99Mb
  server: clr.ducks.tel
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 17844
  password: '907560230'
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡·ğŸ‡ºRU_832 |42.29Mb
  server: clr.ducks.tel
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 17847
  password: '907560230'
  cipher: chacha20-ietf-poly1305
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - Relay_-ğŸ‡ºğŸ‡¸US_492 |40.39Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_649 |23.95Mb
  - netflix_NL |200.92Mb
  - _462 |46.09Mb
  - _458 |17.17Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_474 |16.09Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_595 |12.55Mb
  - disney_SG |34.48Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_650 |10.03Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_651 |11.55Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_653 |18.81Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_663 |13.93Mb
  - _460 |97.16Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_665 |19.06Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_670 |12.95Mb
  - disney_HK |27.18Mb
  - _661 |12.43Mb
  - disney_FR |152.00Mb
  - disney_FR |205.18Mb
  - ğŸ‡§ğŸ‡·BR_674 |115.85Mb
  - ğŸ‡¬ğŸ‡§GB_679 |10.66Mb
  - netflix_NL |183.47Mb
  - netflix_NL |222.24Mb
  - ğŸ‡²ğŸ‡½MX_822 |37.38Mb
  - ğŸ‡­ğŸ‡°HK_699 |21.92Mb
  - Relay_ğŸ‡¯ğŸ‡µJP-ğŸ‡¯ğŸ‡µJP_816 |22.06Mb
  - ğŸ‡·ğŸ‡ºRU_825 |57.69Mb
  - ğŸ‡®ğŸ‡³IN_815 |126.41Mb
  - ğŸ‡²ğŸ‡¾MY_823 |32.03Mb
  - netflix_US |16.93Mb
  - netflix_US |40.80Mb
  - disney_RU |482.11Mb
  - ğŸ‡¸ğŸ‡¬SG_827 |10.95Mb
  - netflix_LU |147.99Mb
  - ğŸ‡ºğŸ‡¸US_833 |143.70Mb
  - ğŸ‡ºğŸ‡¸US_837 |12.56Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_831 |447.99Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡·ğŸ‡ºRU_832 |42.29Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - Relay_-ğŸ‡ºğŸ‡¸US_492 |40.39Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_649 |23.95Mb
  - netflix_NL |200.92Mb
  - _462 |46.09Mb
  - _458 |17.17Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_474 |16.09Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_595 |12.55Mb
  - disney_SG |34.48Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_650 |10.03Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_651 |11.55Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_653 |18.81Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_663 |13.93Mb
  - _460 |97.16Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_665 |19.06Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_670 |12.95Mb
  - disney_HK |27.18Mb
  - _661 |12.43Mb
  - disney_FR |152.00Mb
  - disney_FR |205.18Mb
  - ğŸ‡§ğŸ‡·BR_674 |115.85Mb
  - ğŸ‡¬ğŸ‡§GB_679 |10.66Mb
  - netflix_NL |183.47Mb
  - netflix_NL |222.24Mb
  - ğŸ‡²ğŸ‡½MX_822 |37.38Mb
  - ğŸ‡­ğŸ‡°HK_699 |21.92Mb
  - Relay_ğŸ‡¯ğŸ‡µJP-ğŸ‡¯ğŸ‡µJP_816 |22.06Mb
  - ğŸ‡·ğŸ‡ºRU_825 |57.69Mb
  - ğŸ‡®ğŸ‡³IN_815 |126.41Mb
  - ğŸ‡²ğŸ‡¾MY_823 |32.03Mb
  - netflix_US |16.93Mb
  - netflix_US |40.80Mb
  - disney_RU |482.11Mb
  - ğŸ‡¸ğŸ‡¬SG_827 |10.95Mb
  - netflix_LU |147.99Mb
  - ğŸ‡ºğŸ‡¸US_833 |143.70Mb
  - ğŸ‡ºğŸ‡¸US_837 |12.56Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_831 |447.99Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡·ğŸ‡ºRU_832 |42.29Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
