port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: ' |29.49Mb'
  server: 103.35.189.136
  type: ss
  port: 443
  udp: true
  password: SS2QvbC9nqLp2sXXZo0BVy4slcErRuCt
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_GB |50.41Mb
  server: 146.70.61.37
  type: ss
  port: 8080
  udp: true
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: disney_netflix_GB |14.71Mb
  server: 62.100.205.100
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ' |102.99Mb'
  server: 82.38.31.176
  type: ss
  port: 8080
  udp: true
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ' |13.90Mb'
  server: 196.196.192.58
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _271 |169.07Mb
  server: 51.15.23.166
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ' |46.60Mb'
  server: 138.186.143.32
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ' |46.64Mb'
  server: 138.186.143.32
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ' |14.52Mb'
  server: 141.98.101.178
  type: ss
  port: 443
  udp: true
  password: shadowsocks
  cipher: aes-128-gcm
- name: ' |11.09Mb'
  server: 89.221.225.15
  type: ss
  port: 443
  udp: true
  password: yCbQ4bry4otfifK7oel71NaXpPL9pYJb
  cipher: chacha20-ietf-poly1305
- name: Relay_ |10.40Mb
  server: 193.135.174.135
  type: ss
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ' |26.76Mb'
  server: 156.146.38.167
  type: ss
  port: 443
  udp: true
  password: shadowsocks
  cipher: aes-128-gcm
- name: ' |61.04Mb'
  server: 137.184.174.93
  type: ss
  port: 8080
  udp: true
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: ' |35.16Mb'
  server: 156.146.38.169
  type: ss
  port: 443
  udp: true
  password: shadowsocks
  cipher: aes-128-gcm
- name: ' |33.08Mb'
  server: 185.47.254.87
  type: ss
  port: 990
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: chacha20-ietf-poly1305
- name: ' |235.63Mb'
  server: 151.242.251.142
  type: ss
  port: 8080
  udp: true
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: disney_MX |28.93Mb
  server: 38.165.231.25
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ' |53.75Mb'
  server: 45.87.175.187
  type: ss
  port: 8080
  udp: true
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: ' |21.62Mb'
  server: 95.164.116.33
  type: ss
  port: 443
  password: pQmnC03JObbPhdh5FBJHgD6jnTLchsRA
  cipher: chacha20-ietf-poly1305
- name: ' |215.36Mb'
  server: 82.38.31.179
  type: ss
  port: 8080
  udp: true
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ' |19.10Mb'
  server: 149.22.87.241
  type: ss
  port: 443
  udp: true
  password: shadowsocks
  cipher: aes-128-gcm
- name: disney_PY |17.52Mb
  server: 38.165.233.93
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: _296 |109.34Mb
  server: 185.82.73.212
  type: ss
  port: 8444
  udp: true
  password: _bypfvq6ra7g4n5yCCR9DoVeGya2XUUS
  cipher: chacha20-ietf-poly1305
- name: ' |38.71Mb'
  server: 156.146.38.170
  type: ss
  port: 443
  udp: true
  password: shadowsocks
  cipher: aes-128-gcm
- name: netflix_NL |412.02Mb
  server: 45.14.245.2
  type: ss
  port: 443
  password: 17ZDORWIliQHuO6WRGHChXYMzdRtAYVP
  cipher: chacha20-ietf-poly1305
- name: ' |16.92Mb'
  server: 185.192.124.188
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ' |44.72Mb'
  server: 156.59.243.6
  type: ss
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ' |252.36Mb'
  server: 151.242.251.147
  type: ss
  port: 8080
  password: QCXDxuDlTTMD7jtgHUjIoj
  cipher: chacha20-ietf-poly1305
- name: ' |12.28Mb'
  server: 68.183.227.4
  type: ss
  port: 8080
  udp: true
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: ' |33.58Mb'
  server: 147.78.0.182
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: Relay_ |68.75Mb
  server: 79.127.200.169
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ' |29.25Mb'
  server: 119.59.98.58
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: disney_HK |10.91Mb
  server: 103.149.182.105
  type: ss
  port: 8388
  password: asd123456
  cipher: chacha20-ietf
- name: disney_ES |42.70Mb
  server: 145.249.109.121
  type: ss
  port: 25512
  udp: true
  password: smSMfR9jqLgMkHuQtxSIWh
  cipher: chacha20-ietf-poly1305
- name: ' |42.16Mb'
  server: 173.244.56.6
  type: ss
  port: 443
  udp: true
  password: shadowsocks
  cipher: aes-128-gcm
- name: ' |11.49Mb'
  server: 172.105.199.111
  type: ss
  port: 8080
  udp: true
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: disney_US |69.38Mb
  server: 79.127.200.162
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ' |28.80Mb'
  server: 119.59.98.58
  type: ss
  port: 990
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: chacha20-ietf-poly1305
- name: ' |14.52Mb'
  server: 173.234.29.2
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ' |21.29Mb'
  server: 128.199.172.224
  type: ss
  port: 8080
  udp: true
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: ' |51.72Mb'
  server: 172.233.229.91
  type: vmess
  port: 14102
  udp: true
  uuid: 27ba87fc-583f-4763-9060-83cf0b9264db
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ' |15.52Mb'
  server: 194.246.114.101
  type: ss
  port: 443
  udp: true
  password: HaNqw9pIE4jcx98sg7UQgHeGNTM4R2pk
  cipher: chacha20-ietf-poly1305
- name: ' |566.78Mb'
  server: 192.71.249.78
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: netflix_NL |11.48Mb
  server: 45.87.175.22
  type: ss
  port: 8080
  udp: true
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: ' |137.38Mb'
  server: 82.38.31.194
  type: ss
  port: 8080
  udp: true
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: netflix_NL |218.52Mb
  server: 151.242.251.152
  type: ss
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ' |239.86Mb'
  server: 82.38.31.214
  type: ss
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: disney_HK |16.82Mb
  server: 149.88.95.217
  type: vmess
  port: 35760
  uuid: 17e96792-d8c3-4741-9c34-e5d1c11d754f
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
- name: disney_HK |19.98Mb
  server: 149.88.95.94
  type: vmess
  port: 40741
  uuid: 1b8a751b-4909-4fec-f019-907d92e6c47f
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
- name: disney_HK |20.31Mb
  server: 149.88.95.217
  type: vmess
  port: 40741
  uuid: 1b8a751b-4909-4fec-f019-907d92e6c47f
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
- name: disney_HK |14.99Mb
  server: 149.88.95.94
  type: vmess
  port: 35760
  uuid: 17e96792-d8c3-4741-9c34-e5d1c11d754f
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
- name: Relay_-ğŸ‡¯ğŸ‡µJP_361 |11.28Mb
  server: 160.16.72.33
  type: trojan
  port: 3093
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: netflix_NL |349.53Mb
  server: h110vpnnl.outlinekeys.net
  type: ss
  port: 52571
  udp: true
  password: b0TKxnHAYeeFYyzTAMXn0F
  cipher: chacha20-ietf-poly1305
- name: disney_HK |27.48Mb
  server: 219.79.214.159
  type: trojan
  port: 443
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: Relay_-ğŸ‡¯ğŸ‡µJP_365 |41.91Mb
  server: 160.16.229.223
  type: trojan
  port: 3169
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¯ğŸ‡µJP_366 |13.84Mb
  server: 160.16.87.174
  type: trojan
  port: 3169
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: ' |16.64Mb'
  server: 193.203.203.66
  type: ss
  country: ğŸ‡¨ğŸ‡¦CA
  port: 443
  password: S6jUK9Fw5fMHgNqlqXObHZWv8Tf4nEkm
  cipher: chacha20-ietf-poly1305
- name: ' |13.92Mb'
  server: 160.16.136.130
  type: trojan
  port: 2890
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: ' |18.25Mb'
  server: 160.16.204.136
  type: trojan
  port: 2890
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: ' |14.20Mb'
  server: 160.16.124.55
  type: trojan
  port: 2890
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: ' |11.88Mb'
  server: 47.242.225.242
  type: trojan
  port: 443
  udp: true
  password: 92690597d6298061459918a371e8d77d
  sni: hezijiasuqi.com
  skip-cert-verify: true
- name: ' |12.19Mb'
  server: 160.16.116.227
  type: trojan
  port: 2760
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
  skip-cert-verify: true
- name: Relay_-ğŸ‡­ğŸ‡°HK_352 |15.21Mb
  server: v10.hdacd.com
  type: vmess
  port: 30807
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: ' |10.89Mb'
  server: 160.16.131.243
  type: trojan
  port: 2760
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
  skip-cert-verify: true
- name: disney_DE |289.06Mb
  server: 89.163.140.136
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: Relay_ |41.82Mb
  server: v4.hdacd.com
  type: vmess
  port: 30804
  udp: true
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ' |16.01Mb'
  server: 185.192.124.188
  type: ss
  country: ğŸ‡§ğŸ‡·BR
  port: 990
  password: f8f7aCzcPKbsF8p3
  cipher: chacha20-ietf-poly1305
- name: ' |65.01Mb'
  server: 185.213.23.63
  type: ss
  country: ğŸ‡¨ğŸ‡¦CA
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: disney_CH |59.21Mb
  server: 138.124.67.26
  type: ss
  country: ğŸ‡¨ğŸ‡­CH
  port: 25572
  password: nqcIfYHlpMn3jzqkNDjKaG
  cipher: chacha20-ietf-poly1305
- name: ' |19.13Mb'
  server: 141.98.101.182
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: shadowsocks
  cipher: aes-128-gcm
- name: Relay_ |140.48Mb
  server: 82.38.31.208
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ' |30.26Mb'
  server: 154.205.153.107
  type: ss
  country: ğŸ‡¨ğŸ‡±CL
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ' |200.42Mb'
  server: 45.87.175.185
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_404 |93.43Mb
  server: 45.87.175.180
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: QCXDxuDlTTMD7jtgHUjIoj
  cipher: chacha20-ietf-poly1305
- name: ' |85.93Mb'
  server: 45.87.175.175
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: QCXDxuDlTTMD7jtgHUjIoj
  cipher: chacha20-ietf-poly1305
- name: ' |27.97Mb'
  server: 45.207.157.29
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 13852
  uuid: 845764df-ecb3-4b13-bed2-bf1551b68e9a
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ' |165.86Mb'
  server: 45.87.175.183
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: netflix_NL |102.81Mb
  server: 45.87.175.185
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: Relay_ |38.43Mb
  server: 104.18.14.55
  type: vmess
  country: ğŸZZ
  port: 2052
  uuid: e6447786-8c85-443c-8017-7feaa673ff45
  alterId: 0
  cipher: auto
  network: ws
  servername: in4.123417.xyz
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
  ws-opts:
    path: /
    headers:
      HOST: in4.123417.xyz
- name: Relay_ |40.45Mb
  server: 38.14.99.163
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 59807
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: auto
  network: tcp
  servername: 38.14.99.163
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ' |17.54Mb'
  server: 178.23.190.238
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 443
  password: uo7EbtqIwgZXXHmMv5LbLcOxptyPlNkh
  cipher: chacha20-ietf-poly1305
- name: ' |50.31Mb'
  server: 176.123.5.253
  type: ss
  country: ğŸ‡²ğŸ‡©MD
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ' |139.80Mb'
  server: 193.29.139.141
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 8080
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: ' |290.34Mb'
  server: 194.87.216.218
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 52571
  password: b0TKxnHAYeeFYyzTAMXn0F
  cipher: chacha20-ietf-poly1305
- name: ' |58.20Mb'
  server: 185.113.143.186
  type: ss
  country: ğŸ‡µğŸ‡¹PT
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ' |10.10Mb'
  server: 68.183.227.45
  type: ss
  country: ğŸ‡¸ğŸ‡¬SG
  port: 8080
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: ' |137.58Mb'
  server: 185.231.233.112
  type: ss
  country: ğŸ ZZ
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ' |14.31Mb'
  server: ltnl16.saint.ydns.eu
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - ' |29.49Mb'
  - disney_netflix_GB |50.41Mb
  - disney_netflix_GB |14.71Mb
  - ' |102.99Mb'
  - ' |13.90Mb'
  - _271 |169.07Mb
  - ' |46.60Mb'
  - ' |46.64Mb'
  - ' |14.52Mb'
  - ' |11.09Mb'
  - Relay_ |10.40Mb
  - ' |26.76Mb'
  - ' |61.04Mb'
  - ' |35.16Mb'
  - ' |33.08Mb'
  - ' |235.63Mb'
  - disney_MX |28.93Mb
  - ' |53.75Mb'
  - ' |21.62Mb'
  - ' |215.36Mb'
  - ' |19.10Mb'
  - disney_PY |17.52Mb
  - _296 |109.34Mb
  - ' |38.71Mb'
  - netflix_NL |412.02Mb
  - ' |16.92Mb'
  - ' |44.72Mb'
  - ' |252.36Mb'
  - ' |12.28Mb'
  - ' |33.58Mb'
  - Relay_ |68.75Mb
  - ' |29.25Mb'
  - disney_HK |10.91Mb
  - disney_ES |42.70Mb
  - ' |42.16Mb'
  - ' |11.49Mb'
  - disney_US |69.38Mb
  - ' |28.80Mb'
  - ' |14.52Mb'
  - ' |21.29Mb'
  - ' |51.72Mb'
  - ' |15.52Mb'
  - ' |566.78Mb'
  - netflix_NL |11.48Mb
  - ' |137.38Mb'
  - netflix_NL |218.52Mb
  - ' |239.86Mb'
  - disney_HK |16.82Mb
  - disney_HK |19.98Mb
  - disney_HK |20.31Mb
  - disney_HK |14.99Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_361 |11.28Mb
  - netflix_NL |349.53Mb
  - disney_HK |27.48Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_365 |41.91Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_366 |13.84Mb
  - ' |16.64Mb'
  - ' |13.92Mb'
  - ' |18.25Mb'
  - ' |14.20Mb'
  - ' |11.88Mb'
  - ' |12.19Mb'
  - Relay_-ğŸ‡­ğŸ‡°HK_352 |15.21Mb
  - ' |10.89Mb'
  - disney_DE |289.06Mb
  - Relay_ |41.82Mb
  - ' |16.01Mb'
  - ' |65.01Mb'
  - disney_CH |59.21Mb
  - ' |19.13Mb'
  - Relay_ |140.48Mb
  - ' |30.26Mb'
  - ' |200.42Mb'
  - ğŸ‡±ğŸ‡¹LT_404 |93.43Mb
  - ' |85.93Mb'
  - ' |27.97Mb'
  - ' |165.86Mb'
  - netflix_NL |102.81Mb
  - Relay_ |38.43Mb
  - Relay_ |40.45Mb
  - ' |17.54Mb'
  - ' |50.31Mb'
  - ' |139.80Mb'
  - ' |290.34Mb'
  - ' |58.20Mb'
  - ' |10.10Mb'
  - ' |137.58Mb'
  - ' |14.31Mb'
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - ' |29.49Mb'
  - disney_netflix_GB |50.41Mb
  - disney_netflix_GB |14.71Mb
  - ' |102.99Mb'
  - ' |13.90Mb'
  - _271 |169.07Mb
  - ' |46.60Mb'
  - ' |46.64Mb'
  - ' |14.52Mb'
  - ' |11.09Mb'
  - Relay_ |10.40Mb
  - ' |26.76Mb'
  - ' |61.04Mb'
  - ' |35.16Mb'
  - ' |33.08Mb'
  - ' |235.63Mb'
  - disney_MX |28.93Mb
  - ' |53.75Mb'
  - ' |21.62Mb'
  - ' |215.36Mb'
  - ' |19.10Mb'
  - disney_PY |17.52Mb
  - _296 |109.34Mb
  - ' |38.71Mb'
  - netflix_NL |412.02Mb
  - ' |16.92Mb'
  - ' |44.72Mb'
  - ' |252.36Mb'
  - ' |12.28Mb'
  - ' |33.58Mb'
  - Relay_ |68.75Mb
  - ' |29.25Mb'
  - disney_HK |10.91Mb
  - disney_ES |42.70Mb
  - ' |42.16Mb'
  - ' |11.49Mb'
  - disney_US |69.38Mb
  - ' |28.80Mb'
  - ' |14.52Mb'
  - ' |21.29Mb'
  - ' |51.72Mb'
  - ' |15.52Mb'
  - ' |566.78Mb'
  - netflix_NL |11.48Mb
  - ' |137.38Mb'
  - netflix_NL |218.52Mb
  - ' |239.86Mb'
  - disney_HK |16.82Mb
  - disney_HK |19.98Mb
  - disney_HK |20.31Mb
  - disney_HK |14.99Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_361 |11.28Mb
  - netflix_NL |349.53Mb
  - disney_HK |27.48Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_365 |41.91Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_366 |13.84Mb
  - ' |16.64Mb'
  - ' |13.92Mb'
  - ' |18.25Mb'
  - ' |14.20Mb'
  - ' |11.88Mb'
  - ' |12.19Mb'
  - Relay_-ğŸ‡­ğŸ‡°HK_352 |15.21Mb
  - ' |10.89Mb'
  - disney_DE |289.06Mb
  - Relay_ |41.82Mb
  - ' |16.01Mb'
  - ' |65.01Mb'
  - disney_CH |59.21Mb
  - ' |19.13Mb'
  - Relay_ |140.48Mb
  - ' |30.26Mb'
  - ' |200.42Mb'
  - ğŸ‡±ğŸ‡¹LT_404 |93.43Mb
  - ' |85.93Mb'
  - ' |27.97Mb'
  - ' |165.86Mb'
  - netflix_NL |102.81Mb
  - Relay_ |38.43Mb
  - Relay_ |40.45Mb
  - ' |17.54Mb'
  - ' |50.31Mb'
  - ' |139.80Mb'
  - ' |290.34Mb'
  - ' |58.20Mb'
  - ' |10.10Mb'
  - ' |137.58Mb'
  - ' |14.31Mb'
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
