port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: disney_netflix_US |42.92Mb
  server: 163.192.49.195
  type: vmess
  port: 443
  uuid: bcb7c581-3c95-4569-a4e7-918141e91ea3
  alterId: 0
  cipher: auto
  network: http
  http-opts:
    path:
    - /
    headers:
      Host:
      - a.189.cn
  h2-opts: {}
- name: disney_netflix_US |41.91Mb
  server: 165.140.216.141
  type: vmess
  port: 443
  uuid: e7d72a8d-26f2-4b54-b366-0c43e0bcba7d
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: disney_netflix_DE |276.37Mb
  server: 85.195.101.122
  type: vmess
  port: 40878
  uuid: f3d4167e-b15e-4e46-82e9-9286ef93fda7
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: Relay_-ğŸ‡­ğŸ‡°HK_188 |20.14Mb
  server: www.zhoubowen.vip
  type: vmess
  port: 443
  uuid: 71b2655e-07d9-4dad-a770-a2b08275142b
  alterId: 0
  cipher: auto
  network: ws
  servername: www.zhoubowen.vip
  http-opts: {}
  h2-opts: {}
  tls: true
  ws-opts:
    path: /biutefor.icu
    headers:
      Host: www.zhoubowen.vip
- name: disney_HK |17.84Mb
  server: 154.21.201.83
  type: vmess
  port: 443
  uuid: 4bf075f5-4d5e-4d39-f5ab-b32a86250f0e
  alterId: 0
  cipher: auto
  network: ws
  servername: hk.nbee.pp.ua
  http-opts: {}
  h2-opts: {}
  tls: true
  ws-opts:
    path: /aa
    headers:
      Host: hk.nbee.pp.ua
- name: _220 |10.02Mb
  server: 209.38.31.133
  type: vmess
  port: 32077
  udp: true
  uuid: 412b22ec-e9d9-4ec6-d3ab-6a59537398bf
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: Relay_-ğŸ‡ºğŸ‡¸US_183 |242.32Mb
  server: 3h-kazakhstan1.09vpn.com
  type: vmess
  port: 80
  uuid: 567f4be5-12ab-42e1-b8d9-db6fd1fdd31c
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /vmess/
    headers:
      Host: 3h-kazakhstan1.09vpn.com
- name: disney_netflix_US |22.73Mb
  server: 192.204.47.79
  type: vmess
  port: 42277
  udp: true
  uuid: aee61b21-e85a-484b-f203-b245f1451cff
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _224 |10.40Mb
  server: 54.206.192.9
  type: vmess
  port: 16407
  uuid: 08f45028-1db6-4e93-bf51-d344b6c71e19
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _227 |10.66Mb
  server: 140.238.2.250
  type: vmess
  port: 443
  uuid: 41a7089a-040b-4538-8b8d-010902405bde
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _237 |172.34Mb
  server: 216.238.86.158
  type: vmess
  port: 34460
  udp: true
  uuid: 90be214d-048c-4ea2-a602-b8e4d4e51e36
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _234 |161.93Mb
  server: 38.180.16.86
  type: vmess
  port: 38039
  uuid: 244a3464-1269-43b3-b491-4dc2713eb3f6
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _230 |25.43Mb
  server: 8.218.105.196
  type: vmess
  port: 52752
  uuid: 925bdbf5-72be-4437-bebf-441c61089f6b
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: netflix_SE |142.11Mb
  server: 70.34.218.149
  type: trojan
  port: 11930
  password: BaeSzHdfJIR13l67
  sni: softpillow.silentrocket.click
- name: netflix_CA |24.27Mb
  server: 38.96.254.102
  type: trojan
  port: 18509
  password: .ie4rghJuMkcf0oF
  sni: shoppingmall.electricbanana.click
- name: ğŸ‡ªğŸ‡¸ES_253 |149.23Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 27092
  uuid: a0596ba6-72a3-4366-8992-77088da65bd8
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: _240 |11.44Mb
  server: 160.16.236.32
  type: trojan
  port: 4054
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: _242 |18.41Mb
  server: 153.121.65.107
  type: trojan
  port: 3093
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: _244 |21.57Mb
  server: 153.121.53.187
  type: trojan
  port: 3093
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¸ğŸ‡¬SG_245 |10.15Mb
  server: 160.16.144.208
  type: trojan
  port: 507
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: _233 |44.06Mb
  server: 89.31.120.192
  type: vmess
  port: 443
  uuid: 44537595-9ccc-4b83-8936-5f9ad3229019
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: Relay_-ğŸ‡¯ğŸ‡µJP_249 |18.14Mb
  server: 153.121.67.215
  type: trojan
  port: 1331
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: ğŸ‡ªğŸ‡¸ES_254 |41.02Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 40433
  uuid: d8fd8955-78db-49ba-d86f-3e4729f6ac4d
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: netflix_NL |217.22Mb
  server: 82.38.31.194
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡²ğŸ‡½MX_263 |173.12Mb
  server: 216.238.87.47
  type: vmess
  country: ğŸ‡²ğŸ‡½MX
  port: 27502
  uuid: b8155ce4-7e08-4c40-800f-8671312b7124
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡¬ğŸ‡§GB_256 |65.75Mb
  server: 82.38.31.191
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_257 |221.57Mb
  server: 82.38.31.217
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_258 |471.33Mb
  server: 108.61.197.235
  type: vmess
  country: ğŸ‡¬ğŸ‡§GB
  port: 36713
  uuid: 42031a35-b71e-4845-e1c8-6478acb96613
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
  ws-opts:
    path: /42031a35-b71e-4845-e1c8-6478acb96613
- name: disney_HK |12.04Mb
  server: 45.207.157.29
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 13852
  uuid: 845764df-ecb3-4b13-bed2-bf1551b68e9a
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: _223 |161.36Mb
  server: 38.180.16.86
  type: vmess
  port: 36236
  uuid: a58bc1a5-8c18-49ff-9453-c331b52f45dc
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - disney_netflix_US |42.92Mb
  - disney_netflix_US |41.91Mb
  - disney_netflix_DE |276.37Mb
  - Relay_-ğŸ‡­ğŸ‡°HK_188 |20.14Mb
  - disney_HK |17.84Mb
  - _220 |10.02Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_183 |242.32Mb
  - disney_netflix_US |22.73Mb
  - _224 |10.40Mb
  - _227 |10.66Mb
  - _237 |172.34Mb
  - _234 |161.93Mb
  - _230 |25.43Mb
  - netflix_SE |142.11Mb
  - netflix_CA |24.27Mb
  - ğŸ‡ªğŸ‡¸ES_253 |149.23Mb
  - _240 |11.44Mb
  - _242 |18.41Mb
  - _244 |21.57Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_245 |10.15Mb
  - _233 |44.06Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_249 |18.14Mb
  - ğŸ‡ªğŸ‡¸ES_254 |41.02Mb
  - netflix_NL |217.22Mb
  - ğŸ‡²ğŸ‡½MX_263 |173.12Mb
  - ğŸ‡¬ğŸ‡§GB_256 |65.75Mb
  - ğŸ‡¬ğŸ‡§GB_257 |221.57Mb
  - ğŸ‡¬ğŸ‡§GB_258 |471.33Mb
  - disney_HK |12.04Mb
  - _223 |161.36Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - disney_netflix_US |42.92Mb
  - disney_netflix_US |41.91Mb
  - disney_netflix_DE |276.37Mb
  - Relay_-ğŸ‡­ğŸ‡°HK_188 |20.14Mb
  - disney_HK |17.84Mb
  - _220 |10.02Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_183 |242.32Mb
  - disney_netflix_US |22.73Mb
  - _224 |10.40Mb
  - _227 |10.66Mb
  - _237 |172.34Mb
  - _234 |161.93Mb
  - _230 |25.43Mb
  - netflix_SE |142.11Mb
  - netflix_CA |24.27Mb
  - ğŸ‡ªğŸ‡¸ES_253 |149.23Mb
  - _240 |11.44Mb
  - _242 |18.41Mb
  - _244 |21.57Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_245 |10.15Mb
  - _233 |44.06Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_249 |18.14Mb
  - ğŸ‡ªğŸ‡¸ES_254 |41.02Mb
  - netflix_NL |217.22Mb
  - ğŸ‡²ğŸ‡½MX_263 |173.12Mb
  - ğŸ‡¬ğŸ‡§GB_256 |65.75Mb
  - ğŸ‡¬ğŸ‡§GB_257 |221.57Mb
  - ğŸ‡¬ğŸ‡§GB_258 |471.33Mb
  - disney_HK |12.04Mb
  - _223 |161.36Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
