port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: disney_netflix_US |39.85Mb
  server: 163.192.49.195
  type: vmess
  port: 443
  uuid: bcb7c581-3c95-4569-a4e7-918141e91ea3
  alterId: 0
  cipher: auto
  network: http
  http-opts:
    path:
    - /
    headers:
      Host:
      - a.189.cn
  h2-opts: {}
- name: disney_netflix_US |35.37Mb
  server: 165.140.216.141
  type: vmess
  port: 443
  uuid: e7d72a8d-26f2-4b54-b366-0c43e0bcba7d
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _199 |186.06Mb
  server: 172.235.33.114
  type: vmess
  port: 10001
  uuid: 442a3923-eca1-4af0-b3ff-24a7ce0af68f
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _204 |28.04Mb
  server: 51.79.102.253
  type: vmess
  port: 80
  uuid: 58fe1542-5290-40ad-815a-77707a81afe5
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /IOebhLMhl1CTbFHbL95myfRX2
    headers:
      Host: wrmelmwxlf.gktevlrqznwqqozy.fabpfs66gizmnojhcvqxwl.kytrcfzqla87gvgvs6c7kjnrubuh.cc
- name: _188 |11.83Mb
  server: 45.14.245.2
  type: ss
  port: 443
  password: 17ZDORWIliQHuO6WRGHChXYMzdRtAYVP
  cipher: chacha20-ietf-poly1305
- name: _193 |155.54Mb
  server: 85.195.101.122
  type: vmess
  port: 40878
  uuid: f3d4167e-b15e-4e46-82e9-9286ef93fda7
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _213 |22.68Mb
  server: 91.99.27.55
  type: vmess
  port: 8880
  uuid: f3025961-167b-4f49-e4e3-86505fe980fd
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: disney_MD |203.59Mb
  server: 185.153.197.5
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: _223 |16.11Mb
  server: 8.218.116.26
  type: vmess
  port: 32228
  uuid: e4767e9f-ed00-4f31-a984-a918bdd9b09c
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _218 |11.69Mb
  server: 45.136.12.37
  type: vmess
  port: 38141
  uuid: fd291be6-b48d-43a1-da38-66c7f80e2f80
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: disney_SG |11.56Mb
  server: 165.154.195.38
  type: vmess
  port: 35034
  uuid: 959a8caf-4cea-43d0-a548-3628e7ddfafc
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: Relay_-ğŸ‡§ğŸ‡·BR_189 |73.02Mb
  server: pq-brazil1.09vpn.com
  type: vmess
  port: 80
  uuid: c04c3b34-70fd-4fec-963e-c12d09f36bef
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /vmess/
    headers:
      Host: pq-brazil1.09vpn.com
- name: Relay_-ğŸ‡­ğŸ‡°HK_219 |17.20Mb
  server: www.zhoubowen.vip
  type: vmess
  port: 443
  uuid: 71b2655e-07d9-4dad-a770-a2b08275142b
  alterId: 0
  cipher: auto
  network: ws
  servername: www.zhoubowen.vip
  http-opts: {}
  h2-opts: {}
  tls: true
  ws-opts:
    path: /biutefor.icu
    headers:
      Host: www.zhoubowen.vip
- name: _222 |37.98Mb
  server: 89.31.120.192
  type: vmess
  port: 443
  uuid: 44537595-9ccc-4b83-8936-5f9ad3229019
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _243 |10.35Mb
  server: 54.206.192.9
  type: vmess
  port: 16407
  uuid: 08f45028-1db6-4e93-bf51-d344b6c71e19
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _245 |10.38Mb
  server: 146.56.112.110
  type: vmess
  port: 8888
  uuid: e7c302f3-90d6-42dd-9d7d-94a3683a3707
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _231 |24.92Mb
  server: 8.218.105.196
  type: vmess
  port: 52752
  uuid: 925bdbf5-72be-4437-bebf-441c61089f6b
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _244 |19.15Mb
  server: 47.242.140.52
  type: vmess
  port: 34815
  uuid: 1a46b66c-6ba9-4e9c-aa0b-0ebac2b69e32
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /arki
- name: _255 |159.41Mb
  server: 38.96.254.102
  type: trojan
  port: 18509
  password: .ie4rghJuMkcf0oF
  sni: shoppingmall.electricbanana.click
- name: _249 |11.29Mb
  server: 160.16.236.32
  type: trojan
  port: 4054
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: _247 |11.03Mb
  server: 140.238.2.250
  type: vmess
  port: 443
  uuid: 41a7089a-040b-4538-8b8d-010902405bde
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _250 |23.58Mb
  server: 160.16.117.182
  type: trojan
  port: 3093
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: _246 |11.61Mb
  server: 130.162.152.253
  type: vmess
  port: 56867
  uuid: 5206bb9f-2cbc-44ac-de2a-471439a23707
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: Relay_-ğŸ‡¸ğŸ‡¬SG_252 |10.95Mb
  server: 160.16.153.13
  type: trojan
  port: 3145
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: _253 |19.96Mb
  server: 153.121.51.29
  type: trojan
  port: 2890
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: _258 |45.99Mb
  server: 160.16.196.59
  type: trojan
  port: 2890
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: _259 |22.46Mb
  server: 202.181.103.235
  type: trojan
  port: 2890
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: _262 |56.75Mb
  server: 160.16.124.55
  type: trojan
  port: 2890
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¸ğŸ‡¬SG_264 |10.98Mb
  server: 160.16.144.208
  type: trojan
  port: 507
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: _261 |55.52Mb
  server: 160.16.214.6
  type: trojan
  port: 2890
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: _265 |11.22Mb
  server: 153.121.53.187
  type: trojan
  port: 3093
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: disney_HK |11.46Mb
  server: 219.78.209.224
  type: trojan
  port: 443
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: Pool__266 |182.29Mb
  server: 70.34.218.149
  type: trojan
  port: 11930
  password: BaeSzHdfJIR13l67
  sni: softpillow.silentrocket.click
- name: ğŸ‡ªğŸ‡¸ES_267 |228.69Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 27092
  uuid: a0596ba6-72a3-4366-8992-77088da65bd8
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_HK |18.76Mb
  server: 112.118.116.127
  type: trojan
  port: 443
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: ğŸ‡ºğŸ‡¸US_281 |12.86Mb
  server: 47.253.197.26
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 12056
  uuid: dd7be7f1-38ff-45e6-f1e5-b20c2190f527
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: netflix_NL |106.77Mb
  server: 82.38.31.194
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_269 |103.93Mb
  server: 82.38.31.217
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: netflix_NL |93.87Mb
  server: 82.38.31.191
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: disney_HK |17.43Mb
  server: 45.207.157.29
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 13852
  uuid: 845764df-ecb3-4b13-bed2-bf1551b68e9a
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_US |12.81Mb
  server: cf.fovi.tk
  type: vmess
  country: ğŸZZ
  port: 443
  uuid: bf67437e-6c90-45ca-abc2-c7240a5ce2aa
  alterId: 0
  cipher: auto
  network: ws
  servername: foxpol.fovi.tk
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /eisasqa
    headers:
      HOST: foxpol.fovi.tk
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - disney_netflix_US |39.85Mb
  - disney_netflix_US |35.37Mb
  - _199 |186.06Mb
  - _204 |28.04Mb
  - _188 |11.83Mb
  - _193 |155.54Mb
  - _213 |22.68Mb
  - disney_MD |203.59Mb
  - _223 |16.11Mb
  - _218 |11.69Mb
  - disney_SG |11.56Mb
  - Relay_-ğŸ‡§ğŸ‡·BR_189 |73.02Mb
  - Relay_-ğŸ‡­ğŸ‡°HK_219 |17.20Mb
  - _222 |37.98Mb
  - _243 |10.35Mb
  - _245 |10.38Mb
  - _231 |24.92Mb
  - _244 |19.15Mb
  - _255 |159.41Mb
  - _249 |11.29Mb
  - _247 |11.03Mb
  - _250 |23.58Mb
  - _246 |11.61Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_252 |10.95Mb
  - _253 |19.96Mb
  - _258 |45.99Mb
  - _259 |22.46Mb
  - _262 |56.75Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_264 |10.98Mb
  - _261 |55.52Mb
  - _265 |11.22Mb
  - disney_HK |11.46Mb
  - Pool__266 |182.29Mb
  - ğŸ‡ªğŸ‡¸ES_267 |228.69Mb
  - disney_HK |18.76Mb
  - ğŸ‡ºğŸ‡¸US_281 |12.86Mb
  - netflix_NL |106.77Mb
  - ğŸ‡¬ğŸ‡§GB_269 |103.93Mb
  - netflix_NL |93.87Mb
  - disney_HK |17.43Mb
  - disney_US |12.81Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - disney_netflix_US |39.85Mb
  - disney_netflix_US |35.37Mb
  - _199 |186.06Mb
  - _204 |28.04Mb
  - _188 |11.83Mb
  - _193 |155.54Mb
  - _213 |22.68Mb
  - disney_MD |203.59Mb
  - _223 |16.11Mb
  - _218 |11.69Mb
  - disney_SG |11.56Mb
  - Relay_-ğŸ‡§ğŸ‡·BR_189 |73.02Mb
  - Relay_-ğŸ‡­ğŸ‡°HK_219 |17.20Mb
  - _222 |37.98Mb
  - _243 |10.35Mb
  - _245 |10.38Mb
  - _231 |24.92Mb
  - _244 |19.15Mb
  - _255 |159.41Mb
  - _249 |11.29Mb
  - _247 |11.03Mb
  - _250 |23.58Mb
  - _246 |11.61Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_252 |10.95Mb
  - _253 |19.96Mb
  - _258 |45.99Mb
  - _259 |22.46Mb
  - _262 |56.75Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_264 |10.98Mb
  - _261 |55.52Mb
  - _265 |11.22Mb
  - disney_HK |11.46Mb
  - Pool__266 |182.29Mb
  - ğŸ‡ªğŸ‡¸ES_267 |228.69Mb
  - disney_HK |18.76Mb
  - ğŸ‡ºğŸ‡¸US_281 |12.86Mb
  - netflix_NL |106.77Mb
  - ğŸ‡¬ğŸ‡§GB_269 |103.93Mb
  - netflix_NL |93.87Mb
  - disney_HK |17.43Mb
  - disney_US |12.81Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
