port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: disney_netflix_US |15.00Mb
  server: gy3.hdcloud.link
  type: trojan
  port: 443
  udp: true
  password: 9b6419f8-8120-442e-a48c-6bf52aef0abf
  network: grpc
  grpc-opts:
    grpc-service-name: GunService
- name: disney_netflix_NL |244.11Mb
  server: 151.242.251.137
  type: ss
  port: 8080
  password: o5osZg269v5zHpYjr1xY9s
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_NL |18.77Mb
  server: 153.121.73.102
  type: trojan
  port: 2760
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: netflix_ES |12.99Mb
  server: 213.159.67.124
  type: ss
  port: 443
  password: mbhqsStnFQT1cTZYCdsmkugGUC6GT6rp
  cipher: chacha20-ietf-poly1305
- name: disney_MD |589.50Mb
  server: 185.153.197.5
  type: ss
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: netflix_KR |58.95Mb
  server: 152.70.92.69
  type: vmess
  port: 80
  uuid: bb9c3993-a4b9-4dad-aeb9-ac86371ae68b
  alterId: 0
  cipher: auto
  network: http
  http-opts:
    path:
    - /
  h2-opts: {}
- name: disney_HK |27.37Mb
  server: 58.152.25.20
  type: trojan
  port: 443
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: disney_HK |23.39Mb
  server: 58.152.18.192
  type: trojan
  port: 443
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: netflix_MX |39.14Mb
  server: 216.238.89.53
  type: vmess
  country: ğŸ‡²ğŸ‡½MX
  port: 57283
  uuid: 1a5aafc0-6482-451d-fe76-6875b7818579
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_FR |176.13Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 27092
  uuid: a0596ba6-72a3-4366-8992-77088da65bd8
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: netflix_BR |21.02Mb
  server: 38.180.16.86
  type: vmess
  country: ğŸ‡§ğŸ‡·BR
  port: 36104
  uuid: E146A8CB-9D2F-449C-ADCA-8736FB
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_NL |12.28Mb
  server: 82.38.31.179
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: netflix_BR |19.92Mb
  server: 38.180.16.86
  type: vmess
  country: ğŸ‡§ğŸ‡·BR
  port: 36236
  uuid: a58bc1a5-8c18-49ff-9453-c331b52f45dc
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_US |18.09Mb
  server: 74.117.196.232
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 37934
  uuid: 6d600864-32da-49fd-baf4-7df051762454
  alterId: 0
  cipher: auto
  network: ws
  servername: imafake.locker
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /speedtest
    headers:
      HOST: imafake.locker
- name: disney_netflix_US |31.76Mb
  server: 74.117.196.232
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 37934
  uuid: 54a0bf6d-f2b5-4b2a-942c-798fb129527e
  alterId: 0
  cipher: auto
  network: ws
  servername: imafake.locker
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /speedtest
    headers:
      HOST: imafake.locker
- name: ğŸ‡¬ğŸ‡·GR |383.60Mb
  server: 192.71.166.100
  type: ss
  country: ğŸ‡¬ğŸ‡·GR
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: disney_netflix_US |37.69Mb
  server: 74.117.196.232
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 37934
  uuid: f1a513d2-c32a-49dc-8e64-d4f8a2f1e001
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /speedtest
- name: disney_netflix_JP |20.62Mb
  server: f8bfn-g05.jp07-sh-vm0.entry.fr0528.art
  type: vmess
  port: 28787
  udp: true
  uuid: ca78405e-e554-3cd3-9b6d-2ec98e21c8f1
  alterId: 1
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: disney_PY |17.81Mb
  server: 38.165.233.93
  type: ss
  country: ğŸ‡ºğŸ‡¸ US
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: netflix_HK |29.48Mb
  server: 38.54.98.110
  type: vmess
  country: ğŸ‡²ğŸ‡¾MY
  port: 2052
  uuid: 665d9b8f-153d-4907-adac-de12afd9c851
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: Relay_-ğŸ‡°ğŸ‡·KR_194 |50.75Mb
  server: p141.panda001.net
  type: ss
  port: 4652
  udp: true
  password: qwerREWQ@@
  cipher: aes-256-cfb
- name: disney_netflix_US |37.76Mb
  server: sw19.sesamebuta.top
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  uuid: 805ba514-bf2f-4d5d-df49-8417804e8de3
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /abcd
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - disney_netflix_US |15.00Mb
  - disney_netflix_NL |244.11Mb
  - disney_netflix_NL |18.77Mb
  - netflix_ES |12.99Mb
  - disney_MD |589.50Mb
  - netflix_KR |58.95Mb
  - disney_HK |27.37Mb
  - disney_HK |23.39Mb
  - netflix_MX |39.14Mb
  - disney_netflix_FR |176.13Mb
  - netflix_BR |21.02Mb
  - disney_netflix_NL |12.28Mb
  - netflix_BR |19.92Mb
  - disney_netflix_US |18.09Mb
  - disney_netflix_US |31.76Mb
  - ğŸ‡¬ğŸ‡·GR |383.60Mb
  - disney_netflix_US |37.69Mb
  - disney_netflix_JP |20.62Mb
  - disney_PY |17.81Mb
  - netflix_HK |29.48Mb
  - Relay_-ğŸ‡°ğŸ‡·KR_194 |50.75Mb
  - disney_netflix_US |37.76Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - disney_netflix_US |15.00Mb
  - disney_netflix_NL |244.11Mb
  - disney_netflix_NL |18.77Mb
  - netflix_ES |12.99Mb
  - disney_MD |589.50Mb
  - netflix_KR |58.95Mb
  - disney_HK |27.37Mb
  - disney_HK |23.39Mb
  - netflix_MX |39.14Mb
  - disney_netflix_FR |176.13Mb
  - netflix_BR |21.02Mb
  - disney_netflix_NL |12.28Mb
  - netflix_BR |19.92Mb
  - disney_netflix_US |18.09Mb
  - disney_netflix_US |31.76Mb
  - ğŸ‡¬ğŸ‡·GR |383.60Mb
  - disney_netflix_US |37.69Mb
  - disney_netflix_JP |20.62Mb
  - disney_PY |17.81Mb
  - netflix_HK |29.48Mb
  - Relay_-ğŸ‡°ğŸ‡·KR_194 |50.75Mb
  - disney_netflix_US |37.76Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
