port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: Relay_-ğŸ‡³ğŸ‡±NL_288 |259.36Mb
  server: 151.242.251.137
  type: ss
  port: 8080
  password: o5osZg269v5zHpYjr1xY9s
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_PT |390.50Mb
  server: 185.231.233.112
  type: ss
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: disney_HK |24.04Mb
  server: m.cnmjin.net
  type: vmess
  port: 16632
  udp: true
  uuid: 77439561-dcef-4e45-803a-743cfa7d20c2
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /
    headers:
      Host: 9e97d6c9e2e0ad3444cbf96d3709366d.mobgslb.tbcache.com
- name: disney_SG |10.43Mb
  server: m.cnmjin.net
  type: vmess
  port: 16618
  udp: true
  uuid: 77439561-dcef-4e45-803a-743cfa7d20c2
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /
    headers:
      Host: 9e97d6c9e2e0ad3444cbf96d3709366d.mobgslb.tbcache.com
- name: disney_HK |23.79Mb
  server: m.cnmjin.net
  type: vmess
  port: 16622
  udp: true
  uuid: 77439561-dcef-4e45-803a-743cfa7d20c2
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /
    headers:
      Host: 9e97d6c9e2e0ad3444cbf96d3709366d.mobgslb.tbcache.com
- name: Relay_-ğŸ‡¯ğŸ‡µJP_309 |11.45Mb
  server: m.cnmjin.net
  type: vmess
  port: 16617
  udp: true
  uuid: 77439561-dcef-4e45-803a-743cfa7d20c2
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /
    headers:
      Host: 9e97d6c9e2e0ad3444cbf96d3709366d.mobgslb.tbcache.com
- name: Relay_-ğŸ‡®ğŸ‡³IN_300 |26.96Mb
  server: planb.mojcn.com
  type: vmess
  port: 16626
  udp: true
  uuid: 77439561-dcef-4e45-803a-743cfa7d20c2
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /
    headers:
      Host: 9e97d6c9e2e0ad3444cbf96d3709366d.mobgslb.tbcache.com
- name: Relay_-ğŸ‡¹ğŸ‡¼TW_328 |21.40Mb
  server: planb.mojcn.com
  type: vmess
  port: 16616
  udp: true
  uuid: 77439561-dcef-4e45-803a-743cfa7d20c2
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /
    headers:
      Host: 9e97d6c9e2e0ad3444cbf96d3709366d.mobgslb.tbcache.com
- name: disney_SG |10.40Mb
  server: planb.mojcn.com
  type: vmess
  port: 16618
  udp: true
  uuid: 77439561-dcef-4e45-803a-743cfa7d20c2
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /
    headers:
      Host: 9e97d6c9e2e0ad3444cbf96d3709366d.mobgslb.tbcache.com
- name: disney_HK |24.01Mb
  server: planb.mojcn.com
  type: vmess
  port: 16622
  udp: true
  uuid: 77439561-dcef-4e45-803a-743cfa7d20c2
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /
    headers:
      Host: 9e97d6c9e2e0ad3444cbf96d3709366d.mobgslb.tbcache.com
- name: disney_HK |24.27Mb
  server: planb.mojcn.com
  type: vmess
  port: 16632
  udp: true
  uuid: 77439561-dcef-4e45-803a-743cfa7d20c2
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /
    headers:
      Host: 9e97d6c9e2e0ad3444cbf96d3709366d.mobgslb.tbcache.com
- name: disney_netflix_US |50.11Mb
  server: us19-25.998998.best
  type: vmess
  port: 443
  udp: true
  uuid: b376015d-77d9-4482-9aa9-051be76aac65
  alterId: 0
  cipher: auto
  network: ws
  servername: b376015d-77d9-4482-9aa9-051be76aac65.mihomo.baby
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /saoihgreg9384gh8934
    headers:
      Host: b376015d-77d9-4482-9aa9-051be76aac65.mihomo.baby
- name: Relay_-ğŸ‡³ğŸ‡±NL_351 |16.05Mb
  server: 160.16.124.55
  type: trojan
  port: 2760
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¯ğŸ‡µJP_348 |11.59Mb
  server: 52.195.176.26
  type: trojan
  port: 2145
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: Relay_-ğŸ‡¯ğŸ‡µJP_355 |13.60Mb
  server: 160.16.236.32
  type: trojan
  port: 3093
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¯ğŸ‡µJP_337 |11.28Mb
  server: planb.mojcn.com
  type: vmess
  port: 16617
  udp: true
  uuid: 77439561-dcef-4e45-803a-743cfa7d20c2
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /
    headers:
      Host: 9e97d6c9e2e0ad3444cbf96d3709366d.mobgslb.tbcache.com
- name: Relay_-ğŸ‡¹ğŸ‡¼TW_343 |24.07Mb
  server: m.cnmjin.net
  type: vmess
  port: 16616
  udp: true
  uuid: 77439561-dcef-4e45-803a-743cfa7d20c2
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /
    headers:
      Host: 9e97d6c9e2e0ad3444cbf96d3709366d.mobgslb.tbcache.com
- name: disney_HK |29.17Mb
  server: 58.152.25.20
  type: trojan
  port: 443
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: disney_SG |10.79Mb
  server: t.cnmjcn.cyou
  type: vmess
  port: 16618
  udp: true
  uuid: 77439561-dcef-4e45-803a-743cfa7d20c2
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /
    headers:
      Host: 9e97d6c9e2e0ad3444cbf96d3709366d.mobgslb.tbcache.com
- name: disney_HK |10.44Mb
  server: t.cnmjcn.cyou
  type: vmess
  port: 16622
  udp: true
  uuid: 77439561-dcef-4e45-803a-743cfa7d20c2
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /
    headers:
      Host: 9e97d6c9e2e0ad3444cbf96d3709366d.mobgslb.tbcache.com
- name: disney_HK |10.52Mb
  server: t.cnmjcn.cyou
  type: vmess
  port: 16632
  udp: true
  uuid: 77439561-dcef-4e45-803a-743cfa7d20c2
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /
    headers:
      Host: 9e97d6c9e2e0ad3444cbf96d3709366d.mobgslb.tbcache.com
- name: disney_netflix_FR |188.92Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 27092
  uuid: a0596ba6-72a3-4366-8992-77088da65bd8
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_HK |23.99Mb
  server: 58.152.18.95
  type: trojan
  port: 443
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: ğŸ‡²ğŸ‡½MX_378 |172.99Mb
  server: 216.238.89.53
  type: vmess
  country: ğŸ‡²ğŸ‡½MX
  port: 57283
  uuid: 1a5aafc0-6482-451d-fe76-6875b7818579
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: netflix_NL |222.15Mb
  server: 82.38.31.190
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡§ğŸ‡·BR_361 |11.29Mb
  server: 38.180.16.86
  type: vmess
  country: ğŸ‡§ğŸ‡·BR
  port: 36104
  uuid: E146A8CB-9D2F-449C-ADCA-8736FB
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡±ğŸ‡¹LT_377 |63.97Mb
  server: 45.87.175.166
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 443
  password: 1RWwXhwfAB5gAEozU4G2Pg
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_US |24.05Mb
  server: 38.84.201.21
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 53487
  uuid: c3c1ec05-df2c-4975-9b42-e9b007564eb1
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡­ğŸ‡°HK_371 |19.35Mb
  server: 47.242.125.104
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 58424
  uuid: 80016399-3178-472e-86e3-129aab31a025
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
  ws-opts:
    path: /arki?ed=2048
- name: ğŸ‡°ğŸ‡·KR_376 |10.08Mb
  server: 146.56.112.110
  type: vmess
  country: ğŸ‡°ğŸ‡·KR
  port: 8888
  uuid: e7c302f3-90d6-42dd-9d7d-94a3683a3707
  alterId: 0
  cipher: auto
  network: tcp
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: netflix_AL |43.91Mb
  server: 87.121.162.249
  type: ss
  country: ğŸ‡­ğŸ‡°HK
  port: 443
  password: JGv616hMWdjfuZ00jYfq7XkBHJZrOBrg
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_US |55.10Mb
  server: 100.25.219.192
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡®ğŸ‡±IL_375 |62.62Mb
  server: 45.93.95.187
  type: ss
  country: ğŸ‡®ğŸ‡±IL
  port: 8618
  password: 4lUEC91c1d8oeClzDbYpXA
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_388 |13.66Mb
  server: 45.136.12.37
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 38141
  uuid: fd291be6-b48d-43a1-da38-66c7f80e2f80
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡²ğŸ‡¾MY_379 |29.95Mb
  server: 38.54.98.110
  type: vmess
  country: ğŸ‡²ğŸ‡¾MY
  port: 2052
  uuid: 665d9b8f-153d-4907-adac-de12afd9c851
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: disney_TR |31.10Mb
  server: tr-1.stunnel.cc
  type: ss
  country: ğŸ‡¹ğŸ‡·TR
  port: 8444
  password: tunnel-fbrof
  cipher: chacha20-ietf-poly1305
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - Relay_-ğŸ‡³ğŸ‡±NL_288 |259.36Mb
  - disney_netflix_PT |390.50Mb
  - disney_HK |24.04Mb
  - disney_SG |10.43Mb
  - disney_HK |23.79Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_309 |11.45Mb
  - Relay_-ğŸ‡®ğŸ‡³IN_300 |26.96Mb
  - Relay_-ğŸ‡¹ğŸ‡¼TW_328 |21.40Mb
  - disney_SG |10.40Mb
  - disney_HK |24.01Mb
  - disney_HK |24.27Mb
  - disney_netflix_US |50.11Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_351 |16.05Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_348 |11.59Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_355 |13.60Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_337 |11.28Mb
  - Relay_-ğŸ‡¹ğŸ‡¼TW_343 |24.07Mb
  - disney_HK |29.17Mb
  - disney_SG |10.79Mb
  - disney_HK |10.44Mb
  - disney_HK |10.52Mb
  - disney_netflix_FR |188.92Mb
  - disney_HK |23.99Mb
  - ğŸ‡²ğŸ‡½MX_378 |172.99Mb
  - netflix_NL |222.15Mb
  - ğŸ‡§ğŸ‡·BR_361 |11.29Mb
  - ğŸ‡±ğŸ‡¹LT_377 |63.97Mb
  - disney_netflix_US |24.05Mb
  - ğŸ‡­ğŸ‡°HK_371 |19.35Mb
  - ğŸ‡°ğŸ‡·KR_376 |10.08Mb
  - netflix_AL |43.91Mb
  - disney_netflix_US |55.10Mb
  - ğŸ‡®ğŸ‡±IL_375 |62.62Mb
  - ğŸ‡ºğŸ‡¸US_388 |13.66Mb
  - ğŸ‡²ğŸ‡¾MY_379 |29.95Mb
  - disney_TR |31.10Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - Relay_-ğŸ‡³ğŸ‡±NL_288 |259.36Mb
  - disney_netflix_PT |390.50Mb
  - disney_HK |24.04Mb
  - disney_SG |10.43Mb
  - disney_HK |23.79Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_309 |11.45Mb
  - Relay_-ğŸ‡®ğŸ‡³IN_300 |26.96Mb
  - Relay_-ğŸ‡¹ğŸ‡¼TW_328 |21.40Mb
  - disney_SG |10.40Mb
  - disney_HK |24.01Mb
  - disney_HK |24.27Mb
  - disney_netflix_US |50.11Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_351 |16.05Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_348 |11.59Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_355 |13.60Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_337 |11.28Mb
  - Relay_-ğŸ‡¹ğŸ‡¼TW_343 |24.07Mb
  - disney_HK |29.17Mb
  - disney_SG |10.79Mb
  - disney_HK |10.44Mb
  - disney_HK |10.52Mb
  - disney_netflix_FR |188.92Mb
  - disney_HK |23.99Mb
  - ğŸ‡²ğŸ‡½MX_378 |172.99Mb
  - netflix_NL |222.15Mb
  - ğŸ‡§ğŸ‡·BR_361 |11.29Mb
  - ğŸ‡±ğŸ‡¹LT_377 |63.97Mb
  - disney_netflix_US |24.05Mb
  - ğŸ‡­ğŸ‡°HK_371 |19.35Mb
  - ğŸ‡°ğŸ‡·KR_376 |10.08Mb
  - netflix_AL |43.91Mb
  - disney_netflix_US |55.10Mb
  - ğŸ‡®ğŸ‡±IL_375 |62.62Mb
  - ğŸ‡ºğŸ‡¸US_388 |13.66Mb
  - ğŸ‡²ğŸ‡¾MY_379 |29.95Mb
  - disney_TR |31.10Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
