port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: netflix_NL |259.36Mb
  server: 151.242.251.137
  type: ss
  port: 8080
  password: o5osZg269v5zHpYjr1xY9s
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_PT |390.50Mb
  server: 185.231.233.112
  type: ss
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: Relay_-ğŸ‡¹ğŸ‡¼TW_313 |24.07Mb
  server: m.cnmjin.net
  type: vmess
  port: 16616
  udp: true
  uuid: 77439561-dcef-4e45-803a-743cfa7d20c2
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /
    headers:
      Host: 9e97d6c9e2e0ad3444cbf96d3709366d.mobgslb.tbcache.com
- name: Relay_-ğŸ‡¯ğŸ‡µJP_312 |11.45Mb
  server: m.cnmjin.net
  type: vmess
  port: 16617
  udp: true
  uuid: 77439561-dcef-4e45-803a-743cfa7d20c2
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /
    headers:
      Host: 9e97d6c9e2e0ad3444cbf96d3709366d.mobgslb.tbcache.com
- name: disney_HK |24.04Mb
  server: m.cnmjin.net
  type: vmess
  port: 16632
  udp: true
  uuid: 77439561-dcef-4e45-803a-743cfa7d20c2
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /
    headers:
      Host: 9e97d6c9e2e0ad3444cbf96d3709366d.mobgslb.tbcache.com
- name: disney_HK |23.79Mb
  server: m.cnmjin.net
  type: vmess
  port: 16622
  udp: true
  uuid: 77439561-dcef-4e45-803a-743cfa7d20c2
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /
    headers:
      Host: 9e97d6c9e2e0ad3444cbf96d3709366d.mobgslb.tbcache.com
- name: Relay_-ğŸ‡­ğŸ‡°HK_300 |10.44Mb
  server: t.cnmjcn.cyou
  type: vmess
  port: 16622
  udp: true
  uuid: 77439561-dcef-4e45-803a-743cfa7d20c2
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /
    headers:
      Host: 9e97d6c9e2e0ad3444cbf96d3709366d.mobgslb.tbcache.com
- name: Relay_-ğŸ‡­ğŸ‡°HK_301 |10.52Mb
  server: t.cnmjcn.cyou
  type: vmess
  port: 16632
  udp: true
  uuid: 77439561-dcef-4e45-803a-743cfa7d20c2
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /
    headers:
      Host: 9e97d6c9e2e0ad3444cbf96d3709366d.mobgslb.tbcache.com
- name: Relay_-ğŸ‡¸ğŸ‡¬SG_302 |10.79Mb
  server: t.cnmjcn.cyou
  type: vmess
  port: 16618
  udp: true
  uuid: 77439561-dcef-4e45-803a-743cfa7d20c2
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /
    headers:
      Host: 9e97d6c9e2e0ad3444cbf96d3709366d.mobgslb.tbcache.com
- name: disney_HK |24.27Mb
  server: planb.mojcn.com
  type: vmess
  port: 16632
  udp: true
  uuid: 77439561-dcef-4e45-803a-743cfa7d20c2
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /
    headers:
      Host: 9e97d6c9e2e0ad3444cbf96d3709366d.mobgslb.tbcache.com
- name: Relay_-ğŸ‡¯ğŸ‡µJP_309 |11.28Mb
  server: planb.mojcn.com
  type: vmess
  port: 16617
  udp: true
  uuid: 77439561-dcef-4e45-803a-743cfa7d20c2
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /
    headers:
      Host: 9e97d6c9e2e0ad3444cbf96d3709366d.mobgslb.tbcache.com
- name: Relay_-ğŸ‡¹ğŸ‡¼TW_308 |21.40Mb
  server: planb.mojcn.com
  type: vmess
  port: 16616
  udp: true
  uuid: 77439561-dcef-4e45-803a-743cfa7d20c2
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /
    headers:
      Host: 9e97d6c9e2e0ad3444cbf96d3709366d.mobgslb.tbcache.com
- name: disney_HK |24.01Mb
  server: planb.mojcn.com
  type: vmess
  port: 16622
  udp: true
  uuid: 77439561-dcef-4e45-803a-743cfa7d20c2
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /
    headers:
      Host: 9e97d6c9e2e0ad3444cbf96d3709366d.mobgslb.tbcache.com
- name: disney_SG |10.40Mb
  server: planb.mojcn.com
  type: vmess
  port: 16618
  udp: true
  uuid: 77439561-dcef-4e45-803a-743cfa7d20c2
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /
    headers:
      Host: 9e97d6c9e2e0ad3444cbf96d3709366d.mobgslb.tbcache.com
- name: Relay_-ğŸ‡®ğŸ‡³IN_298 |26.96Mb
  server: planb.mojcn.com
  type: vmess
  port: 16626
  udp: true
  uuid: 77439561-dcef-4e45-803a-743cfa7d20c2
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /
    headers:
      Host: 9e97d6c9e2e0ad3444cbf96d3709366d.mobgslb.tbcache.com
- name: Relay_-ğŸ‡¯ğŸ‡µJP_326 |13.60Mb
  server: 160.16.236.32
  type: trojan
  port: 3093
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¯ğŸ‡µJP_328 |19.55Mb
  server: 160.16.138.24
  type: trojan
  port: 1331
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: disney_netflix_SG |10.43Mb
  server: m.cnmjin.net
  type: vmess
  port: 16618
  udp: true
  uuid: 77439561-dcef-4e45-803a-743cfa7d20c2
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /
    headers:
      Host: 9e97d6c9e2e0ad3444cbf96d3709366d.mobgslb.tbcache.com
- name: disney_netflix_US |50.11Mb
  server: us19-25.998998.best
  type: vmess
  port: 443
  udp: true
  uuid: b376015d-77d9-4482-9aa9-051be76aac65
  alterId: 0
  cipher: auto
  network: ws
  servername: b376015d-77d9-4482-9aa9-051be76aac65.mihomo.baby
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /saoihgreg9384gh8934
    headers:
      Host: b376015d-77d9-4482-9aa9-051be76aac65.mihomo.baby
- name: Relay_-ğŸ‡³ğŸ‡±NL_331 |16.05Mb
  server: 160.16.124.55
  type: trojan
  port: 2760
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¯ğŸ‡µJP_335 |11.59Mb
  server: 52.195.176.26
  type: trojan
  port: 2145
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: disney_netflix_FR |188.92Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 27092
  uuid: a0596ba6-72a3-4366-8992-77088da65bd8
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡§ğŸ‡·BR_338 |11.29Mb
  server: 38.180.16.86
  type: vmess
  country: ğŸ‡§ğŸ‡·BR
  port: 36104
  uuid: E146A8CB-9D2F-449C-ADCA-8736FB
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: netflix_NL |222.15Mb
  server: 82.38.31.190
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: netflix_MX |172.99Mb
  server: 216.238.89.53
  type: vmess
  country: ğŸ‡²ğŸ‡½MX
  port: 57283
  uuid: 1a5aafc0-6482-451d-fe76-6875b7818579
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_HK |29.17Mb
  server: 58.152.25.20
  type: trojan
  port: 443
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: disney_HK |23.99Mb
  server: 58.152.18.95
  type: trojan
  port: 443
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: netflix_AL |43.91Mb
  server: 87.121.162.249
  type: ss
  country: ğŸ‡­ğŸ‡°HK
  port: 443
  password: JGv616hMWdjfuZ00jYfq7XkBHJZrOBrg
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡­ğŸ‡°HK_345 |19.35Mb
  server: 47.242.125.104
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 58424
  uuid: 80016399-3178-472e-86e3-129aab31a025
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
  ws-opts:
    path: /arki?ed=2048
- name: disney_netflix_US |55.10Mb
  server: 100.25.219.192
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡ºğŸ‡¸US_364 |12.01Mb
  server: 74.117.196.232
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 37934
  uuid: f1a513d2-c32a-49dc-8e64-d4f8a2f1e001
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /speedtest
- name: disney_netflix_US |10.46Mb
  server: 74.117.196.232
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 37934
  uuid: e1cc26b3-df0b-477b-afb0-53659a25e978
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /speedtest
- name: netflix_IL |62.62Mb
  server: 45.93.95.187
  type: ss
  country: ğŸ‡®ğŸ‡±IL
  port: 8618
  password: 4lUEC91c1d8oeClzDbYpXA
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_US |24.05Mb
  server: 38.84.201.21
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 53487
  uuid: c3c1ec05-df2c-4975-9b42-e9b007564eb1
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_US |22.51Mb
  server: 74.117.196.232
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 37934
  uuid: b2da9920-b0a7-4354-9e26-3833ab8d00d0
  alterId: 0
  cipher: auto
  network: ws
  servername: imafake.locker
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /speedtest
    headers:
      HOST: imafake.locker
- name: netflix_NL |20.64Mb
  server: 109.71.246.210
  type: ss
  country: ğŸ‡·ğŸ‡ºRU
  port: 56689
  password: YQCSKoCF3QazW8YlvDBWA4
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_US |14.03Mb
  server: 74.117.196.232
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 37934
  uuid: c50f9480-2e1d-40db-9458-630e79636663
  alterId: 0
  cipher: auto
  network: ws
  servername: imafake.locker
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /speedtest
    headers:
      HOST: imafake.locker
- name: ğŸ‡²ğŸ‡¾MY_355 |29.95Mb
  server: 38.54.98.110
  type: vmess
  country: ğŸ‡²ğŸ‡¾MY
  port: 2052
  uuid: 665d9b8f-153d-4907-adac-de12afd9c851
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: ğŸ‡¸ğŸ‡¬SG_357 |11.05Mb
  server: 68.183.178.131
  type: vmess
  country: ğŸ‡¸ğŸ‡¬SG
  port: 58607
  uuid: c11c32cb-27b3-4afa-c0f3-fb250aa4959e
  alterId: 0
  cipher: auto
  network: ws
  servername: www.12333.monster
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /
    headers:
      HOST: www.12333.monster
- name: disney_netflix_TR |31.10Mb
  server: tr-1.stunnel.cc
  type: ss
  country: ğŸ‡¹ğŸ‡·TR
  port: 8444
  password: tunnel-fbrof
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_360 |61.77Mb
  server: pupas-shirting-unsung.freesocks.work
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: p78naCf2EfOlRSLTX0wFVx
  cipher: chacha20-ietf-poly1305
- name: disney_HK |13.66Mb
  server: 45.136.12.37
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 38141
  uuid: fd291be6-b48d-43a1-da38-66c7f80e2f80
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - netflix_NL |259.36Mb
  - disney_netflix_PT |390.50Mb
  - Relay_-ğŸ‡¹ğŸ‡¼TW_313 |24.07Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_312 |11.45Mb
  - disney_HK |24.04Mb
  - disney_HK |23.79Mb
  - Relay_-ğŸ‡­ğŸ‡°HK_300 |10.44Mb
  - Relay_-ğŸ‡­ğŸ‡°HK_301 |10.52Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_302 |10.79Mb
  - disney_HK |24.27Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_309 |11.28Mb
  - Relay_-ğŸ‡¹ğŸ‡¼TW_308 |21.40Mb
  - disney_HK |24.01Mb
  - disney_SG |10.40Mb
  - Relay_-ğŸ‡®ğŸ‡³IN_298 |26.96Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_326 |13.60Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_328 |19.55Mb
  - disney_netflix_SG |10.43Mb
  - disney_netflix_US |50.11Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_331 |16.05Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_335 |11.59Mb
  - disney_netflix_FR |188.92Mb
  - ğŸ‡§ğŸ‡·BR_338 |11.29Mb
  - netflix_NL |222.15Mb
  - netflix_MX |172.99Mb
  - disney_HK |29.17Mb
  - disney_HK |23.99Mb
  - netflix_AL |43.91Mb
  - ğŸ‡­ğŸ‡°HK_345 |19.35Mb
  - disney_netflix_US |55.10Mb
  - ğŸ‡ºğŸ‡¸US_364 |12.01Mb
  - disney_netflix_US |10.46Mb
  - netflix_IL |62.62Mb
  - disney_netflix_US |24.05Mb
  - disney_netflix_US |22.51Mb
  - netflix_NL |20.64Mb
  - disney_netflix_US |14.03Mb
  - ğŸ‡²ğŸ‡¾MY_355 |29.95Mb
  - ğŸ‡¸ğŸ‡¬SG_357 |11.05Mb
  - disney_netflix_TR |31.10Mb
  - ğŸ‡ºğŸ‡¸US_360 |61.77Mb
  - disney_HK |13.66Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - netflix_NL |259.36Mb
  - disney_netflix_PT |390.50Mb
  - Relay_-ğŸ‡¹ğŸ‡¼TW_313 |24.07Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_312 |11.45Mb
  - disney_HK |24.04Mb
  - disney_HK |23.79Mb
  - Relay_-ğŸ‡­ğŸ‡°HK_300 |10.44Mb
  - Relay_-ğŸ‡­ğŸ‡°HK_301 |10.52Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_302 |10.79Mb
  - disney_HK |24.27Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_309 |11.28Mb
  - Relay_-ğŸ‡¹ğŸ‡¼TW_308 |21.40Mb
  - disney_HK |24.01Mb
  - disney_SG |10.40Mb
  - Relay_-ğŸ‡®ğŸ‡³IN_298 |26.96Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_326 |13.60Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_328 |19.55Mb
  - disney_netflix_SG |10.43Mb
  - disney_netflix_US |50.11Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_331 |16.05Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_335 |11.59Mb
  - disney_netflix_FR |188.92Mb
  - ğŸ‡§ğŸ‡·BR_338 |11.29Mb
  - netflix_NL |222.15Mb
  - netflix_MX |172.99Mb
  - disney_HK |29.17Mb
  - disney_HK |23.99Mb
  - netflix_AL |43.91Mb
  - ğŸ‡­ğŸ‡°HK_345 |19.35Mb
  - disney_netflix_US |55.10Mb
  - ğŸ‡ºğŸ‡¸US_364 |12.01Mb
  - disney_netflix_US |10.46Mb
  - netflix_IL |62.62Mb
  - disney_netflix_US |24.05Mb
  - disney_netflix_US |22.51Mb
  - netflix_NL |20.64Mb
  - disney_netflix_US |14.03Mb
  - ğŸ‡²ğŸ‡¾MY_355 |29.95Mb
  - ğŸ‡¸ğŸ‡¬SG_357 |11.05Mb
  - disney_netflix_TR |31.10Mb
  - ğŸ‡ºğŸ‡¸US_360 |61.77Mb
  - disney_HK |13.66Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
