port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: _152 |13.82Mb
  server: 15.235.41.200
  type: vmess
  port: 80
  uuid: 58fe1542-5290-40ad-815a-77707a81afe5
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /IOebhLMhl1CTbFHbL95myfRX2
- name: _238 |42.28Mb
  server: 163.192.49.195
  type: vmess
  port: 443
  uuid: bcb7c581-3c95-4569-a4e7-918141e91ea3
  alterId: 0
  cipher: auto
  network: http
  http-opts:
    path:
    - /
    headers:
      Host:
      - a.189.cn
  h2-opts: {}
- name: ' |58.14Mb'
  server: 45.150.52.40
  type: vmess
  port: 443
  uuid: c31777a1-2ee6-4864-db4c-a79fcbc8188b
  alterId: 0
  cipher: auto
  network: ws
  servername: xsj011-3.facai2024.com
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /c31777a1
- name: ' |159.03Mb'
  server: 82.198.246.97
  type: vmess
  port: 180
  udp: true
  uuid: d13fc2f5-3e05-4795-81eb-44143a09e552
  alterId: 0
  cipher: auto
  servername: 82.198.246.97
  http-opts: {}
  h2-opts: {}
- name: _154 |35.61Mb
  server: 51.79.102.253
  type: vmess
  port: 80
  uuid: 58fe1542-5290-40ad-815a-77707a81afe5
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /IOebhLMhl1CTbFHbL95myfRX2
    headers:
      Host: wrmelmwxlf.gktevlrqznwqqozy.fabpfs66gizmnojhcvqxwl.kytrcfzqla87gvgvs6c7kjnrubuh.cc
- name: _146 |201.74Mb
  server: 85.195.101.122
  type: vmess
  port: 40878
  uuid: f3d4167e-b15e-4e46-82e9-9286ef93fda7
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _149 |221.17Mb
  server: 91.99.27.55
  type: vmess
  port: 8880
  uuid: f3025961-167b-4f49-e4e3-86505fe980fd
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _143 |11.79Mb
  server: 107.174.114.71
  type: ss
  port: 443
  password: 595HLF3fHUuw0McM51tpvPygSIB1uf4D
  cipher: chacha20-ietf-poly1305
- name: _221 |183.69Mb
  server: 172.235.33.114
  type: vmess
  port: 10001
  uuid: 442a3923-eca1-4af0-b3ff-24a7ce0af68f
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: Pool__203 |42.33Mb
  server: 165.140.216.141
  type: vmess
  port: 443
  uuid: e7d72a8d-26f2-4b54-b366-0c43e0bcba7d
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: Relay_-ðŸ‡­ðŸ‡°HK_155 |22.99Mb
  server: www.zhoubowen.vip
  type: vmess
  port: 443
  uuid: 71b2655e-07d9-4dad-a770-a2b08275142b
  alterId: 0
  cipher: auto
  network: ws
  servername: www.zhoubowen.vip
  http-opts: {}
  h2-opts: {}
  tls: true
  ws-opts:
    path: /biutefor.icu
    headers:
      Host: www.zhoubowen.vip
- name: Relay_-ðŸ‡©ðŸ‡ªDE_256 |202.38Mb
  server: koma-yt.pages.dev
  type: trojan
  port: 8443
  udp: true
  password: 8r<[9'l6hAO#8ZQi
  sni: Koma-YT.PAGeS.Dev
  ws-opts:
    path: /tro8sFW1S91B6sZrM1?ed=2560
    headers:
      Host: Koma-YT.PAGeS.Dev
  network: ws
- name: _166 |17.06Mb
  server: 165.154.195.38
  type: vmess
  port: 35034
  uuid: 959a8caf-4cea-43d0-a548-3628e7ddfafc
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _138 |31.48Mb
  server: 209.74.82.196
  type: ss
  port: 48918
  udp: true
  password: 8Ij4seif85QQHfLmR0zYkQ
  cipher: chacha20-ietf-poly1305
- name: _137 |27.40Mb
  server: 209.74.82.227
  type: ss
  port: 26515
  udp: true
  password: uA1rLP5m0mMOQ8FcxRXxgr
  cipher: chacha20-ietf-poly1305
- name: _148 |39.09Mb
  server: 89.31.120.192
  type: vmess
  port: 443
  uuid: 44537595-9ccc-4b83-8936-5f9ad3229019
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _158 |11.06Mb
  server: 103.127.218.91
  type: vmess
  port: 54693
  uuid: 1cef03ad-6343-408c-8121-cbd1fda2ee9d
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /1cef03ad
- name: _218 |10.65Mb
  server: 54.206.192.9
  type: vmess
  port: 16407
  uuid: 08f45028-1db6-4e93-bf51-d344b6c71e19
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _180 |26.45Mb
  server: 8.218.105.196
  type: vmess
  port: 52752
  uuid: 925bdbf5-72be-4437-bebf-441c61089f6b
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
- name: _260 |30.10Mb
  server: 160.16.223.205
  type: trojan
  port: 4054
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: Relay_-ðŸ‡­ðŸ‡°HK_162 |18.98Mb
  server: 154.21.201.83
  type: vmess
  port: 443
  uuid: 4bf075f5-4d5e-4d39-f5ab-b32a86250f0e
  alterId: 0
  cipher: auto
  network: ws
  servername: hk.nbee.pp.ua
  http-opts: {}
  h2-opts: {}
  tls: true
  ws-opts:
    path: /aa
    headers:
      Host: hk.nbee.pp.ua
- name: _266 |46.32Mb
  server: 160.16.124.55
  type: trojan
  port: 2890
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: Relay_-ðŸ‡¯ðŸ‡µJP_273 |12.31Mb
  server: 153.121.67.215
  type: trojan
  port: 1331
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: Relay_-ðŸ‡¯ðŸ‡µJP_274 |20.21Mb
  server: 13.112.81.124
  type: trojan
  port: 3169
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: _255 |20.05Mb
  server: 160.16.117.182
  type: trojan
  port: 3093
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: Pool__269 |186.71Mb
  server: 70.34.218.149
  type: trojan
  port: 11930
  password: BaeSzHdfJIR13l67
  sni: softpillow.silentrocket.click
- name: Relay_-ðŸ‡³ðŸ‡±NL_277 |44.68Mb
  server: 202.181.103.235
  type: trojan
  port: 2890
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: _272 |24.72Mb
  server: 38.96.254.102
  type: trojan
  port: 18509
  password: .ie4rghJuMkcf0oF
  sni: shoppingmall.electricbanana.click
- name: ðŸ‡ªðŸ‡¸ES_279 |23.55Mb
  server: 208.76.223.218
  type: vmess
  country: ðŸ‡ªðŸ‡¸ES
  port: 40433
  uuid: d8fd8955-78db-49ba-d86f-3e4729f6ac4d
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ðŸ‡¬ðŸ‡§GB_280 |301.75Mb
  server: 51.15.17.169
  type: ss
  country: ðŸ‡¬ðŸ‡§GB
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ðŸ‡¬ðŸ‡§GB_281 |188.62Mb
  server: 82.38.31.184
  type: ss
  country: ðŸ‡¬ðŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: Pool_ðŸ‡®ðŸ‡ªIE_307 |94.31Mb
  server: 146.70.90.196
  type: ss
  country: ðŸ‡®ðŸ‡ªIE
  port: 17454
  password: u8gp148iz90ddoo6ms37
  cipher: aes-128-gcm
- name: _153 |57.57Mb
  server: 154.201.76.172
  type: vmess
  port: 20990
  uuid: ba50e1fe-055f-4587-fd0d-36c8d6615192
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: Relay_-ðŸ‡¯ðŸ‡µJP_259 |19.09Mb
  server: 160.16.229.223
  type: trojan
  port: 3093
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: Relay_-ðŸ‡¯ðŸ‡µJP_261 |20.95Mb
  server: 153.121.73.102
  type: trojan
  port: 1331
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: ðŸ‡ºðŸ‡¸US_312 |35.54Mb
  server: 209.74.86.194
  type: ss
  country: ðŸ‡ºðŸ‡¸US
  port: 14936
  password: ppgtoOHdm7cszGunBWBTqQ
  cipher: chacha20-ietf-poly1305
- name: ðŸ‡·ðŸ‡ºRU_310 |102.17Mb
  server: 109.71.246.210
  type: ss
  country: ðŸ‡·ðŸ‡ºRU
  port: 56689
  password: YQCSKoCF3QazW8YlvDBWA4
  cipher: chacha20-ietf-poly1305
- name: _271 |42.35Mb
  server: 160.16.196.59
  type: trojan
  port: 2890
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: _276 |29.10Mb
  server: 58.152.110.82
  type: trojan
  port: 443
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: ðŸ‡ºðŸ‡¸US_314 |23.92Mb
  server: 45.136.12.37
  type: vmess
  country: ðŸ‡ºðŸ‡¸US
  port: 38141
  uuid: fd291be6-b48d-43a1-da38-66c7f80e2f80
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ðŸ‡ºðŸ‡¸US_313 |28.23Mb
  server: 209.74.81.149
  type: ss
  country: ðŸ‡ºðŸ‡¸US
  port: 21166
  password: q92MrrP9oJ3lMEzbQFpyuU
  cipher: chacha20-ietf-poly1305
- name: Relay_ðŸZZ-ðŸ‡ºðŸ‡¸US_315 |16.87Mb
  server: cf.fovi.tk
  type: vmess
  country: ðŸZZ
  port: 443
  uuid: bf67437e-6c90-45ca-abc2-c7240a5ce2aa
  alterId: 0
  cipher: auto
  network: ws
  servername: foxlux.fovi.tk
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /eisasqa
    headers:
      HOST: foxlux.fovi.tk
proxy-groups:
- name: ðŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - _152 |13.82Mb
  - _238 |42.28Mb
  - ' |58.14Mb'
  - ' |159.03Mb'
  - _154 |35.61Mb
  - _146 |201.74Mb
  - _149 |221.17Mb
  - _143 |11.79Mb
  - _221 |183.69Mb
  - Pool__203 |42.33Mb
  - Relay_-ðŸ‡­ðŸ‡°HK_155 |22.99Mb
  - Relay_-ðŸ‡©ðŸ‡ªDE_256 |202.38Mb
  - _166 |17.06Mb
  - _138 |31.48Mb
  - _137 |27.40Mb
  - _148 |39.09Mb
  - _158 |11.06Mb
  - _218 |10.65Mb
  - _180 |26.45Mb
  - _260 |30.10Mb
  - Relay_-ðŸ‡­ðŸ‡°HK_162 |18.98Mb
  - _266 |46.32Mb
  - Relay_-ðŸ‡¯ðŸ‡µJP_273 |12.31Mb
  - Relay_-ðŸ‡¯ðŸ‡µJP_274 |20.21Mb
  - _255 |20.05Mb
  - Pool__269 |186.71Mb
  - Relay_-ðŸ‡³ðŸ‡±NL_277 |44.68Mb
  - _272 |24.72Mb
  - ðŸ‡ªðŸ‡¸ES_279 |23.55Mb
  - ðŸ‡¬ðŸ‡§GB_280 |301.75Mb
  - ðŸ‡¬ðŸ‡§GB_281 |188.62Mb
  - Pool_ðŸ‡®ðŸ‡ªIE_307 |94.31Mb
  - _153 |57.57Mb
  - Relay_-ðŸ‡¯ðŸ‡µJP_259 |19.09Mb
  - Relay_-ðŸ‡¯ðŸ‡µJP_261 |20.95Mb
  - ðŸ‡ºðŸ‡¸US_312 |35.54Mb
  - ðŸ‡·ðŸ‡ºRU_310 |102.17Mb
  - _271 |42.35Mb
  - _276 |29.10Mb
  - ðŸ‡ºðŸ‡¸US_314 |23.92Mb
  - ðŸ‡ºðŸ‡¸US_313 |28.23Mb
  - Relay_ðŸZZ-ðŸ‡ºðŸ‡¸US_315 |16.87Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - _152 |13.82Mb
  - _238 |42.28Mb
  - ' |58.14Mb'
  - ' |159.03Mb'
  - _154 |35.61Mb
  - _146 |201.74Mb
  - _149 |221.17Mb
  - _143 |11.79Mb
  - _221 |183.69Mb
  - Pool__203 |42.33Mb
  - Relay_-ðŸ‡­ðŸ‡°HK_155 |22.99Mb
  - Relay_-ðŸ‡©ðŸ‡ªDE_256 |202.38Mb
  - _166 |17.06Mb
  - _138 |31.48Mb
  - _137 |27.40Mb
  - _148 |39.09Mb
  - _158 |11.06Mb
  - _218 |10.65Mb
  - _180 |26.45Mb
  - _260 |30.10Mb
  - Relay_-ðŸ‡­ðŸ‡°HK_162 |18.98Mb
  - _266 |46.32Mb
  - Relay_-ðŸ‡¯ðŸ‡µJP_273 |12.31Mb
  - Relay_-ðŸ‡¯ðŸ‡µJP_274 |20.21Mb
  - _255 |20.05Mb
  - Pool__269 |186.71Mb
  - Relay_-ðŸ‡³ðŸ‡±NL_277 |44.68Mb
  - _272 |24.72Mb
  - ðŸ‡ªðŸ‡¸ES_279 |23.55Mb
  - ðŸ‡¬ðŸ‡§GB_280 |301.75Mb
  - ðŸ‡¬ðŸ‡§GB_281 |188.62Mb
  - Pool_ðŸ‡®ðŸ‡ªIE_307 |94.31Mb
  - _153 |57.57Mb
  - Relay_-ðŸ‡¯ðŸ‡µJP_259 |19.09Mb
  - Relay_-ðŸ‡¯ðŸ‡µJP_261 |20.95Mb
  - ðŸ‡ºðŸ‡¸US_312 |35.54Mb
  - ðŸ‡·ðŸ‡ºRU_310 |102.17Mb
  - _271 |42.35Mb
  - _276 |29.10Mb
  - ðŸ‡ºðŸ‡¸US_314 |23.92Mb
  - ðŸ‡ºðŸ‡¸US_313 |28.23Mb
  - Relay_ðŸZZ-ðŸ‡ºðŸ‡¸US_315 |16.87Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ðŸš€ èŠ‚ç‚¹é€‰æ‹©
