port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: ğŸ‡¨ğŸ‡¦CA_254 |10.04Mb
  server: 79.127.200.162
  type: ss
  country: ğŸ‡¨ğŸ‡¦CA
  port: 990
  password: f8f7aCzcPKbsF8p3
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¨ğŸ‡¦CA_252 |157.19Mb
  server: 138.197.165.21
  type: ss
  country: ğŸ‡¨ğŸ‡¦CA
  port: 8080
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: ğŸ‡¨ğŸ‡¦CA_253 |10.92Mb
  server: 68.183.193.204
  type: ss
  country: ğŸ‡¨ğŸ‡¦CA
  port: 8080
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: ğŸ‡¨ğŸ‡¦CA_255 |183.39Mb
  server: 138.197.153.10
  type: ss
  country: ğŸ‡¨ğŸ‡¦CA
  port: 8080
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: ğŸ‡¨ğŸ‡¦CA_256 |10.34Mb
  server: 132.145.102.60
  type: ss
  country: ğŸ‡¨ğŸ‡¦CA
  port: 21001
  password: 2a6c0365-e3ed-4aef-81ca-b1b6b46088da
  cipher: chacha20-ietf-poly1305
- name: _232 |10.15Mb
  server: 196.196.192.58
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_288 |210.03Mb
  server: 146.70.23.32
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: _233 |10.15Mb
  server: 37.143.129.98
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _231 |11.40Mb
  server: 89.46.233.36
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_289 |157.06Mb
  server: 89.185.84.185
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: c0rALV8bvjaRHD1hg8SmuN
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡«ğŸ‡®FI_278 |16.18Mb
  server: 65.21.243.22
  type: ss
  country: ğŸ‡«ğŸ‡®FI
  port: 31348
  password: mZGUFWMAlfWqI4vP58zw9DAHxR8TZLndKkvRgHHFa9eqWdnx
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡«ğŸ‡·FR_279 |144.46Mb
  server: 83.147.216.70
  type: ss
  country: ğŸ‡«ğŸ‡·FR
  port: 64519
  password: MVAZ6nsCGVWhTzcRIUD85f
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_291 |10.23Mb
  server: 79.127.233.170
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ğŸ‡¦ğŸ‡ºAU_243 |10.24Mb
  server: 3.25.198.142
  type: ss
  country: ğŸ‡¦ğŸ‡ºAU
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡§ğŸ‡·BR_250 |11.32Mb
  server: 154.90.62.168
  type: ss
  country: ğŸ‡§ğŸ‡·BR
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ğŸ‡¦ğŸ‡ºAU_244 |10.13Mb
  server: 3.107.35.33
  type: ss
  country: ğŸ‡¦ğŸ‡ºAU
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡¬ğŸ‡§GB_292 |73.94Mb
  server: 89.185.84.185
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: DkH7uO7t90Uw4D95zgZVdV
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_296 |77.84Mb
  server: 89.185.84.185
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: gq2tNZSuBwrZXZDZ5Z2Gfo
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_294 |10.32Mb
  server: 141.98.101.181
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: shadowsocks
  cipher: aes-128-gcm
- name: ğŸ‡¬ğŸ‡§GB_293 |10.86Mb
  server: 64.137.109.212
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 44884
  password: 2DGq3jvVRg5n3CcxmysGK2kmrgJeSNof12A76cZvVxqPpetyC1XEciCFufq5xKvRWGGnKVembpThuUSQhbZ7GMsZY4UVxEBw
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡­ğŸ‡ºHU_307 |10.02Mb
  server: 109.61.46.43
  type: ss
  country: ğŸ‡­ğŸ‡ºHU
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸ‡®ğŸ‡·IR-ğŸ‡³ğŸ‡±NL_351 |10.19Mb
  server: 151.242.251.137
  type: ss
  country: ğŸ‡®ğŸ‡·IR
  port: 8080
  password: QCXDxuDlTTMD7jtgHUjIoj
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_360 |10.17Mb
  server: 45.87.175.171
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: QCXDxuDlTTMD7jtgHUjIoj
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡­ğŸ‡°HK_303 |20.86Mb
  server: 8.210.230.179
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 2318
  uuid: 55bb7a7c-c09d-47f6-a047-8472eeaadeff
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
  ws-opts:
    path: /arki?ed=2048
- name: ğŸ‡±ğŸ‡¹LT_369 |10.08Mb
  server: 45.87.175.171
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: 1RWwXhwfAB5gAEozU4G2Pg
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¯ğŸ‡µJP_354 |308.85Mb
  server: 202.182.98.223
  type: ss
  country: ğŸ‡¯ğŸ‡µJP
  port: 9443
  password: lINaALnHIiH4cSj8pJn6TQ==
  cipher: aes-128-gcm
- name: ğŸ‡¯ğŸ‡µJP_355 |10.59Mb
  server: 153.121.43.183
  type: ss
  country: ğŸ‡¯ğŸ‡µJP
  port: 10087
  password: '10086'
  cipher: aes-128-gcm
- name: ğŸ‡±ğŸ‡¹LT_371 |20.42Mb
  server: 45.87.175.199
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: 1RWwXhwfAB5gAEozU4G2Pg
  cipher: chacha20-ietf-poly1305
- name: Pool_ğŸ‡­ğŸ‡°HK_300 |170.00Mb
  server: 150.107.46.21
  type: ssr
  country: ğŸ‡­ğŸ‡°HK
  port: 8083
  password: iFqnzSscN
  cipher: aes-256-cfb
  protocol: origin
  obfs: tls1.2_ticket_auth
- name: ğŸ‡®ğŸ‡³IN_310 |20.80Mb
  server: 13.233.212.186
  type: ss
  country: ğŸ‡®ğŸ‡³IN
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡®ğŸ‡³IN_311 |42.16Mb
  server: 52.66.211.233
  type: ss
  country: ğŸ‡®ğŸ‡³IN
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡®ğŸ‡³IN_309 |39.74Mb
  server: 15.206.124.85
  type: ss
  country: ğŸ‡®ğŸ‡³IN
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡±ğŸ‡¹LT_374 |10.62Mb
  server: 45.87.175.188
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: QCXDxuDlTTMD7jtgHUjIoj
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡³ğŸ‡±NL_391 |14.89Mb
  server: 193.29.139.251
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 8080
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡³ğŸ‡±NL_399 |10.10Mb
  server: 193.29.139.227
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 8080
  password: 4a2rfixophdjffa8KVA4Aa
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡µğŸ‡¦PA_404 |10.58Mb
  server: 138.186.142.80
  type: ss
  country: ğŸ‡µğŸ‡¦PA
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡³ğŸ‡±NL_401 |10.12Mb
  server: 79.127.227.198
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 990
  password: f8f7aCzcPKbsF8p3
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¸ğŸ‡¬SG_453 |10.23Mb
  server: 15.235.83.227
  type: vmess
  country: ğŸ‡¸ğŸ‡¬SG
  port: 443
  uuid: 03fcc618-b93d-6796-6aed-8a38c975d581
  alterId: 0
  cipher: auto
  network: ws
  servername: mankadmu.com
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /linkvws
    headers:
      HOST: mankadmu.com
- name: ğŸ‡¸ğŸ‡¬SG_456 |10.21Mb
  server: 15.235.83.228
  type: vmess
  country: ğŸ‡¸ğŸ‡¬SG
  port: 443
  uuid: 03fcc618-b93d-6796-6aed-8a38c975d581
  alterId: 0
  cipher: auto
  network: ws
  servername: wrmelmwxlf.gktevlrqznwqqozy.fabpfs66gizmnojhcvqxwl.kytrcfzqla87gvgvs6c7kjnrubuh.cc
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /linkvws
    headers:
      HOST: wrmelmwxlf.gktevlrqznwqqozy.fabpfs66gizmnojhcvqxwl.kytrcfzqla87gvgvs6c7kjnrubuh.cc
- name: ğŸ‡ºğŸ‡¸US_480 |10.43Mb
  server: 37.19.198.243
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: shadowsocks
  cipher: aes-128-gcm
- name: ğŸ‡ºğŸ‡¸US_482 |10.24Mb
  server: 67.220.95.26
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 8080
  password: 42000e02-6b4d-46ad-a572-80db7db2a9ce
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡µğŸ‡±PL_410 |149.42Mb
  server: 217.30.10.70
  type: ss
  country: ğŸ‡µğŸ‡±PL
  port: 9015
  password: ZpNDDKRu9MagNvaf
  cipher: aes-256-cfb
- name: ğŸ‡µğŸ‡±PL_411 |171.76Mb
  server: 217.30.10.70
  type: ss
  country: ğŸ‡µğŸ‡±PL
  port: 9041
  password: U6qnYRhfyDmn8sgn
  cipher: aes-256-cfb
- name: ğŸ‡µğŸ‡±PL_413 |11.16Mb
  server: 217.30.10.18
  type: ss
  country: ğŸ‡µğŸ‡±PL
  port: 9097
  password: Sn5B7jTqr76aCJT8
  cipher: aes-256-cfb
- name: ğŸ‡µğŸ‡±PL_429 |12.00Mb
  server: 217.30.10.70
  type: ss
  country: ğŸ‡µğŸ‡±PL
  port: 9053
  password: SBM7R883jBmnqe6C
  cipher: aes-256-cfb
- name: ğŸ‡ºğŸ‡¸US_489 |10.07Mb
  server: 104.192.226.106
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 990
  password: f8f7aCzcPKbsF8p3
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_501 |10.55Mb
  server: 52.87.250.198
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡ºğŸ‡¸US_499 |10.52Mb
  server: 54.227.21.67
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡µğŸ‡±PL_417 |147.77Mb
  server: 217.30.10.70
  type: ss
  country: ğŸ‡µğŸ‡±PL
  port: 9084
  password: c3NtHJ5ujV2tGDfj
  cipher: aes-256-cfb
- name: ğŸ‡ºğŸ‡¸US_509 |10.45Mb
  server: 54.209.249.254
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡µğŸ‡±PL_435 |61.70Mb
  server: 217.30.10.18
  type: ss
  country: ğŸ‡µğŸ‡±PL
  port: 9020
  password: BNmAXXxAHYpTRdzu
  cipher: aes-256-cfb
- name: ğŸ‡·ğŸ‡ºRU_442 |139.35Mb
  server: 95.163.176.37
  type: ss
  country: ğŸ‡·ğŸ‡ºRU
  port: 8506
  password: WLEqen5ubQYw4TbHTxxnjK
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_527 |10.42Mb
  server: 37.19.198.160
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: shadowsocks
  cipher: aes-128-gcm
- name: ğŸ‡ºğŸ‡¸US_530 |10.22Mb
  server: 156.146.38.167
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: shadowsocks
  cipher: aes-128-gcm
- name: ğŸ‡ºğŸ‡¸US_524 |18.19Mb
  server: 167.88.61.110
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 7002
  password: RexnBgU7EV5ADxG
  cipher: aes-256-gcm
- name: disney_US |10.04Mb
  server: 107.151.182.197
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 8080
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: ğŸ‡ºğŸ‡¸US_491 |10.58Mb
  server: 149.22.87.240
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: shadowsocks
  cipher: aes-128-gcm
- name: Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_497 |282.74Mb
  server: us.vmagnum.win
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 57456
  password: 360e21d21977dc11
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_535 |17.93Mb
  server: 167.88.61.110
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 7306
  password: FoOiGlkAA9yPEGP
  cipher: aes-256-gcm
- name: ğŸ‡ºğŸ‡¸US_520 |18.71Mb
  server: 23.157.40.5
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 8118
  password: cdBIDV42DCwnfIN
  cipher: aes-256-gcm
- name: ğŸ‡ºğŸ‡¸US_521 |17.53Mb
  server: 23.157.40.5
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 2376
  password: faBAoD54k87UJG7
  cipher: aes-256-gcm
- name: ğŸ‡ºğŸ‡¸US_532 |18.77Mb
  server: 23.157.40.5
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 5600
  password: Y6R9pAtvxxzmGC
  cipher: aes-256-gcm
- name: ğŸ‡ºğŸ‡¸US_548 |10.31Mb
  server: 54.82.229.122
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡ºğŸ‡¸US_536 |11.33Mb
  server: 167.88.61.113
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 8090
  password: PCnnH6SQSnfoS27
  cipher: aes-256-gcm
- name: ğŸ‡ºğŸ‡¸US_547 |323.93Mb
  server: 104.167.197.25
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 57456
  password: 360e21d21977dc11
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_551 |14.43Mb
  server: 23.154.136.213
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 7307
  password: FoOiGlkAA9yPEGP
  cipher: aes-256-gcm
- name: ğŸ‡ºğŸ‡¸US_537 |11.64Mb
  server: 23.157.40.5
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 8888
  password: Y6R9pAtvxxzmGC
  cipher: aes-256-gcm
- name: ğŸ‡ºğŸ‡¸US_542 |16.76Mb
  server: 23.157.40.5
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 8009
  password: XKFKl2rULjIp74
  cipher: aes-256-gcm
- name: ğŸ‡ºğŸ‡¸US_540 |18.18Mb
  server: 23.157.40.5
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 7002
  password: RexnBgU7EV5ADxG
  cipher: aes-256-gcm
- name: ğŸ‡ºğŸ‡¸US_550 |19.52Mb
  server: 23.157.40.5
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 5000
  password: Y6R9pAtvxxzmGC
  cipher: aes-256-gcm
- name: ğŸ‡ºğŸ‡¸US_558 |10.35Mb
  server: 54.157.216.140
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡ºğŸ‡¸US_546 |10.06Mb
  server: 45.158.171.110
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 8080
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_493 |89.96Mb
  server: imap.roomyinmita.name
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 40565
  password: n7nqKk8Dr1ycsZKd5q5huWdCsbxVQEa4McgLmohr5oeTARXjx49jLFG4Efq4FGN7MdAbVaQUZfp1Y4nCUCMzuqTxqdwBQ19T
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_505 |71.64Mb
  server: imap.roomyinmita.name
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 40565
  password: oEkEWExFKHKeY1xuRns6ErkYbzt3HdCGNPN3nTQnM1FU7yTR1SZTTC2JLtPF7HeFAUCGgx5hvxUGw8ksjEyRioPEeXhxg7Q3
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_528 |68.74Mb
  server: imap.roomyinmita.name
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 40565
  password: xoGddrYBPwuYWj2ZA1kDM5Hz8fpomKaQrLoUDEzoLcgdqkaJdSi6UPTn3EFD6vXtuPBgVvtWeXjzkaWTu5M7cwKHMdyiLVon
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_552 |15.44Mb
  server: 23.157.40.101
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 8008
  password: XKFKl2rULjIp74
  cipher: aes-256-gcm
- name: ğŸ‡ºğŸ‡¸US_557 |80.16Mb
  server: imap.roomyinmita.name
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 40565
  password: 2T4HCndX3QvfDBmGXJnKSct873fvrXjLHPZSpfumFdMMqBUeh8E878f6Zfv4YA21KokhxF1c48rjVLeBeWJu4ovizkPtUMAY
  cipher: chacha20-ietf-poly1305
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - ğŸ‡¨ğŸ‡¦CA_254 |10.04Mb
  - ğŸ‡¨ğŸ‡¦CA_252 |157.19Mb
  - ğŸ‡¨ğŸ‡¦CA_253 |10.92Mb
  - ğŸ‡¨ğŸ‡¦CA_255 |183.39Mb
  - ğŸ‡¨ğŸ‡¦CA_256 |10.34Mb
  - _232 |10.15Mb
  - ğŸ‡¬ğŸ‡§GB_288 |210.03Mb
  - _233 |10.15Mb
  - _231 |11.40Mb
  - ğŸ‡¬ğŸ‡§GB_289 |157.06Mb
  - ğŸ‡«ğŸ‡®FI_278 |16.18Mb
  - ğŸ‡«ğŸ‡·FR_279 |144.46Mb
  - ğŸ‡¬ğŸ‡§GB_291 |10.23Mb
  - ğŸ‡¦ğŸ‡ºAU_243 |10.24Mb
  - ğŸ‡§ğŸ‡·BR_250 |11.32Mb
  - ğŸ‡¦ğŸ‡ºAU_244 |10.13Mb
  - ğŸ‡¬ğŸ‡§GB_292 |73.94Mb
  - ğŸ‡¬ğŸ‡§GB_296 |77.84Mb
  - ğŸ‡¬ğŸ‡§GB_294 |10.32Mb
  - ğŸ‡¬ğŸ‡§GB_293 |10.86Mb
  - ğŸ‡­ğŸ‡ºHU_307 |10.02Mb
  - Relay_ğŸ‡®ğŸ‡·IR-ğŸ‡³ğŸ‡±NL_351 |10.19Mb
  - ğŸ‡±ğŸ‡¹LT_360 |10.17Mb
  - ğŸ‡­ğŸ‡°HK_303 |20.86Mb
  - ğŸ‡±ğŸ‡¹LT_369 |10.08Mb
  - ğŸ‡¯ğŸ‡µJP_354 |308.85Mb
  - ğŸ‡¯ğŸ‡µJP_355 |10.59Mb
  - ğŸ‡±ğŸ‡¹LT_371 |20.42Mb
  - Pool_ğŸ‡­ğŸ‡°HK_300 |170.00Mb
  - ğŸ‡®ğŸ‡³IN_310 |20.80Mb
  - ğŸ‡®ğŸ‡³IN_311 |42.16Mb
  - ğŸ‡®ğŸ‡³IN_309 |39.74Mb
  - ğŸ‡±ğŸ‡¹LT_374 |10.62Mb
  - ğŸ‡³ğŸ‡±NL_391 |14.89Mb
  - ğŸ‡³ğŸ‡±NL_399 |10.10Mb
  - ğŸ‡µğŸ‡¦PA_404 |10.58Mb
  - ğŸ‡³ğŸ‡±NL_401 |10.12Mb
  - ğŸ‡¸ğŸ‡¬SG_453 |10.23Mb
  - ğŸ‡¸ğŸ‡¬SG_456 |10.21Mb
  - ğŸ‡ºğŸ‡¸US_480 |10.43Mb
  - ğŸ‡ºğŸ‡¸US_482 |10.24Mb
  - ğŸ‡µğŸ‡±PL_410 |149.42Mb
  - ğŸ‡µğŸ‡±PL_411 |171.76Mb
  - ğŸ‡µğŸ‡±PL_413 |11.16Mb
  - ğŸ‡µğŸ‡±PL_429 |12.00Mb
  - ğŸ‡ºğŸ‡¸US_489 |10.07Mb
  - ğŸ‡ºğŸ‡¸US_501 |10.55Mb
  - ğŸ‡ºğŸ‡¸US_499 |10.52Mb
  - ğŸ‡µğŸ‡±PL_417 |147.77Mb
  - ğŸ‡ºğŸ‡¸US_509 |10.45Mb
  - ğŸ‡µğŸ‡±PL_435 |61.70Mb
  - ğŸ‡·ğŸ‡ºRU_442 |139.35Mb
  - ğŸ‡ºğŸ‡¸US_527 |10.42Mb
  - ğŸ‡ºğŸ‡¸US_530 |10.22Mb
  - ğŸ‡ºğŸ‡¸US_524 |18.19Mb
  - disney_US |10.04Mb
  - ğŸ‡ºğŸ‡¸US_491 |10.58Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_497 |282.74Mb
  - ğŸ‡ºğŸ‡¸US_535 |17.93Mb
  - ğŸ‡ºğŸ‡¸US_520 |18.71Mb
  - ğŸ‡ºğŸ‡¸US_521 |17.53Mb
  - ğŸ‡ºğŸ‡¸US_532 |18.77Mb
  - ğŸ‡ºğŸ‡¸US_548 |10.31Mb
  - ğŸ‡ºğŸ‡¸US_536 |11.33Mb
  - ğŸ‡ºğŸ‡¸US_547 |323.93Mb
  - ğŸ‡ºğŸ‡¸US_551 |14.43Mb
  - ğŸ‡ºğŸ‡¸US_537 |11.64Mb
  - ğŸ‡ºğŸ‡¸US_542 |16.76Mb
  - ğŸ‡ºğŸ‡¸US_540 |18.18Mb
  - ğŸ‡ºğŸ‡¸US_550 |19.52Mb
  - ğŸ‡ºğŸ‡¸US_558 |10.35Mb
  - ğŸ‡ºğŸ‡¸US_546 |10.06Mb
  - ğŸ‡ºğŸ‡¸US_493 |89.96Mb
  - ğŸ‡ºğŸ‡¸US_505 |71.64Mb
  - ğŸ‡ºğŸ‡¸US_528 |68.74Mb
  - ğŸ‡ºğŸ‡¸US_552 |15.44Mb
  - ğŸ‡ºğŸ‡¸US_557 |80.16Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - ğŸ‡¨ğŸ‡¦CA_254 |10.04Mb
  - ğŸ‡¨ğŸ‡¦CA_252 |157.19Mb
  - ğŸ‡¨ğŸ‡¦CA_253 |10.92Mb
  - ğŸ‡¨ğŸ‡¦CA_255 |183.39Mb
  - ğŸ‡¨ğŸ‡¦CA_256 |10.34Mb
  - _232 |10.15Mb
  - ğŸ‡¬ğŸ‡§GB_288 |210.03Mb
  - _233 |10.15Mb
  - _231 |11.40Mb
  - ğŸ‡¬ğŸ‡§GB_289 |157.06Mb
  - ğŸ‡«ğŸ‡®FI_278 |16.18Mb
  - ğŸ‡«ğŸ‡·FR_279 |144.46Mb
  - ğŸ‡¬ğŸ‡§GB_291 |10.23Mb
  - ğŸ‡¦ğŸ‡ºAU_243 |10.24Mb
  - ğŸ‡§ğŸ‡·BR_250 |11.32Mb
  - ğŸ‡¦ğŸ‡ºAU_244 |10.13Mb
  - ğŸ‡¬ğŸ‡§GB_292 |73.94Mb
  - ğŸ‡¬ğŸ‡§GB_296 |77.84Mb
  - ğŸ‡¬ğŸ‡§GB_294 |10.32Mb
  - ğŸ‡¬ğŸ‡§GB_293 |10.86Mb
  - ğŸ‡­ğŸ‡ºHU_307 |10.02Mb
  - Relay_ğŸ‡®ğŸ‡·IR-ğŸ‡³ğŸ‡±NL_351 |10.19Mb
  - ğŸ‡±ğŸ‡¹LT_360 |10.17Mb
  - ğŸ‡­ğŸ‡°HK_303 |20.86Mb
  - ğŸ‡±ğŸ‡¹LT_369 |10.08Mb
  - ğŸ‡¯ğŸ‡µJP_354 |308.85Mb
  - ğŸ‡¯ğŸ‡µJP_355 |10.59Mb
  - ğŸ‡±ğŸ‡¹LT_371 |20.42Mb
  - Pool_ğŸ‡­ğŸ‡°HK_300 |170.00Mb
  - ğŸ‡®ğŸ‡³IN_310 |20.80Mb
  - ğŸ‡®ğŸ‡³IN_311 |42.16Mb
  - ğŸ‡®ğŸ‡³IN_309 |39.74Mb
  - ğŸ‡±ğŸ‡¹LT_374 |10.62Mb
  - ğŸ‡³ğŸ‡±NL_391 |14.89Mb
  - ğŸ‡³ğŸ‡±NL_399 |10.10Mb
  - ğŸ‡µğŸ‡¦PA_404 |10.58Mb
  - ğŸ‡³ğŸ‡±NL_401 |10.12Mb
  - ğŸ‡¸ğŸ‡¬SG_453 |10.23Mb
  - ğŸ‡¸ğŸ‡¬SG_456 |10.21Mb
  - ğŸ‡ºğŸ‡¸US_480 |10.43Mb
  - ğŸ‡ºğŸ‡¸US_482 |10.24Mb
  - ğŸ‡µğŸ‡±PL_410 |149.42Mb
  - ğŸ‡µğŸ‡±PL_411 |171.76Mb
  - ğŸ‡µğŸ‡±PL_413 |11.16Mb
  - ğŸ‡µğŸ‡±PL_429 |12.00Mb
  - ğŸ‡ºğŸ‡¸US_489 |10.07Mb
  - ğŸ‡ºğŸ‡¸US_501 |10.55Mb
  - ğŸ‡ºğŸ‡¸US_499 |10.52Mb
  - ğŸ‡µğŸ‡±PL_417 |147.77Mb
  - ğŸ‡ºğŸ‡¸US_509 |10.45Mb
  - ğŸ‡µğŸ‡±PL_435 |61.70Mb
  - ğŸ‡·ğŸ‡ºRU_442 |139.35Mb
  - ğŸ‡ºğŸ‡¸US_527 |10.42Mb
  - ğŸ‡ºğŸ‡¸US_530 |10.22Mb
  - ğŸ‡ºğŸ‡¸US_524 |18.19Mb
  - disney_US |10.04Mb
  - ğŸ‡ºğŸ‡¸US_491 |10.58Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_497 |282.74Mb
  - ğŸ‡ºğŸ‡¸US_535 |17.93Mb
  - ğŸ‡ºğŸ‡¸US_520 |18.71Mb
  - ğŸ‡ºğŸ‡¸US_521 |17.53Mb
  - ğŸ‡ºğŸ‡¸US_532 |18.77Mb
  - ğŸ‡ºğŸ‡¸US_548 |10.31Mb
  - ğŸ‡ºğŸ‡¸US_536 |11.33Mb
  - ğŸ‡ºğŸ‡¸US_547 |323.93Mb
  - ğŸ‡ºğŸ‡¸US_551 |14.43Mb
  - ğŸ‡ºğŸ‡¸US_537 |11.64Mb
  - ğŸ‡ºğŸ‡¸US_542 |16.76Mb
  - ğŸ‡ºğŸ‡¸US_540 |18.18Mb
  - ğŸ‡ºğŸ‡¸US_550 |19.52Mb
  - ğŸ‡ºğŸ‡¸US_558 |10.35Mb
  - ğŸ‡ºğŸ‡¸US_546 |10.06Mb
  - ğŸ‡ºğŸ‡¸US_493 |89.96Mb
  - ğŸ‡ºğŸ‡¸US_505 |71.64Mb
  - ğŸ‡ºğŸ‡¸US_528 |68.74Mb
  - ğŸ‡ºğŸ‡¸US_552 |15.44Mb
  - ğŸ‡ºğŸ‡¸US_557 |80.16Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
