port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: netflix_IE |62.44Mb
  server: 18.203.220.111
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: disney_netflix_NL |274.05Mb
  server: 151.242.251.137
  type: ss
  port: 8080
  password: o5osZg269v5zHpYjr1xY9s
  cipher: chacha20-ietf-poly1305
- name: _358 |19.13Mb
  server: 103.106.3.82
  type: ss
  port: 443
  udp: true
  password: 4SaCIazlgumYkM8FkPzlmwjpyWBDZFBk
  cipher: chacha20-ietf-poly1305
- name: Relay_-ğŸ‡­ğŸ‡°HK_396 |15.22Mb
  server: v10.hdacd.com
  type: vmess
  port: 30807
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: Relay_-ğŸ‡ºğŸ‡¸US_411 |10.95Mb
  server: m.cnmjin.net
  type: vmess
  port: 16618
  udp: true
  uuid: 77439561-dcef-4e45-803a-743cfa7d20c2
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /
    headers:
      Host: 9e97d6c9e2e0ad3444cbf96d3709366d.mobgslb.tbcache.com
- name: disney_TW |13.03Mb
  server: m.cnmjin.net
  type: vmess
  port: 16616
  udp: true
  uuid: 77439561-dcef-4e45-803a-743cfa7d20c2
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /
    headers:
      Host: 9e97d6c9e2e0ad3444cbf96d3709366d.mobgslb.tbcache.com
- name: disney_HK |24.29Mb
  server: m.cnmjin.net
  type: vmess
  port: 16622
  udp: true
  uuid: 77439561-dcef-4e45-803a-743cfa7d20c2
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /
    headers:
      Host: 9e97d6c9e2e0ad3444cbf96d3709366d.mobgslb.tbcache.com
- name: Relay_-ğŸ‡ºğŸ‡¸US_374 |10.43Mb
  server: planb.mojcn.com
  type: vmess
  port: 16648
  udp: true
  uuid: 77439561-dcef-4e45-803a-743cfa7d20c2
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /
    headers:
      Host: 9e97d6c9e2e0ad3444cbf96d3709366d.mobgslb.tbcache.com
- name: Relay_-ğŸ‡¯ğŸ‡µJP_423 |11.37Mb
  server: planb.mojcn.com
  type: vmess
  port: 16617
  udp: true
  uuid: 77439561-dcef-4e45-803a-743cfa7d20c2
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /
    headers:
      Host: 9e97d6c9e2e0ad3444cbf96d3709366d.mobgslb.tbcache.com
- name: _445 |15.88Mb
  server: 74.117.196.232
  type: vmess
  port: 37934
  udp: true
  uuid: 27104fae-f047-4993-902a-9368d8a3e9bc
  alterId: 0
  cipher: auto
  network: ws
  servername: imafake.locker
  http-opts: {}
  h2-opts: {}
  tls: true
  ws-opts:
    path: /speedtest
- name: disney_HK |24.35Mb
  server: planb.mojcn.com
  type: vmess
  port: 16632
  udp: true
  uuid: 77439561-dcef-4e45-803a-743cfa7d20c2
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /
    headers:
      Host: 9e97d6c9e2e0ad3444cbf96d3709366d.mobgslb.tbcache.com
- name: disney_netflix_DE |240.38Mb
  server: uk2-2.998998.best
  type: vmess
  port: 443
  udp: true
  uuid: b376015d-77d9-4482-9aa9-051be76aac65
  alterId: 0
  cipher: auto
  network: ws
  servername: b376015d-77d9-4482-9aa9-051be76aac65.placeunaorder.fun
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /logcatxiouerd34try9
    headers:
      Host: b376015d-77d9-4482-9aa9-051be76aac65.placeunaorder.fun
- name: disney_netflix_PT |81.78Mb
  server: 185.231.233.112
  type: ss
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: _474 |10.34Mb
  server: 74.117.196.232
  type: vmess
  port: 37934
  udp: true
  uuid: b01d1e26-2f84-48da-88a1-1d06a77857f3
  alterId: 0
  cipher: auto
  network: ws
  servername: imafake.locker
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /speedtest
- name: disney_HK |23.90Mb
  server: planb.mojcn.com
  type: vmess
  port: 16622
  udp: true
  uuid: 77439561-dcef-4e45-803a-743cfa7d20c2
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /
    headers:
      Host: 9e97d6c9e2e0ad3444cbf96d3709366d.mobgslb.tbcache.com
- name: Relay_-ğŸ‡¯ğŸ‡µJP_454 |11.20Mb
  server: m.cnmjin.net
  type: vmess
  port: 16617
  udp: true
  uuid: 77439561-dcef-4e45-803a-743cfa7d20c2
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /
    headers:
      Host: 9e97d6c9e2e0ad3444cbf96d3709366d.mobgslb.tbcache.com
- name: disney_TW |13.23Mb
  server: planb.mojcn.com
  type: vmess
  port: 16616
  udp: true
  uuid: 77439561-dcef-4e45-803a-743cfa7d20c2
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /
    headers:
      Host: 9e97d6c9e2e0ad3444cbf96d3709366d.mobgslb.tbcache.com
- name: Relay_-ğŸ‡®ğŸ‡³IN_473 |27.07Mb
  server: planb.mojcn.com
  type: vmess
  port: 16626
  udp: true
  uuid: 77439561-dcef-4e45-803a-743cfa7d20c2
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /
    headers:
      Host: 9e97d6c9e2e0ad3444cbf96d3709366d.mobgslb.tbcache.com
- name: disney_HK |24.15Mb
  server: m.cnmjin.net
  type: vmess
  port: 16632
  udp: true
  uuid: 77439561-dcef-4e45-803a-743cfa7d20c2
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /
    headers:
      Host: 9e97d6c9e2e0ad3444cbf96d3709366d.mobgslb.tbcache.com
- name: Relay_-ğŸ‡³ğŸ‡±NL_478 |21.04Mb
  server: 160.16.81.84
  type: trojan
  port: 4054
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: disney_netflix_US |28.45Mb
  server: us5.998998.best
  type: vmess
  port: 443
  udp: true
  uuid: b376015d-77d9-4482-9aa9-051be76aac65
  alterId: 0
  cipher: auto
  network: ws
  servername: b376015d-77d9-4482-9aa9-051be76aac65.fasleangles.fun
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /androirfdsreoightrjh
    headers:
      Host: b376015d-77d9-4482-9aa9-051be76aac65.fasleangles.fun
- name: Relay_-ğŸ‡¯ğŸ‡µJP_480 |23.26Mb
  server: 153.121.51.29
  type: trojan
  port: 3169
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡³ğŸ‡±NL_487 |10.83Mb
  server: 160.16.124.55
  type: trojan
  port: 4054
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¯ğŸ‡µJP_483 |18.00Mb
  server: 52.195.176.26
  type: trojan
  port: 2145
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: Relay_-ğŸ‡³ğŸ‡±NL_488 |11.84Mb
  server: 160.16.124.55
  type: trojan
  port: 2760
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¸ğŸ‡¬SG_489 |22.11Mb
  server: 153.121.51.29
  type: trojan
  port: 127
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: disney_HK |21.76Mb
  server: 58.152.25.20
  type: trojan
  port: 443
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: disney_HK |20.40Mb
  server: 58.152.18.192
  type: trojan
  port: 443
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: disney_FR |149.43Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 27092
  uuid: a0596ba6-72a3-4366-8992-77088da65bd8
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_NL |73.95Mb
  server: 82.38.31.179
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_US |44.66Mb
  server: us19-25.998998.best
  type: vmess
  port: 443
  udp: true
  uuid: b376015d-77d9-4482-9aa9-051be76aac65
  alterId: 0
  cipher: auto
  network: ws
  servername: b376015d-77d9-4482-9aa9-051be76aac65.mihomo.baby
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /saoihgreg9384gh8934
    headers:
      Host: b376015d-77d9-4482-9aa9-051be76aac65.mihomo.baby
- name: ğŸ‡§ğŸ‡·BR_494 |11.91Mb
  server: 38.180.16.86
  type: vmess
  country: ğŸ‡§ğŸ‡·BR
  port: 36104
  uuid: E146A8CB-9D2F-449C-ADCA-8736FB
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_-ğŸ‡³ğŸ‡±NL_491 |10.49Mb
  server: 160.16.63.16
  type: trojan
  port: 4054
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¯ğŸ‡µJP_492 |21.96Mb
  server: 160.16.138.24
  type: trojan
  port: 1331
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: netflix_AL |32.59Mb
  server: 87.121.162.249
  type: ss
  country: ğŸ‡­ğŸ‡°HK
  port: 443
  password: JGv616hMWdjfuZ00jYfq7XkBHJZrOBrg
  cipher: chacha20-ietf-poly1305
- name: disney_HK |14.19Mb
  server: 58.152.18.95
  type: trojan
  port: 443
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: ğŸ‡¦ğŸ‡ºAU_493 |10.25Mb
  server: 54.252.240.128
  type: vmess
  country: ğŸ‡¦ğŸ‡ºAU
  port: 1000
  uuid: ca26a9fd-fef8-4ea7-d194-450ce4e0c67a
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡²ğŸ‡½MX_512 |35.51Mb
  server: 216.238.89.53
  type: vmess
  country: ğŸ‡²ğŸ‡½MX
  port: 57283
  uuid: 1a5aafc0-6482-451d-fe76-6875b7818579
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: netflix_IL |13.24Mb
  server: 45.93.95.187
  type: ss
  country: ğŸ‡®ğŸ‡±IL
  port: 8618
  password: 4lUEC91c1d8oeClzDbYpXA
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_NL |233.43Mb
  server: 45.87.175.166
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 443
  password: 1RWwXhwfAB5gAEozU4G2Pg
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡­ğŸ‡°HK_501 |29.58Mb
  server: 47.242.162.148
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 31813
  uuid: 00308f3b-747a-4710-b2cb-32c8de9785a1
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
  ws-opts:
    path: /arki?ed=2048
- name: ğŸ‡­ğŸ‡°HK_502 |23.84Mb
  server: 47.242.125.104
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 58424
  uuid: 80016399-3178-472e-86e3-129aab31a025
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
  ws-opts:
    path: /arki?ed=2048
- name: disney_netflix_US |50.81Mb
  server: 100.25.219.192
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡­ğŸ‡°HK_503 |81.44Mb
  server: 8.210.134.183
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 3721
  uuid: e72f5c6b-220f-40b3-a115-2d81473458cf
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
  ws-opts:
    path: /
- name: ğŸ‡­ğŸ‡°HK_504 |30.31Mb
  server: 47.243.51.237
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 52801
  uuid: ef93f413-9039-4ddb-aefb-2490287df55a
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
  ws-opts:
    path: /arki?ed=2048
- name: ğŸ‡­ğŸ‡°HK_506 |130.51Mb
  server: 47.242.162.235
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 3787
  uuid: e748fe05-2678-4c31-84c6-14ed825b92b4
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
  ws-opts:
    path: /arki?ed=2048
- name: ğŸ‡­ğŸ‡°HK_507 |21.71Mb
  server: 47.242.140.52
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 48219
  uuid: 006893c6-79b1-4c44-94ff-b8bbea065f1f
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
  ws-opts:
    path: /arki?ed=2048
- name: ğŸ‡·ğŸ‡ºRU_515 |13.42Mb
  server: 45.139.26.173
  type: ss
  country: ğŸ‡·ğŸ‡ºRU
  port: 57456
  password: d3837224ed465f00
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_US |19.05Mb
  server: 38.84.201.21
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 53487
  uuid: c3c1ec05-df2c-4975-9b42-e9b007564eb1
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡ºğŸ‡¸US_523 |21.05Mb
  server: 74.117.196.232
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 37934
  uuid: c50f9480-2e1d-40db-9458-630e79636663
  alterId: 0
  cipher: auto
  network: ws
  servername: imafake.locker
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /speedtest
    headers:
      HOST: imafake.locker
- name: ğŸ‡ºğŸ‡¸US_524 |22.56Mb
  server: 74.117.196.232
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 37934
  uuid: e1cc26b3-df0b-477b-afb0-53659a25e978
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /speedtest
- name: ğŸ‡ºğŸ‡¸US_525 |14.41Mb
  server: 74.117.196.232
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 37934
  uuid: b2da9920-b0a7-4354-9e26-3833ab8d00d0
  alterId: 0
  cipher: auto
  network: ws
  servername: imafake.locker
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /speedtest
    headers:
      HOST: imafake.locker
- name: disney_TR |21.87Mb
  server: 185.39.204.161
  type: ss
  country: ğŸ‡¹ğŸ‡·TR
  port: 33563
  password: bSlgCoGhApOb55tIMD0zxY
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡²ğŸ‡¾MY_513 |18.75Mb
  server: 38.54.98.110
  type: vmess
  country: ğŸ‡²ğŸ‡¾MY
  port: 2052
  uuid: 665d9b8f-153d-4907-adac-de12afd9c851
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: disney_netflix_TR |19.35Mb
  server: tr-1.stunnel.cc
  type: ss
  country: ğŸ‡¹ğŸ‡·TR
  port: 8444
  password: tunnel-fbrof
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¸ğŸ‡¬SG_516 |11.24Mb
  server: 68.183.178.131
  type: vmess
  country: ğŸ‡¸ğŸ‡¬SG
  port: 58607
  uuid: c11c32cb-27b3-4afa-c0f3-fb250aa4959e
  alterId: 0
  cipher: auto
  network: ws
  servername: www.12333.monster
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /
    headers:
      HOST: www.12333.monster
- name: disney_HK |25.27Mb
  server: 45.136.12.37
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 38141
  uuid: fd291be6-b48d-43a1-da38-66c7f80e2f80
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_US |20.17Mb
  server: cf.fovi.tk
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  uuid: bf67437e-6c90-45ca-abc2-c7240a5ce2aa
  alterId: 0
  cipher: auto
  network: ws
  servername: foxlux.fovi.tk
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /eisasqa
    headers:
      HOST: foxlux.fovi.tk
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - netflix_IE |62.44Mb
  - disney_netflix_NL |274.05Mb
  - _358 |19.13Mb
  - Relay_-ğŸ‡­ğŸ‡°HK_396 |15.22Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_411 |10.95Mb
  - disney_TW |13.03Mb
  - disney_HK |24.29Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_374 |10.43Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_423 |11.37Mb
  - _445 |15.88Mb
  - disney_HK |24.35Mb
  - disney_netflix_DE |240.38Mb
  - disney_netflix_PT |81.78Mb
  - _474 |10.34Mb
  - disney_HK |23.90Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_454 |11.20Mb
  - disney_TW |13.23Mb
  - Relay_-ğŸ‡®ğŸ‡³IN_473 |27.07Mb
  - disney_HK |24.15Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_478 |21.04Mb
  - disney_netflix_US |28.45Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_480 |23.26Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_487 |10.83Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_483 |18.00Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_488 |11.84Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_489 |22.11Mb
  - disney_HK |21.76Mb
  - disney_HK |20.40Mb
  - disney_FR |149.43Mb
  - disney_netflix_NL |73.95Mb
  - disney_netflix_US |44.66Mb
  - ğŸ‡§ğŸ‡·BR_494 |11.91Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_491 |10.49Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_492 |21.96Mb
  - netflix_AL |32.59Mb
  - disney_HK |14.19Mb
  - ğŸ‡¦ğŸ‡ºAU_493 |10.25Mb
  - ğŸ‡²ğŸ‡½MX_512 |35.51Mb
  - netflix_IL |13.24Mb
  - disney_netflix_NL |233.43Mb
  - ğŸ‡­ğŸ‡°HK_501 |29.58Mb
  - ğŸ‡­ğŸ‡°HK_502 |23.84Mb
  - disney_netflix_US |50.81Mb
  - ğŸ‡­ğŸ‡°HK_503 |81.44Mb
  - ğŸ‡­ğŸ‡°HK_504 |30.31Mb
  - ğŸ‡­ğŸ‡°HK_506 |130.51Mb
  - ğŸ‡­ğŸ‡°HK_507 |21.71Mb
  - ğŸ‡·ğŸ‡ºRU_515 |13.42Mb
  - disney_netflix_US |19.05Mb
  - ğŸ‡ºğŸ‡¸US_523 |21.05Mb
  - ğŸ‡ºğŸ‡¸US_524 |22.56Mb
  - ğŸ‡ºğŸ‡¸US_525 |14.41Mb
  - disney_TR |21.87Mb
  - ğŸ‡²ğŸ‡¾MY_513 |18.75Mb
  - disney_netflix_TR |19.35Mb
  - ğŸ‡¸ğŸ‡¬SG_516 |11.24Mb
  - disney_HK |25.27Mb
  - disney_netflix_US |20.17Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - netflix_IE |62.44Mb
  - disney_netflix_NL |274.05Mb
  - _358 |19.13Mb
  - Relay_-ğŸ‡­ğŸ‡°HK_396 |15.22Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_411 |10.95Mb
  - disney_TW |13.03Mb
  - disney_HK |24.29Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_374 |10.43Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_423 |11.37Mb
  - _445 |15.88Mb
  - disney_HK |24.35Mb
  - disney_netflix_DE |240.38Mb
  - disney_netflix_PT |81.78Mb
  - _474 |10.34Mb
  - disney_HK |23.90Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_454 |11.20Mb
  - disney_TW |13.23Mb
  - Relay_-ğŸ‡®ğŸ‡³IN_473 |27.07Mb
  - disney_HK |24.15Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_478 |21.04Mb
  - disney_netflix_US |28.45Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_480 |23.26Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_487 |10.83Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_483 |18.00Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_488 |11.84Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_489 |22.11Mb
  - disney_HK |21.76Mb
  - disney_HK |20.40Mb
  - disney_FR |149.43Mb
  - disney_netflix_NL |73.95Mb
  - disney_netflix_US |44.66Mb
  - ğŸ‡§ğŸ‡·BR_494 |11.91Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_491 |10.49Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_492 |21.96Mb
  - netflix_AL |32.59Mb
  - disney_HK |14.19Mb
  - ğŸ‡¦ğŸ‡ºAU_493 |10.25Mb
  - ğŸ‡²ğŸ‡½MX_512 |35.51Mb
  - netflix_IL |13.24Mb
  - disney_netflix_NL |233.43Mb
  - ğŸ‡­ğŸ‡°HK_501 |29.58Mb
  - ğŸ‡­ğŸ‡°HK_502 |23.84Mb
  - disney_netflix_US |50.81Mb
  - ğŸ‡­ğŸ‡°HK_503 |81.44Mb
  - ğŸ‡­ğŸ‡°HK_504 |30.31Mb
  - ğŸ‡­ğŸ‡°HK_506 |130.51Mb
  - ğŸ‡­ğŸ‡°HK_507 |21.71Mb
  - ğŸ‡·ğŸ‡ºRU_515 |13.42Mb
  - disney_netflix_US |19.05Mb
  - ğŸ‡ºğŸ‡¸US_523 |21.05Mb
  - ğŸ‡ºğŸ‡¸US_524 |22.56Mb
  - ğŸ‡ºğŸ‡¸US_525 |14.41Mb
  - disney_TR |21.87Mb
  - ğŸ‡²ğŸ‡¾MY_513 |18.75Mb
  - disney_netflix_TR |19.35Mb
  - ğŸ‡¸ğŸ‡¬SG_516 |11.24Mb
  - disney_HK |25.27Mb
  - disney_netflix_US |20.17Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
