port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: disney_netflix_US |35.31Mb
  server: 172.235.33.114
  type: vmess
  port: 10001
  uuid: 442a3923-eca1-4af0-b3ff-24a7ce0af68f
  alterId: 0
  cipher: auto
  network: tcp
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_HK |23.99Mb
  server: 23.227.38.178
  type: trojan
  port: 443
  udp: true
  password: aff9928f-7ba3-45fb-b56d-4dec45653ca9
  sni: q6clkp794liy3y90.hktimecsgo.xyz
  skip-cert-verify: true
  ws-opts:
    path: /images
    headers:
      Host: q6clkp794liy3y90.hktimecsgo.xyz
  network: ws
- name: disney_netflix_HK |23.97Mb
  server: 23.227.38.178
  type: trojan
  port: 443
  udp: true
  password: a8a5b34d-fe46-487d-bd6a-d9f3101525fd
  sni: q6clkp794liy3y90.hktimecsgo.xyz
  skip-cert-verify: true
  ws-opts:
    path: /images
    headers:
      Host: q6clkp794liy3y90.hktimecsgo.xyz
  network: ws
- name: disney_netflix_NL |309.31Mb
  server: 151.242.251.144
  type: ss
  port: 8080
  udp: true
  password: QCXDxuDlTTMD7jtgHUjIoj
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_NL |25.24Mb
  server: 82.38.31.218
  type: ss
  port: 8080
  udp: true
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_NL |14.90Mb
  server: 82.38.31.179
  type: ss
  port: 8080
  udp: true
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_TW |47.18Mb
  server: 141.193.213.199
  type: trojan
  port: 443
  udp: true
  password: a8a5b34d-fe46-487d-bd6a-d9f3101525fd
  sni: 26z68w0ecxbuyf89.ukgogo202511.top
  skip-cert-verify: true
  ws-opts:
    path: /images
    headers:
      Host: 26z68w0ecxbuyf89.ukgogo202511.top
  network: ws
- name: disney_netflix_NL |19.98Mb
  server: 109.71.246.210
  type: ss
  port: 56689
  udp: true
  password: YQCSKoCF3QazW8YlvDBWA4
  cipher: chacha20-ietf-poly1305
- name: netflix_PL |38.95Mb
  server: 45.15.126.19
  type: ss
  port: 443
  udp: true
  password: 6Ts2ZDTQAf3hkFoB8AFufDwsGrlF4e2t
  cipher: chacha20-ietf-poly1305
- name: netflix_ES |14.13Mb
  server: 213.159.67.124
  type: ss
  port: 443
  password: mbhqsStnFQT1cTZYCdsmkugGUC6GT6rp
  cipher: chacha20-ietf-poly1305
- name: disney_PT |140.61Mb
  server: 185.231.233.112
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: disney_netflix_US |37.00Mb
  server: 82.198.246.97
  type: vmess
  country: ğŸ‡¬ğŸ‡§GB
  port: 180
  uuid: d13fc2f5-3e05-4795-81eb-44143a09e552
  alterId: 0
  cipher: auto
  network: tcp
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_US |30.51Mb
  server: us19-25.998998.best
  type: vmess
  port: 443
  udp: true
  uuid: 24254866-770c-41b4-9404-3f50524f425b
  alterId: 0
  cipher: auto
  network: ws
  servername: 24254866-770c-41b4-9404-3f50524f425b.mihomo.baby
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /saoihgreg9384gh8934
    headers:
      Host: 24254866-770c-41b4-9404-3f50524f425b.mihomo.baby
- name: disney_netflix_FR |20.66Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 27092
  uuid: a0596ba6-72a3-4366-8992-77088da65bd8
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: netflix_KZ |29.89Mb
  server: 103.106.3.82
  type: ss
  port: 443
  udp: true
  password: 4SaCIazlgumYkM8FkPzlmwjpyWBDZFBk
  cipher: chacha20-ietf-poly1305
- name: Relay_ |10.03Mb
  server: f7c5a058-fa4a-4f7c-aed6-203efaf52286.f1eb10ae-1d82-4c6a-b4dd-bd9525520956.com
  type: trojan
  country: ğŸ‡®ğŸ‡ªIE
  port: 12016
  udp: true
  password: 05bf6017-75c3-44c1-b9bf-6a038107afde
  sni: sg6.yuanul.com
  skip-cert-verify: true
- name: disney_TW |10.08Mb
  server: f7c5a058-fa4a-4f7c-aed6-203efaf52286.f1eb10ae-1d82-4c6a-b4dd-bd9525520956.com
  type: trojan
  country: ğŸ‡®ğŸ‡ªIE
  port: 12104
  udp: true
  password: 05bf6017-75c3-44c1-b9bf-6a038107afde
  sni: 108.yuanul.com
  skip-cert-verify: true
- name: disney_HK |10.54Mb
  server: f7c5a058-fa4a-4f7c-aed6-203efaf52286.f1eb10ae-1d82-4c6a-b4dd-bd9525520956.com
  type: trojan
  country: ğŸ‡®ğŸ‡ªIE
  port: 10106
  udp: true
  password: 05bf6017-75c3-44c1-b9bf-6a038107afde
  sni: sni.eos-suzhou-4.cmecloud.cn
  skip-cert-verify: true
- name: disney_netflix_TW |10.33Mb
  server: f7c5a058-fa4a-4f7c-aed6-203efaf52286.f1eb10ae-1d82-4c6a-b4dd-bd9525520956.com
  type: trojan
  country: ğŸ‡®ğŸ‡ªIE
  port: 12105
  udp: true
  password: 05bf6017-75c3-44c1-b9bf-6a038107afde
  skip-cert-verify: true
- name: disney_HK |10.14Mb
  server: f7c5a058-fa4a-4f7c-aed6-203efaf52286.f1eb10ae-1d82-4c6a-b4dd-bd9525520956.com
  type: trojan
  country: ğŸ‡®ğŸ‡ªIE
  port: 10101
  udp: true
  password: 05bf6017-75c3-44c1-b9bf-6a038107afde
  sni: sni.eos-suzhou-4.cmecloud.cn
  skip-cert-verify: true
- name: disney_netflix_US |14.17Mb
  server: f7c5a058-fa4a-4f7c-aed6-203efaf52286.f1eb10ae-1d82-4c6a-b4dd-bd9525520956.com
  type: trojan
  country: ğŸ‡®ğŸ‡ªIE
  port: 13206
  udp: true
  password: 05bf6017-75c3-44c1-b9bf-6a038107afde
  sni: 138.yuanul.com
  skip-cert-verify: true
- name: disney_netflix_NL |34.19Mb
  server: 151.242.251.144
  type: ss
  country: ğŸ‡®ğŸ‡· IR
  port: 8080
  password: 4a2rfixophdjffa8KVA4Aa
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_NL |53.62Mb
  server: 151.242.251.153
  type: ss
  country: ğŸ‡®ğŸ‡· IR
  port: 8080
  password: QCXDxuDlTTMD7jtgHUjIoj
  cipher: chacha20-ietf-poly1305
- name: Relay_ |10.11Mb
  server: f7c5a058-fa4a-4f7c-aed6-203efaf52286.f1eb10ae-1d82-4c6a-b4dd-bd9525520956.com
  type: trojan
  country: ğŸ‡®ğŸ‡ªIE
  port: 10108
  udp: true
  password: 05bf6017-75c3-44c1-b9bf-6a038107afde
  sni: sni.eos-suzhou-4.cmecloud.cn
  skip-cert-verify: true
- name: disney_netflix_SG |10.06Mb
  server: f7c5a058-fa4a-4f7c-aed6-203efaf52286.f1eb10ae-1d82-4c6a-b4dd-bd9525520956.com
  type: trojan
  country: ğŸ‡®ğŸ‡ªIE
  port: 12017
  udp: true
  password: 05bf6017-75c3-44c1-b9bf-6a038107afde
  sni: 63.yuanul.com
  skip-cert-verify: true
- name: disney_netflix_TW |10.29Mb
  server: f7c5a058-fa4a-4f7c-aed6-203efaf52286.f1eb10ae-1d82-4c6a-b4dd-bd9525520956.com
  type: trojan
  country: ğŸ‡®ğŸ‡ªIE
  port: 12101
  udp: true
  password: 05bf6017-75c3-44c1-b9bf-6a038107afde
  sni: 104.yuanul.com
  skip-cert-verify: true
- name: Relay_ |10.07Mb
  server: f7c5a058-fa4a-4f7c-aed6-203efaf52286.f1eb10ae-1d82-4c6a-b4dd-bd9525520956.com
  type: trojan
  country: ğŸ‡®ğŸ‡ªIE
  port: 12014
  udp: true
  password: 05bf6017-75c3-44c1-b9bf-6a038107afde
  sni: sg4.yuanul.com
  skip-cert-verify: true
- name: disney_netflix_US |14.35Mb
  server: f7c5a058-fa4a-4f7c-aed6-203efaf52286.f1eb10ae-1d82-4c6a-b4dd-bd9525520956.com
  type: trojan
  country: ğŸ‡®ğŸ‡ªIE
  port: 13207
  udp: true
  password: 05bf6017-75c3-44c1-b9bf-6a038107afde
  sni: 140.yuanul.com
  skip-cert-verify: true
- name: disney_netflix_US |14.24Mb
  server: f7c5a058-fa4a-4f7c-aed6-203efaf52286.f1eb10ae-1d82-4c6a-b4dd-bd9525520956.com
  type: trojan
  country: ğŸ‡®ğŸ‡ªIE
  port: 13203
  udp: true
  password: 05bf6017-75c3-44c1-b9bf-6a038107afde
  sni: 136.yuanul.com
  skip-cert-verify: true
- name: disney_netflix_US |24.31Mb
  server: f7c5a058-fa4a-4f7c-aed6-203efaf52286.f1eb10ae-1d82-4c6a-b4dd-bd9525520956.com
  type: trojan
  country: ğŸ‡®ğŸ‡ªIE
  port: 13202
  udp: true
  password: 05bf6017-75c3-44c1-b9bf-6a038107afde
  sni: 135.yuanul.com
  skip-cert-verify: true
- name: netflix_JP |17.06Mb
  server: xray.kk37005.tk
  type: vmess
  country: ğŸ‡¯ğŸ‡µJP
  port: 55919
  uuid: 2e7548bb-7c5b-4d97-d64d-1b2fe4050089
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: disney_netflix_US |11.79Mb
  server: cf.fovi.tk
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  uuid: bf67437e-6c90-45ca-abc2-c7240a5ce2aa
  alterId: 0
  cipher: auto
  network: ws
  servername: foxpol.fovi.tk
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /eisasqa
    headers:
      HOST: foxpol.fovi.tk
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - disney_netflix_US |35.31Mb
  - disney_netflix_HK |23.99Mb
  - disney_netflix_HK |23.97Mb
  - disney_netflix_NL |309.31Mb
  - disney_netflix_NL |25.24Mb
  - disney_netflix_NL |14.90Mb
  - disney_netflix_TW |47.18Mb
  - disney_netflix_NL |19.98Mb
  - netflix_PL |38.95Mb
  - netflix_ES |14.13Mb
  - disney_PT |140.61Mb
  - disney_netflix_US |37.00Mb
  - disney_netflix_US |30.51Mb
  - disney_netflix_FR |20.66Mb
  - netflix_KZ |29.89Mb
  - Relay_ |10.03Mb
  - disney_TW |10.08Mb
  - disney_HK |10.54Mb
  - disney_netflix_TW |10.33Mb
  - disney_HK |10.14Mb
  - disney_netflix_US |14.17Mb
  - disney_netflix_NL |34.19Mb
  - disney_netflix_NL |53.62Mb
  - Relay_ |10.11Mb
  - disney_netflix_SG |10.06Mb
  - disney_netflix_TW |10.29Mb
  - Relay_ |10.07Mb
  - disney_netflix_US |14.35Mb
  - disney_netflix_US |14.24Mb
  - disney_netflix_US |24.31Mb
  - netflix_JP |17.06Mb
  - disney_netflix_US |11.79Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - disney_netflix_US |35.31Mb
  - disney_netflix_HK |23.99Mb
  - disney_netflix_HK |23.97Mb
  - disney_netflix_NL |309.31Mb
  - disney_netflix_NL |25.24Mb
  - disney_netflix_NL |14.90Mb
  - disney_netflix_TW |47.18Mb
  - disney_netflix_NL |19.98Mb
  - netflix_PL |38.95Mb
  - netflix_ES |14.13Mb
  - disney_PT |140.61Mb
  - disney_netflix_US |37.00Mb
  - disney_netflix_US |30.51Mb
  - disney_netflix_FR |20.66Mb
  - netflix_KZ |29.89Mb
  - Relay_ |10.03Mb
  - disney_TW |10.08Mb
  - disney_HK |10.54Mb
  - disney_netflix_TW |10.33Mb
  - disney_HK |10.14Mb
  - disney_netflix_US |14.17Mb
  - disney_netflix_NL |34.19Mb
  - disney_netflix_NL |53.62Mb
  - Relay_ |10.11Mb
  - disney_netflix_SG |10.06Mb
  - disney_netflix_TW |10.29Mb
  - Relay_ |10.07Mb
  - disney_netflix_US |14.35Mb
  - disney_netflix_US |14.24Mb
  - disney_netflix_US |24.31Mb
  - netflix_JP |17.06Mb
  - disney_netflix_US |11.79Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
