port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: ğŸ‡ºğŸ‡¸US_22 |31.37Mb
  server: 167.88.61.113
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 8090
  password: PCnnH6SQSnfoS27
  cipher: aes-256-gcm
- name: Pool_ğŸ‡­ğŸ‡°HK_17 |459.00Mb
  server: 150.107.46.21
  type: ssr
  country: ğŸ‡­ğŸ‡°HK
  port: 8083
  password: iFqnzSscN
  cipher: aes-256-cfb
  protocol: origin
  obfs: tls1.2_ticket_auth
- name: ğŸ‡«ğŸ‡·FR_16 |30.74Mb
  server: 83.147.216.70
  type: ss
  country: ğŸ‡«ğŸ‡·FR
  port: 64519
  password: eBzKXxEmQlAZKIBC8PhQYZ
  cipher: chacha20-ietf-poly1305
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - ğŸ‡ºğŸ‡¸US_22 |31.37Mb
  - Pool_ğŸ‡­ğŸ‡°HK_17 |459.00Mb
  - ğŸ‡«ğŸ‡·FR_16 |30.74Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - ğŸ‡ºğŸ‡¸US_22 |31.37Mb
  - Pool_ğŸ‡­ğŸ‡°HK_17 |459.00Mb
  - ğŸ‡«ğŸ‡·FR_16 |30.74Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
