port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: Relay_-ğŸ‡¨ğŸ‡¦CA_296 |69.65Mb
  server: 79.127.200.169
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _303 |237.17Mb
  server: 82.38.31.214
  type: ss
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: _300 |245.95Mb
  server: 151.242.251.152
  type: ss
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: _312 |235.08Mb
  server: 45.87.175.28
  type: ss
  port: 8080
  udp: true
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: _297 |83.33Mb
  server: 194.59.183.134
  type: ss
  port: 46114
  udp: true
  password: lejSRyqa033OEPmEQsvRsl
  cipher: chacha20-ietf-poly1305
- name: _313 |12.23Mb
  server: 192.71.249.78
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: _326 |46.92Mb
  server: 173.234.29.2
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _301 |109.22Mb
  server: 138.186.143.32
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: _306 |32.05Mb
  server: 138.186.143.32
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: Relay_-ğŸ‡ªğŸ‡ªEE_315 |69.88Mb
  server: est01-ss01.tcp-reset-club.net
  type: ss
  port: 8444
  udp: true
  password: AWNeHjukGQWwuFXadw2r6qH7gh4hZ9cj
  cipher: chacha20-ietf-poly1305
- name: _342 |70.19Mb
  server: 172.233.229.91
  type: vmess
  port: 14102
  udp: true
  uuid: 27ba87fc-583f-4763-9060-83cf0b9264db
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: _321 |33.88Mb
  server: 138.186.142.81
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _320 |44.50Mb
  server: 185.82.73.212
  type: ss
  port: 8444
  udp: true
  password: _bypfvq6ra7g4n5yCCR9DoVeGya2XUUS
  cipher: chacha20-ietf-poly1305
- name: _323 |10.77Mb
  server: 82.38.31.199
  type: ss
  port: 8080
  udp: true
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: _331 |296.81Mb
  server: 45.14.245.2
  type: ss
  port: 443
  password: 17ZDORWIliQHuO6WRGHChXYMzdRtAYVP
  cipher: chacha20-ietf-poly1305
- name: _305 |45.64Mb
  server: 156.59.243.6
  type: ss
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: disney_PY |17.20Mb
  server: 38.165.233.93
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: disney_DE |189.02Mb
  server: 89.163.140.136
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ğŸ‡¨ğŸ‡¦CA_364 |62.86Mb
  server: 185.213.23.63
  type: ss
  country: ğŸ‡¨ğŸ‡¦CA
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _316 |12.94Mb
  server: 103.97.203.227
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: disney_SG |17.72Mb
  server: 38.89.142.56
  type: ss
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: Relay_-ğŸ‡¯ğŸ‡µJP_356 |18.96Mb
  server: 160.16.229.223
  type: trojan
  port: 3169
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡­ğŸ‡°HK_330 |28.26Mb
  server: 103.149.182.105
  type: ss
  port: 8388
  password: asd123456
  cipher: chacha20-ietf
- name: ğŸ‡±ğŸ‡¹LT_375 |206.98Mb
  server: 45.87.175.180
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: QCXDxuDlTTMD7jtgHUjIoj
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_377 |200.64Mb
  server: 45.87.175.183
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: netflix_NL |213.42Mb
  server: 45.87.175.185
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: _343 |23.59Mb
  server: 47.242.145.160
  type: vmess
  port: 44457
  uuid: 40290609-2743-4d85-c9c3-4c72dd151b9f
  alterId: 0
  cipher: auto
  network: http
  http-opts:
    method: GET
    path:
    - /
  h2-opts: {}
- name: ğŸ‡²ğŸ‡½MX_383 |34.06Mb
  server: 216.238.87.47
  type: vmess
  country: ğŸ‡²ğŸ‡½MX
  port: 27502
  uuid: b8155ce4-7e08-4c40-800f-8671312b7124
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡±ğŸ‡¹LT_379 |109.33Mb
  server: 45.87.175.185
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡³ğŸ‡±NL_384 |104.44Mb
  server: 193.29.139.188
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 8080
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_392 |149.35Mb
  server: 38.14.99.163
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 59807
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: auto
  network: tcp
  servername: 38.14.99.163
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_ğŸ‡¯ğŸ‡µJP-ğŸ‡¯ğŸ‡µJP_373 |10.86Mb
  server: xray.kk37005.tk
  type: vmess
  country: ğŸ‡¯ğŸ‡µJP
  port: 55919
  uuid: 2e7548bb-7c5b-4d97-d64d-1b2fe4050089
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: ğŸ‡µğŸ‡¹PT_387 |55.61Mb
  server: 185.113.143.186
  type: ss
  country: ğŸ‡µğŸ‡¹PT
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: disney_SG |21.72Mb
  server: 103.248.229.90
  type: ss
  country: ğŸ‡¸ğŸ‡¬SG
  port: 35817
  password: 4VqrUWV7hm
  cipher: aes-256-gcm
- name: ğŸ ZZ_394 |90.06Mb
  server: 185.231.233.112
  type: ss
  country: ğŸ ZZ
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: disney_SG |23.47Mb
  server: 103.248.229.90
  type: ss
  country: ğŸ‡¸ğŸ‡¬SG
  port: 24203
  password: 1GJth1Qjic
  cipher: aes-256-gcm
- name: disney_SG |19.71Mb
  server: 103.248.229.90
  type: ss
  country: ğŸ‡¸ğŸ‡¬SG
  port: 40413
  password: hGpFS8dtyN
  cipher: aes-256-gcm
- name: Relay_ğŸZZ-ğŸ‡®ğŸ‡·IR_395 |26.13Mb
  server: cf.fovi.tk
  type: vmess
  country: ğŸZZ
  port: 443
  uuid: bf67437e-6c90-45ca-abc2-c7240a5ce2aa
  alterId: 0
  cipher: auto
  network: ws
  servername: foxlux.fovi.tk
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /eisasqa
    headers:
      HOST: foxlux.fovi.tk
- name: ğŸ‡±ğŸ‡¹LT_374 |18.08Mb
  server: ltnl16.saint.ydns.eu
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡» LV_381 |54.97Mb
  server: 46.183.217.204
  type: ss
  country: ğŸ‡±ğŸ‡» LV
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - Relay_-ğŸ‡¨ğŸ‡¦CA_296 |69.65Mb
  - _303 |237.17Mb
  - _300 |245.95Mb
  - _312 |235.08Mb
  - _297 |83.33Mb
  - _313 |12.23Mb
  - _326 |46.92Mb
  - _301 |109.22Mb
  - _306 |32.05Mb
  - Relay_-ğŸ‡ªğŸ‡ªEE_315 |69.88Mb
  - _342 |70.19Mb
  - _321 |33.88Mb
  - _320 |44.50Mb
  - _323 |10.77Mb
  - _331 |296.81Mb
  - _305 |45.64Mb
  - disney_PY |17.20Mb
  - disney_DE |189.02Mb
  - ğŸ‡¨ğŸ‡¦CA_364 |62.86Mb
  - _316 |12.94Mb
  - disney_SG |17.72Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_356 |18.96Mb
  - Relay_-ğŸ‡­ğŸ‡°HK_330 |28.26Mb
  - ğŸ‡±ğŸ‡¹LT_375 |206.98Mb
  - ğŸ‡±ğŸ‡¹LT_377 |200.64Mb
  - netflix_NL |213.42Mb
  - _343 |23.59Mb
  - ğŸ‡²ğŸ‡½MX_383 |34.06Mb
  - ğŸ‡±ğŸ‡¹LT_379 |109.33Mb
  - ğŸ‡³ğŸ‡±NL_384 |104.44Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_392 |149.35Mb
  - Relay_ğŸ‡¯ğŸ‡µJP-ğŸ‡¯ğŸ‡µJP_373 |10.86Mb
  - ğŸ‡µğŸ‡¹PT_387 |55.61Mb
  - disney_SG |21.72Mb
  - ğŸ ZZ_394 |90.06Mb
  - disney_SG |23.47Mb
  - disney_SG |19.71Mb
  - Relay_ğŸZZ-ğŸ‡®ğŸ‡·IR_395 |26.13Mb
  - ğŸ‡±ğŸ‡¹LT_374 |18.08Mb
  - ğŸ‡±ğŸ‡» LV_381 |54.97Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - Relay_-ğŸ‡¨ğŸ‡¦CA_296 |69.65Mb
  - _303 |237.17Mb
  - _300 |245.95Mb
  - _312 |235.08Mb
  - _297 |83.33Mb
  - _313 |12.23Mb
  - _326 |46.92Mb
  - _301 |109.22Mb
  - _306 |32.05Mb
  - Relay_-ğŸ‡ªğŸ‡ªEE_315 |69.88Mb
  - _342 |70.19Mb
  - _321 |33.88Mb
  - _320 |44.50Mb
  - _323 |10.77Mb
  - _331 |296.81Mb
  - _305 |45.64Mb
  - disney_PY |17.20Mb
  - disney_DE |189.02Mb
  - ğŸ‡¨ğŸ‡¦CA_364 |62.86Mb
  - _316 |12.94Mb
  - disney_SG |17.72Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_356 |18.96Mb
  - Relay_-ğŸ‡­ğŸ‡°HK_330 |28.26Mb
  - ğŸ‡±ğŸ‡¹LT_375 |206.98Mb
  - ğŸ‡±ğŸ‡¹LT_377 |200.64Mb
  - netflix_NL |213.42Mb
  - _343 |23.59Mb
  - ğŸ‡²ğŸ‡½MX_383 |34.06Mb
  - ğŸ‡±ğŸ‡¹LT_379 |109.33Mb
  - ğŸ‡³ğŸ‡±NL_384 |104.44Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_392 |149.35Mb
  - Relay_ğŸ‡¯ğŸ‡µJP-ğŸ‡¯ğŸ‡µJP_373 |10.86Mb
  - ğŸ‡µğŸ‡¹PT_387 |55.61Mb
  - disney_SG |21.72Mb
  - ğŸ ZZ_394 |90.06Mb
  - disney_SG |23.47Mb
  - disney_SG |19.71Mb
  - Relay_ğŸZZ-ğŸ‡®ğŸ‡·IR_395 |26.13Mb
  - ğŸ‡±ğŸ‡¹LT_374 |18.08Mb
  - ğŸ‡±ğŸ‡» LV_381 |54.97Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
