port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: netflix_IE |220.13Mb
  server: 18.203.220.111
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: netflix_NL |104.93Mb
  server: 151.242.251.137
  type: ss
  port: 8080
  password: o5osZg269v5zHpYjr1xY9s
  cipher: chacha20-ietf-poly1305
- name: disney_PT |636.55Mb
  server: 185.231.233.112
  type: ss
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: netflix_US |16.54Mb
  server: us19-25.998998.best
  type: vmess
  port: 443
  udp: true
  uuid: b376015d-77d9-4482-9aa9-051be76aac65
  alterId: 0
  cipher: auto
  network: ws
  servername: b376015d-77d9-4482-9aa9-051be76aac65.mihomo.baby
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /saoihgreg9384gh8934
    headers:
      Host: b376015d-77d9-4482-9aa9-051be76aac65.mihomo.baby
- name: disney_netflix_DE |232.77Mb
  server: uk2-2.998998.best
  type: vmess
  port: 443
  udp: true
  uuid: b376015d-77d9-4482-9aa9-051be76aac65
  alterId: 0
  cipher: auto
  network: ws
  servername: b376015d-77d9-4482-9aa9-051be76aac65.placeunaorder.fun
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /logcatxiouerd34try9
    headers:
      Host: b376015d-77d9-4482-9aa9-051be76aac65.placeunaorder.fun
- name: _360 |21.28Mb
  server: 103.106.3.82
  type: ss
  port: 443
  udp: true
  password: 4SaCIazlgumYkM8FkPzlmwjpyWBDZFBk
  cipher: chacha20-ietf-poly1305
- name: Relay_-ğŸ‡¸ğŸ‡¬SG_423 |14.46Mb
  server: 153.121.51.29
  type: trojan
  port: 127
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡³ğŸ‡±NL_424 |11.01Mb
  server: 160.16.124.55
  type: trojan
  port: 4054
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: disney_US |35.44Mb
  server: us5.998998.best
  type: vmess
  port: 443
  udp: true
  uuid: b376015d-77d9-4482-9aa9-051be76aac65
  alterId: 0
  cipher: auto
  network: ws
  servername: b376015d-77d9-4482-9aa9-051be76aac65.fasleangles.fun
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /androirfdsreoightrjh
    headers:
      Host: b376015d-77d9-4482-9aa9-051be76aac65.fasleangles.fun
- name: Relay_-ğŸ‡¯ğŸ‡µJP_426 |20.24Mb
  server: 52.195.176.26
  type: trojan
  port: 2145
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: Relay_-ğŸ‡³ğŸ‡±NL_427 |11.49Mb
  server: 160.16.124.55
  type: trojan
  port: 2760
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡³ğŸ‡±NL_428 |10.77Mb
  server: 160.16.63.16
  type: trojan
  port: 4054
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡³ğŸ‡±NL_430 |14.19Mb
  server: 160.16.81.84
  type: trojan
  port: 4054
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: disney_FR |50.84Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 27092
  uuid: a0596ba6-72a3-4366-8992-77088da65bd8
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_-ğŸ‡³ğŸ‡±NL_431 |41.60Mb
  server: 160.16.236.32
  type: trojan
  port: 4054
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¯ğŸ‡µJP_435 |23.02Mb
  server: 153.121.51.29
  type: trojan
  port: 3169
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: disney_HK |23.84Mb
  server: 58.152.25.20
  type: trojan
  port: 443
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: Relay_-ğŸ‡³ğŸ‡±NL_436 |17.14Mb
  server: 160.16.81.84
  type: trojan
  port: 2760
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: ğŸ‡§ğŸ‡·BR_438 |12.56Mb
  server: 38.180.16.86
  type: vmess
  country: ğŸ‡§ğŸ‡·BR
  port: 36104
  uuid: E146A8CB-9D2F-449C-ADCA-8736FB
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡¬ğŸ‡§GB_442 |10.42Mb
  server: 82.38.31.179
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: disney_HK |27.06Mb
  server: 112.118.116.66
  type: trojan
  port: 443
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: netflix_AL |33.56Mb
  server: 87.121.162.249
  type: ss
  country: ğŸ‡­ğŸ‡°HK
  port: 443
  password: JGv616hMWdjfuZ00jYfq7XkBHJZrOBrg
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡²ğŸ‡½MX_453 |35.97Mb
  server: 216.238.89.53
  type: vmess
  country: ğŸ‡²ğŸ‡½MX
  port: 57283
  uuid: 1a5aafc0-6482-451d-fe76-6875b7818579
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡±ğŸ‡¹LT_452 |79.47Mb
  server: 45.87.175.166
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 443
  password: 1RWwXhwfAB5gAEozU4G2Pg
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡®ğŸ‡±IL_450 |11.51Mb
  server: 45.93.95.187
  type: ss
  country: ğŸ‡®ğŸ‡±IL
  port: 8618
  password: 4lUEC91c1d8oeClzDbYpXA
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_461 |53.64Mb
  server: 100.25.219.192
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡­ğŸ‡°HK_444 |111.49Mb
  server: 8.210.134.183
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 3721
  uuid: e72f5c6b-220f-40b3-a115-2d81473458cf
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
  ws-opts:
    path: /
- name: ğŸ‡­ğŸ‡°HK_445 |21.71Mb
  server: 47.242.140.52
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 48219
  uuid: 006893c6-79b1-4c44-94ff-b8bbea065f1f
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
  ws-opts:
    path: /arki?ed=2048
- name: ğŸ‡­ğŸ‡°HK_446 |29.58Mb
  server: 47.242.162.148
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 31813
  uuid: 00308f3b-747a-4710-b2cb-32c8de9785a1
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
  ws-opts:
    path: /arki?ed=2048
- name: ğŸ‡­ğŸ‡°HK_447 |128.68Mb
  server: 47.242.125.104
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 58424
  uuid: 80016399-3178-472e-86e3-129aab31a025
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
  ws-opts:
    path: /arki?ed=2048
- name: ğŸ‡­ğŸ‡°HK_449 |31.36Mb
  server: 47.243.51.237
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 52801
  uuid: ef93f413-9039-4ddb-aefb-2490287df55a
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
  ws-opts:
    path: /arki?ed=2048
- name: disney_US |24.02Mb
  server: 38.84.201.21
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 53487
  uuid: c3c1ec05-df2c-4975-9b42-e9b007564eb1
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡ºğŸ‡¸US_464 |31.18Mb
  server: 74.117.196.232
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 37934
  uuid: 3b475934-cb2a-4d96-b260-5e50cca5d430
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /speedtest
- name: ğŸ‡²ğŸ‡¾MY_454 |27.28Mb
  server: 38.54.98.110
  type: vmess
  country: ğŸ‡²ğŸ‡¾MY
  port: 2052
  uuid: 665d9b8f-153d-4907-adac-de12afd9c851
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: disney_TR |23.61Mb
  server: 185.39.204.161
  type: ss
  country: ğŸ‡¹ğŸ‡·TR
  port: 33563
  password: bSlgCoGhApOb55tIMD0zxY
  cipher: chacha20-ietf-poly1305
- name: disney_TR |11.45Mb
  server: tr-1.stunnel.cc
  type: ss
  country: ğŸ‡¹ğŸ‡·TR
  port: 8444
  password: tunnel-fbrof
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¸ğŸ‡¬SG_455 |11.24Mb
  server: 68.183.178.131
  type: vmess
  country: ğŸ‡¸ğŸ‡¬SG
  port: 58607
  uuid: c11c32cb-27b3-4afa-c0f3-fb250aa4959e
  alterId: 0
  cipher: auto
  network: ws
  servername: www.12333.monster
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /
    headers:
      HOST: www.12333.monster
- name: disney_HK |13.50Mb
  server: 45.136.12.37
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 38141
  uuid: fd291be6-b48d-43a1-da38-66c7f80e2f80
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - netflix_IE |220.13Mb
  - netflix_NL |104.93Mb
  - disney_PT |636.55Mb
  - netflix_US |16.54Mb
  - disney_netflix_DE |232.77Mb
  - _360 |21.28Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_423 |14.46Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_424 |11.01Mb
  - disney_US |35.44Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_426 |20.24Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_427 |11.49Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_428 |10.77Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_430 |14.19Mb
  - disney_FR |50.84Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_431 |41.60Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_435 |23.02Mb
  - disney_HK |23.84Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_436 |17.14Mb
  - ğŸ‡§ğŸ‡·BR_438 |12.56Mb
  - ğŸ‡¬ğŸ‡§GB_442 |10.42Mb
  - disney_HK |27.06Mb
  - netflix_AL |33.56Mb
  - ğŸ‡²ğŸ‡½MX_453 |35.97Mb
  - ğŸ‡±ğŸ‡¹LT_452 |79.47Mb
  - ğŸ‡®ğŸ‡±IL_450 |11.51Mb
  - ğŸ‡ºğŸ‡¸US_461 |53.64Mb
  - ğŸ‡­ğŸ‡°HK_444 |111.49Mb
  - ğŸ‡­ğŸ‡°HK_445 |21.71Mb
  - ğŸ‡­ğŸ‡°HK_446 |29.58Mb
  - ğŸ‡­ğŸ‡°HK_447 |128.68Mb
  - ğŸ‡­ğŸ‡°HK_449 |31.36Mb
  - disney_US |24.02Mb
  - ğŸ‡ºğŸ‡¸US_464 |31.18Mb
  - ğŸ‡²ğŸ‡¾MY_454 |27.28Mb
  - disney_TR |23.61Mb
  - disney_TR |11.45Mb
  - ğŸ‡¸ğŸ‡¬SG_455 |11.24Mb
  - disney_HK |13.50Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - netflix_IE |220.13Mb
  - netflix_NL |104.93Mb
  - disney_PT |636.55Mb
  - netflix_US |16.54Mb
  - disney_netflix_DE |232.77Mb
  - _360 |21.28Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_423 |14.46Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_424 |11.01Mb
  - disney_US |35.44Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_426 |20.24Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_427 |11.49Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_428 |10.77Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_430 |14.19Mb
  - disney_FR |50.84Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_431 |41.60Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_435 |23.02Mb
  - disney_HK |23.84Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_436 |17.14Mb
  - ğŸ‡§ğŸ‡·BR_438 |12.56Mb
  - ğŸ‡¬ğŸ‡§GB_442 |10.42Mb
  - disney_HK |27.06Mb
  - netflix_AL |33.56Mb
  - ğŸ‡²ğŸ‡½MX_453 |35.97Mb
  - ğŸ‡±ğŸ‡¹LT_452 |79.47Mb
  - ğŸ‡®ğŸ‡±IL_450 |11.51Mb
  - ğŸ‡ºğŸ‡¸US_461 |53.64Mb
  - ğŸ‡­ğŸ‡°HK_444 |111.49Mb
  - ğŸ‡­ğŸ‡°HK_445 |21.71Mb
  - ğŸ‡­ğŸ‡°HK_446 |29.58Mb
  - ğŸ‡­ğŸ‡°HK_447 |128.68Mb
  - ğŸ‡­ğŸ‡°HK_449 |31.36Mb
  - disney_US |24.02Mb
  - ğŸ‡ºğŸ‡¸US_464 |31.18Mb
  - ğŸ‡²ğŸ‡¾MY_454 |27.28Mb
  - disney_TR |23.61Mb
  - disney_TR |11.45Mb
  - ğŸ‡¸ğŸ‡¬SG_455 |11.24Mb
  - disney_HK |13.50Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
