port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: _225 |10.49Mb
  server: 66.23.207.82
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _212 |14.09Mb
  server: 173.234.29.2
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _191 |20.49Mb
  server: 147.78.1.27
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _184 |23.08Mb
  server: 147.78.1.230
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _205 |25.43Mb
  server: 138.186.142.81
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _182 |24.69Mb
  server: 138.186.142.80
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _207 |20.45Mb
  server: 176.126.83.158
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _208 |21.03Mb
  server: 38.54.59.180
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _229 |29.06Mb
  server: 190.103.176.32
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _226 |24.78Mb
  server: 46.183.217.204
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _206 |16.65Mb
  server: 154.205.153.107
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _195 |13.98Mb
  server: 38.54.59.107
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡§ğŸ‡ªBE_239 |40.76Mb
  server: 192.71.249.71
  type: ss
  country: ğŸ‡§ğŸ‡ªBE
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ğŸ‡§ğŸ‡ªBE_240 |27.98Mb
  server: 192.71.249.108
  type: ss
  country: ğŸ‡§ğŸ‡ªBE
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_302 |45.70Mb
  server: 104.192.227.162
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: aWqt2Jx9cPauhC7Bb1BdwK
  cipher: chacha20-ietf-poly1305
- name: _234 |20.05Mb
  server: 38.54.57.90
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ªğŸ‡¸ES_253 |42.47Mb
  server: 194.87.45.189
  type: ss
  country: ğŸ‡ªğŸ‡¸ES
  port: 443
  password: XSVQG5Ul3Md0Kutdu819aQ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ªğŸ‡¸ES_254 |46.26Mb
  server: 194.87.45.189
  type: ss
  country: ğŸ‡ªğŸ‡¸ES
  port: 443
  password: VgliqHHPyAsjMKiDU2DReX
  cipher: chacha20-ietf-poly1305
- name: _231 |23.97Mb
  server: 37.143.130.203
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_257 |25.47Mb
  server: 13.40.127.189
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡¸ğŸ‡¬SG_290 |14.26Mb
  server: 104.248.159.99
  type: ss
  country: ğŸ‡¸ğŸ‡¬SG
  port: 8080
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: ğŸ‡¸ğŸ‡¬SG_292 |14.54Mb
  server: 68.183.227.236
  type: ss
  country: ğŸ‡¸ğŸ‡¬SG
  port: 8080
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: ğŸ‡²ğŸ‡¹MT_277 |25.13Mb
  server: 171.22.254.129
  type: ss
  country: ğŸ‡²ğŸ‡¹MT
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - _225 |10.49Mb
  - _212 |14.09Mb
  - _191 |20.49Mb
  - _184 |23.08Mb
  - _205 |25.43Mb
  - _182 |24.69Mb
  - _207 |20.45Mb
  - _208 |21.03Mb
  - _229 |29.06Mb
  - _226 |24.78Mb
  - _206 |16.65Mb
  - _195 |13.98Mb
  - ğŸ‡§ğŸ‡ªBE_239 |40.76Mb
  - ğŸ‡§ğŸ‡ªBE_240 |27.98Mb
  - ğŸ‡ºğŸ‡¸US_302 |45.70Mb
  - _234 |20.05Mb
  - ğŸ‡ªğŸ‡¸ES_253 |42.47Mb
  - ğŸ‡ªğŸ‡¸ES_254 |46.26Mb
  - _231 |23.97Mb
  - ğŸ‡¬ğŸ‡§GB_257 |25.47Mb
  - ğŸ‡¸ğŸ‡¬SG_290 |14.26Mb
  - ğŸ‡¸ğŸ‡¬SG_292 |14.54Mb
  - ğŸ‡²ğŸ‡¹MT_277 |25.13Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - _225 |10.49Mb
  - _212 |14.09Mb
  - _191 |20.49Mb
  - _184 |23.08Mb
  - _205 |25.43Mb
  - _182 |24.69Mb
  - _207 |20.45Mb
  - _208 |21.03Mb
  - _229 |29.06Mb
  - _226 |24.78Mb
  - _206 |16.65Mb
  - _195 |13.98Mb
  - ğŸ‡§ğŸ‡ªBE_239 |40.76Mb
  - ğŸ‡§ğŸ‡ªBE_240 |27.98Mb
  - ğŸ‡ºğŸ‡¸US_302 |45.70Mb
  - _234 |20.05Mb
  - ğŸ‡ªğŸ‡¸ES_253 |42.47Mb
  - ğŸ‡ªğŸ‡¸ES_254 |46.26Mb
  - _231 |23.97Mb
  - ğŸ‡¬ğŸ‡§GB_257 |25.47Mb
  - ğŸ‡¸ğŸ‡¬SG_290 |14.26Mb
  - ğŸ‡¸ğŸ‡¬SG_292 |14.54Mb
  - ğŸ‡²ğŸ‡¹MT_277 |25.13Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
