port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: disney_netflix_US |58.85Mb
  server: 45.150.52.40
  type: vmess
  port: 443
  uuid: c31777a1-2ee6-4864-db4c-a79fcbc8188b
  alterId: 0
  cipher: auto
  network: ws
  servername: xsj011-3.facai2024.com
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /c31777a1
- name: Relay_-ğŸ‡¸ğŸ‡¬SG_164 |11.57Mb
  server: 160.16.153.13
  type: trojan
  port: 3145
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: disney_netflix_US |10.94Mb
  server: 160.16.214.6
  type: trojan
  port: 2890
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¯ğŸ‡µJP_167 |20.42Mb
  server: 160.16.242.183
  type: trojan
  port: 1331
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: disney_netflix_US |11.10Mb
  server: 202.181.103.235
  type: trojan
  port: 2890
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: disney_netflix_NO |16.13Mb
  server: 107.174.114.71
  type: ss
  port: 443
  password: 595HLF3fHUuw0McM51tpvPygSIB1uf4D
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_HK |28.20Mb
  server: 8.218.105.196
  type: vmess
  port: 52752
  uuid: 925bdbf5-72be-4437-bebf-441c61089f6b
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
- name: disney_HK |34.82Mb
  server: 58.152.25.20
  type: trojan
  port: 443
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: disney_US |417.64Mb
  server: 185.221.23.251
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 29431
  uuid: 8b78363e-3c3a-44ab-f0d8-f13d950c8572
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_HK |23.24Mb
  server: 58.152.30.120
  type: trojan
  port: 443
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: disney_netflix_SG |150.10Mb
  server: 103.36.91.32
  type: ss
  port: 8388
  udp: true
  password: asd123456
  cipher: chacha20-ietf
- name: disney_HK |29.34Mb
  server: 58.152.110.82
  type: trojan
  port: 443
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: disney_netflix_FR |246.16Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 27092
  uuid: a0596ba6-72a3-4366-8992-77088da65bd8
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡²ğŸ‡½MX_222 |38.28Mb
  server: 216.238.89.53
  type: vmess
  country: ğŸ‡²ğŸ‡½MX
  port: 57283
  uuid: 1a5aafc0-6482-451d-fe76-6875b7818579
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_FR |37.73Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 40433
  uuid: d8fd8955-78db-49ba-d86f-3e4729f6ac4d
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_HK |14.64Mb
  server: 58.152.25.242
  type: trojan
  port: 443
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: disney_netflix_NL |204.83Mb
  server: 82.38.31.184
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_NL |226.82Mb
  server: 51.15.17.169
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: disney_netflix_US |28.88Mb
  server: 195.66.27.148
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 28709
  password: hShp1Km0NcFSmSigc8ozky
  cipher: chacha20-ietf-poly1305
- name: netflix_IE |15.77Mb
  server: 146.70.90.196
  type: ss
  country: ğŸ‡®ğŸ‡ªIE
  port: 17454
  password: u8gp148iz90ddoo6ms37
  cipher: aes-128-gcm
- name: disney_netflix_US |11.12Mb
  server: 209.74.86.194
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 14936
  password: ppgtoOHdm7cszGunBWBTqQ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡­ğŸ‡°HK_199 |113.04Mb
  server: 8.218.116.26
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 32228
  uuid: e4767e9f-ed00-4f31-a984-a918bdd9b09c
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_US |39.34Mb
  server: 38.14.99.163
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 59807
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: auto
  network: tcp
  servername: 38.14.99.163
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_US |71.41Mb
  server: 47.253.197.26
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 12056
  uuid: dd7be7f1-38ff-45e6-f1e5-b20c2190f527
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_RU |35.32Mb
  server: 81.200.158.206
  type: ss
  country: ğŸ‡·ğŸ‡ºRU
  port: 1080
  password: AqZbt1QCs3ngEfXo1p7T-w
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡·ğŸ‡ºRU_223 |64.61Mb
  server: 45.140.169.26
  type: ss
  country: ğŸ‡·ğŸ‡ºRU
  port: 1012
  password: 7ae4e68cf77f6089
  cipher: aes-256-gcm
- name: ğŸ‡·ğŸ‡ºRU_226 |63.77Mb
  server: 185.22.154.19
  type: ss
  country: ğŸ‡·ğŸ‡ºRU
  port: 1281
  password: f34579d0148b2581
  cipher: aes-256-gcm
- name: disney_netflix_SE |44.37Mb
  server: 91.186.217.246
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 31764
  password: Ftc17VH9ZXQON5vslJCYmv
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_230 |13.27Mb
  server: 209.74.81.149
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 21166
  password: q92MrrP9oJ3lMEzbQFpyuU
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_HK |18.69Mb
  server: 45.136.12.37
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 38141
  uuid: fd291be6-b48d-43a1-da38-66c7f80e2f80
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_US |21.99Mb
  server: cf.fovi.tk
  type: vmess
  country: ğŸZZ
  port: 443
  uuid: bf67437e-6c90-45ca-abc2-c7240a5ce2aa
  alterId: 0
  cipher: auto
  network: ws
  servername: foxlux.fovi.tk
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /eisasqa
    headers:
      HOST: foxlux.fovi.tk
- name: disney_netflix_NL |120.84Mb
  server: 109.71.246.210
  type: ss
  country: ğŸ‡·ğŸ‡ºRU
  port: 56689
  password: YQCSKoCF3QazW8YlvDBWA4
  cipher: chacha20-ietf-poly1305
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - disney_netflix_US |58.85Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_164 |11.57Mb
  - disney_netflix_US |10.94Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_167 |20.42Mb
  - disney_netflix_US |11.10Mb
  - disney_netflix_NO |16.13Mb
  - disney_netflix_HK |28.20Mb
  - disney_HK |34.82Mb
  - disney_US |417.64Mb
  - disney_HK |23.24Mb
  - disney_netflix_SG |150.10Mb
  - disney_HK |29.34Mb
  - disney_netflix_FR |246.16Mb
  - ğŸ‡²ğŸ‡½MX_222 |38.28Mb
  - disney_netflix_FR |37.73Mb
  - disney_HK |14.64Mb
  - disney_netflix_NL |204.83Mb
  - disney_netflix_NL |226.82Mb
  - disney_netflix_US |28.88Mb
  - netflix_IE |15.77Mb
  - disney_netflix_US |11.12Mb
  - ğŸ‡­ğŸ‡°HK_199 |113.04Mb
  - disney_netflix_US |39.34Mb
  - disney_netflix_US |71.41Mb
  - disney_RU |35.32Mb
  - ğŸ‡·ğŸ‡ºRU_223 |64.61Mb
  - ğŸ‡·ğŸ‡ºRU_226 |63.77Mb
  - disney_netflix_SE |44.37Mb
  - ğŸ‡ºğŸ‡¸US_230 |13.27Mb
  - disney_netflix_HK |18.69Mb
  - disney_netflix_US |21.99Mb
  - disney_netflix_NL |120.84Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - disney_netflix_US |58.85Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_164 |11.57Mb
  - disney_netflix_US |10.94Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_167 |20.42Mb
  - disney_netflix_US |11.10Mb
  - disney_netflix_NO |16.13Mb
  - disney_netflix_HK |28.20Mb
  - disney_HK |34.82Mb
  - disney_US |417.64Mb
  - disney_HK |23.24Mb
  - disney_netflix_SG |150.10Mb
  - disney_HK |29.34Mb
  - disney_netflix_FR |246.16Mb
  - ğŸ‡²ğŸ‡½MX_222 |38.28Mb
  - disney_netflix_FR |37.73Mb
  - disney_HK |14.64Mb
  - disney_netflix_NL |204.83Mb
  - disney_netflix_NL |226.82Mb
  - disney_netflix_US |28.88Mb
  - netflix_IE |15.77Mb
  - disney_netflix_US |11.12Mb
  - ğŸ‡­ğŸ‡°HK_199 |113.04Mb
  - disney_netflix_US |39.34Mb
  - disney_netflix_US |71.41Mb
  - disney_RU |35.32Mb
  - ğŸ‡·ğŸ‡ºRU_223 |64.61Mb
  - ğŸ‡·ğŸ‡ºRU_226 |63.77Mb
  - disney_netflix_SE |44.37Mb
  - ğŸ‡ºğŸ‡¸US_230 |13.27Mb
  - disney_netflix_HK |18.69Mb
  - disney_netflix_US |21.99Mb
  - disney_netflix_NL |120.84Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
