port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: ' |39.86Mb'
  server: 207.90.237.163
  type: ss
  port: 808
  udp: true
  password: tvX1v#NSFP_LG_bJ
  cipher: chacha20-ietf-poly1305
- name: _210 |117.23Mb
  server: 78.129.140.11
  type: ss
  port: 443
  udp: true
  password: jXdarwYmQNTjm8BdLv1ZlY
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¨ğŸ‡¦CA_217
  server: 138.197.141.58
  type: ss
  country: ğŸ‡¨ğŸ‡¦CA
  port: 8080
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: ğŸ‡¨ğŸ‡¦CA_218
  server: 23.162.200.125
  type: vmess
  country: ğŸ‡¨ğŸ‡¦CA
  port: 2201
  uuid: 86eab4ac-dbe2-4e2f-a490-4fccade87c35
  alterId: 0
  cipher: auto
  network: tcp
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡¦ğŸ‡ªAE_215
  server: 89.35.119.87
  type: ss
  country: ğŸ‡¦ğŸ‡ªAE
  port: 5904
  password: 5TZnwPb23pQS39lIucspJw
  cipher: chacha20-ietf-poly1305
- name: Relay_-ğŸ‡¸ğŸ‡¬SG_214 |31.06Mb
  server: spevoy.missionsec.us
  type: trojan
  port: 443
  udp: true
  password: R3SuZDAZXDO3FYqxwK36l7gpSIBTFCxlzc89a7qg3S9p8BOCeACSFaA8nxeD2ZlT5Nl4O
  skip-cert-verify: true
- name: ğŸ‡©ğŸ‡ªDE_220 |15.34Mb
  server: 93.186.201.64
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 57456
  password: fe166c5b3465540f
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ªğŸ‡¸ES_222 |24.83Mb
  server: 5.188.181.201
  type: ss
  country: ğŸ‡ªğŸ‡¸ES
  port: 9020
  password: BNmAXXxAHYpTRdzu
  cipher: aes-256-cfb
- name: ğŸ‡¨ğŸ‡³CN_219
  server: 120.210.205.59
  type: vmess
  country: ğŸ‡¨ğŸ‡³CN
  port: 50002
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 64
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡ªğŸ‡¸ES_221
  server: 194.87.45.189
  type: ss
  country: ğŸ‡ªğŸ‡¸ES
  port: 443
  password: cUgm3LyixNv6AElxYBPkoP
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡«ğŸ‡·FR_223
  server: 51.15.17.169
  type: ss
  country: ğŸ‡«ğŸ‡·FR
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: Pool_ğŸ‡¬ğŸ‡§GB_228
  server: 79.127.233.170
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ğŸ‡«ğŸ‡·FR_225
  server: 83.147.216.70
  type: ss
  country: ğŸ‡«ğŸ‡·FR
  port: 64519
  password: Mal9DeKnSFhULd5Nbpkae0
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡«ğŸ‡·FR_224 |164.23Mb
  server: 83.147.216.70
  type: ss
  country: ğŸ‡«ğŸ‡·FR
  port: 64519
  password: KaKeuUdiSZJ1vl2jU8GnfY
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_227 |10.81Mb
  server: 212.102.53.79
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: shadowsocks
  cipher: aes-128-gcm
- name: ğŸ‡«ğŸ‡·FR_226
  server: 83.147.216.70
  type: ss
  country: ğŸ‡«ğŸ‡·FR
  port: 64519
  password: YXgS8ComTam7qoesPlzlMo
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_229 |13.22Mb
  server: 212.102.53.80
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: shadowsocks
  cipher: aes-128-gcm
- name: ğŸ‡®ğŸ‡ªIE_231
  server: 108.129.160.134
  type: ss
  country: ğŸ‡®ğŸ‡ªIE
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡±ğŸ‡¹LT_237 |22.03Mb
  server: 45.87.175.199
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: 4a2rfixophdjffa8KVA4Aa
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸ‡±ğŸ‡¹LT-ğŸ‡³ğŸ‡±NL_238 |11.69Mb
  server: 45.87.175.185
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¯ğŸ‡µJP_235
  server: 160.16.123.124
  type: ss
  country: ğŸ‡¯ğŸ‡µJP
  port: 10087
  password: '10086'
  cipher: aes-128-gcm
- name: ğŸ‡±ğŸ‡¹LT_239
  server: 45.87.175.157
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: 1RWwXhwfAB5gAEozU4G2Pg
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_240 |15.75Mb
  server: 45.87.175.157
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: 4a2rfixophdjffa8KVA4Aa
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_241 |10.40Mb
  server: 45.87.175.164
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_242 |10.93Mb
  server: 45.87.175.166
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: 4a2rfixophdjffa8KVA4Aa
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸ‡±ğŸ‡¹LT-ğŸ‡³ğŸ‡±NL_243
  server: 45.87.175.181
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: 4a2rfixophdjffa8KVA4Aa
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_244
  server: 45.87.175.157
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡³ğŸ‡±NL_245
  server: 103.104.247.45
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 8080
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡³ğŸ‡±NL_248
  server: 193.29.139.202
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 8080
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡³ğŸ‡±NL_247
  server: 193.29.139.227
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 8080
  password: 4a2rfixophdjffa8KVA4Aa
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡³ğŸ‡±NL_249 |10.75Mb
  server: 79.127.227.198
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 990
  password: f8f7aCzcPKbsF8p3
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡µğŸ‡±PL_251
  server: 217.30.10.18
  type: ss
  country: ğŸ‡µğŸ‡±PL
  port: 9073
  password: daFYagqDdBdA6VTX
  cipher: aes-256-cfb
- name: ğŸ‡µğŸ‡±PL_252
  server: 217.30.10.18
  type: ss
  country: ğŸ‡µğŸ‡±PL
  port: 9025
  password: XPtzA9sCug3SPR4c
  cipher: aes-256-cfb
- name: ğŸ‡µğŸ‡±PL_253
  server: 217.30.10.70
  type: ss
  country: ğŸ‡µğŸ‡±PL
  port: 9073
  password: daFYagqDdBdA6VTX
  cipher: aes-256-cfb
- name: ğŸ‡µğŸ‡±PL_254
  server: 217.30.10.18
  type: ss
  country: ğŸ‡µğŸ‡±PL
  port: 9011
  password: M3t2ZEQcMGRWBjRa
  cipher: aes-256-cfb
- name: ğŸ‡µğŸ‡±PL_255
  server: 217.30.10.18
  type: ss
  country: ğŸ‡µğŸ‡±PL
  port: 9032
  password: UWZQeLRWnkqgkseq
  cipher: aes-256-cfb
- name: ğŸ‡µğŸ‡±PL_256
  server: 45.144.49.140
  type: ss
  country: ğŸ‡µğŸ‡±PL
  port: 57456
  password: 360e21d21977dc11
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡µğŸ‡±PL_257
  server: 217.30.10.18
  type: ss
  country: ğŸ‡µğŸ‡±PL
  port: 9003
  password: JdmRK9gMEqFgs8nP
  cipher: aes-256-cfb
- name: ğŸ‡µğŸ‡±PL_258
  server: 217.30.10.70
  type: ss
  country: ğŸ‡µğŸ‡±PL
  port: 9088
  password: f8npKgNzdkss2ytn
  cipher: aes-256-cfb
- name: ğŸ‡µğŸ‡±PL_259
  server: 217.30.10.18
  type: ss
  country: ğŸ‡µğŸ‡±PL
  port: 9014
  password: KnJGad3FqTvjqbaX
  cipher: aes-256-cfb
- name: ğŸ‡µğŸ‡±PL_261 |13.48Mb
  server: 217.30.10.18
  type: ss
  country: ğŸ‡µğŸ‡±PL
  port: 9027
  password: EXN3S3eQpjE7EJu8
  cipher: aes-256-cfb
- name: ğŸ‡µğŸ‡±PL_260
  server: 217.30.10.70
  type: ss
  country: ğŸ‡µğŸ‡±PL
  port: 9041
  password: U6qnYRhfyDmn8sgn
  cipher: aes-256-cfb
- name: ğŸ‡µğŸ‡±PL_262
  server: 217.30.10.18
  type: ss
  country: ğŸ‡µğŸ‡±PL
  port: 9064
  password: cp8pRSUAyLhTfVWH
  cipher: aes-256-cfb
- name: ğŸ‡µğŸ‡±PL_263
  server: 217.30.10.18
  type: ss
  country: ğŸ‡µğŸ‡±PL
  port: 9056
  password: rNBfNuuANFCAk7KB
  cipher: aes-256-cfb
- name: ğŸ‡µğŸ‡±PL_264
  server: 217.30.10.18
  type: ss
  country: ğŸ‡µğŸ‡±PL
  port: 9042
  password: S7KwUu7yBy58S3Ga
  cipher: aes-256-cfb
- name: ğŸ‡µğŸ‡±PL_266
  server: 217.30.10.18
  type: ss
  country: ğŸ‡µğŸ‡±PL
  port: 9031
  password: BwcAUZk8hUFAkDGN
  cipher: aes-256-cfb
- name: ğŸ‡µğŸ‡±PL_267
  server: 217.30.10.70
  type: ss
  country: ğŸ‡µğŸ‡±PL
  port: 9064
  password: cp8pRSUAyLhTfVWH
  cipher: aes-256-cfb
- name: ğŸ‡·ğŸ‡´RO_268
  server: 89.46.238.35
  type: ss
  country: ğŸ‡·ğŸ‡´RO
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ğŸ‡·ğŸ‡ºRU_269
  server: 94.159.96.245
  type: ss
  country: ğŸ‡·ğŸ‡ºRU
  port: 11902
  password: gCEeT2wSWw71yvL8LYFHXz
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡·ğŸ‡ºRU_271 |142.74Mb
  server: 94.159.96.245
  type: ss
  country: ğŸ‡·ğŸ‡ºRU
  port: 11902
  password: nr24KAeCIdBtLZqsTKxZX6
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡·ğŸ‡ºRU_272 |167.36Mb
  server: 94.159.96.245
  type: ss
  country: ğŸ‡·ğŸ‡ºRU
  port: 11902
  password: NSTk9sFhybwuon6uBupMm9
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡·ğŸ‡ºRU_273
  server: 94.159.96.245
  type: ss
  country: ğŸ‡·ğŸ‡ºRU
  port: 11902
  password: DbqAtRexqtqOYyiLiAmuSA
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡·ğŸ‡ºRU_274
  server: 94.159.96.245
  type: ss
  country: ğŸ‡·ğŸ‡ºRU
  port: 11902
  password: 4aSfGt013tPveNbZx44fr0
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡·ğŸ‡ºRU_275
  server: 94.159.96.245
  type: ss
  country: ğŸ‡·ğŸ‡ºRU
  port: 11902
  password: 0w5eUNs7skQuwsYvwI1wOb
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡·ğŸ‡ºRU_276
  server: 94.159.96.245
  type: ss
  country: ğŸ‡·ğŸ‡ºRU
  port: 11902
  password: hYWkDRffZWVhir3riEMtGJ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡·ğŸ‡ºRU_277
  server: 94.159.96.245
  type: ss
  country: ğŸ‡·ğŸ‡ºRU
  port: 11902
  password: 3zMT7XQjbCLEPbnNLSJ9j7
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡°ğŸ‡·KR_236 |10.30Mb
  server: 221.139.79.57
  type: ss
  country: ğŸ‡°ğŸ‡·KR
  port: 37008
  password: qwerREWQ@@
  cipher: aes-256-cfb
- name: ğŸ‡·ğŸ‡ºRU_279
  server: 94.159.96.245
  type: ss
  country: ğŸ‡·ğŸ‡ºRU
  port: 11902
  password: Zu4q35iKuGXqlS1xjMAFMU
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¸ğŸ‡ªSE_280 |13.11Mb
  server: 13.53.37.208
  type: ss
  country: ğŸ‡¸ğŸ‡ªSE
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡¸ğŸ‡ªSE_281
  server: 51.21.244.34
  type: ss
  country: ğŸ‡¸ğŸ‡ªSE
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡¸ğŸ‡¬SG_282 |36.24Mb
  server: 68.183.227.216
  type: ss
  country: ğŸ‡¸ğŸ‡¬SG
  port: 8080
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: ğŸ‡¸ğŸ‡¬SG_284
  server: 64.176.85.73
  type: ss
  country: ğŸ‡¸ğŸ‡¬SG
  port: 1866
  password: oXGp1+ihlfKg826H
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¹ğŸ‡·TR_285 |76.86Mb
  server: 45.89.52.66
  type: ss
  country: ğŸ‡¹ğŸ‡·TR
  port: 9014
  password: KnJGad3FqTvjqbaX
  cipher: aes-256-cfb
- name: ğŸ‡ºğŸ‡¸US_290
  server: 23.157.40.5
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 6679
  password: TEzjfAYq2IjtuoS
  cipher: aes-256-gcm
- name: ğŸ‡ºğŸ‡¸US_292
  server: 23.157.40.5
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 5500
  password: KixLvKzwjekG00rm
  cipher: aes-256-gcm
- name: ğŸ‡¹ğŸ‡¼TW_287
  server: 223.165.4.173
  type: ss
  country: ğŸ‡¹ğŸ‡¼TW
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ğŸ‡ºğŸ‡¸US_295 |68.82Mb
  server: 23.157.40.101
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 8009
  password: XKFKl2rULjIp74
  cipher: aes-256-gcm
- name: ğŸ‡ºğŸ‡¸US_293
  server: 64.74.163.218
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 990
  password: f8f7aCzcPKbsF8p3
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¹ğŸ‡·TR_286
  server: 83.217.9.4
  type: ss
  country: ğŸ‡¹ğŸ‡·TR
  port: 443
  password: v2LBhok5lvjR
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_297 |127.18Mb
  server: 23.157.40.5
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 3306
  password: Y6R9pAtvxxzmGC
  cipher: aes-256-gcm
- name: ğŸ‡ºğŸ‡¸US_294
  server: 13.222.168.151
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡ºğŸ‡¸US_296
  server: 37.19.198.160
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: shadowsocks
  cipher: aes-128-gcm
- name: ğŸ‡ºğŸ‡¸US_302 |14.29Mb
  server: 154.44.15.133
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 44642
  password: iHapGY8XoW
  cipher: aes-256-gcm
- name: ğŸ‡ºğŸ‡¸US_299
  server: 173.244.56.9
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: shadowsocks
  cipher: aes-128-gcm
- name: ğŸ‡ºğŸ‡¸US_301
  server: 159.203.72.194
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 8443
  password: Y2PhBJtc03EnomK4Atb9h6q2cgnAcPV/SxRY5D9wCgU=
  cipher: aes-256-gcm
- name: Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_304
  server: 193.124.24.247
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 6508
  uuid: b68fead5-5b0b-43a1-c34a-804467f0f368
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡ºğŸ‡¸US_298
  server: 149.22.87.241
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: shadowsocks
  cipher: aes-128-gcm
- name: Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_305
  server: 193.124.24.247
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 6511
  uuid: 5ef4e89b-262f-4c74-e793-c7332079f251
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡ºğŸ‡¸US_303 |12.68Mb
  server: 38.107.226.159
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 7307
  password: FoOiGlkAA9yPEGP
  cipher: aes-256-gcm
- name: Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_306
  server: 193.124.24.247
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 6507
  uuid: 3003e094-707c-4dbb-faca-4b8d579bc604
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_307
  server: 193.124.24.247
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 6510
  uuid: 8f44f672-e53b-44fb-b502-c886d37107b5
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_US
  server: 193.124.24.230
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 6505
  uuid: f77456b5-5a82-45ba-a941-1a83c09a1f41
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_309 |32.53Mb
  server: 193.124.24.230
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 6507
  uuid: 5d12135d-1676-490c-b490-b6e624c431a3
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_310 |15.24Mb
  server: 193.124.24.247
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 6502
  uuid: 242f22a3-29d9-4a94-d8ba-88043f2e1921
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Pool_ğŸ‡»ğŸ‡³VN_311
  server: 103.186.154.74
  type: ss
  country: ğŸ‡»ğŸ‡³VN
  port: 38388
  password: Xn8jKdmDM00IeO%#$#fJAMtsEAEUOpH/YWYtYqDFnT0SV
  cipher: aes-256-cfb
- name: ğŸ‡·ğŸ‡ºRU_270
  server: 94.159.96.245
  type: ss
  country: ğŸ‡·ğŸ‡ºRU
  port: 11902
  password: nUgYlUHlKanZuaMAYCCpXa
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡·ğŸ‡ºRU_278
  server: 94.159.96.245
  type: ss
  country: ğŸ‡·ğŸ‡ºRU
  port: 11902
  password: MK6xB3NTB3h9MRNZxzJyjJ
  cipher: chacha20-ietf-poly1305
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - ' |39.86Mb'
  - _210 |117.23Mb
  - ğŸ‡¨ğŸ‡¦CA_217
  - ğŸ‡¨ğŸ‡¦CA_218
  - ğŸ‡¦ğŸ‡ªAE_215
  - Relay_-ğŸ‡¸ğŸ‡¬SG_214 |31.06Mb
  - ğŸ‡©ğŸ‡ªDE_220 |15.34Mb
  - ğŸ‡ªğŸ‡¸ES_222 |24.83Mb
  - ğŸ‡¨ğŸ‡³CN_219
  - ğŸ‡ªğŸ‡¸ES_221
  - ğŸ‡«ğŸ‡·FR_223
  - Pool_ğŸ‡¬ğŸ‡§GB_228
  - ğŸ‡«ğŸ‡·FR_225
  - ğŸ‡«ğŸ‡·FR_224 |164.23Mb
  - ğŸ‡¬ğŸ‡§GB_227 |10.81Mb
  - ğŸ‡«ğŸ‡·FR_226
  - ğŸ‡¬ğŸ‡§GB_229 |13.22Mb
  - ğŸ‡®ğŸ‡ªIE_231
  - ğŸ‡±ğŸ‡¹LT_237 |22.03Mb
  - Relay_ğŸ‡±ğŸ‡¹LT-ğŸ‡³ğŸ‡±NL_238 |11.69Mb
  - ğŸ‡¯ğŸ‡µJP_235
  - ğŸ‡±ğŸ‡¹LT_239
  - ğŸ‡±ğŸ‡¹LT_240 |15.75Mb
  - ğŸ‡±ğŸ‡¹LT_241 |10.40Mb
  - ğŸ‡±ğŸ‡¹LT_242 |10.93Mb
  - Relay_ğŸ‡±ğŸ‡¹LT-ğŸ‡³ğŸ‡±NL_243
  - ğŸ‡±ğŸ‡¹LT_244
  - ğŸ‡³ğŸ‡±NL_245
  - ğŸ‡³ğŸ‡±NL_248
  - ğŸ‡³ğŸ‡±NL_247
  - ğŸ‡³ğŸ‡±NL_249 |10.75Mb
  - ğŸ‡µğŸ‡±PL_251
  - ğŸ‡µğŸ‡±PL_252
  - ğŸ‡µğŸ‡±PL_253
  - ğŸ‡µğŸ‡±PL_254
  - ğŸ‡µğŸ‡±PL_255
  - ğŸ‡µğŸ‡±PL_256
  - ğŸ‡µğŸ‡±PL_257
  - ğŸ‡µğŸ‡±PL_258
  - ğŸ‡µğŸ‡±PL_259
  - ğŸ‡µğŸ‡±PL_261 |13.48Mb
  - ğŸ‡µğŸ‡±PL_260
  - ğŸ‡µğŸ‡±PL_262
  - ğŸ‡µğŸ‡±PL_263
  - ğŸ‡µğŸ‡±PL_264
  - ğŸ‡µğŸ‡±PL_266
  - ğŸ‡µğŸ‡±PL_267
  - ğŸ‡·ğŸ‡´RO_268
  - ğŸ‡·ğŸ‡ºRU_269
  - ğŸ‡·ğŸ‡ºRU_271 |142.74Mb
  - ğŸ‡·ğŸ‡ºRU_272 |167.36Mb
  - ğŸ‡·ğŸ‡ºRU_273
  - ğŸ‡·ğŸ‡ºRU_274
  - ğŸ‡·ğŸ‡ºRU_275
  - ğŸ‡·ğŸ‡ºRU_276
  - ğŸ‡·ğŸ‡ºRU_277
  - ğŸ‡°ğŸ‡·KR_236 |10.30Mb
  - ğŸ‡·ğŸ‡ºRU_279
  - ğŸ‡¸ğŸ‡ªSE_280 |13.11Mb
  - ğŸ‡¸ğŸ‡ªSE_281
  - ğŸ‡¸ğŸ‡¬SG_282 |36.24Mb
  - ğŸ‡¸ğŸ‡¬SG_284
  - ğŸ‡¹ğŸ‡·TR_285 |76.86Mb
  - ğŸ‡ºğŸ‡¸US_290
  - ğŸ‡ºğŸ‡¸US_292
  - ğŸ‡¹ğŸ‡¼TW_287
  - ğŸ‡ºğŸ‡¸US_295 |68.82Mb
  - ğŸ‡ºğŸ‡¸US_293
  - ğŸ‡¹ğŸ‡·TR_286
  - ğŸ‡ºğŸ‡¸US_297 |127.18Mb
  - ğŸ‡ºğŸ‡¸US_294
  - ğŸ‡ºğŸ‡¸US_296
  - ğŸ‡ºğŸ‡¸US_302 |14.29Mb
  - ğŸ‡ºğŸ‡¸US_299
  - ğŸ‡ºğŸ‡¸US_301
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_304
  - ğŸ‡ºğŸ‡¸US_298
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_305
  - ğŸ‡ºğŸ‡¸US_303 |12.68Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_306
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_307
  - disney_US
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_309 |32.53Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_310 |15.24Mb
  - Pool_ğŸ‡»ğŸ‡³VN_311
  - ğŸ‡·ğŸ‡ºRU_270
  - ğŸ‡·ğŸ‡ºRU_278
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - ' |39.86Mb'
  - _210 |117.23Mb
  - ğŸ‡¨ğŸ‡¦CA_217
  - ğŸ‡¨ğŸ‡¦CA_218
  - ğŸ‡¦ğŸ‡ªAE_215
  - Relay_-ğŸ‡¸ğŸ‡¬SG_214 |31.06Mb
  - ğŸ‡©ğŸ‡ªDE_220 |15.34Mb
  - ğŸ‡ªğŸ‡¸ES_222 |24.83Mb
  - ğŸ‡¨ğŸ‡³CN_219
  - ğŸ‡ªğŸ‡¸ES_221
  - ğŸ‡«ğŸ‡·FR_223
  - Pool_ğŸ‡¬ğŸ‡§GB_228
  - ğŸ‡«ğŸ‡·FR_225
  - ğŸ‡«ğŸ‡·FR_224 |164.23Mb
  - ğŸ‡¬ğŸ‡§GB_227 |10.81Mb
  - ğŸ‡«ğŸ‡·FR_226
  - ğŸ‡¬ğŸ‡§GB_229 |13.22Mb
  - ğŸ‡®ğŸ‡ªIE_231
  - ğŸ‡±ğŸ‡¹LT_237 |22.03Mb
  - Relay_ğŸ‡±ğŸ‡¹LT-ğŸ‡³ğŸ‡±NL_238 |11.69Mb
  - ğŸ‡¯ğŸ‡µJP_235
  - ğŸ‡±ğŸ‡¹LT_239
  - ğŸ‡±ğŸ‡¹LT_240 |15.75Mb
  - ğŸ‡±ğŸ‡¹LT_241 |10.40Mb
  - ğŸ‡±ğŸ‡¹LT_242 |10.93Mb
  - Relay_ğŸ‡±ğŸ‡¹LT-ğŸ‡³ğŸ‡±NL_243
  - ğŸ‡±ğŸ‡¹LT_244
  - ğŸ‡³ğŸ‡±NL_245
  - ğŸ‡³ğŸ‡±NL_248
  - ğŸ‡³ğŸ‡±NL_247
  - ğŸ‡³ğŸ‡±NL_249 |10.75Mb
  - ğŸ‡µğŸ‡±PL_251
  - ğŸ‡µğŸ‡±PL_252
  - ğŸ‡µğŸ‡±PL_253
  - ğŸ‡µğŸ‡±PL_254
  - ğŸ‡µğŸ‡±PL_255
  - ğŸ‡µğŸ‡±PL_256
  - ğŸ‡µğŸ‡±PL_257
  - ğŸ‡µğŸ‡±PL_258
  - ğŸ‡µğŸ‡±PL_259
  - ğŸ‡µğŸ‡±PL_261 |13.48Mb
  - ğŸ‡µğŸ‡±PL_260
  - ğŸ‡µğŸ‡±PL_262
  - ğŸ‡µğŸ‡±PL_263
  - ğŸ‡µğŸ‡±PL_264
  - ğŸ‡µğŸ‡±PL_266
  - ğŸ‡µğŸ‡±PL_267
  - ğŸ‡·ğŸ‡´RO_268
  - ğŸ‡·ğŸ‡ºRU_269
  - ğŸ‡·ğŸ‡ºRU_271 |142.74Mb
  - ğŸ‡·ğŸ‡ºRU_272 |167.36Mb
  - ğŸ‡·ğŸ‡ºRU_273
  - ğŸ‡·ğŸ‡ºRU_274
  - ğŸ‡·ğŸ‡ºRU_275
  - ğŸ‡·ğŸ‡ºRU_276
  - ğŸ‡·ğŸ‡ºRU_277
  - ğŸ‡°ğŸ‡·KR_236 |10.30Mb
  - ğŸ‡·ğŸ‡ºRU_279
  - ğŸ‡¸ğŸ‡ªSE_280 |13.11Mb
  - ğŸ‡¸ğŸ‡ªSE_281
  - ğŸ‡¸ğŸ‡¬SG_282 |36.24Mb
  - ğŸ‡¸ğŸ‡¬SG_284
  - ğŸ‡¹ğŸ‡·TR_285 |76.86Mb
  - ğŸ‡ºğŸ‡¸US_290
  - ğŸ‡ºğŸ‡¸US_292
  - ğŸ‡¹ğŸ‡¼TW_287
  - ğŸ‡ºğŸ‡¸US_295 |68.82Mb
  - ğŸ‡ºğŸ‡¸US_293
  - ğŸ‡¹ğŸ‡·TR_286
  - ğŸ‡ºğŸ‡¸US_297 |127.18Mb
  - ğŸ‡ºğŸ‡¸US_294
  - ğŸ‡ºğŸ‡¸US_296
  - ğŸ‡ºğŸ‡¸US_302 |14.29Mb
  - ğŸ‡ºğŸ‡¸US_299
  - ğŸ‡ºğŸ‡¸US_301
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_304
  - ğŸ‡ºğŸ‡¸US_298
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_305
  - ğŸ‡ºğŸ‡¸US_303 |12.68Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_306
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_307
  - disney_US
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_309 |32.53Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_310 |15.24Mb
  - Pool_ğŸ‡»ğŸ‡³VN_311
  - ğŸ‡·ğŸ‡ºRU_270
  - ğŸ‡·ğŸ‡ºRU_278
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
