port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: Relay_-ğŸ‡ºğŸ‡¸US_161 |104.28Mb
  server: 141.193.213.169
  type: vmess
  port: 443
  udp: true
  uuid: a9716062-d7f6-43f2-95d6-6f340097e7f6
  alterId: 0
  cipher: auto
  network: ws
  servername: ya536t05uqu69mbm.usgggggggoehfo.top
  http-opts: {}
  h2-opts: {}
  tls: true
  ws-opts:
    path: /bpjc/us1
    headers:
      Host: ya536t05uqu69mbm.usgggggggoehfo.top
- name: Relay_-ğŸ‡ºğŸ‡¸US_160 |18.57Mb
  server: 141.193.213.168
  type: vmess
  port: 443
  udp: true
  uuid: a9716062-d7f6-43f2-95d6-6f340097e7f6
  alterId: 0
  cipher: auto
  network: ws
  servername: ya536t05uqu69mbm.usgggggggoehfo.top
  http-opts: {}
  h2-opts: {}
  tls: true
  ws-opts:
    path: /bpjc/us1
    headers:
      Host: ya536t05uqu69mbm.usgggggggoehfo.top
- name: Relay_-ğŸ‡ºğŸ‡¸US_159 |17.57Mb
  server: 141.193.213.123
  type: vmess
  port: 443
  udp: true
  uuid: a9716062-d7f6-43f2-95d6-6f340097e7f6
  alterId: 0
  cipher: auto
  network: ws
  servername: ya536t05uqu69mbm.usgggggggoehfo.top
  http-opts: {}
  h2-opts: {}
  tls: true
  ws-opts:
    path: /bpjc/us1
    headers:
      Host: ya536t05uqu69mbm.usgggggggoehfo.top
- name: Relay_-ğŸ‡·ğŸ‡ºRU_164 |66.06Mb
  server: 141.193.213.173
  type: vmess
  port: 2086
  udp: true
  uuid: a9716062-d7f6-43f2-95d6-6f340097e7f6
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /4397hy/843uhbp
    headers:
      Host: er250901.bptimecsgo.xyz
- name: Relay_-ğŸ‡·ğŸ‡ºRU_166 |62.36Mb
  server: 141.193.213.62
  type: vmess
  port: 2086
  udp: true
  uuid: a9716062-d7f6-43f2-95d6-6f340097e7f6
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /4397hy/843uhbp
    headers:
      Host: er250901.bptimecsgo.xyz
- name: Relay_-ğŸ‡ºğŸ‡¸US_171 |18.01Mb
  server: 141.193.213.199
  type: trojan
  port: 443
  udp: true
  password: a9716062-d7f6-43f2-95d6-6f340097e7f6
  sni: 1cyq93vs4amcu625.ukgogo202511.top
  ws-opts:
    path: /images
    headers:
      Host: 1cyq93vs4amcu625.ukgogo202511.top
  network: ws
- name: Relay_-ğŸ‡·ğŸ‡ºRU_163 |71.47Mb
  server: digitalocean.com
  type: vmess
  port: 2086
  udp: true
  uuid: a9716062-d7f6-43f2-95d6-6f340097e7f6
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /4397hy/843uhbp
    headers:
      Host: er250901.bptimecsgo.xyz
- name: Relay_-ğŸ‡ºğŸ‡¸US_165 |162.96Mb
  server: 38.14.99.179
  type: vmess
  port: 59807
  udp: true
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Pool__170 |30.80Mb
  server: 23.247.137.64
  type: trojan
  port: 443
  udp: true
  password: 3c4e10af98c30972
  sni: n2.gladns.com
  network: grpc
  grpc-opts:
    grpc-service-name: db
- name: disney_netflix_NL |227.68Mb
  server: 151.242.251.137
  type: ss
  port: 8080
  password: o5osZg269v5zHpYjr1xY9s
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_NO |14.65Mb
  server: 107.174.114.71
  type: ss
  port: 443
  password: 595HLF3fHUuw0McM51tpvPygSIB1uf4D
  cipher: chacha20-ietf-poly1305
- name: netflix_TR |89.75Mb
  server: 23.227.38.84
  type: trojan
  port: 443
  udp: true
  password: a9716062-d7f6-43f2-95d6-6f340097e7f6
  sni: 9l3ysxf7rj3nz549.tkgogocsgo.top
  ws-opts:
    path: /images
    headers:
      Host: 9l3ysxf7rj3nz549.tkgogocsgo.top
  network: ws
- name: Relay_-ğŸ‡¯ğŸ‡µJP_189 |59.75Mb
  server: 141.193.213.60
  type: trojan
  port: 443
  udp: true
  password: a9716062-d7f6-43f2-95d6-6f340097e7f6
  sni: 5qfg26y3xj2zjlmr.catimecsgo.xyz
  ws-opts:
    path: /images
    headers:
      Host: 5qfg26y3xj2zjlmr.catimecsgo.xyz
  network: ws
- name: Relay_-ğŸ‡³ğŸ‡±NL_172 |47.02Mb
  server: 160.16.131.243
  type: trojan
  port: 2890
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¸ğŸ‡¬SG_176 |11.93Mb
  server: 160.16.131.243
  type: trojan
  port: 127
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡³ğŸ‡±NL_178 |10.86Mb
  server: 160.16.116.227
  type: trojan
  port: 2890
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: disney_HK |21.68Mb
  server: 58.152.30.120
  type: trojan
  port: 443
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: Relay_-ğŸ‡ºğŸ‡¸US_196 |20.48Mb
  server: 23.227.38.43
  type: trojan
  port: 443
  udp: true
  password: a9716062-d7f6-43f2-95d6-6f340097e7f6
  sni: 1cyq93vs4amcu625.ukgogo202511.top
  ws-opts:
    path: /images
    headers:
      Host: 1cyq93vs4amcu625.ukgogo202511.top
  network: ws
- name: Relay_-ğŸ‡¸ğŸ‡¬SG_180 |11.68Mb
  server: 160.16.107.37
  type: trojan
  port: 507
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡ºğŸ‡¸US_199 |38.06Mb
  server: 23.227.38.166
  type: trojan
  port: 443
  udp: true
  password: a9716062-d7f6-43f2-95d6-6f340097e7f6
  sni: ni5qwas2a6ysde23.usgogo202510.top
  ws-opts:
    path: /images
    headers:
      Host: ni5qwas2a6ysde23.usgogo202510.top
  network: ws
- name: Relay_-ğŸ‡¸ğŸ‡¬SG_182 |11.65Mb
  server: 153.121.44.99
  type: trojan
  port: 507
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡·ğŸ‡ºRU_183 |84.26Mb
  server: aeryy5gfrp630ww1.lovebaipiao.net
  type: trojan
  port: 443
  udp: true
  password: a9716062-d7f6-43f2-95d6-6f340097e7f6
  sni: aeryy5gfrp630ww1.lovebaipiao.net
  ws-opts:
    path: /images
    headers:
      Host: aeryy5gfrp630ww1.lovebaipiao.net
  network: ws
- name: Relay_-ğŸ‡¯ğŸ‡µJP_193 |17.42Mb
  server: 160.16.72.33
  type: trojan
  port: 3093
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡³ğŸ‡±NL_194 |46.72Mb
  server: 160.16.151.196
  type: trojan
  port: 2890
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: disney_HK |11.69Mb
  server: 58.152.25.20
  type: trojan
  port: 443
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: Relay_-ğŸ‡¯ğŸ‡µJP_200 |22.41Mb
  server: 160.16.87.174
  type: trojan
  port: 3169
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡³ğŸ‡±NL_201 |54.04Mb
  server: 160.16.57.238
  type: trojan
  port: 4054
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡ºğŸ‡¸US_209 |36.71Mb
  server: 23.227.38.113
  type: trojan
  port: 443
  udp: true
  password: a9716062-d7f6-43f2-95d6-6f340097e7f6
  sni: ni5qwas2a6ysde23.usgogo202510.top
  ws-opts:
    path: /images
    headers:
      Host: ni5qwas2a6ysde23.usgogo202510.top
  network: ws
- name: Relay_-ğŸ‡¯ğŸ‡µJP_202 |19.54Mb
  server: 160.16.70.180
  type: trojan
  port: 1331
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: disney_FR |63.33Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 40433
  uuid: d8fd8955-78db-49ba-d86f-3e4729f6ac4d
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_FR |52.57Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 27092
  uuid: a0596ba6-72a3-4366-8992-77088da65bd8
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_-ğŸ‡³ğŸ‡±NL_205 |42.20Mb
  server: 160.16.236.32
  type: trojan
  port: 4054
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: disney_netflix_NL |236.56Mb
  server: 82.38.31.190
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_NL |230.44Mb
  server: 82.38.31.218
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: disney_HK |28.94Mb
  server: 58.152.110.154
  type: trojan
  port: 443
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: disney_netflix_NL |249.18Mb
  server: 82.38.31.210
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_NL |234.22Mb
  server: 82.38.31.179
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: netflix_AL |45.75Mb
  server: 87.121.162.249
  type: ss
  country: ğŸ‡­ğŸ‡°HK
  port: 443
  password: JGv616hMWdjfuZ00jYfq7XkBHJZrOBrg
  cipher: chacha20-ietf-poly1305
- name: netflix_MX |175.87Mb
  server: 216.238.89.53
  type: vmess
  country: ğŸ‡²ğŸ‡½MX
  port: 57283
  uuid: 1a5aafc0-6482-451d-fe76-6875b7818579
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_-ğŸ‡¯ğŸ‡µJP_192 |59.56Mb
  server: cloudflare.182682.xyz
  type: trojan
  port: 443
  udp: true
  password: a9716062-d7f6-43f2-95d6-6f340097e7f6
  sni: 5qfg26y3xj2zjlmr.catimecsgo.xyz
  ws-opts:
    path: /images
    headers:
      Host: 5qfg26y3xj2zjlmr.catimecsgo.xyz
  network: ws
- name: disney_netflix_NL |87.95Mb
  server: 109.71.246.210
  type: ss
  country: ğŸ‡·ğŸ‡ºRU
  port: 56689
  password: YQCSKoCF3QazW8YlvDBWA4
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_236 |43.03Mb
  server: 104.192.226.106
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: netflix_HK |27.23Mb
  server: 8.218.116.26
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 32228
  uuid: e4767e9f-ed00-4f31-a984-a918bdd9b09c
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_US |162.76Mb
  server: 38.14.99.163
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 59807
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: auto
  network: tcp
  servername: 38.14.99.163
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: netflix_LT |74.27Mb
  server: 45.12.136.170
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: l668XHPejoSNNuD66BYzyehaCpZexiF7
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡²ğŸ‡¾MY_232 |32.21Mb
  server: 38.54.98.110
  type: vmess
  country: ğŸ‡²ğŸ‡¾MY
  port: 2052
  uuid: 665d9b8f-153d-4907-adac-de12afd9c851
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: ğŸ‡¸ğŸ‡¬SG_235 |11.31Mb
  server: 68.183.178.131
  type: vmess
  country: ğŸ‡¸ğŸ‡¬SG
  port: 58607
  uuid: c11c32cb-27b3-4afa-c0f3-fb250aa4959e
  alterId: 0
  cipher: auto
  network: ws
  servername: www.12333.monster
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /
    headers:
      HOST: www.12333.monster
- name: disney_HK |22.58Mb
  server: 45.136.12.37
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 38141
  uuid: fd291be6-b48d-43a1-da38-66c7f80e2f80
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_US |105.13Mb
  server: cf.fovi.tk
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  uuid: bf67437e-6c90-45ca-abc2-c7240a5ce2aa
  alterId: 0
  cipher: auto
  network: ws
  servername: foxlux.fovi.tk
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /eisasqa
    headers:
      HOST: foxlux.fovi.tk
- name: netflix_BE |46.09Mb
  server: 45.83.20.206
  type: ss
  port: 443
  udp: true
  password: g5RQoxQuVtnFv3Xxsa8edPisXNPnyWKy
  cipher: chacha20-ietf-poly1305
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - Relay_-ğŸ‡ºğŸ‡¸US_161 |104.28Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_160 |18.57Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_159 |17.57Mb
  - Relay_-ğŸ‡·ğŸ‡ºRU_164 |66.06Mb
  - Relay_-ğŸ‡·ğŸ‡ºRU_166 |62.36Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_171 |18.01Mb
  - Relay_-ğŸ‡·ğŸ‡ºRU_163 |71.47Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_165 |162.96Mb
  - Pool__170 |30.80Mb
  - disney_netflix_NL |227.68Mb
  - disney_netflix_NO |14.65Mb
  - netflix_TR |89.75Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_189 |59.75Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_172 |47.02Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_176 |11.93Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_178 |10.86Mb
  - disney_HK |21.68Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_196 |20.48Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_180 |11.68Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_199 |38.06Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_182 |11.65Mb
  - Relay_-ğŸ‡·ğŸ‡ºRU_183 |84.26Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_193 |17.42Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_194 |46.72Mb
  - disney_HK |11.69Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_200 |22.41Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_201 |54.04Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_209 |36.71Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_202 |19.54Mb
  - disney_FR |63.33Mb
  - disney_netflix_FR |52.57Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_205 |42.20Mb
  - disney_netflix_NL |236.56Mb
  - disney_netflix_NL |230.44Mb
  - disney_HK |28.94Mb
  - disney_netflix_NL |249.18Mb
  - disney_netflix_NL |234.22Mb
  - netflix_AL |45.75Mb
  - netflix_MX |175.87Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_192 |59.56Mb
  - disney_netflix_NL |87.95Mb
  - ğŸ‡ºğŸ‡¸US_236 |43.03Mb
  - netflix_HK |27.23Mb
  - disney_netflix_US |162.76Mb
  - netflix_LT |74.27Mb
  - ğŸ‡²ğŸ‡¾MY_232 |32.21Mb
  - ğŸ‡¸ğŸ‡¬SG_235 |11.31Mb
  - disney_HK |22.58Mb
  - disney_netflix_US |105.13Mb
  - netflix_BE |46.09Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - Relay_-ğŸ‡ºğŸ‡¸US_161 |104.28Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_160 |18.57Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_159 |17.57Mb
  - Relay_-ğŸ‡·ğŸ‡ºRU_164 |66.06Mb
  - Relay_-ğŸ‡·ğŸ‡ºRU_166 |62.36Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_171 |18.01Mb
  - Relay_-ğŸ‡·ğŸ‡ºRU_163 |71.47Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_165 |162.96Mb
  - Pool__170 |30.80Mb
  - disney_netflix_NL |227.68Mb
  - disney_netflix_NO |14.65Mb
  - netflix_TR |89.75Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_189 |59.75Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_172 |47.02Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_176 |11.93Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_178 |10.86Mb
  - disney_HK |21.68Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_196 |20.48Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_180 |11.68Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_199 |38.06Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_182 |11.65Mb
  - Relay_-ğŸ‡·ğŸ‡ºRU_183 |84.26Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_193 |17.42Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_194 |46.72Mb
  - disney_HK |11.69Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_200 |22.41Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_201 |54.04Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_209 |36.71Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_202 |19.54Mb
  - disney_FR |63.33Mb
  - disney_netflix_FR |52.57Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_205 |42.20Mb
  - disney_netflix_NL |236.56Mb
  - disney_netflix_NL |230.44Mb
  - disney_HK |28.94Mb
  - disney_netflix_NL |249.18Mb
  - disney_netflix_NL |234.22Mb
  - netflix_AL |45.75Mb
  - netflix_MX |175.87Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_192 |59.56Mb
  - disney_netflix_NL |87.95Mb
  - ğŸ‡ºğŸ‡¸US_236 |43.03Mb
  - netflix_HK |27.23Mb
  - disney_netflix_US |162.76Mb
  - netflix_LT |74.27Mb
  - ğŸ‡²ğŸ‡¾MY_232 |32.21Mb
  - ğŸ‡¸ğŸ‡¬SG_235 |11.31Mb
  - disney_HK |22.58Mb
  - disney_netflix_US |105.13Mb
  - netflix_BE |46.09Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
