port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: _232 |10.23Mb
  server: 15.235.85.147
  type: vmess
  port: 443
  udp: true
  uuid: 03fcc618-b93d-6796-6aed-8a38c975d581
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: linkvws
    headers:
      Host: pelang.org
- name: _221 |10.07Mb
  server: 196.196.192.58
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: Relay_-ğŸ‡³ğŸ‡±NL_227 |10.13Mb
  server: 151.242.251.137
  type: ss
  port: 8080
  udp: true
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: _213 |10.53Mb
  server: 45.87.175.158
  type: ss
  port: 8080
  udp: true
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: Relay_-ğŸ‡³ğŸ‡±NL_203 |10.15Mb
  server: 151.242.251.152
  type: ss
  port: 8080
  udp: true
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: _211 |10.19Mb
  server: 185.26.236.196
  type: ss
  port: 8443
  udp: true
  password: hvce9IJx3AVhMgstYwBD4i
  cipher: chacha20-ietf-poly1305
- name: _223 |10.06Mb
  server: 109.61.46.43
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _217 |10.09Mb
  server: 109.61.125.161
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _208 |47.17Mb
  server: 37.143.129.98
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¨ğŸ‡¦CA_265 |10.26Mb
  server: 79.127.200.162
  type: ss
  country: ğŸ‡¨ğŸ‡¦CA
  port: 990
  password: f8f7aCzcPKbsF8p3
  cipher: chacha20-ietf-poly1305
- name: _210 |40.48Mb
  server: 38.54.59.180
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¨ğŸ‡¦CA_266 |10.51Mb
  server: 147.182.146.81
  type: ss
  country: ğŸ‡¨ğŸ‡¦CA
  port: 8080
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: Relay_ğŸ‡¨ğŸ‡¦CA-ğŸ‡¨ğŸ‡¦CA_267 |10.18Mb
  server: 79.127.200.169
  type: ss
  country: ğŸ‡¨ğŸ‡¦CA
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸ‡¨ğŸ‡¦CA-ğŸ‡²ğŸ‡©MD_271 |10.47Mb
  server: 45.154.204.7
  type: ss
  country: ğŸ‡¨ğŸ‡¦CA
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¦ğŸ‡¹AT_256 |10.09Mb
  server: 192.121.170.52
  type: vmess
  country: ğŸ‡¦ğŸ‡¹AT
  port: 20522
  uuid: 08f870ed-520c-483a-bdec-c4884aad4665
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
  ws-opts:
    path: /telegram_@sswia
- name: _240 |10.03Mb
  server: 47.243.48.161
  type: vmess
  port: 42108
  udp: true
  uuid: 0c6a09a1-21b2-4891-8769-aeff793cccf6
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /arki?ed=2048
- name: ğŸ‡§ğŸ‡ªBE_260 |10.08Mb
  server: 192.71.249.108
  type: ss
  country: ğŸ‡§ğŸ‡ªBE
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ğŸ‡¨ğŸ‡·CR_282 |10.36Mb
  server: 145.14.131.99
  type: ss
  country: ğŸ‡¨ğŸ‡·CR
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¦ğŸ‡·AR_254 |13.46Mb
  server: 190.103.176.32
  type: ss
  country: ğŸ‡¦ğŸ‡·AR
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡©ğŸ‡ªDE_292 |10.46Mb
  server: 81.19.141.45
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 443
  password: MrrxToZtXWAIfxUMsJlHYd
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¦ğŸ‡ºAU_258 |10.28Mb
  server: 3.26.167.161
  type: ss
  country: ğŸ‡¦ğŸ‡ºAU
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡©ğŸ‡ªDE_313 |187.30Mb
  server: 85.195.101.122
  type: vmess
  country: ğŸ‡©ğŸ‡ªDE
  port: 40878
  uuid: f3d4167e-b15e-4e46-82e9-9286ef93fda7
  alterId: 0
  cipher: auto
  network: tcp
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡ªğŸ‡¨EC_317 |41.34Mb
  server: 38.165.231.25
  type: ss
  country: ğŸ‡ªğŸ‡¨EC
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡©ğŸ‡°DK_315 |10.51Mb
  server: 121.127.45.165
  type: ss
  country: ğŸ‡©ğŸ‡°DK
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_370 |25.70Mb
  server: 89.185.84.185
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: isJjdU9iV5tmvJa2JDOM4I
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_372 |24.63Mb
  server: 89.185.84.185
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: QpjCHeJf3ig519DjNBytqn
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_376 |10.25Mb
  server: 146.70.61.37
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: ğŸ‡¬ğŸ‡§GB_371 |10.26Mb
  server: 141.98.101.179
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: shadowsocks
  cipher: aes-128-gcm
- name: ğŸ‡¬ğŸ‡§GB_373 |67.84Mb
  server: 89.185.84.185
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: V9gJ8OOLGreg27vYV5HSd3
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_377 |10.38Mb
  server: 62.100.205.100
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_386 |75.63Mb
  server: 89.185.84.185
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: 2kCbzhE1x9M8mfqzDEBeyL
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_391 |32.16Mb
  server: 89.185.84.185
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: uQ61t9OowCuNc2aaU3YRAP
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_389 |124.31Mb
  server: 89.185.84.185
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: dpRpqTAaO4ozrbcm2iN4qs
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_392 |141.22Mb
  server: 89.185.84.185
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: Lm0gSCFwvlkyYeU4nSGbUM
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_393 |176.11Mb
  server: 89.185.84.185
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: iEc68ruj1qOx8hjh1KWZmc
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡®ğŸ‡·IR_431 |10.05Mb
  server: 151.242.251.147
  type: ss
  country: ğŸ‡®ğŸ‡·IR
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡®ğŸ‡¹IT_443 |11.45Mb
  server: 45.134.13.75
  type: ss
  country: ğŸ‡®ğŸ‡¹IT
  port: 443
  password: 2c0dbfc8-c0c1-404e-8ae8-3e7a40bd9e7a
  cipher: aes-256-gcm
- name: ğŸ‡²ğŸ‡½MX_499 |10.47Mb
  server: 147.78.1.230
  type: ss
  country: ğŸ‡²ğŸ‡½MX
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_459 |16.35Mb
  server: 45.87.175.181
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: 1RWwXhwfAB5gAEozU4G2Pg
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_480 |43.05Mb
  server: 45.87.175.188
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: 4a2rfixophdjffa8KVA4Aa
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¯ğŸ‡µJP_447 |10.36Mb
  server: 172.105.199.91
  type: ss
  country: ğŸ‡¯ğŸ‡µJP
  port: 8080
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: ğŸ‡±ğŸ‡¹LT_485 |71.38Mb
  server: 45.87.175.10
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡³ğŸ‡±NL_514 |10.10Mb
  server: 193.29.139.209
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 8080
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸ‡¨ğŸ‡­CH-ğŸ‡¨ğŸ‡­CH_277 |10.03Mb
  server: h110vpnch.outlinekeys.net
  type: ss
  country: ğŸ‡¨ğŸ‡­CH
  port: 4248
  password: XbUOyIsySmsSUDENO70DvJ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡³ğŸ‡±NL_522 |10.12Mb
  server: 193.29.139.157
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 8080
  password: 4a2rfixophdjffa8KVA4Aa
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡µğŸ‡¦PA_530 |44.42Mb
  server: 138.186.142.81
  type: ss
  country: ğŸ‡µğŸ‡¦PA
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡³ğŸ‡´NO_529 |10.01Mb
  server: 185.213.23.63
  type: ss
  country: ğŸ‡³ğŸ‡´NO
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡µğŸ‡±PL_542 |30.35Mb
  server: 77.83.246.74
  type: ss
  country: ğŸ‡µğŸ‡±PL
  port: 443
  password: JiRKsqK7CeIuIX63UZ9hWY
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡µğŸ‡±PL_543 |62.54Mb
  server: 77.83.246.74
  type: ss
  country: ğŸ‡µğŸ‡±PL
  port: 443
  password: enopqMuMmRq50a5wZkUrqs
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡µğŸ‡±PL_544 |11.28Mb
  server: 217.30.10.18
  type: ss
  country: ğŸ‡µğŸ‡±PL
  port: 9024
  password: BejrQvtu9sqUeNuZ
  cipher: aes-256-cfb
- name: ğŸ‡µğŸ‡±PL_568 |12.84Mb
  server: 217.30.10.70
  type: ss
  country: ğŸ‡µğŸ‡±PL
  port: 9037
  password: TN2YqghxeFDKZfLU
  cipher: aes-256-cfb
- name: ğŸ‡µğŸ‡±PL_546 |21.51Mb
  server: 77.83.246.74
  type: ss
  country: ğŸ‡µğŸ‡±PL
  port: 443
  password: nbWYdobo4cvDTKVJYkviI5
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡µğŸ‡±PL_572 |12.95Mb
  server: 217.30.10.70
  type: ss
  country: ğŸ‡µğŸ‡±PL
  port: 9020
  password: BNmAXXxAHYpTRdzu
  cipher: aes-256-cfb
- name: ğŸ‡·ğŸ‡ºRU_600 |12.19Mb
  server: 95.163.176.37
  type: ss
  country: ğŸ‡·ğŸ‡ºRU
  port: 8506
  password: 3gLomcz6tImeLUj9g7g6by
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡·ğŸ‡ºRU_605 |13.52Mb
  server: 95.163.176.37
  type: ss
  country: ğŸ‡·ğŸ‡ºRU
  port: 8506
  password: eUh4lSpi7nOYj0vSrqLUh0
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_484 |10.00Mb
  server: ltnl17.saint.ydns.eu
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: _248 |10.16Mb
  server: 47.243.39.20
  type: vmess
  port: 36512
  udp: true
  uuid: cc13ac4b-d38f-4ebb-8a2a-73cf3aff5650
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /arki?ed=2048
- name: Pool_ğŸ‡­ğŸ‡°HK_406 |437.00Mb
  server: 150.107.46.21
  type: ssr
  country: ğŸ‡­ğŸ‡°HK
  port: 8083
  password: iFqnzSscN
  cipher: aes-256-cfb
  protocol: origin
  obfs: tls1.2_ticket_auth
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - _232 |10.23Mb
  - _221 |10.07Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_227 |10.13Mb
  - _213 |10.53Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_203 |10.15Mb
  - _211 |10.19Mb
  - _223 |10.06Mb
  - _217 |10.09Mb
  - _208 |47.17Mb
  - ğŸ‡¨ğŸ‡¦CA_265 |10.26Mb
  - _210 |40.48Mb
  - ğŸ‡¨ğŸ‡¦CA_266 |10.51Mb
  - Relay_ğŸ‡¨ğŸ‡¦CA-ğŸ‡¨ğŸ‡¦CA_267 |10.18Mb
  - Relay_ğŸ‡¨ğŸ‡¦CA-ğŸ‡²ğŸ‡©MD_271 |10.47Mb
  - ğŸ‡¦ğŸ‡¹AT_256 |10.09Mb
  - _240 |10.03Mb
  - ğŸ‡§ğŸ‡ªBE_260 |10.08Mb
  - ğŸ‡¨ğŸ‡·CR_282 |10.36Mb
  - ğŸ‡¦ğŸ‡·AR_254 |13.46Mb
  - ğŸ‡©ğŸ‡ªDE_292 |10.46Mb
  - ğŸ‡¦ğŸ‡ºAU_258 |10.28Mb
  - ğŸ‡©ğŸ‡ªDE_313 |187.30Mb
  - ğŸ‡ªğŸ‡¨EC_317 |41.34Mb
  - ğŸ‡©ğŸ‡°DK_315 |10.51Mb
  - ğŸ‡¬ğŸ‡§GB_370 |25.70Mb
  - ğŸ‡¬ğŸ‡§GB_372 |24.63Mb
  - ğŸ‡¬ğŸ‡§GB_376 |10.25Mb
  - ğŸ‡¬ğŸ‡§GB_371 |10.26Mb
  - ğŸ‡¬ğŸ‡§GB_373 |67.84Mb
  - ğŸ‡¬ğŸ‡§GB_377 |10.38Mb
  - ğŸ‡¬ğŸ‡§GB_386 |75.63Mb
  - ğŸ‡¬ğŸ‡§GB_391 |32.16Mb
  - ğŸ‡¬ğŸ‡§GB_389 |124.31Mb
  - ğŸ‡¬ğŸ‡§GB_392 |141.22Mb
  - ğŸ‡¬ğŸ‡§GB_393 |176.11Mb
  - ğŸ‡®ğŸ‡·IR_431 |10.05Mb
  - ğŸ‡®ğŸ‡¹IT_443 |11.45Mb
  - ğŸ‡²ğŸ‡½MX_499 |10.47Mb
  - ğŸ‡±ğŸ‡¹LT_459 |16.35Mb
  - ğŸ‡±ğŸ‡¹LT_480 |43.05Mb
  - ğŸ‡¯ğŸ‡µJP_447 |10.36Mb
  - ğŸ‡±ğŸ‡¹LT_485 |71.38Mb
  - ğŸ‡³ğŸ‡±NL_514 |10.10Mb
  - Relay_ğŸ‡¨ğŸ‡­CH-ğŸ‡¨ğŸ‡­CH_277 |10.03Mb
  - ğŸ‡³ğŸ‡±NL_522 |10.12Mb
  - ğŸ‡µğŸ‡¦PA_530 |44.42Mb
  - ğŸ‡³ğŸ‡´NO_529 |10.01Mb
  - ğŸ‡µğŸ‡±PL_542 |30.35Mb
  - ğŸ‡µğŸ‡±PL_543 |62.54Mb
  - ğŸ‡µğŸ‡±PL_544 |11.28Mb
  - ğŸ‡µğŸ‡±PL_568 |12.84Mb
  - ğŸ‡µğŸ‡±PL_546 |21.51Mb
  - ğŸ‡µğŸ‡±PL_572 |12.95Mb
  - ğŸ‡·ğŸ‡ºRU_600 |12.19Mb
  - ğŸ‡·ğŸ‡ºRU_605 |13.52Mb
  - ğŸ‡±ğŸ‡¹LT_484 |10.00Mb
  - _248 |10.16Mb
  - Pool_ğŸ‡­ğŸ‡°HK_406 |437.00Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - _232 |10.23Mb
  - _221 |10.07Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_227 |10.13Mb
  - _213 |10.53Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_203 |10.15Mb
  - _211 |10.19Mb
  - _223 |10.06Mb
  - _217 |10.09Mb
  - _208 |47.17Mb
  - ğŸ‡¨ğŸ‡¦CA_265 |10.26Mb
  - _210 |40.48Mb
  - ğŸ‡¨ğŸ‡¦CA_266 |10.51Mb
  - Relay_ğŸ‡¨ğŸ‡¦CA-ğŸ‡¨ğŸ‡¦CA_267 |10.18Mb
  - Relay_ğŸ‡¨ğŸ‡¦CA-ğŸ‡²ğŸ‡©MD_271 |10.47Mb
  - ğŸ‡¦ğŸ‡¹AT_256 |10.09Mb
  - _240 |10.03Mb
  - ğŸ‡§ğŸ‡ªBE_260 |10.08Mb
  - ğŸ‡¨ğŸ‡·CR_282 |10.36Mb
  - ğŸ‡¦ğŸ‡·AR_254 |13.46Mb
  - ğŸ‡©ğŸ‡ªDE_292 |10.46Mb
  - ğŸ‡¦ğŸ‡ºAU_258 |10.28Mb
  - ğŸ‡©ğŸ‡ªDE_313 |187.30Mb
  - ğŸ‡ªğŸ‡¨EC_317 |41.34Mb
  - ğŸ‡©ğŸ‡°DK_315 |10.51Mb
  - ğŸ‡¬ğŸ‡§GB_370 |25.70Mb
  - ğŸ‡¬ğŸ‡§GB_372 |24.63Mb
  - ğŸ‡¬ğŸ‡§GB_376 |10.25Mb
  - ğŸ‡¬ğŸ‡§GB_371 |10.26Mb
  - ğŸ‡¬ğŸ‡§GB_373 |67.84Mb
  - ğŸ‡¬ğŸ‡§GB_377 |10.38Mb
  - ğŸ‡¬ğŸ‡§GB_386 |75.63Mb
  - ğŸ‡¬ğŸ‡§GB_391 |32.16Mb
  - ğŸ‡¬ğŸ‡§GB_389 |124.31Mb
  - ğŸ‡¬ğŸ‡§GB_392 |141.22Mb
  - ğŸ‡¬ğŸ‡§GB_393 |176.11Mb
  - ğŸ‡®ğŸ‡·IR_431 |10.05Mb
  - ğŸ‡®ğŸ‡¹IT_443 |11.45Mb
  - ğŸ‡²ğŸ‡½MX_499 |10.47Mb
  - ğŸ‡±ğŸ‡¹LT_459 |16.35Mb
  - ğŸ‡±ğŸ‡¹LT_480 |43.05Mb
  - ğŸ‡¯ğŸ‡µJP_447 |10.36Mb
  - ğŸ‡±ğŸ‡¹LT_485 |71.38Mb
  - ğŸ‡³ğŸ‡±NL_514 |10.10Mb
  - Relay_ğŸ‡¨ğŸ‡­CH-ğŸ‡¨ğŸ‡­CH_277 |10.03Mb
  - ğŸ‡³ğŸ‡±NL_522 |10.12Mb
  - ğŸ‡µğŸ‡¦PA_530 |44.42Mb
  - ğŸ‡³ğŸ‡´NO_529 |10.01Mb
  - ğŸ‡µğŸ‡±PL_542 |30.35Mb
  - ğŸ‡µğŸ‡±PL_543 |62.54Mb
  - ğŸ‡µğŸ‡±PL_544 |11.28Mb
  - ğŸ‡µğŸ‡±PL_568 |12.84Mb
  - ğŸ‡µğŸ‡±PL_546 |21.51Mb
  - ğŸ‡µğŸ‡±PL_572 |12.95Mb
  - ğŸ‡·ğŸ‡ºRU_600 |12.19Mb
  - ğŸ‡·ğŸ‡ºRU_605 |13.52Mb
  - ğŸ‡±ğŸ‡¹LT_484 |10.00Mb
  - _248 |10.16Mb
  - Pool_ğŸ‡­ğŸ‡°HK_406 |437.00Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
