port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: ğŸ‡ºğŸ‡¸US_863 |54.67Mb
  server: 3.129.194.11
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡ºğŸ‡¸US_931 |55.45Mb
  server: 18.190.219.74
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡ºğŸ‡¸US_841 |55.51Mb
  server: 3.133.131.192
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡ºğŸ‡¸US_661 |55.42Mb
  server: 3.148.213.139
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: _75 |192.21Mb
  server: 71.19.148.143
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: p78naCf2EfOlRSLTX0wFVx
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_316 |10.06Mb
  server: 89.185.84.185
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: QHJQzz2ZCOBXnwrcvj8uFX
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_432 |15.86Mb
  server: 89.185.84.185
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: bmoj6orLj0ipdovNVUJzVL
  cipher: chacha20-ietf-poly1305
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - ğŸ‡ºğŸ‡¸US_863 |54.67Mb
  - ğŸ‡ºğŸ‡¸US_931 |55.45Mb
  - ğŸ‡ºğŸ‡¸US_841 |55.51Mb
  - ğŸ‡ºğŸ‡¸US_661 |55.42Mb
  - _75 |192.21Mb
  - ğŸ‡¬ğŸ‡§GB_316 |10.06Mb
  - ğŸ‡¬ğŸ‡§GB_432 |15.86Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - ğŸ‡ºğŸ‡¸US_863 |54.67Mb
  - ğŸ‡ºğŸ‡¸US_931 |55.45Mb
  - ğŸ‡ºğŸ‡¸US_841 |55.51Mb
  - ğŸ‡ºğŸ‡¸US_661 |55.42Mb
  - _75 |192.21Mb
  - ğŸ‡¬ğŸ‡§GB_316 |10.06Mb
  - ğŸ‡¬ğŸ‡§GB_432 |15.86Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
