port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: disney_netflix_GB |159.63Mb
  server: koma-yt.pages.dev
  type: trojan
  port: 8443
  udp: true
  password: 8r<[9'l6hAO#8ZQi
  sni: Koma-YT.PAGeS.Dev
  ws-opts:
    path: /tro8sFW1S91B6sZrM1?ed=2560
    headers:
      Host: Koma-YT.PAGeS.Dev
  network: ws
- name: _166 |32.60Mb
  server: 103.231.73.211
  type: ss
  port: 57456
  udp: true
  password: 8afc633eb63227e9
  cipher: chacha20-ietf-poly1305
- name: Relay_-ðŸ‡¸ðŸ‡¬SG_271 |10.29Mb
  server: 160.16.233.76
  type: trojan
  port: 507
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: Relay_-ðŸ‡¯ðŸ‡µJP_274 |21.25Mb
  server: 13.231.156.35
  type: trojan
  port: 1331
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: disney_netflix_US |10.46Mb
  server: 160.16.196.59
  type: trojan
  port: 2890
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: Relay_-ðŸ‡¯ðŸ‡µJP_278 |12.93Mb
  server: 160.16.117.182
  type: trojan
  port: 3093
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: _172 |12.08Mb
  server: 218.237.185.230
  type: ss
  port: 4652
  password: qwerREWQ@@
  cipher: aes-256-cfb
- name: _273 |17.32Mb
  server: 58.152.25.242
  type: trojan
  port: 443
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: disney_netflix_FR |180.24Mb
  server: 208.76.223.218
  type: vmess
  country: ðŸ‡ªðŸ‡¸ES
  port: 27092
  uuid: a0596ba6-72a3-4366-8992-77088da65bd8
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_FR |182.38Mb
  server: 208.76.223.218
  type: vmess
  country: ðŸ‡ªðŸ‡¸ES
  port: 40433
  uuid: d8fd8955-78db-49ba-d86f-3e4729f6ac4d
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_NL |121.23Mb
  server: 109.71.246.210
  type: ss
  country: ðŸ‡·ðŸ‡ºRU
  port: 56689
  password: YQCSKoCF3QazW8YlvDBWA4
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_US |40.43Mb
  server: 38.14.99.163
  type: vmess
  country: ðŸ‡ºðŸ‡¸US
  port: 59807
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: auto
  network: tcp
  servername: 38.14.99.163
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ðŸ‡·ðŸ‡ºRU_385 |15.08Mb
  server: 45.139.26.173
  type: ss
  country: ðŸ‡·ðŸ‡ºRU
  port: 57456
  password: d3837224ed465f00
  cipher: chacha20-ietf-poly1305
- name: netflix_KR |10.77Mb
  server: 146.56.112.110
  type: vmess
  country: ðŸ‡°ðŸ‡·KR
  port: 8888
  uuid: e7c302f3-90d6-42dd-9d7d-94a3683a3707
  alterId: 0
  cipher: auto
  network: tcp
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_-ðŸ‡­ðŸ‡°HK_215 |32.56Mb
  server: v10.hdacd.com
  type: vmess
  port: 30807
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: disney_netflix_SG |11.08Mb
  server: 68.183.178.131
  type: vmess
  country: ðŸ‡¸ðŸ‡¬SG
  port: 58607
  uuid: c11c32cb-27b3-4afa-c0f3-fb250aa4959e
  alterId: 0
  cipher: auto
  network: ws
  servername: www.12333.monster
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /
    headers:
      HOST: www.12333.monster
- name: Relay_ðŸZZ-ðŸ‡ºðŸ‡¸US_391 |11.36Mb
  server: cf.fovi.tk
  type: vmess
  country: ðŸZZ
  port: 443
  uuid: bf67437e-6c90-45ca-abc2-c7240a5ce2aa
  alterId: 0
  cipher: auto
  network: ws
  servername: foxlux.fovi.tk
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /eisasqa
    headers:
      HOST: foxlux.fovi.tk
- name: Relay_-ðŸ‡·ðŸ‡ºRU_167 |20.17Mb
  server: 146.19.128.183
  type: ss
  port: 17847
  udp: true
  password: '907560230'
  cipher: chacha20-ietf-poly1305
- name: disney_HK |12.84Mb
  server: 58.152.18.95
  type: trojan
  port: 443
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
proxy-groups:
- name: ðŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - disney_netflix_GB |159.63Mb
  - _166 |32.60Mb
  - Relay_-ðŸ‡¸ðŸ‡¬SG_271 |10.29Mb
  - Relay_-ðŸ‡¯ðŸ‡µJP_274 |21.25Mb
  - disney_netflix_US |10.46Mb
  - Relay_-ðŸ‡¯ðŸ‡µJP_278 |12.93Mb
  - _172 |12.08Mb
  - _273 |17.32Mb
  - disney_netflix_FR |180.24Mb
  - disney_netflix_FR |182.38Mb
  - disney_netflix_NL |121.23Mb
  - disney_netflix_US |40.43Mb
  - ðŸ‡·ðŸ‡ºRU_385 |15.08Mb
  - netflix_KR |10.77Mb
  - Relay_-ðŸ‡­ðŸ‡°HK_215 |32.56Mb
  - disney_netflix_SG |11.08Mb
  - Relay_ðŸZZ-ðŸ‡ºðŸ‡¸US_391 |11.36Mb
  - Relay_-ðŸ‡·ðŸ‡ºRU_167 |20.17Mb
  - disney_HK |12.84Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - disney_netflix_GB |159.63Mb
  - _166 |32.60Mb
  - Relay_-ðŸ‡¸ðŸ‡¬SG_271 |10.29Mb
  - Relay_-ðŸ‡¯ðŸ‡µJP_274 |21.25Mb
  - disney_netflix_US |10.46Mb
  - Relay_-ðŸ‡¯ðŸ‡µJP_278 |12.93Mb
  - _172 |12.08Mb
  - _273 |17.32Mb
  - disney_netflix_FR |180.24Mb
  - disney_netflix_FR |182.38Mb
  - disney_netflix_NL |121.23Mb
  - disney_netflix_US |40.43Mb
  - ðŸ‡·ðŸ‡ºRU_385 |15.08Mb
  - netflix_KR |10.77Mb
  - Relay_-ðŸ‡­ðŸ‡°HK_215 |32.56Mb
  - disney_netflix_SG |11.08Mb
  - Relay_ðŸZZ-ðŸ‡ºðŸ‡¸US_391 |11.36Mb
  - Relay_-ðŸ‡·ðŸ‡ºRU_167 |20.17Mb
  - disney_HK |12.84Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ðŸš€ èŠ‚ç‚¹é€‰æ‹©
