port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: _175 |61.68Mb
  server: 184.72.124.41
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: disney_netflix_US |60.63Mb
  server: 23.22.182.151
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: disney_netflix_US |63.78Mb
  server: 13.222.155.147
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: _174 |65.26Mb
  server: 54.144.64.227
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: _172 |63.25Mb
  server: 54.227.38.247
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: disney_netflix_US |64.57Mb
  server: 98.81.59.20
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: _188 |62.38Mb
  server: 98.89.32.62
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: disney_netflix_US |64.20Mb
  server: 13.218.107.141
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: disney_netflix_US |61.52Mb
  server: 50.19.46.248
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: netflix_IE |288.34Mb
  server: 54.246.35.116
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: _183 |354.89Mb
  server: 34.251.86.159
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: _177 |172.99Mb
  server: 13.61.180.46
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: disney_netflix_US |65.31Mb
  server: 3.93.196.82
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: disney_netflix_US |63.08Mb
  server: 54.159.62.233
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: _178 |184.75Mb
  server: 13.61.13.231
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: disney_netflix_US |41.26Mb
  server: 3.89.113.22
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: _187 |27.53Mb
  server: 107.174.114.71
  type: ss
  port: 443
  password: 595HLF3fHUuw0McM51tpvPygSIB1uf4D
  cipher: chacha20-ietf-poly1305
- name: _206 |17.66Mb
  server: 51.79.102.253
  type: vmess
  port: 80
  uuid: 58fe1542-5290-40ad-815a-77707a81afe5
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /IOebhLMhl1CTbFHbL95myfRX2
    headers:
      Host: wrmelmwxlf.gktevlrqznwqqozy.fabpfs66gizmnojhcvqxwl.kytrcfzqla87gvgvs6c7kjnrubuh.cc
- name: _192 |310.16Mb
  server: 3.250.105.240
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: netflix_IE |261.41Mb
  server: 3.253.99.197
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: _216 |31.17Mb
  server: 216.238.86.158
  type: vmess
  port: 34460
  udp: true
  uuid: 90be214d-048c-4ea2-a602-b8e4d4e51e36
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _194 |141.27Mb
  server: 51.20.125.235
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: _169 |18.08Mb
  server: 94.198.220.183
  type: ss
  port: 64674
  udp: true
  password: s8LbJCgUiGXeCKVc63tHJP
  cipher: chacha20-ietf-poly1305
- name: disney_US |36.90Mb
  server: 165.140.216.141
  type: vmess
  port: 443
  uuid: e7d72a8d-26f2-4b54-b366-0c43e0bcba7d
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _209 |114.99Mb
  server: 38.180.16.86
  type: vmess
  port: 36236
  uuid: a58bc1a5-8c18-49ff-9453-c331b52f45dc
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _208 |111.59Mb
  server: 38.180.16.86
  type: vmess
  port: 38039
  uuid: 244a3464-1269-43b3-b491-4dc2713eb3f6
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: disney_netflix_US |41.07Mb
  server: 163.192.49.195
  type: vmess
  port: 443
  uuid: bcb7c581-3c95-4569-a4e7-918141e91ea3
  alterId: 0
  cipher: auto
  network: http
  http-opts:
    path:
    - /
    headers:
      Host:
      - a.189.cn
  h2-opts: {}
- name: netflix_DE |260.45Mb
  server: 85.195.101.122
  type: vmess
  port: 40878
  uuid: f3d4167e-b15e-4e46-82e9-9286ef93fda7
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: Relay_-ğŸ‡ºğŸ‡¸US_238 |30.78Mb
  server: 69.84.182.18
  type: trojan
  port: 8443
  udp: true
  password: a431c229-a467-4dfa-9e89-48e0f26c844b
  sni: cdn-node-oss-62.anycdn.de
  ws-opts:
    path: /profile/us2
    headers:
      Host: cdn-node-oss-62.anycdn.de
  network: ws
- name: _224 |18.73Mb
  server: 8.218.105.196
  type: vmess
  port: 52752
  uuid: 925bdbf5-72be-4437-bebf-441c61089f6b
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _212 |40.85Mb
  server: 89.31.120.192
  type: vmess
  port: 443
  uuid: 44537595-9ccc-4b83-8936-5f9ad3229019
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _226 |11.22Mb
  server: 130.162.152.253
  type: vmess
  port: 56867
  uuid: 5206bb9f-2cbc-44ac-de2a-471439a23707
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _227 |10.57Mb
  server: 140.238.2.250
  type: vmess
  port: 443
  uuid: 41a7089a-040b-4538-8b8d-010902405bde
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: disney_GB |268.31Mb
  server: 172.67.134.185
  type: trojan
  port: 443
  udp: true
  password: POORIARED
  sni: reDfRee8.REDFree8.ir
  ws-opts:
    path: /eyJqdW5rIjoiVUl6eXhLZkkwUTJ3ZzkiLCJwcm90b2NvbCI6InRyIiwibW9kZSI6InByb3h5aXAiLCJwYW5lbElQcyI6W119?ed=2560
    headers:
      Host: reDfRee8.REDFree8.ir
  network: ws
- name: _229 |18.19Mb
  server: 54.206.192.9
  type: vmess
  port: 16407
  uuid: 08f45028-1db6-4e93-bf51-d344b6c71e19
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: netflix_SE |36.20Mb
  server: 70.34.218.149
  type: trojan
  port: 11930
  password: BaeSzHdfJIR13l67
  sni: softpillow.silentrocket.click
- name: Relay_-ğŸ‡ºğŸ‡¸US_258 |33.27Mb
  server: 69.84.182.18
  type: trojan
  port: 8443
  udp: true
  password: b870a9da-02b1-4110-88f0-ee40ce5372e8
  sni: cdn-node-oss-62.anycdn.de
  ws-opts:
    path: /profile/us2
    headers:
      Host: cdn-node-oss-62.anycdn.de
  network: ws
- name: disney_SG |15.03Mb
  server: 165.154.195.38
  type: vmess
  port: 35034
  uuid: 959a8caf-4cea-43d0-a548-3628e7ddfafc
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: Relay_-ğŸ‡ºğŸ‡¸US_261 |31.69Mb
  server: 69.84.182.108
  type: trojan
  port: 8443
  udp: true
  password: b1fec179-3d5a-4ec5-bf3c-e10668543b4b
  sni: cdn-node-oss-61.anycdn.de
  ws-opts:
    path: /profile/us1
    headers:
      Host: cdn-node-oss-61.anycdn.de
  network: ws
- name: _241 |11.05Mb
  server: 160.16.229.223
  type: trojan
  port: 3093
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: _244 |20.80Mb
  server: 153.121.39.240
  type: trojan
  port: 4054
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: _251 |11.40Mb
  server: 160.16.63.16
  type: trojan
  port: 4054
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: _257 |20.04Mb
  server: 160.16.151.196
  type: trojan
  port: 4054
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: _259 |14.97Mb
  server: 160.16.236.32
  type: trojan
  port: 4054
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¯ğŸ‡µJP_264 |18.55Mb
  server: 160.16.70.180
  type: trojan
  port: 1331
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¸ğŸ‡¬SG_268 |11.22Mb
  server: 160.16.150.76
  type: trojan
  port: 3145
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: disney_FR |48.80Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 27092
  uuid: a0596ba6-72a3-4366-8992-77088da65bd8
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡²ğŸ‡½MX_288 |229.25Mb
  server: 216.238.87.47
  type: vmess
  country: ğŸ‡²ğŸ‡½MX
  port: 27502
  uuid: b8155ce4-7e08-4c40-800f-8671312b7124
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_FR |26.21Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 40433
  uuid: d8fd8955-78db-49ba-d86f-3e4729f6ac4d
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡ºğŸ‡¸US_290 |62.50Mb
  server: 18.207.122.59
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡¬ğŸ‡§GB_279 |190.67Mb
  server: 82.38.31.191
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_280 |228.14Mb
  server: 82.38.31.194
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: Relay_-ğŸ‡¯ğŸ‡µJP_203 |19.54Mb
  server: r7k75-g06.jp01-nn-vm0.entry.fr0528.art
  type: vmess
  port: 21586
  udp: true
  uuid: 0ffb3763-ac35-3e8b-bf18-944d1c1b03dd
  alterId: 1
  cipher: auto
  servername: r7k75-g06.jp01-nn-vm0.entry.fr0528.art
  http-opts: {}
  h2-opts: {}
  tls: true
- name: ğŸ‡¬ğŸ‡§GB_281 |244.52Mb
  server: 82.38.31.217
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: disney_HK |10.67Mb
  server: green2.cdntencentmusic.com
  type: trojan
  port: 31102
  udp: true
  password: d0838dd8-7132-44bd-9df9-1c9ea5297e88
  sni: green2.cdntencentmusic.com
  skip-cert-verify: true
- name: Relay_-ğŸ‡¯ğŸ‡µJP_218 |15.29Mb
  server: l7140-g06.jp02-e3-vm0.entry.fr0528.art
  type: vmess
  port: 11778
  udp: true
  uuid: 0ffb3763-ac35-3e8b-bf18-944d1c1b03dd
  alterId: 1
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: Relay_-ğŸ‡¯ğŸ‡µJP_214 |13.64Mb
  server: pmg12-g06.jp07-sh-vm0.entry.fr0528.art
  type: vmess
  port: 28788
  udp: true
  uuid: 0ffb3763-ac35-3e8b-bf18-944d1c1b03dd
  alterId: 1
  cipher: auto
  http-opts: {}
  h2-opts: {}
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - _175 |61.68Mb
  - disney_netflix_US |60.63Mb
  - disney_netflix_US |63.78Mb
  - _174 |65.26Mb
  - _172 |63.25Mb
  - disney_netflix_US |64.57Mb
  - _188 |62.38Mb
  - disney_netflix_US |64.20Mb
  - disney_netflix_US |61.52Mb
  - netflix_IE |288.34Mb
  - _183 |354.89Mb
  - _177 |172.99Mb
  - disney_netflix_US |65.31Mb
  - disney_netflix_US |63.08Mb
  - _178 |184.75Mb
  - disney_netflix_US |41.26Mb
  - _187 |27.53Mb
  - _206 |17.66Mb
  - _192 |310.16Mb
  - netflix_IE |261.41Mb
  - _216 |31.17Mb
  - _194 |141.27Mb
  - _169 |18.08Mb
  - disney_US |36.90Mb
  - _209 |114.99Mb
  - _208 |111.59Mb
  - disney_netflix_US |41.07Mb
  - netflix_DE |260.45Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_238 |30.78Mb
  - _224 |18.73Mb
  - _212 |40.85Mb
  - _226 |11.22Mb
  - _227 |10.57Mb
  - disney_GB |268.31Mb
  - _229 |18.19Mb
  - netflix_SE |36.20Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_258 |33.27Mb
  - disney_SG |15.03Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_261 |31.69Mb
  - _241 |11.05Mb
  - _244 |20.80Mb
  - _251 |11.40Mb
  - _257 |20.04Mb
  - _259 |14.97Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_264 |18.55Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_268 |11.22Mb
  - disney_FR |48.80Mb
  - ğŸ‡²ğŸ‡½MX_288 |229.25Mb
  - disney_FR |26.21Mb
  - ğŸ‡ºğŸ‡¸US_290 |62.50Mb
  - ğŸ‡¬ğŸ‡§GB_279 |190.67Mb
  - ğŸ‡¬ğŸ‡§GB_280 |228.14Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_203 |19.54Mb
  - ğŸ‡¬ğŸ‡§GB_281 |244.52Mb
  - disney_HK |10.67Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_218 |15.29Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_214 |13.64Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - _175 |61.68Mb
  - disney_netflix_US |60.63Mb
  - disney_netflix_US |63.78Mb
  - _174 |65.26Mb
  - _172 |63.25Mb
  - disney_netflix_US |64.57Mb
  - _188 |62.38Mb
  - disney_netflix_US |64.20Mb
  - disney_netflix_US |61.52Mb
  - netflix_IE |288.34Mb
  - _183 |354.89Mb
  - _177 |172.99Mb
  - disney_netflix_US |65.31Mb
  - disney_netflix_US |63.08Mb
  - _178 |184.75Mb
  - disney_netflix_US |41.26Mb
  - _187 |27.53Mb
  - _206 |17.66Mb
  - _192 |310.16Mb
  - netflix_IE |261.41Mb
  - _216 |31.17Mb
  - _194 |141.27Mb
  - _169 |18.08Mb
  - disney_US |36.90Mb
  - _209 |114.99Mb
  - _208 |111.59Mb
  - disney_netflix_US |41.07Mb
  - netflix_DE |260.45Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_238 |30.78Mb
  - _224 |18.73Mb
  - _212 |40.85Mb
  - _226 |11.22Mb
  - _227 |10.57Mb
  - disney_GB |268.31Mb
  - _229 |18.19Mb
  - netflix_SE |36.20Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_258 |33.27Mb
  - disney_SG |15.03Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_261 |31.69Mb
  - _241 |11.05Mb
  - _244 |20.80Mb
  - _251 |11.40Mb
  - _257 |20.04Mb
  - _259 |14.97Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_264 |18.55Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_268 |11.22Mb
  - disney_FR |48.80Mb
  - ğŸ‡²ğŸ‡½MX_288 |229.25Mb
  - disney_FR |26.21Mb
  - ğŸ‡ºğŸ‡¸US_290 |62.50Mb
  - ğŸ‡¬ğŸ‡§GB_279 |190.67Mb
  - ğŸ‡¬ğŸ‡§GB_280 |228.14Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_203 |19.54Mb
  - ğŸ‡¬ğŸ‡§GB_281 |244.52Mb
  - disney_HK |10.67Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_218 |15.29Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_214 |13.64Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
