port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: _201 |53.58Mb
  server: 185.82.73.212
  type: ss
  port: 8444
  udp: true
  password: _bypfvq6ra7g4n5yCCR9DoVeGya2XUUS
  cipher: chacha20-ietf-poly1305
- name: netflix_NL |297.15Mb
  server: 45.14.245.2
  type: ss
  port: 443
  password: 17ZDORWIliQHuO6WRGHChXYMzdRtAYVP
  cipher: chacha20-ietf-poly1305
- name: disney_PY |14.48Mb
  server: 38.165.233.93
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: Relay_-ğŸ‡¯ğŸ‡µJP_225 |20.02Mb
  server: 160.16.72.33
  type: trojan
  port: 3093
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¯ğŸ‡µJP_226 |19.28Mb
  server: 160.16.117.182
  type: trojan
  port: 3169
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: _205 |113.91Mb
  server: 47.242.145.160
  type: vmess
  port: 44457
  uuid: 40290609-2743-4d85-c9c3-4c72dd151b9f
  alterId: 0
  cipher: auto
  network: http
  http-opts:
    method: GET
    path:
    - /
  h2-opts: {}
- name: _198 |166.67Mb
  server: 103.149.182.158
  type: ss
  port: 8388
  password: asd123456
  cipher: chacha20-ietf
- name: Relay_-ğŸ‡­ğŸ‡°HK_199 |69.54Mb
  server: 103.149.182.105
  type: ss
  port: 8388
  password: asd123456
  cipher: chacha20-ietf
- name: _207 |19.60Mb
  server: 149.88.95.94
  type: vmess
  port: 40741
  uuid: 1b8a751b-4909-4fec-f019-907d92e6c47f
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
- name: Relay_-ğŸ‡¯ğŸ‡µJP_233 |20.92Mb
  server: 160.16.87.174
  type: trojan
  port: 3169
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¯ğŸ‡µJP_238 |22.87Mb
  server: 153.121.45.139
  type: trojan
  port: 3093
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: ğŸ‡¨ğŸ‡¦CA_246 |41.33Mb
  server: 185.213.23.63
  type: ss
  country: ğŸ‡¨ğŸ‡¦CA
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: disney_DE |65.89Mb
  server: 89.163.140.136
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: Relay_-ğŸ‡¯ğŸ‡µJP_239 |12.25Mb
  server: 160.16.117.182
  type: trojan
  port: 3093
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: netflix_NL |217.02Mb
  server: 45.87.175.180
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: QCXDxuDlTTMD7jtgHUjIoj
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡²ğŸ‡½MX_265 |39.62Mb
  server: 216.238.87.47
  type: vmess
  country: ğŸ‡²ğŸ‡½MX
  port: 27502
  uuid: b8155ce4-7e08-4c40-800f-8671312b7124
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: netflix_IT |57.19Mb
  server: 176.126.83.121
  type: ss
  country: ğŸ‡®ğŸ‡¹IT
  port: 443
  password: Q4t8T7hEYY3mD2Fn4wnxyK4X35AUzvR8
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_262 |33.59Mb
  server: 45.87.175.200
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: disney_HK |10.01Mb
  server: cdnfire.xiaomispeed.com
  type: trojan
  port: 21102
  udp: true
  password: a338457c-9863-4cc7-891c-baba351ecba1
  sni: cdnfire.xiaomispeed.com
  skip-cert-verify: true
- name: ğŸ‡³ğŸ‡±NL_267 |25.40Mb
  server: 193.29.139.141
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 8080
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡³ğŸ‡±NL_268 |53.78Mb
  server: 193.29.139.188
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 8080
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_US |40.08Mb
  server: 38.14.99.163
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 59807
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: auto
  network: tcp
  servername: 38.14.99.163
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_DE |240.38Mb
  server: 62.133.60.60
  type: ss
  country: ğŸ‡·ğŸ‡ºRU
  port: 7048
  password: OgAxVsDP6rexuKtrDhCSVA
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡­ğŸ‡°HK_254 |103.85Mb
  server: 8.218.105.196
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 52752
  uuid: 925bdbf5-72be-4437-bebf-441c61089f6b
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡µğŸ‡¹PT_270 |10.59Mb
  server: 185.113.143.186
  type: ss
  country: ğŸ‡µğŸ‡¹PT
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_278 |22.32Mb
  server: gy3.hdcloud.link
  type: trojan
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  udp: true
  password: 168f29a7-6922-4558-8296-61a69cf6a5a2
  network: grpc
  grpc-opts:
    grpc-service-name: GunService
- name: ğŸ‡¸ğŸ‡¬SG_274 |13.26Mb
  server: 68.183.227.45
  type: ss
  country: ğŸ‡¸ğŸ‡¬SG
  port: 8080
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: ğŸ‡±ğŸ‡¹LT_264 |16.16Mb
  server: ltnl16.saint.ydns.eu
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - _201 |53.58Mb
  - netflix_NL |297.15Mb
  - disney_PY |14.48Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_225 |20.02Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_226 |19.28Mb
  - _205 |113.91Mb
  - _198 |166.67Mb
  - Relay_-ğŸ‡­ğŸ‡°HK_199 |69.54Mb
  - _207 |19.60Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_233 |20.92Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_238 |22.87Mb
  - ğŸ‡¨ğŸ‡¦CA_246 |41.33Mb
  - disney_DE |65.89Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_239 |12.25Mb
  - netflix_NL |217.02Mb
  - ğŸ‡²ğŸ‡½MX_265 |39.62Mb
  - netflix_IT |57.19Mb
  - ğŸ‡±ğŸ‡¹LT_262 |33.59Mb
  - disney_HK |10.01Mb
  - ğŸ‡³ğŸ‡±NL_267 |25.40Mb
  - ğŸ‡³ğŸ‡±NL_268 |53.78Mb
  - disney_netflix_US |40.08Mb
  - disney_DE |240.38Mb
  - ğŸ‡­ğŸ‡°HK_254 |103.85Mb
  - ğŸ‡µğŸ‡¹PT_270 |10.59Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_278 |22.32Mb
  - ğŸ‡¸ğŸ‡¬SG_274 |13.26Mb
  - ğŸ‡±ğŸ‡¹LT_264 |16.16Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - _201 |53.58Mb
  - netflix_NL |297.15Mb
  - disney_PY |14.48Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_225 |20.02Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_226 |19.28Mb
  - _205 |113.91Mb
  - _198 |166.67Mb
  - Relay_-ğŸ‡­ğŸ‡°HK_199 |69.54Mb
  - _207 |19.60Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_233 |20.92Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_238 |22.87Mb
  - ğŸ‡¨ğŸ‡¦CA_246 |41.33Mb
  - disney_DE |65.89Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_239 |12.25Mb
  - netflix_NL |217.02Mb
  - ğŸ‡²ğŸ‡½MX_265 |39.62Mb
  - netflix_IT |57.19Mb
  - ğŸ‡±ğŸ‡¹LT_262 |33.59Mb
  - disney_HK |10.01Mb
  - ğŸ‡³ğŸ‡±NL_267 |25.40Mb
  - ğŸ‡³ğŸ‡±NL_268 |53.78Mb
  - disney_netflix_US |40.08Mb
  - disney_DE |240.38Mb
  - ğŸ‡­ğŸ‡°HK_254 |103.85Mb
  - ğŸ‡µğŸ‡¹PT_270 |10.59Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_278 |22.32Mb
  - ğŸ‡¸ğŸ‡¬SG_274 |13.26Mb
  - ğŸ‡±ğŸ‡¹LT_264 |16.16Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
