port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: _300 |12.18Mb
  server: 15.235.41.200
  type: vmess
  port: 80
  uuid: 58fe1542-5290-40ad-815a-77707a81afe5
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /IOebhLMhl1CTbFHbL95myfRX2
- name: _301 |14.45Mb
  server: 51.79.102.253
  type: vmess
  port: 80
  uuid: 58fe1542-5290-40ad-815a-77707a81afe5
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /IOebhLMhl1CTbFHbL95myfRX2
    headers:
      Host: wrmelmwxlf.gktevlrqznwqqozy.fabpfs66gizmnojhcvqxwl.kytrcfzqla87gvgvs6c7kjnrubuh.cc
- name: disney_CH |71.61Mb
  server: 138.124.67.26
  type: ss
  port: 443
  udp: true
  password: UdKq4itZdbbvsy0PCHTEUi
  cipher: chacha20-ietf-poly1305
- name: _271 |153.35Mb
  server: 51.20.125.235
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: _281 |59.79Mb
  server: 13.61.13.231
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: _283 |186.19Mb
  server: 13.61.180.46
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: _279 |20.51Mb
  server: 46.183.184.60
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: _313 |34.06Mb
  server: 216.238.86.158
  type: vmess
  port: 34460
  udp: true
  uuid: 90be214d-048c-4ea2-a602-b8e4d4e51e36
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: disney_US |40.99Mb
  server: 165.140.216.141
  type: vmess
  port: 443
  uuid: e7d72a8d-26f2-4b54-b366-0c43e0bcba7d
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: disney_US |33.55Mb
  server: 192.204.47.79
  type: vmess
  port: 42277
  udp: true
  uuid: aee61b21-e85a-484b-f203-b245f1451cff
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _305 |15.06Mb
  server: 38.180.16.86
  type: vmess
  port: 38039
  uuid: 244a3464-1269-43b3-b491-4dc2713eb3f6
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _277 |56.31Mb
  server: 103.149.183.191
  type: ss
  port: 8388
  udp: true
  password: asd123456
  cipher: chacha20-ietf
- name: _306 |15.81Mb
  server: 38.180.16.86
  type: vmess
  port: 36236
  uuid: a58bc1a5-8c18-49ff-9453-c331b52f45dc
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: Relay_-ğŸ‡ºğŸ‡¸US_316 |39.24Mb
  server: 38.14.99.163
  type: vmess
  port: 59807
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: Relay_-ğŸ‡ºğŸ‡¸US_319 |40.90Mb
  server: 38.14.99.179
  type: vmess
  port: 59807
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _299 |41.62Mb
  server: 89.31.120.192
  type: vmess
  port: 443
  uuid: 44537595-9ccc-4b83-8936-5f9ad3229019
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: Relay_-ğŸ‡ºğŸ‡¸US_321 |27.41Mb
  server: 20251118.yixianled.com
  type: vmess
  port: 18115
  udp: true
  uuid: 6578c489-28d2-4f12-8c2f-9f2d8789626d
  alterId: 0
  cipher: auto
  network: ws
  servername: 20251118.yixianled.com
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /happy
    headers:
      Host: 20251118.yixianled.com
- name: _308 |11.80Mb
  server: 130.162.152.253
  type: vmess
  port: 56867
  uuid: 5206bb9f-2cbc-44ac-de2a-471439a23707
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _312 |25.47Mb
  server: 8.218.105.196
  type: vmess
  port: 52752
  uuid: 925bdbf5-72be-4437-bebf-441c61089f6b
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _331 |11.63Mb
  server: 160.16.116.227
  type: trojan
  port: 2760
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
  skip-cert-verify: true
- name: _332 |10.65Mb
  server: 160.16.107.37
  type: trojan
  port: 3093
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: _335 |115.72Mb
  server: 146.70.73.210
  type: trojan
  port: 53809
  udp: true
  password: blhwsknjxmfuydz0vhfv
  sni: www.vk.com
  skip-cert-verify: true
- name: _339 |30.67Mb
  server: 153.121.39.240
  type: trojan
  port: 4054
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡§ğŸ‡·BR_329 |73.02Mb
  server: pq-brazil1.09vpn.com
  type: vmess
  port: 80
  uuid: c04c3b34-70fd-4fec-963e-c12d09f36bef
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /vmess/
    headers:
      Host: pq-brazil1.09vpn.com
- name: _350 |11.29Mb
  server: 160.16.131.243
  type: trojan
  port: 2760
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
  skip-cert-verify: true
- name: disney_GB |268.31Mb
  server: 172.67.134.185
  type: trojan
  port: 443
  udp: true
  password: POORIARED
  sni: reDfRee8.REDFree8.ir
  ws-opts:
    path: /eyJqdW5rIjoiVUl6eXhLZkkwUTJ3ZzkiLCJwcm90b2NvbCI6InRyIiwibW9kZSI6InByb3h5aXAiLCJwYW5lbElQcyI6W119?ed=2560
    headers:
      Host: reDfRee8.REDFree8.ir
  network: ws
- name: _352 |49.55Mb
  server: 160.16.57.238
  type: trojan
  port: 4054
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¯ğŸ‡µJP_355 |18.10Mb
  server: 160.16.87.174
  type: trojan
  port: 3169
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: _365 |24.58Mb
  server: 38.96.254.102
  type: trojan
  port: 18509
  password: .ie4rghJuMkcf0oF
  sni: shoppingmall.electricbanana.click
- name: Relay_-ğŸ‡ºğŸ‡¸US_330 |10.62Mb
  server: green2.cdntencentmusic.com
  type: trojan
  port: 31104
  udp: true
  password: 08212351-4fed-40aa-982f-0cfa94048f94
  sni: green2.cdntencentmusic.com
  skip-cert-verify: true
- name: _366 |35.73Mb
  server: 160.16.63.16
  type: trojan
  port: 4054
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: _368 |20.16Mb
  server: 160.16.204.136
  type: trojan
  port: 2890
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: Pool__378 |182.73Mb
  server: 70.34.218.149
  type: trojan
  port: 11930
  password: BaeSzHdfJIR13l67
  sni: softpillow.silentrocket.click
- name: netflix_NL |187.64Mb
  server: 82.38.31.191
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_414 |201.26Mb
  server: 82.38.31.217
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: _356 |54.33Mb
  server: 51aa8f7.p2.glados-config.net
  type: trojan
  port: 443
  udp: true
  password: ab47264dad8b0fbe
  alpn:
  - h2
  sni: n2.gladns.com
  network: grpc
  grpc-opts:
    grpc-service-name: db
- name: ğŸ‡²ğŸ‡½MX_421 |43.81Mb
  server: 216.238.87.47
  type: vmess
  country: ğŸ‡²ğŸ‡½MX
  port: 27502
  uuid: b8155ce4-7e08-4c40-800f-8671312b7124
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: netflix_NL |218.47Mb
  server: 82.38.31.194
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: _363 |113.17Mb
  server: 51aa8f7.p5.glados-config.net
  type: trojan
  port: 443
  udp: true
  password: ab47264dad8b0fbe
  alpn:
  - h2
  sni: n2.gladns.com
  network: grpc
  grpc-opts:
    grpc-service-name: db
- name: Pool_ğŸ‡·ğŸ‡´RO_422 |12.55Mb
  server: 86.106.84.198
  type: ss
  country: ğŸ‡·ğŸ‡´RO
  port: 13265
  password: phizo046s4oqsm33sfvm
  cipher: aes-128-gcm
- name: disney_HK |17.98Mb
  server: 45.207.157.29
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 13852
  uuid: 845764df-ecb3-4b13-bed2-bf1551b68e9a
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡ºğŸ‡¸US_424 |135.38Mb
  server: 45.12.136.170
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: l668XHPejoSNNuD66BYzyehaCpZexiF7
  cipher: chacha20-ietf-poly1305
- name: disney_US |19.57Mb
  server: cf.fovi.tk
  type: vmess
  country: ğŸZZ
  port: 443
  uuid: bf67437e-6c90-45ca-abc2-c7240a5ce2aa
  alterId: 0
  cipher: auto
  network: ws
  servername: foxpol.fovi.tk
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /eisasqa
    headers:
      HOST: foxpol.fovi.tk
- name: Relay_ğŸ‡©ğŸ‡ªDE-ğŸ‡©ğŸ‡ªDE_405 |728.56Mb
  server: cpanel.navar1.ir
  type: vmess
  country: ğŸ‡©ğŸ‡ªDE
  port: 100
  uuid: 95c6f6f0-84f7-4443-8a50-a59f8e66f5ee
  alterId: 0
  cipher: auto
  network: tcp
  servername: cpanel.navar1.ir
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_-ğŸ‡¯ğŸ‡µJP_303 |21.22Mb
  server: yg6.ygkkk.dpdns.org
  type: vmess
  port: 80
  udp: true
  uuid: 130ec091-df05-4af9-9695-dc982e98a8ec
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /130ec091-df05-4af9-9695-dc982e98a8ec-vm?ed=2048
    headers:
      Host: jporacleyg2.336697.xyz
- name: Relay_-ğŸ‡ºğŸ‡¸US_324 |13.33Mb
  server: yg1.ygkkk.dpdns.org
  type: vmess
  port: 443
  udp: true
  uuid: 7a88d322-eb4a-4a59-8c62-8c60d76abf4b
  alterId: 0
  cipher: auto
  network: ws
  servername: jporacleyg.336697.xyz
  http-opts: {}
  h2-opts: {}
  tls: true
  ws-opts:
    path: /7a88d322-eb4a-4a59-8c62-8c60d76abf4b-vm?ed=2048
    headers:
      Host: jporacleyg.336697.xyz
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - _300 |12.18Mb
  - _301 |14.45Mb
  - disney_CH |71.61Mb
  - _271 |153.35Mb
  - _281 |59.79Mb
  - _283 |186.19Mb
  - _279 |20.51Mb
  - _313 |34.06Mb
  - disney_US |40.99Mb
  - disney_US |33.55Mb
  - _305 |15.06Mb
  - _277 |56.31Mb
  - _306 |15.81Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_316 |39.24Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_319 |40.90Mb
  - _299 |41.62Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_321 |27.41Mb
  - _308 |11.80Mb
  - _312 |25.47Mb
  - _331 |11.63Mb
  - _332 |10.65Mb
  - _335 |115.72Mb
  - _339 |30.67Mb
  - Relay_-ğŸ‡§ğŸ‡·BR_329 |73.02Mb
  - _350 |11.29Mb
  - disney_GB |268.31Mb
  - _352 |49.55Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_355 |18.10Mb
  - _365 |24.58Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_330 |10.62Mb
  - _366 |35.73Mb
  - _368 |20.16Mb
  - Pool__378 |182.73Mb
  - netflix_NL |187.64Mb
  - ğŸ‡¬ğŸ‡§GB_414 |201.26Mb
  - _356 |54.33Mb
  - ğŸ‡²ğŸ‡½MX_421 |43.81Mb
  - netflix_NL |218.47Mb
  - _363 |113.17Mb
  - Pool_ğŸ‡·ğŸ‡´RO_422 |12.55Mb
  - disney_HK |17.98Mb
  - ğŸ‡ºğŸ‡¸US_424 |135.38Mb
  - disney_US |19.57Mb
  - Relay_ğŸ‡©ğŸ‡ªDE-ğŸ‡©ğŸ‡ªDE_405 |728.56Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_303 |21.22Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_324 |13.33Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - _300 |12.18Mb
  - _301 |14.45Mb
  - disney_CH |71.61Mb
  - _271 |153.35Mb
  - _281 |59.79Mb
  - _283 |186.19Mb
  - _279 |20.51Mb
  - _313 |34.06Mb
  - disney_US |40.99Mb
  - disney_US |33.55Mb
  - _305 |15.06Mb
  - _277 |56.31Mb
  - _306 |15.81Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_316 |39.24Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_319 |40.90Mb
  - _299 |41.62Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_321 |27.41Mb
  - _308 |11.80Mb
  - _312 |25.47Mb
  - _331 |11.63Mb
  - _332 |10.65Mb
  - _335 |115.72Mb
  - _339 |30.67Mb
  - Relay_-ğŸ‡§ğŸ‡·BR_329 |73.02Mb
  - _350 |11.29Mb
  - disney_GB |268.31Mb
  - _352 |49.55Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_355 |18.10Mb
  - _365 |24.58Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_330 |10.62Mb
  - _366 |35.73Mb
  - _368 |20.16Mb
  - Pool__378 |182.73Mb
  - netflix_NL |187.64Mb
  - ğŸ‡¬ğŸ‡§GB_414 |201.26Mb
  - _356 |54.33Mb
  - ğŸ‡²ğŸ‡½MX_421 |43.81Mb
  - netflix_NL |218.47Mb
  - _363 |113.17Mb
  - Pool_ğŸ‡·ğŸ‡´RO_422 |12.55Mb
  - disney_HK |17.98Mb
  - ğŸ‡ºğŸ‡¸US_424 |135.38Mb
  - disney_US |19.57Mb
  - Relay_ğŸ‡©ğŸ‡ªDE-ğŸ‡©ğŸ‡ªDE_405 |728.56Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_303 |21.22Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_324 |13.33Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
