port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: netflix_NL |202.52Mb
  server: 151.242.251.137
  type: ss
  port: 8080
  password: o5osZg269v5zHpYjr1xY9s
  cipher: chacha20-ietf-poly1305
- name: Relay_-ğŸ‡ºğŸ‡¸US_683 |40.92Mb
  server: 38.14.99.179
  type: vmess
  port: 59807
  udp: true
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_SG |35.33Mb
  server: 188.253.124.53
  type: ss
  port: 63257
  udp: true
  password: RenzheCloudSS
  cipher: rc4-md5
  plugin: obfs
  plugin-opts:
    host: d1bf8290613.microsoft.com
    mode: http
- name: Relay_-ğŸ‡­ğŸ‡°HK_472 |64.35Mb
  server: v10.hdacd.com
  type: vmess
  port: 30807
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: disney_HK |16.50Mb
  server: 58.152.30.120
  type: trojan
  port: 443
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: Relay_-ğŸ‡³ğŸ‡±NL_754 |40.49Mb
  server: 153.121.39.240
  type: trojan
  port: 4054
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: _753 |11.24Mb
  server: 68.183.231.236
  type: trojan
  port: 443
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡³ğŸ‡±NL_766 |35.24Mb
  server: 160.16.57.238
  type: trojan
  port: 4054
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: disney_HK |18.51Mb
  server: 58.152.25.20
  type: trojan
  port: 443
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: Relay_-ğŸ‡³ğŸ‡±NL_767 |42.40Mb
  server: 160.16.236.32
  type: trojan
  port: 4054
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¸ğŸ‡¬SG_768 |13.46Mb
  server: 160.16.131.243
  type: trojan
  port: 127
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: disney_FR |218.26Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 40433
  uuid: d8fd8955-78db-49ba-d86f-3e4729f6ac4d
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_-ğŸ‡³ğŸ‡±NL_772 |40.84Mb
  server: 160.16.124.55
  type: trojan
  port: 4054
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: disney_FR |185.30Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 27092
  uuid: a0596ba6-72a3-4366-8992-77088da65bd8
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_-ğŸ‡¯ğŸ‡µJP_773 |17.26Mb
  server: 153.121.65.107
  type: trojan
  port: 3169
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_ğŸ‡¬ğŸ‡§GB-ğŸ‡³ğŸ‡±NL_782 |98.69Mb
  server: 82.38.31.210
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: netflix_NL |236.80Mb
  server: 82.38.31.218
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_784 |89.16Mb
  server: 82.38.31.190
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: Relay_-ğŸ‡ºğŸ‡¸US_626 |19.68Mb
  server: v29.hdacd.com
  type: vmess
  port: 30829
  udp: true
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡²ğŸ‡½MX_920 |26.46Mb
  server: 216.238.89.53
  type: vmess
  country: ğŸ‡²ğŸ‡½MX
  port: 57283
  uuid: 1a5aafc0-6482-451d-fe76-6875b7818579
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡·ğŸ‡ºRU_923 |60.63Mb
  server: 109.71.246.210
  type: ss
  country: ğŸ‡·ğŸ‡ºRU
  port: 56689
  password: YQCSKoCF3QazW8YlvDBWA4
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡­ğŸ‡°HK_827 |26.08Mb
  server: 47.242.140.52
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 48219
  uuid: 006893c6-79b1-4c44-94ff-b8bbea065f1f
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
  ws-opts:
    path: /arki?ed=2048
- name: disney_KR |16.01Mb
  server: 218.237.185.230
  type: ss
  country: ğŸ‡°ğŸ‡·KR
  port: 4652
  password: qwerREWQ@@
  cipher: aes-256-cfb
- name: ğŸ‡ºğŸ‡¸US_928 |158.62Mb
  server: 45.12.144.18
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: LQyAUItafUmmO3EZZx9UbiX6IGydSBgL
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_930 |41.84Mb
  server: pupas-shirting-unsung.freesocks.work
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: p78naCf2EfOlRSLTX0wFVx
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡²ğŸ‡¾MY_921 |26.12Mb
  server: 38.54.98.110
  type: vmess
  country: ğŸ‡²ğŸ‡¾MY
  port: 2052
  uuid: 665d9b8f-153d-4907-adac-de12afd9c851
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: ğŸ‡¸ğŸ‡¬SG_925 |11.10Mb
  server: 68.183.178.131
  type: vmess
  country: ğŸ‡¸ğŸ‡¬SG
  port: 58607
  uuid: c11c32cb-27b3-4afa-c0f3-fb250aa4959e
  alterId: 0
  cipher: auto
  network: ws
  servername: www.12333.monster
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /
    headers:
      HOST: www.12333.monster
- name: ğŸ‡ºğŸ‡¸US_933 |19.24Mb
  server: 104.192.226.106
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_935 |40.80Mb
  server: 38.14.99.163
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 59807
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: auto
  network: tcp
  servername: 38.14.99.163
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_931 |447.99Mb
  server: clr.ducks.tel
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 17844
  password: '907560230'
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸ‡°ğŸ‡· KR-ğŸ‡°ğŸ‡·KR_915 |10.53Mb
  server: p141.panda001.net
  type: ss
  country: ğŸ‡°ğŸ‡· KR
  port: 4652
  password: qwerREWQ@@
  cipher: aes-256-cfb
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - netflix_NL |202.52Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_683 |40.92Mb
  - disney_SG |35.33Mb
  - Relay_-ğŸ‡­ğŸ‡°HK_472 |64.35Mb
  - disney_HK |16.50Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_754 |40.49Mb
  - _753 |11.24Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_766 |35.24Mb
  - disney_HK |18.51Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_767 |42.40Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_768 |13.46Mb
  - disney_FR |218.26Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_772 |40.84Mb
  - disney_FR |185.30Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_773 |17.26Mb
  - Relay_ğŸ‡¬ğŸ‡§GB-ğŸ‡³ğŸ‡±NL_782 |98.69Mb
  - netflix_NL |236.80Mb
  - ğŸ‡¬ğŸ‡§GB_784 |89.16Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_626 |19.68Mb
  - ğŸ‡²ğŸ‡½MX_920 |26.46Mb
  - ğŸ‡·ğŸ‡ºRU_923 |60.63Mb
  - ğŸ‡­ğŸ‡°HK_827 |26.08Mb
  - disney_KR |16.01Mb
  - ğŸ‡ºğŸ‡¸US_928 |158.62Mb
  - ğŸ‡ºğŸ‡¸US_930 |41.84Mb
  - ğŸ‡²ğŸ‡¾MY_921 |26.12Mb
  - ğŸ‡¸ğŸ‡¬SG_925 |11.10Mb
  - ğŸ‡ºğŸ‡¸US_933 |19.24Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_935 |40.80Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_931 |447.99Mb
  - Relay_ğŸ‡°ğŸ‡· KR-ğŸ‡°ğŸ‡·KR_915 |10.53Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - netflix_NL |202.52Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_683 |40.92Mb
  - disney_SG |35.33Mb
  - Relay_-ğŸ‡­ğŸ‡°HK_472 |64.35Mb
  - disney_HK |16.50Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_754 |40.49Mb
  - _753 |11.24Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_766 |35.24Mb
  - disney_HK |18.51Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_767 |42.40Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_768 |13.46Mb
  - disney_FR |218.26Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_772 |40.84Mb
  - disney_FR |185.30Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_773 |17.26Mb
  - Relay_ğŸ‡¬ğŸ‡§GB-ğŸ‡³ğŸ‡±NL_782 |98.69Mb
  - netflix_NL |236.80Mb
  - ğŸ‡¬ğŸ‡§GB_784 |89.16Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_626 |19.68Mb
  - ğŸ‡²ğŸ‡½MX_920 |26.46Mb
  - ğŸ‡·ğŸ‡ºRU_923 |60.63Mb
  - ğŸ‡­ğŸ‡°HK_827 |26.08Mb
  - disney_KR |16.01Mb
  - ğŸ‡ºğŸ‡¸US_928 |158.62Mb
  - ğŸ‡ºğŸ‡¸US_930 |41.84Mb
  - ğŸ‡²ğŸ‡¾MY_921 |26.12Mb
  - ğŸ‡¸ğŸ‡¬SG_925 |11.10Mb
  - ğŸ‡ºğŸ‡¸US_933 |19.24Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_935 |40.80Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_931 |447.99Mb
  - Relay_ğŸ‡°ğŸ‡· KR-ğŸ‡°ğŸ‡·KR_915 |10.53Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
