port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: _231 |28.34Mb
  server: 173.234.29.2
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _239 |52.75Mb
  server: 66.23.207.82
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _233 |10.38Mb
  server: 147.78.1.230
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _242 |10.49Mb
  server: 145.14.131.99
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _243 |10.30Mb
  server: 196.196.192.58
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _247 |16.57Mb
  server: 77.91.101.132
  type: ss
  port: 43458
  udp: true
  password: SSh5aoQdcX0nZXCAH5yF75
  cipher: chacha20-ietf-poly1305
- name: _244 |10.15Mb
  server: 109.61.46.43
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _249 |50.81Mb
  server: 138.186.142.81
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _236 |10.77Mb
  server: 185.163.204.94
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _248 |10.01Mb
  server: 37.143.129.98
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _252 |10.28Mb
  server: 62.100.205.100
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _255 |10.33Mb
  server: 62.100.205.177
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _263 |52.44Mb
  server: 103.106.228.247
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _256 |10.09Mb
  server: 203.23.128.92
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _266 |10.30Mb
  server: 38.165.231.25
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _267 |45.17Mb
  server: 176.126.83.158
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _269 |46.91Mb
  server: 193.37.255.38
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _264 |44.49Mb
  server: 171.22.254.129
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¨ğŸ‡¦CA_308 |10.42Mb
  server: 79.127.200.162
  type: ss
  country: ğŸ‡¨ğŸ‡¦CA
  port: 990
  password: f8f7aCzcPKbsF8p3
  cipher: chacha20-ietf-poly1305
- name: _278 |10.10Mb
  server: 45.82.252.109
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _275 |40.76Mb
  server: 154.223.20.79
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¨ğŸ‡¦CA_309 |10.25Mb
  server: 79.127.200.169
  type: ss
  country: ğŸ‡¨ğŸ‡¦CA
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¨ğŸ‡¦CA_310 |10.62Mb
  server: 147.182.146.81
  type: ss
  country: ğŸ‡¨ğŸ‡¦CA
  port: 8080
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: ğŸ‡¨ğŸ‡¦CA_312 |412.68Mb
  server: 68.183.193.204
  type: ss
  country: ğŸ‡¨ğŸ‡¦CA
  port: 8080
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: _273 |62.26Mb
  server: 77.83.246.74
  type: ss
  port: 443
  udp: true
  password: 7115Q0ojojBF7mc2F7KLkN
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¨ğŸ‡¦CA_313 |10.71Mb
  server: 147.182.150.107
  type: ss
  country: ğŸ‡¨ğŸ‡¦CA
  port: 8080
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: _279 |41.85Mb
  server: 46.183.185.37
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¨ğŸ‡¦CA_314 |141.71Mb
  server: 138.197.165.21
  type: ss
  country: ğŸ‡¨ğŸ‡¦CA
  port: 8080
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: ğŸ‡¨ğŸ‡¦CA_315 |10.59Mb
  server: 138.197.153.10
  type: ss
  country: ğŸ‡¨ğŸ‡¦CA
  port: 8080
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: _285 |46.32Mb
  server: 185.113.143.186
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡©ğŸ‡°DK_367 |10.27Mb
  server: 192.36.27.94
  type: ss
  country: ğŸ‡©ğŸ‡°DK
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ğŸ‡©ğŸ‡ªDE_335 |13.85Mb
  server: 84.200.91.158
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 443
  password: 2fccd682-c8a6-4a3a-857b-68efd8ed3322
  cipher: aes-256-gcm
- name: ğŸ‡©ğŸ‡ªDE_364 |14.02Mb
  server: 57.129.25.20
  type: vmess
  country: ğŸ‡©ğŸ‡ªDE
  port: 443
  uuid: 03fcc618-b93d-6796-6aed-8a38c975d581
  alterId: 1
  cipher: auto
  network: ws
  servername: 57.129.25.20
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: linkvws
    headers:
      HOST: 57.129.25.20
- name: ğŸ‡©ğŸ‡°DK_368 |10.15Mb
  server: 121.127.45.165
  type: ss
  country: ğŸ‡©ğŸ‡°DK
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ªğŸ‡¸ES_389 |33.17Mb
  server: 212.34.140.184
  type: ss
  country: ğŸ‡ªğŸ‡¸ES
  port: 443
  password: 0NeN5ta7FLa5B9DLytU0um
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡«ğŸ‡·FR_406 |10.36Mb
  server: 57.129.140.88
  type: ss
  country: ğŸ‡«ğŸ‡·FR
  port: 8388
  password: k1v5g9FefdoO
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡«ğŸ‡·FR_421 |85.01Mb
  server: 83.147.216.70
  type: ss
  country: ğŸ‡«ğŸ‡·FR
  port: 64519
  password: 9z4XoS0TfzxNsSqBVAWt7N
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡«ğŸ‡·FR_422 |90.73Mb
  server: 83.147.216.70
  type: ss
  country: ğŸ‡«ğŸ‡·FR
  port: 64519
  password: RLfa7IlzmmrwyBtI4BOJs3
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡«ğŸ‡·FR_423 |89.45Mb
  server: 83.147.216.70
  type: ss
  country: ğŸ‡«ğŸ‡·FR
  port: 64519
  password: WmDhVSiDij7R2XROr3Cm55
  cipher: chacha20-ietf-poly1305
- name: Pool_ğŸ‡¬ğŸ‡§GB_464 |10.30Mb
  server: 79.127.233.170
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: Pool_ğŸ‡¬ğŸ‡§GB_465 |10.08Mb
  server: 79.127.233.170
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 990
  password: f8f7aCzcPKbsF8p3
  cipher: chacha20-ietf-poly1305
- name: Pool_ğŸ‡¬ğŸ‡§GB_445 |10.30Mb
  server: 64.176.184.129
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 1866
  password: oXGp1+ihlfKg826H
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_450 |11.03Mb
  server: 89.185.84.185
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: Qqt1DFQEMvj6oJ69n6uf1Z
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_462 |15.27Mb
  server: 146.70.61.37
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: ğŸ‡¬ğŸ‡§GB_458 |136.75Mb
  server: 213.109.147.242
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 62685
  password: VpKABcOpNNA0l5G2AVOmw8
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_449 |58.13Mb
  server: 64.137.109.212
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 44884
  password: 2DGq3jvVRg5n3CcxmysGK2kmrgJeSNof12A76cZvVxqPpetyC1XEciCFufq5xKvRWGGnKVembpThuUSQhbZ7GMsZY4UVxEBw
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡«ğŸ‡·FR_426 |37.06Mb
  server: 83.147.216.70
  type: ss
  country: ğŸ‡«ğŸ‡·FR
  port: 64519
  password: YXgS8ComTam7qoesPlzlMo
  cipher: chacha20-ietf-poly1305
- name: _238 |15.87Mb
  server: 154.70.207.97
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_463 |32.75Mb
  server: 107.181.147.235
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 40521
  password: Z94FoM1xpW3CJzixME8CjJEFBiCFhKSWfLzT6E92Pjh7y73YfNrwPju46Gd4HE85eXSjNiTtiAYc6WTskuhxZZFebd4rcXfp
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡·GR_475 |43.52Mb
  server: 192.71.166.102
  type: ss
  country: ğŸ‡¬ğŸ‡·GR
  port: 990
  password: f8f7aCzcPKbsF8p3
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡·GR_476 |116.47Mb
  server: 192.71.166.102
  type: ss
  country: ğŸ‡¬ğŸ‡·GR
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ğŸ‡­ğŸ‡°HK_488 |17.75Mb
  server: 154.223.16.212
  type: ss
  country: ğŸ‡­ğŸ‡°HK
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: Pool_ğŸ‡­ğŸ‡°HK_489 |503.00Mb
  server: 150.107.46.21
  type: ssr
  country: ğŸ‡­ğŸ‡°HK
  port: 8083
  password: iFqnzSscN
  cipher: aes-256-cfb
  protocol: origin
  obfs: tls1.2_ticket_auth
- name: ğŸ‡­ğŸ‡°HK_501 |17.56Mb
  server: 47.243.39.20
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 36512
  uuid: cc13ac4b-d38f-4ebb-8a2a-73cf3aff5650
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
  ws-opts:
    path: /arki?ed=2048
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - _231 |28.34Mb
  - _239 |52.75Mb
  - _233 |10.38Mb
  - _242 |10.49Mb
  - _243 |10.30Mb
  - _247 |16.57Mb
  - _244 |10.15Mb
  - _249 |50.81Mb
  - _236 |10.77Mb
  - _248 |10.01Mb
  - _252 |10.28Mb
  - _255 |10.33Mb
  - _263 |52.44Mb
  - _256 |10.09Mb
  - _266 |10.30Mb
  - _267 |45.17Mb
  - _269 |46.91Mb
  - _264 |44.49Mb
  - ğŸ‡¨ğŸ‡¦CA_308 |10.42Mb
  - _278 |10.10Mb
  - _275 |40.76Mb
  - ğŸ‡¨ğŸ‡¦CA_309 |10.25Mb
  - ğŸ‡¨ğŸ‡¦CA_310 |10.62Mb
  - ğŸ‡¨ğŸ‡¦CA_312 |412.68Mb
  - _273 |62.26Mb
  - ğŸ‡¨ğŸ‡¦CA_313 |10.71Mb
  - _279 |41.85Mb
  - ğŸ‡¨ğŸ‡¦CA_314 |141.71Mb
  - ğŸ‡¨ğŸ‡¦CA_315 |10.59Mb
  - _285 |46.32Mb
  - ğŸ‡©ğŸ‡°DK_367 |10.27Mb
  - ğŸ‡©ğŸ‡ªDE_335 |13.85Mb
  - ğŸ‡©ğŸ‡ªDE_364 |14.02Mb
  - ğŸ‡©ğŸ‡°DK_368 |10.15Mb
  - ğŸ‡ªğŸ‡¸ES_389 |33.17Mb
  - ğŸ‡«ğŸ‡·FR_406 |10.36Mb
  - ğŸ‡«ğŸ‡·FR_421 |85.01Mb
  - ğŸ‡«ğŸ‡·FR_422 |90.73Mb
  - ğŸ‡«ğŸ‡·FR_423 |89.45Mb
  - Pool_ğŸ‡¬ğŸ‡§GB_464 |10.30Mb
  - Pool_ğŸ‡¬ğŸ‡§GB_465 |10.08Mb
  - Pool_ğŸ‡¬ğŸ‡§GB_445 |10.30Mb
  - ğŸ‡¬ğŸ‡§GB_450 |11.03Mb
  - ğŸ‡¬ğŸ‡§GB_462 |15.27Mb
  - ğŸ‡¬ğŸ‡§GB_458 |136.75Mb
  - ğŸ‡¬ğŸ‡§GB_449 |58.13Mb
  - ğŸ‡«ğŸ‡·FR_426 |37.06Mb
  - _238 |15.87Mb
  - ğŸ‡¬ğŸ‡§GB_463 |32.75Mb
  - ğŸ‡¬ğŸ‡·GR_475 |43.52Mb
  - ğŸ‡¬ğŸ‡·GR_476 |116.47Mb
  - ğŸ‡­ğŸ‡°HK_488 |17.75Mb
  - Pool_ğŸ‡­ğŸ‡°HK_489 |503.00Mb
  - ğŸ‡­ğŸ‡°HK_501 |17.56Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - _231 |28.34Mb
  - _239 |52.75Mb
  - _233 |10.38Mb
  - _242 |10.49Mb
  - _243 |10.30Mb
  - _247 |16.57Mb
  - _244 |10.15Mb
  - _249 |50.81Mb
  - _236 |10.77Mb
  - _248 |10.01Mb
  - _252 |10.28Mb
  - _255 |10.33Mb
  - _263 |52.44Mb
  - _256 |10.09Mb
  - _266 |10.30Mb
  - _267 |45.17Mb
  - _269 |46.91Mb
  - _264 |44.49Mb
  - ğŸ‡¨ğŸ‡¦CA_308 |10.42Mb
  - _278 |10.10Mb
  - _275 |40.76Mb
  - ğŸ‡¨ğŸ‡¦CA_309 |10.25Mb
  - ğŸ‡¨ğŸ‡¦CA_310 |10.62Mb
  - ğŸ‡¨ğŸ‡¦CA_312 |412.68Mb
  - _273 |62.26Mb
  - ğŸ‡¨ğŸ‡¦CA_313 |10.71Mb
  - _279 |41.85Mb
  - ğŸ‡¨ğŸ‡¦CA_314 |141.71Mb
  - ğŸ‡¨ğŸ‡¦CA_315 |10.59Mb
  - _285 |46.32Mb
  - ğŸ‡©ğŸ‡°DK_367 |10.27Mb
  - ğŸ‡©ğŸ‡ªDE_335 |13.85Mb
  - ğŸ‡©ğŸ‡ªDE_364 |14.02Mb
  - ğŸ‡©ğŸ‡°DK_368 |10.15Mb
  - ğŸ‡ªğŸ‡¸ES_389 |33.17Mb
  - ğŸ‡«ğŸ‡·FR_406 |10.36Mb
  - ğŸ‡«ğŸ‡·FR_421 |85.01Mb
  - ğŸ‡«ğŸ‡·FR_422 |90.73Mb
  - ğŸ‡«ğŸ‡·FR_423 |89.45Mb
  - Pool_ğŸ‡¬ğŸ‡§GB_464 |10.30Mb
  - Pool_ğŸ‡¬ğŸ‡§GB_465 |10.08Mb
  - Pool_ğŸ‡¬ğŸ‡§GB_445 |10.30Mb
  - ğŸ‡¬ğŸ‡§GB_450 |11.03Mb
  - ğŸ‡¬ğŸ‡§GB_462 |15.27Mb
  - ğŸ‡¬ğŸ‡§GB_458 |136.75Mb
  - ğŸ‡¬ğŸ‡§GB_449 |58.13Mb
  - ğŸ‡«ğŸ‡·FR_426 |37.06Mb
  - _238 |15.87Mb
  - ğŸ‡¬ğŸ‡§GB_463 |32.75Mb
  - ğŸ‡¬ğŸ‡·GR_475 |43.52Mb
  - ğŸ‡¬ğŸ‡·GR_476 |116.47Mb
  - ğŸ‡­ğŸ‡°HK_488 |17.75Mb
  - Pool_ğŸ‡­ğŸ‡°HK_489 |503.00Mb
  - ğŸ‡­ğŸ‡°HK_501 |17.56Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
