port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: disney_netflix_GB |144.76Mb
  server: 172.66.44.230
  type: trojan
  port: 8443
  udp: true
  password: 8r<[9'l6hAO#8ZQi
  sni: Koma-YT.PAGeS.Dev
  ws-opts:
    path: /tro8sFW1S91B6sZrM1?ed=2560
    headers:
      Host: Koma-YT.PAGeS.Dev
  network: ws
- name: disney_netflix_GB |159.63Mb
  server: koma-yt.pages.dev
  type: trojan
  port: 8443
  udp: true
  password: 8r<[9'l6hAO#8ZQi
  sni: Koma-YT.PAGeS.Dev
  ws-opts:
    path: /tro8sFW1S91B6sZrM1?ed=2560
    headers:
      Host: Koma-YT.PAGeS.Dev
  network: ws
- name: netflix_MX |31.96Mb
  server: 216.238.89.53
  type: vmess
  country: ðŸ‡²ðŸ‡½MX
  port: 57283
  uuid: 1a5aafc0-6482-451d-fe76-6875b7818579
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_US |40.70Mb
  server: 38.14.99.163
  type: vmess
  country: ðŸ‡ºðŸ‡¸US
  port: 59807
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: auto
  network: tcp
  servername: 38.14.99.163
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_FR |111.02Mb
  server: 208.76.223.218
  type: vmess
  country: ðŸ‡ªðŸ‡¸ES
  port: 40433
  uuid: d8fd8955-78db-49ba-d86f-3e4729f6ac4d
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ðŸ‡·ðŸ‡ºRU_402 |15.08Mb
  server: 45.139.26.173
  type: ss
  country: ðŸ‡·ðŸ‡ºRU
  port: 57456
  password: d3837224ed465f00
  cipher: chacha20-ietf-poly1305
- name: ðŸ‡°ðŸ‡·KR_399 |10.03Mb
  server: 146.56.112.110
  type: vmess
  country: ðŸ‡°ðŸ‡·KR
  port: 8888
  uuid: e7c302f3-90d6-42dd-9d7d-94a3683a3707
  alterId: 0
  cipher: auto
  network: tcp
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ðŸ‡¸ðŸ‡¬SG_404 |11.12Mb
  server: 68.183.178.131
  type: vmess
  country: ðŸ‡¸ðŸ‡¬SG
  port: 58607
  uuid: c11c32cb-27b3-4afa-c0f3-fb250aa4959e
  alterId: 0
  cipher: auto
  network: ws
  servername: www.12333.monster
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /
    headers:
      HOST: www.12333.monster
proxy-groups:
- name: ðŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - disney_netflix_GB |144.76Mb
  - disney_netflix_GB |159.63Mb
  - netflix_MX |31.96Mb
  - disney_netflix_US |40.70Mb
  - disney_netflix_FR |111.02Mb
  - ðŸ‡·ðŸ‡ºRU_402 |15.08Mb
  - ðŸ‡°ðŸ‡·KR_399 |10.03Mb
  - ðŸ‡¸ðŸ‡¬SG_404 |11.12Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - disney_netflix_GB |144.76Mb
  - disney_netflix_GB |159.63Mb
  - netflix_MX |31.96Mb
  - disney_netflix_US |40.70Mb
  - disney_netflix_FR |111.02Mb
  - ðŸ‡·ðŸ‡ºRU_402 |15.08Mb
  - ðŸ‡°ðŸ‡·KR_399 |10.03Mb
  - ðŸ‡¸ðŸ‡¬SG_404 |11.12Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ðŸš€ èŠ‚ç‚¹é€‰æ‹©
