port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: disney_netflix_US |33.54Mb
  server: 192.204.47.79
  type: vmess
  port: 42277
  udp: true
  uuid: aee61b21-e85a-484b-f203-b245f1451cff
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: disney_netflix_US |42.51Mb
  server: 165.140.216.141
  type: vmess
  port: 443
  uuid: e7d72a8d-26f2-4b54-b366-0c43e0bcba7d
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: disney_netflix_DE |260.45Mb
  server: 85.195.101.122
  type: vmess
  port: 40878
  uuid: f3d4167e-b15e-4e46-82e9-9286ef93fda7
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: netflix_SE |137.21Mb
  server: 13.61.13.231
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: netflix_SE |59.35Mb
  server: 51.20.125.235
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: netflix_FI |37.96Mb
  server: 77.83.247.206
  type: ss
  port: 18284
  udp: true
  password: tijsjk3iwzc6b10azb0y
  cipher: aes-128-gcm
- name: _139 |27.53Mb
  server: 107.174.114.71
  type: ss
  port: 443
  password: 595HLF3fHUuw0McM51tpvPygSIB1uf4D
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_US |28.43Mb
  server: 20251118.yixianled.com
  type: vmess
  port: 33921
  udp: true
  uuid: 6578c489-28d2-4f12-8c2f-9f2d8789626d
  alterId: 0
  cipher: auto
  network: ws
  servername: 20251118.yixianled.com
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /happy
    headers:
      Host: 20251118.yixianled.com
- name: disney_netflix_US |17.36Mb
  server: 216.167.49.157
  type: vmess
  port: 36108
  uuid: ac9340c1-61d7-47bd-c5a2-9b888857dec6
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
- name: Pool__137 |19.43Mb
  server: 185.103.110.68
  type: ss
  port: 18283
  udp: true
  password: y3o3ra6edy5nfc6hyb2n
  cipher: aes-128-gcm
- name: disney_netflix_US |42.95Mb
  server: 163.192.49.195
  type: vmess
  port: 443
  uuid: bcb7c581-3c95-4569-a4e7-918141e91ea3
  alterId: 0
  cipher: auto
  network: http
  http-opts:
    path:
    - /
    headers:
      Host:
      - a.189.cn
  h2-opts: {}
- name: disney_TW |14.47Mb
  server: 103.127.218.91
  type: vmess
  port: 54693
  uuid: 1cef03ad-6343-408c-8121-cbd1fda2ee9d
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /1cef03ad
- name: _167 |17.37Mb
  server: 15.235.41.200
  type: vmess
  port: 80
  uuid: 58fe1542-5290-40ad-815a-77707a81afe5
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /IOebhLMhl1CTbFHbL95myfRX2
- name: disney_netflix_DE |50.71Mb
  server: 43.165.7.71
  type: vmess
  port: 19751
  uuid: 6cfa6103-5d06-40cb-f452-b563db578288
  alterId: 0
  cipher: auto
  network: http
  http-opts:
    method: GET
    path:
    - /
  h2-opts: {}
- name: netflix_AE |38.94Mb
  server: 89.31.120.192
  type: vmess
  port: 443
  uuid: 44537595-9ccc-4b83-8936-5f9ad3229019
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _162 |18.10Mb
  server: 8.210.184.105
  type: vmess
  port: 40374
  udp: true
  uuid: 36b76373-7a4f-4669-9113-7d247bcf2704
  alterId: 0
  cipher: auto
  network: http
  http-opts:
    method: GET
    path:
    - /
  h2-opts: {}
- name: disney_netflix_GB |268.31Mb
  server: 172.67.134.185
  type: trojan
  port: 443
  udp: true
  password: POORIARED
  sni: reDfRee8.REDFree8.ir
  ws-opts:
    path: /eyJqdW5rIjoiVUl6eXhLZkkwUTJ3ZzkiLCJwcm90b2NvbCI6InRyIiwibW9kZSI6InByb3h5aXAiLCJwYW5lbElQcyI6W119?ed=2560
    headers:
      Host: reDfRee8.REDFree8.ir
  network: ws
- name: disney_SG |12.30Mb
  server: 165.154.195.38
  type: vmess
  port: 35034
  uuid: 959a8caf-4cea-43d0-a548-3628e7ddfafc
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _181 |21.02Mb
  server: 51.79.102.253
  type: vmess
  port: 80
  uuid: 58fe1542-5290-40ad-815a-77707a81afe5
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /IOebhLMhl1CTbFHbL95myfRX2
    headers:
      Host: wrmelmwxlf.gktevlrqznwqqozy.fabpfs66gizmnojhcvqxwl.kytrcfzqla87gvgvs6c7kjnrubuh.cc
- name: _176 |10.69Mb
  server: 140.238.2.250
  type: vmess
  port: 443
  uuid: 41a7089a-040b-4538-8b8d-010902405bde
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _188 |11.42Mb
  server: 160.16.117.182
  type: trojan
  port: 3093
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: _189 |38.28Mb
  server: 160.16.151.196
  type: trojan
  port: 4054
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: netflix_SE |183.61Mb
  server: 70.34.218.149
  type: trojan
  port: 11930
  password: BaeSzHdfJIR13l67
  sni: softpillow.silentrocket.click
- name: Relay_-ğŸ‡ºğŸ‡¸US_165 |49.00Mb
  server: v4.hdacd.com
  type: vmess
  port: 30804
  udp: true
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_FR |26.68Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 27092
  uuid: a0596ba6-72a3-4366-8992-77088da65bd8
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_FR |33.16Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 40433
  uuid: d8fd8955-78db-49ba-d86f-3e4729f6ac4d
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: netflix_NL |165.55Mb
  server: 82.38.31.194
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: netflix_MX |123.17Mb
  server: 216.238.87.47
  type: vmess
  country: ğŸ‡²ğŸ‡½MX
  port: 27502
  uuid: b8155ce4-7e08-4c40-800f-8671312b7124
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_-ğŸ‡¸ğŸ‡¬SG_195 |10.40Mb
  server: 160.16.150.76
  type: trojan
  port: 3145
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¯ğŸ‡µJP_200 |16.78Mb
  server: 153.121.73.102
  type: trojan
  port: 1331
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: disney_HK |27.77Mb
  server: 58.152.53.174
  type: trojan
  port: 443
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: netflix_CH |59.21Mb
  server: 86.106.84.198
  type: ss
  country: ğŸ‡·ğŸ‡´RO
  port: 13265
  password: phizo046s4oqsm33sfvm
  cipher: aes-128-gcm
- name: ğŸ‡ºğŸ‡¸US_218 |12.28Mb
  server: 45.12.136.170
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: l668XHPejoSNNuD66BYzyehaCpZexiF7
  cipher: chacha20-ietf-poly1305
- name: _160 |33.25Mb
  server: 154.201.76.172
  type: vmess
  port: 20990
  uuid: ba50e1fe-055f-4587-fd0d-36c8d6615192
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - disney_netflix_US |33.54Mb
  - disney_netflix_US |42.51Mb
  - disney_netflix_DE |260.45Mb
  - netflix_SE |137.21Mb
  - netflix_SE |59.35Mb
  - netflix_FI |37.96Mb
  - _139 |27.53Mb
  - disney_netflix_US |28.43Mb
  - disney_netflix_US |17.36Mb
  - Pool__137 |19.43Mb
  - disney_netflix_US |42.95Mb
  - disney_TW |14.47Mb
  - _167 |17.37Mb
  - disney_netflix_DE |50.71Mb
  - netflix_AE |38.94Mb
  - _162 |18.10Mb
  - disney_netflix_GB |268.31Mb
  - disney_SG |12.30Mb
  - _181 |21.02Mb
  - _176 |10.69Mb
  - _188 |11.42Mb
  - _189 |38.28Mb
  - netflix_SE |183.61Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_165 |49.00Mb
  - disney_netflix_FR |26.68Mb
  - disney_netflix_FR |33.16Mb
  - netflix_NL |165.55Mb
  - netflix_MX |123.17Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_195 |10.40Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_200 |16.78Mb
  - disney_HK |27.77Mb
  - netflix_CH |59.21Mb
  - ğŸ‡ºğŸ‡¸US_218 |12.28Mb
  - _160 |33.25Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - disney_netflix_US |33.54Mb
  - disney_netflix_US |42.51Mb
  - disney_netflix_DE |260.45Mb
  - netflix_SE |137.21Mb
  - netflix_SE |59.35Mb
  - netflix_FI |37.96Mb
  - _139 |27.53Mb
  - disney_netflix_US |28.43Mb
  - disney_netflix_US |17.36Mb
  - Pool__137 |19.43Mb
  - disney_netflix_US |42.95Mb
  - disney_TW |14.47Mb
  - _167 |17.37Mb
  - disney_netflix_DE |50.71Mb
  - netflix_AE |38.94Mb
  - _162 |18.10Mb
  - disney_netflix_GB |268.31Mb
  - disney_SG |12.30Mb
  - _181 |21.02Mb
  - _176 |10.69Mb
  - _188 |11.42Mb
  - _189 |38.28Mb
  - netflix_SE |183.61Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_165 |49.00Mb
  - disney_netflix_FR |26.68Mb
  - disney_netflix_FR |33.16Mb
  - netflix_NL |165.55Mb
  - netflix_MX |123.17Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_195 |10.40Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_200 |16.78Mb
  - disney_HK |27.77Mb
  - netflix_CH |59.21Mb
  - ğŸ‡ºğŸ‡¸US_218 |12.28Mb
  - _160 |33.25Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
