port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: _595 |235.87Mb
  server: 45.87.175.181
  type: ss
  port: 8080
  udp: true
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: netflix_NL |255.02Mb
  server: 151.242.251.137
  type: ss
  port: 8080
  password: o5osZg269v5zHpYjr1xY9s
  cipher: chacha20-ietf-poly1305
- name: _601 |232.06Mb
  server: 82.38.31.199
  type: ss
  port: 8080
  udp: true
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: _615 |62.47Mb
  server: 47.253.197.26
  type: vmess
  port: 12056
  uuid: dd7be7f1-38ff-45e6-f1e5-b20c2190f527
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
- name: disney_PT |50.65Mb
  server: 185.231.233.112
  type: ss
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: _598 |51.67Mb
  server: 213.159.67.124
  type: ss
  port: 443
  password: mbhqsStnFQT1cTZYCdsmkugGUC6GT6rp
  cipher: chacha20-ietf-poly1305
- name: _597 |12.94Mb
  server: 45.93.95.187
  type: ss
  port: 8618
  udp: true
  password: 4lUEC91c1d8oeClzDbYpXA
  cipher: chacha20-ietf-poly1305
- name: _602 |13.41Mb
  server: 103.106.3.82
  type: ss
  port: 443
  udp: true
  password: 4SaCIazlgumYkM8FkPzlmwjpyWBDZFBk
  cipher: chacha20-ietf-poly1305
- name: _594 |35.38Mb
  server: 154.90.62.168
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: Relay_-ğŸ‡¯ğŸ‡µJP_622 |13.15Mb
  server: 160.16.223.205
  type: trojan
  port: 1331
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡³ğŸ‡±NL_628 |10.04Mb
  server: 160.16.81.84
  type: trojan
  port: 4054
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: _619 |107.83Mb
  server: 47.243.209.146
  type: vmess
  port: 29333
  uuid: 9681c9ac-c4e3-4600-b698-5cc6b14085f7
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /arki?ed=2048
- name: Relay_-ğŸ‡²ğŸ‡¾MY_610 |30.31Mb
  server: ml0724.ysds168.shop
  type: vmess
  port: 2052
  udp: true
  uuid: 665d9b8f-153d-4907-adac-de12afd9c851
  alterId: 0
  cipher: auto
  servername: ml0724.ysds168.shop
  http-opts: {}
  h2-opts: {}
  tls: true
- name: Relay_-ğŸ‡³ğŸ‡±NL_633 |10.16Mb
  server: 160.16.236.32
  type: trojan
  port: 4054
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¯ğŸ‡µJP_611 |12.58Mb
  server: d0s31-g06.jp02-e3-vm0.entry.fr0528.art
  type: vmess
  port: 11778
  udp: true
  uuid: 8e0c2bc2-705f-375f-a246-82955b5165ef
  alterId: 1
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: disney_US |112.49Mb
  server: 23.247.137.64
  type: trojan
  port: 443
  udp: true
  password: 3c4e10af98c30972
  alpn:
  - h2
  sni: n2.gladns.com
  network: grpc
  grpc-opts:
    grpc-service-name: db
- name: Relay_-ğŸ‡ºğŸ‡¸US_651 |11.34Mb
  server: gy3.hdcloud.link
  type: trojan
  port: 443
  udp: true
  password: 9b6419f8-8120-442e-a48c-6bf52aef0abf
  network: grpc
  grpc-opts:
    grpc-service-name: GunService
- name: _635 |11.61Mb
  server: 58.152.25.20
  type: trojan
  port: 443
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: Relay_-ğŸ‡­ğŸ‡°HK_625 |10.14Mb
  server: green2.cdntencentmusic.com
  type: trojan
  port: 31102
  udp: true
  password: 7832727a-dce8-454a-9df0-591b642f69a9
  sni: green2.cdntencentmusic.com
  skip-cert-verify: true
- name: Relay_-ğŸ‡¯ğŸ‡µJP_640 |14.55Mb
  server: 52.195.176.26
  type: trojan
  port: 2145
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: Relay_-ğŸ‡¯ğŸ‡µJP_648 |12.52Mb
  server: 160.16.236.32
  type: trojan
  port: 3093
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: _637 |12.17Mb
  server: 58.152.18.192
  type: trojan
  port: 443
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: ğŸ‡§ğŸ‡¬BG_659 |43.51Mb
  server: 87.121.162.249
  type: ss
  country: ğŸ‡§ğŸ‡¬BG
  port: 443
  password: JGv616hMWdjfuZ00jYfq7XkBHJZrOBrg
  cipher: chacha20-ietf-poly1305
- name: disney_FR |95.13Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 27092
  uuid: a0596ba6-72a3-4366-8992-77088da65bd8
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡§ğŸ‡·BR_660 |22.56Mb
  server: 38.180.16.86
  type: vmess
  country: ğŸ‡§ğŸ‡·BR
  port: 36236
  uuid: a58bc1a5-8c18-49ff-9453-c331b52f45dc
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_ğŸ‡¬ğŸ‡§GB-ğŸ‡ºğŸ‡¸US_667 |11.70Mb
  server: 82.198.246.97
  type: vmess
  country: ğŸ‡¬ğŸ‡§GB
  port: 180
  uuid: d13fc2f5-3e05-4795-81eb-44143a09e552
  alterId: 0
  cipher: auto
  network: tcp
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: netflix_NL |167.53Mb
  server: 82.38.31.184
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_666 |224.31Mb
  server: 82.38.31.179
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡§ğŸ‡·BR_661 |20.67Mb
  server: 38.180.16.86
  type: vmess
  country: ğŸ‡§ğŸ‡·BR
  port: 36104
  uuid: E146A8CB-9D2F-449C-ADCA-8736FB
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_-ğŸ‡±ğŸ‡»LV_604 |12.16Mb
  server: 31.56.117.73
  type: vmess
  port: 28573
  uuid: aa521837-6bfb-47dd-c87c-ec730a974020
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
- name: ğŸ‡²ğŸ‡½MX_711 |35.11Mb
  server: 216.238.89.53
  type: vmess
  country: ğŸ‡²ğŸ‡½MX
  port: 57283
  uuid: 1a5aafc0-6482-451d-fe76-6875b7818579
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡®ğŸ‡ªIE_707 |80.25Mb
  server: 18.203.220.111
  type: ss
  country: ğŸ‡®ğŸ‡ªIE
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡¬ğŸ‡·GR_668 |502.43Mb
  server: 192.71.166.100
  type: ss
  country: ğŸ‡¬ğŸ‡·GR
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ğŸ‡·ğŸ‡ºRU_713 |53.95Mb
  server: 109.71.246.210
  type: ss
  country: ğŸ‡·ğŸ‡ºRU
  port: 56689
  password: YQCSKoCF3QazW8YlvDBWA4
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡­ğŸ‡°HK_706 |13.07Mb
  server: 112.118.116.66
  type: trojan
  country: ğŸ‡­ğŸ‡°HK
  port: 443
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: ğŸ‡­ğŸ‡°HK_685 |14.87Mb
  server: 47.242.140.52
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 48219
  uuid: 006893c6-79b1-4c44-94ff-b8bbea065f1f
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
  ws-opts:
    path: /arki?ed=2048
- name: ğŸ‡²ğŸ‡¾MY_712 |31.30Mb
  server: 38.54.98.110
  type: vmess
  country: ğŸ‡²ğŸ‡¾MY
  port: 2052
  uuid: 665d9b8f-153d-4907-adac-de12afd9c851
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: ğŸ‡ºğŸ‡¸US_720 |22.99Mb
  server: 45.136.12.37
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 38141
  uuid: fd291be6-b48d-43a1-da38-66c7f80e2f80
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_ğŸ‡­ğŸ‡°HK-ğŸ‡­ğŸ‡°HK_672 |10.24Mb
  server: cgroup.node4.s.nodelist-airport.com
  type: ss
  country: ğŸ‡­ğŸ‡°HK
  port: 32013
  password: 8f3a835c-8a45-480d-ae35-1deb2c52dcae
  cipher: aes-256-gcm
- name: Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_718 |126.53Mb
  server: sw19.sesamebuta.top
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  uuid: 805ba514-bf2f-4d5d-df49-8417804e8de3
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /abcd
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - _595 |235.87Mb
  - netflix_NL |255.02Mb
  - _601 |232.06Mb
  - _615 |62.47Mb
  - disney_PT |50.65Mb
  - _598 |51.67Mb
  - _597 |12.94Mb
  - _602 |13.41Mb
  - _594 |35.38Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_622 |13.15Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_628 |10.04Mb
  - _619 |107.83Mb
  - Relay_-ğŸ‡²ğŸ‡¾MY_610 |30.31Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_633 |10.16Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_611 |12.58Mb
  - disney_US |112.49Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_651 |11.34Mb
  - _635 |11.61Mb
  - Relay_-ğŸ‡­ğŸ‡°HK_625 |10.14Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_640 |14.55Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_648 |12.52Mb
  - _637 |12.17Mb
  - ğŸ‡§ğŸ‡¬BG_659 |43.51Mb
  - disney_FR |95.13Mb
  - ğŸ‡§ğŸ‡·BR_660 |22.56Mb
  - Relay_ğŸ‡¬ğŸ‡§GB-ğŸ‡ºğŸ‡¸US_667 |11.70Mb
  - netflix_NL |167.53Mb
  - ğŸ‡¬ğŸ‡§GB_666 |224.31Mb
  - ğŸ‡§ğŸ‡·BR_661 |20.67Mb
  - Relay_-ğŸ‡±ğŸ‡»LV_604 |12.16Mb
  - ğŸ‡²ğŸ‡½MX_711 |35.11Mb
  - ğŸ‡®ğŸ‡ªIE_707 |80.25Mb
  - ğŸ‡¬ğŸ‡·GR_668 |502.43Mb
  - ğŸ‡·ğŸ‡ºRU_713 |53.95Mb
  - ğŸ‡­ğŸ‡°HK_706 |13.07Mb
  - ğŸ‡­ğŸ‡°HK_685 |14.87Mb
  - ğŸ‡²ğŸ‡¾MY_712 |31.30Mb
  - ğŸ‡ºğŸ‡¸US_720 |22.99Mb
  - Relay_ğŸ‡­ğŸ‡°HK-ğŸ‡­ğŸ‡°HK_672 |10.24Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_718 |126.53Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - _595 |235.87Mb
  - netflix_NL |255.02Mb
  - _601 |232.06Mb
  - _615 |62.47Mb
  - disney_PT |50.65Mb
  - _598 |51.67Mb
  - _597 |12.94Mb
  - _602 |13.41Mb
  - _594 |35.38Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_622 |13.15Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_628 |10.04Mb
  - _619 |107.83Mb
  - Relay_-ğŸ‡²ğŸ‡¾MY_610 |30.31Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_633 |10.16Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_611 |12.58Mb
  - disney_US |112.49Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_651 |11.34Mb
  - _635 |11.61Mb
  - Relay_-ğŸ‡­ğŸ‡°HK_625 |10.14Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_640 |14.55Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_648 |12.52Mb
  - _637 |12.17Mb
  - ğŸ‡§ğŸ‡¬BG_659 |43.51Mb
  - disney_FR |95.13Mb
  - ğŸ‡§ğŸ‡·BR_660 |22.56Mb
  - Relay_ğŸ‡¬ğŸ‡§GB-ğŸ‡ºğŸ‡¸US_667 |11.70Mb
  - netflix_NL |167.53Mb
  - ğŸ‡¬ğŸ‡§GB_666 |224.31Mb
  - ğŸ‡§ğŸ‡·BR_661 |20.67Mb
  - Relay_-ğŸ‡±ğŸ‡»LV_604 |12.16Mb
  - ğŸ‡²ğŸ‡½MX_711 |35.11Mb
  - ğŸ‡®ğŸ‡ªIE_707 |80.25Mb
  - ğŸ‡¬ğŸ‡·GR_668 |502.43Mb
  - ğŸ‡·ğŸ‡ºRU_713 |53.95Mb
  - ğŸ‡­ğŸ‡°HK_706 |13.07Mb
  - ğŸ‡­ğŸ‡°HK_685 |14.87Mb
  - ğŸ‡²ğŸ‡¾MY_712 |31.30Mb
  - ğŸ‡ºğŸ‡¸US_720 |22.99Mb
  - Relay_ğŸ‡­ğŸ‡°HK-ğŸ‡­ğŸ‡°HK_672 |10.24Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_718 |126.53Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
