port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: disney_netflix_US |42.26Mb
  server: 163.192.49.195
  type: vmess
  port: 443
  uuid: bcb7c581-3c95-4569-a4e7-918141e91ea3
  alterId: 0
  cipher: auto
  network: http
  http-opts:
    path:
    - /
    headers:
      Host:
      - a.189.cn
  h2-opts: {}
- name: disney_US |44.54Mb
  server: 165.140.216.141
  type: vmess
  port: 443
  uuid: e7d72a8d-26f2-4b54-b366-0c43e0bcba7d
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: ' |26.86Mb'
  server: 51.79.102.253
  type: vmess
  port: 80
  uuid: 58fe1542-5290-40ad-815a-77707a81afe5
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /IOebhLMhl1CTbFHbL95myfRX2
    headers:
      Host: wrmelmwxlf.gktevlrqznwqqozy.fabpfs66gizmnojhcvqxwl.kytrcfzqla87gvgvs6c7kjnrubuh.cc
- name: netflix_DE |690.17Mb
  server: 85.195.101.122
  type: vmess
  port: 40878
  uuid: f3d4167e-b15e-4e46-82e9-9286ef93fda7
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: disney_US |140.61Mb
  server: 192.204.47.79
  type: vmess
  port: 42277
  udp: true
  uuid: aee61b21-e85a-484b-f203-b245f1451cff
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _236 |23.99Mb
  server: 8.218.116.26
  type: vmess
  port: 32228
  uuid: e4767e9f-ed00-4f31-a984-a918bdd9b09c
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: ' |40.40Mb'
  server: 216.238.86.158
  type: vmess
  port: 34460
  udp: true
  uuid: 90be214d-048c-4ea2-a602-b8e4d4e51e36
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: Relay_-ğŸ‡§ğŸ‡·BR_229 |73.02Mb
  server: pq-brazil1.09vpn.com
  type: vmess
  port: 80
  uuid: c04c3b34-70fd-4fec-963e-c12d09f36bef
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /vmess/
    headers:
      Host: pq-brazil1.09vpn.com
- name: _281 |109.17Mb
  server: 38.96.254.102
  type: trojan
  port: 18509
  password: .ie4rghJuMkcf0oF
  sni: shoppingmall.electricbanana.click
- name: Relay_-ğŸ‡ºğŸ‡¸US_227 |242.32Mb
  server: 3h-kazakhstan1.09vpn.com
  type: vmess
  port: 80
  uuid: 567f4be5-12ab-42e1-b8d9-db6fd1fdd31c
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /vmess/
    headers:
      Host: 3h-kazakhstan1.09vpn.com
- name: ' |43.09Mb'
  server: 89.31.120.192
  type: vmess
  port: 443
  uuid: 44537595-9ccc-4b83-8936-5f9ad3229019
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _285 |11.77Mb
  server: 160.16.117.182
  type: trojan
  port: 3093
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: Pool__283 |36.00Mb
  server: 70.34.218.149
  type: trojan
  port: 11930
  password: BaeSzHdfJIR13l67
  sni: softpillow.silentrocket.click
- name: ' |18.75Mb'
  server: 8.218.105.196
  type: vmess
  port: 52752
  uuid: 925bdbf5-72be-4437-bebf-441c61089f6b
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: disney_FR |149.23Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 27092
  uuid: a0596ba6-72a3-4366-8992-77088da65bd8
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_FR |159.98Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 40433
  uuid: d8fd8955-78db-49ba-d86f-3e4729f6ac4d
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡²ğŸ‡½MX |39.27Mb
  server: 216.238.87.47
  type: vmess
  country: ğŸ‡²ğŸ‡½MX
  port: 27502
  uuid: b8155ce4-7e08-4c40-800f-8671312b7124
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡¬ğŸ‡§GB_296 |233.34Mb
  server: 82.38.31.194
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: disney_HK |15.02Mb
  server: 45.136.12.37
  type: vmess
  port: 38141
  uuid: fd291be6-b48d-43a1-da38-66c7f80e2f80
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: ğŸ‡¬ğŸ‡§GB_297 |203.77Mb
  server: 82.38.31.217
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_298 |91.86Mb
  server: 82.38.31.191
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: disney_HK |20.06Mb
  server: 45.207.157.29
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 13852
  uuid: 845764df-ecb3-4b13-bed2-bf1551b68e9a
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ' |21.84Mb'
  server: 154.201.76.172
  type: vmess
  port: 20990
  uuid: ba50e1fe-055f-4587-fd0d-36c8d6615192
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: ğŸ‡·ğŸ‡ºRU_307 |14.70Mb
  server: 45.129.2.185
  type: ss
  country: ğŸ‡·ğŸ‡ºRU
  port: 10081
  password: c5fcdf7829112cb4
  cipher: aes-256-gcm
- name: _239 |105.13Mb
  server: 183.236.51.36
  type: vmess
  port: 59003
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 64
  cipher: auto
  http-opts: {}
  h2-opts: {}
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - disney_netflix_US |42.26Mb
  - disney_US |44.54Mb
  - ' |26.86Mb'
  - netflix_DE |690.17Mb
  - disney_US |140.61Mb
  - _236 |23.99Mb
  - ' |40.40Mb'
  - Relay_-ğŸ‡§ğŸ‡·BR_229 |73.02Mb
  - _281 |109.17Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_227 |242.32Mb
  - ' |43.09Mb'
  - _285 |11.77Mb
  - Pool__283 |36.00Mb
  - ' |18.75Mb'
  - disney_FR |149.23Mb
  - disney_FR |159.98Mb
  - ğŸ‡²ğŸ‡½MX |39.27Mb
  - ğŸ‡¬ğŸ‡§GB_296 |233.34Mb
  - disney_HK |15.02Mb
  - ğŸ‡¬ğŸ‡§GB_297 |203.77Mb
  - ğŸ‡¬ğŸ‡§GB_298 |91.86Mb
  - disney_HK |20.06Mb
  - ' |21.84Mb'
  - ğŸ‡·ğŸ‡ºRU_307 |14.70Mb
  - _239 |105.13Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - disney_netflix_US |42.26Mb
  - disney_US |44.54Mb
  - ' |26.86Mb'
  - netflix_DE |690.17Mb
  - disney_US |140.61Mb
  - _236 |23.99Mb
  - ' |40.40Mb'
  - Relay_-ğŸ‡§ğŸ‡·BR_229 |73.02Mb
  - _281 |109.17Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_227 |242.32Mb
  - ' |43.09Mb'
  - _285 |11.77Mb
  - Pool__283 |36.00Mb
  - ' |18.75Mb'
  - disney_FR |149.23Mb
  - disney_FR |159.98Mb
  - ğŸ‡²ğŸ‡½MX |39.27Mb
  - ğŸ‡¬ğŸ‡§GB_296 |233.34Mb
  - disney_HK |15.02Mb
  - ğŸ‡¬ğŸ‡§GB_297 |203.77Mb
  - ğŸ‡¬ğŸ‡§GB_298 |91.86Mb
  - disney_HK |20.06Mb
  - ' |21.84Mb'
  - ğŸ‡·ğŸ‡ºRU_307 |14.70Mb
  - _239 |105.13Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
