port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: _303 |15.55Mb
  server: 196.196.192.58
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _314 |41.46Mb
  server: 95.164.116.33
  type: ss
  port: 443
  password: pQmnC03JObbPhdh5FBJHgD6jnTLchsRA
  cipher: chacha20-ietf-poly1305
- name: _305 |14.15Mb
  server: 89.221.225.15
  type: ss
  port: 443
  udp: true
  password: yCbQ4bry4otfifK7oel71NaXpPL9pYJb
  cipher: chacha20-ietf-poly1305
- name: disney_PY |12.38Mb
  server: 38.165.233.93
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: _325 |31.75Mb
  server: 103.35.189.136
  type: ss
  port: 443
  udp: true
  password: SS2QvbC9nqLp2sXXZo0BVy4slcErRuCt
  cipher: chacha20-ietf-poly1305
- name: _318 |43.34Mb
  server: 146.70.61.37
  type: ss
  port: 8080
  udp: true
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: _327 |83.79Mb
  server: 82.38.31.176
  type: ss
  port: 8080
  udp: true
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: _331 |14.02Mb
  server: 173.234.29.2
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _320 |14.19Mb
  server: 138.186.142.81
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _329 |290.08Mb
  server: 51.15.23.166
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: _316 |18.29Mb
  server: 38.89.142.56
  type: ss
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _332 |224.03Mb
  server: 151.242.251.152
  type: ss
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: _334 |237.17Mb
  server: 82.38.31.214
  type: ss
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: _338 |176.89Mb
  server: 82.38.31.179
  type: ss
  port: 8080
  udp: true
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: Relay_-ğŸ‡¨ğŸ‡¦CA_350 |69.34Mb
  server: 79.127.200.169
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _361 |65.80Mb
  server: 172.233.229.91
  type: vmess
  port: 14102
  udp: true
  uuid: 27ba87fc-583f-4763-9060-83cf0b9264db
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_-ğŸ‡ªğŸ‡ªEE_317 |21.69Mb
  server: est01-ss01.tcp-reset-club.net
  type: ss
  port: 8444
  udp: true
  password: AWNeHjukGQWwuFXadw2r6qH7gh4hZ9cj
  cipher: chacha20-ietf-poly1305
- name: _346 |38.00Mb
  server: 45.158.171.70
  type: ss
  port: 8080
  udp: true
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: _343 |500.59Mb
  server: 46.183.184.60
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: _351 |171.24Mb
  server: 45.87.175.28
  type: ss
  port: 8080
  udp: true
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¨ğŸ‡¦CA_396 |63.64Mb
  server: 193.203.203.66
  type: ss
  country: ğŸ‡¨ğŸ‡¦CA
  port: 443
  password: S6jUK9Fw5fMHgNqlqXObHZWv8Tf4nEkm
  cipher: chacha20-ietf-poly1305
- name: _330 |29.74Mb
  server: 156.59.243.6
  type: ss
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _342 |26.73Mb
  server: 103.149.182.86
  type: ss
  port: 8388
  udp: true
  password: asd123456
  cipher: chacha20-ietf
- name: ğŸ‡§ğŸ‡·BR_395 |37.96Mb
  server: 185.192.124.188
  type: ss
  country: ğŸ‡§ğŸ‡·BR
  port: 990
  password: f8f7aCzcPKbsF8p3
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¨ğŸ‡¦CA_397 |85.35Mb
  server: 185.213.23.63
  type: ss
  country: ğŸ‡¨ğŸ‡¦CA
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: disney_CH |12.18Mb
  server: 138.124.67.26
  type: ss
  country: ğŸ‡¨ğŸ‡­CH
  port: 25572
  password: nqcIfYHlpMn3jzqkNDjKaG
  cipher: chacha20-ietf-poly1305
- name: Relay_-ğŸ‡¯ğŸ‡µJP_378 |10.28Mb
  server: 160.16.117.182
  type: trojan
  port: 3169
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¯ğŸ‡µJP_389 |11.53Mb
  server: 160.16.117.182
  type: trojan
  port: 3093
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: _392 |10.36Mb
  server: 160.16.106.144
  type: trojan
  port: 2760
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
  skip-cert-verify: true
- name: ğŸ‡©ğŸ‡ªDE_402 |178.46Mb
  server: 89.163.140.136
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: Relay_ğŸ‡¬ğŸ‡§GB-ğŸ‡³ğŸ‡±NL_403 |107.83Mb
  server: 82.38.31.208
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_414 |98.08Mb
  server: 45.87.175.175
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: QCXDxuDlTTMD7jtgHUjIoj
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_416 |119.62Mb
  server: 45.87.175.183
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_417 |253.95Mb
  server: 45.87.175.185
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_419 |213.56Mb
  server: 45.87.175.185
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡²ğŸ‡½MX_422 |176.91Mb
  server: 216.238.87.47
  type: vmess
  country: ğŸ‡²ğŸ‡½MX
  port: 27502
  uuid: b8155ce4-7e08-4c40-800f-8671312b7124
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: _355 |113.67Mb
  server: h110vpnnl.outlinekeys.net
  type: ss
  port: 52571
  udp: true
  password: b0TKxnHAYeeFYyzTAMXn0F
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡» LV_420 |54.97Mb
  server: 46.183.217.204
  type: ss
  country: ğŸ‡±ğŸ‡» LV
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡³ğŸ‡±NL_425 |24.81Mb
  server: 178.23.190.238
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 443
  password: uo7EbtqIwgZXXHmMv5LbLcOxptyPlNkh
  cipher: chacha20-ietf-poly1305
- name: netflix_PT |57.61Mb
  server: 185.113.143.186
  type: ss
  country: ğŸ‡µğŸ‡¹PT
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_433 |150.58Mb
  server: 38.14.99.163
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 59807
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: auto
  network: tcp
  servername: 38.14.99.163
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_434 |15.05Mb
  server: gy3.hdcloud.link
  type: trojan
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  udp: true
  password: 2cce737c-9c6d-4667-bb3d-aea668a0c10b
  sni: gy3.hdcloud.link
  network: grpc
  grpc-opts:
    grpc-service-name: GunService
- name: ğŸZZ_436 |110.39Mb
  server: hgtrojan.zabc.net
  type: vmess
  country: ğŸZZ
  port: 2083
  uuid: e6395c20-4571-4b34-d6b1-55a5d36e49ea
  alterId: 0
  cipher: auto
  network: ws
  servername: hgtrojan.zabc.net
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /e6395c20
    headers:
      HOST: hgtrojan.zabc.net
- name: Relay_ğŸ‡¯ğŸ‡µJP-ğŸ‡¯ğŸ‡µJP_412 |10.71Mb
  server: xray.kk37005.tk
  type: vmess
  country: ğŸ‡¯ğŸ‡µJP
  port: 55919
  uuid: 2e7548bb-7c5b-4d97-d64d-1b2fe4050089
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: ğŸ‡¸ğŸ‡¬SG_429 |10.20Mb
  server: 68.183.227.45
  type: ss
  country: ğŸ‡¸ğŸ‡¬SG
  port: 8080
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: disney_SG |23.03Mb
  server: 103.248.229.90
  type: ss
  country: ğŸ‡¸ğŸ‡¬SG
  port: 40413
  password: hGpFS8dtyN
  cipher: aes-256-gcm
- name: disney_SG |16.13Mb
  server: 103.248.229.90
  type: ss
  country: ğŸ‡¸ğŸ‡¬SG
  port: 24203
  password: 1GJth1Qjic
  cipher: aes-256-gcm
- name: ğŸ‡¸ğŸ‡¬SG_432 |15.95Mb
  server: 103.248.229.90
  type: ss
  country: ğŸ‡¸ğŸ‡¬SG
  port: 35817
  password: 4VqrUWV7hm
  cipher: aes-256-gcm
- name: _340 |220.96Mb
  server: 45.14.245.2
  type: ss
  port: 443
  password: 17ZDORWIliQHuO6WRGHChXYMzdRtAYVP
  cipher: chacha20-ietf-poly1305
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - _303 |15.55Mb
  - _314 |41.46Mb
  - _305 |14.15Mb
  - disney_PY |12.38Mb
  - _325 |31.75Mb
  - _318 |43.34Mb
  - _327 |83.79Mb
  - _331 |14.02Mb
  - _320 |14.19Mb
  - _329 |290.08Mb
  - _316 |18.29Mb
  - _332 |224.03Mb
  - _334 |237.17Mb
  - _338 |176.89Mb
  - Relay_-ğŸ‡¨ğŸ‡¦CA_350 |69.34Mb
  - _361 |65.80Mb
  - Relay_-ğŸ‡ªğŸ‡ªEE_317 |21.69Mb
  - _346 |38.00Mb
  - _343 |500.59Mb
  - _351 |171.24Mb
  - ğŸ‡¨ğŸ‡¦CA_396 |63.64Mb
  - _330 |29.74Mb
  - _342 |26.73Mb
  - ğŸ‡§ğŸ‡·BR_395 |37.96Mb
  - ğŸ‡¨ğŸ‡¦CA_397 |85.35Mb
  - disney_CH |12.18Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_378 |10.28Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_389 |11.53Mb
  - _392 |10.36Mb
  - ğŸ‡©ğŸ‡ªDE_402 |178.46Mb
  - Relay_ğŸ‡¬ğŸ‡§GB-ğŸ‡³ğŸ‡±NL_403 |107.83Mb
  - ğŸ‡±ğŸ‡¹LT_414 |98.08Mb
  - ğŸ‡±ğŸ‡¹LT_416 |119.62Mb
  - ğŸ‡±ğŸ‡¹LT_417 |253.95Mb
  - ğŸ‡±ğŸ‡¹LT_419 |213.56Mb
  - ğŸ‡²ğŸ‡½MX_422 |176.91Mb
  - _355 |113.67Mb
  - ğŸ‡±ğŸ‡» LV_420 |54.97Mb
  - ğŸ‡³ğŸ‡±NL_425 |24.81Mb
  - netflix_PT |57.61Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_433 |150.58Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_434 |15.05Mb
  - ğŸZZ_436 |110.39Mb
  - Relay_ğŸ‡¯ğŸ‡µJP-ğŸ‡¯ğŸ‡µJP_412 |10.71Mb
  - ğŸ‡¸ğŸ‡¬SG_429 |10.20Mb
  - disney_SG |23.03Mb
  - disney_SG |16.13Mb
  - ğŸ‡¸ğŸ‡¬SG_432 |15.95Mb
  - _340 |220.96Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - _303 |15.55Mb
  - _314 |41.46Mb
  - _305 |14.15Mb
  - disney_PY |12.38Mb
  - _325 |31.75Mb
  - _318 |43.34Mb
  - _327 |83.79Mb
  - _331 |14.02Mb
  - _320 |14.19Mb
  - _329 |290.08Mb
  - _316 |18.29Mb
  - _332 |224.03Mb
  - _334 |237.17Mb
  - _338 |176.89Mb
  - Relay_-ğŸ‡¨ğŸ‡¦CA_350 |69.34Mb
  - _361 |65.80Mb
  - Relay_-ğŸ‡ªğŸ‡ªEE_317 |21.69Mb
  - _346 |38.00Mb
  - _343 |500.59Mb
  - _351 |171.24Mb
  - ğŸ‡¨ğŸ‡¦CA_396 |63.64Mb
  - _330 |29.74Mb
  - _342 |26.73Mb
  - ğŸ‡§ğŸ‡·BR_395 |37.96Mb
  - ğŸ‡¨ğŸ‡¦CA_397 |85.35Mb
  - disney_CH |12.18Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_378 |10.28Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_389 |11.53Mb
  - _392 |10.36Mb
  - ğŸ‡©ğŸ‡ªDE_402 |178.46Mb
  - Relay_ğŸ‡¬ğŸ‡§GB-ğŸ‡³ğŸ‡±NL_403 |107.83Mb
  - ğŸ‡±ğŸ‡¹LT_414 |98.08Mb
  - ğŸ‡±ğŸ‡¹LT_416 |119.62Mb
  - ğŸ‡±ğŸ‡¹LT_417 |253.95Mb
  - ğŸ‡±ğŸ‡¹LT_419 |213.56Mb
  - ğŸ‡²ğŸ‡½MX_422 |176.91Mb
  - _355 |113.67Mb
  - ğŸ‡±ğŸ‡» LV_420 |54.97Mb
  - ğŸ‡³ğŸ‡±NL_425 |24.81Mb
  - netflix_PT |57.61Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_433 |150.58Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_434 |15.05Mb
  - ğŸZZ_436 |110.39Mb
  - Relay_ğŸ‡¯ğŸ‡µJP-ğŸ‡¯ğŸ‡µJP_412 |10.71Mb
  - ğŸ‡¸ğŸ‡¬SG_429 |10.20Mb
  - disney_SG |23.03Mb
  - disney_SG |16.13Mb
  - ğŸ‡¸ğŸ‡¬SG_432 |15.95Mb
  - _340 |220.96Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
