port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: netflix_NL |216.28Mb
  server: 82.38.31.179
  type: ss
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: netflix_TR |21.89Mb
  server: 95.164.116.33
  type: ss
  port: 443
  password: pQmnC03JObbPhdh5FBJHgD6jnTLchsRA
  cipher: chacha20-ietf-poly1305
- name: netflix_IL |18.88Mb
  server: 89.221.225.15
  type: ss
  port: 443
  password: yCbQ4bry4otfifK7oel71NaXpPL9pYJb
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_HK |29.75Mb
  server: 194.246.114.101
  type: ss
  port: 443
  password: HaNqw9pIE4jcx98sg7UQgHeGNTM4R2pk
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_SG |37.32Mb
  server: 185.36.192.228
  type: vmess
  port: 35488
  uuid: fb5a4283-dbfb-458b-8619-c4a53739f781
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
- name: disney_netflix_JP |14.94Mb
  server: 160.16.87.174
  type: trojan
  port: 3093
  password: 44e660b0ee21cf3ac66aee2c08af85d2
  sni: www.nintendogames.net
- name: disney_netflix_JP |10.33Mb
  server: 780265300ad54887a7d6b1a8a96f276a.lh.gtm.cac.cab
  type: trojan
  port: 40668
  udp: true
  password: 259a29a2-b884-47c9-ad0f-689f00b92bdd
  sni: tcjp1.bilibili.com
  skip-cert-verify: true
- name: Relay_-ğŸ‡»ğŸ‡³VN_59 |11.02Mb
  server: gtm1.ktmwan.net
  type: vmess
  port: 12891
  uuid: 1ec49aaf-2990-4c7b-a45c-d190e6ea5438
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /
    headers:
      Host: baidu.com
- name: Relay_-ğŸ‡­ğŸ‡°HK_48 |10.44Mb
  server: gtm1.ktmwan.net
  type: vmess
  port: 12890
  uuid: 1ec49aaf-2990-4c7b-a45c-d190e6ea5438
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /
    headers:
      Host: baidu.com
- name: Relay_-ğŸ‡¸ğŸ‡¬SG_58 |11.66Mb
  server: gtm1.ktmwan.net
  type: vmess
  port: 12901
  uuid: 1ec49aaf-2990-4c7b-a45c-d190e6ea5438
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /
    headers:
      Host: baidu.com
- name: Relay_-ğŸ‡¹ğŸ‡¼TW_50 |10.72Mb
  server: gtm1.ktmwan.net
  type: vmess
  port: 12888
  uuid: 1ec49aaf-2990-4c7b-a45c-d190e6ea5438
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /
    headers:
      Host: baidu.com
- name: netflix_CA |18.51Mb
  server: 45.154.204.7
  type: ss
  country: ğŸ‡¨ğŸ‡¦CA
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_JP |11.21Mb
  server: e29564308aa0306b90a9c95fb29c1873.lh.gtm.cac.cab
  type: trojan
  port: 49631
  udp: true
  password: 259a29a2-b884-47c9-ad0f-689f00b92bdd
  sni: tcjp1.bilibili.com
  skip-cert-verify: true
- name: disney_netflix_SG |11.55Mb
  server: e64015c8088087d04e3e5187cd4dd8cb.lh.gtm.cac.cab
  type: trojan
  port: 47957
  udp: true
  password: 259a29a2-b884-47c9-ad0f-689f00b92bdd
  sni: tcsg1.bilibili.com
  skip-cert-verify: true
- name: disney_netflix_TW |11.83Mb
  server: 8fef41b85872e902603527fa3daceb64.lh.gtm.cac.cab
  type: trojan
  port: 47775
  udp: true
  password: 259a29a2-b884-47c9-ad0f-689f00b92bdd
  sni: tctw1.bilibili.com
  skip-cert-verify: true
- name: disney_netflix_US |10.02Mb
  server: f69cd23a9054671b8fd82d26d8b1c0e3.lh.gtm.cac.cab
  type: trojan
  port: 42499
  udp: true
  password: 259a29a2-b884-47c9-ad0f-689f00b92bdd
  sni: tcus1.bilibili.com
  skip-cert-verify: true
- name: disney_netflix_JP |11.42Mb
  server: c813434f92474856b4082f05c64417fb.lh.gtm.cac.cab
  type: trojan
  port: 42417
  udp: true
  password: 259a29a2-b884-47c9-ad0f-689f00b92bdd
  sni: tcjp1.bilibili.com
  skip-cert-verify: true
- name: disney_netflix_SG |11.46Mb
  server: ca4275179ac8861652c4496db4be61a3.lh.gtm.cac.cab
  type: trojan
  port: 41780
  udp: true
  password: 259a29a2-b884-47c9-ad0f-689f00b92bdd
  sni: tcsg1.bilibili.com
  skip-cert-verify: true
- name: disney_netflix_US |22.96Mb
  server: 23.95.75.146
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: NDRySIABARbErNIVsCNVkyYAHiBzhveT
  cipher: chacha20-ietf-poly1305
- name: netflix_CA |39.28Mb
  server: 23.95.76.59
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_US |47.64Mb
  server: 47.253.228.138
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 22524
  uuid: 80845fcc-f862-45fe-c1d3-0a7120373712
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_HK |30.05Mb
  server: 45.207.157.29
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 13852
  uuid: 845764df-ecb3-4b13-bed2-bf1551b68e9a
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_US |17.15Mb
  server: hgtrojan.zabc.net
  type: vmess
  country: ğŸZZ
  port: 2083
  uuid: e6395c20-4571-4b34-d6b1-55a5d36e49ea
  alterId: 0
  cipher: auto
  network: ws
  servername: hgtrojan.zabc.net
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /e6395c20
    headers:
      HOST: hgtrojan.zabc.net
- name: netflix_MX |42.10Mb
  server: 216.238.86.158
  type: vmess
  country: ğŸ‡²ğŸ‡½MX
  port: 34460
  uuid: 90be214d-048c-4ea2-a602-b8e4d4e51e36
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: netflix_NL |124.23Mb
  server: 178.23.190.238
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 443
  password: uo7EbtqIwgZXXHmMv5LbLcOxptyPlNkh
  cipher: chacha20-ietf-poly1305
- name: disney_US |37.42Mb
  server: us1.opensocks.site
  type: ss
  country: ğŸ‡·ğŸ‡ºRU
  port: 8388
  password: YjkxY
  cipher: chacha20-ietf-poly1305
- name: netflix_MD |41.67Mb
  server: 176.123.1.175
  type: ss
  country: ğŸ‡²ğŸ‡©MD
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_US |11.43Mb
  server: 206.119.191.9
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 7100
  uuid: 10853485-26e1-477b-d257-58a3f4873db3
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_US |10.18Mb
  server: 26512dddfb6153388a0abb59db32d7ff.lh.gtm.cac.cab
  type: trojan
  port: 42253
  udp: true
  password: 259a29a2-b884-47c9-ad0f-689f00b92bdd
  sni: tcus1.bilibili.com
  skip-cert-verify: true
- name: disney_netflix_JP |20.77Mb
  server: n1753598446.wpg27.xyz
  type: vmess
  country: ğŸ‡¯ğŸ‡µJP
  port: 443
  uuid: a5047d95-24b8-451a-93e3-f2a387b93d5a
  alterId: 0
  cipher: auto
  network: ws
  servername: n1753598446.wpg27.xyz
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /
    headers:
      HOST: n1753598446.wpg27.xyz
- name: disney_netflix_SG |11.56Mb
  server: ddfce778596a61464a4b626f5eca88de.lh.gtm.cac.cab
  type: trojan
  port: 48422
  udp: true
  password: 259a29a2-b884-47c9-ad0f-689f00b92bdd
  sni: tcsg1.bilibili.com
  skip-cert-verify: true
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - netflix_NL |216.28Mb
  - netflix_TR |21.89Mb
  - netflix_IL |18.88Mb
  - disney_netflix_HK |29.75Mb
  - disney_netflix_SG |37.32Mb
  - disney_netflix_JP |14.94Mb
  - disney_netflix_JP |10.33Mb
  - Relay_-ğŸ‡»ğŸ‡³VN_59 |11.02Mb
  - Relay_-ğŸ‡­ğŸ‡°HK_48 |10.44Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_58 |11.66Mb
  - Relay_-ğŸ‡¹ğŸ‡¼TW_50 |10.72Mb
  - netflix_CA |18.51Mb
  - disney_netflix_JP |11.21Mb
  - disney_netflix_SG |11.55Mb
  - disney_netflix_TW |11.83Mb
  - disney_netflix_US |10.02Mb
  - disney_netflix_JP |11.42Mb
  - disney_netflix_SG |11.46Mb
  - disney_netflix_US |22.96Mb
  - netflix_CA |39.28Mb
  - disney_netflix_US |47.64Mb
  - disney_netflix_HK |30.05Mb
  - disney_netflix_US |17.15Mb
  - netflix_MX |42.10Mb
  - netflix_NL |124.23Mb
  - disney_US |37.42Mb
  - netflix_MD |41.67Mb
  - disney_netflix_US |11.43Mb
  - disney_netflix_US |10.18Mb
  - disney_netflix_JP |20.77Mb
  - disney_netflix_SG |11.56Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - netflix_NL |216.28Mb
  - netflix_TR |21.89Mb
  - netflix_IL |18.88Mb
  - disney_netflix_HK |29.75Mb
  - disney_netflix_SG |37.32Mb
  - disney_netflix_JP |14.94Mb
  - disney_netflix_JP |10.33Mb
  - Relay_-ğŸ‡»ğŸ‡³VN_59 |11.02Mb
  - Relay_-ğŸ‡­ğŸ‡°HK_48 |10.44Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_58 |11.66Mb
  - Relay_-ğŸ‡¹ğŸ‡¼TW_50 |10.72Mb
  - netflix_CA |18.51Mb
  - disney_netflix_JP |11.21Mb
  - disney_netflix_SG |11.55Mb
  - disney_netflix_TW |11.83Mb
  - disney_netflix_US |10.02Mb
  - disney_netflix_JP |11.42Mb
  - disney_netflix_SG |11.46Mb
  - disney_netflix_US |22.96Mb
  - netflix_CA |39.28Mb
  - disney_netflix_US |47.64Mb
  - disney_netflix_HK |30.05Mb
  - disney_netflix_US |17.15Mb
  - netflix_MX |42.10Mb
  - netflix_NL |124.23Mb
  - disney_US |37.42Mb
  - netflix_MD |41.67Mb
  - disney_netflix_US |11.43Mb
  - disney_netflix_US |10.18Mb
  - disney_netflix_JP |20.77Mb
  - disney_netflix_SG |11.56Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
