port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: disney_MD |10.82Mb
  server: 185.153.197.5
  type: ss
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: _504 |47.70Mb
  server: 213.159.67.124
  type: ss
  port: 443
  password: mbhqsStnFQT1cTZYCdsmkugGUC6GT6rp
  cipher: chacha20-ietf-poly1305
- name: _505 |69.47Mb
  server: 45.93.95.187
  type: ss
  port: 8618
  udp: true
  password: 4lUEC91c1d8oeClzDbYpXA
  cipher: chacha20-ietf-poly1305
- name: _530 |53.36Mb
  server: 47.253.197.26
  type: vmess
  port: 12056
  uuid: dd7be7f1-38ff-45e6-f1e5-b20c2190f527
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
- name: _507 |264.17Mb
  server: 45.87.175.181
  type: ss
  port: 8080
  udp: true
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_NL |236.84Mb
  server: 151.242.251.137
  type: ss
  port: 8080
  password: o5osZg269v5zHpYjr1xY9s
  cipher: chacha20-ietf-poly1305
- name: _525 |192.42Mb
  server: 104.168.94.41
  type: vmess
  port: 32301
  uuid: a2235b72-fd9c-404f-be5a-53b2de0cb798
  alterId: 0
  cipher: auto
  network: http
  http-opts:
    method: GET
    path:
    - /
  h2-opts: {}
- name: disney_PT |16.31Mb
  server: 185.231.233.112
  type: ss
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: Relay_-ğŸ‡¯ğŸ‡µJP_550 |11.33Mb
  server: 160.16.236.32
  type: trojan
  port: 3093
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¯ğŸ‡µJP_551 |19.17Mb
  server: 52.195.176.26
  type: trojan
  port: 2145
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: Relay_-ğŸ‡²ğŸ‡¾MY_526 |30.45Mb
  server: ml0724.ysds168.shop
  type: vmess
  port: 2052
  udp: true
  uuid: 665d9b8f-153d-4907-adac-de12afd9c851
  alterId: 0
  cipher: auto
  servername: ml0724.ysds168.shop
  http-opts: {}
  h2-opts: {}
  tls: true
- name: Relay_-ğŸ‡³ğŸ‡±NL_552 |17.98Mb
  server: 160.16.124.55
  type: trojan
  port: 2760
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: _543 |107.83Mb
  server: 47.243.209.146
  type: vmess
  port: 29333
  uuid: 9681c9ac-c4e3-4600-b698-5cc6b14085f7
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /arki?ed=2048
- name: disney_US |101.69Mb
  server: 23.247.137.64
  type: trojan
  port: 443
  udp: true
  password: 3c4e10af98c30972
  alpn:
  - h2
  sni: n2.gladns.com
  network: grpc
  grpc-opts:
    grpc-service-name: db
- name: Relay_-ğŸ‡±ğŸ‡»LV_537 |15.64Mb
  server: 31.56.117.73
  type: vmess
  port: 28573
  uuid: aa521837-6bfb-47dd-c87c-ec730a974020
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
- name: disney_RU |105.93Mb
  server: 37.18.14.33
  type: trojan
  port: 443
  udp: true
  password: Qzy7tgpRhu
  sni: m.vk.com
  skip-cert-verify: true
- name: Relay_-ğŸ‡ºğŸ‡¸US_566 |15.86Mb
  server: gy3.hdcloud.link
  type: trojan
  port: 443
  udp: true
  password: 9b6419f8-8120-442e-a48c-6bf52aef0abf
  network: grpc
  grpc-opts:
    grpc-service-name: GunService
- name: Relay_-ğŸ‡³ğŸ‡±NL_569 |11.19Mb
  server: 153.121.73.102
  type: trojan
  port: 2760
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡°ğŸ‡·KR_510 |14.52Mb
  server: p141.panda001.net
  type: ss
  port: 4652
  udp: true
  password: qwerREWQ@@
  cipher: aes-256-cfb
- name: Relay_-ğŸ‡³ğŸ‡±NL_571 |10.76Mb
  server: 160.16.214.6
  type: trojan
  port: 4054
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡³ğŸ‡±NL_572 |17.83Mb
  server: 160.16.214.6
  type: trojan
  port: 2760
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: disney_HK |26.16Mb
  server: 58.152.25.20
  type: trojan
  port: 443
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: Relay_-ğŸ‡¯ğŸ‡µJP_574 |14.33Mb
  server: 160.16.223.205
  type: trojan
  port: 1331
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: disney_FR |613.44Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 27092
  uuid: a0596ba6-72a3-4366-8992-77088da65bd8
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡§ğŸ‡¬BG_575 |35.15Mb
  server: 87.121.162.249
  type: ss
  country: ğŸ‡§ğŸ‡¬BG
  port: 443
  password: JGv616hMWdjfuZ00jYfq7XkBHJZrOBrg
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡§ğŸ‡·BR_576 |20.68Mb
  server: 38.180.16.86
  type: vmess
  country: ğŸ‡§ğŸ‡·BR
  port: 36104
  uuid: E146A8CB-9D2F-449C-ADCA-8736FB
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡§ğŸ‡·BR_577 |22.70Mb
  server: 38.180.16.86
  type: vmess
  country: ğŸ‡§ğŸ‡·BR
  port: 36236
  uuid: a58bc1a5-8c18-49ff-9453-c331b52f45dc
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡¬ğŸ‡§GB_583 |238.94Mb
  server: 82.38.31.179
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: _573 |13.74Mb
  server: 58.152.18.192
  type: trojan
  port: 443
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_ğŸ‡¬ğŸ‡§GB-ğŸ‡ºğŸ‡¸US_584 |11.70Mb
  server: 82.198.246.97
  type: vmess
  country: ğŸ‡¬ğŸ‡§GB
  port: 180
  uuid: d13fc2f5-3e05-4795-81eb-44143a09e552
  alterId: 0
  cipher: auto
  network: tcp
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: netflix_IE |80.25Mb
  server: 18.203.220.111
  type: ss
  country: ğŸ‡®ğŸ‡ªIE
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡¬ğŸ‡·GR_585 |517.83Mb
  server: 192.71.166.100
  type: ss
  country: ğŸ‡¬ğŸ‡·GR
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ğŸ‡±ğŸ‡¹LT_685 |261.15Mb
  server: 45.87.175.166
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 443
  password: 1RWwXhwfAB5gAEozU4G2Pg
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡­ğŸ‡°HK_603 |14.87Mb
  server: 47.242.140.52
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 48219
  uuid: 006893c6-79b1-4c44-94ff-b8bbea065f1f
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
  ws-opts:
    path: /arki?ed=2048
- name: ğŸ‡­ğŸ‡°HK_673 |174.55Mb
  server: 8.218.17.136
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 52986
  uuid: 7363d47e-ac8b-4fe0-d23e-99077999a70d
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡­ğŸ‡°HK_679 |175.44Mb
  server: 8.217.176.108
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 33185
  uuid: ebb5a5db-c0dc-487a-c41f-07219c9a0ddc
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_HK |13.07Mb
  server: 112.118.116.66
  type: trojan
  country: ğŸ‡­ğŸ‡°HK
  port: 443
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: ğŸ‡ºğŸ‡¸US_690 |24.95Mb
  server: 23.95.75.146
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: NDRySIABARbErNIVsCNVkyYAHiBzhveT
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡²ğŸ‡½MX_686 |25.86Mb
  server: 216.238.89.53
  type: vmess
  country: ğŸ‡²ğŸ‡½MX
  port: 57283
  uuid: 1a5aafc0-6482-451d-fe76-6875b7818579
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡°ğŸ‡·KR_684 |11.81Mb
  server: 146.56.112.110
  type: vmess
  country: ğŸ‡°ğŸ‡·KR
  port: 8888
  uuid: e7c302f3-90d6-42dd-9d7d-94a3683a3707
  alterId: 0
  cipher: auto
  network: tcp
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡ºğŸ‡¸US_692 |232.09Mb
  server: pupas-shirting-unsung.freesocks.work
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: p78naCf2EfOlRSLTX0wFVx
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_695 |113.16Mb
  server: 74.117.196.232
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 37934
  uuid: 54a0bf6d-f2b5-4b2a-942c-798fb129527e
  alterId: 0
  cipher: auto
  network: ws
  servername: imafake.locker
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /speedtest
    headers:
      HOST: imafake.locker
- name: disney_PY |16.18Mb
  server: 38.165.233.93
  type: ss
  country: ğŸ‡ºğŸ‡¸ US
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: Relay_ğŸ‡­ğŸ‡°HK-ğŸ‡­ğŸ‡°HK_659 |50.24Mb
  server: v10.hdacd.com
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 30807
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: auto
  network: tcp
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡²ğŸ‡¾MY_687 |30.18Mb
  server: 38.54.98.110
  type: vmess
  country: ğŸ‡²ğŸ‡¾MY
  port: 2052
  uuid: 665d9b8f-153d-4907-adac-de12afd9c851
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: disney_HK |22.99Mb
  server: 45.136.12.37
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 38141
  uuid: fd291be6-b48d-43a1-da38-66c7f80e2f80
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_697 |89.93Mb
  server: sw19.sesamebuta.top
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  uuid: 805ba514-bf2f-4d5d-df49-8417804e8de3
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /abcd
- name: disney_US |144.86Mb
  server: cf.fovi.tk
  type: vmess
  country: ğŸZZ
  port: 443
  uuid: bf67437e-6c90-45ca-abc2-c7240a5ce2aa
  alterId: 0
  cipher: auto
  network: ws
  servername: foxlux.fovi.tk
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /eisasqa
    headers:
      HOST: foxlux.fovi.tk
- name: ğŸ‡¬ğŸ‡§GB_581 |35.55Mb
  server: 185.193.48.157
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: zwBLM6bBE5YxvwvnKgxAq3ErXpqMYv20
  cipher: chacha20-ietf-poly1305
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - disney_MD |10.82Mb
  - _504 |47.70Mb
  - _505 |69.47Mb
  - _530 |53.36Mb
  - _507 |264.17Mb
  - disney_netflix_NL |236.84Mb
  - _525 |192.42Mb
  - disney_PT |16.31Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_550 |11.33Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_551 |19.17Mb
  - Relay_-ğŸ‡²ğŸ‡¾MY_526 |30.45Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_552 |17.98Mb
  - _543 |107.83Mb
  - disney_US |101.69Mb
  - Relay_-ğŸ‡±ğŸ‡»LV_537 |15.64Mb
  - disney_RU |105.93Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_566 |15.86Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_569 |11.19Mb
  - Relay_-ğŸ‡°ğŸ‡·KR_510 |14.52Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_571 |10.76Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_572 |17.83Mb
  - disney_HK |26.16Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_574 |14.33Mb
  - disney_FR |613.44Mb
  - ğŸ‡§ğŸ‡¬BG_575 |35.15Mb
  - ğŸ‡§ğŸ‡·BR_576 |20.68Mb
  - ğŸ‡§ğŸ‡·BR_577 |22.70Mb
  - ğŸ‡¬ğŸ‡§GB_583 |238.94Mb
  - _573 |13.74Mb
  - Relay_ğŸ‡¬ğŸ‡§GB-ğŸ‡ºğŸ‡¸US_584 |11.70Mb
  - netflix_IE |80.25Mb
  - ğŸ‡¬ğŸ‡·GR_585 |517.83Mb
  - ğŸ‡±ğŸ‡¹LT_685 |261.15Mb
  - ğŸ‡­ğŸ‡°HK_603 |14.87Mb
  - ğŸ‡­ğŸ‡°HK_673 |174.55Mb
  - ğŸ‡­ğŸ‡°HK_679 |175.44Mb
  - disney_HK |13.07Mb
  - ğŸ‡ºğŸ‡¸US_690 |24.95Mb
  - ğŸ‡²ğŸ‡½MX_686 |25.86Mb
  - ğŸ‡°ğŸ‡·KR_684 |11.81Mb
  - ğŸ‡ºğŸ‡¸US_692 |232.09Mb
  - ğŸ‡ºğŸ‡¸US_695 |113.16Mb
  - disney_PY |16.18Mb
  - Relay_ğŸ‡­ğŸ‡°HK-ğŸ‡­ğŸ‡°HK_659 |50.24Mb
  - ğŸ‡²ğŸ‡¾MY_687 |30.18Mb
  - disney_HK |22.99Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_697 |89.93Mb
  - disney_US |144.86Mb
  - ğŸ‡¬ğŸ‡§GB_581 |35.55Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - disney_MD |10.82Mb
  - _504 |47.70Mb
  - _505 |69.47Mb
  - _530 |53.36Mb
  - _507 |264.17Mb
  - disney_netflix_NL |236.84Mb
  - _525 |192.42Mb
  - disney_PT |16.31Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_550 |11.33Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_551 |19.17Mb
  - Relay_-ğŸ‡²ğŸ‡¾MY_526 |30.45Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_552 |17.98Mb
  - _543 |107.83Mb
  - disney_US |101.69Mb
  - Relay_-ğŸ‡±ğŸ‡»LV_537 |15.64Mb
  - disney_RU |105.93Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_566 |15.86Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_569 |11.19Mb
  - Relay_-ğŸ‡°ğŸ‡·KR_510 |14.52Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_571 |10.76Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_572 |17.83Mb
  - disney_HK |26.16Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_574 |14.33Mb
  - disney_FR |613.44Mb
  - ğŸ‡§ğŸ‡¬BG_575 |35.15Mb
  - ğŸ‡§ğŸ‡·BR_576 |20.68Mb
  - ğŸ‡§ğŸ‡·BR_577 |22.70Mb
  - ğŸ‡¬ğŸ‡§GB_583 |238.94Mb
  - _573 |13.74Mb
  - Relay_ğŸ‡¬ğŸ‡§GB-ğŸ‡ºğŸ‡¸US_584 |11.70Mb
  - netflix_IE |80.25Mb
  - ğŸ‡¬ğŸ‡·GR_585 |517.83Mb
  - ğŸ‡±ğŸ‡¹LT_685 |261.15Mb
  - ğŸ‡­ğŸ‡°HK_603 |14.87Mb
  - ğŸ‡­ğŸ‡°HK_673 |174.55Mb
  - ğŸ‡­ğŸ‡°HK_679 |175.44Mb
  - disney_HK |13.07Mb
  - ğŸ‡ºğŸ‡¸US_690 |24.95Mb
  - ğŸ‡²ğŸ‡½MX_686 |25.86Mb
  - ğŸ‡°ğŸ‡·KR_684 |11.81Mb
  - ğŸ‡ºğŸ‡¸US_692 |232.09Mb
  - ğŸ‡ºğŸ‡¸US_695 |113.16Mb
  - disney_PY |16.18Mb
  - Relay_ğŸ‡­ğŸ‡°HK-ğŸ‡­ğŸ‡°HK_659 |50.24Mb
  - ğŸ‡²ğŸ‡¾MY_687 |30.18Mb
  - disney_HK |22.99Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_697 |89.93Mb
  - disney_US |144.86Mb
  - ğŸ‡¬ğŸ‡§GB_581 |35.55Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
