port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: _325 |54.51Mb
  server: 103.35.189.136
  type: ss
  port: 443
  udp: true
  password: SS2QvbC9nqLp2sXXZo0BVy4slcErRuCt
  cipher: chacha20-ietf-poly1305
- name: _321 |11.74Mb
  server: 172.105.199.111
  type: ss
  port: 8080
  udp: true
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: _327 |16.32Mb
  server: 196.196.192.58
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _329 |12.14Mb
  server: 82.38.31.190
  type: ss
  port: 8080
  udp: true
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: _324 |23.92Mb
  server: 82.38.31.202
  type: ss
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: _328 |42.41Mb
  server: 138.186.143.32
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _326 |553.74Mb
  server: 46.183.184.60
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: _331 |14.84Mb
  server: 89.221.225.15
  type: ss
  port: 443
  udp: true
  password: yCbQ4bry4otfifK7oel71NaXpPL9pYJb
  cipher: chacha20-ietf-poly1305
- name: _333 |20.80Mb
  server: 146.70.61.37
  type: ss
  port: 8080
  udp: true
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: _338 |21.43Mb
  server: 62.100.205.100
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _336 |44.32Mb
  server: 141.98.101.178
  type: ss
  port: 443
  udp: true
  password: shadowsocks
  cipher: aes-128-gcm
- name: _348 |171.51Mb
  server: 138.186.143.32
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: _334 |26.41Mb
  server: 119.59.98.58
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: _354 |16.08Mb
  server: 156.146.38.167
  type: ss
  port: 443
  udp: true
  password: shadowsocks
  cipher: aes-128-gcm
- name: _343 |45.19Mb
  server: 95.164.116.33
  type: ss
  port: 443
  password: pQmnC03JObbPhdh5FBJHgD6jnTLchsRA
  cipher: chacha20-ietf-poly1305
- name: _347 |28.34Mb
  server: 119.59.98.58
  type: ss
  port: 990
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: chacha20-ietf-poly1305
- name: _356 |16.52Mb
  server: 156.146.38.169
  type: ss
  port: 443
  udp: true
  password: shadowsocks
  cipher: aes-128-gcm
- name: _361 |17.93Mb
  server: 156.146.38.170
  type: ss
  port: 443
  udp: true
  password: shadowsocks
  cipher: aes-128-gcm
- name: _363 |44.95Mb
  server: 173.244.56.6
  type: ss
  port: 443
  udp: true
  password: shadowsocks
  cipher: aes-128-gcm
- name: _355 |49.35Mb
  server: 137.184.174.93
  type: ss
  port: 8080
  udp: true
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: _353 |14.56Mb
  server: 149.22.87.241
  type: ss
  port: 443
  udp: true
  password: shadowsocks
  cipher: aes-128-gcm
- name: Relay_-ğŸ‡¨ğŸ‡¦CA_362 |69.23Mb
  server: 79.127.200.169
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _349 |43.26Mb
  server: 103.97.203.227
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: disney_PY |14.55Mb
  server: 38.165.233.93
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: _358 |231.95Mb
  server: 82.38.31.194
  type: ss
  port: 8080
  udp: true
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: _360 |228.01Mb
  server: 151.242.251.147
  type: ss
  port: 8080
  password: QCXDxuDlTTMD7jtgHUjIoj
  cipher: chacha20-ietf-poly1305
- name: _323 |303.37Mb
  server: h110vpnnl.outlinekeys.net
  type: ss
  port: 52571
  udp: true
  password: b0TKxnHAYeeFYyzTAMXn0F
  cipher: chacha20-ietf-poly1305
- name: _368 |12.23Mb
  server: 68.183.227.4
  type: ss
  port: 8080
  udp: true
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: _378 |10.08Mb
  server: 82.38.31.176
  type: ss
  port: 8080
  udp: true
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: disney_ES |21.67Mb
  server: 145.249.109.121
  type: ss
  port: 25512
  udp: true
  password: smSMfR9jqLgMkHuQtxSIWh
  cipher: chacha20-ietf-poly1305
- name: _364 |45.26Mb
  server: 147.78.0.182
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _380 |166.62Mb
  server: 45.87.175.22
  type: ss
  port: 8080
  udp: true
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: _376 |14.12Mb
  server: 128.199.172.224
  type: ss
  port: 8080
  udp: true
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: _371 |44.28Mb
  server: 156.59.243.6
  type: ss
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: Relay_-ğŸ‡­ğŸ‡°HK_381 |28.26Mb
  server: 103.149.182.105
  type: ss
  port: 8388
  password: asd123456
  cipher: chacha20-ietf
- name: _382 |36.54Mb
  server: 45.87.175.28
  type: ss
  port: 8080
  udp: true
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: _388 |22.03Mb
  server: 173.234.29.2
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _383 |10.54Mb
  server: 45.158.171.70
  type: ss
  port: 8080
  udp: true
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: disney_US |69.91Mb
  server: 79.127.200.162
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: _384 |109.34Mb
  server: 185.82.73.212
  type: ss
  port: 8444
  udp: true
  password: _bypfvq6ra7g4n5yCCR9DoVeGya2XUUS
  cipher: chacha20-ietf-poly1305
- name: _385 |13.18Mb
  server: 185.192.124.188
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: disney_MX |28.80Mb
  server: 38.165.231.25
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _391 |242.46Mb
  server: 51.15.23.166
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: _387 |18.34Mb
  server: 194.246.114.101
  type: ss
  port: 443
  udp: true
  password: HaNqw9pIE4jcx98sg7UQgHeGNTM4R2pk
  cipher: chacha20-ietf-poly1305
- name: _386 |10.92Mb
  server: 38.89.142.56
  type: ss
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: disney_HK |18.15Mb
  server: 149.88.95.217
  type: vmess
  port: 40741
  uuid: 1b8a751b-4909-4fec-f019-907d92e6c47f
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
- name: disney_US |19.96Mb
  server: 156.233.232.192
  type: vmess
  port: 24004
  uuid: 582fcb35-20a0-452c-e179-4c759c62c494
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
- name: disney_HK |16.82Mb
  server: 149.88.95.217
  type: vmess
  port: 35760
  uuid: 17e96792-d8c3-4741-9c34-e5d1c11d754f
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
- name: Relay_-ğŸ‡¯ğŸ‡µJP_411 |41.91Mb
  server: 160.16.229.223
  type: trojan
  port: 3169
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: _415 |11.11Mb
  server: 160.16.106.144
  type: trojan
  port: 2760
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
  skip-cert-verify: true
- name: disney_HK |14.99Mb
  server: 149.88.95.94
  type: vmess
  port: 35760
  uuid: 17e96792-d8c3-4741-9c34-e5d1c11d754f
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
- name: _414 |13.28Mb
  server: 47.242.225.242
  type: trojan
  port: 443
  udp: true
  password: 92690597d6298061459918a371e8d77d
  sni: hezijiasuqi.com
  skip-cert-verify: true
- name: disney_HK |16.82Mb
  server: 149.88.95.94
  type: vmess
  port: 40741
  uuid: 1b8a751b-4909-4fec-f019-907d92e6c47f
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
- name: _420 |10.51Mb
  server: 160.16.116.227
  type: trojan
  port: 2760
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
  skip-cert-verify: true
- name: disney_HK |27.27Mb
  server: 219.79.214.159
  type: trojan
  port: 443
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: _422 |16.63Mb
  server: 160.16.204.136
  type: trojan
  port: 2890
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: disney_US |71.13Mb
  server: 156.233.232.177
  type: vmess
  port: 24004
  uuid: 582fcb35-20a0-452c-e179-4c759c62c494
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
- name: _426 |11.15Mb
  server: 160.16.131.243
  type: trojan
  port: 2760
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
  skip-cert-verify: true
- name: ğŸ‡§ğŸ‡·BR_428 |13.14Mb
  server: 185.192.124.188
  type: ss
  country: ğŸ‡§ğŸ‡·BR
  port: 990
  password: f8f7aCzcPKbsF8p3
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¨ğŸ‡¦CA_430 |64.79Mb
  server: 185.213.23.63
  type: ss
  country: ğŸ‡¨ğŸ‡¦CA
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: disney_DE |45.31Mb
  server: 89.163.140.136
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ğŸ‡¨ğŸ‡­CH_431 |48.47Mb
  server: 138.124.67.26
  type: ss
  country: ğŸ‡¨ğŸ‡­CH
  port: 25572
  password: nqcIfYHlpMn3jzqkNDjKaG
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_GB |83.13Mb
  server: 141.98.101.182
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: shadowsocks
  cipher: aes-128-gcm
- name: ğŸ‡®ğŸ‡¹IT_441 |39.45Mb
  server: 176.126.83.121
  type: ss
  country: ğŸ‡®ğŸ‡¹IT
  port: 443
  password: Q4t8T7hEYY3mD2Fn4wnxyK4X35AUzvR8
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡°ğŸ‡·KR_444 |10.37Mb
  server: seoul03.zgjok.com
  type: vmess
  country: ğŸ‡°ğŸ‡·KR
  port: 443
  uuid: 72a0dac4-9689-4a57-b164-5c65bfa94772
  alterId: 0
  cipher: auto
  network: ws
  servername: seoul03.zgjok.com
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /
    headers:
      HOST: seoul03.zgjok.com
- name: ğŸ‡±ğŸ‡¹LT_446 |132.98Mb
  server: 45.87.175.185
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: Relay_-ğŸ‡ºğŸ‡¸US_421 |36.92Mb
  server: green2.cdntencentmusic.com
  type: trojan
  port: 35501
  udp: true
  password: ef76d08c-9841-47e8-92a6-5b74df5d58ac
  sni: green2.cdntencentmusic.com
  skip-cert-verify: true
- name: ğŸ‡±ğŸ‡¹LT_448 |196.79Mb
  server: 45.87.175.185
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_450 |195.14Mb
  server: 45.87.175.180
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: QCXDxuDlTTMD7jtgHUjIoj
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_451 |11.27Mb
  server: 45.87.175.175
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: QCXDxuDlTTMD7jtgHUjIoj
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡²ğŸ‡½MX_455 |15.64Mb
  server: 216.238.87.47
  type: vmess
  country: ğŸ‡²ğŸ‡½MX
  port: 27502
  uuid: b8155ce4-7e08-4c40-800f-8671312b7124
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡±ğŸ‡¹LT_452 |85.07Mb
  server: 45.87.175.183
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸZZ-ğŸ‡®ğŸ‡³IN_468 |145.86Mb
  server: 104.18.14.55
  type: vmess
  country: ğŸZZ
  port: 2052
  uuid: e6447786-8c85-443c-8017-7feaa673ff45
  alterId: 0
  cipher: auto
  network: ws
  servername: in4.123417.xyz
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
  ws-opts:
    path: /
    headers:
      HOST: in4.123417.xyz
- name: ğŸ‡±ğŸ‡» LV_453 |12.57Mb
  server: 46.183.217.204
  type: ss
  country: ğŸ‡±ğŸ‡» LV
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡³ğŸ‡±NL_459 |146.34Mb
  server: 193.29.139.141
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 8080
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: netflix_MD |16.80Mb
  server: 176.123.5.253
  type: ss
  country: ğŸ‡²ğŸ‡©MD
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡³ğŸ‡±NL_460 |300.67Mb
  server: 194.87.216.218
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 52571
  password: b0TKxnHAYeeFYyzTAMXn0F
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡³ğŸ‡±NL_461 |57.99Mb
  server: 178.23.190.238
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 443
  password: uo7EbtqIwgZXXHmMv5LbLcOxptyPlNkh
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡µğŸ‡¹PT_464 |84.52Mb
  server: 185.113.143.186
  type: ss
  country: ğŸ‡µğŸ‡¹PT
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¸ğŸ‡¬SG_465 |12.57Mb
  server: 68.183.227.45
  type: ss
  country: ğŸ‡¸ğŸ‡¬SG
  port: 8080
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: ğŸ ZZ_467 |137.58Mb
  server: 185.231.233.112
  type: ss
  country: ğŸ ZZ
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: Relay_ğŸZZ-ğŸ‡®ğŸ‡·IR_469 |16.79Mb
  server: cf.fovi.tk
  type: vmess
  country: ğŸZZ
  port: 443
  uuid: bf67437e-6c90-45ca-abc2-c7240a5ce2aa
  alterId: 0
  cipher: auto
  network: ws
  servername: foxlux.fovi.tk
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /eisasqa
    headers:
      HOST: foxlux.fovi.tk
- name: _352 |397.68Mb
  server: 45.14.245.2
  type: ss
  port: 443
  password: 17ZDORWIliQHuO6WRGHChXYMzdRtAYVP
  cipher: chacha20-ietf-poly1305
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - _325 |54.51Mb
  - _321 |11.74Mb
  - _327 |16.32Mb
  - _329 |12.14Mb
  - _324 |23.92Mb
  - _328 |42.41Mb
  - _326 |553.74Mb
  - _331 |14.84Mb
  - _333 |20.80Mb
  - _338 |21.43Mb
  - _336 |44.32Mb
  - _348 |171.51Mb
  - _334 |26.41Mb
  - _354 |16.08Mb
  - _343 |45.19Mb
  - _347 |28.34Mb
  - _356 |16.52Mb
  - _361 |17.93Mb
  - _363 |44.95Mb
  - _355 |49.35Mb
  - _353 |14.56Mb
  - Relay_-ğŸ‡¨ğŸ‡¦CA_362 |69.23Mb
  - _349 |43.26Mb
  - disney_PY |14.55Mb
  - _358 |231.95Mb
  - _360 |228.01Mb
  - _323 |303.37Mb
  - _368 |12.23Mb
  - _378 |10.08Mb
  - disney_ES |21.67Mb
  - _364 |45.26Mb
  - _380 |166.62Mb
  - _376 |14.12Mb
  - _371 |44.28Mb
  - Relay_-ğŸ‡­ğŸ‡°HK_381 |28.26Mb
  - _382 |36.54Mb
  - _388 |22.03Mb
  - _383 |10.54Mb
  - disney_US |69.91Mb
  - _384 |109.34Mb
  - _385 |13.18Mb
  - disney_MX |28.80Mb
  - _391 |242.46Mb
  - _387 |18.34Mb
  - _386 |10.92Mb
  - disney_HK |18.15Mb
  - disney_US |19.96Mb
  - disney_HK |16.82Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_411 |41.91Mb
  - _415 |11.11Mb
  - disney_HK |14.99Mb
  - _414 |13.28Mb
  - disney_HK |16.82Mb
  - _420 |10.51Mb
  - disney_HK |27.27Mb
  - _422 |16.63Mb
  - disney_US |71.13Mb
  - _426 |11.15Mb
  - ğŸ‡§ğŸ‡·BR_428 |13.14Mb
  - ğŸ‡¨ğŸ‡¦CA_430 |64.79Mb
  - disney_DE |45.31Mb
  - ğŸ‡¨ğŸ‡­CH_431 |48.47Mb
  - disney_netflix_GB |83.13Mb
  - ğŸ‡®ğŸ‡¹IT_441 |39.45Mb
  - ğŸ‡°ğŸ‡·KR_444 |10.37Mb
  - ğŸ‡±ğŸ‡¹LT_446 |132.98Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_421 |36.92Mb
  - ğŸ‡±ğŸ‡¹LT_448 |196.79Mb
  - ğŸ‡±ğŸ‡¹LT_450 |195.14Mb
  - ğŸ‡±ğŸ‡¹LT_451 |11.27Mb
  - ğŸ‡²ğŸ‡½MX_455 |15.64Mb
  - ğŸ‡±ğŸ‡¹LT_452 |85.07Mb
  - Relay_ğŸZZ-ğŸ‡®ğŸ‡³IN_468 |145.86Mb
  - ğŸ‡±ğŸ‡» LV_453 |12.57Mb
  - ğŸ‡³ğŸ‡±NL_459 |146.34Mb
  - netflix_MD |16.80Mb
  - ğŸ‡³ğŸ‡±NL_460 |300.67Mb
  - ğŸ‡³ğŸ‡±NL_461 |57.99Mb
  - ğŸ‡µğŸ‡¹PT_464 |84.52Mb
  - ğŸ‡¸ğŸ‡¬SG_465 |12.57Mb
  - ğŸ ZZ_467 |137.58Mb
  - Relay_ğŸZZ-ğŸ‡®ğŸ‡·IR_469 |16.79Mb
  - _352 |397.68Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - _325 |54.51Mb
  - _321 |11.74Mb
  - _327 |16.32Mb
  - _329 |12.14Mb
  - _324 |23.92Mb
  - _328 |42.41Mb
  - _326 |553.74Mb
  - _331 |14.84Mb
  - _333 |20.80Mb
  - _338 |21.43Mb
  - _336 |44.32Mb
  - _348 |171.51Mb
  - _334 |26.41Mb
  - _354 |16.08Mb
  - _343 |45.19Mb
  - _347 |28.34Mb
  - _356 |16.52Mb
  - _361 |17.93Mb
  - _363 |44.95Mb
  - _355 |49.35Mb
  - _353 |14.56Mb
  - Relay_-ğŸ‡¨ğŸ‡¦CA_362 |69.23Mb
  - _349 |43.26Mb
  - disney_PY |14.55Mb
  - _358 |231.95Mb
  - _360 |228.01Mb
  - _323 |303.37Mb
  - _368 |12.23Mb
  - _378 |10.08Mb
  - disney_ES |21.67Mb
  - _364 |45.26Mb
  - _380 |166.62Mb
  - _376 |14.12Mb
  - _371 |44.28Mb
  - Relay_-ğŸ‡­ğŸ‡°HK_381 |28.26Mb
  - _382 |36.54Mb
  - _388 |22.03Mb
  - _383 |10.54Mb
  - disney_US |69.91Mb
  - _384 |109.34Mb
  - _385 |13.18Mb
  - disney_MX |28.80Mb
  - _391 |242.46Mb
  - _387 |18.34Mb
  - _386 |10.92Mb
  - disney_HK |18.15Mb
  - disney_US |19.96Mb
  - disney_HK |16.82Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_411 |41.91Mb
  - _415 |11.11Mb
  - disney_HK |14.99Mb
  - _414 |13.28Mb
  - disney_HK |16.82Mb
  - _420 |10.51Mb
  - disney_HK |27.27Mb
  - _422 |16.63Mb
  - disney_US |71.13Mb
  - _426 |11.15Mb
  - ğŸ‡§ğŸ‡·BR_428 |13.14Mb
  - ğŸ‡¨ğŸ‡¦CA_430 |64.79Mb
  - disney_DE |45.31Mb
  - ğŸ‡¨ğŸ‡­CH_431 |48.47Mb
  - disney_netflix_GB |83.13Mb
  - ğŸ‡®ğŸ‡¹IT_441 |39.45Mb
  - ğŸ‡°ğŸ‡·KR_444 |10.37Mb
  - ğŸ‡±ğŸ‡¹LT_446 |132.98Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_421 |36.92Mb
  - ğŸ‡±ğŸ‡¹LT_448 |196.79Mb
  - ğŸ‡±ğŸ‡¹LT_450 |195.14Mb
  - ğŸ‡±ğŸ‡¹LT_451 |11.27Mb
  - ğŸ‡²ğŸ‡½MX_455 |15.64Mb
  - ğŸ‡±ğŸ‡¹LT_452 |85.07Mb
  - Relay_ğŸZZ-ğŸ‡®ğŸ‡³IN_468 |145.86Mb
  - ğŸ‡±ğŸ‡» LV_453 |12.57Mb
  - ğŸ‡³ğŸ‡±NL_459 |146.34Mb
  - netflix_MD |16.80Mb
  - ğŸ‡³ğŸ‡±NL_460 |300.67Mb
  - ğŸ‡³ğŸ‡±NL_461 |57.99Mb
  - ğŸ‡µğŸ‡¹PT_464 |84.52Mb
  - ğŸ‡¸ğŸ‡¬SG_465 |12.57Mb
  - ğŸ ZZ_467 |137.58Mb
  - Relay_ğŸZZ-ğŸ‡®ğŸ‡·IR_469 |16.79Mb
  - _352 |397.68Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
