port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: _543 |36.87Mb
  server: 172.235.33.114
  type: vmess
  port: 10001
  uuid: 442a3923-eca1-4af0-b3ff-24a7ce0af68f
  alterId: 0
  cipher: auto
  network: tcp
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_-ğŸ‡ºğŸ‡¸US_545 |42.04Mb
  server: us19-25.998998.best
  type: vmess
  port: 443
  udp: true
  uuid: 24254866-770c-41b4-9404-3f50524f425b
  alterId: 0
  cipher: auto
  network: ws
  servername: 24254866-770c-41b4-9404-3f50524f425b.mihomo.baby
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /saoihgreg9384gh8934
    headers:
      Host: 24254866-770c-41b4-9404-3f50524f425b.mihomo.baby
- name: Relay_-ğŸ‡³ğŸ‡±NL_527 |239.13Mb
  server: 151.242.251.137
  type: ss
  port: 8080
  password: o5osZg269v5zHpYjr1xY9s
  cipher: chacha20-ietf-poly1305
- name: Relay_-ğŸ‡³ğŸ‡±NL_528 |248.59Mb
  server: 82.38.31.218
  type: ss
  port: 8080
  udp: true
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: Relay_-ğŸ‡³ğŸ‡±NL_532 |338.08Mb
  server: 151.242.251.144
  type: ss
  port: 8080
  udp: true
  password: QCXDxuDlTTMD7jtgHUjIoj
  cipher: chacha20-ietf-poly1305
- name: _533 |16.32Mb
  server: 82.38.31.179
  type: ss
  port: 8080
  udp: true
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: Relay_-ğŸ‡ºğŸ‡¸US_562 |24.46Mb
  server: 141.193.213.199
  type: trojan
  port: 443
  udp: true
  password: a8a5b34d-fe46-487d-bd6a-d9f3101525fd
  sni: 26z68w0ecxbuyf89.ukgogo202511.top
  skip-cert-verify: true
  ws-opts:
    path: /images
    headers:
      Host: 26z68w0ecxbuyf89.ukgogo202511.top
  network: ws
- name: _538 |116.90Mb
  server: 45.15.126.19
  type: ss
  port: 443
  udp: true
  password: 6Ts2ZDTQAf3hkFoB8AFufDwsGrlF4e2t
  cipher: chacha20-ietf-poly1305
- name: _530 |10.74Mb
  server: 213.159.67.124
  type: ss
  port: 443
  password: mbhqsStnFQT1cTZYCdsmkugGUC6GT6rp
  cipher: chacha20-ietf-poly1305
- name: disney_PT |79.12Mb
  server: 185.231.233.112
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: Relay_-ğŸ‡ºğŸ‡¸US_558 |16.17Mb
  server: gy3.hdcloud.link
  type: trojan
  port: 443
  udp: true
  password: 9b6419f8-8120-442e-a48c-6bf52aef0abf
  network: grpc
  grpc-opts:
    grpc-service-name: GunService
- name: disney_FR |49.04Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 27092
  uuid: a0596ba6-72a3-4366-8992-77088da65bd8
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_ğŸ‡®ğŸ‡· IR-ğŸ‡³ğŸ‡±NL_574 |319.78Mb
  server: 151.242.251.144
  type: ss
  country: ğŸ‡®ğŸ‡· IR
  port: 8080
  password: 4a2rfixophdjffa8KVA4Aa
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸ‡®ğŸ‡· IR-ğŸ‡³ğŸ‡±NL_575 |301.07Mb
  server: 151.242.251.153
  type: ss
  country: ğŸ‡®ğŸ‡· IR
  port: 8080
  password: QCXDxuDlTTMD7jtgHUjIoj
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_580 |79.91Mb
  server: pupas-shirting-unsung.freesocks.work
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: p78naCf2EfOlRSLTX0wFVx
  cipher: chacha20-ietf-poly1305
- name: Relay_-ğŸ‡³ğŸ‡±NL_567 |19.45Mb
  server: 18.162.142.242
  type: trojan
  port: 4054
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: disney_MD |10.02Mb
  server: 185.153.197.5
  type: ss
  country: ğŸ‡·ğŸ‡ºRU
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: disney_PY |15.83Mb
  server: 38.165.233.93
  type: ss
  country: ğŸ‡ºğŸ‡¸ US
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: Relay_-ğŸ‡­ğŸ‡°HK_564 |10.32Mb
  server: green2.cdntencentmusic.com
  type: trojan
  port: 31102
  udp: true
  password: c4173b29-4949-4cb7-95d4-b9552ae8d06d
  sni: green2.cdntencentmusic.com
  skip-cert-verify: true
- name: Relay_ğŸ‡¯ğŸ‡µJP-ğŸ‡¯ğŸ‡µJP_576 |11.80Mb
  server: xray.kk37005.tk
  type: vmess
  country: ğŸ‡¯ğŸ‡µJP
  port: 55919
  uuid: 2e7548bb-7c5b-4d97-d64d-1b2fe4050089
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: Relay_-ğŸ‡¯ğŸ‡µJP_547 |12.73Mb
  server: q0xgj-g06.jp07-sh-vm0.entry.fr0528.art
  type: vmess
  port: 28788
  udp: true
  uuid: 8e0c2bc2-705f-375f-a246-82955b5165ef
  alterId: 1
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: Relay_-ğŸ‡¯ğŸ‡µJP_549 |11.47Mb
  server: z4fti-g01.jp04-1d-vm0.entry.fr0528.art
  type: vmess
  port: 444
  udp: true
  uuid: 1a9f857f-9a07-3a8c-a155-f9ab3c457343
  alterId: 1
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_583 |36.30Mb
  server: sw19.sesamebuta.top
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  uuid: 805ba514-bf2f-4d5d-df49-8417804e8de3
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /abcd
- name: disney_JP |12.88Mb
  server: f8bfn-g05.jp07-sh-vm0.entry.fr0528.art
  type: vmess
  port: 28787
  udp: true
  uuid: ca78405e-e554-3cd3-9b6d-2ec98e21c8f1
  alterId: 1
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: Relay_-ğŸ‡¯ğŸ‡µJP_548 |10.88Mb
  server: lnh1f-g04.jp04-1d-vm0.entry.fr0528.art
  type: vmess
  port: 447
  udp: true
  uuid: c18c4112-fb51-3167-bb76-515d7a2b512d
  alterId: 1
  cipher: auto
  http-opts: {}
  h2-opts: {}
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - _543 |36.87Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_545 |42.04Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_527 |239.13Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_528 |248.59Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_532 |338.08Mb
  - _533 |16.32Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_562 |24.46Mb
  - _538 |116.90Mb
  - _530 |10.74Mb
  - disney_PT |79.12Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_558 |16.17Mb
  - disney_FR |49.04Mb
  - Relay_ğŸ‡®ğŸ‡· IR-ğŸ‡³ğŸ‡±NL_574 |319.78Mb
  - Relay_ğŸ‡®ğŸ‡· IR-ğŸ‡³ğŸ‡±NL_575 |301.07Mb
  - ğŸ‡ºğŸ‡¸US_580 |79.91Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_567 |19.45Mb
  - disney_MD |10.02Mb
  - disney_PY |15.83Mb
  - Relay_-ğŸ‡­ğŸ‡°HK_564 |10.32Mb
  - Relay_ğŸ‡¯ğŸ‡µJP-ğŸ‡¯ğŸ‡µJP_576 |11.80Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_547 |12.73Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_549 |11.47Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_583 |36.30Mb
  - disney_JP |12.88Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_548 |10.88Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - _543 |36.87Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_545 |42.04Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_527 |239.13Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_528 |248.59Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_532 |338.08Mb
  - _533 |16.32Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_562 |24.46Mb
  - _538 |116.90Mb
  - _530 |10.74Mb
  - disney_PT |79.12Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_558 |16.17Mb
  - disney_FR |49.04Mb
  - Relay_ğŸ‡®ğŸ‡· IR-ğŸ‡³ğŸ‡±NL_574 |319.78Mb
  - Relay_ğŸ‡®ğŸ‡· IR-ğŸ‡³ğŸ‡±NL_575 |301.07Mb
  - ğŸ‡ºğŸ‡¸US_580 |79.91Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_567 |19.45Mb
  - disney_MD |10.02Mb
  - disney_PY |15.83Mb
  - Relay_-ğŸ‡­ğŸ‡°HK_564 |10.32Mb
  - Relay_ğŸ‡¯ğŸ‡µJP-ğŸ‡¯ğŸ‡µJP_576 |11.80Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_547 |12.73Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_549 |11.47Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_583 |36.30Mb
  - disney_JP |12.88Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_548 |10.88Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
