port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: _362 |81.70Mb
  server: 103.35.189.136
  type: ss
  port: 443
  udp: true
  password: SS2QvbC9nqLp2sXXZo0BVy4slcErRuCt
  cipher: chacha20-ietf-poly1305
- name: _363 |43.70Mb
  server: 104.192.226.106
  type: ss
  port: 990
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: chacha20-ietf-poly1305
- name: _364 |25.96Mb
  server: 196.196.192.58
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _374 |305.54Mb
  server: 146.70.61.37
  type: ss
  port: 8080
  udp: true
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: _361 |15.73Mb
  server: 82.38.31.179
  type: ss
  port: 8080
  udp: true
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: _372 |150.13Mb
  server: 45.87.175.187
  type: ss
  port: 8080
  udp: true
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: _367 |326.66Mb
  server: 51.15.23.166
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: _359 |28.66Mb
  server: 107.174.114.71
  type: ss
  port: 443
  udp: true
  password: 595HLF3fHUuw0McM51tpvPygSIB1uf4D
  cipher: chacha20-ietf-poly1305
- name: _357 |105.62Mb
  server: 141.98.101.178
  type: ss
  port: 443
  udp: true
  password: shadowsocks
  cipher: aes-128-gcm
- name: _386 |53.88Mb
  server: 156.146.38.167
  type: ss
  port: 443
  udp: true
  password: shadowsocks
  cipher: aes-128-gcm
- name: _376 |32.37Mb
  server: 138.186.142.81
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _380 |226.41Mb
  server: 45.87.175.22
  type: ss
  port: 8080
  udp: true
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: _390 |45.74Mb
  server: 156.146.38.169
  type: ss
  port: 443
  udp: true
  password: shadowsocks
  cipher: aes-128-gcm
- name: _360 |12.89Mb
  server: 38.165.233.93
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: _382 |859.38Mb
  server: 82.38.31.190
  type: ss
  port: 8080
  udp: true
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: _399 |16.50Mb
  server: 173.234.29.2
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _396 |46.08Mb
  server: 156.146.38.170
  type: ss
  port: 443
  udp: true
  password: shadowsocks
  cipher: aes-128-gcm
- name: _403 |53.03Mb
  server: 137.184.174.93
  type: ss
  port: 8080
  udp: true
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: _383 |12.44Mb
  server: 89.221.225.15
  type: ss
  port: 443
  udp: true
  password: yCbQ4bry4otfifK7oel71NaXpPL9pYJb
  cipher: chacha20-ietf-poly1305
- name: _404 |62.56Mb
  server: 15.157.66.237
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: _392 |128.29Mb
  server: 45.87.175.28
  type: ss
  port: 8080
  udp: true
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: _384 |45.05Mb
  server: 95.164.116.33
  type: ss
  port: 443
  password: pQmnC03JObbPhdh5FBJHgD6jnTLchsRA
  cipher: chacha20-ietf-poly1305
- name: _393 |11.31Mb
  server: 45.158.171.70
  type: ss
  port: 8080
  udp: true
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: _395 |51.04Mb
  server: 45.12.136.170
  type: ss
  port: 443
  udp: true
  password: l668XHPejoSNNuD66BYzyehaCpZexiF7
  cipher: chacha20-ietf-poly1305
- name: disney_US |70.68Mb
  server: 79.127.200.162
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: _407 |21.92Mb
  server: 151.242.251.147
  type: ss
  port: 8080
  password: QCXDxuDlTTMD7jtgHUjIoj
  cipher: chacha20-ietf-poly1305
- name: _405 |68.98Mb
  server: 5.181.21.246
  type: ss
  port: 443
  udp: true
  password: gKYygTcRYhc3skc2x6tZ073lYz0DnieX
  cipher: chacha20-ietf-poly1305
- name: _413 |742.99Mb
  server: 82.38.31.176
  type: ss
  port: 8080
  udp: true
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: _401 |21.65Mb
  server: 172.105.199.111
  type: ss
  port: 8080
  udp: true
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: _389 |12.27Mb
  server: 172.237.74.36
  type: ss
  port: 443
  udp: true
  password: Dk0XrU/n+SB84g0k+mX4zdy5HVVhuAUP6pCaldJxQjY=
  cipher: aes-256-gcm
- name: _406 |22.69Mb
  server: 149.22.87.241
  type: ss
  port: 443
  udp: true
  password: shadowsocks
  cipher: aes-128-gcm
- name: _412 |30.98Mb
  server: 147.78.0.182
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: Relay_-ğŸ‡¨ğŸ‡¦CA_425 |70.10Mb
  server: 79.127.200.169
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _423 |15.09Mb
  server: 173.244.56.6
  type: ss
  port: 443
  udp: true
  password: shadowsocks
  cipher: aes-128-gcm
- name: _419 |24.95Mb
  server: 185.192.124.188
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: _421 |10.35Mb
  server: 45.87.175.197
  type: ss
  port: 8080
  udp: true
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: disney_MX |28.40Mb
  server: 38.165.231.25
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _410 |43.39Mb
  server: 156.59.243.6
  type: ss
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _433 |54.73Mb
  server: 45.87.175.178
  type: ss
  port: 8080
  udp: true
  password: QCXDxuDlTTMD7jtgHUjIoj
  cipher: chacha20-ietf-poly1305
- name: disney_US |40.40Mb
  server: 154.29.157.189
  type: vmess
  port: 38152
  uuid: b8ce19b1-4b15-41f9-a206-11957cc902d4
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
- name: _416 |15.57Mb
  server: 194.246.114.101
  type: ss
  port: 443
  udp: true
  password: HaNqw9pIE4jcx98sg7UQgHeGNTM4R2pk
  cipher: chacha20-ietf-poly1305
- name: disney_DO |57.17Mb
  server: xcf017-2.facai2024.com
  type: vmess
  port: 443
  uuid: db5208f7-b9b6-4396-b36e-b05b2153f595
  alterId: 0
  cipher: auto
  network: ws
  servername: xcf017-2.facai2024.com
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /db5208f7
- name: _418 |16.17Mb
  server: 128.199.172.224
  type: ss
  port: 8080
  udp: true
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: disney_US |41.34Mb
  server: 165.140.216.141
  type: vmess
  port: 443
  uuid: e7d72a8d-26f2-4b54-b366-0c43e0bcba7d
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _466 |30.58Mb
  server: 47.253.228.138
  type: vmess
  port: 22524
  uuid: 80845fcc-f862-45fe-c1d3-0a7120373712
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
- name: _426 |28.70Mb
  server: 119.59.98.58
  type: ss
  port: 990
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: chacha20-ietf-poly1305
- name: disney_SG |25.05Mb
  server: 185.36.192.228
  type: vmess
  port: 35488
  uuid: fb5a4283-dbfb-458b-8619-c4a53739f781
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
- name: _429 |30.78Mb
  server: 119.59.98.58
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: _450 |10.10Mb
  server: 54.206.192.9
  type: vmess
  port: 16407
  uuid: 08f45028-1db6-4e93-bf51-d344b6c71e19
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: disney_US |11.06Mb
  server: 206.119.191.9
  type: vmess
  port: 7100
  uuid: 10853485-26e1-477b-d257-58a3f4873db3
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
- name: _462 |10.29Mb
  server: 47.243.29.191
  type: vmess
  port: 13141
  uuid: 67126fa6-ecaa-4699-d5e7-515d968b33a9
  alterId: 0
  cipher: auto
  network: http
  http-opts:
    method: GET
    path:
    - /
  h2-opts: {}
- name: Pool__554 |24.55Mb
  server: 38.96.254.102
  type: trojan
  port: 18509
  password: .ie4rghJuMkcf0oF
  sni: shoppingmall.electricbanana.click
- name: _463 |40.34Mb
  server: 89.31.120.192
  type: vmess
  port: 443
  uuid: 44537595-9ccc-4b83-8936-5f9ad3229019
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _502 |10.68Mb
  server: 160.16.81.84
  type: trojan
  port: 2760
  password: 44e660b0ee21cf3ac66aee2c08af85d2
  sni: www.nintendogames.net
  skip-cert-verify: true
- name: Pool__560 |133.10Mb
  server: 70.34.218.149
  type: trojan
  port: 11930
  password: BaeSzHdfJIR13l67
  sni: softpillow.silentrocket.click
- name: _534 |10.20Mb
  server: 160.16.63.16
  type: trojan
  port: 2760
  password: 44e660b0ee21cf3ac66aee2c08af85d2
  sni: www.nintendogames.net
  skip-cert-verify: true
- name: _508 |10.30Mb
  server: 160.16.236.32
  type: trojan
  port: 2760
  password: 44e660b0ee21cf3ac66aee2c08af85d2
  sni: www.nintendogames.net
  skip-cert-verify: true
- name: Relay_-ğŸ‡±ğŸ‡ºLU_486 |52.26Mb
  server: mfyousheng.nl.eu.org
  type: trojan
  port: 443
  udp: true
  password: Puj01Rc8UcA9IzcFcYOs8KMOhCz6aX2Q
  sni: mfyousheng.nl.eu.org
  skip-cert-verify: true
  ws-opts:
    path: /tjwsLhx0SFASG4l9FERJ1g
    headers:
      Host: mfyousheng.nl.eu.org
  network: ws
- name: Relay_-ğŸ‡ºğŸ‡¸US_459 |16.35Mb
  server: v4.hdacd.com
  type: vmess
  port: 30804
  udp: true
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡§ğŸ‡·BR_606 |24.12Mb
  server: 185.192.124.188
  type: ss
  country: ğŸ‡§ğŸ‡·BR
  port: 990
  password: f8f7aCzcPKbsF8p3
  cipher: chacha20-ietf-poly1305
- name: _589 |10.57Mb
  server: 160.16.57.238
  type: trojan
  port: 2760
  password: 44e660b0ee21cf3ac66aee2c08af85d2
  sni: www.nintendogames.net
  skip-cert-verify: true
- name: _591 |10.84Mb
  server: 160.16.116.227
  type: trojan
  port: 2760
  password: 44e660b0ee21cf3ac66aee2c08af85d2
  sni: www.nintendogames.net
  skip-cert-verify: true
- name: Relay_-ğŸ‡¯ğŸ‡µJP_601 |14.95Mb
  server: 160.16.107.37
  type: trojan
  port: 3093
  password: 44e660b0ee21cf3ac66aee2c08af85d2
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¯ğŸ‡µJP_605 |18.07Mb
  server: 160.16.107.37
  type: trojan
  port: 3169
  password: 44e660b0ee21cf3ac66aee2c08af85d2
  sni: www.nintendogames.net
- name: disney_HK |28.31Mb
  server: 219.79.214.159
  type: trojan
  port: 443
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: ğŸ‡¬ğŸ‡§GB_613 |126.99Mb
  server: 141.98.101.182
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: shadowsocks
  cipher: aes-128-gcm
- name: disney_CH |812.37Mb
  server: de1.opensocks.site
  type: ss
  country: ğŸ‡¨ğŸ‡­CH
  port: 8388
  password: NWYxM
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹ LT_652 |39.20Mb
  server: 45.87.175.178
  type: ss
  country: ğŸ‡±ğŸ‡¹ LT
  port: 8080
  password: 1RWwXhwfAB5gAEozU4G2Pg
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹ LT_653 |15.33Mb
  server: 45.87.175.178
  type: ss
  country: ğŸ‡±ğŸ‡¹ LT
  port: 8080
  password: 4a2rfixophdjffa8KVA4Aa
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹ LT_654 |38.93Mb
  server: 45.87.175.178
  type: ss
  country: ğŸ‡±ğŸ‡¹ LT
  port: 8080
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_655 |21.85Mb
  server: 45.87.175.175
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: QCXDxuDlTTMD7jtgHUjIoj
  cipher: chacha20-ietf-poly1305
- name: Relay_-ğŸ‡ºğŸ‡¸US_468 |10.64Mb
  server: v29.hdacd.com
  type: vmess
  port: 30829
  udp: true
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡±ğŸ‡¹LT_657 |47.22Mb
  server: 45.87.175.180
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: QCXDxuDlTTMD7jtgHUjIoj
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡²ğŸ‡½MX_661 |38.84Mb
  server: 216.238.86.158
  type: vmess
  country: ğŸ‡²ğŸ‡½MX
  port: 34460
  uuid: 90be214d-048c-4ea2-a602-b8e4d4e51e36
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡²ğŸ‡½MX_662 |39.68Mb
  server: 216.238.87.47
  type: vmess
  country: ğŸ‡²ğŸ‡½MX
  port: 27502
  uuid: b8155ce4-7e08-4c40-800f-8671312b7124
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_HK |19.94Mb
  server: 45.207.157.29
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 13852
  uuid: 845764df-ecb3-4b13-bed2-bf1551b68e9a
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡±ğŸ‡¹LT_658 |33.87Mb
  server: 45.87.175.200
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡³ğŸ‡±NL_663 |12.53Mb
  server: 193.29.139.141
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 8080
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡³ğŸ‡±NL_664 |75.77Mb
  server: 178.23.190.238
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 443
  password: uo7EbtqIwgZXXHmMv5LbLcOxptyPlNkh
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡µğŸ‡¹PT_669 |65.41Mb
  server: 185.113.143.186
  type: ss
  country: ğŸ‡µğŸ‡¹PT
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸ‡¯ğŸ‡µJP-ğŸ‡¯ğŸ‡µJP_650 |11.26Mb
  server: xray.kk37005.tk
  type: vmess
  country: ğŸ‡¯ğŸ‡µJP
  port: 55919
  uuid: 2e7548bb-7c5b-4d97-d64d-1b2fe4050089
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: ğŸ‡¸ğŸ‡¬SG_671 |16.73Mb
  server: 68.183.227.45
  type: ss
  country: ğŸ‡¸ğŸ‡¬SG
  port: 8080
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: _388 |79.48Mb
  server: 38.54.57.90
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ğŸ‡¹ğŸ‡¼TW_673 |27.19Mb
  server: 38.54.107.101
  type: ss
  country: ğŸ‡¹ğŸ‡¼TW
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸ‡­ğŸ‡°HK-ğŸ‡­ğŸ‡°HK_640 |14.36Mb
  server: n1761214918.74qxv.top
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 443
  uuid: b141803a-209c-47bd-be6e-14d6bc1e96be
  alterId: 0
  cipher: auto
  network: ws
  servername: n1761214918.74qxv.top
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /
    headers:
      HOST: n1761214918.74qxv.top
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - _362 |81.70Mb
  - _363 |43.70Mb
  - _364 |25.96Mb
  - _374 |305.54Mb
  - _361 |15.73Mb
  - _372 |150.13Mb
  - _367 |326.66Mb
  - _359 |28.66Mb
  - _357 |105.62Mb
  - _386 |53.88Mb
  - _376 |32.37Mb
  - _380 |226.41Mb
  - _390 |45.74Mb
  - _360 |12.89Mb
  - _382 |859.38Mb
  - _399 |16.50Mb
  - _396 |46.08Mb
  - _403 |53.03Mb
  - _383 |12.44Mb
  - _404 |62.56Mb
  - _392 |128.29Mb
  - _384 |45.05Mb
  - _393 |11.31Mb
  - _395 |51.04Mb
  - disney_US |70.68Mb
  - _407 |21.92Mb
  - _405 |68.98Mb
  - _413 |742.99Mb
  - _401 |21.65Mb
  - _389 |12.27Mb
  - _406 |22.69Mb
  - _412 |30.98Mb
  - Relay_-ğŸ‡¨ğŸ‡¦CA_425 |70.10Mb
  - _423 |15.09Mb
  - _419 |24.95Mb
  - _421 |10.35Mb
  - disney_MX |28.40Mb
  - _410 |43.39Mb
  - _433 |54.73Mb
  - disney_US |40.40Mb
  - _416 |15.57Mb
  - disney_DO |57.17Mb
  - _418 |16.17Mb
  - disney_US |41.34Mb
  - _466 |30.58Mb
  - _426 |28.70Mb
  - disney_SG |25.05Mb
  - _429 |30.78Mb
  - _450 |10.10Mb
  - disney_US |11.06Mb
  - _462 |10.29Mb
  - Pool__554 |24.55Mb
  - _463 |40.34Mb
  - _502 |10.68Mb
  - Pool__560 |133.10Mb
  - _534 |10.20Mb
  - _508 |10.30Mb
  - Relay_-ğŸ‡±ğŸ‡ºLU_486 |52.26Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_459 |16.35Mb
  - ğŸ‡§ğŸ‡·BR_606 |24.12Mb
  - _589 |10.57Mb
  - _591 |10.84Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_601 |14.95Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_605 |18.07Mb
  - disney_HK |28.31Mb
  - ğŸ‡¬ğŸ‡§GB_613 |126.99Mb
  - disney_CH |812.37Mb
  - ğŸ‡±ğŸ‡¹ LT_652 |39.20Mb
  - ğŸ‡±ğŸ‡¹ LT_653 |15.33Mb
  - ğŸ‡±ğŸ‡¹ LT_654 |38.93Mb
  - ğŸ‡±ğŸ‡¹LT_655 |21.85Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_468 |10.64Mb
  - ğŸ‡±ğŸ‡¹LT_657 |47.22Mb
  - ğŸ‡²ğŸ‡½MX_661 |38.84Mb
  - ğŸ‡²ğŸ‡½MX_662 |39.68Mb
  - disney_HK |19.94Mb
  - ğŸ‡±ğŸ‡¹LT_658 |33.87Mb
  - ğŸ‡³ğŸ‡±NL_663 |12.53Mb
  - ğŸ‡³ğŸ‡±NL_664 |75.77Mb
  - ğŸ‡µğŸ‡¹PT_669 |65.41Mb
  - Relay_ğŸ‡¯ğŸ‡µJP-ğŸ‡¯ğŸ‡µJP_650 |11.26Mb
  - ğŸ‡¸ğŸ‡¬SG_671 |16.73Mb
  - _388 |79.48Mb
  - ğŸ‡¹ğŸ‡¼TW_673 |27.19Mb
  - Relay_ğŸ‡­ğŸ‡°HK-ğŸ‡­ğŸ‡°HK_640 |14.36Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - _362 |81.70Mb
  - _363 |43.70Mb
  - _364 |25.96Mb
  - _374 |305.54Mb
  - _361 |15.73Mb
  - _372 |150.13Mb
  - _367 |326.66Mb
  - _359 |28.66Mb
  - _357 |105.62Mb
  - _386 |53.88Mb
  - _376 |32.37Mb
  - _380 |226.41Mb
  - _390 |45.74Mb
  - _360 |12.89Mb
  - _382 |859.38Mb
  - _399 |16.50Mb
  - _396 |46.08Mb
  - _403 |53.03Mb
  - _383 |12.44Mb
  - _404 |62.56Mb
  - _392 |128.29Mb
  - _384 |45.05Mb
  - _393 |11.31Mb
  - _395 |51.04Mb
  - disney_US |70.68Mb
  - _407 |21.92Mb
  - _405 |68.98Mb
  - _413 |742.99Mb
  - _401 |21.65Mb
  - _389 |12.27Mb
  - _406 |22.69Mb
  - _412 |30.98Mb
  - Relay_-ğŸ‡¨ğŸ‡¦CA_425 |70.10Mb
  - _423 |15.09Mb
  - _419 |24.95Mb
  - _421 |10.35Mb
  - disney_MX |28.40Mb
  - _410 |43.39Mb
  - _433 |54.73Mb
  - disney_US |40.40Mb
  - _416 |15.57Mb
  - disney_DO |57.17Mb
  - _418 |16.17Mb
  - disney_US |41.34Mb
  - _466 |30.58Mb
  - _426 |28.70Mb
  - disney_SG |25.05Mb
  - _429 |30.78Mb
  - _450 |10.10Mb
  - disney_US |11.06Mb
  - _462 |10.29Mb
  - Pool__554 |24.55Mb
  - _463 |40.34Mb
  - _502 |10.68Mb
  - Pool__560 |133.10Mb
  - _534 |10.20Mb
  - _508 |10.30Mb
  - Relay_-ğŸ‡±ğŸ‡ºLU_486 |52.26Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_459 |16.35Mb
  - ğŸ‡§ğŸ‡·BR_606 |24.12Mb
  - _589 |10.57Mb
  - _591 |10.84Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_601 |14.95Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_605 |18.07Mb
  - disney_HK |28.31Mb
  - ğŸ‡¬ğŸ‡§GB_613 |126.99Mb
  - disney_CH |812.37Mb
  - ğŸ‡±ğŸ‡¹ LT_652 |39.20Mb
  - ğŸ‡±ğŸ‡¹ LT_653 |15.33Mb
  - ğŸ‡±ğŸ‡¹ LT_654 |38.93Mb
  - ğŸ‡±ğŸ‡¹LT_655 |21.85Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_468 |10.64Mb
  - ğŸ‡±ğŸ‡¹LT_657 |47.22Mb
  - ğŸ‡²ğŸ‡½MX_661 |38.84Mb
  - ğŸ‡²ğŸ‡½MX_662 |39.68Mb
  - disney_HK |19.94Mb
  - ğŸ‡±ğŸ‡¹LT_658 |33.87Mb
  - ğŸ‡³ğŸ‡±NL_663 |12.53Mb
  - ğŸ‡³ğŸ‡±NL_664 |75.77Mb
  - ğŸ‡µğŸ‡¹PT_669 |65.41Mb
  - Relay_ğŸ‡¯ğŸ‡µJP-ğŸ‡¯ğŸ‡µJP_650 |11.26Mb
  - ğŸ‡¸ğŸ‡¬SG_671 |16.73Mb
  - _388 |79.48Mb
  - ğŸ‡¹ğŸ‡¼TW_673 |27.19Mb
  - Relay_ğŸ‡­ğŸ‡°HK-ğŸ‡­ğŸ‡°HK_640 |14.36Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
