port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: Relay_-ğŸ‡ºğŸ‡¸US_511 |40.79Mb
  server: 38.14.99.179
  type: vmess
  port: 59807
  udp: true
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: netflix_NL |473.22Mb
  server: 151.242.251.137
  type: ss
  port: 8080
  password: o5osZg269v5zHpYjr1xY9s
  cipher: chacha20-ietf-poly1305
- name: Relay_-ğŸ‡³ğŸ‡±NL_647 |20.58Mb
  server: 160.16.132.158
  type: trojan
  port: 4054
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¸ğŸ‡¬SG_649 |12.45Mb
  server: 160.16.131.243
  type: trojan
  port: 127
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡³ğŸ‡±NL_654 |11.47Mb
  server: 160.16.116.227
  type: trojan
  port: 2890
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: _481 |36.08Mb
  server: 188.253.124.53
  type: ss
  port: 63257
  udp: true
  password: RenzheCloudSS
  cipher: rc4-md5
  plugin: obfs
  plugin-opts:
    host: d1bf8290613.microsoft.com
    mode: http
- name: Relay_-ğŸ‡¯ğŸ‡µJP_655 |14.46Mb
  server: 160.16.87.174
  type: trojan
  port: 3169
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¯ğŸ‡µJP_656 |20.30Mb
  server: 153.121.45.139
  type: trojan
  port: 1331
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¯ğŸ‡µJP_657 |20.59Mb
  server: 153.121.38.213
  type: trojan
  port: 1331
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡³ğŸ‡±NL_660 |11.91Mb
  server: 160.16.81.84
  type: trojan
  port: 4054
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: _658 |14.92Mb
  server: 68.183.231.236
  type: trojan
  port: 443
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡³ğŸ‡±NL_662 |41.44Mb
  server: 160.16.131.243
  type: trojan
  port: 2890
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: _659 |12.56Mb
  server: 58.152.25.20
  type: trojan
  port: 443
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: Relay_-ğŸ‡¯ğŸ‡µJP_665 |19.05Mb
  server: 153.121.65.107
  type: trojan
  port: 1331
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡ºğŸ‡¸US_587 |12.55Mb
  server: v29.hdacd.com
  type: vmess
  port: 30829
  udp: true
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_-ğŸ‡ºğŸ‡¸US_530 |57.37Mb
  server: v8.hdacd.com
  type: vmess
  port: 30808
  udp: true
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_-ğŸ‡¸ğŸ‡¬SG_669 |11.59Mb
  server: 160.16.107.37
  type: trojan
  port: 507
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¯ğŸ‡µJP_670 |23.02Mb
  server: 160.16.70.180
  type: trojan
  port: 1331
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: disney_FR |56.97Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 27092
  uuid: a0596ba6-72a3-4366-8992-77088da65bd8
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡§ğŸ‡·BR_674 |21.85Mb
  server: 38.180.16.86
  type: vmess
  country: ğŸ‡§ğŸ‡·BR
  port: 36104
  uuid: E146A8CB-9D2F-449C-ADCA-8736FB
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_FR |60.38Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 40433
  uuid: d8fd8955-78db-49ba-d86f-3e4729f6ac4d
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: _668 |10.81Mb
  server: 58.152.53.8
  type: trojan
  port: 443
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: ğŸ‡¬ğŸ‡§GB_680 |130.15Mb
  server: 82.38.31.179
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸ‡¬ğŸ‡§GB-ğŸ‡³ğŸ‡±NL_682 |502.56Mb
  server: 82.38.31.210
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸ‡¬ğŸ‡§GB-ğŸ‡³ğŸ‡±NL_681 |501.29Mb
  server: 82.38.31.218
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡²ğŸ‡½MX_732 |37.40Mb
  server: 216.238.89.53
  type: vmess
  country: ğŸ‡²ğŸ‡½MX
  port: 57283
  uuid: 1a5aafc0-6482-451d-fe76-6875b7818579
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡­ğŸ‡°HK_687 |40.89Mb
  server: 87.121.162.249
  type: ss
  country: ğŸ‡­ğŸ‡°HK
  port: 443
  password: JGv616hMWdjfuZ00jYfq7XkBHJZrOBrg
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡­ğŸ‡°HK_704 |29.15Mb
  server: 47.243.51.237
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 52801
  uuid: ef93f413-9039-4ddb-aefb-2490287df55a
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
  ws-opts:
    path: /arki?ed=2048
- name: ğŸ‡­ğŸ‡°HK_726 |71.50Mb
  server: 219.79.186.107
  type: trojan
  country: ğŸ‡­ğŸ‡°HK
  port: 443
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: Relay_ğŸ‡¯ğŸ‡µJP-ğŸ‡¯ğŸ‡µJP_729 |20.01Mb
  server: kuame.missionsec.us
  type: trojan
  country: ğŸ‡¯ğŸ‡µJP
  port: 443
  udp: true
  password: FDIypSwe64a3DA7un2R8DFjYXZO3NS05gKZTTOC8SxO0Fy3cqYg3EaFDA3ABaEYKNx39D
  sni: kuame.missionsec.us
  skip-cert-verify: true
- name: ğŸ‡°ğŸ‡·KR_731 |10.84Mb
  server: 146.56.112.110
  type: vmess
  country: ğŸ‡°ğŸ‡·KR
  port: 8888
  uuid: e7c302f3-90d6-42dd-9d7d-94a3683a3707
  alterId: 0
  cipher: auto
  network: tcp
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_NL |57.69Mb
  server: 109.71.246.210
  type: ss
  country: ğŸ‡·ğŸ‡ºRU
  port: 56689
  password: YQCSKoCF3QazW8YlvDBWA4
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_740 |42.68Mb
  server: 104.192.226.106
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: Relay_ğŸ‡°ğŸ‡·KR-ğŸ‡°ğŸ‡·KR_730 |11.55Mb
  server: seoul03.zgjok.com
  type: vmess
  country: ğŸ‡°ğŸ‡·KR
  port: 443
  uuid: 72a0dac4-9689-4a57-b164-5c65bfa94772
  alterId: 0
  cipher: auto
  network: ws
  servername: seoul03.zgjok.com
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /
    headers:
      HOST: seoul03.zgjok.com
- name: ğŸ‡²ğŸ‡¾MY_733 |29.17Mb
  server: 38.54.98.110
  type: vmess
  country: ğŸ‡²ğŸ‡¾MY
  port: 2052
  uuid: 665d9b8f-153d-4907-adac-de12afd9c851
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: disney_RU |491.62Mb
  server: 38.60.223.8
  type: ss
  country: ğŸ‡·ğŸ‡ºRU
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_748 |40.70Mb
  server: 38.14.99.163
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 59807
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: auto
  network: tcp
  servername: 38.14.99.163
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡¸ğŸ‡¬SG_737 |10.72Mb
  server: 68.183.178.131
  type: vmess
  country: ğŸ‡¸ğŸ‡¬SG
  port: 58607
  uuid: c11c32cb-27b3-4afa-c0f3-fb250aa4959e
  alterId: 0
  cipher: auto
  network: ws
  servername: www.12333.monster
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /
    headers:
      HOST: www.12333.monster
- name: ğŸ‡ºğŸ‡¸US_741 |179.67Mb
  server: 45.12.144.18
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: LQyAUItafUmmO3EZZx9UbiX6IGydSBgL
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_742 |135.31Mb
  server: 45.12.136.170
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: l668XHPejoSNNuD66BYzyehaCpZexiF7
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_749 |25.97Mb
  server: 45.136.12.37
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 38141
  uuid: fd291be6-b48d-43a1-da38-66c7f80e2f80
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_750 |26.42Mb
  server: cf.fovi.tk
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  uuid: bf67437e-6c90-45ca-abc2-c7240a5ce2aa
  alterId: 0
  cipher: auto
  network: ws
  servername: foxlux.fovi.tk
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /eisasqa
    headers:
      HOST: foxlux.fovi.tk
- name: disney_DE |447.99Mb
  server: clr.ducks.tel
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 17844
  password: '907560230'
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡·ğŸ‡ºRU_739 |12.49Mb
  server: clr.ducks.tel
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 17847
  password: '907560230'
  cipher: chacha20-ietf-poly1305
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - Relay_-ğŸ‡ºğŸ‡¸US_511 |40.79Mb
  - netflix_NL |473.22Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_647 |20.58Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_649 |12.45Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_654 |11.47Mb
  - _481 |36.08Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_655 |14.46Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_656 |20.30Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_657 |20.59Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_660 |11.91Mb
  - _658 |14.92Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_662 |41.44Mb
  - _659 |12.56Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_665 |19.05Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_587 |12.55Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_530 |57.37Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_669 |11.59Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_670 |23.02Mb
  - disney_FR |56.97Mb
  - ğŸ‡§ğŸ‡·BR_674 |21.85Mb
  - disney_FR |60.38Mb
  - _668 |10.81Mb
  - ğŸ‡¬ğŸ‡§GB_680 |130.15Mb
  - Relay_ğŸ‡¬ğŸ‡§GB-ğŸ‡³ğŸ‡±NL_682 |502.56Mb
  - Relay_ğŸ‡¬ğŸ‡§GB-ğŸ‡³ğŸ‡±NL_681 |501.29Mb
  - ğŸ‡²ğŸ‡½MX_732 |37.40Mb
  - ğŸ‡­ğŸ‡°HK_687 |40.89Mb
  - ğŸ‡­ğŸ‡°HK_704 |29.15Mb
  - ğŸ‡­ğŸ‡°HK_726 |71.50Mb
  - Relay_ğŸ‡¯ğŸ‡µJP-ğŸ‡¯ğŸ‡µJP_729 |20.01Mb
  - ğŸ‡°ğŸ‡·KR_731 |10.84Mb
  - disney_NL |57.69Mb
  - ğŸ‡ºğŸ‡¸US_740 |42.68Mb
  - Relay_ğŸ‡°ğŸ‡·KR-ğŸ‡°ğŸ‡·KR_730 |11.55Mb
  - ğŸ‡²ğŸ‡¾MY_733 |29.17Mb
  - disney_RU |491.62Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_748 |40.70Mb
  - ğŸ‡¸ğŸ‡¬SG_737 |10.72Mb
  - ğŸ‡ºğŸ‡¸US_741 |179.67Mb
  - ğŸ‡ºğŸ‡¸US_742 |135.31Mb
  - ğŸ‡ºğŸ‡¸US_749 |25.97Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_750 |26.42Mb
  - disney_DE |447.99Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡·ğŸ‡ºRU_739 |12.49Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - Relay_-ğŸ‡ºğŸ‡¸US_511 |40.79Mb
  - netflix_NL |473.22Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_647 |20.58Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_649 |12.45Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_654 |11.47Mb
  - _481 |36.08Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_655 |14.46Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_656 |20.30Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_657 |20.59Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_660 |11.91Mb
  - _658 |14.92Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_662 |41.44Mb
  - _659 |12.56Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_665 |19.05Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_587 |12.55Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_530 |57.37Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_669 |11.59Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_670 |23.02Mb
  - disney_FR |56.97Mb
  - ğŸ‡§ğŸ‡·BR_674 |21.85Mb
  - disney_FR |60.38Mb
  - _668 |10.81Mb
  - ğŸ‡¬ğŸ‡§GB_680 |130.15Mb
  - Relay_ğŸ‡¬ğŸ‡§GB-ğŸ‡³ğŸ‡±NL_682 |502.56Mb
  - Relay_ğŸ‡¬ğŸ‡§GB-ğŸ‡³ğŸ‡±NL_681 |501.29Mb
  - ğŸ‡²ğŸ‡½MX_732 |37.40Mb
  - ğŸ‡­ğŸ‡°HK_687 |40.89Mb
  - ğŸ‡­ğŸ‡°HK_704 |29.15Mb
  - ğŸ‡­ğŸ‡°HK_726 |71.50Mb
  - Relay_ğŸ‡¯ğŸ‡µJP-ğŸ‡¯ğŸ‡µJP_729 |20.01Mb
  - ğŸ‡°ğŸ‡·KR_731 |10.84Mb
  - disney_NL |57.69Mb
  - ğŸ‡ºğŸ‡¸US_740 |42.68Mb
  - Relay_ğŸ‡°ğŸ‡·KR-ğŸ‡°ğŸ‡·KR_730 |11.55Mb
  - ğŸ‡²ğŸ‡¾MY_733 |29.17Mb
  - disney_RU |491.62Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_748 |40.70Mb
  - ğŸ‡¸ğŸ‡¬SG_737 |10.72Mb
  - ğŸ‡ºğŸ‡¸US_741 |179.67Mb
  - ğŸ‡ºğŸ‡¸US_742 |135.31Mb
  - ğŸ‡ºğŸ‡¸US_749 |25.97Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_750 |26.42Mb
  - disney_DE |447.99Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡·ğŸ‡ºRU_739 |12.49Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
