port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: _249 |42.26Mb
  server: 163.192.49.195
  type: vmess
  port: 443
  uuid: bcb7c581-3c95-4569-a4e7-918141e91ea3
  alterId: 0
  cipher: auto
  network: http
  http-opts:
    path:
    - /
    headers:
      Host:
      - a.189.cn
  h2-opts: {}
- name: disney_US |44.54Mb
  server: 165.140.216.141
  type: vmess
  port: 443
  uuid: e7d72a8d-26f2-4b54-b366-0c43e0bcba7d
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: disney_US |140.61Mb
  server: 192.204.47.79
  type: vmess
  port: 42277
  udp: true
  uuid: aee61b21-e85a-484b-f203-b245f1451cff
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _232 |40.40Mb
  server: 216.238.86.158
  type: vmess
  port: 34460
  udp: true
  uuid: 90be214d-048c-4ea2-a602-b8e4d4e51e36
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _267 |26.86Mb
  server: 51.79.102.253
  type: vmess
  port: 80
  uuid: 58fe1542-5290-40ad-815a-77707a81afe5
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /IOebhLMhl1CTbFHbL95myfRX2
    headers:
      Host: wrmelmwxlf.gktevlrqznwqqozy.fabpfs66gizmnojhcvqxwl.kytrcfzqla87gvgvs6c7kjnrubuh.cc
- name: _279 |109.17Mb
  server: 38.96.254.102
  type: trojan
  port: 18509
  password: .ie4rghJuMkcf0oF
  sni: shoppingmall.electricbanana.click
- name: _272 |11.77Mb
  server: 160.16.117.182
  type: trojan
  port: 3093
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: netflix_DE |690.17Mb
  server: 85.195.101.122
  type: vmess
  port: 40878
  uuid: f3d4167e-b15e-4e46-82e9-9286ef93fda7
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: disney_HK |17.84Mb
  server: 154.21.201.83
  type: vmess
  port: 443
  uuid: 4bf075f5-4d5e-4d39-f5ab-b32a86250f0e
  alterId: 0
  cipher: auto
  network: ws
  servername: hk.nbee.pp.ua
  http-opts: {}
  h2-opts: {}
  tls: true
  ws-opts:
    path: /aa
    headers:
      Host: hk.nbee.pp.ua
- name: _255 |13.20Mb
  server: 47.242.140.52
  type: vmess
  port: 34815
  uuid: 1a46b66c-6ba9-4e9c-aa0b-0ebac2b69e32
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /arki
- name: _252 |16.52Mb
  server: 47.243.51.237
  type: vmess
  port: 52801
  uuid: ef93f413-9039-4ddb-aefb-2490287df55a
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /arki
- name: _265 |18.75Mb
  server: 8.218.105.196
  type: vmess
  port: 52752
  uuid: 925bdbf5-72be-4437-bebf-441c61089f6b
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _219 |21.84Mb
  server: 154.201.76.172
  type: vmess
  port: 20990
  uuid: ba50e1fe-055f-4587-fd0d-36c8d6615192
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: ğŸ‡²ğŸ‡½MX_292 |39.27Mb
  server: 216.238.87.47
  type: vmess
  country: ğŸ‡²ğŸ‡½MX
  port: 27502
  uuid: b8155ce4-7e08-4c40-800f-8671312b7124
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Pool__274 |36.00Mb
  server: 70.34.218.149
  type: trojan
  port: 11930
  password: BaeSzHdfJIR13l67
  sni: softpillow.silentrocket.click
- name: disney_FR |149.23Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 27092
  uuid: a0596ba6-72a3-4366-8992-77088da65bd8
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_FR |159.98Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 40433
  uuid: d8fd8955-78db-49ba-d86f-3e4729f6ac4d
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: _264 |43.09Mb
  server: 89.31.120.192
  type: vmess
  port: 443
  uuid: 44537595-9ccc-4b83-8936-5f9ad3229019
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: ğŸ‡¬ğŸ‡§GB_284 |233.34Mb
  server: 82.38.31.194
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_283 |91.86Mb
  server: 82.38.31.191
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: disney_HK |20.06Mb
  server: 45.207.157.29
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 13852
  uuid: 845764df-ecb3-4b13-bed2-bf1551b68e9a
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡·ğŸ‡ºRU_293 |14.70Mb
  server: 45.129.2.185
  type: ss
  country: ğŸ‡·ğŸ‡ºRU
  port: 10081
  password: c5fcdf7829112cb4
  cipher: aes-256-gcm
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - _249 |42.26Mb
  - disney_US |44.54Mb
  - disney_US |140.61Mb
  - _232 |40.40Mb
  - _267 |26.86Mb
  - _279 |109.17Mb
  - _272 |11.77Mb
  - netflix_DE |690.17Mb
  - disney_HK |17.84Mb
  - _255 |13.20Mb
  - _252 |16.52Mb
  - _265 |18.75Mb
  - _219 |21.84Mb
  - ğŸ‡²ğŸ‡½MX_292 |39.27Mb
  - Pool__274 |36.00Mb
  - disney_FR |149.23Mb
  - disney_FR |159.98Mb
  - _264 |43.09Mb
  - ğŸ‡¬ğŸ‡§GB_284 |233.34Mb
  - ğŸ‡¬ğŸ‡§GB_283 |91.86Mb
  - disney_HK |20.06Mb
  - ğŸ‡·ğŸ‡ºRU_293 |14.70Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - _249 |42.26Mb
  - disney_US |44.54Mb
  - disney_US |140.61Mb
  - _232 |40.40Mb
  - _267 |26.86Mb
  - _279 |109.17Mb
  - _272 |11.77Mb
  - netflix_DE |690.17Mb
  - disney_HK |17.84Mb
  - _255 |13.20Mb
  - _252 |16.52Mb
  - _265 |18.75Mb
  - _219 |21.84Mb
  - ğŸ‡²ğŸ‡½MX_292 |39.27Mb
  - Pool__274 |36.00Mb
  - disney_FR |149.23Mb
  - disney_FR |159.98Mb
  - _264 |43.09Mb
  - ğŸ‡¬ğŸ‡§GB_284 |233.34Mb
  - ğŸ‡¬ğŸ‡§GB_283 |91.86Mb
  - disney_HK |20.06Mb
  - ğŸ‡·ğŸ‡ºRU_293 |14.70Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
