port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: _196 |64.96Mb
  server: 54.144.64.227
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: disney_netflix_US |65.06Mb
  server: 54.159.62.233
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: _194 |64.90Mb
  server: 23.22.182.151
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: disney_netflix_US |61.53Mb
  server: 13.218.107.141
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: disney_netflix_US |62.97Mb
  server: 184.72.124.41
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: _203 |65.56Mb
  server: 3.93.196.82
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: disney_netflix_US |59.73Mb
  server: 13.222.155.147
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: disney_netflix_US |63.66Mb
  server: 98.89.32.62
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: disney_netflix_US |68.90Mb
  server: 98.81.59.20
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: disney_netflix_US |63.57Mb
  server: 54.91.94.165
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: netflix_IE |191.95Mb
  server: 34.251.86.159
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: netflix_IE |330.24Mb
  server: 3.250.105.240
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: disney_netflix_US |65.31Mb
  server: 50.19.46.248
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: disney_netflix_US |61.91Mb
  server: 3.89.113.22
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: disney_netflix_US |42.61Mb
  server: 163.192.49.195
  type: vmess
  port: 443
  uuid: bcb7c581-3c95-4569-a4e7-918141e91ea3
  alterId: 0
  cipher: auto
  network: http
  http-opts:
    path:
    - /
    headers:
      Host:
      - a.189.cn
  h2-opts: {}
- name: _188 |180.03Mb
  server: 13.61.13.231
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: netflix_SE |159.50Mb
  server: 13.61.180.46
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: disney_netflix_US |44.80Mb
  server: 165.140.216.141
  type: vmess
  port: 443
  uuid: e7d72a8d-26f2-4b54-b366-0c43e0bcba7d
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _224 |18.58Mb
  server: 15.235.41.200
  type: vmess
  port: 80
  uuid: 58fe1542-5290-40ad-815a-77707a81afe5
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /IOebhLMhl1CTbFHbL95myfRX2
- name: disney_MD |11.42Mb
  server: 185.153.197.5
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: netflix_IE |173.03Mb
  server: 54.246.35.116
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: disney_netflix_US |176.41Mb
  server: 192.204.47.79
  type: vmess
  port: 42277
  udp: true
  uuid: aee61b21-e85a-484b-f203-b245f1451cff
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _213 |168.37Mb
  server: 51.20.125.235
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: _219 |23.37Mb
  server: 8.210.184.105
  type: vmess
  port: 40374
  udp: true
  uuid: 36b76373-7a4f-4669-9113-7d247bcf2704
  alterId: 0
  cipher: auto
  network: http
  http-opts:
    method: GET
    path:
    - /
  h2-opts: {}
- name: _228 |21.06Mb
  server: 51.79.102.253
  type: vmess
  port: 80
  uuid: 58fe1542-5290-40ad-815a-77707a81afe5
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /IOebhLMhl1CTbFHbL95myfRX2
    headers:
      Host: wrmelmwxlf.gktevlrqznwqqozy.fabpfs66gizmnojhcvqxwl.kytrcfzqla87gvgvs6c7kjnrubuh.cc
- name: disney_HK |10.75Mb
  server: 104.19.61.72
  type: vmess
  port: 443
  uuid: 4bf075f5-4d5e-4d39-f5ab-b32a86250f0e
  alterId: 0
  cipher: auto
  network: ws
  servername: hk.nbee.pp.ua
  http-opts: {}
  h2-opts: {}
  tls: true
  ws-opts:
    path: /aa
    headers:
      Host: hk.nbee.pp.ua
- name: disney_SG |10.04Mb
  server: 165.154.195.38
  type: vmess
  port: 35034
  uuid: 959a8caf-4cea-43d0-a548-3628e7ddfafc
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _227 |23.66Mb
  server: 8.218.105.196
  type: vmess
  port: 52752
  uuid: 925bdbf5-72be-4437-bebf-441c61089f6b
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _232 |63.19Mb
  server: 38.180.16.86
  type: vmess
  port: 36236
  uuid: a58bc1a5-8c18-49ff-9453-c331b52f45dc
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _220 |21.54Mb
  server: 160.119.196.92
  type: vmess
  port: 36334
  uuid: 575ac7a3-0127-4420-a9ea-5ff3f6c02ac7
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
- name: disney_netflix_DE |18.74Mb
  server: 43.165.7.71
  type: vmess
  port: 19751
  uuid: 6cfa6103-5d06-40cb-f452-b563db578288
  alterId: 0
  cipher: auto
  network: http
  http-opts:
    method: GET
    path:
    - /
  h2-opts: {}
- name: _225 |40.89Mb
  server: 89.31.120.192
  type: vmess
  port: 443
  uuid: 44537595-9ccc-4b83-8936-5f9ad3229019
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: disney_TW |18.59Mb
  server: 103.127.218.91
  type: vmess
  port: 54693
  uuid: 1cef03ad-6343-408c-8121-cbd1fda2ee9d
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /1cef03ad
- name: disney_netflix_GB |232.39Mb
  server: 172.67.134.185
  type: trojan
  port: 443
  udp: true
  password: POORIARED
  sni: reDfRee8.REDFree8.ir
  ws-opts:
    path: /eyJqdW5rIjoiVUl6eXhLZkkwUTJ3ZzkiLCJwcm90b2NvbCI6InRyIiwibW9kZSI6InByb3h5aXAiLCJwYW5lbElQcyI6W119?ed=2560
    headers:
      Host: reDfRee8.REDFree8.ir
  network: ws
- name: _272 |24.42Mb
  server: 38.96.254.102
  type: trojan
  port: 18509
  password: .ie4rghJuMkcf0oF
  sni: shoppingmall.electricbanana.click
- name: _248 |11.28Mb
  server: 146.56.112.110
  type: vmess
  port: 8888
  uuid: e7c302f3-90d6-42dd-9d7d-94a3683a3707
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _250 |109.56Mb
  server: 38.180.16.86
  type: vmess
  port: 38039
  uuid: 244a3464-1269-43b3-b491-4dc2713eb3f6
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: Relay_-ğŸ‡¯ğŸ‡µJP_260 |14.36Mb
  server: 153.121.73.102
  type: trojan
  port: 1331
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: Pool__261 |133.02Mb
  server: 70.34.218.149
  type: trojan
  port: 11930
  password: BaeSzHdfJIR13l67
  sni: softpillow.silentrocket.click
- name: _263 |20.36Mb
  server: 153.121.65.107
  type: trojan
  port: 3093
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: _264 |10.67Mb
  server: 153.121.53.187
  type: trojan
  port: 3093
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¯ğŸ‡µJP_265 |11.88Mb
  server: 160.16.70.180
  type: trojan
  port: 1331
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: _270 |19.96Mb
  server: 160.16.117.182
  type: trojan
  port: 3093
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: disney_HK |11.13Mb
  server: 154.21.201.83
  type: vmess
  port: 443
  uuid: 4bf075f5-4d5e-4d39-f5ab-b32a86250f0e
  alterId: 0
  cipher: auto
  network: ws
  servername: hk.nbee.pp.ua
  http-opts: {}
  h2-opts: {}
  tls: true
  ws-opts:
    path: /aa
    headers:
      Host: hk.nbee.pp.ua
- name: Relay_-ğŸ‡¸ğŸ‡¬SG_274 |12.03Mb
  server: 160.16.153.13
  type: trojan
  port: 3145
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: ğŸ‡²ğŸ‡½MX_300 |40.10Mb
  server: 216.238.87.47
  type: vmess
  country: ğŸ‡²ğŸ‡½MX
  port: 27502
  uuid: b8155ce4-7e08-4c40-800f-8671312b7124
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡®ğŸ‡ªIE_298 |191.33Mb
  server: 52.50.200.2
  type: ss
  country: ğŸ‡®ğŸ‡ªIE
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡¬ğŸ‡§GB_287 |116.37Mb
  server: 82.38.31.194
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: netflix_NL |193.61Mb
  server: 82.38.31.191
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_289 |12.18Mb
  server: 82.38.31.217
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: disney_HK |21.78Mb
  server: 219.78.209.224
  type: trojan
  port: 443
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: disney_netflix_US |65.21Mb
  server: 18.207.122.59
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: disney_HK |15.95Mb
  server: 58.152.30.120
  type: trojan
  port: 443
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: disney_HK |25.09Mb
  server: 45.207.157.29
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 13852
  uuid: 845764df-ecb3-4b13-bed2-bf1551b68e9a
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡ºğŸ‡¸US_304 |17.84Mb
  server: 45.12.136.170
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: l668XHPejoSNNuD66BYzyehaCpZexiF7
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸZZ-ğŸ‡®ğŸ‡·IR_305 |21.88Mb
  server: cf.fovi.tk
  type: vmess
  country: ğŸZZ
  port: 443
  uuid: bf67437e-6c90-45ca-abc2-c7240a5ce2aa
  alterId: 0
  cipher: auto
  network: ws
  servername: foxpol.fovi.tk
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /eisasqa
    headers:
      HOST: foxpol.fovi.tk
- name: Relay_ğŸ‡©ğŸ‡ªDE-ğŸ‡©ğŸ‡ªDE_280 |204.67Mb
  server: cpanel.navar1.ir
  type: vmess
  country: ğŸ‡©ğŸ‡ªDE
  port: 100
  uuid: 95c6f6f0-84f7-4443-8a50-a59f8e66f5ee
  alterId: 0
  cipher: auto
  network: tcp
  servername: cpanel.navar1.ir
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - _196 |64.96Mb
  - disney_netflix_US |65.06Mb
  - _194 |64.90Mb
  - disney_netflix_US |61.53Mb
  - disney_netflix_US |62.97Mb
  - _203 |65.56Mb
  - disney_netflix_US |59.73Mb
  - disney_netflix_US |63.66Mb
  - disney_netflix_US |68.90Mb
  - disney_netflix_US |63.57Mb
  - netflix_IE |191.95Mb
  - netflix_IE |330.24Mb
  - disney_netflix_US |65.31Mb
  - disney_netflix_US |61.91Mb
  - disney_netflix_US |42.61Mb
  - _188 |180.03Mb
  - netflix_SE |159.50Mb
  - disney_netflix_US |44.80Mb
  - _224 |18.58Mb
  - disney_MD |11.42Mb
  - netflix_IE |173.03Mb
  - disney_netflix_US |176.41Mb
  - _213 |168.37Mb
  - _219 |23.37Mb
  - _228 |21.06Mb
  - disney_HK |10.75Mb
  - disney_SG |10.04Mb
  - _227 |23.66Mb
  - _232 |63.19Mb
  - _220 |21.54Mb
  - disney_netflix_DE |18.74Mb
  - _225 |40.89Mb
  - disney_TW |18.59Mb
  - disney_netflix_GB |232.39Mb
  - _272 |24.42Mb
  - _248 |11.28Mb
  - _250 |109.56Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_260 |14.36Mb
  - Pool__261 |133.02Mb
  - _263 |20.36Mb
  - _264 |10.67Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_265 |11.88Mb
  - _270 |19.96Mb
  - disney_HK |11.13Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_274 |12.03Mb
  - ğŸ‡²ğŸ‡½MX_300 |40.10Mb
  - ğŸ‡®ğŸ‡ªIE_298 |191.33Mb
  - ğŸ‡¬ğŸ‡§GB_287 |116.37Mb
  - netflix_NL |193.61Mb
  - ğŸ‡¬ğŸ‡§GB_289 |12.18Mb
  - disney_HK |21.78Mb
  - disney_netflix_US |65.21Mb
  - disney_HK |15.95Mb
  - disney_HK |25.09Mb
  - ğŸ‡ºğŸ‡¸US_304 |17.84Mb
  - Relay_ğŸZZ-ğŸ‡®ğŸ‡·IR_305 |21.88Mb
  - Relay_ğŸ‡©ğŸ‡ªDE-ğŸ‡©ğŸ‡ªDE_280 |204.67Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - _196 |64.96Mb
  - disney_netflix_US |65.06Mb
  - _194 |64.90Mb
  - disney_netflix_US |61.53Mb
  - disney_netflix_US |62.97Mb
  - _203 |65.56Mb
  - disney_netflix_US |59.73Mb
  - disney_netflix_US |63.66Mb
  - disney_netflix_US |68.90Mb
  - disney_netflix_US |63.57Mb
  - netflix_IE |191.95Mb
  - netflix_IE |330.24Mb
  - disney_netflix_US |65.31Mb
  - disney_netflix_US |61.91Mb
  - disney_netflix_US |42.61Mb
  - _188 |180.03Mb
  - netflix_SE |159.50Mb
  - disney_netflix_US |44.80Mb
  - _224 |18.58Mb
  - disney_MD |11.42Mb
  - netflix_IE |173.03Mb
  - disney_netflix_US |176.41Mb
  - _213 |168.37Mb
  - _219 |23.37Mb
  - _228 |21.06Mb
  - disney_HK |10.75Mb
  - disney_SG |10.04Mb
  - _227 |23.66Mb
  - _232 |63.19Mb
  - _220 |21.54Mb
  - disney_netflix_DE |18.74Mb
  - _225 |40.89Mb
  - disney_TW |18.59Mb
  - disney_netflix_GB |232.39Mb
  - _272 |24.42Mb
  - _248 |11.28Mb
  - _250 |109.56Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_260 |14.36Mb
  - Pool__261 |133.02Mb
  - _263 |20.36Mb
  - _264 |10.67Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_265 |11.88Mb
  - _270 |19.96Mb
  - disney_HK |11.13Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_274 |12.03Mb
  - ğŸ‡²ğŸ‡½MX_300 |40.10Mb
  - ğŸ‡®ğŸ‡ªIE_298 |191.33Mb
  - ğŸ‡¬ğŸ‡§GB_287 |116.37Mb
  - netflix_NL |193.61Mb
  - ğŸ‡¬ğŸ‡§GB_289 |12.18Mb
  - disney_HK |21.78Mb
  - disney_netflix_US |65.21Mb
  - disney_HK |15.95Mb
  - disney_HK |25.09Mb
  - ğŸ‡ºğŸ‡¸US_304 |17.84Mb
  - Relay_ğŸZZ-ğŸ‡®ğŸ‡·IR_305 |21.88Mb
  - Relay_ğŸ‡©ğŸ‡ªDE-ğŸ‡©ğŸ‡ªDE_280 |204.67Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
