port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: _196 |16.03Mb
  server: 167.160.90.178
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _212 |39.91Mb
  server: 173.234.29.2
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _184 |10.70Mb
  server: 147.78.1.230
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _225 |29.29Mb
  server: 66.23.207.82
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _205 |16.46Mb
  server: 138.186.142.81
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _202 |15.39Mb
  server: 94.156.250.122
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _206 |16.27Mb
  server: 154.205.153.107
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _207 |34.02Mb
  server: 176.126.83.158
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _216 |34.10Mb
  server: 91.219.237.163
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _195 |10.82Mb
  server: 38.54.59.107
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _221 |25.02Mb
  server: 109.61.39.28
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡¹GT_262 |33.14Mb
  server: 185.47.254.87
  type: ss
  country: ğŸ‡¬ğŸ‡¹GT
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _230 |31.12Mb
  server: 37.235.56.69
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _229 |12.22Mb
  server: 190.103.176.32
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _217 |12.89Mb
  server: 156.38.168.58
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _231 |20.19Mb
  server: 37.143.130.203
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _228 |26.07Mb
  server: 45.159.250.190
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _233 |11.23Mb
  server: 212.102.54.45
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡©ğŸ‡°DK_251 |12.89Mb
  server: 121.127.45.165
  type: ss
  country: ğŸ‡©ğŸ‡°DK
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¨ğŸ‡¿CZ_247 |12.39Mb
  server: 95.173.218.203
  type: ss
  country: ğŸ‡¨ğŸ‡¿CZ
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_303 |10.46Mb
  server: 16.52.161.97
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡­ğŸ‡·HR_266 |32.22Mb
  server: 169.150.242.77
  type: ss
  country: ğŸ‡­ğŸ‡·HR
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¸ğŸ‡¬SG_290 |49.86Mb
  server: 104.248.159.99
  type: ss
  country: ğŸ‡¸ğŸ‡¬SG
  port: 8080
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: ğŸ‡¸ğŸ‡¬SG_292 |50.79Mb
  server: 68.183.227.236
  type: ss
  country: ğŸ‡¸ğŸ‡¬SG
  port: 8080
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: ğŸ‡¹ğŸ‡¼TW_295 |21.89Mb
  server: 38.54.107.101
  type: ss
  country: ğŸ‡¹ğŸ‡¼TW
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_300 |23.12Mb
  server: 38.247.64.176
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_298 |14.94Mb
  server: 38.89.142.56
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡®ğŸ‡¶IQ_305 |33.09Mb
  server: 193.135.174.135
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¸ğŸ‡¨SC_286 |33.54Mb
  server: 154.205.159.100
  type: ss
  country: ğŸ‡¸ğŸ‡¨SC
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¸ğŸ‡¨SC_287 |12.80Mb
  server: 154.205.150.157
  type: ss
  country: ğŸ‡¸ğŸ‡¨SC
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - _196 |16.03Mb
  - _212 |39.91Mb
  - _184 |10.70Mb
  - _225 |29.29Mb
  - _205 |16.46Mb
  - _202 |15.39Mb
  - _206 |16.27Mb
  - _207 |34.02Mb
  - _216 |34.10Mb
  - _195 |10.82Mb
  - _221 |25.02Mb
  - ğŸ‡¬ğŸ‡¹GT_262 |33.14Mb
  - _230 |31.12Mb
  - _229 |12.22Mb
  - _217 |12.89Mb
  - _231 |20.19Mb
  - _228 |26.07Mb
  - _233 |11.23Mb
  - ğŸ‡©ğŸ‡°DK_251 |12.89Mb
  - ğŸ‡¨ğŸ‡¿CZ_247 |12.39Mb
  - ğŸ‡ºğŸ‡¸US_303 |10.46Mb
  - ğŸ‡­ğŸ‡·HR_266 |32.22Mb
  - ğŸ‡¸ğŸ‡¬SG_290 |49.86Mb
  - ğŸ‡¸ğŸ‡¬SG_292 |50.79Mb
  - ğŸ‡¹ğŸ‡¼TW_295 |21.89Mb
  - ğŸ‡ºğŸ‡¸US_300 |23.12Mb
  - ğŸ‡ºğŸ‡¸US_298 |14.94Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡®ğŸ‡¶IQ_305 |33.09Mb
  - ğŸ‡¸ğŸ‡¨SC_286 |33.54Mb
  - ğŸ‡¸ğŸ‡¨SC_287 |12.80Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - _196 |16.03Mb
  - _212 |39.91Mb
  - _184 |10.70Mb
  - _225 |29.29Mb
  - _205 |16.46Mb
  - _202 |15.39Mb
  - _206 |16.27Mb
  - _207 |34.02Mb
  - _216 |34.10Mb
  - _195 |10.82Mb
  - _221 |25.02Mb
  - ğŸ‡¬ğŸ‡¹GT_262 |33.14Mb
  - _230 |31.12Mb
  - _229 |12.22Mb
  - _217 |12.89Mb
  - _231 |20.19Mb
  - _228 |26.07Mb
  - _233 |11.23Mb
  - ğŸ‡©ğŸ‡°DK_251 |12.89Mb
  - ğŸ‡¨ğŸ‡¿CZ_247 |12.39Mb
  - ğŸ‡ºğŸ‡¸US_303 |10.46Mb
  - ğŸ‡­ğŸ‡·HR_266 |32.22Mb
  - ğŸ‡¸ğŸ‡¬SG_290 |49.86Mb
  - ğŸ‡¸ğŸ‡¬SG_292 |50.79Mb
  - ğŸ‡¹ğŸ‡¼TW_295 |21.89Mb
  - ğŸ‡ºğŸ‡¸US_300 |23.12Mb
  - ğŸ‡ºğŸ‡¸US_298 |14.94Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡®ğŸ‡¶IQ_305 |33.09Mb
  - ğŸ‡¸ğŸ‡¨SC_286 |33.54Mb
  - ğŸ‡¸ğŸ‡¨SC_287 |12.80Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
