port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: disney_DO |50.05Mb
  server: 45.150.52.40
  type: vmess
  port: 443
  uuid: c31777a1-2ee6-4864-db4c-a79fcbc8188b
  alterId: 0
  cipher: auto
  network: ws
  servername: xsj011-3.facai2024.com
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /c31777a1
- name: disney_netflix_US |37.12Mb
  server: 107.182.189.99
  type: ss
  port: 18605
  password: 68zES9hWLbwmu4r8
  cipher: aes-256-gcm
- name: disney_netflix_DE |255.61Mb
  server: 43.165.7.71
  type: vmess
  port: 19751
  uuid: 6cfa6103-5d06-40cb-f452-b563db578288
  alterId: 0
  cipher: auto
  network: http
  http-opts:
    method: GET
    path:
    - /
  h2-opts: {}
- name: disney_NO |25.52Mb
  server: 107.174.114.71
  type: ss
  port: 443
  password: 595HLF3fHUuw0McM51tpvPygSIB1uf4D
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_GB |167.35Mb
  server: 172.66.44.230
  type: trojan
  port: 8443
  udp: true
  password: 8r<[9'l6hAO#8ZQi
  sni: Koma-YT.PAGeS.Dev
  ws-opts:
    path: /tro8sFW1S91B6sZrM1?ed=2560
    headers:
      Host: Koma-YT.PAGeS.Dev
  network: ws
- name: Relay_-ðŸ‡¯ðŸ‡µJP_345 |19.35Mb
  server: 160.16.117.182
  type: trojan
  port: 3093
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: disney_netflix_GB |159.63Mb
  server: koma-yt.pages.dev
  type: trojan
  port: 8443
  udp: true
  password: 8r<[9'l6hAO#8ZQi
  sni: Koma-YT.PAGeS.Dev
  ws-opts:
    path: /tro8sFW1S91B6sZrM1?ed=2560
    headers:
      Host: Koma-YT.PAGeS.Dev
  network: ws
- name: _243 |19.01Mb
  server: 8.210.255.93
  type: vmess
  port: 18063
  uuid: 492a4c84-c62b-4a7d-dd01-30f3e5bb2c73
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
- name: _236 |12.98Mb
  server: 8.218.105.196
  type: vmess
  port: 52752
  uuid: 925bdbf5-72be-4437-bebf-441c61089f6b
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
- name: _224 |56.71Mb
  server: pupas-shirting-unsung.freesocks.work
  type: ss
  port: 443
  udp: true
  password: p78naCf2EfOlRSLTX0wFVx
  cipher: chacha20-ietf-poly1305
- name: disney_SG |13.88Mb
  server: 210.87.110.16
  type: vmess
  port: 20297
  uuid: 692c1141-f196-4ac4-8af6-7a3b67304b90
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
- name: disney_HK |23.40Mb
  server: 58.152.18.95
  type: trojan
  port: 443
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: Relay_-ðŸ‡³ðŸ‡±NL_351 |10.61Mb
  server: 160.16.196.59
  type: trojan
  port: 2890
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: Relay_-ðŸ‡¸ðŸ‡¬SG_354 |11.07Mb
  server: 160.16.233.76
  type: trojan
  port: 507
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: Relay_-ðŸ‡¸ðŸ‡¬SG_359 |10.75Mb
  server: 54.178.25.255
  type: trojan
  port: 3145
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: disney_HK |17.75Mb
  server: 58.152.30.120
  type: trojan
  port: 443
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: Relay_-ðŸ‡³ðŸ‡±NL_360 |10.30Mb
  server: 160.16.136.130
  type: trojan
  port: 4054
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: disney_HK |16.14Mb
  server: 58.152.25.242
  type: trojan
  port: 443
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: disney_FR |202.97Mb
  server: 208.76.223.218
  type: vmess
  country: ðŸ‡ªðŸ‡¸ES
  port: 40433
  uuid: d8fd8955-78db-49ba-d86f-3e4729f6ac4d
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ðŸ‡²ðŸ‡½MX_460 |164.49Mb
  server: 216.238.89.53
  type: vmess
  country: ðŸ‡²ðŸ‡½MX
  port: 57283
  uuid: 1a5aafc0-6482-451d-fe76-6875b7818579
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_FR |229.66Mb
  server: 208.76.223.218
  type: vmess
  country: ðŸ‡ªðŸ‡¸ES
  port: 27092
  uuid: a0596ba6-72a3-4366-8992-77088da65bd8
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_HK |22.95Mb
  server: 58.152.25.20
  type: trojan
  port: 443
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: _228 |10.10Mb
  server: switcher-nick-croquet.freesocks.work
  type: ss
  port: 443
  password: RFK38Cg7APneSB5cWDcpbm
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_US |48.30Mb
  server: 47.253.197.26
  type: vmess
  country: ðŸ‡ºðŸ‡¸US
  port: 12056
  uuid: dd7be7f1-38ff-45e6-f1e5-b20c2190f527
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_US |191.38Mb
  server: 38.14.99.163
  type: vmess
  country: ðŸ‡ºðŸ‡¸US
  port: 59807
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: auto
  network: tcp
  servername: 38.14.99.163
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_NL |166.88Mb
  server: 109.71.246.210
  type: ss
  country: ðŸ‡·ðŸ‡ºRU
  port: 56689
  password: YQCSKoCF3QazW8YlvDBWA4
  cipher: chacha20-ietf-poly1305
- name: disney_RU |36.98Mb
  server: 81.200.158.206
  type: ss
  country: ðŸ‡·ðŸ‡ºRU
  port: 1080
  password: AqZbt1QCs3ngEfXo1p7T-w
  cipher: chacha20-ietf-poly1305
- name: ðŸ‡°ðŸ‡·KR_459 |10.28Mb
  server: 146.56.112.110
  type: vmess
  country: ðŸ‡°ðŸ‡·KR
  port: 8888
  uuid: e7c302f3-90d6-42dd-9d7d-94a3683a3707
  alterId: 0
  cipher: auto
  network: tcp
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_DE |286.92Mb
  server: 63.180.131.159
  type: trojan
  country: ðŸ‡ºðŸ‡¸US
  port: 22223
  udp: true
  password: telegram-id-directvpn
  sni: trojan.burgerip.co.uk
  skip-cert-verify: true
- name: Relay_ðŸ‡°ðŸ‡·KR-ðŸ‡°ðŸ‡·KR_458 |10.30Mb
  server: seoul03.zgjok.com
  type: vmess
  country: ðŸ‡°ðŸ‡·KR
  port: 443
  uuid: 72a0dac4-9689-4a57-b164-5c65bfa94772
  alterId: 0
  cipher: auto
  network: ws
  servername: seoul03.zgjok.com
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /
    headers:
      HOST: seoul03.zgjok.com
- name: ðŸ‡¸ðŸ‡¬SG_465 |11.05Mb
  server: 68.183.178.131
  type: vmess
  country: ðŸ‡¸ðŸ‡¬SG
  port: 58607
  uuid: c11c32cb-27b3-4afa-c0f3-fb250aa4959e
  alterId: 0
  cipher: auto
  network: ws
  servername: www.12333.monster
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /
    headers:
      HOST: www.12333.monster
- name: ðŸ‡µðŸ‡¹ PT_461 |140.11Mb
  server: 185.231.233.112
  type: ss
  country: ðŸ‡µðŸ‡¹ PT
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: disney_netflix_US |88.83Mb
  server: cf.fovi.tk
  type: vmess
  country: ðŸZZ
  port: 443
  uuid: bf67437e-6c90-45ca-abc2-c7240a5ce2aa
  alterId: 0
  cipher: auto
  network: ws
  servername: foxlux.fovi.tk
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /eisasqa
    headers:
      HOST: foxlux.fovi.tk
proxy-groups:
- name: ðŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - disney_DO |50.05Mb
  - disney_netflix_US |37.12Mb
  - disney_netflix_DE |255.61Mb
  - disney_NO |25.52Mb
  - disney_netflix_GB |167.35Mb
  - Relay_-ðŸ‡¯ðŸ‡µJP_345 |19.35Mb
  - disney_netflix_GB |159.63Mb
  - _243 |19.01Mb
  - _236 |12.98Mb
  - _224 |56.71Mb
  - disney_SG |13.88Mb
  - disney_HK |23.40Mb
  - Relay_-ðŸ‡³ðŸ‡±NL_351 |10.61Mb
  - Relay_-ðŸ‡¸ðŸ‡¬SG_354 |11.07Mb
  - Relay_-ðŸ‡¸ðŸ‡¬SG_359 |10.75Mb
  - disney_HK |17.75Mb
  - Relay_-ðŸ‡³ðŸ‡±NL_360 |10.30Mb
  - disney_HK |16.14Mb
  - disney_FR |202.97Mb
  - ðŸ‡²ðŸ‡½MX_460 |164.49Mb
  - disney_netflix_FR |229.66Mb
  - disney_HK |22.95Mb
  - _228 |10.10Mb
  - disney_netflix_US |48.30Mb
  - disney_netflix_US |191.38Mb
  - disney_netflix_NL |166.88Mb
  - disney_RU |36.98Mb
  - ðŸ‡°ðŸ‡·KR_459 |10.28Mb
  - disney_netflix_DE |286.92Mb
  - Relay_ðŸ‡°ðŸ‡·KR-ðŸ‡°ðŸ‡·KR_458 |10.30Mb
  - ðŸ‡¸ðŸ‡¬SG_465 |11.05Mb
  - ðŸ‡µðŸ‡¹ PT_461 |140.11Mb
  - disney_netflix_US |88.83Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - disney_DO |50.05Mb
  - disney_netflix_US |37.12Mb
  - disney_netflix_DE |255.61Mb
  - disney_NO |25.52Mb
  - disney_netflix_GB |167.35Mb
  - Relay_-ðŸ‡¯ðŸ‡µJP_345 |19.35Mb
  - disney_netflix_GB |159.63Mb
  - _243 |19.01Mb
  - _236 |12.98Mb
  - _224 |56.71Mb
  - disney_SG |13.88Mb
  - disney_HK |23.40Mb
  - Relay_-ðŸ‡³ðŸ‡±NL_351 |10.61Mb
  - Relay_-ðŸ‡¸ðŸ‡¬SG_354 |11.07Mb
  - Relay_-ðŸ‡¸ðŸ‡¬SG_359 |10.75Mb
  - disney_HK |17.75Mb
  - Relay_-ðŸ‡³ðŸ‡±NL_360 |10.30Mb
  - disney_HK |16.14Mb
  - disney_FR |202.97Mb
  - ðŸ‡²ðŸ‡½MX_460 |164.49Mb
  - disney_netflix_FR |229.66Mb
  - disney_HK |22.95Mb
  - _228 |10.10Mb
  - disney_netflix_US |48.30Mb
  - disney_netflix_US |191.38Mb
  - disney_netflix_NL |166.88Mb
  - disney_RU |36.98Mb
  - ðŸ‡°ðŸ‡·KR_459 |10.28Mb
  - disney_netflix_DE |286.92Mb
  - Relay_ðŸ‡°ðŸ‡·KR-ðŸ‡°ðŸ‡·KR_458 |10.30Mb
  - ðŸ‡¸ðŸ‡¬SG_465 |11.05Mb
  - ðŸ‡µðŸ‡¹ PT_461 |140.11Mb
  - disney_netflix_US |88.83Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ðŸš€ èŠ‚ç‚¹é€‰æ‹©
