port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: Relay_-ğŸ‡³ğŸ‡±NL_473 |239.19Mb
  server: 151.242.251.137
  type: ss
  port: 8080
  password: o5osZg269v5zHpYjr1xY9s
  cipher: chacha20-ietf-poly1305
- name: disney_PT |44.40Mb
  server: 185.231.233.112
  type: ss
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: _477 |103.73Mb
  server: 213.159.67.124
  type: ss
  port: 443
  password: mbhqsStnFQT1cTZYCdsmkugGUC6GT6rp
  cipher: chacha20-ietf-poly1305
- name: disney_TR |11.59Mb
  server: 185.39.204.161
  type: ss
  port: 33563
  udp: true
  password: bSlgCoGhApOb55tIMD0zxY
  cipher: chacha20-ietf-poly1305
- name: _483 |243.69Mb
  server: 45.87.175.181
  type: ss
  port: 8080
  udp: true
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: _525 |63.94Mb
  server: 47.253.197.26
  type: vmess
  port: 12056
  uuid: dd7be7f1-38ff-45e6-f1e5-b20c2190f527
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
- name: _540 |39.35Mb
  server: 104.168.94.41
  type: vmess
  port: 32301
  uuid: a2235b72-fd9c-404f-be5a-53b2de0cb798
  alterId: 0
  cipher: auto
  network: http
  http-opts:
    method: GET
    path:
    - /
  h2-opts: {}
- name: _487 |25.05Mb
  server: 47.243.51.237
  type: vmess
  port: 52801
  uuid: ef93f413-9039-4ddb-aefb-2490287df55a
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /arki?ed=2048
- name: _493 |24.85Mb
  server: 47.243.51.237
  type: vmess
  port: 27165
  uuid: be5f65df-e104-4e2a-9391-d10454da7df1
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /arki?ed=2048
- name: Relay_-ğŸ‡²ğŸ‡¾MY_506 |28.79Mb
  server: ml0724.ysds168.shop
  type: vmess
  port: 2052
  udp: true
  uuid: 665d9b8f-153d-4907-adac-de12afd9c851
  alterId: 0
  cipher: auto
  servername: ml0724.ysds168.shop
  http-opts: {}
  h2-opts: {}
  tls: true
- name: _527 |14.32Mb
  server: 47.243.51.237
  type: vmess
  port: 23559
  uuid: e3f4cb0e-3b3d-41ad-b24a-9cbc2927b451
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /arki?ed=2048
- name: Relay_-ğŸ‡®ğŸ‡³IN_500 |28.04Mb
  server: planb.mojcn.com
  type: vmess
  port: 16626
  udp: true
  uuid: 77439561-dcef-4e45-803a-743cfa7d20c2
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /
    headers:
      Host: 9e97d6c9e2e0ad3444cbf96d3709366d.mobgslb.tbcache.com
- name: Relay_-ğŸ‡¹ğŸ‡¼TW_514 |52.95Mb
  server: planb.mojcn.com
  type: vmess
  port: 16616
  udp: true
  uuid: 77439561-dcef-4e45-803a-743cfa7d20c2
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /
    headers:
      Host: 9e97d6c9e2e0ad3444cbf96d3709366d.mobgslb.tbcache.com
- name: Relay_-ğŸ‡³ğŸ‡±NL_562 |11.81Mb
  server: 160.16.81.84
  type: trojan
  port: 2760
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¯ğŸ‡µJP_542 |12.04Mb
  server: planb.mojcn.com
  type: vmess
  port: 16617
  udp: true
  uuid: 77439561-dcef-4e45-803a-743cfa7d20c2
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /
    headers:
      Host: 9e97d6c9e2e0ad3444cbf96d3709366d.mobgslb.tbcache.com
- name: Relay_-ğŸ‡¯ğŸ‡µJP_565 |17.92Mb
  server: 160.16.138.24
  type: trojan
  port: 3169
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡³ğŸ‡±NL_566 |20.58Mb
  server: 160.16.124.55
  type: trojan
  port: 2760
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: disney_US |109.92Mb
  server: 23.247.137.64
  type: trojan
  port: 443
  udp: true
  password: 3c4e10af98c30972
  alpn:
  - h2
  sni: n2.gladns.com
  network: grpc
  grpc-opts:
    grpc-service-name: db
- name: Relay_-ğŸ‡ºğŸ‡¸US_486 |10.12Mb
  server: m.cnmjin.net
  type: vmess
  port: 16618
  udp: true
  uuid: 77439561-dcef-4e45-803a-743cfa7d20c2
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /
    headers:
      Host: 9e97d6c9e2e0ad3444cbf96d3709366d.mobgslb.tbcache.com
- name: Relay_-ğŸ‡¯ğŸ‡µJP_517 |11.90Mb
  server: m.cnmjin.net
  type: vmess
  port: 16617
  udp: true
  uuid: 77439561-dcef-4e45-803a-743cfa7d20c2
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /
    headers:
      Host: 9e97d6c9e2e0ad3444cbf96d3709366d.mobgslb.tbcache.com
- name: Relay_-ğŸ‡¯ğŸ‡µJP_569 |21.97Mb
  server: 160.16.138.24
  type: trojan
  port: 1331
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¯ğŸ‡µJP_573 |19.56Mb
  server: 52.195.176.26
  type: trojan
  port: 2145
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: Relay_-ğŸ‡³ğŸ‡±NL_578 |57.39Mb
  server: 160.16.81.84
  type: trojan
  port: 4054
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: ğŸ‡§ğŸ‡¬BG_588 |16.22Mb
  server: 87.121.162.249
  type: ss
  country: ğŸ‡§ğŸ‡¬BG
  port: 443
  password: JGv616hMWdjfuZ00jYfq7XkBHJZrOBrg
  cipher: chacha20-ietf-poly1305
- name: Relay_-ğŸ‡³ğŸ‡±NL_586 |57.52Mb
  server: 160.16.236.32
  type: trojan
  port: 4054
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡³ğŸ‡±NL_572 |50.52Mb
  server: 18.162.142.242
  type: trojan
  port: 4054
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: disney_FR |59.84Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 27092
  uuid: a0596ba6-72a3-4366-8992-77088da65bd8
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡§ğŸ‡·BR_590 |20.04Mb
  server: 38.180.16.86
  type: vmess
  country: ğŸ‡§ğŸ‡·BR
  port: 36104
  uuid: E146A8CB-9D2F-449C-ADCA-8736FB
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡§ğŸ‡·BR_589 |18.17Mb
  server: 38.180.16.86
  type: vmess
  country: ğŸ‡§ğŸ‡·BR
  port: 36236
  uuid: a58bc1a5-8c18-49ff-9453-c331b52f45dc
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: _579 |18.03Mb
  server: 58.152.18.192
  type: trojan
  port: 443
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: ğŸ‡ºğŸ‡¸US_675 |19.76Mb
  server: 23.95.75.146
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: NDRySIABARbErNIVsCNVkyYAHiBzhveT
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_595 |214.14Mb
  server: 82.38.31.190
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¦ğŸ‡ºAU_587 |10.57Mb
  server: 95.111.222.113
  type: ss
  country: ğŸ‡¦ğŸ‡ºAU
  port: 443
  password: SVt6ZiWzRI1Yxeig4xBZwiJOt6ceXwGa
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_597 |222.77Mb
  server: 82.38.31.184
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡¦ğŸ‡ºAU_681 |41.72Mb
  server: sy4.620720.xyz
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  uuid: 516d8a7a-3f0b-41d3-bad0-246116381516
  alterId: 0
  cipher: auto
  network: ws
  servername: sy4.620720.xyz
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /
    headers:
      HOST: sy4.620720.xyz
- name: ğŸ‡ºğŸ‡¸US_676 |235.66Mb
  server: 38.84.201.21
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 53487
  uuid: c3c1ec05-df2c-4975-9b42-e9b007564eb1
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡®ğŸ‡ªIE_667 |313.68Mb
  server: 18.203.220.111
  type: ss
  country: ğŸ‡®ğŸ‡ªIE
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡ºğŸ‡¸ US_673 |16.01Mb
  server: 38.165.233.93
  type: ss
  country: ğŸ‡ºğŸ‡¸ US
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: disney_TR |13.10Mb
  server: tr-1.stunnel.cc
  type: ss
  country: ğŸ‡¹ğŸ‡·TR
  port: 8444
  password: tunnel-fbrof
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸ‡­ğŸ‡°HK-ğŸ‡­ğŸ‡°HK_606 |10.24Mb
  server: cgroup.node4.s.nodelist-airport.com
  type: ss
  country: ğŸ‡­ğŸ‡°HK
  port: 32013
  password: 8f3a835c-8a45-480d-ae35-1deb2c52dcae
  cipher: aes-256-gcm
- name: ğŸ‡²ğŸ‡¾MY_670 |29.82Mb
  server: 38.54.98.110
  type: vmess
  country: ğŸ‡²ğŸ‡¾MY
  port: 2052
  uuid: 665d9b8f-153d-4907-adac-de12afd9c851
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_683 |37.77Mb
  server: sw19.sesamebuta.top
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  uuid: 805ba514-bf2f-4d5d-df49-8417804e8de3
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /abcd
- name: Relay_ğŸZZ-ğŸ‡®ğŸ‡·IR_687 |24.30Mb
  server: cf.fovi.tk
  type: vmess
  country: ğŸZZ
  port: 443
  uuid: bf67437e-6c90-45ca-abc2-c7240a5ce2aa
  alterId: 0
  cipher: auto
  network: ws
  servername: foxlux.fovi.tk
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /eisasqa
    headers:
      HOST: foxlux.fovi.tk
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - Relay_-ğŸ‡³ğŸ‡±NL_473 |239.19Mb
  - disney_PT |44.40Mb
  - _477 |103.73Mb
  - disney_TR |11.59Mb
  - _483 |243.69Mb
  - _525 |63.94Mb
  - _540 |39.35Mb
  - _487 |25.05Mb
  - _493 |24.85Mb
  - Relay_-ğŸ‡²ğŸ‡¾MY_506 |28.79Mb
  - _527 |14.32Mb
  - Relay_-ğŸ‡®ğŸ‡³IN_500 |28.04Mb
  - Relay_-ğŸ‡¹ğŸ‡¼TW_514 |52.95Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_562 |11.81Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_542 |12.04Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_565 |17.92Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_566 |20.58Mb
  - disney_US |109.92Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_486 |10.12Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_517 |11.90Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_569 |21.97Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_573 |19.56Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_578 |57.39Mb
  - ğŸ‡§ğŸ‡¬BG_588 |16.22Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_586 |57.52Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_572 |50.52Mb
  - disney_FR |59.84Mb
  - ğŸ‡§ğŸ‡·BR_590 |20.04Mb
  - ğŸ‡§ğŸ‡·BR_589 |18.17Mb
  - _579 |18.03Mb
  - ğŸ‡ºğŸ‡¸US_675 |19.76Mb
  - ğŸ‡¬ğŸ‡§GB_595 |214.14Mb
  - ğŸ‡¦ğŸ‡ºAU_587 |10.57Mb
  - ğŸ‡¬ğŸ‡§GB_597 |222.77Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡¦ğŸ‡ºAU_681 |41.72Mb
  - ğŸ‡ºğŸ‡¸US_676 |235.66Mb
  - ğŸ‡®ğŸ‡ªIE_667 |313.68Mb
  - ğŸ‡ºğŸ‡¸ US_673 |16.01Mb
  - disney_TR |13.10Mb
  - Relay_ğŸ‡­ğŸ‡°HK-ğŸ‡­ğŸ‡°HK_606 |10.24Mb
  - ğŸ‡²ğŸ‡¾MY_670 |29.82Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_683 |37.77Mb
  - Relay_ğŸZZ-ğŸ‡®ğŸ‡·IR_687 |24.30Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - Relay_-ğŸ‡³ğŸ‡±NL_473 |239.19Mb
  - disney_PT |44.40Mb
  - _477 |103.73Mb
  - disney_TR |11.59Mb
  - _483 |243.69Mb
  - _525 |63.94Mb
  - _540 |39.35Mb
  - _487 |25.05Mb
  - _493 |24.85Mb
  - Relay_-ğŸ‡²ğŸ‡¾MY_506 |28.79Mb
  - _527 |14.32Mb
  - Relay_-ğŸ‡®ğŸ‡³IN_500 |28.04Mb
  - Relay_-ğŸ‡¹ğŸ‡¼TW_514 |52.95Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_562 |11.81Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_542 |12.04Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_565 |17.92Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_566 |20.58Mb
  - disney_US |109.92Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_486 |10.12Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_517 |11.90Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_569 |21.97Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_573 |19.56Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_578 |57.39Mb
  - ğŸ‡§ğŸ‡¬BG_588 |16.22Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_586 |57.52Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_572 |50.52Mb
  - disney_FR |59.84Mb
  - ğŸ‡§ğŸ‡·BR_590 |20.04Mb
  - ğŸ‡§ğŸ‡·BR_589 |18.17Mb
  - _579 |18.03Mb
  - ğŸ‡ºğŸ‡¸US_675 |19.76Mb
  - ğŸ‡¬ğŸ‡§GB_595 |214.14Mb
  - ğŸ‡¦ğŸ‡ºAU_587 |10.57Mb
  - ğŸ‡¬ğŸ‡§GB_597 |222.77Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡¦ğŸ‡ºAU_681 |41.72Mb
  - ğŸ‡ºğŸ‡¸US_676 |235.66Mb
  - ğŸ‡®ğŸ‡ªIE_667 |313.68Mb
  - ğŸ‡ºğŸ‡¸ US_673 |16.01Mb
  - disney_TR |13.10Mb
  - Relay_ğŸ‡­ğŸ‡°HK-ğŸ‡­ğŸ‡°HK_606 |10.24Mb
  - ğŸ‡²ğŸ‡¾MY_670 |29.82Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_683 |37.77Mb
  - Relay_ğŸZZ-ğŸ‡®ğŸ‡·IR_687 |24.30Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
