port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: netflix_NL |104.93Mb
  server: 151.242.251.137
  type: ss
  port: 8080
  password: o5osZg269v5zHpYjr1xY9s
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_PT |636.55Mb
  server: 185.231.233.112
  type: ss
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: _363 |21.28Mb
  server: 103.106.3.82
  type: ss
  port: 443
  udp: true
  password: 4SaCIazlgumYkM8FkPzlmwjpyWBDZFBk
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_US |35.44Mb
  server: us5.998998.best
  type: vmess
  port: 443
  udp: true
  uuid: b376015d-77d9-4482-9aa9-051be76aac65
  alterId: 0
  cipher: auto
  network: ws
  servername: b376015d-77d9-4482-9aa9-051be76aac65.fasleangles.fun
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /androirfdsreoightrjh
    headers:
      Host: b376015d-77d9-4482-9aa9-051be76aac65.fasleangles.fun
- name: Relay_-ğŸ‡¹ğŸ‡¼TW_376 |17.21Mb
  server: planb.mojcn.com
  type: vmess
  port: 16616
  udp: true
  uuid: 77439561-dcef-4e45-803a-743cfa7d20c2
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /
    headers:
      Host: 9e97d6c9e2e0ad3444cbf96d3709366d.mobgslb.tbcache.com
- name: Relay_-ğŸ‡¯ğŸ‡µJP_404 |11.12Mb
  server: planb.mojcn.com
  type: vmess
  port: 16617
  udp: true
  uuid: 77439561-dcef-4e45-803a-743cfa7d20c2
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /
    headers:
      Host: 9e97d6c9e2e0ad3444cbf96d3709366d.mobgslb.tbcache.com
- name: Relay_-ğŸ‡ºğŸ‡¸US_371 |10.43Mb
  server: planb.mojcn.com
  type: vmess
  port: 16648
  udp: true
  uuid: 77439561-dcef-4e45-803a-743cfa7d20c2
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /
    headers:
      Host: 9e97d6c9e2e0ad3444cbf96d3709366d.mobgslb.tbcache.com
- name: disney_HK |24.08Mb
  server: planb.mojcn.com
  type: vmess
  port: 16632
  udp: true
  uuid: 77439561-dcef-4e45-803a-743cfa7d20c2
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /
    headers:
      Host: 9e97d6c9e2e0ad3444cbf96d3709366d.mobgslb.tbcache.com
- name: disney_US |28.21Mb
  server: 74.117.196.232
  type: vmess
  port: 37934
  udp: true
  uuid: b01d1e26-2f84-48da-88a1-1d06a77857f3
  alterId: 0
  cipher: auto
  network: ws
  servername: imafake.locker
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /speedtest
- name: disney_netflix_DE |232.77Mb
  server: uk2-2.998998.best
  type: vmess
  port: 443
  udp: true
  uuid: b376015d-77d9-4482-9aa9-051be76aac65
  alterId: 0
  cipher: auto
  network: ws
  servername: b376015d-77d9-4482-9aa9-051be76aac65.placeunaorder.fun
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /logcatxiouerd34try9
    headers:
      Host: b376015d-77d9-4482-9aa9-051be76aac65.placeunaorder.fun
- name: disney_HK |24.01Mb
  server: planb.mojcn.com
  type: vmess
  port: 16622
  udp: true
  uuid: 77439561-dcef-4e45-803a-743cfa7d20c2
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /
    headers:
      Host: 9e97d6c9e2e0ad3444cbf96d3709366d.mobgslb.tbcache.com
- name: disney_SG |10.95Mb
  server: planb.mojcn.com
  type: vmess
  port: 16618
  udp: true
  uuid: 77439561-dcef-4e45-803a-743cfa7d20c2
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /
    headers:
      Host: 9e97d6c9e2e0ad3444cbf96d3709366d.mobgslb.tbcache.com
- name: Relay_-ğŸ‡®ğŸ‡³IN_414 |27.45Mb
  server: planb.mojcn.com
  type: vmess
  port: 16626
  udp: true
  uuid: 77439561-dcef-4e45-803a-743cfa7d20c2
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /
    headers:
      Host: 9e97d6c9e2e0ad3444cbf96d3709366d.mobgslb.tbcache.com
- name: Relay_-ğŸ‡³ğŸ‡±NL_416 |17.14Mb
  server: 160.16.81.84
  type: trojan
  port: 2760
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: disney_HK |24.36Mb
  server: m.cnmjin.net
  type: vmess
  port: 16622
  udp: true
  uuid: 77439561-dcef-4e45-803a-743cfa7d20c2
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /
    headers:
      Host: 9e97d6c9e2e0ad3444cbf96d3709366d.mobgslb.tbcache.com
- name: disney_SG |11.42Mb
  server: m.cnmjin.net
  type: vmess
  port: 16618
  udp: true
  uuid: 77439561-dcef-4e45-803a-743cfa7d20c2
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /
    headers:
      Host: 9e97d6c9e2e0ad3444cbf96d3709366d.mobgslb.tbcache.com
- name: disney_HK |24.34Mb
  server: m.cnmjin.net
  type: vmess
  port: 16632
  udp: true
  uuid: 77439561-dcef-4e45-803a-743cfa7d20c2
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /
    headers:
      Host: 9e97d6c9e2e0ad3444cbf96d3709366d.mobgslb.tbcache.com
- name: Relay_-ğŸ‡¯ğŸ‡µJP_403 |11.02Mb
  server: m.cnmjin.net
  type: vmess
  port: 16617
  udp: true
  uuid: 77439561-dcef-4e45-803a-743cfa7d20c2
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /
    headers:
      Host: 9e97d6c9e2e0ad3444cbf96d3709366d.mobgslb.tbcache.com
- name: Relay_-ğŸ‡¹ğŸ‡¼TW_375 |12.31Mb
  server: m.cnmjin.net
  type: vmess
  port: 16616
  udp: true
  uuid: 77439561-dcef-4e45-803a-743cfa7d20c2
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /
    headers:
      Host: 9e97d6c9e2e0ad3444cbf96d3709366d.mobgslb.tbcache.com
- name: Relay_-ğŸ‡³ğŸ‡±NL_417 |11.49Mb
  server: 160.16.124.55
  type: trojan
  port: 2760
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: disney_HK |23.84Mb
  server: 58.152.25.20
  type: trojan
  port: 443
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: Relay_-ğŸ‡¯ğŸ‡µJP_424 |20.24Mb
  server: 52.195.176.26
  type: trojan
  port: 2145
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: Relay_-ğŸ‡¯ğŸ‡µJP_422 |23.02Mb
  server: 153.121.51.29
  type: trojan
  port: 3169
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡³ğŸ‡±NL_426 |41.60Mb
  server: 160.16.236.32
  type: trojan
  port: 4054
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡³ğŸ‡±NL_420 |14.19Mb
  server: 160.16.81.84
  type: trojan
  port: 4054
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¸ğŸ‡¬SG_425 |14.46Mb
  server: 153.121.51.29
  type: trojan
  port: 127
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: _419 |10.10Mb
  server: 58.152.18.192
  type: trojan
  port: 443
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: disney_HK |27.06Mb
  server: 112.118.116.66
  type: trojan
  port: 443
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: disney_netflix_US |16.54Mb
  server: us19-25.998998.best
  type: vmess
  port: 443
  udp: true
  uuid: b376015d-77d9-4482-9aa9-051be76aac65
  alterId: 0
  cipher: auto
  network: ws
  servername: b376015d-77d9-4482-9aa9-051be76aac65.mihomo.baby
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /saoihgreg9384gh8934
    headers:
      Host: b376015d-77d9-4482-9aa9-051be76aac65.mihomo.baby
- name: Relay_-ğŸ‡³ğŸ‡±NL_431 |11.01Mb
  server: 160.16.124.55
  type: trojan
  port: 4054
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡³ğŸ‡±NL_430 |10.77Mb
  server: 160.16.63.16
  type: trojan
  port: 4054
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: disney_netflix_FR |50.84Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 27092
  uuid: a0596ba6-72a3-4366-8992-77088da65bd8
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: netflix_NL |10.42Mb
  server: 82.38.31.179
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: _429 |14.19Mb
  server: 58.152.18.95
  type: trojan
  port: 443
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: ğŸ‡§ğŸ‡·BR_433 |12.56Mb
  server: 38.180.16.86
  type: vmess
  country: ğŸ‡§ğŸ‡·BR
  port: 36104
  uuid: E146A8CB-9D2F-449C-ADCA-8736FB
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡­ğŸ‡°HK_440 |111.49Mb
  server: 8.210.134.183
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 3721
  uuid: e72f5c6b-220f-40b3-a115-2d81473458cf
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
  ws-opts:
    path: /
- name: netflix_AL |33.56Mb
  server: 87.121.162.249
  type: ss
  country: ğŸ‡­ğŸ‡°HK
  port: 443
  password: JGv616hMWdjfuZ00jYfq7XkBHJZrOBrg
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡­ğŸ‡°HK_441 |126.50Mb
  server: 47.243.12.217
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 28405
  uuid: cac3e30d-fa01-4993-ac1e-d6971263ea90
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
  ws-opts:
    path: /arki?ed=2048
- name: ğŸ‡²ğŸ‡½MX_452 |35.97Mb
  server: 216.238.89.53
  type: vmess
  country: ğŸ‡²ğŸ‡½MX
  port: 57283
  uuid: 1a5aafc0-6482-451d-fe76-6875b7818579
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡­ğŸ‡°HK_442 |21.71Mb
  server: 47.242.140.52
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 48219
  uuid: 006893c6-79b1-4c44-94ff-b8bbea065f1f
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
  ws-opts:
    path: /arki?ed=2048
- name: ğŸ‡­ğŸ‡°HK_443 |178.47Mb
  server: 47.242.162.235
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 3787
  uuid: e748fe05-2678-4c31-84c6-14ed825b92b4
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
  ws-opts:
    path: /arki?ed=2048
- name: ğŸ‡­ğŸ‡°HK_446 |128.68Mb
  server: 47.242.125.104
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 58424
  uuid: 80016399-3178-472e-86e3-129aab31a025
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
  ws-opts:
    path: /arki?ed=2048
- name: ğŸ‡­ğŸ‡°HK_447 |31.36Mb
  server: 47.243.51.237
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 52801
  uuid: ef93f413-9039-4ddb-aefb-2490287df55a
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
  ws-opts:
    path: /arki?ed=2048
- name: disney_netflix_US |24.02Mb
  server: 38.84.201.21
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 53487
  uuid: c3c1ec05-df2c-4975-9b42-e9b007564eb1
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡°ğŸ‡·KR_450 |11.40Mb
  server: 146.56.112.110
  type: vmess
  country: ğŸ‡°ğŸ‡·KR
  port: 8888
  uuid: e7c302f3-90d6-42dd-9d7d-94a3683a3707
  alterId: 0
  cipher: auto
  network: tcp
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_US |31.18Mb
  server: 74.117.196.232
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 37934
  uuid: 3b475934-cb2a-4d96-b260-5e50cca5d430
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /speedtest
- name: netflix_NL |79.47Mb
  server: 45.87.175.166
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 443
  password: 1RWwXhwfAB5gAEozU4G2Pg
  cipher: chacha20-ietf-poly1305
- name: netflix_IL |11.51Mb
  server: 45.93.95.187
  type: ss
  country: ğŸ‡®ğŸ‡±IL
  port: 8618
  password: 4lUEC91c1d8oeClzDbYpXA
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡²ğŸ‡¾MY_453 |27.28Mb
  server: 38.54.98.110
  type: vmess
  country: ğŸ‡²ğŸ‡¾MY
  port: 2052
  uuid: 665d9b8f-153d-4907-adac-de12afd9c851
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: ğŸ‡¸ğŸ‡¬SG_455 |11.24Mb
  server: 68.183.178.131
  type: vmess
  country: ğŸ‡¸ğŸ‡¬SG
  port: 58607
  uuid: c11c32cb-27b3-4afa-c0f3-fb250aa4959e
  alterId: 0
  cipher: auto
  network: ws
  servername: www.12333.monster
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /
    headers:
      HOST: www.12333.monster
- name: disney_HK |13.50Mb
  server: 45.136.12.37
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 38141
  uuid: fd291be6-b48d-43a1-da38-66c7f80e2f80
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_TR |11.45Mb
  server: tr-1.stunnel.cc
  type: ss
  country: ğŸ‡¹ğŸ‡·TR
  port: 8444
  password: tunnel-fbrof
  cipher: chacha20-ietf-poly1305
- name: disney_TR |23.61Mb
  server: 185.39.204.161
  type: ss
  country: ğŸ‡¹ğŸ‡·TR
  port: 33563
  password: bSlgCoGhApOb55tIMD0zxY
  cipher: chacha20-ietf-poly1305
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - netflix_NL |104.93Mb
  - disney_netflix_PT |636.55Mb
  - _363 |21.28Mb
  - disney_netflix_US |35.44Mb
  - Relay_-ğŸ‡¹ğŸ‡¼TW_376 |17.21Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_404 |11.12Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_371 |10.43Mb
  - disney_HK |24.08Mb
  - disney_US |28.21Mb
  - disney_netflix_DE |232.77Mb
  - disney_HK |24.01Mb
  - disney_SG |10.95Mb
  - Relay_-ğŸ‡®ğŸ‡³IN_414 |27.45Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_416 |17.14Mb
  - disney_HK |24.36Mb
  - disney_SG |11.42Mb
  - disney_HK |24.34Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_403 |11.02Mb
  - Relay_-ğŸ‡¹ğŸ‡¼TW_375 |12.31Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_417 |11.49Mb
  - disney_HK |23.84Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_424 |20.24Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_422 |23.02Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_426 |41.60Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_420 |14.19Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_425 |14.46Mb
  - _419 |10.10Mb
  - disney_HK |27.06Mb
  - disney_netflix_US |16.54Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_431 |11.01Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_430 |10.77Mb
  - disney_netflix_FR |50.84Mb
  - netflix_NL |10.42Mb
  - _429 |14.19Mb
  - ğŸ‡§ğŸ‡·BR_433 |12.56Mb
  - ğŸ‡­ğŸ‡°HK_440 |111.49Mb
  - netflix_AL |33.56Mb
  - ğŸ‡­ğŸ‡°HK_441 |126.50Mb
  - ğŸ‡²ğŸ‡½MX_452 |35.97Mb
  - ğŸ‡­ğŸ‡°HK_442 |21.71Mb
  - ğŸ‡­ğŸ‡°HK_443 |178.47Mb
  - ğŸ‡­ğŸ‡°HK_446 |128.68Mb
  - ğŸ‡­ğŸ‡°HK_447 |31.36Mb
  - disney_netflix_US |24.02Mb
  - ğŸ‡°ğŸ‡·KR_450 |11.40Mb
  - disney_netflix_US |31.18Mb
  - netflix_NL |79.47Mb
  - netflix_IL |11.51Mb
  - ğŸ‡²ğŸ‡¾MY_453 |27.28Mb
  - ğŸ‡¸ğŸ‡¬SG_455 |11.24Mb
  - disney_HK |13.50Mb
  - disney_netflix_TR |11.45Mb
  - disney_TR |23.61Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - netflix_NL |104.93Mb
  - disney_netflix_PT |636.55Mb
  - _363 |21.28Mb
  - disney_netflix_US |35.44Mb
  - Relay_-ğŸ‡¹ğŸ‡¼TW_376 |17.21Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_404 |11.12Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_371 |10.43Mb
  - disney_HK |24.08Mb
  - disney_US |28.21Mb
  - disney_netflix_DE |232.77Mb
  - disney_HK |24.01Mb
  - disney_SG |10.95Mb
  - Relay_-ğŸ‡®ğŸ‡³IN_414 |27.45Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_416 |17.14Mb
  - disney_HK |24.36Mb
  - disney_SG |11.42Mb
  - disney_HK |24.34Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_403 |11.02Mb
  - Relay_-ğŸ‡¹ğŸ‡¼TW_375 |12.31Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_417 |11.49Mb
  - disney_HK |23.84Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_424 |20.24Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_422 |23.02Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_426 |41.60Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_420 |14.19Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_425 |14.46Mb
  - _419 |10.10Mb
  - disney_HK |27.06Mb
  - disney_netflix_US |16.54Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_431 |11.01Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_430 |10.77Mb
  - disney_netflix_FR |50.84Mb
  - netflix_NL |10.42Mb
  - _429 |14.19Mb
  - ğŸ‡§ğŸ‡·BR_433 |12.56Mb
  - ğŸ‡­ğŸ‡°HK_440 |111.49Mb
  - netflix_AL |33.56Mb
  - ğŸ‡­ğŸ‡°HK_441 |126.50Mb
  - ğŸ‡²ğŸ‡½MX_452 |35.97Mb
  - ğŸ‡­ğŸ‡°HK_442 |21.71Mb
  - ğŸ‡­ğŸ‡°HK_443 |178.47Mb
  - ğŸ‡­ğŸ‡°HK_446 |128.68Mb
  - ğŸ‡­ğŸ‡°HK_447 |31.36Mb
  - disney_netflix_US |24.02Mb
  - ğŸ‡°ğŸ‡·KR_450 |11.40Mb
  - disney_netflix_US |31.18Mb
  - netflix_NL |79.47Mb
  - netflix_IL |11.51Mb
  - ğŸ‡²ğŸ‡¾MY_453 |27.28Mb
  - ğŸ‡¸ğŸ‡¬SG_455 |11.24Mb
  - disney_HK |13.50Mb
  - disney_netflix_TR |11.45Mb
  - disney_TR |23.61Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
