port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: netflix_US |61.56Mb
  server: 3.89.113.22
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: _258 |66.05Mb
  server: 98.81.59.20
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: _288 |64.60Mb
  server: 13.218.107.141
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: _290 |53.81Mb
  server: 13.222.155.147
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: _291 |53.46Mb
  server: 50.19.46.248
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: _292 |67.02Mb
  server: 98.89.32.62
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: _280 |333.59Mb
  server: 3.253.99.197
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: _281 |339.05Mb
  server: 3.250.105.240
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: _285 |335.09Mb
  server: 54.246.35.116
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: _293 |168.33Mb
  server: 163.192.49.195
  type: vmess
  port: 443
  uuid: bcb7c581-3c95-4569-a4e7-918141e91ea3
  alterId: 0
  cipher: auto
  network: http
  http-opts:
    path:
    - /
    headers:
      Host:
      - a.189.cn
  h2-opts: {}
- name: _289 |136.60Mb
  server: 51.20.125.235
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: _298 |262.48Mb
  server: 85.195.101.122
  type: vmess
  port: 40878
  uuid: f3d4167e-b15e-4e46-82e9-9286ef93fda7
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: Relay_-ğŸ‡­ğŸ‡°HK_294 |10.36Mb
  server: 131.186.63.89
  type: vmess
  port: 11655
  uuid: 4bf075f5-4d5e-4d39-f5ab-b32a86250f0e
  alterId: 0
  cipher: auto
  network: ws
  servername: hk.nbee.pp.ua
  http-opts: {}
  h2-opts: {}
  tls: true
  ws-opts:
    path: /aa
    headers:
      Host: hk.nbee.pp.ua
- name: _286 |22.32Mb
  server: 103.149.182.86
  type: ss
  port: 8388
  udp: true
  password: asd123456
  cipher: chacha20-ietf
- name: _310 |13.10Mb
  server: 15.235.41.200
  type: vmess
  port: 80
  uuid: 58fe1542-5290-40ad-815a-77707a81afe5
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /IOebhLMhl1CTbFHbL95myfRX2
- name: _301 |24.10Mb
  server: 8.218.105.196
  type: vmess
  port: 52752
  uuid: 925bdbf5-72be-4437-bebf-441c61089f6b
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _296 |13.14Mb
  server: 156.245.232.15
  type: vmess
  port: 14914
  udp: true
  uuid: d3dfab98-c7d2-45d7-9941-b3dc634696e4
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _306 |11.26Mb
  server: 156.245.232.15
  type: vmess
  port: 42640
  udp: true
  uuid: 48a33a1b-a6fb-4d6a-94c5-c6808f1c4b1f
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: disney_SG |14.88Mb
  server: 165.154.195.38
  type: vmess
  port: 35034
  uuid: 959a8caf-4cea-43d0-a548-3628e7ddfafc
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: disney_US |12.90Mb
  server: 192.204.47.79
  type: vmess
  port: 42277
  udp: true
  uuid: aee61b21-e85a-484b-f203-b245f1451cff
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _311 |12.08Mb
  server: 140.238.2.250
  type: vmess
  port: 443
  uuid: 41a7089a-040b-4538-8b8d-010902405bde
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _313 |38.10Mb
  server: 89.31.120.192
  type: vmess
  port: 443
  uuid: 44537595-9ccc-4b83-8936-5f9ad3229019
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _314 |13.24Mb
  server: 130.162.152.253
  type: vmess
  port: 56867
  uuid: 5206bb9f-2cbc-44ac-de2a-471439a23707
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: Pool__326 |162.48Mb
  server: 70.34.218.149
  type: trojan
  port: 11930
  password: BaeSzHdfJIR13l67
  sni: softpillow.silentrocket.click
- name: _325 |13.72Mb
  server: 160.16.214.6
  type: trojan
  port: 2890
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: _320 |10.02Mb
  server: 54.206.192.9
  type: vmess
  port: 16407
  uuid: 08f45028-1db6-4e93-bf51-d344b6c71e19
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: disney_GB |169.79Mb
  server: 172.67.134.185
  type: trojan
  port: 443
  udp: true
  password: POORIARED
  sni: reDfRee8.REDFree8.ir
  ws-opts:
    path: /eyJqdW5rIjoiVUl6eXhLZkkwUTJ3ZzkiLCJwcm90b2NvbCI6InRyIiwibW9kZSI6InByb3h5aXAiLCJwYW5lbElQcyI6W119?ed=2560
    headers:
      Host: reDfRee8.REDFree8.ir
  network: ws
- name: _317 |12.01Mb
  server: 146.56.112.110
  type: vmess
  port: 8888
  uuid: e7c302f3-90d6-42dd-9d7d-94a3683a3707
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _316 |23.51Mb
  server: 183.236.51.36
  type: vmess
  port: 59003
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 64
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _337 |24.49Mb
  server: 38.96.254.102
  type: trojan
  port: 18509
  password: .ie4rghJuMkcf0oF
  sni: shoppingmall.electricbanana.click
- name: disney_HK |12.58Mb
  server: 154.21.201.83
  type: vmess
  port: 443
  uuid: 4bf075f5-4d5e-4d39-f5ab-b32a86250f0e
  alterId: 0
  cipher: auto
  network: ws
  servername: hk.nbee.pp.ua
  http-opts: {}
  h2-opts: {}
  tls: true
  ws-opts:
    path: /aa
    headers:
      Host: hk.nbee.pp.ua
- name: _329 |13.00Mb
  server: 153.121.51.29
  type: trojan
  port: 2890
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: disney_FR |105.67Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 27092
  uuid: a0596ba6-72a3-4366-8992-77088da65bd8
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_FR |166.18Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 40433
  uuid: d8fd8955-78db-49ba-d86f-3e4729f6ac4d
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_-ğŸ‡¯ğŸ‡µJP_333 |20.43Mb
  server: 153.121.73.102
  type: trojan
  port: 1331
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¸ğŸ‡¬SG_335 |10.70Mb
  server: 160.16.153.13
  type: trojan
  port: 3145
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: ğŸ‡¬ğŸ‡§GB_358 |203.90Mb
  server: 82.38.31.194
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US |345.21Mb
  server: 18.207.122.59
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡¬ğŸ‡§GB_359 |211.90Mb
  server: 82.38.31.191
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: _338 |49.27Mb
  server: 202.181.103.235
  type: trojan
  port: 2890
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: ğŸ‡¬ğŸ‡§GB_360 |220.78Mb
  server: 82.38.31.217
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: _348 |16.19Mb
  server: 160.16.196.59
  type: trojan
  port: 2890
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: ğŸ‡²ğŸ‡½MX_370 |41.94Mb
  server: 216.238.87.47
  type: vmess
  country: ğŸ‡²ğŸ‡½MX
  port: 27502
  uuid: b8155ce4-7e08-4c40-800f-8671312b7124
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡®ğŸ‡ªIE_368 |404.16Mb
  server: 52.50.200.2
  type: ss
  country: ğŸ‡®ğŸ‡ªIE
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: Relay_ğŸ‡©ğŸ‡ªDE-ğŸ‡©ğŸ‡ªDE_353 |222.90Mb
  server: cpanel.navar1.ir
  type: vmess
  country: ğŸ‡©ğŸ‡ªDE
  port: 100
  uuid: 95c6f6f0-84f7-4443-8a50-a59f8e66f5ee
  alterId: 0
  cipher: auto
  network: tcp
  servername: cpanel.navar1.ir
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_HK |19.32Mb
  server: 45.207.157.29
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 13852
  uuid: 845764df-ecb3-4b13-bed2-bf1551b68e9a
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡­ğŸ‡°HK_362 |11.80Mb
  server: 156.245.232.15
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 21246
  uuid: 9526b462-c45f-4940-83b9-a204462b0744
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_ğŸZZ-ğŸ‡®ğŸ‡·IR_374 |28.60Mb
  server: cf.fovi.tk
  type: vmess
  country: ğŸZZ
  port: 443
  uuid: bf67437e-6c90-45ca-abc2-c7240a5ce2aa
  alterId: 0
  cipher: auto
  network: ws
  servername: foxpol.fovi.tk
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /eisasqa
    headers:
      HOST: foxpol.fovi.tk
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - netflix_US |61.56Mb
  - _258 |66.05Mb
  - _288 |64.60Mb
  - _290 |53.81Mb
  - _291 |53.46Mb
  - _292 |67.02Mb
  - _280 |333.59Mb
  - _281 |339.05Mb
  - _285 |335.09Mb
  - _293 |168.33Mb
  - _289 |136.60Mb
  - _298 |262.48Mb
  - Relay_-ğŸ‡­ğŸ‡°HK_294 |10.36Mb
  - _286 |22.32Mb
  - _310 |13.10Mb
  - _301 |24.10Mb
  - _296 |13.14Mb
  - _306 |11.26Mb
  - disney_SG |14.88Mb
  - disney_US |12.90Mb
  - _311 |12.08Mb
  - _313 |38.10Mb
  - _314 |13.24Mb
  - Pool__326 |162.48Mb
  - _325 |13.72Mb
  - _320 |10.02Mb
  - disney_GB |169.79Mb
  - _317 |12.01Mb
  - _316 |23.51Mb
  - _337 |24.49Mb
  - disney_HK |12.58Mb
  - _329 |13.00Mb
  - disney_FR |105.67Mb
  - disney_FR |166.18Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_333 |20.43Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_335 |10.70Mb
  - ğŸ‡¬ğŸ‡§GB_358 |203.90Mb
  - ğŸ‡ºğŸ‡¸US |345.21Mb
  - ğŸ‡¬ğŸ‡§GB_359 |211.90Mb
  - _338 |49.27Mb
  - ğŸ‡¬ğŸ‡§GB_360 |220.78Mb
  - _348 |16.19Mb
  - ğŸ‡²ğŸ‡½MX_370 |41.94Mb
  - ğŸ‡®ğŸ‡ªIE_368 |404.16Mb
  - Relay_ğŸ‡©ğŸ‡ªDE-ğŸ‡©ğŸ‡ªDE_353 |222.90Mb
  - disney_HK |19.32Mb
  - ğŸ‡­ğŸ‡°HK_362 |11.80Mb
  - Relay_ğŸZZ-ğŸ‡®ğŸ‡·IR_374 |28.60Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - netflix_US |61.56Mb
  - _258 |66.05Mb
  - _288 |64.60Mb
  - _290 |53.81Mb
  - _291 |53.46Mb
  - _292 |67.02Mb
  - _280 |333.59Mb
  - _281 |339.05Mb
  - _285 |335.09Mb
  - _293 |168.33Mb
  - _289 |136.60Mb
  - _298 |262.48Mb
  - Relay_-ğŸ‡­ğŸ‡°HK_294 |10.36Mb
  - _286 |22.32Mb
  - _310 |13.10Mb
  - _301 |24.10Mb
  - _296 |13.14Mb
  - _306 |11.26Mb
  - disney_SG |14.88Mb
  - disney_US |12.90Mb
  - _311 |12.08Mb
  - _313 |38.10Mb
  - _314 |13.24Mb
  - Pool__326 |162.48Mb
  - _325 |13.72Mb
  - _320 |10.02Mb
  - disney_GB |169.79Mb
  - _317 |12.01Mb
  - _316 |23.51Mb
  - _337 |24.49Mb
  - disney_HK |12.58Mb
  - _329 |13.00Mb
  - disney_FR |105.67Mb
  - disney_FR |166.18Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_333 |20.43Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_335 |10.70Mb
  - ğŸ‡¬ğŸ‡§GB_358 |203.90Mb
  - ğŸ‡ºğŸ‡¸US |345.21Mb
  - ğŸ‡¬ğŸ‡§GB_359 |211.90Mb
  - _338 |49.27Mb
  - ğŸ‡¬ğŸ‡§GB_360 |220.78Mb
  - _348 |16.19Mb
  - ğŸ‡²ğŸ‡½MX_370 |41.94Mb
  - ğŸ‡®ğŸ‡ªIE_368 |404.16Mb
  - Relay_ğŸ‡©ğŸ‡ªDE-ğŸ‡©ğŸ‡ªDE_353 |222.90Mb
  - disney_HK |19.32Mb
  - ğŸ‡­ğŸ‡°HK_362 |11.80Mb
  - Relay_ğŸZZ-ğŸ‡®ğŸ‡·IR_374 |28.60Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
