port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: _302 |24.35Mb
  server: 196.196.192.58
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _298 |127.98Mb
  server: 82.38.31.202
  type: ss
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: _306 |216.21Mb
  server: 45.87.175.168
  type: ss
  port: 8080
  udp: true
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: netflix_NL |207.33Mb
  server: 151.242.251.152
  type: ss
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: _310 |208.75Mb
  server: 193.29.139.206
  type: ss
  port: 8080
  udp: true
  password: 4a2rfixophdjffa8KVA4Aa
  cipher: chacha20-ietf-poly1305
- name: _303 |11.90Mb
  server: 138.186.142.81
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: disney_MX |29.71Mb
  server: 38.165.231.25
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: Relay_-ğŸ‡¨ğŸ‡¦CA_321 |69.77Mb
  server: 79.127.200.169
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: Relay_-ğŸ‡ªğŸ‡ªEE_307 |63.58Mb
  server: est01-ss01.tcp-reset-club.net
  type: ss
  port: 8444
  udp: true
  password: AWNeHjukGQWwuFXadw2r6qH7gh4hZ9cj
  cipher: chacha20-ietf-poly1305
- name: Relay_-ğŸ‡®ğŸ‡¹IT_316 |14.70Mb
  server: 193.135.174.135
  type: ss
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _326 |45.18Mb
  server: 173.244.56.6
  type: ss
  port: 443
  udp: true
  password: shadowsocks
  cipher: aes-128-gcm
- name: _318 |37.55Mb
  server: 62.100.205.100
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _324 |83.93Mb
  server: 51.15.23.166
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: _331 |155.55Mb
  server: 82.38.31.176
  type: ss
  port: 8080
  udp: true
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: _332 |223.84Mb
  server: 151.242.251.147
  type: ss
  port: 8080
  password: QCXDxuDlTTMD7jtgHUjIoj
  cipher: chacha20-ietf-poly1305
- name: netflix_NL |169.03Mb
  server: 82.38.31.214
  type: ss
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: _330 |55.82Mb
  server: 89.221.225.15
  type: ss
  port: 443
  udp: true
  password: yCbQ4bry4otfifK7oel71NaXpPL9pYJb
  cipher: chacha20-ietf-poly1305
- name: disney_US |67.12Mb
  server: 79.127.200.162
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: _322 |22.45Mb
  server: 149.22.87.241
  type: ss
  port: 443
  udp: true
  password: shadowsocks
  cipher: aes-128-gcm
- name: _314 |31.90Mb
  server: 119.59.98.58
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: _340 |221.98Mb
  server: 45.14.245.2
  type: ss
  port: 443
  password: 17ZDORWIliQHuO6WRGHChXYMzdRtAYVP
  cipher: chacha20-ietf-poly1305
- name: _342 |226.21Mb
  server: 82.38.31.179
  type: ss
  port: 8080
  udp: true
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: disney_PY |151.42Mb
  server: 38.165.233.93
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: _334 |22.44Mb
  server: 172.105.199.111
  type: ss
  port: 8080
  udp: true
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: _350 |136.13Mb
  server: 185.82.73.212
  type: ss
  port: 8444
  udp: true
  password: _bypfvq6ra7g4n5yCCR9DoVeGya2XUUS
  cipher: chacha20-ietf-poly1305
- name: disney_SG |11.25Mb
  server: 38.89.142.56
  type: ss
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _363 |73.87Mb
  server: 103.35.189.136
  type: ss
  port: 443
  udp: true
  password: SS2QvbC9nqLp2sXXZo0BVy4slcErRuCt
  cipher: chacha20-ietf-poly1305
- name: _352 |174.30Mb
  server: 151.242.251.142
  type: ss
  port: 8080
  udp: true
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: _351 |13.58Mb
  server: 192.71.249.78
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: netflix_US |30.63Mb
  server: 156.146.38.167
  type: ss
  port: 443
  udp: true
  password: shadowsocks
  cipher: aes-128-gcm
- name: _364 |32.52Mb
  server: 156.146.38.169
  type: ss
  port: 443
  udp: true
  password: shadowsocks
  cipher: aes-128-gcm
- name: _365 |50.00Mb
  server: 156.146.38.170
  type: ss
  port: 443
  udp: true
  password: shadowsocks
  cipher: aes-128-gcm
- name: disney_ES |21.52Mb
  server: 145.249.109.121
  type: ss
  port: 25512
  udp: true
  password: smSMfR9jqLgMkHuQtxSIWh
  cipher: chacha20-ietf-poly1305
- name: _337 |22.26Mb
  server: 128.199.172.224
  type: ss
  port: 8080
  udp: true
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: _355 |52.16Mb
  server: 95.164.116.33
  type: ss
  port: 443
  password: pQmnC03JObbPhdh5FBJHgD6jnTLchsRA
  cipher: chacha20-ietf-poly1305
- name: _366 |198.58Mb
  server: 82.38.31.194
  type: ss
  port: 8080
  udp: true
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: _344 |23.09Mb
  server: 194.246.114.101
  type: ss
  port: 443
  udp: true
  password: HaNqw9pIE4jcx98sg7UQgHeGNTM4R2pk
  cipher: chacha20-ietf-poly1305
- name: Relay_-ğŸ‡ºğŸ‡¸US_369 |175.86Mb
  server: 82.198.246.97
  type: vmess
  port: 180
  uuid: d13fc2f5-3e05-4795-81eb-44143a09e552
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _381 |305.98Mb
  server: 172.233.229.91
  type: vmess
  port: 14102
  udp: true
  uuid: 27ba87fc-583f-4763-9060-83cf0b9264db
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: _367 |19.27Mb
  server: 185.192.124.188
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: _357 |44.47Mb
  server: 147.78.0.182
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _356 |40.10Mb
  server: 156.59.243.6
  type: ss
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: netflix_NL |192.07Mb
  server: h110vpnnl.outlinekeys.net
  type: ss
  port: 52571
  udp: true
  password: b0TKxnHAYeeFYyzTAMXn0F
  cipher: chacha20-ietf-poly1305
- name: disney_US |59.76Mb
  server: 156.233.232.192
  type: vmess
  port: 24004
  uuid: 582fcb35-20a0-452c-e179-4c759c62c494
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
- name: _386 |37.94Mb
  server: 160.16.89.176
  type: trojan
  port: 2890
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: disney_US |71.80Mb
  server: 156.233.232.192
  type: vmess
  port: 44329
  uuid: 1ba1fb56-e235-419e-c193-1c291adad4a7
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
- name: _387 |10.30Mb
  server: 160.16.116.227
  type: trojan
  port: 2760
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
  skip-cert-verify: true
- name: disney_HK |10.69Mb
  server: 149.88.95.217
  type: vmess
  port: 40741
  uuid: 1b8a751b-4909-4fec-f019-907d92e6c47f
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
- name: disney_US |71.13Mb
  server: 156.233.232.177
  type: vmess
  port: 24004
  uuid: 582fcb35-20a0-452c-e179-4c759c62c494
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
- name: disney_US |75.48Mb
  server: 156.233.232.177
  type: vmess
  port: 44329
  uuid: 1ba1fb56-e235-419e-c193-1c291adad4a7
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
- name: Relay_-ğŸ‡­ğŸ‡°HK_372 |126.80Mb
  server: v9.hdacd.com
  type: vmess
  port: 30809
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _389 |12.12Mb
  server: 47.242.225.242
  type: trojan
  port: 443
  udp: true
  password: 92690597d6298061459918a371e8d77d
  sni: hezijiasuqi.com
  skip-cert-verify: true
- name: _391 |42.57Mb
  server: 160.16.204.136
  type: trojan
  port: 2890
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: _396 |10.94Mb
  server: 160.16.131.243
  type: trojan
  port: 2760
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
  skip-cert-verify: true
- name: ğŸ‡¨ğŸ‡¦CA_404 |17.36Mb
  server: 193.203.203.66
  type: ss
  country: ğŸ‡¨ğŸ‡¦CA
  port: 443
  password: S6jUK9Fw5fMHgNqlqXObHZWv8Tf4nEkm
  cipher: chacha20-ietf-poly1305
- name: Relay_-ğŸ‡¯ğŸ‡µJP_397 |13.84Mb
  server: 160.16.87.174
  type: trojan
  port: 3169
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¯ğŸ‡µJP_398 |13.43Mb
  server: 153.121.38.213
  type: trojan
  port: 3169
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: _399 |13.94Mb
  server: 160.16.136.130
  type: trojan
  port: 2890
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: ğŸ‡§ğŸ‡·BR_402 |19.33Mb
  server: 185.192.124.188
  type: ss
  country: ğŸ‡§ğŸ‡·BR
  port: 990
  password: f8f7aCzcPKbsF8p3
  cipher: chacha20-ietf-poly1305
- name: _401 |11.02Mb
  server: 160.16.106.144
  type: trojan
  port: 2760
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
  skip-cert-verify: true
- name: _393 |11.82Mb
  server: 112.118.116.8
  type: trojan
  port: 443
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: ğŸ‡¨ğŸ‡¦CA_403 |46.27Mb
  server: 185.213.23.63
  type: ss
  country: ğŸ‡¨ğŸ‡¦CA
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _400 |21.11Mb
  server: 219.79.214.159
  type: trojan
  port: 443
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: Relay_ğŸ‡¬ğŸ‡§GB-ğŸ‡³ğŸ‡±NL_410 |214.90Mb
  server: 82.38.31.208
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: disney_DE |23.15Mb
  server: 89.163.140.136
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: disney_CH |238.60Mb
  server: 138.124.67.26
  type: ss
  country: ğŸ‡¨ğŸ‡­CH
  port: 25572
  password: nqcIfYHlpMn3jzqkNDjKaG
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_421 |180.73Mb
  server: 45.87.175.183
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_422 |195.14Mb
  server: 45.87.175.180
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: QCXDxuDlTTMD7jtgHUjIoj
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_427 |208.22Mb
  server: 45.87.175.185
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_428 |217.42Mb
  server: 45.87.175.185
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡³ğŸ‡±NL_433 |10.00Mb
  server: 193.29.139.141
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 8080
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸZZ-ğŸ‡®ğŸ‡³IN_443 |112.06Mb
  server: 104.18.14.55
  type: vmess
  country: ğŸZZ
  port: 2052
  uuid: e6447786-8c85-443c-8017-7feaa673ff45
  alterId: 0
  cipher: auto
  network: ws
  servername: in4.123417.xyz
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
  ws-opts:
    path: /
    headers:
      HOST: in4.123417.xyz
- name: ğŸ‡³ğŸ‡±NL_434 |218.56Mb
  server: 194.87.216.218
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 52571
  password: b0TKxnHAYeeFYyzTAMXn0F
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡®ğŸ‡³IN_415 |132.50Mb
  server: 103.97.203.220
  type: vmess
  country: ğŸ‡®ğŸ‡³IN
  port: 550
  uuid: 9e0e83ca-0fbc-44b1-8024-0eb8f9414156
  alterId: 0
  cipher: auto
  network: tcp
  servername: t.me/v2Line
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_440 |40.72Mb
  server: 38.14.99.163
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 59807
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: auto
  network: tcp
  servername: 38.14.99.163
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡²ğŸ‡©MD_429 |14.38Mb
  server: 176.123.5.253
  type: ss
  country: ğŸ‡²ğŸ‡©MD
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡µğŸ‡¹PT_438 |42.02Mb
  server: 185.113.143.186
  type: ss
  country: ğŸ‡µğŸ‡¹PT
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸZZ_444 |107.75Mb
  server: hgtrojan.zabc.net
  type: vmess
  country: ğŸZZ
  port: 2083
  uuid: e6395c20-4571-4b34-d6b1-55a5d36e49ea
  alterId: 0
  cipher: auto
  network: ws
  servername: hgtrojan.zabc.net
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /e6395c20
    headers:
      HOST: hgtrojan.zabc.net
- name: Relay_ğŸ‡¯ğŸ‡µJP-ğŸ‡¯ğŸ‡µJP_418 |10.67Mb
  server: xray.kk37005.tk
  type: vmess
  country: ğŸ‡¯ğŸ‡µJP
  port: 55919
  uuid: 2e7548bb-7c5b-4d97-d64d-1b2fe4050089
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: ğŸ‡¸ğŸ‡¬SG_439 |21.00Mb
  server: 68.183.227.45
  type: ss
  country: ğŸ‡¸ğŸ‡¬SG
  port: 8080
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: ğŸ ZZ_441 |137.58Mb
  server: 185.231.233.112
  type: ss
  country: ğŸ ZZ
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: Relay_ğŸZZ-ğŸ‡®ğŸ‡·IR_442 |16.79Mb
  server: cf.fovi.tk
  type: vmess
  country: ğŸZZ
  port: 443
  uuid: bf67437e-6c90-45ca-abc2-c7240a5ce2aa
  alterId: 0
  cipher: auto
  network: ws
  servername: foxlux.fovi.tk
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /eisasqa
    headers:
      HOST: foxlux.fovi.tk
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - _302 |24.35Mb
  - _298 |127.98Mb
  - _306 |216.21Mb
  - netflix_NL |207.33Mb
  - _310 |208.75Mb
  - _303 |11.90Mb
  - disney_MX |29.71Mb
  - Relay_-ğŸ‡¨ğŸ‡¦CA_321 |69.77Mb
  - Relay_-ğŸ‡ªğŸ‡ªEE_307 |63.58Mb
  - Relay_-ğŸ‡®ğŸ‡¹IT_316 |14.70Mb
  - _326 |45.18Mb
  - _318 |37.55Mb
  - _324 |83.93Mb
  - _331 |155.55Mb
  - _332 |223.84Mb
  - netflix_NL |169.03Mb
  - _330 |55.82Mb
  - disney_US |67.12Mb
  - _322 |22.45Mb
  - _314 |31.90Mb
  - _340 |221.98Mb
  - _342 |226.21Mb
  - disney_PY |151.42Mb
  - _334 |22.44Mb
  - _350 |136.13Mb
  - disney_SG |11.25Mb
  - _363 |73.87Mb
  - _352 |174.30Mb
  - _351 |13.58Mb
  - netflix_US |30.63Mb
  - _364 |32.52Mb
  - _365 |50.00Mb
  - disney_ES |21.52Mb
  - _337 |22.26Mb
  - _355 |52.16Mb
  - _366 |198.58Mb
  - _344 |23.09Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_369 |175.86Mb
  - _381 |305.98Mb
  - _367 |19.27Mb
  - _357 |44.47Mb
  - _356 |40.10Mb
  - netflix_NL |192.07Mb
  - disney_US |59.76Mb
  - _386 |37.94Mb
  - disney_US |71.80Mb
  - _387 |10.30Mb
  - disney_HK |10.69Mb
  - disney_US |71.13Mb
  - disney_US |75.48Mb
  - Relay_-ğŸ‡­ğŸ‡°HK_372 |126.80Mb
  - _389 |12.12Mb
  - _391 |42.57Mb
  - _396 |10.94Mb
  - ğŸ‡¨ğŸ‡¦CA_404 |17.36Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_397 |13.84Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_398 |13.43Mb
  - _399 |13.94Mb
  - ğŸ‡§ğŸ‡·BR_402 |19.33Mb
  - _401 |11.02Mb
  - _393 |11.82Mb
  - ğŸ‡¨ğŸ‡¦CA_403 |46.27Mb
  - _400 |21.11Mb
  - Relay_ğŸ‡¬ğŸ‡§GB-ğŸ‡³ğŸ‡±NL_410 |214.90Mb
  - disney_DE |23.15Mb
  - disney_CH |238.60Mb
  - ğŸ‡±ğŸ‡¹LT_421 |180.73Mb
  - ğŸ‡±ğŸ‡¹LT_422 |195.14Mb
  - ğŸ‡±ğŸ‡¹LT_427 |208.22Mb
  - ğŸ‡±ğŸ‡¹LT_428 |217.42Mb
  - ğŸ‡³ğŸ‡±NL_433 |10.00Mb
  - Relay_ğŸZZ-ğŸ‡®ğŸ‡³IN_443 |112.06Mb
  - ğŸ‡³ğŸ‡±NL_434 |218.56Mb
  - ğŸ‡®ğŸ‡³IN_415 |132.50Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_440 |40.72Mb
  - ğŸ‡²ğŸ‡©MD_429 |14.38Mb
  - ğŸ‡µğŸ‡¹PT_438 |42.02Mb
  - ğŸZZ_444 |107.75Mb
  - Relay_ğŸ‡¯ğŸ‡µJP-ğŸ‡¯ğŸ‡µJP_418 |10.67Mb
  - ğŸ‡¸ğŸ‡¬SG_439 |21.00Mb
  - ğŸ ZZ_441 |137.58Mb
  - Relay_ğŸZZ-ğŸ‡®ğŸ‡·IR_442 |16.79Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - _302 |24.35Mb
  - _298 |127.98Mb
  - _306 |216.21Mb
  - netflix_NL |207.33Mb
  - _310 |208.75Mb
  - _303 |11.90Mb
  - disney_MX |29.71Mb
  - Relay_-ğŸ‡¨ğŸ‡¦CA_321 |69.77Mb
  - Relay_-ğŸ‡ªğŸ‡ªEE_307 |63.58Mb
  - Relay_-ğŸ‡®ğŸ‡¹IT_316 |14.70Mb
  - _326 |45.18Mb
  - _318 |37.55Mb
  - _324 |83.93Mb
  - _331 |155.55Mb
  - _332 |223.84Mb
  - netflix_NL |169.03Mb
  - _330 |55.82Mb
  - disney_US |67.12Mb
  - _322 |22.45Mb
  - _314 |31.90Mb
  - _340 |221.98Mb
  - _342 |226.21Mb
  - disney_PY |151.42Mb
  - _334 |22.44Mb
  - _350 |136.13Mb
  - disney_SG |11.25Mb
  - _363 |73.87Mb
  - _352 |174.30Mb
  - _351 |13.58Mb
  - netflix_US |30.63Mb
  - _364 |32.52Mb
  - _365 |50.00Mb
  - disney_ES |21.52Mb
  - _337 |22.26Mb
  - _355 |52.16Mb
  - _366 |198.58Mb
  - _344 |23.09Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_369 |175.86Mb
  - _381 |305.98Mb
  - _367 |19.27Mb
  - _357 |44.47Mb
  - _356 |40.10Mb
  - netflix_NL |192.07Mb
  - disney_US |59.76Mb
  - _386 |37.94Mb
  - disney_US |71.80Mb
  - _387 |10.30Mb
  - disney_HK |10.69Mb
  - disney_US |71.13Mb
  - disney_US |75.48Mb
  - Relay_-ğŸ‡­ğŸ‡°HK_372 |126.80Mb
  - _389 |12.12Mb
  - _391 |42.57Mb
  - _396 |10.94Mb
  - ğŸ‡¨ğŸ‡¦CA_404 |17.36Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_397 |13.84Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_398 |13.43Mb
  - _399 |13.94Mb
  - ğŸ‡§ğŸ‡·BR_402 |19.33Mb
  - _401 |11.02Mb
  - _393 |11.82Mb
  - ğŸ‡¨ğŸ‡¦CA_403 |46.27Mb
  - _400 |21.11Mb
  - Relay_ğŸ‡¬ğŸ‡§GB-ğŸ‡³ğŸ‡±NL_410 |214.90Mb
  - disney_DE |23.15Mb
  - disney_CH |238.60Mb
  - ğŸ‡±ğŸ‡¹LT_421 |180.73Mb
  - ğŸ‡±ğŸ‡¹LT_422 |195.14Mb
  - ğŸ‡±ğŸ‡¹LT_427 |208.22Mb
  - ğŸ‡±ğŸ‡¹LT_428 |217.42Mb
  - ğŸ‡³ğŸ‡±NL_433 |10.00Mb
  - Relay_ğŸZZ-ğŸ‡®ğŸ‡³IN_443 |112.06Mb
  - ğŸ‡³ğŸ‡±NL_434 |218.56Mb
  - ğŸ‡®ğŸ‡³IN_415 |132.50Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_440 |40.72Mb
  - ğŸ‡²ğŸ‡©MD_429 |14.38Mb
  - ğŸ‡µğŸ‡¹PT_438 |42.02Mb
  - ğŸZZ_444 |107.75Mb
  - Relay_ğŸ‡¯ğŸ‡µJP-ğŸ‡¯ğŸ‡µJP_418 |10.67Mb
  - ğŸ‡¸ğŸ‡¬SG_439 |21.00Mb
  - ğŸ ZZ_441 |137.58Mb
  - Relay_ğŸZZ-ğŸ‡®ğŸ‡·IR_442 |16.79Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
