port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: netflix_NL |230.64Mb
  server: 151.242.251.137
  type: ss
  port: 8080
  password: o5osZg269v5zHpYjr1xY9s
  cipher: chacha20-ietf-poly1305
- name: disney_PT |59.70Mb
  server: 185.231.233.112
  type: ss
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: Relay_-ğŸ‡¸ğŸ‡¬SG_394 |13.61Mb
  server: 153.121.51.29
  type: trojan
  port: 127
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡³ğŸ‡±NL_386 |11.26Mb
  server: 160.16.63.16
  type: trojan
  port: 4054
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡³ğŸ‡±NL_385 |20.15Mb
  server: 160.16.81.84
  type: trojan
  port: 4054
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: _293 |15.06Mb
  server: 103.106.3.82
  type: ss
  port: 443
  udp: true
  password: 4SaCIazlgumYkM8FkPzlmwjpyWBDZFBk
  cipher: chacha20-ietf-poly1305
- name: disney_SG |13.68Mb
  server: 103.36.91.32
  type: ss
  port: 8388
  udp: true
  password: asd123456
  cipher: chacha20-ietf
- name: Relay_-ğŸ‡³ğŸ‡±NL_395 |38.07Mb
  server: 160.16.236.32
  type: trojan
  port: 4054
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡³ğŸ‡±NL_398 |10.80Mb
  server: 160.16.124.55
  type: trojan
  port: 4054
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: ğŸ‡ªğŸ‡¸ES_413 |21.59Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 40433
  uuid: d8fd8955-78db-49ba-d86f-3e4729f6ac4d
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡§ğŸ‡·BR_411 |18.80Mb
  server: 38.180.16.86
  type: vmess
  country: ğŸ‡§ğŸ‡·BR
  port: 36104
  uuid: E146A8CB-9D2F-449C-ADCA-8736FB
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_-ğŸ‡¯ğŸ‡µJP_405 |23.20Mb
  server: 52.195.176.26
  type: trojan
  port: 2145
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: Relay_-ğŸ‡³ğŸ‡±NL_403 |11.22Mb
  server: 160.16.124.55
  type: trojan
  port: 2760
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: ğŸ‡ªğŸ‡¸ES_414 |44.24Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 27092
  uuid: a0596ba6-72a3-4366-8992-77088da65bd8
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡¦ğŸ‡ºAU_410 |11.71Mb
  server: 54.252.240.128
  type: vmess
  country: ğŸ‡¦ğŸ‡ºAU
  port: 1000
  uuid: ca26a9fd-fef8-4ea7-d194-450ce4e0c67a
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡²ğŸ‡½MX_428 |40.01Mb
  server: 216.238.89.53
  type: vmess
  country: ğŸ‡²ğŸ‡½MX
  port: 57283
  uuid: 1a5aafc0-6482-451d-fe76-6875b7818579
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_US |19.64Mb
  server: 38.84.201.21
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 53487
  uuid: c3c1ec05-df2c-4975-9b42-e9b007564eb1
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡­ğŸ‡°HK_419 |113.55Mb
  server: 47.242.140.52
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 48219
  uuid: 006893c6-79b1-4c44-94ff-b8bbea065f1f
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
  ws-opts:
    path: /arki?ed=2048
- name: ğŸ‡­ğŸ‡°HK_420 |132.75Mb
  server: 47.242.162.148
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 31813
  uuid: 00308f3b-747a-4710-b2cb-32c8de9785a1
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
  ws-opts:
    path: /arki?ed=2048
- name: ğŸ‡­ğŸ‡°HK_421 |122.47Mb
  server: 8.218.116.26
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 32228
  uuid: e4767e9f-ed00-4f31-a984-a918bdd9b09c
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡­ğŸ‡°HK_423 |65.93Mb
  server: 47.243.12.217
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 28405
  uuid: cac3e30d-fa01-4993-ac1e-d6971263ea90
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
  ws-opts:
    path: /arki?ed=2048
- name: ğŸ‡²ğŸ‡¾MY_429 |26.28Mb
  server: 38.54.98.110
  type: vmess
  country: ğŸ‡²ğŸ‡¾MY
  port: 2052
  uuid: 665d9b8f-153d-4907-adac-de12afd9c851
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: ğŸ‡¸ğŸ‡¬SG_431 |11.00Mb
  server: 68.183.178.131
  type: vmess
  country: ğŸ‡¸ğŸ‡¬SG
  port: 58607
  uuid: c11c32cb-27b3-4afa-c0f3-fb250aa4959e
  alterId: 0
  cipher: auto
  network: ws
  servername: www.12333.monster
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /
    headers:
      HOST: www.12333.monster
- name: disney_HK |19.99Mb
  server: 45.136.12.37
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 38141
  uuid: fd291be6-b48d-43a1-da38-66c7f80e2f80
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - netflix_NL |230.64Mb
  - disney_PT |59.70Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_394 |13.61Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_386 |11.26Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_385 |20.15Mb
  - _293 |15.06Mb
  - disney_SG |13.68Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_395 |38.07Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_398 |10.80Mb
  - ğŸ‡ªğŸ‡¸ES_413 |21.59Mb
  - ğŸ‡§ğŸ‡·BR_411 |18.80Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_405 |23.20Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_403 |11.22Mb
  - ğŸ‡ªğŸ‡¸ES_414 |44.24Mb
  - ğŸ‡¦ğŸ‡ºAU_410 |11.71Mb
  - ğŸ‡²ğŸ‡½MX_428 |40.01Mb
  - disney_US |19.64Mb
  - ğŸ‡­ğŸ‡°HK_419 |113.55Mb
  - ğŸ‡­ğŸ‡°HK_420 |132.75Mb
  - ğŸ‡­ğŸ‡°HK_421 |122.47Mb
  - ğŸ‡­ğŸ‡°HK_423 |65.93Mb
  - ğŸ‡²ğŸ‡¾MY_429 |26.28Mb
  - ğŸ‡¸ğŸ‡¬SG_431 |11.00Mb
  - disney_HK |19.99Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - netflix_NL |230.64Mb
  - disney_PT |59.70Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_394 |13.61Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_386 |11.26Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_385 |20.15Mb
  - _293 |15.06Mb
  - disney_SG |13.68Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_395 |38.07Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_398 |10.80Mb
  - ğŸ‡ªğŸ‡¸ES_413 |21.59Mb
  - ğŸ‡§ğŸ‡·BR_411 |18.80Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_405 |23.20Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_403 |11.22Mb
  - ğŸ‡ªğŸ‡¸ES_414 |44.24Mb
  - ğŸ‡¦ğŸ‡ºAU_410 |11.71Mb
  - ğŸ‡²ğŸ‡½MX_428 |40.01Mb
  - disney_US |19.64Mb
  - ğŸ‡­ğŸ‡°HK_419 |113.55Mb
  - ğŸ‡­ğŸ‡°HK_420 |132.75Mb
  - ğŸ‡­ğŸ‡°HK_421 |122.47Mb
  - ğŸ‡­ğŸ‡°HK_423 |65.93Mb
  - ğŸ‡²ğŸ‡¾MY_429 |26.28Mb
  - ğŸ‡¸ğŸ‡¬SG_431 |11.00Mb
  - disney_HK |19.99Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
