port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: _308 |13.64Mb
  server: 185.47.254.87
  type: ss
  port: 990
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: chacha20-ietf-poly1305
- name: _310 |11.68Mb
  server: 38.165.231.25
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _297 |87.82Mb
  server: 82.38.31.176
  type: ss
  port: 8080
  udp: true
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: _298 |10.77Mb
  server: 82.38.31.199
  type: ss
  port: 8080
  udp: true
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: _314 |12.42Mb
  server: 45.87.175.22
  type: ss
  port: 8080
  udp: true
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: _309 |12.65Mb
  server: 192.71.249.78
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: Relay_-ğŸ‡­ğŸ‡°HK_306 |28.26Mb
  server: 103.149.182.105
  type: ss
  port: 8388
  password: asd123456
  cipher: chacha20-ietf
- name: Relay_-ğŸ‡«ğŸ‡®FI_305 |37.94Mb
  server: 193.135.174.135
  type: ss
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: Relay_-ğŸ‡¨ğŸ‡¦CA_323 |66.18Mb
  server: 79.127.200.169
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _320 |213.54Mb
  server: 82.38.31.214
  type: ss
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: _300 |45.28Mb
  server: 156.59.243.6
  type: ss
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _299 |45.46Mb
  server: 103.97.203.227
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _321 |167.01Mb
  server: 45.87.175.28
  type: ss
  port: 8080
  udp: true
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: _325 |434.74Mb
  server: 45.14.245.2
  type: ss
  port: 443
  password: 17ZDORWIliQHuO6WRGHChXYMzdRtAYVP
  cipher: chacha20-ietf-poly1305
- name: _343 |72.36Mb
  server: 172.233.229.91
  type: vmess
  port: 14102
  udp: true
  uuid: 27ba87fc-583f-4763-9060-83cf0b9264db
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: _327 |26.73Mb
  server: 103.149.182.86
  type: ss
  port: 8388
  udp: true
  password: asd123456
  cipher: chacha20-ietf
- name: _330 |246.22Mb
  server: 151.242.251.152
  type: ss
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: Relay_-ğŸ‡¯ğŸ‡µJP_347 |13.80Mb
  server: 160.16.117.182
  type: trojan
  port: 3093
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: _350 |10.54Mb
  server: 160.16.116.227
  type: trojan
  port: 2760
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
  skip-cert-verify: true
- name: _341 |23.59Mb
  server: 47.242.145.160
  type: vmess
  port: 44457
  uuid: 40290609-2743-4d85-c9c3-4c72dd151b9f
  alterId: 0
  cipher: auto
  network: http
  http-opts:
    method: GET
    path:
    - /
  h2-opts: {}
- name: _331 |17.08Mb
  server: 38.165.233.93
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: Relay_-ğŸ‡¯ğŸ‡µJP_351 |10.75Mb
  server: 160.16.117.182
  type: trojan
  port: 3169
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¯ğŸ‡µJP_352 |11.60Mb
  server: 153.121.45.139
  type: trojan
  port: 3093
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¯ğŸ‡µJP_355 |18.96Mb
  server: 160.16.229.223
  type: trojan
  port: 3169
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: ğŸ‡¨ğŸ‡¦CA_362 |90.49Mb
  server: 185.213.23.63
  type: ss
  country: ğŸ‡¨ğŸ‡¦CA
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡©ğŸ‡ªDE_366 |63.10Mb
  server: 89.163.140.136
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: Relay_ğŸ‡¬ğŸ‡§GB-ğŸ‡³ğŸ‡±NL_367 |182.70Mb
  server: 82.38.31.208
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡²ğŸ‡½MX_384 |35.25Mb
  server: 216.238.87.47
  type: vmess
  country: ğŸ‡²ğŸ‡½MX
  port: 27502
  uuid: b8155ce4-7e08-4c40-800f-8671312b7124
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡®ğŸ‡¹IT_373 |10.01Mb
  server: 176.126.83.121
  type: ss
  country: ğŸ‡®ğŸ‡¹IT
  port: 443
  password: Q4t8T7hEYY3mD2Fn4wnxyK4X35AUzvR8
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_390 |40.99Mb
  server: 38.14.99.163
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 59807
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: auto
  network: tcp
  servername: 38.14.99.163
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡±ğŸ‡¹LT_376 |109.33Mb
  server: 45.87.175.185
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_379 |200.64Mb
  server: 45.87.175.183
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_381 |199.74Mb
  server: 45.87.175.180
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: QCXDxuDlTTMD7jtgHUjIoj
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_382 |213.42Mb
  server: 45.87.175.185
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_391 |54.19Mb
  server: 47.253.197.26
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 12056
  uuid: dd7be7f1-38ff-45e6-f1e5-b20c2190f527
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡³ğŸ‡±NL_385 |147.10Mb
  server: 193.29.139.141
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 8080
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡³ğŸ‡±NL_386 |77.30Mb
  server: 193.29.139.188
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 8080
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡µğŸ‡¹PT_388 |50.12Mb
  server: 185.113.143.186
  type: ss
  country: ğŸ‡µğŸ‡¹PT
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: disney_US |26.13Mb
  server: cf.fovi.tk
  type: vmess
  country: ğŸZZ
  port: 443
  uuid: bf67437e-6c90-45ca-abc2-c7240a5ce2aa
  alterId: 0
  cipher: auto
  network: ws
  servername: foxlux.fovi.tk
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /eisasqa
    headers:
      HOST: foxlux.fovi.tk
- name: ğŸ‡±ğŸ‡¹LT_377 |11.01Mb
  server: ltnl16.saint.ydns.eu
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: _324 |47.44Mb
  server: 173.234.29.2
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - _308 |13.64Mb
  - _310 |11.68Mb
  - _297 |87.82Mb
  - _298 |10.77Mb
  - _314 |12.42Mb
  - _309 |12.65Mb
  - Relay_-ğŸ‡­ğŸ‡°HK_306 |28.26Mb
  - Relay_-ğŸ‡«ğŸ‡®FI_305 |37.94Mb
  - Relay_-ğŸ‡¨ğŸ‡¦CA_323 |66.18Mb
  - _320 |213.54Mb
  - _300 |45.28Mb
  - _299 |45.46Mb
  - _321 |167.01Mb
  - _325 |434.74Mb
  - _343 |72.36Mb
  - _327 |26.73Mb
  - _330 |246.22Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_347 |13.80Mb
  - _350 |10.54Mb
  - _341 |23.59Mb
  - _331 |17.08Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_351 |10.75Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_352 |11.60Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_355 |18.96Mb
  - ğŸ‡¨ğŸ‡¦CA_362 |90.49Mb
  - ğŸ‡©ğŸ‡ªDE_366 |63.10Mb
  - Relay_ğŸ‡¬ğŸ‡§GB-ğŸ‡³ğŸ‡±NL_367 |182.70Mb
  - ğŸ‡²ğŸ‡½MX_384 |35.25Mb
  - ğŸ‡®ğŸ‡¹IT_373 |10.01Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_390 |40.99Mb
  - ğŸ‡±ğŸ‡¹LT_376 |109.33Mb
  - ğŸ‡±ğŸ‡¹LT_379 |200.64Mb
  - ğŸ‡±ğŸ‡¹LT_381 |199.74Mb
  - ğŸ‡±ğŸ‡¹LT_382 |213.42Mb
  - ğŸ‡ºğŸ‡¸US_391 |54.19Mb
  - ğŸ‡³ğŸ‡±NL_385 |147.10Mb
  - ğŸ‡³ğŸ‡±NL_386 |77.30Mb
  - ğŸ‡µğŸ‡¹PT_388 |50.12Mb
  - disney_US |26.13Mb
  - ğŸ‡±ğŸ‡¹LT_377 |11.01Mb
  - _324 |47.44Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - _308 |13.64Mb
  - _310 |11.68Mb
  - _297 |87.82Mb
  - _298 |10.77Mb
  - _314 |12.42Mb
  - _309 |12.65Mb
  - Relay_-ğŸ‡­ğŸ‡°HK_306 |28.26Mb
  - Relay_-ğŸ‡«ğŸ‡®FI_305 |37.94Mb
  - Relay_-ğŸ‡¨ğŸ‡¦CA_323 |66.18Mb
  - _320 |213.54Mb
  - _300 |45.28Mb
  - _299 |45.46Mb
  - _321 |167.01Mb
  - _325 |434.74Mb
  - _343 |72.36Mb
  - _327 |26.73Mb
  - _330 |246.22Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_347 |13.80Mb
  - _350 |10.54Mb
  - _341 |23.59Mb
  - _331 |17.08Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_351 |10.75Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_352 |11.60Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_355 |18.96Mb
  - ğŸ‡¨ğŸ‡¦CA_362 |90.49Mb
  - ğŸ‡©ğŸ‡ªDE_366 |63.10Mb
  - Relay_ğŸ‡¬ğŸ‡§GB-ğŸ‡³ğŸ‡±NL_367 |182.70Mb
  - ğŸ‡²ğŸ‡½MX_384 |35.25Mb
  - ğŸ‡®ğŸ‡¹IT_373 |10.01Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_390 |40.99Mb
  - ğŸ‡±ğŸ‡¹LT_376 |109.33Mb
  - ğŸ‡±ğŸ‡¹LT_379 |200.64Mb
  - ğŸ‡±ğŸ‡¹LT_381 |199.74Mb
  - ğŸ‡±ğŸ‡¹LT_382 |213.42Mb
  - ğŸ‡ºğŸ‡¸US_391 |54.19Mb
  - ğŸ‡³ğŸ‡±NL_385 |147.10Mb
  - ğŸ‡³ğŸ‡±NL_386 |77.30Mb
  - ğŸ‡µğŸ‡¹PT_388 |50.12Mb
  - disney_US |26.13Mb
  - ğŸ‡±ğŸ‡¹LT_377 |11.01Mb
  - _324 |47.44Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
