port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: netflix_US |150.76Mb
  server: 82.198.246.97
  type: vmess
  port: 180
  udp: true
  uuid: d13fc2f5-3e05-4795-81eb-44143a09e552
  alterId: 0
  cipher: auto
  servername: 82.198.246.97
  http-opts: {}
  h2-opts: {}
- name: _44 |59.59Mb
  server: 45.150.52.40
  type: vmess
  port: 443
  uuid: c31777a1-2ee6-4864-db4c-a79fcbc8188b
  alterId: 0
  cipher: auto
  network: ws
  servername: xsj011-3.facai2024.com
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /c31777a1
- name: Relay_-ğŸ‡¯ğŸ‡µJP_69 |13.83Mb
  server: 160.16.242.183
  type: trojan
  port: 1331
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡³ğŸ‡±NL_67 |28.86Mb
  server: 160.16.89.176
  type: trojan
  port: 4054
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: netflix_SG |11.00Mb
  server: 160.16.153.13
  type: trojan
  port: 3145
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: disney_netflix_FR |33.49Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 27092
  uuid: a0596ba6-72a3-4366-8992-77088da65bd8
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_FR |137.71Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 40433
  uuid: d8fd8955-78db-49ba-d86f-3e4729f6ac4d
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: netflix_MX |174.29Mb
  server: 216.238.89.53
  type: vmess
  country: ğŸ‡²ğŸ‡½MX
  port: 57283
  uuid: 1a5aafc0-6482-451d-fe76-6875b7818579
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_NO |24.28Mb
  server: 107.174.114.71
  type: ss
  port: 443
  password: 595HLF3fHUuw0McM51tpvPygSIB1uf4D
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_HK |16.85Mb
  server: 58.152.18.95
  type: trojan
  port: 443
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: netflix_US |251.31Mb
  server: 195.66.27.148
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 28709
  password: hShp1Km0NcFSmSigc8ozky
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_HK |17.89Mb
  server: 8.218.105.196
  type: vmess
  port: 52752
  uuid: 925bdbf5-72be-4437-bebf-441c61089f6b
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
- name: netflix_US |14.68Mb
  server: 38.14.99.163
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 59807
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: auto
  network: tcp
  servername: 38.14.99.163
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: netflix_US |25.37Mb
  server: 209.74.86.194
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 14936
  password: ppgtoOHdm7cszGunBWBTqQ
  cipher: chacha20-ietf-poly1305
- name: netflix_NL |334.24Mb
  server: 51.15.17.169
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: netflix_IE |390.25Mb
  server: 146.70.90.196
  type: ss
  country: ğŸ‡®ğŸ‡ªIE
  port: 17454
  password: u8gp148iz90ddoo6ms37
  cipher: aes-128-gcm
- name: netflix_US |10.99Mb
  server: 209.74.81.149
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 21166
  password: q92MrrP9oJ3lMEzbQFpyuU
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_SE |51.56Mb
  server: 91.186.217.246
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 31764
  password: Ftc17VH9ZXQON5vslJCYmv
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_HK |26.79Mb
  server: 45.136.12.37
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 38141
  uuid: fd291be6-b48d-43a1-da38-66c7f80e2f80
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_ğŸZZ-ğŸ‡ºğŸ‡¸US_175 |28.39Mb
  server: cf.fovi.tk
  type: vmess
  country: ğŸZZ
  port: 443
  uuid: bf67437e-6c90-45ca-abc2-c7240a5ce2aa
  alterId: 0
  cipher: auto
  network: ws
  servername: foxlux.fovi.tk
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /eisasqa
    headers:
      HOST: foxlux.fovi.tk
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - netflix_US |150.76Mb
  - _44 |59.59Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_69 |13.83Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_67 |28.86Mb
  - netflix_SG |11.00Mb
  - disney_netflix_FR |33.49Mb
  - disney_netflix_FR |137.71Mb
  - netflix_MX |174.29Mb
  - disney_NO |24.28Mb
  - disney_netflix_HK |16.85Mb
  - netflix_US |251.31Mb
  - disney_netflix_HK |17.89Mb
  - netflix_US |14.68Mb
  - netflix_US |25.37Mb
  - netflix_NL |334.24Mb
  - netflix_IE |390.25Mb
  - netflix_US |10.99Mb
  - disney_netflix_SE |51.56Mb
  - disney_netflix_HK |26.79Mb
  - Relay_ğŸZZ-ğŸ‡ºğŸ‡¸US_175 |28.39Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - netflix_US |150.76Mb
  - _44 |59.59Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_69 |13.83Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_67 |28.86Mb
  - netflix_SG |11.00Mb
  - disney_netflix_FR |33.49Mb
  - disney_netflix_FR |137.71Mb
  - netflix_MX |174.29Mb
  - disney_NO |24.28Mb
  - disney_netflix_HK |16.85Mb
  - netflix_US |251.31Mb
  - disney_netflix_HK |17.89Mb
  - netflix_US |14.68Mb
  - netflix_US |25.37Mb
  - netflix_NL |334.24Mb
  - netflix_IE |390.25Mb
  - netflix_US |10.99Mb
  - disney_netflix_SE |51.56Mb
  - disney_netflix_HK |26.79Mb
  - Relay_ğŸZZ-ğŸ‡ºğŸ‡¸US_175 |28.39Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
