port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: disney_netflix_GB |202.38Mb
  server: koma-yt.pages.dev
  type: trojan
  port: 8443
  udp: true
  password: 8r<[9'l6hAO#8ZQi
  sni: Koma-YT.PAGeS.Dev
  ws-opts:
    path: /tro8sFW1S91B6sZrM1?ed=2560
    headers:
      Host: Koma-YT.PAGeS.Dev
  network: ws
- name: Relay_-ðŸ‡³ðŸ‡±NL_104 |20.66Mb
  server: 160.16.89.176
  type: trojan
  port: 4054
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: disney_netflix_US |13.91Mb
  server: 160.16.214.6
  type: trojan
  port: 2890
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: disney_netflix_US |20.36Mb
  server: 202.181.103.235
  type: trojan
  port: 2890
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: disney_netflix_NL |129.38Mb
  server: 82.38.31.184
  type: ss
  country: ðŸ‡¬ðŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: netflix_HK |18.78Mb
  server: 8.218.105.196
  type: vmess
  port: 52752
  uuid: 925bdbf5-72be-4437-bebf-441c61089f6b
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
- name: disney_netflix_US |32.49Mb
  server: 209.74.86.194
  type: ss
  country: ðŸ‡ºðŸ‡¸US
  port: 14936
  password: ppgtoOHdm7cszGunBWBTqQ
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_US |30.82Mb
  server: 209.74.82.196
  type: ss
  port: 48918
  udp: true
  password: 8Ij4seif85QQHfLmR0zYkQ
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_US |27.89Mb
  server: 209.74.82.227
  type: ss
  port: 26515
  udp: true
  password: uA1rLP5m0mMOQ8FcxRXxgr
  cipher: chacha20-ietf-poly1305
- name: netflix_IE |294.50Mb
  server: 146.70.90.196
  type: ss
  country: ðŸ‡®ðŸ‡ªIE
  port: 17454
  password: u8gp148iz90ddoo6ms37
  cipher: aes-128-gcm
- name: disney_netflix_NL |105.11Mb
  server: 109.71.246.210
  type: ss
  country: ðŸ‡·ðŸ‡ºRU
  port: 56689
  password: YQCSKoCF3QazW8YlvDBWA4
  cipher: chacha20-ietf-poly1305
- name: ðŸ‡¬ðŸ‡·GR_111 |522.98Mb
  server: 192.71.166.100
  type: ss
  country: ðŸ‡¬ðŸ‡·GR
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: disney_netflix_SE |71.00Mb
  server: 91.186.217.246
  type: ss
  country: ðŸ‡ºðŸ‡¸US
  port: 31764
  password: Ftc17VH9ZXQON5vslJCYmv
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_US |32.05Mb
  server: 209.74.81.149
  type: ss
  country: ðŸ‡ºðŸ‡¸US
  port: 21166
  password: q92MrrP9oJ3lMEzbQFpyuU
  cipher: chacha20-ietf-poly1305
- name: netflix_KR |10.38Mb
  server: seoul03.zgjok.com
  type: vmess
  country: ðŸ‡°ðŸ‡·KR
  port: 443
  uuid: 72a0dac4-9689-4a57-b164-5c65bfa94772
  alterId: 0
  cipher: auto
  network: ws
  servername: seoul03.zgjok.com
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /
    headers:
      HOST: seoul03.zgjok.com
- name: _90 |58.90Mb
  server: 45.150.52.40
  type: vmess
  port: 443
  uuid: c31777a1-2ee6-4864-db4c-a79fcbc8188b
  alterId: 0
  cipher: auto
  network: ws
  servername: xsj011-3.facai2024.com
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /c31777a1
- name: ðŸ‡¬ðŸ‡§GB_109 |32.98Mb
  server: 195.66.27.148
  type: ss
  country: ðŸ‡¬ðŸ‡§GB
  port: 28709
  password: hShp1Km0NcFSmSigc8ozky
  cipher: chacha20-ietf-poly1305
proxy-groups:
- name: ðŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - disney_netflix_GB |202.38Mb
  - Relay_-ðŸ‡³ðŸ‡±NL_104 |20.66Mb
  - disney_netflix_US |13.91Mb
  - disney_netflix_US |20.36Mb
  - disney_netflix_NL |129.38Mb
  - netflix_HK |18.78Mb
  - disney_netflix_US |32.49Mb
  - disney_netflix_US |30.82Mb
  - disney_netflix_US |27.89Mb
  - netflix_IE |294.50Mb
  - disney_netflix_NL |105.11Mb
  - ðŸ‡¬ðŸ‡·GR_111 |522.98Mb
  - disney_netflix_SE |71.00Mb
  - disney_netflix_US |32.05Mb
  - netflix_KR |10.38Mb
  - _90 |58.90Mb
  - ðŸ‡¬ðŸ‡§GB_109 |32.98Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - disney_netflix_GB |202.38Mb
  - Relay_-ðŸ‡³ðŸ‡±NL_104 |20.66Mb
  - disney_netflix_US |13.91Mb
  - disney_netflix_US |20.36Mb
  - disney_netflix_NL |129.38Mb
  - netflix_HK |18.78Mb
  - disney_netflix_US |32.49Mb
  - disney_netflix_US |30.82Mb
  - disney_netflix_US |27.89Mb
  - netflix_IE |294.50Mb
  - disney_netflix_NL |105.11Mb
  - ðŸ‡¬ðŸ‡·GR_111 |522.98Mb
  - disney_netflix_SE |71.00Mb
  - disney_netflix_US |32.05Mb
  - netflix_KR |10.38Mb
  - _90 |58.90Mb
  - ðŸ‡¬ðŸ‡§GB_109 |32.98Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ðŸš€ èŠ‚ç‚¹é€‰æ‹©
