port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: disney_netflix_HK |22.51Mb
  server: 23.227.38.178
  type: trojan
  port: 443
  udp: true
  password: aff9928f-7ba3-45fb-b56d-4dec45653ca9
  sni: q6clkp794liy3y90.hktimecsgo.xyz
  skip-cert-verify: true
  ws-opts:
    path: /images
    headers:
      Host: q6clkp794liy3y90.hktimecsgo.xyz
  network: ws
- name: disney_netflix_TW |47.75Mb
  server: 141.193.213.199
  type: trojan
  port: 443
  udp: true
  password: a8a5b34d-fe46-487d-bd6a-d9f3101525fd
  sni: 26z68w0ecxbuyf89.ukgogo202511.top
  skip-cert-verify: true
  ws-opts:
    path: /images
    headers:
      Host: 26z68w0ecxbuyf89.ukgogo202511.top
  network: ws
- name: _47 |31.47Mb
  server: 172.235.33.114
  type: vmess
  port: 10001
  uuid: 442a3923-eca1-4af0-b3ff-24a7ce0af68f
  alterId: 0
  cipher: auto
  network: tcp
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_FR |20.23Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 27092
  uuid: a0596ba6-72a3-4366-8992-77088da65bd8
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_NL |67.73Mb
  server: 109.71.246.210
  type: ss
  port: 56689
  udp: true
  password: YQCSKoCF3QazW8YlvDBWA4
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_NL |320.22Mb
  server: 82.38.31.218
  type: ss
  port: 8080
  udp: true
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: netflix_ES |26.63Mb
  server: 213.159.67.124
  type: ss
  port: 443
  password: mbhqsStnFQT1cTZYCdsmkugGUC6GT6rp
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_TW |10.25Mb
  server: f7c5a058-fa4a-4f7c-aed6-203efaf52286.f1eb10ae-1d82-4c6a-b4dd-bd9525520956.com
  type: trojan
  country: ğŸ‡®ğŸ‡ªIE
  port: 12102
  udp: true
  password: 05bf6017-75c3-44c1-b9bf-6a038107afde
  sni: 106.yuanul.com
  skip-cert-verify: true
- name: netflix_SG |10.46Mb
  server: f7c5a058-fa4a-4f7c-aed6-203efaf52286.f1eb10ae-1d82-4c6a-b4dd-bd9525520956.com
  type: trojan
  country: ğŸ‡®ğŸ‡ªIE
  port: 12016
  udp: true
  password: 05bf6017-75c3-44c1-b9bf-6a038107afde
  sni: sg6.yuanul.com
  skip-cert-verify: true
- name: netflix_SG |10.20Mb
  server: f7c5a058-fa4a-4f7c-aed6-203efaf52286.f1eb10ae-1d82-4c6a-b4dd-bd9525520956.com
  type: trojan
  country: ğŸ‡®ğŸ‡ªIE
  port: 12013
  udp: true
  password: 05bf6017-75c3-44c1-b9bf-6a038107afde
  sni: tr.yuanul.com
  skip-cert-verify: true
- name: disney_netflix_HK |10.36Mb
  server: f7c5a058-fa4a-4f7c-aed6-203efaf52286.f1eb10ae-1d82-4c6a-b4dd-bd9525520956.com
  type: trojan
  country: ğŸ‡®ğŸ‡ªIE
  port: 10104
  udp: true
  password: 05bf6017-75c3-44c1-b9bf-6a038107afde
  sni: sni.eos-suzhou-4.cmecloud.cn
  skip-cert-verify: true
- name: netflix_SG |10.15Mb
  server: f7c5a058-fa4a-4f7c-aed6-203efaf52286.f1eb10ae-1d82-4c6a-b4dd-bd9525520956.com
  type: trojan
  country: ğŸ‡®ğŸ‡ªIE
  port: 12014
  udp: true
  password: 05bf6017-75c3-44c1-b9bf-6a038107afde
  sni: sg4.yuanul.com
  skip-cert-verify: true
- name: disney_netflix_US |57.60Mb
  server: f7c5a058-fa4a-4f7c-aed6-203efaf52286.f1eb10ae-1d82-4c6a-b4dd-bd9525520956.com
  type: trojan
  country: ğŸ‡®ğŸ‡ªIE
  port: 13203
  udp: true
  password: 05bf6017-75c3-44c1-b9bf-6a038107afde
  sni: 136.yuanul.com
  skip-cert-verify: true
- name: disney_netflix_TW |10.53Mb
  server: f7c5a058-fa4a-4f7c-aed6-203efaf52286.f1eb10ae-1d82-4c6a-b4dd-bd9525520956.com
  type: trojan
  country: ğŸ‡®ğŸ‡ªIE
  port: 12106
  udp: true
  password: 05bf6017-75c3-44c1-b9bf-6a038107afde
  sni: 110.yuanul.com
  skip-cert-verify: true
- name: disney_netflix_HK |10.51Mb
  server: f7c5a058-fa4a-4f7c-aed6-203efaf52286.f1eb10ae-1d82-4c6a-b4dd-bd9525520956.com
  type: trojan
  country: ğŸ‡®ğŸ‡ªIE
  port: 10107
  udp: true
  password: 05bf6017-75c3-44c1-b9bf-6a038107afde
  sni: sni.eos-suzhou-4.cmecloud.cn
  skip-cert-verify: true
- name: disney_netflix_US |58.64Mb
  server: f7c5a058-fa4a-4f7c-aed6-203efaf52286.f1eb10ae-1d82-4c6a-b4dd-bd9525520956.com
  type: trojan
  country: ğŸ‡®ğŸ‡ªIE
  port: 13206
  udp: true
  password: 05bf6017-75c3-44c1-b9bf-6a038107afde
  sni: 138.yuanul.com
  skip-cert-verify: true
- name: disney_netflix_US |47.66Mb
  server: us19-25.998998.best
  type: vmess
  port: 443
  udp: true
  uuid: 24254866-770c-41b4-9404-3f50524f425b
  alterId: 0
  cipher: auto
  network: ws
  servername: 24254866-770c-41b4-9404-3f50524f425b.mihomo.baby
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /saoihgreg9384gh8934
    headers:
      Host: 24254866-770c-41b4-9404-3f50524f425b.mihomo.baby
- name: disney_netflix_NL |310.42Mb
  server: 151.242.251.144
  type: ss
  country: ğŸ‡®ğŸ‡· IR
  port: 8080
  password: 4a2rfixophdjffa8KVA4Aa
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_NL |255.87Mb
  server: 151.242.251.153
  type: ss
  country: ğŸ‡®ğŸ‡· IR
  port: 8080
  password: QCXDxuDlTTMD7jtgHUjIoj
  cipher: chacha20-ietf-poly1305
- name: netflix_JP |10.13Mb
  server: f7c5a058-fa4a-4f7c-aed6-203efaf52286.f1eb10ae-1d82-4c6a-b4dd-bd9525520956.com
  type: trojan
  country: ğŸ‡®ğŸ‡ªIE
  port: 12204
  udp: true
  password: 05bf6017-75c3-44c1-b9bf-6a038107afde
  sni: 121.yuanul.com
  skip-cert-verify: true
- name: disney_netflix_US |57.92Mb
  server: f7c5a058-fa4a-4f7c-aed6-203efaf52286.f1eb10ae-1d82-4c6a-b4dd-bd9525520956.com
  type: trojan
  country: ğŸ‡®ğŸ‡ªIE
  port: 13207
  udp: true
  password: 05bf6017-75c3-44c1-b9bf-6a038107afde
  sni: 140.yuanul.com
  skip-cert-verify: true
- name: Relay_ğŸ‡®ğŸ‡ªIE-ğŸ‡®ğŸ‡·IR_101 |10.36Mb
  server: f7c5a058-fa4a-4f7c-aed6-203efaf52286.f1eb10ae-1d82-4c6a-b4dd-bd9525520956.com
  type: trojan
  country: ğŸ‡®ğŸ‡ªIE
  port: 10105
  udp: true
  password: 05bf6017-75c3-44c1-b9bf-6a038107afde
  sni: sni.eos-suzhou-4.cmecloud.cn
  skip-cert-verify: true
- name: disney_netflix_HK |10.26Mb
  server: f7c5a058-fa4a-4f7c-aed6-203efaf52286.f1eb10ae-1d82-4c6a-b4dd-bd9525520956.com
  type: trojan
  country: ğŸ‡®ğŸ‡ªIE
  port: 10101
  udp: true
  password: 05bf6017-75c3-44c1-b9bf-6a038107afde
  sni: sni.eos-suzhou-4.cmecloud.cn
  skip-cert-verify: true
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - disney_netflix_HK |22.51Mb
  - disney_netflix_TW |47.75Mb
  - _47 |31.47Mb
  - disney_netflix_FR |20.23Mb
  - disney_netflix_NL |67.73Mb
  - disney_netflix_NL |320.22Mb
  - netflix_ES |26.63Mb
  - disney_netflix_TW |10.25Mb
  - netflix_SG |10.46Mb
  - netflix_SG |10.20Mb
  - disney_netflix_HK |10.36Mb
  - netflix_SG |10.15Mb
  - disney_netflix_US |57.60Mb
  - disney_netflix_TW |10.53Mb
  - disney_netflix_HK |10.51Mb
  - disney_netflix_US |58.64Mb
  - disney_netflix_US |47.66Mb
  - disney_netflix_NL |310.42Mb
  - disney_netflix_NL |255.87Mb
  - netflix_JP |10.13Mb
  - disney_netflix_US |57.92Mb
  - Relay_ğŸ‡®ğŸ‡ªIE-ğŸ‡®ğŸ‡·IR_101 |10.36Mb
  - disney_netflix_HK |10.26Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - disney_netflix_HK |22.51Mb
  - disney_netflix_TW |47.75Mb
  - _47 |31.47Mb
  - disney_netflix_FR |20.23Mb
  - disney_netflix_NL |67.73Mb
  - disney_netflix_NL |320.22Mb
  - netflix_ES |26.63Mb
  - disney_netflix_TW |10.25Mb
  - netflix_SG |10.46Mb
  - netflix_SG |10.20Mb
  - disney_netflix_HK |10.36Mb
  - netflix_SG |10.15Mb
  - disney_netflix_US |57.60Mb
  - disney_netflix_TW |10.53Mb
  - disney_netflix_HK |10.51Mb
  - disney_netflix_US |58.64Mb
  - disney_netflix_US |47.66Mb
  - disney_netflix_NL |310.42Mb
  - disney_netflix_NL |255.87Mb
  - netflix_JP |10.13Mb
  - disney_netflix_US |57.92Mb
  - Relay_ğŸ‡®ğŸ‡ªIE-ğŸ‡®ğŸ‡·IR_101 |10.36Mb
  - disney_netflix_HK |10.26Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
