port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: disney_netflix_US |59.97Mb
  server: 45.150.52.40
  type: vmess
  port: 443
  uuid: c31777a1-2ee6-4864-db4c-a79fcbc8188b
  alterId: 0
  cipher: auto
  network: ws
  servername: xsj011-3.facai2024.com
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /c31777a1
- name: disney_GB |60.65Mb
  server: koma-yt.pages.dev
  type: trojan
  port: 8443
  udp: true
  password: 8r<[9'l6hAO#8ZQi
  sni: Koma-YT.PAGeS.Dev
  ws-opts:
    path: /tro8sFW1S91B6sZrM1?ed=2560
    headers:
      Host: Koma-YT.PAGeS.Dev
  network: ws
- name: disney_netflix_US |10.62Mb
  server: 160.16.214.6
  type: trojan
  port: 2890
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: Relay_-ðŸ‡³ðŸ‡±NL_143 |25.97Mb
  server: 160.16.106.144
  type: trojan
  port: 4054
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: Relay_-ðŸ‡³ðŸ‡±NL_142 |14.09Mb
  server: 160.16.89.176
  type: trojan
  port: 4054
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: disney_netflix_US |11.19Mb
  server: 202.181.103.235
  type: trojan
  port: 2890
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: netflix_JP |19.98Mb
  server: 160.16.242.183
  type: trojan
  port: 1331
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: disney_US |13.12Mb
  server: 185.221.23.251
  type: vmess
  country: ðŸ‡ªðŸ‡¸ES
  port: 29431
  uuid: 8b78363e-3c3a-44ab-f0d8-f13d950c8572
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: _125 |114.79Mb
  server: 47.242.145.160
  type: vmess
  port: 44457
  uuid: 40290609-2743-4d85-c9c3-4c72dd151b9f
  alterId: 0
  cipher: auto
  network: http
  http-opts:
    method: GET
    path:
    - /
  h2-opts: {}
- name: _133 |122.00Mb
  server: 8.218.105.196
  type: vmess
  port: 52752
  uuid: 925bdbf5-72be-4437-bebf-441c61089f6b
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
- name: Relay_-ðŸ‡¯ðŸ‡µJP_147 |13.33Mb
  server: 153.121.73.102
  type: trojan
  port: 1331
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: disney_netflix_HK |23.96Mb
  server: 58.152.110.82
  type: trojan
  port: 443
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: disney_netflix_FR |206.32Mb
  server: 208.76.223.218
  type: vmess
  country: ðŸ‡ªðŸ‡¸ES
  port: 40433
  uuid: d8fd8955-78db-49ba-d86f-3e4729f6ac4d
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_FR |167.71Mb
  server: 208.76.223.218
  type: vmess
  country: ðŸ‡ªðŸ‡¸ES
  port: 27092
  uuid: a0596ba6-72a3-4366-8992-77088da65bd8
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: netflix_NL |165.97Mb
  server: 82.38.31.184
  type: ss
  country: ðŸ‡¬ðŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: netflix_NL |112.14Mb
  server: 51.15.17.169
  type: ss
  country: ðŸ‡¬ðŸ‡§GB
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: disney_netflix_US |22.50Mb
  server: 195.66.27.148
  type: ss
  country: ðŸ‡¬ðŸ‡§GB
  port: 28709
  password: hShp1Km0NcFSmSigc8ozky
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_US |62.32Mb
  server: 47.253.197.26
  type: vmess
  country: ðŸ‡ºðŸ‡¸US
  port: 12056
  uuid: dd7be7f1-38ff-45e6-f1e5-b20c2190f527
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: netflix_IE |15.45Mb
  server: 146.70.90.196
  type: ss
  country: ðŸ‡®ðŸ‡ªIE
  port: 17454
  password: u8gp148iz90ddoo6ms37
  cipher: aes-128-gcm
- name: netflix_MX |38.97Mb
  server: 216.238.89.53
  type: vmess
  country: ðŸ‡²ðŸ‡½MX
  port: 57283
  uuid: 1a5aafc0-6482-451d-fe76-6875b7818579
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_NL |36.46Mb
  server: 109.71.246.210
  type: ss
  country: ðŸ‡·ðŸ‡ºRU
  port: 56689
  password: YQCSKoCF3QazW8YlvDBWA4
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_US |39.19Mb
  server: 38.14.99.163
  type: vmess
  country: ðŸ‡ºðŸ‡¸US
  port: 59807
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: auto
  network: tcp
  servername: 38.14.99.163
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ðŸ‡·ðŸ‡ºRU_221 |37.68Mb
  server: 81.200.158.206
  type: ss
  country: ðŸ‡·ðŸ‡ºRU
  port: 1080
  password: AqZbt1QCs3ngEfXo1p7T-w
  cipher: chacha20-ietf-poly1305
- name: netflix_KR |11.87Mb
  server: 146.56.112.110
  type: vmess
  country: ðŸ‡°ðŸ‡·KR
  port: 8888
  uuid: e7c302f3-90d6-42dd-9d7d-94a3683a3707
  alterId: 0
  cipher: auto
  network: tcp
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_HK |27.32Mb
  server: 8.218.116.26
  type: vmess
  country: ðŸ‡­ðŸ‡°HK
  port: 32228
  uuid: e4767e9f-ed00-4f31-a984-a918bdd9b09c
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_SE |59.10Mb
  server: 91.186.217.246
  type: ss
  country: ðŸ‡ºðŸ‡¸US
  port: 31764
  password: Ftc17VH9ZXQON5vslJCYmv
  cipher: chacha20-ietf-poly1305
- name: Relay_-ðŸ‡§ðŸ‡¬BG_112 |24.89Mb
  server: clr.ducks.tel
  type: ss
  port: 17844
  password: '907560230'
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_US |17.36Mb
  server: cf.fovi.tk
  type: vmess
  country: ðŸZZ
  port: 443
  uuid: bf67437e-6c90-45ca-abc2-c7240a5ce2aa
  alterId: 0
  cipher: auto
  network: ws
  servername: foxlux.fovi.tk
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /eisasqa
    headers:
      HOST: foxlux.fovi.tk
proxy-groups:
- name: ðŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - disney_netflix_US |59.97Mb
  - disney_GB |60.65Mb
  - disney_netflix_US |10.62Mb
  - Relay_-ðŸ‡³ðŸ‡±NL_143 |25.97Mb
  - Relay_-ðŸ‡³ðŸ‡±NL_142 |14.09Mb
  - disney_netflix_US |11.19Mb
  - netflix_JP |19.98Mb
  - disney_US |13.12Mb
  - _125 |114.79Mb
  - _133 |122.00Mb
  - Relay_-ðŸ‡¯ðŸ‡µJP_147 |13.33Mb
  - disney_netflix_HK |23.96Mb
  - disney_netflix_FR |206.32Mb
  - disney_netflix_FR |167.71Mb
  - netflix_NL |165.97Mb
  - netflix_NL |112.14Mb
  - disney_netflix_US |22.50Mb
  - disney_netflix_US |62.32Mb
  - netflix_IE |15.45Mb
  - netflix_MX |38.97Mb
  - disney_NL |36.46Mb
  - disney_netflix_US |39.19Mb
  - ðŸ‡·ðŸ‡ºRU_221 |37.68Mb
  - netflix_KR |11.87Mb
  - disney_netflix_HK |27.32Mb
  - disney_netflix_SE |59.10Mb
  - Relay_-ðŸ‡§ðŸ‡¬BG_112 |24.89Mb
  - disney_netflix_US |17.36Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - disney_netflix_US |59.97Mb
  - disney_GB |60.65Mb
  - disney_netflix_US |10.62Mb
  - Relay_-ðŸ‡³ðŸ‡±NL_143 |25.97Mb
  - Relay_-ðŸ‡³ðŸ‡±NL_142 |14.09Mb
  - disney_netflix_US |11.19Mb
  - netflix_JP |19.98Mb
  - disney_US |13.12Mb
  - _125 |114.79Mb
  - _133 |122.00Mb
  - Relay_-ðŸ‡¯ðŸ‡µJP_147 |13.33Mb
  - disney_netflix_HK |23.96Mb
  - disney_netflix_FR |206.32Mb
  - disney_netflix_FR |167.71Mb
  - netflix_NL |165.97Mb
  - netflix_NL |112.14Mb
  - disney_netflix_US |22.50Mb
  - disney_netflix_US |62.32Mb
  - netflix_IE |15.45Mb
  - netflix_MX |38.97Mb
  - disney_NL |36.46Mb
  - disney_netflix_US |39.19Mb
  - ðŸ‡·ðŸ‡ºRU_221 |37.68Mb
  - netflix_KR |11.87Mb
  - disney_netflix_HK |27.32Mb
  - disney_netflix_SE |59.10Mb
  - Relay_-ðŸ‡§ðŸ‡¬BG_112 |24.89Mb
  - disney_netflix_US |17.36Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ðŸš€ èŠ‚ç‚¹é€‰æ‹©
