port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: disney_netflix_US |43.51Mb
  server: 88.210.36.107
  type: ss
  port: 2377
  udp: true
  password: t0srmdxrm3xyjnvqz9ewlxb2myq7rjuv
  cipher: chacha20-ietf-poly1305
  plugin: obfs
  plugin-opts:
    host: (TG @WangCai2)e7b7ab7:102816
    mode: tls
- name: disney_netflix_US |43.60Mb
  server: 88.210.36.109
  type: ss
  port: 2377
  udp: true
  password: t0srmdxrm3xyjnvqz9ewlxb2myq7rjuv
  cipher: chacha20-ietf-poly1305
  plugin: obfs
  plugin-opts:
    host: (TG @WangCai2)e7b7ab7:102816
    mode: tls
- name: disney_netflix_US |42.01Mb
  server: 88.210.36.106
  type: ss
  port: 2377
  udp: true
  password: t0srmdxrm3xyjnvqz9ewlxb2myq7rjuv
  cipher: chacha20-ietf-poly1305
  plugin: obfs
  plugin-opts:
    host: (TG @WangCai2)e7b7ab7:102816
    mode: tls
- name: disney_netflix_US |44.21Mb
  server: 88.210.36.108
  type: ss
  port: 2377
  udp: true
  password: t0srmdxrm3xyjnvqz9ewlxb2myq7rjuv
  cipher: chacha20-ietf-poly1305
  plugin: obfs
  plugin-opts:
    host: (TG @WangCai2)e7b7ab7:102816
    mode: tls
- name: Relay_-ğŸ‡ºğŸ‡¸US_116 |166.35Mb
  server: 82.198.246.97
  type: vmess
  port: 180
  uuid: d13fc2f5-3e05-4795-81eb-44143a09e552
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: Relay_-ğŸ‡¯ğŸ‡µJP_122 |10.22Mb
  server: 160.16.87.174
  type: trojan
  port: 3169
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: _119 |10.95Mb
  server: 160.16.131.243
  type: trojan
  port: 2760
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
  skip-cert-verify: true
- name: disney_netflix_US |11.11Mb
  server: 160.16.136.130
  type: trojan
  port: 2890
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: _124 |15.10Mb
  server: 202.181.103.246
  type: trojan
  port: 4054
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: disney_netflix_US |57.40Mb
  server: 160.16.204.136
  type: trojan
  port: 2890
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: disney_netflix_NL |62.11Mb
  server: 45.14.245.2
  type: ss
  port: 443
  password: 17ZDORWIliQHuO6WRGHChXYMzdRtAYVP
  cipher: chacha20-ietf-poly1305
- name: _109 |221.71Mb
  server: 82.38.31.179
  type: ss
  port: 8080
  udp: true
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_DE |229.24Mb
  server: 45.80.188.48
  type: vmess
  port: 50255
  uuid: bc140c02-25a9-4feb-96bb-7d772b17fd17
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
- name: disney_netflix_PY |99.09Mb
  server: 38.165.233.93
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: netflix_MX |37.93Mb
  server: 216.238.87.47
  type: vmess
  country: ğŸ‡²ğŸ‡½MX
  port: 27502
  uuid: b8155ce4-7e08-4c40-800f-8671312b7124
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_US |18.65Mb
  server: 38.14.99.163
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 59807
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: auto
  network: tcp
  servername: 38.14.99.163
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_JP |11.04Mb
  server: 153.121.45.139
  type: trojan
  port: 3093
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: disney_netflix_NL |10.50Mb
  server: 160.16.116.227
  type: trojan
  port: 2760
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
  skip-cert-verify: true
- name: Relay_-ğŸ‡¸ğŸ‡¬SG_129 |11.36Mb
  server: 160.16.196.59
  type: trojan
  port: 1507
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: _131 |12.35Mb
  server: 160.16.57.238
  type: trojan
  port: 4054
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: disney_netflix_NL |35.77Mb
  server: 91.221.37.30
  type: ss
  port: 1234
  udp: true
  password: cPzFh2p9MWXvVYWs5hX55e5BZFty7ke-
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_US |58.01Mb
  server: 205.209.109.194
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 17277
  password: d2fkgzsdu5sturjs8f19
  cipher: aes-128-gcm
- name: ğŸ‡­ğŸ‡°HK_133 |26.76Mb
  server: 8.218.105.196
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 52752
  uuid: 925bdbf5-72be-4437-bebf-441c61089f6b
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡­ğŸ‡°HK_134 |159.71Mb
  server: 8.218.116.26
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 32228
  uuid: e4767e9f-ed00-4f31-a984-a918bdd9b09c
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_US |15.31Mb
  server: cf.fovi.tk
  type: vmess
  country: ğŸZZ
  port: 443
  uuid: bf67437e-6c90-45ca-abc2-c7240a5ce2aa
  alterId: 0
  cipher: auto
  network: ws
  servername: foxlux.fovi.tk
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /eisasqa
    headers:
      HOST: foxlux.fovi.tk
- name: ğŸ‡ºğŸ‡¸US_139 |42.82Mb
  server: 47.253.197.26
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 12056
  uuid: dd7be7f1-38ff-45e6-f1e5-b20c2190f527
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - disney_netflix_US |43.51Mb
  - disney_netflix_US |43.60Mb
  - disney_netflix_US |42.01Mb
  - disney_netflix_US |44.21Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_116 |166.35Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_122 |10.22Mb
  - _119 |10.95Mb
  - disney_netflix_US |11.11Mb
  - _124 |15.10Mb
  - disney_netflix_US |57.40Mb
  - disney_netflix_NL |62.11Mb
  - _109 |221.71Mb
  - disney_netflix_DE |229.24Mb
  - disney_netflix_PY |99.09Mb
  - netflix_MX |37.93Mb
  - disney_netflix_US |18.65Mb
  - disney_netflix_JP |11.04Mb
  - disney_netflix_NL |10.50Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_129 |11.36Mb
  - _131 |12.35Mb
  - disney_netflix_NL |35.77Mb
  - disney_netflix_US |58.01Mb
  - ğŸ‡­ğŸ‡°HK_133 |26.76Mb
  - ğŸ‡­ğŸ‡°HK_134 |159.71Mb
  - disney_netflix_US |15.31Mb
  - ğŸ‡ºğŸ‡¸US_139 |42.82Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - disney_netflix_US |43.51Mb
  - disney_netflix_US |43.60Mb
  - disney_netflix_US |42.01Mb
  - disney_netflix_US |44.21Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_116 |166.35Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_122 |10.22Mb
  - _119 |10.95Mb
  - disney_netflix_US |11.11Mb
  - _124 |15.10Mb
  - disney_netflix_US |57.40Mb
  - disney_netflix_NL |62.11Mb
  - _109 |221.71Mb
  - disney_netflix_DE |229.24Mb
  - disney_netflix_PY |99.09Mb
  - netflix_MX |37.93Mb
  - disney_netflix_US |18.65Mb
  - disney_netflix_JP |11.04Mb
  - disney_netflix_NL |10.50Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_129 |11.36Mb
  - _131 |12.35Mb
  - disney_netflix_NL |35.77Mb
  - disney_netflix_US |58.01Mb
  - ğŸ‡­ğŸ‡°HK_133 |26.76Mb
  - ğŸ‡­ğŸ‡°HK_134 |159.71Mb
  - disney_netflix_US |15.31Mb
  - ğŸ‡ºğŸ‡¸US_139 |42.82Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
