port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: disney_GB |167.35Mb
  server: 172.66.44.230
  type: trojan
  port: 8443
  udp: true
  password: 8r<[9'l6hAO#8ZQi
  sni: Koma-YT.PAGeS.Dev
  ws-opts:
    path: /tro8sFW1S91B6sZrM1?ed=2560
    headers:
      Host: Koma-YT.PAGeS.Dev
  network: ws
- name: disney_GB |159.63Mb
  server: koma-yt.pages.dev
  type: trojan
  port: 8443
  udp: true
  password: 8r<[9'l6hAO#8ZQi
  sni: Koma-YT.PAGeS.Dev
  ws-opts:
    path: /tro8sFW1S91B6sZrM1?ed=2560
    headers:
      Host: Koma-YT.PAGeS.Dev
  network: ws
- name: ðŸ‡²ðŸ‡½MX_420 |38.74Mb
  server: 216.238.89.53
  type: vmess
  country: ðŸ‡²ðŸ‡½MX
  port: 57283
  uuid: 1a5aafc0-6482-451d-fe76-6875b7818579
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_FR |111.02Mb
  server: 208.76.223.218
  type: vmess
  country: ðŸ‡ªðŸ‡¸ES
  port: 40433
  uuid: d8fd8955-78db-49ba-d86f-3e4729f6ac4d
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: _181 |67.75Mb
  server: 43.165.7.71
  type: vmess
  port: 19751
  uuid: 6cfa6103-5d06-40cb-f452-b563db578288
  alterId: 0
  cipher: auto
  network: http
  http-opts:
    method: GET
    path:
    - /
  h2-opts: {}
- name: Relay_ðŸ‡ºðŸ‡¸US-ðŸ‡ºðŸ‡¸US_425 |40.70Mb
  server: 38.14.99.163
  type: vmess
  country: ðŸ‡ºðŸ‡¸US
  port: 59807
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: auto
  network: tcp
  servername: 38.14.99.163
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_-ðŸ‡¯ðŸ‡µJP_320 |11.08Mb
  server: 160.16.117.182
  type: trojan
  port: 3093
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: ðŸ‡·ðŸ‡ºRU_422 |15.08Mb
  server: 45.139.26.173
  type: ss
  country: ðŸ‡·ðŸ‡ºRU
  port: 57456
  password: d3837224ed465f00
  cipher: chacha20-ietf-poly1305
- name: ðŸ‡°ðŸ‡·KR_418 |11.28Mb
  server: 146.56.112.110
  type: vmess
  country: ðŸ‡°ðŸ‡·KR
  port: 8888
  uuid: e7c302f3-90d6-42dd-9d7d-94a3683a3707
  alterId: 0
  cipher: auto
  network: tcp
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_HK |10.07Mb
  server: 58.152.30.120
  type: trojan
  port: 443
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: disney_SG |31.43Mb
  server: 210.87.110.16
  type: vmess
  port: 20297
  uuid: 692c1141-f196-4ac4-8af6-7a3b67304b90
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
- name: ðŸ‡µðŸ‡¹ PT_421 |72.66Mb
  server: 185.231.233.112
  type: ss
  country: ðŸ‡µðŸ‡¹ PT
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
proxy-groups:
- name: ðŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - disney_GB |167.35Mb
  - disney_GB |159.63Mb
  - ðŸ‡²ðŸ‡½MX_420 |38.74Mb
  - disney_netflix_FR |111.02Mb
  - _181 |67.75Mb
  - Relay_ðŸ‡ºðŸ‡¸US-ðŸ‡ºðŸ‡¸US_425 |40.70Mb
  - Relay_-ðŸ‡¯ðŸ‡µJP_320 |11.08Mb
  - ðŸ‡·ðŸ‡ºRU_422 |15.08Mb
  - ðŸ‡°ðŸ‡·KR_418 |11.28Mb
  - disney_HK |10.07Mb
  - disney_SG |31.43Mb
  - ðŸ‡µðŸ‡¹ PT_421 |72.66Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - disney_GB |167.35Mb
  - disney_GB |159.63Mb
  - ðŸ‡²ðŸ‡½MX_420 |38.74Mb
  - disney_netflix_FR |111.02Mb
  - _181 |67.75Mb
  - Relay_ðŸ‡ºðŸ‡¸US-ðŸ‡ºðŸ‡¸US_425 |40.70Mb
  - Relay_-ðŸ‡¯ðŸ‡µJP_320 |11.08Mb
  - ðŸ‡·ðŸ‡ºRU_422 |15.08Mb
  - ðŸ‡°ðŸ‡·KR_418 |11.28Mb
  - disney_HK |10.07Mb
  - disney_SG |31.43Mb
  - ðŸ‡µðŸ‡¹ PT_421 |72.66Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ðŸš€ èŠ‚ç‚¹é€‰æ‹©
