port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: disney_netflix_US |56.33Mb
  server: 45.150.52.40
  type: vmess
  port: 443
  uuid: c31777a1-2ee6-4864-db4c-a79fcbc8188b
  alterId: 0
  cipher: auto
  network: ws
  servername: xsj011-3.facai2024.com
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /c31777a1
- name: disney_netflix_DE |257.56Mb
  server: 85.195.101.122
  type: vmess
  port: 40878
  uuid: f3d4167e-b15e-4e46-82e9-9286ef93fda7
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: disney_HK |57.57Mb
  server: 154.201.76.172
  type: vmess
  port: 20990
  uuid: ba50e1fe-055f-4587-fd0d-36c8d6615192
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: disney_NO |11.70Mb
  server: 107.174.114.71
  type: ss
  port: 443
  password: 595HLF3fHUuw0McM51tpvPygSIB1uf4D
  cipher: chacha20-ietf-poly1305
- name: netflix_CA |35.04Mb
  server: 51.79.102.253
  type: vmess
  port: 80
  uuid: 58fe1542-5290-40ad-815a-77707a81afe5
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /IOebhLMhl1CTbFHbL95myfRX2
    headers:
      Host: wrmelmwxlf.gktevlrqznwqqozy.fabpfs66gizmnojhcvqxwl.kytrcfzqla87gvgvs6c7kjnrubuh.cc
- name: _121 |10.65Mb
  server: 103.127.218.91
  type: vmess
  port: 54693
  uuid: 1cef03ad-6343-408c-8121-cbd1fda2ee9d
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /1cef03ad
- name: disney_netflix_HK |20.48Mb
  server: 8.218.105.196
  type: vmess
  port: 52752
  uuid: 925bdbf5-72be-4437-bebf-441c61089f6b
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
- name: disney_netflix_US |42.40Mb
  server: 163.192.49.195
  type: vmess
  port: 443
  uuid: bcb7c581-3c95-4569-a4e7-918141e91ea3
  alterId: 0
  cipher: auto
  network: http
  http-opts:
    path:
    - /
    headers:
      Host:
      - a.189.cn
  h2-opts: {}
- name: disney_netflix_US |41.72Mb
  server: 172.235.33.114
  type: vmess
  port: 10001
  uuid: 442a3923-eca1-4af0-b3ff-24a7ce0af68f
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: disney_netflix_HK |14.32Mb
  server: 47.242.140.52
  type: vmess
  port: 34815
  uuid: 1a46b66c-6ba9-4e9c-aa0b-0ebac2b69e32
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /arki
- name: disney_netflix_US |27.83Mb
  server: 209.74.82.227
  type: ss
  port: 26515
  udp: true
  password: uA1rLP5m0mMOQ8FcxRXxgr
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_US |28.80Mb
  server: 209.74.82.196
  type: ss
  port: 48918
  udp: true
  password: 8Ij4seif85QQHfLmR0zYkQ
  cipher: chacha20-ietf-poly1305
- name: _167 |28.48Mb
  server: 15.235.41.200
  type: vmess
  port: 80
  uuid: 58fe1542-5290-40ad-815a-77707a81afe5
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /IOebhLMhl1CTbFHbL95myfRX2
- name: disney_netflix_US |39.33Mb
  server: 165.140.216.141
  type: vmess
  port: 443
  uuid: e7d72a8d-26f2-4b54-b366-0c43e0bcba7d
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: disney_netflix_DE |341.74Mb
  server: 91.99.27.55
  type: vmess
  port: 8880
  uuid: f3025961-167b-4f49-e4e3-86505fe980fd
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: disney_netflix_GB |202.38Mb
  server: koma-yt.pages.dev
  type: trojan
  port: 8443
  udp: true
  password: 8r<[9'l6hAO#8ZQi
  sni: Koma-YT.PAGeS.Dev
  ws-opts:
    path: /tro8sFW1S91B6sZrM1?ed=2560
    headers:
      Host: Koma-YT.PAGeS.Dev
  network: ws
- name: netflix_CA |24.45Mb
  server: 38.96.254.102
  type: trojan
  port: 18509
  password: .ie4rghJuMkcf0oF
  sni: shoppingmall.electricbanana.click
- name: netflix_AE |38.95Mb
  server: 89.31.120.192
  type: vmess
  port: 443
  uuid: 44537595-9ccc-4b83-8936-5f9ad3229019
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: netflix_SE |175.76Mb
  server: 70.34.218.149
  type: trojan
  port: 11930
  password: BaeSzHdfJIR13l67
  sni: softpillow.silentrocket.click
- name: Relay_-ðŸ‡¯ðŸ‡µJP_225 |14.61Mb
  server: 160.16.242.183
  type: trojan
  port: 1331
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: Relay_-ðŸ‡¯ðŸ‡µJP_226 |19.28Mb
  server: 153.121.73.102
  type: trojan
  port: 1331
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: _227 |46.21Mb
  server: 160.16.223.205
  type: trojan
  port: 4054
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: _228 |12.17Mb
  server: 160.16.117.182
  type: trojan
  port: 3093
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: _169 |10.65Mb
  server: 54.206.192.9
  type: vmess
  port: 16407
  uuid: 08f45028-1db6-4e93-bf51-d344b6c71e19
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _233 |10.98Mb
  server: 160.16.124.55
  type: trojan
  port: 2890
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: Relay_-ðŸ‡¯ðŸ‡µJP_238 |12.12Mb
  server: 153.121.67.215
  type: trojan
  port: 1331
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: ðŸ‡ªðŸ‡¸ES_246 |29.38Mb
  server: 208.76.223.218
  type: vmess
  country: ðŸ‡ªðŸ‡¸ES
  port: 27092
  uuid: a0596ba6-72a3-4366-8992-77088da65bd8
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_FR |145.15Mb
  server: 208.76.223.218
  type: vmess
  country: ðŸ‡ªðŸ‡¸ES
  port: 40433
  uuid: d8fd8955-78db-49ba-d86f-3e4729f6ac4d
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_-ðŸ‡¯ðŸ‡µJP_240 |12.34Mb
  server: 13.112.81.124
  type: trojan
  port: 3169
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: disney_netflix_NL |237.79Mb
  server: 82.38.31.184
  type: ss
  country: ðŸ‡¬ðŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: _235 |10.96Mb
  server: 58.152.25.20
  type: trojan
  port: 443
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: netflix_JP |19.09Mb
  server: 160.16.229.223
  type: trojan
  port: 3093
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: disney_netflix_NL |141.10Mb
  server: 51.15.17.169
  type: ss
  country: ðŸ‡¬ðŸ‡§GB
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: netflix_IE |409.13Mb
  server: 146.70.90.196
  type: ss
  country: ðŸ‡®ðŸ‡ªIE
  port: 17454
  password: u8gp148iz90ddoo6ms37
  cipher: aes-128-gcm
- name: disney_netflix_US |57.78Mb
  server: 47.253.197.26
  type: vmess
  country: ðŸ‡ºðŸ‡¸US
  port: 12056
  uuid: dd7be7f1-38ff-45e6-f1e5-b20c2190f527
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_HK |28.56Mb
  server: 58.152.110.82
  type: trojan
  port: 443
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: disney_netflix_US |30.45Mb
  server: 209.74.86.194
  type: ss
  country: ðŸ‡ºðŸ‡¸US
  port: 14936
  password: ppgtoOHdm7cszGunBWBTqQ
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_NL |17.97Mb
  server: 109.71.246.210
  type: ss
  country: ðŸ‡·ðŸ‡ºRU
  port: 56689
  password: YQCSKoCF3QazW8YlvDBWA4
  cipher: chacha20-ietf-poly1305
- name: disney_RU |41.56Mb
  server: 81.200.158.206
  type: ss
  country: ðŸ‡·ðŸ‡ºRU
  port: 1080
  password: AqZbt1QCs3ngEfXo1p7T-w
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_US |26.27Mb
  server: 209.74.81.149
  type: ss
  country: ðŸ‡ºðŸ‡¸US
  port: 21166
  password: q92MrrP9oJ3lMEzbQFpyuU
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_US |11.73Mb
  server: cf.fovi.tk
  type: vmess
  country: ðŸZZ
  port: 443
  uuid: bf67437e-6c90-45ca-abc2-c7240a5ce2aa
  alterId: 0
  cipher: auto
  network: ws
  servername: foxlux.fovi.tk
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /eisasqa
    headers:
      HOST: foxlux.fovi.tk
proxy-groups:
- name: ðŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - disney_netflix_US |56.33Mb
  - disney_netflix_DE |257.56Mb
  - disney_HK |57.57Mb
  - disney_NO |11.70Mb
  - netflix_CA |35.04Mb
  - _121 |10.65Mb
  - disney_netflix_HK |20.48Mb
  - disney_netflix_US |42.40Mb
  - disney_netflix_US |41.72Mb
  - disney_netflix_HK |14.32Mb
  - disney_netflix_US |27.83Mb
  - disney_netflix_US |28.80Mb
  - _167 |28.48Mb
  - disney_netflix_US |39.33Mb
  - disney_netflix_DE |341.74Mb
  - disney_netflix_GB |202.38Mb
  - netflix_CA |24.45Mb
  - netflix_AE |38.95Mb
  - netflix_SE |175.76Mb
  - Relay_-ðŸ‡¯ðŸ‡µJP_225 |14.61Mb
  - Relay_-ðŸ‡¯ðŸ‡µJP_226 |19.28Mb
  - _227 |46.21Mb
  - _228 |12.17Mb
  - _169 |10.65Mb
  - _233 |10.98Mb
  - Relay_-ðŸ‡¯ðŸ‡µJP_238 |12.12Mb
  - ðŸ‡ªðŸ‡¸ES_246 |29.38Mb
  - disney_FR |145.15Mb
  - Relay_-ðŸ‡¯ðŸ‡µJP_240 |12.34Mb
  - disney_netflix_NL |237.79Mb
  - _235 |10.96Mb
  - netflix_JP |19.09Mb
  - disney_netflix_NL |141.10Mb
  - netflix_IE |409.13Mb
  - disney_netflix_US |57.78Mb
  - disney_netflix_HK |28.56Mb
  - disney_netflix_US |30.45Mb
  - disney_netflix_NL |17.97Mb
  - disney_RU |41.56Mb
  - disney_netflix_US |26.27Mb
  - disney_netflix_US |11.73Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - disney_netflix_US |56.33Mb
  - disney_netflix_DE |257.56Mb
  - disney_HK |57.57Mb
  - disney_NO |11.70Mb
  - netflix_CA |35.04Mb
  - _121 |10.65Mb
  - disney_netflix_HK |20.48Mb
  - disney_netflix_US |42.40Mb
  - disney_netflix_US |41.72Mb
  - disney_netflix_HK |14.32Mb
  - disney_netflix_US |27.83Mb
  - disney_netflix_US |28.80Mb
  - _167 |28.48Mb
  - disney_netflix_US |39.33Mb
  - disney_netflix_DE |341.74Mb
  - disney_netflix_GB |202.38Mb
  - netflix_CA |24.45Mb
  - netflix_AE |38.95Mb
  - netflix_SE |175.76Mb
  - Relay_-ðŸ‡¯ðŸ‡µJP_225 |14.61Mb
  - Relay_-ðŸ‡¯ðŸ‡µJP_226 |19.28Mb
  - _227 |46.21Mb
  - _228 |12.17Mb
  - _169 |10.65Mb
  - _233 |10.98Mb
  - Relay_-ðŸ‡¯ðŸ‡µJP_238 |12.12Mb
  - ðŸ‡ªðŸ‡¸ES_246 |29.38Mb
  - disney_FR |145.15Mb
  - Relay_-ðŸ‡¯ðŸ‡µJP_240 |12.34Mb
  - disney_netflix_NL |237.79Mb
  - _235 |10.96Mb
  - netflix_JP |19.09Mb
  - disney_netflix_NL |141.10Mb
  - netflix_IE |409.13Mb
  - disney_netflix_US |57.78Mb
  - disney_netflix_HK |28.56Mb
  - disney_netflix_US |30.45Mb
  - disney_netflix_NL |17.97Mb
  - disney_RU |41.56Mb
  - disney_netflix_US |26.27Mb
  - disney_netflix_US |11.73Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ðŸš€ èŠ‚ç‚¹é€‰æ‹©
