port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: netflix_US |23.07Mb
  server: 209.74.82.227
  type: ss
  port: 26515
  udp: true
  password: uA1rLP5m0mMOQ8FcxRXxgr
  cipher: chacha20-ietf-poly1305
- name: netflix_US |27.55Mb
  server: 209.74.82.196
  type: ss
  port: 48918
  udp: true
  password: 8Ij4seif85QQHfLmR0zYkQ
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_GB |60.65Mb
  server: koma-yt.pages.dev
  type: trojan
  port: 8443
  udp: true
  password: 8r<[9'l6hAO#8ZQi
  sni: Koma-YT.PAGeS.Dev
  ws-opts:
    path: /tro8sFW1S91B6sZrM1?ed=2560
    headers:
      Host: Koma-YT.PAGeS.Dev
  network: ws
- name: Relay_-ðŸ‡ºðŸ‡¸US_89 |14.37Mb
  server: v8.hdacd.com
  type: vmess
  port: 30808
  udp: true
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: Relay_-ðŸ‡¸ðŸ‡¬SG_104 |11.19Mb
  server: 160.16.153.13
  type: trojan
  port: 3145
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: netflix_US |43.41Mb
  server: 202.181.103.235
  type: trojan
  port: 2890
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: netflix_US |21.95Mb
  server: 160.16.214.6
  type: trojan
  port: 2890
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: _92 |176.30Mb
  server: 43.165.7.71
  type: vmess
  port: 19751
  uuid: 6cfa6103-5d06-40cb-f452-b563db578288
  alterId: 0
  cipher: auto
  network: http
  http-opts:
    method: GET
    path:
    - /
  h2-opts: {}
- name: netflix_HK |18.08Mb
  server: 8.218.105.196
  type: vmess
  port: 52752
  uuid: 925bdbf5-72be-4437-bebf-441c61089f6b
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
- name: netflix_US |32.06Mb
  server: 209.74.86.194
  type: ss
  country: ðŸ‡ºðŸ‡¸US
  port: 14936
  password: ppgtoOHdm7cszGunBWBTqQ
  cipher: chacha20-ietf-poly1305
- name: netflix_NL |248.88Mb
  server: 51.15.17.169
  type: ss
  country: ðŸ‡¬ðŸ‡§GB
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: netflix_NL |10.00Mb
  server: 82.38.31.184
  type: ss
  country: ðŸ‡¬ðŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: netflix_IE |277.05Mb
  server: 146.70.90.196
  type: ss
  country: ðŸ‡®ðŸ‡ªIE
  port: 17454
  password: u8gp148iz90ddoo6ms37
  cipher: aes-128-gcm
- name: netflix_NL |105.11Mb
  server: 109.71.246.210
  type: ss
  country: ðŸ‡·ðŸ‡ºRU
  port: 56689
  password: YQCSKoCF3QazW8YlvDBWA4
  cipher: chacha20-ietf-poly1305
- name: ðŸ‡¬ðŸ‡·GR_115 |176.75Mb
  server: 192.71.166.100
  type: ss
  country: ðŸ‡¬ðŸ‡·GR
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: netflix_KR |10.51Mb
  server: seoul03.zgjok.com
  type: vmess
  country: ðŸ‡°ðŸ‡·KR
  port: 443
  uuid: 72a0dac4-9689-4a57-b164-5c65bfa94772
  alterId: 0
  cipher: auto
  network: ws
  servername: seoul03.zgjok.com
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /
    headers:
      HOST: seoul03.zgjok.com
- name: disney_netflix_SE |64.60Mb
  server: 91.186.217.246
  type: ss
  country: ðŸ‡ºðŸ‡¸US
  port: 31764
  password: Ftc17VH9ZXQON5vslJCYmv
  cipher: chacha20-ietf-poly1305
- name: netflix_US |31.58Mb
  server: 209.74.81.149
  type: ss
  country: ðŸ‡ºðŸ‡¸US
  port: 21166
  password: q92MrrP9oJ3lMEzbQFpyuU
  cipher: chacha20-ietf-poly1305
proxy-groups:
- name: ðŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - netflix_US |23.07Mb
  - netflix_US |27.55Mb
  - disney_netflix_GB |60.65Mb
  - Relay_-ðŸ‡ºðŸ‡¸US_89 |14.37Mb
  - Relay_-ðŸ‡¸ðŸ‡¬SG_104 |11.19Mb
  - netflix_US |43.41Mb
  - netflix_US |21.95Mb
  - _92 |176.30Mb
  - netflix_HK |18.08Mb
  - netflix_US |32.06Mb
  - netflix_NL |248.88Mb
  - netflix_NL |10.00Mb
  - netflix_IE |277.05Mb
  - netflix_NL |105.11Mb
  - ðŸ‡¬ðŸ‡·GR_115 |176.75Mb
  - netflix_KR |10.51Mb
  - disney_netflix_SE |64.60Mb
  - netflix_US |31.58Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - netflix_US |23.07Mb
  - netflix_US |27.55Mb
  - disney_netflix_GB |60.65Mb
  - Relay_-ðŸ‡ºðŸ‡¸US_89 |14.37Mb
  - Relay_-ðŸ‡¸ðŸ‡¬SG_104 |11.19Mb
  - netflix_US |43.41Mb
  - netflix_US |21.95Mb
  - _92 |176.30Mb
  - netflix_HK |18.08Mb
  - netflix_US |32.06Mb
  - netflix_NL |248.88Mb
  - netflix_NL |10.00Mb
  - netflix_IE |277.05Mb
  - netflix_NL |105.11Mb
  - ðŸ‡¬ðŸ‡·GR_115 |176.75Mb
  - netflix_KR |10.51Mb
  - disney_netflix_SE |64.60Mb
  - netflix_US |31.58Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ðŸš€ èŠ‚ç‚¹é€‰æ‹©
