port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: disney_netflix_US |60.93Mb
  server: 45.150.52.40
  type: vmess
  port: 443
  uuid: c31777a1-2ee6-4864-db4c-a79fcbc8188b
  alterId: 0
  cipher: auto
  network: ws
  servername: xsj011-3.facai2024.com
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /c31777a1
- name: disney_netflix_GB |60.65Mb
  server: koma-yt.pages.dev
  type: trojan
  port: 8443
  udp: true
  password: 8r<[9'l6hAO#8ZQi
  sni: Koma-YT.PAGeS.Dev
  ws-opts:
    path: /tro8sFW1S91B6sZrM1?ed=2560
    headers:
      Host: Koma-YT.PAGeS.Dev
  network: ws
- name: Relay_-ðŸ‡¯ðŸ‡µJP_136 |19.10Mb
  server: 160.16.229.223
  type: trojan
  port: 3093
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: disney_netflix_US |10.87Mb
  server: 202.181.103.235
  type: trojan
  port: 2890
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: disney_netflix_US |10.96Mb
  server: 160.16.214.6
  type: trojan
  port: 2890
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: _106 |24.17Mb
  server: 95.40.113.242
  type: ss
  port: 50005
  udp: true
  password: c5d45d2b-c425-4b24-8794-613b831d5f0c
  cipher: aes-256-gcm
- name: Relay_-ðŸ‡¯ðŸ‡µJP_142 |11.74Mb
  server: 153.121.73.102
  type: trojan
  port: 1331
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: disney_netflix_US |22.58Mb
  server: 209.74.82.196
  type: ss
  port: 48918
  udp: true
  password: 8Ij4seif85QQHfLmR0zYkQ
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_US |18.41Mb
  server: 209.74.82.227
  type: ss
  port: 26515
  udp: true
  password: uA1rLP5m0mMOQ8FcxRXxgr
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_FR |34.28Mb
  server: 208.76.223.218
  type: vmess
  country: ðŸ‡ªðŸ‡¸ES
  port: 40433
  uuid: d8fd8955-78db-49ba-d86f-3e4729f6ac4d
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_-ðŸ‡­ðŸ‡°HK_120 |43.35Mb
  server: v10.hdacd.com
  type: vmess
  port: 30807
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: netflix_NL |359.43Mb
  server: 51.15.17.169
  type: ss
  country: ðŸ‡¬ðŸ‡§GB
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ðŸ‡ºðŸ‡¸US_253 |62.32Mb
  server: 47.253.197.26
  type: vmess
  country: ðŸ‡ºðŸ‡¸US
  port: 12056
  uuid: dd7be7f1-38ff-45e6-f1e5-b20c2190f527
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: _146 |12.00Mb
  server: 58.152.110.82
  type: trojan
  port: 443
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: netflix_IE |239.57Mb
  server: 146.70.90.196
  type: ss
  country: ðŸ‡®ðŸ‡ªIE
  port: 17454
  password: u8gp148iz90ddoo6ms37
  cipher: aes-128-gcm
- name: ðŸ‡¬ðŸ‡§GB_160 |21.08Mb
  server: 195.66.27.148
  type: ss
  country: ðŸ‡¬ðŸ‡§GB
  port: 28709
  password: hShp1Km0NcFSmSigc8ozky
  cipher: chacha20-ietf-poly1305
- name: netflix_NL |105.11Mb
  server: 109.71.246.210
  type: ss
  country: ðŸ‡·ðŸ‡ºRU
  port: 56689
  password: YQCSKoCF3QazW8YlvDBWA4
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_US |25.38Mb
  server: 209.74.86.194
  type: ss
  country: ðŸ‡ºðŸ‡¸US
  port: 14936
  password: ppgtoOHdm7cszGunBWBTqQ
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_US |40.62Mb
  server: 38.14.99.163
  type: vmess
  country: ðŸ‡ºðŸ‡¸US
  port: 59807
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: auto
  network: tcp
  servername: 38.14.99.163
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_SE |66.79Mb
  server: 91.186.217.246
  type: ss
  country: ðŸ‡ºðŸ‡¸US
  port: 31764
  password: Ftc17VH9ZXQON5vslJCYmv
  cipher: chacha20-ietf-poly1305
- name: Relay_-ðŸ‡ºðŸ‡¸US_126 |14.37Mb
  server: v8.hdacd.com
  type: vmess
  port: 30808
  udp: true
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: ðŸ‡ºðŸ‡¸US_252 |14.04Mb
  server: 45.136.12.37
  type: vmess
  country: ðŸ‡ºðŸ‡¸US
  port: 38141
  uuid: fd291be6-b48d-43a1-da38-66c7f80e2f80
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ðŸ‡·ðŸ‡ºRU_239 |45.62Mb
  server: 81.200.158.206
  type: ss
  country: ðŸ‡·ðŸ‡ºRU
  port: 1080
  password: AqZbt1QCs3ngEfXo1p7T-w
  cipher: chacha20-ietf-poly1305
proxy-groups:
- name: ðŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - disney_netflix_US |60.93Mb
  - disney_netflix_GB |60.65Mb
  - Relay_-ðŸ‡¯ðŸ‡µJP_136 |19.10Mb
  - disney_netflix_US |10.87Mb
  - disney_netflix_US |10.96Mb
  - _106 |24.17Mb
  - Relay_-ðŸ‡¯ðŸ‡µJP_142 |11.74Mb
  - disney_netflix_US |22.58Mb
  - disney_netflix_US |18.41Mb
  - disney_netflix_FR |34.28Mb
  - Relay_-ðŸ‡­ðŸ‡°HK_120 |43.35Mb
  - netflix_NL |359.43Mb
  - ðŸ‡ºðŸ‡¸US_253 |62.32Mb
  - _146 |12.00Mb
  - netflix_IE |239.57Mb
  - ðŸ‡¬ðŸ‡§GB_160 |21.08Mb
  - netflix_NL |105.11Mb
  - disney_netflix_US |25.38Mb
  - disney_netflix_US |40.62Mb
  - disney_netflix_SE |66.79Mb
  - Relay_-ðŸ‡ºðŸ‡¸US_126 |14.37Mb
  - ðŸ‡ºðŸ‡¸US_252 |14.04Mb
  - ðŸ‡·ðŸ‡ºRU_239 |45.62Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - disney_netflix_US |60.93Mb
  - disney_netflix_GB |60.65Mb
  - Relay_-ðŸ‡¯ðŸ‡µJP_136 |19.10Mb
  - disney_netflix_US |10.87Mb
  - disney_netflix_US |10.96Mb
  - _106 |24.17Mb
  - Relay_-ðŸ‡¯ðŸ‡µJP_142 |11.74Mb
  - disney_netflix_US |22.58Mb
  - disney_netflix_US |18.41Mb
  - disney_netflix_FR |34.28Mb
  - Relay_-ðŸ‡­ðŸ‡°HK_120 |43.35Mb
  - netflix_NL |359.43Mb
  - ðŸ‡ºðŸ‡¸US_253 |62.32Mb
  - _146 |12.00Mb
  - netflix_IE |239.57Mb
  - ðŸ‡¬ðŸ‡§GB_160 |21.08Mb
  - netflix_NL |105.11Mb
  - disney_netflix_US |25.38Mb
  - disney_netflix_US |40.62Mb
  - disney_netflix_SE |66.79Mb
  - Relay_-ðŸ‡ºðŸ‡¸US_126 |14.37Mb
  - ðŸ‡ºðŸ‡¸US_252 |14.04Mb
  - ðŸ‡·ðŸ‡ºRU_239 |45.62Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ðŸš€ èŠ‚ç‚¹é€‰æ‹©
