port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: disney_MD |310.16Mb
  server: 185.153.197.5
  type: ss
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: netflix_NL |183.93Mb
  server: 151.242.251.137
  type: ss
  port: 8080
  password: o5osZg269v5zHpYjr1xY9s
  cipher: chacha20-ietf-poly1305
- name: _375 |16.70Mb
  server: 103.106.3.82
  type: ss
  port: 443
  udp: true
  password: 4SaCIazlgumYkM8FkPzlmwjpyWBDZFBk
  cipher: chacha20-ietf-poly1305
- name: Relay_-ğŸ‡¯ğŸ‡µJP_450 |20.50Mb
  server: 52.195.176.26
  type: trojan
  port: 2145
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: Relay_-ğŸ‡³ğŸ‡±NL_451 |10.86Mb
  server: 160.16.81.84
  type: trojan
  port: 4054
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¸ğŸ‡¬SG_452 |16.13Mb
  server: 153.121.51.29
  type: trojan
  port: 127
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡³ğŸ‡±NL_454 |14.79Mb
  server: 160.16.236.32
  type: trojan
  port: 4054
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡³ğŸ‡±NL_455 |21.17Mb
  server: 160.16.124.55
  type: trojan
  port: 4054
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: netflix_DE |256.35Mb
  server: 3.123.51.236
  type: trojan
  country: ğŸ‡©ğŸ‡ªDE
  port: 22223
  udp: true
  password: telegram-id-directvpn
  sni: trojan.burgerip.co.uk
  skip-cert-verify: true
- name: disney_HK |23.70Mb
  server: 58.152.25.20
  type: trojan
  port: 443
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: disney_netflix_FR |215.55Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 27092
  uuid: a0596ba6-72a3-4366-8992-77088da65bd8
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡§ğŸ‡·BR_460 |18.70Mb
  server: 38.180.16.86
  type: vmess
  country: ğŸ‡§ğŸ‡·BR
  port: 36104
  uuid: E146A8CB-9D2F-449C-ADCA-8736FB
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_FR |233.27Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 40433
  uuid: d8fd8955-78db-49ba-d86f-3e4729f6ac4d
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡¦ğŸ‡ºAU_459 |11.71Mb
  server: 54.252.240.128
  type: vmess
  country: ğŸ‡¦ğŸ‡ºAU
  port: 1000
  uuid: ca26a9fd-fef8-4ea7-d194-450ce4e0c67a
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: netflix_NL |208.14Mb
  server: 82.38.31.190
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: Relay_-ğŸ‡­ğŸ‡°HK_444 |14.18Mb
  server: v10.hdacd.com
  type: vmess
  port: 30807
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: ğŸ‡²ğŸ‡½MX_490 |37.17Mb
  server: 216.238.89.53
  type: vmess
  country: ğŸ‡²ğŸ‡½MX
  port: 57283
  uuid: 1a5aafc0-6482-451d-fe76-6875b7818579
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡±ğŸ‡¹LT_489 |159.48Mb
  server: 45.87.175.166
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 443
  password: 1RWwXhwfAB5gAEozU4G2Pg
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡­ğŸ‡°HK_475 |29.85Mb
  server: 47.242.140.52
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 48219
  uuid: 006893c6-79b1-4c44-94ff-b8bbea065f1f
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
  ws-opts:
    path: /arki?ed=2048
- name: ğŸ‡­ğŸ‡°HK_485 |23.99Mb
  server: 8.218.116.26
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 32228
  uuid: e4767e9f-ed00-4f31-a984-a918bdd9b09c
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡­ğŸ‡°HK_472 |27.28Mb
  server: 47.243.51.237
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 52801
  uuid: ef93f413-9039-4ddb-aefb-2490287df55a
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
  ws-opts:
    path: /arki?ed=2048
- name: ğŸ‡­ğŸ‡°HK_482 |178.47Mb
  server: 47.242.162.235
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 3787
  uuid: e748fe05-2678-4c31-84c6-14ed825b92b4
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
  ws-opts:
    path: /arki?ed=2048
- name: ğŸ‡·ğŸ‡ºRU_493 |13.42Mb
  server: 45.139.26.173
  type: ss
  country: ğŸ‡·ğŸ‡ºRU
  port: 57456
  password: d3837224ed465f00
  cipher: chacha20-ietf-poly1305
- name: disney_US |15.66Mb
  server: 38.84.201.21
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 53487
  uuid: c3c1ec05-df2c-4975-9b42-e9b007564eb1
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡ºğŸ‡¸US_498 |12.48Mb
  server: pupas-shirting-unsung.freesocks.work
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: p78naCf2EfOlRSLTX0wFVx
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡²ğŸ‡¾MY_491 |30.67Mb
  server: 38.54.98.110
  type: vmess
  country: ğŸ‡²ğŸ‡¾MY
  port: 2052
  uuid: 665d9b8f-153d-4907-adac-de12afd9c851
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: disney_HK |19.51Mb
  server: 45.136.12.37
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 38141
  uuid: fd291be6-b48d-43a1-da38-66c7f80e2f80
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡¸ğŸ‡¬SG_494 |10.81Mb
  server: 68.183.178.131
  type: vmess
  country: ğŸ‡¸ğŸ‡¬SG
  port: 58607
  uuid: c11c32cb-27b3-4afa-c0f3-fb250aa4959e
  alterId: 0
  cipher: auto
  network: ws
  servername: www.12333.monster
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /
    headers:
      HOST: www.12333.monster
- name: netflix_AL |34.88Mb
  server: 87.121.162.249
  type: ss
  country: ğŸ‡­ğŸ‡°HK
  port: 443
  password: JGv616hMWdjfuZ00jYfq7XkBHJZrOBrg
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡­ğŸ‡°HK_480 |83.87Mb
  server: 8.210.134.183
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 3721
  uuid: e72f5c6b-220f-40b3-a115-2d81473458cf
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
  ws-opts:
    path: /
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - disney_MD |310.16Mb
  - netflix_NL |183.93Mb
  - _375 |16.70Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_450 |20.50Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_451 |10.86Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_452 |16.13Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_454 |14.79Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_455 |21.17Mb
  - netflix_DE |256.35Mb
  - disney_HK |23.70Mb
  - disney_netflix_FR |215.55Mb
  - ğŸ‡§ğŸ‡·BR_460 |18.70Mb
  - disney_netflix_FR |233.27Mb
  - ğŸ‡¦ğŸ‡ºAU_459 |11.71Mb
  - netflix_NL |208.14Mb
  - Relay_-ğŸ‡­ğŸ‡°HK_444 |14.18Mb
  - ğŸ‡²ğŸ‡½MX_490 |37.17Mb
  - ğŸ‡±ğŸ‡¹LT_489 |159.48Mb
  - ğŸ‡­ğŸ‡°HK_475 |29.85Mb
  - ğŸ‡­ğŸ‡°HK_485 |23.99Mb
  - ğŸ‡­ğŸ‡°HK_472 |27.28Mb
  - ğŸ‡­ğŸ‡°HK_482 |178.47Mb
  - ğŸ‡·ğŸ‡ºRU_493 |13.42Mb
  - disney_US |15.66Mb
  - ğŸ‡ºğŸ‡¸US_498 |12.48Mb
  - ğŸ‡²ğŸ‡¾MY_491 |30.67Mb
  - disney_HK |19.51Mb
  - ğŸ‡¸ğŸ‡¬SG_494 |10.81Mb
  - netflix_AL |34.88Mb
  - ğŸ‡­ğŸ‡°HK_480 |83.87Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - disney_MD |310.16Mb
  - netflix_NL |183.93Mb
  - _375 |16.70Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_450 |20.50Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_451 |10.86Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_452 |16.13Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_454 |14.79Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_455 |21.17Mb
  - netflix_DE |256.35Mb
  - disney_HK |23.70Mb
  - disney_netflix_FR |215.55Mb
  - ğŸ‡§ğŸ‡·BR_460 |18.70Mb
  - disney_netflix_FR |233.27Mb
  - ğŸ‡¦ğŸ‡ºAU_459 |11.71Mb
  - netflix_NL |208.14Mb
  - Relay_-ğŸ‡­ğŸ‡°HK_444 |14.18Mb
  - ğŸ‡²ğŸ‡½MX_490 |37.17Mb
  - ğŸ‡±ğŸ‡¹LT_489 |159.48Mb
  - ğŸ‡­ğŸ‡°HK_475 |29.85Mb
  - ğŸ‡­ğŸ‡°HK_485 |23.99Mb
  - ğŸ‡­ğŸ‡°HK_472 |27.28Mb
  - ğŸ‡­ğŸ‡°HK_482 |178.47Mb
  - ğŸ‡·ğŸ‡ºRU_493 |13.42Mb
  - disney_US |15.66Mb
  - ğŸ‡ºğŸ‡¸US_498 |12.48Mb
  - ğŸ‡²ğŸ‡¾MY_491 |30.67Mb
  - disney_HK |19.51Mb
  - ğŸ‡¸ğŸ‡¬SG_494 |10.81Mb
  - netflix_AL |34.88Mb
  - ğŸ‡­ğŸ‡°HK_480 |83.87Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
