port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: ' |71.89Mb'
  server: 185.82.73.212
  type: ss
  port: 8444
  udp: true
  password: _bypfvq6ra7g4n5yCCR9DoVeGya2XUUS
  cipher: chacha20-ietf-poly1305
- name: ' |422.92Mb'
  server: 45.14.245.2
  type: ss
  port: 443
  password: 17ZDORWIliQHuO6WRGHChXYMzdRtAYVP
  cipher: chacha20-ietf-poly1305
- name: ' |146.69Mb'
  server: 82.38.31.199
  type: ss
  port: 8080
  udp: true
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ' |119.14Mb'
  server: 103.149.183.80
  type: ss
  port: 8388
  udp: true
  password: asd123456
  cipher: chacha20-ietf
- name: ' |11.32Mb'
  server: 103.149.183.200
  type: ss
  port: 8388
  udp: true
  password: asd123456
  cipher: chacha20-ietf
- name: ' |70.03Mb'
  server: 194.59.183.134
  type: ss
  port: 46114
  udp: true
  password: lejSRyqa033OEPmEQsvRsl
  cipher: chacha20-ietf-poly1305
- name: ' |420.28Mb'
  server: 46.183.184.60
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ' |69.86Mb'
  server: 145.249.109.121
  type: ss
  port: 25512
  udp: true
  password: smSMfR9jqLgMkHuQtxSIWh
  cipher: chacha20-ietf-poly1305
- name: ' |18.05Mb'
  server: 38.165.233.93
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ' |43.43Mb'
  server: 91.221.37.30
  type: ss
  port: 1234
  udp: true
  password: cPzFh2p9MWXvVYWs5hX55e5BZFty7ke-
  cipher: chacha20-ietf-poly1305
- name: ' |13.65Mb'
  server: 160.16.117.182
  type: trojan
  port: 3093
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: ' |18.71Mb'
  server: 153.121.45.139
  type: trojan
  port: 3093
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: ' |37.01Mb'
  server: 160.16.136.130
  type: trojan
  port: 2890
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: ' |11.01Mb'
  server: 160.16.131.243
  type: trojan
  port: 2760
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
  skip-cert-verify: true
- name: ' |10.36Mb'
  server: 160.16.132.158
  type: trojan
  port: 1507
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: ' |10.68Mb'
  server: 160.16.153.13
  type: trojan
  port: 3145
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: ğŸ‡ºğŸ‡¸US |40.25Mb
  server: 38.14.99.163
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 59807
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: auto
  network: tcp
  servername: 38.14.99.163
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ' |10.72Mb'
  server: 160.16.196.59
  type: trojan
  port: 1507
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: ' |30.05Mb'
  server: 112.118.116.178
  type: trojan
  port: 443
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: ' |43.59Mb'
  server: 160.16.204.136
  type: trojan
  port: 2890
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: ğŸ‡²ğŸ‡½MX |41.84Mb
  server: 216.238.87.47
  type: vmess
  country: ğŸ‡²ğŸ‡½MX
  port: 27502
  uuid: b8155ce4-7e08-4c40-800f-8671312b7124
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡ºğŸ‡¸US |70.55Mb
  server: 205.209.109.194
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 17277
  password: d2fkgzsdu5sturjs8f19
  cipher: aes-128-gcm
- name: ' |60.15Mb'
  server: 47.253.197.26
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 12056
  uuid: dd7be7f1-38ff-45e6-f1e5-b20c2190f527
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡­ğŸ‡°HK |117.64Mb
  server: 8.218.116.26
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 32228
  uuid: e4767e9f-ed00-4f31-a984-a918bdd9b09c
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸZZ |35.43Mb
  server: cf.fovi.tk
  type: vmess
  country: ğŸZZ
  port: 443
  uuid: bf67437e-6c90-45ca-abc2-c7240a5ce2aa
  alterId: 0
  cipher: auto
  network: ws
  servername: foxlux.fovi.tk
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /eisasqa
    headers:
      HOST: foxlux.fovi.tk
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - ' |71.89Mb'
  - ' |422.92Mb'
  - ' |146.69Mb'
  - ' |119.14Mb'
  - ' |11.32Mb'
  - ' |70.03Mb'
  - ' |420.28Mb'
  - ' |69.86Mb'
  - ' |18.05Mb'
  - ' |43.43Mb'
  - ' |13.65Mb'
  - ' |18.71Mb'
  - ' |37.01Mb'
  - ' |11.01Mb'
  - ' |10.36Mb'
  - ' |10.68Mb'
  - ğŸ‡ºğŸ‡¸US |40.25Mb
  - ' |10.72Mb'
  - ' |30.05Mb'
  - ' |43.59Mb'
  - ğŸ‡²ğŸ‡½MX |41.84Mb
  - ğŸ‡ºğŸ‡¸US |70.55Mb
  - ' |60.15Mb'
  - ğŸ‡­ğŸ‡°HK |117.64Mb
  - ğŸZZ |35.43Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - ' |71.89Mb'
  - ' |422.92Mb'
  - ' |146.69Mb'
  - ' |119.14Mb'
  - ' |11.32Mb'
  - ' |70.03Mb'
  - ' |420.28Mb'
  - ' |69.86Mb'
  - ' |18.05Mb'
  - ' |43.43Mb'
  - ' |13.65Mb'
  - ' |18.71Mb'
  - ' |37.01Mb'
  - ' |11.01Mb'
  - ' |10.36Mb'
  - ' |10.68Mb'
  - ğŸ‡ºğŸ‡¸US |40.25Mb
  - ' |10.72Mb'
  - ' |30.05Mb'
  - ' |43.59Mb'
  - ğŸ‡²ğŸ‡½MX |41.84Mb
  - ğŸ‡ºğŸ‡¸US |70.55Mb
  - ' |60.15Mb'
  - ğŸ‡­ğŸ‡°HK |117.64Mb
  - ğŸZZ |35.43Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
