port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: _206 |12.29Mb
  server: 194.59.183.134
  type: ss
  port: 46114
  udp: true
  password: lejSRyqa033OEPmEQsvRsl
  cipher: chacha20-ietf-poly1305
- name: _211 |170.18Mb
  server: 145.249.109.121
  type: ss
  port: 25512
  udp: true
  password: smSMfR9jqLgMkHuQtxSIWh
  cipher: chacha20-ietf-poly1305
- name: _203 |546.27Mb
  server: 46.183.184.60
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: disney_PY |17.61Mb
  server: 38.165.233.93
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: _216 |113.91Mb
  server: 47.242.145.160
  type: vmess
  port: 44457
  uuid: 40290609-2743-4d85-c9c3-4c72dd151b9f
  alterId: 0
  cipher: auto
  network: http
  http-opts:
    method: GET
    path:
    - /
  h2-opts: {}
- name: _217 |108.49Mb
  server: 149.88.95.94
  type: vmess
  port: 18937
  uuid: ebaa1ae1-fa4d-40d8-958f-d4524d551218
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
- name: _214 |166.67Mb
  server: 103.149.182.158
  type: ss
  port: 8388
  password: asd123456
  cipher: chacha20-ietf
- name: Pool__225 |116.62Mb
  server: 149.88.95.217
  type: vmess
  port: 18937
  uuid: ebaa1ae1-fa4d-40d8-958f-d4524d551218
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
- name: _221 |116.28Mb
  server: 149.88.95.94
  type: vmess
  port: 35760
  uuid: 17e96792-d8c3-4741-9c34-e5d1c11d754f
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
- name: _228 |19.60Mb
  server: 149.88.95.94
  type: vmess
  port: 40741
  uuid: 1b8a751b-4909-4fec-f019-907d92e6c47f
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
- name: Relay_-ğŸ‡¯ğŸ‡µJP_231 |20.64Mb
  server: 160.16.87.174
  type: trojan
  port: 3169
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: ğŸ‡²ğŸ‡½MX_253 |41.63Mb
  server: 216.238.87.47
  type: vmess
  country: ğŸ‡²ğŸ‡½MX
  port: 27502
  uuid: b8155ce4-7e08-4c40-800f-8671312b7124
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_-ğŸ‡¯ğŸ‡µJP_232 |19.04Mb
  server: 160.16.117.182
  type: trojan
  port: 3169
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¯ğŸ‡µJP_233 |22.87Mb
  server: 153.121.45.139
  type: trojan
  port: 3093
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¯ğŸ‡µJP_239 |18.35Mb
  server: 160.16.117.182
  type: trojan
  port: 3093
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: disney_netflix_US |38.56Mb
  server: 38.14.99.163
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 59807
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: auto
  network: tcp
  servername: 38.14.99.163
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_-ğŸ‡¯ğŸ‡µJP_241 |20.02Mb
  server: 160.16.72.33
  type: trojan
  port: 3093
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_258 |20.49Mb
  server: gy3.hdcloud.link
  type: trojan
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  udp: true
  password: 168f29a7-6922-4558-8296-61a69cf6a5a2
  network: grpc
  grpc-opts:
    grpc-service-name: GunService
- name: disney_HK |16.80Mb
  server: 45.207.157.29
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 13852
  uuid: 845764df-ecb3-4b13-bed2-bf1551b68e9a
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_ğŸZZ-ğŸ‡®ğŸ‡·IR_259 |12.19Mb
  server: cf.fovi.tk
  type: vmess
  country: ğŸZZ
  port: 443
  uuid: bf67437e-6c90-45ca-abc2-c7240a5ce2aa
  alterId: 0
  cipher: auto
  network: ws
  servername: foxlux.fovi.tk
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /eisasqa
    headers:
      HOST: foxlux.fovi.tk
- name: netflix_NL |69.79Mb
  server: 45.14.245.2
  type: ss
  port: 443
  password: 17ZDORWIliQHuO6WRGHChXYMzdRtAYVP
  cipher: chacha20-ietf-poly1305
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - _206 |12.29Mb
  - _211 |170.18Mb
  - _203 |546.27Mb
  - disney_PY |17.61Mb
  - _216 |113.91Mb
  - _217 |108.49Mb
  - _214 |166.67Mb
  - Pool__225 |116.62Mb
  - _221 |116.28Mb
  - _228 |19.60Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_231 |20.64Mb
  - ğŸ‡²ğŸ‡½MX_253 |41.63Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_232 |19.04Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_233 |22.87Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_239 |18.35Mb
  - disney_netflix_US |38.56Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_241 |20.02Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_258 |20.49Mb
  - disney_HK |16.80Mb
  - Relay_ğŸZZ-ğŸ‡®ğŸ‡·IR_259 |12.19Mb
  - netflix_NL |69.79Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - _206 |12.29Mb
  - _211 |170.18Mb
  - _203 |546.27Mb
  - disney_PY |17.61Mb
  - _216 |113.91Mb
  - _217 |108.49Mb
  - _214 |166.67Mb
  - Pool__225 |116.62Mb
  - _221 |116.28Mb
  - _228 |19.60Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_231 |20.64Mb
  - ğŸ‡²ğŸ‡½MX_253 |41.63Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_232 |19.04Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_233 |22.87Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_239 |18.35Mb
  - disney_netflix_US |38.56Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_241 |20.02Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_258 |20.49Mb
  - disney_HK |16.80Mb
  - Relay_ğŸZZ-ğŸ‡®ğŸ‡·IR_259 |12.19Mb
  - netflix_NL |69.79Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
