port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: disney_netflix_US |43.39Mb
  server: 88.210.36.106
  type: ss
  port: 2377
  udp: true
  password: t0srmdxrm3xyjnvqz9ewlxb2myq7rjuv
  cipher: chacha20-ietf-poly1305
  plugin: obfs
  plugin-opts:
    host: (TG @WangCai2)e7b7ab7:102816
    mode: tls
- name: disney_netflix_US |44.14Mb
  server: 88.210.36.108
  type: ss
  port: 2377
  udp: true
  password: t0srmdxrm3xyjnvqz9ewlxb2myq7rjuv
  cipher: chacha20-ietf-poly1305
  plugin: obfs
  plugin-opts:
    host: (TG @WangCai2)e7b7ab7:102816
    mode: tls
- name: disney_netflix_US |43.62Mb
  server: 88.210.36.107
  type: ss
  port: 2377
  udp: true
  password: t0srmdxrm3xyjnvqz9ewlxb2myq7rjuv
  cipher: chacha20-ietf-poly1305
  plugin: obfs
  plugin-opts:
    host: (TG @WangCai2)e7b7ab7:102816
    mode: tls
- name: disney_netflix_US |43.78Mb
  server: 88.210.36.109
  type: ss
  port: 2377
  udp: true
  password: t0srmdxrm3xyjnvqz9ewlxb2myq7rjuv
  cipher: chacha20-ietf-poly1305
  plugin: obfs
  plugin-opts:
    host: (TG @WangCai2)e7b7ab7:102816
    mode: tls
- name: Relay_-ğŸ‡ºğŸ‡¸US_154 |252.22Mb
  server: 82.198.246.97
  type: vmess
  port: 180
  uuid: d13fc2f5-3e05-4795-81eb-44143a09e552
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: disney_netflix_NL |307.80Mb
  server: 45.14.245.2
  type: ss
  port: 443
  password: 17ZDORWIliQHuO6WRGHChXYMzdRtAYVP
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_NL |10.61Mb
  server: 82.38.31.179
  type: ss
  port: 8080
  udp: true
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_PY |17.89Mb
  server: 38.165.233.93
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: disney_netflix_US |19.83Mb
  server: 160.16.204.136
  type: trojan
  port: 2890
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: _167 |15.10Mb
  server: 202.181.103.246
  type: trojan
  port: 4054
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¸ğŸ‡¬SG_169 |18.83Mb
  server: 160.16.196.59
  type: trojan
  port: 1507
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: _150 |54.71Mb
  server: 185.82.73.212
  type: ss
  port: 8444
  udp: true
  password: _bypfvq6ra7g4n5yCCR9DoVeGya2XUUS
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_DE |234.26Mb
  server: 45.80.188.48
  type: vmess
  port: 50255
  uuid: bc140c02-25a9-4feb-96bb-7d772b17fd17
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
- name: netflix_MX |134.42Mb
  server: 216.238.87.47
  type: vmess
  country: ğŸ‡²ğŸ‡½MX
  port: 27502
  uuid: b8155ce4-7e08-4c40-800f-8671312b7124
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: _171 |12.35Mb
  server: 160.16.57.238
  type: trojan
  port: 4054
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: disney_netflix_US |70.98Mb
  server: 205.209.109.194
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 17277
  password: d2fkgzsdu5sturjs8f19
  cipher: aes-128-gcm
- name: _172 |10.97Mb
  server: 160.16.131.243
  type: trojan
  port: 2760
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
  skip-cert-verify: true
- name: _176 |10.86Mb
  server: 160.16.116.227
  type: trojan
  port: 2760
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
  skip-cert-verify: true
- name: disney_HK |26.90Mb
  server: 112.118.116.178
  type: trojan
  port: 443
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: _168 |10.17Mb
  server: 219.79.214.159
  type: trojan
  port: 443
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: Relay_ğŸZZ-ğŸ‡®ğŸ‡·IR_189 |30.09Mb
  server: cf.fovi.tk
  type: vmess
  country: ğŸZZ
  port: 443
  uuid: bf67437e-6c90-45ca-abc2-c7240a5ce2aa
  alterId: 0
  cipher: auto
  network: ws
  servername: foxlux.fovi.tk
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /eisasqa
    headers:
      HOST: foxlux.fovi.tk
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - disney_netflix_US |43.39Mb
  - disney_netflix_US |44.14Mb
  - disney_netflix_US |43.62Mb
  - disney_netflix_US |43.78Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_154 |252.22Mb
  - disney_netflix_NL |307.80Mb
  - disney_netflix_NL |10.61Mb
  - disney_netflix_PY |17.89Mb
  - disney_netflix_US |19.83Mb
  - _167 |15.10Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_169 |18.83Mb
  - _150 |54.71Mb
  - disney_netflix_DE |234.26Mb
  - netflix_MX |134.42Mb
  - _171 |12.35Mb
  - disney_netflix_US |70.98Mb
  - _172 |10.97Mb
  - _176 |10.86Mb
  - disney_HK |26.90Mb
  - _168 |10.17Mb
  - Relay_ğŸZZ-ğŸ‡®ğŸ‡·IR_189 |30.09Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - disney_netflix_US |43.39Mb
  - disney_netflix_US |44.14Mb
  - disney_netflix_US |43.62Mb
  - disney_netflix_US |43.78Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_154 |252.22Mb
  - disney_netflix_NL |307.80Mb
  - disney_netflix_NL |10.61Mb
  - disney_netflix_PY |17.89Mb
  - disney_netflix_US |19.83Mb
  - _167 |15.10Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_169 |18.83Mb
  - _150 |54.71Mb
  - disney_netflix_DE |234.26Mb
  - netflix_MX |134.42Mb
  - _171 |12.35Mb
  - disney_netflix_US |70.98Mb
  - _172 |10.97Mb
  - _176 |10.86Mb
  - disney_HK |26.90Mb
  - _168 |10.17Mb
  - Relay_ğŸZZ-ğŸ‡®ğŸ‡·IR_189 |30.09Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
