port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: netflix_DE |237.62Mb
  server: 43.165.7.71
  type: vmess
  port: 19751
  uuid: 6cfa6103-5d06-40cb-f452-b563db578288
  alterId: 0
  cipher: auto
  network: http
  http-opts:
    method: GET
    path:
    - /
  h2-opts: {}
- name: disney_netflix_GB |202.38Mb
  server: koma-yt.pages.dev
  type: trojan
  port: 8443
  udp: true
  password: 8r<[9'l6hAO#8ZQi
  sni: Koma-YT.PAGeS.Dev
  ws-opts:
    path: /tro8sFW1S91B6sZrM1?ed=2560
    headers:
      Host: Koma-YT.PAGeS.Dev
  network: ws
- name: disney_netflix_HK |13.28Mb
  server: 8.218.105.196
  type: vmess
  port: 52752
  uuid: 925bdbf5-72be-4437-bebf-441c61089f6b
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
- name: disney_netflix_HK |17.07Mb
  server: 58.152.110.82
  type: trojan
  port: 443
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: disney_US |361.32Mb
  server: 185.221.23.251
  type: vmess
  country: ðŸ‡ªðŸ‡¸ES
  port: 29431
  uuid: 8b78363e-3c3a-44ab-f0d8-f13d950c8572
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_US |21.07Mb
  server: 209.74.82.196
  type: ss
  port: 48918
  udp: true
  password: 8Ij4seif85QQHfLmR0zYkQ
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_US |20.76Mb
  server: 209.74.82.227
  type: ss
  port: 26515
  udp: true
  password: uA1rLP5m0mMOQ8FcxRXxgr
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_US |12.18Mb
  server: 202.181.103.235
  type: trojan
  port: 2890
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: ðŸ‡ªðŸ‡¸ES_110 |145.15Mb
  server: 208.76.223.218
  type: vmess
  country: ðŸ‡ªðŸ‡¸ES
  port: 40433
  uuid: d8fd8955-78db-49ba-d86f-3e4729f6ac4d
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_-ðŸ‡­ðŸ‡°HK_94 |12.30Mb
  server: v10.hdacd.com
  type: vmess
  port: 30807
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: netflix_IE |242.33Mb
  server: 146.70.90.196
  type: ss
  country: ðŸ‡®ðŸ‡ªIE
  port: 17454
  password: u8gp148iz90ddoo6ms37
  cipher: aes-128-gcm
- name: netflix_NL |410.03Mb
  server: 51.15.17.169
  type: ss
  country: ðŸ‡¬ðŸ‡§GB
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: disney_netflix_US |11.46Mb
  server: 160.16.214.6
  type: trojan
  port: 2890
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: netflix_NL |105.11Mb
  server: 109.71.246.210
  type: ss
  country: ðŸ‡·ðŸ‡ºRU
  port: 56689
  password: YQCSKoCF3QazW8YlvDBWA4
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_US |34.04Mb
  server: 209.74.86.194
  type: ss
  country: ðŸ‡ºðŸ‡¸US
  port: 14936
  password: ppgtoOHdm7cszGunBWBTqQ
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_HK |19.66Mb
  server: 58.152.25.242
  type: trojan
  port: 443
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: netflix_KR |18.04Mb
  server: 146.56.112.110
  type: vmess
  country: ðŸ‡°ðŸ‡·KR
  port: 8888
  uuid: e7c302f3-90d6-42dd-9d7d-94a3683a3707
  alterId: 0
  cipher: auto
  network: tcp
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_ðŸ‡°ðŸ‡·KR-ðŸ‡°ðŸ‡·KR_158 |10.38Mb
  server: seoul03.zgjok.com
  type: vmess
  country: ðŸ‡°ðŸ‡·KR
  port: 443
  uuid: 72a0dac4-9689-4a57-b164-5c65bfa94772
  alterId: 0
  cipher: auto
  network: ws
  servername: seoul03.zgjok.com
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /
    headers:
      HOST: seoul03.zgjok.com
- name: disney_netflix_US |25.15Mb
  server: 209.74.81.149
  type: ss
  country: ðŸ‡ºðŸ‡¸US
  port: 21166
  password: q92MrrP9oJ3lMEzbQFpyuU
  cipher: chacha20-ietf-poly1305
- name: ðŸ‡¬ðŸ‡§GB_113 |32.98Mb
  server: 195.66.27.148
  type: ss
  country: ðŸ‡¬ðŸ‡§GB
  port: 28709
  password: hShp1Km0NcFSmSigc8ozky
  cipher: chacha20-ietf-poly1305
proxy-groups:
- name: ðŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - netflix_DE |237.62Mb
  - disney_netflix_GB |202.38Mb
  - disney_netflix_HK |13.28Mb
  - disney_netflix_HK |17.07Mb
  - disney_US |361.32Mb
  - disney_netflix_US |21.07Mb
  - disney_netflix_US |20.76Mb
  - disney_netflix_US |12.18Mb
  - ðŸ‡ªðŸ‡¸ES_110 |145.15Mb
  - Relay_-ðŸ‡­ðŸ‡°HK_94 |12.30Mb
  - netflix_IE |242.33Mb
  - netflix_NL |410.03Mb
  - disney_netflix_US |11.46Mb
  - netflix_NL |105.11Mb
  - disney_netflix_US |34.04Mb
  - disney_netflix_HK |19.66Mb
  - netflix_KR |18.04Mb
  - Relay_ðŸ‡°ðŸ‡·KR-ðŸ‡°ðŸ‡·KR_158 |10.38Mb
  - disney_netflix_US |25.15Mb
  - ðŸ‡¬ðŸ‡§GB_113 |32.98Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - netflix_DE |237.62Mb
  - disney_netflix_GB |202.38Mb
  - disney_netflix_HK |13.28Mb
  - disney_netflix_HK |17.07Mb
  - disney_US |361.32Mb
  - disney_netflix_US |21.07Mb
  - disney_netflix_US |20.76Mb
  - disney_netflix_US |12.18Mb
  - ðŸ‡ªðŸ‡¸ES_110 |145.15Mb
  - Relay_-ðŸ‡­ðŸ‡°HK_94 |12.30Mb
  - netflix_IE |242.33Mb
  - netflix_NL |410.03Mb
  - disney_netflix_US |11.46Mb
  - netflix_NL |105.11Mb
  - disney_netflix_US |34.04Mb
  - disney_netflix_HK |19.66Mb
  - netflix_KR |18.04Mb
  - Relay_ðŸ‡°ðŸ‡·KR-ðŸ‡°ðŸ‡·KR_158 |10.38Mb
  - disney_netflix_US |25.15Mb
  - ðŸ‡¬ðŸ‡§GB_113 |32.98Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ðŸš€ èŠ‚ç‚¹é€‰æ‹©
