port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: disney_netflix_US |40.80Mb
  server: 38.14.99.179
  type: vmess
  port: 59807
  udp: true
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_NL |195.32Mb
  server: 151.242.251.137
  type: ss
  port: 8080
  password: o5osZg269v5zHpYjr1xY9s
  cipher: chacha20-ietf-poly1305
- name: Relay_-ğŸ‡¯ğŸ‡µJP_515 |17.08Mb
  server: 153.121.65.107
  type: trojan
  port: 1331
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: _423 |52.05Mb
  server: 152.70.92.69
  type: vmess
  port: 80
  uuid: bb9c3993-a4b9-4dad-aeb9-ac86371ae68b
  alterId: 0
  cipher: auto
  network: http
  http-opts:
    path:
    - /
  h2-opts: {}
- name: disney_HK |74.44Mb
  server: 58.152.30.120
  type: trojan
  port: 443
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: Relay_-ğŸ‡¯ğŸ‡µJP_519 |10.04Mb
  server: 160.16.87.174
  type: trojan
  port: 3169
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: ğŸ‡§ğŸ‡·BR_522 |11.85Mb
  server: 38.180.16.86
  type: vmess
  country: ğŸ‡§ğŸ‡·BR
  port: 36104
  uuid: E146A8CB-9D2F-449C-ADCA-8736FB
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_HK |81.89Mb
  server: 58.152.25.20
  type: trojan
  port: 443
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: disney_HK |75.07Mb
  server: 58.152.53.8
  type: trojan
  port: 443
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: disney_FR |97.40Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 40433
  uuid: d8fd8955-78db-49ba-d86f-3e4729f6ac4d
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_NL |216.84Mb
  server: 82.38.31.210
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_NL |110.26Mb
  server: 82.38.31.190
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_NL |247.04Mb
  server: 82.38.31.218
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_FR |183.12Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 27092
  uuid: a0596ba6-72a3-4366-8992-77088da65bd8
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡­ğŸ‡°HK_539 |128.30Mb
  server: 47.242.140.52
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 48219
  uuid: 006893c6-79b1-4c44-94ff-b8bbea065f1f
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
  ws-opts:
    path: /arki?ed=2048
- name: ğŸ‡­ğŸ‡°HK_554 |123.27Mb
  server: 8.218.116.26
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 32228
  uuid: e4767e9f-ed00-4f31-a984-a918bdd9b09c
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_HK |75.67Mb
  server: 219.79.186.107
  type: trojan
  country: ğŸ‡­ğŸ‡°HK
  port: 443
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: ğŸ‡²ğŸ‡½MX_594 |39.07Mb
  server: 216.238.89.53
  type: vmess
  country: ğŸ‡²ğŸ‡½MX
  port: 57283
  uuid: 1a5aafc0-6482-451d-fe76-6875b7818579
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_ğŸ‡­ğŸ‡°HK-ğŸ‡ºğŸ‡¸US_545 |57.13Mb
  server: v24.hdacd.com
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 30824
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: auto
  network: tcp
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡®ğŸ‡³IN_588 |124.27Mb
  server: 134.209.147.198
  type: ss
  country: ğŸ‡®ğŸ‡³IN
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ğŸ‡°ğŸ‡·KR_593 |11.74Mb
  server: 146.56.112.110
  type: vmess
  country: ğŸ‡°ğŸ‡·KR
  port: 8888
  uuid: e7c302f3-90d6-42dd-9d7d-94a3683a3707
  alterId: 0
  cipher: auto
  network: tcp
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_US |42.29Mb
  server: 104.192.226.106
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: disney_netflix_NL |65.83Mb
  server: 109.71.246.210
  type: ss
  country: ğŸ‡·ğŸ‡ºRU
  port: 56689
  password: YQCSKoCF3QazW8YlvDBWA4
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸ‡°ğŸ‡·KR-ğŸ‡°ğŸ‡·KR_592 |10.16Mb
  server: seoul03.zgjok.com
  type: vmess
  country: ğŸ‡°ğŸ‡·KR
  port: 443
  uuid: 72a0dac4-9689-4a57-b164-5c65bfa94772
  alterId: 0
  cipher: auto
  network: ws
  servername: seoul03.zgjok.com
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /
    headers:
      HOST: seoul03.zgjok.com
- name: disney_netflix_US |40.95Mb
  server: 38.14.99.163
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 59807
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: auto
  network: tcp
  servername: 38.14.99.163
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: netflix_LU |190.23Mb
  server: 45.12.144.18
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: LQyAUItafUmmO3EZZx9UbiX6IGydSBgL
  cipher: chacha20-ietf-poly1305
- name: netflix_LT |98.32Mb
  server: 45.12.136.170
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: l668XHPejoSNNuD66BYzyehaCpZexiF7
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡²ğŸ‡¾MY_595 |29.39Mb
  server: 38.54.98.110
  type: vmess
  country: ğŸ‡²ğŸ‡¾MY
  port: 2052
  uuid: 665d9b8f-153d-4907-adac-de12afd9c851
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: ğŸ‡¸ğŸ‡¬SG_599 |11.32Mb
  server: 68.183.178.131
  type: vmess
  country: ğŸ‡¸ğŸ‡¬SG
  port: 58607
  uuid: c11c32cb-27b3-4afa-c0f3-fb250aa4959e
  alterId: 0
  cipher: auto
  network: ws
  servername: www.12333.monster
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /
    headers:
      HOST: www.12333.monster
- name: Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡§ğŸ‡¬BG_644 |333.18Mb
  server: clr.ducks.tel
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 17844
  password: '907560230'
  cipher: chacha20-ietf-poly1305
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - disney_netflix_US |40.80Mb
  - disney_netflix_NL |195.32Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_515 |17.08Mb
  - _423 |52.05Mb
  - disney_HK |74.44Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_519 |10.04Mb
  - ğŸ‡§ğŸ‡·BR_522 |11.85Mb
  - disney_HK |81.89Mb
  - disney_HK |75.07Mb
  - disney_FR |97.40Mb
  - disney_netflix_NL |216.84Mb
  - disney_netflix_NL |110.26Mb
  - disney_netflix_NL |247.04Mb
  - disney_netflix_FR |183.12Mb
  - ğŸ‡­ğŸ‡°HK_539 |128.30Mb
  - ğŸ‡­ğŸ‡°HK_554 |123.27Mb
  - disney_HK |75.67Mb
  - ğŸ‡²ğŸ‡½MX_594 |39.07Mb
  - Relay_ğŸ‡­ğŸ‡°HK-ğŸ‡ºğŸ‡¸US_545 |57.13Mb
  - ğŸ‡®ğŸ‡³IN_588 |124.27Mb
  - ğŸ‡°ğŸ‡·KR_593 |11.74Mb
  - disney_netflix_US |42.29Mb
  - disney_netflix_NL |65.83Mb
  - Relay_ğŸ‡°ğŸ‡·KR-ğŸ‡°ğŸ‡·KR_592 |10.16Mb
  - disney_netflix_US |40.95Mb
  - netflix_LU |190.23Mb
  - netflix_LT |98.32Mb
  - ğŸ‡²ğŸ‡¾MY_595 |29.39Mb
  - ğŸ‡¸ğŸ‡¬SG_599 |11.32Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡§ğŸ‡¬BG_644 |333.18Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - disney_netflix_US |40.80Mb
  - disney_netflix_NL |195.32Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_515 |17.08Mb
  - _423 |52.05Mb
  - disney_HK |74.44Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_519 |10.04Mb
  - ğŸ‡§ğŸ‡·BR_522 |11.85Mb
  - disney_HK |81.89Mb
  - disney_HK |75.07Mb
  - disney_FR |97.40Mb
  - disney_netflix_NL |216.84Mb
  - disney_netflix_NL |110.26Mb
  - disney_netflix_NL |247.04Mb
  - disney_netflix_FR |183.12Mb
  - ğŸ‡­ğŸ‡°HK_539 |128.30Mb
  - ğŸ‡­ğŸ‡°HK_554 |123.27Mb
  - disney_HK |75.67Mb
  - ğŸ‡²ğŸ‡½MX_594 |39.07Mb
  - Relay_ğŸ‡­ğŸ‡°HK-ğŸ‡ºğŸ‡¸US_545 |57.13Mb
  - ğŸ‡®ğŸ‡³IN_588 |124.27Mb
  - ğŸ‡°ğŸ‡·KR_593 |11.74Mb
  - disney_netflix_US |42.29Mb
  - disney_netflix_NL |65.83Mb
  - Relay_ğŸ‡°ğŸ‡·KR-ğŸ‡°ğŸ‡·KR_592 |10.16Mb
  - disney_netflix_US |40.95Mb
  - netflix_LU |190.23Mb
  - netflix_LT |98.32Mb
  - ğŸ‡²ğŸ‡¾MY_595 |29.39Mb
  - ğŸ‡¸ğŸ‡¬SG_599 |11.32Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡§ğŸ‡¬BG_644 |333.18Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
