port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: disney_FI | 7.51Mb
  server: 89.35.119.87
  type: ss
  port: 5904
  udp: true
  password: 5TZnwPb23pQS39lIucspJw
  cipher: chacha20-ietf-poly1305
- name: _141 | 5.62Mb
  server: 104.192.227.162
  type: ss
  port: 443
  udp: true
  password: kXu982CGkJ2MP3RKLTV6Qz
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡§ğŸ‡ªBE_144 | 2.35Mb
  server: 192.71.249.108
  type: ss
  country: ğŸ‡§ğŸ‡ªBE
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ğŸ‡§ğŸ‡¬BG_145 |24.86Mb
  server: 37.19.203.147
  type: ss
  country: ğŸ‡§ğŸ‡¬BG
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ğŸ‡¨ğŸ‡³CN_146 | 4.88Mb
  server: 106.14.75.114
  type: vmess
  country: ğŸ‡¨ğŸ‡³CN
  port: 50002
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 64
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_ğŸ‡¦ğŸ‡ªAE-ğŸ‡¦ğŸ‡ªAE_143 | 6.33Mb
  server: fin.outlinebot1.ru
  type: ss
  country: ğŸ‡¦ğŸ‡ªAE
  port: 5904
  password: 5TZnwPb23pQS39lIucspJw
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡©ğŸ‡ªDE_147
  server: 116.203.43.2
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 8080
  password: 42000e02-6b4d-46ad-a572-80db7db2a9ce
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡©ğŸ‡ªDE_148 | 4.64Mb
  server: 18.199.92.80
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡©ğŸ‡ªDE_150 | 3.99Mb
  server: 18.185.56.207
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡©ğŸ‡ªDE_149 | 2.56Mb
  server: 18.159.194.97
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡©ğŸ‡ªDE_151 | 3.65Mb
  server: 18.156.83.254
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡©ğŸ‡ªDE_152 | 8.37Mb
  server: 85.195.101.122
  type: vmess
  country: ğŸ‡©ğŸ‡ªDE
  port: 40878
  uuid: f3d4167e-b15e-4e46-82e9-9286ef93fda7
  alterId: 0
  cipher: auto
  network: tcp
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡«ğŸ‡·FR_155
  server: 62.210.88.22
  type: ss
  country: ğŸ‡«ğŸ‡·FR
  port: 443
  password: bdFQkay7jQQ633kavfCBuv
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡«ğŸ‡®FI_154 | 9.67Mb
  server: 65.21.243.22
  type: ss
  country: ğŸ‡«ğŸ‡®FI
  port: 31348
  password: mZGUFWMAlfWqI4vP58zw9DAHxR8TZLndKkvRgHHFa9eqWdnx
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_157 | 4.34Mb
  server: 89.185.84.185
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: MGRRe7tTNdT59gifkMqof0
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡«ğŸ‡·FR_156
  server: 62.210.88.22
  type: ss
  country: ğŸ‡«ğŸ‡·FR
  port: 443
  password: HizwHj42uY1ghwsYnbx6Ga
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡®ğŸ‡¹IT_159 | 3.23Mb
  server: 45.134.13.75
  type: ss
  country: ğŸ‡®ğŸ‡¹IT
  port: 443
  password: f81262f1-fafc-44ee-96da-f68ad6bdfd4f
  cipher: aes-256-gcm
- name: ğŸ‡¯ğŸ‡µJP_160 | 5.22Mb
  server: jp008.421421.xyz
  type: trojan
  country: ğŸ‡¯ğŸ‡µJP
  port: 20230
  udp: true
  password: f08d6a6b-a0b3-410e-a0ba-eae71b521904
  sni: www.alibaba.com
  skip-cert-verify: true
  network: ws
- name: Pool_ğŸ‡­ğŸ‡°HK_158 |914.00Mb
  server: 150.107.46.21
  type: ssr
  country: ğŸ‡­ğŸ‡°HK
  port: 8083
  password: iFqnzSscN
  cipher: aes-256-cfb
  protocol: origin
  obfs: tls1.2_ticket_auth
- name: Relay_ğŸ‡±ğŸ‡¹LT-ğŸ‡³ğŸ‡±NL_162 | 5.41Mb
  server: 45.87.175.180
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: QCXDxuDlTTMD7jtgHUjIoj
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_164 | 2.12Mb
  server: 45.87.175.188
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_165 | 6.91Mb
  server: 45.87.175.164
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: 4a2rfixophdjffa8KVA4Aa
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡³ğŸ‡±NL_166 | 7.97Mb
  server: 149.34.244.71
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 443
  password: shadowsocks
  cipher: aes-128-gcm
- name: ğŸ‡µğŸ‡±PL_167 | 9.56Mb
  server: 217.30.10.70
  type: ss
  country: ğŸ‡µğŸ‡±PL
  port: 9070
  password: bf7v334KKDV3YDhH
  cipher: aes-256-cfb
- name: ğŸ‡¸ğŸ‡ªSE_169 |30.10Mb
  server: 51.20.248.11
  type: ss
  country: ğŸ‡¸ğŸ‡ªSE
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡µğŸ‡¾PY_168 |32.95Mb
  server: 38.165.233.18
  type: ss
  country: ğŸ‡µğŸ‡¾PY
  port: 990
  password: f8f7aCzcPKbsF8p3
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_170 |16.08Mb
  server: 18.225.255.52
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡ºğŸ‡¸US_171 |35.09Mb
  server: 18.222.182.194
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡ºğŸ‡¸US_172 |10.86Mb
  server: 23.157.40.101
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 8009
  password: XKFKl2rULjIp74
  cipher: aes-256-gcm
- name: ğŸ‡ºğŸ‡¸US_174 | 5.28Mb
  server: 23.157.40.101
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 8000
  password: KixLvKzwjekG00rm
  cipher: aes-256-gcm
- name: ğŸ‡ºğŸ‡¸US_173 | 8.60Mb
  server: 149.22.87.204
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: shadowsocks
  cipher: aes-128-gcm
- name: ğŸ‡ªğŸ‡¸ES_153 |70.02Mb
  server: 194.87.45.189
  type: ss
  country: ğŸ‡ªğŸ‡¸ES
  port: 443
  password: hZlWzM8qE1D2W1RQ6Q679K
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_176 |14.21Mb
  server: 167.160.90.218
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ğŸ‡ºğŸ‡¸US_175 | 3.28Mb
  server: 45.158.171.146
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 8080
  password: 4a2rfixophdjffa8KVA4Aa
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_178 | 7.78Mb
  server: 173.244.56.6
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: shadowsocks
  cipher: aes-128-gcm
- name: ğŸ‡ºğŸ‡¸US_181 | 6.30Mb
  server: 54.92.201.198
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡ºğŸ‡¸US_177 | 3.55Mb
  server: 45.158.171.150
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 8080
  password: 4a2rfixophdjffa8KVA4Aa
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_182 |22.76Mb
  server: 23.157.40.5
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 8888
  password: Y6R9pAtvxxzmGC
  cipher: aes-256-gcm
- name: ğŸ‡ºğŸ‡¸US_183 |21.47Mb
  server: 38.110.1.122
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 8090
  password: PCnnH6SQSnfoS27
  cipher: aes-256-gcm
- name: ğŸ‡ºğŸ‡¸US_184 | 3.98Mb
  server: 64.74.163.218
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 990
  password: f8f7aCzcPKbsF8p3
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_185 |11.91Mb
  server: 64.74.163.130
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 990
  password: f8f7aCzcPKbsF8p3
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_179 |22.86Mb
  server: 54.234.202.51
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: disney_US | 9.24Mb
  server: 193.124.24.230
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 6506
  uuid: ef5c146e-1dbd-4b9d-a18f-4b29af4a17e2
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_US | 8.78Mb
  server: 165.140.216.141
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  uuid: e7d72a8d-26f2-4b54-b366-0c43e0bcba7d
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: _142 |10.69Mb
  server: 207.90.237.163
  type: ss
  port: 808
  udp: true
  password: tvX1v#NSFP_LG_bJ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡»ğŸ‡³VN_188
  server: 103.186.155.116
  type: ss
  country: ğŸ‡»ğŸ‡³VN
  port: 38388
  password: Xn8jKdmDM00IeO%#$#fJAMtsEAEUOpH/YWYtYqDFnT0SV
  cipher: aes-256-cfb
- name: ğŸ‡»ğŸ‡³VN_190
  server: 103.186.155.207
  type: ss
  country: ğŸ‡»ğŸ‡³VN
  port: 38388
  password: Xn8jKdmDM00IeO%#$#fJAMtsEAEUOpH/YWYtYqDFnT0SV
  cipher: aes-256-cfb
- name: ğŸ‡»ğŸ‡³VN_189
  server: 103.186.155.28
  type: ss
  country: ğŸ‡»ğŸ‡³VN
  port: 38388
  password: Xn8jKdmDM00IeO%#$#fJAMtsEAEUOpH/YWYtYqDFnT0SV
  cipher: aes-256-cfb
- name: ğŸ‡±ğŸ‡¹LT_163 | 7.25Mb
  server: 45.87.175.10
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - disney_FI | 7.51Mb
  - _141 | 5.62Mb
  - ğŸ‡§ğŸ‡ªBE_144 | 2.35Mb
  - ğŸ‡§ğŸ‡¬BG_145 |24.86Mb
  - ğŸ‡¨ğŸ‡³CN_146 | 4.88Mb
  - Relay_ğŸ‡¦ğŸ‡ªAE-ğŸ‡¦ğŸ‡ªAE_143 | 6.33Mb
  - ğŸ‡©ğŸ‡ªDE_147
  - ğŸ‡©ğŸ‡ªDE_148 | 4.64Mb
  - ğŸ‡©ğŸ‡ªDE_150 | 3.99Mb
  - ğŸ‡©ğŸ‡ªDE_149 | 2.56Mb
  - ğŸ‡©ğŸ‡ªDE_151 | 3.65Mb
  - ğŸ‡©ğŸ‡ªDE_152 | 8.37Mb
  - ğŸ‡«ğŸ‡·FR_155
  - ğŸ‡«ğŸ‡®FI_154 | 9.67Mb
  - ğŸ‡¬ğŸ‡§GB_157 | 4.34Mb
  - ğŸ‡«ğŸ‡·FR_156
  - ğŸ‡®ğŸ‡¹IT_159 | 3.23Mb
  - ğŸ‡¯ğŸ‡µJP_160 | 5.22Mb
  - Pool_ğŸ‡­ğŸ‡°HK_158 |914.00Mb
  - Relay_ğŸ‡±ğŸ‡¹LT-ğŸ‡³ğŸ‡±NL_162 | 5.41Mb
  - ğŸ‡±ğŸ‡¹LT_164 | 2.12Mb
  - ğŸ‡±ğŸ‡¹LT_165 | 6.91Mb
  - ğŸ‡³ğŸ‡±NL_166 | 7.97Mb
  - ğŸ‡µğŸ‡±PL_167 | 9.56Mb
  - ğŸ‡¸ğŸ‡ªSE_169 |30.10Mb
  - ğŸ‡µğŸ‡¾PY_168 |32.95Mb
  - ğŸ‡ºğŸ‡¸US_170 |16.08Mb
  - ğŸ‡ºğŸ‡¸US_171 |35.09Mb
  - ğŸ‡ºğŸ‡¸US_172 |10.86Mb
  - ğŸ‡ºğŸ‡¸US_174 | 5.28Mb
  - ğŸ‡ºğŸ‡¸US_173 | 8.60Mb
  - ğŸ‡ªğŸ‡¸ES_153 |70.02Mb
  - ğŸ‡ºğŸ‡¸US_176 |14.21Mb
  - ğŸ‡ºğŸ‡¸US_175 | 3.28Mb
  - ğŸ‡ºğŸ‡¸US_178 | 7.78Mb
  - ğŸ‡ºğŸ‡¸US_181 | 6.30Mb
  - ğŸ‡ºğŸ‡¸US_177 | 3.55Mb
  - ğŸ‡ºğŸ‡¸US_182 |22.76Mb
  - ğŸ‡ºğŸ‡¸US_183 |21.47Mb
  - ğŸ‡ºğŸ‡¸US_184 | 3.98Mb
  - ğŸ‡ºğŸ‡¸US_185 |11.91Mb
  - ğŸ‡ºğŸ‡¸US_179 |22.86Mb
  - disney_US | 9.24Mb
  - disney_US | 8.78Mb
  - _142 |10.69Mb
  - ğŸ‡»ğŸ‡³VN_188
  - ğŸ‡»ğŸ‡³VN_190
  - ğŸ‡»ğŸ‡³VN_189
  - ğŸ‡±ğŸ‡¹LT_163 | 7.25Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - disney_FI | 7.51Mb
  - _141 | 5.62Mb
  - ğŸ‡§ğŸ‡ªBE_144 | 2.35Mb
  - ğŸ‡§ğŸ‡¬BG_145 |24.86Mb
  - ğŸ‡¨ğŸ‡³CN_146 | 4.88Mb
  - Relay_ğŸ‡¦ğŸ‡ªAE-ğŸ‡¦ğŸ‡ªAE_143 | 6.33Mb
  - ğŸ‡©ğŸ‡ªDE_147
  - ğŸ‡©ğŸ‡ªDE_148 | 4.64Mb
  - ğŸ‡©ğŸ‡ªDE_150 | 3.99Mb
  - ğŸ‡©ğŸ‡ªDE_149 | 2.56Mb
  - ğŸ‡©ğŸ‡ªDE_151 | 3.65Mb
  - ğŸ‡©ğŸ‡ªDE_152 | 8.37Mb
  - ğŸ‡«ğŸ‡·FR_155
  - ğŸ‡«ğŸ‡®FI_154 | 9.67Mb
  - ğŸ‡¬ğŸ‡§GB_157 | 4.34Mb
  - ğŸ‡«ğŸ‡·FR_156
  - ğŸ‡®ğŸ‡¹IT_159 | 3.23Mb
  - ğŸ‡¯ğŸ‡µJP_160 | 5.22Mb
  - Pool_ğŸ‡­ğŸ‡°HK_158 |914.00Mb
  - Relay_ğŸ‡±ğŸ‡¹LT-ğŸ‡³ğŸ‡±NL_162 | 5.41Mb
  - ğŸ‡±ğŸ‡¹LT_164 | 2.12Mb
  - ğŸ‡±ğŸ‡¹LT_165 | 6.91Mb
  - ğŸ‡³ğŸ‡±NL_166 | 7.97Mb
  - ğŸ‡µğŸ‡±PL_167 | 9.56Mb
  - ğŸ‡¸ğŸ‡ªSE_169 |30.10Mb
  - ğŸ‡µğŸ‡¾PY_168 |32.95Mb
  - ğŸ‡ºğŸ‡¸US_170 |16.08Mb
  - ğŸ‡ºğŸ‡¸US_171 |35.09Mb
  - ğŸ‡ºğŸ‡¸US_172 |10.86Mb
  - ğŸ‡ºğŸ‡¸US_174 | 5.28Mb
  - ğŸ‡ºğŸ‡¸US_173 | 8.60Mb
  - ğŸ‡ªğŸ‡¸ES_153 |70.02Mb
  - ğŸ‡ºğŸ‡¸US_176 |14.21Mb
  - ğŸ‡ºğŸ‡¸US_175 | 3.28Mb
  - ğŸ‡ºğŸ‡¸US_178 | 7.78Mb
  - ğŸ‡ºğŸ‡¸US_181 | 6.30Mb
  - ğŸ‡ºğŸ‡¸US_177 | 3.55Mb
  - ğŸ‡ºğŸ‡¸US_182 |22.76Mb
  - ğŸ‡ºğŸ‡¸US_183 |21.47Mb
  - ğŸ‡ºğŸ‡¸US_184 | 3.98Mb
  - ğŸ‡ºğŸ‡¸US_185 |11.91Mb
  - ğŸ‡ºğŸ‡¸US_179 |22.86Mb
  - disney_US | 9.24Mb
  - disney_US | 8.78Mb
  - _142 |10.69Mb
  - ğŸ‡»ğŸ‡³VN_188
  - ğŸ‡»ğŸ‡³VN_190
  - ğŸ‡»ğŸ‡³VN_189
  - ğŸ‡±ğŸ‡¹LT_163 | 7.25Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
