port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: ğŸ‡¨ğŸ‡¦CA_375 |21.16Mb
  server: 138.197.165.21
  type: ss
  country: ğŸ‡¨ğŸ‡¦CA
  port: 8080
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: ğŸ‡¨ğŸ‡¦CA_374 |10.92Mb
  server: 68.183.193.204
  type: ss
  country: ğŸ‡¨ğŸ‡¦CA
  port: 8080
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: ğŸ‡¨ğŸ‡¿CZ_379 |29.54Mb
  server: 195.181.160.6
  type: ss
  country: ğŸ‡¨ğŸ‡¿CZ
  port: 990
  password: f8f7aCzcPKbsF8p3
  cipher: chacha20-ietf-poly1305
- name: _356 |30.30Mb
  server: 176.126.83.158
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡©ğŸ‡ªDE_387 |93.19Mb
  server: 85.195.101.122
  type: vmess
  country: ğŸ‡©ğŸ‡ªDE
  port: 40878
  uuid: f3d4167e-b15e-4e46-82e9-9286ef93fda7
  alterId: 0
  cipher: auto
  network: tcp
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: _350 |30.25Mb
  server: 37.143.129.98
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _352 |10.43Mb
  server: 192.71.249.108
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¦ğŸ‡ºAU_367 |13.54Mb
  server: 3.25.225.79
  type: ss
  country: ğŸ‡¦ğŸ‡ºAU
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡«ğŸ‡·FR_395 |145.67Mb
  server: 83.147.216.70
  type: ss
  country: ğŸ‡«ğŸ‡·FR
  port: 64519
  password: F3nY73di5onWV3gotbpI0Q
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¦ğŸ‡·AR_361 |19.93Mb
  server: 38.54.45.129
  type: ss
  country: ğŸ‡¦ğŸ‡·AR
  port: 990
  password: f8f7aCzcPKbsF8p3
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡«ğŸ‡·FR_396 |148.76Mb
  server: 83.147.216.70
  type: ss
  country: ğŸ‡«ğŸ‡·FR
  port: 64519
  password: eBzKXxEmQlAZKIBC8PhQYZ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_404 |10.84Mb
  server: 141.98.101.179
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: shadowsocks
  cipher: aes-128-gcm
- name: ğŸ‡¯ğŸ‡µJP_433 |32.28Mb
  server: 153.121.51.214
  type: ss
  country: ğŸ‡¯ğŸ‡µJP
  port: 10087
  password: '10086'
  cipher: aes-128-gcm
- name: ğŸ‡±ğŸ‡¹LT_439 |10.17Mb
  server: 45.87.175.171
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: QCXDxuDlTTMD7jtgHUjIoj
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡³ğŸ‡±NL_453 |10.03Mb
  server: 193.29.139.157
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 8080
  password: QCXDxuDlTTMD7jtgHUjIoj
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡³ğŸ‡±NL_454 |14.69Mb
  server: 79.127.227.53
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ğŸ‡³ğŸ‡±NL_457 |12.03Mb
  server: 79.127.227.198
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 990
  password: f8f7aCzcPKbsF8p3
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡®ğŸ‡³IN_411 |15.59Mb
  server: 52.66.211.233
  type: ss
  country: ğŸ‡®ğŸ‡³IN
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡®ğŸ‡³IN_413 |40.88Mb
  server: 13.126.253.30
  type: ss
  country: ğŸ‡®ğŸ‡³IN
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: Pool_ğŸ‡­ğŸ‡°HK_405 |634.00Mb
  server: 150.107.46.21
  type: ssr
  country: ğŸ‡­ğŸ‡°HK
  port: 8083
  password: iFqnzSscN
  cipher: aes-256-cfb
  protocol: origin
  obfs: tls1.2_ticket_auth
- name: ğŸ‡·ğŸ‡ºRU_476 |10.83Mb
  server: 95.163.176.37
  type: ss
  country: ğŸ‡·ğŸ‡ºRU
  port: 8506
  password: VdswxetVc6AhIps18rtYbm
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_509 |17.74Mb
  server: 54.90.199.180
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡µğŸ‡¾PY_474 |20.96Mb
  server: 38.165.233.18
  type: ss
  country: ğŸ‡µğŸ‡¾PY
  port: 990
  password: f8f7aCzcPKbsF8p3
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_510 |18.28Mb
  server: 167.88.61.110
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 2376
  password: faBAoD54k87UJG7
  cipher: aes-256-gcm
- name: ğŸ‡·ğŸ‡ºRU_479 |10.75Mb
  server: 95.163.176.37
  type: ss
  country: ğŸ‡·ğŸ‡ºRU
  port: 8506
  password: n4J9KuWgBBXPBoDn0SdprD
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡·ğŸ‡ºRU_480 |10.29Mb
  server: 95.163.176.37
  type: ss
  country: ğŸ‡·ğŸ‡ºRU
  port: 8506
  password: KVe53W0gvOHIOJxXChJ5uA
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡·ğŸ‡ºRU_478 |22.37Mb
  server: 5.129.201.43
  type: ss
  country: ğŸ‡·ğŸ‡ºRU
  port: 23256
  password: yALtyAtHfbw1Vu4pqh6wUc
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_512 |20.49Mb
  server: 23.157.40.5
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 2376
  password: faBAoD54k87UJG7
  cipher: aes-256-gcm
- name: ğŸ‡ºğŸ‡¸US_511 |94.43Mb
  server: 167.88.61.113
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 6697
  password: TEzjfAYq2IjtuoS
  cipher: aes-256-gcm
- name: ğŸ‡ºğŸ‡¸US_521 |27.43Mb
  server: 23.157.40.5
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 5498
  password: lGqs95QkFHo2NV
  cipher: aes-256-gcm
- name: ğŸ‡ºğŸ‡¸US_523 |102.27Mb
  server: 167.88.61.113
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 8090
  password: PCnnH6SQSnfoS27
  cipher: aes-256-gcm
- name: ğŸ‡ºğŸ‡¸US_525 |107.86Mb
  server: 23.157.40.101
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 8000
  password: KixLvKzwjekG00rm
  cipher: aes-256-gcm
- name: ğŸ‡ºğŸ‡¸US_522 |14.71Mb
  server: 54.84.99.165
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡¹ğŸ‡·TR_486 |55.38Mb
  server: 45.89.52.66
  type: ss
  country: ğŸ‡¹ğŸ‡·TR
  port: 9019
  password: GA9KzeEgvfxNrgmM
  cipher: aes-256-cfb
- name: ğŸ‡ºğŸ‡¸US_527 |17.21Mb
  server: 23.157.40.5
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 8091
  password: PCnnH6SQSnfoS27
  cipher: aes-256-gcm
- name: ğŸ‡ºğŸ‡¸US_529 |31.56Mb
  server: 23.157.40.5
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 5000
  password: Y6R9pAtvxxzmGC
  cipher: aes-256-gcm
- name: ğŸ‡ºğŸ‡¸US_530 |16.03Mb
  server: 23.157.40.5
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 8888
  password: Y6R9pAtvxxzmGC
  cipher: aes-256-gcm
- name: ğŸ‡ºğŸ‡¸US_536 |22.13Mb
  server: 23.157.40.5
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 7001
  password: RexnBgU7EV5ADxG
  cipher: aes-256-gcm
- name: ğŸ‡ºğŸ‡¸US_544 |61.13Mb
  server: 23.157.40.5
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 8080
  password: KixLvKzwjekG00rm
  cipher: aes-256-gcm
- name: ğŸ‡ºğŸ‡¸US_537 |42.90Mb
  server: 64.74.163.130
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 990
  password: f8f7aCzcPKbsF8p3
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_542 |42.34Mb
  server: 64.74.163.218
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 990
  password: f8f7aCzcPKbsF8p3
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_548 |83.42Mb
  server: 167.88.61.110
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 8119
  password: cdBIDV42DCwnfIN
  cipher: aes-256-gcm
- name: ğŸ‡ºğŸ‡¸US_533 |26.27Mb
  server: 23.157.40.5
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 8008
  password: XKFKl2rULjIp74
  cipher: aes-256-gcm
- name: ğŸ‡ºğŸ‡¸US_551 |40.64Mb
  server: 23.157.40.5
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 5499
  password: lGqs95QkFHo2NV
  cipher: aes-256-gcm
- name: ğŸ‡ºğŸ‡¸US_552 |47.42Mb
  server: 167.88.61.110
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 6679
  password: TEzjfAYq2IjtuoS
  cipher: aes-256-gcm
- name: disney_US |175.91Mb
  server: 193.124.24.247
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 6506
  uuid: c53d41d1-7d56-43ce-9994-408780c6476a
  alterId: 0
  cipher: auto
  network: tcp
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_US |146.32Mb
  server: 193.124.24.247
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 6508
  uuid: b68fead5-5b0b-43a1-c34a-804467f0f368
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡ºğŸ‡¸US_553 |24.80Mb
  server: 167.88.61.110
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 7001
  password: RexnBgU7EV5ADxG
  cipher: aes-256-gcm
- name: ğŸ‡ºğŸ‡¸US_556 |19.94Mb
  server: 104.192.226.106
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 990
  password: f8f7aCzcPKbsF8p3
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_555 |64.24Mb
  server: 167.88.61.110
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 8118
  password: cdBIDV42DCwnfIN
  cipher: aes-256-gcm
- name: disney_US |119.96Mb
  server: 193.124.24.247
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 6504
  uuid: 7ceb165c-9aff-4ab7-ce9e-1df31a5ed911
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_US |178.61Mb
  server: 193.124.24.247
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 6502
  uuid: 242f22a3-29d9-4a94-d8ba-88043f2e1921
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_US |162.16Mb
  server: 193.124.24.247
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 6507
  uuid: 3003e094-707c-4dbb-faca-4b8d579bc604
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_US |151.38Mb
  server: 193.124.24.247
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 6515
  uuid: 2f3c646a-37f3-483a-a2a5-6bc1c5e526ae
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_US |119.69Mb
  server: 193.124.24.247
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 6513
  uuid: 5cf7fcbc-e2c1-42c4-d0d7-79c45a7d588d
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_US |174.19Mb
  server: 193.124.24.247
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 6510
  uuid: 8f44f672-e53b-44fb-b502-c886d37107b5
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡ºğŸ‡¸US_577 |254.14Mb
  server: 15.204.11.190
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 15361
  uuid: 5d7bf9e3-415c-40f3-c66d-a54ea0fd860e
  alterId: 0
  cipher: auto
  network: tcp
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_US |72.56Mb
  server: 64.81.118.54
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 20521
  uuid: 375c4b8f-b646-45c1-96a8-e9d86d4163e5
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
  ws-opts:
    path: /
- name: ğŸ‡ºğŸ‡¸US_564 |12.63Mb
  server: 38.54.57.90
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_516 |71.64Mb
  server: imap.roomyinmita.name
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 40565
  password: oEkEWExFKHKeY1xuRns6ErkYbzt3HdCGNPN3nTQnM1FU7yTR1SZTTC2JLtPF7HeFAUCGgx5hvxUGw8ksjEyRioPEeXhxg7Q3
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_581 |79.55Mb
  server: 66.253.7.254
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 45979
  uuid: 23bdf6df-c482-46d0-c0f4-5a98d534ea11
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
  ws-opts:
    path: /test
- name: ğŸ‡«ğŸ‡·FR_400 |150.81Mb
  server: 83.147.216.70
  type: ss
  country: ğŸ‡«ğŸ‡·FR
  port: 64519
  password: Vq1y6zEAmcfGoBB0dRBbV7
  cipher: chacha20-ietf-poly1305
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - ğŸ‡¨ğŸ‡¦CA_375 |21.16Mb
  - ğŸ‡¨ğŸ‡¦CA_374 |10.92Mb
  - ğŸ‡¨ğŸ‡¿CZ_379 |29.54Mb
  - _356 |30.30Mb
  - ğŸ‡©ğŸ‡ªDE_387 |93.19Mb
  - _350 |30.25Mb
  - _352 |10.43Mb
  - ğŸ‡¦ğŸ‡ºAU_367 |13.54Mb
  - ğŸ‡«ğŸ‡·FR_395 |145.67Mb
  - ğŸ‡¦ğŸ‡·AR_361 |19.93Mb
  - ğŸ‡«ğŸ‡·FR_396 |148.76Mb
  - ğŸ‡¬ğŸ‡§GB_404 |10.84Mb
  - ğŸ‡¯ğŸ‡µJP_433 |32.28Mb
  - ğŸ‡±ğŸ‡¹LT_439 |10.17Mb
  - ğŸ‡³ğŸ‡±NL_453 |10.03Mb
  - ğŸ‡³ğŸ‡±NL_454 |14.69Mb
  - ğŸ‡³ğŸ‡±NL_457 |12.03Mb
  - ğŸ‡®ğŸ‡³IN_411 |15.59Mb
  - ğŸ‡®ğŸ‡³IN_413 |40.88Mb
  - Pool_ğŸ‡­ğŸ‡°HK_405 |634.00Mb
  - ğŸ‡·ğŸ‡ºRU_476 |10.83Mb
  - ğŸ‡ºğŸ‡¸US_509 |17.74Mb
  - ğŸ‡µğŸ‡¾PY_474 |20.96Mb
  - ğŸ‡ºğŸ‡¸US_510 |18.28Mb
  - ğŸ‡·ğŸ‡ºRU_479 |10.75Mb
  - ğŸ‡·ğŸ‡ºRU_480 |10.29Mb
  - ğŸ‡·ğŸ‡ºRU_478 |22.37Mb
  - ğŸ‡ºğŸ‡¸US_512 |20.49Mb
  - ğŸ‡ºğŸ‡¸US_511 |94.43Mb
  - ğŸ‡ºğŸ‡¸US_521 |27.43Mb
  - ğŸ‡ºğŸ‡¸US_523 |102.27Mb
  - ğŸ‡ºğŸ‡¸US_525 |107.86Mb
  - ğŸ‡ºğŸ‡¸US_522 |14.71Mb
  - ğŸ‡¹ğŸ‡·TR_486 |55.38Mb
  - ğŸ‡ºğŸ‡¸US_527 |17.21Mb
  - ğŸ‡ºğŸ‡¸US_529 |31.56Mb
  - ğŸ‡ºğŸ‡¸US_530 |16.03Mb
  - ğŸ‡ºğŸ‡¸US_536 |22.13Mb
  - ğŸ‡ºğŸ‡¸US_544 |61.13Mb
  - ğŸ‡ºğŸ‡¸US_537 |42.90Mb
  - ğŸ‡ºğŸ‡¸US_542 |42.34Mb
  - ğŸ‡ºğŸ‡¸US_548 |83.42Mb
  - ğŸ‡ºğŸ‡¸US_533 |26.27Mb
  - ğŸ‡ºğŸ‡¸US_551 |40.64Mb
  - ğŸ‡ºğŸ‡¸US_552 |47.42Mb
  - disney_US |175.91Mb
  - disney_US |146.32Mb
  - ğŸ‡ºğŸ‡¸US_553 |24.80Mb
  - ğŸ‡ºğŸ‡¸US_556 |19.94Mb
  - ğŸ‡ºğŸ‡¸US_555 |64.24Mb
  - disney_US |119.96Mb
  - disney_US |178.61Mb
  - disney_US |162.16Mb
  - disney_US |151.38Mb
  - disney_US |119.69Mb
  - disney_US |174.19Mb
  - ğŸ‡ºğŸ‡¸US_577 |254.14Mb
  - disney_US |72.56Mb
  - ğŸ‡ºğŸ‡¸US_564 |12.63Mb
  - ğŸ‡ºğŸ‡¸US_516 |71.64Mb
  - ğŸ‡ºğŸ‡¸US_581 |79.55Mb
  - ğŸ‡«ğŸ‡·FR_400 |150.81Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - ğŸ‡¨ğŸ‡¦CA_375 |21.16Mb
  - ğŸ‡¨ğŸ‡¦CA_374 |10.92Mb
  - ğŸ‡¨ğŸ‡¿CZ_379 |29.54Mb
  - _356 |30.30Mb
  - ğŸ‡©ğŸ‡ªDE_387 |93.19Mb
  - _350 |30.25Mb
  - _352 |10.43Mb
  - ğŸ‡¦ğŸ‡ºAU_367 |13.54Mb
  - ğŸ‡«ğŸ‡·FR_395 |145.67Mb
  - ğŸ‡¦ğŸ‡·AR_361 |19.93Mb
  - ğŸ‡«ğŸ‡·FR_396 |148.76Mb
  - ğŸ‡¬ğŸ‡§GB_404 |10.84Mb
  - ğŸ‡¯ğŸ‡µJP_433 |32.28Mb
  - ğŸ‡±ğŸ‡¹LT_439 |10.17Mb
  - ğŸ‡³ğŸ‡±NL_453 |10.03Mb
  - ğŸ‡³ğŸ‡±NL_454 |14.69Mb
  - ğŸ‡³ğŸ‡±NL_457 |12.03Mb
  - ğŸ‡®ğŸ‡³IN_411 |15.59Mb
  - ğŸ‡®ğŸ‡³IN_413 |40.88Mb
  - Pool_ğŸ‡­ğŸ‡°HK_405 |634.00Mb
  - ğŸ‡·ğŸ‡ºRU_476 |10.83Mb
  - ğŸ‡ºğŸ‡¸US_509 |17.74Mb
  - ğŸ‡µğŸ‡¾PY_474 |20.96Mb
  - ğŸ‡ºğŸ‡¸US_510 |18.28Mb
  - ğŸ‡·ğŸ‡ºRU_479 |10.75Mb
  - ğŸ‡·ğŸ‡ºRU_480 |10.29Mb
  - ğŸ‡·ğŸ‡ºRU_478 |22.37Mb
  - ğŸ‡ºğŸ‡¸US_512 |20.49Mb
  - ğŸ‡ºğŸ‡¸US_511 |94.43Mb
  - ğŸ‡ºğŸ‡¸US_521 |27.43Mb
  - ğŸ‡ºğŸ‡¸US_523 |102.27Mb
  - ğŸ‡ºğŸ‡¸US_525 |107.86Mb
  - ğŸ‡ºğŸ‡¸US_522 |14.71Mb
  - ğŸ‡¹ğŸ‡·TR_486 |55.38Mb
  - ğŸ‡ºğŸ‡¸US_527 |17.21Mb
  - ğŸ‡ºğŸ‡¸US_529 |31.56Mb
  - ğŸ‡ºğŸ‡¸US_530 |16.03Mb
  - ğŸ‡ºğŸ‡¸US_536 |22.13Mb
  - ğŸ‡ºğŸ‡¸US_544 |61.13Mb
  - ğŸ‡ºğŸ‡¸US_537 |42.90Mb
  - ğŸ‡ºğŸ‡¸US_542 |42.34Mb
  - ğŸ‡ºğŸ‡¸US_548 |83.42Mb
  - ğŸ‡ºğŸ‡¸US_533 |26.27Mb
  - ğŸ‡ºğŸ‡¸US_551 |40.64Mb
  - ğŸ‡ºğŸ‡¸US_552 |47.42Mb
  - disney_US |175.91Mb
  - disney_US |146.32Mb
  - ğŸ‡ºğŸ‡¸US_553 |24.80Mb
  - ğŸ‡ºğŸ‡¸US_556 |19.94Mb
  - ğŸ‡ºğŸ‡¸US_555 |64.24Mb
  - disney_US |119.96Mb
  - disney_US |178.61Mb
  - disney_US |162.16Mb
  - disney_US |151.38Mb
  - disney_US |119.69Mb
  - disney_US |174.19Mb
  - ğŸ‡ºğŸ‡¸US_577 |254.14Mb
  - disney_US |72.56Mb
  - ğŸ‡ºğŸ‡¸US_564 |12.63Mb
  - ğŸ‡ºğŸ‡¸US_516 |71.64Mb
  - ğŸ‡ºğŸ‡¸US_581 |79.55Mb
  - ğŸ‡«ğŸ‡·FR_400 |150.81Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
