port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: _297 |14.61Mb
  server: 160.16.72.33
  type: trojan
  port: 3093
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¯ğŸ‡µJP_299 |20.42Mb
  server: 160.16.87.174
  type: trojan
  port: 3169
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: _282 |12.29Mb
  server: 194.59.183.134
  type: ss
  port: 46114
  udp: true
  password: lejSRyqa033OEPmEQsvRsl
  cipher: chacha20-ietf-poly1305
- name: netflix_NL |222.63Mb
  server: 45.14.245.2
  type: ss
  port: 443
  password: 17ZDORWIliQHuO6WRGHChXYMzdRtAYVP
  cipher: chacha20-ietf-poly1305
- name: _289 |113.91Mb
  server: 47.242.145.160
  type: vmess
  port: 44457
  uuid: 40290609-2743-4d85-c9c3-4c72dd151b9f
  alterId: 0
  cipher: auto
  network: http
  http-opts:
    method: GET
    path:
    - /
  h2-opts: {}
- name: disney_HK |69.54Mb
  server: 103.149.182.105
  type: ss
  port: 8388
  password: asd123456
  cipher: chacha20-ietf
- name: _284 |472.43Mb
  server: 46.183.184.60
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: Relay_-ğŸ‡¯ğŸ‡µJP_301 |22.05Mb
  server: 153.121.45.139
  type: trojan
  port: 3093
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: _303 |12.61Mb
  server: 160.16.204.136
  type: trojan
  port: 2890
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: disney_PY |16.48Mb
  server: 38.165.233.93
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: _304 |10.41Mb
  server: 160.16.116.227
  type: trojan
  port: 2760
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
  skip-cert-verify: true
- name: _306 |10.95Mb
  server: 160.16.131.243
  type: trojan
  port: 2760
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
  skip-cert-verify: true
- name: Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_332 |174.00Mb
  server: 38.14.99.163
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 59807
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: auto
  network: tcp
  servername: 38.14.99.163
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: _307 |43.05Mb
  server: 160.16.136.130
  type: trojan
  port: 2890
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¯ğŸ‡µJP_308 |21.75Mb
  server: 160.16.117.182
  type: trojan
  port: 3169
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¯ğŸ‡µJP_309 |14.19Mb
  server: 160.16.117.182
  type: trojan
  port: 3093
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: ğŸ‡²ğŸ‡½MX_324 |38.49Mb
  server: 216.238.87.47
  type: vmess
  country: ğŸ‡²ğŸ‡½MX
  port: 27502
  uuid: b8155ce4-7e08-4c40-800f-8671312b7124
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_333 |18.79Mb
  server: gy3.hdcloud.link
  type: trojan
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  udp: true
  password: 168f29a7-6922-4558-8296-61a69cf6a5a2
  network: grpc
  grpc-opts:
    grpc-service-name: GunService
- name: ğŸ‡­ğŸ‡°HK_318 |107.48Mb
  server: 8.218.116.26
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 32228
  uuid: e4767e9f-ed00-4f31-a984-a918bdd9b09c
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡­ğŸ‡°HK_320 |120.78Mb
  server: 8.218.105.196
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 52752
  uuid: 925bdbf5-72be-4437-bebf-441c61089f6b
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_DE |45.39Mb
  server: 1762945941.tencentapp.cn
  type: vmess
  country: ğŸZZ
  port: 443
  uuid: b1b67a69-f741-45f5-b382-5ac15508204e
  alterId: 0
  cipher: auto
  network: ws
  servername: 10o4ar.speed.nlbbacvb.cccp.cctvalipay.cn
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /
    headers:
      HOST: 10o4ar.speed.nlbbacvb.cccp.cctvalipay.cn
- name: ğŸ‡¨ğŸ‡­CH_312 |11.30Mb
  server: 138.124.67.26
  type: ss
  country: ğŸ‡¨ğŸ‡­CH
  port: 25572
  password: nqcIfYHlpMn3jzqkNDjKaG
  cipher: chacha20-ietf-poly1305
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - _297 |14.61Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_299 |20.42Mb
  - _282 |12.29Mb
  - netflix_NL |222.63Mb
  - _289 |113.91Mb
  - disney_HK |69.54Mb
  - _284 |472.43Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_301 |22.05Mb
  - _303 |12.61Mb
  - disney_PY |16.48Mb
  - _304 |10.41Mb
  - _306 |10.95Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_332 |174.00Mb
  - _307 |43.05Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_308 |21.75Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_309 |14.19Mb
  - ğŸ‡²ğŸ‡½MX_324 |38.49Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_333 |18.79Mb
  - ğŸ‡­ğŸ‡°HK_318 |107.48Mb
  - ğŸ‡­ğŸ‡°HK_320 |120.78Mb
  - disney_DE |45.39Mb
  - ğŸ‡¨ğŸ‡­CH_312 |11.30Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - _297 |14.61Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_299 |20.42Mb
  - _282 |12.29Mb
  - netflix_NL |222.63Mb
  - _289 |113.91Mb
  - disney_HK |69.54Mb
  - _284 |472.43Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_301 |22.05Mb
  - _303 |12.61Mb
  - disney_PY |16.48Mb
  - _304 |10.41Mb
  - _306 |10.95Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_332 |174.00Mb
  - _307 |43.05Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_308 |21.75Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_309 |14.19Mb
  - ğŸ‡²ğŸ‡½MX_324 |38.49Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_333 |18.79Mb
  - ğŸ‡­ğŸ‡°HK_318 |107.48Mb
  - ğŸ‡­ğŸ‡°HK_320 |120.78Mb
  - disney_DE |45.39Mb
  - ğŸ‡¨ğŸ‡­CH_312 |11.30Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
