port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: ' |35.91Mb'
  server: 172.235.33.114
  type: vmess
  port: 10001
  uuid: 442a3923-eca1-4af0-b3ff-24a7ce0af68f
  alterId: 0
  cipher: auto
  network: tcp
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: netflix_NL |246.82Mb
  server: 45.87.175.177
  type: ss
  port: 8080
  udp: true
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: Relay_-ğŸ‡³ğŸ‡±NL_400 |327.39Mb
  server: 151.242.251.144
  type: ss
  port: 8080
  udp: true
  password: QCXDxuDlTTMD7jtgHUjIoj
  cipher: chacha20-ietf-poly1305
- name: Relay_-ğŸ‡³ğŸ‡±NL_403 |118.08Mb
  server: 82.38.31.218
  type: ss
  port: 8080
  udp: true
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: _408 |14.46Mb
  server: 82.38.31.179
  type: ss
  port: 8080
  udp: true
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: _410 |82.47Mb
  server: 45.15.126.19
  type: ss
  port: 443
  udp: true
  password: 6Ts2ZDTQAf3hkFoB8AFufDwsGrlF4e2t
  cipher: chacha20-ietf-poly1305
- name: Relay_-ğŸ‡ºğŸ‡¸US_441 |39.21Mb
  server: 141.193.213.199
  type: trojan
  port: 443
  udp: true
  password: a8a5b34d-fe46-487d-bd6a-d9f3101525fd
  sni: 26z68w0ecxbuyf89.ukgogo202511.top
  skip-cert-verify: true
  ws-opts:
    path: /images
    headers:
      Host: 26z68w0ecxbuyf89.ukgogo202511.top
  network: ws
- name: disney_US |30.37Mb
  server: 158.101.11.204
  type: trojan
  port: 15805
  udp: true
  password: iwangjie
  sni: nodes.830901.xyz
  ws-opts:
    path: /?ed=2560
    headers:
      Host: nodes.830901.xyz
  network: ws
- name: disney_PT |103.11Mb
  server: 185.231.233.112
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: _407 |42.34Mb
  server: 213.159.67.124
  type: ss
  port: 443
  password: mbhqsStnFQT1cTZYCdsmkugGUC6GT6rp
  cipher: chacha20-ietf-poly1305
- name: Relay_ |49.79Mb
  server: us19-25.998998.best
  type: vmess
  port: 443
  udp: true
  uuid: 24254866-770c-41b4-9404-3f50524f425b
  alterId: 0
  cipher: auto
  network: ws
  servername: 24254866-770c-41b4-9404-3f50524f425b.mihomo.baby
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /saoihgreg9384gh8934
    headers:
      Host: 24254866-770c-41b4-9404-3f50524f425b.mihomo.baby
- name: Relay_-ğŸ‡¯ğŸ‡µJP_432 |10.99Mb
  server: 160.16.138.24
  type: trojan
  port: 3169
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: disney_FR |81.63Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 27092
  uuid: a0596ba6-72a3-4366-8992-77088da65bd8
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_ğŸ‡®ğŸ‡· IR-ğŸ‡³ğŸ‡±NL_448 |302.10Mb
  server: 151.242.251.153
  type: ss
  country: ğŸ‡®ğŸ‡· IR
  port: 8080
  password: QCXDxuDlTTMD7jtgHUjIoj
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸ‡®ğŸ‡· IR-ğŸ‡³ğŸ‡±NL_449 |302.22Mb
  server: 151.242.251.144
  type: ss
  country: ğŸ‡®ğŸ‡· IR
  port: 8080
  password: 4a2rfixophdjffa8KVA4Aa
  cipher: chacha20-ietf-poly1305
- name: _433 |28.23Mb
  server: 37.18.14.33
  type: trojan
  port: 443
  udp: true
  password: Qzy7tgpRhu
  sni: m.vk.com
  skip-cert-verify: true
- name: disney_PY |144.28Mb
  server: 38.165.233.93
  type: ss
  country: ğŸ‡ºğŸ‡¸ US
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: Relay_ |10.74Mb
  server: w13.luoli.de
  type: vmess
  port: 443
  udp: true
  uuid: 42a99644-b90b-3627-8809-a2d6c4078b59
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  tls: true
  ws-opts:
    path: /v2ws
    headers:
      Host: w13.luoli.de
- name: disney_HK |10.42Mb
  server: green2.cdntencentmusic.com
  type: trojan
  port: 31102
  udp: true
  password: 7ca90727-8867-47aa-9486-70dbd06d9e32
  sni: green2.cdntencentmusic.com
  skip-cert-verify: true
- name: Relay_ğŸ‡ºğŸ‡¸US |33.12Mb
  server: sw19.sesamebuta.top
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  uuid: 805ba514-bf2f-4d5d-df49-8417804e8de3
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /abcd
- name: Relay_-ğŸ‡¯ğŸ‡µJP_413 |23.01Mb
  server: nom6p-g05.jp03-j7-vm0.entry.fr0528.art
  type: vmess
  port: 21585
  udp: true
  uuid: ca78405e-e554-3cd3-9b6d-2ec98e21c8f1
  alterId: 1
  cipher: auto
  http-opts: {}
  h2-opts: {}
  tls: true
- name: Relay_ğŸ‡ºğŸ‡¸US |22.93Mb
  server: cf.fovi.tk
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  uuid: bf67437e-6c90-45ca-abc2-c7240a5ce2aa
  alterId: 0
  cipher: auto
  network: ws
  servername: foxpol.fovi.tk
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /eisasqa
    headers:
      HOST: foxpol.fovi.tk
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - ' |35.91Mb'
  - netflix_NL |246.82Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_400 |327.39Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_403 |118.08Mb
  - _408 |14.46Mb
  - _410 |82.47Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_441 |39.21Mb
  - disney_US |30.37Mb
  - disney_PT |103.11Mb
  - _407 |42.34Mb
  - Relay_ |49.79Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_432 |10.99Mb
  - disney_FR |81.63Mb
  - Relay_ğŸ‡®ğŸ‡· IR-ğŸ‡³ğŸ‡±NL_448 |302.10Mb
  - Relay_ğŸ‡®ğŸ‡· IR-ğŸ‡³ğŸ‡±NL_449 |302.22Mb
  - _433 |28.23Mb
  - disney_PY |144.28Mb
  - Relay_ |10.74Mb
  - disney_HK |10.42Mb
  - Relay_ğŸ‡ºğŸ‡¸US |33.12Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_413 |23.01Mb
  - Relay_ğŸ‡ºğŸ‡¸US |22.93Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - ' |35.91Mb'
  - netflix_NL |246.82Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_400 |327.39Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_403 |118.08Mb
  - _408 |14.46Mb
  - _410 |82.47Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_441 |39.21Mb
  - disney_US |30.37Mb
  - disney_PT |103.11Mb
  - _407 |42.34Mb
  - Relay_ |49.79Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_432 |10.99Mb
  - disney_FR |81.63Mb
  - Relay_ğŸ‡®ğŸ‡· IR-ğŸ‡³ğŸ‡±NL_448 |302.10Mb
  - Relay_ğŸ‡®ğŸ‡· IR-ğŸ‡³ğŸ‡±NL_449 |302.22Mb
  - _433 |28.23Mb
  - disney_PY |144.28Mb
  - Relay_ |10.74Mb
  - disney_HK |10.42Mb
  - Relay_ğŸ‡ºğŸ‡¸US |33.12Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_413 |23.01Mb
  - Relay_ğŸ‡ºğŸ‡¸US |22.93Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
