port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: disney_netflix_GB |159.63Mb
  server: koma-yt.pages.dev
  type: trojan
  port: 8443
  udp: true
  password: 8r<[9'l6hAO#8ZQi
  sni: Koma-YT.PAGeS.Dev
  ws-opts:
    path: /tro8sFW1S91B6sZrM1?ed=2560
    headers:
      Host: Koma-YT.PAGeS.Dev
  network: ws
- name: disney_netflix_NO |22.06Mb
  server: 107.174.114.71
  type: ss
  port: 443
  password: 595HLF3fHUuw0McM51tpvPygSIB1uf4D
  cipher: chacha20-ietf-poly1305
- name: _178 |32.60Mb
  server: 103.231.73.211
  type: ss
  port: 57456
  udp: true
  password: 8afc633eb63227e9
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_FR |173.84Mb
  server: 208.76.223.218
  type: vmess
  country: ðŸ‡ªðŸ‡¸ES
  port: 27092
  uuid: a0596ba6-72a3-4366-8992-77088da65bd8
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_-ðŸ‡·ðŸ‡ºRU_179 |14.81Mb
  server: 146.19.128.183
  type: ss
  port: 17847
  udp: true
  password: '907560230'
  cipher: chacha20-ietf-poly1305
- name: Relay_-ðŸ‡¯ðŸ‡µJP_272 |19.99Mb
  server: 160.16.117.182
  type: trojan
  port: 3093
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: Relay_-ðŸ‡¯ðŸ‡µJP_271 |20.10Mb
  server: 13.231.156.35
  type: trojan
  port: 1331
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: disney_netflix_FR |180.46Mb
  server: 208.76.223.218
  type: vmess
  country: ðŸ‡ªðŸ‡¸ES
  port: 40433
  uuid: d8fd8955-78db-49ba-d86f-3e4729f6ac4d
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: netflix_MX |41.05Mb
  server: 216.238.89.53
  type: vmess
  country: ðŸ‡²ðŸ‡½MX
  port: 57283
  uuid: 1a5aafc0-6482-451d-fe76-6875b7818579
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_HK |28.85Mb
  server: 58.152.110.154
  type: trojan
  port: 443
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: disney_HK |11.43Mb
  server: 58.152.30.120
  type: trojan
  port: 443
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: disney_netflix_HK |29.85Mb
  server: 58.152.18.95
  type: trojan
  port: 443
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: netflix_NL |74.05Mb
  server: 109.71.246.210
  type: ss
  country: ðŸ‡·ðŸ‡ºRU
  port: 56689
  password: YQCSKoCF3QazW8YlvDBWA4
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_US |37.08Mb
  server: 38.14.99.163
  type: vmess
  country: ðŸ‡ºðŸ‡¸US
  port: 59807
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: auto
  network: tcp
  servername: 38.14.99.163
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ðŸ‡ºðŸ‡¸US_378 |10.46Mb
  server: 45.83.22.118
  type: ss
  country: ðŸ‡ºðŸ‡¸US
  port: 8443
  password: 6af24790-76c9-49d3-bbe0-01285239e57d
  cipher: aes-256-gcm
- name: Relay_-ðŸ‡ºðŸ‡¸US_182 |15.32Mb
  server: clr.ducks.tel
  type: ss
  port: 17844
  password: '907560230'
  cipher: chacha20-ietf-poly1305
- name: ðŸ‡¸ðŸ‡¬SG_376 |10.10Mb
  server: 68.183.178.131
  type: vmess
  country: ðŸ‡¸ðŸ‡¬SG
  port: 58607
  uuid: c11c32cb-27b3-4afa-c0f3-fb250aa4959e
  alterId: 0
  cipher: auto
  network: ws
  servername: www.12333.monster
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /
    headers:
      HOST: www.12333.monster
- name: disney_netflix_US |16.44Mb
  server: cf.fovi.tk
  type: vmess
  country: ðŸZZ
  port: 443
  uuid: bf67437e-6c90-45ca-abc2-c7240a5ce2aa
  alterId: 0
  cipher: auto
  network: ws
  servername: foxlux.fovi.tk
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /eisasqa
    headers:
      HOST: foxlux.fovi.tk
proxy-groups:
- name: ðŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - disney_netflix_GB |159.63Mb
  - disney_netflix_NO |22.06Mb
  - _178 |32.60Mb
  - disney_netflix_FR |173.84Mb
  - Relay_-ðŸ‡·ðŸ‡ºRU_179 |14.81Mb
  - Relay_-ðŸ‡¯ðŸ‡µJP_272 |19.99Mb
  - Relay_-ðŸ‡¯ðŸ‡µJP_271 |20.10Mb
  - disney_netflix_FR |180.46Mb
  - netflix_MX |41.05Mb
  - disney_HK |28.85Mb
  - disney_HK |11.43Mb
  - disney_netflix_HK |29.85Mb
  - netflix_NL |74.05Mb
  - disney_netflix_US |37.08Mb
  - ðŸ‡ºðŸ‡¸US_378 |10.46Mb
  - Relay_-ðŸ‡ºðŸ‡¸US_182 |15.32Mb
  - ðŸ‡¸ðŸ‡¬SG_376 |10.10Mb
  - disney_netflix_US |16.44Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - disney_netflix_GB |159.63Mb
  - disney_netflix_NO |22.06Mb
  - _178 |32.60Mb
  - disney_netflix_FR |173.84Mb
  - Relay_-ðŸ‡·ðŸ‡ºRU_179 |14.81Mb
  - Relay_-ðŸ‡¯ðŸ‡µJP_272 |19.99Mb
  - Relay_-ðŸ‡¯ðŸ‡µJP_271 |20.10Mb
  - disney_netflix_FR |180.46Mb
  - netflix_MX |41.05Mb
  - disney_HK |28.85Mb
  - disney_HK |11.43Mb
  - disney_netflix_HK |29.85Mb
  - netflix_NL |74.05Mb
  - disney_netflix_US |37.08Mb
  - ðŸ‡ºðŸ‡¸US_378 |10.46Mb
  - Relay_-ðŸ‡ºðŸ‡¸US_182 |15.32Mb
  - ðŸ‡¸ðŸ‡¬SG_376 |10.10Mb
  - disney_netflix_US |16.44Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ðŸš€ èŠ‚ç‚¹é€‰æ‹©
