port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: Relay_-ğŸ‡­ğŸ‡°HK_204 |21.16Mb
  server: www.zhoubowen.vip
  type: vmess
  port: 443
  uuid: 71b2655e-07d9-4dad-a770-a2b08275142b
  alterId: 0
  cipher: auto
  network: ws
  servername: www.zhoubowen.vip
  http-opts: {}
  h2-opts: {}
  tls: true
  ws-opts:
    path: /biutefor.icu
    headers:
      Host: www.zhoubowen.vip
- name: _195 |39.62Mb
  server: 163.192.49.195
  type: vmess
  port: 443
  uuid: bcb7c581-3c95-4569-a4e7-918141e91ea3
  alterId: 0
  cipher: auto
  network: http
  http-opts:
    path:
    - /
    headers:
      Host:
      - a.189.cn
  h2-opts: {}
- name: _201 |24.89Mb
  server: 216.227.168.157
  type: vmess
  port: 45237
  uuid: 469e0b31-30c3-4dab-800d-711232634ce1
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _205 |27.04Mb
  server: 51.79.102.253
  type: vmess
  port: 80
  uuid: 58fe1542-5290-40ad-815a-77707a81afe5
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /IOebhLMhl1CTbFHbL95myfRX2
    headers:
      Host: wrmelmwxlf.gktevlrqznwqqozy.fabpfs66gizmnojhcvqxwl.kytrcfzqla87gvgvs6c7kjnrubuh.cc
- name: _197 |173.99Mb
  server: 85.195.101.122
  type: vmess
  port: 40878
  uuid: f3d4167e-b15e-4e46-82e9-9286ef93fda7
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _206 |13.40Mb
  server: 209.126.84.189
  type: vmess
  port: 443
  uuid: 2c981164-9b93-4bca-94ff-b78d3f8498d7
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /vmessws
- name: Relay_-ğŸ‡§ğŸ‡·BR_202 |73.02Mb
  server: pq-brazil1.09vpn.com
  type: vmess
  port: 80
  uuid: c04c3b34-70fd-4fec-963e-c12d09f36bef
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /vmess/
    headers:
      Host: pq-brazil1.09vpn.com
- name: _213 |12.10Mb
  server: 103.127.218.91
  type: vmess
  port: 54693
  uuid: 1cef03ad-6343-408c-8121-cbd1fda2ee9d
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /1cef03ad
- name: _217 |10.22Mb
  server: 54.206.192.9
  type: vmess
  port: 16407
  uuid: 08f45028-1db6-4e93-bf51-d344b6c71e19
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _216 |11.98Mb
  server: 130.162.152.253
  type: vmess
  port: 56867
  uuid: 5206bb9f-2cbc-44ac-de2a-471439a23707
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: disney_HK |25.71Mb
  server: 45.136.12.37
  type: vmess
  port: 38141
  uuid: fd291be6-b48d-43a1-da38-66c7f80e2f80
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: disney_US |36.18Mb
  server: 165.140.216.141
  type: vmess
  port: 443
  uuid: e7d72a8d-26f2-4b54-b366-0c43e0bcba7d
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _225 |22.93Mb
  server: 47.242.140.52
  type: vmess
  port: 34815
  uuid: 1a46b66c-6ba9-4e9c-aa0b-0ebac2b69e32
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /arki
- name: _229 |26.82Mb
  server: 8.218.105.196
  type: vmess
  port: 52752
  uuid: 925bdbf5-72be-4437-bebf-441c61089f6b
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: Pool__271 |169.54Mb
  server: 70.34.218.149
  type: trojan
  port: 11930
  password: BaeSzHdfJIR13l67
  sni: softpillow.silentrocket.click
- name: _244 |11.14Mb
  server: 146.56.112.110
  type: vmess
  port: 8888
  uuid: e7c302f3-90d6-42dd-9d7d-94a3683a3707
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _247 |11.66Mb
  server: 140.238.2.250
  type: vmess
  port: 443
  uuid: 41a7089a-040b-4538-8b8d-010902405bde
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _240 |41.56Mb
  server: 172.235.33.114
  type: vmess
  port: 10001
  uuid: 442a3923-eca1-4af0-b3ff-24a7ce0af68f
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _267 |43.69Mb
  server: 153.121.51.29
  type: trojan
  port: 2890
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: _270 |39.97Mb
  server: 160.16.236.32
  type: trojan
  port: 4054
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: disney_HK |26.04Mb
  server: 58.152.53.174
  type: trojan
  port: 443
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: _257 |43.04Mb
  server: 89.31.120.192
  type: vmess
  port: 443
  uuid: 44537595-9ccc-4b83-8936-5f9ad3229019
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _265 |89.75Mb
  server: 183.236.51.36
  type: vmess
  port: 59003
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 64
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: disney_FR |214.21Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 40433
  uuid: d8fd8955-78db-49ba-d86f-3e4729f6ac4d
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_FR |201.20Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 27092
  uuid: a0596ba6-72a3-4366-8992-77088da65bd8
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: _272 |45.75Mb
  server: 160.16.214.6
  type: trojan
  port: 2890
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¸ğŸ‡¬SG_273 |10.73Mb
  server: 160.16.153.13
  type: trojan
  port: 3145
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: ğŸ‡¬ğŸ‡§GB_285 |115.13Mb
  server: 82.38.31.194
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_290 |12.86Mb
  server: 47.253.197.26
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 12056
  uuid: dd7be7f1-38ff-45e6-f1e5-b20c2190f527
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: _276 |48.72Mb
  server: 160.16.124.55
  type: trojan
  port: 2890
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¸ğŸ‡¬SG_277 |10.77Mb
  server: 160.16.144.208
  type: trojan
  port: 507
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: _278 |14.10Mb
  server: 160.16.196.59
  type: trojan
  port: 2890
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: _281 |11.69Mb
  server: 153.121.65.107
  type: trojan
  port: 3093
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: disney_HK |27.56Mb
  server: 219.78.209.224
  type: trojan
  port: 443
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: netflix_NL |118.70Mb
  server: 82.38.31.191
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_287 |117.92Mb
  server: 82.38.31.217
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡·ğŸ‡ºRU_289 |25.31Mb
  server: 45.129.2.185
  type: ss
  country: ğŸ‡·ğŸ‡ºRU
  port: 10081
  password: c5fcdf7829112cb4
  cipher: aes-256-gcm
- name: disney_HK |19.32Mb
  server: 45.207.157.29
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 13852
  uuid: 845764df-ecb3-4b13-bed2-bf1551b68e9a
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_US |12.80Mb
  server: cf.fovi.tk
  type: vmess
  country: ğŸZZ
  port: 443
  uuid: bf67437e-6c90-45ca-abc2-c7240a5ce2aa
  alterId: 0
  cipher: auto
  network: ws
  servername: foxpol.fovi.tk
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /eisasqa
    headers:
      HOST: foxpol.fovi.tk
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - Relay_-ğŸ‡­ğŸ‡°HK_204 |21.16Mb
  - _195 |39.62Mb
  - _201 |24.89Mb
  - _205 |27.04Mb
  - _197 |173.99Mb
  - _206 |13.40Mb
  - Relay_-ğŸ‡§ğŸ‡·BR_202 |73.02Mb
  - _213 |12.10Mb
  - _217 |10.22Mb
  - _216 |11.98Mb
  - disney_HK |25.71Mb
  - disney_US |36.18Mb
  - _225 |22.93Mb
  - _229 |26.82Mb
  - Pool__271 |169.54Mb
  - _244 |11.14Mb
  - _247 |11.66Mb
  - _240 |41.56Mb
  - _267 |43.69Mb
  - _270 |39.97Mb
  - disney_HK |26.04Mb
  - _257 |43.04Mb
  - _265 |89.75Mb
  - disney_FR |214.21Mb
  - disney_FR |201.20Mb
  - _272 |45.75Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_273 |10.73Mb
  - ğŸ‡¬ğŸ‡§GB_285 |115.13Mb
  - ğŸ‡ºğŸ‡¸US_290 |12.86Mb
  - _276 |48.72Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_277 |10.77Mb
  - _278 |14.10Mb
  - _281 |11.69Mb
  - disney_HK |27.56Mb
  - netflix_NL |118.70Mb
  - ğŸ‡¬ğŸ‡§GB_287 |117.92Mb
  - ğŸ‡·ğŸ‡ºRU_289 |25.31Mb
  - disney_HK |19.32Mb
  - disney_US |12.80Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - Relay_-ğŸ‡­ğŸ‡°HK_204 |21.16Mb
  - _195 |39.62Mb
  - _201 |24.89Mb
  - _205 |27.04Mb
  - _197 |173.99Mb
  - _206 |13.40Mb
  - Relay_-ğŸ‡§ğŸ‡·BR_202 |73.02Mb
  - _213 |12.10Mb
  - _217 |10.22Mb
  - _216 |11.98Mb
  - disney_HK |25.71Mb
  - disney_US |36.18Mb
  - _225 |22.93Mb
  - _229 |26.82Mb
  - Pool__271 |169.54Mb
  - _244 |11.14Mb
  - _247 |11.66Mb
  - _240 |41.56Mb
  - _267 |43.69Mb
  - _270 |39.97Mb
  - disney_HK |26.04Mb
  - _257 |43.04Mb
  - _265 |89.75Mb
  - disney_FR |214.21Mb
  - disney_FR |201.20Mb
  - _272 |45.75Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_273 |10.73Mb
  - ğŸ‡¬ğŸ‡§GB_285 |115.13Mb
  - ğŸ‡ºğŸ‡¸US_290 |12.86Mb
  - _276 |48.72Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_277 |10.77Mb
  - _278 |14.10Mb
  - _281 |11.69Mb
  - disney_HK |27.56Mb
  - netflix_NL |118.70Mb
  - ğŸ‡¬ğŸ‡§GB_287 |117.92Mb
  - ğŸ‡·ğŸ‡ºRU_289 |25.31Mb
  - disney_HK |19.32Mb
  - disney_US |12.80Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
