port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: Relay_-ğŸ‡ºğŸ‡¸US_562 |33.41Mb
  server: us19-25.998998.best
  type: vmess
  port: 443
  udp: true
  uuid: 24254866-770c-41b4-9404-3f50524f425b
  alterId: 0
  cipher: auto
  network: ws
  servername: 24254866-770c-41b4-9404-3f50524f425b.mihomo.baby
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /saoihgreg9384gh8934
    headers:
      Host: 24254866-770c-41b4-9404-3f50524f425b.mihomo.baby
- name: netflix_NL |160.33Mb
  server: 151.242.251.144
  type: ss
  port: 8080
  udp: true
  password: QCXDxuDlTTMD7jtgHUjIoj
  cipher: chacha20-ietf-poly1305
- name: _555 |258.12Mb
  server: 45.87.175.177
  type: ss
  port: 8080
  udp: true
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: Relay_-ğŸ‡³ğŸ‡±NL_544 |349.21Mb
  server: 151.242.251.137
  type: ss
  port: 8080
  password: o5osZg269v5zHpYjr1xY9s
  cipher: chacha20-ietf-poly1305
- name: netflix_NL |144.97Mb
  server: 82.38.31.218
  type: ss
  port: 8080
  udp: true
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: Relay_-ğŸ‡ºğŸ‡¸US_582 |45.00Mb
  server: 141.193.213.199
  type: trojan
  port: 443
  udp: true
  password: a8a5b34d-fe46-487d-bd6a-d9f3101525fd
  sni: 26z68w0ecxbuyf89.ukgogo202511.top
  skip-cert-verify: true
  ws-opts:
    path: /images
    headers:
      Host: 26z68w0ecxbuyf89.ukgogo202511.top
  network: ws
- name: netflix_PL |30.10Mb
  server: 45.15.126.19
  type: ss
  port: 443
  udp: true
  password: 6Ts2ZDTQAf3hkFoB8AFufDwsGrlF4e2t
  cipher: chacha20-ietf-poly1305
- name: Relay_-ğŸ‡³ğŸ‡±NL_568 |11.58Mb
  server: 160.16.214.6
  type: trojan
  port: 4054
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: disney_PT |22.68Mb
  server: 185.231.233.112
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: _552 |27.54Mb
  server: 213.159.67.124
  type: ss
  port: 443
  password: mbhqsStnFQT1cTZYCdsmkugGUC6GT6rp
  cipher: chacha20-ietf-poly1305
- name: Relay_-ğŸ‡ºğŸ‡¸US_567 |33.31Mb
  server: w10.luoli.de
  type: vmess
  port: 443
  udp: true
  uuid: 42a99644-b90b-3627-8809-a2d6c4078b59
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  tls: true
  ws-opts:
    path: /v2ws
    headers:
      Host: w10.luoli.de
- name: Relay_-ğŸ‡¯ğŸ‡µJP_563 |10.98Mb
  server: w13.luoli.de
  type: vmess
  port: 443
  udp: true
  uuid: 42a99644-b90b-3627-8809-a2d6c4078b59
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  tls: true
  ws-opts:
    path: /v2ws
    headers:
      Host: w13.luoli.de
- name: Relay_-ğŸ‡³ğŸ‡±NL_574 |46.36Mb
  server: 18.162.142.242
  type: trojan
  port: 4054
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: disney_FR |138.13Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 27092
  uuid: a0596ba6-72a3-4366-8992-77088da65bd8
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡ºğŸ‡¸US_600 |44.58Mb
  server: pupas-shirting-unsung.freesocks.work
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: p78naCf2EfOlRSLTX0wFVx
  cipher: chacha20-ietf-poly1305
- name: netflix_NL |356.07Mb
  server: 151.242.251.144
  type: ss
  country: ğŸ‡®ğŸ‡· IR
  port: 8080
  password: 4a2rfixophdjffa8KVA4Aa
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸ‡®ğŸ‡· IR-ğŸ‡³ğŸ‡±NL_595 |303.14Mb
  server: 151.242.251.153
  type: ss
  country: ğŸ‡®ğŸ‡· IR
  port: 8080
  password: QCXDxuDlTTMD7jtgHUjIoj
  cipher: chacha20-ietf-poly1305
- name: _584 |28.23Mb
  server: 37.18.14.33
  type: trojan
  port: 443
  udp: true
  password: Qzy7tgpRhu
  sni: m.vk.com
  skip-cert-verify: true
- name: Relay_-ğŸ‡­ğŸ‡°HK_587 |10.25Mb
  server: green2.cdntencentmusic.com
  type: trojan
  port: 31102
  udp: true
  password: 4a269dea-f3dd-48d8-86aa-39596e68d71d
  sni: green2.cdntencentmusic.com
  skip-cert-verify: true
- name: Relay_-ğŸ‡­ğŸ‡°HK_572 |10.37Mb
  server: green2.cdntencentmusic.com
  type: trojan
  port: 31102
  udp: true
  password: 040073da-c543-43b9-849c-61992a6e0838
  sni: green2.cdntencentmusic.com
  skip-cert-verify: true
- name: disney_MD |11.97Mb
  server: 185.153.197.5
  type: ss
  country: ğŸ‡·ğŸ‡ºRU
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: disney_PY |11.50Mb
  server: 38.165.233.93
  type: ss
  country: ğŸ‡ºğŸ‡¸ US
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: Relay_-ğŸ‡ºğŸ‡¸US_583 |10.10Mb
  server: jp3.t.sgateway.link
  type: trojan
  port: 5223
  udp: true
  password: Q9gofGxinwLv0TfDfdKmdttdPGxrhKQS
  sni: pod-jp-z1.psusercontent.com
  skip-cert-verify: true
- name: Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_602 |35.81Mb
  server: sw19.sesamebuta.top
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  uuid: 805ba514-bf2f-4d5d-df49-8417804e8de3
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /abcd
- name: Relay_ğŸ‡¯ğŸ‡µJP-ğŸ‡¯ğŸ‡µJP_596 |11.53Mb
  server: xray.kk37005.tk
  type: vmess
  country: ğŸ‡¯ğŸ‡µJP
  port: 55919
  uuid: 2e7548bb-7c5b-4d97-d64d-1b2fe4050089
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - Relay_-ğŸ‡ºğŸ‡¸US_562 |33.41Mb
  - netflix_NL |160.33Mb
  - _555 |258.12Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_544 |349.21Mb
  - netflix_NL |144.97Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_582 |45.00Mb
  - netflix_PL |30.10Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_568 |11.58Mb
  - disney_PT |22.68Mb
  - _552 |27.54Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_567 |33.31Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_563 |10.98Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_574 |46.36Mb
  - disney_FR |138.13Mb
  - ğŸ‡ºğŸ‡¸US_600 |44.58Mb
  - netflix_NL |356.07Mb
  - Relay_ğŸ‡®ğŸ‡· IR-ğŸ‡³ğŸ‡±NL_595 |303.14Mb
  - _584 |28.23Mb
  - Relay_-ğŸ‡­ğŸ‡°HK_587 |10.25Mb
  - Relay_-ğŸ‡­ğŸ‡°HK_572 |10.37Mb
  - disney_MD |11.97Mb
  - disney_PY |11.50Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_583 |10.10Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_602 |35.81Mb
  - Relay_ğŸ‡¯ğŸ‡µJP-ğŸ‡¯ğŸ‡µJP_596 |11.53Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - Relay_-ğŸ‡ºğŸ‡¸US_562 |33.41Mb
  - netflix_NL |160.33Mb
  - _555 |258.12Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_544 |349.21Mb
  - netflix_NL |144.97Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_582 |45.00Mb
  - netflix_PL |30.10Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_568 |11.58Mb
  - disney_PT |22.68Mb
  - _552 |27.54Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_567 |33.31Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_563 |10.98Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_574 |46.36Mb
  - disney_FR |138.13Mb
  - ğŸ‡ºğŸ‡¸US_600 |44.58Mb
  - netflix_NL |356.07Mb
  - Relay_ğŸ‡®ğŸ‡· IR-ğŸ‡³ğŸ‡±NL_595 |303.14Mb
  - _584 |28.23Mb
  - Relay_-ğŸ‡­ğŸ‡°HK_587 |10.25Mb
  - Relay_-ğŸ‡­ğŸ‡°HK_572 |10.37Mb
  - disney_MD |11.97Mb
  - disney_PY |11.50Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_583 |10.10Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_602 |35.81Mb
  - Relay_ğŸ‡¯ğŸ‡µJP-ğŸ‡¯ğŸ‡µJP_596 |11.53Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
