port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: netflix_MX |170.60Mb
  server: 216.238.87.47
  type: vmess
  country: ğŸ‡²ğŸ‡½MX
  port: 27502
  uuid: b8155ce4-7e08-4c40-800f-8671312b7124
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_JP |20.95Mb
  server: 160.16.72.33
  type: trojan
  port: 3093
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: netflix_NL |122.94Mb
  server: 45.14.245.2
  type: ss
  port: 443
  password: 17ZDORWIliQHuO6WRGHChXYMzdRtAYVP
  cipher: chacha20-ietf-poly1305
- name: netflix_DE |79.10Mb
  server: 45.80.188.48
  type: vmess
  port: 50255
  uuid: bc140c02-25a9-4feb-96bb-7d772b17fd17
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
- name: _41 |163.53Mb
  server: 38.165.233.93
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: netflix_NG |47.14Mb
  server: 176.97.192.4
  type: vmess
  port: 35227
  uuid: 5dd60293-2743-422d-aa73-08823eb5167e
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - netflix_MX |170.60Mb
  - disney_netflix_JP |20.95Mb
  - netflix_NL |122.94Mb
  - netflix_DE |79.10Mb
  - _41 |163.53Mb
  - netflix_NG |47.14Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - netflix_MX |170.60Mb
  - disney_netflix_JP |20.95Mb
  - netflix_NL |122.94Mb
  - netflix_DE |79.10Mb
  - _41 |163.53Mb
  - netflix_NG |47.14Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
