port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: ğŸ‡¦ğŸ‡ªAE_167 | 7.41Mb
  type: vmess
  server: 89.31.120.192
  port: 443
  uuid: 44537595-9ccc-4b83-8936-5f9ad3229019
  alterId: 0
  cipher: auto
  udp: true
- name: Relay_ğŸ‡¦ğŸ‡¹AT-ğŸ‡«ğŸ‡·FR_172
  type: vmess
  server: 46.29.34.205
  port: 59956
  uuid: ca0c9937-58a6-44ea-9111-a6abac267d0f
  alterId: 0
  cipher: auto
  udp: true
- name: ğŸ‡¨ğŸ‡¦CA_195 | 1.73Mb
  type: vmess
  server: 51.79.102.253
  port: 80
  uuid: 58fe1542-5290-40ad-815a-77707a81afe5
  alterId: 0
  cipher: auto
  udp: true
  network: ws
  ws-opts:
    path: /IOebhLMhl1CTbFHbL95myfRX2
    headers:
      Host: ''
- name: ğŸ‡¨ğŸ‡¦CA_196 |10.36Mb
  type: vmess
  server: 51.222.158.243
  port: 8443
  uuid: 4b0df213-0e59-4c16-b391-e0d97686bfa9
  alterId: 0
  cipher: auto
  udp: true
  network: ws
  ws-opts:
    path: /vmess/
    headers:
      Host: ''
  tls: true
- name: ğŸ‡¨ğŸ‡¦CA_197 |225.04Mb
  type: vmess
  server: 51.79.86.182
  port: 42610
  uuid: e0957ca6-f613-4017-ff3c-effd1da8871a
  alterId: 0
  cipher: auto
  udp: true
- name: ğŸ‡¨ğŸ‡¦CA_198 |12.84Mb
  type: vmess
  server: 51.79.103.76
  port: 80
  uuid: 58fe1542-5290-40ad-815a-77707a81afe5
  alterId: 0
  cipher: auto
  udp: true
  network: ws
  ws-opts:
    path: /IOebhLMhl1CTbFHbL95myfRX2
    headers:
      Host: wrmelmwxlf.gktevlrqznwqqozy.fabpfs66gizmnojhcvqxwl.kytrcfzqla87gvgvs6c7kjnrubuh.cc
- name: ğŸ‡¨ğŸ‡³CN_204 | 2.00Mb
  type: vmess
  server: 120.210.205.59
  port: 50002
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 64
  cipher: auto
  udp: true
- name: ğŸ‡¨ğŸ‡³CN_205 | 3.08Mb
  type: vmess
  server: 120.26.55.225
  port: 50112
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 64
  cipher: auto
  udp: true
- name: ğŸ‡¨ğŸ‡³CN_206 | 3.10Mb
  type: vmess
  server: 106.14.75.114
  port: 50002
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 64
  cipher: auto
  udp: true
- name: ğŸ‡¨ğŸ‡³CN_207 | 5.43Mb
  type: vmess
  server: 112.132.215.34
  port: 50007
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: auto
  udp: true
- name: ğŸ‡¨ğŸ‡³CN_208 | 3.02Mb
  type: vmess
  server: 39.107.155.11
  port: 30302
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 64
  cipher: auto
  udp: true
- name: ğŸ‡©ğŸ‡ªDE_245 | 1.98Mb
  type: vmess
  server: 94.136.185.230
  port: 10534
  uuid: b01c7ef9-33ec-41f6-bfbf-77ddc4d21649
  alterId: 0
  cipher: auto
  udp: true
- name: ğŸ‡©ğŸ‡ªDE_246 | 2.59Mb
  type: vmess
  server: 62.146.235.193
  port: 28011
  uuid: cfc5a87f-3c13-4e25-b556-176cdd6b5c6a
  alterId: 0
  cipher: auto
  udp: true
- name: ğŸ‡©ğŸ‡ªDE_247 | 0.99Mb
  type: vmess
  server: 82.197.69.131
  port: 39674
  uuid: 5a89386a-827b-4f54-8778-2f1b5122c6ef
  alterId: 0
  cipher: auto
  udp: true
- name: ğŸ‡©ğŸ‡ªDE_248 | 4.20Mb
  type: vmess
  server: 85.195.101.122
  port: 40878
  uuid: f3d4167e-b15e-4e46-82e9-9286ef93fda7
  alterId: 0
  cipher: auto
  udp: true
- name: Relay_ğŸ‡©ğŸ‡ªDE-ğŸ‡©ğŸ‡ªDE_249 |12.26Mb
  type: vmess
  server: cpanel.erade32.ir
  port: 100
  uuid: 0888adea-086c-4783-9989-85df86819c1f
  alterId: 0
  cipher: auto
  udp: true
- name: ğŸ‡«ğŸ‡·FR_277
  type: vmess
  server: 5.196.29.123
  port: 2082
  uuid: 112ac36f-3f53-4e26-8371-d25c028e1b9a
  alterId: 0
  cipher: auto
  udp: true
  network: ws
  ws-opts:
    path: /
    headers:
      Host: ''
- name: ğŸ‡«ğŸ‡·FR_278
  type: vmess
  server: 135.125.182.74
  port: 28213
  uuid: 81852771-76fb-4e94-e4f1-4e37a698a49a
  alterId: 0
  cipher: auto
  udp: true
- name: ğŸ‡¬ğŸ‡§GB_307 | 8.51Mb
  type: vmess
  server: 216.173.69.250
  port: 8443
  uuid: 91382092-2330-455b-8a1c-9c129cfe661a
  alterId: 0
  cipher: auto
  udp: true
  network: ws
  ws-opts:
    path: /
    headers:
      Host: ''
- name: Relay_ğŸ‡¬ğŸ‡§GB-ğŸ‡ºğŸ‡¸US_309 | 9.78Mb
  type: vmess
  server: 25.129.196.249
  port: 8880
  uuid: d5ed323c-019e-37c7-b7a7-cf7dc699e9c4
  alterId: 0
  cipher: auto
  udp: true
  network: ws
  ws-opts:
    path: /dabai&Telegram%F0%9F%87%A8%F0%9F%87%B3%20@WangCai2%20/
    headers:
      Host: TG.WangCai2.s2.db-link02.top
- name: Relay_ğŸ‡¬ğŸ‡§GB-ğŸ‡ºğŸ‡¸US_310 |16.09Mb
  type: vmess
  server: 25.25.25.249
  port: 8880
  uuid: c8c50f25-6eea-3645-967b-b48e12e0c99b
  alterId: 0
  cipher: auto
  udp: true
  network: ws
  ws-opts:
    path: /dabai&Telegram%F0%9F%87%A8%F0%9F%87%B3%20@WangCai2%20/
    headers:
      Host: TG.WangCai2.s2.db-link02.top
- name: Relay_ğŸ‡¬ğŸ‡§GB-ğŸ‡ºğŸ‡¸US_311 |83.83Mb
  type: vmess
  server: 25.129.198.249
  port: 8880
  uuid: 53ec5471-532d-371f-a499-c152006493b8
  alterId: 0
  cipher: auto
  udp: true
  network: ws
  ws-opts:
    path: /dabai&Telegram%F0%9F%87%A8%F0%9F%87%B3%20@WangCai2%20/
    headers:
      Host: TG.WangCai2.s2.db-link02.top
- name: ğŸ‡¬ğŸ‡§GB_312 | 6.81Mb
  type: vmess
  server: 51.38.64.209
  port: 44023
  uuid: 7da457da-ed0f-437d-c81d-6c35885bbea3
  alterId: 0
  cipher: auto
  udp: true
- name: Relay_ğŸ‡­ğŸ‡°HK-ğŸ‡­ğŸ‡°HK_331
  type: vmess
  server: 1e426046-t0fds0-t12cnj-1ol97.hk.p5pv.com
  port: 80
  uuid: 93fb69fc-77cf-11ee-85ee-f23c91369f2d
  alterId: 2
  cipher: auto
  udp: true
  network: ws
  ws-opts:
    path: /
    headers:
      Host: broadcastlv.chat.bilibili.com
- name: ğŸ‡®ğŸ‡©ID_335 | 7.95Mb
  type: vmess
  server: 154.90.49.57
  port: 58868
  uuid: fbffeb6b-b5e5-4f77-8888-c7919fbeb0ad
  alterId: 0
  cipher: auto
  udp: true
- name: Relay_ğŸ‡®ğŸ‡©ID-ğŸ‡®ğŸ‡©ID_336 | 9.23Mb
  type: vmess
  server: id-sep4th.wimax.cc
  port: 443
  uuid: 113b5339-c438-4aad-9066-68c445a0e238
  alterId: 0
  cipher: auto
  udp: true
  network: ws
  ws-opts:
    path: /prayer-times/today
    headers:
      Host: id-sep4th.wimax.cc
  tls: true
  servername: id-sep4th.wimax.cc
- name: ğŸ‡®ğŸ‡³IN_345 | 1.29Mb
  type: vmess
  server: 188.208.141.177
  port: 443
  uuid: 0970834f-5b4d-44da-d890-19dcb2a72d4c
  alterId: 0
  cipher: auto
  udp: true
- name: ğŸ‡®ğŸ‡¶IQ_346 | 2.21Mb
  type: vmess
  server: 154.93.37.21
  port: 443
  uuid: 64a37ce5-e713-4ad4-c1de-b68761e9fef6
  alterId: 0
  cipher: auto
  udp: true
- name: ğŸ‡²ğŸ‡¾MY_448
  type: vmess
  server: 103.186.117.229
  port: 45497
  uuid: 2e257f9c-fa0e-442f-f53c-6a452924c0c2
  alterId: 0
  cipher: auto
  udp: true
- name: ğŸ‡µğŸ‡±PL_559
  type: vmess
  server: 51.68.191.233
  port: 80
  uuid: f0eda072-9ae8-494c-a495-215fa5729467
  alterId: 0
  cipher: auto
  udp: true
  network: ws
  ws-opts:
    path: /vmess/
    headers:
      Host: ''
- name: ğŸ‡·ğŸ‡ºRU_597 |11.44Mb
  type: vmess
  server: 45.67.230.79
  port: 11052
  uuid: 314185f7-931d-4656-922d-0857e7afd224
  alterId: 0
  cipher: auto
  udp: true
- name: ğŸ‡¸ğŸ‡¬SG_622 |43.05Mb
  type: vmess
  server: 15.235.41.200
  port: 80
  uuid: 58fe1542-5290-40ad-815a-77707a81afe5
  alterId: 0
  cipher: auto
  udp: true
  network: ws
  ws-opts:
    path: /IOebhLMhl1CTbFHbL95myfRX2
    headers:
      Host: google.com
- name: ğŸ‡¹ğŸ‡¼TW_630 | 8.47Mb
  type: vmess
  server: 165.154.195.38
  port: 35034
  uuid: 959a8caf-4cea-43d0-a548-3628e7ddfafc
  alterId: 0
  cipher: auto
  udp: true
- name: ğŸ‡¹ğŸ‡¼TW_631 |44.21Mb
  type: vmess
  server: 103.61.139.137
  port: 20521
  uuid: f8d93cfb-3d5d-447c-a697-16496dd74697
  alterId: 0
  cipher: auto
  udp: true
  network: ws
  ws-opts:
    path: /
    headers:
      Host: ''
- name: disney_US | 7.73Mb
  type: vmess
  server: 165.140.216.141
  port: 443
  uuid: e7d72a8d-26f2-4b54-b366-0c43e0bcba7d
  alterId: 0
  cipher: auto
  udp: true
- name: ğŸ‡ºğŸ‡¸US_808 | 3.26Mb
  type: vmess
  server: 62.60.187.28
  port: 20086
  uuid: 570b4cfc-80d5-4277-8c97-8444ba0689b9
  alterId: 0
  cipher: auto
  udp: true
  network: ws
  ws-opts:
    path: /
    headers:
      Host: ''
- name: ğŸ‡ºğŸ‡¸US_809 | 4.92Mb
  type: vmess
  server: 15.204.11.190
  port: 15361
  uuid: 5d7bf9e3-415c-40f3-c66d-a54ea0fd860e
  alterId: 0
  cipher: auto
  udp: true
- name: Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_810 | 1.86Mb
  type: vmess
  server: 38.12.83.217
  port: 30002
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 64
  cipher: auto
  udp: true
- name: ğŸ‡ºğŸ‡¸US_812 |13.06Mb
  type: vmess
  server: 137.175.124.167
  port: 20086
  uuid: b4bce500-11fe-4f8f-a344-01ac247af9bd
  alterId: 0
  cipher: auto
  udp: true
  network: ws
  ws-opts:
    path: /
    headers:
      Host: ''
- name: disney_US | 3.29Mb
  type: vmess
  server: 107.172.5.52
  port: 35703
  uuid: 420c92f0-16db-4306-8129-935bd942897e
  alterId: 0
  cipher: auto
  udp: true
- name: ğŸ‡ºğŸ‡¸US_814 |14.92Mb
  type: vmess
  server: 206.206.80.227
  port: 20086
  uuid: 0abb7b9e-81ba-4336-8ca7-056866032ff3
  alterId: 0
  cipher: auto
  udp: true
  network: ws
  ws-opts:
    path: /
    headers:
      Host: ''
- name: disney_US |164.15Mb
  type: vmess
  server: 2.58.87.221
  port: 12269
  uuid: db85ff0e-c33f-401d-c415-4c7cce135704
  alterId: 0
  cipher: auto
  udp: true
  network: ws
  ws-opts:
    path: /
    headers:
      Host: ''
- name: ğŸ‡ºğŸ‡¸US_816 |14.88Mb
  type: vmess
  server: 15.204.234.200
  port: 41100
  uuid: c7f169a3-2e9a-4894-ba53-7b2fa6fd08b4
  alterId: 0
  cipher: auto
  udp: true
- name: ğŸ‡ºğŸ‡¸US_817 |13.01Mb
  type: vmess
  server: 206.119.191.9
  port: 7998
  uuid: 984429ed-3959-4022-e248-cbcb19c96f9a
  alterId: 0
  cipher: auto
  udp: true
- name: disney_US |451.42Mb
  type: vmess
  server: 2.58.87.221
  port: 46628
  uuid: f6ba9e5a-711c-496f-be60-ac5464dec2b8
  alterId: 0
  cipher: auto
  udp: true
- name: ğŸ‡ºğŸ‡¸US_819 |83.58Mb
  type: vmess
  server: 172.233.171.224
  port: 16416
  uuid: 8c1b9bea-cb51-43bb-a65c-0af31bbbf145
  alterId: 0
  cipher: auto
  udp: true
- name: ğŸ‡ºğŸ‡¸US_820
  type: vmess
  server: 45.128.54.84
  port: 37313
  uuid: 72feb833-4196-4a70-a3f5-aeb011f7d534
  alterId: 0
  cipher: auto
  udp: true
- name: ğŸZZ_845 |42.25Mb
  type: vmess
  server: npmjs.com
  port: 8080
  uuid: jrghxqxyoy
  alterId: 0
  cipher: auto
  udp: true
  network: ws
  ws-opts:
    path: /download/cdn
    headers:
      Host: jrghxqxyoy-518237151.zamam.co
- name: Relay_ğŸZZ-ğŸ‡¬ğŸ‡§GB_846 | 4.19Mb
  type: vmess
  server: test3.flha.ru
  port: 80
  uuid: 9a81340d-f81b-4c76-8abb-f4d305c535c0
  alterId: 0
  cipher: auto
  udp: true
  network: ws
  ws-opts:
    path: /9a81340d-f81b-4c76-8abb-f4d305c535c0-vmess
    headers:
      Host: test3.flha.ru
- name: ğŸZZ_847 |22.95Mb
  type: vmess
  server: npmjs.com
  port: 8080
  uuid: vw6hjp6qlg
  alterId: 0
  cipher: auto
  udp: true
  network: ws
  ws-opts:
    path: /download/cdn
    headers:
      Host: vw6hjp6qlg-525340125.zamam.co
- name: ğŸZZ_848 |24.61Mb
  type: vmess
  server: npmjs.com
  port: 8080
  uuid: pmxnbcrrfd
  alterId: 0
  cipher: auto
  udp: true
  network: ws
  ws-opts:
    path: /download/cdn
    headers:
      Host: pmxnbcrrfd-4515167105.zamam.co
- name: ğŸZZ_849 |27.63Mb
  type: vmess
  server: npmjs.com
  port: 8080
  uuid: d3m1xvk50k
  alterId: 0
  cipher: auto
  udp: true
  network: ws
  ws-opts:
    path: /download/cdn
    headers:
      Host: d3m1xvk50k-525340173.zamam.co
- name: Relay_ğŸZZ-ğŸ‡ºğŸ‡¸US_850 | 3.63Mb
  type: vmess
  server: 104.17.221.248
  port: 8080
  uuid: a1a607e6-a04c-3db6-a36f-c2a4312e2fe1
  alterId: 0
  cipher: auto
  udp: true
  network: ws
  ws-opts:
    path: /dabai.in104.24.181.249
    headers:
      Host: 100-54-104-116.s1.cn-db.top
- name: Relay_ğŸZZ-ğŸ‡¹ğŸ‡¼TW_851
  type: vmess
  server: api.jquery.com
  port: 443
  uuid: 56529ad8-61d2-4bfa-aa0b-a800719cb5fe
  alterId: 0
  cipher: auto
  udp: true
  network: ws
  ws-opts:
    path: /tw.niskakowski.ggff.net/aa
    headers:
      Host: admin.kasrax.ir
  tls: true
  servername: admin.kasrax.ir
- name: Relay_ğŸZZ-ğŸ‡©ğŸ‡ªDE_852 |41.48Mb
  type: vmess
  server: npmjs.com
  port: 8080
  uuid: nasnet
  alterId: 0
  cipher: auto
  udp: true
  network: ws
  ws-opts:
    path: /NASNET/cdn
    headers:
      Host: nasnet-4515017475.mashallahbet.com
- name: ğŸZZ_853 | 5.60Mb
  type: vmess
  server: 161.248.30.3
  port: 20086
  uuid: 1006a928-2021-4a3b-beb5-d5853c6281c5
  alterId: 0
  cipher: auto
  udp: true
  network: ws
  ws-opts:
    path: /
    headers:
      Host: ''
proxy-groups:
- name: Proxy
  type: select
  proxies:
  - ğŸ‡¦ğŸ‡ªAE_167 | 7.41Mb
  - Relay_ğŸ‡¦ğŸ‡¹AT-ğŸ‡«ğŸ‡·FR_172
  - ğŸ‡¨ğŸ‡¦CA_195 | 1.73Mb
  - ğŸ‡¨ğŸ‡¦CA_196 |10.36Mb
  - ğŸ‡¨ğŸ‡¦CA_197 |225.04Mb
  - ğŸ‡¨ğŸ‡¦CA_198 |12.84Mb
  - ğŸ‡¨ğŸ‡³CN_204 | 2.00Mb
  - ğŸ‡¨ğŸ‡³CN_205 | 3.08Mb
  - ğŸ‡¨ğŸ‡³CN_206 | 3.10Mb
  - ğŸ‡¨ğŸ‡³CN_207 | 5.43Mb
  - ğŸ‡¨ğŸ‡³CN_208 | 3.02Mb
  - ğŸ‡©ğŸ‡ªDE_245 | 1.98Mb
  - ğŸ‡©ğŸ‡ªDE_246 | 2.59Mb
  - ğŸ‡©ğŸ‡ªDE_247 | 0.99Mb
  - ğŸ‡©ğŸ‡ªDE_248 | 4.20Mb
  - Relay_ğŸ‡©ğŸ‡ªDE-ğŸ‡©ğŸ‡ªDE_249 |12.26Mb
  - ğŸ‡«ğŸ‡·FR_277
  - ğŸ‡«ğŸ‡·FR_278
  - ğŸ‡¬ğŸ‡§GB_307 | 8.51Mb
  - Relay_ğŸ‡¬ğŸ‡§GB-ğŸ‡ºğŸ‡¸US_309 | 9.78Mb
  - Relay_ğŸ‡¬ğŸ‡§GB-ğŸ‡ºğŸ‡¸US_310 |16.09Mb
  - Relay_ğŸ‡¬ğŸ‡§GB-ğŸ‡ºğŸ‡¸US_311 |83.83Mb
  - ğŸ‡¬ğŸ‡§GB_312 | 6.81Mb
  - Relay_ğŸ‡­ğŸ‡°HK-ğŸ‡­ğŸ‡°HK_331
  - ğŸ‡®ğŸ‡©ID_335 | 7.95Mb
  - Relay_ğŸ‡®ğŸ‡©ID-ğŸ‡®ğŸ‡©ID_336 | 9.23Mb
  - ğŸ‡®ğŸ‡³IN_345 | 1.29Mb
  - ğŸ‡®ğŸ‡¶IQ_346 | 2.21Mb
  - ğŸ‡²ğŸ‡¾MY_448
  - ğŸ‡µğŸ‡±PL_559
  - ğŸ‡·ğŸ‡ºRU_597 |11.44Mb
  - ğŸ‡¸ğŸ‡¬SG_622 |43.05Mb
  - ğŸ‡¹ğŸ‡¼TW_630 | 8.47Mb
  - ğŸ‡¹ğŸ‡¼TW_631 |44.21Mb
  - disney_US | 7.73Mb
  - ğŸ‡ºğŸ‡¸US_808 | 3.26Mb
  - ğŸ‡ºğŸ‡¸US_809 | 4.92Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_810 | 1.86Mb
  - ğŸ‡ºğŸ‡¸US_812 |13.06Mb
  - disney_US | 3.29Mb
  - ğŸ‡ºğŸ‡¸US_814 |14.92Mb
  - disney_US |164.15Mb
  - ğŸ‡ºğŸ‡¸US_816 |14.88Mb
  - ğŸ‡ºğŸ‡¸US_817 |13.01Mb
  - disney_US |451.42Mb
  - ğŸ‡ºğŸ‡¸US_819 |83.58Mb
  - ğŸ‡ºğŸ‡¸US_820
  - ğŸZZ_845 |42.25Mb
  - Relay_ğŸZZ-ğŸ‡¬ğŸ‡§GB_846 | 4.19Mb
  - ğŸZZ_847 |22.95Mb
  - ğŸZZ_848 |24.61Mb
  - ğŸZZ_849 |27.63Mb
  - Relay_ğŸZZ-ğŸ‡ºğŸ‡¸US_850 | 3.63Mb
  - Relay_ğŸZZ-ğŸ‡¹ğŸ‡¼TW_851
  - Relay_ğŸZZ-ğŸ‡©ğŸ‡ªDE_852 |41.48Mb
  - ğŸZZ_853 | 5.60Mb
  url: https://www.google.com/generate_204
rules:
- GEOIP,CN,DIRECT
- MATCH,Proxy
