port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: ğŸ‡¨ğŸ‡¦CA_269 |183.39Mb
  server: 138.197.153.10
  type: ss
  country: ğŸ‡¨ğŸ‡¦CA
  port: 8080
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: ğŸ‡¨ğŸ‡¦CA_271 |10.34Mb
  server: 132.145.102.60
  type: ss
  country: ğŸ‡¨ğŸ‡¦CA
  port: 21001
  password: 2a6c0365-e3ed-4aef-81ca-b1b6b46088da
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¨ğŸ‡¦CA_272 |157.19Mb
  server: 138.197.165.21
  type: ss
  country: ğŸ‡¨ğŸ‡¦CA
  port: 8080
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: Relay_ğŸ‡¨ğŸ‡¦CA-ğŸ‡¨ğŸ‡¦CA_274 |10.14Mb
  server: ca07.giamping.com
  type: ss
  country: ğŸ‡¨ğŸ‡¦CA
  port: 8080
  password: 42000e02-6b4d-46ad-a572-80db7db2a9ce
  cipher: chacha20-ietf-poly1305
- name: _251 |10.15Mb
  server: 196.196.192.58
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸ‡¨ğŸ‡¦CA-ğŸ‡¨ğŸ‡¦CA_275 |138.00Mb
  server: ssca.irundns.net
  type: ssr
  country: ğŸ‡¨ğŸ‡¦CA
  port: 443
  password: $$Turb0VPN$$
  cipher: aes-128-cfb
  protocol: auth_aes128_md5
  obfs: http_post
- name: ğŸ‡¦ğŸ‡«AF_256 |10.11Mb
  server: 121.127.45.165
  type: ss
  country: ğŸ‡¦ğŸ‡«AF
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _247 |10.15Mb
  server: 37.143.129.98
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _242 |11.40Mb
  server: 89.46.233.36
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¦ğŸ‡·AR_257 |163.08Mb
  server: 190.103.176.32
  type: ss
  country: ğŸ‡¦ğŸ‡·AR
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ğŸ‡¨ğŸ‡¿CZ_284 |10.02Mb
  server: 195.181.160.6
  type: ss
  country: ğŸ‡¨ğŸ‡¿CZ
  port: 990
  password: f8f7aCzcPKbsF8p3
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¦ğŸ‡ºAU_263 |10.10Mb
  server: 3.27.81.63
  type: ss
  country: ğŸ‡¦ğŸ‡ºAU
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡¦ğŸ‡ºAU_259 |10.24Mb
  server: 3.25.198.142
  type: ss
  country: ğŸ‡¦ğŸ‡ºAU
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡©ğŸ‡°DK_293 |10.15Mb
  server: 192.36.27.94
  type: ss
  country: ğŸ‡©ğŸ‡°DK
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ğŸ‡§ğŸ‡·BR_268 |11.32Mb
  server: 154.90.62.168
  type: ss
  country: ğŸ‡§ğŸ‡·BR
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ğŸ‡¬ğŸ‡§GB_310 |10.23Mb
  server: 79.127.233.170
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: Pool_ğŸ‡¬ğŸ‡§GB_317 |10.15Mb
  server: 64.176.184.129
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 1866
  password: oXGp1+ihlfKg826H
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡«ğŸ‡·FR_299 |138.26Mb
  server: 83.147.216.70
  type: ss
  country: ğŸ‡«ğŸ‡·FR
  port: 64519
  password: YXgS8ComTam7qoesPlzlMo
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡«ğŸ‡·FR_300 |155.03Mb
  server: 83.147.216.70
  type: ss
  country: ğŸ‡«ğŸ‡·FR
  port: 64519
  password: Mal9DeKnSFhULd5Nbpkae0
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_318 |73.94Mb
  server: 89.185.84.185
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: DkH7uO7t90Uw4D95zgZVdV
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_319 |73.62Mb
  server: 89.185.84.185
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: MFZdcVQe5UQtzAzQekyMcD
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_324 |10.32Mb
  server: 141.98.101.181
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: shadowsocks
  cipher: aes-128-gcm
- name: ğŸ‡¬ğŸ‡§GB_323 |73.42Mb
  server: 89.185.84.185
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: JP45VRXJqp1E1G2Wr6MSbR
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡­ğŸ‡ºHU_333 |10.02Mb
  server: 109.61.46.43
  type: ss
  country: ğŸ‡­ğŸ‡ºHU
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡©ğŸ‡ªDE_292 |86.47Mb
  server: 94.136.185.230
  type: vmess
  country: ğŸ‡©ğŸ‡ªDE
  port: 10534
  uuid: b01c7ef9-33ec-41f6-bfbf-77ddc4d21649
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡®ğŸ‡·IR_381 |10.07Mb
  server: 151.242.251.147
  type: ss
  country: ğŸ‡®ğŸ‡·IR
  port: 8080
  password: o5osZg269v5zHpYjr1xY9s
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡®ğŸ‡³IN_335 |40.34Mb
  server: 13.233.190.89
  type: ss
  country: ğŸ‡®ğŸ‡³IN
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: Relay_ğŸ‡®ğŸ‡·IR-ğŸ‡³ğŸ‡±NL_383 |10.09Mb
  server: 151.242.251.137
  type: ss
  country: ğŸ‡®ğŸ‡·IR
  port: 8080
  password: 4a2rfixophdjffa8KVA4Aa
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡®ğŸ‡³IN_336 |39.75Mb
  server: 65.2.189.85
  type: ss
  country: ğŸ‡®ğŸ‡³IN
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡®ğŸ‡³IN_338 |40.88Mb
  server: 13.126.253.30
  type: ss
  country: ğŸ‡®ğŸ‡³IN
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡®ğŸ‡³IN_337 |41.04Mb
  server: 43.205.237.107
  type: ss
  country: ğŸ‡®ğŸ‡³IN
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡®ğŸ‡³IN_339 |20.80Mb
  server: 13.233.212.186
  type: ss
  country: ğŸ‡®ğŸ‡³IN
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡®ğŸ‡·IR_388 |10.11Mb
  server: 151.242.251.147
  type: ss
  country: ğŸ‡®ğŸ‡·IR
  port: 8080
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡®ğŸ‡¹IT_389 |10.02Mb
  server: 212.102.54.45
  type: ss
  country: ğŸ‡®ğŸ‡¹IT
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡­ğŸ‡°HK_332 |44.40Mb
  server: 103.243.25.213
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 21533
  uuid: 6d4e2341-e33d-428d-bc70-1461592ab1a2
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
  ws-opts:
    path: /arki?ed=2048
- name: Pool_ğŸ‡­ğŸ‡°HK_329 |170.00Mb
  server: 150.107.46.21
  type: ssr
  country: ğŸ‡­ğŸ‡°HK
  port: 8083
  password: iFqnzSscN
  cipher: aes-256-cfb
  protocol: origin
  obfs: tls1.2_ticket_auth
- name: ğŸ‡±ğŸ‡¹LT_400 |10.62Mb
  server: 45.87.175.188
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: QCXDxuDlTTMD7jtgHUjIoj
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_406 |13.16Mb
  server: 45.87.175.188
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: 1RWwXhwfAB5gAEozU4G2Pg
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_405 |10.17Mb
  server: 45.87.175.171
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: QCXDxuDlTTMD7jtgHUjIoj
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_410 |10.08Mb
  server: 45.87.175.171
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: 1RWwXhwfAB5gAEozU4G2Pg
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡²ğŸ‡½MX_419 |10.51Mb
  server: 147.78.1.230
  type: ss
  country: ğŸ‡²ğŸ‡½MX
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ğŸ‡¯ğŸ‡µJP_391 |10.36Mb
  server: 160.16.123.124
  type: ss
  country: ğŸ‡¯ğŸ‡µJP
  port: 10087
  password: '10086'
  cipher: aes-128-gcm
- name: ğŸ‡³ğŸ‡±NL_421 |10.06Mb
  server: 77.238.224.29
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 55702
  password: S2QudBxi0vRySw4YRLloPq
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡³ğŸ‡±NL_424 |10.04Mb
  server: 193.29.139.162
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 8080
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡°ğŸ‡·KR_395 |20.55Mb
  server: 221.139.79.57
  type: ss
  country: ğŸ‡°ğŸ‡·KR
  port: 37008
  password: qwerREWQ@@
  cipher: aes-256-cfb
- name: ğŸ‡³ğŸ‡±NL_431 |10.10Mb
  server: 193.29.139.227
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 8080
  password: 4a2rfixophdjffa8KVA4Aa
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡³ğŸ‡±NL_428 |10.12Mb
  server: 79.127.227.198
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 990
  password: f8f7aCzcPKbsF8p3
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¸ğŸ‡¬SG_486 |10.21Mb
  server: 15.235.83.228
  type: vmess
  country: ğŸ‡¸ğŸ‡¬SG
  port: 443
  uuid: 03fcc618-b93d-6796-6aed-8a38c975d581
  alterId: 0
  cipher: auto
  network: ws
  servername: wrmelmwxlf.gktevlrqznwqqozy.fabpfs66gizmnojhcvqxwl.kytrcfzqla87gvgvs6c7kjnrubuh.cc
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /linkvws
    headers:
      HOST: wrmelmwxlf.gktevlrqznwqqozy.fabpfs66gizmnojhcvqxwl.kytrcfzqla87gvgvs6c7kjnrubuh.cc
- name: ğŸ‡µğŸ‡±PL_452 |147.77Mb
  server: 217.30.10.70
  type: ss
  country: ğŸ‡µğŸ‡±PL
  port: 9084
  password: c3NtHJ5ujV2tGDfj
  cipher: aes-256-cfb
- name: ğŸ‡µğŸ‡±PL_456 |12.00Mb
  server: 217.30.10.70
  type: ss
  country: ğŸ‡µğŸ‡±PL
  port: 9053
  password: SBM7R883jBmnqe6C
  cipher: aes-256-cfb
- name: ğŸ‡ºğŸ‡¸US_515 |14.43Mb
  server: 23.154.136.213
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 7307
  password: FoOiGlkAA9yPEGP
  cipher: aes-256-gcm
- name: ğŸ‡ºğŸ‡¸US_536 |10.42Mb
  server: 37.19.198.160
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: shadowsocks
  cipher: aes-128-gcm
- name: ğŸ‡ºğŸ‡¸US_549 |10.45Mb
  server: 54.209.249.254
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡µğŸ‡±PL_472 |171.76Mb
  server: 217.30.10.70
  type: ss
  country: ğŸ‡µğŸ‡±PL
  port: 9041
  password: U6qnYRhfyDmn8sgn
  cipher: aes-256-cfb
- name: ğŸ‡·ğŸ‡ºRU_478 |139.35Mb
  server: 95.163.176.37
  type: ss
  country: ğŸ‡·ğŸ‡ºRU
  port: 8506
  password: WLEqen5ubQYw4TbHTxxnjK
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_522 |10.07Mb
  server: 104.192.226.106
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 990
  password: f8f7aCzcPKbsF8p3
  cipher: chacha20-ietf-poly1305
- name: disney_US |10.04Mb
  server: 107.151.182.197
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 8080
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: ğŸ‡ºğŸ‡¸US_571 |10.31Mb
  server: 74.50.99.86
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 8080
  password: 42000e02-6b4d-46ad-a572-80db7db2a9ce
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_529 |11.64Mb
  server: 23.157.40.5
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 8888
  password: Y6R9pAtvxxzmGC
  cipher: aes-256-gcm
- name: ğŸ‡ºğŸ‡¸US_563 |10.22Mb
  server: 156.146.38.167
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: shadowsocks
  cipher: aes-128-gcm
- name: ğŸ‡ºğŸ‡¸US_541 |19.52Mb
  server: 23.157.40.5
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 5000
  password: Y6R9pAtvxxzmGC
  cipher: aes-256-gcm
- name: ğŸ‡ºğŸ‡¸US_559 |18.19Mb
  server: 167.88.61.110
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 7002
  password: RexnBgU7EV5ADxG
  cipher: aes-256-gcm
- name: disney_US |10.14Mb
  server: 193.124.24.247
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 6502
  uuid: 242f22a3-29d9-4a94-d8ba-88043f2e1921
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡ºğŸ‡¸US_558 |10.06Mb
  server: 45.158.171.110
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 8080
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: disney_US |10.29Mb
  server: 193.124.24.247
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 6515
  uuid: 2f3c646a-37f3-483a-a2a5-6bc1c5e526ae
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_US |10.17Mb
  server: 193.124.24.247
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 6507
  uuid: 3003e094-707c-4dbb-faca-4b8d579bc604
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_US |10.28Mb
  server: 193.124.24.247
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 6506
  uuid: c53d41d1-7d56-43ce-9994-408780c6476a
  alterId: 0
  cipher: auto
  network: tcp
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡ºğŸ‡¸US_597 |453.37Mb
  server: 15.204.11.190
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 15361
  uuid: 5d7bf9e3-415c-40f3-c66d-a54ea0fd860e
  alterId: 0
  cipher: auto
  network: tcp
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡ºğŸ‡¸US_564 |17.53Mb
  server: 23.157.40.5
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 2376
  password: faBAoD54k87UJG7
  cipher: aes-256-gcm
- name: ğŸ‡ºğŸ‡¸US_577 |16.76Mb
  server: 23.157.40.5
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 8009
  password: XKFKl2rULjIp74
  cipher: aes-256-gcm
- name: Relay_ğŸZZ-ğŸ‡ºğŸ‡¸US_629 |317.81Mb
  server: 104.16.155.10
  type: vmess
  country: ğŸZZ
  port: 2052
  uuid: a1a607e6-a04c-3db6-a36f-c2a4312e2fe1
  alterId: 0
  cipher: auto
  network: ws
  servername: 100-253-62-167.s5.cn-db.top
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
  ws-opts:
    path: /dabai.in172.64.15.49
    headers:
      HOST: 100-253-62-167.s5.cn-db.top
- name: disney_US |10.21Mb
  server: 193.124.24.247
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 6510
  uuid: 8f44f672-e53b-44fb-b502-c886d37107b5
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_US |907.74Mb
  server: 154.201.76.172
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 20521
  uuid: 496cec71-a0fd-4f25-bba1-cba9e9d5a52f
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
  ws-opts:
    path: /
- name: ğŸ‡ºğŸ‡¸US_601 |763.32Mb
  server: 43.162.114.137
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 59674
  uuid: 6a4ce5b9-0d60-4a21-a8fe-897798019500
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡ºğŸ‡¸US_551 |10.58Mb
  server: 149.22.87.240
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: shadowsocks
  cipher: aes-128-gcm
- name: disney_US |10.29Mb
  server: 193.124.24.247
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 6504
  uuid: 7ceb165c-9aff-4ab7-ce9e-1df31a5ed911
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_GI |80.16Mb
  server: imap.roomyinmita.name
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 40565
  password: 2T4HCndX3QvfDBmGXJnKSct873fvrXjLHPZSpfumFdMMqBUeh8E878f6Zfv4YA21KokhxF1c48rjVLeBeWJu4ovizkPtUMAY
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_320 |72.27Mb
  server: 89.185.84.185
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: dpRpqTAaO4ozrbcm2iN4qs
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸZZ-ğŸ‡ºğŸ‡¸US_632 |10.03Mb
  server: s1.db-link03.top
  type: vmess
  country: ğŸZZ
  port: 80
  uuid: 25fbcec6-e45a-3a86-977a-12c40bf649ba
  alterId: 0
  cipher: auto
  network: ws
  servername: f7f48a0f7685b208efdf4956ae5eb0a0.s1.db-link03.top
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
  ws-opts:
    path: /dabai.in?=f7f48a0f7685b208efdf4956ae5eb0a0
    headers:
      HOST: f7f48a0f7685b208efdf4956ae5eb0a0.s1.db-link03.top
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - ğŸ‡¨ğŸ‡¦CA_269 |183.39Mb
  - ğŸ‡¨ğŸ‡¦CA_271 |10.34Mb
  - ğŸ‡¨ğŸ‡¦CA_272 |157.19Mb
  - Relay_ğŸ‡¨ğŸ‡¦CA-ğŸ‡¨ğŸ‡¦CA_274 |10.14Mb
  - _251 |10.15Mb
  - Relay_ğŸ‡¨ğŸ‡¦CA-ğŸ‡¨ğŸ‡¦CA_275 |138.00Mb
  - ğŸ‡¦ğŸ‡«AF_256 |10.11Mb
  - _247 |10.15Mb
  - _242 |11.40Mb
  - ğŸ‡¦ğŸ‡·AR_257 |163.08Mb
  - ğŸ‡¨ğŸ‡¿CZ_284 |10.02Mb
  - ğŸ‡¦ğŸ‡ºAU_263 |10.10Mb
  - ğŸ‡¦ğŸ‡ºAU_259 |10.24Mb
  - ğŸ‡©ğŸ‡°DK_293 |10.15Mb
  - ğŸ‡§ğŸ‡·BR_268 |11.32Mb
  - ğŸ‡¬ğŸ‡§GB_310 |10.23Mb
  - Pool_ğŸ‡¬ğŸ‡§GB_317 |10.15Mb
  - ğŸ‡«ğŸ‡·FR_299 |138.26Mb
  - ğŸ‡«ğŸ‡·FR_300 |155.03Mb
  - ğŸ‡¬ğŸ‡§GB_318 |73.94Mb
  - ğŸ‡¬ğŸ‡§GB_319 |73.62Mb
  - ğŸ‡¬ğŸ‡§GB_324 |10.32Mb
  - ğŸ‡¬ğŸ‡§GB_323 |73.42Mb
  - ğŸ‡­ğŸ‡ºHU_333 |10.02Mb
  - ğŸ‡©ğŸ‡ªDE_292 |86.47Mb
  - ğŸ‡®ğŸ‡·IR_381 |10.07Mb
  - ğŸ‡®ğŸ‡³IN_335 |40.34Mb
  - Relay_ğŸ‡®ğŸ‡·IR-ğŸ‡³ğŸ‡±NL_383 |10.09Mb
  - ğŸ‡®ğŸ‡³IN_336 |39.75Mb
  - ğŸ‡®ğŸ‡³IN_338 |40.88Mb
  - ğŸ‡®ğŸ‡³IN_337 |41.04Mb
  - ğŸ‡®ğŸ‡³IN_339 |20.80Mb
  - ğŸ‡®ğŸ‡·IR_388 |10.11Mb
  - ğŸ‡®ğŸ‡¹IT_389 |10.02Mb
  - ğŸ‡­ğŸ‡°HK_332 |44.40Mb
  - Pool_ğŸ‡­ğŸ‡°HK_329 |170.00Mb
  - ğŸ‡±ğŸ‡¹LT_400 |10.62Mb
  - ğŸ‡±ğŸ‡¹LT_406 |13.16Mb
  - ğŸ‡±ğŸ‡¹LT_405 |10.17Mb
  - ğŸ‡±ğŸ‡¹LT_410 |10.08Mb
  - ğŸ‡²ğŸ‡½MX_419 |10.51Mb
  - ğŸ‡¯ğŸ‡µJP_391 |10.36Mb
  - ğŸ‡³ğŸ‡±NL_421 |10.06Mb
  - ğŸ‡³ğŸ‡±NL_424 |10.04Mb
  - ğŸ‡°ğŸ‡·KR_395 |20.55Mb
  - ğŸ‡³ğŸ‡±NL_431 |10.10Mb
  - ğŸ‡³ğŸ‡±NL_428 |10.12Mb
  - ğŸ‡¸ğŸ‡¬SG_486 |10.21Mb
  - ğŸ‡µğŸ‡±PL_452 |147.77Mb
  - ğŸ‡µğŸ‡±PL_456 |12.00Mb
  - ğŸ‡ºğŸ‡¸US_515 |14.43Mb
  - ğŸ‡ºğŸ‡¸US_536 |10.42Mb
  - ğŸ‡ºğŸ‡¸US_549 |10.45Mb
  - ğŸ‡µğŸ‡±PL_472 |171.76Mb
  - ğŸ‡·ğŸ‡ºRU_478 |139.35Mb
  - ğŸ‡ºğŸ‡¸US_522 |10.07Mb
  - disney_US |10.04Mb
  - ğŸ‡ºğŸ‡¸US_571 |10.31Mb
  - ğŸ‡ºğŸ‡¸US_529 |11.64Mb
  - ğŸ‡ºğŸ‡¸US_563 |10.22Mb
  - ğŸ‡ºğŸ‡¸US_541 |19.52Mb
  - ğŸ‡ºğŸ‡¸US_559 |18.19Mb
  - disney_US |10.14Mb
  - ğŸ‡ºğŸ‡¸US_558 |10.06Mb
  - disney_US |10.29Mb
  - disney_US |10.17Mb
  - disney_US |10.28Mb
  - ğŸ‡ºğŸ‡¸US_597 |453.37Mb
  - ğŸ‡ºğŸ‡¸US_564 |17.53Mb
  - ğŸ‡ºğŸ‡¸US_577 |16.76Mb
  - Relay_ğŸZZ-ğŸ‡ºğŸ‡¸US_629 |317.81Mb
  - disney_US |10.21Mb
  - disney_US |907.74Mb
  - ğŸ‡ºğŸ‡¸US_601 |763.32Mb
  - ğŸ‡ºğŸ‡¸US_551 |10.58Mb
  - disney_US |10.29Mb
  - disney_GI |80.16Mb
  - ğŸ‡¬ğŸ‡§GB_320 |72.27Mb
  - Relay_ğŸZZ-ğŸ‡ºğŸ‡¸US_632 |10.03Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - ğŸ‡¨ğŸ‡¦CA_269 |183.39Mb
  - ğŸ‡¨ğŸ‡¦CA_271 |10.34Mb
  - ğŸ‡¨ğŸ‡¦CA_272 |157.19Mb
  - Relay_ğŸ‡¨ğŸ‡¦CA-ğŸ‡¨ğŸ‡¦CA_274 |10.14Mb
  - _251 |10.15Mb
  - Relay_ğŸ‡¨ğŸ‡¦CA-ğŸ‡¨ğŸ‡¦CA_275 |138.00Mb
  - ğŸ‡¦ğŸ‡«AF_256 |10.11Mb
  - _247 |10.15Mb
  - _242 |11.40Mb
  - ğŸ‡¦ğŸ‡·AR_257 |163.08Mb
  - ğŸ‡¨ğŸ‡¿CZ_284 |10.02Mb
  - ğŸ‡¦ğŸ‡ºAU_263 |10.10Mb
  - ğŸ‡¦ğŸ‡ºAU_259 |10.24Mb
  - ğŸ‡©ğŸ‡°DK_293 |10.15Mb
  - ğŸ‡§ğŸ‡·BR_268 |11.32Mb
  - ğŸ‡¬ğŸ‡§GB_310 |10.23Mb
  - Pool_ğŸ‡¬ğŸ‡§GB_317 |10.15Mb
  - ğŸ‡«ğŸ‡·FR_299 |138.26Mb
  - ğŸ‡«ğŸ‡·FR_300 |155.03Mb
  - ğŸ‡¬ğŸ‡§GB_318 |73.94Mb
  - ğŸ‡¬ğŸ‡§GB_319 |73.62Mb
  - ğŸ‡¬ğŸ‡§GB_324 |10.32Mb
  - ğŸ‡¬ğŸ‡§GB_323 |73.42Mb
  - ğŸ‡­ğŸ‡ºHU_333 |10.02Mb
  - ğŸ‡©ğŸ‡ªDE_292 |86.47Mb
  - ğŸ‡®ğŸ‡·IR_381 |10.07Mb
  - ğŸ‡®ğŸ‡³IN_335 |40.34Mb
  - Relay_ğŸ‡®ğŸ‡·IR-ğŸ‡³ğŸ‡±NL_383 |10.09Mb
  - ğŸ‡®ğŸ‡³IN_336 |39.75Mb
  - ğŸ‡®ğŸ‡³IN_338 |40.88Mb
  - ğŸ‡®ğŸ‡³IN_337 |41.04Mb
  - ğŸ‡®ğŸ‡³IN_339 |20.80Mb
  - ğŸ‡®ğŸ‡·IR_388 |10.11Mb
  - ğŸ‡®ğŸ‡¹IT_389 |10.02Mb
  - ğŸ‡­ğŸ‡°HK_332 |44.40Mb
  - Pool_ğŸ‡­ğŸ‡°HK_329 |170.00Mb
  - ğŸ‡±ğŸ‡¹LT_400 |10.62Mb
  - ğŸ‡±ğŸ‡¹LT_406 |13.16Mb
  - ğŸ‡±ğŸ‡¹LT_405 |10.17Mb
  - ğŸ‡±ğŸ‡¹LT_410 |10.08Mb
  - ğŸ‡²ğŸ‡½MX_419 |10.51Mb
  - ğŸ‡¯ğŸ‡µJP_391 |10.36Mb
  - ğŸ‡³ğŸ‡±NL_421 |10.06Mb
  - ğŸ‡³ğŸ‡±NL_424 |10.04Mb
  - ğŸ‡°ğŸ‡·KR_395 |20.55Mb
  - ğŸ‡³ğŸ‡±NL_431 |10.10Mb
  - ğŸ‡³ğŸ‡±NL_428 |10.12Mb
  - ğŸ‡¸ğŸ‡¬SG_486 |10.21Mb
  - ğŸ‡µğŸ‡±PL_452 |147.77Mb
  - ğŸ‡µğŸ‡±PL_456 |12.00Mb
  - ğŸ‡ºğŸ‡¸US_515 |14.43Mb
  - ğŸ‡ºğŸ‡¸US_536 |10.42Mb
  - ğŸ‡ºğŸ‡¸US_549 |10.45Mb
  - ğŸ‡µğŸ‡±PL_472 |171.76Mb
  - ğŸ‡·ğŸ‡ºRU_478 |139.35Mb
  - ğŸ‡ºğŸ‡¸US_522 |10.07Mb
  - disney_US |10.04Mb
  - ğŸ‡ºğŸ‡¸US_571 |10.31Mb
  - ğŸ‡ºğŸ‡¸US_529 |11.64Mb
  - ğŸ‡ºğŸ‡¸US_563 |10.22Mb
  - ğŸ‡ºğŸ‡¸US_541 |19.52Mb
  - ğŸ‡ºğŸ‡¸US_559 |18.19Mb
  - disney_US |10.14Mb
  - ğŸ‡ºğŸ‡¸US_558 |10.06Mb
  - disney_US |10.29Mb
  - disney_US |10.17Mb
  - disney_US |10.28Mb
  - ğŸ‡ºğŸ‡¸US_597 |453.37Mb
  - ğŸ‡ºğŸ‡¸US_564 |17.53Mb
  - ğŸ‡ºğŸ‡¸US_577 |16.76Mb
  - Relay_ğŸZZ-ğŸ‡ºğŸ‡¸US_629 |317.81Mb
  - disney_US |10.21Mb
  - disney_US |907.74Mb
  - ğŸ‡ºğŸ‡¸US_601 |763.32Mb
  - ğŸ‡ºğŸ‡¸US_551 |10.58Mb
  - disney_US |10.29Mb
  - disney_GI |80.16Mb
  - ğŸ‡¬ğŸ‡§GB_320 |72.27Mb
  - Relay_ğŸZZ-ğŸ‡ºğŸ‡¸US_632 |10.03Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
