port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: disney_netflix_NL |221.91Mb
  server: 151.242.251.137
  type: ss
  port: 8080
  password: o5osZg269v5zHpYjr1xY9s
  cipher: chacha20-ietf-poly1305
- name: _490 |14.15Mb
  server: 154.90.62.168
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: _491 |44.67Mb
  server: 213.159.67.124
  type: ss
  port: 443
  password: mbhqsStnFQT1cTZYCdsmkugGUC6GT6rp
  cipher: chacha20-ietf-poly1305
- name: netflix_US |60.42Mb
  server: 107.175.87.207
  type: ss
  port: 10011
  udp: true
  password: 86039b71-ba82-4ca8-838e-87086ae666de
  cipher: chacha20-ietf-poly1305
- name: disney_US |20.56Mb
  server: 216.167.49.157
  type: vmess
  port: 36108
  uuid: ac9340c1-61d7-47bd-c5a2-9b888857dec6
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
- name: netflix_US |45.29Mb
  server: 47.253.197.26
  type: vmess
  port: 12056
  uuid: dd7be7f1-38ff-45e6-f1e5-b20c2190f527
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
- name: _497 |191.24Mb
  server: 45.87.175.181
  type: ss
  port: 8080
  udp: true
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: disney_MD |332.83Mb
  server: 185.153.197.5
  type: ss
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: disney_PT |642.74Mb
  server: 185.231.233.112
  type: ss
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: _496 |10.99Mb
  server: 103.106.3.82
  type: ss
  port: 443
  udp: true
  password: 4SaCIazlgumYkM8FkPzlmwjpyWBDZFBk
  cipher: chacha20-ietf-poly1305
- name: disney_LV |77.69Mb
  server: 31.56.117.73
  type: vmess
  port: 28573
  uuid: aa521837-6bfb-47dd-c87c-ec730a974020
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
- name: _507 |19.04Mb
  server: 152.70.92.69
  type: vmess
  port: 80
  uuid: bb9c3993-a4b9-4dad-aeb9-ac86371ae68b
  alterId: 0
  cipher: auto
  network: http
  http-opts:
    path:
    - /
  h2-opts: {}
- name: _525 |10.94Mb
  server: 47.243.212.142
  type: vmess
  port: 35193
  uuid: c76ee219-2274-4768-8953-200fa72d2a60
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /arki?ed=2048
- name: Relay_-ğŸ‡³ğŸ‡±NL_532 |11.48Mb
  server: 153.121.73.102
  type: trojan
  port: 2760
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: disney_RU |96.43Mb
  server: 37.18.14.33
  type: trojan
  port: 443
  udp: true
  password: Qzy7tgpRhu
  sni: m.vk.com
  skip-cert-verify: true
- name: disney_HK |28.36Mb
  server: 58.152.25.20
  type: trojan
  port: 443
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: Relay_-ğŸ‡ºğŸ‡¸US_542 |16.56Mb
  server: gy3.hdcloud.link
  type: trojan
  port: 443
  udp: true
  password: 9b6419f8-8120-442e-a48c-6bf52aef0abf
  network: grpc
  grpc-opts:
    grpc-service-name: GunService
- name: disney_HK |19.44Mb
  server: 58.152.18.95
  type: trojan
  port: 443
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: Relay_-ğŸ‡²ğŸ‡¾MY_504 |28.17Mb
  server: ml0724.ysds168.shop
  type: vmess
  port: 2052
  udp: true
  uuid: 665d9b8f-153d-4907-adac-de12afd9c851
  alterId: 0
  cipher: auto
  servername: ml0724.ysds168.shop
  http-opts: {}
  h2-opts: {}
  tls: true
- name: disney_HK |24.39Mb
  server: 58.152.18.192
  type: trojan
  port: 443
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: ğŸ‡§ğŸ‡¬BG_548 |28.24Mb
  server: 87.121.162.249
  type: ss
  country: ğŸ‡§ğŸ‡¬BG
  port: 443
  password: JGv616hMWdjfuZ00jYfq7XkBHJZrOBrg
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡§ğŸ‡·BR_549 |22.37Mb
  server: 38.180.16.86
  type: vmess
  country: ğŸ‡§ğŸ‡·BR
  port: 36236
  uuid: a58bc1a5-8c18-49ff-9453-c331b52f45dc
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡§ğŸ‡·BR_550 |22.81Mb
  server: 38.180.16.86
  type: vmess
  country: ğŸ‡§ğŸ‡·BR
  port: 36104
  uuid: E146A8CB-9D2F-449C-ADCA-8736FB
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_TW |13.49Mb
  server: 154.83.92.111
  type: ss
  country: ğŸ‡­ğŸ‡°HK
  port: 10014
  password: 8bd43408-d561-4bf7-b5fb-152acaa8fe34
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡²ğŸ‡½MX_633 |32.37Mb
  server: 216.238.89.53
  type: vmess
  country: ğŸ‡²ğŸ‡½MX
  port: 57283
  uuid: 1a5aafc0-6482-451d-fe76-6875b7818579
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡­ğŸ‡°HK_581 |18.90Mb
  server: 8.218.17.136
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 52986
  uuid: 7363d47e-ac8b-4fe0-d23e-99077999a70d
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: netflix_US |48.82Mb
  server: 23.95.75.146
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: NDRySIABARbErNIVsCNVkyYAHiBzhveT
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡®ğŸ‡ªIE_630 |340.94Mb
  server: 18.203.220.111
  type: ss
  country: ğŸ‡®ğŸ‡ªIE
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡­ğŸ‡°HK_616 |115.59Mb
  server: 47.242.140.52
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 48219
  uuid: 006893c6-79b1-4c44-94ff-b8bbea065f1f
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
  ws-opts:
    path: /arki?ed=2048
- name: disney_HK |27.87Mb
  server: 112.118.116.66
  type: trojan
  country: ğŸ‡­ğŸ‡°HK
  port: 443
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: ğŸ‡ºğŸ‡¸US_642 |24.04Mb
  server: 74.117.196.232
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 37934
  uuid: 4f3cfda3-a255-40eb-8801-71f9fffb19d6
  alterId: 0
  cipher: auto
  network: ws
  servername: imafake.locker
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /speedtest
    headers:
      HOST: imafake.locker
- name: ğŸ‡ºğŸ‡¸US_643 |11.97Mb
  server: 74.117.196.232
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 37934
  uuid: 54a0bf6d-f2b5-4b2a-942c-798fb129527e
  alterId: 0
  cipher: auto
  network: ws
  servername: imafake.locker
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /speedtest
    headers:
      HOST: imafake.locker
- name: ğŸ‡ºğŸ‡¸US_645 |16.38Mb
  server: 74.117.196.232
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 37934
  uuid: f1a513d2-c32a-49dc-8e64-d4f8a2f1e001
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /speedtest
- name: ğŸ‡ºğŸ‡¸US_644 |16.64Mb
  server: 74.117.196.232
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 37934
  uuid: e3cb685e-7840-45cb-9d64-b2028d9b635e
  alterId: 0
  cipher: auto
  network: ws
  servername: imafake.locker
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /speedtest
    headers:
      HOST: imafake.locker
- name: disney_NL |145.37Mb
  server: 109.71.246.210
  type: ss
  country: ğŸ‡·ğŸ‡ºRU
  port: 56689
  password: YQCSKoCF3QazW8YlvDBWA4
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_647 |19.34Mb
  server: 74.117.196.232
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 37934
  uuid: 3b475934-cb2a-4d96-b260-5e50cca5d430
  alterId: 0
  cipher: auto
  network: ws
  servername: imafake.locker
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /speedtest
    headers:
      HOST: imafake.locker
- name: ğŸ‡ºğŸ‡¸US_649 |10.73Mb
  server: 74.117.196.232
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 37934
  uuid: 6d600864-32da-49fd-baf4-7df051762454
  alterId: 0
  cipher: auto
  network: ws
  servername: imafake.locker
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /speedtest
    headers:
      HOST: imafake.locker
- name: ğŸ‡ºğŸ‡¸US_650 |10.31Mb
  server: 74.117.196.232
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 37934
  uuid: 254551f6-ec28-4938-ad0e-0aa4aa1965ec
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /speedtest
- name: ğŸ‡²ğŸ‡¾MY_634 |29.94Mb
  server: 38.54.98.110
  type: vmess
  country: ğŸ‡²ğŸ‡¾MY
  port: 2052
  uuid: 665d9b8f-153d-4907-adac-de12afd9c851
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: ğŸ‡ºğŸ‡¸ US_636 |16.42Mb
  server: 38.165.233.93
  type: ss
  country: ğŸ‡ºğŸ‡¸ US
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: Relay_ğŸ‡­ğŸ‡°HK-ğŸ‡­ğŸ‡°HK_587 |33.17Mb
  server: v10.hdacd.com
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 30807
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: auto
  network: tcp
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_646 |36.74Mb
  server: sw19.sesamebuta.top
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  uuid: 805ba514-bf2f-4d5d-df49-8417804e8de3
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /abcd
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - disney_netflix_NL |221.91Mb
  - _490 |14.15Mb
  - _491 |44.67Mb
  - netflix_US |60.42Mb
  - disney_US |20.56Mb
  - netflix_US |45.29Mb
  - _497 |191.24Mb
  - disney_MD |332.83Mb
  - disney_PT |642.74Mb
  - _496 |10.99Mb
  - disney_LV |77.69Mb
  - _507 |19.04Mb
  - _525 |10.94Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_532 |11.48Mb
  - disney_RU |96.43Mb
  - disney_HK |28.36Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_542 |16.56Mb
  - disney_HK |19.44Mb
  - Relay_-ğŸ‡²ğŸ‡¾MY_504 |28.17Mb
  - disney_HK |24.39Mb
  - ğŸ‡§ğŸ‡¬BG_548 |28.24Mb
  - ğŸ‡§ğŸ‡·BR_549 |22.37Mb
  - ğŸ‡§ğŸ‡·BR_550 |22.81Mb
  - disney_TW |13.49Mb
  - ğŸ‡²ğŸ‡½MX_633 |32.37Mb
  - ğŸ‡­ğŸ‡°HK_581 |18.90Mb
  - netflix_US |48.82Mb
  - ğŸ‡®ğŸ‡ªIE_630 |340.94Mb
  - ğŸ‡­ğŸ‡°HK_616 |115.59Mb
  - disney_HK |27.87Mb
  - ğŸ‡ºğŸ‡¸US_642 |24.04Mb
  - ğŸ‡ºğŸ‡¸US_643 |11.97Mb
  - ğŸ‡ºğŸ‡¸US_645 |16.38Mb
  - ğŸ‡ºğŸ‡¸US_644 |16.64Mb
  - disney_NL |145.37Mb
  - ğŸ‡ºğŸ‡¸US_647 |19.34Mb
  - ğŸ‡ºğŸ‡¸US_649 |10.73Mb
  - ğŸ‡ºğŸ‡¸US_650 |10.31Mb
  - ğŸ‡²ğŸ‡¾MY_634 |29.94Mb
  - ğŸ‡ºğŸ‡¸ US_636 |16.42Mb
  - Relay_ğŸ‡­ğŸ‡°HK-ğŸ‡­ğŸ‡°HK_587 |33.17Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_646 |36.74Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - disney_netflix_NL |221.91Mb
  - _490 |14.15Mb
  - _491 |44.67Mb
  - netflix_US |60.42Mb
  - disney_US |20.56Mb
  - netflix_US |45.29Mb
  - _497 |191.24Mb
  - disney_MD |332.83Mb
  - disney_PT |642.74Mb
  - _496 |10.99Mb
  - disney_LV |77.69Mb
  - _507 |19.04Mb
  - _525 |10.94Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_532 |11.48Mb
  - disney_RU |96.43Mb
  - disney_HK |28.36Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_542 |16.56Mb
  - disney_HK |19.44Mb
  - Relay_-ğŸ‡²ğŸ‡¾MY_504 |28.17Mb
  - disney_HK |24.39Mb
  - ğŸ‡§ğŸ‡¬BG_548 |28.24Mb
  - ğŸ‡§ğŸ‡·BR_549 |22.37Mb
  - ğŸ‡§ğŸ‡·BR_550 |22.81Mb
  - disney_TW |13.49Mb
  - ğŸ‡²ğŸ‡½MX_633 |32.37Mb
  - ğŸ‡­ğŸ‡°HK_581 |18.90Mb
  - netflix_US |48.82Mb
  - ğŸ‡®ğŸ‡ªIE_630 |340.94Mb
  - ğŸ‡­ğŸ‡°HK_616 |115.59Mb
  - disney_HK |27.87Mb
  - ğŸ‡ºğŸ‡¸US_642 |24.04Mb
  - ğŸ‡ºğŸ‡¸US_643 |11.97Mb
  - ğŸ‡ºğŸ‡¸US_645 |16.38Mb
  - ğŸ‡ºğŸ‡¸US_644 |16.64Mb
  - disney_NL |145.37Mb
  - ğŸ‡ºğŸ‡¸US_647 |19.34Mb
  - ğŸ‡ºğŸ‡¸US_649 |10.73Mb
  - ğŸ‡ºğŸ‡¸US_650 |10.31Mb
  - ğŸ‡²ğŸ‡¾MY_634 |29.94Mb
  - ğŸ‡ºğŸ‡¸ US_636 |16.42Mb
  - Relay_ğŸ‡­ğŸ‡°HK-ğŸ‡­ğŸ‡°HK_587 |33.17Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_646 |36.74Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
