port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: _156
  type: vmess
  server: 112.132.215.12
  port: 50002
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 64
  cipher: auto
  udp: true
- name: Relay_-ğŸ‡ºğŸ‡¸US_157 | 3.94Mb
  type: vmess
  server: 45.144.174.211
  port: 25039
  uuid: 6ff16ecc-2ba4-401d-b1ed-35c40a62808f
  alterId: 0
  cipher: auto
  udp: true
  network: ws
  ws-opts:
    path: /
    headers:
      Host: ''
- name: ğŸ‡¦ğŸ‡ºAU_164 | 9.70Mb
  type: vmess
  server: 103.57.249.204
  port: 443
  uuid: f13143a7-542d-49ec-9428-098142b6977c
  alterId: 0
  cipher: auto
  udp: true
- name: ğŸ‡¨ğŸ‡¦CA_179 | 7.83Mb
  type: vmess
  server: 51.79.86.182
  port: 42610
  uuid: e0957ca6-f613-4017-ff3c-effd1da8871a
  alterId: 0
  cipher: auto
  udp: true
- name: ğŸ‡¨ğŸ‡¦CA_180 |10.81Mb
  type: vmess
  server: 23.162.200.227
  port: 443
  uuid: 03fcc618-b93d-6796-6aed-8a38c975d581
  alterId: 0
  cipher: auto
  udp: true
  network: ws
  ws-opts:
    path: /linkvws
    headers:
      Host: ''
  tls: true
- name: ğŸ‡¨ğŸ‡³CN_186 | 1.66Mb
  type: vmess
  server: 112.132.215.12
  port: 50002
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 64
  cipher: auto
  udp: true
- name: ğŸ‡¨ğŸ‡³CN_187 |48.87Mb
  type: vmess
  server: 120.210.205.59
  port: 50002
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 64
  cipher: auto
  udp: true
- name: ğŸ‡¨ğŸ‡³CN_188 | 2.36Mb
  type: vmess
  server: 120.26.55.225
  port: 50112
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 64
  cipher: auto
  udp: true
- name: ğŸ‡¨ğŸ‡³CN_189 | 5.33Mb
  type: vmess
  server: 112.132.215.34
  port: 50007
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: auto
  udp: true
- name: ğŸ‡©ğŸ‡ªDE_216 |10.26Mb
  type: vmess
  server: 57.129.28.69
  port: 443
  uuid: 03fcc618-b93d-6796-6aed-8a38c975d581
  alterId: 0
  cipher: auto
  udp: true
  network: ws
  ws-opts:
    path: /linkvws
    headers:
      Host: baradiha.com
  tls: true
  servername: baradiha.com
- name: ğŸ‡©ğŸ‡ªDE_218 | 2.72Mb
  type: vmess
  server: 94.136.185.230
  port: 10534
  uuid: b01c7ef9-33ec-41f6-bfbf-77ddc4d21649
  alterId: 0
  cipher: auto
  udp: true
- name: ğŸ‡©ğŸ‡ªDE_219 |90.77Mb
  type: vmess
  server: 57.129.25.25
  port: 443
  uuid: 03fcc618-b93d-6796-6aed-8a38c975d581
  alterId: 0
  cipher: auto
  udp: true
  network: ws
  ws-opts:
    path: /linkvws
    headers:
      Host: f.khilei.com
  tls: true
  servername: f.khilei.com
- name: ğŸ‡©ğŸ‡ªDE_220 |21.24Mb
  type: vmess
  server: 62.146.235.193
  port: 28011
  uuid: cfc5a87f-3c13-4e25-b556-176cdd6b5c6a
  alterId: 0
  cipher: auto
  udp: true
- name: ğŸ‡©ğŸ‡ªDE_221 | 3.52Mb
  type: vmess
  server: 82.197.69.131
  port: 39674
  uuid: 5a89386a-827b-4f54-8778-2f1b5122c6ef
  alterId: 0
  cipher: auto
  udp: true
- name: ğŸ‡«ğŸ‡·FR_247 |115.59Mb
  type: vmess
  server: 135.125.182.74
  port: 28213
  uuid: 81852771-76fb-4e94-e4f1-4e37a698a49a
  alterId: 0
  cipher: auto
  udp: true
- name: Relay_ğŸ‡«ğŸ‡·FR-ğŸ‡ºğŸ‡¸US_248
  type: vmess
  server: 141.145.205.115
  port: 8443
  uuid: de94cc0a-0592-4969-b1fc-97ea8f0ea0b3
  alterId: 0
  cipher: auto
  udp: true
  network: ws
  ws-opts:
    path: /us.kkp.me.eu.org/aa
    headers:
      Host: farid.1.berozha.ir
  tls: true
  servername: farid.1.berozha.ir
- name: ğŸ‡«ğŸ‡·FR_249
  type: vmess
  server: 5.196.29.123
  port: 2082
  uuid: 112ac36f-3f53-4e26-8371-d25c028e1b9a
  alterId: 0
  cipher: auto
  udp: true
  network: ws
  ws-opts:
    path: /
    headers:
      Host: ''
- name: Relay_ğŸ‡¬ğŸ‡§GB-ğŸ‡ºğŸ‡¸US_281
  type: vmess
  server: 141.147.85.167
  port: 8443
  uuid: de94cc0a-0592-4969-b1fc-97ea8f0ea0b3
  alterId: 0
  cipher: auto
  udp: true
  network: ws
  ws-opts:
    path: /us.kkp.me.eu.org/aa
    headers:
      Host: farid.1.berozha.ir
  tls: true
  servername: farid.1.berozha.ir
- name: Relay_ğŸ‡¬ğŸ‡§GB-ğŸ‡ºğŸ‡¸US_282 | 2.82Mb
  type: vmess
  server: 25.129.197.249
  port: 8880
  uuid: 8c757cf8-d26c-342c-90ca-45b455d55ca8
  alterId: 0
  cipher: auto
  udp: true
  network: ws
  ws-opts:
    path: /dabai&Telegram%F0%9F%87%A8%F0%9F%87%B3%20@WangCai2%20/
    headers:
      Host: TG.WangCai2.s2.db-link02.top
- name: Relay_ğŸ‡¬ğŸ‡§GB-ğŸ‡ºğŸ‡¸US_283 |10.02Mb
  type: vmess
  server: 25.129.198.249
  port: 8880
  uuid: 53ec5471-532d-371f-a499-c152006493b8
  alterId: 0
  cipher: auto
  udp: true
  network: ws
  ws-opts:
    path: /dabai&Telegram%F0%9F%87%A8%F0%9F%87%B3%20@WangCai2%20/
    headers:
      Host: TG.WangCai2.s2.db-link02.top
- name: ğŸ‡¬ğŸ‡§GB_284 | 9.48Mb
  type: vmess
  server: 51.38.64.209
  port: 44023
  uuid: 7da457da-ed0f-437d-c81d-6c35885bbea3
  alterId: 0
  cipher: auto
  udp: true
- name: Relay_ğŸ‡¬ğŸ‡§GB-ğŸ‡ºğŸ‡¸US_285 | 3.75Mb
  type: vmess
  server: 25.129.199.249
  port: 8880
  uuid: b417c566-92c5-34dd-b324-1a32959ccd8f
  alterId: 0
  cipher: auto
  udp: true
  network: ws
  ws-opts:
    path: /dabai&Telegram%F0%9F%87%A8%F0%9F%87%B3%20@WangCai2%20/
    headers:
      Host: TG.WangCai2.s2.db-link02.top
- name: Relay_ğŸ‡¬ğŸ‡§GB-ğŸ‡ºğŸ‡¸US_286 |10.79Mb
  type: vmess
  server: 25.25.25.249
  port: 8880
  uuid: c8c50f25-6eea-3645-967b-b48e12e0c99b
  alterId: 0
  cipher: auto
  udp: true
  network: ws
  ws-opts:
    path: /dabai&Telegram%F0%9F%87%A8%F0%9F%87%B3%20@WangCai2%20/
    headers:
      Host: TG.WangCai2.s2.db-link02.top
- name: ğŸ‡­ğŸ‡°HK_295 | 5.99Mb
  type: vmess
  server: 203.184.246.211
  port: 51043
  uuid: c05b241c-0de2-4959-b3a0-ec3df5bfda99
  alterId: 0
  cipher: auto
  udp: true
- name: Relay_ğŸ‡­ğŸ‡°HK-ğŸ‡ºğŸ‡¸US_296
  type: vmess
  server: 62.60.251.254
  port: 443
  uuid: de94cc0a-0592-4969-b1fc-97ea8f0ea0b3
  alterId: 0
  cipher: auto
  udp: true
  network: ws
  ws-opts:
    path: /us.kkp.me.eu.org/aa
    headers:
      Host: farid.1.berozha.ir
  tls: true
  servername: farid.1.berozha.ir
- name: ğŸ‡­ğŸ‡°HK_297 | 7.26Mb
  type: vmess
  server: 203.184.246.7
  port: 24229
  uuid: 50b9297e-c728-46c0-de4b-36ddf8948007
  alterId: 0
  cipher: auto
  udp: true
- name: Relay_ğŸ‡­ğŸ‡°HK-ğŸ‡ºğŸ‡¸US_298
  type: vmess
  server: 202.85.53.74
  port: 443
  uuid: de94cc0a-0592-4969-b1fc-97ea8f0ea0b3
  alterId: 0
  cipher: auto
  udp: true
  network: ws
  ws-opts:
    path: /us.kkp.me.eu.org/aa
    headers:
      Host: farid.1.berozha.ir
  tls: true
  servername: farid.1.berozha.ir
- name: ğŸ‡®ğŸ‡©ID_302 | 9.66Mb
  type: vmess
  server: 154.90.49.57
  port: 58868
  uuid: fbffeb6b-b5e5-4f77-8888-c7919fbeb0ad
  alterId: 0
  cipher: auto
  udp: true
- name: ğŸ‡®ğŸ‡³IN_312 | 1.89Mb
  type: vmess
  server: 152.67.8.205
  port: 80
  uuid: 9db4c708-aef8-4359-821b-38e47990be0d
  alterId: 0
  cipher: auto
  udp: true
  network: ws
  ws-opts:
    path: /
    headers:
      Host: ''
- name: ğŸ‡®ğŸ‡¶IQ_313 | 4.92Mb
  type: vmess
  server: 154.93.37.21
  port: 443
  uuid: 64a37ce5-e713-4ad4-c1de-b68761e9fef6
  alterId: 0
  cipher: auto
  udp: true
- name: Relay_ğŸ‡¯ğŸ‡µJP-ğŸ‡ºğŸ‡¸US_329
  type: vmess
  server: 121.85.55.59
  port: 19842
  uuid: de94cc0a-0592-4969-b1fc-97ea8f0ea0b3
  alterId: 0
  cipher: auto
  udp: true
  network: ws
  ws-opts:
    path: /us.kkp.me.eu.org/aa
    headers:
      Host: farid.1.berozha.ir
  tls: true
  servername: farid.1.berozha.ir
- name: Relay_ğŸ‡¯ğŸ‡µJP-ğŸ‡ºğŸ‡¸US_330
  type: vmess
  server: 138.3.222.33
  port: 443
  uuid: de94cc0a-0592-4969-b1fc-97ea8f0ea0b3
  alterId: 0
  cipher: auto
  udp: true
  network: ws
  ws-opts:
    path: /us.kkp.me.eu.org/aa
    headers:
      Host: farid.1.berozha.ir
  tls: true
  servername: farid.1.berozha.ir
- name: Relay_ğŸ‡¯ğŸ‡µJP-ğŸ‡ºğŸ‡¸US_331
  type: vmess
  server: 132.145.127.203
  port: 2053
  uuid: de94cc0a-0592-4969-b1fc-97ea8f0ea0b3
  alterId: 0
  cipher: auto
  udp: true
  network: ws
  ws-opts:
    path: /us.kkp.me.eu.org/aa
    headers:
      Host: farid.1.berozha.ir
  tls: true
  servername: farid.1.berozha.ir
- name: ğŸ‡¯ğŸ‡µJP_332 |11.79Mb
  type: vmess
  server: 172.104.98.192
  port: 43722
  uuid: 71dc43f8-dc50-4bb6-93e2-95dd5149d7fd
  alterId: 0
  cipher: auto
  udp: true
- name: disney_RU | 9.04Mb
  type: vmess
  server: 45.67.230.79
  port: 11052
  uuid: 314185f7-931d-4656-922d-0857e7afd224
  alterId: 0
  cipher: auto
  udp: true
- name: disney_US
  type: vmess
  server: 114.129.43.140
  port: 443
  uuid: de94cc0a-0592-4969-b1fc-97ea8f0ea0b3
  alterId: 0
  cipher: auto
  udp: true
  network: ws
  ws-opts:
    path: /us.kkp.me.eu.org/aa
    headers:
      Host: farid.1.berozha.ir
  tls: true
  servername: farid.1.berozha.ir
- name: Pool_ğŸ‡¸ğŸ‡¬SG_590 | 7.85Mb
  type: vmess
  server: 202.79.161.188
  port: 443
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 64
  cipher: auto
  udp: true
  network: ws
  ws-opts:
    path: /path/170733132233
    headers:
      Host: ''
  tls: true
- name: disney_SG | 3.01Mb
  type: vmess
  server: 165.154.195.38
  port: 35034
  uuid: 959a8caf-4cea-43d0-a548-3628e7ddfafc
  alterId: 0
  cipher: auto
  udp: true
- name: ğŸ‡¹ğŸ‡¼TW_600 |58.97Mb
  type: vmess
  server: 45.121.48.174
  port: 20788
  uuid: bfc630aa-4598-4481-9338-cac15e3e6b65
  alterId: 0
  cipher: auto
  udp: true
- name: ğŸ‡ºğŸ‡¸US_721 |13.12Mb
  type: vmess
  server: 45.128.54.84
  port: 37313
  uuid: 72feb833-4196-4a70-a3f5-aeb011f7d534
  alterId: 0
  cipher: auto
  udp: true
- name: ğŸ‡ºğŸ‡¸US_722 | 6.25Mb
  type: vmess
  server: 206.206.80.227
  port: 20086
  uuid: 0abb7b9e-81ba-4336-8ca7-056866032ff3
  alterId: 0
  cipher: auto
  udp: true
  network: ws
  ws-opts:
    path: /
    headers:
      Host: ''
- name: ğŸ‡ºğŸ‡¸US_723 | 2.79Mb
  type: vmess
  server: 15.204.234.200
  port: 41100
  uuid: c7f169a3-2e9a-4894-ba53-7b2fa6fd08b4
  alterId: 0
  cipher: auto
  udp: true
- name: ğŸ‡ºğŸ‡¸US_724 | 7.52Mb
  type: vmess
  server: 137.175.124.167
  port: 20086
  uuid: b4bce500-11fe-4f8f-a344-01ac247af9bd
  alterId: 0
  cipher: auto
  udp: true
  network: ws
  ws-opts:
    path: /
    headers:
      Host: ''
- name: disney_US | 2.49Mb
  type: vmess
  server: 206.119.191.9
  port: 7998
  uuid: 984429ed-3959-4022-e248-cbcb19c96f9a
  alterId: 0
  cipher: auto
  udp: true
- name: disney_US_1
  type: vmess
  server: 205.198.68.177
  port: 443
  uuid: de94cc0a-0592-4969-b1fc-97ea8f0ea0b3
  alterId: 0
  cipher: auto
  udp: true
  network: ws
  ws-opts:
    path: /us.kkp.me.eu.org/aa
    headers:
      Host: farid.1.berozha.ir
  tls: true
  servername: farid.1.berozha.ir
- name: ğŸ‡ºğŸ‡¸US_727 |91.84Mb
  type: vmess
  server: 172.233.171.224
  port: 16416
  uuid: 8c1b9bea-cb51-43bb-a65c-0af31bbbf145
  alterId: 0
  cipher: auto
  udp: true
- name: ğŸ‡ºğŸ‡¸US_728 |14.72Mb
  type: vmess
  server: 15.204.11.190
  port: 15361
  uuid: 5d7bf9e3-415c-40f3-c66d-a54ea0fd860e
  alterId: 0
  cipher: auto
  udp: true
- name: disney_US | 2.64Mb
  type: vmess
  server: 206.119.191.20
  port: 7998
  uuid: 984429ed-3959-4022-e248-cbcb19c96f9a
  alterId: 0
  cipher: auto
  udp: true
- name: ğŸZZ_746 | 7.01Mb
  type: vmess
  server: 104.17.176.171
  port: 8080
  uuid: vw6hjp6qlg
  alterId: 0
  cipher: auto
  udp: true
  network: ws
  ws-opts:
    path: /download/cdn
    headers:
      Host: vw6hjp6qlg-525340125.zamam.co
- name: ğŸZZ_747 | 5.35Mb
  type: vmess
  server: npmjs.com
  port: 8080
  uuid: d3m1xvk50k
  alterId: 0
  cipher: auto
  udp: true
  network: ws
  ws-opts:
    path: /download/cdn
    headers:
      Host: d3m1xvk50k-525340173.zamam.co
- name: ğŸZZ_748 | 3.91Mb
  type: vmess
  server: 161.248.30.3
  port: 20086
  uuid: 1006a928-2021-4a3b-beb5-d5853c6281c5
  alterId: 0
  cipher: auto
  udp: true
  network: ws
  ws-opts:
    path: /
    headers:
      Host: ''
- name: ğŸZZ_750 | 3.40Mb
  type: vmess
  server: npmjs.com
  port: 8080
  uuid: vw6hjp6qlg
  alterId: 0
  cipher: auto
  udp: true
  network: ws
  ws-opts:
    path: /download/cdn
    headers:
      Host: vw6hjp6qlg-525340125.zamam.co
- name: disney_DE |21.86Mb
  type: vmess
  server: npmjs.com
  port: 8080
  uuid: nasnet
  alterId: 0
  cipher: auto
  udp: true
  network: ws
  ws-opts:
    path: /NASNET/cdn
    headers:
      Host: nasnet-4515017475.mashallahbet.com
proxy-groups:
- name: Proxy
  type: select
  proxies:
  - _156
  - Relay_-ğŸ‡ºğŸ‡¸US_157 | 3.94Mb
  - ğŸ‡¦ğŸ‡ºAU_164 | 9.70Mb
  - ğŸ‡¨ğŸ‡¦CA_179 | 7.83Mb
  - ğŸ‡¨ğŸ‡¦CA_180 |10.81Mb
  - ğŸ‡¨ğŸ‡³CN_186 | 1.66Mb
  - ğŸ‡¨ğŸ‡³CN_187 |48.87Mb
  - ğŸ‡¨ğŸ‡³CN_188 | 2.36Mb
  - ğŸ‡¨ğŸ‡³CN_189 | 5.33Mb
  - ğŸ‡©ğŸ‡ªDE_216 |10.26Mb
  - ğŸ‡©ğŸ‡ªDE_218 | 2.72Mb
  - ğŸ‡©ğŸ‡ªDE_219 |90.77Mb
  - ğŸ‡©ğŸ‡ªDE_220 |21.24Mb
  - ğŸ‡©ğŸ‡ªDE_221 | 3.52Mb
  - ğŸ‡«ğŸ‡·FR_247 |115.59Mb
  - Relay_ğŸ‡«ğŸ‡·FR-ğŸ‡ºğŸ‡¸US_248
  - ğŸ‡«ğŸ‡·FR_249
  - Relay_ğŸ‡¬ğŸ‡§GB-ğŸ‡ºğŸ‡¸US_281
  - Relay_ğŸ‡¬ğŸ‡§GB-ğŸ‡ºğŸ‡¸US_282 | 2.82Mb
  - Relay_ğŸ‡¬ğŸ‡§GB-ğŸ‡ºğŸ‡¸US_283 |10.02Mb
  - ğŸ‡¬ğŸ‡§GB_284 | 9.48Mb
  - Relay_ğŸ‡¬ğŸ‡§GB-ğŸ‡ºğŸ‡¸US_285 | 3.75Mb
  - Relay_ğŸ‡¬ğŸ‡§GB-ğŸ‡ºğŸ‡¸US_286 |10.79Mb
  - ğŸ‡­ğŸ‡°HK_295 | 5.99Mb
  - Relay_ğŸ‡­ğŸ‡°HK-ğŸ‡ºğŸ‡¸US_296
  - ğŸ‡­ğŸ‡°HK_297 | 7.26Mb
  - Relay_ğŸ‡­ğŸ‡°HK-ğŸ‡ºğŸ‡¸US_298
  - ğŸ‡®ğŸ‡©ID_302 | 9.66Mb
  - ğŸ‡®ğŸ‡³IN_312 | 1.89Mb
  - ğŸ‡®ğŸ‡¶IQ_313 | 4.92Mb
  - Relay_ğŸ‡¯ğŸ‡µJP-ğŸ‡ºğŸ‡¸US_329
  - Relay_ğŸ‡¯ğŸ‡µJP-ğŸ‡ºğŸ‡¸US_330
  - Relay_ğŸ‡¯ğŸ‡µJP-ğŸ‡ºğŸ‡¸US_331
  - ğŸ‡¯ğŸ‡µJP_332 |11.79Mb
  - disney_RU | 9.04Mb
  - disney_US
  - Pool_ğŸ‡¸ğŸ‡¬SG_590 | 7.85Mb
  - disney_SG | 3.01Mb
  - ğŸ‡¹ğŸ‡¼TW_600 |58.97Mb
  - ğŸ‡ºğŸ‡¸US_721 |13.12Mb
  - ğŸ‡ºğŸ‡¸US_722 | 6.25Mb
  - ğŸ‡ºğŸ‡¸US_723 | 2.79Mb
  - ğŸ‡ºğŸ‡¸US_724 | 7.52Mb
  - disney_US | 2.49Mb
  - disney_US_1
  - ğŸ‡ºğŸ‡¸US_727 |91.84Mb
  - ğŸ‡ºğŸ‡¸US_728 |14.72Mb
  - disney_US | 2.64Mb
  - ğŸZZ_746 | 7.01Mb
  - ğŸZZ_747 | 5.35Mb
  - ğŸZZ_748 | 3.91Mb
  - ğŸZZ_750 | 3.40Mb
  - disney_DE |21.86Mb
  url: https://www.google.com/generate_204
rules:
- GEOIP,CN,DIRECT
- MATCH,Proxy
