port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: ğŸ‡¨ğŸ‡¦CA_156 |14.68Mb
  server: 79.127.200.162
  type: ss
  country: ğŸ‡¨ğŸ‡¦CA
  port: 990
  password: f8f7aCzcPKbsF8p3
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_178 |92.16Mb
  server: 146.70.61.37
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: ğŸ‡§ğŸ‡¬BG_151 |32.72Mb
  server: 94.156.250.122
  type: ss
  country: ğŸ‡§ğŸ‡¬BG
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¦ğŸ‡¹AT_140 |15.44Mb
  server: 151.236.11.221
  type: ss
  country: ğŸ‡¦ğŸ‡¹AT
  port: 8443
  password: kNAssqfNR8hhvm9rSSJvhq
  cipher: chacha20-ietf-poly1305
- name: Relay_-ğŸ‡¯ğŸ‡µJP_136 |18.45Mb
  server: 160.16.68.250
  type: trojan
  port: 4451
  password: 253bc477d4e43c209f2d427272968280
  sni: www.nintendogames.net
  network: tcp
- name: Relay_ğŸ‡¨ğŸ‡¦CA-ğŸ‡¨ğŸ‡¦CA_161 |431.00Mb
  server: ssca.irundns.net
  type: ssr
  country: ğŸ‡¨ğŸ‡¦CA
  port: 443
  password: $$Turb0VPN$$
  cipher: aes-128-cfb
  protocol: auth_aes128_md5
  obfs: http_post
- name: ğŸ‡¬ğŸ‡§GB_180 |61.95Mb
  server: 38.180.30.147
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8388
  password: IDJY0hgIuUk7
  cipher: chacha20-ietf-poly1305
- name: Pool_ğŸ‡¬ğŸ‡§GB_184 |10.85Mb
  server: 79.127.233.170
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 990
  password: f8f7aCzcPKbsF8p3
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¦ğŸ‡ºAU_144 |80.44Mb
  server: 143.244.62.106
  type: ss
  country: ğŸ‡¦ğŸ‡ºAU
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ğŸ‡¦ğŸ‡ºAU_143 |28.42Mb
  server: 3.25.198.142
  type: ss
  country: ğŸ‡¦ğŸ‡ºAU
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: Relay_-ğŸ‡ºğŸ‡¸US_130 |24.93Mb
  server: us-n1.speedyyun.com
  type: vmess
  port: 25314
  udp: true
  uuid: 2a6c0365-e3ed-4aef-81ca-b1b6b46088da
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /victorias
    headers:
      Host: us-n1.speedyyun.com
- name: ğŸ‡¬ğŸ‡§GB_185 |14.29Mb
  server: 141.98.101.182
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: shadowsocks
  cipher: aes-128-gcm
- name: ğŸ‡²ğŸ‡½MX_245 |10.44Mb
  server: 147.78.1.230
  type: ss
  country: ğŸ‡²ğŸ‡½MX
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: Relay_ğŸ‡®ğŸ‡·IR-ğŸ‡³ğŸ‡±NL_232 |10.14Mb
  server: 151.242.251.144
  type: ss
  country: ğŸ‡®ğŸ‡·IR
  port: 8080
  password: o5osZg269v5zHpYjr1xY9s
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_188 |12.30Mb
  server: 216.173.70.187
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 57456
  password: 360e21d21977dc11
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¯ğŸ‡µJP_235 |10.50Mb
  server: 160.16.123.124
  type: ss
  country: ğŸ‡¯ğŸ‡µJP
  port: 10087
  password: '10086'
  cipher: aes-128-gcm
- name: ğŸ‡³ğŸ‡±NL_255 |10.15Mb
  server: 193.29.139.209
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 8080
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡³ğŸ‡±NL_256 |10.18Mb
  server: 193.29.139.144
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 8080
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡³ğŸ‡±NL_251 |63.23Mb
  server: 208.67.105.196
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 42029
  password: SjdGCHwafjktt1rzpGxTKYTvVBWb8Xa6E5DTr6MzbdHQSwvpLiDczj3n6MBjy2uyFSzgqgvCWsDQmpM4VQzfPzyGYF58wdyD
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡°ğŸ‡·KR_238 |122.23Mb
  server: 221.139.79.57
  type: ss
  country: ğŸ‡°ğŸ‡·KR
  port: 37008
  password: qwerREWQ@@
  cipher: aes-256-cfb
- name: Pool_ğŸ‡­ğŸ‡°HK_195 |804.00Mb
  server: 150.107.46.21
  type: ssr
  country: ğŸ‡­ğŸ‡°HK
  port: 8083
  password: iFqnzSscN
  cipher: aes-256-cfb
  protocol: origin
  obfs: tls1.2_ticket_auth
- name: ğŸ‡­ğŸ‡°HK_196 |13.91Mb
  server: 47.239.141.74
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 11886
  uuid: 0d36b017-6d7c-493d-bb12-55c34faf6efc
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
  ws-opts:
    path: /
- name: ğŸ‡³ğŸ‡±NL_259 |11.90Mb
  server: 193.29.139.227
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 8080
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡³ğŸ‡±NL_260 |10.17Mb
  server: 193.29.139.233
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 8080
  password: QCXDxuDlTTMD7jtgHUjIoj
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡³ğŸ‡±NL_261 |10.13Mb
  server: 193.29.139.162
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 8080
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡³ğŸ‡±NL_262 |10.20Mb
  server: 193.29.139.217
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 8080
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡³ğŸ‡±NL_264 |10.19Mb
  server: 193.29.139.217
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 8080
  password: 1RWwXhwfAB5gAEozU4G2Pg
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡µğŸ‡±PL_265 |49.66Mb
  server: 217.30.10.18
  type: ss
  country: ğŸ‡µğŸ‡±PL
  port: 9094
  password: rpgbNnU9rDDU4aWZ
  cipher: aes-256-cfb
- name: ğŸ‡µğŸ‡±PL_266 |55.70Mb
  server: 217.30.10.18
  type: ss
  country: ğŸ‡µğŸ‡±PL
  port: 9027
  password: EXN3S3eQpjE7EJu8
  cipher: aes-256-cfb
- name: ğŸ‡µğŸ‡±PL_270 |12.89Mb
  server: 217.30.10.70
  type: ss
  country: ğŸ‡µğŸ‡±PL
  port: 9098
  password: aLpQtfEZe445QyHk
  cipher: aes-256-cfb
- name: ğŸ‡µğŸ‡±PL_284 |76.82Mb
  server: 217.30.10.70
  type: ss
  country: ğŸ‡µğŸ‡±PL
  port: 9084
  password: c3NtHJ5ujV2tGDfj
  cipher: aes-256-cfb
- name: ğŸ‡µğŸ‡±PL_271 |12.03Mb
  server: 217.30.10.18
  type: ss
  country: ğŸ‡µğŸ‡±PL
  port: 9060
  password: ueLXVkvh4hckhErQ
  cipher: aes-256-cfb
- name: ğŸ‡µğŸ‡±PL_286 |46.11Mb
  server: 217.30.10.70
  type: ss
  country: ğŸ‡µğŸ‡±PL
  port: 9007
  password: kSPmvwdFzGMMW5pY
  cipher: aes-256-cfb
- name: ğŸ‡µğŸ‡±PL_287 |125.73Mb
  server: 217.30.10.70
  type: ss
  country: ğŸ‡µğŸ‡±PL
  port: 9079
  password: TPqX8edgbAURcAMb
  cipher: aes-256-cfb
- name: ğŸ‡µğŸ‡±PL_288 |90.45Mb
  server: 217.30.10.18
  type: ss
  country: ğŸ‡µğŸ‡±PL
  port: 9056
  password: rNBfNuuANFCAk7KB
  cipher: aes-256-cfb
- name: ğŸ‡µğŸ‡±PL_289 |149.72Mb
  server: 217.30.10.18
  type: ss
  country: ğŸ‡µğŸ‡±PL
  port: 9088
  password: f8npKgNzdkss2ytn
  cipher: aes-256-cfb
- name: ğŸ‡µğŸ‡±PL_290 |31.14Mb
  server: 217.30.10.70
  type: ss
  country: ğŸ‡µğŸ‡±PL
  port: 9019
  password: GA9KzeEgvfxNrgmM
  cipher: aes-256-cfb
- name: ğŸ‡µğŸ‡±PL_295 |105.68Mb
  server: 217.30.10.70
  type: ss
  country: ğŸ‡µğŸ‡±PL
  port: 9026
  password: QWDDvVE9npNurQfA
  cipher: aes-256-cfb
- name: ğŸ‡µğŸ‡±PL_293 |11.23Mb
  server: 217.30.10.70
  type: ss
  country: ğŸ‡µğŸ‡±PL
  port: 9033
  password: UTJA57ypk2XKQpnm
  cipher: aes-256-cfb
- name: ğŸ‡ºğŸ‡¸US_329 |110.63Mb
  server: 167.88.61.113
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 5003
  password: g5MeD6Ft3CWlJId
  cipher: aes-256-gcm
- name: ğŸ‡·ğŸ‡ºRU_302 |161.40Mb
  server: 95.163.176.37
  type: ss
  country: ğŸ‡·ğŸ‡ºRU
  port: 8506
  password: n4J9KuWgBBXPBoDn0SdprD
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡·ğŸ‡ºRU_300 |113.41Mb
  server: 95.163.176.37
  type: ss
  country: ğŸ‡·ğŸ‡ºRU
  port: 8506
  password: ZK8Hv7D68bNRynZeqLVFLM
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡µğŸ‡¹PT_296 |43.32Mb
  server: 185.231.233.173
  type: ss
  country: ğŸ‡µğŸ‡¹PT
  port: 990
  password: f8f7aCzcPKbsF8p3
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_340 |19.52Mb
  server: 54.157.216.140
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡ºğŸ‡¸US_339 |50.96Mb
  server: 54.227.21.67
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡ºğŸ‡¸US_333 |52.90Mb
  server: 167.88.61.59
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 8091
  password: PCnnH6SQSnfoS27
  cipher: aes-256-gcm
- name: ğŸ‡·ğŸ‡ºRU_303 |149.57Mb
  server: 95.163.176.37
  type: ss
  country: ğŸ‡·ğŸ‡ºRU
  port: 8506
  password: KVe53W0gvOHIOJxXChJ5uA
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡·ğŸ‡ºRU_304 |109.54Mb
  server: 95.163.176.37
  type: ss
  country: ğŸ‡·ğŸ‡ºRU
  port: 8506
  password: VdswxetVc6AhIps18rtYbm
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_343 |10.40Mb
  server: 37.19.198.244
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: shadowsocks
  cipher: aes-128-gcm
- name: ğŸ‡ºğŸ‡¸US_336 |73.07Mb
  server: 23.157.40.5
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 8009
  password: XKFKl2rULjIp74
  cipher: aes-256-gcm
- name: ğŸ‡¸ğŸ‡ªSE_305 |11.63Mb
  server: 121.127.46.147
  type: ss
  country: ğŸ‡¸ğŸ‡ªSE
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ğŸ‡ºğŸ‡¸US_349 |10.30Mb
  server: 37.19.198.243
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: shadowsocks
  cipher: aes-128-gcm
- name: ğŸ‡ºğŸ‡¸US_350 |10.28Mb
  server: 37.19.198.236
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: shadowsocks
  cipher: aes-128-gcm
- name: ğŸ‡ºğŸ‡¸US_363 |10.20Mb
  server: 156.146.38.170
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: shadowsocks
  cipher: aes-128-gcm
- name: Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_364 |37.34Mb
  server: 193.124.24.247
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 6511
  uuid: 5ef4e89b-262f-4c74-e793-c7332079f251
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡ºğŸ‡¸US_345 |10.40Mb
  server: 173.244.56.9
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: shadowsocks
  cipher: aes-128-gcm
- name: ğŸ‡ºğŸ‡¸US_360 |24.68Mb
  server: 216.132.112.116
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 34958
  password: AJtV4VCLaVQUKGH4g1ADSyqvzCA0mSpN46an12ZeIKhx
  cipher: aes-256-gcm
- name: ğŸ‡ºğŸ‡¸US_362 |19.08Mb
  server: 54.209.249.254
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_370 |11.82Mb
  server: 193.124.24.247
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 6515
  uuid: 2f3c646a-37f3-483a-a2a5-6bc1c5e526ae
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡ºğŸ‡¸US_335 |23.76Mb
  server: 45.158.171.70
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 8080
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_352 |68.90Mb
  server: 23.157.40.5
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 5000
  password: Y6R9pAtvxxzmGC
  cipher: aes-256-gcm
- name: ğŸ‡ºğŸ‡¸US_353 |157.34Mb
  server: 23.157.40.5
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 6679
  password: TEzjfAYq2IjtuoS
  cipher: aes-256-gcm
- name: ğŸ‡ºğŸ‡¸US_359 |49.94Mb
  server: 167.88.61.59
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 8118
  password: cdBIDV42DCwnfIN
  cipher: aes-256-gcm
- name: Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_332 |10.94Mb
  server: us.vmagnum.win
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 57456
  password: 360e21d21977dc11
  cipher: chacha20-ietf-poly1305
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - ğŸ‡¨ğŸ‡¦CA_156 |14.68Mb
  - ğŸ‡¬ğŸ‡§GB_178 |92.16Mb
  - ğŸ‡§ğŸ‡¬BG_151 |32.72Mb
  - ğŸ‡¦ğŸ‡¹AT_140 |15.44Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_136 |18.45Mb
  - Relay_ğŸ‡¨ğŸ‡¦CA-ğŸ‡¨ğŸ‡¦CA_161 |431.00Mb
  - ğŸ‡¬ğŸ‡§GB_180 |61.95Mb
  - Pool_ğŸ‡¬ğŸ‡§GB_184 |10.85Mb
  - ğŸ‡¦ğŸ‡ºAU_144 |80.44Mb
  - ğŸ‡¦ğŸ‡ºAU_143 |28.42Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_130 |24.93Mb
  - ğŸ‡¬ğŸ‡§GB_185 |14.29Mb
  - ğŸ‡²ğŸ‡½MX_245 |10.44Mb
  - Relay_ğŸ‡®ğŸ‡·IR-ğŸ‡³ğŸ‡±NL_232 |10.14Mb
  - ğŸ‡¬ğŸ‡§GB_188 |12.30Mb
  - ğŸ‡¯ğŸ‡µJP_235 |10.50Mb
  - ğŸ‡³ğŸ‡±NL_255 |10.15Mb
  - ğŸ‡³ğŸ‡±NL_256 |10.18Mb
  - ğŸ‡³ğŸ‡±NL_251 |63.23Mb
  - ğŸ‡°ğŸ‡·KR_238 |122.23Mb
  - Pool_ğŸ‡­ğŸ‡°HK_195 |804.00Mb
  - ğŸ‡­ğŸ‡°HK_196 |13.91Mb
  - ğŸ‡³ğŸ‡±NL_259 |11.90Mb
  - ğŸ‡³ğŸ‡±NL_260 |10.17Mb
  - ğŸ‡³ğŸ‡±NL_261 |10.13Mb
  - ğŸ‡³ğŸ‡±NL_262 |10.20Mb
  - ğŸ‡³ğŸ‡±NL_264 |10.19Mb
  - ğŸ‡µğŸ‡±PL_265 |49.66Mb
  - ğŸ‡µğŸ‡±PL_266 |55.70Mb
  - ğŸ‡µğŸ‡±PL_270 |12.89Mb
  - ğŸ‡µğŸ‡±PL_284 |76.82Mb
  - ğŸ‡µğŸ‡±PL_271 |12.03Mb
  - ğŸ‡µğŸ‡±PL_286 |46.11Mb
  - ğŸ‡µğŸ‡±PL_287 |125.73Mb
  - ğŸ‡µğŸ‡±PL_288 |90.45Mb
  - ğŸ‡µğŸ‡±PL_289 |149.72Mb
  - ğŸ‡µğŸ‡±PL_290 |31.14Mb
  - ğŸ‡µğŸ‡±PL_295 |105.68Mb
  - ğŸ‡µğŸ‡±PL_293 |11.23Mb
  - ğŸ‡ºğŸ‡¸US_329 |110.63Mb
  - ğŸ‡·ğŸ‡ºRU_302 |161.40Mb
  - ğŸ‡·ğŸ‡ºRU_300 |113.41Mb
  - ğŸ‡µğŸ‡¹PT_296 |43.32Mb
  - ğŸ‡ºğŸ‡¸US_340 |19.52Mb
  - ğŸ‡ºğŸ‡¸US_339 |50.96Mb
  - ğŸ‡ºğŸ‡¸US_333 |52.90Mb
  - ğŸ‡·ğŸ‡ºRU_303 |149.57Mb
  - ğŸ‡·ğŸ‡ºRU_304 |109.54Mb
  - ğŸ‡ºğŸ‡¸US_343 |10.40Mb
  - ğŸ‡ºğŸ‡¸US_336 |73.07Mb
  - ğŸ‡¸ğŸ‡ªSE_305 |11.63Mb
  - ğŸ‡ºğŸ‡¸US_349 |10.30Mb
  - ğŸ‡ºğŸ‡¸US_350 |10.28Mb
  - ğŸ‡ºğŸ‡¸US_363 |10.20Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_364 |37.34Mb
  - ğŸ‡ºğŸ‡¸US_345 |10.40Mb
  - ğŸ‡ºğŸ‡¸US_360 |24.68Mb
  - ğŸ‡ºğŸ‡¸US_362 |19.08Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_370 |11.82Mb
  - ğŸ‡ºğŸ‡¸US_335 |23.76Mb
  - ğŸ‡ºğŸ‡¸US_352 |68.90Mb
  - ğŸ‡ºğŸ‡¸US_353 |157.34Mb
  - ğŸ‡ºğŸ‡¸US_359 |49.94Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_332 |10.94Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - ğŸ‡¨ğŸ‡¦CA_156 |14.68Mb
  - ğŸ‡¬ğŸ‡§GB_178 |92.16Mb
  - ğŸ‡§ğŸ‡¬BG_151 |32.72Mb
  - ğŸ‡¦ğŸ‡¹AT_140 |15.44Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_136 |18.45Mb
  - Relay_ğŸ‡¨ğŸ‡¦CA-ğŸ‡¨ğŸ‡¦CA_161 |431.00Mb
  - ğŸ‡¬ğŸ‡§GB_180 |61.95Mb
  - Pool_ğŸ‡¬ğŸ‡§GB_184 |10.85Mb
  - ğŸ‡¦ğŸ‡ºAU_144 |80.44Mb
  - ğŸ‡¦ğŸ‡ºAU_143 |28.42Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_130 |24.93Mb
  - ğŸ‡¬ğŸ‡§GB_185 |14.29Mb
  - ğŸ‡²ğŸ‡½MX_245 |10.44Mb
  - Relay_ğŸ‡®ğŸ‡·IR-ğŸ‡³ğŸ‡±NL_232 |10.14Mb
  - ğŸ‡¬ğŸ‡§GB_188 |12.30Mb
  - ğŸ‡¯ğŸ‡µJP_235 |10.50Mb
  - ğŸ‡³ğŸ‡±NL_255 |10.15Mb
  - ğŸ‡³ğŸ‡±NL_256 |10.18Mb
  - ğŸ‡³ğŸ‡±NL_251 |63.23Mb
  - ğŸ‡°ğŸ‡·KR_238 |122.23Mb
  - Pool_ğŸ‡­ğŸ‡°HK_195 |804.00Mb
  - ğŸ‡­ğŸ‡°HK_196 |13.91Mb
  - ğŸ‡³ğŸ‡±NL_259 |11.90Mb
  - ğŸ‡³ğŸ‡±NL_260 |10.17Mb
  - ğŸ‡³ğŸ‡±NL_261 |10.13Mb
  - ğŸ‡³ğŸ‡±NL_262 |10.20Mb
  - ğŸ‡³ğŸ‡±NL_264 |10.19Mb
  - ğŸ‡µğŸ‡±PL_265 |49.66Mb
  - ğŸ‡µğŸ‡±PL_266 |55.70Mb
  - ğŸ‡µğŸ‡±PL_270 |12.89Mb
  - ğŸ‡µğŸ‡±PL_284 |76.82Mb
  - ğŸ‡µğŸ‡±PL_271 |12.03Mb
  - ğŸ‡µğŸ‡±PL_286 |46.11Mb
  - ğŸ‡µğŸ‡±PL_287 |125.73Mb
  - ğŸ‡µğŸ‡±PL_288 |90.45Mb
  - ğŸ‡µğŸ‡±PL_289 |149.72Mb
  - ğŸ‡µğŸ‡±PL_290 |31.14Mb
  - ğŸ‡µğŸ‡±PL_295 |105.68Mb
  - ğŸ‡µğŸ‡±PL_293 |11.23Mb
  - ğŸ‡ºğŸ‡¸US_329 |110.63Mb
  - ğŸ‡·ğŸ‡ºRU_302 |161.40Mb
  - ğŸ‡·ğŸ‡ºRU_300 |113.41Mb
  - ğŸ‡µğŸ‡¹PT_296 |43.32Mb
  - ğŸ‡ºğŸ‡¸US_340 |19.52Mb
  - ğŸ‡ºğŸ‡¸US_339 |50.96Mb
  - ğŸ‡ºğŸ‡¸US_333 |52.90Mb
  - ğŸ‡·ğŸ‡ºRU_303 |149.57Mb
  - ğŸ‡·ğŸ‡ºRU_304 |109.54Mb
  - ğŸ‡ºğŸ‡¸US_343 |10.40Mb
  - ğŸ‡ºğŸ‡¸US_336 |73.07Mb
  - ğŸ‡¸ğŸ‡ªSE_305 |11.63Mb
  - ğŸ‡ºğŸ‡¸US_349 |10.30Mb
  - ğŸ‡ºğŸ‡¸US_350 |10.28Mb
  - ğŸ‡ºğŸ‡¸US_363 |10.20Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_364 |37.34Mb
  - ğŸ‡ºğŸ‡¸US_345 |10.40Mb
  - ğŸ‡ºğŸ‡¸US_360 |24.68Mb
  - ğŸ‡ºğŸ‡¸US_362 |19.08Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_370 |11.82Mb
  - ğŸ‡ºğŸ‡¸US_335 |23.76Mb
  - ğŸ‡ºğŸ‡¸US_352 |68.90Mb
  - ğŸ‡ºğŸ‡¸US_353 |157.34Mb
  - ğŸ‡ºğŸ‡¸US_359 |49.94Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_332 |10.94Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
