port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: _213 |38.93Mb
  server: 66.23.207.82
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _221 |53.15Mb
  server: 167.160.90.178
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: Pool__212 |11.64Mb
  server: 62.100.205.177
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _211 |11.35Mb
  server: 62.100.205.100
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _215 |33.49Mb
  server: 138.186.142.81
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _216 |35.51Mb
  server: 138.186.142.80
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _238 |30.48Mb
  server: 173.234.29.2
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _214 |29.06Mb
  server: 37.235.56.69
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _225 |32.94Mb
  server: 91.219.237.163
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸ‡¨ğŸ‡¦CA-ğŸ‡¨ğŸ‡¦CA_252 |24.14Mb
  server: 79.127.200.169
  type: ss
  country: ğŸ‡¨ğŸ‡¦CA
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _207 |12.29Mb
  server: 185.163.204.94
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¨ğŸ‡¦CA_253 |133.90Mb
  server: 137.184.174.93
  type: ss
  country: ğŸ‡¨ğŸ‡¦CA
  port: 8080
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: _206 |26.69Mb
  server: 185.113.143.186
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _231 |12.59Mb
  server: 212.102.54.45
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡§ğŸ‡ªBE_248 |32.97Mb
  server: 192.71.249.108
  type: ss
  country: ğŸ‡§ğŸ‡ªBE
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_314 |12.71Mb
  server: 18.170.218.19
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡¬ğŸ‡§GB_315 |21.62Mb
  server: 35.179.184.210
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡©ğŸ‡ªDE_272 |37.67Mb
  server: 81.19.141.45
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 443
  password: OL7MQydIsTbln3xOq4lVvM
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_316 |10.83Mb
  server: 3.9.171.152
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: _230 |32.32Mb
  server: 154.205.153.107
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡«ğŸ‡®FI_306 |61.96Mb
  server: 37.143.129.230
  type: ss
  country: ğŸ‡«ğŸ‡®FI
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ğŸ‡«ğŸ‡®FI_307 |30.19Mb
  server: 37.143.129.98
  type: ss
  country: ğŸ‡«ğŸ‡®FI
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_326 |13.45Mb
  server: 89.185.84.185
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: 91C9JOHiGkfq6bN28Nie2x
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_337 |16.86Mb
  server: 18.134.245.70
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: _235 |21.68Mb
  server: 37.143.130.203
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_362 |12.63Mb
  server: 45.87.175.164
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: 1RWwXhwfAB5gAEozU4G2Pg
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_363 |12.65Mb
  server: 45.87.175.187
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡­ğŸ‡·HR_343 |10.83Mb
  server: 169.150.242.77
  type: ss
  country: ğŸ‡­ğŸ‡·HR
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_416 |26.21Mb
  server: 3.133.131.192
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡µğŸ‡±PL_374 |10.96Mb
  server: 217.30.10.18
  type: ss
  country: ğŸ‡µğŸ‡±PL
  port: 9032
  password: UWZQeLRWnkqgkseq
  cipher: aes-256-cfb
- name: ğŸ‡ºğŸ‡¸US_423 |34.84Mb
  server: 3.147.66.58
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡¸ğŸ‡ªSE_403 |12.70Mb
  server: 13.60.9.137
  type: ss
  country: ğŸ‡¸ğŸ‡ªSE
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡ºğŸ‡¸US_415 |96.03Mb
  server: 167.88.61.113
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 8881
  password: kDWvXYZoTBcGkC4
  cipher: aes-256-gcm
- name: ğŸ‡ºğŸ‡¸US_433 |33.15Mb
  server: 3.140.185.191
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡¸ğŸ‡°SK_405 |17.23Mb
  server: 193.37.255.38
  type: ss
  country: ğŸ‡¸ğŸ‡°SK
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡µğŸ‡±PL_378 |42.66Mb
  server: 77.83.246.74
  type: ss
  country: ğŸ‡µğŸ‡±PL
  port: 443
  password: tVZZkK258knbSmtMKjTEPQ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_425 |27.28Mb
  server: 104.192.226.106
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 990
  password: f8f7aCzcPKbsF8p3
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_437 |53.96Mb
  server: 71.19.148.143
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: p78naCf2EfOlRSLTX0wFVx
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_424 |43.06Mb
  server: 95.164.123.39
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 32821
  password: yXQLzA62V0b4swsrwFi5bL
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_414 |76.89Mb
  server: 172.238.21.121
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 64919
  password: 0ghZkORvV4grvekDJ9Wcge
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_446 |10.58Mb
  server: 173.255.248.230
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 3526
  password: P1quTcRWo5Kyar6oG0RtK1
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_459 |100.17Mb
  server: 193.124.24.247
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 6515
  uuid: 2f3c646a-37f3-483a-a2a5-6bc1c5e526ae
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡ºğŸ‡¸US_442 |142.56Mb
  server: 167.88.61.110
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 8091
  password: PCnnH6SQSnfoS27
  cipher: aes-256-gcm
- name: ğŸ‡ºğŸ‡¸US_441 |95.78Mb
  server: 167.88.61.110
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 6379
  password: zDNVedRFPQexG9v
  cipher: aes-256-gcm
- name: ğŸ‡ºğŸ‡¸US_447 |59.68Mb
  server: 167.88.61.110
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 6679
  password: TEzjfAYq2IjtuoS
  cipher: aes-256-gcm
- name: ğŸ‡ºğŸ‡¸US_448 |41.13Mb
  server: 167.88.61.110
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 7002
  password: RexnBgU7EV5ADxG
  cipher: aes-256-gcm
- name: ğŸ‡ºğŸ‡¸US_440 |22.72Mb
  server: 38.247.64.176
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡µğŸ‡±PL_377 |21.45Mb
  server: 77.83.246.74
  type: ss
  country: ğŸ‡µğŸ‡±PL
  port: 443
  password: mOLxFRatDFzZ8NI7qdm8Pj
  cipher: chacha20-ietf-poly1305
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - _213 |38.93Mb
  - _221 |53.15Mb
  - Pool__212 |11.64Mb
  - _211 |11.35Mb
  - _215 |33.49Mb
  - _216 |35.51Mb
  - _238 |30.48Mb
  - _214 |29.06Mb
  - _225 |32.94Mb
  - Relay_ğŸ‡¨ğŸ‡¦CA-ğŸ‡¨ğŸ‡¦CA_252 |24.14Mb
  - _207 |12.29Mb
  - ğŸ‡¨ğŸ‡¦CA_253 |133.90Mb
  - _206 |26.69Mb
  - _231 |12.59Mb
  - ğŸ‡§ğŸ‡ªBE_248 |32.97Mb
  - ğŸ‡¬ğŸ‡§GB_314 |12.71Mb
  - ğŸ‡¬ğŸ‡§GB_315 |21.62Mb
  - ğŸ‡©ğŸ‡ªDE_272 |37.67Mb
  - ğŸ‡¬ğŸ‡§GB_316 |10.83Mb
  - _230 |32.32Mb
  - ğŸ‡«ğŸ‡®FI_306 |61.96Mb
  - ğŸ‡«ğŸ‡®FI_307 |30.19Mb
  - ğŸ‡¬ğŸ‡§GB_326 |13.45Mb
  - ğŸ‡¬ğŸ‡§GB_337 |16.86Mb
  - _235 |21.68Mb
  - ğŸ‡±ğŸ‡¹LT_362 |12.63Mb
  - ğŸ‡±ğŸ‡¹LT_363 |12.65Mb
  - ğŸ‡­ğŸ‡·HR_343 |10.83Mb
  - ğŸ‡ºğŸ‡¸US_416 |26.21Mb
  - ğŸ‡µğŸ‡±PL_374 |10.96Mb
  - ğŸ‡ºğŸ‡¸US_423 |34.84Mb
  - ğŸ‡¸ğŸ‡ªSE_403 |12.70Mb
  - ğŸ‡ºğŸ‡¸US_415 |96.03Mb
  - ğŸ‡ºğŸ‡¸US_433 |33.15Mb
  - ğŸ‡¸ğŸ‡°SK_405 |17.23Mb
  - ğŸ‡µğŸ‡±PL_378 |42.66Mb
  - ğŸ‡ºğŸ‡¸US_425 |27.28Mb
  - ğŸ‡ºğŸ‡¸US_437 |53.96Mb
  - ğŸ‡ºğŸ‡¸US_424 |43.06Mb
  - ğŸ‡ºğŸ‡¸US_414 |76.89Mb
  - ğŸ‡ºğŸ‡¸US_446 |10.58Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_459 |100.17Mb
  - ğŸ‡ºğŸ‡¸US_442 |142.56Mb
  - ğŸ‡ºğŸ‡¸US_441 |95.78Mb
  - ğŸ‡ºğŸ‡¸US_447 |59.68Mb
  - ğŸ‡ºğŸ‡¸US_448 |41.13Mb
  - ğŸ‡ºğŸ‡¸US_440 |22.72Mb
  - ğŸ‡µğŸ‡±PL_377 |21.45Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - _213 |38.93Mb
  - _221 |53.15Mb
  - Pool__212 |11.64Mb
  - _211 |11.35Mb
  - _215 |33.49Mb
  - _216 |35.51Mb
  - _238 |30.48Mb
  - _214 |29.06Mb
  - _225 |32.94Mb
  - Relay_ğŸ‡¨ğŸ‡¦CA-ğŸ‡¨ğŸ‡¦CA_252 |24.14Mb
  - _207 |12.29Mb
  - ğŸ‡¨ğŸ‡¦CA_253 |133.90Mb
  - _206 |26.69Mb
  - _231 |12.59Mb
  - ğŸ‡§ğŸ‡ªBE_248 |32.97Mb
  - ğŸ‡¬ğŸ‡§GB_314 |12.71Mb
  - ğŸ‡¬ğŸ‡§GB_315 |21.62Mb
  - ğŸ‡©ğŸ‡ªDE_272 |37.67Mb
  - ğŸ‡¬ğŸ‡§GB_316 |10.83Mb
  - _230 |32.32Mb
  - ğŸ‡«ğŸ‡®FI_306 |61.96Mb
  - ğŸ‡«ğŸ‡®FI_307 |30.19Mb
  - ğŸ‡¬ğŸ‡§GB_326 |13.45Mb
  - ğŸ‡¬ğŸ‡§GB_337 |16.86Mb
  - _235 |21.68Mb
  - ğŸ‡±ğŸ‡¹LT_362 |12.63Mb
  - ğŸ‡±ğŸ‡¹LT_363 |12.65Mb
  - ğŸ‡­ğŸ‡·HR_343 |10.83Mb
  - ğŸ‡ºğŸ‡¸US_416 |26.21Mb
  - ğŸ‡µğŸ‡±PL_374 |10.96Mb
  - ğŸ‡ºğŸ‡¸US_423 |34.84Mb
  - ğŸ‡¸ğŸ‡ªSE_403 |12.70Mb
  - ğŸ‡ºğŸ‡¸US_415 |96.03Mb
  - ğŸ‡ºğŸ‡¸US_433 |33.15Mb
  - ğŸ‡¸ğŸ‡°SK_405 |17.23Mb
  - ğŸ‡µğŸ‡±PL_378 |42.66Mb
  - ğŸ‡ºğŸ‡¸US_425 |27.28Mb
  - ğŸ‡ºğŸ‡¸US_437 |53.96Mb
  - ğŸ‡ºğŸ‡¸US_424 |43.06Mb
  - ğŸ‡ºğŸ‡¸US_414 |76.89Mb
  - ğŸ‡ºğŸ‡¸US_446 |10.58Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_459 |100.17Mb
  - ğŸ‡ºğŸ‡¸US_442 |142.56Mb
  - ğŸ‡ºğŸ‡¸US_441 |95.78Mb
  - ğŸ‡ºğŸ‡¸US_447 |59.68Mb
  - ğŸ‡ºğŸ‡¸US_448 |41.13Mb
  - ğŸ‡ºğŸ‡¸US_440 |22.72Mb
  - ğŸ‡µğŸ‡±PL_377 |21.45Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
