port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: disney_TW |35.60Mb
  server: 141.193.213.199
  type: trojan
  port: 443
  udp: true
  password: a8a5b34d-fe46-487d-bd6a-d9f3101525fd
  sni: 26z68w0ecxbuyf89.ukgogo202511.top
  skip-cert-verify: true
  ws-opts:
    path: /images
    headers:
      Host: 26z68w0ecxbuyf89.ukgogo202511.top
  network: ws
- name: disney_netflix_NL |293.12Mb
  server: 82.38.31.218
  type: ss
  port: 8080
  udp: true
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_NL |128.10Mb
  server: 45.87.175.177
  type: ss
  port: 8080
  udp: true
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_NL |345.17Mb
  server: 151.242.251.144
  type: ss
  port: 8080
  udp: true
  password: QCXDxuDlTTMD7jtgHUjIoj
  cipher: chacha20-ietf-poly1305
- name: Relay_-ğŸ‡ºğŸ‡¸US_337 |18.14Mb
  server: us19-25.998998.best
  type: vmess
  port: 443
  udp: true
  uuid: 24254866-770c-41b4-9404-3f50524f425b
  alterId: 0
  cipher: auto
  network: ws
  servername: 24254866-770c-41b4-9404-3f50524f425b.mihomo.baby
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /saoihgreg9384gh8934
    headers:
      Host: 24254866-770c-41b4-9404-3f50524f425b.mihomo.baby
- name: netflix_PL |169.88Mb
  server: 45.15.126.19
  type: ss
  port: 443
  udp: true
  password: 6Ts2ZDTQAf3hkFoB8AFufDwsGrlF4e2t
  cipher: chacha20-ietf-poly1305
- name: Relay_-ğŸ‡³ğŸ‡±NL_345 |53.59Mb
  server: 160.16.204.136
  type: trojan
  port: 2890
  password: 2cf6d686799e6fa95316394064f26c0a
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡³ğŸ‡±NL_346 |52.41Mb
  server: 160.16.196.59
  type: trojan
  port: 4054
  password: 2cf6d686799e6fa95316394064f26c0a
  sni: www.nintendogames.net
- name: _336 |10.29Mb
  server: 95.111.222.113
  type: ss
  port: 443
  udp: true
  password: SVt6ZiWzRI1Yxeig4xBZwiJOt6ceXwGa
  cipher: chacha20-ietf-poly1305
- name: netflix_US |136.20Mb
  server: 82.198.246.97
  type: vmess
  country: ğŸ‡¬ğŸ‡§GB
  port: 180
  uuid: d13fc2f5-3e05-4795-81eb-44143a09e552
  alterId: 0
  cipher: auto
  network: tcp
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_RU |27.41Mb
  server: 37.18.14.33
  type: trojan
  port: 443
  udp: true
  password: Qzy7tgpRhu
  sni: m.vk.com
  skip-cert-verify: true
- name: Relay_-ğŸ‡³ğŸ‡±NL_348 |54.17Mb
  server: 160.16.136.130
  type: trojan
  port: 4054
  password: 2cf6d686799e6fa95316394064f26c0a
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¯ğŸ‡µJP_349 |11.81Mb
  server: 160.16.89.176
  type: trojan
  port: 3169
  password: 2cf6d686799e6fa95316394064f26c0a
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¯ğŸ‡µJP_350 |11.30Mb
  server: 160.16.204.136
  type: trojan
  port: 3169
  password: 2cf6d686799e6fa95316394064f26c0a
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡³ğŸ‡±NL_356 |10.82Mb
  server: 160.16.196.59
  type: trojan
  port: 2760
  password: 2cf6d686799e6fa95316394064f26c0a
  sni: www.nintendogames.net
- name: disney_FR |133.62Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 27092
  uuid: a0596ba6-72a3-4366-8992-77088da65bd8
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_PT |306.82Mb
  server: 185.231.233.112
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: disney_netflix_NL |276.11Mb
  server: 151.242.251.144
  type: ss
  country: ğŸ‡®ğŸ‡· IR
  port: 8080
  password: 4a2rfixophdjffa8KVA4Aa
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_NL |330.92Mb
  server: 151.242.251.153
  type: ss
  country: ğŸ‡®ğŸ‡· IR
  port: 8080
  password: QCXDxuDlTTMD7jtgHUjIoj
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_370 |13.08Mb
  server: pupas-shirting-unsung.freesocks.work
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: p78naCf2EfOlRSLTX0wFVx
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡·ğŸ‡ºRU_368 |39.53Mb
  server: 45.136.244.201
  type: vmess
  country: ğŸ‡·ğŸ‡ºRU
  port: 49934
  uuid: 90afa47d-341a-497d-ae25-1d81258804d5
  alterId: 0
  cipher: auto
  network: tcp
  servername: green2.cdntencentmusic.com
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_MD |12.85Mb
  server: 185.153.197.5
  type: ss
  country: ğŸ‡·ğŸ‡ºRU
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_373 |35.52Mb
  server: sw19.sesamebuta.top
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  uuid: 805ba514-bf2f-4d5d-df49-8417804e8de3
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /abcd
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - disney_TW |35.60Mb
  - disney_netflix_NL |293.12Mb
  - disney_netflix_NL |128.10Mb
  - disney_netflix_NL |345.17Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_337 |18.14Mb
  - netflix_PL |169.88Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_345 |53.59Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_346 |52.41Mb
  - _336 |10.29Mb
  - netflix_US |136.20Mb
  - disney_RU |27.41Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_348 |54.17Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_349 |11.81Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_350 |11.30Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_356 |10.82Mb
  - disney_FR |133.62Mb
  - disney_PT |306.82Mb
  - disney_netflix_NL |276.11Mb
  - disney_netflix_NL |330.92Mb
  - ğŸ‡ºğŸ‡¸US_370 |13.08Mb
  - ğŸ‡·ğŸ‡ºRU_368 |39.53Mb
  - disney_MD |12.85Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_373 |35.52Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - disney_TW |35.60Mb
  - disney_netflix_NL |293.12Mb
  - disney_netflix_NL |128.10Mb
  - disney_netflix_NL |345.17Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_337 |18.14Mb
  - netflix_PL |169.88Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_345 |53.59Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_346 |52.41Mb
  - _336 |10.29Mb
  - netflix_US |136.20Mb
  - disney_RU |27.41Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_348 |54.17Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_349 |11.81Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_350 |11.30Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_356 |10.82Mb
  - disney_FR |133.62Mb
  - disney_PT |306.82Mb
  - disney_netflix_NL |276.11Mb
  - disney_netflix_NL |330.92Mb
  - ğŸ‡ºğŸ‡¸US_370 |13.08Mb
  - ğŸ‡·ğŸ‡ºRU_368 |39.53Mb
  - disney_MD |12.85Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_373 |35.52Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
