port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: netflix_US |27.35Mb
  server: 173.234.29.2
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _354 |44.50Mb
  server: 185.82.73.212
  type: ss
  port: 8444
  udp: true
  password: _bypfvq6ra7g4n5yCCR9DoVeGya2XUUS
  cipher: chacha20-ietf-poly1305
- name: _358 |50.16Mb
  server: 45.14.245.2
  type: ss
  port: 443
  password: 17ZDORWIliQHuO6WRGHChXYMzdRtAYVP
  cipher: chacha20-ietf-poly1305
- name: _352 |979.94Mb
  server: 151.242.251.152
  type: ss
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: _353 |175.76Mb
  server: 82.38.31.199
  type: ss
  port: 8080
  udp: true
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: _362 |122.14Mb
  server: 82.38.31.202
  type: ss
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: Relay_-ğŸ‡­ğŸ‡°HK_357 |28.26Mb
  server: 103.149.182.105
  type: ss
  port: 8388
  password: asd123456
  cipher: chacha20-ietf
- name: _361 |106.47Mb
  server: 46.246.96.30
  type: ss
  port: 31561
  udp: true
  password: hc8LMJew3Fl9MbcFCoFgT0
  cipher: chacha20-ietf-poly1305
- name: disney_PY |149.15Mb
  server: 38.165.233.93
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: disney_HK |166.67Mb
  server: 103.149.182.158
  type: ss
  port: 8388
  password: asd123456
  cipher: chacha20-ietf
- name: Relay_-ğŸ‡¯ğŸ‡µJP_390 |12.71Mb
  server: 160.16.117.182
  type: trojan
  port: 3169
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: _391 |10.12Mb
  server: 160.16.131.243
  type: trojan
  port: 2760
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
  skip-cert-verify: true
- name: _372 |975.86Mb
  server: 45.87.175.28
  type: ss
  port: 8080
  udp: true
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: _373 |228.74Mb
  server: 45.158.171.70
  type: ss
  port: 8080
  udp: true
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: _392 |11.09Mb
  server: 160.16.106.144
  type: trojan
  port: 2760
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
  skip-cert-verify: true
- name: _384 |23.59Mb
  server: 47.242.145.160
  type: vmess
  port: 44457
  uuid: 40290609-2743-4d85-c9c3-4c72dd151b9f
  alterId: 0
  cipher: auto
  network: http
  http-opts:
    method: GET
    path:
    - /
  h2-opts: {}
- name: Relay_-ğŸ‡¯ğŸ‡µJP_395 |11.60Mb
  server: 153.121.45.139
  type: trojan
  port: 3093
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¸ğŸ‡ªSE_370 |37.94Mb
  server: 193.135.174.135
  type: ss
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _397 |10.61Mb
  server: 160.16.116.227
  type: trojan
  port: 2760
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
  skip-cert-verify: true
- name: Relay_-ğŸ‡¯ğŸ‡µJP_399 |20.61Mb
  server: 160.16.229.223
  type: trojan
  port: 3169
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: _371 |46.08Mb
  server: 156.59.243.6
  type: ss
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸ‡¬ğŸ‡§GB-ğŸ‡³ğŸ‡±NL_405 |955.74Mb
  server: 82.38.31.208
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: disney_DE |203.43Mb
  server: 89.163.140.136
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ğŸ‡¨ğŸ‡¦CA_402 |42.52Mb
  server: 185.213.23.63
  type: ss
  country: ğŸ‡¨ğŸ‡¦CA
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: disney_HK |28.44Mb
  server: 45.207.157.29
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 13852
  uuid: 845764df-ecb3-4b13-bed2-bf1551b68e9a
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡®ğŸ‡¹IT_411 |53.48Mb
  server: 176.126.83.121
  type: ss
  country: ğŸ‡®ğŸ‡¹IT
  port: 443
  password: Q4t8T7hEYY3mD2Fn4wnxyK4X35AUzvR8
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡²ğŸ‡½MX_424 |38.44Mb
  server: 216.238.87.47
  type: vmess
  country: ğŸ‡²ğŸ‡½MX
  port: 27502
  uuid: b8155ce4-7e08-4c40-800f-8671312b7124
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡±ğŸ‡¹LT_415 |195.20Mb
  server: 45.87.175.190
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡®ğŸ‡³IN_410 |154.25Mb
  server: 103.97.203.220
  type: vmess
  country: ğŸ‡®ğŸ‡³IN
  port: 550
  uuid: 9e0e83ca-0fbc-44b1-8024-0eb8f9414156
  alterId: 0
  cipher: auto
  network: tcp
  servername: t.me/v2Line
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_431 |40.81Mb
  server: 38.14.99.163
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 59807
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: auto
  network: tcp
  servername: 38.14.99.163
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡±ğŸ‡¹LT_418 |225.33Mb
  server: 45.87.175.200
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡» LV_422 |78.86Mb
  server: 46.183.217.204
  type: ss
  country: ğŸ‡±ğŸ‡» LV
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡²ğŸ‡©MD_423 |46.58Mb
  server: 176.123.5.253
  type: ss
  country: ğŸ‡²ğŸ‡©MD
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡µğŸ‡¹PT_428 |80.94Mb
  server: 185.113.143.186
  type: ss
  country: ğŸ‡µğŸ‡¹PT
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¸ğŸ‡¬SG_429 |12.73Mb
  server: 68.183.227.45
  type: ss
  country: ğŸ‡¸ğŸ‡¬SG
  port: 8080
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: ğŸ ZZ_433 |41.62Mb
  server: 185.231.233.112
  type: ss
  country: ğŸ ZZ
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: Relay_ğŸ‡¯ğŸ‡µJP-ğŸ‡¯ğŸ‡µJP_413 |10.65Mb
  server: xray.kk37005.tk
  type: vmess
  country: ğŸ‡¯ğŸ‡µJP
  port: 55919
  uuid: 2e7548bb-7c5b-4d97-d64d-1b2fe4050089
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: ğŸ‡±ğŸ‡¹LT_417 |979.99Mb
  server: ltnl16.saint.ydns.eu
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: disney_US |26.13Mb
  server: cf.fovi.tk
  type: vmess
  country: ğŸZZ
  port: 443
  uuid: bf67437e-6c90-45ca-abc2-c7240a5ce2aa
  alterId: 0
  cipher: auto
  network: ws
  servername: foxlux.fovi.tk
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /eisasqa
    headers:
      HOST: foxlux.fovi.tk
- name: netflix_US |54.19Mb
  server: 47.253.197.26
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 12056
  uuid: dd7be7f1-38ff-45e6-f1e5-b20c2190f527
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: _356 |14.23Mb
  server: 194.59.183.134
  type: ss
  port: 46114
  udp: true
  password: lejSRyqa033OEPmEQsvRsl
  cipher: chacha20-ietf-poly1305
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - netflix_US |27.35Mb
  - _354 |44.50Mb
  - _358 |50.16Mb
  - _352 |979.94Mb
  - _353 |175.76Mb
  - _362 |122.14Mb
  - Relay_-ğŸ‡­ğŸ‡°HK_357 |28.26Mb
  - _361 |106.47Mb
  - disney_PY |149.15Mb
  - disney_HK |166.67Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_390 |12.71Mb
  - _391 |10.12Mb
  - _372 |975.86Mb
  - _373 |228.74Mb
  - _392 |11.09Mb
  - _384 |23.59Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_395 |11.60Mb
  - Relay_-ğŸ‡¸ğŸ‡ªSE_370 |37.94Mb
  - _397 |10.61Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_399 |20.61Mb
  - _371 |46.08Mb
  - Relay_ğŸ‡¬ğŸ‡§GB-ğŸ‡³ğŸ‡±NL_405 |955.74Mb
  - disney_DE |203.43Mb
  - ğŸ‡¨ğŸ‡¦CA_402 |42.52Mb
  - disney_HK |28.44Mb
  - ğŸ‡®ğŸ‡¹IT_411 |53.48Mb
  - ğŸ‡²ğŸ‡½MX_424 |38.44Mb
  - ğŸ‡±ğŸ‡¹LT_415 |195.20Mb
  - ğŸ‡®ğŸ‡³IN_410 |154.25Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_431 |40.81Mb
  - ğŸ‡±ğŸ‡¹LT_418 |225.33Mb
  - ğŸ‡±ğŸ‡» LV_422 |78.86Mb
  - ğŸ‡²ğŸ‡©MD_423 |46.58Mb
  - ğŸ‡µğŸ‡¹PT_428 |80.94Mb
  - ğŸ‡¸ğŸ‡¬SG_429 |12.73Mb
  - ğŸ ZZ_433 |41.62Mb
  - Relay_ğŸ‡¯ğŸ‡µJP-ğŸ‡¯ğŸ‡µJP_413 |10.65Mb
  - ğŸ‡±ğŸ‡¹LT_417 |979.99Mb
  - disney_US |26.13Mb
  - netflix_US |54.19Mb
  - _356 |14.23Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - netflix_US |27.35Mb
  - _354 |44.50Mb
  - _358 |50.16Mb
  - _352 |979.94Mb
  - _353 |175.76Mb
  - _362 |122.14Mb
  - Relay_-ğŸ‡­ğŸ‡°HK_357 |28.26Mb
  - _361 |106.47Mb
  - disney_PY |149.15Mb
  - disney_HK |166.67Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_390 |12.71Mb
  - _391 |10.12Mb
  - _372 |975.86Mb
  - _373 |228.74Mb
  - _392 |11.09Mb
  - _384 |23.59Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_395 |11.60Mb
  - Relay_-ğŸ‡¸ğŸ‡ªSE_370 |37.94Mb
  - _397 |10.61Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_399 |20.61Mb
  - _371 |46.08Mb
  - Relay_ğŸ‡¬ğŸ‡§GB-ğŸ‡³ğŸ‡±NL_405 |955.74Mb
  - disney_DE |203.43Mb
  - ğŸ‡¨ğŸ‡¦CA_402 |42.52Mb
  - disney_HK |28.44Mb
  - ğŸ‡®ğŸ‡¹IT_411 |53.48Mb
  - ğŸ‡²ğŸ‡½MX_424 |38.44Mb
  - ğŸ‡±ğŸ‡¹LT_415 |195.20Mb
  - ğŸ‡®ğŸ‡³IN_410 |154.25Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_431 |40.81Mb
  - ğŸ‡±ğŸ‡¹LT_418 |225.33Mb
  - ğŸ‡±ğŸ‡» LV_422 |78.86Mb
  - ğŸ‡²ğŸ‡©MD_423 |46.58Mb
  - ğŸ‡µğŸ‡¹PT_428 |80.94Mb
  - ğŸ‡¸ğŸ‡¬SG_429 |12.73Mb
  - ğŸ ZZ_433 |41.62Mb
  - Relay_ğŸ‡¯ğŸ‡µJP-ğŸ‡¯ğŸ‡µJP_413 |10.65Mb
  - ğŸ‡±ğŸ‡¹LT_417 |979.99Mb
  - disney_US |26.13Mb
  - netflix_US |54.19Mb
  - _356 |14.23Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
