port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: netflix_NL |65.66Mb
  server: 151.242.251.137
  type: ss
  port: 8080
  password: o5osZg269v5zHpYjr1xY9s
  cipher: chacha20-ietf-poly1305
- name: _356 |22.27Mb
  server: 103.106.3.82
  type: ss
  port: 443
  udp: true
  password: 4SaCIazlgumYkM8FkPzlmwjpyWBDZFBk
  cipher: chacha20-ietf-poly1305
- name: disney_PT |45.75Mb
  server: 185.231.233.112
  type: ss
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: _358 |13.68Mb
  server: 103.36.91.32
  type: ss
  port: 8388
  udp: true
  password: asd123456
  cipher: chacha20-ietf
- name: Relay_-ğŸ‡ºğŸ‡¸US_371 |10.43Mb
  server: planb.mojcn.com
  type: vmess
  port: 16648
  udp: true
  uuid: 77439561-dcef-4e45-803a-743cfa7d20c2
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /
    headers:
      Host: 9e97d6c9e2e0ad3444cbf96d3709366d.mobgslb.tbcache.com
- name: Relay_-ğŸ‡¯ğŸ‡µJP_394 |11.37Mb
  server: planb.mojcn.com
  type: vmess
  port: 16617
  udp: true
  uuid: 77439561-dcef-4e45-803a-743cfa7d20c2
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /
    headers:
      Host: 9e97d6c9e2e0ad3444cbf96d3709366d.mobgslb.tbcache.com
- name: disney_HK |24.10Mb
  server: planb.mojcn.com
  type: vmess
  port: 16632
  udp: true
  uuid: 77439561-dcef-4e45-803a-743cfa7d20c2
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /
    headers:
      Host: 9e97d6c9e2e0ad3444cbf96d3709366d.mobgslb.tbcache.com
- name: disney_netflix_US |46.72Mb
  server: us19-25.998998.best
  type: vmess
  port: 443
  udp: true
  uuid: b376015d-77d9-4482-9aa9-051be76aac65
  alterId: 0
  cipher: auto
  network: ws
  servername: b376015d-77d9-4482-9aa9-051be76aac65.mihomo.baby
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /saoihgreg9384gh8934
    headers:
      Host: b376015d-77d9-4482-9aa9-051be76aac65.mihomo.baby
- name: Relay_-ğŸ‡¹ğŸ‡¼TW_417 |18.72Mb
  server: planb.mojcn.com
  type: vmess
  port: 16616
  udp: true
  uuid: 77439561-dcef-4e45-803a-743cfa7d20c2
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /
    headers:
      Host: 9e97d6c9e2e0ad3444cbf96d3709366d.mobgslb.tbcache.com
- name: _429 |19.78Mb
  server: 74.117.196.232
  type: vmess
  port: 37934
  udp: true
  uuid: 254551f6-ec28-4938-ad0e-0aa4aa1965ec
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /speedtest
- name: Relay_-ğŸ‡¹ğŸ‡¼TW_381 |20.84Mb
  server: m.cnmjin.net
  type: vmess
  port: 16616
  udp: true
  uuid: 77439561-dcef-4e45-803a-743cfa7d20c2
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /
    headers:
      Host: 9e97d6c9e2e0ad3444cbf96d3709366d.mobgslb.tbcache.com
- name: disney_HK |23.86Mb
  server: m.cnmjin.net
  type: vmess
  port: 16622
  udp: true
  uuid: 77439561-dcef-4e45-803a-743cfa7d20c2
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /
    headers:
      Host: 9e97d6c9e2e0ad3444cbf96d3709366d.mobgslb.tbcache.com
- name: disney_SG |10.95Mb
  server: m.cnmjin.net
  type: vmess
  port: 16618
  udp: true
  uuid: 77439561-dcef-4e45-803a-743cfa7d20c2
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /
    headers:
      Host: 9e97d6c9e2e0ad3444cbf96d3709366d.mobgslb.tbcache.com
- name: disney_HK |24.04Mb
  server: planb.mojcn.com
  type: vmess
  port: 16622
  udp: true
  uuid: 77439561-dcef-4e45-803a-743cfa7d20c2
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /
    headers:
      Host: 9e97d6c9e2e0ad3444cbf96d3709366d.mobgslb.tbcache.com
- name: Relay_-ğŸ‡­ğŸ‡°HK_390 |11.14Mb
  server: t.cnmjcn.cyou
  type: vmess
  port: 16632
  udp: true
  uuid: 77439561-dcef-4e45-803a-743cfa7d20c2
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /
    headers:
      Host: 9e97d6c9e2e0ad3444cbf96d3709366d.mobgslb.tbcache.com
- name: Relay_-ğŸ‡­ğŸ‡°HK_396 |11.02Mb
  server: t.cnmjcn.cyou
  type: vmess
  port: 16622
  udp: true
  uuid: 77439561-dcef-4e45-803a-743cfa7d20c2
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /
    headers:
      Host: 9e97d6c9e2e0ad3444cbf96d3709366d.mobgslb.tbcache.com
- name: Relay_-ğŸ‡¸ğŸ‡¬SG_404 |11.40Mb
  server: t.cnmjcn.cyou
  type: vmess
  port: 16618
  udp: true
  uuid: 77439561-dcef-4e45-803a-743cfa7d20c2
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /
    headers:
      Host: 9e97d6c9e2e0ad3444cbf96d3709366d.mobgslb.tbcache.com
- name: Relay_-ğŸ‡¯ğŸ‡µJP_426 |11.20Mb
  server: m.cnmjin.net
  type: vmess
  port: 16617
  udp: true
  uuid: 77439561-dcef-4e45-803a-743cfa7d20c2
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /
    headers:
      Host: 9e97d6c9e2e0ad3444cbf96d3709366d.mobgslb.tbcache.com
- name: disney_HK |24.07Mb
  server: m.cnmjin.net
  type: vmess
  port: 16632
  udp: true
  uuid: 77439561-dcef-4e45-803a-743cfa7d20c2
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /
    headers:
      Host: 9e97d6c9e2e0ad3444cbf96d3709366d.mobgslb.tbcache.com
- name: Relay_-ğŸ‡¯ğŸ‡µJP_444 |11.95Mb
  server: 52.195.176.26
  type: trojan
  port: 2145
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: Relay_-ğŸ‡®ğŸ‡³IN_438 |27.48Mb
  server: planb.mojcn.com
  type: vmess
  port: 16626
  udp: true
  uuid: 77439561-dcef-4e45-803a-743cfa7d20c2
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /
    headers:
      Host: 9e97d6c9e2e0ad3444cbf96d3709366d.mobgslb.tbcache.com
- name: Relay_-ğŸ‡³ğŸ‡±NL_445 |13.12Mb
  server: 160.16.124.55
  type: trojan
  port: 2760
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¯ğŸ‡µJP_450 |22.28Mb
  server: 160.16.138.24
  type: trojan
  port: 1331
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡³ğŸ‡±NL_454 |45.52Mb
  server: 160.16.81.84
  type: trojan
  port: 4054
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: disney_FR |42.99Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 27092
  uuid: a0596ba6-72a3-4366-8992-77088da65bd8
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_HK |29.33Mb
  server: 58.152.25.20
  type: trojan
  port: 443
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: disney_HK |14.19Mb
  server: 58.152.18.95
  type: trojan
  port: 443
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: disney_HK |23.30Mb
  server: 58.152.18.192
  type: trojan
  port: 443
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: netflix_NL |251.07Mb
  server: 82.38.31.190
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_461 |19.52Mb
  server: 82.38.31.179
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡­ğŸ‡°HK_462 |37.27Mb
  server: 87.121.162.249
  type: ss
  country: ğŸ‡­ğŸ‡°HK
  port: 443
  password: JGv616hMWdjfuZ00jYfq7XkBHJZrOBrg
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡²ğŸ‡½MX_478 |243.26Mb
  server: 216.238.89.53
  type: vmess
  country: ğŸ‡²ğŸ‡½MX
  port: 57283
  uuid: 1a5aafc0-6482-451d-fe76-6875b7818579
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡­ğŸ‡°HK_468 |20.40Mb
  server: 8.218.116.26
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 32228
  uuid: e4767e9f-ed00-4f31-a984-a918bdd9b09c
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡­ğŸ‡°HK_469 |29.58Mb
  server: 47.242.162.148
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 31813
  uuid: 00308f3b-747a-4710-b2cb-32c8de9785a1
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
  ws-opts:
    path: /arki?ed=2048
- name: ğŸ‡­ğŸ‡°HK_470 |30.46Mb
  server: 47.243.51.237
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 52801
  uuid: ef93f413-9039-4ddb-aefb-2490287df55a
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
  ws-opts:
    path: /arki?ed=2048
- name: netflix_NL |63.97Mb
  server: 45.87.175.166
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 443
  password: 1RWwXhwfAB5gAEozU4G2Pg
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡°ğŸ‡·KR_476 |10.08Mb
  server: 146.56.112.110
  type: vmess
  country: ğŸ‡°ğŸ‡·KR
  port: 8888
  uuid: e7c302f3-90d6-42dd-9d7d-94a3683a3707
  alterId: 0
  cipher: auto
  network: tcp
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: netflix_IL |73.18Mb
  server: 45.93.95.187
  type: ss
  country: ğŸ‡®ğŸ‡±IL
  port: 8618
  password: 4lUEC91c1d8oeClzDbYpXA
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_487 |10.82Mb
  server: 74.117.196.232
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 37934
  uuid: f1a513d2-c32a-49dc-8e64-d4f8a2f1e001
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /speedtest
- name: ğŸ‡ºğŸ‡¸US_485 |41.87Mb
  server: 100.25.219.192
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡ºğŸ‡¸US_490 |10.08Mb
  server: 74.117.196.232
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 37934
  uuid: 35f332d0-0b05-4cc6-91cb-ec0d4465055f
  alterId: 0
  cipher: auto
  network: ws
  servername: imafake.locker
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /speedtest
    headers:
      HOST: imafake.locker
- name: ğŸ‡ºğŸ‡¸US_491 |16.11Mb
  server: 74.117.196.232
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 37934
  uuid: c50f9480-2e1d-40db-9458-630e79636663
  alterId: 0
  cipher: auto
  network: ws
  servername: imafake.locker
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /speedtest
    headers:
      HOST: imafake.locker
- name: disney_netflix_US |20.66Mb
  server: 38.84.201.21
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 53487
  uuid: c3c1ec05-df2c-4975-9b42-e9b007564eb1
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡ºğŸ‡¸US_493 |18.70Mb
  server: 74.117.196.232
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 37934
  uuid: b2da9920-b0a7-4354-9e26-3833ab8d00d0
  alterId: 0
  cipher: auto
  network: ws
  servername: imafake.locker
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /speedtest
    headers:
      HOST: imafake.locker
- name: ğŸ‡²ğŸ‡¾MY_479 |30.84Mb
  server: 38.54.98.110
  type: vmess
  country: ğŸ‡²ğŸ‡¾MY
  port: 2052
  uuid: 665d9b8f-153d-4907-adac-de12afd9c851
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: ğŸ‡¸ğŸ‡¬SG_482 |11.05Mb
  server: 68.183.178.131
  type: vmess
  country: ğŸ‡¸ğŸ‡¬SG
  port: 58607
  uuid: c11c32cb-27b3-4afa-c0f3-fb250aa4959e
  alterId: 0
  cipher: auto
  network: ws
  servername: www.12333.monster
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /
    headers:
      HOST: www.12333.monster
- name: disney_TR |31.63Mb
  server: tr-1.stunnel.cc
  type: ss
  country: ğŸ‡¹ğŸ‡·TR
  port: 8444
  password: tunnel-fbrof
  cipher: chacha20-ietf-poly1305
- name: disney_HK |20.50Mb
  server: 45.136.12.37
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 38141
  uuid: fd291be6-b48d-43a1-da38-66c7f80e2f80
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_US |33.72Mb
  server: cf.fovi.tk
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  uuid: bf67437e-6c90-45ca-abc2-c7240a5ce2aa
  alterId: 0
  cipher: auto
  network: ws
  servername: foxlux.fovi.tk
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /eisasqa
    headers:
      HOST: foxlux.fovi.tk
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - netflix_NL |65.66Mb
  - _356 |22.27Mb
  - disney_PT |45.75Mb
  - _358 |13.68Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_371 |10.43Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_394 |11.37Mb
  - disney_HK |24.10Mb
  - disney_netflix_US |46.72Mb
  - Relay_-ğŸ‡¹ğŸ‡¼TW_417 |18.72Mb
  - _429 |19.78Mb
  - Relay_-ğŸ‡¹ğŸ‡¼TW_381 |20.84Mb
  - disney_HK |23.86Mb
  - disney_SG |10.95Mb
  - disney_HK |24.04Mb
  - Relay_-ğŸ‡­ğŸ‡°HK_390 |11.14Mb
  - Relay_-ğŸ‡­ğŸ‡°HK_396 |11.02Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_404 |11.40Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_426 |11.20Mb
  - disney_HK |24.07Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_444 |11.95Mb
  - Relay_-ğŸ‡®ğŸ‡³IN_438 |27.48Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_445 |13.12Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_450 |22.28Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_454 |45.52Mb
  - disney_FR |42.99Mb
  - disney_HK |29.33Mb
  - disney_HK |14.19Mb
  - disney_HK |23.30Mb
  - netflix_NL |251.07Mb
  - ğŸ‡¬ğŸ‡§GB_461 |19.52Mb
  - ğŸ‡­ğŸ‡°HK_462 |37.27Mb
  - ğŸ‡²ğŸ‡½MX_478 |243.26Mb
  - ğŸ‡­ğŸ‡°HK_468 |20.40Mb
  - ğŸ‡­ğŸ‡°HK_469 |29.58Mb
  - ğŸ‡­ğŸ‡°HK_470 |30.46Mb
  - netflix_NL |63.97Mb
  - ğŸ‡°ğŸ‡·KR_476 |10.08Mb
  - netflix_IL |73.18Mb
  - ğŸ‡ºğŸ‡¸US_487 |10.82Mb
  - ğŸ‡ºğŸ‡¸US_485 |41.87Mb
  - ğŸ‡ºğŸ‡¸US_490 |10.08Mb
  - ğŸ‡ºğŸ‡¸US_491 |16.11Mb
  - disney_netflix_US |20.66Mb
  - ğŸ‡ºğŸ‡¸US_493 |18.70Mb
  - ğŸ‡²ğŸ‡¾MY_479 |30.84Mb
  - ğŸ‡¸ğŸ‡¬SG_482 |11.05Mb
  - disney_TR |31.63Mb
  - disney_HK |20.50Mb
  - disney_netflix_US |33.72Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - netflix_NL |65.66Mb
  - _356 |22.27Mb
  - disney_PT |45.75Mb
  - _358 |13.68Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_371 |10.43Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_394 |11.37Mb
  - disney_HK |24.10Mb
  - disney_netflix_US |46.72Mb
  - Relay_-ğŸ‡¹ğŸ‡¼TW_417 |18.72Mb
  - _429 |19.78Mb
  - Relay_-ğŸ‡¹ğŸ‡¼TW_381 |20.84Mb
  - disney_HK |23.86Mb
  - disney_SG |10.95Mb
  - disney_HK |24.04Mb
  - Relay_-ğŸ‡­ğŸ‡°HK_390 |11.14Mb
  - Relay_-ğŸ‡­ğŸ‡°HK_396 |11.02Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_404 |11.40Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_426 |11.20Mb
  - disney_HK |24.07Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_444 |11.95Mb
  - Relay_-ğŸ‡®ğŸ‡³IN_438 |27.48Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_445 |13.12Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_450 |22.28Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_454 |45.52Mb
  - disney_FR |42.99Mb
  - disney_HK |29.33Mb
  - disney_HK |14.19Mb
  - disney_HK |23.30Mb
  - netflix_NL |251.07Mb
  - ğŸ‡¬ğŸ‡§GB_461 |19.52Mb
  - ğŸ‡­ğŸ‡°HK_462 |37.27Mb
  - ğŸ‡²ğŸ‡½MX_478 |243.26Mb
  - ğŸ‡­ğŸ‡°HK_468 |20.40Mb
  - ğŸ‡­ğŸ‡°HK_469 |29.58Mb
  - ğŸ‡­ğŸ‡°HK_470 |30.46Mb
  - netflix_NL |63.97Mb
  - ğŸ‡°ğŸ‡·KR_476 |10.08Mb
  - netflix_IL |73.18Mb
  - ğŸ‡ºğŸ‡¸US_487 |10.82Mb
  - ğŸ‡ºğŸ‡¸US_485 |41.87Mb
  - ğŸ‡ºğŸ‡¸US_490 |10.08Mb
  - ğŸ‡ºğŸ‡¸US_491 |16.11Mb
  - disney_netflix_US |20.66Mb
  - ğŸ‡ºğŸ‡¸US_493 |18.70Mb
  - ğŸ‡²ğŸ‡¾MY_479 |30.84Mb
  - ğŸ‡¸ğŸ‡¬SG_482 |11.05Mb
  - disney_TR |31.63Mb
  - disney_HK |20.50Mb
  - disney_netflix_US |33.72Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
