port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: disney_netflix_US |66.22Mb
  server: 184.72.124.41
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: disney_netflix_US |63.97Mb
  server: 54.227.38.247
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: disney_netflix_US |66.44Mb
  server: 54.159.62.233
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: _174 |63.52Mb
  server: 54.91.94.165
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: disney_netflix_US |65.26Mb
  server: 54.144.64.227
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: _179 |67.15Mb
  server: 3.93.196.82
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: disney_netflix_US |60.21Mb
  server: 23.22.182.151
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: netflix_IE |136.96Mb
  server: 34.251.86.159
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: _170 |163.20Mb
  server: 51.20.125.235
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: Pool__177 |35.11Mb
  server: 185.103.110.68
  type: ss
  port: 18283
  udp: true
  password: y3o3ra6edy5nfc6hyb2n
  cipher: aes-128-gcm
- name: disney_netflix_US |57.81Mb
  server: 3.89.113.22
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: netflix_FI |49.56Mb
  server: 77.83.247.206
  type: ss
  port: 18284
  udp: true
  password: tijsjk3iwzc6b10azb0y
  cipher: aes-128-gcm
- name: netflix_SE |102.44Mb
  server: 13.61.13.231
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: disney_netflix_US |60.60Mb
  server: 13.222.155.147
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: _190 |27.53Mb
  server: 107.174.114.71
  type: ss
  port: 443
  password: 595HLF3fHUuw0McM51tpvPygSIB1uf4D
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_US |66.36Mb
  server: 98.89.32.62
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: disney_netflix_US |67.05Mb
  server: 50.19.46.248
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: disney_netflix_US |58.25Mb
  server: 13.218.107.141
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: _203 |36.58Mb
  server: 98.81.59.20
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: _192 |210.30Mb
  server: 62.133.60.43
  type: ss
  port: 36456
  udp: true
  password: lXk5EGzRVYDjYqcWC5FwD3
  cipher: chacha20-ietf-poly1305
- name: netflix_IE |165.81Mb
  server: 3.250.105.240
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: disney_netflix_US |41.82Mb
  server: 163.192.49.195
  type: vmess
  port: 443
  uuid: bcb7c581-3c95-4569-a4e7-918141e91ea3
  alterId: 0
  cipher: auto
  network: http
  http-opts:
    path:
    - /
    headers:
      Host:
      - a.189.cn
  h2-opts: {}
- name: netflix_IE |210.80Mb
  server: 3.253.99.197
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: netflix_IE |190.10Mb
  server: 54.246.35.116
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: disney_US |40.41Mb
  server: 165.140.216.141
  type: vmess
  port: 443
  uuid: e7d72a8d-26f2-4b54-b366-0c43e0bcba7d
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _214 |50.71Mb
  server: 43.165.7.71
  type: vmess
  port: 19751
  uuid: 6cfa6103-5d06-40cb-f452-b563db578288
  alterId: 0
  cipher: auto
  network: http
  http-opts:
    method: GET
    path:
    - /
  h2-opts: {}
- name: _207 |159.39Mb
  server: 38.180.16.86
  type: vmess
  port: 36236
  uuid: a58bc1a5-8c18-49ff-9453-c331b52f45dc
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: disney_netflix_US |29.37Mb
  server: 192.204.47.79
  type: vmess
  port: 42277
  udp: true
  uuid: aee61b21-e85a-484b-f203-b245f1451cff
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _233 |22.84Mb
  server: 15.235.41.200
  type: vmess
  port: 80
  uuid: 58fe1542-5290-40ad-815a-77707a81afe5
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /IOebhLMhl1CTbFHbL95myfRX2
- name: Relay_-ğŸ‡ºğŸ‡¸US_229 |28.43Mb
  server: 20251118.yixianled.com
  type: vmess
  port: 33921
  udp: true
  uuid: 6578c489-28d2-4f12-8c2f-9f2d8789626d
  alterId: 0
  cipher: auto
  network: ws
  servername: 20251118.yixianled.com
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /happy
    headers:
      Host: 20251118.yixianled.com
- name: disney_netflix_DE |260.45Mb
  server: 85.195.101.122
  type: vmess
  port: 40878
  uuid: f3d4167e-b15e-4e46-82e9-9286ef93fda7
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _231 |54.86Mb
  server: 38.180.16.86
  type: vmess
  port: 38039
  uuid: 244a3464-1269-43b3-b491-4dc2713eb3f6
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _225 |11.25Mb
  server: 130.162.152.253
  type: vmess
  port: 56867
  uuid: 5206bb9f-2cbc-44ac-de2a-471439a23707
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _216 |27.92Mb
  server: 8.218.105.196
  type: vmess
  port: 52752
  uuid: 925bdbf5-72be-4437-bebf-441c61089f6b
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: disney_netflix_US |33.39Mb
  server: 69.84.182.18
  type: trojan
  port: 8443
  udp: true
  password: b1fec179-3d5a-4ec5-bf3c-e10668543b4b
  sni: cdn-node-oss-62.anycdn.de
  ws-opts:
    path: /profile/us2
    headers:
      Host: cdn-node-oss-62.anycdn.de
  network: ws
- name: _228 |10.63Mb
  server: 140.238.2.250
  type: vmess
  port: 443
  uuid: 41a7089a-040b-4538-8b8d-010902405bde
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: disney_netflix_US |31.05Mb
  server: 69.84.182.108
  type: trojan
  port: 8443
  udp: true
  password: b1fec179-3d5a-4ec5-bf3c-e10668543b4b
  sni: cdn-node-oss-61.anycdn.de
  ws-opts:
    path: /profile/us1
    headers:
      Host: cdn-node-oss-61.anycdn.de
  network: ws
- name: disney_netflix_GB |268.31Mb
  server: 172.67.134.185
  type: trojan
  port: 443
  udp: true
  password: POORIARED
  sni: reDfRee8.REDFree8.ir
  ws-opts:
    path: /eyJqdW5rIjoiVUl6eXhLZkkwUTJ3ZzkiLCJwcm90b2NvbCI6InRyIiwibW9kZSI6InByb3h5aXAiLCJwYW5lbElQcyI6W119?ed=2560
    headers:
      Host: reDfRee8.REDFree8.ir
  network: ws
- name: _217 |35.98Mb
  server: 89.31.120.192
  type: vmess
  port: 443
  uuid: 44537595-9ccc-4b83-8936-5f9ad3229019
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: Relay_-ğŸ‡§ğŸ‡·BR_242 |73.02Mb
  server: pq-brazil1.09vpn.com
  type: vmess
  port: 80
  uuid: c04c3b34-70fd-4fec-963e-c12d09f36bef
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /vmess/
    headers:
      Host: pq-brazil1.09vpn.com
- name: netflix_SE |186.12Mb
  server: 70.34.218.149
  type: trojan
  port: 11930
  password: BaeSzHdfJIR13l67
  sni: softpillow.silentrocket.click
- name: netflix_CA |161.55Mb
  server: 38.96.254.102
  type: trojan
  port: 18509
  password: .ie4rghJuMkcf0oF
  sni: shoppingmall.electricbanana.click
- name: Relay_-ğŸ‡­ğŸ‡°HK_240 |15.88Mb
  server: 154.21.201.83
  type: vmess
  port: 443
  uuid: 4bf075f5-4d5e-4d39-f5ab-b32a86250f0e
  alterId: 0
  cipher: auto
  network: ws
  servername: hk.nbee.pp.ua
  http-opts: {}
  h2-opts: {}
  tls: true
  ws-opts:
    path: /aa
    headers:
      Host: hk.nbee.pp.ua
- name: Relay_-ğŸ‡¯ğŸ‡µJP_246 |16.78Mb
  server: 153.121.73.102
  type: trojan
  port: 1331
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: _244 |12.87Mb
  server: 47.243.51.237
  type: vmess
  port: 52801
  uuid: ef93f413-9039-4ddb-aefb-2490287df55a
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /arki
- name: Relay_-ğŸ‡¯ğŸ‡µJP_255 |18.86Mb
  server: 160.16.70.180
  type: trojan
  port: 1331
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: _256 |14.63Mb
  server: 160.16.63.16
  type: trojan
  port: 4054
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: netflix_FR |169.34Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 27092
  uuid: a0596ba6-72a3-4366-8992-77088da65bd8
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: _251 |21.25Mb
  server: 58.152.53.174
  type: trojan
  port: 443
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: netflix_FR |163.78Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 40433
  uuid: d8fd8955-78db-49ba-d86f-3e4729f6ac4d
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_-ğŸ‡¸ğŸ‡¬SG_258 |10.18Mb
  server: 160.16.150.76
  type: trojan
  port: 3145
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: disney_netflix_US |68.11Mb
  server: 18.207.122.59
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡¬ğŸ‡§GB_275 |234.68Mb
  server: 82.38.31.194
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: _262 |12.13Mb
  server: 153.121.53.187
  type: trojan
  port: 3093
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: ğŸ‡¬ğŸ‡§GB_276 |210.63Mb
  server: 82.38.31.191
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: netflix_NL |241.30Mb
  server: 82.38.31.217
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡²ğŸ‡½MX_285 |15.11Mb
  server: 216.238.87.47
  type: vmess
  country: ğŸ‡²ğŸ‡½MX
  port: 27502
  uuid: b8155ce4-7e08-4c40-800f-8671312b7124
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: netflix_IE |193.75Mb
  server: 52.50.200.2
  type: ss
  country: ğŸ‡®ğŸ‡ªIE
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: Relay_ğŸZZ-ğŸ‡®ğŸ‡·IR_290 |16.10Mb
  server: cf.fovi.tk
  type: vmess
  country: ğŸZZ
  port: 443
  uuid: bf67437e-6c90-45ca-abc2-c7240a5ce2aa
  alterId: 0
  cipher: auto
  network: ws
  servername: foxpol.fovi.tk
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /eisasqa
    headers:
      HOST: foxpol.fovi.tk
- name: disney_netflix_DE |176.79Mb
  server: cpanel.navar1.ir
  type: vmess
  country: ğŸ‡©ğŸ‡ªDE
  port: 100
  uuid: 95c6f6f0-84f7-4443-8a50-a59f8e66f5ee
  alterId: 0
  cipher: auto
  network: tcp
  servername: cpanel.navar1.ir
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡­ğŸ‡°HK_279 |15.04Mb
  server: 45.207.157.29
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 13852
  uuid: 845764df-ecb3-4b13-bed2-bf1551b68e9a
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_-ğŸ‡ºğŸ‡¸US_223 |13.41Mb
  server: yg1.ygkkk.dpdns.org
  type: vmess
  port: 443
  udp: true
  uuid: 7a88d322-eb4a-4a59-8c62-8c60d76abf4b
  alterId: 0
  cipher: auto
  network: ws
  servername: jporacleyg.336697.xyz
  http-opts: {}
  h2-opts: {}
  tls: true
  ws-opts:
    path: /7a88d322-eb4a-4a59-8c62-8c60d76abf4b-vm?ed=2048
    headers:
      Host: jporacleyg.336697.xyz
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - disney_netflix_US |66.22Mb
  - disney_netflix_US |63.97Mb
  - disney_netflix_US |66.44Mb
  - _174 |63.52Mb
  - disney_netflix_US |65.26Mb
  - _179 |67.15Mb
  - disney_netflix_US |60.21Mb
  - netflix_IE |136.96Mb
  - _170 |163.20Mb
  - Pool__177 |35.11Mb
  - disney_netflix_US |57.81Mb
  - netflix_FI |49.56Mb
  - netflix_SE |102.44Mb
  - disney_netflix_US |60.60Mb
  - _190 |27.53Mb
  - disney_netflix_US |66.36Mb
  - disney_netflix_US |67.05Mb
  - disney_netflix_US |58.25Mb
  - _203 |36.58Mb
  - _192 |210.30Mb
  - netflix_IE |165.81Mb
  - disney_netflix_US |41.82Mb
  - netflix_IE |210.80Mb
  - netflix_IE |190.10Mb
  - disney_US |40.41Mb
  - _214 |50.71Mb
  - _207 |159.39Mb
  - disney_netflix_US |29.37Mb
  - _233 |22.84Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_229 |28.43Mb
  - disney_netflix_DE |260.45Mb
  - _231 |54.86Mb
  - _225 |11.25Mb
  - _216 |27.92Mb
  - disney_netflix_US |33.39Mb
  - _228 |10.63Mb
  - disney_netflix_US |31.05Mb
  - disney_netflix_GB |268.31Mb
  - _217 |35.98Mb
  - Relay_-ğŸ‡§ğŸ‡·BR_242 |73.02Mb
  - netflix_SE |186.12Mb
  - netflix_CA |161.55Mb
  - Relay_-ğŸ‡­ğŸ‡°HK_240 |15.88Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_246 |16.78Mb
  - _244 |12.87Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_255 |18.86Mb
  - _256 |14.63Mb
  - netflix_FR |169.34Mb
  - _251 |21.25Mb
  - netflix_FR |163.78Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_258 |10.18Mb
  - disney_netflix_US |68.11Mb
  - ğŸ‡¬ğŸ‡§GB_275 |234.68Mb
  - _262 |12.13Mb
  - ğŸ‡¬ğŸ‡§GB_276 |210.63Mb
  - netflix_NL |241.30Mb
  - ğŸ‡²ğŸ‡½MX_285 |15.11Mb
  - netflix_IE |193.75Mb
  - Relay_ğŸZZ-ğŸ‡®ğŸ‡·IR_290 |16.10Mb
  - disney_netflix_DE |176.79Mb
  - ğŸ‡­ğŸ‡°HK_279 |15.04Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_223 |13.41Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - disney_netflix_US |66.22Mb
  - disney_netflix_US |63.97Mb
  - disney_netflix_US |66.44Mb
  - _174 |63.52Mb
  - disney_netflix_US |65.26Mb
  - _179 |67.15Mb
  - disney_netflix_US |60.21Mb
  - netflix_IE |136.96Mb
  - _170 |163.20Mb
  - Pool__177 |35.11Mb
  - disney_netflix_US |57.81Mb
  - netflix_FI |49.56Mb
  - netflix_SE |102.44Mb
  - disney_netflix_US |60.60Mb
  - _190 |27.53Mb
  - disney_netflix_US |66.36Mb
  - disney_netflix_US |67.05Mb
  - disney_netflix_US |58.25Mb
  - _203 |36.58Mb
  - _192 |210.30Mb
  - netflix_IE |165.81Mb
  - disney_netflix_US |41.82Mb
  - netflix_IE |210.80Mb
  - netflix_IE |190.10Mb
  - disney_US |40.41Mb
  - _214 |50.71Mb
  - _207 |159.39Mb
  - disney_netflix_US |29.37Mb
  - _233 |22.84Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_229 |28.43Mb
  - disney_netflix_DE |260.45Mb
  - _231 |54.86Mb
  - _225 |11.25Mb
  - _216 |27.92Mb
  - disney_netflix_US |33.39Mb
  - _228 |10.63Mb
  - disney_netflix_US |31.05Mb
  - disney_netflix_GB |268.31Mb
  - _217 |35.98Mb
  - Relay_-ğŸ‡§ğŸ‡·BR_242 |73.02Mb
  - netflix_SE |186.12Mb
  - netflix_CA |161.55Mb
  - Relay_-ğŸ‡­ğŸ‡°HK_240 |15.88Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_246 |16.78Mb
  - _244 |12.87Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_255 |18.86Mb
  - _256 |14.63Mb
  - netflix_FR |169.34Mb
  - _251 |21.25Mb
  - netflix_FR |163.78Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_258 |10.18Mb
  - disney_netflix_US |68.11Mb
  - ğŸ‡¬ğŸ‡§GB_275 |234.68Mb
  - _262 |12.13Mb
  - ğŸ‡¬ğŸ‡§GB_276 |210.63Mb
  - netflix_NL |241.30Mb
  - ğŸ‡²ğŸ‡½MX_285 |15.11Mb
  - netflix_IE |193.75Mb
  - Relay_ğŸZZ-ğŸ‡®ğŸ‡·IR_290 |16.10Mb
  - disney_netflix_DE |176.79Mb
  - ğŸ‡­ğŸ‡°HK_279 |15.04Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_223 |13.41Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
