port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: netflix_US |39.52Mb
  server: 38.14.99.179
  type: vmess
  port: 59807
  udp: true
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: _440 |19.38Mb
  server: 152.70.92.69
  type: vmess
  port: 80
  uuid: bb9c3993-a4b9-4dad-aeb9-ac86371ae68b
  alterId: 0
  cipher: auto
  network: http
  http-opts:
    path:
    - /
  h2-opts: {}
- name: netflix_NL |230.07Mb
  server: 151.242.251.137
  type: ss
  port: 8080
  password: o5osZg269v5zHpYjr1xY9s
  cipher: chacha20-ietf-poly1305
- name: disney_HK |133.39Mb
  server: 103.149.182.38
  type: ss
  port: 8388
  udp: true
  password: asd123456
  cipher: chacha20-ietf
- name: Relay_-ğŸ‡¯ğŸ‡µJP_560 |18.93Mb
  server: 160.16.87.174
  type: trojan
  port: 3169
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: disney_HK |10.91Mb
  server: 58.152.25.20
  type: trojan
  port: 443
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: _386 |10.59Mb
  server: 185.153.197.5
  type: ss
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: Relay_-ğŸ‡³ğŸ‡±NL_561 |37.44Mb
  server: 160.16.63.16
  type: trojan
  port: 4054
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¸ğŸ‡¬SG_568 |10.47Mb
  server: 160.16.107.37
  type: trojan
  port: 507
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¯ğŸ‡µJP_573 |13.51Mb
  server: 153.121.65.107
  type: trojan
  port: 3169
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: disney_HK |26.79Mb
  server: 58.152.30.120
  type: trojan
  port: 443
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: disney_HK |11.63Mb
  server: 58.152.110.154
  type: trojan
  port: 443
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: _574 |23.18Mb
  server: 58.152.53.8
  type: trojan
  port: 443
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: Relay_-ğŸ‡³ğŸ‡±NL_575 |17.91Mb
  server: 160.16.116.227
  type: trojan
  port: 2890
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¯ğŸ‡µJP_577 |17.08Mb
  server: 153.121.65.107
  type: trojan
  port: 1331
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¸ğŸ‡¬SG_578 |17.61Mb
  server: 160.16.131.243
  type: trojan
  port: 127
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡³ğŸ‡±NL_579 |33.69Mb
  server: 153.121.39.240
  type: trojan
  port: 4054
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: disney_FR |31.34Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 40433
  uuid: d8fd8955-78db-49ba-d86f-3e4729f6ac4d
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_FR |27.35Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 27092
  uuid: a0596ba6-72a3-4366-8992-77088da65bd8
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: netflix_NL |199.22Mb
  server: 82.38.31.218
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_586 |192.88Mb
  server: 82.38.31.190
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: netflix_NL |223.58Mb
  server: 82.38.31.210
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡­ğŸ‡°HK_598 |10.53Mb
  server: 87.121.162.249
  type: ss
  country: ğŸ‡­ğŸ‡°HK
  port: 443
  password: JGv616hMWdjfuZ00jYfq7XkBHJZrOBrg
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡­ğŸ‡°HK_621 |74.53Mb
  server: 8.210.134.183
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 3721
  uuid: e72f5c6b-220f-40b3-a115-2d81473458cf
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
  ws-opts:
    path: /
- name: ğŸ‡­ğŸ‡°HK_624 |27.20Mb
  server: 8.218.116.26
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 32228
  uuid: e4767e9f-ed00-4f31-a984-a918bdd9b09c
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡­ğŸ‡°HK_634 |30.08Mb
  server: 47.242.140.52
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 48219
  uuid: 006893c6-79b1-4c44-94ff-b8bbea065f1f
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
  ws-opts:
    path: /arki?ed=2048
- name: disney_HK |27.71Mb
  server: 219.79.186.107
  type: trojan
  country: ğŸ‡­ğŸ‡°HK
  port: 443
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: ğŸ‡²ğŸ‡½MX_644 |38.48Mb
  server: 216.238.89.53
  type: vmess
  country: ğŸ‡²ğŸ‡½MX
  port: 57283
  uuid: 1a5aafc0-6482-451d-fe76-6875b7818579
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_ğŸ‡°ğŸ‡·KR-ğŸ‡°ğŸ‡·KR_643 |10.27Mb
  server: seoul03.zgjok.com
  type: vmess
  country: ğŸ‡°ğŸ‡·KR
  port: 443
  uuid: 72a0dac4-9689-4a57-b164-5c65bfa94772
  alterId: 0
  cipher: auto
  network: ws
  servername: seoul03.zgjok.com
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /
    headers:
      HOST: seoul03.zgjok.com
- name: ğŸ‡®ğŸ‡³IN_639 |180.12Mb
  server: 134.209.147.198
  type: ss
  country: ğŸ‡®ğŸ‡³IN
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ğŸ‡ºğŸ‡¸US_700 |42.73Mb
  server: 104.192.226.106
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ğŸ‡²ğŸ‡¾MY_645 |29.46Mb
  server: 38.54.98.110
  type: vmess
  country: ğŸ‡²ğŸ‡¾MY
  port: 2052
  uuid: 665d9b8f-153d-4907-adac-de12afd9c851
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: ğŸ‡·ğŸ‡ºRU_648 |65.83Mb
  server: 109.71.246.210
  type: ss
  country: ğŸ‡·ğŸ‡ºRU
  port: 56689
  password: YQCSKoCF3QazW8YlvDBWA4
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸ‡­ğŸ‡°HK-ğŸ‡ºğŸ‡¸US_626 |18.48Mb
  server: v24.hdacd.com
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 30824
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: auto
  network: tcp
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: netflix_US |39.53Mb
  server: 38.14.99.163
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 59807
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: auto
  network: tcp
  servername: 38.14.99.163
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡¸ğŸ‡¬SG_649 |11.05Mb
  server: 68.183.178.131
  type: vmess
  country: ğŸ‡¸ğŸ‡¬SG
  port: 58607
  uuid: c11c32cb-27b3-4afa-c0f3-fb250aa4959e
  alterId: 0
  cipher: auto
  network: ws
  servername: www.12333.monster
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /
    headers:
      HOST: www.12333.monster
- name: netflix_LU |179.67Mb
  server: 45.12.144.18
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: LQyAUItafUmmO3EZZx9UbiX6IGydSBgL
  cipher: chacha20-ietf-poly1305
- name: disney_HK |99.57Mb
  server: 45.136.12.37
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 38141
  uuid: fd291be6-b48d-43a1-da38-66c7f80e2f80
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡ºğŸ‡¸US_703 |126.62Mb
  server: 45.12.136.170
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: l668XHPejoSNNuD66BYzyehaCpZexiF7
  cipher: chacha20-ietf-poly1305
- name: disney_DE |284.30Mb
  server: clr.ducks.tel
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 17844
  password: '907560230'
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡·ğŸ‡ºRU_698 |229.04Mb
  server: clr.ducks.tel
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 17847
  password: '907560230'
  cipher: chacha20-ietf-poly1305
- name: _379 |46.09Mb
  server: 45.83.20.206
  type: ss
  port: 443
  udp: true
  password: g5RQoxQuVtnFv3Xxsa8edPisXNPnyWKy
  cipher: chacha20-ietf-poly1305
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - netflix_US |39.52Mb
  - _440 |19.38Mb
  - netflix_NL |230.07Mb
  - disney_HK |133.39Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_560 |18.93Mb
  - disney_HK |10.91Mb
  - _386 |10.59Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_561 |37.44Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_568 |10.47Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_573 |13.51Mb
  - disney_HK |26.79Mb
  - disney_HK |11.63Mb
  - _574 |23.18Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_575 |17.91Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_577 |17.08Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_578 |17.61Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_579 |33.69Mb
  - disney_FR |31.34Mb
  - disney_FR |27.35Mb
  - netflix_NL |199.22Mb
  - ğŸ‡¬ğŸ‡§GB_586 |192.88Mb
  - netflix_NL |223.58Mb
  - ğŸ‡­ğŸ‡°HK_598 |10.53Mb
  - ğŸ‡­ğŸ‡°HK_621 |74.53Mb
  - ğŸ‡­ğŸ‡°HK_624 |27.20Mb
  - ğŸ‡­ğŸ‡°HK_634 |30.08Mb
  - disney_HK |27.71Mb
  - ğŸ‡²ğŸ‡½MX_644 |38.48Mb
  - Relay_ğŸ‡°ğŸ‡·KR-ğŸ‡°ğŸ‡·KR_643 |10.27Mb
  - ğŸ‡®ğŸ‡³IN_639 |180.12Mb
  - ğŸ‡ºğŸ‡¸US_700 |42.73Mb
  - ğŸ‡²ğŸ‡¾MY_645 |29.46Mb
  - ğŸ‡·ğŸ‡ºRU_648 |65.83Mb
  - Relay_ğŸ‡­ğŸ‡°HK-ğŸ‡ºğŸ‡¸US_626 |18.48Mb
  - netflix_US |39.53Mb
  - ğŸ‡¸ğŸ‡¬SG_649 |11.05Mb
  - netflix_LU |179.67Mb
  - disney_HK |99.57Mb
  - ğŸ‡ºğŸ‡¸US_703 |126.62Mb
  - disney_DE |284.30Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡·ğŸ‡ºRU_698 |229.04Mb
  - _379 |46.09Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - netflix_US |39.52Mb
  - _440 |19.38Mb
  - netflix_NL |230.07Mb
  - disney_HK |133.39Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_560 |18.93Mb
  - disney_HK |10.91Mb
  - _386 |10.59Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_561 |37.44Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_568 |10.47Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_573 |13.51Mb
  - disney_HK |26.79Mb
  - disney_HK |11.63Mb
  - _574 |23.18Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_575 |17.91Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_577 |17.08Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_578 |17.61Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_579 |33.69Mb
  - disney_FR |31.34Mb
  - disney_FR |27.35Mb
  - netflix_NL |199.22Mb
  - ğŸ‡¬ğŸ‡§GB_586 |192.88Mb
  - netflix_NL |223.58Mb
  - ğŸ‡­ğŸ‡°HK_598 |10.53Mb
  - ğŸ‡­ğŸ‡°HK_621 |74.53Mb
  - ğŸ‡­ğŸ‡°HK_624 |27.20Mb
  - ğŸ‡­ğŸ‡°HK_634 |30.08Mb
  - disney_HK |27.71Mb
  - ğŸ‡²ğŸ‡½MX_644 |38.48Mb
  - Relay_ğŸ‡°ğŸ‡·KR-ğŸ‡°ğŸ‡·KR_643 |10.27Mb
  - ğŸ‡®ğŸ‡³IN_639 |180.12Mb
  - ğŸ‡ºğŸ‡¸US_700 |42.73Mb
  - ğŸ‡²ğŸ‡¾MY_645 |29.46Mb
  - ğŸ‡·ğŸ‡ºRU_648 |65.83Mb
  - Relay_ğŸ‡­ğŸ‡°HK-ğŸ‡ºğŸ‡¸US_626 |18.48Mb
  - netflix_US |39.53Mb
  - ğŸ‡¸ğŸ‡¬SG_649 |11.05Mb
  - netflix_LU |179.67Mb
  - disney_HK |99.57Mb
  - ğŸ‡ºğŸ‡¸US_703 |126.62Mb
  - disney_DE |284.30Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡·ğŸ‡ºRU_698 |229.04Mb
  - _379 |46.09Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
