port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: ' |40.73Mb'
  server: 173.234.29.2
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ' |46.38Mb'
  server: 66.23.207.82
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ' |24.45Mb'
  server: 167.160.90.178
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ' |12.31Mb'
  server: 138.186.142.81
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ' |12.58Mb'
  server: 103.106.228.247
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ' |23.86Mb'
  server: 109.61.46.43
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡©ğŸ‡ªDE_160 |21.99Mb
  server: 81.19.141.45
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 443
  password: GolXNbBG1EfcTZhaccBOAG
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡©ğŸ‡ªDE_168 |10.72Mb
  server: 81.19.141.45
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 443
  password: OL7MQydIsTbln3xOq4lVvM
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡©ğŸ‡ªDE_162 |28.09Mb
  server: 81.19.141.45
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 443
  password: vB6TuCo7UfccmLm3qxheKt
  cipher: chacha20-ietf-poly1305
- name: ' |26.23Mb'
  server: 154.205.153.107
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ' |17.22Mb'
  server: 176.123.1.175
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡©ğŸ‡ªDE_169 |12.38Mb
  server: 18.199.98.206
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡©ğŸ‡ªDE_174 |19.32Mb
  server: 3.120.149.63
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡©ğŸ‡ªDE_178 |13.16Mb
  server: 81.19.141.45
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 443
  password: mGmgnK6npgEFJS6kk2ox2P
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡©ğŸ‡ªDE_181 |12.01Mb
  server: 3.72.36.198
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡©ğŸ‡ªDE_182 |46.00Mb
  server: 81.19.141.45
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 443
  password: 4FGE1sy7r8aLz8esdjXCXf
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡©ğŸ‡ªDE_183 |47.10Mb
  server: 81.19.141.45
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 443
  password: cM0e4xONCGzYr68GM821pi
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ªğŸ‡¸ES_190 |31.72Mb
  server: 194.87.45.189
  type: ss
  country: ğŸ‡ªğŸ‡¸ES
  port: 443
  password: bwCWtYQWtc4ez14JGe7K51
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ªğŸ‡¸ES_191 |29.76Mb
  server: 194.87.45.189
  type: ss
  country: ğŸ‡ªğŸ‡¸ES
  port: 443
  password: sZXSQhZw1EWmHwPKWVBWBa
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ªğŸ‡¸ES_193 |29.35Mb
  server: 194.87.45.189
  type: ss
  country: ğŸ‡ªğŸ‡¸ES
  port: 443
  password: N84ONRImQbuWzmeIuEGxIH
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ªğŸ‡¸ES_194 |11.43Mb
  server: 194.87.45.189
  type: ss
  country: ğŸ‡ªğŸ‡¸ES
  port: 443
  password: PF8oJRt30ghJcFgHkk4yi5
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ªğŸ‡¸ES_195 |22.27Mb
  server: 194.87.45.189
  type: ss
  country: ğŸ‡ªğŸ‡¸ES
  port: 443
  password: Il5SCqyrvK4naIheuaVjIz
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ªğŸ‡¸ES_199 |19.67Mb
  server: 194.87.45.189
  type: ss
  country: ğŸ‡ªğŸ‡¸ES
  port: 443
  password: 3sWY7JfNX2oDGQPmTx1DFP
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ªğŸ‡¸ES_198 |14.17Mb
  server: 194.87.45.189
  type: ss
  country: ğŸ‡ªğŸ‡¸ES
  port: 443
  password: rlZrTPevXyv8GDenQNlkyz
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ªğŸ‡¸ES_200 |43.05Mb
  server: 194.87.45.189
  type: ss
  country: ğŸ‡ªğŸ‡¸ES
  port: 443
  password: 9GyGpqucu0IozRSh15x0eS
  cipher: chacha20-ietf-poly1305
- name: ' |20.93Mb'
  server: 185.47.254.87
  type: ss
  country: ğŸ‡¬ğŸ‡¹GT
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_240 |10.41Mb
  server: 35.176.123.151
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ' |12.50Mb'
  server: 37.143.129.98
  type: ss
  country: ğŸ‡«ğŸ‡®FI
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ªğŸ‡¸ES_203 |50.53Mb
  server: 194.87.45.189
  type: ss
  country: ğŸ‡ªğŸ‡¸ES
  port: 443
  password: rN359Xk9FoKLVk9OvC5af7
  cipher: chacha20-ietf-poly1305
- name: ' |23.99Mb'
  server: 196.196.192.58
  type: ss
  country: ğŸ‡®ğŸ‡ªIE
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ªğŸ‡¸ES_213 |15.65Mb
  server: 194.87.45.189
  type: ss
  country: ğŸ‡ªğŸ‡¸ES
  port: 443
  password: tmFV0a2acZt6Jb6U0KDdBf
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸ‡®ğŸ‡·IR-ğŸ‡³ğŸ‡±NL_275 |16.32Mb
  server: 151.242.251.133
  type: ss
  country: ğŸ‡®ğŸ‡·IR
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: Pool_ğŸ‡­ğŸ‡°HK_243 |690.00Mb
  server: 150.107.46.21
  type: ssr
  country: ğŸ‡­ğŸ‡°HK
  port: 8083
  password: iFqnzSscN
  cipher: aes-256-cfb
  protocol: origin
  obfs: tls1.2_ticket_auth
- name: ğŸ‡¯ğŸ‡µJP_281 |23.08Mb
  server: 153.121.43.183
  type: ss
  country: ğŸ‡¯ğŸ‡µJP
  port: 10087
  password: '10086'
  cipher: aes-128-gcm
- name: ğŸ‡¯ğŸ‡µJP_284 |41.72Mb
  server: 140.83.80.36
  type: vmess
  country: ğŸ‡¯ğŸ‡µJP
  port: 22545
  uuid: 5b907403-239e-4660-8ab6-b6f3d811d1da
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
  ws-opts:
    path: /
- name: ' |22.20Mb'
  server: 194.68.27.76
  type: ss
  country: ğŸ‡¯ğŸ‡µJP
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ' |17.78Mb'
  server: 103.97.203.227
  type: ss
  country: ğŸ‡®ğŸ‡³IN
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¯ğŸ‡µJP_285 |41.97Mb
  server: 45.32.45.45
  type: vmess
  country: ğŸ‡¯ğŸ‡µJP
  port: 14760
  uuid: dbf7a6e4-d518-4f9b-a55e-27ef892ffac1
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡³ğŸ‡±NL_295 |16.64Mb
  server: 193.29.139.188
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 8080
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡³ğŸ‡±NL_297 |13.19Mb
  server: 193.29.139.189
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 8080
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_357 |67.91Mb
  server: 107.151.182.197
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 8080
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: ğŸ‡ºğŸ‡¸US_365 |17.05Mb
  server: 3.138.124.46
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ' |25.59Mb'
  server: 171.22.254.129
  type: ss
  country: ğŸ‡²ğŸ‡¹MT
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ' |21.35Mb'
  server: 185.113.143.186
  type: ss
  country: ğŸ‡µğŸ‡¹PT
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_385 |354.02Mb
  server: 193.124.24.247
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 6506
  uuid: c53d41d1-7d56-43ce-9994-408780c6476a
  alterId: 0
  cipher: auto
  network: tcp
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡ºğŸ‡¸US_383 |54.76Mb
  server: 154.29.158.139
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 12299
  uuid: cccfe679-fbd0-4402-caf2-67e919db436f
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡ºğŸ‡¸US_390 |26.12Mb
  server: 38.34.24.196
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 20522
  uuid: f65ae5d8-f779-4ab2-8ba3-e4d46d34ef9d
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
  ws-opts:
    path: /telegram_@sswia
- name: ğŸ‡·ğŸ‡ºRU_334 |36.89Mb
  server: 147.45.235.63
  type: ss
  country: ğŸ‡·ğŸ‡ºRU
  port: 49115
  password: yYLiE0LOsr0CwIjbiCSLy2
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¸ğŸ‡¬SG_348 |12.21Mb
  server: 66.42.63.36
  type: vmess
  country: ğŸ‡¸ğŸ‡¬SG
  port: 27555
  uuid: 852b7a0d-7817-4473-9473-546080ce951e
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ' |27.47Mb'
  server: 89.46.238.35
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ªğŸ‡¸ES_201 |23.17Mb
  server: 194.87.45.189
  type: ss
  country: ğŸ‡ªğŸ‡¸ES
  port: 443
  password: AnxMfj2oL2RaZTQVfVd5EY
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡®ğŸ‡¶IQ_267 |135.88Mb
  server: 81.90.31.219
  type: ss
  country: ğŸ‡®ğŸ‡¶IQ
  port: 443
  password: FLrqhjDbj4whGWWqfLZ2yZ
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_378 |914.77Mb
  server: 193.124.24.247
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 6508
  uuid: b68fead5-5b0b-43a1-c34a-804467f0f368
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - ' |40.73Mb'
  - ' |46.38Mb'
  - ' |24.45Mb'
  - ' |12.31Mb'
  - ' |12.58Mb'
  - ' |23.86Mb'
  - ğŸ‡©ğŸ‡ªDE_160 |21.99Mb
  - ğŸ‡©ğŸ‡ªDE_168 |10.72Mb
  - ğŸ‡©ğŸ‡ªDE_162 |28.09Mb
  - ' |26.23Mb'
  - ' |17.22Mb'
  - ğŸ‡©ğŸ‡ªDE_169 |12.38Mb
  - ğŸ‡©ğŸ‡ªDE_174 |19.32Mb
  - ğŸ‡©ğŸ‡ªDE_178 |13.16Mb
  - ğŸ‡©ğŸ‡ªDE_181 |12.01Mb
  - ğŸ‡©ğŸ‡ªDE_182 |46.00Mb
  - ğŸ‡©ğŸ‡ªDE_183 |47.10Mb
  - ğŸ‡ªğŸ‡¸ES_190 |31.72Mb
  - ğŸ‡ªğŸ‡¸ES_191 |29.76Mb
  - ğŸ‡ªğŸ‡¸ES_193 |29.35Mb
  - ğŸ‡ªğŸ‡¸ES_194 |11.43Mb
  - ğŸ‡ªğŸ‡¸ES_195 |22.27Mb
  - ğŸ‡ªğŸ‡¸ES_199 |19.67Mb
  - ğŸ‡ªğŸ‡¸ES_198 |14.17Mb
  - ğŸ‡ªğŸ‡¸ES_200 |43.05Mb
  - ' |20.93Mb'
  - ğŸ‡¬ğŸ‡§GB_240 |10.41Mb
  - ' |12.50Mb'
  - ğŸ‡ªğŸ‡¸ES_203 |50.53Mb
  - ' |23.99Mb'
  - ğŸ‡ªğŸ‡¸ES_213 |15.65Mb
  - Relay_ğŸ‡®ğŸ‡·IR-ğŸ‡³ğŸ‡±NL_275 |16.32Mb
  - Pool_ğŸ‡­ğŸ‡°HK_243 |690.00Mb
  - ğŸ‡¯ğŸ‡µJP_281 |23.08Mb
  - ğŸ‡¯ğŸ‡µJP_284 |41.72Mb
  - ' |22.20Mb'
  - ' |17.78Mb'
  - ğŸ‡¯ğŸ‡µJP_285 |41.97Mb
  - ğŸ‡³ğŸ‡±NL_295 |16.64Mb
  - ğŸ‡³ğŸ‡±NL_297 |13.19Mb
  - ğŸ‡ºğŸ‡¸US_357 |67.91Mb
  - ğŸ‡ºğŸ‡¸US_365 |17.05Mb
  - ' |25.59Mb'
  - ' |21.35Mb'
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_385 |354.02Mb
  - ğŸ‡ºğŸ‡¸US_383 |54.76Mb
  - ğŸ‡ºğŸ‡¸US_390 |26.12Mb
  - ğŸ‡·ğŸ‡ºRU_334 |36.89Mb
  - ğŸ‡¸ğŸ‡¬SG_348 |12.21Mb
  - ' |27.47Mb'
  - ğŸ‡ªğŸ‡¸ES_201 |23.17Mb
  - ğŸ‡®ğŸ‡¶IQ_267 |135.88Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_378 |914.77Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - ' |40.73Mb'
  - ' |46.38Mb'
  - ' |24.45Mb'
  - ' |12.31Mb'
  - ' |12.58Mb'
  - ' |23.86Mb'
  - ğŸ‡©ğŸ‡ªDE_160 |21.99Mb
  - ğŸ‡©ğŸ‡ªDE_168 |10.72Mb
  - ğŸ‡©ğŸ‡ªDE_162 |28.09Mb
  - ' |26.23Mb'
  - ' |17.22Mb'
  - ğŸ‡©ğŸ‡ªDE_169 |12.38Mb
  - ğŸ‡©ğŸ‡ªDE_174 |19.32Mb
  - ğŸ‡©ğŸ‡ªDE_178 |13.16Mb
  - ğŸ‡©ğŸ‡ªDE_181 |12.01Mb
  - ğŸ‡©ğŸ‡ªDE_182 |46.00Mb
  - ğŸ‡©ğŸ‡ªDE_183 |47.10Mb
  - ğŸ‡ªğŸ‡¸ES_190 |31.72Mb
  - ğŸ‡ªğŸ‡¸ES_191 |29.76Mb
  - ğŸ‡ªğŸ‡¸ES_193 |29.35Mb
  - ğŸ‡ªğŸ‡¸ES_194 |11.43Mb
  - ğŸ‡ªğŸ‡¸ES_195 |22.27Mb
  - ğŸ‡ªğŸ‡¸ES_199 |19.67Mb
  - ğŸ‡ªğŸ‡¸ES_198 |14.17Mb
  - ğŸ‡ªğŸ‡¸ES_200 |43.05Mb
  - ' |20.93Mb'
  - ğŸ‡¬ğŸ‡§GB_240 |10.41Mb
  - ' |12.50Mb'
  - ğŸ‡ªğŸ‡¸ES_203 |50.53Mb
  - ' |23.99Mb'
  - ğŸ‡ªğŸ‡¸ES_213 |15.65Mb
  - Relay_ğŸ‡®ğŸ‡·IR-ğŸ‡³ğŸ‡±NL_275 |16.32Mb
  - Pool_ğŸ‡­ğŸ‡°HK_243 |690.00Mb
  - ğŸ‡¯ğŸ‡µJP_281 |23.08Mb
  - ğŸ‡¯ğŸ‡µJP_284 |41.72Mb
  - ' |22.20Mb'
  - ' |17.78Mb'
  - ğŸ‡¯ğŸ‡µJP_285 |41.97Mb
  - ğŸ‡³ğŸ‡±NL_295 |16.64Mb
  - ğŸ‡³ğŸ‡±NL_297 |13.19Mb
  - ğŸ‡ºğŸ‡¸US_357 |67.91Mb
  - ğŸ‡ºğŸ‡¸US_365 |17.05Mb
  - ' |25.59Mb'
  - ' |21.35Mb'
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_385 |354.02Mb
  - ğŸ‡ºğŸ‡¸US_383 |54.76Mb
  - ğŸ‡ºğŸ‡¸US_390 |26.12Mb
  - ğŸ‡·ğŸ‡ºRU_334 |36.89Mb
  - ğŸ‡¸ğŸ‡¬SG_348 |12.21Mb
  - ' |27.47Mb'
  - ğŸ‡ªğŸ‡¸ES_201 |23.17Mb
  - ğŸ‡®ğŸ‡¶IQ_267 |135.88Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_378 |914.77Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
