port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: netflix_NL |241.65Mb
  server: 45.87.175.166
  type: ss
  port: 443
  udp: true
  password: 1RWwXhwfAB5gAEozU4G2Pg
  cipher: chacha20-ietf-poly1305
- name: _258 |142.70Mb
  server: 82.38.31.187
  type: ss
  port: 8080
  udp: true
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: _262 |213.06Mb
  server: 5.181.21.246
  type: ss
  port: 443
  udp: true
  password: gKYygTcRYhc3skc2x6tZ073lYz0DnieX
  cipher: chacha20-ietf-poly1305
- name: Pool__264 |60.36Mb
  server: 86.106.84.195
  type: ss
  port: 13262
  udp: true
  password: kfuzkwdg4oynv495aywc
  cipher: aes-128-gcm
- name: _256 |64.35Mb
  server: 13.61.180.46
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: netflix_SE |184.47Mb
  server: 51.20.125.235
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: _257 |64.51Mb
  server: 13.61.13.231
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: _268 |56.31Mb
  server: 103.149.183.191
  type: ss
  port: 8388
  udp: true
  password: asd123456
  cipher: chacha20-ietf
- name: Relay_-ğŸ‡ºğŸ‡¸US_280 |40.54Mb
  server: 38.14.99.179
  type: vmess
  port: 59807
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _281 |41.66Mb
  server: 163.192.49.195
  type: vmess
  port: 443
  uuid: bcb7c581-3c95-4569-a4e7-918141e91ea3
  alterId: 0
  cipher: auto
  network: http
  http-opts:
    path:
    - /
    headers:
      Host:
      - a.189.cn
  h2-opts: {}
- name: disney_US |38.18Mb
  server: 165.140.216.141
  type: vmess
  port: 443
  uuid: e7d72a8d-26f2-4b54-b366-0c43e0bcba7d
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: Relay_-ğŸ‡ºğŸ‡¸US_287 |40.09Mb
  server: 38.14.99.163
  type: vmess
  port: 59807
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _276 |17.52Mb
  server: 216.238.86.158
  type: vmess
  port: 34460
  udp: true
  uuid: 90be214d-048c-4ea2-a602-b8e4d4e51e36
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: disney_US |33.50Mb
  server: 192.204.47.79
  type: vmess
  port: 42277
  udp: true
  uuid: aee61b21-e85a-484b-f203-b245f1451cff
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _283 |15.40Mb
  server: 51.79.102.253
  type: vmess
  port: 80
  uuid: 58fe1542-5290-40ad-815a-77707a81afe5
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /IOebhLMhl1CTbFHbL95myfRX2
    headers:
      Host: wrmelmwxlf.gktevlrqznwqqozy.fabpfs66gizmnojhcvqxwl.kytrcfzqla87gvgvs6c7kjnrubuh.cc
- name: _279 |28.43Mb
  server: 15.235.41.200
  type: vmess
  port: 80
  uuid: 58fe1542-5290-40ad-815a-77707a81afe5
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /IOebhLMhl1CTbFHbL95myfRX2
- name: Relay_-ğŸ‡¨ğŸ‡­CH_278 |70.50Mb
  server: lt.fxlcn.com
  type: vmess
  port: 45288
  uuid: 469e0b31-30c3-4dab-800d-711232634ce1
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _298 |25.89Mb
  server: 8.210.184.105
  type: vmess
  port: 40374
  udp: true
  uuid: 36b76373-7a4f-4669-9113-7d247bcf2704
  alterId: 0
  cipher: auto
  network: http
  http-opts:
    method: GET
    path:
    - /
  h2-opts: {}
- name: _302 |22.72Mb
  server: 8.218.105.196
  type: vmess
  port: 52752
  uuid: 925bdbf5-72be-4437-bebf-441c61089f6b
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _305 |11.21Mb
  server: 130.162.152.253
  type: vmess
  port: 56867
  uuid: 5206bb9f-2cbc-44ac-de2a-471439a23707
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _292 |41.39Mb
  server: 89.31.120.192
  type: vmess
  port: 443
  uuid: 44537595-9ccc-4b83-8936-5f9ad3229019
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _307 |10.47Mb
  server: 140.238.2.250
  type: vmess
  port: 443
  uuid: 41a7089a-040b-4538-8b8d-010902405bde
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _308 |16.65Mb
  server: 154.201.76.172
  type: vmess
  port: 20990
  uuid: ba50e1fe-055f-4587-fd0d-36c8d6615192
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: disney_TW |10.14Mb
  server: 103.127.218.91
  type: vmess
  port: 54693
  uuid: 1cef03ad-6343-408c-8121-cbd1fda2ee9d
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /1cef03ad
- name: _318 |12.15Mb
  server: 160.16.107.37
  type: trojan
  port: 3093
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: Pool__319 |180.61Mb
  server: 70.34.218.149
  type: trojan
  port: 11930
  password: BaeSzHdfJIR13l67
  sni: softpillow.silentrocket.click
- name: Relay_-ğŸ‡¸ğŸ‡¬SG_323 |10.25Mb
  server: 160.16.150.76
  type: trojan
  port: 3145
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: _312 |11.34Mb
  server: 146.56.112.110
  type: vmess
  port: 8888
  uuid: e7c302f3-90d6-42dd-9d7d-94a3683a3707
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _331 |35.73Mb
  server: 160.16.63.16
  type: trojan
  port: 4054
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: disney_GB |268.31Mb
  server: 172.67.134.185
  type: trojan
  port: 443
  udp: true
  password: POORIARED
  sni: reDfRee8.REDFree8.ir
  ws-opts:
    path: /eyJqdW5rIjoiVUl6eXhLZkkwUTJ3ZzkiLCJwcm90b2NvbCI6InRyIiwibW9kZSI6InByb3h5aXAiLCJwYW5lbElQcyI6W119?ed=2560
    headers:
      Host: reDfRee8.REDFree8.ir
  network: ws
- name: _336 |24.51Mb
  server: 38.96.254.102
  type: trojan
  port: 18509
  password: .ie4rghJuMkcf0oF
  sni: shoppingmall.electricbanana.click
- name: _332 |10.96Mb
  server: 160.16.116.227
  type: trojan
  port: 2760
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
  skip-cert-verify: true
- name: _333 |30.67Mb
  server: 153.121.39.240
  type: trojan
  port: 4054
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: _335 |11.80Mb
  server: 160.16.131.243
  type: trojan
  port: 2760
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
  skip-cert-verify: true
- name: Relay_-ğŸ‡ºğŸ‡¸US_295 |13.33Mb
  server: yg1.ygkkk.dpdns.org
  type: vmess
  port: 443
  udp: true
  uuid: 7a88d322-eb4a-4a59-8c62-8c60d76abf4b
  alterId: 0
  cipher: auto
  network: ws
  servername: jporacleyg.336697.xyz
  http-opts: {}
  h2-opts: {}
  tls: true
  ws-opts:
    path: /7a88d322-eb4a-4a59-8c62-8c60d76abf4b-vm?ed=2048
    headers:
      Host: jporacleyg.336697.xyz
- name: Relay_-ğŸ‡¯ğŸ‡µJP_299 |11.64Mb
  server: yg1.ygkkk.dpdns.org
  type: vmess
  port: 443
  udp: true
  uuid: 130ec091-df05-4af9-9695-dc982e98a8ec
  alterId: 0
  cipher: auto
  network: ws
  servername: jporacleyg2.336697.xyz
  http-opts: {}
  h2-opts: {}
  tls: true
  ws-opts:
    path: /130ec091-df05-4af9-9695-dc982e98a8ec-vm
    headers:
      Host: jporacleyg2.336697.xyz
- name: disney_FR |215.24Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 27092
  uuid: a0596ba6-72a3-4366-8992-77088da65bd8
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_FR |212.85Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 40433
  uuid: d8fd8955-78db-49ba-d86f-3e4729f6ac4d
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_-ğŸ‡¯ğŸ‡µJP_294 |21.22Mb
  server: yg6.ygkkk.dpdns.org
  type: vmess
  port: 80
  udp: true
  uuid: 130ec091-df05-4af9-9695-dc982e98a8ec
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /130ec091-df05-4af9-9695-dc982e98a8ec-vm?ed=2048
    headers:
      Host: jporacleyg2.336697.xyz
- name: ğŸ‡¬ğŸ‡§GB_367 |208.29Mb
  server: 82.38.31.194
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡²ğŸ‡½MX_375 |147.15Mb
  server: 216.238.87.47
  type: vmess
  country: ğŸ‡²ğŸ‡½MX
  port: 27502
  uuid: b8155ce4-7e08-4c40-800f-8671312b7124
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: netflix_NL |236.50Mb
  server: 82.38.31.217
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_369 |215.29Mb
  server: 82.38.31.191
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_378 |70.96Mb
  server: 47.253.197.26
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 12056
  uuid: dd7be7f1-38ff-45e6-f1e5-b20c2190f527
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_HK |22.87Mb
  server: 45.207.157.29
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 13852
  uuid: 845764df-ecb3-4b13-bed2-bf1551b68e9a
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Pool_ğŸ‡·ğŸ‡´RO_376 |26.37Mb
  server: 86.106.84.198
  type: ss
  country: ğŸ‡·ğŸ‡´RO
  port: 13265
  password: phizo046s4oqsm33sfvm
  cipher: aes-128-gcm
- name: ğŸ‡ºğŸ‡¸US_377 |133.85Mb
  server: 45.12.136.170
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: l668XHPejoSNNuD66BYzyehaCpZexiF7
  cipher: chacha20-ietf-poly1305
- name: disney_JP |18.18Mb
  server: silwu1.donghui.tech
  type: ss
  country: ğŸ‡¨ğŸ‡³CN
  port: 58903
  password: 71bc5b04-b0b9-42b3-b65c-31d787a960ed
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸ‡©ğŸ‡ªDE-ğŸ‡©ğŸ‡ªDE_360 |886.94Mb
  server: cpanel.navar1.ir
  type: vmess
  country: ğŸ‡©ğŸ‡ªDE
  port: 100
  uuid: 95c6f6f0-84f7-4443-8a50-a59f8e66f5ee
  alterId: 0
  cipher: auto
  network: tcp
  servername: cpanel.navar1.ir
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_HK |14.24Mb
  server: silwu1.donghui.tech
  type: ss
  country: ğŸ‡¨ğŸ‡³CN
  port: 58906
  password: 71bc5b04-b0b9-42b3-b65c-31d787a960ed
  cipher: chacha20-ietf-poly1305
- name: disney_HK |10.53Mb
  server: silwu1.donghui.tech
  type: ss
  country: ğŸ‡¨ğŸ‡³CN
  port: 50951
  password: 71bc5b04-b0b9-42b3-b65c-31d787a960ed
  cipher: chacha20-ietf-poly1305
- name: disney_US |34.25Mb
  server: cf.fovi.tk
  type: vmess
  country: ğŸZZ
  port: 443
  uuid: bf67437e-6c90-45ca-abc2-c7240a5ce2aa
  alterId: 0
  cipher: auto
  network: ws
  servername: foxpol.fovi.tk
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /eisasqa
    headers:
      HOST: foxpol.fovi.tk
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - netflix_NL |241.65Mb
  - _258 |142.70Mb
  - _262 |213.06Mb
  - Pool__264 |60.36Mb
  - _256 |64.35Mb
  - netflix_SE |184.47Mb
  - _257 |64.51Mb
  - _268 |56.31Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_280 |40.54Mb
  - _281 |41.66Mb
  - disney_US |38.18Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_287 |40.09Mb
  - _276 |17.52Mb
  - disney_US |33.50Mb
  - _283 |15.40Mb
  - _279 |28.43Mb
  - Relay_-ğŸ‡¨ğŸ‡­CH_278 |70.50Mb
  - _298 |25.89Mb
  - _302 |22.72Mb
  - _305 |11.21Mb
  - _292 |41.39Mb
  - _307 |10.47Mb
  - _308 |16.65Mb
  - disney_TW |10.14Mb
  - _318 |12.15Mb
  - Pool__319 |180.61Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_323 |10.25Mb
  - _312 |11.34Mb
  - _331 |35.73Mb
  - disney_GB |268.31Mb
  - _336 |24.51Mb
  - _332 |10.96Mb
  - _333 |30.67Mb
  - _335 |11.80Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_295 |13.33Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_299 |11.64Mb
  - disney_FR |215.24Mb
  - disney_FR |212.85Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_294 |21.22Mb
  - ğŸ‡¬ğŸ‡§GB_367 |208.29Mb
  - ğŸ‡²ğŸ‡½MX_375 |147.15Mb
  - netflix_NL |236.50Mb
  - ğŸ‡¬ğŸ‡§GB_369 |215.29Mb
  - ğŸ‡ºğŸ‡¸US_378 |70.96Mb
  - disney_HK |22.87Mb
  - Pool_ğŸ‡·ğŸ‡´RO_376 |26.37Mb
  - ğŸ‡ºğŸ‡¸US_377 |133.85Mb
  - disney_JP |18.18Mb
  - Relay_ğŸ‡©ğŸ‡ªDE-ğŸ‡©ğŸ‡ªDE_360 |886.94Mb
  - disney_HK |14.24Mb
  - disney_HK |10.53Mb
  - disney_US |34.25Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - netflix_NL |241.65Mb
  - _258 |142.70Mb
  - _262 |213.06Mb
  - Pool__264 |60.36Mb
  - _256 |64.35Mb
  - netflix_SE |184.47Mb
  - _257 |64.51Mb
  - _268 |56.31Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_280 |40.54Mb
  - _281 |41.66Mb
  - disney_US |38.18Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_287 |40.09Mb
  - _276 |17.52Mb
  - disney_US |33.50Mb
  - _283 |15.40Mb
  - _279 |28.43Mb
  - Relay_-ğŸ‡¨ğŸ‡­CH_278 |70.50Mb
  - _298 |25.89Mb
  - _302 |22.72Mb
  - _305 |11.21Mb
  - _292 |41.39Mb
  - _307 |10.47Mb
  - _308 |16.65Mb
  - disney_TW |10.14Mb
  - _318 |12.15Mb
  - Pool__319 |180.61Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_323 |10.25Mb
  - _312 |11.34Mb
  - _331 |35.73Mb
  - disney_GB |268.31Mb
  - _336 |24.51Mb
  - _332 |10.96Mb
  - _333 |30.67Mb
  - _335 |11.80Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_295 |13.33Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_299 |11.64Mb
  - disney_FR |215.24Mb
  - disney_FR |212.85Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_294 |21.22Mb
  - ğŸ‡¬ğŸ‡§GB_367 |208.29Mb
  - ğŸ‡²ğŸ‡½MX_375 |147.15Mb
  - netflix_NL |236.50Mb
  - ğŸ‡¬ğŸ‡§GB_369 |215.29Mb
  - ğŸ‡ºğŸ‡¸US_378 |70.96Mb
  - disney_HK |22.87Mb
  - Pool_ğŸ‡·ğŸ‡´RO_376 |26.37Mb
  - ğŸ‡ºğŸ‡¸US_377 |133.85Mb
  - disney_JP |18.18Mb
  - Relay_ğŸ‡©ğŸ‡ªDE-ğŸ‡©ğŸ‡ªDE_360 |886.94Mb
  - disney_HK |14.24Mb
  - disney_HK |10.53Mb
  - disney_US |34.25Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
