port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: _191 |65.89Mb
  server: 54.227.38.247
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: netflix_US |67.66Mb
  server: 54.91.94.165
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: _189 |67.01Mb
  server: 54.159.62.233
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: netflix_US |65.26Mb
  server: 54.144.64.227
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: _183 |318.57Mb
  server: 3.253.99.197
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: _196 |60.50Mb
  server: 23.22.182.151
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: _194 |66.42Mb
  server: 184.72.124.41
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: _198 |64.57Mb
  server: 98.81.59.20
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: netflix_US |66.70Mb
  server: 50.19.46.248
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: netflix_US |41.19Mb
  server: 13.218.107.141
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: _210 |66.86Mb
  server: 98.89.32.62
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: netflix_US |55.16Mb
  server: 13.222.155.147
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: netflix_US |40.99Mb
  server: 163.192.49.195
  type: vmess
  port: 443
  uuid: bcb7c581-3c95-4569-a4e7-918141e91ea3
  alterId: 0
  cipher: auto
  network: http
  http-opts:
    path:
    - /
    headers:
      Host:
      - a.189.cn
  h2-opts: {}
- name: disney_US |37.05Mb
  server: 165.140.216.141
  type: vmess
  port: 443
  uuid: e7d72a8d-26f2-4b54-b366-0c43e0bcba7d
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _212 |55.55Mb
  server: 3.89.113.22
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: _202 |342.54Mb
  server: 34.251.86.159
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: _206 |347.13Mb
  server: 3.250.105.240
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: _213 |67.15Mb
  server: 3.93.196.82
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: _199 |178.51Mb
  server: 13.61.13.231
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: _236 |31.50Mb
  server: 216.238.86.158
  type: vmess
  port: 34460
  udp: true
  uuid: 90be214d-048c-4ea2-a602-b8e4d4e51e36
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _217 |296.74Mb
  server: 54.246.35.116
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: _226 |22.84Mb
  server: 15.235.41.200
  type: vmess
  port: 80
  uuid: 58fe1542-5290-40ad-815a-77707a81afe5
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /IOebhLMhl1CTbFHbL95myfRX2
- name: _214 |141.27Mb
  server: 51.20.125.235
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: _238 |17.66Mb
  server: 51.79.102.253
  type: vmess
  port: 80
  uuid: 58fe1542-5290-40ad-815a-77707a81afe5
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /IOebhLMhl1CTbFHbL95myfRX2
    headers:
      Host: wrmelmwxlf.gktevlrqznwqqozy.fabpfs66gizmnojhcvqxwl.kytrcfzqla87gvgvs6c7kjnrubuh.cc
- name: _232 |24.98Mb
  server: 8.218.105.196
  type: vmess
  port: 52752
  uuid: 925bdbf5-72be-4437-bebf-441c61089f6b
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: Relay_-ğŸ‡ºğŸ‡¸US_255 |32.23Mb
  server: 69.84.182.108
  type: trojan
  port: 8443
  udp: true
  password: b1fec179-3d5a-4ec5-bf3c-e10668543b4b
  sni: cdn-node-oss-61.anycdn.de
  ws-opts:
    path: /profile/us1
    headers:
      Host: cdn-node-oss-61.anycdn.de
  network: ws
- name: _237 |260.45Mb
  server: 85.195.101.122
  type: vmess
  port: 40878
  uuid: f3d4167e-b15e-4e46-82e9-9286ef93fda7
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _234 |154.30Mb
  server: 38.180.16.86
  type: vmess
  port: 38039
  uuid: 244a3464-1269-43b3-b491-4dc2713eb3f6
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _241 |10.70Mb
  server: 140.238.2.250
  type: vmess
  port: 443
  uuid: 41a7089a-040b-4538-8b8d-010902405bde
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _239 |10.96Mb
  server: 130.162.152.253
  type: vmess
  port: 56867
  uuid: 5206bb9f-2cbc-44ac-de2a-471439a23707
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _253 |17.22Mb
  server: 153.121.39.240
  type: trojan
  port: 4054
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: _229 |40.99Mb
  server: 89.31.120.192
  type: vmess
  port: 443
  uuid: 44537595-9ccc-4b83-8936-5f9ad3229019
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _245 |13.22Mb
  server: 54.206.192.9
  type: vmess
  port: 16407
  uuid: 08f45028-1db6-4e93-bf51-d344b6c71e19
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _257 |12.79Mb
  server: 160.16.124.55
  type: trojan
  port: 2890
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: _258 |51.25Mb
  server: 160.16.196.59
  type: trojan
  port: 2890
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡ºğŸ‡¸US_272 |28.30Mb
  server: 69.84.182.18
  type: trojan
  port: 8443
  udp: true
  password: b870a9da-02b1-4110-88f0-ee40ce5372e8
  sni: cdn-node-oss-62.anycdn.de
  ws-opts:
    path: /profile/us2
    headers:
      Host: cdn-node-oss-62.anycdn.de
  network: ws
- name: _242 |148.81Mb
  server: 38.180.16.86
  type: vmess
  port: 36236
  uuid: a58bc1a5-8c18-49ff-9453-c331b52f45dc
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: disney_netflix_GB |268.31Mb
  server: 172.67.134.185
  type: trojan
  port: 443
  udp: true
  password: POORIARED
  sni: reDfRee8.REDFree8.ir
  ws-opts:
    path: /eyJqdW5rIjoiVUl6eXhLZkkwUTJ3ZzkiLCJwcm90b2NvbCI6InRyIiwibW9kZSI6InByb3h5aXAiLCJwYW5lbElQcyI6W119?ed=2560
    headers:
      Host: reDfRee8.REDFree8.ir
  network: ws
- name: disney_HK |17.48Mb
  server: 154.21.201.83
  type: vmess
  port: 443
  uuid: 4bf075f5-4d5e-4d39-f5ab-b32a86250f0e
  alterId: 0
  cipher: auto
  network: ws
  servername: hk.nbee.pp.ua
  http-opts: {}
  h2-opts: {}
  tls: true
  ws-opts:
    path: /aa
    headers:
      Host: hk.nbee.pp.ua
- name: _260 |20.04Mb
  server: 160.16.151.196
  type: trojan
  port: 4054
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: _262 |14.63Mb
  server: 160.16.63.16
  type: trojan
  port: 4054
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¸ğŸ‡¬SG_263 |10.20Mb
  server: 160.16.150.76
  type: trojan
  port: 3145
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¯ğŸ‡µJP_265 |16.78Mb
  server: 153.121.73.102
  type: trojan
  port: 1331
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: _270 |23.25Mb
  server: 202.181.103.235
  type: trojan
  port: 2890
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: _271 |56.21Mb
  server: 153.121.51.29
  type: trojan
  port: 2890
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: _275 |12.13Mb
  server: 153.121.53.187
  type: trojan
  port: 3093
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: Pool__267 |67.04Mb
  server: 70.34.218.149
  type: trojan
  port: 11930
  password: BaeSzHdfJIR13l67
  sni: softpillow.silentrocket.click
- name: disney_FR |26.21Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 40433
  uuid: d8fd8955-78db-49ba-d86f-3e4729f6ac4d
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_FR |48.80Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 27092
  uuid: a0596ba6-72a3-4366-8992-77088da65bd8
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡ºğŸ‡¸US_315 |65.54Mb
  server: 18.207.122.59
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: netflix_NL |175.57Mb
  server: 82.38.31.194
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_302 |175.04Mb
  server: 82.38.31.191
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_303 |180.48Mb
  server: 82.38.31.217
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: disney_HK |15.04Mb
  server: 45.207.157.29
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 13852
  uuid: 845764df-ecb3-4b13-bed2-bf1551b68e9a
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡®ğŸ‡ªIE_307 |300.30Mb
  server: 52.50.200.2
  type: ss
  country: ğŸ‡®ğŸ‡ªIE
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: Relay_ğŸ‡©ğŸ‡ªDE-ğŸ‡©ğŸ‡ªDE_293 |176.79Mb
  server: cpanel.navar1.ir
  type: vmess
  country: ğŸ‡©ğŸ‡ªDE
  port: 100
  uuid: 95c6f6f0-84f7-4443-8a50-a59f8e66f5ee
  alterId: 0
  cipher: auto
  network: tcp
  servername: cpanel.navar1.ir
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - _191 |65.89Mb
  - netflix_US |67.66Mb
  - _189 |67.01Mb
  - netflix_US |65.26Mb
  - _183 |318.57Mb
  - _196 |60.50Mb
  - _194 |66.42Mb
  - _198 |64.57Mb
  - netflix_US |66.70Mb
  - netflix_US |41.19Mb
  - _210 |66.86Mb
  - netflix_US |55.16Mb
  - netflix_US |40.99Mb
  - disney_US |37.05Mb
  - _212 |55.55Mb
  - _202 |342.54Mb
  - _206 |347.13Mb
  - _213 |67.15Mb
  - _199 |178.51Mb
  - _236 |31.50Mb
  - _217 |296.74Mb
  - _226 |22.84Mb
  - _214 |141.27Mb
  - _238 |17.66Mb
  - _232 |24.98Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_255 |32.23Mb
  - _237 |260.45Mb
  - _234 |154.30Mb
  - _241 |10.70Mb
  - _239 |10.96Mb
  - _253 |17.22Mb
  - _229 |40.99Mb
  - _245 |13.22Mb
  - _257 |12.79Mb
  - _258 |51.25Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_272 |28.30Mb
  - _242 |148.81Mb
  - disney_netflix_GB |268.31Mb
  - disney_HK |17.48Mb
  - _260 |20.04Mb
  - _262 |14.63Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_263 |10.20Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_265 |16.78Mb
  - _270 |23.25Mb
  - _271 |56.21Mb
  - _275 |12.13Mb
  - Pool__267 |67.04Mb
  - disney_FR |26.21Mb
  - disney_FR |48.80Mb
  - ğŸ‡ºğŸ‡¸US_315 |65.54Mb
  - netflix_NL |175.57Mb
  - ğŸ‡¬ğŸ‡§GB_302 |175.04Mb
  - ğŸ‡¬ğŸ‡§GB_303 |180.48Mb
  - disney_HK |15.04Mb
  - ğŸ‡®ğŸ‡ªIE_307 |300.30Mb
  - Relay_ğŸ‡©ğŸ‡ªDE-ğŸ‡©ğŸ‡ªDE_293 |176.79Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - _191 |65.89Mb
  - netflix_US |67.66Mb
  - _189 |67.01Mb
  - netflix_US |65.26Mb
  - _183 |318.57Mb
  - _196 |60.50Mb
  - _194 |66.42Mb
  - _198 |64.57Mb
  - netflix_US |66.70Mb
  - netflix_US |41.19Mb
  - _210 |66.86Mb
  - netflix_US |55.16Mb
  - netflix_US |40.99Mb
  - disney_US |37.05Mb
  - _212 |55.55Mb
  - _202 |342.54Mb
  - _206 |347.13Mb
  - _213 |67.15Mb
  - _199 |178.51Mb
  - _236 |31.50Mb
  - _217 |296.74Mb
  - _226 |22.84Mb
  - _214 |141.27Mb
  - _238 |17.66Mb
  - _232 |24.98Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_255 |32.23Mb
  - _237 |260.45Mb
  - _234 |154.30Mb
  - _241 |10.70Mb
  - _239 |10.96Mb
  - _253 |17.22Mb
  - _229 |40.99Mb
  - _245 |13.22Mb
  - _257 |12.79Mb
  - _258 |51.25Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_272 |28.30Mb
  - _242 |148.81Mb
  - disney_netflix_GB |268.31Mb
  - disney_HK |17.48Mb
  - _260 |20.04Mb
  - _262 |14.63Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_263 |10.20Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_265 |16.78Mb
  - _270 |23.25Mb
  - _271 |56.21Mb
  - _275 |12.13Mb
  - Pool__267 |67.04Mb
  - disney_FR |26.21Mb
  - disney_FR |48.80Mb
  - ğŸ‡ºğŸ‡¸US_315 |65.54Mb
  - netflix_NL |175.57Mb
  - ğŸ‡¬ğŸ‡§GB_302 |175.04Mb
  - ğŸ‡¬ğŸ‡§GB_303 |180.48Mb
  - disney_HK |15.04Mb
  - ğŸ‡®ğŸ‡ªIE_307 |300.30Mb
  - Relay_ğŸ‡©ğŸ‡ªDE-ğŸ‡©ğŸ‡ªDE_293 |176.79Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
