port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: _257 |32.11Mb
  server: 173.234.29.2
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: Relay_-ğŸ‡¨ğŸ‡¦CA_239 |67.38Mb
  server: 79.127.200.169
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _252 |307.73Mb
  server: 62.100.205.100
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: netflix_NL |396.10Mb
  server: 45.14.245.2
  type: ss
  port: 443
  password: 17ZDORWIliQHuO6WRGHChXYMzdRtAYVP
  cipher: chacha20-ietf-poly1305
- name: _231 |44.50Mb
  server: 185.82.73.212
  type: ss
  port: 8444
  udp: true
  password: _bypfvq6ra7g4n5yCCR9DoVeGya2XUUS
  cipher: chacha20-ietf-poly1305
- name: netflix_BE |14.84Mb
  server: 192.71.249.78
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: Relay_-ğŸ‡ªğŸ‡ªEE_255 |21.69Mb
  server: est01-ss01.tcp-reset-club.net
  type: ss
  port: 8444
  udp: true
  password: AWNeHjukGQWwuFXadw2r6qH7gh4hZ9cj
  cipher: chacha20-ietf-poly1305
- name: _232 |17.72Mb
  server: 38.89.142.56
  type: ss
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: disney_PY |17.30Mb
  server: 38.165.233.93
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: _260 |11.89Mb
  server: 45.87.175.22
  type: ss
  port: 8080
  udp: true
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: _267 |53.35Mb
  server: 172.233.229.91
  type: vmess
  port: 14102
  udp: true
  uuid: 27ba87fc-583f-4763-9060-83cf0b9264db
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: _261 |21.90Mb
  server: 193.29.139.177
  type: ss
  port: 8080
  udp: true
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: _273 |10.41Mb
  server: 160.16.116.227
  type: trojan
  port: 2760
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
  skip-cert-verify: true
- name: _246 |44.52Mb
  server: 156.59.243.6
  type: ss
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: Relay_-ğŸ‡¯ğŸ‡µJP_277 |11.53Mb
  server: 160.16.117.182
  type: trojan
  port: 3093
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: ğŸ‡¨ğŸ‡¦CA_289 |66.94Mb
  server: 193.203.203.66
  type: ss
  country: ğŸ‡¨ğŸ‡¦CA
  port: 443
  password: S6jUK9Fw5fMHgNqlqXObHZWv8Tf4nEkm
  cipher: chacha20-ietf-poly1305
- name: Relay_-ğŸ‡¯ğŸ‡µJP_279 |10.28Mb
  server: 160.16.117.182
  type: trojan
  port: 3169
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: _265 |224.03Mb
  server: 151.242.251.152
  type: ss
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: _280 |10.41Mb
  server: 160.16.131.243
  type: trojan
  port: 2760
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
  skip-cert-verify: true
- name: Relay_-ğŸ‡¯ğŸ‡µJP_282 |11.60Mb
  server: 153.121.45.139
  type: trojan
  port: 3093
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: ğŸ‡¨ğŸ‡¦CA_290 |65.10Mb
  server: 185.213.23.63
  type: ss
  country: ğŸ‡¨ğŸ‡¦CA
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡§ğŸ‡·BR_288 |20.12Mb
  server: 185.192.124.188
  type: ss
  country: ğŸ‡§ğŸ‡·BR
  port: 990
  password: f8f7aCzcPKbsF8p3
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¨ğŸ‡­CH_291 |35.05Mb
  server: 138.124.67.26
  type: ss
  country: ğŸ‡¨ğŸ‡­CH
  port: 25572
  password: nqcIfYHlpMn3jzqkNDjKaG
  cipher: chacha20-ietf-poly1305
- name: netflix_NL |107.83Mb
  server: 82.38.31.208
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: disney_DE |231.84Mb
  server: 89.163.140.136
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ğŸ‡±ğŸ‡¹LT_306 |147.32Mb
  server: 45.87.175.185
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_307 |131.27Mb
  server: 45.87.175.180
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: QCXDxuDlTTMD7jtgHUjIoj
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_308 |227.21Mb
  server: 45.87.175.183
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡²ğŸ‡½MX_314 |132.29Mb
  server: 216.238.87.47
  type: vmess
  country: ğŸ‡²ğŸ‡½MX
  port: 27502
  uuid: b8155ce4-7e08-4c40-800f-8671312b7124
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡±ğŸ‡¹LT_309 |225.16Mb
  server: 45.87.175.185
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡³ğŸ‡±NL_315 |195.88Mb
  server: 193.29.139.188
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 8080
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: disney_DE |260.26Mb
  server: h110vpnde.outlinekeys.net
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 7048
  password: Y52dYtnOWIKtbVTMcmhACO
  cipher: chacha20-ietf-poly1305
- name: netflix_NL |11.01Mb
  server: 193.29.139.141
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 8080
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_325 |158.71Mb
  server: 38.14.99.163
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 59807
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: auto
  network: tcp
  servername: 38.14.99.163
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡²ğŸ‡©MD_313 |21.42Mb
  server: 176.123.5.253
  type: ss
  country: ğŸ‡²ğŸ‡©MD
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡³ğŸ‡±NL_317 |90.99Mb
  server: 194.87.216.218
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 52571
  password: b0TKxnHAYeeFYyzTAMXn0F
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡³ğŸ‡±NL_318 |12.84Mb
  server: 178.23.190.238
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 443
  password: uo7EbtqIwgZXXHmMv5LbLcOxptyPlNkh
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸ‡¯ğŸ‡µJP-ğŸ‡¯ğŸ‡µJP_305 |11.47Mb
  server: xray.kk37005.tk
  type: vmess
  country: ğŸ‡¯ğŸ‡µJP
  port: 55919
  uuid: 2e7548bb-7c5b-4d97-d64d-1b2fe4050089
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_326 |15.98Mb
  server: gy3.hdcloud.link
  type: trojan
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  udp: true
  password: 2cce737c-9c6d-4667-bb3d-aea668a0c10b
  sni: gy3.hdcloud.link
  network: grpc
  grpc-opts:
    grpc-service-name: GunService
- name: ğŸ‡µğŸ‡¹PT_320 |71.46Mb
  server: 185.113.143.186
  type: ss
  country: ğŸ‡µğŸ‡¹PT
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: disney_SG |23.47Mb
  server: 103.248.229.90
  type: ss
  country: ğŸ‡¸ğŸ‡¬SG
  port: 24203
  password: 1GJth1Qjic
  cipher: aes-256-gcm
- name: disney_SG |21.72Mb
  server: 103.248.229.90
  type: ss
  country: ğŸ‡¸ğŸ‡¬SG
  port: 35817
  password: 4VqrUWV7hm
  cipher: aes-256-gcm
- name: disney_SG |19.71Mb
  server: 103.248.229.90
  type: ss
  country: ğŸ‡¸ğŸ‡¬SG
  port: 40413
  password: hGpFS8dtyN
  cipher: aes-256-gcm
- name: ğŸ‡±ğŸ‡¹LT_311 |14.07Mb
  server: ltnl16.saint.ydns.eu
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - _257 |32.11Mb
  - Relay_-ğŸ‡¨ğŸ‡¦CA_239 |67.38Mb
  - _252 |307.73Mb
  - netflix_NL |396.10Mb
  - _231 |44.50Mb
  - netflix_BE |14.84Mb
  - Relay_-ğŸ‡ªğŸ‡ªEE_255 |21.69Mb
  - _232 |17.72Mb
  - disney_PY |17.30Mb
  - _260 |11.89Mb
  - _267 |53.35Mb
  - _261 |21.90Mb
  - _273 |10.41Mb
  - _246 |44.52Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_277 |11.53Mb
  - ğŸ‡¨ğŸ‡¦CA_289 |66.94Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_279 |10.28Mb
  - _265 |224.03Mb
  - _280 |10.41Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_282 |11.60Mb
  - ğŸ‡¨ğŸ‡¦CA_290 |65.10Mb
  - ğŸ‡§ğŸ‡·BR_288 |20.12Mb
  - ğŸ‡¨ğŸ‡­CH_291 |35.05Mb
  - netflix_NL |107.83Mb
  - disney_DE |231.84Mb
  - ğŸ‡±ğŸ‡¹LT_306 |147.32Mb
  - ğŸ‡±ğŸ‡¹LT_307 |131.27Mb
  - ğŸ‡±ğŸ‡¹LT_308 |227.21Mb
  - ğŸ‡²ğŸ‡½MX_314 |132.29Mb
  - ğŸ‡±ğŸ‡¹LT_309 |225.16Mb
  - ğŸ‡³ğŸ‡±NL_315 |195.88Mb
  - disney_DE |260.26Mb
  - netflix_NL |11.01Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_325 |158.71Mb
  - ğŸ‡²ğŸ‡©MD_313 |21.42Mb
  - ğŸ‡³ğŸ‡±NL_317 |90.99Mb
  - ğŸ‡³ğŸ‡±NL_318 |12.84Mb
  - Relay_ğŸ‡¯ğŸ‡µJP-ğŸ‡¯ğŸ‡µJP_305 |11.47Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_326 |15.98Mb
  - ğŸ‡µğŸ‡¹PT_320 |71.46Mb
  - disney_SG |23.47Mb
  - disney_SG |21.72Mb
  - disney_SG |19.71Mb
  - ğŸ‡±ğŸ‡¹LT_311 |14.07Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - _257 |32.11Mb
  - Relay_-ğŸ‡¨ğŸ‡¦CA_239 |67.38Mb
  - _252 |307.73Mb
  - netflix_NL |396.10Mb
  - _231 |44.50Mb
  - netflix_BE |14.84Mb
  - Relay_-ğŸ‡ªğŸ‡ªEE_255 |21.69Mb
  - _232 |17.72Mb
  - disney_PY |17.30Mb
  - _260 |11.89Mb
  - _267 |53.35Mb
  - _261 |21.90Mb
  - _273 |10.41Mb
  - _246 |44.52Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_277 |11.53Mb
  - ğŸ‡¨ğŸ‡¦CA_289 |66.94Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_279 |10.28Mb
  - _265 |224.03Mb
  - _280 |10.41Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_282 |11.60Mb
  - ğŸ‡¨ğŸ‡¦CA_290 |65.10Mb
  - ğŸ‡§ğŸ‡·BR_288 |20.12Mb
  - ğŸ‡¨ğŸ‡­CH_291 |35.05Mb
  - netflix_NL |107.83Mb
  - disney_DE |231.84Mb
  - ğŸ‡±ğŸ‡¹LT_306 |147.32Mb
  - ğŸ‡±ğŸ‡¹LT_307 |131.27Mb
  - ğŸ‡±ğŸ‡¹LT_308 |227.21Mb
  - ğŸ‡²ğŸ‡½MX_314 |132.29Mb
  - ğŸ‡±ğŸ‡¹LT_309 |225.16Mb
  - ğŸ‡³ğŸ‡±NL_315 |195.88Mb
  - disney_DE |260.26Mb
  - netflix_NL |11.01Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_325 |158.71Mb
  - ğŸ‡²ğŸ‡©MD_313 |21.42Mb
  - ğŸ‡³ğŸ‡±NL_317 |90.99Mb
  - ğŸ‡³ğŸ‡±NL_318 |12.84Mb
  - Relay_ğŸ‡¯ğŸ‡µJP-ğŸ‡¯ğŸ‡µJP_305 |11.47Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_326 |15.98Mb
  - ğŸ‡µğŸ‡¹PT_320 |71.46Mb
  - disney_SG |23.47Mb
  - disney_SG |21.72Mb
  - disney_SG |19.71Mb
  - ğŸ‡±ğŸ‡¹LT_311 |14.07Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
