port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: _364 |11.16Mb
  server: 138.186.142.81
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _362 |709.95Mb
  server: 45.87.175.28
  type: ss
  port: 8080
  udp: true
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: _354 |157.14Mb
  server: 45.158.171.70
  type: ss
  port: 8080
  udp: true
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: _357 |155.25Mb
  server: 82.38.31.199
  type: ss
  port: 8080
  udp: true
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: _361 |32.15Mb
  server: 194.59.183.134
  type: ss
  port: 46114
  udp: true
  password: lejSRyqa033OEPmEQsvRsl
  cipher: chacha20-ietf-poly1305
- name: _367 |31.84Mb
  server: 173.234.29.2
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _356 |79.78Mb
  server: 46.246.96.30
  type: ss
  port: 31561
  udp: true
  password: hc8LMJew3Fl9MbcFCoFgT0
  cipher: chacha20-ietf-poly1305
- name: _366 |302.66Mb
  server: 185.153.197.5
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: disney_PY |137.07Mb
  server: 38.165.233.93
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: _370 |44.50Mb
  server: 185.82.73.212
  type: ss
  port: 8444
  udp: true
  password: _bypfvq6ra7g4n5yCCR9DoVeGya2XUUS
  cipher: chacha20-ietf-poly1305
- name: _373 |938.83Mb
  server: 151.242.251.152
  type: ss
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: _368 |22.34Mb
  server: 45.14.245.2
  type: ss
  port: 443
  password: 17ZDORWIliQHuO6WRGHChXYMzdRtAYVP
  cipher: chacha20-ietf-poly1305
- name: netflix_NL |848.93Mb
  server: 82.38.31.202
  type: ss
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: _375 |763.43Mb
  server: 45.87.175.22
  type: ss
  port: 8080
  udp: true
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: _359 |44.90Mb
  server: 156.59.243.6
  type: ss
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _355 |10.90Mb
  server: 38.89.142.56
  type: ss
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: Relay_-ğŸ‡¯ğŸ‡µJP_394 |13.94Mb
  server: 160.16.117.182
  type: trojan
  port: 3169
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: _379 |23.59Mb
  server: 47.242.145.160
  type: vmess
  port: 44457
  uuid: 40290609-2743-4d85-c9c3-4c72dd151b9f
  alterId: 0
  cipher: auto
  network: http
  http-opts:
    method: GET
    path:
    - /
  h2-opts: {}
- name: _393 |28.53Mb
  server: 219.79.214.159
  type: trojan
  port: 443
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: Relay_-ğŸ‡¯ğŸ‡µJP_395 |11.60Mb
  server: 153.121.45.139
  type: trojan
  port: 3093
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: _397 |15.42Mb
  server: 160.16.106.144
  type: trojan
  port: 2890
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: _400 |10.34Mb
  server: 160.16.116.227
  type: trojan
  port: 2760
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
  skip-cert-verify: true
- name: _401 |10.91Mb
  server: 160.16.106.144
  type: trojan
  port: 2760
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
  skip-cert-verify: true
- name: Relay_-ğŸ‡¯ğŸ‡µJP_402 |15.48Mb
  server: 160.16.229.223
  type: trojan
  port: 3169
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¯ğŸ‡µJP_405 |16.66Mb
  server: 160.16.117.182
  type: trojan
  port: 3093
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: disney_HK |23.15Mb
  server: 112.118.116.8
  type: trojan
  port: 443
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: disney_DE |223.32Mb
  server: 89.163.140.136
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: Relay_-ğŸ‡¯ğŸ‡µJP_408 |11.35Mb
  server: 160.16.72.33
  type: trojan
  port: 3093
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: ğŸ‡¨ğŸ‡¦CA_413 |87.36Mb
  server: 185.213.23.63
  type: ss
  country: ğŸ‡¨ğŸ‡¦CA
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸ‡¬ğŸ‡§GB-ğŸ‡³ğŸ‡±NL_418 |996.59Mb
  server: 82.38.31.208
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡²ğŸ‡½MX_435 |38.08Mb
  server: 216.238.87.47
  type: vmess
  country: ğŸ‡²ğŸ‡½MX
  port: 27502
  uuid: b8155ce4-7e08-4c40-800f-8671312b7124
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡®ğŸ‡¹IT_424 |46.53Mb
  server: 176.126.83.121
  type: ss
  country: ğŸ‡®ğŸ‡¹IT
  port: 443
  password: Q4t8T7hEYY3mD2Fn4wnxyK4X35AUzvR8
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_427 |161.03Mb
  server: 45.87.175.200
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_430 |156.54Mb
  server: 45.87.175.190
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_443 |40.75Mb
  server: 38.14.99.163
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 59807
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: auto
  network: tcp
  servername: 38.14.99.163
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_HK |25.67Mb
  server: 45.207.157.29
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 13852
  uuid: 845764df-ecb3-4b13-bed2-bf1551b68e9a
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡­ğŸ‡°HK_422 |13.78Mb
  server: 8.218.105.196
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 52752
  uuid: 925bdbf5-72be-4437-bebf-441c61089f6b
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡µğŸ‡¹PT_440 |67.15Mb
  server: 185.113.143.186
  type: ss
  country: ğŸ‡µğŸ‡¹PT
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¸ğŸ‡¬SG_441 |15.13Mb
  server: 68.183.227.45
  type: ss
  country: ğŸ‡¸ğŸ‡¬SG
  port: 8080
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: Relay_ğŸ‡¯ğŸ‡µJP-ğŸ‡¯ğŸ‡µJP_426 |11.53Mb
  server: xray.kk37005.tk
  type: vmess
  country: ğŸ‡¯ğŸ‡µJP
  port: 55919
  uuid: 2e7548bb-7c5b-4d97-d64d-1b2fe4050089
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: disney_netflix_US |26.13Mb
  server: cf.fovi.tk
  type: vmess
  country: ğŸZZ
  port: 443
  uuid: bf67437e-6c90-45ca-abc2-c7240a5ce2aa
  alterId: 0
  cipher: auto
  network: ws
  servername: foxlux.fovi.tk
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /eisasqa
    headers:
      HOST: foxlux.fovi.tk
- name: disney_LV |105.20Mb
  server: 46.183.217.204
  type: ss
  country: ğŸ‡±ğŸ‡» LV
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_442 |54.19Mb
  server: 47.253.197.26
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 12056
  uuid: dd7be7f1-38ff-45e6-f1e5-b20c2190f527
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - _364 |11.16Mb
  - _362 |709.95Mb
  - _354 |157.14Mb
  - _357 |155.25Mb
  - _361 |32.15Mb
  - _367 |31.84Mb
  - _356 |79.78Mb
  - _366 |302.66Mb
  - disney_PY |137.07Mb
  - _370 |44.50Mb
  - _373 |938.83Mb
  - _368 |22.34Mb
  - netflix_NL |848.93Mb
  - _375 |763.43Mb
  - _359 |44.90Mb
  - _355 |10.90Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_394 |13.94Mb
  - _379 |23.59Mb
  - _393 |28.53Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_395 |11.60Mb
  - _397 |15.42Mb
  - _400 |10.34Mb
  - _401 |10.91Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_402 |15.48Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_405 |16.66Mb
  - disney_HK |23.15Mb
  - disney_DE |223.32Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_408 |11.35Mb
  - ğŸ‡¨ğŸ‡¦CA_413 |87.36Mb
  - Relay_ğŸ‡¬ğŸ‡§GB-ğŸ‡³ğŸ‡±NL_418 |996.59Mb
  - ğŸ‡²ğŸ‡½MX_435 |38.08Mb
  - ğŸ‡®ğŸ‡¹IT_424 |46.53Mb
  - ğŸ‡±ğŸ‡¹LT_427 |161.03Mb
  - ğŸ‡±ğŸ‡¹LT_430 |156.54Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_443 |40.75Mb
  - disney_HK |25.67Mb
  - ğŸ‡­ğŸ‡°HK_422 |13.78Mb
  - ğŸ‡µğŸ‡¹PT_440 |67.15Mb
  - ğŸ‡¸ğŸ‡¬SG_441 |15.13Mb
  - Relay_ğŸ‡¯ğŸ‡µJP-ğŸ‡¯ğŸ‡µJP_426 |11.53Mb
  - disney_netflix_US |26.13Mb
  - disney_LV |105.20Mb
  - ğŸ‡ºğŸ‡¸US_442 |54.19Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - _364 |11.16Mb
  - _362 |709.95Mb
  - _354 |157.14Mb
  - _357 |155.25Mb
  - _361 |32.15Mb
  - _367 |31.84Mb
  - _356 |79.78Mb
  - _366 |302.66Mb
  - disney_PY |137.07Mb
  - _370 |44.50Mb
  - _373 |938.83Mb
  - _368 |22.34Mb
  - netflix_NL |848.93Mb
  - _375 |763.43Mb
  - _359 |44.90Mb
  - _355 |10.90Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_394 |13.94Mb
  - _379 |23.59Mb
  - _393 |28.53Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_395 |11.60Mb
  - _397 |15.42Mb
  - _400 |10.34Mb
  - _401 |10.91Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_402 |15.48Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_405 |16.66Mb
  - disney_HK |23.15Mb
  - disney_DE |223.32Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_408 |11.35Mb
  - ğŸ‡¨ğŸ‡¦CA_413 |87.36Mb
  - Relay_ğŸ‡¬ğŸ‡§GB-ğŸ‡³ğŸ‡±NL_418 |996.59Mb
  - ğŸ‡²ğŸ‡½MX_435 |38.08Mb
  - ğŸ‡®ğŸ‡¹IT_424 |46.53Mb
  - ğŸ‡±ğŸ‡¹LT_427 |161.03Mb
  - ğŸ‡±ğŸ‡¹LT_430 |156.54Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_443 |40.75Mb
  - disney_HK |25.67Mb
  - ğŸ‡­ğŸ‡°HK_422 |13.78Mb
  - ğŸ‡µğŸ‡¹PT_440 |67.15Mb
  - ğŸ‡¸ğŸ‡¬SG_441 |15.13Mb
  - Relay_ğŸ‡¯ğŸ‡µJP-ğŸ‡¯ğŸ‡µJP_426 |11.53Mb
  - disney_netflix_US |26.13Mb
  - disney_LV |105.20Mb
  - ğŸ‡ºğŸ‡¸US_442 |54.19Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
