port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: _352 |165.87Mb
  server: 172.235.33.114
  type: vmess
  port: 10001
  uuid: 442a3923-eca1-4af0-b3ff-24a7ce0af68f
  alterId: 0
  cipher: auto
  network: tcp
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: _341 |75.76Mb
  server: 82.38.31.179
  type: ss
  port: 8080
  udp: true
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: Relay_-ğŸ‡³ğŸ‡±NL_342 |293.12Mb
  server: 82.38.31.218
  type: ss
  port: 8080
  udp: true
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: _350 |302.21Mb
  server: 45.87.175.177
  type: ss
  port: 8080
  udp: true
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: disney_TW |41.42Mb
  server: 141.193.213.199
  type: trojan
  port: 443
  udp: true
  password: a8a5b34d-fe46-487d-bd6a-d9f3101525fd
  sni: 26z68w0ecxbuyf89.ukgogo202511.top
  skip-cert-verify: true
  ws-opts:
    path: /images
    headers:
      Host: 26z68w0ecxbuyf89.ukgogo202511.top
  network: ws
- name: _344 |167.76Mb
  server: 45.15.126.19
  type: ss
  port: 443
  udp: true
  password: 6Ts2ZDTQAf3hkFoB8AFufDwsGrlF4e2t
  cipher: chacha20-ietf-poly1305
- name: Relay_-ğŸ‡ºğŸ‡¸US_353 |27.73Mb
  server: us19-25.998998.best
  type: vmess
  port: 443
  udp: true
  uuid: 24254866-770c-41b4-9404-3f50524f425b
  alterId: 0
  cipher: auto
  network: ws
  servername: 24254866-770c-41b4-9404-3f50524f425b.mihomo.baby
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /saoihgreg9384gh8934
    headers:
      Host: 24254866-770c-41b4-9404-3f50524f425b.mihomo.baby
- name: disney_PT |134.22Mb
  server: 185.231.233.112
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: Relay_-ğŸ‡³ğŸ‡±NL_356 |47.13Mb
  server: 160.16.136.130
  type: trojan
  port: 4054
  password: 2cf6d686799e6fa95316394064f26c0a
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡³ğŸ‡±NL_357 |39.76Mb
  server: 160.16.196.59
  type: trojan
  port: 4054
  password: 2cf6d686799e6fa95316394064f26c0a
  sni: www.nintendogames.net
- name: disney_FR |146.74Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 27092
  uuid: a0596ba6-72a3-4366-8992-77088da65bd8
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: netflix_NL |330.92Mb
  server: 151.242.251.153
  type: ss
  country: ğŸ‡®ğŸ‡· IR
  port: 8080
  password: QCXDxuDlTTMD7jtgHUjIoj
  cipher: chacha20-ietf-poly1305
- name: disney_RU |27.41Mb
  server: 37.18.14.33
  type: trojan
  port: 443
  udp: true
  password: Qzy7tgpRhu
  sni: m.vk.com
  skip-cert-verify: true
- name: Relay_-ğŸ‡³ğŸ‡±NL_358 |43.61Mb
  server: 160.16.204.136
  type: trojan
  port: 2890
  password: 2cf6d686799e6fa95316394064f26c0a
  sni: www.nintendogames.net
- name: _351 |25.69Mb
  server: 103.149.182.86
  type: ss
  port: 8388
  password: asd123456
  cipher: chacha20-ietf
- name: Relay_ğŸZZ-ğŸ‡¦ğŸ‡ºAU_385 |13.82Mb
  server: sy4.620720.xyz
  type: vmess
  country: ğŸZZ
  port: 443
  uuid: 516d8a7a-3f0b-41d3-bad0-246116381516
  alterId: 0
  cipher: auto
  network: ws
  servername: sy4.620720.xyz
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /
    headers:
      HOST: sy4.620720.xyz
- name: Relay_-ğŸ‡¯ğŸ‡µJP_362 |11.81Mb
  server: 160.16.89.176
  type: trojan
  port: 3169
  password: 2cf6d686799e6fa95316394064f26c0a
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡³ğŸ‡±NL_367 |10.59Mb
  server: 160.16.196.59
  type: trojan
  port: 2760
  password: 2cf6d686799e6fa95316394064f26c0a
  sni: www.nintendogames.net
- name: ğŸ‡ºğŸ‡¸US_382 |35.68Mb
  server: pupas-shirting-unsung.freesocks.work
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: p78naCf2EfOlRSLTX0wFVx
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡·ğŸ‡ºRU_379 |391.98Mb
  server: 185.153.197.5
  type: ss
  country: ğŸ‡·ğŸ‡ºRU
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: disney_PY |16.05Mb
  server: 38.165.233.93
  type: ss
  country: ğŸ‡ºğŸ‡¸ US
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_383 |31.37Mb
  server: sw19.sesamebuta.top
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  uuid: 805ba514-bf2f-4d5d-df49-8417804e8de3
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /abcd
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - _352 |165.87Mb
  - _341 |75.76Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_342 |293.12Mb
  - _350 |302.21Mb
  - disney_TW |41.42Mb
  - _344 |167.76Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_353 |27.73Mb
  - disney_PT |134.22Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_356 |47.13Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_357 |39.76Mb
  - disney_FR |146.74Mb
  - netflix_NL |330.92Mb
  - disney_RU |27.41Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_358 |43.61Mb
  - _351 |25.69Mb
  - Relay_ğŸZZ-ğŸ‡¦ğŸ‡ºAU_385 |13.82Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_362 |11.81Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_367 |10.59Mb
  - ğŸ‡ºğŸ‡¸US_382 |35.68Mb
  - ğŸ‡·ğŸ‡ºRU_379 |391.98Mb
  - disney_PY |16.05Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_383 |31.37Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - _352 |165.87Mb
  - _341 |75.76Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_342 |293.12Mb
  - _350 |302.21Mb
  - disney_TW |41.42Mb
  - _344 |167.76Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_353 |27.73Mb
  - disney_PT |134.22Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_356 |47.13Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_357 |39.76Mb
  - disney_FR |146.74Mb
  - netflix_NL |330.92Mb
  - disney_RU |27.41Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_358 |43.61Mb
  - _351 |25.69Mb
  - Relay_ğŸZZ-ğŸ‡¦ğŸ‡ºAU_385 |13.82Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_362 |11.81Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_367 |10.59Mb
  - ğŸ‡ºğŸ‡¸US_382 |35.68Mb
  - ğŸ‡·ğŸ‡ºRU_379 |391.98Mb
  - disney_PY |16.05Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_383 |31.37Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
