port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: ğŸ‡ºğŸ‡¸US_15 |41.57Mb
  server: 216.167.34.227
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 45979
  uuid: 23bdf6df-c482-46d0-c0f4-5a98d534ea11
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
  ws-opts:
    path: /test
- name: ğŸ‡²ğŸ‡½MX_11 |10.31Mb
  server: 147.78.1.230
  type: ss
  country: ğŸ‡²ğŸ‡½MX
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: Relay_-ğŸ‡ºğŸ‡¸US_06 |24.93Mb
  server: us-n1.speedyyun.com
  type: vmess
  port: 25314
  udp: true
  uuid: 2a6c0365-e3ed-4aef-81ca-b1b6b46088da
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /victorias
    headers:
      Host: us-n1.speedyyun.com
- name: ğŸ‡³ğŸ‡±NL_12 |18.61Mb
  server: 193.29.139.164
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 8080
  password: 4a2rfixophdjffa8KVA4Aa
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡­ğŸ‡°HK_08 |10.06Mb
  server: 203.23.128.92
  type: ss
  country: ğŸ‡­ğŸ‡°HK
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: Pool_ğŸ‡­ğŸ‡°HK_10 |519.00Mb
  server: 150.107.46.21
  type: ssr
  country: ğŸ‡­ğŸ‡°HK
  port: 8083
  password: iFqnzSscN
  cipher: aes-256-cfb
  protocol: origin
  obfs: tls1.2_ticket_auth
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - ğŸ‡ºğŸ‡¸US_15 |41.57Mb
  - ğŸ‡²ğŸ‡½MX_11 |10.31Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_06 |24.93Mb
  - ğŸ‡³ğŸ‡±NL_12 |18.61Mb
  - ğŸ‡­ğŸ‡°HK_08 |10.06Mb
  - Pool_ğŸ‡­ğŸ‡°HK_10 |519.00Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - ğŸ‡ºğŸ‡¸US_15 |41.57Mb
  - ğŸ‡²ğŸ‡½MX_11 |10.31Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_06 |24.93Mb
  - ğŸ‡³ğŸ‡±NL_12 |18.61Mb
  - ğŸ‡­ğŸ‡°HK_08 |10.06Mb
  - Pool_ğŸ‡­ğŸ‡°HK_10 |519.00Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
