port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: netflix_DE |69.84Mb
  server: 43.165.7.71
  type: vmess
  port: 19751
  uuid: 6cfa6103-5d06-40cb-f452-b563db578288
  alterId: 0
  cipher: auto
  network: http
  http-opts:
    method: GET
    path:
    - /
  h2-opts: {}
- name: disney_netflix_GB |167.35Mb
  server: 172.66.44.230
  type: trojan
  port: 8443
  udp: true
  password: 8r<[9'l6hAO#8ZQi
  sni: Koma-YT.PAGeS.Dev
  ws-opts:
    path: /tro8sFW1S91B6sZrM1?ed=2560
    headers:
      Host: Koma-YT.PAGeS.Dev
  network: ws
- name: disney_netflix_GB |159.63Mb
  server: koma-yt.pages.dev
  type: trojan
  port: 8443
  udp: true
  password: 8r<[9'l6hAO#8ZQi
  sni: Koma-YT.PAGeS.Dev
  ws-opts:
    path: /tro8sFW1S91B6sZrM1?ed=2560
    headers:
      Host: Koma-YT.PAGeS.Dev
  network: ws
- name: Relay_-ðŸ‡³ðŸ‡±NL_324 |10.88Mb
  server: 160.16.196.59
  type: trojan
  port: 2890
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: disney_netflix_FR |111.02Mb
  server: 208.76.223.218
  type: vmess
  country: ðŸ‡ªðŸ‡¸ES
  port: 40433
  uuid: d8fd8955-78db-49ba-d86f-3e4729f6ac4d
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_HK |20.54Mb
  server: 58.152.30.120
  type: trojan
  port: 443
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: disney_HK |18.93Mb
  server: 58.152.18.95
  type: trojan
  port: 443
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: disney_SG |30.93Mb
  server: 210.87.110.16
  type: vmess
  port: 20297
  uuid: 692c1141-f196-4ac4-8af6-7a3b67304b90
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
- name: disney_HK |20.88Mb
  server: 58.152.25.242
  type: trojan
  port: 443
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: ðŸ‡²ðŸ‡½MX_435 |39.79Mb
  server: 216.238.89.53
  type: vmess
  country: ðŸ‡²ðŸ‡½MX
  port: 57283
  uuid: 1a5aafc0-6482-451d-fe76-6875b7818579
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_-ðŸ‡­ðŸ‡°HK_190 |12.53Mb
  server: v10.hdacd.com
  type: vmess
  port: 30807
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: Relay_ðŸ‡ºðŸ‡¸US-ðŸ‡ºðŸ‡¸US_442 |40.84Mb
  server: 38.14.99.163
  type: vmess
  country: ðŸ‡ºðŸ‡¸US
  port: 59807
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: auto
  network: tcp
  servername: 38.14.99.163
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_-ðŸ‡­ðŸ‡°HK_277 |12.91Mb
  server: v10.zgtfqs.click
  type: vmess
  port: 30807
  udp: true
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_NL |51.28Mb
  server: 109.71.246.210
  type: ss
  country: ðŸ‡·ðŸ‡ºRU
  port: 56689
  password: YQCSKoCF3QazW8YlvDBWA4
  cipher: chacha20-ietf-poly1305
- name: ðŸ‡°ðŸ‡·KR_434 |11.28Mb
  server: 146.56.112.110
  type: vmess
  country: ðŸ‡°ðŸ‡·KR
  port: 8888
  uuid: e7c302f3-90d6-42dd-9d7d-94a3683a3707
  alterId: 0
  cipher: auto
  network: tcp
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_PT |148.86Mb
  server: 185.231.233.112
  type: ss
  country: ðŸ‡µðŸ‡¹ PT
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: Relay_ðŸ‡°ðŸ‡·KR-ðŸ‡°ðŸ‡·KR_433 |14.03Mb
  server: seoul03.zgjok.com
  type: vmess
  country: ðŸ‡°ðŸ‡·KR
  port: 443
  uuid: 72a0dac4-9689-4a57-b164-5c65bfa94772
  alterId: 0
  cipher: auto
  network: ws
  servername: seoul03.zgjok.com
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /
    headers:
      HOST: seoul03.zgjok.com
- name: ðŸ‡¸ðŸ‡¬SG_440 |11.05Mb
  server: 68.183.178.131
  type: vmess
  country: ðŸ‡¸ðŸ‡¬SG
  port: 58607
  uuid: c11c32cb-27b3-4afa-c0f3-fb250aa4959e
  alterId: 0
  cipher: auto
  network: ws
  servername: www.12333.monster
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /
    headers:
      HOST: www.12333.monster
- name: Relay_ðŸ‡­ðŸ‡°HK-ðŸ‡ºðŸ‡¸US_368 |11.58Mb
  server: v8.hdacd.com
  type: vmess
  country: ðŸ‡­ðŸ‡°HK
  port: 30808
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: auto
  network: tcp
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_US |17.00Mb
  server: cf.fovi.tk
  type: vmess
  country: ðŸZZ
  port: 443
  uuid: bf67437e-6c90-45ca-abc2-c7240a5ce2aa
  alterId: 0
  cipher: auto
  network: ws
  servername: foxlux.fovi.tk
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /eisasqa
    headers:
      HOST: foxlux.fovi.tk
proxy-groups:
- name: ðŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - netflix_DE |69.84Mb
  - disney_netflix_GB |167.35Mb
  - disney_netflix_GB |159.63Mb
  - Relay_-ðŸ‡³ðŸ‡±NL_324 |10.88Mb
  - disney_netflix_FR |111.02Mb
  - disney_HK |20.54Mb
  - disney_HK |18.93Mb
  - disney_SG |30.93Mb
  - disney_HK |20.88Mb
  - ðŸ‡²ðŸ‡½MX_435 |39.79Mb
  - Relay_-ðŸ‡­ðŸ‡°HK_190 |12.53Mb
  - Relay_ðŸ‡ºðŸ‡¸US-ðŸ‡ºðŸ‡¸US_442 |40.84Mb
  - Relay_-ðŸ‡­ðŸ‡°HK_277 |12.91Mb
  - disney_netflix_NL |51.28Mb
  - ðŸ‡°ðŸ‡·KR_434 |11.28Mb
  - disney_PT |148.86Mb
  - Relay_ðŸ‡°ðŸ‡·KR-ðŸ‡°ðŸ‡·KR_433 |14.03Mb
  - ðŸ‡¸ðŸ‡¬SG_440 |11.05Mb
  - Relay_ðŸ‡­ðŸ‡°HK-ðŸ‡ºðŸ‡¸US_368 |11.58Mb
  - disney_US |17.00Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - netflix_DE |69.84Mb
  - disney_netflix_GB |167.35Mb
  - disney_netflix_GB |159.63Mb
  - Relay_-ðŸ‡³ðŸ‡±NL_324 |10.88Mb
  - disney_netflix_FR |111.02Mb
  - disney_HK |20.54Mb
  - disney_HK |18.93Mb
  - disney_SG |30.93Mb
  - disney_HK |20.88Mb
  - ðŸ‡²ðŸ‡½MX_435 |39.79Mb
  - Relay_-ðŸ‡­ðŸ‡°HK_190 |12.53Mb
  - Relay_ðŸ‡ºðŸ‡¸US-ðŸ‡ºðŸ‡¸US_442 |40.84Mb
  - Relay_-ðŸ‡­ðŸ‡°HK_277 |12.91Mb
  - disney_netflix_NL |51.28Mb
  - ðŸ‡°ðŸ‡·KR_434 |11.28Mb
  - disney_PT |148.86Mb
  - Relay_ðŸ‡°ðŸ‡·KR-ðŸ‡°ðŸ‡·KR_433 |14.03Mb
  - ðŸ‡¸ðŸ‡¬SG_440 |11.05Mb
  - Relay_ðŸ‡­ðŸ‡°HK-ðŸ‡ºðŸ‡¸US_368 |11.58Mb
  - disney_US |17.00Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ðŸš€ èŠ‚ç‚¹é€‰æ‹©
