port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: disney_netflix_US |41.34Mb
  server: 172.235.33.114
  type: vmess
  port: 10001
  uuid: 442a3923-eca1-4af0-b3ff-24a7ce0af68f
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: disney_netflix_US |43.53Mb
  server: 165.140.216.141
  type: vmess
  port: 443
  uuid: e7d72a8d-26f2-4b54-b366-0c43e0bcba7d
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: disney_netflix_US |42.08Mb
  server: 163.192.49.195
  type: vmess
  port: 443
  uuid: bcb7c581-3c95-4569-a4e7-918141e91ea3
  alterId: 0
  cipher: auto
  network: http
  http-opts:
    path:
    - /
    headers:
      Host:
      - a.189.cn
  h2-opts: {}
- name: _212 |13.38Mb
  server: 15.235.41.200
  type: vmess
  port: 80
  uuid: 58fe1542-5290-40ad-815a-77707a81afe5
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /IOebhLMhl1CTbFHbL95myfRX2
- name: _202 |14.43Mb
  server: 51.79.102.253
  type: vmess
  port: 80
  uuid: 58fe1542-5290-40ad-815a-77707a81afe5
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /IOebhLMhl1CTbFHbL95myfRX2
    headers:
      Host: wrmelmwxlf.gktevlrqznwqqozy.fabpfs66gizmnojhcvqxwl.kytrcfzqla87gvgvs6c7kjnrubuh.cc
- name: _192 |61.20Mb
  server: 91.99.27.55
  type: vmess
  port: 8880
  uuid: f3025961-167b-4f49-e4e3-86505fe980fd
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _194 |270.98Mb
  server: 85.195.101.122
  type: vmess
  port: 40878
  uuid: f3d4167e-b15e-4e46-82e9-9286ef93fda7
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _207 |15.32Mb
  server: 45.136.12.37
  type: vmess
  port: 38141
  uuid: fd291be6-b48d-43a1-da38-66c7f80e2f80
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: disney_netflix_US |54.49Mb
  server: 45.150.52.40
  type: vmess
  port: 443
  uuid: c31777a1-2ee6-4864-db4c-a79fcbc8188b
  alterId: 0
  cipher: auto
  network: ws
  servername: xsj011-3.facai2024.com
  http-opts: {}
  h2-opts: {}
  tls: true
  ws-opts:
    path: /c31777a1
    headers:
      Host: xsj011-3.facai2024.com
- name: _213 |41.78Mb
  server: 89.31.120.192
  type: vmess
  port: 443
  uuid: 44537595-9ccc-4b83-8936-5f9ad3229019
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: disney_TW |19.46Mb
  server: 103.127.218.91
  type: vmess
  port: 54693
  uuid: 1cef03ad-6343-408c-8121-cbd1fda2ee9d
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /1cef03ad
- name: _224 |116.32Mb
  server: 38.180.16.86
  type: vmess
  port: 38039
  uuid: 244a3464-1269-43b3-b491-4dc2713eb3f6
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _229 |71.57Mb
  server: 38.180.16.86
  type: vmess
  port: 36236
  uuid: a58bc1a5-8c18-49ff-9453-c331b52f45dc
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _230 |10.96Mb
  server: 140.238.2.250
  type: vmess
  port: 443
  uuid: 41a7089a-040b-4538-8b8d-010902405bde
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _260 |21.29Mb
  server: 160.16.229.223
  type: trojan
  port: 3093
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: _261 |12.14Mb
  server: 202.181.103.235
  type: trojan
  port: 2890
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: _263 |50.43Mb
  server: 160.16.223.205
  type: trojan
  port: 4054
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡ºğŸ‡¸US_209 |211.58Mb
  server: 3h-kazakhstan1.09vpn.com
  type: vmess
  port: 80
  uuid: 567f4be5-12ab-42e1-b8d9-db6fd1fdd31c
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /vmess/
    headers:
      Host: 3h-kazakhstan1.09vpn.com
- name: _265 |10.46Mb
  server: 160.16.214.6
  type: trojan
  port: 2890
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: netflix_CA |24.59Mb
  server: 38.96.254.102
  type: trojan
  port: 18509
  password: .ie4rghJuMkcf0oF
  sni: shoppingmall.electricbanana.click
- name: disney_HK |16.57Mb
  server: 58.152.30.120
  type: trojan
  port: 443
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: Relay_-ğŸ‡¯ğŸ‡µJP_270 |11.46Mb
  server: 13.112.81.124
  type: trojan
  port: 3169
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: disney_HK |28.35Mb
  server: 58.152.18.95
  type: trojan
  port: 443
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: Pool__268 |51.99Mb
  server: 70.34.218.149
  type: trojan
  port: 11930
  password: BaeSzHdfJIR13l67
  sni: softpillow.silentrocket.click
- name: disney_HK |28.10Mb
  server: 58.152.110.82
  type: trojan
  port: 443
  udp: true
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: _273 |47.09Mb
  server: 160.16.124.55
  type: trojan
  port: 2890
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¸ğŸ‡¬SG_274 |11.35Mb
  server: 160.16.153.13
  type: trojan
  port: 3145
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: _277 |16.56Mb
  server: 160.16.117.182
  type: trojan
  port: 3093
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡ºğŸ‡¸US_197 |11.76Mb
  server: v29.hdacd.com
  type: vmess
  port: 30829
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: disney_HK |26.43Mb
  server: 219.78.209.224
  type: trojan
  port: 443
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: disney_FR |137.97Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 40433
  uuid: d8fd8955-78db-49ba-d86f-3e4729f6ac4d
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_FR |34.26Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 27092
  uuid: a0596ba6-72a3-4366-8992-77088da65bd8
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_HK |27.54Mb
  server: 58.152.53.174
  type: trojan
  port: 443
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: ğŸ‡¬ğŸ‡§GB_282 |229.59Mb
  server: 82.38.31.217
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_283 |97.71Mb
  server: 82.38.31.191
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: netflix_NL |177.80Mb
  server: 82.38.31.194
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: disney_HK |23.06Mb
  server: 45.207.157.29
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 13852
  uuid: 845764df-ecb3-4b13-bed2-bf1551b68e9a
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_ğŸ‡¹ğŸ‡·TR-ğŸ‡¹ğŸ‡·TR_287 |35.84Mb
  server: tr-1.stunnel.cc
  type: ss
  country: ğŸ‡¹ğŸ‡·TR
  port: 8444
  password: tunnel-fbrof
  cipher: chacha20-ietf-poly1305
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - disney_netflix_US |41.34Mb
  - disney_netflix_US |43.53Mb
  - disney_netflix_US |42.08Mb
  - _212 |13.38Mb
  - _202 |14.43Mb
  - _192 |61.20Mb
  - _194 |270.98Mb
  - _207 |15.32Mb
  - disney_netflix_US |54.49Mb
  - _213 |41.78Mb
  - disney_TW |19.46Mb
  - _224 |116.32Mb
  - _229 |71.57Mb
  - _230 |10.96Mb
  - _260 |21.29Mb
  - _261 |12.14Mb
  - _263 |50.43Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_209 |211.58Mb
  - _265 |10.46Mb
  - netflix_CA |24.59Mb
  - disney_HK |16.57Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_270 |11.46Mb
  - disney_HK |28.35Mb
  - Pool__268 |51.99Mb
  - disney_HK |28.10Mb
  - _273 |47.09Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_274 |11.35Mb
  - _277 |16.56Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_197 |11.76Mb
  - disney_HK |26.43Mb
  - disney_FR |137.97Mb
  - disney_FR |34.26Mb
  - disney_HK |27.54Mb
  - ğŸ‡¬ğŸ‡§GB_282 |229.59Mb
  - ğŸ‡¬ğŸ‡§GB_283 |97.71Mb
  - netflix_NL |177.80Mb
  - disney_HK |23.06Mb
  - Relay_ğŸ‡¹ğŸ‡·TR-ğŸ‡¹ğŸ‡·TR_287 |35.84Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - disney_netflix_US |41.34Mb
  - disney_netflix_US |43.53Mb
  - disney_netflix_US |42.08Mb
  - _212 |13.38Mb
  - _202 |14.43Mb
  - _192 |61.20Mb
  - _194 |270.98Mb
  - _207 |15.32Mb
  - disney_netflix_US |54.49Mb
  - _213 |41.78Mb
  - disney_TW |19.46Mb
  - _224 |116.32Mb
  - _229 |71.57Mb
  - _230 |10.96Mb
  - _260 |21.29Mb
  - _261 |12.14Mb
  - _263 |50.43Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_209 |211.58Mb
  - _265 |10.46Mb
  - netflix_CA |24.59Mb
  - disney_HK |16.57Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_270 |11.46Mb
  - disney_HK |28.35Mb
  - Pool__268 |51.99Mb
  - disney_HK |28.10Mb
  - _273 |47.09Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_274 |11.35Mb
  - _277 |16.56Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_197 |11.76Mb
  - disney_HK |26.43Mb
  - disney_FR |137.97Mb
  - disney_FR |34.26Mb
  - disney_HK |27.54Mb
  - ğŸ‡¬ğŸ‡§GB_282 |229.59Mb
  - ğŸ‡¬ğŸ‡§GB_283 |97.71Mb
  - netflix_NL |177.80Mb
  - disney_HK |23.06Mb
  - Relay_ğŸ‡¹ğŸ‡·TR-ğŸ‡¹ğŸ‡·TR_287 |35.84Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
