port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: _202 |49.26Mb
  server: 167.160.90.178
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _193 |13.38Mb
  server: 147.78.1.27
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _208 |906.33Mb
  server: 38.34.24.196
  type: vmess
  port: 20522
  uuid: f65ae5d8-f779-4ab2-8ba3-e4d46d34ef9d
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /telegram_@sswia
- name: _166 |43.94Mb
  server: 138.186.142.81
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _176 |44.16Mb
  server: 138.186.142.80
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _175 |14.41Mb
  server: 109.61.46.43
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _205 |47.96Mb
  server: 212.102.54.45
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _195 |31.21Mb
  server: 154.205.153.107
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _170 |13.57Mb
  server: 185.237.185.89
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _165 |43.75Mb
  server: 38.54.59.180
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: Relay_-ğŸ‡ºğŸ‡¸US_221 |144.27Mb
  server: xcf056-1.facai2024.com
  type: vmess
  port: 443
  uuid: ead690c8-ba41-43be-bceb-bcbf714ceb11
  alterId: 0
  cipher: auto
  network: ws
  servername: xcf056-1.facai2024.com
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /ead690c8
- name: Relay_ğŸ‡¨ğŸ‡¦CA-ğŸ‡¨ğŸ‡¦CA_246 |152.00Mb
  server: ssca.irundns.net
  type: ssr
  country: ğŸ‡¨ğŸ‡¦CA
  port: 443
  password: $$Turb0VPN$$
  cipher: aes-128-cfb
  protocol: auth_aes128_md5
  obfs: http_post
- name: ğŸ‡¨ğŸ‡·CR_262 |48.16Mb
  server: 145.14.131.37
  type: ss
  country: ğŸ‡¨ğŸ‡·CR
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡¹GT_346 |38.67Mb
  server: 185.47.254.87
  type: ss
  country: ğŸ‡¬ğŸ‡¹GT
  port: 990
  password: f8f7aCzcPKbsF8p3
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡¹GT_347 |15.05Mb
  server: 185.47.254.87
  type: ss
  country: ğŸ‡¬ğŸ‡¹GT
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡§ğŸ‡·BR_235 |10.84Mb
  server: 185.192.124.188
  type: ss
  country: ğŸ‡§ğŸ‡·BR
  port: 990
  password: f8f7aCzcPKbsF8p3
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_327 |17.64Mb
  server: 141.98.101.182
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: shadowsocks
  cipher: aes-128-gcm
- name: _156 |36.37Mb
  server: 38.54.59.107
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡©ğŸ‡°DK_297 |49.23Mb
  server: 121.127.45.165
  type: ss
  country: ğŸ‡©ğŸ‡°DK
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¯ğŸ‡µJP_384 |18.06Mb
  server: 172.105.199.91
  type: ss
  country: ğŸ‡¯ğŸ‡µJP
  port: 8080
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: ğŸ‡¬ğŸ‡§GB_341 |10.15Mb
  server: 89.213.156.225
  type: vmess
  country: ğŸ‡¬ğŸ‡§GB
  port: 42719
  uuid: 1ea5b565-c2c9-4315-b34f-29c958b3968d
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
  ws-opts:
    path: /arki?ed=2048
- name: ğŸ‡¯ğŸ‡µJP_385 |12.71Mb
  server: 172.105.199.111
  type: ss
  country: ğŸ‡¯ğŸ‡µJP
  port: 8080
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: ğŸ‡¯ğŸ‡µJP_386 |14.73Mb
  server: 153.121.51.214
  type: ss
  country: ğŸ‡¯ğŸ‡µJP
  port: 10087
  password: '10086'
  cipher: aes-128-gcm
- name: ğŸ‡¯ğŸ‡µJP_388 |10.37Mb
  server: 140.83.80.36
  type: vmess
  country: ğŸ‡¯ğŸ‡µJP
  port: 22545
  uuid: 5b907403-239e-4660-8ab6-b6f3d811d1da
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
  ws-opts:
    path: /
- name: ğŸ‡±ğŸ‡¹LT_395 |12.28Mb
  server: 45.87.175.157
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: QCXDxuDlTTMD7jtgHUjIoj
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸ‡¯ğŸ‡µJP-ğŸ‡¯ğŸ‡µJP_387 |10.19Mb
  server: xray.kk37005.tk
  type: vmess
  country: ğŸ‡¯ğŸ‡µJP
  port: 55919
  uuid: 2e7548bb-7c5b-4d97-d64d-1b2fe4050089
  alterId: 0
  cipher: auto
  network: tcp
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: ğŸ‡±ğŸ‡¹LT_401 |13.05Mb
  server: 45.87.175.164
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: Pool_ğŸ‡­ğŸ‡°HK_351 |443.00Mb
  server: 150.107.46.21
  type: ssr
  country: ğŸ‡­ğŸ‡°HK
  port: 8083
  password: iFqnzSscN
  cipher: aes-256-cfb
  protocol: origin
  obfs: tls1.2_ticket_auth
- name: ğŸ‡±ğŸ‡¹LT_413 |12.26Mb
  server: 45.87.175.192
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_415 |11.95Mb
  server: 45.87.175.164
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: QCXDxuDlTTMD7jtgHUjIoj
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_422 |11.96Mb
  server: 45.87.175.181
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: 4a2rfixophdjffa8KVA4Aa
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_430 |13.52Mb
  server: 45.87.175.165
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: QCXDxuDlTTMD7jtgHUjIoj
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_431 |15.79Mb
  server: 45.87.175.181
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡³ğŸ‡±NL_441 |13.70Mb
  server: 193.29.139.164
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 8080
  password: 4a2rfixophdjffa8KVA4Aa
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡³ğŸ‡±NL_445 |15.70Mb
  server: 193.29.139.217
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 8080
  password: 4a2rfixophdjffa8KVA4Aa
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡³ğŸ‡±NL_447 |18.30Mb
  server: 77.238.224.29
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 55702
  password: S2QudBxi0vRySw4YRLloPq
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡³ğŸ‡±NL_451 |10.84Mb
  server: 193.29.139.199
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 8080
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_426 |12.56Mb
  server: beesyar.org
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡³ğŸ‡±NL_452 |11.03Mb
  server: 193.29.139.157
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 8080
  password: QCXDxuDlTTMD7jtgHUjIoj
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡³ğŸ‡±NL_457 |12.25Mb
  server: 193.29.139.157
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 8080
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡²ğŸ‡¹MT_435 |22.96Mb
  server: 171.22.254.129
  type: ss
  country: ğŸ‡²ğŸ‡¹MT
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡³ğŸ‡±NL_461 |12.94Mb
  server: 193.29.139.144
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 8080
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡·ğŸ‡ºRU_527 |79.31Mb
  server: 95.163.176.37
  type: ss
  country: ğŸ‡·ğŸ‡ºRU
  port: 8506
  password: VdswxetVc6AhIps18rtYbm
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡µğŸ‡¹PT_520 |43.32Mb
  server: 185.113.143.186
  type: ss
  country: ğŸ‡µğŸ‡¹PT
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡·ğŸ‡´RO_523 |16.06Mb
  server: 188.214.36.155
  type: ss
  country: ğŸ‡·ğŸ‡´RO
  port: 990
  password: f8f7aCzcPKbsF8p3
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡·ğŸ‡ºRU_529 |167.27Mb
  server: 95.163.176.37
  type: ss
  country: ğŸ‡·ğŸ‡ºRU
  port: 8506
  password: KVe53W0gvOHIOJxXChJ5uA
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡·ğŸ‡ºRU_528 |173.32Mb
  server: 95.163.176.37
  type: ss
  country: ğŸ‡·ğŸ‡ºRU
  port: 8506
  password: dURrI3V1m42NLew9vJk6XC
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡·ğŸ‡ºRU_530 |68.70Mb
  server: 95.163.176.37
  type: ss
  country: ğŸ‡·ğŸ‡ºRU
  port: 8506
  password: lrU5qzW5nOHsIWiDRcDOpY
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_568 |55.43Mb
  server: 3.145.163.105
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡ºğŸ‡¸US_570 |34.11Mb
  server: 3.147.66.58
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡·ğŸ‡ºRU_531 |10.00Mb
  server: 146.70.52.150
  type: ss
  country: ğŸ‡·ğŸ‡ºRU
  port: 8080
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: ğŸ‡·ğŸ‡ºRU_532 |170.32Mb
  server: 95.163.176.37
  type: ss
  country: ğŸ‡·ğŸ‡ºRU
  port: 8506
  password: eUh4lSpi7nOYj0vSrqLUh0
  cipher: chacha20-ietf-poly1305
- name: disney_US |25.68Mb
  server: 216.132.112.116
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 34958
  password: AJtV4VCLaVQUKGH4g1ADSyqvzCA0mSpN46an12ZeIKhx
  cipher: aes-256-gcm
- name: ğŸ‡·ğŸ‡ºRU_533 |177.05Mb
  server: 95.163.176.37
  type: ss
  country: ğŸ‡·ğŸ‡ºRU
  port: 8506
  password: ZK8Hv7D68bNRynZeqLVFLM
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_577 |61.15Mb
  server: 104.192.226.106
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 990
  password: f8f7aCzcPKbsF8p3
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_584 |13.77Mb
  server: 156.146.38.169
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: shadowsocks
  cipher: aes-128-gcm
- name: ğŸ‡ºğŸ‡¸US_581 |76.09Mb
  server: 173.244.56.6
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: shadowsocks
  cipher: aes-128-gcm
- name: ğŸ‡¸ğŸ‡¬SG_542 |10.22Mb
  server: 68.183.235.122
  type: ss
  country: ğŸ‡¸ğŸ‡¬SG
  port: 8080
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: ğŸ‡ºğŸ‡¸US_589 |32.39Mb
  server: 3.139.67.190
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡¸ğŸ‡°SK_550 |48.16Mb
  server: 193.37.255.38
  type: ss
  country: ğŸ‡¸ğŸ‡°SK
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_590 |55.42Mb
  server: 3.148.213.139
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡ºğŸ‡¸US_569 |123.39Mb
  server: 94.131.22.134
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 40565
  password: n7nqKk8Dr1ycsZKd5q5huWdCsbxVQEa4McgLmohr5oeTARXjx49jLFG4Efq4FGN7MdAbVaQUZfp1Y4nCUCMzuqTxqdwBQ19T
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_591 |10.46Mb
  server: 3.21.158.73
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡¹ğŸ‡¼TW_553 |127.76Mb
  server: 223.165.4.173
  type: ss
  country: ğŸ‡¹ğŸ‡¼TW
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ğŸ‡ºğŸ‡¸US_592 |10.90Mb
  server: 173.244.56.9
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: shadowsocks
  cipher: aes-128-gcm
- name: ğŸ‡ºğŸ‡¸US_583 |14.53Mb
  server: 149.22.87.204
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: shadowsocks
  cipher: aes-128-gcm
- name: disney_US |13.36Mb
  server: 193.124.24.247
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 6503
  uuid: 978d0097-dc80-48db-935a-348a08dff336
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡²ğŸ‡©MD_606 |10.27Mb
  server: 23.95.76.147
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_608 |55.51Mb
  server: 3.133.131.192
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: disney_US |895.03Mb
  server: 193.124.24.247
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 6508
  uuid: b68fead5-5b0b-43a1-c34a-804467f0f368
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_US |56.31Mb
  server: 193.124.24.247
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 6515
  uuid: 2f3c646a-37f3-483a-a2a5-6bc1c5e526ae
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_US |10.13Mb
  server: 193.124.24.247
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 6513
  uuid: 5cf7fcbc-e2c1-42c4-d0d7-79c45a7d588d
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_US |994.15Mb
  server: 154.64.243.19
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 38533
  uuid: 9bc23ccf-4769-4e9a-b278-2dfa8d9ef425
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
  ws-opts:
    path: /
- name: ğŸ‡ºğŸ‡¸US_618 |15.80Mb
  server: 47.86.85.95
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 26006
  uuid: 7d719104-729e-4698-a597-59798aa64f0f
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
  ws-opts:
    path: /arki?ed=2048
- name: ğŸ‡ºğŸ‡¸US_579 |96.03Mb
  server: imap.roomyinmita.name
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 40565
  password: oEkEWExFKHKeY1xuRns6ErkYbzt3HdCGNPN3nTQnM1FU7yTR1SZTTC2JLtPF7HeFAUCGgx5hvxUGw8ksjEyRioPEeXhxg7Q3
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_578 |78.23Mb
  server: imap.roomyinmita.name
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 40565
  password: Rf2YYzTe6TNnBU1dxZuAa7a8Yde8qMEY5ex74ay2sUMdvwjpcxvkCnuXWea88JrgubHhrRvd3RNAG4gxaG7xAQ8UA2NNgKtm
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_575 |71.33Mb
  server: imap.roomyinmita.name
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 40565
  password: n7nqKk8Dr1ycsZKd5q5huWdCsbxVQEa4McgLmohr5oeTARXjx49jLFG4Efq4FGN7MdAbVaQUZfp1Y4nCUCMzuqTxqdwBQ19T
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_588 |40.17Mb
  server: imap.roomyinmita.name
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 40565
  password: HoLrWgDZRsGAFfyScdAZucVSE3S8gn9K966G9ggvmFwHL937vbCHjSCb81cbbf1ubdvk1d8HabZLFK1b8yM7QtPhmmA67YbV
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_609 |17.10Mb
  server: xu.xutong.top
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 22309
  uuid: 3140d444-6a3e-45d6-9aba-2d987c28728a
  alterId: 0
  cipher: auto
  network: tcp
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - _202 |49.26Mb
  - _193 |13.38Mb
  - _208 |906.33Mb
  - _166 |43.94Mb
  - _176 |44.16Mb
  - _175 |14.41Mb
  - _205 |47.96Mb
  - _195 |31.21Mb
  - _170 |13.57Mb
  - _165 |43.75Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_221 |144.27Mb
  - Relay_ğŸ‡¨ğŸ‡¦CA-ğŸ‡¨ğŸ‡¦CA_246 |152.00Mb
  - ğŸ‡¨ğŸ‡·CR_262 |48.16Mb
  - ğŸ‡¬ğŸ‡¹GT_346 |38.67Mb
  - ğŸ‡¬ğŸ‡¹GT_347 |15.05Mb
  - ğŸ‡§ğŸ‡·BR_235 |10.84Mb
  - ğŸ‡¬ğŸ‡§GB_327 |17.64Mb
  - _156 |36.37Mb
  - ğŸ‡©ğŸ‡°DK_297 |49.23Mb
  - ğŸ‡¯ğŸ‡µJP_384 |18.06Mb
  - ğŸ‡¬ğŸ‡§GB_341 |10.15Mb
  - ğŸ‡¯ğŸ‡µJP_385 |12.71Mb
  - ğŸ‡¯ğŸ‡µJP_386 |14.73Mb
  - ğŸ‡¯ğŸ‡µJP_388 |10.37Mb
  - ğŸ‡±ğŸ‡¹LT_395 |12.28Mb
  - Relay_ğŸ‡¯ğŸ‡µJP-ğŸ‡¯ğŸ‡µJP_387 |10.19Mb
  - ğŸ‡±ğŸ‡¹LT_401 |13.05Mb
  - Pool_ğŸ‡­ğŸ‡°HK_351 |443.00Mb
  - ğŸ‡±ğŸ‡¹LT_413 |12.26Mb
  - ğŸ‡±ğŸ‡¹LT_415 |11.95Mb
  - ğŸ‡±ğŸ‡¹LT_422 |11.96Mb
  - ğŸ‡±ğŸ‡¹LT_430 |13.52Mb
  - ğŸ‡±ğŸ‡¹LT_431 |15.79Mb
  - ğŸ‡³ğŸ‡±NL_441 |13.70Mb
  - ğŸ‡³ğŸ‡±NL_445 |15.70Mb
  - ğŸ‡³ğŸ‡±NL_447 |18.30Mb
  - ğŸ‡³ğŸ‡±NL_451 |10.84Mb
  - ğŸ‡±ğŸ‡¹LT_426 |12.56Mb
  - ğŸ‡³ğŸ‡±NL_452 |11.03Mb
  - ğŸ‡³ğŸ‡±NL_457 |12.25Mb
  - ğŸ‡²ğŸ‡¹MT_435 |22.96Mb
  - ğŸ‡³ğŸ‡±NL_461 |12.94Mb
  - ğŸ‡·ğŸ‡ºRU_527 |79.31Mb
  - ğŸ‡µğŸ‡¹PT_520 |43.32Mb
  - ğŸ‡·ğŸ‡´RO_523 |16.06Mb
  - ğŸ‡·ğŸ‡ºRU_529 |167.27Mb
  - ğŸ‡·ğŸ‡ºRU_528 |173.32Mb
  - ğŸ‡·ğŸ‡ºRU_530 |68.70Mb
  - ğŸ‡ºğŸ‡¸US_568 |55.43Mb
  - ğŸ‡ºğŸ‡¸US_570 |34.11Mb
  - ğŸ‡·ğŸ‡ºRU_531 |10.00Mb
  - ğŸ‡·ğŸ‡ºRU_532 |170.32Mb
  - disney_US |25.68Mb
  - ğŸ‡·ğŸ‡ºRU_533 |177.05Mb
  - ğŸ‡ºğŸ‡¸US_577 |61.15Mb
  - ğŸ‡ºğŸ‡¸US_584 |13.77Mb
  - ğŸ‡ºğŸ‡¸US_581 |76.09Mb
  - ğŸ‡¸ğŸ‡¬SG_542 |10.22Mb
  - ğŸ‡ºğŸ‡¸US_589 |32.39Mb
  - ğŸ‡¸ğŸ‡°SK_550 |48.16Mb
  - ğŸ‡ºğŸ‡¸US_590 |55.42Mb
  - ğŸ‡ºğŸ‡¸US_569 |123.39Mb
  - ğŸ‡ºğŸ‡¸US_591 |10.46Mb
  - ğŸ‡¹ğŸ‡¼TW_553 |127.76Mb
  - ğŸ‡ºğŸ‡¸US_592 |10.90Mb
  - ğŸ‡ºğŸ‡¸US_583 |14.53Mb
  - disney_US |13.36Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡²ğŸ‡©MD_606 |10.27Mb
  - ğŸ‡ºğŸ‡¸US_608 |55.51Mb
  - disney_US |895.03Mb
  - disney_US |56.31Mb
  - disney_US |10.13Mb
  - disney_US |994.15Mb
  - ğŸ‡ºğŸ‡¸US_618 |15.80Mb
  - ğŸ‡ºğŸ‡¸US_579 |96.03Mb
  - ğŸ‡ºğŸ‡¸US_578 |78.23Mb
  - ğŸ‡ºğŸ‡¸US_575 |71.33Mb
  - ğŸ‡ºğŸ‡¸US_588 |40.17Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_609 |17.10Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - _202 |49.26Mb
  - _193 |13.38Mb
  - _208 |906.33Mb
  - _166 |43.94Mb
  - _176 |44.16Mb
  - _175 |14.41Mb
  - _205 |47.96Mb
  - _195 |31.21Mb
  - _170 |13.57Mb
  - _165 |43.75Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_221 |144.27Mb
  - Relay_ğŸ‡¨ğŸ‡¦CA-ğŸ‡¨ğŸ‡¦CA_246 |152.00Mb
  - ğŸ‡¨ğŸ‡·CR_262 |48.16Mb
  - ğŸ‡¬ğŸ‡¹GT_346 |38.67Mb
  - ğŸ‡¬ğŸ‡¹GT_347 |15.05Mb
  - ğŸ‡§ğŸ‡·BR_235 |10.84Mb
  - ğŸ‡¬ğŸ‡§GB_327 |17.64Mb
  - _156 |36.37Mb
  - ğŸ‡©ğŸ‡°DK_297 |49.23Mb
  - ğŸ‡¯ğŸ‡µJP_384 |18.06Mb
  - ğŸ‡¬ğŸ‡§GB_341 |10.15Mb
  - ğŸ‡¯ğŸ‡µJP_385 |12.71Mb
  - ğŸ‡¯ğŸ‡µJP_386 |14.73Mb
  - ğŸ‡¯ğŸ‡µJP_388 |10.37Mb
  - ğŸ‡±ğŸ‡¹LT_395 |12.28Mb
  - Relay_ğŸ‡¯ğŸ‡µJP-ğŸ‡¯ğŸ‡µJP_387 |10.19Mb
  - ğŸ‡±ğŸ‡¹LT_401 |13.05Mb
  - Pool_ğŸ‡­ğŸ‡°HK_351 |443.00Mb
  - ğŸ‡±ğŸ‡¹LT_413 |12.26Mb
  - ğŸ‡±ğŸ‡¹LT_415 |11.95Mb
  - ğŸ‡±ğŸ‡¹LT_422 |11.96Mb
  - ğŸ‡±ğŸ‡¹LT_430 |13.52Mb
  - ğŸ‡±ğŸ‡¹LT_431 |15.79Mb
  - ğŸ‡³ğŸ‡±NL_441 |13.70Mb
  - ğŸ‡³ğŸ‡±NL_445 |15.70Mb
  - ğŸ‡³ğŸ‡±NL_447 |18.30Mb
  - ğŸ‡³ğŸ‡±NL_451 |10.84Mb
  - ğŸ‡±ğŸ‡¹LT_426 |12.56Mb
  - ğŸ‡³ğŸ‡±NL_452 |11.03Mb
  - ğŸ‡³ğŸ‡±NL_457 |12.25Mb
  - ğŸ‡²ğŸ‡¹MT_435 |22.96Mb
  - ğŸ‡³ğŸ‡±NL_461 |12.94Mb
  - ğŸ‡·ğŸ‡ºRU_527 |79.31Mb
  - ğŸ‡µğŸ‡¹PT_520 |43.32Mb
  - ğŸ‡·ğŸ‡´RO_523 |16.06Mb
  - ğŸ‡·ğŸ‡ºRU_529 |167.27Mb
  - ğŸ‡·ğŸ‡ºRU_528 |173.32Mb
  - ğŸ‡·ğŸ‡ºRU_530 |68.70Mb
  - ğŸ‡ºğŸ‡¸US_568 |55.43Mb
  - ğŸ‡ºğŸ‡¸US_570 |34.11Mb
  - ğŸ‡·ğŸ‡ºRU_531 |10.00Mb
  - ğŸ‡·ğŸ‡ºRU_532 |170.32Mb
  - disney_US |25.68Mb
  - ğŸ‡·ğŸ‡ºRU_533 |177.05Mb
  - ğŸ‡ºğŸ‡¸US_577 |61.15Mb
  - ğŸ‡ºğŸ‡¸US_584 |13.77Mb
  - ğŸ‡ºğŸ‡¸US_581 |76.09Mb
  - ğŸ‡¸ğŸ‡¬SG_542 |10.22Mb
  - ğŸ‡ºğŸ‡¸US_589 |32.39Mb
  - ğŸ‡¸ğŸ‡°SK_550 |48.16Mb
  - ğŸ‡ºğŸ‡¸US_590 |55.42Mb
  - ğŸ‡ºğŸ‡¸US_569 |123.39Mb
  - ğŸ‡ºğŸ‡¸US_591 |10.46Mb
  - ğŸ‡¹ğŸ‡¼TW_553 |127.76Mb
  - ğŸ‡ºğŸ‡¸US_592 |10.90Mb
  - ğŸ‡ºğŸ‡¸US_583 |14.53Mb
  - disney_US |13.36Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡²ğŸ‡©MD_606 |10.27Mb
  - ğŸ‡ºğŸ‡¸US_608 |55.51Mb
  - disney_US |895.03Mb
  - disney_US |56.31Mb
  - disney_US |10.13Mb
  - disney_US |994.15Mb
  - ğŸ‡ºğŸ‡¸US_618 |15.80Mb
  - ğŸ‡ºğŸ‡¸US_579 |96.03Mb
  - ğŸ‡ºğŸ‡¸US_578 |78.23Mb
  - ğŸ‡ºğŸ‡¸US_575 |71.33Mb
  - ğŸ‡ºğŸ‡¸US_588 |40.17Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_609 |17.10Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
