port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: _251 |51.50Mb
  server: 137.184.174.93
  type: ss
  port: 8080
  udp: true
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: _254 |13.15Mb
  server: 23.95.75.146
  type: ss
  port: 443
  udp: true
  password: NDRySIABARbErNIVsCNVkyYAHiBzhveT
  cipher: chacha20-ietf-poly1305
- name: _256 |26.63Mb
  server: 23.95.72.81
  type: ss
  port: 443
  udp: true
  password: UAMVtHm54uahd6SiN5WcD16rsPSdabPG
  cipher: chacha20-ietf-poly1305
- name: disney_NL |86.43Mb
  server: 109.71.246.210
  type: ss
  port: 56689
  udp: true
  password: YQCSKoCF3QazW8YlvDBWA4
  cipher: chacha20-ietf-poly1305
- name: _253 |171.34Mb
  server: 45.87.175.155
  type: ss
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: netflix_NL |179.97Mb
  server: 82.38.31.218
  type: ss
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: Relay_-ğŸ‡ºğŸ‡¸US_267 |50.96Mb
  server: 104.18.13.167
  type: vmess
  port: 443
  udp: true
  uuid: 24254866-770c-41b4-9404-3f50524f425b
  alterId: 0
  cipher: auto
  network: ws
  servername: 24254866-770c-41b4-9404-3f50524f425b.mihomo.baby
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /saoihgreg9384gh8934
    headers:
      Host: 24254866-770c-41b4-9404-3f50524f425b.mihomo.baby
- name: _252 |86.74Mb
  server: 185.156.110.92
  type: ss
  port: 443
  udp: true
  password: gXOXk2FJwsz9P6nXIICuDNOqF9gWX1dn
  cipher: chacha20-ietf-poly1305
- name: _262 |153.24Mb
  server: 82.38.31.176
  type: ss
  port: 8080
  udp: true
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: _249 |15.13Mb
  server: 213.159.67.124
  type: ss
  port: 443
  udp: true
  password: mbhqsStnFQT1cTZYCdsmkugGUC6GT6rp
  cipher: chacha20-ietf-poly1305
- name: netflix_IE |277.29Mb
  server: 18.203.224.78
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: _258 |10.13Mb
  server: 213.159.66.206
  type: ss
  port: 443
  udp: true
  password: pl2XtR0pzwknQOGwewbwXtPYDw1zn9Vu
  cipher: chacha20-ietf-poly1305
- name: Relay_-ğŸ‡ºğŸ‡¸US_268 |37.89Mb
  server: 38.14.99.179
  type: vmess
  port: 59807
  udp: true
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 64
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_-ğŸ‡ºğŸ‡¸US_269 |12.90Mb
  server: 82.198.246.97
  type: vmess
  port: 180
  uuid: d13fc2f5-3e05-4795-81eb-44143a09e552
  alterId: 0
  cipher: auto
  network: tcp
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_-ğŸ‡ºğŸ‡¸US_274 |37.37Mb
  server: 38.14.99.163
  type: vmess
  port: 59807
  udp: true
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 64
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: _266 |43.05Mb
  server: 45.15.126.19
  type: ss
  port: 443
  udp: true
  password: 6Ts2ZDTQAf3hkFoB8AFufDwsGrlF4e2t
  cipher: chacha20-ietf-poly1305
- name: _271 |155.61Mb
  server: 45.136.244.201
  type: vmess
  port: 49934
  uuid: 90afa47d-341a-497d-ae25-1d81258804d5
  alterId: 0
  cipher: auto
  network: tcp
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_-ğŸ‡ºğŸ‡¸US_287 |32.02Mb
  server: usiys.southbyte.xyz
  type: trojan
  port: 5897
  udp: true
  password: fg20mtCFHy
  sni: usiys.southbyte.xyz
  skip-cert-verify: true
- name: Relay_-ğŸ‡­ğŸ‡°HK_279 |10.44Mb
  server: 131.186.63.89
  type: vmess
  port: 11655
  uuid: 4bf075f5-4d5e-4d39-f5ab-b32a86250f0e
  alterId: 0
  cipher: auto
  network: ws
  servername: hk.nbee.pp.ua
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /aa
    headers:
      Host: hk.nbee.pp.ua
- name: Relay_-ğŸ‡ºğŸ‡¸US_297 |32.15Mb
  server: 141.193.213.199
  type: trojan
  port: 443
  udp: true
  password: a8a5b34d-fe46-487d-bd6a-d9f3101525fd
  sni: 26z68w0ecxbuyf89.ukgogo202511.top
  skip-cert-verify: true
  ws-opts:
    path: /images
    headers:
      Host: 26z68w0ecxbuyf89.ukgogo202511.top
  network: ws
- name: disney_DE |153.74Mb
  server: uk2-2.998998.best
  type: vmess
  port: 443
  udp: true
  uuid: 24254866-770c-41b4-9404-3f50524f425b
  alterId: 0
  cipher: auto
  network: ws
  servername: 24254866-770c-41b4-9404-3f50524f425b.placeunaorder.fun
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /logcatxiouerd34try9
    headers:
      Host: 24254866-770c-41b4-9404-3f50524f425b.placeunaorder.fun
- name: netflix_US |48.68Mb
  server: us19-25.998998.best
  type: vmess
  port: 443
  udp: true
  uuid: 24254866-770c-41b4-9404-3f50524f425b
  alterId: 0
  cipher: auto
  network: ws
  servername: 24254866-770c-41b4-9404-3f50524f425b.mihomo.baby
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /saoihgreg9384gh8934
    headers:
      Host: 24254866-770c-41b4-9404-3f50524f425b.mihomo.baby
- name: Relay_-ğŸ‡ºğŸ‡¸US_309 |47.82Mb
  server: 141.193.213.199
  type: trojan
  port: 443
  udp: true
  password: a544940a-2c1c-4723-96cc-d03053a95530
  sni: 26z68w0ecxbuyf89.ukgogo202511.top
  skip-cert-verify: true
  ws-opts:
    path: /images
    headers:
      Host: 26z68w0ecxbuyf89.ukgogo202511.top
  network: ws
- name: Relay_-ğŸ‡¯ğŸ‡µJP_312 |45.89Mb
  server: 141.193.213.60
  type: trojan
  port: 443
  udp: true
  password: 8b45d379-702f-41b3-a6b2-9c87a01dcd5c
  sni: a3t5vfl95f4d5d9y.catimecsgo.xyz
  skip-cert-verify: true
  ws-opts:
    path: /images
    headers:
      Host: a3t5vfl95f4d5d9y.catimecsgo.xyz
  network: ws
- name: Relay_-ğŸ‡­ğŸ‡°HK_276 |19.87Mb
  server: www.zhoubowen.vip
  type: vmess
  port: 443
  udp: true
  uuid: 71b2655e-07d9-4dad-a770-a2b08275142b
  alterId: 0
  cipher: auto
  network: ws
  servername: www.zhoubowen.vip
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /biutefor.icu
    headers:
      Host: www.zhoubowen.vip
- name: disney_RU |40.50Mb
  server: 37.18.14.33
  type: trojan
  port: 443
  udp: true
  password: Qzy7tgpRhu
  sni: m.vk.com
  skip-cert-verify: true
- name: Relay_-ğŸ‡¯ğŸ‡µJP_294 |11.54Mb
  server: 160.16.117.182
  type: trojan
  port: 3169
  password: 2cf6d686799e6fa95316394064f26c0a
  sni: www.nintendogames.net
- name: disney_netflix_FR |101.78Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 27092
  uuid: a0596ba6-72a3-4366-8992-77088da65bd8
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡§ğŸ‡·BR_316 |102.35Mb
  server: 38.180.16.86
  type: vmess
  country: ğŸ‡§ğŸ‡·BR
  port: 36236
  uuid: a58bc1a5-8c18-49ff-9453-c331b52f45dc
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡§ğŸ‡·BR_317 |102.79Mb
  server: 38.180.16.86
  type: vmess
  country: ğŸ‡§ğŸ‡·BR
  port: 36104
  uuid: E146A8CB-9D2F-449C-ADCA-8736FB
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_-ğŸ‡³ğŸ‡±NL_306 |18.61Mb
  server: 160.16.240.91
  type: trojan
  port: 4054
  password: 2cf6d686799e6fa95316394064f26c0a
  sni: www.nintendogames.net
- name: netflix_NL |193.84Mb
  server: 82.38.31.191
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_323 |161.25Mb
  server: 82.38.31.194
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: disney_HK |28.38Mb
  server: gd.bjnet2.com
  type: ss
  port: 36602
  udp: true
  password: 84d85af8-2807-4306-a701-f784676b77c3
  cipher: aes-128-gcm
  plugin: obfs
  plugin-opts:
    host: de5bdbffa87896a4b126f8b62150bb4e.baidu.com
    mode: http
- name: disney_US |26.24Mb
  server: gd.bjnet2.com
  type: ss
  port: 36608
  udp: true
  password: 84d85af8-2807-4306-a701-f784676b77c3
  cipher: aes-128-gcm
  plugin: obfs
  plugin-opts:
    host: de5bdbffa87896a4b126f8b62150bb4e.baidu.com
    mode: http
- name: ğŸ‡ºğŸ‡¸US_335 |52.30Mb
  server: 107.23.148.46
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡²ğŸ‡½MX_333 |42.11Mb
  server: 216.238.89.53
  type: vmess
  country: ğŸ‡²ğŸ‡½MX
  port: 57283
  uuid: 1a5aafc0-6482-451d-fe76-6875b7818579
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡¯ğŸ‡µJP_339 |55.15Mb
  server: t1.620720.xyz
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 8443
  uuid: 516d8a7a-3f0b-41d3-bad0-246116381516
  alterId: 0
  cipher: auto
  network: ws
  servername: t1.620720.xyz
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /
    headers:
      HOST: t1.620720.xyz
- name: ğŸ‡±ğŸ‡¹LT_332 |13.25Mb
  server: 45.87.175.166
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 443
  password: 1RWwXhwfAB5gAEozU4G2Pg
  cipher: chacha20-ietf-poly1305
- name: netflix_NL |155.35Mb
  server: 45.87.175.174
  type: ss
  country: ğŸ‡±ğŸ‡¹ LT
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: disney_US |36.45Mb
  server: 216.167.107.61
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 44805
  uuid: f7d62526-9e06-455e-82bd-241d368002e8
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡ºğŸ‡¸US_336 |27.21Mb
  server: 74.117.196.232
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 37934
  uuid: 12929592-a7bd-41eb-ab4d-d804f76c4ff9
  alterId: 0
  cipher: auto
  network: ws
  servername: imafake.locker
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /speedtest
    headers:
      HOST: imafake.locker
- name: ğŸ‡ºğŸ‡¸US_338 |36.81Mb
  server: 74.117.196.232
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 37934
  uuid: 9631096d-3032-4942-9446-bdf12665682b
  alterId: 0
  cipher: auto
  network: ws
  servername: imafake.locker
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /speedtest
    headers:
      HOST: imafake.locker
- name: ğŸ‡°ğŸ‡·KR_328 |10.11Mb
  server: 146.56.112.110
  type: vmess
  country: ğŸ‡°ğŸ‡·KR
  port: 8888
  uuid: e7c302f3-90d6-42dd-9d7d-94a3683a3707
  alterId: 0
  cipher: auto
  network: tcp
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_-ğŸ‡ºğŸ‡¸US_278 |71.45Mb
  server: v24.hdacd.com
  type: vmess
  port: 30824
  udp: true
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_US |13.77Mb
  server: cf.fovi.tk
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  uuid: bf67437e-6c90-45ca-abc2-c7240a5ce2aa
  alterId: 0
  cipher: auto
  network: ws
  servername: foxlux.fovi.tk
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /eisasqa
    headers:
      HOST: foxlux.fovi.tk
- name: ğŸ‡·ğŸ‡´RO_334 |159.38Mb
  server: 89.46.233.148
  type: ss
  country: ğŸ‡·ğŸ‡´RO
  port: 443
  password: XeGAcwaviWxXzg87AwvnE6gWbhHHGwwB
  cipher: chacha20-ietf-poly1305
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - _251 |51.50Mb
  - _254 |13.15Mb
  - _256 |26.63Mb
  - disney_NL |86.43Mb
  - _253 |171.34Mb
  - netflix_NL |179.97Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_267 |50.96Mb
  - _252 |86.74Mb
  - _262 |153.24Mb
  - _249 |15.13Mb
  - netflix_IE |277.29Mb
  - _258 |10.13Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_268 |37.89Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_269 |12.90Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_274 |37.37Mb
  - _266 |43.05Mb
  - _271 |155.61Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_287 |32.02Mb
  - Relay_-ğŸ‡­ğŸ‡°HK_279 |10.44Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_297 |32.15Mb
  - disney_DE |153.74Mb
  - netflix_US |48.68Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_309 |47.82Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_312 |45.89Mb
  - Relay_-ğŸ‡­ğŸ‡°HK_276 |19.87Mb
  - disney_RU |40.50Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_294 |11.54Mb
  - disney_netflix_FR |101.78Mb
  - ğŸ‡§ğŸ‡·BR_316 |102.35Mb
  - ğŸ‡§ğŸ‡·BR_317 |102.79Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_306 |18.61Mb
  - netflix_NL |193.84Mb
  - ğŸ‡¬ğŸ‡§GB_323 |161.25Mb
  - disney_HK |28.38Mb
  - disney_US |26.24Mb
  - ğŸ‡ºğŸ‡¸US_335 |52.30Mb
  - ğŸ‡²ğŸ‡½MX_333 |42.11Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡¯ğŸ‡µJP_339 |55.15Mb
  - ğŸ‡±ğŸ‡¹LT_332 |13.25Mb
  - netflix_NL |155.35Mb
  - disney_US |36.45Mb
  - ğŸ‡ºğŸ‡¸US_336 |27.21Mb
  - ğŸ‡ºğŸ‡¸US_338 |36.81Mb
  - ğŸ‡°ğŸ‡·KR_328 |10.11Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_278 |71.45Mb
  - disney_US |13.77Mb
  - ğŸ‡·ğŸ‡´RO_334 |159.38Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - _251 |51.50Mb
  - _254 |13.15Mb
  - _256 |26.63Mb
  - disney_NL |86.43Mb
  - _253 |171.34Mb
  - netflix_NL |179.97Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_267 |50.96Mb
  - _252 |86.74Mb
  - _262 |153.24Mb
  - _249 |15.13Mb
  - netflix_IE |277.29Mb
  - _258 |10.13Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_268 |37.89Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_269 |12.90Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_274 |37.37Mb
  - _266 |43.05Mb
  - _271 |155.61Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_287 |32.02Mb
  - Relay_-ğŸ‡­ğŸ‡°HK_279 |10.44Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_297 |32.15Mb
  - disney_DE |153.74Mb
  - netflix_US |48.68Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_309 |47.82Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_312 |45.89Mb
  - Relay_-ğŸ‡­ğŸ‡°HK_276 |19.87Mb
  - disney_RU |40.50Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_294 |11.54Mb
  - disney_netflix_FR |101.78Mb
  - ğŸ‡§ğŸ‡·BR_316 |102.35Mb
  - ğŸ‡§ğŸ‡·BR_317 |102.79Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_306 |18.61Mb
  - netflix_NL |193.84Mb
  - ğŸ‡¬ğŸ‡§GB_323 |161.25Mb
  - disney_HK |28.38Mb
  - disney_US |26.24Mb
  - ğŸ‡ºğŸ‡¸US_335 |52.30Mb
  - ğŸ‡²ğŸ‡½MX_333 |42.11Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡¯ğŸ‡µJP_339 |55.15Mb
  - ğŸ‡±ğŸ‡¹LT_332 |13.25Mb
  - netflix_NL |155.35Mb
  - disney_US |36.45Mb
  - ğŸ‡ºğŸ‡¸US_336 |27.21Mb
  - ğŸ‡ºğŸ‡¸US_338 |36.81Mb
  - ğŸ‡°ğŸ‡·KR_328 |10.11Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_278 |71.45Mb
  - disney_US |13.77Mb
  - ğŸ‡·ğŸ‡´RO_334 |159.38Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
