port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: _680 |435.28Mb
  server: 138.197.153.10
  type: ss
  country: ğŸ‡¨ğŸ‡¦CA
  port: 8080
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: ğŸ‡¦ğŸ‡ºAU_338 |10.10Mb
  server: 3.25.198.142
  type: ss
  country: ğŸ‡¦ğŸ‡ºAU
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡³ğŸ‡±NL_652 |10.16Mb
  server: 193.29.139.227
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 8080
  password: 4a2rfixophdjffa8KVA4Aa
  cipher: chacha20-ietf-poly1305
- name: _821 |10.50Mb
  server: 137.184.174.93
  type: ss
  country: ğŸ‡¨ğŸ‡¦CA
  port: 8080
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: Relay_ğŸ‡®ğŸ‡·IR-ğŸ‡³ğŸ‡±NL_643 |10.14Mb
  server: 151.242.251.144
  type: ss
  country: ğŸ‡®ğŸ‡·IR
  port: 8080
  password: o5osZg269v5zHpYjr1xY9s
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸ‡®ğŸ‡·IR-ğŸ‡³ğŸ‡±NL_641 |10.17Mb
  server: 151.242.251.137
  type: ss
  country: ğŸ‡®ğŸ‡·IR
  port: 8080
  password: 4a2rfixophdjffa8KVA4Aa
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¦ğŸ‡¹AT_537 |188.27Mb
  server: 151.236.11.221
  type: ss
  country: ğŸ‡¦ğŸ‡¹AT
  port: 8443
  password: kNAssqfNR8hhvm9rSSJvhq
  cipher: chacha20-ietf-poly1305
- name: _674 |200.54Mb
  server: 192.71.249.71
  type: ss
  country: ğŸ‡§ğŸ‡ªBE
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: Relay_ğŸ‡®ğŸ‡·IR-ğŸ‡³ğŸ‡±NL_642 |10.16Mb
  server: 151.242.251.131
  type: ss
  country: ğŸ‡®ğŸ‡·IR
  port: 8080
  password: o5osZg269v5zHpYjr1xY9s
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¦ğŸ‡ºAU_399 |10.09Mb
  server: 3.27.81.63
  type: ss
  country: ğŸ‡¦ğŸ‡ºAU
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡³ğŸ‡±NL_882 |10.05Mb
  server: 208.67.105.196
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 42029
  password: Fzf5vaXFs7oCY3Xb33aZ945xkhvFt2rrxdRBY9D3dQecNQKEXysBXb2eVPzDVb9iqM3iBhwJHEi5eWhzAXJXEP2vUwWCpZXD
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_568 |10.14Mb
  server: 45.87.175.164
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: 1RWwXhwfAB5gAEozU4G2Pg
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡«ğŸ‡·FR_565 |13.09Mb
  server: 83.147.216.70
  type: ss
  country: ğŸ‡«ğŸ‡·FR
  port: 64519
  password: w3TdzsHosPQjGAaLmo9lGQ
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸ‡®ğŸ‡·IR-ğŸ‡³ğŸ‡±NL_646 |10.18Mb
  server: 151.242.251.137
  type: ss
  country: ğŸ‡®ğŸ‡·IR
  port: 8080
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸ‡®ğŸ‡·IR-ğŸ‡³ğŸ‡±NL_639 |10.13Mb
  server: 151.242.251.153
  type: ss
  country: ğŸ‡®ğŸ‡·IR
  port: 8080
  password: 4a2rfixophdjffa8KVA4Aa
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸ‡®ğŸ‡·IR-ğŸ‡³ğŸ‡±NL_648 |10.13Mb
  server: 151.242.251.153
  type: ss
  country: ğŸ‡®ğŸ‡·IR
  port: 8080
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: _517 |12.03Mb
  server: 217.30.10.18
  type: ss
  country: ğŸ‡µğŸ‡±PL
  port: 9060
  password: ueLXVkvh4hckhErQ
  cipher: aes-256-cfb
- name: _638 |10.59Mb
  server: 172.105.199.111
  type: ss
  country: ğŸ‡¯ğŸ‡µJP
  port: 8080
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: ğŸ‡µğŸ‡±PL_606 |148.81Mb
  server: 217.30.10.70
  type: ss
  country: ğŸ‡µğŸ‡±PL
  port: 9032
  password: UWZQeLRWnkqgkseq
  cipher: aes-256-cfb
- name: ğŸ‡³ğŸ‡±NL_343 |10.12Mb
  server: 77.238.224.29
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 55702
  password: S2QudBxi0vRySw4YRLloPq
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_631 |221.74Mb
  server: 78.129.140.11
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: O3RSuJO9eedxV0a146FsxR
  cipher: chacha20-ietf-poly1305
- name: ' |10.03Mb'
  server: 8.217.209.82
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 3600
  uuid: d31a1f2f-b552-44fc-893a-6cf55fa2d4e3
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
  ws-opts:
    path: /arki?ed=2048
- name: Pool_ğŸ‡¬ğŸ‡§GB_767 |201.52Mb
  server: 64.176.184.129
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 1866
  password: oXGp1+ihlfKg826H
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸ‡®ğŸ‡·IR-ğŸ‡³ğŸ‡±NL_651 |10.13Mb
  server: 151.242.251.153
  type: ss
  country: ğŸ‡®ğŸ‡·IR
  port: 8080
  password: o5osZg269v5zHpYjr1xY9s
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¯ğŸ‡µJP_561 |10.28Mb
  server: 153.121.43.183
  type: ss
  country: ğŸ‡¯ğŸ‡µJP
  port: 10087
  password: '10086'
  cipher: aes-128-gcm
- name: _602 |10.52Mb
  server: 178.128.231.214
  type: ss
  country: ğŸ‡¨ğŸ‡¦CA
  port: 8080
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: Pool__494 |10.20Mb
  server: 79.127.233.170
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ' |97.11Mb'
  server: 43.154.249.143
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 27839
  uuid: 20aa3d37-e03a-4ea6-82b1-3ef868f3473d
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
  ws-opts:
    path: /arki?ed=2048
- name: _666 |159.08Mb
  server: 217.30.10.18
  type: ss
  country: ğŸ‡µğŸ‡±PL
  port: 9025
  password: XPtzA9sCug3SPR4c
  cipher: aes-256-cfb
- name: _619 |41.94Mb
  server: 217.30.10.18
  type: ss
  country: ğŸ‡µğŸ‡±PL
  port: 9033
  password: UTJA57ypk2XKQpnm
  cipher: aes-256-cfb
- name: ğŸ‡µğŸ‡¹PT_612 |43.32Mb
  server: 185.231.233.173
  type: ss
  country: ğŸ‡µğŸ‡¹PT
  port: 990
  password: f8f7aCzcPKbsF8p3
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡«ğŸ‡·FR_759 |14.15Mb
  server: 83.147.216.70
  type: ss
  country: ğŸ‡«ğŸ‡·FR
  port: 64519
  password: kmgk1sWY4Fh4dw9bxk2NBG
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_610 |16.66Mb
  server: 45.87.175.35
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡®ğŸ‡ªIE_318 |10.16Mb
  server: 54.216.80.211
  type: ss
  country: ğŸ‡®ğŸ‡ªIE
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡¬ğŸ‡§GB_745 |10.21Mb
  server: 89.185.84.185
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: XsMiWpupGob8IouVwYW5WC
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡©ğŸ‡ªDE_552 |10.07Mb
  server: de15.giamping.com
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 8080
  password: 42000e02-6b4d-46ad-a572-80db7db2a9ce
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¦ğŸ‡ºAU_403 |10.05Mb
  server: 3.27.47.19
  type: ss
  country: ğŸ‡¦ğŸ‡ºAU
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: Pool_ğŸ‡­ğŸ‡°HK_505 |390.00Mb
  server: 150.107.46.21
  type: ssr
  country: ğŸ‡­ğŸ‡°HK
  port: 8083
  password: iFqnzSscN
  cipher: aes-256-cfb
  protocol: origin
  obfs: tls1.2_ticket_auth
- name: _407 |10.15Mb
  server: 193.29.139.179
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 8080
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡³ğŸ‡±NL_648 |10.17Mb
  server: 193.29.139.233
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 8080
  password: QCXDxuDlTTMD7jtgHUjIoj
  cipher: chacha20-ietf-poly1305
- name: _564 |10.44Mb
  server: 147.78.1.230
  type: ss
  country: ğŸ‡²ğŸ‡½MX
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: _642 |148.18Mb
  server: 217.30.10.18
  type: ss
  country: ğŸ‡µğŸ‡±PL
  port: 9006
  password: FAdUvMJUq5vDgKEq
  cipher: aes-256-cfb
- name: ğŸ‡³ğŸ‡±NL_626 |10.19Mb
  server: 193.29.139.173
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 8080
  password: 4a2rfixophdjffa8KVA4Aa
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡«ğŸ‡·FR_806 |14.46Mb
  server: 83.147.216.70
  type: ss
  country: ğŸ‡«ğŸ‡·FR
  port: 64519
  password: MVAZ6nsCGVWhTzcRIUD85f
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡§ğŸ‡·BR_358 |122.03Mb
  server: 38.54.57.90
  type: ss
  country: ğŸ‡§ğŸ‡·BR
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ğŸ‡³ğŸ‡±NL_674 |10.18Mb
  server: 193.29.139.144
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 8080
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡³ğŸ‡±NL_647 |10.15Mb
  server: 193.29.139.209
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 8080
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_531 |10.11Mb
  server: 45.87.175.181
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: _616 |13.52Mb
  server: 217.30.10.18
  type: ss
  country: ğŸ‡µğŸ‡±PL
  port: 9046
  password: NvS8N4Vf8qAGPSCL
  cipher: aes-256-cfb
- name: _645 |146.95Mb
  server: 217.30.10.70
  type: ss
  country: ğŸ‡µğŸ‡±PL
  port: 9097
  password: Sn5B7jTqr76aCJT8
  cipher: aes-256-cfb
- name: _687 |200.66Mb
  server: 146.70.23.32
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: _399 |10.22Mb
  server: 109.201.152.181
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 443
  password: shadowsocks
  cipher: aes-128-cfb
- name: ğŸ‡«ğŸ‡·FR_527 |14.53Mb
  server: 83.147.216.70
  type: ss
  country: ğŸ‡«ğŸ‡·FR
  port: 64519
  password: MPFzoWp2cXcJ2xrlOGleaf
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_603 |10.10Mb
  server: 45.87.175.154
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: 1RWwXhwfAB5gAEozU4G2Pg
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡«ğŸ‡·FR_477 |12.85Mb
  server: 83.147.216.70
  type: ss
  country: ğŸ‡«ğŸ‡·FR
  port: 64519
  password: YXgS8ComTam7qoesPlzlMo
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡«ğŸ‡·FR_799 |14.53Mb
  server: 83.147.216.70
  type: ss
  country: ğŸ‡«ğŸ‡·FR
  port: 64519
  password: KaKeuUdiSZJ1vl2jU8GnfY
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_616 |11.39Mb
  server: 45.87.175.69
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡«ğŸ‡·FR_700 |13.01Mb
  server: 83.147.216.70
  type: ss
  country: ğŸ‡«ğŸ‡·FR
  port: 64519
  password: 9z4XoS0TfzxNsSqBVAWt7N
  cipher: chacha20-ietf-poly1305
- name: _290 |10.17Mb
  server: 151.242.251.131
  type: ss
  country: ğŸ‡®ğŸ‡·IR
  port: 8080
  password: QCXDxuDlTTMD7jtgHUjIoj
  cipher: chacha20-ietf-poly1305
- name: _418 |10.50Mb
  server: 160.16.123.124
  type: ss
  country: ğŸ‡¯ğŸ‡µJP
  port: 10087
  password: '10086'
  cipher: aes-128-gcm
- name: ğŸ‡«ğŸ‡·FR_970 |10.12Mb
  server: 83.147.216.70
  type: ss
  country: ğŸ‡«ğŸ‡·FR
  port: 64519
  password: w9DF9RTnarCQ0crI5rykEU
  cipher: chacha20-ietf-poly1305
- name: _683 |12.53Mb
  server: 217.30.10.70
  type: ss
  country: ğŸ‡µğŸ‡±PL
  port: 9025
  password: XPtzA9sCug3SPR4c
  cipher: aes-256-cfb
- name: _652 |78.10Mb
  server: 134.209.147.198
  type: ss
  country: ğŸ‡®ğŸ‡³IN
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: _276 |172.21Mb
  server: 185.192.124.188
  type: ss
  country: ğŸ‡§ğŸ‡·BR
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: _232 |77.48Mb
  server: 185.231.233.112
  type: ss
  country: ğŸ‡µğŸ‡¹PT
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - _680 |435.28Mb
  - ğŸ‡¦ğŸ‡ºAU_338 |10.10Mb
  - ğŸ‡³ğŸ‡±NL_652 |10.16Mb
  - _821 |10.50Mb
  - Relay_ğŸ‡®ğŸ‡·IR-ğŸ‡³ğŸ‡±NL_643 |10.14Mb
  - Relay_ğŸ‡®ğŸ‡·IR-ğŸ‡³ğŸ‡±NL_641 |10.17Mb
  - ğŸ‡¦ğŸ‡¹AT_537 |188.27Mb
  - _674 |200.54Mb
  - Relay_ğŸ‡®ğŸ‡·IR-ğŸ‡³ğŸ‡±NL_642 |10.16Mb
  - ğŸ‡¦ğŸ‡ºAU_399 |10.09Mb
  - ğŸ‡³ğŸ‡±NL_882 |10.05Mb
  - ğŸ‡±ğŸ‡¹LT_568 |10.14Mb
  - ğŸ‡«ğŸ‡·FR_565 |13.09Mb
  - Relay_ğŸ‡®ğŸ‡·IR-ğŸ‡³ğŸ‡±NL_646 |10.18Mb
  - Relay_ğŸ‡®ğŸ‡·IR-ğŸ‡³ğŸ‡±NL_639 |10.13Mb
  - Relay_ğŸ‡®ğŸ‡·IR-ğŸ‡³ğŸ‡±NL_648 |10.13Mb
  - _517 |12.03Mb
  - _638 |10.59Mb
  - ğŸ‡µğŸ‡±PL_606 |148.81Mb
  - ğŸ‡³ğŸ‡±NL_343 |10.12Mb
  - ğŸ‡¬ğŸ‡§GB_631 |221.74Mb
  - ' |10.03Mb'
  - Pool_ğŸ‡¬ğŸ‡§GB_767 |201.52Mb
  - Relay_ğŸ‡®ğŸ‡·IR-ğŸ‡³ğŸ‡±NL_651 |10.13Mb
  - ğŸ‡¯ğŸ‡µJP_561 |10.28Mb
  - _602 |10.52Mb
  - Pool__494 |10.20Mb
  - ' |97.11Mb'
  - _666 |159.08Mb
  - _619 |41.94Mb
  - ğŸ‡µğŸ‡¹PT_612 |43.32Mb
  - ğŸ‡«ğŸ‡·FR_759 |14.15Mb
  - ğŸ‡±ğŸ‡¹LT_610 |16.66Mb
  - ğŸ‡®ğŸ‡ªIE_318 |10.16Mb
  - ğŸ‡¬ğŸ‡§GB_745 |10.21Mb
  - ğŸ‡©ğŸ‡ªDE_552 |10.07Mb
  - ğŸ‡¦ğŸ‡ºAU_403 |10.05Mb
  - Pool_ğŸ‡­ğŸ‡°HK_505 |390.00Mb
  - _407 |10.15Mb
  - ğŸ‡³ğŸ‡±NL_648 |10.17Mb
  - _564 |10.44Mb
  - _642 |148.18Mb
  - ğŸ‡³ğŸ‡±NL_626 |10.19Mb
  - ğŸ‡«ğŸ‡·FR_806 |14.46Mb
  - ğŸ‡§ğŸ‡·BR_358 |122.03Mb
  - ğŸ‡³ğŸ‡±NL_674 |10.18Mb
  - ğŸ‡³ğŸ‡±NL_647 |10.15Mb
  - ğŸ‡±ğŸ‡¹LT_531 |10.11Mb
  - _616 |13.52Mb
  - _645 |146.95Mb
  - _687 |200.66Mb
  - _399 |10.22Mb
  - ğŸ‡«ğŸ‡·FR_527 |14.53Mb
  - ğŸ‡±ğŸ‡¹LT_603 |10.10Mb
  - ğŸ‡«ğŸ‡·FR_477 |12.85Mb
  - ğŸ‡«ğŸ‡·FR_799 |14.53Mb
  - ğŸ‡±ğŸ‡¹LT_616 |11.39Mb
  - ğŸ‡«ğŸ‡·FR_700 |13.01Mb
  - _290 |10.17Mb
  - _418 |10.50Mb
  - ğŸ‡«ğŸ‡·FR_970 |10.12Mb
  - _683 |12.53Mb
  - _652 |78.10Mb
  - _276 |172.21Mb
  - _232 |77.48Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - _680 |435.28Mb
  - ğŸ‡¦ğŸ‡ºAU_338 |10.10Mb
  - ğŸ‡³ğŸ‡±NL_652 |10.16Mb
  - _821 |10.50Mb
  - Relay_ğŸ‡®ğŸ‡·IR-ğŸ‡³ğŸ‡±NL_643 |10.14Mb
  - Relay_ğŸ‡®ğŸ‡·IR-ğŸ‡³ğŸ‡±NL_641 |10.17Mb
  - ğŸ‡¦ğŸ‡¹AT_537 |188.27Mb
  - _674 |200.54Mb
  - Relay_ğŸ‡®ğŸ‡·IR-ğŸ‡³ğŸ‡±NL_642 |10.16Mb
  - ğŸ‡¦ğŸ‡ºAU_399 |10.09Mb
  - ğŸ‡³ğŸ‡±NL_882 |10.05Mb
  - ğŸ‡±ğŸ‡¹LT_568 |10.14Mb
  - ğŸ‡«ğŸ‡·FR_565 |13.09Mb
  - Relay_ğŸ‡®ğŸ‡·IR-ğŸ‡³ğŸ‡±NL_646 |10.18Mb
  - Relay_ğŸ‡®ğŸ‡·IR-ğŸ‡³ğŸ‡±NL_639 |10.13Mb
  - Relay_ğŸ‡®ğŸ‡·IR-ğŸ‡³ğŸ‡±NL_648 |10.13Mb
  - _517 |12.03Mb
  - _638 |10.59Mb
  - ğŸ‡µğŸ‡±PL_606 |148.81Mb
  - ğŸ‡³ğŸ‡±NL_343 |10.12Mb
  - ğŸ‡¬ğŸ‡§GB_631 |221.74Mb
  - ' |10.03Mb'
  - Pool_ğŸ‡¬ğŸ‡§GB_767 |201.52Mb
  - Relay_ğŸ‡®ğŸ‡·IR-ğŸ‡³ğŸ‡±NL_651 |10.13Mb
  - ğŸ‡¯ğŸ‡µJP_561 |10.28Mb
  - _602 |10.52Mb
  - Pool__494 |10.20Mb
  - ' |97.11Mb'
  - _666 |159.08Mb
  - _619 |41.94Mb
  - ğŸ‡µğŸ‡¹PT_612 |43.32Mb
  - ğŸ‡«ğŸ‡·FR_759 |14.15Mb
  - ğŸ‡±ğŸ‡¹LT_610 |16.66Mb
  - ğŸ‡®ğŸ‡ªIE_318 |10.16Mb
  - ğŸ‡¬ğŸ‡§GB_745 |10.21Mb
  - ğŸ‡©ğŸ‡ªDE_552 |10.07Mb
  - ğŸ‡¦ğŸ‡ºAU_403 |10.05Mb
  - Pool_ğŸ‡­ğŸ‡°HK_505 |390.00Mb
  - _407 |10.15Mb
  - ğŸ‡³ğŸ‡±NL_648 |10.17Mb
  - _564 |10.44Mb
  - _642 |148.18Mb
  - ğŸ‡³ğŸ‡±NL_626 |10.19Mb
  - ğŸ‡«ğŸ‡·FR_806 |14.46Mb
  - ğŸ‡§ğŸ‡·BR_358 |122.03Mb
  - ğŸ‡³ğŸ‡±NL_674 |10.18Mb
  - ğŸ‡³ğŸ‡±NL_647 |10.15Mb
  - ğŸ‡±ğŸ‡¹LT_531 |10.11Mb
  - _616 |13.52Mb
  - _645 |146.95Mb
  - _687 |200.66Mb
  - _399 |10.22Mb
  - ğŸ‡«ğŸ‡·FR_527 |14.53Mb
  - ğŸ‡±ğŸ‡¹LT_603 |10.10Mb
  - ğŸ‡«ğŸ‡·FR_477 |12.85Mb
  - ğŸ‡«ğŸ‡·FR_799 |14.53Mb
  - ğŸ‡±ğŸ‡¹LT_616 |11.39Mb
  - ğŸ‡«ğŸ‡·FR_700 |13.01Mb
  - _290 |10.17Mb
  - _418 |10.50Mb
  - ğŸ‡«ğŸ‡·FR_970 |10.12Mb
  - _683 |12.53Mb
  - _652 |78.10Mb
  - _276 |172.21Mb
  - _232 |77.48Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
