port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: _174 |62.95Mb
  server: 54.144.64.227
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: disney_netflix_US |61.64Mb
  server: 23.22.182.151
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: _172 |64.05Mb
  server: 54.227.38.247
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: _175 |67.01Mb
  server: 184.72.124.41
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: disney_netflix_US |61.39Mb
  server: 13.222.155.147
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: _188 |68.11Mb
  server: 98.89.32.62
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: disney_netflix_US |64.57Mb
  server: 98.81.59.20
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: disney_netflix_US |62.75Mb
  server: 13.218.107.141
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: disney_netflix_US |62.24Mb
  server: 50.19.46.248
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: netflix_IE |351.57Mb
  server: 54.246.35.116
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: _183 |282.65Mb
  server: 34.251.86.159
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: _177 |150.85Mb
  server: 13.61.180.46
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: _178 |159.06Mb
  server: 13.61.13.231
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: disney_netflix_US |64.77Mb
  server: 3.89.113.22
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: disney_netflix_US |59.61Mb
  server: 54.159.62.233
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: disney_netflix_US |64.49Mb
  server: 3.93.196.82
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: _192 |353.42Mb
  server: 3.250.105.240
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: netflix_IE |308.93Mb
  server: 3.253.99.197
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: _216 |31.17Mb
  server: 216.238.86.158
  type: vmess
  port: 34460
  udp: true
  uuid: 90be214d-048c-4ea2-a602-b8e4d4e51e36
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _194 |167.77Mb
  server: 51.20.125.235
  type: ss
  port: 443
  udp: true
  password: amazonskr05
  cipher: aes-256-cfb
- name: _220 |11.28Mb
  server: 15.235.41.200
  type: vmess
  port: 80
  uuid: 58fe1542-5290-40ad-815a-77707a81afe5
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /IOebhLMhl1CTbFHbL95myfRX2
- name: netflix_DE |260.45Mb
  server: 85.195.101.122
  type: vmess
  port: 40878
  uuid: f3d4167e-b15e-4e46-82e9-9286ef93fda7
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _215 |23.18Mb
  server: 8.210.184.105
  type: vmess
  port: 40374
  udp: true
  uuid: 36b76373-7a4f-4669-9113-7d247bcf2704
  alterId: 0
  cipher: auto
  network: http
  http-opts:
    method: GET
    path:
    - /
  h2-opts: {}
- name: _212 |42.26Mb
  server: 89.31.120.192
  type: vmess
  port: 443
  uuid: 44537595-9ccc-4b83-8936-5f9ad3229019
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: disney_US |41.34Mb
  server: 165.140.216.141
  type: vmess
  port: 443
  uuid: e7d72a8d-26f2-4b54-b366-0c43e0bcba7d
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: disney_netflix_US |42.13Mb
  server: 163.192.49.195
  type: vmess
  port: 443
  uuid: bcb7c581-3c95-4569-a4e7-918141e91ea3
  alterId: 0
  cipher: auto
  network: http
  http-opts:
    path:
    - /
    headers:
      Host:
      - a.189.cn
  h2-opts: {}
- name: Relay_-ğŸ‡ºğŸ‡¸US_238 |31.20Mb
  server: 69.84.182.18
  type: trojan
  port: 8443
  udp: true
  password: a431c229-a467-4dfa-9e89-48e0f26c844b
  sni: cdn-node-oss-62.anycdn.de
  ws-opts:
    path: /profile/us2
    headers:
      Host: cdn-node-oss-62.anycdn.de
  network: ws
- name: _224 |25.62Mb
  server: 8.218.105.196
  type: vmess
  port: 52752
  uuid: 925bdbf5-72be-4437-bebf-441c61089f6b
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: netflix_SE |162.27Mb
  server: 70.34.218.149
  type: trojan
  port: 11930
  password: BaeSzHdfJIR13l67
  sni: softpillow.silentrocket.click
- name: _226 |10.84Mb
  server: 130.162.152.253
  type: vmess
  port: 56867
  uuid: 5206bb9f-2cbc-44ac-de2a-471439a23707
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: disney_GB |266.12Mb
  server: 172.67.134.185
  type: trojan
  port: 443
  udp: true
  password: POORIARED
  sni: reDfRee8.REDFree8.ir
  ws-opts:
    path: /eyJqdW5rIjoiVUl6eXhLZkkwUTJ3ZzkiLCJwcm90b2NvbCI6InRyIiwibW9kZSI6InByb3h5aXAiLCJwYW5lbElQcyI6W119?ed=2560
    headers:
      Host: reDfRee8.REDFree8.ir
  network: ws
- name: _229 |12.49Mb
  server: 54.206.192.9
  type: vmess
  port: 16407
  uuid: 08f45028-1db6-4e93-bf51-d344b6c71e19
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _241 |11.05Mb
  server: 160.16.229.223
  type: trojan
  port: 3093
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: disney_SG |18.20Mb
  server: 165.154.195.38
  type: vmess
  port: 35034
  uuid: 959a8caf-4cea-43d0-a548-3628e7ddfafc
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: _244 |10.15Mb
  server: 153.121.39.240
  type: trojan
  port: 4054
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¯ğŸ‡µJP_203 |12.01Mb
  server: r7k75-g06.jp01-nn-vm0.entry.fr0528.art
  type: vmess
  port: 21586
  udp: true
  uuid: 0ffb3763-ac35-3e8b-bf18-944d1c1b03dd
  alterId: 1
  cipher: auto
  servername: r7k75-g06.jp01-nn-vm0.entry.fr0528.art
  http-opts: {}
  h2-opts: {}
  tls: true
- name: disney_FR |164.15Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 27092
  uuid: a0596ba6-72a3-4366-8992-77088da65bd8
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: _257 |46.63Mb
  server: 160.16.151.196
  type: trojan
  port: 4054
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: disney_FR |187.06Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 40433
  uuid: d8fd8955-78db-49ba-d86f-3e4729f6ac4d
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: _169 |18.08Mb
  server: 94.198.220.183
  type: ss
  port: 64674
  udp: true
  password: s8LbJCgUiGXeCKVc63tHJP
  cipher: chacha20-ietf-poly1305
- name: _259 |52.22Mb
  server: 160.16.236.32
  type: trojan
  port: 4054
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¸ğŸ‡¬SG_268 |10.05Mb
  server: 160.16.150.76
  type: trojan
  port: 3145
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: ğŸ‡ºğŸ‡¸US_290 |51.73Mb
  server: 18.207.122.59
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: Relay_-ğŸ‡¯ğŸ‡µJP_218 |23.96Mb
  server: l7140-g06.jp02-e3-vm0.entry.fr0528.art
  type: vmess
  port: 11778
  udp: true
  uuid: 0ffb3763-ac35-3e8b-bf18-944d1c1b03dd
  alterId: 1
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: ğŸ‡²ğŸ‡½MX_288 |183.28Mb
  server: 216.238.87.47
  type: vmess
  country: ğŸ‡²ğŸ‡½MX
  port: 27502
  uuid: b8155ce4-7e08-4c40-800f-8671312b7124
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡¬ğŸ‡§GB_279 |233.05Mb
  server: 82.38.31.191
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_280 |238.31Mb
  server: 82.38.31.194
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_281 |244.52Mb
  server: 82.38.31.217
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_291 |64.11Mb
  server: 45.12.136.170
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: l668XHPejoSNNuD66BYzyehaCpZexiF7
  cipher: chacha20-ietf-poly1305
- name: disney_KZ |10.97Mb
  server: 31.3.209.183
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 28212
  password: Kmn7dHPw5wNfkqQMPcGWQA
  cipher: chacha20-ietf-poly1305
- name: disney_PT |147.68Mb
  server: 185.231.233.112
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - _174 |62.95Mb
  - disney_netflix_US |61.64Mb
  - _172 |64.05Mb
  - _175 |67.01Mb
  - disney_netflix_US |61.39Mb
  - _188 |68.11Mb
  - disney_netflix_US |64.57Mb
  - disney_netflix_US |62.75Mb
  - disney_netflix_US |62.24Mb
  - netflix_IE |351.57Mb
  - _183 |282.65Mb
  - _177 |150.85Mb
  - _178 |159.06Mb
  - disney_netflix_US |64.77Mb
  - disney_netflix_US |59.61Mb
  - disney_netflix_US |64.49Mb
  - _192 |353.42Mb
  - netflix_IE |308.93Mb
  - _216 |31.17Mb
  - _194 |167.77Mb
  - _220 |11.28Mb
  - netflix_DE |260.45Mb
  - _215 |23.18Mb
  - _212 |42.26Mb
  - disney_US |41.34Mb
  - disney_netflix_US |42.13Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_238 |31.20Mb
  - _224 |25.62Mb
  - netflix_SE |162.27Mb
  - _226 |10.84Mb
  - disney_GB |266.12Mb
  - _229 |12.49Mb
  - _241 |11.05Mb
  - disney_SG |18.20Mb
  - _244 |10.15Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_203 |12.01Mb
  - disney_FR |164.15Mb
  - _257 |46.63Mb
  - disney_FR |187.06Mb
  - _169 |18.08Mb
  - _259 |52.22Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_268 |10.05Mb
  - ğŸ‡ºğŸ‡¸US_290 |51.73Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_218 |23.96Mb
  - ğŸ‡²ğŸ‡½MX_288 |183.28Mb
  - ğŸ‡¬ğŸ‡§GB_279 |233.05Mb
  - ğŸ‡¬ğŸ‡§GB_280 |238.31Mb
  - ğŸ‡¬ğŸ‡§GB_281 |244.52Mb
  - ğŸ‡ºğŸ‡¸US_291 |64.11Mb
  - disney_KZ |10.97Mb
  - disney_PT |147.68Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - _174 |62.95Mb
  - disney_netflix_US |61.64Mb
  - _172 |64.05Mb
  - _175 |67.01Mb
  - disney_netflix_US |61.39Mb
  - _188 |68.11Mb
  - disney_netflix_US |64.57Mb
  - disney_netflix_US |62.75Mb
  - disney_netflix_US |62.24Mb
  - netflix_IE |351.57Mb
  - _183 |282.65Mb
  - _177 |150.85Mb
  - _178 |159.06Mb
  - disney_netflix_US |64.77Mb
  - disney_netflix_US |59.61Mb
  - disney_netflix_US |64.49Mb
  - _192 |353.42Mb
  - netflix_IE |308.93Mb
  - _216 |31.17Mb
  - _194 |167.77Mb
  - _220 |11.28Mb
  - netflix_DE |260.45Mb
  - _215 |23.18Mb
  - _212 |42.26Mb
  - disney_US |41.34Mb
  - disney_netflix_US |42.13Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_238 |31.20Mb
  - _224 |25.62Mb
  - netflix_SE |162.27Mb
  - _226 |10.84Mb
  - disney_GB |266.12Mb
  - _229 |12.49Mb
  - _241 |11.05Mb
  - disney_SG |18.20Mb
  - _244 |10.15Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_203 |12.01Mb
  - disney_FR |164.15Mb
  - _257 |46.63Mb
  - disney_FR |187.06Mb
  - _169 |18.08Mb
  - _259 |52.22Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_268 |10.05Mb
  - ğŸ‡ºğŸ‡¸US_290 |51.73Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_218 |23.96Mb
  - ğŸ‡²ğŸ‡½MX_288 |183.28Mb
  - ğŸ‡¬ğŸ‡§GB_279 |233.05Mb
  - ğŸ‡¬ğŸ‡§GB_280 |238.31Mb
  - ğŸ‡¬ğŸ‡§GB_281 |244.52Mb
  - ğŸ‡ºğŸ‡¸US_291 |64.11Mb
  - disney_KZ |10.97Mb
  - disney_PT |147.68Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
