port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: ğŸ‡¨ğŸ‡¦CA_414 |16.31Mb
  server: 138.197.153.10
  type: ss
  country: ğŸ‡¨ğŸ‡¦CA
  port: 8080
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: _390 |10.43Mb
  server: 192.71.249.108
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _394 |30.30Mb
  server: 176.126.83.158
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _388 |30.25Mb
  server: 37.143.129.98
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡«ğŸ‡·FR_436 |154.05Mb
  server: 83.147.216.70
  type: ss
  country: ğŸ‡«ğŸ‡·FR
  port: 64519
  password: WmDhVSiDij7R2XROr3Cm55
  cipher: chacha20-ietf-poly1305
- name: _382 |18.59Mb
  server: 38.54.59.180
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡«ğŸ‡·FR_439 |144.49Mb
  server: 83.147.216.70
  type: ss
  country: ğŸ‡«ğŸ‡·FR
  port: 64519
  password: BJ5nDZTulmYznHvHXhS6Z3
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡«ğŸ‡·FR_442 |10.10Mb
  server: 83.147.216.70
  type: ss
  country: ğŸ‡«ğŸ‡·FR
  port: 64519
  password: KaKeuUdiSZJ1vl2jU8GnfY
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¦ğŸ‡ºAU_401 |13.54Mb
  server: 3.25.225.79
  type: ss
  country: ğŸ‡¦ğŸ‡ºAU
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: Pool_ğŸ‡¬ğŸ‡§GB_462 |20.47Mb
  server: 79.127.233.170
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ğŸ‡«ğŸ‡·FR_443 |136.85Mb
  server: 83.147.216.70
  type: ss
  country: ğŸ‡«ğŸ‡·FR
  port: 64519
  password: 0NLl8N1SbQnJTF0XSftoEQ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡«ğŸ‡·FR_444 |124.63Mb
  server: 83.147.216.70
  type: ss
  country: ğŸ‡«ğŸ‡·FR
  port: 64519
  password: rOQrWhz7otxOrPBC6uHd3F
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡«ğŸ‡·FR_447 |133.92Mb
  server: 83.147.216.70
  type: ss
  country: ğŸ‡«ğŸ‡·FR
  port: 64519
  password: LCL2yAP1iPOvAEe8dWe2h1
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡«ğŸ‡·FR_448 |143.13Mb
  server: 83.147.216.70
  type: ss
  country: ğŸ‡«ğŸ‡·FR
  port: 64519
  password: YcFXLOkdEY2YKV662wBbjn
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡«ğŸ‡·FR_452 |127.86Mb
  server: 83.147.216.70
  type: ss
  country: ğŸ‡«ğŸ‡·FR
  port: 64519
  password: PSmqa9uK9Oo1eivPyXiAH8
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡«ğŸ‡·FR_454 |34.55Mb
  server: 83.147.216.70
  type: ss
  country: ğŸ‡«ğŸ‡·FR
  port: 64519
  password: MPFzoWp2cXcJ2xrlOGleaf
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_468 |10.86Mb
  server: 64.137.109.212
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 44884
  password: 2DGq3jvVRg5n3CcxmysGK2kmrgJeSNof12A76cZvVxqPpetyC1XEciCFufq5xKvRWGGnKVembpThuUSQhbZ7GMsZY4UVxEBw
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡®ğŸ‡·IR_508 |11.28Mb
  server: 151.242.251.147
  type: ss
  country: ğŸ‡®ğŸ‡·IR
  port: 8080
  password: QCXDxuDlTTMD7jtgHUjIoj
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸ‡®ğŸ‡·IR-ğŸ‡³ğŸ‡±NL_512 |10.54Mb
  server: 151.242.251.153
  type: ss
  country: ğŸ‡®ğŸ‡·IR
  port: 8080
  password: 4a2rfixophdjffa8KVA4Aa
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_523 |11.20Mb
  server: 45.87.175.199
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¯ğŸ‡µJP_516 |32.28Mb
  server: 153.121.51.214
  type: ss
  country: ğŸ‡¯ğŸ‡µJP
  port: 10087
  password: '10086'
  cipher: aes-128-gcm
- name: ğŸ‡±ğŸ‡¹LT_533 |12.01Mb
  server: 45.87.175.181
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_537 |11.81Mb
  server: 45.87.175.181
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: 4a2rfixophdjffa8KVA4Aa
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_539 |10.17Mb
  server: 45.87.175.171
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: QCXDxuDlTTMD7jtgHUjIoj
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡®ğŸ‡³IN_477 |40.88Mb
  server: 13.126.253.30
  type: ss
  country: ğŸ‡®ğŸ‡³IN
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡®ğŸ‡³IN_478 |16.84Mb
  server: 13.233.190.89
  type: ss
  country: ğŸ‡®ğŸ‡³IN
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡³ğŸ‡±NL_547 |14.69Mb
  server: 79.127.227.53
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ğŸ‡³ğŸ‡±NL_551 |10.03Mb
  server: 193.29.139.157
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 8080
  password: QCXDxuDlTTMD7jtgHUjIoj
  cipher: chacha20-ietf-poly1305
- name: Pool_ğŸ‡­ğŸ‡°HK_470 |634.00Mb
  server: 150.107.46.21
  type: ssr
  country: ğŸ‡­ğŸ‡°HK
  port: 8083
  password: iFqnzSscN
  cipher: aes-256-cfb
  protocol: origin
  obfs: tls1.2_ticket_auth
- name: ğŸ‡µğŸ‡ªPE_563 |39.22Mb
  server: 185.47.252.251
  type: ss
  country: ğŸ‡µğŸ‡ªPE
  port: 990
  password: f8f7aCzcPKbsF8p3
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡µğŸ‡±PL_574 |149.42Mb
  server: 217.30.10.70
  type: ss
  country: ğŸ‡µğŸ‡±PL
  port: 9015
  password: ZpNDDKRu9MagNvaf
  cipher: aes-256-cfb
- name: ğŸ‡µğŸ‡±PL_580 |11.54Mb
  server: 217.30.10.18
  type: ss
  country: ğŸ‡µğŸ‡±PL
  port: 9006
  password: FAdUvMJUq5vDgKEq
  cipher: aes-256-cfb
- name: ğŸ‡µğŸ‡±PL_586 |11.16Mb
  server: 217.30.10.18
  type: ss
  country: ğŸ‡µğŸ‡±PL
  port: 9097
  password: Sn5B7jTqr76aCJT8
  cipher: aes-256-cfb
- name: ğŸ‡µğŸ‡±PL_587 |11.29Mb
  server: 217.30.10.70
  type: ss
  country: ğŸ‡µğŸ‡±PL
  port: 9027
  password: EXN3S3eQpjE7EJu8
  cipher: aes-256-cfb
- name: ğŸ‡·ğŸ‡ºRU_593 |17.61Mb
  server: 95.163.176.37
  type: ss
  country: ğŸ‡·ğŸ‡ºRU
  port: 8506
  password: eUh4lSpi7nOYj0vSrqLUh0
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_632 |42.90Mb
  server: 64.74.163.130
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 990
  password: f8f7aCzcPKbsF8p3
  cipher: chacha20-ietf-poly1305
- name: disney_PY |20.96Mb
  server: 38.165.233.18
  type: ss
  country: ğŸ‡µğŸ‡¾PY
  port: 990
  password: f8f7aCzcPKbsF8p3
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡·ğŸ‡ºRU_595 |10.75Mb
  server: 95.163.176.37
  type: ss
  country: ğŸ‡·ğŸ‡ºRU
  port: 8506
  password: n4J9KuWgBBXPBoDn0SdprD
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡·ğŸ‡ºRU_597 |12.49Mb
  server: 95.163.176.37
  type: ss
  country: ğŸ‡·ğŸ‡ºRU
  port: 8506
  password: 3gLomcz6tImeLUj9g7g6by
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡·ğŸ‡ºRU_599 |14.18Mb
  server: 95.163.176.37
  type: ss
  country: ğŸ‡·ğŸ‡ºRU
  port: 8506
  password: WLEqen5ubQYw4TbHTxxnjK
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_637 |14.71Mb
  server: 54.84.99.165
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡ºğŸ‡¸US_644 |10.23Mb
  server: 54.226.24.40
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: disney_RU |22.37Mb
  server: 5.129.201.43
  type: ss
  country: ğŸ‡·ğŸ‡ºRU
  port: 23256
  password: yALtyAtHfbw1Vu4pqh6wUc
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_635 |102.27Mb
  server: 167.88.61.113
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 8090
  password: PCnnH6SQSnfoS27
  cipher: aes-256-gcm
- name: ğŸ‡ºğŸ‡¸US_658 |20.84Mb
  server: 54.157.216.140
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: disney_SE |10.22Mb
  server: 121.127.46.147
  type: ss
  country: ğŸ‡¸ğŸ‡ªSE
  port: 990
  password: f8f7aCzcPKbsF8p3
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_642 |94.43Mb
  server: 167.88.61.113
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 6697
  password: TEzjfAYq2IjtuoS
  cipher: aes-256-gcm
- name: ğŸ‡ºğŸ‡¸US_659 |10.40Mb
  server: 37.19.198.244
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: shadowsocks
  cipher: aes-128-gcm
- name: ğŸ‡ºğŸ‡¸US_649 |99.09Mb
  server: 167.88.61.59
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 8118
  password: cdBIDV42DCwnfIN
  cipher: aes-256-gcm
- name: ğŸ‡ºğŸ‡¸US_647 |15.44Mb
  server: 23.157.40.101
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 8008
  password: XKFKl2rULjIp74
  cipher: aes-256-gcm
- name: ğŸ‡ºğŸ‡¸US_648 |18.28Mb
  server: 167.88.61.110
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 2376
  password: faBAoD54k87UJG7
  cipher: aes-256-gcm
- name: ğŸ‡ºğŸ‡¸US_671 |19.94Mb
  server: 104.192.226.106
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 990
  password: f8f7aCzcPKbsF8p3
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_667 |24.80Mb
  server: 167.88.61.110
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 7001
  password: RexnBgU7EV5ADxG
  cipher: aes-256-gcm
- name: ğŸ‡ºğŸ‡¸US_676 |10.42Mb
  server: 37.19.198.160
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: shadowsocks
  cipher: aes-128-gcm
- name: ğŸ‡ºğŸ‡¸US_670 |83.42Mb
  server: 167.88.61.110
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 8119
  password: cdBIDV42DCwnfIN
  cipher: aes-256-gcm
- name: ğŸ‡ºğŸ‡¸US_672 |11.99Mb
  server: 167.88.61.110
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 7306
  password: FoOiGlkAA9yPEGP
  cipher: aes-256-gcm
- name: disney_US |174.19Mb
  server: 193.124.24.247
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 6510
  uuid: 8f44f672-e53b-44fb-b502-c886d37107b5
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_US |146.32Mb
  server: 193.124.24.247
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 6508
  uuid: b68fead5-5b0b-43a1-c34a-804467f0f368
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_US |119.96Mb
  server: 193.124.24.247
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 6504
  uuid: 7ceb165c-9aff-4ab7-ce9e-1df31a5ed911
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡ºğŸ‡¸US_679 |47.42Mb
  server: 167.88.61.110
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 6679
  password: TEzjfAYq2IjtuoS
  cipher: aes-256-gcm
- name: disney_US |178.61Mb
  server: 193.124.24.247
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 6502
  uuid: 242f22a3-29d9-4a94-d8ba-88043f2e1921
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_US |175.91Mb
  server: 193.124.24.247
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 6506
  uuid: c53d41d1-7d56-43ce-9994-408780c6476a
  alterId: 0
  cipher: auto
  network: tcp
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_US |174.30Mb
  server: 193.124.24.247
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 6514
  uuid: c362d735-01a8-48eb-baa2-ae7aa63bfdc3
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡ºğŸ‡¸US_680 |107.86Mb
  server: 23.157.40.101
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 8000
  password: KixLvKzwjekG00rm
  cipher: aes-256-gcm
- name: ğŸ‡ºğŸ‡¸US_694 |254.14Mb
  server: 15.204.11.190
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 15361
  uuid: 5d7bf9e3-415c-40f3-c66d-a54ea0fd860e
  alterId: 0
  cipher: auto
  network: tcp
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡ºğŸ‡¸US_681 |64.24Mb
  server: 167.88.61.110
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 8118
  password: cdBIDV42DCwnfIN
  cipher: aes-256-gcm
- name: ğŸ‡±ğŸ‡¹LT_524 |10.05Mb
  server: ltnl11.saint.ydns.eu
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¿ğŸ‡¦ZA_706 |37.85Mb
  server: 156.38.168.58
  type: ss
  country: ğŸ‡¿ğŸ‡¦ZA
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡§ğŸ‡ªBE_404 |11.30Mb
  server: 192.71.249.71
  type: ss
  country: ğŸ‡§ğŸ‡ªBE
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ğŸ‡«ğŸ‡·FR_435 |155.03Mb
  server: 83.147.216.70
  type: ss
  country: ğŸ‡«ğŸ‡·FR
  port: 64519
  password: Mal9DeKnSFhULd5Nbpkae0
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸZZ-ğŸ‡ºğŸ‡¸US_715 |16.62Mb
  server: s1.db-link03.top
  type: vmess
  country: ğŸZZ
  port: 80
  uuid: 25fbcec6-e45a-3a86-977a-12c40bf649ba
  alterId: 0
  cipher: auto
  network: ws
  servername: f7f48a0f7685b208efdf4956ae5eb0a0.s1.db-link03.top
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
  ws-opts:
    path: /dabai.in?=f7f48a0f7685b208efdf4956ae5eb0a0
    headers:
      HOST: f7f48a0f7685b208efdf4956ae5eb0a0.s1.db-link03.top
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - ğŸ‡¨ğŸ‡¦CA_414 |16.31Mb
  - _390 |10.43Mb
  - _394 |30.30Mb
  - _388 |30.25Mb
  - ğŸ‡«ğŸ‡·FR_436 |154.05Mb
  - _382 |18.59Mb
  - ğŸ‡«ğŸ‡·FR_439 |144.49Mb
  - ğŸ‡«ğŸ‡·FR_442 |10.10Mb
  - ğŸ‡¦ğŸ‡ºAU_401 |13.54Mb
  - Pool_ğŸ‡¬ğŸ‡§GB_462 |20.47Mb
  - ğŸ‡«ğŸ‡·FR_443 |136.85Mb
  - ğŸ‡«ğŸ‡·FR_444 |124.63Mb
  - ğŸ‡«ğŸ‡·FR_447 |133.92Mb
  - ğŸ‡«ğŸ‡·FR_448 |143.13Mb
  - ğŸ‡«ğŸ‡·FR_452 |127.86Mb
  - ğŸ‡«ğŸ‡·FR_454 |34.55Mb
  - ğŸ‡¬ğŸ‡§GB_468 |10.86Mb
  - ğŸ‡®ğŸ‡·IR_508 |11.28Mb
  - Relay_ğŸ‡®ğŸ‡·IR-ğŸ‡³ğŸ‡±NL_512 |10.54Mb
  - ğŸ‡±ğŸ‡¹LT_523 |11.20Mb
  - ğŸ‡¯ğŸ‡µJP_516 |32.28Mb
  - ğŸ‡±ğŸ‡¹LT_533 |12.01Mb
  - ğŸ‡±ğŸ‡¹LT_537 |11.81Mb
  - ğŸ‡±ğŸ‡¹LT_539 |10.17Mb
  - ğŸ‡®ğŸ‡³IN_477 |40.88Mb
  - ğŸ‡®ğŸ‡³IN_478 |16.84Mb
  - ğŸ‡³ğŸ‡±NL_547 |14.69Mb
  - ğŸ‡³ğŸ‡±NL_551 |10.03Mb
  - Pool_ğŸ‡­ğŸ‡°HK_470 |634.00Mb
  - ğŸ‡µğŸ‡ªPE_563 |39.22Mb
  - ğŸ‡µğŸ‡±PL_574 |149.42Mb
  - ğŸ‡µğŸ‡±PL_580 |11.54Mb
  - ğŸ‡µğŸ‡±PL_586 |11.16Mb
  - ğŸ‡µğŸ‡±PL_587 |11.29Mb
  - ğŸ‡·ğŸ‡ºRU_593 |17.61Mb
  - ğŸ‡ºğŸ‡¸US_632 |42.90Mb
  - disney_PY |20.96Mb
  - ğŸ‡·ğŸ‡ºRU_595 |10.75Mb
  - ğŸ‡·ğŸ‡ºRU_597 |12.49Mb
  - ğŸ‡·ğŸ‡ºRU_599 |14.18Mb
  - ğŸ‡ºğŸ‡¸US_637 |14.71Mb
  - ğŸ‡ºğŸ‡¸US_644 |10.23Mb
  - disney_RU |22.37Mb
  - ğŸ‡ºğŸ‡¸US_635 |102.27Mb
  - ğŸ‡ºğŸ‡¸US_658 |20.84Mb
  - disney_SE |10.22Mb
  - ğŸ‡ºğŸ‡¸US_642 |94.43Mb
  - ğŸ‡ºğŸ‡¸US_659 |10.40Mb
  - ğŸ‡ºğŸ‡¸US_649 |99.09Mb
  - ğŸ‡ºğŸ‡¸US_647 |15.44Mb
  - ğŸ‡ºğŸ‡¸US_648 |18.28Mb
  - ğŸ‡ºğŸ‡¸US_671 |19.94Mb
  - ğŸ‡ºğŸ‡¸US_667 |24.80Mb
  - ğŸ‡ºğŸ‡¸US_676 |10.42Mb
  - ğŸ‡ºğŸ‡¸US_670 |83.42Mb
  - ğŸ‡ºğŸ‡¸US_672 |11.99Mb
  - disney_US |174.19Mb
  - disney_US |146.32Mb
  - disney_US |119.96Mb
  - ğŸ‡ºğŸ‡¸US_679 |47.42Mb
  - disney_US |178.61Mb
  - disney_US |175.91Mb
  - disney_US |174.30Mb
  - ğŸ‡ºğŸ‡¸US_680 |107.86Mb
  - ğŸ‡ºğŸ‡¸US_694 |254.14Mb
  - ğŸ‡ºğŸ‡¸US_681 |64.24Mb
  - ğŸ‡±ğŸ‡¹LT_524 |10.05Mb
  - ğŸ‡¿ğŸ‡¦ZA_706 |37.85Mb
  - ğŸ‡§ğŸ‡ªBE_404 |11.30Mb
  - ğŸ‡«ğŸ‡·FR_435 |155.03Mb
  - Relay_ğŸZZ-ğŸ‡ºğŸ‡¸US_715 |16.62Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - ğŸ‡¨ğŸ‡¦CA_414 |16.31Mb
  - _390 |10.43Mb
  - _394 |30.30Mb
  - _388 |30.25Mb
  - ğŸ‡«ğŸ‡·FR_436 |154.05Mb
  - _382 |18.59Mb
  - ğŸ‡«ğŸ‡·FR_439 |144.49Mb
  - ğŸ‡«ğŸ‡·FR_442 |10.10Mb
  - ğŸ‡¦ğŸ‡ºAU_401 |13.54Mb
  - Pool_ğŸ‡¬ğŸ‡§GB_462 |20.47Mb
  - ğŸ‡«ğŸ‡·FR_443 |136.85Mb
  - ğŸ‡«ğŸ‡·FR_444 |124.63Mb
  - ğŸ‡«ğŸ‡·FR_447 |133.92Mb
  - ğŸ‡«ğŸ‡·FR_448 |143.13Mb
  - ğŸ‡«ğŸ‡·FR_452 |127.86Mb
  - ğŸ‡«ğŸ‡·FR_454 |34.55Mb
  - ğŸ‡¬ğŸ‡§GB_468 |10.86Mb
  - ğŸ‡®ğŸ‡·IR_508 |11.28Mb
  - Relay_ğŸ‡®ğŸ‡·IR-ğŸ‡³ğŸ‡±NL_512 |10.54Mb
  - ğŸ‡±ğŸ‡¹LT_523 |11.20Mb
  - ğŸ‡¯ğŸ‡µJP_516 |32.28Mb
  - ğŸ‡±ğŸ‡¹LT_533 |12.01Mb
  - ğŸ‡±ğŸ‡¹LT_537 |11.81Mb
  - ğŸ‡±ğŸ‡¹LT_539 |10.17Mb
  - ğŸ‡®ğŸ‡³IN_477 |40.88Mb
  - ğŸ‡®ğŸ‡³IN_478 |16.84Mb
  - ğŸ‡³ğŸ‡±NL_547 |14.69Mb
  - ğŸ‡³ğŸ‡±NL_551 |10.03Mb
  - Pool_ğŸ‡­ğŸ‡°HK_470 |634.00Mb
  - ğŸ‡µğŸ‡ªPE_563 |39.22Mb
  - ğŸ‡µğŸ‡±PL_574 |149.42Mb
  - ğŸ‡µğŸ‡±PL_580 |11.54Mb
  - ğŸ‡µğŸ‡±PL_586 |11.16Mb
  - ğŸ‡µğŸ‡±PL_587 |11.29Mb
  - ğŸ‡·ğŸ‡ºRU_593 |17.61Mb
  - ğŸ‡ºğŸ‡¸US_632 |42.90Mb
  - disney_PY |20.96Mb
  - ğŸ‡·ğŸ‡ºRU_595 |10.75Mb
  - ğŸ‡·ğŸ‡ºRU_597 |12.49Mb
  - ğŸ‡·ğŸ‡ºRU_599 |14.18Mb
  - ğŸ‡ºğŸ‡¸US_637 |14.71Mb
  - ğŸ‡ºğŸ‡¸US_644 |10.23Mb
  - disney_RU |22.37Mb
  - ğŸ‡ºğŸ‡¸US_635 |102.27Mb
  - ğŸ‡ºğŸ‡¸US_658 |20.84Mb
  - disney_SE |10.22Mb
  - ğŸ‡ºğŸ‡¸US_642 |94.43Mb
  - ğŸ‡ºğŸ‡¸US_659 |10.40Mb
  - ğŸ‡ºğŸ‡¸US_649 |99.09Mb
  - ğŸ‡ºğŸ‡¸US_647 |15.44Mb
  - ğŸ‡ºğŸ‡¸US_648 |18.28Mb
  - ğŸ‡ºğŸ‡¸US_671 |19.94Mb
  - ğŸ‡ºğŸ‡¸US_667 |24.80Mb
  - ğŸ‡ºğŸ‡¸US_676 |10.42Mb
  - ğŸ‡ºğŸ‡¸US_670 |83.42Mb
  - ğŸ‡ºğŸ‡¸US_672 |11.99Mb
  - disney_US |174.19Mb
  - disney_US |146.32Mb
  - disney_US |119.96Mb
  - ğŸ‡ºğŸ‡¸US_679 |47.42Mb
  - disney_US |178.61Mb
  - disney_US |175.91Mb
  - disney_US |174.30Mb
  - ğŸ‡ºğŸ‡¸US_680 |107.86Mb
  - ğŸ‡ºğŸ‡¸US_694 |254.14Mb
  - ğŸ‡ºğŸ‡¸US_681 |64.24Mb
  - ğŸ‡±ğŸ‡¹LT_524 |10.05Mb
  - ğŸ‡¿ğŸ‡¦ZA_706 |37.85Mb
  - ğŸ‡§ğŸ‡ªBE_404 |11.30Mb
  - ğŸ‡«ğŸ‡·FR_435 |155.03Mb
  - Relay_ğŸZZ-ğŸ‡ºğŸ‡¸US_715 |16.62Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
