port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: _515 |224.73Mb
  server: 82.38.31.176
  type: ss
  port: 8080
  udp: true
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: Relay_-ğŸ‡³ğŸ‡±NL_523 |263.85Mb
  server: 151.242.251.137
  type: ss
  port: 8080
  password: o5osZg269v5zHpYjr1xY9s
  cipher: chacha20-ietf-poly1305
- name: _522 |255.66Mb
  server: 45.87.175.181
  type: ss
  port: 8080
  udp: true
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: disney_PT |399.49Mb
  server: 185.231.233.112
  type: ss
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: _524 |75.49Mb
  server: 213.159.67.124
  type: ss
  port: 443
  password: mbhqsStnFQT1cTZYCdsmkugGUC6GT6rp
  cipher: chacha20-ietf-poly1305
- name: disney_TR |11.59Mb
  server: 185.39.204.161
  type: ss
  port: 33563
  udp: true
  password: bSlgCoGhApOb55tIMD0zxY
  cipher: chacha20-ietf-poly1305
- name: Relay_-ğŸ‡¯ğŸ‡µJP_526 |11.74Mb
  server: planb.mojcn.com
  type: vmess
  port: 16617
  udp: true
  uuid: 77439561-dcef-4e45-803a-743cfa7d20c2
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /
    headers:
      Host: 9e97d6c9e2e0ad3444cbf96d3709366d.mobgslb.tbcache.com
- name: Relay_-ğŸ‡­ğŸ‡°HK_525 |23.99Mb
  server: planb.mojcn.com
  type: vmess
  port: 16632
  udp: true
  uuid: 77439561-dcef-4e45-803a-743cfa7d20c2
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /
    headers:
      Host: 9e97d6c9e2e0ad3444cbf96d3709366d.mobgslb.tbcache.com
- name: _512 |13.60Mb
  server: 103.106.3.82
  type: ss
  port: 443
  udp: true
  password: 4SaCIazlgumYkM8FkPzlmwjpyWBDZFBk
  cipher: chacha20-ietf-poly1305
- name: Relay_-ğŸ‡®ğŸ‡³IN_544 |74.25Mb
  server: planb.mojcn.com
  type: vmess
  port: 16626
  udp: true
  uuid: 77439561-dcef-4e45-803a-743cfa7d20c2
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /
    headers:
      Host: 9e97d6c9e2e0ad3444cbf96d3709366d.mobgslb.tbcache.com
- name: Relay_-ğŸ‡­ğŸ‡°HK_548 |23.65Mb
  server: planb.mojcn.com
  type: vmess
  port: 16622
  udp: true
  uuid: 77439561-dcef-4e45-803a-743cfa7d20c2
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /
    headers:
      Host: 9e97d6c9e2e0ad3444cbf96d3709366d.mobgslb.tbcache.com
- name: _560 |39.35Mb
  server: 104.168.94.41
  type: vmess
  port: 32301
  uuid: a2235b72-fd9c-404f-be5a-53b2de0cb798
  alterId: 0
  cipher: auto
  network: http
  http-opts:
    method: GET
    path:
    - /
  h2-opts: {}
- name: _562 |63.94Mb
  server: 47.253.197.26
  type: vmess
  port: 12056
  uuid: dd7be7f1-38ff-45e6-f1e5-b20c2190f527
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
- name: Relay_-ğŸ‡²ğŸ‡¾MY_535 |25.13Mb
  server: ml0724.ysds168.shop
  type: vmess
  port: 2052
  udp: true
  uuid: 665d9b8f-153d-4907-adac-de12afd9c851
  alterId: 0
  cipher: auto
  servername: ml0724.ysds168.shop
  http-opts: {}
  h2-opts: {}
  tls: true
- name: _549 |10.68Mb
  server: 54.252.240.128
  type: vmess
  port: 1000
  uuid: ca26a9fd-fef8-4ea7-d194-450ce4e0c67a
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
- name: _575 |11.51Mb
  server: 74.117.196.232
  type: vmess
  port: 37934
  udp: true
  uuid: e1cc26b3-df0b-477b-afb0-53659a25e978
  alterId: 0
  cipher: auto
  network: ws
  servername: imafake.locker
  http-opts: {}
  h2-opts: {}
  tls: true
  ws-opts:
    path: /speedtest
- name: Relay_-ğŸ‡­ğŸ‡°HK_542 |22.88Mb
  server: m.cnmjin.net
  type: vmess
  port: 16622
  udp: true
  uuid: 77439561-dcef-4e45-803a-743cfa7d20c2
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /
    headers:
      Host: 9e97d6c9e2e0ad3444cbf96d3709366d.mobgslb.tbcache.com
- name: Relay_-ğŸ‡­ğŸ‡°HK_553 |23.82Mb
  server: m.cnmjin.net
  type: vmess
  port: 16632
  udp: true
  uuid: 77439561-dcef-4e45-803a-743cfa7d20c2
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /
    headers:
      Host: 9e97d6c9e2e0ad3444cbf96d3709366d.mobgslb.tbcache.com
- name: Relay_-ğŸ‡¹ğŸ‡¼TW_572 |11.59Mb
  server: m.cnmjin.net
  type: vmess
  port: 16616
  udp: true
  uuid: 77439561-dcef-4e45-803a-743cfa7d20c2
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /
    headers:
      Host: 9e97d6c9e2e0ad3444cbf96d3709366d.mobgslb.tbcache.com
- name: Relay_-ğŸ‡ºğŸ‡¸US_568 |10.33Mb
  server: planb.mojcn.com
  type: vmess
  port: 16618
  udp: true
  uuid: 77439561-dcef-4e45-803a-743cfa7d20c2
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /
    headers:
      Host: 9e97d6c9e2e0ad3444cbf96d3709366d.mobgslb.tbcache.com
- name: Relay_-ğŸ‡ºğŸ‡¸US_569 |11.48Mb
  server: m.cnmjin.net
  type: vmess
  port: 16618
  udp: true
  uuid: 77439561-dcef-4e45-803a-743cfa7d20c2
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /
    headers:
      Host: 9e97d6c9e2e0ad3444cbf96d3709366d.mobgslb.tbcache.com
- name: Relay_-ğŸ‡¯ğŸ‡µJP_586 |17.92Mb
  server: 160.16.138.24
  type: trojan
  port: 3169
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¯ğŸ‡µJP_587 |19.36Mb
  server: 160.16.138.24
  type: trojan
  port: 1331
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¯ğŸ‡µJP_589 |11.59Mb
  server: 52.195.176.26
  type: trojan
  port: 2145
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: Relay_-ğŸ‡¹ğŸ‡¼TW_574 |16.94Mb
  server: planb.mojcn.com
  type: vmess
  port: 16616
  udp: true
  uuid: 77439561-dcef-4e45-803a-743cfa7d20c2
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /
    headers:
      Host: 9e97d6c9e2e0ad3444cbf96d3709366d.mobgslb.tbcache.com
- name: disney_US |110.08Mb
  server: 23.247.137.64
  type: trojan
  port: 443
  udp: true
  password: 3c4e10af98c30972
  alpn:
  - h2
  sni: n2.gladns.com
  network: grpc
  grpc-opts:
    grpc-service-name: db
- name: Relay_-ğŸ‡³ğŸ‡±NL_593 |11.41Mb
  server: 160.16.81.84
  type: trojan
  port: 2760
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡³ğŸ‡±NL_603 |47.46Mb
  server: 160.16.236.32
  type: trojan
  port: 4054
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¯ğŸ‡µJP_597 |10.47Mb
  server: 160.16.236.32
  type: trojan
  port: 3093
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡³ğŸ‡±NL_606 |45.70Mb
  server: 160.16.81.84
  type: trojan
  port: 4054
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡³ğŸ‡±NL_591 |40.89Mb
  server: 18.162.142.242
  type: trojan
  port: 4054
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡³ğŸ‡±NL_608 |19.51Mb
  server: 160.16.124.55
  type: trojan
  port: 2760
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: ğŸ‡§ğŸ‡·BR_613 |20.30Mb
  server: 38.180.16.86
  type: vmess
  country: ğŸ‡§ğŸ‡·BR
  port: 36236
  uuid: a58bc1a5-8c18-49ff-9453-c331b52f45dc
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡§ğŸ‡¬BG_612 |31.26Mb
  server: 87.121.162.249
  type: ss
  country: ğŸ‡§ğŸ‡¬BG
  port: 443
  password: JGv616hMWdjfuZ00jYfq7XkBHJZrOBrg
  cipher: chacha20-ietf-poly1305
- name: disney_FR |207.86Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 27092
  uuid: a0596ba6-72a3-4366-8992-77088da65bd8
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡²ğŸ‡½MX_706 |169.18Mb
  server: 216.238.89.53
  type: vmess
  country: ğŸ‡²ğŸ‡½MX
  port: 57283
  uuid: 1a5aafc0-6482-451d-fe76-6875b7818579
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡¬ğŸ‡§GB_620 |165.77Mb
  server: 82.38.31.184
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡§ğŸ‡·BR_614 |21.66Mb
  server: 38.180.16.86
  type: vmess
  country: ğŸ‡§ğŸ‡·BR
  port: 36104
  uuid: E146A8CB-9D2F-449C-ADCA-8736FB
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡®ğŸ‡ªIE_701 |62.44Mb
  server: 18.203.220.111
  type: ss
  country: ğŸ‡®ğŸ‡ªIE
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡ºğŸ‡¸US_715 |12.46Mb
  server: 74.117.196.232
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 37934
  uuid: 6d600864-32da-49fd-baf4-7df051762454
  alterId: 0
  cipher: auto
  network: ws
  servername: imafake.locker
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /speedtest
    headers:
      HOST: imafake.locker
- name: Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡¦ğŸ‡ºAU_713 |10.13Mb
  server: sy4.620720.xyz
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  uuid: 516d8a7a-3f0b-41d3-bad0-246116381516
  alterId: 0
  cipher: auto
  network: ws
  servername: sy4.620720.xyz
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /
    headers:
      HOST: sy4.620720.xyz
- name: disney_HK |23.99Mb
  server: 112.118.116.66
  type: trojan
  country: ğŸ‡­ğŸ‡°HK
  port: 443
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: ğŸ‡ºğŸ‡¸US_711 |10.44Mb
  server: 23.95.75.146
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: NDRySIABARbErNIVsCNVkyYAHiBzhveT
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_721 |10.18Mb
  server: 74.117.196.232
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 37934
  uuid: 254551f6-ec28-4938-ad0e-0aa4aa1965ec
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /speedtest
- name: ğŸ‡ºğŸ‡¸US_723 |11.38Mb
  server: 74.117.196.232
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 37934
  uuid: 4f3cfda3-a255-40eb-8801-71f9fffb19d6
  alterId: 0
  cipher: auto
  network: ws
  servername: imafake.locker
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /speedtest
    headers:
      HOST: imafake.locker
- name: ğŸ‡²ğŸ‡¾MY_707 |28.53Mb
  server: 38.54.98.110
  type: vmess
  country: ğŸ‡²ğŸ‡¾MY
  port: 2052
  uuid: 665d9b8f-153d-4907-adac-de12afd9c851
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: disney_PY |17.21Mb
  server: 38.165.233.93
  type: ss
  country: ğŸ‡ºğŸ‡¸ US
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: Relay_ğŸ‡­ğŸ‡°HK-ğŸ‡­ğŸ‡°HK_630 |12.54Mb
  server: cgroup.node4.s2.nodelist-airport.com
  type: ss
  country: ğŸ‡­ğŸ‡°HK
  port: 48712
  password: 8f3a835c-8a45-480d-ae35-1deb2c52dcae
  cipher: aes-256-gcm
- name: Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_720 |32.44Mb
  server: sw19.sesamebuta.top
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  uuid: 805ba514-bf2f-4d5d-df49-8417804e8de3
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /abcd
- name: _511 |10.01Mb
  server: 45.93.95.187
  type: ss
  port: 8618
  udp: true
  password: 4lUEC91c1d8oeClzDbYpXA
  cipher: chacha20-ietf-poly1305
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - _515 |224.73Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_523 |263.85Mb
  - _522 |255.66Mb
  - disney_PT |399.49Mb
  - _524 |75.49Mb
  - disney_TR |11.59Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_526 |11.74Mb
  - Relay_-ğŸ‡­ğŸ‡°HK_525 |23.99Mb
  - _512 |13.60Mb
  - Relay_-ğŸ‡®ğŸ‡³IN_544 |74.25Mb
  - Relay_-ğŸ‡­ğŸ‡°HK_548 |23.65Mb
  - _560 |39.35Mb
  - _562 |63.94Mb
  - Relay_-ğŸ‡²ğŸ‡¾MY_535 |25.13Mb
  - _549 |10.68Mb
  - _575 |11.51Mb
  - Relay_-ğŸ‡­ğŸ‡°HK_542 |22.88Mb
  - Relay_-ğŸ‡­ğŸ‡°HK_553 |23.82Mb
  - Relay_-ğŸ‡¹ğŸ‡¼TW_572 |11.59Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_568 |10.33Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_569 |11.48Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_586 |17.92Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_587 |19.36Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_589 |11.59Mb
  - Relay_-ğŸ‡¹ğŸ‡¼TW_574 |16.94Mb
  - disney_US |110.08Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_593 |11.41Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_603 |47.46Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_597 |10.47Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_606 |45.70Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_591 |40.89Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_608 |19.51Mb
  - ğŸ‡§ğŸ‡·BR_613 |20.30Mb
  - ğŸ‡§ğŸ‡¬BG_612 |31.26Mb
  - disney_FR |207.86Mb
  - ğŸ‡²ğŸ‡½MX_706 |169.18Mb
  - ğŸ‡¬ğŸ‡§GB_620 |165.77Mb
  - ğŸ‡§ğŸ‡·BR_614 |21.66Mb
  - ğŸ‡®ğŸ‡ªIE_701 |62.44Mb
  - ğŸ‡ºğŸ‡¸US_715 |12.46Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡¦ğŸ‡ºAU_713 |10.13Mb
  - disney_HK |23.99Mb
  - ğŸ‡ºğŸ‡¸US_711 |10.44Mb
  - ğŸ‡ºğŸ‡¸US_721 |10.18Mb
  - ğŸ‡ºğŸ‡¸US_723 |11.38Mb
  - ğŸ‡²ğŸ‡¾MY_707 |28.53Mb
  - disney_PY |17.21Mb
  - Relay_ğŸ‡­ğŸ‡°HK-ğŸ‡­ğŸ‡°HK_630 |12.54Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_720 |32.44Mb
  - _511 |10.01Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - _515 |224.73Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_523 |263.85Mb
  - _522 |255.66Mb
  - disney_PT |399.49Mb
  - _524 |75.49Mb
  - disney_TR |11.59Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_526 |11.74Mb
  - Relay_-ğŸ‡­ğŸ‡°HK_525 |23.99Mb
  - _512 |13.60Mb
  - Relay_-ğŸ‡®ğŸ‡³IN_544 |74.25Mb
  - Relay_-ğŸ‡­ğŸ‡°HK_548 |23.65Mb
  - _560 |39.35Mb
  - _562 |63.94Mb
  - Relay_-ğŸ‡²ğŸ‡¾MY_535 |25.13Mb
  - _549 |10.68Mb
  - _575 |11.51Mb
  - Relay_-ğŸ‡­ğŸ‡°HK_542 |22.88Mb
  - Relay_-ğŸ‡­ğŸ‡°HK_553 |23.82Mb
  - Relay_-ğŸ‡¹ğŸ‡¼TW_572 |11.59Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_568 |10.33Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_569 |11.48Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_586 |17.92Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_587 |19.36Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_589 |11.59Mb
  - Relay_-ğŸ‡¹ğŸ‡¼TW_574 |16.94Mb
  - disney_US |110.08Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_593 |11.41Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_603 |47.46Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_597 |10.47Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_606 |45.70Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_591 |40.89Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_608 |19.51Mb
  - ğŸ‡§ğŸ‡·BR_613 |20.30Mb
  - ğŸ‡§ğŸ‡¬BG_612 |31.26Mb
  - disney_FR |207.86Mb
  - ğŸ‡²ğŸ‡½MX_706 |169.18Mb
  - ğŸ‡¬ğŸ‡§GB_620 |165.77Mb
  - ğŸ‡§ğŸ‡·BR_614 |21.66Mb
  - ğŸ‡®ğŸ‡ªIE_701 |62.44Mb
  - ğŸ‡ºğŸ‡¸US_715 |12.46Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡¦ğŸ‡ºAU_713 |10.13Mb
  - disney_HK |23.99Mb
  - ğŸ‡ºğŸ‡¸US_711 |10.44Mb
  - ğŸ‡ºğŸ‡¸US_721 |10.18Mb
  - ğŸ‡ºğŸ‡¸US_723 |11.38Mb
  - ğŸ‡²ğŸ‡¾MY_707 |28.53Mb
  - disney_PY |17.21Mb
  - Relay_ğŸ‡­ğŸ‡°HK-ğŸ‡­ğŸ‡°HK_630 |12.54Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_720 |32.44Mb
  - _511 |10.01Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
