port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: ' |47.83Mb'
  server: 137.184.174.93
  type: ss
  port: 8080
  udp: true
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: ' |42.87Mb'
  server: 104.192.226.106
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ' |28.06Mb'
  server: 23.95.72.81
  type: ss
  port: 443
  udp: true
  password: UAMVtHm54uahd6SiN5WcD16rsPSdabPG
  cipher: chacha20-ietf-poly1305
- name: Relay_ |309.67Mb
  server: 82.38.31.218
  type: ss
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_NL |288.19Mb
  server: 151.242.251.144
  type: ss
  port: 8080
  udp: true
  password: QCXDxuDlTTMD7jtgHUjIoj
  cipher: chacha20-ietf-poly1305
- name: Relay_ |15.54Mb
  server: 23.227.38.178
  type: trojan
  port: 443
  udp: true
  password: a544940a-2c1c-4723-96cc-d03053a95530
  sni: q6clkp794liy3y90.hktimecsgo.xyz
  skip-cert-verify: true
  ws-opts:
    path: /images
    headers:
      Host: q6clkp794liy3y90.hktimecsgo.xyz
  network: ws
- name: ' |22.92Mb'
  server: 45.15.126.19
  type: ss
  port: 443
  udp: true
  password: 6Ts2ZDTQAf3hkFoB8AFufDwsGrlF4e2t
  cipher: chacha20-ietf-poly1305
- name: Relay_ |47.08Mb
  server: 104.18.13.167
  type: vmess
  port: 443
  udp: true
  uuid: 24254866-770c-41b4-9404-3f50524f425b
  alterId: 0
  cipher: auto
  network: ws
  servername: 24254866-770c-41b4-9404-3f50524f425b.mihomo.baby
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /saoihgreg9384gh8934
    headers:
      Host: 24254866-770c-41b4-9404-3f50524f425b.mihomo.baby
- name: Relay_ |20.92Mb
  server: 23.227.38.178
  type: trojan
  port: 443
  udp: true
  password: a8a5b34d-fe46-487d-bd6a-d9f3101525fd
  sni: q6clkp794liy3y90.hktimecsgo.xyz
  skip-cert-verify: true
  ws-opts:
    path: /images
    headers:
      Host: q6clkp794liy3y90.hktimecsgo.xyz
  network: ws
- name: Relay_ |12.49Mb
  server: 23.227.38.178
  type: trojan
  port: 443
  udp: true
  password: aff9928f-7ba3-45fb-b56d-4dec45653ca9
  sni: q6clkp794liy3y90.hktimecsgo.xyz
  skip-cert-verify: true
  ws-opts:
    path: /images
    headers:
      Host: q6clkp794liy3y90.hktimecsgo.xyz
  network: ws
- name: _173 |22.03Mb
  server: 213.159.67.124
  type: ss
  port: 443
  udp: true
  password: mbhqsStnFQT1cTZYCdsmkugGUC6GT6rp
  cipher: chacha20-ietf-poly1305
- name: Relay_ |37.57Mb
  server: 141.193.213.199
  type: trojan
  port: 443
  udp: true
  password: a8a5b34d-fe46-487d-bd6a-d9f3101525fd
  sni: 26z68w0ecxbuyf89.ukgogo202511.top
  skip-cert-verify: true
  ws-opts:
    path: /images
    headers:
      Host: 26z68w0ecxbuyf89.ukgogo202511.top
  network: ws
- name: Relay_ |19.17Mb
  server: 23.227.38.178
  type: trojan
  port: 443
  udp: true
  password: 8b45d379-702f-41b3-a6b2-9c87a01dcd5c
  sni: q6clkp794liy3y90.hktimecsgo.xyz
  skip-cert-verify: true
  ws-opts:
    path: /images
    headers:
      Host: q6clkp794liy3y90.hktimecsgo.xyz
  network: ws
- name: Relay_ |35.93Mb
  server: us19-25.998998.best
  type: vmess
  port: 443
  udp: true
  uuid: 24254866-770c-41b4-9404-3f50524f425b
  alterId: 0
  cipher: auto
  network: ws
  servername: 24254866-770c-41b4-9404-3f50524f425b.mihomo.baby
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /saoihgreg9384gh8934
    headers:
      Host: 24254866-770c-41b4-9404-3f50524f425b.mihomo.baby
- name: Relay_ |32.45Mb
  server: usiys.southbyte.xyz
  type: trojan
  port: 5897
  udp: true
  password: fg20mtCFHy
  sni: usiys.southbyte.xyz
  skip-cert-verify: true
- name: ' |129.36Mb'
  server: 134.209.147.198
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: Relay_ |11.05Mb
  server: 23.227.38.178
  type: trojan
  port: 443
  udp: true
  password: 13d29042-ab82-4195-9cd4-2bafc518e201
  sni: q6clkp794liy3y90.hktimecsgo.xyz
  skip-cert-verify: true
  ws-opts:
    path: /images
    headers:
      Host: q6clkp794liy3y90.hktimecsgo.xyz
  network: ws
- name: ' |24.17Mb'
  server: 95.111.222.113
  type: ss
  port: 443
  udp: true
  password: SVt6ZiWzRI1Yxeig4xBZwiJOt6ceXwGa
  cipher: chacha20-ietf-poly1305
- name: Relay_ |21.26Mb
  server: 23.227.38.178
  type: trojan
  port: 443
  udp: true
  password: 832afa39-df88-47ba-8234-45ef9c7080de
  sni: q6clkp794liy3y90.hktimecsgo.xyz
  skip-cert-verify: true
  ws-opts:
    path: /images
    headers:
      Host: q6clkp794liy3y90.hktimecsgo.xyz
  network: ws
- name: ' |12.43Mb'
  server: 103.106.3.82
  type: ss
  port: 443
  udp: true
  password: 4SaCIazlgumYkM8FkPzlmwjpyWBDZFBk
  cipher: chacha20-ietf-poly1305
- name: Relay_ |11.92Mb
  server: 160.16.70.180
  type: trojan
  port: 4054
  password: 2cf6d686799e6fa95316394064f26c0a
  sni: www.nintendogames.net
- name: ' |40.95Mb'
  server: 149.28.76.252
  type: trojan
  port: 443
  udp: true
  password: 7f7fea1d-16cf-3f0b-95c8-2dbb2fc5a97c
  sni: usa.sstank.top
  skip-cert-verify: true
- name: Relay_ |41.93Mb
  server: 141.193.213.199
  type: trojan
  port: 443
  udp: true
  password: a544940a-2c1c-4723-96cc-d03053a95530
  sni: 26z68w0ecxbuyf89.ukgogo202511.top
  skip-cert-verify: true
  ws-opts:
    path: /images
    headers:
      Host: 26z68w0ecxbuyf89.ukgogo202511.top
  network: ws
- name: disney_US |39.42Mb
  server: fondly.appagent.net
  type: trojan
  port: 28331
  password: RFxCa3A4zwRXcICDlYxpZR8qSS3lEN93CSYFyA3TaDIyS2aXD2leS6we5yZEOn03qcNYD
  sni: fondly.appagent.net
- name: Relay_-ğŸ‡³ğŸ‡±NL_222 |39.89Mb
  server: 160.16.116.227
  type: trojan
  port: 4054
  password: 2cf6d686799e6fa95316394064f26c0a
  sni: www.nintendogames.net
- name: Relay_ |10.27Mb
  server: 153.121.39.240
  type: trojan
  port: 3093
  password: 2cf6d686799e6fa95316394064f26c0a
  sni: www.nintendogames.net
- name: disney_FR |108.68Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 27092
  uuid: a0596ba6-72a3-4366-8992-77088da65bd8
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡¬ğŸ‡§GB |251.54Mb
  server: 82.38.31.191
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸ‡¬ğŸ‡§GB |273.21Mb
  server: 82.38.31.210
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: disney_RU |53.72Mb
  server: 37.18.14.33
  type: trojan
  port: 443
  udp: true
  password: Qzy7tgpRhu
  sni: m.vk.com
  skip-cert-verify: true
- name: Relay_-ğŸ‡¯ğŸ‡µJP_233 |21.96Mb
  server: 153.121.44.99
  type: trojan
  port: 3093
  password: 2cf6d686799e6fa95316394064f26c0a
  sni: www.nintendogames.net
- name: disney_HK |10.84Mb
  server: cdnfire.xiaomispeed.com
  type: trojan
  port: 21102
  udp: true
  password: 70e5578a-c298-48b8-a967-f9c4d360173a
  sni: cdnfire.xiaomispeed.com
  skip-cert-verify: true
- name: disney_netflix_NL |287.61Mb
  server: 82.38.31.194
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡·GR_243 |465.38Mb
  server: 192.71.166.100
  type: ss
  country: ğŸ‡¬ğŸ‡·GR
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: Relay_ |94.96Mb
  server: p141.panda001.net
  type: ss
  port: 4652
  udp: true
  password: qwerREWQ@@
  cipher: aes-256-cfb
- name: Relay_ğŸ‡®ğŸ‡ªIE-ğŸ‡ªğŸ‡¸ES_255 |10.32Mb
  server: f7c5a058-fa4a-4f7c-aed6-203efaf52286.f1eb10ae-1d82-4c6a-b4dd-bd9525520956.com
  type: trojan
  country: ğŸ‡®ğŸ‡ªIE
  port: 12012
  udp: true
  password: 05bf6017-75c3-44c1-b9bf-6a038107afde
  sni: tr.yuanul.com
  skip-cert-verify: true
- name: disney_TW |65.90Mb
  server: f7c5a058-fa4a-4f7c-aed6-203efaf52286.f1eb10ae-1d82-4c6a-b4dd-bd9525520956.com
  type: trojan
  country: ğŸ‡®ğŸ‡ªIE
  port: 12103
  udp: true
  password: 05bf6017-75c3-44c1-b9bf-6a038107afde
  sni: 116.yuanul.com
  skip-cert-verify: true
- name: Relay_ğŸ‡®ğŸ‡ªIE-ğŸ‡®ğŸ‡·IR_249 |10.46Mb
  server: f7c5a058-fa4a-4f7c-aed6-203efaf52286.f1eb10ae-1d82-4c6a-b4dd-bd9525520956.com
  type: trojan
  country: ğŸ‡®ğŸ‡ªIE
  port: 10107
  udp: true
  password: 05bf6017-75c3-44c1-b9bf-6a038107afde
  sni: sni.eos-suzhou-4.cmecloud.cn
  skip-cert-verify: true
- name: disney_HK |10.43Mb
  server: f7c5a058-fa4a-4f7c-aed6-203efaf52286.f1eb10ae-1d82-4c6a-b4dd-bd9525520956.com
  type: trojan
  country: ğŸ‡®ğŸ‡ªIE
  port: 10108
  udp: true
  password: 05bf6017-75c3-44c1-b9bf-6a038107afde
  sni: sni.eos-suzhou-4.cmecloud.cn
  skip-cert-verify: true
- name: Relay_ğŸ‡®ğŸ‡ªIE-ğŸ‡®ğŸ‡·IR_252 |10.58Mb
  server: f7c5a058-fa4a-4f7c-aed6-203efaf52286.f1eb10ae-1d82-4c6a-b4dd-bd9525520956.com
  type: trojan
  country: ğŸ‡®ğŸ‡ªIE
  port: 10102
  udp: true
  password: 05bf6017-75c3-44c1-b9bf-6a038107afde
  sni: sni.eos-suzhou-4.cmecloud.cn
  skip-cert-verify: true
- name: Relay_ğŸ‡®ğŸ‡ªIE-ğŸ‡®ğŸ‡·IR_245 |10.41Mb
  server: f7c5a058-fa4a-4f7c-aed6-203efaf52286.f1eb10ae-1d82-4c6a-b4dd-bd9525520956.com
  type: trojan
  country: ğŸ‡®ğŸ‡ªIE
  port: 10106
  udp: true
  password: 05bf6017-75c3-44c1-b9bf-6a038107afde
  sni: sni.eos-suzhou-4.cmecloud.cn
  skip-cert-verify: true
- name: Relay_ğŸ‡®ğŸ‡ªIE-ğŸ‡ªğŸ‡¸ES_251 |10.24Mb
  server: f7c5a058-fa4a-4f7c-aed6-203efaf52286.f1eb10ae-1d82-4c6a-b4dd-bd9525520956.com
  type: trojan
  country: ğŸ‡®ğŸ‡ªIE
  port: 12014
  udp: true
  password: 05bf6017-75c3-44c1-b9bf-6a038107afde
  sni: sg4.yuanul.com
  skip-cert-verify: true
- name: disney_TW |73.52Mb
  server: f7c5a058-fa4a-4f7c-aed6-203efaf52286.f1eb10ae-1d82-4c6a-b4dd-bd9525520956.com
  type: trojan
  country: ğŸ‡®ğŸ‡ªIE
  port: 12106
  udp: true
  password: 05bf6017-75c3-44c1-b9bf-6a038107afde
  sni: 110.yuanul.com
  skip-cert-verify: true
- name: Relay_ğŸ‡®ğŸ‡ªIE-ğŸ‡ªğŸ‡¸ES_248 |10.04Mb
  server: f7c5a058-fa4a-4f7c-aed6-203efaf52286.f1eb10ae-1d82-4c6a-b4dd-bd9525520956.com
  type: trojan
  country: ğŸ‡®ğŸ‡ªIE
  port: 12015
  udp: true
  password: 05bf6017-75c3-44c1-b9bf-6a038107afde
  sni: sg5.yuanul.com
  skip-cert-verify: true
- name: disney_netflix_NL |244.35Mb
  server: 151.242.251.153
  type: ss
  country: ğŸ‡®ğŸ‡· IR
  port: 8080
  password: QCXDxuDlTTMD7jtgHUjIoj
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_NL |340.85Mb
  server: 151.242.251.144
  type: ss
  country: ğŸ‡®ğŸ‡· IR
  port: 8080
  password: 4a2rfixophdjffa8KVA4Aa
  cipher: chacha20-ietf-poly1305
- name: disney_TW |72.70Mb
  server: f7c5a058-fa4a-4f7c-aed6-203efaf52286.f1eb10ae-1d82-4c6a-b4dd-bd9525520956.com
  type: trojan
  country: ğŸ‡®ğŸ‡ªIE
  port: 12102
  udp: true
  password: 05bf6017-75c3-44c1-b9bf-6a038107afde
  sni: 106.yuanul.com
  skip-cert-verify: true
- name: Relay_ğŸ‡®ğŸ‡ªIE-ğŸ‡ªğŸ‡¸ES_272 |10.20Mb
  server: f7c5a058-fa4a-4f7c-aed6-203efaf52286.f1eb10ae-1d82-4c6a-b4dd-bd9525520956.com
  type: trojan
  country: ğŸ‡®ğŸ‡ªIE
  port: 12016
  udp: true
  password: 05bf6017-75c3-44c1-b9bf-6a038107afde
  sni: sg6.yuanul.com
  skip-cert-verify: true
- name: disney_TW |66.47Mb
  server: f7c5a058-fa4a-4f7c-aed6-203efaf52286.f1eb10ae-1d82-4c6a-b4dd-bd9525520956.com
  type: trojan
  country: ğŸ‡®ğŸ‡ªIE
  port: 12105
  udp: true
  password: 05bf6017-75c3-44c1-b9bf-6a038107afde
  skip-cert-verify: true
- name: Relay_ğŸ‡®ğŸ‡ªIE-ğŸ‡ªğŸ‡¸ES_260 |10.30Mb
  server: f7c5a058-fa4a-4f7c-aed6-203efaf52286.f1eb10ae-1d82-4c6a-b4dd-bd9525520956.com
  type: trojan
  country: ğŸ‡®ğŸ‡ªIE
  port: 12013
  udp: true
  password: 05bf6017-75c3-44c1-b9bf-6a038107afde
  sni: tr.yuanul.com
  skip-cert-verify: true
- name: disney_TW |10.38Mb
  server: f7c5a058-fa4a-4f7c-aed6-203efaf52286.f1eb10ae-1d82-4c6a-b4dd-bd9525520956.com
  type: trojan
  country: ğŸ‡®ğŸ‡ªIE
  port: 12104
  udp: true
  password: 05bf6017-75c3-44c1-b9bf-6a038107afde
  sni: 108.yuanul.com
  skip-cert-verify: true
- name: disney_US |10.04Mb
  server: f7c5a058-fa4a-4f7c-aed6-203efaf52286.f1eb10ae-1d82-4c6a-b4dd-bd9525520956.com
  type: trojan
  country: ğŸ‡®ğŸ‡ªIE
  port: 13205
  udp: true
  password: 05bf6017-75c3-44c1-b9bf-6a038107afde
  sni: 138.yuanul.com
  skip-cert-verify: true
- name: Relay_ğŸ‡®ğŸ‡ªIE-ğŸ‡®ğŸ‡·IR_262 |10.30Mb
  server: f7c5a058-fa4a-4f7c-aed6-203efaf52286.f1eb10ae-1d82-4c6a-b4dd-bd9525520956.com
  type: trojan
  country: ğŸ‡®ğŸ‡ªIE
  port: 10104
  udp: true
  password: 05bf6017-75c3-44c1-b9bf-6a038107afde
  sni: sni.eos-suzhou-4.cmecloud.cn
  skip-cert-verify: true
- name: disney_HK |10.46Mb
  server: f7c5a058-fa4a-4f7c-aed6-203efaf52286.f1eb10ae-1d82-4c6a-b4dd-bd9525520956.com
  type: trojan
  country: ğŸ‡®ğŸ‡ªIE
  port: 10103
  udp: true
  password: 05bf6017-75c3-44c1-b9bf-6a038107afde
  sni: sni.eos-suzhou-4.cmecloud.cn
  skip-cert-verify: true
- name: ğŸ‡ºğŸ‡¸US |19.64Mb
  server: 74.117.196.232
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 37934
  uuid: 9631096d-3032-4942-9446-bdf12665682b
  alterId: 0
  cipher: auto
  network: ws
  servername: imafake.locker
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /speedtest
    headers:
      HOST: imafake.locker
- name: ğŸ‡ºğŸ‡¸US |18.70Mb
  server: 74.117.196.232
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 37934
  uuid: 12929592-a7bd-41eb-ab4d-d804f76c4ff9
  alterId: 0
  cipher: auto
  network: ws
  servername: imafake.locker
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /speedtest
    headers:
      HOST: imafake.locker
- name: ğŸ‡±ğŸ‡¹ LT |133.94Mb
  server: 45.87.175.174
  type: ss
  country: ğŸ‡±ğŸ‡¹ LT
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸ‡¯ğŸ‡µJP-ğŸ‡¯ğŸ‡µJP_288 |11.31Mb
  server: xray.kk37005.tk
  type: vmess
  country: ğŸ‡¯ğŸ‡µJP
  port: 55919
  uuid: 2e7548bb-7c5b-4d97-d64d-1b2fe4050089
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡®ğŸ‡·IR_296 |13.77Mb
  server: cf.fovi.tk
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  uuid: bf67437e-6c90-45ca-abc2-c7240a5ce2aa
  alterId: 0
  cipher: auto
  network: ws
  servername: foxlux.fovi.tk
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /eisasqa
    headers:
      HOST: foxlux.fovi.tk
- name: ' |86.43Mb'
  server: 109.71.246.210
  type: ss
  port: 56689
  udp: true
  password: YQCSKoCF3QazW8YlvDBWA4
  cipher: chacha20-ietf-poly1305
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - ' |47.83Mb'
  - ' |42.87Mb'
  - ' |28.06Mb'
  - Relay_ |309.67Mb
  - disney_netflix_NL |288.19Mb
  - Relay_ |15.54Mb
  - ' |22.92Mb'
  - Relay_ |47.08Mb
  - Relay_ |20.92Mb
  - Relay_ |12.49Mb
  - _173 |22.03Mb
  - Relay_ |37.57Mb
  - Relay_ |19.17Mb
  - Relay_ |35.93Mb
  - Relay_ |32.45Mb
  - ' |129.36Mb'
  - Relay_ |11.05Mb
  - ' |24.17Mb'
  - Relay_ |21.26Mb
  - ' |12.43Mb'
  - Relay_ |11.92Mb
  - ' |40.95Mb'
  - Relay_ |41.93Mb
  - disney_US |39.42Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_222 |39.89Mb
  - Relay_ |10.27Mb
  - disney_FR |108.68Mb
  - ğŸ‡¬ğŸ‡§GB |251.54Mb
  - Relay_ğŸ‡¬ğŸ‡§GB |273.21Mb
  - disney_RU |53.72Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_233 |21.96Mb
  - disney_HK |10.84Mb
  - disney_netflix_NL |287.61Mb
  - ğŸ‡¬ğŸ‡·GR_243 |465.38Mb
  - Relay_ |94.96Mb
  - Relay_ğŸ‡®ğŸ‡ªIE-ğŸ‡ªğŸ‡¸ES_255 |10.32Mb
  - disney_TW |65.90Mb
  - Relay_ğŸ‡®ğŸ‡ªIE-ğŸ‡®ğŸ‡·IR_249 |10.46Mb
  - disney_HK |10.43Mb
  - Relay_ğŸ‡®ğŸ‡ªIE-ğŸ‡®ğŸ‡·IR_252 |10.58Mb
  - Relay_ğŸ‡®ğŸ‡ªIE-ğŸ‡®ğŸ‡·IR_245 |10.41Mb
  - Relay_ğŸ‡®ğŸ‡ªIE-ğŸ‡ªğŸ‡¸ES_251 |10.24Mb
  - disney_TW |73.52Mb
  - Relay_ğŸ‡®ğŸ‡ªIE-ğŸ‡ªğŸ‡¸ES_248 |10.04Mb
  - disney_netflix_NL |244.35Mb
  - disney_netflix_NL |340.85Mb
  - disney_TW |72.70Mb
  - Relay_ğŸ‡®ğŸ‡ªIE-ğŸ‡ªğŸ‡¸ES_272 |10.20Mb
  - disney_TW |66.47Mb
  - Relay_ğŸ‡®ğŸ‡ªIE-ğŸ‡ªğŸ‡¸ES_260 |10.30Mb
  - disney_TW |10.38Mb
  - disney_US |10.04Mb
  - Relay_ğŸ‡®ğŸ‡ªIE-ğŸ‡®ğŸ‡·IR_262 |10.30Mb
  - disney_HK |10.46Mb
  - ğŸ‡ºğŸ‡¸US |19.64Mb
  - ğŸ‡ºğŸ‡¸US |18.70Mb
  - ğŸ‡±ğŸ‡¹ LT |133.94Mb
  - Relay_ğŸ‡¯ğŸ‡µJP-ğŸ‡¯ğŸ‡µJP_288 |11.31Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡®ğŸ‡·IR_296 |13.77Mb
  - ' |86.43Mb'
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - ' |47.83Mb'
  - ' |42.87Mb'
  - ' |28.06Mb'
  - Relay_ |309.67Mb
  - disney_netflix_NL |288.19Mb
  - Relay_ |15.54Mb
  - ' |22.92Mb'
  - Relay_ |47.08Mb
  - Relay_ |20.92Mb
  - Relay_ |12.49Mb
  - _173 |22.03Mb
  - Relay_ |37.57Mb
  - Relay_ |19.17Mb
  - Relay_ |35.93Mb
  - Relay_ |32.45Mb
  - ' |129.36Mb'
  - Relay_ |11.05Mb
  - ' |24.17Mb'
  - Relay_ |21.26Mb
  - ' |12.43Mb'
  - Relay_ |11.92Mb
  - ' |40.95Mb'
  - Relay_ |41.93Mb
  - disney_US |39.42Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_222 |39.89Mb
  - Relay_ |10.27Mb
  - disney_FR |108.68Mb
  - ğŸ‡¬ğŸ‡§GB |251.54Mb
  - Relay_ğŸ‡¬ğŸ‡§GB |273.21Mb
  - disney_RU |53.72Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_233 |21.96Mb
  - disney_HK |10.84Mb
  - disney_netflix_NL |287.61Mb
  - ğŸ‡¬ğŸ‡·GR_243 |465.38Mb
  - Relay_ |94.96Mb
  - Relay_ğŸ‡®ğŸ‡ªIE-ğŸ‡ªğŸ‡¸ES_255 |10.32Mb
  - disney_TW |65.90Mb
  - Relay_ğŸ‡®ğŸ‡ªIE-ğŸ‡®ğŸ‡·IR_249 |10.46Mb
  - disney_HK |10.43Mb
  - Relay_ğŸ‡®ğŸ‡ªIE-ğŸ‡®ğŸ‡·IR_252 |10.58Mb
  - Relay_ğŸ‡®ğŸ‡ªIE-ğŸ‡®ğŸ‡·IR_245 |10.41Mb
  - Relay_ğŸ‡®ğŸ‡ªIE-ğŸ‡ªğŸ‡¸ES_251 |10.24Mb
  - disney_TW |73.52Mb
  - Relay_ğŸ‡®ğŸ‡ªIE-ğŸ‡ªğŸ‡¸ES_248 |10.04Mb
  - disney_netflix_NL |244.35Mb
  - disney_netflix_NL |340.85Mb
  - disney_TW |72.70Mb
  - Relay_ğŸ‡®ğŸ‡ªIE-ğŸ‡ªğŸ‡¸ES_272 |10.20Mb
  - disney_TW |66.47Mb
  - Relay_ğŸ‡®ğŸ‡ªIE-ğŸ‡ªğŸ‡¸ES_260 |10.30Mb
  - disney_TW |10.38Mb
  - disney_US |10.04Mb
  - Relay_ğŸ‡®ğŸ‡ªIE-ğŸ‡®ğŸ‡·IR_262 |10.30Mb
  - disney_HK |10.46Mb
  - ğŸ‡ºğŸ‡¸US |19.64Mb
  - ğŸ‡ºğŸ‡¸US |18.70Mb
  - ğŸ‡±ğŸ‡¹ LT |133.94Mb
  - Relay_ğŸ‡¯ğŸ‡µJP-ğŸ‡¯ğŸ‡µJP_288 |11.31Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡®ğŸ‡·IR_296 |13.77Mb
  - ' |86.43Mb'
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
