port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: disney_netflix_US |42.69Mb
  server: 88.210.36.106
  type: ss
  port: 2377
  udp: true
  password: t0srmdxrm3xyjnvqz9ewlxb2myq7rjuv
  cipher: chacha20-ietf-poly1305
  plugin: obfs
  plugin-opts:
    host: (TG @WangCai2)e7b7ab7:102816
    mode: tls
- name: disney_netflix_US |43.25Mb
  server: 88.210.36.109
  type: ss
  port: 2377
  udp: true
  password: t0srmdxrm3xyjnvqz9ewlxb2myq7rjuv
  cipher: chacha20-ietf-poly1305
  plugin: obfs
  plugin-opts:
    host: (TG @WangCai2)e7b7ab7:102816
    mode: tls
- name: disney_netflix_US |44.01Mb
  server: 88.210.36.108
  type: ss
  port: 2377
  udp: true
  password: t0srmdxrm3xyjnvqz9ewlxb2myq7rjuv
  cipher: chacha20-ietf-poly1305
  plugin: obfs
  plugin-opts:
    host: (TG @WangCai2)e7b7ab7:102816
    mode: tls
- name: disney_netflix_US |43.97Mb
  server: 88.210.36.107
  type: ss
  port: 2377
  udp: true
  password: t0srmdxrm3xyjnvqz9ewlxb2myq7rjuv
  cipher: chacha20-ietf-poly1305
  plugin: obfs
  plugin-opts:
    host: (TG @WangCai2)e7b7ab7:102816
    mode: tls
- name: disney_netflix_US |74.51Mb
  server: 205.209.109.194
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 17277
  password: d2fkgzsdu5sturjs8f19
  cipher: aes-128-gcm
- name: _39 |163.22Mb
  server: 82.38.31.179
  type: ss
  port: 8080
  udp: true
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_US |73.18Mb
  server: 69.164.240.83
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 10878
  password: t6d26id0pjzdo3x5wtlf
  cipher: aes-128-gcm
- name: disney_netflix_US |73.43Mb
  server: 69.164.240.86
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 10880
  password: 3px0wmx0e81145g568ga
  cipher: aes-128-gcm
- name: netflix_MX |44.48Mb
  server: 216.238.87.47
  type: vmess
  country: ğŸ‡²ğŸ‡½MX
  port: 27502
  uuid: b8155ce4-7e08-4c40-800f-8671312b7124
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: _42 |392.56Mb
  server: 185.153.197.5
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: disney_netflix_PY |148.20Mb
  server: 38.165.233.93
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: netflix_NG |50.42Mb
  server: 176.97.192.4
  type: vmess
  port: 22700
  uuid: 9f698736-b5d2-4acc-81c3-8b96e1aeb772
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
- name: disney_netflix_JP |13.46Mb
  server: 160.16.72.33
  type: trojan
  port: 3093
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: netflix_NG |48.07Mb
  server: 176.97.192.4
  type: vmess
  port: 35227
  uuid: 5dd60293-2743-422d-aa73-08823eb5167e
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
- name: netflix_DE |189.47Mb
  server: 45.80.188.48
  type: vmess
  port: 50255
  uuid: bc140c02-25a9-4feb-96bb-7d772b17fd17
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - disney_netflix_US |42.69Mb
  - disney_netflix_US |43.25Mb
  - disney_netflix_US |44.01Mb
  - disney_netflix_US |43.97Mb
  - disney_netflix_US |74.51Mb
  - _39 |163.22Mb
  - disney_netflix_US |73.18Mb
  - disney_netflix_US |73.43Mb
  - netflix_MX |44.48Mb
  - _42 |392.56Mb
  - disney_netflix_PY |148.20Mb
  - netflix_NG |50.42Mb
  - disney_netflix_JP |13.46Mb
  - netflix_NG |48.07Mb
  - netflix_DE |189.47Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - disney_netflix_US |42.69Mb
  - disney_netflix_US |43.25Mb
  - disney_netflix_US |44.01Mb
  - disney_netflix_US |43.97Mb
  - disney_netflix_US |74.51Mb
  - _39 |163.22Mb
  - disney_netflix_US |73.18Mb
  - disney_netflix_US |73.43Mb
  - netflix_MX |44.48Mb
  - _42 |392.56Mb
  - disney_netflix_PY |148.20Mb
  - netflix_NG |50.42Mb
  - disney_netflix_JP |13.46Mb
  - netflix_NG |48.07Mb
  - netflix_DE |189.47Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
