port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: disney_netflix_GB |159.63Mb
  server: koma-yt.pages.dev
  type: trojan
  port: 8443
  udp: true
  password: 8r<[9'l6hAO#8ZQi
  sni: Koma-YT.PAGeS.Dev
  ws-opts:
    path: /tro8sFW1S91B6sZrM1?ed=2560
    headers:
      Host: Koma-YT.PAGeS.Dev
  network: ws
- name: _142 |15.08Mb
  server: 46.183.184.60
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: _145 |25.14Mb
  server: 103.231.73.211
  type: ss
  port: 57456
  udp: true
  password: 8afc633eb63227e9
  cipher: chacha20-ietf-poly1305
- name: disney_MD |409.67Mb
  server: 185.153.197.5
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: Relay_-ðŸ‡³ðŸ‡±NL_244 |45.08Mb
  server: 160.16.136.130
  type: trojan
  port: 4054
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: Relay_-ðŸ‡³ðŸ‡±NL_243 |11.04Mb
  server: 160.16.196.59
  type: trojan
  port: 2890
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: Relay_-ðŸ‡¸ðŸ‡¬SG_242 |10.18Mb
  server: 160.16.233.76
  type: trojan
  port: 507
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: disney_HK |20.45Mb
  server: 58.152.25.242
  type: trojan
  port: 443
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: Relay_-ðŸ‡¯ðŸ‡µJP_247 |12.24Mb
  server: 13.231.156.35
  type: trojan
  port: 1331
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: _246 |11.63Mb
  server: 58.152.30.120
  type: trojan
  port: 443
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: netflix_MX |39.38Mb
  server: 216.238.89.53
  type: vmess
  country: ðŸ‡²ðŸ‡½MX
  port: 57283
  uuid: 1a5aafc0-6482-451d-fe76-6875b7818579
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_HK |26.33Mb
  server: 58.152.18.95
  type: trojan
  port: 443
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: Relay_-ðŸ‡¯ðŸ‡µJP_248 |11.33Mb
  server: 160.16.117.182
  type: trojan
  port: 3093
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: disney_netflix_US |40.85Mb
  server: 38.14.99.163
  type: vmess
  country: ðŸ‡ºðŸ‡¸US
  port: 59807
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: auto
  network: tcp
  servername: 38.14.99.163
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ðŸ‡·ðŸ‡ºRU_351 |15.08Mb
  server: 45.139.26.173
  type: ss
  country: ðŸ‡·ðŸ‡ºRU
  port: 57456
  password: d3837224ed465f00
  cipher: chacha20-ietf-poly1305
- name: ðŸ‡­ðŸ‡°HK_346 |122.66Mb
  server: 8.218.116.26
  type: vmess
  country: ðŸ‡­ðŸ‡°HK
  port: 32228
  uuid: e4767e9f-ed00-4f31-a984-a918bdd9b09c
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ðŸ‡¸ðŸ‡¬SG_352 |11.27Mb
  server: 68.183.178.131
  type: vmess
  country: ðŸ‡¸ðŸ‡¬SG
  port: 58607
  uuid: c11c32cb-27b3-4afa-c0f3-fb250aa4959e
  alterId: 0
  cipher: auto
  network: ws
  servername: www.12333.monster
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /
    headers:
      HOST: www.12333.monster
- name: Relay_ðŸ‡­ðŸ‡°HK-ðŸ‡ºðŸ‡¸US_338 |11.58Mb
  server: v8.hdacd.com
  type: vmess
  country: ðŸ‡­ðŸ‡°HK
  port: 30808
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: auto
  network: tcp
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
proxy-groups:
- name: ðŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - disney_netflix_GB |159.63Mb
  - _142 |15.08Mb
  - _145 |25.14Mb
  - disney_MD |409.67Mb
  - Relay_-ðŸ‡³ðŸ‡±NL_244 |45.08Mb
  - Relay_-ðŸ‡³ðŸ‡±NL_243 |11.04Mb
  - Relay_-ðŸ‡¸ðŸ‡¬SG_242 |10.18Mb
  - disney_HK |20.45Mb
  - Relay_-ðŸ‡¯ðŸ‡µJP_247 |12.24Mb
  - _246 |11.63Mb
  - netflix_MX |39.38Mb
  - disney_HK |26.33Mb
  - Relay_-ðŸ‡¯ðŸ‡µJP_248 |11.33Mb
  - disney_netflix_US |40.85Mb
  - ðŸ‡·ðŸ‡ºRU_351 |15.08Mb
  - ðŸ‡­ðŸ‡°HK_346 |122.66Mb
  - ðŸ‡¸ðŸ‡¬SG_352 |11.27Mb
  - Relay_ðŸ‡­ðŸ‡°HK-ðŸ‡ºðŸ‡¸US_338 |11.58Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - disney_netflix_GB |159.63Mb
  - _142 |15.08Mb
  - _145 |25.14Mb
  - disney_MD |409.67Mb
  - Relay_-ðŸ‡³ðŸ‡±NL_244 |45.08Mb
  - Relay_-ðŸ‡³ðŸ‡±NL_243 |11.04Mb
  - Relay_-ðŸ‡¸ðŸ‡¬SG_242 |10.18Mb
  - disney_HK |20.45Mb
  - Relay_-ðŸ‡¯ðŸ‡µJP_247 |12.24Mb
  - _246 |11.63Mb
  - netflix_MX |39.38Mb
  - disney_HK |26.33Mb
  - Relay_-ðŸ‡¯ðŸ‡µJP_248 |11.33Mb
  - disney_netflix_US |40.85Mb
  - ðŸ‡·ðŸ‡ºRU_351 |15.08Mb
  - ðŸ‡­ðŸ‡°HK_346 |122.66Mb
  - ðŸ‡¸ðŸ‡¬SG_352 |11.27Mb
  - Relay_ðŸ‡­ðŸ‡°HK-ðŸ‡ºðŸ‡¸US_338 |11.58Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ðŸš€ èŠ‚ç‚¹é€‰æ‹©
