port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: ğŸ‡¨ğŸ‡¦CA_255 |183.39Mb
  server: 138.197.153.10
  type: ss
  country: ğŸ‡¨ğŸ‡¦CA
  port: 8080
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: ğŸ‡¨ğŸ‡¦CA_253 |10.92Mb
  server: 68.183.193.204
  type: ss
  country: ğŸ‡¨ğŸ‡¦CA
  port: 8080
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: ğŸ‡¨ğŸ‡¦CA_252 |157.19Mb
  server: 138.197.165.21
  type: ss
  country: ğŸ‡¨ğŸ‡¦CA
  port: 8080
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: ğŸ‡¨ğŸ‡¦CA_254 |10.04Mb
  server: 79.127.200.162
  type: ss
  country: ğŸ‡¨ğŸ‡¦CA
  port: 990
  password: f8f7aCzcPKbsF8p3
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¨ğŸ‡¦CA_256 |10.34Mb
  server: 132.145.102.60
  type: ss
  country: ğŸ‡¨ğŸ‡¦CA
  port: 21001
  password: 2a6c0365-e3ed-4aef-81ca-b1b6b46088da
  cipher: chacha20-ietf-poly1305
- name: _232 |10.15Mb
  server: 196.196.192.58
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _233 |10.15Mb
  server: 37.143.129.98
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_288 |210.03Mb
  server: 146.70.23.32
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: _231 |11.40Mb
  server: 89.46.233.36
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡«ğŸ‡®FI_278 |16.18Mb
  server: 65.21.243.22
  type: ss
  country: ğŸ‡«ğŸ‡®FI
  port: 31348
  password: mZGUFWMAlfWqI4vP58zw9DAHxR8TZLndKkvRgHHFa9eqWdnx
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_291 |10.23Mb
  server: 79.127.233.170
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ğŸ‡«ğŸ‡·FR_279 |144.46Mb
  server: 83.147.216.70
  type: ss
  country: ğŸ‡«ğŸ‡·FR
  port: 64519
  password: MVAZ6nsCGVWhTzcRIUD85f
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_289 |157.06Mb
  server: 89.185.84.185
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: c0rALV8bvjaRHD1hg8SmuN
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡§ğŸ‡·BR_250 |11.32Mb
  server: 154.90.62.168
  type: ss
  country: ğŸ‡§ğŸ‡·BR
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ğŸ‡¬ğŸ‡§GB_294 |10.32Mb
  server: 141.98.101.181
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: shadowsocks
  cipher: aes-128-gcm
- name: ğŸ‡¦ğŸ‡ºAU_243 |10.24Mb
  server: 3.25.198.142
  type: ss
  country: ğŸ‡¦ğŸ‡ºAU
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡¦ğŸ‡ºAU_244 |10.13Mb
  server: 3.107.35.33
  type: ss
  country: ğŸ‡¦ğŸ‡ºAU
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡¬ğŸ‡§GB_292 |73.94Mb
  server: 89.185.84.185
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: DkH7uO7t90Uw4D95zgZVdV
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_293 |10.86Mb
  server: 64.137.109.212
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 44884
  password: 2DGq3jvVRg5n3CcxmysGK2kmrgJeSNof12A76cZvVxqPpetyC1XEciCFufq5xKvRWGGnKVembpThuUSQhbZ7GMsZY4UVxEBw
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_296 |77.84Mb
  server: 89.185.84.185
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: gq2tNZSuBwrZXZDZ5Z2Gfo
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡­ğŸ‡ºHU_307 |10.02Mb
  server: 109.61.46.43
  type: ss
  country: ğŸ‡­ğŸ‡ºHU
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡­ğŸ‡°HK_303 |20.86Mb
  server: 8.210.230.179
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 2318
  uuid: 55bb7a7c-c09d-47f6-a047-8472eeaadeff
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
  ws-opts:
    path: /arki?ed=2048
- name: ğŸ‡®ğŸ‡³IN_309 |39.74Mb
  server: 15.206.124.85
  type: ss
  country: ğŸ‡®ğŸ‡³IN
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡®ğŸ‡³IN_310 |20.80Mb
  server: 13.233.212.186
  type: ss
  country: ğŸ‡®ğŸ‡³IN
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡®ğŸ‡³IN_311 |42.16Mb
  server: 52.66.211.233
  type: ss
  country: ğŸ‡®ğŸ‡³IN
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: Pool_ğŸ‡­ğŸ‡°HK_300 |170.00Mb
  server: 150.107.46.21
  type: ssr
  country: ğŸ‡­ğŸ‡°HK
  port: 8083
  password: iFqnzSscN
  cipher: aes-256-cfb
  protocol: origin
  obfs: tls1.2_ticket_auth
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - ğŸ‡¨ğŸ‡¦CA_255 |183.39Mb
  - ğŸ‡¨ğŸ‡¦CA_253 |10.92Mb
  - ğŸ‡¨ğŸ‡¦CA_252 |157.19Mb
  - ğŸ‡¨ğŸ‡¦CA_254 |10.04Mb
  - ğŸ‡¨ğŸ‡¦CA_256 |10.34Mb
  - _232 |10.15Mb
  - _233 |10.15Mb
  - ğŸ‡¬ğŸ‡§GB_288 |210.03Mb
  - _231 |11.40Mb
  - ğŸ‡«ğŸ‡®FI_278 |16.18Mb
  - ğŸ‡¬ğŸ‡§GB_291 |10.23Mb
  - ğŸ‡«ğŸ‡·FR_279 |144.46Mb
  - ğŸ‡¬ğŸ‡§GB_289 |157.06Mb
  - ğŸ‡§ğŸ‡·BR_250 |11.32Mb
  - ğŸ‡¬ğŸ‡§GB_294 |10.32Mb
  - ğŸ‡¦ğŸ‡ºAU_243 |10.24Mb
  - ğŸ‡¦ğŸ‡ºAU_244 |10.13Mb
  - ğŸ‡¬ğŸ‡§GB_292 |73.94Mb
  - ğŸ‡¬ğŸ‡§GB_293 |10.86Mb
  - ğŸ‡¬ğŸ‡§GB_296 |77.84Mb
  - ğŸ‡­ğŸ‡ºHU_307 |10.02Mb
  - ğŸ‡­ğŸ‡°HK_303 |20.86Mb
  - ğŸ‡®ğŸ‡³IN_309 |39.74Mb
  - ğŸ‡®ğŸ‡³IN_310 |20.80Mb
  - ğŸ‡®ğŸ‡³IN_311 |42.16Mb
  - Pool_ğŸ‡­ğŸ‡°HK_300 |170.00Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - ğŸ‡¨ğŸ‡¦CA_255 |183.39Mb
  - ğŸ‡¨ğŸ‡¦CA_253 |10.92Mb
  - ğŸ‡¨ğŸ‡¦CA_252 |157.19Mb
  - ğŸ‡¨ğŸ‡¦CA_254 |10.04Mb
  - ğŸ‡¨ğŸ‡¦CA_256 |10.34Mb
  - _232 |10.15Mb
  - _233 |10.15Mb
  - ğŸ‡¬ğŸ‡§GB_288 |210.03Mb
  - _231 |11.40Mb
  - ğŸ‡«ğŸ‡®FI_278 |16.18Mb
  - ğŸ‡¬ğŸ‡§GB_291 |10.23Mb
  - ğŸ‡«ğŸ‡·FR_279 |144.46Mb
  - ğŸ‡¬ğŸ‡§GB_289 |157.06Mb
  - ğŸ‡§ğŸ‡·BR_250 |11.32Mb
  - ğŸ‡¬ğŸ‡§GB_294 |10.32Mb
  - ğŸ‡¦ğŸ‡ºAU_243 |10.24Mb
  - ğŸ‡¦ğŸ‡ºAU_244 |10.13Mb
  - ğŸ‡¬ğŸ‡§GB_292 |73.94Mb
  - ğŸ‡¬ğŸ‡§GB_293 |10.86Mb
  - ğŸ‡¬ğŸ‡§GB_296 |77.84Mb
  - ğŸ‡­ğŸ‡ºHU_307 |10.02Mb
  - ğŸ‡­ğŸ‡°HK_303 |20.86Mb
  - ğŸ‡®ğŸ‡³IN_309 |39.74Mb
  - ğŸ‡®ğŸ‡³IN_310 |20.80Mb
  - ğŸ‡®ğŸ‡³IN_311 |42.16Mb
  - Pool_ğŸ‡­ğŸ‡°HK_300 |170.00Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
