port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: disney_netflix_GB |144.76Mb
  server: 172.66.44.230
  type: trojan
  port: 8443
  udp: true
  password: 8r<[9'l6hAO#8ZQi
  sni: Koma-YT.PAGeS.Dev
  ws-opts:
    path: /tro8sFW1S91B6sZrM1?ed=2560
    headers:
      Host: Koma-YT.PAGeS.Dev
  network: ws
- name: disney_netflix_GB |159.63Mb
  server: koma-yt.pages.dev
  type: trojan
  port: 8443
  udp: true
  password: 8r<[9'l6hAO#8ZQi
  sni: Koma-YT.PAGeS.Dev
  ws-opts:
    path: /tro8sFW1S91B6sZrM1?ed=2560
    headers:
      Host: Koma-YT.PAGeS.Dev
  network: ws
- name: _169 |61.54Mb
  server: pupas-shirting-unsung.freesocks.work
  type: ss
  port: 443
  udp: true
  password: p78naCf2EfOlRSLTX0wFVx
  cipher: chacha20-ietf-poly1305
- name: _167 |394.98Mb
  server: 46.183.184.60
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: _168 |25.14Mb
  server: 103.231.73.211
  type: ss
  port: 57456
  udp: true
  password: 8afc633eb63227e9
  cipher: chacha20-ietf-poly1305
- name: Relay_-ðŸ‡¯ðŸ‡µJP_261 |13.73Mb
  server: 160.16.117.182
  type: trojan
  port: 3093
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: Relay_-ðŸ‡¸ðŸ‡¬SG_262 |10.24Mb
  server: 160.16.233.76
  type: trojan
  port: 507
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: Relay_-ðŸ‡³ðŸ‡±NL_267 |13.72Mb
  server: 160.16.136.130
  type: trojan
  port: 4054
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: Relay_-ðŸ‡³ðŸ‡±NL_269 |11.20Mb
  server: 160.16.196.59
  type: trojan
  port: 2890
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: netflix_US |178.40Mb
  server: 38.14.99.163
  type: vmess
  country: ðŸ‡ºðŸ‡¸US
  port: 59807
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: auto
  network: tcp
  servername: 38.14.99.163
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_HK |11.66Mb
  server: 58.152.18.95
  type: trojan
  port: 443
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: ðŸ‡­ðŸ‡°HK_311 |157.15Mb
  server: 8.218.116.26
  type: vmess
  country: ðŸ‡­ðŸ‡°HK
  port: 32228
  uuid: e4767e9f-ed00-4f31-a984-a918bdd9b09c
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ðŸ‡°ðŸ‡·KR_367 |10.03Mb
  server: 146.56.112.110
  type: vmess
  country: ðŸ‡°ðŸ‡·KR
  port: 8888
  uuid: e7c302f3-90d6-42dd-9d7d-94a3683a3707
  alterId: 0
  cipher: auto
  network: tcp
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ðŸ‡¸ðŸ‡¬SG_370 |10.66Mb
  server: 68.183.178.131
  type: vmess
  country: ðŸ‡¸ðŸ‡¬SG
  port: 58607
  uuid: c11c32cb-27b3-4afa-c0f3-fb250aa4959e
  alterId: 0
  cipher: auto
  network: ws
  servername: www.12333.monster
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /
    headers:
      HOST: www.12333.monster
proxy-groups:
- name: ðŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - disney_netflix_GB |144.76Mb
  - disney_netflix_GB |159.63Mb
  - _169 |61.54Mb
  - _167 |394.98Mb
  - _168 |25.14Mb
  - Relay_-ðŸ‡¯ðŸ‡µJP_261 |13.73Mb
  - Relay_-ðŸ‡¸ðŸ‡¬SG_262 |10.24Mb
  - Relay_-ðŸ‡³ðŸ‡±NL_267 |13.72Mb
  - Relay_-ðŸ‡³ðŸ‡±NL_269 |11.20Mb
  - netflix_US |178.40Mb
  - disney_HK |11.66Mb
  - ðŸ‡­ðŸ‡°HK_311 |157.15Mb
  - ðŸ‡°ðŸ‡·KR_367 |10.03Mb
  - ðŸ‡¸ðŸ‡¬SG_370 |10.66Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - disney_netflix_GB |144.76Mb
  - disney_netflix_GB |159.63Mb
  - _169 |61.54Mb
  - _167 |394.98Mb
  - _168 |25.14Mb
  - Relay_-ðŸ‡¯ðŸ‡µJP_261 |13.73Mb
  - Relay_-ðŸ‡¸ðŸ‡¬SG_262 |10.24Mb
  - Relay_-ðŸ‡³ðŸ‡±NL_267 |13.72Mb
  - Relay_-ðŸ‡³ðŸ‡±NL_269 |11.20Mb
  - netflix_US |178.40Mb
  - disney_HK |11.66Mb
  - ðŸ‡­ðŸ‡°HK_311 |157.15Mb
  - ðŸ‡°ðŸ‡·KR_367 |10.03Mb
  - ðŸ‡¸ðŸ‡¬SG_370 |10.66Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ðŸš€ èŠ‚ç‚¹é€‰æ‹©
