port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: ' |249.31Mb'
  server: 45.87.175.181
  type: ss
  port: 8080
  udp: true
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: ' |16.20Mb'
  server: 45.93.95.187
  type: ss
  port: 8618
  udp: true
  password: 4lUEC91c1d8oeClzDbYpXA
  cipher: chacha20-ietf-poly1305
- name: ' |148.63Mb'
  server: 82.38.31.199
  type: ss
  port: 8080
  udp: true
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ' |11.49Mb'
  server: 103.106.3.82
  type: ss
  port: 443
  udp: true
  password: 4SaCIazlgumYkM8FkPzlmwjpyWBDZFBk
  cipher: chacha20-ietf-poly1305
- name: ' |32.59Mb'
  server: 213.159.67.124
  type: ss
  port: 443
  password: mbhqsStnFQT1cTZYCdsmkugGUC6GT6rp
  cipher: chacha20-ietf-poly1305
- name: disney_PT |12.44Mb
  server: 185.231.233.112
  type: ss
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: Relay_ |227.88Mb
  server: 151.242.251.137
  type: ss
  port: 8080
  password: o5osZg269v5zHpYjr1xY9s
  cipher: chacha20-ietf-poly1305
- name: _659 |24.85Mb
  server: 74.117.196.232
  type: vmess
  port: 37934
  udp: true
  uuid: e1cc26b3-df0b-477b-afb0-53659a25e978
  alterId: 0
  cipher: auto
  network: ws
  servername: imafake.locker
  http-opts: {}
  h2-opts: {}
  tls: true
  ws-opts:
    path: /speedtest
- name: ' |48.06Mb'
  server: 154.90.62.168
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: _653 |29.37Mb
  server: 47.243.209.146
  type: vmess
  port: 29333
  uuid: 9681c9ac-c4e3-4600-b698-5cc6b14085f7
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /arki?ed=2048
- name: _670 |69.80Mb
  server: 47.253.197.26
  type: vmess
  port: 12056
  uuid: dd7be7f1-38ff-45e6-f1e5-b20c2190f527
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
- name: _658 |20.36Mb
  server: 47.242.239.78
  type: vmess
  port: 4210
  uuid: 58f25da8-4de6-4de0-973c-700cd1637ad9
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /arki?ed=2048
- name: _661 |19.38Mb
  server: 47.243.51.237
  type: vmess
  port: 52801
  uuid: ef93f413-9039-4ddb-aefb-2490287df55a
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /arki?ed=2048
- name: _663 |20.37Mb
  server: 47.243.51.237
  type: vmess
  port: 27165
  uuid: be5f65df-e104-4e2a-9391-d10454da7df1
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /arki?ed=2048
- name: _680 |29.61Mb
  server: 104.168.94.41
  type: vmess
  port: 32301
  uuid: a2235b72-fd9c-404f-be5a-53b2de0cb798
  alterId: 0
  cipher: auto
  network: http
  http-opts:
    method: GET
    path:
    - /
  h2-opts: {}
- name: Relay_-ğŸ‡²ğŸ‡¾MY_665 |30.37Mb
  server: ml0724.ysds168.shop
  type: vmess
  port: 2052
  udp: true
  uuid: 665d9b8f-153d-4907-adac-de12afd9c851
  alterId: 0
  cipher: auto
  servername: ml0724.ysds168.shop
  http-opts: {}
  h2-opts: {}
  tls: true
- name: _667 |18.52Mb
  server: 47.242.239.78
  type: vmess
  port: 55855
  uuid: a863724f-d62e-4303-9bb4-5b7ce5ae60ad
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /arki?ed=2048
- name: _668 |17.58Mb
  server: 47.243.51.237
  type: vmess
  port: 23559
  uuid: e3f4cb0e-3b3d-41ad-b24a-9cbc2927b451
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /arki?ed=2048
- name: _678 |20.03Mb
  server: 47.243.209.146
  type: vmess
  port: 5410
  uuid: 27fa4383-2e52-4ae5-ac1c-2c0059e4081e
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  ws-opts:
    path: /arki?ed=2048
- name: Relay_-ğŸ‡³ğŸ‡±NL_691 |10.98Mb
  server: 160.16.81.84
  type: trojan
  port: 2760
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¯ğŸ‡µJP_692 |21.44Mb
  server: 160.16.223.205
  type: trojan
  port: 1331
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡³ğŸ‡±NL_689 |10.24Mb
  server: 18.162.142.242
  type: trojan
  port: 4054
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡³ğŸ‡±NL_694 |17.31Mb
  server: 160.16.124.55
  type: trojan
  port: 2760
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡³ğŸ‡±NL_699 |10.86Mb
  server: 160.16.81.84
  type: trojan
  port: 4054
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: disney_US |70.82Mb
  server: 23.247.137.64
  type: trojan
  port: 443
  udp: true
  password: 3c4e10af98c30972
  alpn:
  - h2
  sni: n2.gladns.com
  network: grpc
  grpc-opts:
    grpc-service-name: db
- name: Relay_-ğŸ‡¯ğŸ‡µJP_700 |13.99Mb
  server: 160.16.236.32
  type: trojan
  port: 3093
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡³ğŸ‡±NL_701 |11.06Mb
  server: 160.16.236.32
  type: trojan
  port: 4054
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¯ğŸ‡µJP_703 |14.94Mb
  server: 52.195.176.26
  type: trojan
  port: 2145
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: ' |45.37Mb'
  server: 87.121.162.249
  type: ss
  country: ğŸ‡§ğŸ‡¬BG
  port: 443
  password: JGv616hMWdjfuZ00jYfq7XkBHJZrOBrg
  cipher: chacha20-ietf-poly1305
- name: disney_FR |222.30Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 27092
  uuid: a0596ba6-72a3-4366-8992-77088da65bd8
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡§ğŸ‡·BR_714 |21.82Mb
  server: 38.180.16.86
  type: vmess
  country: ğŸ‡§ğŸ‡·BR
  port: 36236
  uuid: a58bc1a5-8c18-49ff-9453-c331b52f45dc
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_-ğŸ‡¯ğŸ‡µJP_710 |21.63Mb
  server: 160.16.138.24
  type: trojan
  port: 1331
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: ğŸ‡§ğŸ‡·BR_715 |23.13Mb
  server: 38.180.16.86
  type: vmess
  country: ğŸ‡§ğŸ‡·BR
  port: 36104
  uuid: E146A8CB-9D2F-449C-ADCA-8736FB
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ' |32.67Mb'
  server: 82.38.31.184
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡²ğŸ‡½MX_758 |174.94Mb
  server: 216.238.89.53
  type: vmess
  country: ğŸ‡²ğŸ‡½MX
  port: 57283
  uuid: 1a5aafc0-6482-451d-fe76-6875b7818579
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ' |11.85Mb'
  server: 23.95.75.146
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: NDRySIABARbErNIVsCNVkyYAHiBzhveT
  cipher: chacha20-ietf-poly1305
- name: ' |284.14Mb'
  server: 18.203.220.111
  type: ss
  country: ğŸ‡®ğŸ‡ªIE
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡ºğŸ‡¸US_765 |10.41Mb
  server: 74.117.196.232
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 37934
  uuid: 3b475934-cb2a-4d96-b260-5e50cca5d430
  alterId: 0
  cipher: auto
  network: ws
  servername: imafake.locker
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /speedtest
    headers:
      HOST: imafake.locker
- name: ğŸ‡­ğŸ‡°HK_745 |13.75Mb
  server: 47.242.140.52
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 48219
  uuid: 006893c6-79b1-4c44-94ff-b8bbea065f1f
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
  ws-opts:
    path: /arki?ed=2048
- name: ' |133.40Mb'
  server: 38.165.233.93
  type: ss
  country: ğŸ‡ºğŸ‡¸ US
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ğŸ‡­ğŸ‡°HK_755 |12.69Mb
  server: 112.118.116.66
  type: trojan
  country: ğŸ‡­ğŸ‡°HK
  port: 443
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: ğŸ‡ºğŸ‡¸US_767 |10.97Mb
  server: 74.117.196.232
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 37934
  uuid: 4f3cfda3-a255-40eb-8801-71f9fffb19d6
  alterId: 0
  cipher: auto
  network: ws
  servername: imafake.locker
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /speedtest
    headers:
      HOST: imafake.locker
- name: ğŸ‡ºğŸ‡¸US_768 |12.95Mb
  server: 74.117.196.232
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 37934
  uuid: 254551f6-ec28-4938-ad0e-0aa4aa1965ec
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /speedtest
- name: ğŸ‡²ğŸ‡¾MY_759 |24.55Mb
  server: 38.54.98.110
  type: vmess
  country: ğŸ‡²ğŸ‡¾MY
  port: 2052
  uuid: 665d9b8f-153d-4907-adac-de12afd9c851
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: ğŸ‡ºğŸ‡¸US_771 |13.26Mb
  server: 74.117.196.232
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 37934
  uuid: e3cb685e-7840-45cb-9d64-b2028d9b635e
  alterId: 0
  cipher: auto
  network: ws
  servername: imafake.locker
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /speedtest
    headers:
      HOST: imafake.locker
- name: ğŸ‡ºğŸ‡¸US_769 |15.12Mb
  server: 74.117.196.232
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 37934
  uuid: b2da9920-b0a7-4354-9e26-3833ab8d00d0
  alterId: 0
  cipher: auto
  network: ws
  servername: imafake.locker
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /speedtest
    headers:
      HOST: imafake.locker
- name: ğŸ‡ºğŸ‡¸US_773 |15.02Mb
  server: 74.117.196.232
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 37934
  uuid: 54a0bf6d-f2b5-4b2a-942c-798fb129527e
  alterId: 0
  cipher: auto
  network: ws
  servername: imafake.locker
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /speedtest
    headers:
      HOST: imafake.locker
- name: ğŸ‡ºğŸ‡¸US_775 |11.38Mb
  server: 74.117.196.232
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 37934
  uuid: 6d600864-32da-49fd-baf4-7df051762454
  alterId: 0
  cipher: auto
  network: ws
  servername: imafake.locker
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /speedtest
    headers:
      HOST: imafake.locker
- name: Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_766 |25.54Mb
  server: sw19.sesamebuta.top
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  uuid: 805ba514-bf2f-4d5d-df49-8417804e8de3
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /abcd
- name: ' |53.95Mb'
  server: 109.71.246.210
  type: ss
  country: ğŸ‡·ğŸ‡ºRU
  port: 56689
  password: YQCSKoCF3QazW8YlvDBWA4
  cipher: chacha20-ietf-poly1305
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - ' |249.31Mb'
  - ' |16.20Mb'
  - ' |148.63Mb'
  - ' |11.49Mb'
  - ' |32.59Mb'
  - disney_PT |12.44Mb
  - Relay_ |227.88Mb
  - _659 |24.85Mb
  - ' |48.06Mb'
  - _653 |29.37Mb
  - _670 |69.80Mb
  - _658 |20.36Mb
  - _661 |19.38Mb
  - _663 |20.37Mb
  - _680 |29.61Mb
  - Relay_-ğŸ‡²ğŸ‡¾MY_665 |30.37Mb
  - _667 |18.52Mb
  - _668 |17.58Mb
  - _678 |20.03Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_691 |10.98Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_692 |21.44Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_689 |10.24Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_694 |17.31Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_699 |10.86Mb
  - disney_US |70.82Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_700 |13.99Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_701 |11.06Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_703 |14.94Mb
  - ' |45.37Mb'
  - disney_FR |222.30Mb
  - ğŸ‡§ğŸ‡·BR_714 |21.82Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_710 |21.63Mb
  - ğŸ‡§ğŸ‡·BR_715 |23.13Mb
  - ' |32.67Mb'
  - ğŸ‡²ğŸ‡½MX_758 |174.94Mb
  - ' |11.85Mb'
  - ' |284.14Mb'
  - ğŸ‡ºğŸ‡¸US_765 |10.41Mb
  - ğŸ‡­ğŸ‡°HK_745 |13.75Mb
  - ' |133.40Mb'
  - ğŸ‡­ğŸ‡°HK_755 |12.69Mb
  - ğŸ‡ºğŸ‡¸US_767 |10.97Mb
  - ğŸ‡ºğŸ‡¸US_768 |12.95Mb
  - ğŸ‡²ğŸ‡¾MY_759 |24.55Mb
  - ğŸ‡ºğŸ‡¸US_771 |13.26Mb
  - ğŸ‡ºğŸ‡¸US_769 |15.12Mb
  - ğŸ‡ºğŸ‡¸US_773 |15.02Mb
  - ğŸ‡ºğŸ‡¸US_775 |11.38Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_766 |25.54Mb
  - ' |53.95Mb'
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - ' |249.31Mb'
  - ' |16.20Mb'
  - ' |148.63Mb'
  - ' |11.49Mb'
  - ' |32.59Mb'
  - disney_PT |12.44Mb
  - Relay_ |227.88Mb
  - _659 |24.85Mb
  - ' |48.06Mb'
  - _653 |29.37Mb
  - _670 |69.80Mb
  - _658 |20.36Mb
  - _661 |19.38Mb
  - _663 |20.37Mb
  - _680 |29.61Mb
  - Relay_-ğŸ‡²ğŸ‡¾MY_665 |30.37Mb
  - _667 |18.52Mb
  - _668 |17.58Mb
  - _678 |20.03Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_691 |10.98Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_692 |21.44Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_689 |10.24Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_694 |17.31Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_699 |10.86Mb
  - disney_US |70.82Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_700 |13.99Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_701 |11.06Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_703 |14.94Mb
  - ' |45.37Mb'
  - disney_FR |222.30Mb
  - ğŸ‡§ğŸ‡·BR_714 |21.82Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_710 |21.63Mb
  - ğŸ‡§ğŸ‡·BR_715 |23.13Mb
  - ' |32.67Mb'
  - ğŸ‡²ğŸ‡½MX_758 |174.94Mb
  - ' |11.85Mb'
  - ' |284.14Mb'
  - ğŸ‡ºğŸ‡¸US_765 |10.41Mb
  - ğŸ‡­ğŸ‡°HK_745 |13.75Mb
  - ' |133.40Mb'
  - ğŸ‡­ğŸ‡°HK_755 |12.69Mb
  - ğŸ‡ºğŸ‡¸US_767 |10.97Mb
  - ğŸ‡ºğŸ‡¸US_768 |12.95Mb
  - ğŸ‡²ğŸ‡¾MY_759 |24.55Mb
  - ğŸ‡ºğŸ‡¸US_771 |13.26Mb
  - ğŸ‡ºğŸ‡¸US_769 |15.12Mb
  - ğŸ‡ºğŸ‡¸US_773 |15.02Mb
  - ğŸ‡ºğŸ‡¸US_775 |11.38Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_766 |25.54Mb
  - ' |53.95Mb'
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
