port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: disney_netflix_US |158.01Mb
  server: 172.235.33.114
  type: vmess
  port: 10001
  uuid: 442a3923-eca1-4af0-b3ff-24a7ce0af68f
  alterId: 0
  cipher: auto
  network: tcp
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_US |46.64Mb
  server: us19-25.998998.best
  type: vmess
  port: 443
  udp: true
  uuid: 24254866-770c-41b4-9404-3f50524f425b
  alterId: 0
  cipher: auto
  network: ws
  servername: 24254866-770c-41b4-9404-3f50524f425b.mihomo.baby
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /saoihgreg9384gh8934
    headers:
      Host: 24254866-770c-41b4-9404-3f50524f425b.mihomo.baby
- name: disney_netflix_NL |256.28Mb
  server: 45.87.175.177
  type: ss
  port: 8080
  udp: true
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_NL |10.13Mb
  server: 82.38.31.179
  type: ss
  port: 8080
  udp: true
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_NL |269.21Mb
  server: 151.242.251.144
  type: ss
  port: 8080
  udp: true
  password: QCXDxuDlTTMD7jtgHUjIoj
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_NL |17.36Mb
  server: 109.71.246.210
  type: ss
  port: 56689
  udp: true
  password: YQCSKoCF3QazW8YlvDBWA4
  cipher: chacha20-ietf-poly1305
- name: Relay_-ğŸ‡ºğŸ‡¸US_141 |40.78Mb
  server: 141.193.213.199
  type: trojan
  port: 443
  udp: true
  password: a8a5b34d-fe46-487d-bd6a-d9f3101525fd
  sni: 26z68w0ecxbuyf89.ukgogo202511.top
  skip-cert-verify: true
  ws-opts:
    path: /images
    headers:
      Host: 26z68w0ecxbuyf89.ukgogo202511.top
  network: ws
- name: netflix_HK |19.05Mb
  server: 23.227.38.178
  type: trojan
  port: 443
  udp: true
  password: aff9928f-7ba3-45fb-b56d-4dec45653ca9
  sni: q6clkp794liy3y90.hktimecsgo.xyz
  skip-cert-verify: true
  ws-opts:
    path: /images
    headers:
      Host: q6clkp794liy3y90.hktimecsgo.xyz
  network: ws
- name: disney_netflix_PL |173.22Mb
  server: 45.15.126.19
  type: ss
  port: 443
  udp: true
  password: 6Ts2ZDTQAf3hkFoB8AFufDwsGrlF4e2t
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸ‡¬ğŸ‡§GB-ğŸ‡ºğŸ‡¸US_149 |217.95Mb
  server: 82.198.246.97
  type: vmess
  country: ğŸ‡¬ğŸ‡§GB
  port: 180
  uuid: d13fc2f5-3e05-4795-81eb-44143a09e552
  alterId: 0
  cipher: auto
  network: tcp
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_-ğŸ‡³ğŸ‡±NL_131 |22.04Mb
  server: 160.16.136.130
  type: trojan
  port: 4054
  password: 2cf6d686799e6fa95316394064f26c0a
  sni: www.nintendogames.net
- name: disney_netflix_FR |113.68Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 27092
  uuid: a0596ba6-72a3-4366-8992-77088da65bd8
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_PT |155.85Mb
  server: 185.231.233.112
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: netflix_KZ |27.63Mb
  server: 103.106.3.82
  type: ss
  port: 443
  udp: true
  password: 4SaCIazlgumYkM8FkPzlmwjpyWBDZFBk
  cipher: chacha20-ietf-poly1305
- name: disney_RU |27.41Mb
  server: 37.18.14.33
  type: trojan
  port: 443
  udp: true
  password: Qzy7tgpRhu
  sni: m.vk.com
  skip-cert-verify: true
- name: Relay_-ğŸ‡³ğŸ‡±NL_134 |51.24Mb
  server: 160.16.204.136
  type: trojan
  port: 2890
  password: 2cf6d686799e6fa95316394064f26c0a
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡³ğŸ‡±NL_136 |57.03Mb
  server: 160.16.196.59
  type: trojan
  port: 4054
  password: 2cf6d686799e6fa95316394064f26c0a
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡³ğŸ‡±NL_145 |41.91Mb
  server: 160.16.89.176
  type: trojan
  port: 2890
  password: 2cf6d686799e6fa95316394064f26c0a
  sni: www.nintendogames.net
- name: Relay_ğŸ‡®ğŸ‡ªIE-ğŸ‡ªğŸ‡¸ES_169 |10.03Mb
  server: f7c5a058-fa4a-4f7c-aed6-203efaf52286.f1eb10ae-1d82-4c6a-b4dd-bd9525520956.com
  type: trojan
  country: ğŸ‡®ğŸ‡ªIE
  port: 12014
  udp: true
  password: 05bf6017-75c3-44c1-b9bf-6a038107afde
  sni: sg4.yuanul.com
  skip-cert-verify: true
- name: Relay_ğŸ‡®ğŸ‡ªIE-ğŸ‡ªğŸ‡¸ES_159 |10.37Mb
  server: f7c5a058-fa4a-4f7c-aed6-203efaf52286.f1eb10ae-1d82-4c6a-b4dd-bd9525520956.com
  type: trojan
  country: ğŸ‡®ğŸ‡ªIE
  port: 12017
  udp: true
  password: 05bf6017-75c3-44c1-b9bf-6a038107afde
  sni: 63.yuanul.com
  skip-cert-verify: true
- name: disney_TW |10.23Mb
  server: f7c5a058-fa4a-4f7c-aed6-203efaf52286.f1eb10ae-1d82-4c6a-b4dd-bd9525520956.com
  type: trojan
  country: ğŸ‡®ğŸ‡ªIE
  port: 12102
  udp: true
  password: 05bf6017-75c3-44c1-b9bf-6a038107afde
  sni: 106.yuanul.com
  skip-cert-verify: true
- name: disney_US |53.67Mb
  server: f7c5a058-fa4a-4f7c-aed6-203efaf52286.f1eb10ae-1d82-4c6a-b4dd-bd9525520956.com
  type: trojan
  country: ğŸ‡®ğŸ‡ªIE
  port: 13206
  udp: true
  password: 05bf6017-75c3-44c1-b9bf-6a038107afde
  sni: 138.yuanul.com
  skip-cert-verify: true
- name: disney_US |53.22Mb
  server: f7c5a058-fa4a-4f7c-aed6-203efaf52286.f1eb10ae-1d82-4c6a-b4dd-bd9525520956.com
  type: trojan
  country: ğŸ‡®ğŸ‡ªIE
  port: 13202
  udp: true
  password: 05bf6017-75c3-44c1-b9bf-6a038107afde
  sni: 135.yuanul.com
  skip-cert-verify: true
- name: Relay_ğŸ‡®ğŸ‡ªIE-ğŸ‡®ğŸ‡·IR_165 |10.54Mb
  server: f7c5a058-fa4a-4f7c-aed6-203efaf52286.f1eb10ae-1d82-4c6a-b4dd-bd9525520956.com
  type: trojan
  country: ğŸ‡®ğŸ‡ªIE
  port: 10105
  udp: true
  password: 05bf6017-75c3-44c1-b9bf-6a038107afde
  sni: sni.eos-suzhou-4.cmecloud.cn
  skip-cert-verify: true
- name: Relay_ğŸ‡®ğŸ‡ªIE-ğŸ‡®ğŸ‡·IR_155 |23.04Mb
  server: f7c5a058-fa4a-4f7c-aed6-203efaf52286.f1eb10ae-1d82-4c6a-b4dd-bd9525520956.com
  type: trojan
  country: ğŸ‡®ğŸ‡ªIE
  port: 10101
  udp: true
  password: 05bf6017-75c3-44c1-b9bf-6a038107afde
  sni: sni.eos-suzhou-4.cmecloud.cn
  skip-cert-verify: true
- name: Relay_ğŸ‡®ğŸ‡ªIE-ğŸ‡ªğŸ‡¸ES_164 |10.03Mb
  server: f7c5a058-fa4a-4f7c-aed6-203efaf52286.f1eb10ae-1d82-4c6a-b4dd-bd9525520956.com
  type: trojan
  country: ğŸ‡®ğŸ‡ªIE
  port: 12012
  udp: true
  password: 05bf6017-75c3-44c1-b9bf-6a038107afde
  sni: tr.yuanul.com
  skip-cert-verify: true
- name: disney_TW |10.11Mb
  server: f7c5a058-fa4a-4f7c-aed6-203efaf52286.f1eb10ae-1d82-4c6a-b4dd-bd9525520956.com
  type: trojan
  country: ğŸ‡®ğŸ‡ªIE
  port: 12104
  udp: true
  password: 05bf6017-75c3-44c1-b9bf-6a038107afde
  sni: 108.yuanul.com
  skip-cert-verify: true
- name: Relay_ğŸ‡®ğŸ‡ªIE-ğŸ‡ªğŸ‡¸ES_158 |10.16Mb
  server: f7c5a058-fa4a-4f7c-aed6-203efaf52286.f1eb10ae-1d82-4c6a-b4dd-bd9525520956.com
  type: trojan
  country: ğŸ‡®ğŸ‡ªIE
  port: 12016
  udp: true
  password: 05bf6017-75c3-44c1-b9bf-6a038107afde
  sni: sg6.yuanul.com
  skip-cert-verify: true
- name: disney_netflix_NL |317.51Mb
  server: 151.242.251.144
  type: ss
  country: ğŸ‡®ğŸ‡· IR
  port: 8080
  password: 4a2rfixophdjffa8KVA4Aa
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸ‡®ğŸ‡ªIE-ğŸ‡®ğŸ‡·IR_176 |21.73Mb
  server: f7c5a058-fa4a-4f7c-aed6-203efaf52286.f1eb10ae-1d82-4c6a-b4dd-bd9525520956.com
  type: trojan
  country: ğŸ‡®ğŸ‡ªIE
  port: 10108
  udp: true
  password: 05bf6017-75c3-44c1-b9bf-6a038107afde
  sni: sni.eos-suzhou-4.cmecloud.cn
  skip-cert-verify: true
- name: Relay_ğŸ‡®ğŸ‡ªIE-ğŸ‡ºğŸ‡¸US_185 |43.42Mb
  server: f7c5a058-fa4a-4f7c-aed6-203efaf52286.f1eb10ae-1d82-4c6a-b4dd-bd9525520956.com
  type: trojan
  country: ğŸ‡®ğŸ‡ªIE
  port: 13207
  udp: true
  password: 05bf6017-75c3-44c1-b9bf-6a038107afde
  sni: 140.yuanul.com
  skip-cert-verify: true
- name: disney_US |43.57Mb
  server: f7c5a058-fa4a-4f7c-aed6-203efaf52286.f1eb10ae-1d82-4c6a-b4dd-bd9525520956.com
  type: trojan
  country: ğŸ‡®ğŸ‡ªIE
  port: 13203
  udp: true
  password: 05bf6017-75c3-44c1-b9bf-6a038107afde
  sni: 136.yuanul.com
  skip-cert-verify: true
- name: disney_US |43.08Mb
  server: f7c5a058-fa4a-4f7c-aed6-203efaf52286.f1eb10ae-1d82-4c6a-b4dd-bd9525520956.com
  type: trojan
  country: ğŸ‡®ğŸ‡ªIE
  port: 13205
  udp: true
  password: 05bf6017-75c3-44c1-b9bf-6a038107afde
  sni: 138.yuanul.com
  skip-cert-verify: true
- name: disney_US |42.68Mb
  server: f7c5a058-fa4a-4f7c-aed6-203efaf52286.f1eb10ae-1d82-4c6a-b4dd-bd9525520956.com
  type: trojan
  country: ğŸ‡®ğŸ‡ªIE
  port: 13208
  udp: true
  password: 05bf6017-75c3-44c1-b9bf-6a038107afde
  sni: 141.yuanul.com
  skip-cert-verify: true
- name: disney_netflix_US |53.91Mb
  server: f7c5a058-fa4a-4f7c-aed6-203efaf52286.f1eb10ae-1d82-4c6a-b4dd-bd9525520956.com
  type: trojan
  country: ğŸ‡®ğŸ‡ªIE
  port: 13204
  udp: true
  password: 05bf6017-75c3-44c1-b9bf-6a038107afde
  sni: 136.yuanul.com
  skip-cert-verify: true
- name: Relay_ğŸ‡®ğŸ‡ªIE-ğŸ‡®ğŸ‡·IR_190 |10.46Mb
  server: f7c5a058-fa4a-4f7c-aed6-203efaf52286.f1eb10ae-1d82-4c6a-b4dd-bd9525520956.com
  type: trojan
  country: ğŸ‡®ğŸ‡ªIE
  port: 10103
  udp: true
  password: 05bf6017-75c3-44c1-b9bf-6a038107afde
  sni: sni.eos-suzhou-4.cmecloud.cn
  skip-cert-verify: true
- name: disney_TW |10.50Mb
  server: f7c5a058-fa4a-4f7c-aed6-203efaf52286.f1eb10ae-1d82-4c6a-b4dd-bd9525520956.com
  type: trojan
  country: ğŸ‡®ğŸ‡ªIE
  port: 12103
  udp: true
  password: 05bf6017-75c3-44c1-b9bf-6a038107afde
  sni: 116.yuanul.com
  skip-cert-verify: true
- name: disney_US |43.76Mb
  server: f7c5a058-fa4a-4f7c-aed6-203efaf52286.f1eb10ae-1d82-4c6a-b4dd-bd9525520956.com
  type: trojan
  country: ğŸ‡®ğŸ‡ªIE
  port: 13201
  udp: true
  password: 05bf6017-75c3-44c1-b9bf-6a038107afde
  sni: 133.yuanul.com
  skip-cert-verify: true
- name: disney_netflix_US |20.10Mb
  server: 74.117.196.232
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 37934
  uuid: f1a513d2-c32a-49dc-8e64-d4f8a2f1e001
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /speedtest
- name: Relay_ğŸ‡¯ğŸ‡µJP-ğŸ‡¯ğŸ‡µJP_193 |11.01Mb
  server: xray.kk37005.tk
  type: vmess
  country: ğŸ‡¯ğŸ‡µJP
  port: 55919
  uuid: 2e7548bb-7c5b-4d97-d64d-1b2fe4050089
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: disney_netflix_US |109.58Mb
  server: cf.fovi.tk
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  uuid: bf67437e-6c90-45ca-abc2-c7240a5ce2aa
  alterId: 0
  cipher: auto
  network: ws
  servername: foxpol.fovi.tk
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /eisasqa
    headers:
      HOST: foxpol.fovi.tk
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - disney_netflix_US |158.01Mb
  - disney_netflix_US |46.64Mb
  - disney_netflix_NL |256.28Mb
  - disney_netflix_NL |10.13Mb
  - disney_netflix_NL |269.21Mb
  - disney_netflix_NL |17.36Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_141 |40.78Mb
  - netflix_HK |19.05Mb
  - disney_netflix_PL |173.22Mb
  - Relay_ğŸ‡¬ğŸ‡§GB-ğŸ‡ºğŸ‡¸US_149 |217.95Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_131 |22.04Mb
  - disney_netflix_FR |113.68Mb
  - disney_PT |155.85Mb
  - netflix_KZ |27.63Mb
  - disney_RU |27.41Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_134 |51.24Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_136 |57.03Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_145 |41.91Mb
  - Relay_ğŸ‡®ğŸ‡ªIE-ğŸ‡ªğŸ‡¸ES_169 |10.03Mb
  - Relay_ğŸ‡®ğŸ‡ªIE-ğŸ‡ªğŸ‡¸ES_159 |10.37Mb
  - disney_TW |10.23Mb
  - disney_US |53.67Mb
  - disney_US |53.22Mb
  - Relay_ğŸ‡®ğŸ‡ªIE-ğŸ‡®ğŸ‡·IR_165 |10.54Mb
  - Relay_ğŸ‡®ğŸ‡ªIE-ğŸ‡®ğŸ‡·IR_155 |23.04Mb
  - Relay_ğŸ‡®ğŸ‡ªIE-ğŸ‡ªğŸ‡¸ES_164 |10.03Mb
  - disney_TW |10.11Mb
  - Relay_ğŸ‡®ğŸ‡ªIE-ğŸ‡ªğŸ‡¸ES_158 |10.16Mb
  - disney_netflix_NL |317.51Mb
  - Relay_ğŸ‡®ğŸ‡ªIE-ğŸ‡®ğŸ‡·IR_176 |21.73Mb
  - Relay_ğŸ‡®ğŸ‡ªIE-ğŸ‡ºğŸ‡¸US_185 |43.42Mb
  - disney_US |43.57Mb
  - disney_US |43.08Mb
  - disney_US |42.68Mb
  - disney_netflix_US |53.91Mb
  - Relay_ğŸ‡®ğŸ‡ªIE-ğŸ‡®ğŸ‡·IR_190 |10.46Mb
  - disney_TW |10.50Mb
  - disney_US |43.76Mb
  - disney_netflix_US |20.10Mb
  - Relay_ğŸ‡¯ğŸ‡µJP-ğŸ‡¯ğŸ‡µJP_193 |11.01Mb
  - disney_netflix_US |109.58Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - disney_netflix_US |158.01Mb
  - disney_netflix_US |46.64Mb
  - disney_netflix_NL |256.28Mb
  - disney_netflix_NL |10.13Mb
  - disney_netflix_NL |269.21Mb
  - disney_netflix_NL |17.36Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_141 |40.78Mb
  - netflix_HK |19.05Mb
  - disney_netflix_PL |173.22Mb
  - Relay_ğŸ‡¬ğŸ‡§GB-ğŸ‡ºğŸ‡¸US_149 |217.95Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_131 |22.04Mb
  - disney_netflix_FR |113.68Mb
  - disney_PT |155.85Mb
  - netflix_KZ |27.63Mb
  - disney_RU |27.41Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_134 |51.24Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_136 |57.03Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_145 |41.91Mb
  - Relay_ğŸ‡®ğŸ‡ªIE-ğŸ‡ªğŸ‡¸ES_169 |10.03Mb
  - Relay_ğŸ‡®ğŸ‡ªIE-ğŸ‡ªğŸ‡¸ES_159 |10.37Mb
  - disney_TW |10.23Mb
  - disney_US |53.67Mb
  - disney_US |53.22Mb
  - Relay_ğŸ‡®ğŸ‡ªIE-ğŸ‡®ğŸ‡·IR_165 |10.54Mb
  - Relay_ğŸ‡®ğŸ‡ªIE-ğŸ‡®ğŸ‡·IR_155 |23.04Mb
  - Relay_ğŸ‡®ğŸ‡ªIE-ğŸ‡ªğŸ‡¸ES_164 |10.03Mb
  - disney_TW |10.11Mb
  - Relay_ğŸ‡®ğŸ‡ªIE-ğŸ‡ªğŸ‡¸ES_158 |10.16Mb
  - disney_netflix_NL |317.51Mb
  - Relay_ğŸ‡®ğŸ‡ªIE-ğŸ‡®ğŸ‡·IR_176 |21.73Mb
  - Relay_ğŸ‡®ğŸ‡ªIE-ğŸ‡ºğŸ‡¸US_185 |43.42Mb
  - disney_US |43.57Mb
  - disney_US |43.08Mb
  - disney_US |42.68Mb
  - disney_netflix_US |53.91Mb
  - Relay_ğŸ‡®ğŸ‡ªIE-ğŸ‡®ğŸ‡·IR_190 |10.46Mb
  - disney_TW |10.50Mb
  - disney_US |43.76Mb
  - disney_netflix_US |20.10Mb
  - Relay_ğŸ‡¯ğŸ‡µJP-ğŸ‡¯ğŸ‡µJP_193 |11.01Mb
  - disney_netflix_US |109.58Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
