port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: _204 |21.25Mb
  server: 137.184.174.93
  type: ss
  port: 8080
  udp: true
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: _216 |51.38Mb
  server: 156.146.38.167
  type: ss
  port: 443
  udp: true
  password: shadowsocks
  cipher: aes-128-gcm
- name: _201 |10.01Mb
  server: 62.100.205.100
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _200 |223.95Mb
  server: 45.87.175.28
  type: ss
  port: 8080
  udp: true
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: _208 |146.67Mb
  server: 82.38.31.190
  type: ss
  port: 8080
  udp: true
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_GB |58.10Mb
  server: 141.98.101.178
  type: ss
  port: 443
  udp: true
  password: shadowsocks
  cipher: aes-128-gcm
- name: _212 |240.22Mb
  server: 151.242.251.142
  type: ss
  port: 8080
  udp: true
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: disney_ES |10.02Mb
  server: 145.249.109.121
  type: ss
  port: 25512
  udp: true
  password: smSMfR9jqLgMkHuQtxSIWh
  cipher: chacha20-ietf-poly1305
- name: _218 |124.25Mb
  server: 82.38.31.202
  type: ss
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: _225 |53.03Mb
  server: 156.146.38.169
  type: ss
  port: 443
  udp: true
  password: shadowsocks
  cipher: aes-128-gcm
- name: Relay_-ğŸ‡¨ğŸ‡¦CA_231 |67.96Mb
  server: 79.127.200.169
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_NL |111.91Mb
  server: 193.29.139.177
  type: ss
  port: 8080
  udp: true
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: _214 |17.63Mb
  server: 95.164.116.33
  type: ss
  port: 443
  password: pQmnC03JObbPhdh5FBJHgD6jnTLchsRA
  cipher: chacha20-ietf-poly1305
- name: _235 |46.11Mb
  server: 173.234.29.2
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _228 |10.01Mb
  server: 196.196.192.58
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _227 |44.50Mb
  server: 185.82.73.212
  type: ss
  port: 8444
  udp: true
  password: _bypfvq6ra7g4n5yCCR9DoVeGya2XUUS
  cipher: chacha20-ietf-poly1305
- name: Relay_-ğŸ‡ªğŸ‡ªEE_199 |12.82Mb
  server: est01-ss01.tcp-reset-club.net
  type: ss
  port: 8444
  udp: true
  password: AWNeHjukGQWwuFXadw2r6qH7gh4hZ9cj
  cipher: chacha20-ietf-poly1305
- name: _233 |193.72Mb
  server: 82.38.31.214
  type: ss
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: _222 |67.12Mb
  server: 89.221.225.15
  type: ss
  port: 443
  udp: true
  password: yCbQ4bry4otfifK7oel71NaXpPL9pYJb
  cipher: chacha20-ietf-poly1305
- name: _234 |207.45Mb
  server: 151.242.251.152
  type: ss
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: _249 |61.15Mb
  server: 103.35.189.136
  type: ss
  port: 443
  udp: true
  password: SS2QvbC9nqLp2sXXZo0BVy4slcErRuCt
  cipher: chacha20-ietf-poly1305
- name: _246 |51.14Mb
  server: 156.146.38.170
  type: ss
  port: 443
  udp: true
  password: shadowsocks
  cipher: aes-128-gcm
- name: Relay_-ğŸ‡µğŸ‡±PL_236 |20.69Mb
  server: 193.135.174.135
  type: ss
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _242 |232.37Mb
  server: 82.38.31.179
  type: ss
  port: 8080
  udp: true
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: _240 |14.73Mb
  server: 185.192.124.188
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: _257 |10.52Mb
  server: 147.78.1.230
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: _250 |43.58Mb
  server: 138.186.143.32
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: _244 |26.87Mb
  server: 147.78.0.182
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_GB |740.94Mb
  server: 146.70.61.37
  type: ss
  port: 8080
  udp: true
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: _255 |160.03Mb
  server: 138.186.143.32
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: _269 |387.41Mb
  server: 172.233.229.91
  type: vmess
  port: 14102
  udp: true
  uuid: 27ba87fc-583f-4763-9060-83cf0b9264db
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: _232 |45.19Mb
  server: 156.59.243.6
  type: ss
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: disney_PY |17.75Mb
  server: 38.165.233.93
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: _265 |375.39Mb
  server: 51.15.23.166
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: _267 |243.11Mb
  server: 45.14.245.2
  type: ss
  port: 443
  password: 17ZDORWIliQHuO6WRGHChXYMzdRtAYVP
  cipher: chacha20-ietf-poly1305
- name: _251 |10.03Mb
  server: 103.149.182.158
  type: ss
  port: 8388
  password: asd123456
  cipher: chacha20-ietf
- name: _256 |29.80Mb
  server: 194.246.114.101
  type: ss
  port: 443
  udp: true
  password: HaNqw9pIE4jcx98sg7UQgHeGNTM4R2pk
  cipher: chacha20-ietf-poly1305
- name: _261 |12.97Mb
  server: 172.105.199.111
  type: ss
  port: 8080
  udp: true
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: Relay_-ğŸ‡¯ğŸ‡µJP_284 |10.28Mb
  server: 160.16.117.182
  type: trojan
  port: 3169
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: _285 |10.83Mb
  server: 160.16.106.144
  type: trojan
  port: 2760
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
  skip-cert-verify: true
- name: _260 |22.62Mb
  server: 128.199.172.224
  type: ss
  port: 8080
  udp: true
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: ğŸ‡¨ğŸ‡¦CA_301 |45.66Mb
  server: 193.203.203.66
  type: ss
  country: ğŸ‡¨ğŸ‡¦CA
  port: 443
  password: S6jUK9Fw5fMHgNqlqXObHZWv8Tf4nEkm
  cipher: chacha20-ietf-poly1305
- name: _286 |10.92Mb
  server: 160.16.116.227
  type: trojan
  port: 2760
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
  skip-cert-verify: true
- name: _292 |10.86Mb
  server: 160.16.131.243
  type: trojan
  port: 2760
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
  skip-cert-verify: true
- name: ğŸ‡§ğŸ‡·BR_300 |21.78Mb
  server: 185.192.124.188
  type: ss
  country: ğŸ‡§ğŸ‡·BR
  port: 990
  password: f8f7aCzcPKbsF8p3
  cipher: chacha20-ietf-poly1305
- name: disney_HK |23.07Mb
  server: 58.152.30.31
  type: trojan
  port: 443
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: Relay_-ğŸ‡¯ğŸ‡µJP_298 |11.53Mb
  server: 160.16.117.182
  type: trojan
  port: 3093
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: ğŸ‡¨ğŸ‡¦CA_302 |38.35Mb
  server: 185.213.23.63
  type: ss
  country: ğŸ‡¨ğŸ‡¦CA
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: disney_HK |21.11Mb
  server: 219.79.214.159
  type: trojan
  port: 443
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: disney_CH |190.66Mb
  server: 138.124.67.26
  type: ss
  country: ğŸ‡¨ğŸ‡­CH
  port: 25572
  password: nqcIfYHlpMn3jzqkNDjKaG
  cipher: chacha20-ietf-poly1305
- name: disney_DE |275.68Mb
  server: 89.163.140.136
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: _299 |26.71Mb
  server: 112.118.116.8
  type: trojan
  port: 443
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: ğŸ‡©ğŸ‡ªDE_310 |245.01Mb
  server: 3.66.69.180
  type: trojan
  country: ğŸ‡©ğŸ‡ªDE
  port: 22223
  udp: true
  password: telegram-id-directvpn
  sni: trojan.burgerip.co.uk
  skip-cert-verify: true
- name: disney_netflix_NL |136.87Mb
  server: 82.38.31.208
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡©ğŸ‡ªDE_311 |313.97Mb
  server: 3.66.69.180
  type: trojan
  country: ğŸ‡©ğŸ‡ªDE
  port: 22222
  udp: true
  password: telegram-id-privatevpns
  sni: trojan.burgerip.co.uk
  skip-cert-verify: true
- name: disney_HK |66.27Mb
  server: v9.hdacd.com
  type: vmess
  port: 30809
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: disney_netflix_GB |78.44Mb
  server: 141.98.101.182
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: shadowsocks
  cipher: aes-128-gcm
- name: ğŸ‡±ğŸ‡¹LT_327 |197.43Mb
  server: 45.87.175.185
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_328 |221.97Mb
  server: 45.87.175.180
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: QCXDxuDlTTMD7jtgHUjIoj
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_329 |217.26Mb
  server: 45.87.175.185
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_NL |214.07Mb
  server: 45.87.175.183
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: disney_HK |29.66Mb
  server: 45.207.157.29
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 13852
  uuid: 845764df-ecb3-4b13-bed2-bf1551b68e9a
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡²ğŸ‡½MX_336 |38.20Mb
  server: 216.238.87.47
  type: vmess
  country: ğŸ‡²ğŸ‡½MX
  port: 27502
  uuid: b8155ce4-7e08-4c40-800f-8671312b7124
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡±ğŸ‡¹LT_333 |49.78Mb
  server: 45.87.175.175
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: QCXDxuDlTTMD7jtgHUjIoj
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡­ğŸ‡°HK_316 |112.97Mb
  server: 8.218.116.26
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 32228
  uuid: e4767e9f-ed00-4f31-a984-a918bdd9b09c
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡­ğŸ‡°HK_317 |123.03Mb
  server: 8.218.105.196
  type: vmess
  country: ğŸ‡­ğŸ‡°HK
  port: 52752
  uuid: 925bdbf5-72be-4437-bebf-441c61089f6b
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡³ğŸ‡±NL_339 |47.09Mb
  server: 178.23.190.238
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 443
  password: uo7EbtqIwgZXXHmMv5LbLcOxptyPlNkh
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡³ğŸ‡±NL_341 |147.22Mb
  server: 193.29.139.141
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 8080
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡µğŸ‡¹PT_345 |58.17Mb
  server: 185.113.143.186
  type: ss
  country: ğŸ‡µğŸ‡¹PT
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸZZ-ğŸ‡®ğŸ‡³IN_352 |37.74Mb
  server: 104.18.14.55
  type: vmess
  country: ğŸZZ
  port: 2052
  uuid: e6447786-8c85-443c-8017-7feaa673ff45
  alterId: 0
  cipher: auto
  network: ws
  servername: in4.123417.xyz
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
  ws-opts:
    path: /
    headers:
      HOST: in4.123417.xyz
- name: netflix_US |34.64Mb
  server: hgtrojan.zabc.net
  type: vmess
  country: ğŸZZ
  port: 2083
  uuid: e6395c20-4571-4b34-d6b1-55a5d36e49ea
  alterId: 0
  cipher: auto
  network: ws
  servername: hgtrojan.zabc.net
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /e6395c20
    headers:
      HOST: hgtrojan.zabc.net
- name: disney_PT |212.72Mb
  server: 185.231.233.112
  type: ss
  country: ğŸ ZZ
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: disney_SG |17.19Mb
  server: 103.248.229.90
  type: ss
  country: ğŸ‡¸ğŸ‡¬SG
  port: 24203
  password: 1GJth1Qjic
  cipher: aes-256-gcm
- name: disney_SG |20.65Mb
  server: 103.248.229.90
  type: ss
  country: ğŸ‡¸ğŸ‡¬SG
  port: 40413
  password: hGpFS8dtyN
  cipher: aes-256-gcm
- name: ğŸ‡¸ğŸ‡¬SG_348 |11.84Mb
  server: 103.248.229.90
  type: ss
  country: ğŸ‡¸ğŸ‡¬SG
  port: 35817
  password: 4VqrUWV7hm
  cipher: aes-256-gcm
- name: ğŸ‡¸ğŸ‡¬SG_349 |13.75Mb
  server: 68.183.227.45
  type: ss
  country: ğŸ‡¸ğŸ‡¬SG
  port: 8080
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: Relay_ğŸ‡¯ğŸ‡µJP-ğŸ‡¯ğŸ‡µJP_323 |10.52Mb
  server: xray.kk37005.tk
  type: vmess
  country: ğŸ‡¯ğŸ‡µJP
  port: 55919
  uuid: 2e7548bb-7c5b-4d97-d64d-1b2fe4050089
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: ğŸ‡±ğŸ‡¹LT_330 |47.92Mb
  server: ltnl16.saint.ydns.eu
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: disney_LV |54.97Mb
  server: 46.183.217.204
  type: ss
  country: ğŸ‡±ğŸ‡» LV
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: netflix_DE |42.82Mb
  server: 194.59.183.134
  type: ss
  port: 46114
  udp: true
  password: lejSRyqa033OEPmEQsvRsl
  cipher: chacha20-ietf-poly1305
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - _204 |21.25Mb
  - _216 |51.38Mb
  - _201 |10.01Mb
  - _200 |223.95Mb
  - _208 |146.67Mb
  - disney_netflix_GB |58.10Mb
  - _212 |240.22Mb
  - disney_ES |10.02Mb
  - _218 |124.25Mb
  - _225 |53.03Mb
  - Relay_-ğŸ‡¨ğŸ‡¦CA_231 |67.96Mb
  - disney_netflix_NL |111.91Mb
  - _214 |17.63Mb
  - _235 |46.11Mb
  - _228 |10.01Mb
  - _227 |44.50Mb
  - Relay_-ğŸ‡ªğŸ‡ªEE_199 |12.82Mb
  - _233 |193.72Mb
  - _222 |67.12Mb
  - _234 |207.45Mb
  - _249 |61.15Mb
  - _246 |51.14Mb
  - Relay_-ğŸ‡µğŸ‡±PL_236 |20.69Mb
  - _242 |232.37Mb
  - _240 |14.73Mb
  - _257 |10.52Mb
  - _250 |43.58Mb
  - _244 |26.87Mb
  - disney_netflix_GB |740.94Mb
  - _255 |160.03Mb
  - _269 |387.41Mb
  - _232 |45.19Mb
  - disney_PY |17.75Mb
  - _265 |375.39Mb
  - _267 |243.11Mb
  - _251 |10.03Mb
  - _256 |29.80Mb
  - _261 |12.97Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_284 |10.28Mb
  - _285 |10.83Mb
  - _260 |22.62Mb
  - ğŸ‡¨ğŸ‡¦CA_301 |45.66Mb
  - _286 |10.92Mb
  - _292 |10.86Mb
  - ğŸ‡§ğŸ‡·BR_300 |21.78Mb
  - disney_HK |23.07Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_298 |11.53Mb
  - ğŸ‡¨ğŸ‡¦CA_302 |38.35Mb
  - disney_HK |21.11Mb
  - disney_CH |190.66Mb
  - disney_DE |275.68Mb
  - _299 |26.71Mb
  - ğŸ‡©ğŸ‡ªDE_310 |245.01Mb
  - disney_netflix_NL |136.87Mb
  - ğŸ‡©ğŸ‡ªDE_311 |313.97Mb
  - disney_HK |66.27Mb
  - disney_netflix_GB |78.44Mb
  - ğŸ‡±ğŸ‡¹LT_327 |197.43Mb
  - ğŸ‡±ğŸ‡¹LT_328 |221.97Mb
  - ğŸ‡±ğŸ‡¹LT_329 |217.26Mb
  - disney_netflix_NL |214.07Mb
  - disney_HK |29.66Mb
  - ğŸ‡²ğŸ‡½MX_336 |38.20Mb
  - ğŸ‡±ğŸ‡¹LT_333 |49.78Mb
  - ğŸ‡­ğŸ‡°HK_316 |112.97Mb
  - ğŸ‡­ğŸ‡°HK_317 |123.03Mb
  - ğŸ‡³ğŸ‡±NL_339 |47.09Mb
  - ğŸ‡³ğŸ‡±NL_341 |147.22Mb
  - ğŸ‡µğŸ‡¹PT_345 |58.17Mb
  - Relay_ğŸZZ-ğŸ‡®ğŸ‡³IN_352 |37.74Mb
  - netflix_US |34.64Mb
  - disney_PT |212.72Mb
  - disney_SG |17.19Mb
  - disney_SG |20.65Mb
  - ğŸ‡¸ğŸ‡¬SG_348 |11.84Mb
  - ğŸ‡¸ğŸ‡¬SG_349 |13.75Mb
  - Relay_ğŸ‡¯ğŸ‡µJP-ğŸ‡¯ğŸ‡µJP_323 |10.52Mb
  - ğŸ‡±ğŸ‡¹LT_330 |47.92Mb
  - disney_LV |54.97Mb
  - netflix_DE |42.82Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - _204 |21.25Mb
  - _216 |51.38Mb
  - _201 |10.01Mb
  - _200 |223.95Mb
  - _208 |146.67Mb
  - disney_netflix_GB |58.10Mb
  - _212 |240.22Mb
  - disney_ES |10.02Mb
  - _218 |124.25Mb
  - _225 |53.03Mb
  - Relay_-ğŸ‡¨ğŸ‡¦CA_231 |67.96Mb
  - disney_netflix_NL |111.91Mb
  - _214 |17.63Mb
  - _235 |46.11Mb
  - _228 |10.01Mb
  - _227 |44.50Mb
  - Relay_-ğŸ‡ªğŸ‡ªEE_199 |12.82Mb
  - _233 |193.72Mb
  - _222 |67.12Mb
  - _234 |207.45Mb
  - _249 |61.15Mb
  - _246 |51.14Mb
  - Relay_-ğŸ‡µğŸ‡±PL_236 |20.69Mb
  - _242 |232.37Mb
  - _240 |14.73Mb
  - _257 |10.52Mb
  - _250 |43.58Mb
  - _244 |26.87Mb
  - disney_netflix_GB |740.94Mb
  - _255 |160.03Mb
  - _269 |387.41Mb
  - _232 |45.19Mb
  - disney_PY |17.75Mb
  - _265 |375.39Mb
  - _267 |243.11Mb
  - _251 |10.03Mb
  - _256 |29.80Mb
  - _261 |12.97Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_284 |10.28Mb
  - _285 |10.83Mb
  - _260 |22.62Mb
  - ğŸ‡¨ğŸ‡¦CA_301 |45.66Mb
  - _286 |10.92Mb
  - _292 |10.86Mb
  - ğŸ‡§ğŸ‡·BR_300 |21.78Mb
  - disney_HK |23.07Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_298 |11.53Mb
  - ğŸ‡¨ğŸ‡¦CA_302 |38.35Mb
  - disney_HK |21.11Mb
  - disney_CH |190.66Mb
  - disney_DE |275.68Mb
  - _299 |26.71Mb
  - ğŸ‡©ğŸ‡ªDE_310 |245.01Mb
  - disney_netflix_NL |136.87Mb
  - ğŸ‡©ğŸ‡ªDE_311 |313.97Mb
  - disney_HK |66.27Mb
  - disney_netflix_GB |78.44Mb
  - ğŸ‡±ğŸ‡¹LT_327 |197.43Mb
  - ğŸ‡±ğŸ‡¹LT_328 |221.97Mb
  - ğŸ‡±ğŸ‡¹LT_329 |217.26Mb
  - disney_netflix_NL |214.07Mb
  - disney_HK |29.66Mb
  - ğŸ‡²ğŸ‡½MX_336 |38.20Mb
  - ğŸ‡±ğŸ‡¹LT_333 |49.78Mb
  - ğŸ‡­ğŸ‡°HK_316 |112.97Mb
  - ğŸ‡­ğŸ‡°HK_317 |123.03Mb
  - ğŸ‡³ğŸ‡±NL_339 |47.09Mb
  - ğŸ‡³ğŸ‡±NL_341 |147.22Mb
  - ğŸ‡µğŸ‡¹PT_345 |58.17Mb
  - Relay_ğŸZZ-ğŸ‡®ğŸ‡³IN_352 |37.74Mb
  - netflix_US |34.64Mb
  - disney_PT |212.72Mb
  - disney_SG |17.19Mb
  - disney_SG |20.65Mb
  - ğŸ‡¸ğŸ‡¬SG_348 |11.84Mb
  - ğŸ‡¸ğŸ‡¬SG_349 |13.75Mb
  - Relay_ğŸ‡¯ğŸ‡µJP-ğŸ‡¯ğŸ‡µJP_323 |10.52Mb
  - ğŸ‡±ğŸ‡¹LT_330 |47.92Mb
  - disney_LV |54.97Mb
  - netflix_DE |42.82Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
