port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: disney_netflix_US |63.29Mb
  server: 107.175.87.207
  type: ss
  port: 10011
  udp: true
  password: 86039b71-ba82-4ca8-838e-87086ae666de
  cipher: chacha20-ietf-poly1305
- name: disney_US |35.76Mb
  server: 216.167.49.157
  type: vmess
  port: 36108
  uuid: ac9340c1-61d7-47bd-c5a2-9b888857dec6
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
- name: disney_netflix_NL |257.88Mb
  server: 45.87.175.181
  type: ss
  port: 8080
  udp: true
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: Relay_-ğŸ‡³ğŸ‡±NL_416 |220.64Mb
  server: 151.242.251.137
  type: ss
  port: 8080
  password: o5osZg269v5zHpYjr1xY9s
  cipher: chacha20-ietf-poly1305
- name: disney_PT |464.47Mb
  server: 185.231.233.112
  type: ss
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: _429 |221.90Mb
  server: 104.168.94.41
  type: vmess
  port: 32301
  uuid: a2235b72-fd9c-404f-be5a-53b2de0cb798
  alterId: 0
  cipher: auto
  network: http
  http-opts:
    method: GET
    path:
    - /
  h2-opts: {}
- name: netflix_ES |10.37Mb
  server: 213.159.67.124
  type: ss
  port: 443
  password: mbhqsStnFQT1cTZYCdsmkugGUC6GT6rp
  cipher: chacha20-ietf-poly1305
- name: Relay_-ğŸ‡ºğŸ‡¸US_444 |12.41Mb
  server: gy3.hdcloud.link
  type: trojan
  port: 443
  udp: true
  password: 9b6419f8-8120-442e-a48c-6bf52aef0abf
  network: grpc
  grpc-opts:
    grpc-service-name: GunService
- name: disney_netflix_LV |83.02Mb
  server: 31.56.117.73
  type: vmess
  port: 28573
  uuid: aa521837-6bfb-47dd-c87c-ec730a974020
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
- name: _419 |49.50Mb
  server: 154.90.62.168
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: Relay_-ğŸ‡³ğŸ‡±NL_442 |10.58Mb
  server: 160.16.214.6
  type: trojan
  port: 4054
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: _432 |16.65Mb
  server: 47.76.31.123
  type: vmess
  port: 46356
  uuid: 2dec1dc2-e102-402f-e759-a719a0bc9111
  alterId: 0
  cipher: auto
  network: http
  http-opts:
    method: GET
    path:
    - /
  h2-opts: {}
- name: _439 |58.04Mb
  server: 152.70.92.69
  type: vmess
  port: 80
  uuid: bb9c3993-a4b9-4dad-aeb9-ac86371ae68b
  alterId: 0
  cipher: auto
  network: http
  http-opts:
    path:
    - /
  h2-opts: {}
- name: Relay_-ğŸ‡³ğŸ‡±NL_452 |12.28Mb
  server: 153.121.73.102
  type: trojan
  port: 2760
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: disney_HK |27.67Mb
  server: 58.152.25.20
  type: trojan
  port: 443
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: Relay_-ğŸ‡²ğŸ‡¾MY_430 |25.64Mb
  server: ml0724.ysds168.shop
  type: vmess
  port: 2052
  udp: true
  uuid: 665d9b8f-153d-4907-adac-de12afd9c851
  alterId: 0
  cipher: auto
  servername: ml0724.ysds168.shop
  http-opts: {}
  h2-opts: {}
  tls: true
- name: disney_HK |14.51Mb
  server: 58.152.18.192
  type: trojan
  port: 443
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: ğŸ‡§ğŸ‡¬BG_460 |44.41Mb
  server: 87.121.162.249
  type: ss
  country: ğŸ‡§ğŸ‡¬BG
  port: 443
  password: JGv616hMWdjfuZ00jYfq7XkBHJZrOBrg
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡§ğŸ‡·BR_461 |23.71Mb
  server: 38.180.16.86
  type: vmess
  country: ğŸ‡§ğŸ‡·BR
  port: 36104
  uuid: E146A8CB-9D2F-449C-ADCA-8736FB
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_FR |145.67Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 27092
  uuid: a0596ba6-72a3-4366-8992-77088da65bd8
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡§ğŸ‡·BR_462 |19.68Mb
  server: 38.180.16.86
  type: vmess
  country: ğŸ‡§ğŸ‡·BR
  port: 36236
  uuid: a58bc1a5-8c18-49ff-9453-c331b52f45dc
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡²ğŸ‡½MX_565 |42.63Mb
  server: 216.238.89.53
  type: vmess
  country: ğŸ‡²ğŸ‡½MX
  port: 57283
  uuid: 1a5aafc0-6482-451d-fe76-6875b7818579
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_US |39.24Mb
  server: 23.95.75.146
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: NDRySIABARbErNIVsCNVkyYAHiBzhveT
  cipher: chacha20-ietf-poly1305
- name: netflix_IE |295.37Mb
  server: 18.203.220.111
  type: ss
  country: ğŸ‡®ğŸ‡ªIE
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡±ğŸ‡¹LT_564 |16.30Mb
  server: 45.87.175.166
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 443
  password: 1RWwXhwfAB5gAEozU4G2Pg
  cipher: chacha20-ietf-poly1305
- name: disney_HK |28.52Mb
  server: 112.118.116.66
  type: trojan
  country: ğŸ‡­ğŸ‡°HK
  port: 443
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: ğŸ‡ºğŸ‡¸US_571 |66.47Mb
  server: 74.117.196.232
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 37934
  uuid: 254551f6-ec28-4938-ad0e-0aa4aa1965ec
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /speedtest
- name: ğŸ‡ºğŸ‡¸US_572 |36.22Mb
  server: 74.117.196.232
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 37934
  uuid: f1a513d2-c32a-49dc-8e64-d4f8a2f1e001
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /speedtest
- name: ğŸ‡ºğŸ‡¸US_573 |18.09Mb
  server: 74.117.196.232
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 37934
  uuid: 6d600864-32da-49fd-baf4-7df051762454
  alterId: 0
  cipher: auto
  network: ws
  servername: imafake.locker
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /speedtest
    headers:
      HOST: imafake.locker
- name: ğŸ‡ºğŸ‡¸US_574 |36.59Mb
  server: 74.117.196.232
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 37934
  uuid: b01d1e26-2f84-48da-88a1-1d06a77857f3
  alterId: 0
  cipher: auto
  network: ws
  servername: imafake.locker
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /speedtest
    headers:
      HOST: imafake.locker
- name: ğŸ‡²ğŸ‡¾MY_566 |29.69Mb
  server: 38.54.98.110
  type: vmess
  country: ğŸ‡²ğŸ‡¾MY
  port: 2052
  uuid: 665d9b8f-153d-4907-adac-de12afd9c851
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: ğŸ‡ºğŸ‡¸US_575 |37.76Mb
  server: 74.117.196.232
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 37934
  uuid: e3cb685e-7840-45cb-9d64-b2028d9b635e
  alterId: 0
  cipher: auto
  network: ws
  servername: imafake.locker
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /speedtest
    headers:
      HOST: imafake.locker
- name: ğŸ‡ºğŸ‡¸US_576 |36.77Mb
  server: 74.117.196.232
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 37934
  uuid: b2da9920-b0a7-4354-9e26-3833ab8d00d0
  alterId: 0
  cipher: auto
  network: ws
  servername: imafake.locker
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /speedtest
    headers:
      HOST: imafake.locker
- name: disney_PY |15.38Mb
  server: 38.165.233.93
  type: ss
  country: ğŸ‡ºğŸ‡¸ US
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ğŸ‡ºğŸ‡¸US_577 |36.40Mb
  server: 74.117.196.232
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 37934
  uuid: 3b475934-cb2a-4d96-b260-5e50cca5d430
  alterId: 0
  cipher: auto
  network: ws
  servername: imafake.locker
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /speedtest
    headers:
      HOST: imafake.locker
- name: ğŸ‡ºğŸ‡¸US_578 |36.43Mb
  server: 74.117.196.232
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 37934
  uuid: 4f3cfda3-a255-40eb-8801-71f9fffb19d6
  alterId: 0
  cipher: auto
  network: ws
  servername: imafake.locker
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /speedtest
    headers:
      HOST: imafake.locker
- name: Relay_-ğŸ‡ºğŸ‡¸US_449 |10.03Mb
  server: jp3.t.sgateway.link
  type: trojan
  port: 5223
  password: Q9gofGxinwLv0TfDfdKmdttdPGxrhKQS
  sni: pod-jp-z1.psusercontent.com
- name: disney_netflix_US |78.81Mb
  server: 74.117.196.232
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 37934
  uuid: 54a0bf6d-f2b5-4b2a-942c-798fb129527e
  alterId: 0
  cipher: auto
  network: ws
  servername: imafake.locker
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /speedtest
    headers:
      HOST: imafake.locker
- name: Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_570 |37.82Mb
  server: sw19.sesamebuta.top
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  uuid: 805ba514-bf2f-4d5d-df49-8417804e8de3
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /abcd
- name: ğŸ‡ºğŸ‡¸US_581 |22.51Mb
  server: 45.136.12.37
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 38141
  uuid: fd291be6-b48d-43a1-da38-66c7f80e2f80
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_-ğŸ‡°ğŸ‡·KR_413 |14.52Mb
  server: p141.panda001.net
  type: ss
  port: 4652
  udp: true
  password: qwerREWQ@@
  cipher: aes-256-cfb
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - disney_netflix_US |63.29Mb
  - disney_US |35.76Mb
  - disney_netflix_NL |257.88Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_416 |220.64Mb
  - disney_PT |464.47Mb
  - _429 |221.90Mb
  - netflix_ES |10.37Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_444 |12.41Mb
  - disney_netflix_LV |83.02Mb
  - _419 |49.50Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_442 |10.58Mb
  - _432 |16.65Mb
  - _439 |58.04Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_452 |12.28Mb
  - disney_HK |27.67Mb
  - Relay_-ğŸ‡²ğŸ‡¾MY_430 |25.64Mb
  - disney_HK |14.51Mb
  - ğŸ‡§ğŸ‡¬BG_460 |44.41Mb
  - ğŸ‡§ğŸ‡·BR_461 |23.71Mb
  - disney_netflix_FR |145.67Mb
  - ğŸ‡§ğŸ‡·BR_462 |19.68Mb
  - ğŸ‡²ğŸ‡½MX_565 |42.63Mb
  - disney_netflix_US |39.24Mb
  - netflix_IE |295.37Mb
  - ğŸ‡±ğŸ‡¹LT_564 |16.30Mb
  - disney_HK |28.52Mb
  - ğŸ‡ºğŸ‡¸US_571 |66.47Mb
  - ğŸ‡ºğŸ‡¸US_572 |36.22Mb
  - ğŸ‡ºğŸ‡¸US_573 |18.09Mb
  - ğŸ‡ºğŸ‡¸US_574 |36.59Mb
  - ğŸ‡²ğŸ‡¾MY_566 |29.69Mb
  - ğŸ‡ºğŸ‡¸US_575 |37.76Mb
  - ğŸ‡ºğŸ‡¸US_576 |36.77Mb
  - disney_PY |15.38Mb
  - ğŸ‡ºğŸ‡¸US_577 |36.40Mb
  - ğŸ‡ºğŸ‡¸US_578 |36.43Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_449 |10.03Mb
  - disney_netflix_US |78.81Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_570 |37.82Mb
  - ğŸ‡ºğŸ‡¸US_581 |22.51Mb
  - Relay_-ğŸ‡°ğŸ‡·KR_413 |14.52Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - disney_netflix_US |63.29Mb
  - disney_US |35.76Mb
  - disney_netflix_NL |257.88Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_416 |220.64Mb
  - disney_PT |464.47Mb
  - _429 |221.90Mb
  - netflix_ES |10.37Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_444 |12.41Mb
  - disney_netflix_LV |83.02Mb
  - _419 |49.50Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_442 |10.58Mb
  - _432 |16.65Mb
  - _439 |58.04Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_452 |12.28Mb
  - disney_HK |27.67Mb
  - Relay_-ğŸ‡²ğŸ‡¾MY_430 |25.64Mb
  - disney_HK |14.51Mb
  - ğŸ‡§ğŸ‡¬BG_460 |44.41Mb
  - ğŸ‡§ğŸ‡·BR_461 |23.71Mb
  - disney_netflix_FR |145.67Mb
  - ğŸ‡§ğŸ‡·BR_462 |19.68Mb
  - ğŸ‡²ğŸ‡½MX_565 |42.63Mb
  - disney_netflix_US |39.24Mb
  - netflix_IE |295.37Mb
  - ğŸ‡±ğŸ‡¹LT_564 |16.30Mb
  - disney_HK |28.52Mb
  - ğŸ‡ºğŸ‡¸US_571 |66.47Mb
  - ğŸ‡ºğŸ‡¸US_572 |36.22Mb
  - ğŸ‡ºğŸ‡¸US_573 |18.09Mb
  - ğŸ‡ºğŸ‡¸US_574 |36.59Mb
  - ğŸ‡²ğŸ‡¾MY_566 |29.69Mb
  - ğŸ‡ºğŸ‡¸US_575 |37.76Mb
  - ğŸ‡ºğŸ‡¸US_576 |36.77Mb
  - disney_PY |15.38Mb
  - ğŸ‡ºğŸ‡¸US_577 |36.40Mb
  - ğŸ‡ºğŸ‡¸US_578 |36.43Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_449 |10.03Mb
  - disney_netflix_US |78.81Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_570 |37.82Mb
  - ğŸ‡ºğŸ‡¸US_581 |22.51Mb
  - Relay_-ğŸ‡°ğŸ‡·KR_413 |14.52Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
