port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: ğŸ‡¨ğŸ‡¦CA_37 |16.34Mb
  server: 138.197.153.10
  type: ss
  country: ğŸ‡¨ğŸ‡¦CA
  port: 8080
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: ğŸ‡¨ğŸ‡¦CA_42 |151.74Mb
  server: 147.182.146.81
  type: ss
  country: ğŸ‡¨ğŸ‡¦CA
  port: 8080
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: ğŸ‡©ğŸ‡ªDE_92 |66.40Mb
  server: 85.195.101.122
  type: vmess
  country: ğŸ‡©ğŸ‡ªDE
  port: 40878
  uuid: f3d4167e-b15e-4e46-82e9-9286ef93fda7
  alterId: 0
  cipher: auto
  network: tcp
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡©ğŸ‡ªDE_47 |17.52Mb
  server: 18.158.60.169
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡©ğŸ‡ªDE_46 |19.47Mb
  server: 3.79.57.79
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡©ğŸ‡ªDE_45 |21.71Mb
  server: 35.159.233.191
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡©ğŸ‡ªDE_52 |17.76Mb
  server: 3.123.25.149
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡©ğŸ‡ªDE_85 |19.26Mb
  server: 3.127.136.134
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡¬ğŸ‡§GB_143 |20.44Mb
  server: 89.185.84.185
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: iEc68ruj1qOx8hjh1KWZmc
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡©ğŸ‡ªDE_63 |32.63Mb
  server: 81.19.141.45
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 443
  password: 0dEg9sKUtuROxn3zaNogzU
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡©ğŸ‡ªDE_89 |56.25Mb
  server: 81.19.141.45
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 443
  password: EEIh3YZZ5QZRvJM6C04YSM
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_144 |146.36Mb
  server: 78.129.140.11
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: DpBNt4YF9cIcVnWOcJqRgy
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_147 |42.09Mb
  server: 52.56.146.226
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡¬ğŸ‡§GB_153 |10.30Mb
  server: 18.135.29.154
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡¬ğŸ‡§GB_145 |19.17Mb
  server: 89.185.84.185
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: FXjMQIem0uShGvRzOpfyib
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_152 |19.80Mb
  server: 89.185.84.185
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: zyzuJ2H4Tp5Cr8T9nnPKv2
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_155 |20.83Mb
  server: 89.185.84.185
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: tVBUTDznmHpV3lpKzbw2Nl
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_162 |19.49Mb
  server: 89.185.84.185
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: ocLhdiEXutNDlofHdfKPJB
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_170 |178.38Mb
  server: 146.70.61.37
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: ğŸ‡¬ğŸ‡§GB_167 |54.28Mb
  server: 89.185.84.185
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: WhUYn0yZ6bLrILxzItfxSI
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_168 |15.49Mb
  server: 89.185.84.185
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: B2ISJ3faDXlkRUXUeQu182
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_169 |18.65Mb
  server: 89.185.84.185
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: IKM7Oo8MqE5gaba7mifgyx
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_171 |10.03Mb
  server: 89.185.84.185
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: m8V5Orkxu2ob8LH24OFobn
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_175 |11.95Mb
  server: 89.185.84.185
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: bmoj6orLj0ipdovNVUJzVL
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_173 |18.17Mb
  server: 89.185.84.185
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: gbCXg98Ecfx15al9somp9w
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_180 |47.38Mb
  server: 18.169.158.38
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡¬ğŸ‡§GB_176 |13.97Mb
  server: 89.185.84.185
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: IP77QXJz3YEA90m7miLOBu
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_177 |10.94Mb
  server: 89.185.84.185
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: RCep1UaygXjYEdFS9kOsm3
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡®ğŸ‡¶IQ_185 |48.98Mb
  server: 81.90.31.219
  type: ss
  country: ğŸ‡®ğŸ‡¶IQ
  port: 443
  password: iRZgNTcrf657aaZpPkCFWu
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡®ğŸ‡¶IQ_196 |13.01Mb
  server: 81.90.31.219
  type: ss
  country: ğŸ‡®ğŸ‡¶IQ
  port: 443
  password: yXauOaEDOdhZ4N2doT3FXF
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_210 |10.88Mb
  server: 45.87.175.164
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: 1RWwXhwfAB5gAEozU4G2Pg
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_217 |23.80Mb
  server: 45.87.175.174
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_218 |24.05Mb
  server: 45.87.175.28
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡³ğŸ‡±NL_225 |11.77Mb
  server: 193.29.139.177
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 8080
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_301 |12.61Mb
  server: 64.74.163.218
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 990
  password: f8f7aCzcPKbsF8p3
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_303 |27.67Mb
  server: 104.192.227.162
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: lDNvvsfmLxIWlnV0PzaZvZ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡®ğŸ‡¶IQ_200 |108.39Mb
  server: 81.90.31.219
  type: ss
  country: ğŸ‡®ğŸ‡¶IQ
  port: 443
  password: k7IzlcAz0OMAy68jdZTn2Y
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_310 |22.05Mb
  server: 64.74.163.130
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 990
  password: f8f7aCzcPKbsF8p3
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_315 |10.77Mb
  server: 18.118.137.217
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡­ğŸ‡°HK_182 |10.69Mb
  server: 203.23.128.33
  type: ss
  country: ğŸ‡­ğŸ‡°HK
  port: 990
  password: f8f7aCzcPKbsF8p3
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_296 |33.94Mb
  server: 104.192.226.106
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 990
  password: f8f7aCzcPKbsF8p3
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¯ğŸ‡µJP_205 |11.49Mb
  server: 45.32.45.45
  type: vmess
  country: ğŸ‡¯ğŸ‡µJP
  port: 14760
  uuid: dbf7a6e4-d518-4f9b-a55e-27ef892ffac1
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡ºğŸ‡¸US_309 |15.19Mb
  server: 104.192.226.106
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡³ğŸ‡±NL_302 |18.59Mb
  server: 45.158.171.70
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 8080
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡·ğŸ‡ºRU_271 |13.08Mb
  server: 212.192.14.234
  type: ss
  country: ğŸ‡·ğŸ‡ºRU
  port: 24441
  password: eaTzMJaYNiUu8GKuTOefke
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_323 |372.50Mb
  server: 193.124.24.247
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 6510
  uuid: 8f44f672-e53b-44fb-b502-c886d37107b5
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡ºğŸ‡¸US_292 |99.84Mb
  server: 45.12.150.199
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 39447
  password: VnSL5YmYusDmMsUV2Y9dh7
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_321 |44.19Mb
  server: 43.162.114.137
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 59674
  uuid: 6a4ce5b9-0d60-4a21-a8fe-897798019500
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_US |562.84Mb
  server: 154.29.158.139
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 12299
  uuid: cccfe679-fbd0-4402-caf2-67e919db436f
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡ºğŸ‡¸US_318 |28.96Mb
  server: 149.22.87.240
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: shadowsocks
  cipher: aes-128-gcm
- name: Pool_ğŸ‡­ğŸ‡°HK_183 |433.00Mb
  server: 150.107.46.21
  type: ssr
  country: ğŸ‡­ğŸ‡°HK
  port: 8083
  password: iFqnzSscN
  cipher: aes-256-cfb
  protocol: origin
  obfs: tls1.2_ticket_auth
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - ğŸ‡¨ğŸ‡¦CA_37 |16.34Mb
  - ğŸ‡¨ğŸ‡¦CA_42 |151.74Mb
  - ğŸ‡©ğŸ‡ªDE_92 |66.40Mb
  - ğŸ‡©ğŸ‡ªDE_47 |17.52Mb
  - ğŸ‡©ğŸ‡ªDE_46 |19.47Mb
  - ğŸ‡©ğŸ‡ªDE_45 |21.71Mb
  - ğŸ‡©ğŸ‡ªDE_52 |17.76Mb
  - ğŸ‡©ğŸ‡ªDE_85 |19.26Mb
  - ğŸ‡¬ğŸ‡§GB_143 |20.44Mb
  - ğŸ‡©ğŸ‡ªDE_63 |32.63Mb
  - ğŸ‡©ğŸ‡ªDE_89 |56.25Mb
  - ğŸ‡¬ğŸ‡§GB_144 |146.36Mb
  - ğŸ‡¬ğŸ‡§GB_147 |42.09Mb
  - ğŸ‡¬ğŸ‡§GB_153 |10.30Mb
  - ğŸ‡¬ğŸ‡§GB_145 |19.17Mb
  - ğŸ‡¬ğŸ‡§GB_152 |19.80Mb
  - ğŸ‡¬ğŸ‡§GB_155 |20.83Mb
  - ğŸ‡¬ğŸ‡§GB_162 |19.49Mb
  - ğŸ‡¬ğŸ‡§GB_170 |178.38Mb
  - ğŸ‡¬ğŸ‡§GB_167 |54.28Mb
  - ğŸ‡¬ğŸ‡§GB_168 |15.49Mb
  - ğŸ‡¬ğŸ‡§GB_169 |18.65Mb
  - ğŸ‡¬ğŸ‡§GB_171 |10.03Mb
  - ğŸ‡¬ğŸ‡§GB_175 |11.95Mb
  - ğŸ‡¬ğŸ‡§GB_173 |18.17Mb
  - ğŸ‡¬ğŸ‡§GB_180 |47.38Mb
  - ğŸ‡¬ğŸ‡§GB_176 |13.97Mb
  - ğŸ‡¬ğŸ‡§GB_177 |10.94Mb
  - ğŸ‡®ğŸ‡¶IQ_185 |48.98Mb
  - ğŸ‡®ğŸ‡¶IQ_196 |13.01Mb
  - ğŸ‡±ğŸ‡¹LT_210 |10.88Mb
  - ğŸ‡±ğŸ‡¹LT_217 |23.80Mb
  - ğŸ‡±ğŸ‡¹LT_218 |24.05Mb
  - ğŸ‡³ğŸ‡±NL_225 |11.77Mb
  - ğŸ‡ºğŸ‡¸US_301 |12.61Mb
  - ğŸ‡ºğŸ‡¸US_303 |27.67Mb
  - ğŸ‡®ğŸ‡¶IQ_200 |108.39Mb
  - ğŸ‡ºğŸ‡¸US_310 |22.05Mb
  - ğŸ‡ºğŸ‡¸US_315 |10.77Mb
  - ğŸ‡­ğŸ‡°HK_182 |10.69Mb
  - ğŸ‡ºğŸ‡¸US_296 |33.94Mb
  - ğŸ‡¯ğŸ‡µJP_205 |11.49Mb
  - ğŸ‡ºğŸ‡¸US_309 |15.19Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡³ğŸ‡±NL_302 |18.59Mb
  - ğŸ‡·ğŸ‡ºRU_271 |13.08Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_323 |372.50Mb
  - ğŸ‡ºğŸ‡¸US_292 |99.84Mb
  - ğŸ‡ºğŸ‡¸US_321 |44.19Mb
  - disney_US |562.84Mb
  - ğŸ‡ºğŸ‡¸US_318 |28.96Mb
  - Pool_ğŸ‡­ğŸ‡°HK_183 |433.00Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - ğŸ‡¨ğŸ‡¦CA_37 |16.34Mb
  - ğŸ‡¨ğŸ‡¦CA_42 |151.74Mb
  - ğŸ‡©ğŸ‡ªDE_92 |66.40Mb
  - ğŸ‡©ğŸ‡ªDE_47 |17.52Mb
  - ğŸ‡©ğŸ‡ªDE_46 |19.47Mb
  - ğŸ‡©ğŸ‡ªDE_45 |21.71Mb
  - ğŸ‡©ğŸ‡ªDE_52 |17.76Mb
  - ğŸ‡©ğŸ‡ªDE_85 |19.26Mb
  - ğŸ‡¬ğŸ‡§GB_143 |20.44Mb
  - ğŸ‡©ğŸ‡ªDE_63 |32.63Mb
  - ğŸ‡©ğŸ‡ªDE_89 |56.25Mb
  - ğŸ‡¬ğŸ‡§GB_144 |146.36Mb
  - ğŸ‡¬ğŸ‡§GB_147 |42.09Mb
  - ğŸ‡¬ğŸ‡§GB_153 |10.30Mb
  - ğŸ‡¬ğŸ‡§GB_145 |19.17Mb
  - ğŸ‡¬ğŸ‡§GB_152 |19.80Mb
  - ğŸ‡¬ğŸ‡§GB_155 |20.83Mb
  - ğŸ‡¬ğŸ‡§GB_162 |19.49Mb
  - ğŸ‡¬ğŸ‡§GB_170 |178.38Mb
  - ğŸ‡¬ğŸ‡§GB_167 |54.28Mb
  - ğŸ‡¬ğŸ‡§GB_168 |15.49Mb
  - ğŸ‡¬ğŸ‡§GB_169 |18.65Mb
  - ğŸ‡¬ğŸ‡§GB_171 |10.03Mb
  - ğŸ‡¬ğŸ‡§GB_175 |11.95Mb
  - ğŸ‡¬ğŸ‡§GB_173 |18.17Mb
  - ğŸ‡¬ğŸ‡§GB_180 |47.38Mb
  - ğŸ‡¬ğŸ‡§GB_176 |13.97Mb
  - ğŸ‡¬ğŸ‡§GB_177 |10.94Mb
  - ğŸ‡®ğŸ‡¶IQ_185 |48.98Mb
  - ğŸ‡®ğŸ‡¶IQ_196 |13.01Mb
  - ğŸ‡±ğŸ‡¹LT_210 |10.88Mb
  - ğŸ‡±ğŸ‡¹LT_217 |23.80Mb
  - ğŸ‡±ğŸ‡¹LT_218 |24.05Mb
  - ğŸ‡³ğŸ‡±NL_225 |11.77Mb
  - ğŸ‡ºğŸ‡¸US_301 |12.61Mb
  - ğŸ‡ºğŸ‡¸US_303 |27.67Mb
  - ğŸ‡®ğŸ‡¶IQ_200 |108.39Mb
  - ğŸ‡ºğŸ‡¸US_310 |22.05Mb
  - ğŸ‡ºğŸ‡¸US_315 |10.77Mb
  - ğŸ‡­ğŸ‡°HK_182 |10.69Mb
  - ğŸ‡ºğŸ‡¸US_296 |33.94Mb
  - ğŸ‡¯ğŸ‡µJP_205 |11.49Mb
  - ğŸ‡ºğŸ‡¸US_309 |15.19Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡³ğŸ‡±NL_302 |18.59Mb
  - ğŸ‡·ğŸ‡ºRU_271 |13.08Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_323 |372.50Mb
  - ğŸ‡ºğŸ‡¸US_292 |99.84Mb
  - ğŸ‡ºğŸ‡¸US_321 |44.19Mb
  - disney_US |562.84Mb
  - ğŸ‡ºğŸ‡¸US_318 |28.96Mb
  - Pool_ğŸ‡­ğŸ‡°HK_183 |433.00Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
