port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: ' |29.49Mb'
  server: 103.35.189.136
  type: ss
  port: 443
  udp: true
  password: SS2QvbC9nqLp2sXXZo0BVy4slcErRuCt
  cipher: chacha20-ietf-poly1305
- name: ' |61.04Mb'
  server: 137.184.174.93
  type: ss
  port: 8080
  udp: true
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: ' |13.90Mb'
  server: 196.196.192.58
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ' |235.63Mb'
  server: 151.242.251.142
  type: ss
  port: 8080
  udp: true
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ' |14.52Mb'
  server: 141.98.101.178
  type: ss
  port: 443
  udp: true
  password: shadowsocks
  cipher: aes-128-gcm
- name: ' |566.78Mb'
  server: 192.71.249.78
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ' |26.76Mb'
  server: 156.146.38.167
  type: ss
  port: 443
  udp: true
  password: shadowsocks
  cipher: aes-128-gcm
- name: ' |10.40Mb'
  server: 193.135.174.135
  type: ss
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ' |35.16Mb'
  server: 156.146.38.169
  type: ss
  port: 443
  udp: true
  password: shadowsocks
  cipher: aes-128-gcm
- name: ' |21.62Mb'
  server: 95.164.116.33
  type: ss
  port: 443
  password: pQmnC03JObbPhdh5FBJHgD6jnTLchsRA
  cipher: chacha20-ietf-poly1305
- name: ' |42.16Mb'
  server: 173.244.56.6
  type: ss
  port: 443
  udp: true
  password: shadowsocks
  cipher: aes-128-gcm
- name: ' |12.28Mb'
  server: 68.183.227.4
  type: ss
  port: 8080
  udp: true
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: ' |46.60Mb'
  server: 138.186.143.32
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ' |46.64Mb'
  server: 138.186.143.32
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ' |11.48Mb'
  server: 45.87.175.22
  type: ss
  port: 8080
  udp: true
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: ' |28.80Mb'
  server: 119.59.98.58
  type: ss
  port: 990
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: chacha20-ietf-poly1305
- name: ' |252.36Mb'
  server: 151.242.251.147
  type: ss
  port: 8080
  password: QCXDxuDlTTMD7jtgHUjIoj
  cipher: chacha20-ietf-poly1305
- name: ' |349.53Mb'
  server: h110vpnnl.outlinekeys.net
  type: ss
  port: 52571
  udp: true
  password: b0TKxnHAYeeFYyzTAMXn0F
  cipher: chacha20-ietf-poly1305
- name: ' |38.71Mb'
  server: 156.146.38.170
  type: ss
  port: 443
  udp: true
  password: shadowsocks
  cipher: aes-128-gcm
- name: ' |17.72Mb'
  server: 38.89.142.56
  type: ss
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ' |33.08Mb'
  server: 185.47.254.87
  type: ss
  port: 990
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: chacha20-ietf-poly1305
- name: ' |29.25Mb'
  server: 119.59.98.58
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ' |33.58Mb'
  server: 147.78.0.182
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ' |50.41Mb'
  server: 146.70.61.37
  type: ss
  port: 8080
  udp: true
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: ' |16.92Mb'
  server: 185.192.124.188
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ' |137.38Mb'
  server: 82.38.31.194
  type: ss
  port: 8080
  udp: true
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ' |26.73Mb'
  server: 103.149.182.86
  type: ss
  port: 8388
  udp: true
  password: asd123456
  cipher: chacha20-ietf
- name: ' |28.93Mb'
  server: 38.165.231.25
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ' |218.52Mb'
  server: 151.242.251.152
  type: ss
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ' |14.71Mb'
  server: 62.100.205.100
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ' |17.52Mb'
  server: 38.165.233.93
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ' |19.10Mb'
  server: 149.22.87.241
  type: ss
  port: 443
  udp: true
  password: shadowsocks
  cipher: aes-128-gcm
- name: ' |20.82Mb'
  server: est01-ss01.tcp-reset-club.net
  type: ss
  port: 8444
  udp: true
  password: AWNeHjukGQWwuFXadw2r6qH7gh4hZ9cj
  cipher: chacha20-ietf-poly1305
- name: ' |215.36Mb'
  server: 82.38.31.179
  type: ss
  port: 8080
  udp: true
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ' |44.72Mb'
  server: 156.59.243.6
  type: ss
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ' |69.38Mb'
  server: 79.127.200.162
  type: ss
  port: 989
  udp: true
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ' |11.09Mb'
  server: 89.221.225.15
  type: ss
  port: 443
  udp: true
  password: yCbQ4bry4otfifK7oel71NaXpPL9pYJb
  cipher: chacha20-ietf-poly1305
- name: ' |21.29Mb'
  server: 128.199.172.224
  type: ss
  port: 8080
  udp: true
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: ' |11.49Mb'
  server: 172.105.199.111
  type: ss
  port: 8080
  udp: true
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: ' |412.02Mb'
  server: 45.14.245.2
  type: ss
  port: 443
  password: 17ZDORWIliQHuO6WRGHChXYMzdRtAYVP
  cipher: chacha20-ietf-poly1305
- name: ' |68.75Mb'
  server: 79.127.200.169
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ' |35.13Mb'
  server: luo.yixianled.com
  type: vmess
  port: 34610
  udp: true
  uuid: 6578c489-28d2-4f12-8c2f-9f2d8789626d
  alterId: 0
  cipher: auto
  network: ws
  servername: luo.yixianled.com
  http-opts: {}
  h2-opts: {}
  tls: true
  ws-opts:
    path: /happy
    headers:
      Host: luo.yixianled.com
- name: ' |53.75Mb'
  server: 45.87.175.187
  type: ss
  port: 8080
  udp: true
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: ' |15.52Mb'
  server: 194.246.114.101
  type: ss
  port: 443
  udp: true
  password: HaNqw9pIE4jcx98sg7UQgHeGNTM4R2pk
  cipher: chacha20-ietf-poly1305
- name: ' |51.72Mb'
  server: 172.233.229.91
  type: vmess
  port: 14102
  udp: true
  uuid: 27ba87fc-583f-4763-9060-83cf0b9264db
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ' |42.70Mb'
  server: 145.249.109.121
  type: ss
  port: 25512
  udp: true
  password: smSMfR9jqLgMkHuQtxSIWh
  cipher: chacha20-ietf-poly1305
- name: ' |102.99Mb'
  server: 82.38.31.176
  type: ss
  port: 8080
  udp: true
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ' |239.86Mb'
  server: 82.38.31.214
  type: ss
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ' |10.91Mb'
  server: 103.149.182.105
  type: ss
  port: 8388
  password: asd123456
  cipher: chacha20-ietf
- name: ' |20.31Mb'
  server: 149.88.95.217
  type: vmess
  port: 40741
  uuid: 1b8a751b-4909-4fec-f019-907d92e6c47f
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
- name: ' |19.98Mb'
  server: 149.88.95.94
  type: vmess
  port: 40741
  uuid: 1b8a751b-4909-4fec-f019-907d92e6c47f
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
- name: ' |16.82Mb'
  server: 149.88.95.217
  type: vmess
  port: 35760
  uuid: 17e96792-d8c3-4741-9c34-e5d1c11d754f
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
- name: ' |18.25Mb'
  server: 160.16.204.136
  type: trojan
  port: 2890
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: ' |10.50Mb'
  server: 160.16.117.182
  type: trojan
  port: 3169
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: ' |14.99Mb'
  server: 149.88.95.94
  type: vmess
  port: 35760
  uuid: 17e96792-d8c3-4741-9c34-e5d1c11d754f
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
- name: ' |13.92Mb'
  server: 160.16.136.130
  type: trojan
  port: 2890
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: ' |12.19Mb'
  server: 160.16.116.227
  type: trojan
  port: 2760
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
  skip-cert-verify: true
- name: ' |16.64Mb'
  server: 193.203.203.66
  type: ss
  country: üá®üá¶CA
  port: 443
  password: S6jUK9Fw5fMHgNqlqXObHZWv8Tf4nEkm
  cipher: chacha20-ietf-poly1305
- name: ' |14.20Mb'
  server: 160.16.124.55
  type: trojan
  port: 2890
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
- name: ' |27.48Mb'
  server: 219.79.214.159
  type: trojan
  port: 443
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: ' |11.88Mb'
  server: 47.242.225.242
  type: trojan
  port: 443
  udp: true
  password: 92690597d6298061459918a371e8d77d
  sni: hezijiasuqi.com
  skip-cert-verify: true
- name: ' |10.89Mb'
  server: 160.16.131.243
  type: trojan
  port: 2760
  password: e2722c0fb503f8a592436c12bce0509a
  sni: www.nintendogames.net
  skip-cert-verify: true
- name: ' |16.01Mb'
  server: 185.192.124.188
  type: ss
  country: üáßüá∑BR
  port: 990
  password: f8f7aCzcPKbsF8p3
  cipher: chacha20-ietf-poly1305
- name: ' |65.01Mb'
  server: 185.213.23.63
  type: ss
  country: üá®üá¶CA
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ' |289.06Mb'
  server: 89.163.140.136
  type: ss
  country: üá©üá™DE
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ' |59.21Mb'
  server: 138.124.67.26
  type: ss
  country: üá®üá≠CH
  port: 25572
  password: nqcIfYHlpMn3jzqkNDjKaG
  cipher: chacha20-ietf-poly1305
- name: ' |19.13Mb'
  server: 141.98.101.182
  type: ss
  country: üá¨üáßGB
  port: 443
  password: shadowsocks
  cipher: aes-128-gcm
- name: ' |140.48Mb'
  server: 82.38.31.208
  type: ss
  country: üá¨üáßGB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ' |27.97Mb'
  server: 45.207.157.29
  type: vmess
  country: üá≠üá∞HK
  port: 13852
  uuid: 845764df-ecb3-4b13-bed2-bf1551b68e9a
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ' |30.26Mb'
  server: 154.205.153.107
  type: ss
  country: üá®üá±CL
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ' |200.42Mb'
  server: 45.87.175.185
  type: ss
  country: üá±üáπLT
  port: 8080
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: ' |85.93Mb'
  server: 45.87.175.175
  type: ss
  country: üá±üáπLT
  port: 8080
  password: QCXDxuDlTTMD7jtgHUjIoj
  cipher: chacha20-ietf-poly1305
- name: ' |165.86Mb'
  server: 45.87.175.183
  type: ss
  country: üá±üáπLT
  port: 8080
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: ' |102.81Mb'
  server: 45.87.175.185
  type: ss
  country: üá±üáπLT
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ' |40.45Mb'
  server: 38.14.99.163
  type: vmess
  country: üá∫üá∏US
  port: 59807
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: auto
  network: tcp
  servername: 38.14.99.163
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ' |290.34Mb'
  server: 194.87.216.218
  type: ss
  country: üá≥üá±NL
  port: 52571
  password: b0TKxnHAYeeFYyzTAMXn0F
  cipher: chacha20-ietf-poly1305
- name: ' |17.54Mb'
  server: 178.23.190.238
  type: ss
  country: üá≥üá±NL
  port: 443
  password: uo7EbtqIwgZXXHmMv5LbLcOxptyPlNkh
  cipher: chacha20-ietf-poly1305
- name: ' |38.43Mb'
  server: 104.18.14.55
  type: vmess
  country: üèÅZZ
  port: 2052
  uuid: e6447786-8c85-443c-8017-7feaa673ff45
  alterId: 0
  cipher: auto
  network: ws
  servername: in4.123417.xyz
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
  ws-opts:
    path: /
    headers:
      HOST: in4.123417.xyz
- name: ' |50.31Mb'
  server: 176.123.5.253
  type: ss
  country: üá≤üá©MD
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ' |56.65Mb'
  server: 45.150.52.40
  type: vmess
  country: üá∫üá∏US
  port: 443
  uuid: c31777a1-2ee6-4864-db4c-a79fcbc8188b
  alterId: 0
  cipher: auto
  network: ws
  servername: xsj011-3.facai2024.com
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /c31777a1
    headers:
      HOST: xsj011-3.facai2024.com
- name: ' |41.82Mb'
  server: v4.hdacd.com
  type: vmess
  port: 30804
  udp: true
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ' |139.80Mb'
  server: 193.29.139.141
  type: ss
  country: üá≥üá±NL
  port: 8080
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: ' |58.20Mb'
  server: 185.113.143.186
  type: ss
  country: üáµüáπPT
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ' |10.10Mb'
  server: 68.183.227.45
  type: ss
  country: üá∏üá¨SG
  port: 8080
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: ' |137.58Mb'
  server: 185.231.233.112
  type: ss
  country: üèÅ ZZ
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ' |14.31Mb'
  server: ltnl16.saint.ydns.eu
  type: ss
  country: üá±üáπLT
  port: 8080
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: ' |14.52Mb'
  server: 173.234.29.2
  type: ss
  port: 990
  udp: true
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
proxy-groups:
- name: üöÄ ËäÇÁÇπÈÄâÊã©
  type: select
  proxies:
  - ‚ôªÔ∏è Ëá™Âä®ÈÄâÊã©
  - ' |29.49Mb'
  - ' |61.04Mb'
  - ' |13.90Mb'
  - ' |235.63Mb'
  - ' |14.52Mb'
  - ' |566.78Mb'
  - ' |26.76Mb'
  - ' |10.40Mb'
  - ' |35.16Mb'
  - ' |21.62Mb'
  - ' |42.16Mb'
  - ' |12.28Mb'
  - ' |46.60Mb'
  - ' |46.64Mb'
  - ' |11.48Mb'
  - ' |28.80Mb'
  - ' |252.36Mb'
  - ' |349.53Mb'
  - ' |38.71Mb'
  - ' |17.72Mb'
  - ' |33.08Mb'
  - ' |29.25Mb'
  - ' |33.58Mb'
  - ' |50.41Mb'
  - ' |16.92Mb'
  - ' |137.38Mb'
  - ' |26.73Mb'
  - ' |28.93Mb'
  - ' |218.52Mb'
  - ' |14.71Mb'
  - ' |17.52Mb'
  - ' |19.10Mb'
  - ' |20.82Mb'
  - ' |215.36Mb'
  - ' |44.72Mb'
  - ' |69.38Mb'
  - ' |11.09Mb'
  - ' |21.29Mb'
  - ' |11.49Mb'
  - ' |412.02Mb'
  - ' |68.75Mb'
  - ' |35.13Mb'
  - ' |53.75Mb'
  - ' |15.52Mb'
  - ' |51.72Mb'
  - ' |42.70Mb'
  - ' |102.99Mb'
  - ' |239.86Mb'
  - ' |10.91Mb'
  - ' |20.31Mb'
  - ' |19.98Mb'
  - ' |16.82Mb'
  - ' |18.25Mb'
  - ' |10.50Mb'
  - ' |14.99Mb'
  - ' |13.92Mb'
  - ' |12.19Mb'
  - ' |16.64Mb'
  - ' |14.20Mb'
  - ' |27.48Mb'
  - ' |11.88Mb'
  - ' |10.89Mb'
  - ' |16.01Mb'
  - ' |65.01Mb'
  - ' |289.06Mb'
  - ' |59.21Mb'
  - ' |19.13Mb'
  - ' |140.48Mb'
  - ' |27.97Mb'
  - ' |30.26Mb'
  - ' |200.42Mb'
  - ' |85.93Mb'
  - ' |165.86Mb'
  - ' |102.81Mb'
  - ' |40.45Mb'
  - ' |290.34Mb'
  - ' |17.54Mb'
  - ' |38.43Mb'
  - ' |50.31Mb'
  - ' |56.65Mb'
  - ' |41.82Mb'
  - ' |139.80Mb'
  - ' |58.20Mb'
  - ' |10.10Mb'
  - ' |137.58Mb'
  - ' |14.31Mb'
  - ' |14.52Mb'
  url: https://www.google.com/generate_204
- name: ‚ôªÔ∏è Ëá™Âä®ÈÄâÊã©
  type: url-test
  proxies:
  - ' |29.49Mb'
  - ' |61.04Mb'
  - ' |13.90Mb'
  - ' |235.63Mb'
  - ' |14.52Mb'
  - ' |566.78Mb'
  - ' |26.76Mb'
  - ' |10.40Mb'
  - ' |35.16Mb'
  - ' |21.62Mb'
  - ' |42.16Mb'
  - ' |12.28Mb'
  - ' |46.60Mb'
  - ' |46.64Mb'
  - ' |11.48Mb'
  - ' |28.80Mb'
  - ' |252.36Mb'
  - ' |349.53Mb'
  - ' |38.71Mb'
  - ' |17.72Mb'
  - ' |33.08Mb'
  - ' |29.25Mb'
  - ' |33.58Mb'
  - ' |50.41Mb'
  - ' |16.92Mb'
  - ' |137.38Mb'
  - ' |26.73Mb'
  - ' |28.93Mb'
  - ' |218.52Mb'
  - ' |14.71Mb'
  - ' |17.52Mb'
  - ' |19.10Mb'
  - ' |20.82Mb'
  - ' |215.36Mb'
  - ' |44.72Mb'
  - ' |69.38Mb'
  - ' |11.09Mb'
  - ' |21.29Mb'
  - ' |11.49Mb'
  - ' |412.02Mb'
  - ' |68.75Mb'
  - ' |35.13Mb'
  - ' |53.75Mb'
  - ' |15.52Mb'
  - ' |51.72Mb'
  - ' |42.70Mb'
  - ' |102.99Mb'
  - ' |239.86Mb'
  - ' |10.91Mb'
  - ' |20.31Mb'
  - ' |19.98Mb'
  - ' |16.82Mb'
  - ' |18.25Mb'
  - ' |10.50Mb'
  - ' |14.99Mb'
  - ' |13.92Mb'
  - ' |12.19Mb'
  - ' |16.64Mb'
  - ' |14.20Mb'
  - ' |27.48Mb'
  - ' |11.88Mb'
  - ' |10.89Mb'
  - ' |16.01Mb'
  - ' |65.01Mb'
  - ' |289.06Mb'
  - ' |59.21Mb'
  - ' |19.13Mb'
  - ' |140.48Mb'
  - ' |27.97Mb'
  - ' |30.26Mb'
  - ' |200.42Mb'
  - ' |85.93Mb'
  - ' |165.86Mb'
  - ' |102.81Mb'
  - ' |40.45Mb'
  - ' |290.34Mb'
  - ' |17.54Mb'
  - ' |38.43Mb'
  - ' |50.31Mb'
  - ' |56.65Mb'
  - ' |41.82Mb'
  - ' |139.80Mb'
  - ' |58.20Mb'
  - ' |10.10Mb'
  - ' |137.58Mb'
  - ' |14.31Mb'
  - ' |14.52Mb'
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,üöÄ ËäÇÁÇπÈÄâÊã©
