port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: disney_netflix_US |58.98Mb
  server: 45.150.52.40
  type: vmess
  port: 443
  uuid: c31777a1-2ee6-4864-db4c-a79fcbc8188b
  alterId: 0
  cipher: auto
  network: ws
  servername: xsj011-3.facai2024.com
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /c31777a1
- name: disney_US |53.86Mb
  server: 185.221.23.251
  type: vmess
  country: ðŸ‡ªðŸ‡¸ES
  port: 29431
  uuid: 8b78363e-3c3a-44ab-f0d8-f13d950c8572
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_-ðŸ‡¸ðŸ‡¬SG_135 |10.57Mb
  server: 160.16.153.13
  type: trojan
  port: 3145
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: disney_netflix_US |10.75Mb
  server: 160.16.214.6
  type: trojan
  port: 2890
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: disney_netflix_GB |60.65Mb
  server: koma-yt.pages.dev
  type: trojan
  port: 8443
  udp: true
  password: 8r<[9'l6hAO#8ZQi
  sni: Koma-YT.PAGeS.Dev
  ws-opts:
    path: /tro8sFW1S91B6sZrM1?ed=2560
    headers:
      Host: Koma-YT.PAGeS.Dev
  network: ws
- name: disney_netflix_US |10.76Mb
  server: 202.181.103.235
  type: trojan
  port: 2890
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: disney_netflix_HK |24.60Mb
  server: 58.152.110.82
  type: trojan
  port: 443
  password: 76d630f2af6619c4a5de0ef953df3c6a
  sni: www.nintendogames.net
- name: disney_netflix_HK |25.11Mb
  server: 8.218.105.196
  type: vmess
  port: 52752
  uuid: 925bdbf5-72be-4437-bebf-441c61089f6b
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
- name: netflix_MX |37.87Mb
  server: 216.238.89.53
  type: vmess
  country: ðŸ‡²ðŸ‡½MX
  port: 57283
  uuid: 1a5aafc0-6482-451d-fe76-6875b7818579
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: netflix_IE |282.40Mb
  server: 146.70.90.196
  type: ss
  country: ðŸ‡®ðŸ‡ªIE
  port: 17454
  password: u8gp148iz90ddoo6ms37
  cipher: aes-128-gcm
- name: netflix_NL |169.92Mb
  server: 82.38.31.184
  type: ss
  country: ðŸ‡¬ðŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: netflix_NL |88.88Mb
  server: 51.15.17.169
  type: ss
  country: ðŸ‡¬ðŸ‡§GB
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: disney_netflix_US |11.39Mb
  server: 195.66.27.148
  type: ss
  country: ðŸ‡¬ðŸ‡§GB
  port: 28709
  password: hShp1Km0NcFSmSigc8ozky
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_US |38.94Mb
  server: 38.14.99.163
  type: vmess
  country: ðŸ‡ºðŸ‡¸US
  port: 59807
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: auto
  network: tcp
  servername: 38.14.99.163
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: netflix_KR |10.67Mb
  server: 146.56.112.110
  type: vmess
  country: ðŸ‡°ðŸ‡·KR
  port: 8888
  uuid: e7c302f3-90d6-42dd-9d7d-94a3683a3707
  alterId: 0
  cipher: auto
  network: tcp
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_-ðŸ‡¸ðŸ‡¬SG_105 |24.89Mb
  server: clr.ducks.tel
  type: ss
  port: 17844
  password: '907560230'
  cipher: chacha20-ietf-poly1305
- name: netflix_NL |14.20Mb
  server: 109.71.246.210
  type: ss
  country: ðŸ‡·ðŸ‡ºRU
  port: 56689
  password: YQCSKoCF3QazW8YlvDBWA4
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_SE |65.41Mb
  server: 91.186.217.246
  type: ss
  country: ðŸ‡ºðŸ‡¸US
  port: 31764
  password: Ftc17VH9ZXQON5vslJCYmv
  cipher: chacha20-ietf-poly1305
- name: Relay_-ðŸ‡­ðŸ‡°HK_129 |43.35Mb
  server: v10.hdacd.com
  type: vmess
  port: 30807
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: auto
  http-opts: {}
  h2-opts: {}
- name: disney_RU |45.62Mb
  server: 81.200.158.206
  type: ss
  country: ðŸ‡·ðŸ‡ºRU
  port: 1080
  password: AqZbt1QCs3ngEfXo1p7T-w
  cipher: chacha20-ietf-poly1305
proxy-groups:
- name: ðŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - disney_netflix_US |58.98Mb
  - disney_US |53.86Mb
  - Relay_-ðŸ‡¸ðŸ‡¬SG_135 |10.57Mb
  - disney_netflix_US |10.75Mb
  - disney_netflix_GB |60.65Mb
  - disney_netflix_US |10.76Mb
  - disney_netflix_HK |24.60Mb
  - disney_netflix_HK |25.11Mb
  - netflix_MX |37.87Mb
  - netflix_IE |282.40Mb
  - netflix_NL |169.92Mb
  - netflix_NL |88.88Mb
  - disney_netflix_US |11.39Mb
  - disney_netflix_US |38.94Mb
  - netflix_KR |10.67Mb
  - Relay_-ðŸ‡¸ðŸ‡¬SG_105 |24.89Mb
  - netflix_NL |14.20Mb
  - disney_netflix_SE |65.41Mb
  - Relay_-ðŸ‡­ðŸ‡°HK_129 |43.35Mb
  - disney_RU |45.62Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - disney_netflix_US |58.98Mb
  - disney_US |53.86Mb
  - Relay_-ðŸ‡¸ðŸ‡¬SG_135 |10.57Mb
  - disney_netflix_US |10.75Mb
  - disney_netflix_GB |60.65Mb
  - disney_netflix_US |10.76Mb
  - disney_netflix_HK |24.60Mb
  - disney_netflix_HK |25.11Mb
  - netflix_MX |37.87Mb
  - netflix_IE |282.40Mb
  - netflix_NL |169.92Mb
  - netflix_NL |88.88Mb
  - disney_netflix_US |11.39Mb
  - disney_netflix_US |38.94Mb
  - netflix_KR |10.67Mb
  - Relay_-ðŸ‡¸ðŸ‡¬SG_105 |24.89Mb
  - netflix_NL |14.20Mb
  - disney_netflix_SE |65.41Mb
  - Relay_-ðŸ‡­ðŸ‡°HK_129 |43.35Mb
  - disney_RU |45.62Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ðŸš€ èŠ‚ç‚¹é€‰æ‹©
