port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: Relay_-ğŸ‡ºğŸ‡¸US_501 |40.83Mb
  server: 38.14.99.179
  type: vmess
  port: 59807
  udp: true
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: _470 |15.84Mb
  server: 103.231.73.211
  type: ss
  port: 57456
  udp: true
  password: 8afc633eb63227e9
  cipher: chacha20-ietf-poly1305
- name: _467 |13.68Mb
  server: 103.36.91.32
  type: ss
  port: 8388
  udp: true
  password: asd123456
  cipher: chacha20-ietf
- name: disney_SG |33.87Mb
  server: 188.253.124.53
  type: ss
  port: 63257
  udp: true
  password: RenzheCloudSS
  cipher: rc4-md5
  plugin: obfs
  plugin-opts:
    host: d1bf8290613.microsoft.com
    mode: http
- name: _733 |28.18Mb
  server: 58.152.110.154
  type: trojan
  port: 443
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¯ğŸ‡µJP_744 |14.35Mb
  server: 153.121.38.213
  type: trojan
  port: 1331
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡ºğŸ‡¸US_475 |16.09Mb
  server: v8.hdacd.com
  type: vmess
  port: 30808
  udp: true
  uuid: cbb3f877-d1fb-344c-87a9-d153bffd5484
  alterId: 2
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_-ğŸ‡³ğŸ‡±NL_745 |40.49Mb
  server: 153.121.39.240
  type: trojan
  port: 4054
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: _743 |11.73Mb
  server: 68.183.231.236
  type: trojan
  port: 443
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¯ğŸ‡µJP_746 |14.01Mb
  server: 160.16.72.33
  type: trojan
  port: 3093
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: disney_FR |218.26Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 40433
  uuid: d8fd8955-78db-49ba-d86f-3e4729f6ac4d
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡§ğŸ‡·BR_754 |159.76Mb
  server: 38.180.16.86
  type: vmess
  country: ğŸ‡§ğŸ‡·BR
  port: 36104
  uuid: E146A8CB-9D2F-449C-ADCA-8736FB
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_FR |185.30Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 27092
  uuid: a0596ba6-72a3-4366-8992-77088da65bd8
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_-ğŸ‡³ğŸ‡±NL_747 |20.58Mb
  server: 160.16.132.158
  type: trojan
  port: 4054
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: ğŸ‡¬ğŸ‡§GB_758 |39.20Mb
  server: 82.38.31.190
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: Relay_-ğŸ‡³ğŸ‡±NL_749 |42.40Mb
  server: 160.16.236.32
  type: trojan
  port: 4054
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: ğŸ‡²ğŸ‡½MX_900 |41.43Mb
  server: 216.238.89.53
  type: vmess
  country: ğŸ‡²ğŸ‡½MX
  port: 57283
  uuid: 1a5aafc0-6482-451d-fe76-6875b7818579
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡·ğŸ‡ºRU_902 |125.86Mb
  server: 109.71.246.210
  type: ss
  country: ğŸ‡·ğŸ‡ºRU
  port: 56689
  password: YQCSKoCF3QazW8YlvDBWA4
  cipher: chacha20-ietf-poly1305
- name: disney_RU |441.43Mb
  server: 38.60.223.8
  type: ss
  country: ğŸ‡·ğŸ‡ºRU
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ğŸ‡®ğŸ‡³IN_895 |152.83Mb
  server: 134.209.147.198
  type: ss
  country: ğŸ‡®ğŸ‡³IN
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ğŸ‡­ğŸ‡°HK_894 |71.50Mb
  server: 219.79.186.107
  type: trojan
  country: ğŸ‡­ğŸ‡°HK
  port: 443
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: Relay_ğŸ‡¯ğŸ‡µJP-ğŸ‡¯ğŸ‡µJP_896 |10.80Mb
  server: kuame.missionsec.us
  type: trojan
  country: ğŸ‡¯ğŸ‡µJP
  port: 443
  udp: true
  password: FDIypSwe64a3DA7un2R8DFjYXZO3NS05gKZTTOC8SxO0Fy3cqYg3EaFDA3ABaEYKNx39D
  sni: kuame.missionsec.us
  skip-cert-verify: true
- name: netflix_LU |23.81Mb
  server: 45.12.144.18
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: LQyAUItafUmmO3EZZx9UbiX6IGydSBgL
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_913 |35.41Mb
  server: 104.192.226.106
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_914 |40.27Mb
  server: 38.14.99.163
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 59807
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: auto
  network: tcp
  servername: 38.14.99.163
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡²ğŸ‡¾MY_901 |19.23Mb
  server: 38.54.98.110
  type: vmess
  country: ğŸ‡²ğŸ‡¾MY
  port: 2052
  uuid: 665d9b8f-153d-4907-adac-de12afd9c851
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡§ğŸ‡¬BG_908 |447.99Mb
  server: clr.ducks.tel
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 17844
  password: '907560230'
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_915 |286.95Mb
  server: 63.181.59.61
  type: trojan
  country: ğŸ‡ºğŸ‡¸US
  port: 22222
  udp: true
  password: telegram-id-privatevpns
  skip-cert-verify: true
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - Relay_-ğŸ‡ºğŸ‡¸US_501 |40.83Mb
  - _470 |15.84Mb
  - _467 |13.68Mb
  - disney_SG |33.87Mb
  - _733 |28.18Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_744 |14.35Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_475 |16.09Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_745 |40.49Mb
  - _743 |11.73Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_746 |14.01Mb
  - disney_FR |218.26Mb
  - ğŸ‡§ğŸ‡·BR_754 |159.76Mb
  - disney_FR |185.30Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_747 |20.58Mb
  - ğŸ‡¬ğŸ‡§GB_758 |39.20Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_749 |42.40Mb
  - ğŸ‡²ğŸ‡½MX_900 |41.43Mb
  - ğŸ‡·ğŸ‡ºRU_902 |125.86Mb
  - disney_RU |441.43Mb
  - ğŸ‡®ğŸ‡³IN_895 |152.83Mb
  - ğŸ‡­ğŸ‡°HK_894 |71.50Mb
  - Relay_ğŸ‡¯ğŸ‡µJP-ğŸ‡¯ğŸ‡µJP_896 |10.80Mb
  - netflix_LU |23.81Mb
  - ğŸ‡ºğŸ‡¸US_913 |35.41Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_914 |40.27Mb
  - ğŸ‡²ğŸ‡¾MY_901 |19.23Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡§ğŸ‡¬BG_908 |447.99Mb
  - ğŸ‡ºğŸ‡¸US_915 |286.95Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - Relay_-ğŸ‡ºğŸ‡¸US_501 |40.83Mb
  - _470 |15.84Mb
  - _467 |13.68Mb
  - disney_SG |33.87Mb
  - _733 |28.18Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_744 |14.35Mb
  - Relay_-ğŸ‡ºğŸ‡¸US_475 |16.09Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_745 |40.49Mb
  - _743 |11.73Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_746 |14.01Mb
  - disney_FR |218.26Mb
  - ğŸ‡§ğŸ‡·BR_754 |159.76Mb
  - disney_FR |185.30Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_747 |20.58Mb
  - ğŸ‡¬ğŸ‡§GB_758 |39.20Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_749 |42.40Mb
  - ğŸ‡²ğŸ‡½MX_900 |41.43Mb
  - ğŸ‡·ğŸ‡ºRU_902 |125.86Mb
  - disney_RU |441.43Mb
  - ğŸ‡®ğŸ‡³IN_895 |152.83Mb
  - ğŸ‡­ğŸ‡°HK_894 |71.50Mb
  - Relay_ğŸ‡¯ğŸ‡µJP-ğŸ‡¯ğŸ‡µJP_896 |10.80Mb
  - netflix_LU |23.81Mb
  - ğŸ‡ºğŸ‡¸US_913 |35.41Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_914 |40.27Mb
  - ğŸ‡²ğŸ‡¾MY_901 |19.23Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡§ğŸ‡¬BG_908 |447.99Mb
  - ğŸ‡ºğŸ‡¸US_915 |286.95Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
