port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: ' |17.04Mb'
  server: 207.90.237.163
  type: ss
  port: 808
  udp: true
  password: tvX1v#NSFP_LG_bJ
  cipher: chacha20-ietf-poly1305
- name: Relay_-ğŸ‡¸ğŸ‡¬SG_214 | 8.62Mb
  server: spevoy.missionsec.us
  type: trojan
  port: 443
  udp: true
  password: R3SuZDAZXDO3FYqxwK36l7gpSIBTFCxlzc89a7qg3S9p8BOCeACSFaA8nxeD2ZlT5Nl4O
  skip-cert-verify: true
- name: ğŸ‡¨ğŸ‡¦CA_217 | 2.81Mb
  server: 138.197.141.58
  type: ss
  country: ğŸ‡¨ğŸ‡¦CA
  port: 8080
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: ğŸ‡¦ğŸ‡ªAE_215 | 3.32Mb
  server: 89.35.119.87
  type: ss
  country: ğŸ‡¦ğŸ‡ªAE
  port: 5904
  password: 5TZnwPb23pQS39lIucspJw
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡©ğŸ‡ªDE_220 | 0.47Mb
  server: 93.186.201.64
  type: ss
  country: ğŸ‡©ğŸ‡ªDE
  port: 57456
  password: fe166c5b3465540f
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ªğŸ‡¸ES_222 |24.83Mb
  server: 5.188.181.201
  type: ss
  country: ğŸ‡ªğŸ‡¸ES
  port: 9020
  password: BNmAXXxAHYpTRdzu
  cipher: aes-256-cfb
- name: ğŸ‡«ğŸ‡·FR_223 |15.16Mb
  server: 51.15.17.169
  type: ss
  country: ğŸ‡«ğŸ‡·FR
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: Pool_ğŸ‡¬ğŸ‡§GB_228 | 2.97Mb
  server: 79.127.233.170
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ğŸ‡«ğŸ‡·FR_224 | 3.40Mb
  server: 83.147.216.70
  type: ss
  country: ğŸ‡«ğŸ‡·FR
  port: 64519
  password: KaKeuUdiSZJ1vl2jU8GnfY
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_227 | 2.39Mb
  server: 212.102.53.79
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: shadowsocks
  cipher: aes-128-gcm
- name: ğŸ‡«ğŸ‡·FR_225 | 1.06Mb
  server: 83.147.216.70
  type: ss
  country: ğŸ‡«ğŸ‡·FR
  port: 64519
  password: Mal9DeKnSFhULd5Nbpkae0
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡«ğŸ‡·FR_226 | 2.61Mb
  server: 83.147.216.70
  type: ss
  country: ğŸ‡«ğŸ‡·FR
  port: 64519
  password: YXgS8ComTam7qoesPlzlMo
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¬ğŸ‡§GB_229 | 3.19Mb
  server: 212.102.53.80
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 443
  password: shadowsocks
  cipher: aes-128-gcm
- name: ğŸ‡¯ğŸ‡µJP_235 |17.90Mb
  server: 160.16.123.124
  type: ss
  country: ğŸ‡¯ğŸ‡µJP
  port: 10087
  password: '10086'
  cipher: aes-128-gcm
- name: ğŸ‡°ğŸ‡·KR_236 |21.91Mb
  server: 221.139.79.57
  type: ss
  country: ğŸ‡°ğŸ‡·KR
  port: 37008
  password: qwerREWQ@@
  cipher: aes-256-cfb
- name: ğŸ‡±ğŸ‡¹LT_237 |37.61Mb
  server: 45.87.175.199
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: 4a2rfixophdjffa8KVA4Aa
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸ‡±ğŸ‡¹LT-ğŸ‡³ğŸ‡±NL_238 |40.28Mb
  server: 45.87.175.185
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_239 |19.54Mb
  server: 45.87.175.157
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: 1RWwXhwfAB5gAEozU4G2Pg
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_240 |31.14Mb
  server: 45.87.175.157
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: 4a2rfixophdjffa8KVA4Aa
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_241 |28.36Mb
  server: 45.87.175.164
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_242 |37.91Mb
  server: 45.87.175.166
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: 4a2rfixophdjffa8KVA4Aa
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸ‡±ğŸ‡¹LT-ğŸ‡³ğŸ‡±NL_243 |47.70Mb
  server: 45.87.175.181
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: 4a2rfixophdjffa8KVA4Aa
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_244 |45.38Mb
  server: 45.87.175.157
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: Pool_ğŸ‡­ğŸ‡°HK_230 |811.00Mb
  server: 150.107.46.21
  type: ssr
  country: ğŸ‡­ğŸ‡°HK
  port: 8083
  password: iFqnzSscN
  cipher: aes-256-cfb
  protocol: origin
  obfs: tls1.2_ticket_auth
- name: ğŸ‡³ğŸ‡±NL_245 |47.42Mb
  server: 103.104.247.45
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 8080
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡³ğŸ‡±NL_246 |40.96Mb
  server: 193.29.139.160
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 8080
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡³ğŸ‡±NL_247 |18.05Mb
  server: 193.29.139.227
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 8080
  password: 4a2rfixophdjffa8KVA4Aa
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡³ğŸ‡±NL_248 |32.79Mb
  server: 193.29.139.202
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 8080
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡³ğŸ‡±NL_249 |41.62Mb
  server: 79.127.227.198
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 990
  password: f8f7aCzcPKbsF8p3
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡µğŸ‡±PL_253 |110.67Mb
  server: 217.30.10.70
  type: ss
  country: ğŸ‡µğŸ‡±PL
  port: 9073
  password: daFYagqDdBdA6VTX
  cipher: aes-256-cfb
- name: ğŸ‡µğŸ‡±PL_256 | 0.79Mb
  server: 45.144.49.140
  type: ss
  country: ğŸ‡µğŸ‡±PL
  port: 57456
  password: 360e21d21977dc11
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡µğŸ‡±PL_257 |28.06Mb
  server: 217.30.10.18
  type: ss
  country: ğŸ‡µğŸ‡±PL
  port: 9003
  password: JdmRK9gMEqFgs8nP
  cipher: aes-256-cfb
- name: ğŸ‡µğŸ‡±PL_259 | 0.20Mb
  server: 217.30.10.18
  type: ss
  country: ğŸ‡µğŸ‡±PL
  port: 9014
  password: KnJGad3FqTvjqbaX
  cipher: aes-256-cfb
- name: ğŸ‡µğŸ‡±PL_260 |31.08Mb
  server: 217.30.10.70
  type: ss
  country: ğŸ‡µğŸ‡±PL
  port: 9041
  password: U6qnYRhfyDmn8sgn
  cipher: aes-256-cfb
- name: ğŸ‡µğŸ‡±PL_261 | 0.30Mb
  server: 217.30.10.18
  type: ss
  country: ğŸ‡µğŸ‡±PL
  port: 9027
  password: EXN3S3eQpjE7EJu8
  cipher: aes-256-cfb
- name: ğŸ‡µğŸ‡±PL_264 |21.92Mb
  server: 217.30.10.18
  type: ss
  country: ğŸ‡µğŸ‡±PL
  port: 9042
  password: S7KwUu7yBy58S3Ga
  cipher: aes-256-cfb
- name: ğŸ‡µğŸ‡±PL_266 |24.22Mb
  server: 217.30.10.18
  type: ss
  country: ğŸ‡µğŸ‡±PL
  port: 9031
  password: BwcAUZk8hUFAkDGN
  cipher: aes-256-cfb
- name: ğŸ‡µğŸ‡±PL_267 |19.86Mb
  server: 217.30.10.70
  type: ss
  country: ğŸ‡µğŸ‡±PL
  port: 9064
  password: cp8pRSUAyLhTfVWH
  cipher: aes-256-cfb
- name: ğŸ‡·ğŸ‡ºRU_273 | 9.99Mb
  server: 94.159.96.245
  type: ss
  country: ğŸ‡·ğŸ‡ºRU
  port: 11902
  password: DbqAtRexqtqOYyiLiAmuSA
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¨ğŸ‡¦CA_218 | 2.56Mb
  server: 23.162.200.125
  type: vmess
  country: ğŸ‡¨ğŸ‡¦CA
  port: 2201
  uuid: 86eab4ac-dbe2-4e2f-a490-4fccade87c35
  alterId: 0
  cipher: auto
  network: tcp
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡ªğŸ‡¸ES_221 | 0.83Mb
  server: 194.87.45.189
  type: ss
  country: ğŸ‡ªğŸ‡¸ES
  port: 443
  password: cUgm3LyixNv6AElxYBPkoP
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡·ğŸ‡ºRU_277 | 7.29Mb
  server: 94.159.96.245
  type: ss
  country: ğŸ‡·ğŸ‡ºRU
  port: 11902
  password: 3zMT7XQjbCLEPbnNLSJ9j7
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¸ğŸ‡ªSE_280 | 3.23Mb
  server: 13.53.37.208
  type: ss
  country: ğŸ‡¸ğŸ‡ªSE
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡¸ğŸ‡ªSE_281 | 0.39Mb
  server: 51.21.244.34
  type: ss
  country: ğŸ‡¸ğŸ‡ªSE
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡¸ğŸ‡¬SG_282 | 7.21Mb
  server: 68.183.227.216
  type: ss
  country: ğŸ‡¸ğŸ‡¬SG
  port: 8080
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: ğŸ‡¸ğŸ‡¬SG_284 | 0.93Mb
  server: 64.176.85.73
  type: ss
  country: ğŸ‡¸ğŸ‡¬SG
  port: 1866
  password: oXGp1+ihlfKg826H
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¹ğŸ‡·TR_285 |76.86Mb
  server: 45.89.52.66
  type: ss
  country: ğŸ‡¹ğŸ‡·TR
  port: 9014
  password: KnJGad3FqTvjqbaX
  cipher: aes-256-cfb
- name: ğŸ‡ºğŸ‡¸US_293 | 4.50Mb
  server: 64.74.163.218
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 990
  password: f8f7aCzcPKbsF8p3
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_294 | 5.97Mb
  server: 13.222.168.151
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡ºğŸ‡¸US_296 | 2.85Mb
  server: 37.19.198.160
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: shadowsocks
  cipher: aes-128-gcm
- name: ğŸ‡·ğŸ‡ºRU_276 | 7.09Mb
  server: 94.159.96.245
  type: ss
  country: ğŸ‡·ğŸ‡ºRU
  port: 11902
  password: hYWkDRffZWVhir3riEMtGJ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_299 | 4.05Mb
  server: 173.244.56.9
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: shadowsocks
  cipher: aes-128-gcm
- name: ğŸ‡ºğŸ‡¸US_298 | 3.44Mb
  server: 149.22.87.241
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: shadowsocks
  cipher: aes-128-gcm
- name: ğŸ‡ºğŸ‡¸US_302 | 5.80Mb
  server: 154.44.15.133
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 44642
  password: iHapGY8XoW
  cipher: aes-256-gcm
- name: ğŸ‡ºğŸ‡¸US_301 | 3.39Mb
  server: 159.203.72.194
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 8443
  password: Y2PhBJtc03EnomK4Atb9h6q2cgnAcPV/SxRY5D9wCgU=
  cipher: aes-256-gcm
- name: ğŸ‡ºğŸ‡¸US_303 | 5.78Mb
  server: 38.107.226.159
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 7307
  password: FoOiGlkAA9yPEGP
  cipher: aes-256-gcm
- name: Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_304 | 3.76Mb
  server: 193.124.24.247
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 6508
  uuid: b68fead5-5b0b-43a1-c34a-804467f0f368
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_305 | 3.24Mb
  server: 193.124.24.247
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 6511
  uuid: 5ef4e89b-262f-4c74-e793-c7332079f251
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_306 | 2.97Mb
  server: 193.124.24.247
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 6507
  uuid: 3003e094-707c-4dbb-faca-4b8d579bc604
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_US | 3.22Mb
  server: 193.124.24.230
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 6505
  uuid: f77456b5-5a82-45ba-a941-1a83c09a1f41
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_309 | 4.53Mb
  server: 193.124.24.230
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 6507
  uuid: 5d12135d-1676-490c-b490-b6e624c431a3
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡ºğŸ‡¸US_295 |65.62Mb
  server: 23.157.40.101
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 8009
  password: XKFKl2rULjIp74
  cipher: aes-256-gcm
- name: Pool_ğŸ‡»ğŸ‡³VN_311
  server: 103.186.154.74
  type: ss
  country: ğŸ‡»ğŸ‡³VN
  port: 38388
  password: Xn8jKdmDM00IeO%#$#fJAMtsEAEUOpH/YWYtYqDFnT0SV
  cipher: aes-256-cfb
- name: ğŸ‡¹ğŸ‡·TR_286 | 0.35Mb
  server: 83.217.9.4
  type: ss
  country: ğŸ‡¹ğŸ‡·TR
  port: 443
  password: v2LBhok5lvjR
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_307 | 2.65Mb
  server: 193.124.24.247
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 6510
  uuid: 8f44f672-e53b-44fb-b502-c886d37107b5
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡ºğŸ‡¸US_290 | 7.97Mb
  server: 23.157.40.5
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 6679
  password: TEzjfAYq2IjtuoS
  cipher: aes-256-gcm
- name: ğŸ‡ºğŸ‡¸US_292 | 5.18Mb
  server: 23.157.40.5
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 5500
  password: KixLvKzwjekG00rm
  cipher: aes-256-gcm
- name: ğŸ‡ºğŸ‡¸US_297 | 2.18Mb
  server: 23.157.40.5
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 3306
  password: Y6R9pAtvxxzmGC
  cipher: aes-256-gcm
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - ' |17.04Mb'
  - Relay_-ğŸ‡¸ğŸ‡¬SG_214 | 8.62Mb
  - ğŸ‡¨ğŸ‡¦CA_217 | 2.81Mb
  - ğŸ‡¦ğŸ‡ªAE_215 | 3.32Mb
  - ğŸ‡©ğŸ‡ªDE_220 | 0.47Mb
  - ğŸ‡ªğŸ‡¸ES_222 |24.83Mb
  - ğŸ‡«ğŸ‡·FR_223 |15.16Mb
  - Pool_ğŸ‡¬ğŸ‡§GB_228 | 2.97Mb
  - ğŸ‡«ğŸ‡·FR_224 | 3.40Mb
  - ğŸ‡¬ğŸ‡§GB_227 | 2.39Mb
  - ğŸ‡«ğŸ‡·FR_225 | 1.06Mb
  - ğŸ‡«ğŸ‡·FR_226 | 2.61Mb
  - ğŸ‡¬ğŸ‡§GB_229 | 3.19Mb
  - ğŸ‡¯ğŸ‡µJP_235 |17.90Mb
  - ğŸ‡°ğŸ‡·KR_236 |21.91Mb
  - ğŸ‡±ğŸ‡¹LT_237 |37.61Mb
  - Relay_ğŸ‡±ğŸ‡¹LT-ğŸ‡³ğŸ‡±NL_238 |40.28Mb
  - ğŸ‡±ğŸ‡¹LT_239 |19.54Mb
  - ğŸ‡±ğŸ‡¹LT_240 |31.14Mb
  - ğŸ‡±ğŸ‡¹LT_241 |28.36Mb
  - ğŸ‡±ğŸ‡¹LT_242 |37.91Mb
  - Relay_ğŸ‡±ğŸ‡¹LT-ğŸ‡³ğŸ‡±NL_243 |47.70Mb
  - ğŸ‡±ğŸ‡¹LT_244 |45.38Mb
  - Pool_ğŸ‡­ğŸ‡°HK_230 |811.00Mb
  - ğŸ‡³ğŸ‡±NL_245 |47.42Mb
  - ğŸ‡³ğŸ‡±NL_246 |40.96Mb
  - ğŸ‡³ğŸ‡±NL_247 |18.05Mb
  - ğŸ‡³ğŸ‡±NL_248 |32.79Mb
  - ğŸ‡³ğŸ‡±NL_249 |41.62Mb
  - ğŸ‡µğŸ‡±PL_253 |110.67Mb
  - ğŸ‡µğŸ‡±PL_256 | 0.79Mb
  - ğŸ‡µğŸ‡±PL_257 |28.06Mb
  - ğŸ‡µğŸ‡±PL_259 | 0.20Mb
  - ğŸ‡µğŸ‡±PL_260 |31.08Mb
  - ğŸ‡µğŸ‡±PL_261 | 0.30Mb
  - ğŸ‡µğŸ‡±PL_264 |21.92Mb
  - ğŸ‡µğŸ‡±PL_266 |24.22Mb
  - ğŸ‡µğŸ‡±PL_267 |19.86Mb
  - ğŸ‡·ğŸ‡ºRU_273 | 9.99Mb
  - ğŸ‡¨ğŸ‡¦CA_218 | 2.56Mb
  - ğŸ‡ªğŸ‡¸ES_221 | 0.83Mb
  - ğŸ‡·ğŸ‡ºRU_277 | 7.29Mb
  - ğŸ‡¸ğŸ‡ªSE_280 | 3.23Mb
  - ğŸ‡¸ğŸ‡ªSE_281 | 0.39Mb
  - ğŸ‡¸ğŸ‡¬SG_282 | 7.21Mb
  - ğŸ‡¸ğŸ‡¬SG_284 | 0.93Mb
  - ğŸ‡¹ğŸ‡·TR_285 |76.86Mb
  - ğŸ‡ºğŸ‡¸US_293 | 4.50Mb
  - ğŸ‡ºğŸ‡¸US_294 | 5.97Mb
  - ğŸ‡ºğŸ‡¸US_296 | 2.85Mb
  - ğŸ‡·ğŸ‡ºRU_276 | 7.09Mb
  - ğŸ‡ºğŸ‡¸US_299 | 4.05Mb
  - ğŸ‡ºğŸ‡¸US_298 | 3.44Mb
  - ğŸ‡ºğŸ‡¸US_302 | 5.80Mb
  - ğŸ‡ºğŸ‡¸US_301 | 3.39Mb
  - ğŸ‡ºğŸ‡¸US_303 | 5.78Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_304 | 3.76Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_305 | 3.24Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_306 | 2.97Mb
  - disney_US | 3.22Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_309 | 4.53Mb
  - ğŸ‡ºğŸ‡¸US_295 |65.62Mb
  - Pool_ğŸ‡»ğŸ‡³VN_311
  - ğŸ‡¹ğŸ‡·TR_286 | 0.35Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_307 | 2.65Mb
  - ğŸ‡ºğŸ‡¸US_290 | 7.97Mb
  - ğŸ‡ºğŸ‡¸US_292 | 5.18Mb
  - ğŸ‡ºğŸ‡¸US_297 | 2.18Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - ' |17.04Mb'
  - Relay_-ğŸ‡¸ğŸ‡¬SG_214 | 8.62Mb
  - ğŸ‡¨ğŸ‡¦CA_217 | 2.81Mb
  - ğŸ‡¦ğŸ‡ªAE_215 | 3.32Mb
  - ğŸ‡©ğŸ‡ªDE_220 | 0.47Mb
  - ğŸ‡ªğŸ‡¸ES_222 |24.83Mb
  - ğŸ‡«ğŸ‡·FR_223 |15.16Mb
  - Pool_ğŸ‡¬ğŸ‡§GB_228 | 2.97Mb
  - ğŸ‡«ğŸ‡·FR_224 | 3.40Mb
  - ğŸ‡¬ğŸ‡§GB_227 | 2.39Mb
  - ğŸ‡«ğŸ‡·FR_225 | 1.06Mb
  - ğŸ‡«ğŸ‡·FR_226 | 2.61Mb
  - ğŸ‡¬ğŸ‡§GB_229 | 3.19Mb
  - ğŸ‡¯ğŸ‡µJP_235 |17.90Mb
  - ğŸ‡°ğŸ‡·KR_236 |21.91Mb
  - ğŸ‡±ğŸ‡¹LT_237 |37.61Mb
  - Relay_ğŸ‡±ğŸ‡¹LT-ğŸ‡³ğŸ‡±NL_238 |40.28Mb
  - ğŸ‡±ğŸ‡¹LT_239 |19.54Mb
  - ğŸ‡±ğŸ‡¹LT_240 |31.14Mb
  - ğŸ‡±ğŸ‡¹LT_241 |28.36Mb
  - ğŸ‡±ğŸ‡¹LT_242 |37.91Mb
  - Relay_ğŸ‡±ğŸ‡¹LT-ğŸ‡³ğŸ‡±NL_243 |47.70Mb
  - ğŸ‡±ğŸ‡¹LT_244 |45.38Mb
  - Pool_ğŸ‡­ğŸ‡°HK_230 |811.00Mb
  - ğŸ‡³ğŸ‡±NL_245 |47.42Mb
  - ğŸ‡³ğŸ‡±NL_246 |40.96Mb
  - ğŸ‡³ğŸ‡±NL_247 |18.05Mb
  - ğŸ‡³ğŸ‡±NL_248 |32.79Mb
  - ğŸ‡³ğŸ‡±NL_249 |41.62Mb
  - ğŸ‡µğŸ‡±PL_253 |110.67Mb
  - ğŸ‡µğŸ‡±PL_256 | 0.79Mb
  - ğŸ‡µğŸ‡±PL_257 |28.06Mb
  - ğŸ‡µğŸ‡±PL_259 | 0.20Mb
  - ğŸ‡µğŸ‡±PL_260 |31.08Mb
  - ğŸ‡µğŸ‡±PL_261 | 0.30Mb
  - ğŸ‡µğŸ‡±PL_264 |21.92Mb
  - ğŸ‡µğŸ‡±PL_266 |24.22Mb
  - ğŸ‡µğŸ‡±PL_267 |19.86Mb
  - ğŸ‡·ğŸ‡ºRU_273 | 9.99Mb
  - ğŸ‡¨ğŸ‡¦CA_218 | 2.56Mb
  - ğŸ‡ªğŸ‡¸ES_221 | 0.83Mb
  - ğŸ‡·ğŸ‡ºRU_277 | 7.29Mb
  - ğŸ‡¸ğŸ‡ªSE_280 | 3.23Mb
  - ğŸ‡¸ğŸ‡ªSE_281 | 0.39Mb
  - ğŸ‡¸ğŸ‡¬SG_282 | 7.21Mb
  - ğŸ‡¸ğŸ‡¬SG_284 | 0.93Mb
  - ğŸ‡¹ğŸ‡·TR_285 |76.86Mb
  - ğŸ‡ºğŸ‡¸US_293 | 4.50Mb
  - ğŸ‡ºğŸ‡¸US_294 | 5.97Mb
  - ğŸ‡ºğŸ‡¸US_296 | 2.85Mb
  - ğŸ‡·ğŸ‡ºRU_276 | 7.09Mb
  - ğŸ‡ºğŸ‡¸US_299 | 4.05Mb
  - ğŸ‡ºğŸ‡¸US_298 | 3.44Mb
  - ğŸ‡ºğŸ‡¸US_302 | 5.80Mb
  - ğŸ‡ºğŸ‡¸US_301 | 3.39Mb
  - ğŸ‡ºğŸ‡¸US_303 | 5.78Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_304 | 3.76Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_305 | 3.24Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_306 | 2.97Mb
  - disney_US | 3.22Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_309 | 4.53Mb
  - ğŸ‡ºğŸ‡¸US_295 |65.62Mb
  - Pool_ğŸ‡»ğŸ‡³VN_311
  - ğŸ‡¹ğŸ‡·TR_286 | 0.35Mb
  - Relay_ğŸ‡ºğŸ‡¸US-ğŸ‡ºğŸ‡¸US_307 | 2.65Mb
  - ğŸ‡ºğŸ‡¸US_290 | 7.97Mb
  - ğŸ‡ºğŸ‡¸US_292 | 5.18Mb
  - ğŸ‡ºğŸ‡¸US_297 | 2.18Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
