port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: disney_netflix_US |41.64Mb
  server: 38.14.99.179
  type: vmess
  port: 59807
  udp: true
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: auto
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: _448 |12.14Mb
  server: 74.117.196.232
  type: vmess
  port: 37934
  udp: true
  uuid: 254551f6-ec28-4938-ad0e-0aa4aa1965ec
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /speedtest
- name: disney_netflix_NL |237.95Mb
  server: 151.242.251.137
  type: ss
  port: 8080
  password: o5osZg269v5zHpYjr1xY9s
  cipher: chacha20-ietf-poly1305
- name: Relay_-ğŸ‡³ğŸ‡±NL_459 |22.00Mb
  server: 160.16.131.243
  type: trojan
  port: 2890
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¸ğŸ‡¬SG_461 |15.31Mb
  server: 160.16.131.243
  type: trojan
  port: 127
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¯ğŸ‡µJP_462 |10.04Mb
  server: 160.16.87.174
  type: trojan
  port: 3169
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: disney_HK |12.32Mb
  server: 58.152.30.120
  type: trojan
  port: 443
  udp: true
  password: BxceQaOe
  sni: t.me/ripaojiedian
  skip-cert-verify: true
- name: Relay_-ğŸ‡³ğŸ‡±NL_465 |40.67Mb
  server: 160.16.236.32
  type: trojan
  port: 4054
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¸ğŸ‡¬SG_467 |11.32Mb
  server: 160.16.107.37
  type: trojan
  port: 507
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡¸ğŸ‡¬SG_468 |10.27Mb
  server: 153.121.44.99
  type: trojan
  port: 507
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡³ğŸ‡±NL_469 |56.26Mb
  server: 160.16.151.196
  type: trojan
  port: 2890
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: Relay_-ğŸ‡³ğŸ‡±NL_471 |21.78Mb
  server: 160.16.116.227
  type: trojan
  port: 2890
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: disney_netflix_FR |43.16Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 40433
  uuid: d8fd8955-78db-49ba-d86f-3e4729f6ac4d
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_FR |67.39Mb
  server: 208.76.223.218
  type: vmess
  country: ğŸ‡ªğŸ‡¸ES
  port: 27092
  uuid: a0596ba6-72a3-4366-8992-77088da65bd8
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_NL |247.04Mb
  server: 82.38.31.218
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: disney_netflix_NL |219.23Mb
  server: 82.38.31.210
  type: ss
  country: ğŸ‡¬ğŸ‡§GB
  port: 8080
  password: k1dBOmOB4oqi7Ump37a1bQ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡§ğŸ‡·BR_480 |12.63Mb
  server: 38.180.16.86
  type: vmess
  country: ğŸ‡§ğŸ‡·BR
  port: 36104
  uuid: E146A8CB-9D2F-449C-ADCA-8736FB
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: Relay_-ğŸ‡¯ğŸ‡µJP_472 |14.73Mb
  server: 153.121.65.107
  type: trojan
  port: 1331
  password: 79314e99f0a473fe86efc7827942ad00
  sni: www.nintendogames.net
- name: ğŸ‡ºğŸ‡¸US_576 |43.24Mb
  server: 104.192.226.106
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: disney_netflix_NL |13.87Mb
  server: 45.87.175.166
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 443
  password: 1RWwXhwfAB5gAEozU4G2Pg
  cipher: chacha20-ietf-poly1305
- name: disney_RU |335.40Mb
  server: 38.60.223.8
  type: ss
  country: ğŸ‡·ğŸ‡ºRU
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: netflix_LU |19.79Mb
  server: 45.12.144.18
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: LQyAUItafUmmO3EZZx9UbiX6IGydSBgL
  cipher: chacha20-ietf-poly1305
- name: netflix_LT |126.99Mb
  server: 45.12.136.170
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: l668XHPejoSNNuD66BYzyehaCpZexiF7
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡°ğŸ‡·KR_555 |11.07Mb
  server: 146.56.112.110
  type: vmess
  country: ğŸ‡°ğŸ‡·KR
  port: 8888
  uuid: e7c302f3-90d6-42dd-9d7d-94a3683a3707
  alterId: 0
  cipher: auto
  network: tcp
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: disney_netflix_US |41.38Mb
  server: 38.14.99.163
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 59807
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 0
  cipher: auto
  network: tcp
  servername: 38.14.99.163
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
- name: ğŸ‡¸ğŸ‡¬SG_561 |10.64Mb
  server: 68.183.178.131
  type: vmess
  country: ğŸ‡¸ğŸ‡¬SG
  port: 58607
  uuid: c11c32cb-27b3-4afa-c0f3-fb250aa4959e
  alterId: 0
  cipher: auto
  network: ws
  servername: www.12333.monster
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
  ws-opts:
    path: /
    headers:
      HOST: www.12333.monster
- name: disney_netflix_HK |14.95Mb
  server: 38.54.98.110
  type: vmess
  country: ğŸ‡²ğŸ‡¾MY
  port: 2052
  uuid: 665d9b8f-153d-4907-adac-de12afd9c851
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  tls: true
  skip-cert-verify: true
- name: disney_HK |10.63Mb
  server: 45.136.12.37
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 38141
  uuid: fd291be6-b48d-43a1-da38-66c7f80e2f80
  alterId: 0
  cipher: auto
  network: none
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - disney_netflix_US |41.64Mb
  - _448 |12.14Mb
  - disney_netflix_NL |237.95Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_459 |22.00Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_461 |15.31Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_462 |10.04Mb
  - disney_HK |12.32Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_465 |40.67Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_467 |11.32Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_468 |10.27Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_469 |56.26Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_471 |21.78Mb
  - disney_netflix_FR |43.16Mb
  - disney_netflix_FR |67.39Mb
  - disney_netflix_NL |247.04Mb
  - disney_netflix_NL |219.23Mb
  - ğŸ‡§ğŸ‡·BR_480 |12.63Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_472 |14.73Mb
  - ğŸ‡ºğŸ‡¸US_576 |43.24Mb
  - disney_netflix_NL |13.87Mb
  - disney_RU |335.40Mb
  - netflix_LU |19.79Mb
  - netflix_LT |126.99Mb
  - ğŸ‡°ğŸ‡·KR_555 |11.07Mb
  - disney_netflix_US |41.38Mb
  - ğŸ‡¸ğŸ‡¬SG_561 |10.64Mb
  - disney_netflix_HK |14.95Mb
  - disney_HK |10.63Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - disney_netflix_US |41.64Mb
  - _448 |12.14Mb
  - disney_netflix_NL |237.95Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_459 |22.00Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_461 |15.31Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_462 |10.04Mb
  - disney_HK |12.32Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_465 |40.67Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_467 |11.32Mb
  - Relay_-ğŸ‡¸ğŸ‡¬SG_468 |10.27Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_469 |56.26Mb
  - Relay_-ğŸ‡³ğŸ‡±NL_471 |21.78Mb
  - disney_netflix_FR |43.16Mb
  - disney_netflix_FR |67.39Mb
  - disney_netflix_NL |247.04Mb
  - disney_netflix_NL |219.23Mb
  - ğŸ‡§ğŸ‡·BR_480 |12.63Mb
  - Relay_-ğŸ‡¯ğŸ‡µJP_472 |14.73Mb
  - ğŸ‡ºğŸ‡¸US_576 |43.24Mb
  - disney_netflix_NL |13.87Mb
  - disney_RU |335.40Mb
  - netflix_LU |19.79Mb
  - netflix_LT |126.99Mb
  - ğŸ‡°ğŸ‡·KR_555 |11.07Mb
  - disney_netflix_US |41.38Mb
  - ğŸ‡¸ğŸ‡¬SG_561 |10.64Mb
  - disney_netflix_HK |14.95Mb
  - disney_HK |10.63Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
