port: 7890
socks-port: 7891
allow-lan: true
mode: Rule
log-level: info
external-controller: :9090
proxies:
- name: ğŸ‡§ğŸ‡¬BG_369 |42.29Mb
  server: 37.19.203.147
  type: ss
  country: ğŸ‡§ğŸ‡¬BG
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ğŸ‡«ğŸ‡·FR_396 |53.96Mb
  server: 83.147.216.70
  type: ss
  country: ğŸ‡«ğŸ‡·FR
  port: 64519
  password: eBzKXxEmQlAZKIBC8PhQYZ
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡«ğŸ‡·FR_395 |65.33Mb
  server: 83.147.216.70
  type: ss
  country: ğŸ‡«ğŸ‡·FR
  port: 64519
  password: F3nY73di5onWV3gotbpI0Q
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¦ğŸ‡·AR_361 |26.43Mb
  server: 38.54.45.129
  type: ss
  country: ğŸ‡¦ğŸ‡·AR
  port: 990
  password: f8f7aCzcPKbsF8p3
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡«ğŸ‡·FR_400 |52.51Mb
  server: 83.147.216.70
  type: ss
  country: ğŸ‡«ğŸ‡·FR
  port: 64519
  password: Vq1y6zEAmcfGoBB0dRBbV7
  cipher: chacha20-ietf-poly1305
- name: Pool_ğŸ‡­ğŸ‡°HK_405 |632.00Mb
  server: 150.107.46.21
  type: ssr
  country: ğŸ‡­ğŸ‡°HK
  port: 8083
  password: iFqnzSscN
  cipher: aes-256-cfb
  protocol: origin
  obfs: tls1.2_ticket_auth
- name: ğŸ‡®ğŸ‡³IN_413 |21.20Mb
  server: 13.126.253.30
  type: ss
  country: ğŸ‡®ğŸ‡³IN
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡®ğŸ‡³IN_411 |17.41Mb
  server: 52.66.211.233
  type: ss
  country: ğŸ‡®ğŸ‡³IN
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡®ğŸ‡³IN_412 |11.66Mb
  server: 13.126.110.79
  type: ss
  country: ğŸ‡®ğŸ‡³IN
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: Relay_ğŸ‡®ğŸ‡·IR-ğŸ‡³ğŸ‡±NL_425 |42.47Mb
  server: 151.242.251.144
  type: ss
  country: ğŸ‡®ğŸ‡·IR
  port: 8080
  password: QCXDxuDlTTMD7jtgHUjIoj
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡®ğŸ‡³IN_410 |32.10Mb
  server: 103.111.114.29
  type: ss
  country: ğŸ‡®ğŸ‡³IN
  port: 57456
  password: 360e21d21977dc11
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸ‡®ğŸ‡·IR-ğŸ‡³ğŸ‡±NL_426 |46.18Mb
  server: 151.242.251.153
  type: ss
  country: ğŸ‡®ğŸ‡·IR
  port: 8080
  password: cvII85TrW6n0OGyfpHVS1u
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸ‡®ğŸ‡·IR-ğŸ‡³ğŸ‡±NL_427 |44.38Mb
  server: 151.242.251.137
  type: ss
  country: ğŸ‡®ğŸ‡·IR
  port: 8080
  password: 4a2rfixophdjffa8KVA4Aa
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡®ğŸ‡·IR_429 |29.73Mb
  server: 151.242.251.147
  type: ss
  country: ğŸ‡®ğŸ‡·IR
  port: 8080
  password: 4a2rfixophdjffa8KVA4Aa
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸ‡®ğŸ‡·IR-ğŸ‡³ğŸ‡±NL_428 |45.81Mb
  server: 151.242.251.153
  type: ss
  country: ğŸ‡®ğŸ‡·IR
  port: 8080
  password: QCXDxuDlTTMD7jtgHUjIoj
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸ‡®ğŸ‡·IR-ğŸ‡³ğŸ‡±NL_430 |39.18Mb
  server: 151.242.251.144
  type: ss
  country: ğŸ‡®ğŸ‡·IR
  port: 8080
  password: o5osZg269v5zHpYjr1xY9s
  cipher: chacha20-ietf-poly1305
- name: Relay_ğŸ‡®ğŸ‡·IR-ğŸ‡³ğŸ‡±NL_431 |36.81Mb
  server: 151.242.251.137
  type: ss
  country: ğŸ‡®ğŸ‡·IR
  port: 8080
  password: QCXDxuDlTTMD7jtgHUjIoj
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_439 |32.69Mb
  server: 45.87.175.171
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: QCXDxuDlTTMD7jtgHUjIoj
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_441 |11.95Mb
  server: 45.87.175.157
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: 4a2rfixophdjffa8KVA4Aa
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_442 |24.89Mb
  server: 45.87.175.157
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: 1RWwXhwfAB5gAEozU4G2Pg
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_443 |23.44Mb
  server: 45.87.175.171
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: 1RWwXhwfAB5gAEozU4G2Pg
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¯ğŸ‡µJP_432 |50.29Mb
  server: 202.182.98.223
  type: ss
  country: ğŸ‡¯ğŸ‡µJP
  port: 9443
  password: lINaALnHIiH4cSj8pJn6TQ==
  cipher: aes-128-gcm
- name: ğŸ‡¯ğŸ‡µJP_434 |19.61Mb
  server: 194.68.27.76
  type: ss
  country: ğŸ‡¯ğŸ‡µJP
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ğŸ‡±ğŸ‡¹LT_444 |23.29Mb
  server: 45.87.175.171
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: 4a2rfixophdjffa8KVA4Aa
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_446 |23.79Mb
  server: 45.87.175.65
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡±ğŸ‡¹LT_449 |26.02Mb
  server: 45.87.175.92
  type: ss
  country: ğŸ‡±ğŸ‡¹LT
  port: 8080
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡³ğŸ‡±NL_453 |38.32Mb
  server: 193.29.139.157
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 8080
  password: QCXDxuDlTTMD7jtgHUjIoj
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡³ğŸ‡±NL_455 |16.85Mb
  server: 193.29.139.227
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 8080
  password: 4a2rfixophdjffa8KVA4Aa
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡³ğŸ‡±NL_456 |22.45Mb
  server: 193.29.139.199
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 8080
  password: 4a2rfixophdjffa8KVA4Aa
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡³ğŸ‡±NL_454 |42.09Mb
  server: 79.127.227.53
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ğŸ‡³ğŸ‡±NL_457 |27.64Mb
  server: 79.127.227.198
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 990
  password: f8f7aCzcPKbsF8p3
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡³ğŸ‡±NL_460 |32.81Mb
  server: 193.29.139.157
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 8080
  password: 4a2rfixophdjffa8KVA4Aa
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡³ğŸ‡±NL_458 |42.61Mb
  server: 193.29.139.162
  type: ss
  country: ğŸ‡³ğŸ‡±NL
  port: 8080
  password: 4a2rfixophdjffa8KVA4Aa
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡µğŸ‡±PL_462 |54.42Mb
  server: 217.30.10.70
  type: ss
  country: ğŸ‡µğŸ‡±PL
  port: 9059
  password: 9XwYyZsK8SNzQDtY
  cipher: aes-256-cfb
- name: ğŸ‡ºğŸ‡¸US_509 |27.43Mb
  server: 54.90.199.180
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡ºğŸ‡¸US_515 |24.53Mb
  server: 54.234.186.14
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡µğŸ‡±PL_467 |37.08Mb
  server: 217.30.10.70
  type: ss
  country: ğŸ‡µğŸ‡±PL
  port: 9037
  password: TN2YqghxeFDKZfLU
  cipher: aes-256-cfb
- name: ğŸ‡ºğŸ‡¸US_517 |26.56Mb
  server: 54.82.229.122
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡ºğŸ‡¸US_505 |25.99Mb
  server: 104.167.197.25
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 57456
  password: 360e21d21977dc11
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_522 |24.98Mb
  server: 54.84.99.165
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡ºğŸ‡¸US_524 |21.67Mb
  server: 52.90.171.241
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: disney_US |55.67Mb
  server: 107.151.182.197
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 8080
  password: 14fFPrbezE3HDZzsMOr6
  cipher: rc4-md5
- name: ğŸ‡µğŸ‡±PL_468 |21.12Mb
  server: 92.118.205.228
  type: ss
  country: ğŸ‡µğŸ‡±PL
  port: 990
  password: f8f7aCzcPKbsF8p3
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_537 |32.55Mb
  server: 64.74.163.130
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 990
  password: f8f7aCzcPKbsF8p3
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_540 |12.73Mb
  server: 54.227.21.67
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: amazonskr05
  cipher: aes-256-cfb
- name: ğŸ‡ºğŸ‡¸US_507 |31.36Mb
  server: 45.158.171.66
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 8080
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_543 |44.96Mb
  server: 104.192.226.106
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 989
  password: f8f7aCzcPKbsF8p3
  cipher: aes-256-cfb
- name: ğŸ‡ºğŸ‡¸US_542 |35.55Mb
  server: 64.74.163.218
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 990
  password: f8f7aCzcPKbsF8p3
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_547 |57.46Mb
  server: 71.19.148.143
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 443
  password: p78naCf2EfOlRSLTX0wFVx
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡¹ğŸ‡·TR_486 |15.91Mb
  server: 45.89.52.66
  type: ss
  country: ğŸ‡¹ğŸ‡·TR
  port: 9019
  password: GA9KzeEgvfxNrgmM
  cipher: aes-256-cfb
- name: ğŸ‡ºğŸ‡¸US_528 |38.77Mb
  server: 45.158.171.146
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 8080
  password: 4a2rfixophdjffa8KVA4Aa
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡µğŸ‡¾PY_474 |31.28Mb
  server: 38.165.233.18
  type: ss
  country: ğŸ‡µğŸ‡¾PY
  port: 990
  password: f8f7aCzcPKbsF8p3
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_529 |11.55Mb
  server: 23.157.40.5
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 5000
  password: Y6R9pAtvxxzmGC
  cipher: aes-256-gcm
- name: ğŸ‡ºğŸ‡¸US_533 |10.20Mb
  server: 23.157.40.5
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 8008
  password: XKFKl2rULjIp74
  cipher: aes-256-gcm
- name: ğŸ‡ºğŸ‡¸US_556 |30.02Mb
  server: 104.192.226.106
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 990
  password: f8f7aCzcPKbsF8p3
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_552 |15.61Mb
  server: 167.88.61.110
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 6679
  password: TEzjfAYq2IjtuoS
  cipher: aes-256-gcm
- name: ğŸ‡ºğŸ‡¸US_549 |31.44Mb
  server: 45.158.171.70
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 8080
  password: oZIoA69Q8yhcQV8ka3Pa3A
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_551 |14.10Mb
  server: 23.157.40.5
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 5499
  password: lGqs95QkFHo2NV
  cipher: aes-256-gcm
- name: ğŸ‡ºğŸ‡¸US_564 |24.08Mb
  server: 38.54.57.90
  type: ss
  country: ğŸ‡ºğŸ‡¸US
  port: 990
  password: ARgvGZywA+gacgGV26Bvmu05+wZmRW/j+AdU+Z8Bt44=
  cipher: chacha20-ietf-poly1305
- name: ğŸ‡ºğŸ‡¸US_581 |79.55Mb
  server: 66.253.7.254
  type: vmess
  country: ğŸ‡ºğŸ‡¸US
  port: 45979
  uuid: 23bdf6df-c482-46d0-c0f4-5a98d534ea11
  alterId: 0
  cipher: auto
  network: ws
  http-opts: {}
  h2-opts: {}
  skip-cert-verify: true
  ws-opts:
    path: /test
proxy-groups:
- name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  type: select
  proxies:
  - â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  - ğŸ‡§ğŸ‡¬BG_369 |42.29Mb
  - ğŸ‡«ğŸ‡·FR_396 |53.96Mb
  - ğŸ‡«ğŸ‡·FR_395 |65.33Mb
  - ğŸ‡¦ğŸ‡·AR_361 |26.43Mb
  - ğŸ‡«ğŸ‡·FR_400 |52.51Mb
  - Pool_ğŸ‡­ğŸ‡°HK_405 |632.00Mb
  - ğŸ‡®ğŸ‡³IN_413 |21.20Mb
  - ğŸ‡®ğŸ‡³IN_411 |17.41Mb
  - ğŸ‡®ğŸ‡³IN_412 |11.66Mb
  - Relay_ğŸ‡®ğŸ‡·IR-ğŸ‡³ğŸ‡±NL_425 |42.47Mb
  - ğŸ‡®ğŸ‡³IN_410 |32.10Mb
  - Relay_ğŸ‡®ğŸ‡·IR-ğŸ‡³ğŸ‡±NL_426 |46.18Mb
  - Relay_ğŸ‡®ğŸ‡·IR-ğŸ‡³ğŸ‡±NL_427 |44.38Mb
  - ğŸ‡®ğŸ‡·IR_429 |29.73Mb
  - Relay_ğŸ‡®ğŸ‡·IR-ğŸ‡³ğŸ‡±NL_428 |45.81Mb
  - Relay_ğŸ‡®ğŸ‡·IR-ğŸ‡³ğŸ‡±NL_430 |39.18Mb
  - Relay_ğŸ‡®ğŸ‡·IR-ğŸ‡³ğŸ‡±NL_431 |36.81Mb
  - ğŸ‡±ğŸ‡¹LT_439 |32.69Mb
  - ğŸ‡±ğŸ‡¹LT_441 |11.95Mb
  - ğŸ‡±ğŸ‡¹LT_442 |24.89Mb
  - ğŸ‡±ğŸ‡¹LT_443 |23.44Mb
  - ğŸ‡¯ğŸ‡µJP_432 |50.29Mb
  - ğŸ‡¯ğŸ‡µJP_434 |19.61Mb
  - ğŸ‡±ğŸ‡¹LT_444 |23.29Mb
  - ğŸ‡±ğŸ‡¹LT_446 |23.79Mb
  - ğŸ‡±ğŸ‡¹LT_449 |26.02Mb
  - ğŸ‡³ğŸ‡±NL_453 |38.32Mb
  - ğŸ‡³ğŸ‡±NL_455 |16.85Mb
  - ğŸ‡³ğŸ‡±NL_456 |22.45Mb
  - ğŸ‡³ğŸ‡±NL_454 |42.09Mb
  - ğŸ‡³ğŸ‡±NL_457 |27.64Mb
  - ğŸ‡³ğŸ‡±NL_460 |32.81Mb
  - ğŸ‡³ğŸ‡±NL_458 |42.61Mb
  - ğŸ‡µğŸ‡±PL_462 |54.42Mb
  - ğŸ‡ºğŸ‡¸US_509 |27.43Mb
  - ğŸ‡ºğŸ‡¸US_515 |24.53Mb
  - ğŸ‡µğŸ‡±PL_467 |37.08Mb
  - ğŸ‡ºğŸ‡¸US_517 |26.56Mb
  - ğŸ‡ºğŸ‡¸US_505 |25.99Mb
  - ğŸ‡ºğŸ‡¸US_522 |24.98Mb
  - ğŸ‡ºğŸ‡¸US_524 |21.67Mb
  - disney_US |55.67Mb
  - ğŸ‡µğŸ‡±PL_468 |21.12Mb
  - ğŸ‡ºğŸ‡¸US_537 |32.55Mb
  - ğŸ‡ºğŸ‡¸US_540 |12.73Mb
  - ğŸ‡ºğŸ‡¸US_507 |31.36Mb
  - ğŸ‡ºğŸ‡¸US_543 |44.96Mb
  - ğŸ‡ºğŸ‡¸US_542 |35.55Mb
  - ğŸ‡ºğŸ‡¸US_547 |57.46Mb
  - ğŸ‡¹ğŸ‡·TR_486 |15.91Mb
  - ğŸ‡ºğŸ‡¸US_528 |38.77Mb
  - ğŸ‡µğŸ‡¾PY_474 |31.28Mb
  - ğŸ‡ºğŸ‡¸US_529 |11.55Mb
  - ğŸ‡ºğŸ‡¸US_533 |10.20Mb
  - ğŸ‡ºğŸ‡¸US_556 |30.02Mb
  - ğŸ‡ºğŸ‡¸US_552 |15.61Mb
  - ğŸ‡ºğŸ‡¸US_549 |31.44Mb
  - ğŸ‡ºğŸ‡¸US_551 |14.10Mb
  - ğŸ‡ºğŸ‡¸US_564 |24.08Mb
  - ğŸ‡ºğŸ‡¸US_581 |79.55Mb
  url: https://www.google.com/generate_204
- name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©
  type: url-test
  proxies:
  - ğŸ‡§ğŸ‡¬BG_369 |42.29Mb
  - ğŸ‡«ğŸ‡·FR_396 |53.96Mb
  - ğŸ‡«ğŸ‡·FR_395 |65.33Mb
  - ğŸ‡¦ğŸ‡·AR_361 |26.43Mb
  - ğŸ‡«ğŸ‡·FR_400 |52.51Mb
  - Pool_ğŸ‡­ğŸ‡°HK_405 |632.00Mb
  - ğŸ‡®ğŸ‡³IN_413 |21.20Mb
  - ğŸ‡®ğŸ‡³IN_411 |17.41Mb
  - ğŸ‡®ğŸ‡³IN_412 |11.66Mb
  - Relay_ğŸ‡®ğŸ‡·IR-ğŸ‡³ğŸ‡±NL_425 |42.47Mb
  - ğŸ‡®ğŸ‡³IN_410 |32.10Mb
  - Relay_ğŸ‡®ğŸ‡·IR-ğŸ‡³ğŸ‡±NL_426 |46.18Mb
  - Relay_ğŸ‡®ğŸ‡·IR-ğŸ‡³ğŸ‡±NL_427 |44.38Mb
  - ğŸ‡®ğŸ‡·IR_429 |29.73Mb
  - Relay_ğŸ‡®ğŸ‡·IR-ğŸ‡³ğŸ‡±NL_428 |45.81Mb
  - Relay_ğŸ‡®ğŸ‡·IR-ğŸ‡³ğŸ‡±NL_430 |39.18Mb
  - Relay_ğŸ‡®ğŸ‡·IR-ğŸ‡³ğŸ‡±NL_431 |36.81Mb
  - ğŸ‡±ğŸ‡¹LT_439 |32.69Mb
  - ğŸ‡±ğŸ‡¹LT_441 |11.95Mb
  - ğŸ‡±ğŸ‡¹LT_442 |24.89Mb
  - ğŸ‡±ğŸ‡¹LT_443 |23.44Mb
  - ğŸ‡¯ğŸ‡µJP_432 |50.29Mb
  - ğŸ‡¯ğŸ‡µJP_434 |19.61Mb
  - ğŸ‡±ğŸ‡¹LT_444 |23.29Mb
  - ğŸ‡±ğŸ‡¹LT_446 |23.79Mb
  - ğŸ‡±ğŸ‡¹LT_449 |26.02Mb
  - ğŸ‡³ğŸ‡±NL_453 |38.32Mb
  - ğŸ‡³ğŸ‡±NL_455 |16.85Mb
  - ğŸ‡³ğŸ‡±NL_456 |22.45Mb
  - ğŸ‡³ğŸ‡±NL_454 |42.09Mb
  - ğŸ‡³ğŸ‡±NL_457 |27.64Mb
  - ğŸ‡³ğŸ‡±NL_460 |32.81Mb
  - ğŸ‡³ğŸ‡±NL_458 |42.61Mb
  - ğŸ‡µğŸ‡±PL_462 |54.42Mb
  - ğŸ‡ºğŸ‡¸US_509 |27.43Mb
  - ğŸ‡ºğŸ‡¸US_515 |24.53Mb
  - ğŸ‡µğŸ‡±PL_467 |37.08Mb
  - ğŸ‡ºğŸ‡¸US_517 |26.56Mb
  - ğŸ‡ºğŸ‡¸US_505 |25.99Mb
  - ğŸ‡ºğŸ‡¸US_522 |24.98Mb
  - ğŸ‡ºğŸ‡¸US_524 |21.67Mb
  - disney_US |55.67Mb
  - ğŸ‡µğŸ‡±PL_468 |21.12Mb
  - ğŸ‡ºğŸ‡¸US_537 |32.55Mb
  - ğŸ‡ºğŸ‡¸US_540 |12.73Mb
  - ğŸ‡ºğŸ‡¸US_507 |31.36Mb
  - ğŸ‡ºğŸ‡¸US_543 |44.96Mb
  - ğŸ‡ºğŸ‡¸US_542 |35.55Mb
  - ğŸ‡ºğŸ‡¸US_547 |57.46Mb
  - ğŸ‡¹ğŸ‡·TR_486 |15.91Mb
  - ğŸ‡ºğŸ‡¸US_528 |38.77Mb
  - ğŸ‡µğŸ‡¾PY_474 |31.28Mb
  - ğŸ‡ºğŸ‡¸US_529 |11.55Mb
  - ğŸ‡ºğŸ‡¸US_533 |10.20Mb
  - ğŸ‡ºğŸ‡¸US_556 |30.02Mb
  - ğŸ‡ºğŸ‡¸US_552 |15.61Mb
  - ğŸ‡ºğŸ‡¸US_549 |31.44Mb
  - ğŸ‡ºğŸ‡¸US_551 |14.10Mb
  - ğŸ‡ºğŸ‡¸US_564 |24.08Mb
  - ğŸ‡ºğŸ‡¸US_581 |79.55Mb
  url: https://www.google.com/generate_204
  interval: 300
  tolerance: 50
  max-history: 10
rules:
- GEOIP,CN,DIRECT
- MATCH,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
